### ISSUE TITLE
Can not unlock/change pin using the SO pin

### ISSUE THREAD

**Issue by java-artisan** [OpenSC/OpenSC#1002]
xubuntu 16.10, amd64
OpenSC 0.16.0 [gcc  6.2.0 20160914]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

### Expected behaviour

The user pin code gets changed.

### Actual behaviour

Error : The message suggests it tried to change the SO pin.

### Steps to reproduce

1. pkcs11-tool --login --login-type so --so-pin ********************** --change-pin --new-pin ******
2. 
3. 

### Logs

Using slot 0 with a present token (0x0)
error: PKCS11 function C_SetPIN failed: rv = CKR_PIN_LEN_RANGE (0xa2)

Aborting.

**Comment by frankmorgner** [comment]
please use `pkcs15-tool --change-pin -vvv` and paste the output here (note that you may remove your pin from the log)

**Comment by java-artisan** [comment]
https://gist.github.com/java-artisan/40fca4bf723b5b09e72b6f075fac8205

**Comment by frankmorgner** [comment]
Your PIN is blocked, you need to unblock it first. Try `pkcs15-tool --unblock-pin`
