### ISSUE TITLE
setcos cards max send size issue

### ISSUE THREAD

**Issue by alxnik** [OpenSC/OpenSC#1009]
The max send size for setcos cards is set to 65k by setting SC_CARD_CAP_APDU_EXT in card capabilities (src/libopensc/card-setcos.c). When pkcs15-init tries to send to the card a 256 buffer, it fails (logs below). If SC_CARD_CAP_APDU_EXT is unset, everything works ok.

This seems to be a regression because OpenSC 0.14 is working ok.

Reader used: SCM Microsystems Inc. SCR 335 [CCID Interface] (000000CE) 00 00

### Expected behaviour

"pkcs15-init --store-pin --auth-id 01" should work ok with setcos cards

### Actual behaviour

"pkcs15-init --store-pin --auth-id 01"
fails with "Failed to store PIN: Internal error"

### Steps to reproduce

1.  pkcs15-init -E
2. pkcs15-init -C
3. pkcs15-init --store-pin --auth-id 01

### Logs
0x7f0daddcc700 07:40:56.456 [pkcs15-init] apdu.c:376:sc_single_transmit: CLA:0, INS:D6, P1:0, P2:0, data(256) 0x5634bcc01fc0
0x7f0daddcc700 07:40:56.456 [pkcs15-init] apdu.c:129:sc_apdu2bytes: invalid Lc length for CASE 3 extended APDU (need ENVELOPE)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] apdu.c:384:sc_single_transmit: unable to transmit APDU: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] apdu.c:520:sc_transmit: transmit APDU failed: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] card.c:434:sc_unlock: called
0x7f0daddcc700 07:40:56.456 [pkcs15-init] iso7816.c:321:iso7816_update_binary: APDU transmit failed: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] card.c:662:sc_update_binary: returning with: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] pkcs15-lib.c:3672:sc_pkcs15init_update_file: returning with: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] pkcs15-lib.c:2821:sc_pkcs15init_update_any_df: Failed to encode or update xDF: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] pkcs15-lib.c:2886:sc_pkcs15init_add_object: returning with: -1400 (Internal error)
0x7f0daddcc700 07:40:56.456 [pkcs15-init] pkcs15-lib.c:1025:sc_pkcs15init_store_pin: Failed to add PIN object: -1400 (Internal error)

**Comment by frankmorgner** [comment]
please check if https://github.com/OpenSC/OpenSC/pull/1010 fixes your problem

**Comment by alxnik** [comment]
Yep, that did the trick. Thanks for the quick reply
