### ISSUE TITLE
Support of new GOST Algoritms

### ISSUE THREAD

**Issue by alexyack** [OpenSC/OpenSC#1015]
### Expected behaviour

Please add support of modern GOST algorithms.

### Actual behaviour

Now pkcs11-tool report a list of unknown algorithms:

> C:\Temp>pkcs11-tool --module rtpkcs11ecp.dll -T -M
> Available slots:
> Slot 0 (0x0): Aktiv Rutoken ECP 0
>   token label        : Token
>   token manufacturer : Aktiv Co.
>   token model        : Rutoken ECP
>   token flags        : rng, login required, PIN initialized, token initialized, user PIN count low, user PIN to be changed, SO PIN to be changed, other flags=0x100000
>   hardware version   : 20.5
>   firmware version   : 23.2
>   serial num         : 88888888
> Using slot 0 with a present token (0x0)
> Supported mechanisms:
>   RSA-PKCS-KEY-PAIR-GEN, keySize={512,2048}, hw, generate_key_pair
>   RSA-PKCS, keySize={512,2048}, hw, encrypt, decrypt, sign, verify
>   RSA-PKCS-OAEP, keySize={512,2048}, hw, encrypt, decrypt
>   MD5, digest
>   SHA-1, digest
>   GOSTR3410-KEY-PAIR-GEN, hw, generate_key_pair
>   GOSTR3410, hw, sign, verify
>   **mechtype-0x1204, hw, derive
>   mechtype-0xD4321005, hw, generate_key_pair
>   mechtype-0xD4321006, hw, sign, verify
>   mechtype-0xD4321007, hw, derive**
>   GOSTR3411, hw, digest
>   **mechtype-0xD4321012, hw, digest
>   mechtype-0xD4321013, hw, digest**
>   GOSTR3410-WITH-GOSTR3411, hw, digest, sign
>   **mechtype-0xD4321008, hw, digest, sign
>   mechtype-0xD4321009, hw, digest, sign
>   mechtype-0x1224, hw, wrap, unwrap
>   mechtype-0x1221, hw, encrypt, decrypt
>   mechtype-0x1222, hw, encrypt, decrypt
>   mechtype-0x1220, hw, generate
>   mechtype-0x1223, hw, sign, verify**
> 

PKCS#11 module and SDK with new definitions can be found [here](https://www.rutoken.ru/support/download/get/sdk.html)
File [rtpkcs11t.h.txt](https://github.com/OpenSC/OpenSC/files/889905/rtpkcs11t.h.txt) contains required definitions.

**Comment by frankmorgner** [comment]
You're welcome to add support of new mechanisms of any sort...
