### ISSUE TITLE
Unsupported card (Oberthus ID-One Cosmo V7)

### ISSUE THREAD

**Issue by mariusz-saldak** [OpenSC/OpenSC#1016]
### Expected behaviour
Reading tokens from the card (Oberthus ID-One Cosmo V7).
MacOS Sierra 10.12
OpenSC 0.16.0 [gcc  4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]

### Actual behaviour
Message "Unsupported card" from "opensc-tool -an"

> Using reader with a card: VASCO DIGIPASS 870
Unsupported card

### Steps to reproduce

1. Connect Vasco Digipass 870 with card Oberthus ID-One Cosmo to macbook with mac osx 10.12
2. Run command "opensc-tool -an"

### Logs

> Using reader with a card: VASCO DIGIPASS 870
Connecting to card in reader VASCO DIGIPASS 870...
Using card driver Default driver for unknown cards.
Card name: Unsupported card

**Comment by frankmorgner** [comment]
If you're planning to make a contribution to the project, we'd love to add a new card to OpenSC. We would be happy to get you going and to comment on your code. However, please have in mind that in lack of hardware, documentation and manpower, we can't do this on our own.

**Comment by dengert** [comment]
Also keep in mind, that a card may be used by multiple applets, such as PIV, OpenPGP, EiD  by organizations such as governments. So its more then the card "Oberthus ID-One Cosmo V7" that needs to be supported.

**Comment by dengert** [comment]
https://smartcard-atr.appspot.com/parse?ATR=3bdb960080b1fe451f83564453493701110000000175
show your card is unknown, with the historical bytes  being: 56 44 53 49 37 01 11 00 00 00 01
starting with VDSI7 which might be a clue to what application is on the card.
