### ISSUE TITLE
openpgp-tool - 2048 bit key generation does not work on Windows 8.1 (Invalid ASN.1 object)

### ISSUE THREAD

**Issue by szszszsz** [OpenSC/OpenSC#1024]
### Expected behaviour

RSA key should be generated and saved on Nitrokey Pro device with `openpgp-tool` command.

### Actual behaviour

It looks like device is generating the key but final result is not saved to the device and a fingerprint consisting of only zeroes is shown to the user. When checked with `gpg2 --card-status` there are no new keys.
Size `1024` works but both `2048` and `4096` are not. Log shows (from `pro0.7-keygen-verbose-windows8.1-opensc0.16.txt`):
```
2017-04-13 17:02:20.073 [openpgp-tool] card-openpgp.c:2059:pgp_parse_and_set_pubkey_output: Unexpected end of contents.:
 -1401 (Invalid ASN.1 object)
```

### Other
It works on:
- Windows 8.1 with 0.15 
- Ubuntu 16.10 with OpenSC 0.16. 

Logs attached.

#### Card details
```
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Nitrokey Nitrokey Pro 0
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -a
Using reader with a card: Nitrokey Nitrokey Pro 0
3b:da:18:ff:81:b1:fe:75:1f:03:00:31:c5:73:c0:01:40:00:90:00:0c
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -n
Using reader with a card: Nitrokey Nitrokey Pro 0
CryptoStick v1.2 (OpenPGP v2.0)
```
#### Environment:
OS: tested and taken logs on Windows 8.1 x64, reported also on Windows 7 x32
Nitrokey Pro v0.7 (tested), v0.8 (reported too)
OpenSC versions tested (all x64): 
1. official 0.16  
2. latest master (1ca09b8f105d9e9ef6c237c924245ceec5d9c4c7, [build](https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.16.0.1209) )
3. 0.16 with disabled locking https://github.com/OpenSC/OpenSC/pull/868
4. 0.15 (it is not reproducing here)

After each installation a reboot was made to make sure proper libraries are used.

#### Steps:
0. Clear card with `./openpgp-tool.exe --erase`
1. Run `./openpgp-tool.exe --verify CHV3 --pin 12345678 --gen-key 1 --key-len 2048` or
`./openpgp-tool.exe --verify CHV3 --pin 12345678 --gen-key 1 --key-len 4096`
2. Check fingerprint in command results - it should be a non-zero value like:
```
Using reader with a card: Nitrokey Nitrokey Pro 0
Fingerprint:
C861E7B5EF26B9AF4601C1111CB1C450 C6F64CA9
````

#### Working
[pro0.7-keygen-ubuntu16.10-opensc0.16.txt](https://github.com/OpenSC/OpenSC/files/920548/pro0.7-keygen-ubuntu-opensc0.16.txt)
[pro0.7-keygen-verbose-ubuntu16.10-opensc0.16.txt](https://github.com/OpenSC/OpenSC/files/920550/pro0.7-keygen-verbose-ubuntu16.10-opensc0.16.txt)
[pro0.7-keygen-verbose-windows8.1-opensc0.15.txt](https://github.com/OpenSC/OpenSC/files/920551/pro0.7-keygen-verbose-windows8.1-opensc0.15.txt)
#### Issue reproduces
[pro0.7-keygen-verbose-windows8.1-opensc0.16.txt](https://github.com/OpenSC/OpenSC/files/920554/pro0.7-keygen-verbose-windows8.1-opensc0.16.txt)

**Comment by frankmorgner** [comment]
This token is also subject to https://github.com/OpenSC/OpenSC/issues/1011. @hongquan do you think this should work with `openpgp-tool`?

**Comment by hongquan** [comment]
@frankmorgner Yes, it should work with `openpgp-tool`. I will try to test and fix with 4096 key size on Linux. But for Windows, hmmm, it is difficult to me, because I have no Windows machine (virtual machine not work) and I used to fail to build OpenSC for Windows.

**Comment by frankmorgner** [comment]
@hongquan Our AppVeyor CI integration provides Windows Installers: In https://ci.appveyor.com/project/LudovicRousseau/OpenSC click on a specific build and checkout the *Artifacts*.

**Comment by szszszsz** [comment]
@hongquan This is already tested on Ubuntu 16.10 and it worked. I had problems setting it up on Windows too. Let me know if you will succeed with that.
@frankmorgner Appveyor builds are very handy indeed (I have used it already once), however it takes its time. Do you have some working setup guide for Windows 8.1? I have used description from [Wiki](https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer#build-instructions-windows), but it seems not to be updated recently or incomplete. I tried to mimic running Appveyor setup scripts locally too, but I have encountered error during the compilation with one of the OS headers. I will add the error message in a second in hope someone has seen fixed that.

**Comment by hongquan** [comment]
Hi. I confirm that `opengpg-tool` can generate 4096-bit key with `openpgp-tool`.

```
$ pkcs15-tool -k
Using reader with a card: Nitrokey Nitrokey Pro (00003A630000000000000000) 00 00
Private RSA Key [Signature key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x20C], sign, signRecover, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 4096
	Key ref        : 0 (0x0)
	Native         : yes
	Auth ID        : 01
	ID             : 01
	MD:guid        : 9cb8d513-372a-e0f8-8916-07812208e323
```

**Comment by hongquan** [comment]
Hi @szszszsz Can you test with this Windows build https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.16.0.1223/job/9ud9dhq21w5wxawa/artifacts ?
It contains the latest source of OpenSC.

**Comment by szszszsz** [comment]
@hongquan Sure! I will check it in a minute and will edit the post.

**Comment by szszszsz** [comment]
@hongquan It works now on my machine! Both test commands have returned non-zero fingerprint.
I have already tested the latest master back then (on the issue registration day, build .1209), so I have not expected this. Just in case this is not a side-effect of my previous installations or development setup for OpenSC I would like to ask someone to confirm this too. I will install development build .1209 for test once again (it was failing back then) and will check one more time suggested by you (and now working) build .1223.

**Comment by szszszsz** [comment]
Build .1209 is not working as expected - I can assume then this was fixed by recent commits. I guess this could be closed now.
