### ISSUE TITLE
DNIe logout incorrectly closes the secure channel

### ISSUE THREAD

**Issue by rickyepoderi** [OpenSC/OpenSC#1036]
Hi,

I did too many changes that  creating a regression was easy. Testing the card @miguel-cv told me that _openconnect_ doesn't work for him in the last version. Looking to the logs the problem happens when the _logout_ of the card is called. The DNIe logout method just mark the secure channel as OFF (but doing nothing) and, since the _sc_reset_ was removed, the card maintains the channel created, so the next login fails. I have checked the official implementation and the logout does nothing (so there is no real logout, the channel remains open and marked as open, in the next login the channel is open again through the previous channel).

My tests didn't show the problem because each test always calls the c_finalize and somehow it clears everything. The problem is triggered if you perform two logins without finalizing. I will need to add another test for this.

So I have to fix this new issue and I see two solutions: 

* Logout doing the same as the official implementation (nothing).
* Provoke an error that really closes the channel (exactly what happens now but controlled). For example I've seen that card-npa implements this idea.

@frankmorgner What do you think is the best way to go? I think that the second is more secure but I'm not sure.

Thanks!

**Comment by rickyepoderi** [comment]
This seems to work as an example for the SM error idea:

```C
        /* mark the channel as closed */
        result = cwa_create_secure_channel(card,
                GET_DNIE_PRIV_DATA(card)->cwa_provider, CWA_SM_OFF);
        LOG_TEST_RET(card->ctx, result, "Cannot close the secure channel");
        /* request the Master File to provoke an SM error and close the channel */
        result = dnie_compose_and_send_apdu(card, (const u8 *) DNIE_MF_NAME,
                sizeof(DNIE_MF_NAME) - 1, 4, &file);
        if (result == SC_ERROR_SM)
                result = SC_SUCCESS;
```

**Comment by frankmorgner** [comment]
The German ID card (`card-npa`) is binding the authentication status to a SM channel, as far as I know it doesn't have an explicit logout command. To deauthenticate means to terminate the SM channel. The SM channel is terminated if...
- the card receives some command without SM or
- the card recognizes an SM error

The SM channel can be established between
- OpenSC and card
- Reader and card

So what you can see in https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-npa.c#L679 is the following:
1. Disable SM in OpenSC if possible (`sc_sm_stop`)
2. if SM between card and Reader, then provoke an SM error by sending a badly encrypted APDU
3. Select MF without SM

If you have only OpenSC opening the SM channel, then calling `sc_sm_stop` would actually be enough, because the next command will always be without SM. If I read your explanation correctly, then this is what OpenSC is currently doing with DNIe (and what the *official* implementation is doing). It is unclear for me, why logging in in this situation fails, because establishing a new SM channel and validating the PIN should work now. I suspect there could be some other problem with the dnie driver that keeps a wrong state about the login status...

**Comment by rickyepoderi** [comment]
@frankmonger, In DNIe there's no logout command either (at least no one listed in the official documentation pdf), for what I see it's very similar to what you describe in the card-npa (but only the reader part). When a user is logged in the secure channel is established, and logout is equal to terminate the channel.

In the current implementation the login fails because the channel is terminated at software level (sm_mode is set to SM_MODE_NONE) but the card still thinks it's in place. So when you send the first plain apdu, the card was expecting an encrypted one and gives a SM error (0x69 0x87). The channel is terminated because of the error.

The official PKCS#11 library does nothing (nothing at all) for the logout (the channel is still maintained, the logout is just done at PKCS#11 level). When a new login is requested the new channel is started over the previous one (the apdus to start the channel are encrypted using the previous channel, it's weird, but it's like this).

In the code I presented before, what I do is sent a select_file operation but not using SM (plain or unencrypted) so the error is provoked intentionally to terminate the channel. Similar to what you are doing in card-npa in point (2) of your explanation. I force an error sending a plain apdu and the channel is terminated.

Both solutions seem to work for me (not very tested, but at least you can login again with both). I'm just asking which option you think is better, doing nothing like the official implementation or terminating the channel like in card-npa... IMHO I think the second option is more secure but I have zero experience.

Thanks!

**Comment by rickyepoderi** [comment]
I've taken a look to the card-npa code again and it's different. Now I see it. When you say between reader and card you are talking about some standard. In DNIe it's not the case. Sorry for that (I have just learned that PACE is a kind of secure communication for contactless readers).

But the summary is the same, the secure channel should be terminated to perform a real logout. And I just know to do it forcing an error. The other option is not terminating the channel. Previously it worked because there was a _sc_reset_ in the card before creating the channel.

Sorry again for being annoying but I prefer to ask before than doing things wrong.

**Comment by frankmorgner** [comment]
No problem. I think it's best to follow your idea of [disabling SM and then selecting MF (ignoring `0x6987`)](https://github.com/OpenSC/OpenSC/issues/1036#issuecomment-296446455)

**Comment by rickyepoderi** [comment]
@miguel-cv I have done the change, now the channel is closed forcing a plain apdu (select MF). Please test this branch with openconnect:

https://github.com/rickyepoderi/OpenSC/tree/issue1036

And, if you can, try with v2.0 my dnie-pkcs11-tester (I have changed it again, now it's test oriented). Just run the "-a" option with a DNIe 2.0. I'm no going to have access to a 2.0 in the short time. No hurry, test when you have time.

**Comment by miguel-cv** [comment]
Ok, will test next monday....¡thanks!

**Comment by miguel-cv** [comment]
Tested, works well. I'll try to find my 2.0 card...XD

**Comment by rickyepoderi** [comment]
Ok Miguel. I'm going to prepare the pull now. Thanks!
