### ISSUE TITLE
MacOS: cannot use /Library/OpenSC/lib/opensc-pkcs11.so - agent refused operation

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1040]
### Expected behaviour

Using MacOS Sierra latest version, with built in ssh, "ssh-add -s /Library/OpenSC/lib/opensc-pkcs11.so" works properly.

### Actual behaviour

We fail with the error "agent refused operation".

Little-Net:~ minfrin$ ssh-add -s /Library/OpenSC/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11: 
Could not add card "/Library/OpenSC/lib/opensc-pkcs11.so": agent refused operation

### Steps to reproduce

1. MacOS Sierra latest version 10.12.4
2. Run "ssh-add -s /Library/OpenSC/lib/opensc-pkcs11.so"

This bug is similar to https://github.com/OpenSC/OpenSC/issues/1008, but that bug describes the pkcs11 driver in /usr/local/lib, in this case we have the driver in /Library/OpenSC/lib/.

It seems the /Library/OpenSC/lib/ directory is not "blessed".

**Comment by frankmorgner** [comment]
#1008 describes that the symbolic link is mapped to /Library/OpenSC/lib. Please make a pull request as described in  #1008 to solve this issue

**Comment by minfrin** [comment]
I don't follow at all - what symbolic link are we talking about?

The bottom line is opensc used to work out of the box on MacOS Sierra, it now doesn't.

Please fix this - I cannot give my team instructions to refer to some bug report on github in order that they can log into our systems with ssh.

If I knew what was wrong I'd happily contribute a PR, but alas I do not. All I can confirm is out the box, opensc no longer works on MacOS Sierra.

**Comment by frankmorgner** [comment]
Simply try the suggested fix: https://github.com/OpenSC/OpenSC/pull/1041

**Comment by JustusW** [comment]
2022, I get a password prompt, no matter what I do, same error, what dis?
