### ISSUE TITLE
opensc-tool --send-apdu unexpected behaviour

### ISSUE THREAD

**Issue by user8547** [OpenSC/OpenSC#1044]
According to the man page the --send-apdu flag of opensc-tool can be used to send arbitrary APDU in format AA:BB:CC:DD:EE:FF... to card.

The problem is that opensc-tool modifies APDU being sent and replaces the status word returned.

For example, sending this APDU ``
$ opensc-tool -s 00:00:00:00:01:05:00
``
we see from APDU trace (``pcscd -f -a``) that actually APDU ``00:00:00:00:01:05`` is sent to the card (Le from case 4 APDU is removed).

However, when sending this APDU ``$ opensc-tool -s 00:00:00:00:01:05`` the APDU is sent without modification, but SW response reported by opensc-tool is ``(SW1=0x90, SW2=0x00)``, while actually the card returns SW 0x61XX asking to issue GET RESPONSE to obtain response data which is not done by opensc-tool in this case 3 APDU.

How it should be: opensc-tool should send requested APDU without modification and transparently issue GET RESPONSE whenever 0x61XX SW is returned by the card.

Furthermore, we can see in the APDU trace that opensc-tool issues several unrequested APDUs before the requested APDU is sent to card:
```
08034970 APDU: 00 A4 04 00 0F D2 33 00 00 00 45 73 74 45 49 44 20 76 33 35 
00039562 SW: 6D 00 
00001195 APDU: 00 CA DF 30 05 
00012482 SW: 6D 00 
00008406 APDU: 00 A4 04 00 06 A0 00 00 00 01 01 
00024937 SW: 6D 00 
00003125 APDU: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 
00028572 SW: 6D 00 
00006325 APDU: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 
00028606 SW: 6D 00 
00006977 APDU: 00 A4 04 00 0C F2 76 A2 88 BC FB A6 9D 34 F3 10 01 
00032206 SW: 6D 00 
```
--send-apdu should not send these application selection APDUs.

**Comment by dengert** [comment]
The other APDUs sent before the -s APDU is sent are done to select a card driver. You can force a card driver by using the -c option.

Several -v options will show more of what OpenSC is doing. Or use the debugging options in opensc.conf

Depending on the protocol used by the reader and card, Le may not be sent.
 
opensc-tool.c uses the sc_bytes_to_apdu and  sc_transmit_apdu routine and opensc-tool always pass a response buffer. sc_transmit_apdu will look at the protocols and data and use GET_RESPONSE if needed in a loop.
  
What version of OpenSC and PCSC are you using,
What OS?
What type of card? 

and APDU of all zeros looks strange. ISO 7816-4 does not define '00' as an INS. Could the reader be interpreting the 00:00:00:00?

**Comment by frankmorgner** [comment]
The idea behind the tools is to allow low level access to cards that are supported by OpenSC. Since your card does not seem to be supported by OpenSC and it does not appear to be compliant to ISO 7816-4 (e.g. the internal default card driver), you're better off using something else than OpenSC.

There are some free tools available, please use Google.

**Comment by frankmorgner** [comment]
Please make a pull request if you think the man page or the help is misleading.

**Comment by dengert** [comment]
I agree that there is an issue.  opensc-tool only allocates a SC_MAX_APDU_BUFFER_SIZE (261)  rbuf in send_apdu  as the receive buffer. There is no way to specify how large the buffer should be as only a single byte at the end of the input hex string is used to define both Le and the receive buffer size. It needs to have a way to specify Extended  APDUs as well as short APDUs and let the sc_transmit_apdu use GET RESPONSE to read more data. 

The card-piv.c has a similar -s option, but it has a receive buffer of size 8192, and thus sc_transmit_apdu will use GET RESPONSE to read upto the 8192 bytes. (the size was arbitrary, but should support upto  65K+2  the max for any extended APDU too. 

A simple fix is to change the size of  rbuf  in send_apdu.  

It also looks like there is  problem with buf  (the send buffer)  being to small, as sc_bytes2apdu  tries to support extended APDU for send, but does not allow for the user to provide for input larger then SC_MAX_APDU_BUFFER_SIZE.

And the piv-tool.c works fin with OpenSSL-1.0.2 but has a problem with initialization of OpenSSL  in OpenSSL-1.1

I can submit a fix for these problems in the next few days.

**Comment by frankmorgner** [comment]
Agreed, `buf` and  `rbuf` could be bigger.

**Comment by dengert** [comment]
@frankmorgner  
Would you accept 65K+2 (2 for status) as the rbuf?
Or allocate a 65K+2 if Le=0 which would allow for GET_RESPONSE

**Comment by user8547** [comment]
The man page could say that:

1. APDU specified will be modified before sent to card;
2. Some additional APDUs will be sent before it;
3. Return value displayed may not correspond to the actual return value received from card.

From the current man page one could assume that --send-apdu of opensc-tool is a good way how send raw APDU to card and check the response.

**Comment by frankmorgner** [comment]
@dengert normally I'd prefer dynamic memory allocation based on `le` and `sc_get_max_recv_size`. However, since we're only in `opensc-tool`, static memory allocation would be acceptable as well. Please don't introduce more parameters. No need to allocate two extra bytes; `reader-pcsc.c` does this already.

@user8547 
1. I suspect you're sending you connected to your card with T=0, which makes your APDU invalid and OpenSC is so kind to correct this for you. You could try forcing `t1` in `opensc.conf`.
2. additional APDUs are sent when connecting, this is part of the recognition process. As @dengert , you can avoid this by forcing a specific card driver (i.e. the ISO 7816 driver).
3. The return value should not have been modified.

Please send a log with debugging enabled if you need more help. I still think your problem is better solved with a different tool.

**Comment by user8547** [comment]
1. Yes, this is T=0 only card. However, OpenSC should not correct anything. Java smartcardio is not correcting anything and pyscard either. The card and reader in question actually respond differently based on whether Le is sent to PCSC.
2. Maybe ISO 7816 driver then should be set to be default.
3. As you see in the example above OpenSC reports SW 9000 where 61XX was returned.

Sure I can send raw APDUs using Java or Python, but using command line tool to send APDU in one-liner is neater.

**Comment by dengert** [comment]
@user8547 
(2.) No    ISO 7816 driver then should **not** be set to be default. Opensc-tool has  other parameters that depend on the card driver: --serial, --list-files, --list-algorithms.  If you don't like the driver, you can use the --card-driver option to set the one that comes closest to your card. 

(3.) The sc_send_apdu does more then just send the APDU. It adjusts for the protocol which is based on the card and reader as determined by the card driver.  It will do command chaining and will  call GET RESPONSE. if the card returns 90 00, it return 90 00. If the receive buffer is filled by the original APDU or by GET RESPONSE(s) it will also return 90 00.  i.e. it will return up to the number of bytes the caller requests or the card provides. 

One problem with the current -s parameter, it has no way to set the size of the  receive buffer. It defaults to  SC_MAX_APDU_BUFFER_SIZE which does not allow for the card returning large objects. It also looks like if command chaining is needed it is up to the caller to do it with multiple -s parameters. 

But the more I look at what you are trying to do does not depend on the SC_MAX_APDU_BUFFER_SIZE.

@user8547 You still did not say what version of OpenSC you are using or what reader or card. There have been changes in the apdu.c in the area of the GET RESPONSE loop. 

And as @frankmorgner points out if you don't like the way it does it there are other programs that can be used.
