### ISSUE TITLE
Crash in chromium using DNIe and boringssl

### ISSUE THREAD

**Issue by rickyepoderi** [OpenSC/OpenSC#1047]
Hi,

I'm filing this issue just to advise a weird problem I've been tracking the last days. You can just close it as soon as you read it, I just want it here to inform people.

It seems that google has been forking openssl, it is called [boringssl](https://www.chromium.org/Home/chromium-security/boringssl), and it is used inside chrome/chromium. When the opensc pkcs#11 library is installed in the chrome certificate store (_~/.pki/nssdb_) if the _boringssl.so_ is used dynamically in the system the drivers inside the pkcs#11 use the google implementation. I've just found one distro for the moment that works this way, fedora. In the case of DNIe the browser crashes (in the secure channel creation the _X509_verify_ function is used to verify some certs inside the card, I don't know why, one call crashes).

It seems that google recommends to link boringssl statically in the chromium binary, it's just thought to be private. This way everything works because openssl default system libs are loaded (this is done in the official chrome package for linux and in other distros like debian).

I have filed two bugs (fedora and google):

* https://bugzilla.redhat.com/show_bug.cgi?id=1448649
* https://bugs.chromium.org/p/boringssl/issues/detail?id=194

For the moment they are only driving me crazy. I think I did all I could. More drivers (the ones that use openssl) could be affected. So if you see something weird like this just remember this issue.

Thanks!

**Comment by dengert** [comment]
From the redhat bur responses it sounds like a linking problem. 

Since opensc-pklcs11.so is meant to be a "module" and not just a library, are we using the libtool features to create a module and is it passing the correct options to ld to do this? 

Many years ago I ran into a similar problem on Solaris wiith Kerberos and PAM and IIRC a modules needed to be self contained i.e. no unresolved external references.

It could be the opensc build environment for Chromium needs some work. 

It could also be some issue with the openssl/boringssl version numbers. The OpenSC sc-ossl-compat.h  might be having a problem with version numbers, or the build is using the wrong header files.

**Comment by rickyepoderi** [comment]
The main reason is that opensc-pkcs11.so depends on libopensc.so and in turn on libcrypto.so. And chromium has already loaded another library libboringssl.so that has the same symbol _X509_verify_ exposed, so the pkcs11 uses that instead of loading the one in libcrypto.so. I can reproduce the same crash using LD_PRELOAD.

```
$ LD_PRELOAD=/usr/lib64/chromium-browser/libboringssl.so pkcs11-tool -I -l
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.16)
Using slot 0 with a present token (0x0)
Logging in to "PIN1 (DNI electrónico)".
Please enter User PIN: 
Segmentation fault (core dumped)
```

For what I understand reading the bug in google the boringssl.so should be linked statically, in an end-user distribution should be like this. But you know, crashing is not the best argument to say I'm doing the things right. And yes, the easiest way of fixing the issue is that fedora would change the distribution of chromium and the boringssl.so library would dissapear inside the binary. But I'm not going to waste more time on this, I think that I've done everything I could.

**Comment by dengert** [comment]
I gather that your LD_PRELOAD example is an way to force the bug as found in the browser loading opensc-pkcs11.so. 

My argument is that opensc-pkcs11.so should be treated as a module and not just a shared library. I contend that doing this would avoid the situation. 
And that to do this the libtool needs to add for a module -Bsymbolic  if using gnu ld or similar option for other loaders. 
For example thunderbird will add -Bsymbolic when building components. In 2003, I was doing some thing like this for PAM modules on Solaris, and HPUX. I din't have access to the details of how I did it. 


libtool has a place to add these, but is not normally being set:

# Commands used to build a loadable module if different from building
# a shared archive 
module_cmds=""
module_expsym_cmds=""

If you are willing, can you try adding -Bsymbolic to the LD_FLAGS  used to build opensc-pkcs11.so
If that works we can look at what it takes to do this via libtool.

**Comment by dengert** [comment]
Or can you try https://github.com/dengert/OpenSC/tree/Bsymbolic

do the make with OPENSC_MODULE_LDFLAGS="-Wl,-Bsymbolic" 

If this works we can look at a more permanent solution.

**Comment by rickyepoderi** [comment]
Hi Doug,

I did some tests before on my own and I couldn't make it work. I have compiled everything with "-Wl,-Bsymbolic" and nothing works. First I try just putting the flag to opensc lib:

```
$ readelf -a /home/rmartinc/apps/opensc/lib/libopensc.so.4 | grep SYMBOLIC
 0x0000000000000010 (SYMBOLIC)           0x0
$ readelf -a /home/rmartinc/apps/opensc/lib/opensc-pkcs11.so | grep SYMBOLIC
 0x0000000000000010 (SYMBOLIC)           0x0

```
Then to the libcryto too:

```
$ readelf -a /home/rmartinc/apps/libressl-2.5.4/lib/libcrypto.so | grep SYMBOLIC
 0x0000000000000010 (SYMBOLIC)           0x0
```

And no results, it keeps crashing and using the LD_PRELOAD.

```
$ ldd pkcs11-tool 
	linux-vdso.so.1 (0x00007ffe0232a000)
	libopensc.so.4 => /home/rmartinc/apps/opensc/lib/libopensc.so.4 (0x00007fc442819000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc4425e5000)
	libcrypto.so.41 => /home/rmartinc/apps/libressl-2.5.4/lib/libcrypto.so.41 (0x00007fc442226000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc44200b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc441e05000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc441be7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc441821000)
	/lib64/ld-linux-x86-64.so.2 (0x000056236839e000)
$ LD_PRELOAD=/usr/lib64/chromium-browser/libboringssl.so ./pkcs11-tool -l -I
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.16)
Using slot 0 with a present token (0x0)
Logging in to "PIN1 (DNI electrónico)".
Please enter User PIN: 
Segmentation fault (core dumped)
```

If you want I can try your branch but I think I did the same things (adding the flag directly to resulting Makefiles). At least the libraries show the SYMBOLIC that was not there before. And same result. I have wasted a lot of time with this issue, I don't know why google forks openssl if they are going to implement it partially, at least they can change the method names (or something similar) to avoid these problems.

**Comment by dengert** [comment]
Does it work with the browser? The dynamic loader may use LD_PRELOAD for every module that get loaded. The point of the -Bsymbolic is to avoid picking up functions from the caller, and  readelf show it is there. So not clear why it is picking up boringssl.so. I am surprised what Google did too. 

I had installed a chromium dev  (Ubuntu) virtual machine last year but never did anything with it and it is out of date. I can install a newer version. What do I need to do to reproduce your test of the failing browser?

**Comment by frankmorgner** [comment]
I think a better approach would be to link statically when creating the pkcs11 library. That's already what we're doing when compiling for Windows.

**Comment by frankmorgner** [comment]
BTW, I recently discovered that Windows has a cool feature of being able to load multiple versions of the a library at the same time. This is missing in Unix as far as I know and thus requires renaming the symbols at load time as you suggested, @dengert . I never managed to do this actually, which supports what other people are saying about it: It's not very practical. Hence, I think creating a standalone PKCS#11 library would be more favorable.

**Comment by rickyepoderi** [comment]
@dengert 
>Does it work with the browser? The dynamic loader may use LD_PRELOAD for every module that get loaded. The point of the -Bsymbolic is to avoid picking up functions from the caller, and readelf show it is there. So not clear why it is picking up boringssl.so. I am surprised what Google did too.

No, same crash in the browser.

>I had installed a chromium dev (Ubuntu) virtual machine last year but never did anything with it and it is out of date. I can install a newer version. What do I need to do to reproduce your test of the failing browser?

You need a distribution with the libboringssl.so, I only know Fedora for the moment. Common google download and other distros (debian for example) distribute it statically inside the binary so there is no problem. Besides what crashes and what works in libboringssl.so is not clear (in DNIe there are two _X509_verify_ and the first one crashes and the second one works). So it's very difficult to say something.

@frankmorgner 
>I think a better approach would be to link statically when creating the pkcs11 library. That's already what we're doing when compiling for Windows.

Think that you need to link statically the libcrypto, I don't think this is a good solution either. I have spent some time with this problem, and my conclusion is the distros should distribute chromium as recommended by google and the libboringssl.so should never be present. I just wanted that nobody will waste his/her time with the same issue again.

**Comment by dengert** [comment]
Here is another thought.   Is the problem caused by loading the libsmm-local.so ?  
Should it have -Bsymbolic? 

As you point out: "I just wanted that nobody will waste his/her time". Because this is fedora issue, I don't want to  setup another VM to try fedora.
