### ISSUE TITLE
SC-HSM: "An error occurred while retrieving a digital certificate from the  inserted smart card. An internal consistency check failed."

### ISSUE THREAD

**Issue by ldti** [OpenSC/OpenSC#1049]
### Expected behaviour

login or authentication using smartcard

### Actual behaviour

getting the error in the title in application log.
logon dialog shows incorrect username or password.

### Steps to reproduce

1. create logon smartcard template
2.  enroll to smartcard (will sometimes fail with a similar error about consistency
3. try to login or authenticate

### Logs

[opensc-debug.log.txt](https://github.com/OpenSC/OpenSC/files/1001336/opensc-debug.log.txt)

**Comment by frankmorgner** [comment]
You seem to be using @CardContact 's sc-hsm. Unfortunately, your log is too big for a quick review. I couldn't find something obvious. Maybe @CardContact has some better idea...

**Comment by CardContact** [comment]
I can't see anything suspicious in the log.

**Comment by frankmorgner** [comment]
can you debug the logon process to get a more detailed error message?

@ldti are you sure that your logon template is working?

**Comment by CardContact** [comment]
No additional feedback in 20 days. Closing now.
