### ISSUE TITLE
is the openSC supported by Gemalto

### ISSUE THREAD

**Issue by guesmihela** [OpenSC/OpenSC#1052]
### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

### Steps to reproduce

1. 
2. 
3. 

### Logs

Debug output is essential to identify the problem. You can enable debugging by
editing the file `opensc.conf`:
```
    # A debug level of 3 catches most problems
    # Some sensitive data may be logged, too, (e.g. PIN codes)
    debug = 3;

    # Where to write the debug output (default: `stdout`)
    #debug_file = opensc-debug.log
```

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs. Before pasting here, remove your sensitive data from your log (e.g. PIN
code or certificates).

```
Paste Log output with less than 10 lines here
```

**Comment by frankmorgner** [comment]
I don't understand; what is your question?

**Comment by guesmihela** [comment]
I am trying to install chrome token signing  extension in my browser Google chrome (Windows 64) and I install smart card reader gemalto  . but the extension doesn't work . I see in the code C++ of chrome token signing  ,  in the pkcs11PATH.cpp  ,   opensc-pkcs11.so and  opensc-pkcs11.dll .

**Comment by frankmorgner** [comment]
I'm sorry, I still don't get what you're after. If you're using chrome on Win64 you shouldn't see  opensc-pkcs11.so. To make chrome work on Windows install the win64 msi: https://github.com/OpenSC/OpenSC/releases/download/0.16.0/OpenSC-0.16.0-win64_vs12-Release.msi. Everything else should work out of the box.
