### ISSUE TITLE
Support for STARCOS v. 3.5 cards, e.g. DGN

### ISSUE THREAD

**Issue by djtm** [OpenSC/OpenSC#1054]
This is a feature request and to collect resources.

There is an open source implementation for these cards here:
https://github.com/CardContact/sc-hsm-embedded

**Comment by frankmorgner** [comment]
I'm unsure what you mean by "collecting ressources", but @CardContact also regularly contributes to OpenSC. Maybe you can contact them for contributing the missing pieces to OpenSC...

**Comment by CardContact** [comment]
What would be the benefit of doing that ?

Those cards a read/only cards and OpenSC wouldn't do anything more than what the sc-hsm-pkcs11 driver does (except maybe for minidriver support).

**Comment by djtm** [comment]
https://github.com/CardContact/sc-hsm-embedded/issues/16#issuecomment-305113030

**Comment by CardContact** [comment]
Minidriver support now available in [sc-hsm-embedded](/CardContact/sc-hsm-embedded) for those cards and no volunteer to do or sponsor the integration.

**Comment by frankmorgner** [comment]
@djtm could check if https://github.com/OpenSC/OpenSC/pull/1272 works for you?
