### ISSUE TITLE
0.17.0: Update NEWS file

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1062]
Draft below:
# New in 0.17.0
## Support for new Cards
* CAC (Common Access Card)
* GoID (SC-HSM with built-in PIN pad and fingerprint sensor)
* Coolkey
* JPKI (Japanese Individual Number Card)
* nPA (German ID card, eSign Application)
## General Improvements
* PKCS#15
    * Implemented file caching based on card's contact-less UID
    * Cache EF.ODF and EF.TokenInfo
    * File caching is done transparently when the user sets the config option.
* `opensc.conf`
    * Added `disable_popups` for disabling internal UI
    * All Windows specific reader configuration is handled by the pcsc driver (cardmod driver was removed)
* Build Environment
    * Allow setting `PKG_CONFIG_PATH` for macOS build
    * Added compatibility with Visual Studio 2015
    * Allow building against LibreSSL
    * Allow building against OpenSSL 1.1.0
    * Allow building against WiX 3.11
    * Allow building minidriver with MinGW
    * Include OpenPACE library by default
    * Removed `BUILD_ON`/`BUILD_FOR` variable
* Simplified installer on macOS and Windows
* Added support for PIN commands via PC/SC escape commands
* Added support for card reader access via CryptoTokenKit
* Added support for PIN entry on card for verification/unblock/change
* Recognize T=0 limitation of sending 255 bytes
* Force T=1 for contactless cards
* Allow setting driver via `OPENSC_DRIVER` environment variable
* Fixed many bugs
* Fixed many compiler warnings
* Fixed possible issues (memory corruptions, memory leaks, double free, ...)
* Internal refactoring and cleanup
## PKCS#11
* Move PIN type label front of description
* `C_GetTokenInfo` read the login status from the card if possible
* Don't use ':' in the token name (#849)
* Install `opensc-pkcs11.pc` for usage with `pkg-config`
* Don't shrink the number of slots (#629)
* Add session handle uniqueness check to PKCS#11 `C_OpenSession()`
* Activate functionality of `C_WaitForSlot()` for pcsc-lite >= 1.8.22
## Minidriver
* Support PIN unblocking in minidriver via PUK as response
* Added support for Session PIN
## Tokend
* Allow usage of readers PIN pad by entering an empty PIN
## OpenSC Tools
* Fixed Bash completion (#782)
* `opensc-tool`
    * Added `--reset` option
* `opensc-explorer`
    * Show tag 0x82 for unknown files
* `pkcs15-tool`
    * Fixed `--read-ssh-key` crash (#788)
    * Added `--clear-cache`
    * Fixed locking the card on Windows (#868)
    * Add `--list-info` option
    * Make `--list-...` messages consistent
    * Add `--short` option
    * `--read-data-object`: Do not print data to terminal when output file is given
    * Reword `--no-prompt` to `--use-pinpad`, old option still available as alias
    * Added `--test-session-pin` option
* `pkcs15-init`
    * Fix using PINPAD to verify PIN (#856)
    * Fixed locking the card on Windows (#868)
    * Added `--secret-key-algorithm` option
    * Print more detailed secret key information
* `pkcs11-tool`
    * Added `keygen` for secret key generation
    * Better handling of PIN (re-) validation
    * Fixed --id for `C_GenerateKey`, DES and DES3 keygen mechanism (#857)
    * Added `--derive-pass-der` option
    * Added `--generate-random` option
    * Add GOSTR3410 keypair generation
* `npa-tool` (new)
    * Allows read/write access to EAC tokens
    * Allows PIN management for EAC tokens
* `gids-tool`
    * Fixed entering SN via command line
* `sc-hsm-tool`
    * Added `--print-dkek-share` (hidden from the user)
    * Fixed locking the card on Windows (#868)
## CardOS
* Better support for CardOS 5.3
## DNIe
* Fixed interaction with DNIe UI
* Added support for DNIe 3.0
## ePass2003
* Add new ATR for entersafe PKI card
* Solved Incorrect PIN raise wrong CKR error
## GemsafeV1
* PTeid: add objects (SOD, TRACe, CA) and fix flags
* PTeid: Support PIN max tries and tries left report
* PTeid: Properly report cards with 2048b keys.
## MyEID
* Fix to ECDH implementation (#756)
* Added support for symmetric keys
## OpenPGP
* Improve handling of OpenPGP card PIN change and unblock commands
## PIV
* Some workarounds for PIV-alike cards (e.g. Yubikey)
* Change driver's short name to 'PIV-II'
* Use certificate's keyUsage to set PKCS#11 key attributes
## SC-HSM
* Use PKCS#15 file cache
* Prevent unnecessary applet selection and state resets
* Added support for session pin
* Fixed forcing a card driver via opensc.conf
## STARCOS
* Read the maximum transcive sice from the card's ATR (#765)

**Comment by dengert** [comment]
@frankmorgner 
What are the 2 binary files: /etc/DESRCACC100001 and etc/UTSRCACC100001 as part of  74ec7b04ffda539819eb8bfd6a0e766e69d8c946

Where is the source, and licence info on these 2 files. 
Are they created as part of config, of make?

Should they be ignored in gitignore?

**Comment by frankmorgner** [comment]
`DESRCACC100001` and `UTSRCACC100001` are the two possible device issuer root certificates of @CardContact's SC-HSM ("card verifiable certificates"). We use the document's signed public key to perform a key agreement for deriving SM keys. This secures the contact-less communication between OpenSC and the card. The two files *are* important!

**Comment by Jakuje** [comment]
I would highlight also the restoring of a blocking `C_WaitForSlot()` functionality (#899).

**Comment by frankmorgner** [comment]
Thanks, I updated the the draft above.

**Comment by Phoenyx33** [comment]
A quick question about the wiki, the place where it shows the data to create the .reg file says the entry "Crypto Provider" should be "Microsoft Base Smart Card Provider". However when I installed the 0.16 version and went to check the registry it was already filled in but with "OpensSC CSP". Which is the correct entry please?

**Comment by frankmorgner** [comment]
@Phoenyx33 Could you give the link?

**Comment by Phoenyx33** [comment]
This is the link to the relevant paragraph:
https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM#using-the-smartcard-hsm-with-the-csp-minidriver

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by frankmorgner** [comment]
Indeed, we're using "OpenSC CSP" as identifier. I corrected the wiki page. As with every wiki, some information may be out of date. Note that per concept, you are allowed to add/remove/modify the content of the wiki.

But the matter is also more complicated: Some other identifier should also technically work, but it would mean that
- the registry entry is *not* removed when OpenSC is uninstalled
- when requesting the crypto provider via MS Crypto API NG, the identifier would be different (obviously)

**Comment by CardContact** [comment]
We should remove UTSRCACC100001 from the distribution, as this root certificate is only used for internal testing.

**Comment by frankmorgner** [comment]
OK, could you make a PR?

**Comment by CardContact** [comment]
Is it referenced anywhere else than in opensc.wxs.in ?

**Comment by frankmorgner** [comment]
only in `etc/Makefile.am`

**Comment by frankmorgner** [comment]
@CardContact I removed UTSRCACC100001. Could you please have a look at #1050? It's still not fixed and is about to included in 0.17.0.
