### ISSUE TITLE
plcs11-tool fails for keys with CKA_ALWAYS_AUTHENTICATE

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#1063]
@frankmorgner  @nunojpg 

 423375c6f85853d359d502a28e676a09e33a0ac1 removed the calls to login(sess, CKU_CONTEXT_SPECIFIC) and replaces them with calls to authenticate_if_required. 

But authenticate_if_required  returns if the session is CKS_RW_USER_FUNCTION. But when a key has CKA_ALWAYS_AUTHENTICATE=true, the user must already be logged in AND a call to C_Login with CKU_CONTEXT_SPECIFIC. must be made.

An additional bug: authenticate_if_required only calls login(session, CKU_CONTEXT_SPECIFIC) if  CKF_PROTECTED_AUTHENTICATION_PATH is set.  

The need to use CKU_CONTEXT_SPECIFIC is independent from CKF_PROTECTED_AUTHENTICATION_PATH

This needs to be fixed before 0.17.0 is released.

**Comment by frankmorgner** [comment]
Hmm, we discussed this in https://github.com/OpenSC/OpenSC/pull/989 and did not find a solution. I don't think I'll find time soon to look deeper into this. Maybe reverting is the safest option although the situation before the change was also suboptimal...

**Comment by dengert** [comment]
I have created https://github.com/OpenSC/OpenSC/pull/1064 that addresses the issue, and covers all the C_SignInit, C_Sign C_SignFinal, C_DecryptInit and C_Decrypt command. I believe it will also address @nunojpg issues. 

Please have a look at this.

**Comment by dengert** [comment]
Reverting https://github.com/OpenSC/OpenSC/commit/423375c6f85853d359d502a28e676a09e33a0ac1 
for 0.17.0 would be a good idea.
