### ISSUE TITLE
C_Login(CRU_CONTEXT_SPECIFIC), Thunderbird and  SC_PIN_CMD_GET_INFO

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#1071]
### Expected behaviour
Thunderbird should sign email with a key that has CKA_ALWAYS_AUTHENTICATE

### Actual behaviour

Thunderbird issues C_Login(CRU_CONTEXT_SPECIFIC) then does a number of other PKCS#11 commands
including C_GetTonkeInfo that causes a Verify with SC_PIN_CMD_GET_INFO to be sent to the card. 

PIV card enforces no commands between the VERIFY with the PIN, and the crypto operation whe using key with CKA_ALWAYS_AUTHENTICATE

When the C_Sign is called, the card returns  security status not satisfied because the SC_PIN_CMD_GET_INFO command was sent to card.

C_Sign returns CKR_USER_NOT_LOGGED_IN. 

### Steps to reproduce

1. Run thundierbird with OpenSC 0.17.0-rc1, and use SPY or opensc debug log 
2. 
3. 

I have a solution, and will submit PR later today (6/18/2017) or tomorrow for 0.17.0

```

**Comment by Jakuje** [comment]
If I remember well, this is a bug in NSS I reported some half a year ago:

https://bugzilla.mozilla.org/show_bug.cgi?id=1333725

I talked about it with Bob, but it probably got lost in recent releases (not fixed in [current code](https://dxr.mozilla.org/mozilla-central/source/security/nss/lib/pk11wrap/pk11auth.c#639)). I will try to ask about the status or if we can get that fixed tomorrow.

**Comment by dengert** [comment]
The PIV driver used to work with Thunderbird, because it would cache the certs in memory during its initialization and thus no commands would be sent to the card between the VERIFY PIN and the crypto command. So its not finding the objects that are the problem for teh PIV card. But PKCS#11 expects the C_Login(CRU_CONTEXT_SPECIFIC) to follow a C_SignInit, where as the the PIV card driver expects the C_Login to be just before the  crypto operation C_Sign. So to be on the safe side the application should do C_SignInit, C_Login( CRU_CONTEXT_SPECIFIC), C_Sign with no other PKCS#11 calls. Other cards may respond differently.   

So to be on the safe side the application should do C_SignInit, C_Login( CRU_CONTEXT_SPECIFIC), C_Sign. Also applies for any crypto operation using a key with   CKA_ALWAYS_AUTHENTICATE=true

Its turns out the call to C_Get_SessionInfo that is the problem for the PIV driver 

These commits: https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b introduced the base code and PIV specific code to to send a VERIFY with Lc=0 (without pin) to the card
SC_PIN_CMD_GET_INFO is this type of verify.  This should then return 90 00 if the user was logged in.  The was done to test if the card was still present and test the security status of the card. 

But its turns out with PIV cards this sends an extra command to the card between the VERIFY PIN and the crypto command.  

My prototype fix runs on Ubuntu. It has framework-pkcs15.c set a flag in the sc_card structure when a C_Login(CKU_CONTEXT_SPECIFIC) is started. A card driver can use this as needed. The card-piv.c  uses this to not send  a SC_PIN_CMD_GET_INFO VERIFY Lc=0 until a crypto operation is done. The card driver can then set the flag to zero as needed. or ignore it.)  This works for a PIV card. I don't know of any other cards that enforce the CKA_ALWAYS_AUTHENTICATE (or the pkcs15 equivalent: user_consent)  on the card.  

A better way might be to have sc_pkcs15_verify_ext() with additional flags set as to what type of verify is being done. Is it for CKU_CONTEXT_SPECIFIC or not. This new routine would set the flag in sc_card.  This could then be used outside of framework-pkcs11.c  
@frankmorgner,  what do you think?

Thunderbird is not the only application that does not handle CKA_ALWAYS_AUTHENTICATE well. 


Here is an example from TB 52.2.0 32 bit on Windows 10 using the opensc- 0.17.0-rc1 
Same with TB 52.1.1 64 bit on Ubuntu-16.4
Starting with the C_Login 
167: C_Login
2017-06-17 20:09:22.604
[in] hSession = 0x6e099c8
[in] userType = CKU_CONTEXT_SPECIFIC
[in] pPin[ulPinLen] 0ad55278 / 6
    00000000  31 32 33 34 35 36                                123456          
Returned:  0 CKR_OK

168: C_GetSessionInfo
2017-06-17 20:09:22.856
[in] hSession = 0x6da87f0
[out] pInfo: 
      slotID:                  0
      state:                  '           CKS_RO_USER_FUNCTIONS'
      flags:                   4
        CKF_SERIAL_SESSION               
      ulDeviceError:           0
Returned:  0 CKR_OK

169: C_GetAttributeValue
2017-06-17 20:09:23.035
[in] hSession = 0x6da87f0
[in] hObject = 0x6da81d0
[in] pTemplate[2]: 
    CKA_ID                00000000 / 0
    CKA_CLASS             00000000 / 0
[out] pTemplate[2]: 
    CKA_ID                00000000 / 1
    CKA_CLASS             00000000 / 4
Returned:  0 CKR_OK

170: C_GetAttributeValue
2017-06-17 20:09:23.049
[in] hSession = 0x6da87f0
[in] hObject = 0x6da81d0
[in] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    CKA_CLASS             0dc21818 / 4
[out] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    00000000  02                                               .               
    CKA_CLASS             CKO_CERTIFICATE      
Returned:  0 CKR_OK

171: C_FindObjectsInit
2017-06-17 20:09:23.064
[in] hSession = 0x6da87f0
[in] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    00000000  02                                               .               
    CKA_CLASS             CKO_PRIVATE_KEY      
Returned:  0 CKR_OK

172: C_FindObjects
2017-06-17 20:09:23.337
[in] hSession = 0x6da87f0
[in] ulMaxObjectCount = 0x1
[out] ulObjectCount = 0x1
Object 0x6d61938 matches
Returned:  0 CKR_OK

173: C_FindObjectsFinal
2017-06-17 20:09:23.341
[in] hSession = 0x6da87f0
Returned:  0 CKR_OK

174: C_GetSlotInfo
2017-06-17 20:09:23.347
[in] slotID = 0x0

175: C_GetSlotList
2017-06-17 20:09:23.392
[in] tokenPresent = 0x0
[out] pInfo: 
      slotDescription:        'SCM Microsystems Inc. SCR35xx US'
                              'B Smart Card Reader 0           '
      manufacturerID:         'SCM Microsystems Inc.           '
      hardwareVersion:         3.4
      firmwareVersion:         0.0
      flags:                   7
        CKF_TOKEN_PRESENT                
        CKF_REMOVABLE_DEVICE             
        CKF_HW_SLOT                      
Returned:  0 CKR_OK

176: C_GetSessionInfo
2017-06-17 20:09:23.417
[in] hSession = 0x6da87f0
[out] pSlotList: 
Count is 1
[out] *pulCount = 0x1
Returned:  0 CKR_OK
[out] pInfo: 
      slotID:                  0
      state:                  '           CKS_RO_USER_FUNCTIONS'
      flags:                   4
        CKF_SERIAL_SESSION               
      ulDeviceError:           0
Returned:  0 CKR_OK

177: C_GetAttributeValue
2017-06-17 20:09:23.643
[in] hSession = 0x6da87f0
[in] hObject = 0x6da8400
[in] pTemplate[2]: 
    CKA_ID                00000000 / 0
    CKA_CLASS             00000000 / 0
[out] pTemplate[2]: 
    CKA_ID                00000000 / 1
    CKA_CLASS             00000000 / 4
Returned:  0 CKR_OK

178: C_GetAttributeValue
2017-06-17 20:09:23.661
[in] hSession = 0x6da87f0
[in] hObject = 0x6da8400
[in] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    CKA_CLASS             0dc21818 / 4
[out] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    00000000  03                                               .               
    CKA_CLASS             CKO_CERTIFICATE      
Returned:  0 CKR_OK

179: C_FindObjectsInit
2017-06-17 20:09:23.676
[in] hSession = 0x6da87f0
[in] pTemplate[2]: 
    CKA_ID                0dc21810 / 1
    00000000  03                                               .               
    CKA_CLASS             CKO_PRIVATE_KEY      
Returned:  0 CKR_OK

180: C_FindObjects
2017-06-17 20:09:23.927
[in] hSession = 0x6da87f0
[in] ulMaxObjectCount = 0x1
[out] ulObjectCount = 0x1
Object 0x6d61a50 matches
Returned:  0 CKR_OK

181: C_FindObjectsFinal
2017-06-17 20:09:23.930
[in] hSession = 0x6da87f0
Returned:  0 CKR_OK

182: C_Sign
2017-06-17 20:09:23.935
[in] hSession = 0x6e099c8
[in] pData[ulDataLen] 0b377010 / 51
    00000000  30 31 30 0D 06 09 60 86 48 01 65 03 04 02 01 05  010...`.H.e.....
    00000010  00 04 20 E6 11 EC EA BE 44 7F 48 DA 7D 64 38 66  .. .....DH.}d8f
    00000020  33 25 97 9C 0A B5 16 03 63 BD 11 81 34 FB 83 B8  3%......c...4...
    00000030  5D 81 26                                         ].&             

183: C_GetSlotList
2017-06-17 20:09:24.463
[in] tokenPresent = 0x0
Returned:  257 CKR_USER_NOT_LOGGED_IN

**Comment by frankmorgner** [comment]
**NIST Special Publication 800-73-4**:

>3.2.1 VERIFY Card Command

...

>If the VERIFY command fails for one of the reasons specified above, then the security  status and the retry counter of the key reference shall remain unchanged. If P1='00', and Lc  and the command data field are absent, the command can be used to retrieve the number of further retries allowed ('63 CX'), or to check whether verification is not needed ('90 00').

...

>If P1='FF' , and Lc and the command data field are absent, the command shall reset the security status of the key reference in P2. The security status of the key reference specified in P2 shall be set to FALSE and the retry counter associated with the key reference shall remain unchanged.

Maybe it's because I'm not a native speaker, but it appears that both paragraphs are a bit contradicting: Why would someone want to *check whether verification is not needed* when the same command resets the *security status of the key reference in P2* (because Lc is absent)? For me, this feels like a problem with the specification (and some implementer blindly following the specification).

In terms of handling this issue, I am not a fan of introducing yet more hacks and flags for specific cards on the more general layers of OpenSC (i.e. `sc_card_context_specific_login` in #1072). Wouldn't it be best to simply remove `SC_CARD_CAP_ISO7816_PIN_INFO` from the PIV flags? This should disable asking the card for the state and enable caching the login state at the PKCS#11 level. This way, PIV should behave as in the releases before...

**Comment by dengert** [comment]
NIST 800-73-4  Part 2 also states: 
"3.2.1 X.509 Certificate for Digital Signature"
 The PKI cryptographic function (see Table 4b) is protected with a “PIN Always” or “OCC Always” access rule. In other words, the PIN or OCC data must be submitted and verified every time immediately before a digital signature key operation. This ensures cardholder participation every time the private key is used for digital signature generation.5

(I had referred to "Always Authenticate" but should have said "PIN Always". Sorry for any confusion.)


https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b and https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b solved another major problem. The OpenSC C_Get*Info routines would report stale information and not the current state of the card. Other applications may have used the card.  Having  the current status is important for an application that starts a session then lets the user do other things before actually using the session. A browser or e-mail program is a prime example. I would not want to remove `SC_CARD_CAP_ISO7816_PIN_INFO` from the PIV code. 

The  VERIFY Lc=0 command  does not change the card security status. But it does violate the "PIN Always" rule  for the SIGN Key.  The card views the VERIFY Lc=0 as a command between the VERIFY PIN and SIGN commands. The patch is designed to let the card driver know that a C_Login(CKU_CONTEXT_SPECIFIC) is being issued, so the card driver can avoid sending  any commands  until the SIGN command is sent. 

The current sc_pkcs15_verify_pin is called for both the normal C_Login and C_Login(CKU_CONTEXT_SPECIFIC). So a card driver has no way to what is going on. 

On could argue that the application is at fault, issuing C_Get*Info calls between a C_Login(CKU_CONTEXT_SPECIFIC) command the C_Sign command. But as you pointed out PKCS\#11 says the C_Login(CKU_CONTEXT_SPECIFIC) must be issues immediately after the C_SignInit. But the "PIN Always" rule implies the   C_Login(CKU_CONTEXT_SPECIFIC) should be done immediately before the C_SIgn. (Both can be true if the application does not call any other PKCS\#11 calls between  C_SignInit,   C_Login(CKU_CONTEXT_SPECIFIC) and C_Sign.) 

NIST 800-73 does not say anything about PKCS\#11. 

You may call the patch a hack, I call it an essential piece of information to the card driver. Other card drivers could also use this information as needed.  We could modify sc_pkcs15_verify_pin  to pass the type of verify being done to the card driver. But that would require a API change.  We could add some other routine to  pass this information or a  sc_pkcs15_verify_pin_ext routine.

**Comment by frankmorgner** [comment]
From what I've noticed, it seems that PIV support in OpenSC has been acceptable in the past years, even without support for `SC_CARD_CAP_ISO7816_PIN_INFO`. Also, macOS and Windows now have native support for PIV, which probably most users will use without ever noticing OpenSC. So I'd like to think of alternative solutions that don't require changing everything above `card-piv.c` and `pkcs15-piv.c`. Since you agree that NIST says nothing about PKCS#11, I think you will agree that the PKCS#11 flags don't necessarily need to be passed to the card driver.

In your proposal you're passing the information about a successful verify (i.e. "we are doing something context specific") from PKCS#11 to the card driver. However, you could simply keep this information in the card driver when the PIN get verified. So I'd suggest the following change:

1. Cache the login status in the PIV's card driver.
2. If the PIN status is requested, do the following:
    1. If we know the status is not cached or the cache says that the user is logged out, then ask the card about the status
    2. Otherwise return the cached status and don't send any command to the card.

I think this would the same result as your proposal just without modifying all the layers above the card driver.

**Comment by dengert** [comment]
In your first paragraph, I agree that most people on Windows using PIV have never heard of OpenSC, and just use what Microsoft provides. Early in 2004 or so  at  NIST conference an Apple developer said they  would have a PIV driver, even questioning why I would write one! Well  here it is in 2017 and we have MacOS user like @mouse07410 using the OpenSC drivers for MacOS, because Apple  never got it write. 

But on both platforms, there are still PKCS\#11 applications like Thunderbird and FireFox, so OpenSC usefull. And there is Android ports of OpenSC too. So I think there are still uses for OpenSC on other platforms. 
 
You said: " Since you agree that NIST says nothing about PKCS#11, I think you will agree that the PKCS#11 flags don't necessarily need to be passed to the card driver."  **No I do not agree.** 

What I will agree is that a carefully crafted PKCS\#11 application can use the SIGN key, if it does  
not make any PKCS\#11 calls between the C_Login(CKU_CONTEXT_SPECIFIC) and the C_Sign.  

We are dealing with incompatibly standards for PKCS\#11, cards and applications. The best we can do is try and accommodate them as best we can.  The patch is an example of how to accommodate the latest problem, that the `SC_CARD_CAP_ISO7816_PIN_INFO` introduced to solve a more serious problem of  OpenSC  reporting stale information about the card state.  But the method of doing a command to the card then caused the PIV "PIN Always" rule enforced by the card to be violated. 

The PIV already cached all the certificates, and the public keys and information about the matching private keys to avoid accessing the card. But the `SC_CARD_CAP_ISO7816_PIN_INFO` code introduced a new why to interfere with the "PIN Always" rule. 

OpenSC could tell all the applications to rewrite their PKCS\#11 code to not do any PKCS\#11 calls between the C_Login(CKU_CONTEXT_SPECIFIC) and the C_Sign. But that would be like the English language Idiom:  "The tail wagging the dog"

It looks like @Jakuje  reported that they could not get OpenSC to work with Thunderbird over a year ago. https://bugzilla.mozilla.org/show_bug.cgi?id=1333725 It points at NSS updating the database as the problem, it may be with some cards, but with the PIV that is not the problem, as the PIV driver has cached the certs, pubkey and privkey info so no commands are sent to the card.  But what it does show is C_Get*Info calls being done.   

If @Jakuje can get Mozilla to fix Thunderbird to not make all the extra calls to C_Get*Info routines between the 
C_Login(CKU_CONTEXT_SPECIFIC) and the C_Sign that would be great. But that is out of  OpenSC's control and it only one application. 

The patch does not affect any other drivers, but could be of use if other drivers have a similar situation. 
 As other cards start to use PKCS\#15 "user_consent"  key and the card starts to enforce it, they could use this  patch too. 

I don't think I am asking for much, to add the few lines to framework-pkcs11.c  and opensc.h to pass the need information down to the card driver level. 

I would like to hear from others, like @Jakuje and @mouse07410  who have run into this problem since  
 `SC_CARD_CAP_ISO7816_PIN_INFO` was introduced or who want to use Thunderbird signed and/or encrypted e-mail using a PIV type card.

**Comment by frankmorgner** [comment]
OpenSC is the only OSS implementation for the PIV card. So while the usefulness for the PIV end user may be debatable, it certainly has its place. I just wanted to make the point that we don't need to support every little technical detail possible (e.g. `SC_CARD_CAP_ISO7816_PIN_INFO`) if almost nobody will recognize it.

Did you think about the solution at the driver level I proposed? I think it should have the exact same result as your changes.

**Comment by dengert** [comment]
If you turn off `SC_CARD_CAP_ISO7816_PIN_INFO` why not just revert all of https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b ? The whole point of https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b  is  to test the card to see if the security state has changed. This usually is caused by interference from some other application trying to use the card. 

I am saying https://github.com/OpenSC/OpenSC/commit/2f10de4f5c190e61bec4e6a582982404780f0d9b  is important, especially when the mail program like Thunderbird has an open session then tries to sign an e-mail. This is usually after a long time period. 

The patch in effect turns off SC_CARD_CAP_ISO7816_PIN_INFO but only between the C_Login(CKU_CONTEXT_SPECIFIC) and the crypto operation which should be vert short and without interference from other applications.  NSS is using some type of polling loop or thread that calls  C_GetSlotList, C_GetSlotInfo and C_GetSessionInfo. These cause the card to be queried.

**Comment by frankmorgner** [comment]
>The patch in effect turns off SC_CARD_CAP_ISO7816_PIN_INFO but only between the C_Login(CKU_CONTEXT_SPECIFIC) and the crypto operation which should be vert short and without interference from other applications. NSS is using some type of polling loop or thread that calls C_GetSlotList, C_GetSlotInfo and C_GetSessionInfo. These cause the card to be queried.

Yes, I understood. And I suggested an alternative implementation that realizes this at the driver level. To make things clearer, I've created the following commits
1. Restore 0.16.0 behavior of the PIV driver: https://github.com/frankmorgner/OpenSC/commit/f071cb236a84081d4d820a10e4de410c3f9773ec (Not what you want, I know, but still fixes things without making them worse compared to 0.16.0.)
2. Disable Status query when the PIN has been verified: https://github.com/frankmorgner/OpenSC/commit/884793417debce6923e9fb7847b46949bc0f73a6 (Should allow `C_GetSlotList`, `C_GetSlotInfo` and `C_GetSessionInfo` after `C_Login(CKU_CONTEXT_SPECIFIC)`.)

**Comment by dengert** [comment]
@frankmorgner 
I see 3 commits but you only talk about https://github.com/frankmorgner/OpenSC/commit/f071cb236a84081d4d820a10e4de410c3f9773ec and 
 frankmorgner/OpenSC@8847934
It looks like  https://github.com/frankmorgner/OpenSC/commit/1b7932ab43ce77533998d2774878738c8a341cd8 reverts  https://github.com/frankmorgner/OpenSC/commit/f071cb236a84081d4d820a10e4de410c3f9773ec
bit to took out the `/* TODO may turn off SC_CARD_CAP_ISO7816_PIN_INFO later */ comment line.

Your patch has made things worse. Thunderbird prompts for the PIN, but it never gets sent to the card and the email is not signed.  And thundebird closes the main window, but still keep prompting for the PIN.  Even pulling  out the card does not get it to end, I have to kill the process.

Do you have a way to test a PIV card or NEO with a a SIGN cert that wants "PIN Always"?

I had a solution that worked, and could be used by other card drivers that wil run into this type of problem in the future. 

If you want I will write a sc_pkcs15_verify_pin_context_specific to be used from framework-pkcs15.c 
It will set the  sc_card_context_specific_login flag and and call a sc_pkcs15_verify_pin. It could be added to the API so could be used if needed from other non PKCS\#11 applications. 

If you don't agree I would rather see no change made, and I will discuses this more with the Mozilla and RedHat people on how to not cause the card to be queried  between the C_Login(CKU_CONTEXT_SPECIFIC) and the C_Sign. 
I will be the "tail trying to wag the Mozilla dog" and see how far I can get.

**Comment by dengert** [comment]
Updated the https://bugzilla.mozilla.org/show_bug.cgi?id=1333725 with reference to this issue.

**Comment by frankmorgner** [comment]
I have a Yubikey. Do you know how to initialize it to get "PIN Always"?

**Comment by dengert** [comment]
@mouse07410  may have more information, as would any Yubkey developer.

The  9C key is by default marked as "PIN Always". 

See this page and search for "PIN Always" 
https://developers.yubico.com/yubico-piv-tool/Manuals/yubico-piv-tool.1.html
The 9C private key is "PIN Always"

(I believe one of their tools let you set the "PIN Always" on any key. Never tried it.
and no code was added to query the card to see which keys have "PIN Always".)

The cert (02) that matches the 9C key should be to sign e-mail and have keyUsage=signing, non-repudiation and a subjectAltName=email:<email@address> 
To use with Thunderbird the <email@address> should match the email address on the account.
  
Also note that different versions of NEO/Yubikey have comparability issues.
Look in card-piv.c for the  CI_* defines and how they handle VERIFY Lc=0
Then look where the CI_* are used.

**Comment by mouse07410** [comment]
>> I have a Yubikey. Do you know how to initialize it to get "PIN Always"?
>
> @mouse07410 may have more information, as would any Yubkey developer.

One way I know of is setting the appropriate flags at the on-card key generation time using [yubico-piv-tool](https://github.com/Yubico/yubico-piv-tool.git) application open-sourced by Yubico. Another way is using their `libykcs11.so` library (an loose analog of `opensc-pkcs11.so`) that is now included as a part of `yubico-piv-tool` package.

It looks like you can set the appropriate flag at the key *import* time as well, but only for Yubikey 4 (i.e., not for Yubikey NEO).

I have not experimented with this at all, because I'm perfectly happy with the default policy (only the Digital Signature key has ALWAYS_AUTHENTICATE attribute).

Here's the help output from the current `yubico-piv-tool` (pay attention at how keys `9c` and `9e` are described):

```
$ yubico-piv-tool --help
yubico-piv-tool 1.4.4

Usage: yubico-piv-tool [OPTIONS]...

  -h, --help               Print help and exit
      --full-help          Print help, including hidden options, and exit
  -V, --version            Print version and exit
  -v, --verbose[=INT]      Print more information  (default=`0')
  -r, --reader=STRING      Only use a matching reader  (default=`Yubikey')
  -k, --key[=STRING]       Management key to use, if no value is specified key
                             will be asked for
                             (default=`010203040506070801020304050607080102030405060708')
  -a, --action=ENUM        Action to take  (possible values="version",
                             "generate", "set-mgm-key", "reset",
                             "pin-retries", "import-key",
                             "import-certificate", "set-chuid",
                             "request-certificate", "verify-pin",
                             "change-pin", "change-puk", "unblock-pin",
                             "selfsign-certificate", "delete-certificate",
                             "read-certificate", "status",
                             "test-signature", "test-decipher",
                             "list-readers", "set-ccc", "write-object",
                             "read-object", "attest")

       Multiple actions may be given at once and will be executed in order
       for example --action=verify-pin --action=request-certificate

  -s, --slot=ENUM          What key slot to operate on  (possible
                             values="9a", "9c", "9d", "9e", "82",
                             "83", "84", "85", "86", "87", "88",
                             "89", "8a", "8b", "8c", "8d", "8e",
                             "8f", "90", "91", "92", "93", "94",
                             "95", "f9")

       9a is for PIV Authentication
       9c is for Digital Signature (PIN always checked)
       9d is for Key Management
       9e is for Card Authentication (PIN never checked)
       82-95 is for Retired Key Management
       f9 is for Attestation

  -A, --algorithm=ENUM     What algorithm to use  (possible values="RSA1024",
                             "RSA2048", "ECCP256", "ECCP384"
                             default=`RSA2048')
  -H, --hash=ENUM          Hash to use for signatures  (possible
                             values="SHA1", "SHA256", "SHA384",
                             "SHA512" default=`SHA256')
  -n, --new-key=STRING     New management key to use for action set-mgm-key, if
                             omitted key will be asked for
      --pin-retries=INT    Number of retries before the pin code is blocked
      --puk-retries=INT    Number of retries before the puk code is blocked
  -i, --input=STRING       Filename to use as input, - for stdin  (default=`-')
  -o, --output=STRING      Filename to use as output, - for stdout
                             (default=`-')
  -K, --key-format=ENUM    Format of the key being read/written  (possible
                             values="PEM", "PKCS12", "GZIP", "DER",
                             "SSH" default=`PEM')
  -p, --password=STRING    Password for decryption of private key file, if
                             omitted password will be asked for
  -S, --subject=STRING     The subject to use for certificate request

       The subject must be written as:
       /CN=host.example.com/OU=test/O=example.com/

      --serial=INT         Serial number of the self-signed certificate
      --valid-days=INT     Time (in days) until the self-signed certificate
                             expires  (default=`365')
  -P, --pin=STRING         Pin/puk code for verification, if omitted pin/puk
                             will be asked for
  -N, --new-pin=STRING     New pin/puk code for changing, if omitted pin/puk
                             will be asked for
      --pin-policy=ENUM    Set pin policy for action generate or import-key.
                             Only available on YubiKey 4  (possible
                             values="never", "once", "always")
      --touch-policy=ENUM  Set touch policy for action generate, import-key or
                             set-mgm-key. Only available on YubiKey 4
                             (possible values="never", "always",
                             "cached")
      --id=INT             Id of object for write/read object
  -f, --format=ENUM        Format of data for write/read object  (possible
                             values="hex", "base64", "binary"
                             default=`hex')
```

**Comment by dengert** [comment]
IN #1072 I have updated the branch with a new conmit to replace the code in framework-pkcs15.c wit a call to a new sc_pkcs15_verify_pin_context_specific. 

See https://github.com/OpenSC/OpenSC/pull/1072#issuecomment-310678440  for an annotated  opensc-debug-log.txt showing how C_Login, C_GetSessionInfo, VERIFY Lc=0 interact.  

With this new commit, no changes are needed to Thunderbird to use OpenSC with PIV SIGN key that enforce the NIST 800-73  "PIN Always" rule.
