### ISSUE TITLE
ePass2003 EC not supported

### ISSUE THREAD

**Issue by majkrzak** [OpenSC/OpenSC#1073]
It seems that OpenSC (**0.16.0** Arch Linux build) don't support elliptic curves on Feitian Technologies, Inc. ePass2003 USB token (**096e:0807**).

    ~> opensc-tool --list-algorithms
    Using reader with a card: Feitian ePass2003 00 00
    Algorithm: rsa
    Key length: 512
    Flags: onboard key generation padding ( none ) hashes ( )

    Algorithm: rsa
    Key length: 768
    Flags: onboard key generation padding ( none ) hashes ( )

    Algorithm: rsa
    Key length: 1024
    Flags: onboard key generation padding ( none ) hashes ( )

    Algorithm: rsa
    Key length: 2048
    Flags: onboard key generation padding ( none ) hashes ( )

    ~> pkcs11-tool -k --key-type EC:prime256v1
    Using slot 0 with a present token (0x0)
    error: Generate EC key mechanism not supported

    ~> pkcs15-init --generate-key EC:prime256v1 --key-usage sign --auth-id 1
    Using reader with a card: Feitian ePass2003 00 00
    Failed to generate key: Not supported

Bay the way: why is epass2003.profile described as `pkcs15 profile for entersafe`

**Comment by frankmorgner** [comment]
The initial implementation was provided by @viktorTarasov, most recent changes are from @FeitianSmartcardReader. Maybe they can help.

**Comment by FeitianSmartcardReader** [comment]
@majkrzak  We will check the issue and back to you soon, thanks

**Comment by FeitianSmartcardReader** [comment]
@majkrzak The issue already solved, I am working submit pull request of this issue, will keep update, thanks

**Comment by FeitianSmartcardReader** [comment]
@majkrzak please using latest version
https://github.com/FeitianSmartcardReader/OpenSC

**test log**
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs11-tool --module /usr/local/lib/opensc-pkcs11.so -l -p 1234 -k --key-type EC:prime256v1 -a myaeskey
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-init --generate-key EC:prime256v1 --key-usage sign --auth-id 1
Using reader with a card: FT  ePass2003Auto
User PIN [User PIN] required.
Please enter User PIN [User PIN]: 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ 
Hongbins-MacBook-Pro:OpenSC Ben$ pkcs15-tool -D
Using reader with a card: FT  ePass2003Auto
PKCS#15 Card [“epass2003”]:
	Version        : 0
	Serial number  : 0900000000000000
	Manufacturer ID: EnterSafe
	Last update    : 20170810091954Z
	Flags          : EID compliant
PIN [User PIN]
	Object Flags   : [0x3], private, modifiable
	ID             : 01
	Flags          : [0x32], local, initialized, needs-padding
	Length         : min_len:4, max_len:16, stored_len:16
	Pad char       : 0x00
	Reference      : 1 (0x01)
	Type           : ascii-numeric
	Path           : 3f005015

Private EC Key [myaeskey]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x10C], sign, signRecover, derive
	Access Flags   : [0x0]
	FieldLength    : 256
	Key ref        : 0 (0x0)
	Native         : yes
	Path           : 3f0050152900
	Auth ID        : 01
	ID             : 0c45525113139b102993eec81e89398bdac3f318
	MD:guid        : 4a4d3e6f-5b32-23a5-0bdb-1da7887f8897

Private EC Key [Private Key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0xC], sign, signRecover
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	FieldLength    : 256
	Key ref        : 1 (0x1)
	Native         : yes
	Path           : 3f0050152901
	Auth ID        : 01
	ID             : 8ee34d9f23a7d5ee3ee21fa09b1485c9128feeb8
	MD:guid        : 10354d8d-ec05-1c45-d517-799fdec77092

Public RSA Key [myaeskey]
	Object Flags   : [0x2], modifiable
	Usage          : [0x1C0], verify, verifyRecover, derive
	Access Flags   : [0x0]
	ModLength      : 255
	Key ref        : 0 (0x0)
	Native         : no
	Path           : 3f0050153000
	ID             : 0c45525113139b102993eec81e89398bdac3f318

Public RSA Key [Private Key]
	Object Flags   : [0x2], modifiable
	Usage          : [0xC0], verify, verifyRecover
	Access Flags   : [0x0]
	ModLength      : 255
	Key ref        : 0 (0x0)
	Native         : no
	Path           : 3f0050153001
	ID             : 8ee34d9f23a7d5ee3ee21fa09b1485c9128feeb8

Hongbins-MacBook-Pro:OpenSC Ben$

**Comment by majkrzak** [comment]
Thx, but I am little bit lazy and I will wait for Arch package update ;)

**Comment by majkrzak** [comment]
Thx, @frankmorgner. When can I expect 0.17.1 release?
