### ISSUE TITLE
sc-hsm: Change PIN via pkcs-11 fails

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#1076]
### Expected behaviour

Changing the SmartCard-HSM PIN via pkcs11-tool.

### Actual behaviour

C_SetPIN fails with rv = CKR_DATA_INVALID

Apparently the code tries to change the SoC PIN, which fails on a vanilla SmartCard-HSM.

### Steps to reproduce

+ MODULE=../pkcs11/.libs/opensc-pkcs11.so
+ PIN=648219
+ SOPIN=3537363231383830
+ SOPIN2=0123456789ABCDEF
+ KEYID=10
+ CAID=11
+ DATAID=20
+ ./pkcs11-tool --module ../pkcs11/.libs/opensc-pkcs11.so --init-token --label test --so-pin 3537363231383830
Using slot 1 with a present token (0x4)
Token successfully initialized
+ ./pkcs11-tool --module ../pkcs11/.libs/opensc-pkcs11.so --login --login-type so --so-pin 3537363231383830 --init-pin --new-pin 648219
Using slot 1 with a present token (0x4)
User PIN successfully initialized
+ ./pkcs11-tool --module ../pkcs11/.libs/opensc-pkcs11.so --login --login-type so --so-pin 3537363231383830 --init-pin --new-pin 648219
Using slot 1 with a present token (0x4)
User PIN successfully initialized
+ ./pkcs11-tool --module ../pkcs11/.libs/opensc-pkcs11.so --login --pin 648219 --change-pin --new-pin 648219
Using slot 1 with a present token (0x4)
error: PKCS11 function C_SetPIN failed: rv = CKR_DATA_INVALID (0x20)

### Logs

0x7f1209457700 16:26:54.054 [opensc-pkcs11] pkcs11-session.c:425:C_SetPIN: Changing PIN (session 0x18a8e70; login user 1)
0x7f1209457700 16:26:54.054 [opensc-pkcs11] framework-pkcs15.c:1721:pkcs15_change_pin: Change 'UserPIN' (ref:129,type:1)
0x7f1209457700 16:26:54.054 [opensc-pkcs11] pkcs15-pin.c:478:sc_pkcs15_change_pin: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:407:sc_lock: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] reader-pcsc.c:612:pcsc_lock: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:449:sc_lock: returning with: 0 (Success)
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:748:sc_select_file: called; type=0, path=e82b0601040181c31f0201::
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:783:sc_select_file: returning with: 0 (Success)
0x7f1209457700 16:26:54.054 [opensc-pkcs11] sec.c:169:sc_pin_cmd: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] apdu.c:554:sc_transmit_apdu: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:407:sc_lock: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] card.c:449:sc_lock: returning with: 0 (Success)
0x7f1209457700 16:26:54.054 [opensc-pkcs11] apdu.c:521:sc_transmit: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] apdu.c:371:sc_single_transmit: called
0x7f1209457700 16:26:54.054 [opensc-pkcs11] apdu.c:378:sc_single_transmit: CLA:0, INS:A4, P1:4, P2:C, data(14) 0x7ffe76bd5630
0x7f1209457700 16:26:54.054 [opensc-pkcs11] reader-pcsc.c:283:pcsc_transmit: reader 'Identive SCT3522CC token [CCID Interface] (21121349600022) 00 00'
0x7f1209457700 16:26:54.054 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit: 
Outgoing APDU (19 bytes):
00 A4 04 0C 0E FF 6D 69 6E 42 69 6F 43 6C 69 65 ......minBioClie
6E 74 01                                        nt.
0x7f1209457700 16:26:54.054 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f1209457700 16:26:54.075 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit: 
Incoming APDU (2 bytes):
6A 86 j.
0x7f1209457700 16:26:54.075 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
0x7f1209457700 16:26:54.075 [opensc-pkcs11] apdu.c:543:sc_transmit: returning with: 0 (Success)
0x7f1209457700 16:26:54.075 [opensc-pkcs11] card.c:459:sc_unlock: called
0x7f1209457700 16:26:54.075 [opensc-pkcs11] iso7816.c:124:iso7816_check_sw: Incorrect parameters P1-P2
0x7f1209457700 16:26:54.075 [opensc-pkcs11] card-sc-hsm.c:308:sc_hsm_soc_change: Could not select MinBioClient application: -1205 (Incorrect parameters in APDU)
0x7f1209457700 16:26:54.075 [opensc-pkcs11] sec.c:216:sc_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
0x7f1209457700 16:26:54.075 [opensc-pkcs11] card.c:459:sc_unlock: called
0x7f1209457700 16:26:54.075 [opensc-pkcs11] reader-pcsc.c:662:pcsc_unlock: called
0x7f1209457700 16:26:54.078 [opensc-pkcs11] framework-pkcs15.c:1759:pkcs15_change_pin: PIN change returns -1205
0x7f1209457700 16:26:54.078 [opensc-pkcs11] misc.c:61:sc_to_cryptoki_error_common: libopensc return value: -1205 (Incorrect parameters

**Comment by CardContact** [comment]
Changing the SO-PIN with

./pkcs11-tool --module ${MODULE} --login --login-type so --so-pin ${SOPIN} --change-pin --new-pin ${SOPIN2}

also fails.

**Comment by frankmorgner** [comment]
This should not be triggered for standard sc-hsm. Please attach a complete log.

**Comment by CardContact** [comment]
[change_pin.txt](https://github.com/OpenSC/OpenSC/files/1098539/change_pin.txt)
[change_so_pin.txt](https://github.com/OpenSC/OpenSC/files/1098540/change_so_pin.txt)

**Comment by frankmorgner** [comment]
According to your initial commit https://github.com/CardContact/OpenSC/commit/a374525819d3baaa0dd3a24b303e28c6b3634a41#diff-d643a0fa169471dbf2912f4866dc49c5R920, `SC_CARD_CAP_PROTECTED_AUTHENTICATION_PATH` is detected if
```
Outgoing APDU (4 bytes):
00 20 00 85 . ..
```
does **not** yield `SC_ERROR_DATA_OBJECT_NOT_FOUND`. However, your card returns *Incorrect parameters P1-P2*:
```
Incoming APDU (2 bytes):
6A 86 j.
```
What do you suggest as alternative detection method?

**Comment by CardContact** [comment]
Apparently there is a difference between the code base for JCOP 2.4.2r3 (with Biomatch) and JCOP 2.4.1r3 (without Biomatch). The former returns _Reference data not found_ when one of the bio templates is referenced, the later returns _Incorrect parameter P1-P2_.

I'll push a change to cover both cases. In my tests this fixed the problem.
