### ISSUE TITLE
EstEID: PIN1 verify fails with PinPAD

### ISSUE THREAD

**Issue by metsma** [OpenSC/OpenSC#1083]
### Expected behaviour
pkcs11-tool --module=/usr/local/lib/opensc-pkcs11.so --slot 0 --login -O
Private Key Object; RSA ...

### Actual behaviour
pkcs11-tool --module=/usr/local/lib/opensc-pkcs11.so --slot 0 --login -O
error: PKCS11 function C_Login failed: rv = CKR_PIN_INCORRECT (0xa0)
Aborting.

PIN2 succeeds
pkcs11-tool --module=/usr/local/lib/opensc-pkcs11.so --slot 1 --login -O
Private Key Object; RSA 

### Steps to reproduce
pkcs11-tool --module=/usr/local/lib/opensc-pkcs11.so --slot 0 --login -O
Private Key Object; RSA 

### Logs
Failed PIN1 attempt
```
0x7f1681803700 14:01:16.814 [opensc-pkcs11] card-mcrd.c:1390:mcrd_pin_cmd: called
0x7f1681803700 14:01:16.814 [opensc-pkcs11] reader-pcsc.c:1644:pcsc_pin_cmd: called
0x7f1681803700 14:01:16.814 [opensc-pkcs11] reader-pcsc.c:184:pcsc_internal_transmit: called
0x7f1681803700 14:01:16.814 [opensc-pkcs11] reader-pcsc.c:1684:pcsc_pin_cmd: PC/SC v2 pinpad block: 1E1E0200000C0402FF00000000000004 00000000200001
0x7f1681803700 14:01:16.814 [opensc-pkcs11] reader-pcsc.c:184:pcsc_internal_transmit: called
0x7f1681803700 14:01:20.964 [opensc-pkcs11] card-mcrd.c:1430:mcrd_pin_cmd: returning with: -1214 (PIN code or key incorrect)
0x7f1681803700 14:01:20.964 [opensc-pkcs11] sec.c:206:sc_pin_cmd: returning with: -1214 (PIN code or key incorrect)
0x7f1681803700 14:01:20.964 [opensc-pkcs11] pkcs15-pin.c:368:sc_pkcs15_verify_pin: PIN cmd result -1214
0x7f1681803700 14:01:20.964 [opensc-pkcs11] card.c:392:sc_unlock: called
0x7f1681803700 14:01:20.964 [opensc-pkcs11] reader-pcsc.c:556:pcsc_unlock: called
0x7f1681803700 14:01:20.968 [opensc-pkcs11] pkcs15-pin.c:373:sc_pkcs15_verify_pin: returning with: -1214 (PIN code or key incorrect)
0x7f1681803700 14:01:20.968 [opensc-pkcs11] framework-pkcs15.c:1513:pkcs15_login: PKCS15 verify PIN returned -1214
0x7f1681803700 14:01:20.968 [opensc-pkcs11] misc.c:61:sc_to_cryptoki_error_common: libopensc return value: -1214 (PIN code or key incorrect)
```
positive PIN2 attempt
```
0x7fd747f3e700 14:01:32.203 [opensc-pkcs11] reader-pcsc.c:1644:pcsc_pin_cmd: called
0x7fd747f3e700 14:01:32.203 [opensc-pkcs11] reader-pcsc.c:184:pcsc_internal_transmit: called
0x7fd747f3e700 14:01:32.203 [opensc-pkcs11] reader-pcsc.c:1684:pcsc_pin_cmd: PC/SC v2 pinpad block: 1E1E0200000C0502FF00000000000004 00000000200002
0x7fd747f3e700 14:01:32.203 [opensc-pkcs11] reader-pcsc.c:184:pcsc_internal_transmit: called
0x7fd747f3e700 14:01:37.018 [opensc-pkcs11] card-mcrd.c:1430:mcrd_pin_cmd: returning with: 0 (Success)
0x7fd747f3e700 14:01:37.018 [opensc-pkcs11] sec.c:206:sc_pin_cmd: returning with: 0 (Success)
0x7fd747f3e700 14:01:37.018 [opensc-pkcs11] pkcs15-pin.c:368:sc_pkcs15_verify_pin: PIN cmd result 0
0x7fd747f3e700 14:01:37.018 [opensc-pkcs11] pkcs15-pin.c:594:sc_pkcs15_pincache_add: called
0x7fd747f3e700 14:01:37.018 [opensc-pkcs11] pkcs15-pin.c:634:sc_pkcs15_pincache_add: PIN(PIN2) cached
```

Tested with custom application and CMD  1E1E0200000C0402FF00000000000004 00000000200001 works as expected.
Ubuntu 16.04
Reader: OmniKey 3821

**Comment by frankmorgner** [comment]
@martinpaljak Could you have a look at this?

**Comment by martinpaljak** [comment]
What is the actual SW response from the reader? And maybe include the CCID level trace, that would have more context than here.

**Comment by metsma** [comment]
Opensc PIN1 failed https://www.dropbox.com/s/7th1futd9z9tidl/PIN1-neg.txt?dl=0
Opensc PIN2 positive https://www.dropbox.com/s/ocsh1k347wdmft0/PIN2-pos.txt?dl=0
Custom application PIN1 positive https://www.dropbox.com/s/buhzvdmnjw7ro1q/PIN1-pos.txt?dl=0

**Comment by frankmorgner** [comment]
negative:
```
Control TxBuffer: 1E 1E 02 00 00 0C 04 02 FF 00 00 00 00 00 00 04 00 00 00 00 20 00 01
 -> 000000 69 13 00 00 00 00 69 00 00 00 00 1E 02 00 00 0C 04 02 FF 00 00 00 00 00 00 00 20 00 01 
 <- 000000 80 02 00 00 00 00 69 00 00 00 63 C2 
Control RxBuffer: 63 C2
```
positive:
```
Control TxBuffer: 1E 1E 02 00 00 0C 04 02 FF 09 04 00 00 00 00 05 00 00 00 00 20 00 01 00
 -> 000000 69 14 00 00 00 00 3F 00 00 00 00 1E 02 00 00 0C 04 02 FF 09 04 00 00 00 00 00 20 00 01 00 
 <- 000000 80 02 00 00 00 00 3F 00 00 00 90 00 
Control RxBuffer: 90 00
```
I think we can ignore LangId (`09 04` vs `00 00`), which leaves the missing Le byte as possible source of the problem (APDU length 5 vs length 4). However, since you said your custom application works with OpenSC's PIN command, that's unlikely.

Looking at a couple of APDUs before PIN verification shows that in the negative case, there are some PIN status requests preceding the verification. In the positive case these requests are missing:

| negative | positive |
| - | - |
| `APDU: 00 A4 02 04 02 DD CE 00` | `APDU: 00 A4 02 00 02 DD CE 00` |
| `APDU: 00 B0 00 00 00` | `APDU: 00 B0 00 00 00` |
| `APDU: 00 B0 01 00 00` | `APDU: 00 B0 01 00 00` |
| `APDU: 00 B0 02 00 00` | `APDU: 00 B0 02 00 00` |
| `APDU: 00 B0 03 00 00` | `APDU: 00 B0 03 00 00` |
| `APDU: 00 B0 04 00 00` | `APDU: 00 B0 04 00 00` |
| `APDU: 00 B0 05 00 00` | `APDU: 00 B0 05 00 00` |
| `APDU: 00 A4 00 00 00` |
| `APDU: 00 A4 02 04 02 00 16 00` |
| `APDU: 00 B2 01 04 10` |
| `APDU: 00 A4 00 00 00` |
| `APDU: 00 A4 02 04 02 00 16 00` |
| `APDU: 00 B2 01 04 10` |
| `Control TxBuffer` | `Control TxBuffer` |

Maybe the extra selection of MF (`00 A4 00 00 00`) breaks the PIN verification.

Please hack your OpenSC source code to
- add an extra Le byte to the PIN command and/or
- omit the PIN status request before the PIN verification

... and check whether that fixes your problem.

**Comment by metsma** [comment]
Tested same command on OSX/Win and it works, strange
1E 1E 02 00 00 0C 04 02 FF 00 00 00 00 00 00 05 00 00 00 00 20 00 01 00

**Comment by martinpaljak** [comment]
That is not a Le byte, the question is where the effective PIN length ("variable length PIN block") is written (which will become the Lc). The byte will be handled as input template for the PIN APDU on CCID layer, and apparently the 0x00 is better than no 0x00.

That behaviour was not documented in CCID spec but seemed to be the de facto implementation of variable length PIN blocks and resulted from empirical testing. Apparently the extra 0x00 (that will become Lc of the resulting command) is necessary, I do not recall the details.

Have a look here: https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1652 and https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1780

Thus the constructed block gets mangled somewhere.

**Comment by metsma** [comment]
Frank where should I look to add the additional Lc byte? Im lost in the opensc code?
Why Linux and OSX/Windows behave differently?

**Comment by frankmorgner** [comment]
Well, regarding the different behavior, that surely has to do with the different interpretation of PC/SC part 10 of those different implementations.

However, OpenSC should not send a case 1 APDU for PIN verification. The mcrd driver calls ISO's `pin_cmd`, which itself [builds a PIN APDU that always sends some data](https://github.com/OpenSC/OpenSC/blob/baa709ff74631336694c609ccfc2b7c32bd3cf53/src/libopensc/iso7816.c#L999) (i.e. case 3 with an LC byte and some data). The ISO driver only uses a case 1 APDU, when [it queries the status of the PIN](https://github.com/OpenSC/OpenSC/blob/baa709ff74631336694c609ccfc2b7c32bd3cf53/src/libopensc/iso7816.c#L1070) (which seems to be happening in your case).

I think you will need to step through the code to see under what circumstances the PIN command in question is used. (Note that the debug message for the PIN query [has changed recently to be less alarming](https://github.com/OpenSC/OpenSC/commit/bc075d66396f870153dde9572c343626c6cf3d1b)).

**Comment by frankmorgner** [comment]
@metsma a complete OpenSC log may also be more interesting than the pcscd trace.

**Comment by metsma** [comment]
OSX PIN1 success: https://www.dropbox.com/s/773cd9nwe2e86ji/OSX-PIN1-success.log?dl=0

**Comment by metsma** [comment]
Linux PIN1 negative: https://www.dropbox.com/s/vd3odgmypft4jlx/opensc-PIN1.log?dl=0
Linux PIN2 success: https://www.dropbox.com/s/d2lqyk6r97z0f5h/opensc-PIN2.log?dl=0

**Comment by metsma** [comment]
PIN1 4-12
PIN2 5-12

**Comment by metsma** [comment]
Same reader works on OSX/Windows and not on Linux

**Comment by dengert** [comment]
Well still look at 424. Also look for update to pcsc and ccid. The system
ccid may be out of date.

**Comment by metsma** [comment]
Seems like master opensc and Ubuntu 17.10 (pcsc 1.8.22, ccid 1.4.27) works.
Ubuntu 17.10 bundled opensc 0.17.0 does not work.

**Comment by metsma** [comment]
master and bundled opensc 0.17.0 on Ubuntu 16.04 (pcsc 1.4.14, ccid 1.4.22) does not work

**Comment by metsma** [comment]
Seems like commit 251a5f9fef8d8110fe6f5029863ea545bbe9635a fixes the problem.
Least git bisect claims so

**Comment by frankmorgner** [comment]
Sounds reasonable, thanks for the update!

Indeed the previous heuristic based on `data->pin1.length_offset` (ignoring the rest of the APDU) looks a bit fishy.

**Comment by metsma** [comment]
I can confirm, cherry picking this patch to 0.17.0 release fixes the problem.
Closing the issue, Thank you
