### ISSUE TITLE
any plans of support openssl-1.1.0 for pkcs11-helper ?

### ISSUE THREAD

**Issue by chipitsine** [OpenSC/OpenSC#1087]
### Expected behaviour

pkcs11-helper should build with openssl-1.1.0

### Actual behaviour

it fails to build

### Steps to reproduce

1. logs of openvpn-build: https://api.travis-ci.org/jobs/249719089/log.txt?deansi=true
2. 
3. 

### Logs

Debug output is essential to identify the problem. You can enable debugging by
editing the file `opensc.conf`:
```
    # A debug level of 3 catches most problems
    # Some sensitive data may be logged, too, (e.g. PIN codes)
    debug = 3;

    # Where to write the debug output (default: `stdout`)
    #debug_file = opensc-debug.log
```

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs. Before pasting here, remove your sensitive data from your log (e.g. PIN
code or certificates).

```
Paste Log output with less than 10 lines here
```

**Comment by chipitsine** [comment]
I meant 1.11 from https://sourceforge.net/projects/opensc/files/pkcs11-helper/
actually, I see 1.22 on github, hmm...

**Comment by frankmorgner** [comment]
@alonbl ?

**Comment by alonbl** [comment]
please discuss pkcs11-helper at [1], it should support openssl-1.1.

[1] https://github.com/opensc/pkcs11-helper/
