### ISSUE TITLE
MyEID  pkcs11-tool --login --test  fail for RSA 2048 

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#1089]
MyEID card version 3.3.3, opensc 0.17.0 - from git:

$ pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "MyEID".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (key_1024) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
  testing key 1 (1536 bits, label=key_1536) with 1 signature mechanism
    RSA-X-509: OK
  testing key 2 (2048 bits, label=key_2048) with 1 signature mechanism
error: PKCS11 function C_Sign failed: rv = CKR_DATA_INVALID (0x20)
Aborting.

additional information - from MyEID reference manual (2.1.4):
Raw RSA operation is not supported on 2048 bit keys when computing a digital signature

There seems to be a problem in outgoing APDU :
first security env. is set: 
00 22 41 B6 0A 80 01 00 81 02 4B 03 84 01 00
(0x80,0x01,0x00 is request for RAW RSA operation and no HASH algorithm)
Then digital signature is requested .. 
00 2A 9E 00 FF  01 FF FF FF FF FF FF FF FF FF FF .....

MyEID reference manual says:
P1=0x9E return digital signature data
P2=0x9A: data field contains data to be signed
I can't explain why opensc sends P2 = 0. Relevant part from src/libopensc/card-myeid.c:

        if (datalen == 256)   {
                apdu.p2 = data[0];
                memcpy(sbuf, data+1, datalen-1);
                apdu.lc = datalen - 1;
                apdu.datalen = datalen - 1;
        }

My tests with  same key and  SHA1-RSA-PKCS return correct result. 
(pkcs11-tool   --sign --slot 0 -m SHA1-RSA-PKCS .....)

**Comment by frankmorgner** [comment]
@hhonkanen already stated that the current implementation has doesn't respect the card's limitations. Thanks for pointing out the details, which hopefully fixes this behavior soon.

You're welcome to have a deeper look and make a pull request...

**Comment by hhonkanen** [comment]
I think that we should notice at higher level that MyEID cannot do RSA-X-509 with a 2048 bit key and maybe return some other error message. The problem is that because it works with 1024 bit keys, the driver lists this mechanism as supported. Anyway, it has been like this for a long time, so nothing is broken in 0.17 regarding this. The code that sets P2 = 0 doens't make sense, but it wouldn't work in any other way either. I think it's ok to leave it as it is in 0.17.

We are planning to implement raw 2K RSA on MyEID, because there has been lots of questions about this and users expect RSA-X-509 to work.

**Comment by frankmorgner** [comment]
On the PKCS#15 layer, the card should correctly initialize `p15card->tokeninfo->supported_algos `, 
 which allows to be more explicit (see comments here https://github.com/OpenSC/OpenSC/issues/508#issuecomment-145305403)

**Comment by popovec** [comment]
Please check pull request #1091, I found a way to use decipher operation for 2048 bit signature.

$ pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "MyEID".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (key_1024) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
  testing key 1 (1536 bits, label=key_1536) with 1 signature mechanism
    RSA-X-509: OK
  testing key 2 (2048 bits, label=key_2048) with 1 signature mechanism
    RSA-X-509: OK
  testing key 3 (512 bits, label=key_512) with 1 signature mechanism
    RSA-X-509: OK
  testing key 4 (768 bits, label=key_768) with 1 signature mechanism
    RSA-X-509: OK
Verify (currently only for RSA)
  testing key 0 (key_1024)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
  testing key 1 (key_1536) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (key_2048) with 1 mechanism
    RSA-X-509: OK
  testing key 3 (key_512) with 1 mechanism
    RSA-X-509: OK
  testing key 4 (key_768) with 1 mechanism
    RSA-X-509: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (key_1024) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 1 (key_1536) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 2 (key_2048) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 3 (key_512) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 4 (key_768) 
    RSA-X-509: OK
    RSA-PKCS: OK
No errors

**Comment by popovec** [comment]
I repeated the test, opensc from github after applying #1091, everything works.
