### ISSUE TITLE
OpenSC-0.17.0.dmg is unsigned

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1111]
### Problem Description

When installing OpenSC-0.17.0.dmg on MacOS Sierra, the OS complains that the DMG is unsigned.

"“OpenSC 0.17.0.pkg” can’t be opened because it is from an unidentified developer."

### Proposed Resolution

Sign the DMGs.

**Comment by frankmorgner** [comment]
See https://github.com/OpenSC/OpenSC/wiki/macOS-Quick-Start#2-install-the-pkg
