### ISSUE TITLE
Open minidriver with Gids-Card

### ISSUE THREAD

**Issue by khanhnd1405** [OpenSC/OpenSC#1125]
### Problem Description

I have problem, please support to help me.

I want to use Gids card on windows XP, i know Open-minidriver support gids card. 
I must enable "ENABLE_ZLIB" to build Gids-card. I need config it where, please?

Thanks so much!

**Comment by frankmorgner** [comment]
excuse me?

**Comment by khanhnd1405** [comment]
Dear,

I want to build Gids-card.c but I don't know enable "Enable_zlib" where? please help me!

**Comment by frankmorgner** [comment]
It's explained here: https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows

Check the CI script to see it in work: https://github.com/OpenSC/OpenSC/blob/master/appveyor.yml

You don't need OpenSC for GIDS on Windows! Windows already has an GIDS minidriver!

**Comment by frankmorgner** [comment]
Windows XP doesn't have a built-in minidriver. So I understand that OpenSC may be handy here.

However, please note that we are about to drop Windows XP support for OpenSC, see https://github.com/OpenSC/OpenSC/pull/1126.

**Comment by khanhnd1405** [comment]
Dear,

If i want to use windows xp, i can use minidriver of opensc communication to card-gids?
Opensc support windows xp? Pls tell to help me!

**Comment by khanhnd1405** [comment]
Dear frankmorgner,

I need build card-gids on opensc, do i need openssl, openpace and zlib library?

**Comment by frankmorgner** [comment]
You'll need to check the source code to know for sure.

**Comment by khanhnd1405** [comment]
I saw zlib-dll folder in config file. I find it where? If possible, pls help me!

**Comment by khanhnd1405** [comment]
Dear Pro,

I want registry my minidriver in windows. When i use to issue certificate to smartcard. Minidriver can't know my smartcard. Do I need registry to microsoft to get certificated before use minidriver in windows operating system? Please help me!
