### ISSUE TITLE
New CardOS 5.3 not working

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#1134]
Hello,

Today I just got a new cardos smartcard, this smartcard is not working with opensc unfortunately.

```
$ ./src/tools/opensc-tool --atr
Using reader with a card: Alcor Micro AU9560 00 00
3b:d2:18:00:81:31:fe:58:c9:02:17
```

Adding that ATR to the list of the cardos 5.0 smartcard in the code (git HEAD) is not completely helping:

```
$ ./src/tools/pkcs11-tool -L 
Available slots:
Slot 0 (0x0): Alcor Micro AU9560 00 00
C_GetTokenInfo() failed: rv = CKR_TOKEN_NOT_PRESENT
```

```
$ ./src/tools/cardos-tool -i
Using reader with a card: Alcor Micro AU9560 00 00
3b:d2:18:00:81:31:fe:58:c9:02:17
Info : CardOS DI V5.3, 2015
Serial number: XX XX XX XX XX XX XX XX
OS Version: 201.2 (unknown Version)
Current life cycle: 16 (operational)
Security Status of current DF:
Free memory : 678
ATR Status: 0x0 ROM-ATR
Packages installed:
XXX
Ram size: 7, Eeprom size: 51, cpu type: 78, chip config: 63, chip manufacturer: 5
Free eeprom memory: 22685
Current Maximum Data Field Length: 640
Complete chip production data:
XXXX
System keys: PackageLoadKey (version 0x00, retries 10)
System keys: StartKey (version 0xff, retries 10)
Path to current DF:
```

**Comment by frankmorgner** [comment]
Support for CardOS 5.3 is incomplete, see https://github.com/OpenSC/OpenSC/search?q=cardos+5.3&type=Issues&utf8=%E2%9C%93 for details.

@Jakuje do you want to add something?

**Comment by bigon** [comment]
I previously owned a cardos 5.0 smartcard and I was able to use it to login to some sites using firefox with opensc 0.17.0. I was hoping that it would be the same with the 5.3 version of the smartcard

**Comment by Jakuje** [comment]
> $ ./src/tools/opensc-tool --atr
> 3b:d2:18:00:81:31:fe:58:c9:02:17

The ATR is different from the CardOS 5.3 cards I have and which are [recognized in OpenSC](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-cardos.c#L62) at the moment:

Unfortunately there is no list available that would say which card is which under this ATR. Adding ATR to the recognized cards is the first step. If the card is already provisioned, there should be no problem with using it. If there is, please, provide the debug logs -- there might be something obvious.

If the card is not provisioned/initialized yet, the `opensc-tool` does not work at this moment with CardOS 5.x. You are not the only one, requesting this functionality (see issue #1119). Ideally, I would like to have a look into that in future, but currently I have no cards that I would be able to try with nor any documentation where to start.

**Comment by bigon** [comment]
The card is already provisioned using a Windows Machine.

I've added the ATR to the list of supported ones, you'll find below the logs when doing `./src/tools/pkcs11-tool -L`:

[opensc-debug.log.txt](https://github.com/OpenSC/OpenSC/files/1237097/opensc-debug.log.txt)

**Comment by frankmorgner** [comment]
Sorry, I don't have special insights to share. You may have noticed that for `sm-eac.c` I even preferred OpenSSL's awkward ASN.1 parser over OpenSC's parser.

I'd suggest trying to use an `SC_ASN1_CHOICE`, just like `pkcs15-skey.c` is doing the decoding...

**Comment by Jakuje** [comment]
Yes, you are right. Thanks for the pointer. It is CHOICE. Even though I was digging in ASN.1 a lot recently, I somehow assumed it has some specific encoding, but it is just the encoding of the "chosen" type.

I came up with the following patch which allows me to parse the `TokenInfo` structure provided by the debug log above. I am not using the parsed OIDs in any place at the moment:
https://github.com/OpenSC/OpenSC/compare/master...Jakuje:cardos-tokeninfo-ecc

@bigon can you verify that it solves the problem and you are able to progress further with your CardOS 5 card? Note, that the operation with ECC keys will most probably not work, since only RSA signatures are implemented at this time in CardOS driver.

**Comment by bigon** [comment]
OK it seems to work, with the patch I now get:

```
$ ./src/tools/pkcs11-tool -L 
Available slots:
Slot 0 (0x0): Alcor Micro AU9560 00 00
  token label        : PIN (Atos PKI + OTP Card  V5.3(0
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0205723400170D37
  pin min/max        : 6/16
Slot 1 (0x1): Alcor Micro AU9560 00 00
  token label        : Extra PIN #1 (Atos PKI + OTP Car
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0205723400170D37
  pin min/max        : 4/16
Slot 2 (0x2): Alcor Micro AU9560 00 00
  token label        : Extra PIN #0 (Atos PKI + OTP Car
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0205723400170D37
  pin min/max        : 4/16
```

And I can also login on a site using firefox \o/

**Comment by bigon** [comment]
As a minor issue, `cardos-tools -i` still shows "unknown Version"

```
$ src/tools/cardos-tool -i
Using reader with a card: Alcor Micro AU9560 00 00
3b:d2:18:00:81:31:fe:58:c9:02:17
Info : CardOS DI V5.3, 2015
Serial number: X X X
OS Version: 201.2 (unknown Version)
Current life cycle: 16 (operational)
Security Status of current DF:
Free memory : 410
ATR Status: 0x0 ROM-ATR
Packages installed:
E1 0B 53 06 11 04 09 01 C9 02 8F 01 01 E1 0B 53 ..S............S
06 11 04 06 01 C9 02 8F 01 01                   ..........
Ram size: 7, Eeprom size: 51, cpu type: 78, chip config: 63, chip manufacturer: 5
Free eeprom memory: 22685
Current Maximum Data Field Length: 640
Complete chip production data:
XXX
System keys: PackageLoadKey (version 0x00, retries 10)
System keys: StartKey (version 0xff, retries 10)
Path to current DF:
50 15 P.
```

**Comment by Jakuje** [comment]
Thanks for testing. I added the conversion in the `cardos-tool` in the #1136. It is just a minor tweak and I hope there are no other versions that would refer to V5.3 (mine is `OS Version: 201.3 (that's CardOS V5.3)`).

**Comment by arbabilo** [comment]
Excellent work Jakuje, works fine for me with crados 5.3
