### ISSUE TITLE
Firefox ask for the pin in random order when a card has multiple slot

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#1135]
Hello,

With opensc 0.17.0 (with patches from #1134) and a cardos 5.3 smartcard, firefox is asking me for the pin code in a random order.

I would expect opensc to first ask me to unlock the slot one and try to login with that key/certificate and only fallback to the other slots if it fails.

My (cardos) smartcard has the following slot:

```
$ ./src/tools/pkcs11-tool -L
Available slots:
Slot 0 (0x0): Alcor Micro AU9560 00 00
  token label        : PIN (Atos PKI + OTP Card  V5.3(0
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : XXX
  pin min/max        : 6/16
Slot 1 (0x1): Alcor Micro AU9560 00 00
  token label        : Extra PIN #1 (Atos PKI + OTP Car
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : XXX
  pin min/max        : 4/16
Slot 2 (0x2): Alcor Micro AU9560 00 00
  token label        : Extra PIN #0 (Atos PKI + OTP Car
  token manufacturer : www.atos.net/cardos
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : XXX
  pin min/max        : 4/16
```

Asking the pin in a random order could confuse the user and lead him to lock the card if the wrong code is entered to unlock the wrong slot

**Comment by Jakuje** [comment]
AFAIK, this was why the `onepin` library should be used in Firefox.

**Comment by bigon** [comment]
OK, you are probably correct here, using the "onepin" variant is fixing my original problem.

Making it more clear in the doc what is onepin and what it should be used for might be a good idea, it was definitely not clear to me and google is pointing me to old bugreports and mailinglist messages

**Comment by Jakuje** [comment]
I never had a card with multiple pins so I didn't notice the difference so far (except in the reading of the code). Feel free to propose a solution where to write this (manual page, readme, ...), which wiki to update (well ... you can do that already ...) where would you search for this information.

**Comment by frankmorgner** [comment]
This is a Firefox specific problem, which never got fixed by Mozilla. The onepin module is a workaround for Firefox's shortcoming.

Indeed, the wiki only has sparse information for actual users, such as a list of supported applications and how to use them. I actually planned to do this for the current release, but I never had enough time. Feel free to create a wiki page yourself for Firefox (it's a wiki!).

**Comment by bigon** [comment]
If there a bug logged on the firefox bugzilla?

**Comment by Jakuje** [comment]
One of the proposed solutions is described in this bug [1]. This was brought up last year on mailing list [2], but in the end, we did not come to any solution with Mozilla.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=511652
[2] https://sourceforge.net/p/opensc/mailman/message/35407621/
