### ISSUE TITLE
SO-PIN changeable even if not hexadecimal

### ISSUE THREAD

**Issue by techge** [OpenSC/OpenSC#1152]
### Problem Description

A [user of the Nitrokey HSM](https://support.nitrokey.com/t/nitrokey-hsm-so-pin-conversion/629) tried to change the SO-PIN but used a unicode passphrase instead of a hexadecimal PIN. The command the user used was

`pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --login --login-type so --so-pin 3537363231383830 --change-pin --new-pin ‘JcobBr{y#)bE)W#b’`

The PIN nevertheless got changed "successfully". But as there are only hexadecimal PINs allowed, the passphrase is consequently not useable. Now the user does not know what the SO-PIN actually was changed into.

### Proposed Resolution
Please do a check an proposed SO-PIN before changing.

### Further Notes ###
It seems to me, that the function [change_pin()](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L1479) of pcks11-tool is used for user PIN and SO-PIN as well. That is may the reason why the PIN got still changed although the proposed new PIN is not in hexadecimal.

It is of course vital for the user to get to know what SO-PIN now is active on his device. So maybe you can reconstruct his changed SO-PIN on basis of the code of the current release. That would be great!

Trying to just convert the passphrase into hexadecimal I get 
‘JcobBr{y#)bE)W#b’ -> E280984A636F6242727B792329624529572362E28099
taking the first 16 hexadecimal characters would be E280984A636F6242
Could this be the SO-PIN now?

Or does the tool use actually just the inner part: JcobBr{y#)bE)W#b  ?

Kind regards
techge

**Comment by CardContact** [comment]
What version of OpenSC ? Might be related to #674.

**Comment by techge** [comment]
Well, I saw this issue as well, but I thought that it wasn't hexadecimal anyway, but I will ask the user.

**Comment by frankmorgner** [comment]
Sounds like you're requesting a format check in [`_validate_pin()`](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-pin.c#L257). This could indeed be useful... But in terms of PIN formatting, we currently don't have a way to say how the PIN input needs to look like. We're only storing how OpenSC is formatting them (and the [available encodings](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/opensc.h#L353-L355) don't even include Hex-ASCII).

https://github.com/OpenSC/OpenSC/commit/ae359ba1803ec9c529f69b33035617ae5d928a53 solves this issue by adding card driver specific checking. This is something your card driver (which one?) could do as well without extensive modifications of the rest of the code.

**Comment by techge** [comment]
@frankmorgner 
> ae359ba solves this issue by adding card driver specific checking. This is something your card driver (which one?) could do as well without extensive modifications of the rest of the code.
The Nitroy HSM is actually based on CardContactHSM, so the mentioned commit should implement exactly something like this for this card? Or did I understood you wrong?

@dengert 
Thank you a lot for your suggestions. Unfortunately the user is not responding right now (the issue was unanswered for some time by me, so no blame on him 😞 ). We will try based on your tips eventually.

**Comment by frankmorgner** [comment]
thanks for the update!

The issue itself should be resolved by https://github.com/OpenSC/OpenSC/issues/674 then.
