### ISSUE TITLE
Minimal example for one id card

### ISSUE THREAD

**Issue by adrianbrink** [OpenSC/OpenSC#1161]
I have a German or an Estonian ID card available and I would like to use them to sign a random string of bytes. 

Are there good examples on how to get started? I would greatly appreciate it if there was an example of how to get from pluging in the card-reader to being able to interact with the card (even just version number).

Any help would be appreciated.

**Comment by Jakuje** [comment]
Some time ago, I put together a gist, describing how to use OpenSC command-line tools to sign and verify the arbitrary data:
https://gist.github.com/Jakuje/5a993d2b2d8a9cac35203599e49e6831

Creating this as a wiki of OpenSC would probably make sense, but there is already a lot of pages, poorly linked together so this would probably need some care.

For more advanced usages, the manual pages of `pkcs11-tool` is a probably a good place to start.

**Comment by frankmorgner** [comment]
You should say, what you're trying to do with your cards (with minimal effort)...

**Comment by adrianbrink** [comment]
Use a card to sign an Ethereum transaction. 

I would like to write a binary that uses OpenSC as a library to allow a user to use an ID card to sign an Ethereum transaction.

**Comment by frankmorgner** [comment]
Via minidriver there is https://github.com/pauldotknopf/WindowsSDK7-Samples/tree/master/security/cryptoapi/CertSign

Via PKCS#11 there is https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c

**Comment by adrianbrink** [comment]
PKCS#11 is completely cross-platform, correct?

Alright, I'll try and figure out how to compile and call this C code from rust.

**Comment by frankmorgner** [comment]
@adrianbrink correct, but PKCS#11 also requires more user interaction to set up the correct configuration.

**Comment by adrianbrink** [comment]
Can the application author handle all the extra interaction or is it something that the end-user has to do?

**Comment by frankmorgner** [comment]
Theoretically, yes. But that implies that your application/author forces a specific middleware (and card).

**Comment by adrianbrink** [comment]
ah okay, thanks @frankmorgner
