### ISSUE TITLE
CAC email certificate issue

### ISSUE THREAD

**Issue by thukk** [OpenSC/OpenSC#1164]
### Problem Description

Using a Gemalto CAC.  Tried using opensc with Firefox for webmail in RHEL 7.4.  Opensc does not see the email certificate.  It sees the other 2 certificates.  Using coolkey, I am able to use the email certificate and log in to webmail.

### Proposed Resolution

opensc should read all 3 certificates from CAC.

### Steps to reproduce

Load opensc to Firefox and use CAC.  2 or 3 certificates are recognized.

**Comment by Jakuje** [comment]
If you are using OpenSC with RHEL7.4, please, open a ticket with your Red Hat support. They will be able to help you and investigate where the problem is.
Unfortunately, from this report without any logs, it is hard to say what is going on there.

**Comment by frankmorgner** [comment]
@thukk did you fix this issue? How?

**Comment by thukk** [comment]
@frankmorgner 

I haven't been able to fix it.  I just use coolkey for Firefox and openSC for everything else.

With coolkey, I can see the Email certificate.  With OpenSC, I only see Digital Signature and PIV Authentication.  

I dont think it has anything to do with RHEL 7.4 specifically, I am just loading opensc-pkcs11.so library into FireFox...

**Comment by Jakuje** [comment]
The thing is that OpenSC version in RHEL7.4 is older than master, that already contains several fixes related to CAC driver and that might already address your issue.

The debug logs `OPENSC_DEBUG=9 pkcs11-tool` should give us some idea what could go wrong. It would be nice to see where is the issue and have it fixed. All the cards I have access to seems to list all the certificates properly.

**Comment by thukk** [comment]
I think trying the newer version would be the prudent step to see if the issue might already be fixed.  I removed opensc via yum and an working through installing opensc 0.17.0 from source.

When building, I did run into an error that winscard.h is missing.  Working through that right now...once I get it installed, I will report back with my findings.

**Comment by dengert** [comment]
The issue may have to do with key usage. With the PIV NIST defines the usage for the 4 certificates:

- X.509 Certificate for PIV Authentication - Used to authenticate to hosts and network services  
- X.509 Certificate for Digital Signature - Used to sign documents and e-mail not authentication..
- X.509 Certificate for Key Management - Used for encryption of documents and e-mail
- X.509 Certificate for Card Authentication - Used for the card to authenticate itself, not the user. 

From your description it sounds like the webmail is expectioning to use the X.509 Certificate for Digital Signature. for authenticate as you are using the PIV terms "Digital Signature and PIV Authentication."

OpenSC has drivers for both PIV and CAC. If your card is a dual PIV/CAC card with the default AID of  PIV, the OpenSC PIV driver will be selected. You could try modifying the opensc.conf file to not use the PIV driver, and the CAC driver should be selected. 

Before you modify opensc.conf, 
What do `opensc-tool -a` and  `pkcs11-tool -O` show?

**Comment by thukk** [comment]
using opensc 0.16

# opensc-tool -a
Using reader with a card: SCM Microsystems Inc. SCR 3310 [CCID Interface] 00 00
3b:7d:96:00:00:80:31:80:65:b0:83:11:17:d6:83:00:90:00
# pkcs11-tool -O
Using slot 0 with a present token (0x0)
Public Key Object; RSA 2048 bits
  label:      PIV AUTH pubkey
  ID:         01
  Usage:      encrypt, verify, wrap
Certificate Object; type = X.509 cert
  label:      Certificate for PIV Authentication
  ID:         01
Public Key Object; RSA 2048 bits
  label:      SIGN pubkey
  ID:         02
  Usage:      encrypt, verify
Certificate Object; type = X.509 cert
  label:      Certificate for Digital Signature
  ID:         02
Public Key Object; RSA 2048 bits
  label:      KEY MAN pubkey
  ID:         03
  Usage:      encrypt, wrap
Certificate Object; type = X.509 cert
  label:      Certificate for Key Management
  ID:         03
Data object 34356864
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 34356960
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 34352480
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 34352576
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 34352960
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 34353056
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 34353152
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 34353248
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>

**Comment by dengert** [comment]
OK that is using the PIC driver in OpenSC. There is also a CAC driver.
Run `opensc-tool --list-drivers` to see the list. 

You can  modify the list of drivers to load. See the "Whitelist of card drivers to load at start-up"
and add just the CAC driver.  
You could also use the  force_card_driver =

**Comment by thukk** [comment]
I have opensc 0.16 installed via yum, so I am editing /etc/opensc-x86_64.conf.

I changed like 136 to card_drivers = cac, internal;
I also changed line 155 to force_card_driver = cac;

no change...

**Comment by thukk** [comment]
I was finally able to get back around to this.  If I set force_card_driver = cac', I am given the chance to open webmail using my email certificate.  If I do not force it to load the cac drivers, my CAC is loaded as PIV-II and I am not presented with my email certificate.  

I don't know if it is a bug per se...opensc is just loading what driver it thinks it needs...

**Comment by dengert** [comment]
Some CAC cards are dual mode, i.e. they have two card applications. NIST defined PIV with the intent to phase out CAC. But that process is moving very slow. 

OpenSC can not support two  card applications at the same time in the same process. 
See  https://github.com/OpenSC/OpenSC/issues/962

But I would be interested in why webmail does not see the e-mail certificate. It could be it is only accessible via the CAC. 

Getting a debug log and a SPY trace while running webmail with the PIV driver would show if it can not find the certificate or what what else might be going on See
https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

You can also use the environment variable OPENSC_DRIVER=  to force a specific driver.

**Comment by thukk** [comment]
using libcoolkey, all 3 certificates show as valid options.  I tried forcing coolkey, but the token did not show up at all in FireFox.

The problem with forcing a specific driver is if I have alternate tokens, I may not want them to use the cac driver...

**Comment by dengert** [comment]
Just to point out how complicated Dual Interface cards can be, Google for this:
Technical Bulletin: CAC Data Model Change in 144K Dual Interface Cards

Then see this from 2009:
http://www.cac.mil/Portals/53/Documents/ref5-Technical_Bulletin_CAC_2_6_2b_Applet_Structure_June_2009.pdf

This says the PIV interface (PIV AID) should have access to the  CAC sign and encrypt carts/keys
for at least 2 card types. It sounds like your card may not have access to these. This may be that your card does not comply with the above Bulletin for some reason. You may have to research who issued your card, what type card you have and what are the policies for your card.  

 Also see: https://github.com/OpenSC/OpenSC/issues/962 That is trying to address some of these issues.

And as you and https://github.com/OpenSC/OpenSC/issues/962 point out there is not a good way with current OpenSC to force the use of one driver over another. 

But there are a few things ways today you could do:

- Use the environment variable `OPENSC_DRIVER=` to force the use of a specific driver for this process. for example when starting FireFox or your mail program.  

- Edit the system `opensc.conf` and change `drivers =` to list the driver(s) you want to use. 

- Use the environment variable `OPENSC_CONF=` to point to a modified `opensc.conf` that lists the driver(s) to use for the current process.

**Comment by Jakuje** [comment]
@thukk is there anything more to resolve or discuss in this issue?

**Comment by thukk** [comment]
No, I worked with RH to get my CAC working with the newer versions of opensc available in the official repo.  There was also an issue with unlocking the machine if coolkey was also installed (which prompted my initial ticket to RH when 7.5 came out)

opensc-0.16.0-8, cac explicitly defined in /etc/opensc-x86_64.conf works with my CAC.
