### ISSUE TITLE
API access to smart card

### ISSUE THREAD

**Issue by adrianbrink** [OpenSC/OpenSC#1165]
I would like to get access to a smartcard reader programmatically from Rust.

How do I use OpenSC as a library or what libraries are out there?

Also, am I correct in the assumption that with OpenSC I don't care about the specific reader or smart card. I just have a single API that interacts with every supported card reader?

**Comment by dengert** [comment]
https://pcsclite.alioth.debian.org/pcsclite.html
is probably where you want to start. 

OpenSC supports selected smart cards and It uses PCSC or OpenCT to access the readers.  
So it only works with smartcards it understands. 

For a history of PCSC see
https://en.wikipedia.org/wiki/PC/SC

OpenSC can also use OpenCT:
https://github.com/OpenSC/openct/wiki

At a lower level. If the reader is USB, and most are these days, also see:
https://en.wikipedia.org/wiki/CCID_(protocol)

You may want to look at EMV too.

**Comment by frankmorgner** [comment]
Use the standardized C-APIs (PKCS#11, CryptoAPI, TokenD, CryptoTokenKit) for card access via OpenSC. All those APIs are usable in Rust out of the box ("Foreign Function Interface").
