### ISSUE TITLE
Failure to init Muscle Card

### ISSUE THREAD

**Issue by klali** [OpenSC/OpenSC#117]
pkcs15-init -C fails on a Muscle card with this error:

  Failed to create PKCS #15 meta structure: File not found

the relevant part of a verbose log seems to be:

0x7f0112a5f700 12:47:38.382 [pkcs15-init] card-muscle.c:371:select_item: returning with: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] card-muscle.c:440:muscle_select_file: returning with: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] card.c:681:sc_select_file: 'SELECT' error: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] card.c:402:sc_unlock: called
0x7f0112a5f700 12:47:38.382 [pkcs15-init] pkcs15-pin.c:372:sc_pkcs15_verify_pin: returning with: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] pkcs15-lib.c:3302:sc_pkcs15init_verify_secret: Cannot validate pkcs15 PIN: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] pkcs15-lib.c:3383:sc_pkcs15init_authenticate: returning with: -1201 (File not found)
0x7f0112a5f700 12:47:38.382 [pkcs15-init] pkcs15-lib.c:826:sc_pkcs15init_add_app: Create 'DIR' error: -1201 (File not found)

With the patch from https://github.com/joelhockey/OpenSC/commit/c010dc798bc2a2ab13c21d963dce5d126812b81f it works.
This seems to be due to the fact that the pin_obj is created as a virtual object in sc_pkcs15init_add_app() while then looked for directly with sc_select_file() in sc_pkcs15_verify_pin().

**Comment by frankmorgner** [comment]
You can use OpenSCDP to initialize the applet, see http://www.openscdp.org/scripts/musclecard/. When initialized, the card should be readable via OpenSC.

**Comment by frankmorgner** [comment]
joelhockey@c010dc7 does not work together with https://github.com/martinpaljak/MuscleApplet/commit/d005f36209bdd7020bac0d783b228243126fd2f8. Obviously @martinpaljak introduced a bug in https://github.com/martinpaljak/MuscleApplet/commit/d0b4864db27590e6f7c2a81a33e70bc97f4079b6 where the private pins object is never initialized.

Does anyone know what the last working version of the muscle applet was?

**Comment by frankmorgner** [comment]
@klali how can this be reproduced, i.e. where do you got the applet from?

**Comment by klali** [comment]
Not sure where I got it, haven't looked at muscle at all for close to 2 years.

**Comment by frankmorgner** [comment]
@mostafabarmshory, @nelenkov do you know where to get the applet?

**Comment by mostafabarmshory** [comment]
@frankmorgner

To be hones with you, I forget.

**Comment by frankmorgner** [comment]
closing this issue as "won't fix". Workaround has been suggested above https://github.com/OpenSC/OpenSC/issues/117#issuecomment-125914554
