### ISSUE TITLE
macOS: engine_pkcs11 fails to prompt & receive PIN

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1174]
### Problem Description

MacOS 10.12.6 Sierra, Xcode-9.0.1. 

```
$ echo bc09ceb7b67e28ffb7c7ef146091d1c5eeb1d66d6fc5810e4173478ec044a371 | xxd -r -p -c 200 | openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20pubkey;type=public" -pkeyopt rsa_padding_mode:oaep -out /tmp/derive.58072.key.enc
engine "pkcs11" set.
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private" -pkeyopt rsa_padding_mode:oaep -in /tmp/derive.58072.key.enc | xxd -p -c 200
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri the Great:
UI_process failed
No PIN code was entered
Login to token failed, returning NULL...
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140736170533896:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:886:
140736170533896:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
Error initializing context
```

UI process is failing.

### Proposed Resolution

Downgrade to before the UI PR merge. Probably limit your UI improvements to Windows.

### Steps to reproduce

See above.

This is what the code outputs when I revert your 391b32c and 6a4e120.
```
$ echo bc09ceb7b67e28ffb7c7ef146091d1c5eeb1d66d6fc5810e4173478ec044a371 | xxd -r -p -c 200 | openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20pubkey;type=public" -pkeyopt rsa_padding_mode:oaep -out /tmp/derive.58072.key.enc
engine "pkcs11" set.
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private" -pkeyopt rsa_padding_mode:oaep -in /tmp/derive.58072.key.enc | xxd -p -c 200
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri the Great:
bc09ceb7b67e28ffb7c7ef146091d1c5eeb1d66d6fc5810e4173478ec044a371
$
```

**Comment by frankmorgner** [comment]
I think `UI_process` failed in [engine_pkcs11](https://github.com/OpenSC/engine_pkcs11/blob/1f5bae04a1bfbf9f14d83870f466d279cbfa7778/src/engine_pkcs11.c#L146). May be, pkcs11_engine mistakes the [forked process that sends the notification](https://github.com/OpenSC/OpenSC/blob/master/src/ui/notify.c#L304-L313) with *some process* that should capture the PIN. 

This may be a bug in pkcs11_engine. Please debug pkcs11_engine (or OpenSSL itself) to investigate this problem. It's unfortunate that you hadn't tested this in the 10 weeks #1126 was up for review.

You can disable notifications by passing `--disable-notify` to `./configure`.

**Comment by mouse07410** [comment]
>  It's unfortunate that you hadn't tested this in the 10 weeks #1126 was up for review.

Like we all, I've been busy with other things, including much simpler #1169 that's waiting to be merged.

> This may be a bug in pkcs11_engine. Please debug pkcs11_engine (or OpenSSL itself) to investigate this problem.

Are you implying that this OpenSC change is an OpenSSL bug???

I'll ask @mtrojnar help in debugging pkcs11_engine. *Though I really wonder who needs this elephantine feature, and why the old "normal" way is not good enough.*

**Comment by erick-orozco** [comment]
I was facing the same issue in Windows, setting the pin-value in the pkcs11 uri worked for me:

openssl -key "pkcs11:id=myID;**pin-value:xxxxx**";
