### ISSUE TITLE
Crash in OpenSC with Estonian smart card devices

### ISSUE THREAD

**Issue by marco-c** [OpenSC/OpenSC#1176]
We have several reports of crashes with older versions of OpenSC, and we are considering blocklisting it in https://bugzilla.mozilla.org/show_bug.cgi?id=1407337.

I'm not sure how to get OpenSC to be injected, so I can't verify that the blocklist patch is working and is safe (that is, it doesn't cause other problems). Could you help?

**Comment by frankmorgner** [comment]
See https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

**Comment by dengert** [comment]
As a member of the OpenSC team, I have been involved in using smartcards with Mozilla NSS for years. From 2010 to 2015 as deengert@anl.gov and after I retired as deengert@gmail.com. Most of the activity was with making sure OpenSC worked with NSS for FireFox and Thunderbird so user could use their U.S gov issued PIV cards. 

Since I retired I do not have a good way to test OpenSC with Firefox, but have done work with Thunderbird signed and encrypted email. 

Sorry to hear that you are having problems with older versions of OpenSC, with newer versions of FireFox.   

On what OS have you seen these crashes: Windows, MacOS and/or Linux?

Are the crashes when loading the module, or when it is used? 

A PKCS\#11 trace would be very helpful, preferably using the OpenSC PKCS\#11_SPY:
 https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

With you blacklist, can you detect the version and tell users to use a newer version?

Let us know how we could reproduce the problems you are seeing.

**Comment by marco-c** [comment]
Unfortunately we aren't able to reproduce the crash, we are only receiving crash reports that happen in the DLL: https://crash-stats.mozilla.com/search/?signature=~opensc&date=%3E%3D2017-10-11T15%3A47%3A00.000Z&date=%3C2017-10-18T15%3A47%3A00.000Z&_sort=-date&_facets=signature&_facets=version&_facets=cpu_arch&_facets=platform&_facets=platform_version&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature. The most affected OSes are Windows 7 and Windows 10.

An example crash report: https://crash-stats.mozilla.com/report/index/04f1523c-7845-4ed1-9a94-a39e80171018.

We have noticed it only happens on OpenSC <= 0.15.0.0, so we are only considering blocking those versions, but we have no way to tell the user to update.

I can try contacting some users to ask them more details and to see if they are willing to share crash dumps with you.
In the meantime, if you want to have symbolicated stack traces, you could upload debugging symbols on Socorro (our crash reporting system). You can send them to me and I can upload them; and then for the future you could create an account on crash-stats.mozilla.com and upload them yourself (see https://developer.mozilla.org/en-US/docs/Uploading_symbols_to_Mozillas_symbol_server#New_Upload_System, there's also an API to do it automatically).

**Comment by marco-c** [comment]
> See https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

If you follow these steps, opensc-pkcs11.dll is injected, but not onepin-opensc-pkcs11.dll.

**Comment by dengert** [comment]
@frankmorgner I notice in the https://crash-stats.mozilla.com/report/index/04f1523c-7845-4ed1-9a94-a39e80171018  NSS is calling secmod_HandleWaitForSlotEvent. I know we have had some issues with C_WaitForSlot. https://github.com/OpenSC/OpenSC/issues/629 and https://github.com/OpenSC/OpenSC/issues/943 but it could be that there is something else going on when a card is inserted or removed that caused the problem. 

Personally I don't see a problem in blacking listing those versions.  On Windows OpenSC does not make changes to previous versions. To get a fix the user has to download the latest version or nightly build from https://github.com/OpenSC/OpenSC/wiki or compile it from source. 

So IMHO, I would recommend trying the latest version anyway. Other OpenSC developers may have a different option.

**Comment by frankmorgner** [comment]
@marco-c if you know the exact version of OpenSC in question, I can generate the pdb files. But I'm afraid I won't go through the registering and upload process that you linked to.

onepin-opensc-pkcs11.dll can be found in the same directory as opensc-pkcs11.dll. If you block one DLL, you should block the other too, because it most likely contains the same bug.

I'm not so sure whether one of the issues you linked to, @dengert, can cause a crash. But since version 0.15.0 we added a lot of fixes that certainly could cause such a problem. And, indeed, since we're not making fixes of older releases, users should only use the latest version (0.17.0).

**Comment by dengert** [comment]
Do any of your bug reports indicate what type type of smart card or reader was being used? That would also help.  Each has its own driver. 

Are all your bug reports for the onepin-opensc-pkcs11.dll  Are there any for opensc-pkcs11.dll? That could help narrow down what card or driver is being used.

**Comment by marco-c** [comment]
> @marco-c if you know the exact version of OpenSC in question, I can generate the pdb files.

The version with the biggest number of crash reports (625 in the past two weeks) is 0.15.0.0.

> But I'm afraid I won't go through the registering and upload process that you linked to.

No worries, I can upload them myself. Just out of curiosity, is there anything we can do to make uploading symbols easier?

> Are all your bug reports for the onepin-opensc-pkcs11.dll Are there any for opensc-pkcs11.dll? That could help narrow down what card or driver is being used.

There are only four reports with opensc-pkcs11.dll, so they are probably related to other crashes.

**Comment by dengert** [comment]
@frankmorgner @martinpaljak @viktorTarasov 

https://bugzilla.mozilla.org/show_bug.cgi?id=1407337#c29
Says: 
btw, I spoke with a Firefox user who hit this openpin-opensc-pkcs11.dll crash.
He didn't install the OpenSC software himself. The old DLL version (0.15.0) was
packaged in the Estonian government's eID smartcard software.

So this may be a bigger problem, and maybe related to a specific card.

**Comment by frankmorgner** [comment]
@marco-c x86 debug files are available at https://ci.appveyor.com/project/frankmorgner/opensc/build/job/2jt4fyitumfj39g9/artifacts, 64 bit files are available at https://ci.appveyor.com/project/frankmorgner/opensc/build/job/4bbxveq9xgug29ts/artifacts

**Comment by frankmorgner** [comment]
@marco-c, where can I find the backtrace based on the debug files, which causes the problems?

**Comment by marco-c** [comment]
@frankmorgner could you send me symbols for version 0.17.0.1265? Note that I can't access the artifacts on appveyor.

**Comment by marco-c** [comment]
Either 0.17.0.1265 or 0.17.0.1268. We have noticed the crash (not sure if it's the same as the one in 0.15) is still occuring with these versions.

More than 40% of the crashes (in total around 7000 per week) are happening to Estonian users.

**Comment by dengert** [comment]
With 7000 a week crashes a week, and AFAIK OpenSC is distributed by the Estonian government with their ID cards. How do we (OpenSC and Mozilla) get the Estonian government involved? 

Why are older versions of OpenSC crashing with newer versions of FireFox? What changed in FireFox?

Have newer Estonian ID cards been issued lately? But the distributed OpenSC is still the older version?

Has Mozilla changed how it calls PKCS\#11 in recent versions? 

Can anyone get the Estonian government agency that distributes the cards and OpenSC involved?

**PKCS\#11 spy traces would be very helpful as well as opensc-debug traces. Does anyone have access  
to a failing card to get these? Can Mozilla get in touch with any of the users?**
 
**With 7000 failures a week, I would suspect that the users are living with the failure. Maybe it only happens when FireFox is closed or the use pulls out the card. Situations the user does not care about.** 
Have any users reported the problem to anyone? (Mozilla, OpenSC or Estonian government)

OpenSC supports many smart cards, and if these problems are specific to a subset of cards, turning off any use of OpenSC via FireFox will impact a lot of other users who are not having problems. 

**Where are the other 60% of failures coming from?**  Can we pin down the failures to a subset of cards?

Telling use to update OpenSC is reasonable, but you comment that you are seeing failures with 0.17.0 is alarming. If you turn off all versions of OpenSC with FireFox without knowing what the problem is is just going to get a lot of users ticked off.

**Comment by marco-c** [comment]
We can try contacting some users to see if they are willing to share more information.

Here are some comments:
> Pärast sertifikaatide uuendamist ID-kaardi lugejasse sisestamisel Firefox koheselt crashib
> Browser crashes every time I use smart card device.
> Closed at starting - "Not secure"
> Ei lase allkirjastada,selgus ,et määratud maksetes vanad andmed.
> Ei saa maksta pangakaardiga.
> ID card in computer causes crash
> Peale ID-Kaardi sertifikaadi uuendamist, ei lase Firefoxi avada, kui id-kaart on lugejas.
> Probably weakness of Estonian ID card extantion soft.
> This happens alredy meny times when i insert a estonian id-card to the card reader
> When a ID smart card is inserted in the card reader FireFox craches
> ei saa kasutada uuendatud id kaarti, teatab mingist veast
> sulgub ID kaardiga
> using opensc-pkcs11.so as a module file name to security device mannager.

We are not considering blocking the new version of OpenSC. We blocked the old version assuming that it was the only affected one.

Most people crashing have addons from https://github.com/open-eid ("{aa84ce40-4253-a00a-8cd6-0800200f9a67}", which is https://github.com/open-eid/firefox-pkcs11-loader and/or "{443830f0-1fff-4f9a-aa1e-444bafbc7319}", which is https://github.com/open-eid/chrome-token-signing).

I'm CCing some people from https://github.com/open-eid to make them aware of the problem. They probably have these cards and they might be able to reproduce the crash.
CC @martinpaljak @metsma @allanjuhanson @rvillido

**Comment by metsma** [comment]
> With 7000 a week crashes a week, and AFAIK OpenSC is distributed by the Estonian government with their ID cards. How do we (OpenSC and Mozilla) get the Estonian government involved?

I am involved.

> Why are older versions of OpenSC crashing with newer versions of FireFox? What changed in FireFox?

I am unable produce the crash on my environments.

> Have newer Estonian ID cards been issued lately? But the distributed OpenSC is still the older version?

https://arstechnica.com/information-technology/2017/10/crypto-failure-cripples-millions-of-high-security-keys-750k-estonian-ids/
https://github.com/OpenSC/OpenSC/pull/1158

> Has Mozilla changed how it calls PKCS#11 in recent versions?

Dunno, the crashes have been there forever and unable reproduce them, most of the stack traces do not make sense. I don't find in appveyor artifacts any pdb files to help with stacktrace.

> Can anyone get the Estonian government agency that distributes the cards and OpenSC involved?

How can I help?

> PKCS#11 spy traces would be very helpful as well as opensc-debug traces. Does anyone have access to a failing card to get these? Can Mozilla get in touch with any of the users?

I have test cards and personal EID card

> With 7000 failures a week, I would suspect that the users are living with the failure. Maybe it only happens when FireFox is closed or the use pulls out the card. Situations the user does not care about. Have any users reported the problem to anyone? (Mozilla, OpenSC or Estonian government)

Mozilla polls backend the card so often and we need use in parallel pkcs11 (with plugin) for signing, maybe this is related?

**Comment by metsma** [comment]
> Pärast sertifikaatide uuendamist ID-kaardi lugejasse sisestamisel Firefox koheselt crashib
> Peale ID-Kaardi sertifikaadi uuendamist, ei lase Firefoxi avada, kui id-kaart on lugejas.
Translates: After upgrading card to ECC certificates FF crashes.
Probably still uses outdated opensc onepin module.

**Comment by frankmorgner** [comment]
build debug version of 0.15.0:
- [onepin-opensc-pkcs11.pdb (x86)](https://ci.appveyor.com/api/buildjobs/2jt4fyitumfj39g9/artifacts/onepin-opensc-pkcs11.pdb)
- [onepin-opensc-pkcs11.pdb (x64)](https://ci.appveyor.com/api/buildjobs/4bbxveq9xgug29ts/artifacts/onepin-opensc-pkcs11.pdb)

@marco-c did you have trouble finding the links or do you want to have the pdb files it by mail?

**Comment by marco-c** [comment]
@frankmorgner the library you ship has no link to any debug file (see https://crash-stats.mozilla.com/report/index/5d35d253-b38c-4099-8416-5c5aa0171010#tab-modules, the debug identifier and debug file are empty). So I'm not sure I'm going to be able to use those PDB files to symbolicate the minidumps (I assume you haven't built the PDB files at the same time as when you built the library).

**Comment by metsma** [comment]
Maybe we need adjust appveyor builds to include release build pdb artifacts?

**Comment by juneyourtech** [comment]
Firefox also crashes at launch, when the card is inserted beforehand.

Firefox won't crash with an OmniKey CardMan 1021 reader, but will crash, when the card is in the internal Arcor-made reader, which can be found in many hp EliteBooks.

Environment (I usually don't have access to it, so it's from memory) —
- Windows 10 64-bit, Fall Creators Update and previous release;
- The latest Firefox 52esr, crashes were in both 64-bit and 32-bit Firefoxes;
- The latest Estonian ID card software was installed every time;
- an hp EliteBook with internal smart card reader by Arcor;
- The crash happened with the generic driver, then with the driver downloadable from the hp homepage, and also when the driver was updated through Device Manager, presumably via Windows Update.

In the Windows Device Manager, the internal Arcor reader shows only when the card is inserted.

Whereas with the Omnikey reader, no crash happened. The driver was the default Omnikey driver for the device in Win10, with no updates.

**Comment by marco-c** [comment]
@juneyourtech can you reproduce the crash with the latest version of OpenSC?
@frankmorgner could you send a debug version of OpenSC to @juneyourtech, so he can produce a symbolicated crash report.

**Comment by juneyourtech** [comment]
@marco-c Sorry, I don't have access to such a particular set of devices to try this out. Maybe @metsma can help you out with that.

**Comment by frankmorgner** [comment]
DLLs with debug symbols (0.15.0):
- [OpenSC-win64_vs12-Debug.msi](https://ci.appveyor.com/api/buildjobs/4bbxveq9xgug29ts/artifacts/OpenSC-win64_vs12-Debug.msi)
- [OpenSC-win32_vs12-Debug.msi](https://ci.appveyor.com/api/buildjobs/2jt4fyitumfj39g9/artifacts/OpenSC-win32_vs12-Debug.msi)

PDB files of 0.15.0:
- [onepin-opensc-pkcs11.pdb (x86)](https://ci.appveyor.com/api/buildjobs/2jt4fyitumfj39g9/artifacts/onepin-opensc-pkcs11.pdb)
- [onepin-opensc-pkcs11.pdb (x64)](https://ci.appveyor.com/api/buildjobs/4bbxveq9xgug29ts/artifacts/onepin-opensc-pkcs11.pdb)

**Comment by dengert** [comment]
@juneyourtech, You said you are using an HP EliteBook with Alcor reader. 
@metsma You said   "Translates: After upgrading card to ECC certificates FF crashes."

Are these newer Estonian cards with ECC being distributed to every one? 
Do they also have larger RSA keys too?
Could they require extended APDU? 

Googling for smart card reader HP Elitebook Estonian
shows a number of interesting articles.

https://support.hp.com/ee-en/document/c05480628
From April is for a  different card implies the reader driver has issues with cards using larger keys.  

https://support.hp.com/bg-en/document/c03105481
Says: "This is working as designed, the Smart Card reader is only activated once a Smart Card is inserted." This could be an issue if FireFox is started and starts to query for readers, and only when the card is inserted is the reader discovered. Can you try inserting the card before FireFox is started. 

The HP Reader issues may not be related to the main problem, but if new cards with larger keys are being issued that could  be related to the main issue.

**Comment by metsma** [comment]
> Are these newer Estonian cards with ECC being distributed to every one?

Applets are upgraded from RSA 2048 -> EC P384

> Do they also have larger RSA keys too?

RSA has weaknes on Infineon chips, only EC keys are available

> Could they require extended APDU?

EC Signature and certificate are smaller than RSA

As far I have experience with Alcor reader (HP and Lenovo) operate on T=0 protocol with default drivers.
Microsoft driver prefers T=1

**Comment by juneyourtech** [comment]
@dengert wrote:
> You said you are using an HP EliteBook with Alcor reader.
I was using this notebook at the time I found out the issue with the Alcor reader, but I usually do not have access to it, because it's someone else's computer.

> Can you try inserting the card before FireFox is started.
As I'd explained upthread: Even, if the card is inserted into the internal reader beforehand, Firefox crashes at launch. Some of the the crash reports explain, that Firefox crashes, when inserting the card at the time Firefox is running.

Sidenote: At the time I wrote my initial post, I'd edited it for clarity. It's possible, that edits to the post may be missing in e-mail-based threads after I'd initially submitted the comment.

**Comment by metsma** [comment]
I figured out. Alcor drivers use T=0 and it fails to read certificate.
Crash fix is here https://github.com/OpenSC/OpenSC/pull/1189
and the reason why the reading fails is in issue https://github.com/OpenSC/OpenSC/issues/1190

**Comment by frankmorgner** [comment]
@marco-c looks like the problem was still present in the most recent release of OpenSC... A new release of OpenSC will take some time; do you know when your change in Firefox will be released?

**Comment by metsma** [comment]
We can probably distribute patched opensc in estonia.
Before I need figure out how to fix #1190, its not related directly card specific issue and does it affect other drivers.

**Comment by marco-c** [comment]
> @marco-c looks like the problem was still present in the most recent release of OpenSC... 

Yeah, I was aware of this (https://github.com/OpenSC/OpenSC/issues/1176#issuecomment-342107672).

> A new release of OpenSC will take some time; do you know when your change in Firefox will be released?

The block for 0.15.0.0 is going to be in Firefox 57. Since this problem seems to only affect Estonian users and they will be updated shortly, we will not block any other version and will await for your fix.

In the future, it might be worth shipping the library without stripping the PDB information out of the DLL, so we can get you a fully symbolicated stack trace on demand.

**Comment by marco-c** [comment]
> In the future, it might be worth shipping the library without stripping the PDB information out of the DLL, so we can get you a fully symbolicated stack trace on demand.

I filed https://github.com/OpenSC/OpenSC/issues/1191 for this.

**Comment by metsma** [comment]
> Since this problem seems to only affect Estonian users and they will be updated shortly

Hopefully anybody with familiar OpenSC internals can help me with the #1190.

**Comment by marco-c** [comment]
@metsma can you deploy the new version of OpenSC which contains the fix?

**Comment by metsma** [comment]
Update is on the way, the downside is Firefox removed from 57 release PKCS11 loading support with extension

**Comment by metsma** [comment]
We are now distributing updated opensc.
