### ISSUE TITLE
epass2003 cannot generate EC key

### ISSUE THREAD

**Issue by majkrzak** [OpenSC/OpenSC#1177]
Due to laziness of @frankmorgner I had to build opensc by myself. It was quite problematic, because master do not build. Propably because somone who is committing straight there. But it is topic for other issue

**My current problem is that I'm not able to generate EC key**, because OpenSC is reporting `Failed to generate key: Incorrect parameters in APDU`. 

@FeitianSmartcardReader did you tested it?

[Detailed log](https://github.com/OpenSC/OpenSC/files/1424208/ec.log)

**Comment by frankmorgner** [comment]
@majkrzak you should think again how you treat a community of mostly volunteers. Please put your verbal excretions on Facebook, twitter or somewhere else where nobody cares for it. This forum is meant for constructive conversations.

master builds perfectly [on all platforms](https://github.com/OpenSC/OpenSC#opensc-documentation). From CI, you'll find Windows binaries in the [jobs](https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.17.0.1482) artifacts

**Comment by FeitianSmartcardReader** [comment]
@majkrzak may please let us know where you buy epass2003 from? the default epass2003 doesn't support ECC, if you haven't ask ECC support with our sales, then should be our default version. if you want ECC supported version, you can go our web store to buy and make notes tell business people "needs ECC support", any questions, let me know anytime, thanks

**Comment by majkrzak** [comment]
@FeitianSmartcardReader token was bought via rockey.pl and ECDSA support
was defined there. Could you give me a convinient way of checking if it is
supported? Serial number firmware version, etc...

03.11.2017 10:21 "Feitian Technologies" <notifications@github.com>
napisał(a):

@majkrzak <https://github.com/majkrzak> may please let us know where you
buy epass2003 from? the default epass2003 doesn't support ECC, if you
haven't ask ECC support with our sales, then should be our default version.
if you want ECC supported version, you can go our web store to buy and make
notes tell business people "needs ECC support", any questions, let me know
anytime, thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSC/OpenSC/issues/1177#issuecomment-341653345>, or mute
the thread

**Comment by FeitianSmartcardReader** [comment]
@majkrzak Thanks for reply. I did check with our engineer, he said you already did check in your log, so your token confirm doesn't support ECC, you can buy from online store or buy from reseller and let them know you need ECC version, thanks
