### ISSUE TITLE
Firefox 56.0.2 (64-bit) on Windows UI is different than documentation

### ISSUE THREAD

**Issue by bob-fontana** [OpenSC/OpenSC#1181]
### Problem Description

56.0.2 (64-bit) on Windows doesn't see to match the documentation.  There are no longer tabs -- only 4 sidebar menu options.  The Advanced tab is found by clicking Privacy and Security. 
### Proposed Resolution
Update the documentation to reflect FF 56.0.2 (64-bit).
### Steps to reproduce
Update Firefox to 56.0.2 and follow the instructions at https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step
### Logs

No log output available.  Can't configure browser.

**Comment by frankmorgner** [comment]
Please help yourself and update the wiki.
