### ISSUE TITLE
Firefox 56.0.2 (64-bit) doesn't load OpenSC .dll

### ISSUE THREAD

**Issue by bob-fontana** [OpenSC/OpenSC#1182]
### Problem Description

Firefox 56.0.2 (64-bit) cannot load the OpenSC PKCS11 driver.
### Proposed Resolution
Add support for Firefix 64-bit or update the documentation to be more specific about which versions of Windows and which versions of Firefox are supported.
### Steps to reproduce
On Windows 10 64-bit, try to follow the instructions at [OpenSC's Wiki](https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step) and it will be observed that the minidriver cannot be loaded.
### Logs

No logs available.  Didn't get that far.

**Comment by frankmorgner** [comment]
I understand that you're sad about the current state of documentation, so am I. But following you're request, **you** could at least describe what kind of problem you're experiencing on which kind of machine with what version of Windows!

**Comment by bob-fontana** [comment]
Uninstalled, reinstalled, ensuring that all sub-packages were selected, and the opensc-pkcs11.dll module appeared.

**Comment by bob-fontana** [comment]
Closing.  Probably operator error.
