### ISSUE TITLE
Compiling OpenSC to work with an Oberthur ID-One Cosmo v7 (AuthentIC 3.2.2) smart card in Windows 10 x64

### ISSUE THREAD

**Issue by lmiguelmh** [OpenSC/OpenSC#1184]
### Problem Description

Hello to this great community. I compiled OpenSC for Windows 10 x64 using Visual Studio 2012 compiler. I followed these instructions https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows and https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start. I didn't enable the support for OpenSSL, OpenPACE, zlib. All compiles correctly and I use the generated installer to install it. When I test it:

> C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe --name --atr
> Using reader with a card: Gemplus USB Smart Card Reader 0
> 3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
> Unsupported card

I have the same problem when installing the _light_ version of OpenSC. This is not the case when installing the _full_ OpenSC version, in which case it works as expected:

> C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe --name --atr
> Using reader with a card: Gemplus USB Smart Card Reader 0
> 3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
> Oberthur AuthentIC 3.2.2

I know this card is supported as it is stated here:
- https://github.com/OpenSC/OpenSC/wiki/Supported-hardware-(smart-cards-and-USB-tokens) 
- https://github.com/OpenSC/OpenSC/wiki/Oberthur-AuthentIC-applet-v2.2
- https://github.com/OpenSC/OpenSC/wiki/Oberthur_AuthentIC_v3

### Proposed Resolution

Compile the full version of OpenSC?
How do I do this? Is it in another branch?

### Steps to reproduce

Install OpenSC light version and execute:
> C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe --name --atr
> Using reader with a card: Gemplus USB Smart Card Reader 0
> 3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
> Unsupported card

Install OpenSC full version and execute:
> C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe --name --atr
> Using reader with a card: Gemplus USB Smart Card Reader 0
> 3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
> Oberthur AuthentIC 3.2.2

### Logs

I can generate the logs.

**Comment by lmiguelmh** [comment]
I found more instructions to build for Windows, I do not see a major difference between them:
- https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer
- https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows

Anyway, I found that the ATR should be specified in the configuration file: https://github.com/OpenSC/OpenSC/blob/00a710b93999bad9fffd701d1cb775bca3a36a12/src/libopensc/card.c#L223

So, I will replicate the contents of the configuration file and try to copy the profile file... 

> 	# Oberthur's AuthentIC v3.2.2
> 	card_atr 3B:DD:18:00:81:31:FE:45:80:F9:A0:00:00:00:77:01:00:70:0A:90:00:8B {
> 		type = 11100;
> 		driver = "authentic";
> 		name = "AuthentIC v3.1";
> 
> 		# Name of SM configuration sub-section
> 		# secure_messaging = local_authentic;
> 	}
> 

Atte.

**Comment by lmiguelmh** [comment]
The configuration file for the light version *does* contain the Oberthur AuthentIC configuration.
What is different is the libraries: `opensc-pkcs11.dll` and `opensc-minidriver.dll`, which by the way are installed in `C:\Windows\System32`. So I assume I need to enable something in the compilation or I need the optional packages (OpenSSL, zlib, OpenPACE).

**Comment by dengert** [comment]
It needs OpenSSL:
card-authentic.c line 27  `#ifdef ENABLE_OPENSSL   /* empty file without openssl */`

Why do you need to build without the other packages?

**Comment by lmiguelmh** [comment]
@dengert thanks!
I will compile it on Monday...
About your question: It was my first try :)

**Comment by frankmorgner** [comment]
Have you [adjusted your configuration](https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows#edit-makerulesmak) based on the additional packages, that you've built?

CI uses [this script](https://github.com/OpenSC/OpenSC/blob/master/appveyor.yml) to build the package, example output is available [here](https://ci.appveyor.com/project/LudovicRousseau/OpenSC/branch/master)

**Comment by lmiguelmh** [comment]
@frankmorgner I am using Cygwin and adjusting my configuration now but after:
`./configure --disable-readline --disable-zlib`

I am getting this summary (**notice the line: OpenSSL support: no**):

```
OpenSC has been configured with the following options:
...
User binaries:           /usr/local/bin
Configuration files:     /usr/local/etc
XSL stylesheets:         no
...
man support:             no
doc support:             no
thread locking support:  yes
zlib support:            no
readline support:        no
OpenSSL support:         no
PC/SC support:           yes
CryptoTokenKit support:  no
OpenCT support:          no
CT-API support:          no
minidriver support:      no
SM support:              yes
SM default module:       smm-local.dll
DNIe UI support:         no
Notification support:    yes
Debug file:              %TEMP%\\opensc-debug.log

PC/SC default provider:  winscard.dll
PKCS11 default provider: opensc-pkcs11.dll

Host:                    x86_64-unknown-cygwin
Compiler:                gcc
Preprocessor flags:       -DCRYPTOKI_FORCE_WIN32
Compiler flags:          -fno-strict-aliasing -g -O2 -Wall -Wextra -Wno-unused-parameter -Weron-after-statement
Linker flags:
Libraries:

READLINE_CFLAGS:
READLINE_LIBS:
ZLIB_CFLAGS:
ZLIB_LIBS:
OPENSSL_CFLAGS:
OPENSSL_LIBS:
OPENPACE_CFLAGS:
OPENPACE_LIBS:
OPENCT_CFLAGS:
OPENCT_LIBS:
PCSC_CFLAGS:             -I/usr/include/PCSC
CRYPTOTOKENKIT_CFLAGS:
GDBUS:                   /usr/bin/gdbus
GIO2_CFLAGS:
GIO2_LIBS:
```

**Comment by lmiguelmh** [comment]
I modified the file `Make.rules.mak` according https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows#edit-makerulesmak:
```
# If you want support for OpenSSL (needed for pkcs15-init tool, software hashing in PKCS#11 library and verification):
# - download and build OpenSSL
# - uncomment the line starting with OPENSSL_DEF
# - set the OPENSSL_INCL_DIR below to your openssl include directory, preceded by "/I"
# - set the OPENSSL_LIB below to your openssl lib file
OPENSSL_DEF= /DENABLE_OPENSSL
!IF "$(OPENSSL_DEF)" == "/DENABLE_OPENSSL"
!IF "$(PLATFORM)" == "x86"
OPENSSL_DIR = C:\OpenSSL-Win32
!ELSE
OPENSSL_DIR = C:\OpenSSL-Win64
!ENDIF
OPENSSL_INCL_DIR = /I$(OPENSSL_DIR)\include

#define OPENSSL_STATIC if you have visual studio compatible with OpenSSL's static binaries
OPENSSL_STATIC_DIR = static

!IF "$(DEBUG_DEF)" == "/DDEBUG"
!IF "$(PLATFORM)" == "x86"
# OpenSSL 1.0.2
#OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libeay32MTd.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
# OpenSSL 1.1.0
OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libcrypto32MTd.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
!ELSE
# OpenSSL 1.0.2
#OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libeay32MTd.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
# OpenSSL 1.1.0
OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libcrypto64MTd.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
!ENDIF
!ELSE
!IF "$(PLATFORM)" == "x86"
# OpenSSL 1.0.2
#OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libeay32MT.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
# OpenSSL 1.1.0
OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libcrypto32MT.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
!ELSE
# OpenSSL 1.0.2
#OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libeay32MT.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
# OpenSSL 1.1.0
OPENSSL_LIB = $(OPENSSL_DIR)\lib\VC\$(OPENSSL_STATIC_DIR)\libcrypto64MT.lib user32.lib advapi32.lib crypt32.lib ws2_32.lib
!ENDIF
!ENDIF

PROGRAMS_OPENSSL = cryptoflex-tool.exe pkcs15-init.exe netkey-tool.exe piv-tool.exe \
	westcos-tool.exe sc-hsm-tool.exe dnie-tool.exe gids-tool.exe npa-tool.exe
OPENSC_FEATURES = $(OPENSC_FEATURES) openssl
CANDLEFLAGS = -dOpenSSL="$(OPENSSL_DIR)" $(CANDLEFLAGS)
!ENDIF

```

**Comment by lmiguelmh** [comment]
Using:
`$ ./configure --enable-openssl --disable-readline --disable-zlib`
Gives:
`configure: error: OpenSSL linkage required, but no OpenSSL was found`
So, I assume I need to configure the %PATH% *on* Cygwin...

**Comment by lmiguelmh** [comment]
Ok, I added OpenSSL binaries to the path.

```
$ echo $PATH
/usr/local/bin:/usr/bin:/cygdrive/c/OpenSSL-Win64
```

The problem still continues... I've managed to trace the problem back to this line in `configure` file:

**Line 20229**
```
if ac_fn_c_try_link "$LINENO"; then :
  ac_cv_lib_crypto_RSA_version=yes
else
  ac_cv_lib_crypto_RSA_version=no
fi
```
After this line it fails with:

`configure: error: OpenSSL linkage required, but no OpenSSL was found`

Do you know what `ac_fn_c_try_link "$LINENO";` is trying to do?

**Comment by lmiguelmh** [comment]
Ok. I've wasted my time using `--enable-openssl` in the configure tool... The thing is just to use **ignore it** and use `--disable-openssl` in accordance with the steps detailed in https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows#edit-makerulesmak

```
C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe --name --atr
Using reader with a card: Gemplus USB Smart Card Reader 0
3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
Oberthur AuthentIC 3.2.2
```
Now the real journey starts for me. Thanks for all your support!
