### ISSUE TITLE
MacOS High Sierra: dmg creation hangs up

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1197]
### Problem Description

MacOS 10.13.1 High Sierra, Xcode-9.1. Current GitHub master.

Near the end of the OpenSC build process (initiated by `./bootstrap && MacOSX/build`) the build hangs badly (i.e., cannot kill it with <Ctrl-C>) executing the following line:
```
hdiutil create -srcfolder OpenSC-0.17.0.pkg -srcfolder 'OpenSC Uninstaller.app' -volname OpenSC OpenSC-0.17.0.dmg
```

### Proposed Resolution

I wish I knew.

### Steps to reproduce

Clone the stuff, and do `./bootstrap && MacOSX/build`

### Logs

Found nothing in system logs. ;-(

**Comment by frankmorgner** [comment]
The [latest build](https://travis-ci.org/OpenSC/OpenSC/builds/300047278) worked perfectly, the problem with the [previous build](https://travis-ci.org/OpenSC/OpenSC/jobs/299595490) seems to be related to the travis ci infrastructure rather than with our repository
