### ISSUE TITLE
MacOS High Sierra: build hangs up on dmg creation (2nd submission)

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1198]
@frankmorgner you **really** should pay more attention to what [the issue](https://github.com/OpenSC/OpenSC/issues/1197) says before closing it via "shooting from the hip" approach.

Your "[latest build](https://travis-ci.org/OpenSC/OpenSC/builds/300047278)" reports that it uses Xcode-7.3 on MacOS El Capitan **10.11** (I conjecture it's 10.11.5).
From your successful Travis build:
```
Host:                    x86_64-apple-darwin15.6.0
```

I am reporting failure on MacOS High Sierra **10.13** and Xcode-9.1 - notice it's different from Xcode-7 .3 used in your build:
```
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
. . . . .
```
Travis doesn't help here.

Oh, and this build has been working for me successfully up to and including MacOS Sierra **10.12** with Xcode-9.1. But after the yesterday's OS upgrade to 10.13 it started failing consistently on `hdiutil`. Did not find anything relevant in the syslog. ~~Want to tell me again that it works on 10.11?~~

### Problem Description

MacOS 10.13.1 High Sierra, Xcode-9.1. Current GitHub master.

Near the end of the OpenSC build process (initiated by ./bootstrap && MacOSX/build) the build hangs badly (i.e., cannot kill it with ) executing the following line:

```
rm -f OpenSC OpenSC-0.17.0.dmg
hdiutil create -srcfolder OpenSC-0.17.0.pkg -srcfolder 'OpenSC Uninstaller.app' -volname OpenSC OpenSC-0.17.0.dmg
```

### Steps to reproduce

Clone the stuff, and do `./bootstrap && MacOSX/build` **on MacOS High Sierra 10.13.1** (with Xcode-9.1, but Xcode version probably doesn't matter).

As I said, there's nothing in the logs (that I could see). But if any info could help here, please let me know and I'll provide.

**Comment by metsma** [comment]
I can reproduce the issue, only way to finish script is comment out hdiutil

**Comment by mouse07410** [comment]
@metsma the fix in in my fork https://github.com/mouse07410/OpenSC.git
Not that generating .dmg is that critical... ;-)

**Comment by mouse07410** [comment]
My MacOS build diverged enough from yours to make a straight PR harder, and frankly, my time is also quite tight.

Here's what fixes the problem for High Sierra, while not breaking my Travis CI:
```
@@ -127,7 +152,12 @@ osacompile -o "OpenSC Uninstaller.app" "MacOSX/OpenSC_Uninstaller.applescript"
 # Create .dmg
 rm -f OpenSC-@PACKAGE_VERSION@.dmg
 i=0
-while ! hdiutil create -srcfolder "OpenSC @PACKAGE_VERSION@.pkg" -srcfolder "OpenSC Uninstaller.app" -volname "@PACKAGE_NAME@" OpenSC-@PACKAGE_VERSION@.dmg
+# Workaround for MacOS High Sierra, whose hdiutil hangs when
+# more than one "-srcfolder xxx" parameter is present
+tmpdir=$(mktemp -d /tmp/hdiutil.XXXXX)
+cp -pr "OpenSC-@PACKAGE_VERSION@.pkg" ${tmpdir}/.
+cp -pr "OpenSC Uninstaller.app" ${tmpdir}/.
+while ! hdiutil create -srcfolder ${tmpdir} -volname "@PACKAGE_NAME@" OpenSC-@PACKAGE_VERSION@.dmg
 do
        i=$[$i+1]
        if [ $i -gt 2 ]
```

Feel free to integrate it.
