### ISSUE TITLE
How to deal with CKR_PIN_LOCKED

### ISSUE THREAD

**Issue by phuongnd08** [OpenSC/OpenSC#1199]
Our bank gave us the Aladdin token which has been working great for a while.
Suddenly the token getting locked, attempting test login returns this:

```
$ pkcs11-tool --module /lib/libeTokenHID.so.9 --slot-index 1 --login --test
error: PKCS11 function C_Login failed: rv = CKR_PIN_LOCKED (0xa4)
```

I guess it's not about password correct but perhaps being disconnected suddenly somehow cause the device to incorrectly locked itself.

I noticed that there is option to unlock-pin but it asking for another password:

```
$ pkcs11-tool --module /lib/libeTokenHID.so.9 --slot-index 1 --unlock-pin
Using slot with index 1 (0x1)
Please enter unblock code for User PIN:
```

Not sure what is that, apparently not the token password. Is there any way to unlock my token so it will accept password again?

**Comment by dengert** [comment]
Talk to your bank.

**Comment by phuongnd08** [comment]
I have asked the bank. They want me to bring the token to them which will take a few weeks since I'm out of the city.

When I do a `pksc11-tool -T` I'm getting this:
```
token flags        : rng, login required, PIN initialized, token initialized, user PIN count low, user PIN locked, other flags=0x200
```

What could it mean?

**Comment by frankmorgner** [comment]
It means that you **really** need to go to your bank.

**Comment by phuongnd08** [comment]
Okay, the bank fixed the token.
Though could you shed some light on what does that mean by "user PIN count low"?
Does that mean we submitted incorrect password multiple times or does that mean the token password need to be updated once in a while?

**Comment by dengert** [comment]
"user pin low" comes from the PKCS\#11 standards: http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html
```
CKF_USER_PIN_COUNT_LOW 0x00010000 True if an incorrect user login
PIN has been entered at least
once since the last successful
authentication.
CKF_USER_PIN_FINAL_TRY 0x00020000 True if supplying an incorrect
user PIN will cause it to
become locked.
CKF_USER_PIN_LOCKED 0x00040000 True if the user PIN has been
locked. User login to the token
is not possible
```
The limit of failed attempts in a row before card is locked is set by the card issuer. You may want to ask
your bank what the limit is. 

But most cards report the number of attempts remaining to enter a valid PIN. "user PIN count low" is a best attempt to indicate that you only have a few attempts left. The card will reset its counter when a correct pin is entered. So if you get a failed message using some new software or new device be careful to not keep trying the same PIN. You can use software or device that has worked and recommended by the card issuer.  

It looks like `pkcs11-tool  -login  ...` will only try once and exit if  login fails.  So it should only count as one bad attempt.    

You asked about  "being disconnected suddenly". The should not cause the PIN to be locked. But that again depends on the device.  (The login is done by the card, so it does not depend on a network.)

**Comment by phuongnd08** [comment]
Okay thank you. Though I never attempted an incorrect password (not of I know of). So I guess some undocumented mechanism inside the token would lock itself if certain conditions are met, not necessary the number of failed password attempts. Thank you for explaining.

**Comment by dengert** [comment]
It could be a bug in OpenSC. Your bank may have non standard code that OpenSC does not handle. 
If you really want to get it working with OpenSC, see these pages  and others on the WIKI. 

 https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC
 https://github.com/OpenSC/OpenSC/wiki/Getting-involved-in-OpenSC-development

A debug log would show how your PIN was sent to the card, and what the card returned. Note the debug log will contain your PIN and maybe other information you may not want exposed. You may want to obfuscate it before sending the log.  

Also note that if a login fails, use your card with some software where your PIN works, so it resets the counter before trying any other tests.

**Comment by mouse07410** [comment]
Note that I've seen the allowed number of incorrect attempts to be set to as low as **2**. The third incorrect attempt would lock the PIN/card.
