### ISSUE TITLE
pkcs11 read certificate 

### ISSUE THREAD

**Issue by revTimo** [OpenSC/OpenSC#1200]
hi, i don't know too much how to use pkcs11 options.
This is what i m doing in pkcs15 `pkcs15-tool --read-certificate 2 --verify-pin --auth-id 02`
how to write the same command in pkcs11?
thanks

**Comment by Jakuje** [comment]
I wrote simple guide to work with PKCS#11 using `pkcs11-tool` some time ago:

https://gist.github.com/Jakuje/5a993d2b2d8a9cac35203599e49e6831

It starts with reading certificate from the card using PKCS#11. What you are looking for is probably

```
SIGN_KEY_ID=2
pkcs11-tool --read-object  --id $SIGN_KEY_ID --type cert > $SIGN_KEY_ID.cert
```

If the certificate is not readable without login, use also the `--login` switch, which will ask for PIN before reading the certificate. For more reference, manual page for `pkcs11-tool` should help you.

**Comment by frankmorgner** [comment]
@Jakuje maybe you could put some of that guide into the OpenSC wiki. I think this is not the first time, you're referencing this.

**Comment by revTimo** [comment]
@Jakuje thanks

**Comment by Jakuje** [comment]
@frankmorgner Thanks for the suggestion. I was considering to do something like that for some time, but somehow did not find the best place for it. Wiki is certainly a good place:

https://github.com/OpenSC/OpenSC/wiki/Using-pkcs11-tool-and-OpenSSL

**Comment by frankmorgner** [comment]
an other option would be to put example usage into the man page. Ideally, the man-page should then also be available (or referenced) on our website to have the information in one place.
