### ISSUE TITLE
RPC failure on smart card logon with Windows 10

### ISSUE THREAD

**Issue by SCOLL7527** [OpenSC/OpenSC#1209]
Hi,

I don't know if this is relevant here, but I'm trying to reduce as much as I can where to look to identify my problem.

I use a smart card (Identiv uTrust 3522 embd SE Token 0) to log in on a Windows client. I managed to set up a Samba AD on a VM, on my Windows 7 machine. Then clients can log in using the smart card.

Then I tried to set it up on a Windows 10, without success. I get a "RPC failure" when I try to log in using the smart card, event log say "lsass.exe has crashed" and then my machine reboots by itself. I asked on Stack Exchange and on the Samba mailing list (but it doesn't seem like Samba is the issue here) with no response.

I found this : [https://social.technet.microsoft.com/Forums/en-US/98956e76-1d45-4c1f-943e-97b6da5484f4/smartcard-rpc-error-anniversary-update?forum=win10itprosecurity](url) which corresponds to my problem. The hotfix available doesn't do anything.

Is this a known problem with using smart card and Windows 10 on a joined domain, or is it just me ?

Best regards,

S.

Logs : 
```
$ opensc-tool.exe -n
Using reader with a card: Identiv uTrust 3522 embd SE Token 0
SmartCard-HSM Applet for JCOP version 2.3
```

```
$ opensc-tool --info
OpenSC 0.17.0 [Microsoft 1800]
Enabled features:pcsc openssl zlib
```

Set up : 
Windows 10 Entreprise N with Hyper V
Samba AD on Ubuntu Server 16.04.3

**Comment by frankmorgner** [comment]
@CardContact ?

Is the problem caused by removing the card (https://github.com/OpenSC/OpenSC/issues/585, https://github.com/OpenSC/OpenSC/issues/973)?

**Comment by frankmorgner** [comment]
please generate a debug log

**Comment by dengert** [comment]
Could be Windows 10 uses RPC that is not supported by your Samba AD. 

Searching for: Samba AD windows 10
Shows a lot of issues.

Do event logs on the failing compute show more than "lsass.exe has crashed".

Can you run wireshark on AD and look for RPCS? Not sure if they are encrypted or not. 

The reference to  https://social.technet.microsoft.com/Forums/en-US/98956e76-1d45-4c1f-943e-97b6da5484f4/smartcard-rpc-error-anniversary-update?forum=win10itprosecurity  id for a Yubico smartcard. The Yubico has a PIV **like** APPlet that can use the Microsoft PIC driver. As they said Yubico was in contact with Microsoft. So this does not sound like an OpenSC issue., but more of a Windows 10 to the DC.

It also said: "The interesting part is, if you use the yubikey to authenticate via RDP it works." 
Are you using Remote Desktop Connection to connect to the VM? There might be issues with who controls access to the card.

**Comment by SCOLL7527** [comment]
Yes, after digging more into it, it probably is a problem with Windows 10, more specifically about a different COM object.
I'm trying to fix this, I can give results here if I manage to, if it can help someone later.

> please generate a debug log
What would you need on this ?

> Are you using Remote Desktop Connection to connect to the VM?
No, I joined my machine to domain so I'm connecting to the domain but on the same, it's not using RDC for logging in.

**Comment by dengert** [comment]
Just some oth3r thoughts:

Windows 10 introduced "Windows 10 Credential Guard Architecture" a lot of new protection for LSASS:
 https://yungchou.wordpress.com/2016/03/14/an-introduction-of-windows-10-credential-guard/

Looks like it is only for Windows 10 Enterprise. and uses RPCs. 

Smartcard login uses Kerberos PKINIT to get TGTs. These are protected by the new  ""Windows 10 Credential Guard Architecture" if its is on.

Note that Credential Guard requires the hypervisor to be running and if you are also using some other VM host software that may cause problems. 

I would also question if the Samba DC needs some updating.

**Comment by dengert** [comment]
This may also apply:
https://docs.microsoft.com/en-us/windows-server/security/kerberos/whats-new-in-kerberos-authentication 

 "Beginning with Windows 10, version 1607 and Windows Server 2016, Kerberos clients attempt the RFC 8070 PKInit freshness extension for public key based sign-ons." i.e. smart card use public key based sign-ons. 
It looks like there is an option to disable this feature. 

If this is indeed the problem a wireshark trace for Kerb protocol would show this and error message. 

RFC 8070 defines  PA_AS_FRESHNESS but not its contents. The URL above does say there is an RPC involved.

**Comment by SCOLL7527** [comment]
> Smartcard login uses Kerberos PKINIT to get TGTs. These are protected by the new ""Windows 10 Credential Guard Architecture" if its is on.

Yes I checked it, it's disabled by default, and by changing it (from "not configured" to "Disabled" didn't change anything.

> "Beginning with Windows 10, version 1607 and Windows Server 2016, Kerberos clients attempt the RFC 8070 PKInit freshness extension for public key based sign-ons." i.e. smart card use public key based sign-ons.
It looks like there is an option to disable this feature.

Same here, it's disabled by default. And even if it was not, my Samba AD is a 2008 level server, so this applies:

> Support for PKInit Freshness Extension requires Windows Server 2016 domain functional level (DFL). If the domain controller's domain is not at Windows Server 2016 DFL or higher this policy will not be applied. 

I indded try Wireshark. I see kerberos authentication between my client and my AD, it's successful. Authentication on the server is ok but then Windows encounters a problem.

**Comment by dengert** [comment]
If you have not found these, they might help.

Debugging Kerberos, PKINIT and other related programs:
https://docs.microsoft.com/en-us/windows/access-protection/smart-cards/smart-card-debugging-information

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/overview-of-rpc-debugging

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/extra-tools

https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/Windows_Protocols.zip
Includes 500 or so protocol documents. MS-KILE is the Kerberos one. 

I would still suspect Windows 10 introduced some feature that the Samba AD is not handling correctly. 
If there was no response from the Samba AD community, I bet no one else is using Samba AD with smartcard login. 
If it fails with a Microsoft DC, I would expect it would have been fixed.

**Comment by SCOLL7527** [comment]
Yes I stumbled upon RPC debugging. Unfortunately, dbgrpc needs the endpoint pid of the RPC service I want to debug, which I don't know. Listing all endpoint give a 220-entry-long list of name like "OLE729E0E4B9B0ADE7B4100A2B3".

Samba doc doesn't clearly say what is happening when trying to log in via smart card.  I'm at loss here.

Thanks for your help. I'm going to file a bug report on Samba, maybe it'll speed things up to get a reply from them.

> I would still suspect Windows 10 introduced some feature that the Samba AD is not handling correctly.

Yes, that's why I think too.

**Comment by dengert** [comment]
So far you have said you are using:

- "(IdentivuTrust 3522 embd SE Token 0)"
- "Windows 10 Entreprise N with Hyper V"
- Samba AD on Ubuntu Server 16.04.3

What version of Samba AD? Can you test with the latest version?
Does this mean the Windows 10 is the guest OS? 
Can you get it to fail without Hyper V involved at all? 
Can you get this to fail on a Windows Pro system? (Maybe problem is related Enterprise features.)

For the Samba people or others to fix this bug, they need a way to test it. Do you have any other smart cards? In particular, Windows has built in drivers (i.e. does not need OpenSC) for a number of smart cards, including PIV. The Yubico NEO and Yubikey are PIV like and can work with the Microsoft drivers.  If it fails in the same way using one of these, it takes OpenSC out of the picture. And could give Samba a way to test the problem internally. 

Have you tried Remote Desktop Connection RDC with the smartcard from some machine to the failing Windows 10? With RDC the OpenSC or Microsoft drivers are run on the failing Windows 10. 
RDC client-> failing Windows 10 -> Samba AD. In this case the RDC Client could be someone from outside with a smart card helping to test a  "failing Windows 10 -> Samba AD" at another site. 

The Windows runas command has a /smartcard option to use the smartcard for authentication. 
This might also make it easier to test and debug then actually using logon. There are a number of options about /profile and /netonly. See if runas fails or works with some combinations of these options.

**Comment by SCOLL7527** [comment]
Set up is exactly: 
Client : Windows 10 Entreprise N
Server : Ubuntu 16.04.3 Server running on the client (Win10) via Hyper V
  (So server is indeed running on the guest OS)
Samba ver : 4.3.11-Ubuntu

> Can you get this to fail on a Windows Pro system?

I tried it also on a Winndows 10 Pro with Ubuntu Server running on VM Box, I get the same error. Doesn't seem to be related to Entreprise features.

> Do you have any other smart cards?

I'll see if I can get another one of a different brand.

> Have you tried Remote Desktop Connection RDC

Didn't tink about this, that's a great idea !

I'll see if I can test with /smartcard option.

Thank you for your input.

**Comment by dengert** [comment]
One more thing. Since the problem appears to be with Windows 10 (recent update?) There are a number of changes in Samba between 4.3.11(2016-07-05)  and 4.7.3 (2017-11-20) Ubuntu Bionic Beaver (17.10 due for release April 2018) has Samba 4.7.1. So you may want to try prerelease of Bionic or build the latest Samba yourself.

**Comment by SCOLL7527** [comment]
Oh fuck me ! How could I not think about this ?! So many hours ..
I'm running a LTS server version so indeed, version was a bit old. Now it works fine ! I'll notice the team that there's a problem with this version but it's good with 4.7.3. Was also not a problem concerning OpenSC.

Thank you very much ! I'd buy you a beer if I could.

Cheers
