### ISSUE TITLE
The return value of pkcs15 tool pin fail

### ISSUE THREAD

**Issue by revTimo** [OpenSC/OpenSC#1211]
hi,
i am running pkcs15 tool from python like this
`proc = Popen('pkcs15-tool --read-certificate 2 --verify-pin --auth-id 02 --pin  wrongpin',
                             stdout=PIPE, stdin=PIPE)`
i want to write a program likes
`if pin fail: 
   print "wrong pin, retry!"
`
so i need to know what is the return value when pkcs15 verify pin is fail,

thanks

**Comment by frankmorgner** [comment]
If it works for you, you're free to use` pkcs15-tool`, however, OpenSC also offers *real* APIs for interoperability. For example, you could use PKCS#11 instead.

**Comment by revTimo** [comment]
@frankmorgner 
thanks for u r advice, but i don't get your point clearly,
my problem is when i type the wrong pin, it's return `Operation failed: PIN code or key incorrect`　and sometimes `Operation failed: Invalid PIN length`.  So I am in trouble with if pin fail condition checking, do u have any advice for this. 
If it is difficult with pkcs15, i only have to do with pkcs11 right?

**Comment by frankmorgner** [comment]
Both messages are signaling a problem with the PIN verification. The OpenSC tools are only meant for debugging and development; in production you should use the official APIs. There is a PKCS#11 wrapper for Python, if you don't want to handle the C-calls manually. Google for the package and use it!
