### ISSUE TITLE
Ask : where did the getCLASS, getLABEL, getID, function come from?

### ISSUE THREAD

**Issue by herpiko** [OpenSC/OpenSC#1214]
I'm trying to understand `pkcs11-tool` source code and found these functions help to parse the object handle. One of them :  

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L3696

But where did they come from? I've done grep `getLABEL` against OpenSC source code and found none.

Thank you

**Comment by frankmorgner** [comment]
They're defined [here](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L463-L520)

**Comment by herpiko** [comment]
@frankmorgner I didn't see any line that defines the `getLABEL` function. All lines that contain `getLABEL` string are the line that using the function, not a definition.

**Comment by herpiko** [comment]
@frankmorgner I found it. Thank you.
