### ISSUE TITLE
Partial support for OpenPGP v3.3

### ISSUE THREAD

**Issue by szszszsz** [OpenSC/OpenSC#1215]
### Problem Description
OpenPGP v3.3 card is not detected by the OpenSC tools. It is explicitly not supported, as says comment ([card-openpgp.c#L27](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-openpgp.c#L27)).  If possible it would be great to support it on the level of v2.1 standard first, that is without new features introduced in OpenPGP v3.3 - these could be added later.

### Proposed Resolution
Perhaps all needed changes could be enclosed within `card-openpgp.c`, specifically:
- adding ATR
- adding OpenPGP version constant
- changing DOs' names and access if needed
- adding DOs for future work (optional)
- setting PIN length to 64 bytes (would be great to set 64 UTF-8 chars as in specification, if supported)

### Steps to reproduce
Reader with inserted OpenPGP v3.3 card (OpenPGP v2.1 for environment confirmation)
Environments:
- Ubuntu 17.04, OpenSC 0.16 (success with OpenPGP v2.1)
- Ubuntu 17.10, OpenSC compiled from 654ca69c47f98dd6a82b4adc0bb6bb8ead887163 (current master, OpenSC 0.17+ [1]), Docker container (success with OpenPGP v2.1)

Steps:
1. Run `pkcs11-tool -L` 
2. Expect shown smartcard details (slot should not be `(empty)`)

[1] Version string from `opensc-tool`: `OpenSC-0.16.0-444-g654ca69c, rev: 654ca69c, commit-time: 2017-11-21 13:01:12 +0100`

CC: @jans23

**Comment by frankmorgner** [comment]
Just go ahaid 👍. Are you aiming for a specific time line?

@hongquan are you also working on this?

**Comment by hongquan** [comment]
@frankmorgner I'm not working on this.

**Comment by szszszsz** [comment]
@frankmorgner Work is planned for January 2018 (have to clear other tasks first). 
@hongquan Not yet. Any tips would the plan suffice?

**Comment by hongquan** [comment]
@szszszsz I think it is enough.

**Comment by frankmorgner** [comment]
From your todo list above I only implemented the basics in my PR. The following is still missing:

- [ ] changing DOs' names and access if needed
- [ ] adding DOs for future work (optional)
- [ ] setting PIN length to 64 bytes (would be great to set 64 UTF-8 chars as in specification, if supported)

**Comment by alex-nitrokey** [comment]
Hi, I am a bit confused. I want to test the basic OpenPGP Card 3 functionality and give feedback. I am not sure: All your commits so far are in master now, aren't they? Or is there another branch I should use for testing the implementation done so far?

**Comment by frankmorgner** [comment]
Yes, all of the work regarding OpenPGP version 3 is merged into master.

**Comment by alex-nitrokey** [comment]
Okay...

I tested opensc-git-0.17.0+174+g8ee2c619 under Arch Linux with Nitrokey Pro 0.8 and OpenPGP Card 3.3. I basically tested what is shown [on the wiki](https://github.com/OpenSC/OpenSC/wiki/OpenPGP-card). Everything seems to work fine so far.

I had a look at the changelog in the specification of OpenPGP Card v3 [as seen here](https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.3.pdf).

These are the added DOs as far as I can see:

* Extended length information (DO 7F66) (p. 13)
* General feature management (DO 7F74) (p. 14)
* Cardholder certificate (ISO 7816-6) for Decipher and Sign (DO 7F21?)
* User Interaction Flags introduced - UIF-DOs (D6 - D8) (p. 29)
* KDF-DO (Key Derivation Function) (p. 18)

Canges which seems to be noteworthy as well:

* RSA 1024 support is removed from OpenPGP Card v3 which may needs adjustment in OpenSC as well
* Enhancement of VERIFY (additional PIN format)
* Support for ECDSA/DH algorithm added

Please let me know, if I can help in testing or other things.

Kind regards

**Comment by frankmorgner** [comment]
I think all existing functionality that has previously worked with OpenPGP < 3  has been sufficiently tested with OpenPGP > 3 now.
