### ISSUE TITLE
Unusable eID cards with release versions of OpenSC

### ISSUE THREAD

**Issue by leio** [OpenSC/OpenSC#1216]
Please strongly consider making a new release to have a released version that supports smartcards issued to ~half the population of Estonia.

### Problem Description

Estonian ID cards that were issued new certificates for the Infineon ROCA vulnerability do not work with released versions of OpenSC, as packaged by downstreams if not patched at each downstream.
I am currently blocked on this for properly integrating eID support into Gentoo Linux.

### Proposed Resolution

Release an OpenSC-0.18 from git master after appropriate release engineering processes, so that downstreams can package it without chasing for patches. Some downstreams might not even want to include patches over a new official release.

### Steps to reproduce

Have an eID card issued after October 2014 and try to use it. It will not work due to lack of patches for it in #1158 and more.

**Comment by frankmorgner** [comment]
@metsma already helped distributing a fixed version, see https://github.com/OpenSC/OpenSC/issues/1176. For a new release see https://github.com/OpenSC/OpenSC/projects/4

**Comment by leio** [comment]
That distribution is for Windows users, not Linux. Linux distributions use officially released versions of OpenSC. Thanks for the pointer to the release blockers of 0.18..
