### ISSUE TITLE
macOS High Sierra Support - CardOS v4

### ISSUE THREAD

**Issue by netlocksecurity** [OpenSC/OpenSC#1218]
I apologize if this is the wrong venue for this communication but that last .17 build of OpenSC does not appear to be compatible with CardOS v4 but only with High Sierra.  Can someone please point me in the right direction to someone who may be able to assist?  

I've observed this issue migrating from Sierra (10.12) to High Sierra (10.13) and with a clean install of High Sierra (10.13). Any application that would normally read/auth with the card appears to be timing out (Microsoft Outlook 2016, Juniper VPN client, FireFox/Chrome).  Again, this works flawlessly on Sierra.

**Comment by Jakuje** [comment]
This should be resolved by the PR #1212 (not part of 0.17.0 release) or there is a workaround in #1208. Can you verify it gets resolved by the fix/workaround?

**Comment by netlocksecurity** [comment]
Jakuje,
Thank you for the quick response.  I'm not as familiar with this as I would like to be.  I was able to find the conf file in /Library/OpenSC/etc/ and I saw some places that I could uncomment the max/min values mentioned but I'm not sure if that was all that it took or if i need to reboot/restart service?  I know that you're very busy.  Any help that you can provide is extremely appreciated.

OS: macOS High Sierra 10.13.1
Build: MacBook Pro 2016 w/ Touchbar
Card: PKI w/ Siemens CardOS v.4

*on a different note, I did enable debug in the config file and although I can duplicate the issue, there appears to be no output.

**Comment by Jakuje** [comment]
You should not need to reboot, but if OpenSC library reads the configuration only during initialization and if the PKCS#11 module is loaded in NSS database of Firefox or in some other tool, you might need to restart the affected application, relogin. Rebooting computer should make the options effective.

**Comment by netlocksecurity** [comment]
Jakuje, you're a genius!  Un-commenting those two entries did the trick and after a reboot, I was back to normal.  Thank you for all of the work that you guys are doing with this!  Please let me know if you need assistance field testing v. .18!
