### ISSUE TITLE
pkcs15-init --secret-key-algorithm: How is des (i.e. des/56) intended to be handled?

### ISSUE THREAD

**Issue by carblue** [OpenSC/OpenSC#1219]
### Problem Description

The tool pkcs15-init will default to a key length of 7 bytes for des specified on the command line (same for explicitly specifying des/56), 7 bytes read from a file and written as is to card in the card-myeid.c example (as the sc_pkcs15_skey.data_len is 7) and result in a wrong SKDF entry referring key length. Only specifying explicitly des/64 makes things work as expected (at least for my card). Thus why the 7 byte default? Is it just an error or intended? An other default - for 3des - is a multiple of 8! The defaults are inconsistent.

DES is the building block of 3DES, the only algorithm possible for SM with my card ACOS5-64 (16 and 24 byte keys), thus I will transfer the answer to what I'm more interested in:  des/112 opposed to des/128 and des/168 opposed to des/192 as well.

I assume every card out there (like mine) stores a DES key value as 8 bytes i.e. sizeof(DES_cblock), similar for 3DES 16 or 24 bytes, and wonder, whether storing des/56 key in card-myeid.c (effectively storing 7 bytes) does work as intended.

Thus I assumed, des/56 in pkcs15-init is NOT an error but intended and the indication, that the 7 byte (effective) key data read from file still needs to be transformed to an odd-parity DES_cblock,
As pkcs15-init doesn't do the transformation, my card driver does it, if the data received from pkcs15-init are less than (a multiple of) 8 bytes, but turned out to be the wrong place for the transformation: The driver has no influence on what goes into SKDF.

First, I have to call in my init-function
	_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   56);
	_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   64);
// more calls for 3des omitted here
to make des/56 acceptable too which doesn't feel the right way to me.

Second, the command  pkcs15-init --store-secret-key file --secret-key-algorithm des --auth-id 01 --id 02   with 7 bytes (hex F1 C3 46 0B 14 22 04) in file, calls profile->ops->store_key and for my card ultimately would store the correct/transformed 8 byte DES_cblock key (hex F1 E0 D0 C1 B0 A1 89 08) 
but ends up with this (wrong for my card) SKDF-entry:

[2](4 elem)
  SEQUENCE(3 elem)
    UTF8String Secret Key
    BIT STRING(2 bit) 11
    OCTET STRING(1 byte) 01
  SEQUENCE(4 elem)
    OCTET STRING(1 byte) 02
    BIT STRING(2 bit) 11
    BIT STRING(4 bit) 1011
    INTEGER 0                <- not inportant for me: pkcs15-init doesn't handle keyReference
  [0](1 elem)
    INTEGER 56               <- this is wrong (at least for my card), the key on card has key length 64 bit
  [1](1 elem)
    SEQUENCE(1 elem)
      SEQUENCE(1 elem)
        OCTET STRING(6 byte) 3F0041004102

Am I right with my assumptions?
Will this wrong SKDF entry raise any trouble?
Currently my experimentally working secret key usage is based on an empty SKDF and my driver doesn't actually store a secret key but just logs what it would store.

If my assumptions are right, my proposal is in the following section.

Another problem I couldn't solve so far is how to configure my acos5_64.profile correctly, or the opensc code has no provision for that:
acos5_64.profile has an entry BSO secret-key in template "key-domain" (otherwise storing fails referring to missing secret-key file in this template) with the key/value-pairs
file-id   = 4102;
type      = internal-ef;
structure = linear-variable;

But only 1 internal EF for secret keys (stored in it's records) is allowed by acos in each application DF and the next to-be-stored secret key will end up with the wrong path in SKDF: 3F0041004103; thus I can't currently bypass the incrementing and storing key would fail already in selecting wrong path.

### Proposed Resolution

I like the idea of handling effective key length values in pkcs15-init as des/56, des/112 and des/168, but those shouldn't pass through to any driver in this originally specified form.
Any card driver that wants to deal with des, 3des, should only have to call
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   64) and/or
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 128) and/or
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 192) and/or
and receive 8/16/24 bytes for those cases, which involves, that pkcs15-init must take care for the other options by transforming effective key to DES_cblock (or multiple in case of 3DES) key and correct the specified option's key length accordingly.
Also, the default for des, in the same logic as for 3des, in static const struct alg_spec alg_types_sym[] should be:
	{ "des",	SC_ALGORITHM_DES,	64 },
the current settings are inconsistent.

I'm not proficient in every detail of C and it's standard lib for bit manipulations, but in the D language my basic function looks like this, but in lack of D's BitArray I doubt everything is useful for C: 

```
/* for inkey.length<8 bytes, inkey interpreted as NOT containing parity bits i,e, the effective key material, typically given with 56 bits==7 bytes (but also possible less for DES)
 * inkey will be read bitwise beginning from inkey index==0 and a 0 bit for parity "inserted" after each 7. inkey bit; ultimately all parity bits set as required.
 * possible enhancement in calling function: refuse the resulting DES_cblock if DES_is_weak_key(&result)==1;
 * TODO  ckeck what happens for inkey.length==0
 * TODO  check if littleEndian <-> bigEndian has any influence; for me with littleEndian it works
 */
DES_cblock transform_key_effective_to_DES_cblock_odd_parity(in ubyte[] inkey)
{
	import std.bitmanip : BitArray;
//import deimos.openssl.des : DES_cblock, DES_set_odd_parity;

	size_t inLen = inkey.length;
	assert(inLen<8);
	ubyte[] key  = new ubyte[](inLen); // const inkey can't be used directly because of the bitswap required and no mem will be allocated for BitArray, it will just be a view inside key
	foreach (i, b; inkey[])
		key[i] = bitswap(b); // bitswap required here, otherwise bits of each inkey byte appear reversed in BitArray; same requirement for the reverse: from BitArray content to ubyte

	BitArray    key_ba = BitArray(key, inLen*8);
	DES_cblock  result;

	foreach (i; 0..8) {
		if (i>0)
			key_ba >>= 7; // the 7 bits already processed shift out. 7 zero bits shift in at the other end of BitArray
		result[i] = (bitswap((cast(ubyte[])(cast(void[])key_ba))[0]) >>> 1) << 1; // the incidental bit (not belonging to result) zeroized by shifting, ready to be the new parity bit 
	}
	DES_set_odd_parity(&result);
	return result;
}
```

### Steps to reproduce

Use any card that is served by card-myeid-driver (it's currently the only one that calls _sc_card_add_symmetric_alg; or extend any other driver code and profile as required for card that is capable to deal with DES and/or 3DES) and execute: pkcs15-init --store-secret-key file --secret-key-algorithm des --auth-id 01 --id 03 (adapt the store-secret-key/auth-id/id arguments as appropriate and provide 8 bytes in file as key, the last byte being e.g. 0xFF as sentinel; or adapt for 3des key type accordingly).
opensc-debug.log will reveal the first 7 bytes from file (and no more !) to be written, and (correctly) not the sentinel.

More details in my Problem Description

Thanks for Your attention,
carblue

**Comment by carblue** [comment]
correction to the above:
all mention of des/key_length with key_length>64 : correct/read as 3des/key_length

**Comment by carblue** [comment]
correction to the above:
My statement: "The driver has no influence on what goes into SKDF" is wrong. Due to the pointer arguments a driver still has influence on a new SKDF entry and can prevent a wrong value for key length.
Thus the question arises, where key transformation and key length correction shall be done if required: In pkcs15-init or any card's driver that is prepared to do it?

### Steps to reproduce
should also include inspecting opensc-debug.log what get's written to SKDF.

**Comment by frankmorgner** [comment]
There was some discussion in https://github.com/OpenSC/OpenSC/pull/1025.

@fabled, can you help?

**Comment by fabled** [comment]
Inconsistency between different DES lengths 56 bits as without parity bits vs. 128/192 as with parity was unintended. Probably due to reading some documentation with similar inconsistency. I am not sure what the original PKCS#15 requires us to do here - the algorithm identifying SecretKey types were removed/obsoleted in ISO/IEC 7816-15. MyEID also seems internally want 8 bytes for "56 bit" des keys. If your card does that too, it might be a good way to go. Even better if we find a proper SKDF dump describing valid DES key.

But I would be OK to remove "des/56" and replace it universally with "des/64".

**Comment by carblue** [comment]
@fabled

Your MyEID card, my ACOS5-64 card and probably any card out there expects to receive 8 bytes from tool pkcs15-init when specifying --secret-key-algorithm des; the new default value 64 in alg_types_sym for des (I think we agree about this) will reflect that and the inconsistancy is removed.

In card-myeid.c, if the driver doesn't care for 7->8 byte transformation, You/whoever will replace
   _sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 56, flags);
by _sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 64, flags);
and it will work as expected.

des, 3des and aes are the 3 cases without specifying key_length and the user of pkcs15-init gets written to the card what intuitively expected (supposed check_key_compatibility says okay);

The only other 'regular' use cases - now with specifying key_length - are 3des/128, and (the NIST selected) aes/192, aes/256 (all these mentioned so far are possible sym./secret keys for ACOS5-64).

The 'irregular' use cases, specifying key_length for des or 3des, that are not a multiple of 8 bytes/64 bits, and not intended by You, originating from 'effective==without parity bits' key material:
Are You going to keep or remove them?

I plead for keeping the 'irregular' use cases and would still like to call in my card driver's init function:
```
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   56, flags); // driver has to transform  7 bytes receivable to  8 bytes key length
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   64, flags); // driver processes  8 bytes receivable as given

_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 112, flags); // driver has to transform 14 bytes receivable to 16 bytes key length
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 128, flags); // driver processes 16 bytes receivable as given
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 168, flags); // driver has to transform 21 bytes receivable to 24 bytes key length
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 192, flags); // driver processes 24 bytes receivable as given

_sc_card_add_symmetric_alg(card, SC_ALGORITHM_AES,  128, flags); // driver processes 16 bytes receivable as given
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_AES,  192, flags); // driver processes 24 bytes receivable as given
_sc_card_add_symmetric_alg(card, SC_ALGORITHM_AES,  256, flags); // driver processes 32 bytes receivable as given
```

Rethinking that (whereto I originally stated "doesn't feel the right way to me") , it may be seen as a feature of a/my driver:
If a card calls e.g.  _sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 56, flags);
it thereby explicitly declares, that it will accept 7 bytes (only) for des from pkcs15-init and handle everything required (like additional parity bits) for a valid 8 byte odd-parity des key on it's own (including correct key_length for SKDF).
No change to pkcs15-int/parse_alg_spec (except those proposed in the following) is required, the burden is with the driver, though I imagine, if used by several drivers, common code may later be factored out to an opensc function.

The current situation is, whatever is specified as key_length, it will be passed to the card as long as the card "registers" for that.
Putting it to some extreme, des/99 is possible when "registering" by _sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 99, flags);
and the card can expect 13 bytes receivable

Thus the only other enhancement I can think of currently for pkcs15-int/parse_alg_spec referring to secret keys:
I propose *keybits to be checked as a multiple of 8 bits (bytes shall be read from file and all secret key's key_length in bits are multiples of 8).
I propose *keybits to be checked against a maximum value depending on algorithm:
des:  *keybits<=64
3des: *keybits<=192
aes:  *keybits<=256

An enhancement for all card drivers storing des/3des keys, might be correcting wrong parity input and refusing weak/semi-weak key storage (I remember having had problems with acos in this regard; openssl has functions DES_set_odd_parity, DES_check_key_parity, DES_is_weak_key).

I can't comment referring to ISO/IEC 7816-15: I don't have it, I'm working with old, publicly available PKCS#15 docs from RSA, but not in-depth regarding secret keys.

**Comment by dengert** [comment]
Sorry for late reply.

See below PKCS\#15: "The **optional** keyLen field signals the key length used, in those cases where a particular algorithm can have a varying key length." DES does not, it is 8 bytes.

 Looking at PKCS`#11  versions 2.01 (1997) to 2.40 (2014) all say: "DES keys must always have their parity bits properly set as described in FIPS PUB 46-3. Attempting to create or unwrap a DES key with incorrect parity will return an error." Similar wording for DES2 and DES3. (V2.40 appears to have dropped some of the wording for CKK_DES as DES is not considered secure.) DES, DES2 and DES3 are 8, 16 and 24 bytes long and include valid parity. 

The point being DES has always always been 8 bytes with parity. (Even 40 bit DES was 8 bytes long.)
The 56 or 40 is really strength comparison and not the size of the key. 

PKCS\#15 V1.1 (2000) also says: "In other words, in the IC card case, each EF(SKDF) shall consist of a number of context tagged elements representing different secret keys. Each element shall consist of a
number of common object attributes (CommonObjectAttributes, CommonKeyAttributes and
CommonSecretKeyAttributes) and in addition the particular secret key type’s attributes. All
key types defined in this version correspond to key types defined in PKCS #11, and they
all contain the same attributes, GenericSecretKeyAttributes, defined below."

So how the use of 7 bytes crept into the code is not from PKCS\X11 or PKCS\#15.

The only places you get to specify the size of a key is in the size of the OCTET STRING:
```
GenericSecretKeyAttributes ::= SEQUENCE {
      value ObjectValue { OCTET STRING },
      ... -- For future extensions
      }
```
and in the optional keyLen in bits:
```
CommonSecretKeyAttributes ::= SEQUENCE {
          keyLen INTEGER OPTIONAL, -- keylength (in bits)
```
That also says:  "The **optional** keyLen field signals the key length used, in those cases where a particular algorithm can have a varying key length."  But DES, DES2 and DES3 are fixed length. 

So if your card really wants 7 byte DES keys, that should be up to the card driver to add/remove the parity bits as needed. 

I do not see any PKCS\#11 or PKCS\#15 code to add parity bits for DES. That has always been upto the caller to pass in valid parity for DES keys.

**Comment by carblue** [comment]
Perhaps my input so far was befuddling, such that this issue didn't make progress within almost 2 years: So I will resume:

The core problem is, that only the second of following invocations succeeds, but not the first one, though both should be treated identically by OpenSC:
```
user@host:~$ pkcs15-init --store-secret-key file.hex --auth-id 01 --id 09 --secret-key-algorithm des
Using reader with a card: ACS CryptoMate64 00 00
Failed to store secret key: Key length/algorithm not supported by card
user@host:~$ pkcs15-init --store-secret-key file.hex --auth-id 01 --id 09 --secret-key-algorithm des/64
Using reader with a card: ACS CryptoMate64 00 00
user@host:~$ 
```

If I add 
```
_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   56, 0);
```
to the existing code in acos5_init (https://github.com/carblue/acos5):
```
_card_add_symmetric_alg(card, SC_ALGORITHM_DES,   64, 0);
_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 128, 0);
_card_add_symmetric_alg(card, SC_ALGORITHM_3DES, 192, 0);
```
then also the invocation with option '--secret-key-algorithm des' succeeds, but that may/does raise a second problem: Only 7 bytes got read now from file.hex, and a card driver - that doesn't handle this - has stored a broken DES key and a broken SKDF entry with key_length 56.
Currently the card-myeid.c exposes that problem !

I'll tackle the first problem by a PR changing the default from 56 to 64 for spec des  in `static const struct alg_spec alg_types_sym[]`.

@frankmorgner
I'm not a maintainer of card-myeid.c, but on behalf of those I'll also submit a PR removing the current problem with 56/64 from card-myeid.c, changing from
```
		if (card_caps.max_des_key_length >= 56)
			_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 56, flags);
```
to
```
		if (card_caps.max_des_key_length >= 64)
			_sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 64, flags);
```
That should by revised.

**Comment by dengert** [comment]
@carblue  said:
"Only 7 bytes got read now from file.hex, and a card driver - that doesn't handle this - has stored a broken DES key and a broken SKDF entry with key_length 56.
Currently the card-myeid.c exposes that problem !"

Are there cards in the field where only 7 bytes were read and written to the card? 

The key has to be in the possession of some other party which should have the correct 8 byte key with correct parity. If the card accepted only 56 bits, there does not appear to be anyway these keys could be used. It would be missing the last byte with 7 bits of key (and parity bit) that the other party has. (Only if two cards have the same 7 bytes and the cards added the same last byte could they be used to encrypt/decrypt. And it may not be secure and parity bits may be wrong too and if the card used the 7 parity bits as key bits, you really have only 56-7=49 bits of key. 

DES is not secure. On "19 May  2005  NIST withdraws FIPS 46-3" and as noted in many standard documents DES has been dropped. 

So why are we so concerned about DES? Or even a less secure 49 bit DES?

**Comment by carblue** [comment]
@dengert 
"DES is not secure": You and I know that, but does every OpenSC user who can still use it from OpenSC via card-myeid.c currently?
An even better solution would be to remove DES/SC_ALGORITHM_DES from OpenSC.

I will close this issue latest end of 2019 no matter what happens: My driver actually doesn't expose/use the SC_ALGORITHM_DES algo, nor SC_ALGORITHM_3DES/128.

**Comment by mouse07410** [comment]
@dengert, the correct DES key is indeed 56 bits, not 64 bits (I published papers about DES key schedule in early 90-ties:).

Whether DES is secure or not, is less relevant here. And indeed, DES has been withdrawn wow a while ago - but that doesn't mean you shouldn't interoperate with ancient hardware.

**Comment by dengert** [comment]
Yes 56 bits of key and 8 bits of parity.  But  PKCS15 and PKCS11  say the length is 8 bytes or 64 bits. 
Where the confusion come in is in `_card_add_symmetric_alg'. that has bits.

**Comment by mouse07410** [comment]
I don't recall where the parity bits are coming from. But if the card expects 64 bits - add them in software before passing the key to it. Although I suspect there address cards that want 64 bits, and cards that want 56 bits.

(Apparently, authors of the PKCS standards weren't as well-versed in this add they should've been ;)

**Comment by frankmorgner** [comment]
Requiring a DES key to be 56 or 64 bytes is just a matter of taste. Until looking into `card-myeid.c`, I have personally not seen any implementation that actually takes 56 bit (i.e. 7 bytes) for a DES key. Everyone else uses 64 bits (i.e. 8 bytes).

Whether forcing 56 or 64 bits of input is just a matter of taste, but it's true that OpenSC is inconsistent in this regard right now. Given the fact that even `card-myeid.c` includes the parity bits for 2/3-key-DES by requiring a full 128/192 bit input, we should also include the parity bits in the DES input, i.e. requiring 64 bits input.

So yes, I agree that pkcs15-init should take 64 bits by default. (And `card-myeid.c` should in turn remove the parity bits somewhere in `myeid_generate_store_key()` if needed.) @fabled, would you care to test such a change?

**Comment by popovec** [comment]
MyEID 4.0.1 does not accept 56 bit DES key. Please read comments on #1832. @hhonkanen  can you recheck this with MyEID 4.2 and 4.5 ?

**Comment by hhonkanen** [comment]
@popovec also newer MyEID versions (4.2 and 4.5) require DES keys to be in 64 bit format. I would suggest removing the following lines and allowing only 64 bit input for plain DES:
                if (card_caps.max_des_key_length >= 56)
                        _sc_card_add_symmetric_alg(card, SC_ALGORITHM_DES, 56, flags);

In MyEID plain DES is supported only for backward compatibility, so we have no plans to change anything in its implementation.
