### ISSUE TITLE
Gemalto PC Pinpad not working with OpenPGP card

### ISSUE THREAD

**Issue by amaccuish** [OpenSC/OpenSC#1221]
### Problem Description

The Gemalto PC Pinpad does not supported variable length pins. This has been solved for some card drivers but not for openpgp cards. The gnupg solution is to store the PIN lengths in a DO object on the card. More information can be found here: https://wiki.gnupg.org/CardReader/GemaltoPC

### Proposed Resolution
card-openpgp.c should check for the login-data DO and the specific format if a Gemalto card reader is present.

### Steps to reproduce

1. Perform any operation with pkcs11-tool
2. Error returned is:

```
Using slot 0 with a present token (0x0)
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.

```

Thanks!

**Comment by frankmorgner** [comment]
So your suggestion is to honor the "Login Data" object on the OpenPGP card, which gpg personalizes to configure the PIN properties correctly, right? That's surely reasonable.

Are you planning to implement this feature? (Otherwise, I fear that the combination of an OpenSC developer sharing the same card and reader is near zero...)

**Comment by amaccuish** [comment]
Sadly I don't think I have the necessary skills :( I'll give it a shot but really more happy to help debug.

I tried forcing opensc to always use a length of 6 to test the concept; the reader finally woke up and asked me to enter the PIN, further than I had got before, but then failed with a length error.

**Comment by amaccuish** [comment]
You can see how gnupg did it here: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=scd/app-openpgp.c;h=689d880d492a72d6053ba767d9ace9eafb4d62c5;hb=refs/heads/master

 624 /* GnuPG makes special use of the login-data DO, this function parses
 625    the login data to store the flags for later use.  It may be called
 626    at any time and should be called after changing the login-data DO.
 627 
 628    Everything up to a LF is considered a mailbox or account name.  If
 629    the first LF is followed by DC4 (0x14) control sequence are
 630    expected up to the next LF.  Control sequences are separated by FS
 631    (0x18) and consist of key=value pairs.  There are two keys defined:
 632 
 633     F=<flags>
 634 
 635     Where FLAGS is a plain hexadecimal number representing flag values.
 636     The lsb is here the rightmost bit.  Defined flags bits are:
 637 
 638       Bit 0 = CHV1 and CHV2 are not syncronized
 639       Bit 1 = CHV2 has been set to the default PIN of "123456"
 640               (this implies that bit 0 is also set).
 641 
 642     P=<pinpad-request>
 643 
 644     Where PINPAD_REQUEST is in the format of: <n> or <n>,<m>.
 645     N for user PIN, M for admin PIN.  If M is missing it means M=N.
 646     0 means to force not to use pinpad.
 647 
 648 */

and

 698       else if (buflen > 1 && *buffer == 'P' && buffer[1] == '=')
 699         {
 700           /* Pinpad request control sequence found.  */
 701           buffer += 2;
 702           buflen -= 2;
 703 
 704           if (buflen)
 705             {
 706               if (digitp (buffer))
 707                 {
 708                   char *q;
 709                   int n, m;
 710 
 711                   n = strtol (buffer, &q, 10);
 712                   if (q >= (char *)buffer + buflen
 713                       || *q == '\x18' || *q == '\n')
 714                     m = n;
 715                   else
 716                     {
 717                       if (*q++ != ',' || !digitp (q))
 718                         goto next;
 719                       m = strtol (q, &q, 10);
 720                     }
 721 
 722                   if (buflen < ((unsigned char *)q - buffer))
 723                     break;
 724 
 725                   buflen -= ((unsigned char *)q - buffer);
 726                   buffer = q;
 727 
 728                   if (buflen && !(*buffer == '\n' || *buffer == '\x18'))
 729                     goto next;
 730                   app->app_local->pinpad.specified = 1;
 731                   app->app_local->pinpad.fixedlen_user = n;
 732                   app->app_local->pinpad.fixedlen_admin = m;
 733                 }
 734             }
 735         }

**Comment by amaccuish** [comment]
In addition, there was a patch for the entersafe driver: https://www.mail-archive.com/opensc-devel@lists.opensc-project.org/msg05943.html

Not the best as the PIN is fixed. At least with OpenPGP cards there's a standard way to indicate the lengths of the PINs.

**Comment by amaccuish** [comment]
These changes get the pin pad prompt, and make the OpenSC APDU similar to GPGs, but OpenSC won't add 0x00 padding at the end. 

Here are the APDUs:
TxBuffer (OpenPGP, works): 00 00 82 06 00 10 01 02 01 09 04 00 00 00 0B 0B 00 00 00 00 20 00 82 06 FF FF FF FF FF FF 
TxBuffer (with the changes I now get the PIN prompt, but then CKR_DATA_LEN_RANGE is returned): 1E 1E 82 06 00 10 01 02 01 00 00 00 00 00 00 05 00 00 00 00 20 00 82 00 

	data->pin1.pad_length = 0x08;
	data->pin1.encoding = SC_PIN_ENCODING_ASCII;
	data->pin1.max_length = 0x08;
	data->pin1.min_length = 0x04;
	data->flags = SC_PIN_CMD_NEED_PADDING;

	/* bmFormatString */
	tmp = 0x00;
	if (data->pin1.encoding == SC_PIN_ENCODING_ASCII) {
		tmp |= SC_CCID_PIN_ENCODING_ASCII;

		/* if the effective PIN length offset is specified, use it */
		if (data->pin1.length_offset > 4) {
/*			tmp |= SC_CCID_PIN_UNITS_BYTES; */
...

	tmp = 0x82;
	pin_verify->bmFormatString = tmp;

	/* bmPINBlockString */
...
	tmp = 0x06;
	pin_verify->bmPINBlockString = tmp;
...
	pin_verify->wPINMaxExtraDigit = HOST_TO_CCID_16(0x0110); /* Min Max */

**Comment by amaccuish** [comment]
So this makes it work, however of course it's tied to my reader and an openpgp card. This doesn't read the DO, that's next, however the pinpad works!

/* Build a PIN verification block + APDU */
static int part10_build_verify_pin_block(struct sc_reader *reader, u8 * buf, size_t * size, struct sc_pin_cmd_data *data)
{
	int offset = 0, count = 0;
	sc_apdu_t *apdu = data->apdu;
	u8 tmp;
	unsigned int tmp16;
	PIN_VERIFY_STRUCTURE *pin_verify  = (PIN_VERIFY_STRUCTURE *)buf;

	/* PIN verification control message */
	pin_verify->bTimerOut = 0x00;
	pin_verify->bTimerOut2 = 0x00;

	tmp = 0x82;
	pin_verify->bmFormatString = tmp;

	/* bmPINBlockString */
	tmp = 0x06;
	pin_verify->bmPINBlockString = tmp;

	/* bmPINLengthFormat */
	tmp = 0x00;
	pin_verify->bmPINLengthFormat = tmp;	/* bmPINLengthFormat */

	pin_verify->wPINMaxExtraDigit = HOST_TO_CCID_16(0x0110); /* Min Max */

	pin_verify->bEntryValidationCondition = 0x02; /* Keypress only */

	pin_verify->bNumberMessage = 0x01; /* Default message */

	/* Ignore language and T=1 parameters. */
	pin_verify->wLangId = HOST_TO_CCID_16(0x0409);
	pin_verify->bMsgIndex = 0x00;
	pin_verify->bTeoPrologue[0] = 0x00;
	pin_verify->bTeoPrologue[1] = 0x00;
	pin_verify->bTeoPrologue[2] = 0x00;
	
	/* APDU itself */
	pin_verify->abData[offset++] = apdu->cla;
	pin_verify->abData[offset++] = apdu->ins;
	pin_verify->abData[offset++] = apdu->p1;
	pin_verify->abData[offset++] = apdu->p2;

	pin_verify->abData[offset++] = pin_verify->bmPINBlockString;
	memset(&pin_verify->abData[offset], 0xff, pin_verify->bmPINBlockString);
	offset += pin_verify->bmPINBlockString;

	pin_verify->ulDataLength = HOST_TO_CCID_32(offset); /* APDU size */

	count = sizeof(PIN_VERIFY_STRUCTURE) + offset;
	*size = count;
	return SC_SUCCESS;
}

**Comment by amaccuish** [comment]
Ok so narrowed this down. These changes are needed for the Gemplus Reader and an OpenPGP card:

	data->pin1.encoding   = SC_PIN_ENCODING_ASCII;
	data->pin1.min_length = 4;
	data->pin1.max_length = 8;
	data->pin1.pad_length = 6;
	data->flags |= SC_PIN_CMD_NEED_PADDING;

This could then be wrapped in a check for the reader? Is this acceptable?

**Comment by amaccuish** [comment]
I've implemented this fully now in the proper place (card-openpgp.c). The DO is read and checked for a length. If it's present, we use it. Hopefully this could be merged?

[fixed_length_pin.txt](https://github.com/OpenSC/OpenSC/files/1563420/fixed_length_pin.txt)

**Comment by dengert** [comment]
Does this actually work?
What it looks like is OpenPGP supports padding, yet in http://g10code.com/docs/openpgp-card-2.0.pdf
it does not say it supports padding or not. But uses the Lc for the APDU to contain the length of the PIN or PINs. In 7.2.3 CHANGE REFERENCE DATA it says it does not need padding because:
"The length of the existing password is known in the card, so that neither a delimiter nor padding for filling up fixed formats is necessary." 

So it may work on some cards but not on others that do not support padding. Can you find a reference that says it does support padding?

Did you look at what is the value of card->max_pin_len for your card?

You may still want to set 
data->pin1.min_length = 6;    /* or for P2 8*/ 
as in 7.2.2 Verify it says:
"Lc xx (min. 06 for PW1, min. 08 for PW3, max. see DO ´C4´)"

**Comment by amaccuish** [comment]
Yes it works. I've got OpenSC hooked up to SSH and Firefox and both work great now. When I need to perform an operation, my card reader now lights up and takes my PIN.

I believe the padding is more for the reader, but I could be wrong. Without the padding I received length errors, with padding switched on it all worked. Looking at APDUs generated by gnupg, they also use padding when a reader requiring a fixed length pin is used.

The card->max_pin_len is actually also used in another part of the code that returns the maximum of the card, which for me is 20. However the pinpad reader will not accept a maximum length of more than 8, as listed here: [https://pcsclite.alioth.debian.org/ccid/supported.html#0x08E60x3478](url)

- Does not support minimum PIN length (wPINMaxExtraDigit) lower than 4
- Does not support maximum PIN length (wPINMaxExtraDigit) greater than 8

That's why we should check the login-data object, which people with such readers can use to specify the PIN length, which can be used to choose suitable max/mins and for the padding.

Setting data->pin1.min_length = 6; seems like a good idea, since that will always be the absolute minimum the openpgp card will support anyway. I didn't find anything in reader_pcsc.c that uses the pin2.X, so I just voided that part from the DO and didn't sent anything referencing it.

**Comment by Nosti31** [comment]
Thanks @amaccuish, that works perfect ! Any date to merge this patch ?

**Comment by Jakuje** [comment]
@amaccuish Please, fill a new pull request with that diff. I would also be for moving that code into separate function, ideally out of the `pgp_pin_cmd()` function -- it can be retrieved just once during initialization and the values reused for other PIN prompts (if needed for non-repudiation).

If that is a workaround for specific card reader, do we have a way of detecting it and ignoring it for others?

**Comment by amaccuish** [comment]
@Jakuje so right now it applies to OpenPGP cards that have this specific data object, so the only time this is executed is for users with an OpenPGP card, who have specifically followed the instructions on the gnupgp website for the GemPC reader, to create a DO with the right format. I will test and see if the problem occurs with my Estonian card (for which it would not be possible to store the right values on the card since I don't have write access).

I'll get started also on a PR with it in a separate function.

**Comment by amaccuish** [comment]
fyi the instructions they give are here: https://wiki.gnupg.org/CardReader/GemaltoPC

**Comment by frankmorgner** [comment]
@amaccuish please check if https://github.com/OpenSC/OpenSC/pull/1315 allows you using your reader.
