### ISSUE TITLE
DNIe driver does not load certificates in Firefox

### ISSUE THREAD

**Issue by marcu87** [OpenSC/OpenSC#1223]
Hi, I'm having the exact same problem as https://github.com/OpenSC/OpenSC/issues/451 using Ubuntu 17.04 and the last master version of OpenSC.

I did compiled the software like this:

./configure --exec-prefix=/usr/local --prefix=/usr --enable-dnie-ui --enable-sm

My problem is, from Firefox I can login succesfully, but the certificates are not imported.

I'm lost, should this not be fixed? Anyone facing the same problem nowdays?

Thanks!

**Comment by frankmorgner** [comment]
If it works in `pkcs11-tool --login --test`, it should also work in Firefox. Can you enable debugging `debug = 20;` and send a log? (Remove your PIN from the Log!)

**Comment by frankmorgner** [comment]
How did you fix this?
