### ISSUE TITLE
ECDH key agreement failing with Java Sun PKCS#11 - CKR_KEY_TYPE_INCONSISTENT

### ISSUE THREAD

**Issue by NeilMadden** [OpenSC/OpenSC#1227]
### Problem Description

I originally asked about this issue on the [Nitrokey forum](https://support.nitrokey.com/t/nitrokeyhsm-and-java-sun-pkcs-11/812) and was asked to raise a ticket here. I will raise two tickets for what I believe are two separate issues. This is the first one:

I am trying to perform ECDH key agreement using a static P-256 (secp256r1) private key stored on a Nitrokey HSM via the [Sun Java PKCS#11 provider](https://docs.oracle.com/javase/8/docs/technotes/guides/security/p11guide.html) and the OpenSC 0.17.0 PKCS#11 driver. This is with Java 1.8 on Mac OS X 10.12.6. I perform the key agreement using an ephemeral P-256 public key created either in-memory using the default JDK EC provider, or on-card using the PKCS#11 provider. In both cases the key agreement fails with CKR_KEY_TYPE_INCONSISTENT.

I am able to successfully perform key agreement if I use the JCE provider that ships with Smart Card Shell, so this appears to be some interaction between the Sun PKCS#11 provider and the OpenSC PKCS#11 driver.
 
### Proposed Resolution

Unsure - needs expert investigation. Ideally OpenSC would work out-of-the-box with the built-in Java PKCS#11 provider, but I do not know enough to say if that is achievable.

### Steps to reproduce

1. Install OpenSC 0.17.0 PKCS#11 driver, Java 1.8 from Oracle with Sun PKCS#11 provider, and a NitrokeyHSM device with a NIST P-256 (secp256r1) EC private key with the label "p256".
2. Compile and run the following Java program passing in the HSM user PIN as a command line argument (or modify to read the pin from somewhere secure):

```java
    import java.security.*;
    import java.security.interfaces.*;
    import javax.crypto.*;
    import javax.crypto.spec.*;
    
    import java.util.*;
    import javax.xml.bind.DatatypeConverter;
    
    public class hsm {
    
        public static void main(String...args) throws Exception {
            if (args.length != 1) {
                System.err.println("Usage: java hsm <pin>");
                System.exit(1);
            }
            char[] pin = args[0].toCharArray();
    
            //Security.addProvider(new de.cardcontact.smartcardhsmprovider.SmartCardHSMProvider());
            //Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
            
            // Load the HSM as a PKCS#11 keystore
            System.out.println("Loading keystore");
            //KeyStore hsm = KeyStore.getInstance("SmartCardHSMKeyStore");
            KeyStore hsm = KeyStore.getInstance("PKCS11");
            hsm.load(null, pin);
            Arrays.fill(pin, ' ');
    
            // Load an EC P-256 private key from the keystore
            System.out.println("Loading static ECDH keys");
            Key staticPrivateKey = hsm.getKey("p256", new char[0]); // No password
            Key staticPublicKey = hsm.getCertificate("p256").getPublicKey();
    
            System.out.println("Static Private: " + staticPrivateKey);
            System.out.println("Static Public : " + staticPublicKey);
    
            // Generate an ephemeral key-pair on the device
            System.out.println("Generating ephemeral ECDH keys");
            KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC");
            kpg.initialize(((ECPublicKey) staticPublicKey).getParams());
            KeyPair ephemeralKeys = kpg.generateKeyPair();
    
            System.out.println("Ephemeral Priv: " + ephemeralKeys.getPrivate());
            System.out.println("Ephemeral Pub : " + ephemeralKeys.getPublic());
    
            // Now perform ECDH key agreement between static private and ephemeral public keys
            System.out.println("Performing ECDH key agreement");
            KeyAgreement ecdh = KeyAgreement.getInstance("ECDH", hsm.getProvider());
            ecdh.init(staticPrivateKey);
            ecdh.doPhase(ephemeralKeys.getPublic(), true);
    
            try {
                byte[] sharedSecret = ecdh.generateSecret();
                System.out.println("Derived shared secret: " + DatatypeConverter.printHexBinary(sharedSecret));
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(1);
            }
        }
    }
```

Output:
```
Loading keystore
Loading static ECDH keys
Static Private: SunPKCS11-NitrokeyHSM EC private key, 256 bits (id 140427861996000, token object, sensitive, unextractable)
Static Public : Sun EC public key, 256 bits
  public x coord: 23919995184559860976253713360680914112848079777551416149635514637024520745309
  public y coord: 17120898397917041930631477206293964934850084751907000036557497273114856567487
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Generating ephemeral ECDH keys
Ephemeral Priv: sun.security.ec.ECPrivateKeyImpl@ffffefb4
Ephemeral Pub : Sun EC public key, 256 bits
  public x coord: 42108767978133338221549784299893126415504716108836482249120389112490804088186
  public y coord: 1164207916027692920404281125182054490018062384678274234098212394143804067961
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Performing ECDH key agreement
java.security.ProviderException: Could not derive key
	at sun.security.pkcs11.P11ECDHKeyAgreement.engineGenerateSecret(P11ECDHKeyAgreement.java:144)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:586)
	at hsm.main(hsm.java:52)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_KEY_TYPE_INCONSISTENT
	at sun.security.pkcs11.wrapper.PKCS11.C_DeriveKey(Native Method)
	at sun.security.pkcs11.P11ECDHKeyAgreement.engineGenerateSecret(P11ECDHKeyAgreement.java:133)
	... 2 more
```
### Logs

See https://gist.github.com/NeilMadden/cfdd09ee53f9e12bb19514e86b425925

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by NeilMadden** [comment]
My other issue was with RSA unwrap not working, but I see from the source code that this just isn't implemented at all, so I will not raise a bug for this: https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11-object.c#L1032

**Comment by dengert** [comment]
A SPY trace would help see what is going on. In the OpenSC log, I do not see any attempt to do a C_DeriveKey  and OpenSC does not return CKR_KEY_TYPE_INCONSISTENT to any calls. 

You may want to try look at to get PKCS\#11:calls https://docs.oracle.com/javase/8/docs/technotes/guides/security/p11guide.html#TroubleShoot

And your blog of course:
https://neilmadden.wordpress.com/2016/05/20/ephemeral-elliptic-curve-diffie-hellman-key-agreement-in-java/

Is it possible that  `KeyAgreement.getInstance("ECDH", hsm.getProvider());` is not providing the correct provider? But providing a secret key derive, rather than ECDH1. Also how do you specify the  CK_EC_KDF_TYPE? 

PKCS\#11 2.40 has this footnote in 2.3.8 EC mechanism parameters:
"1 The encoding in V2.20 was not specified and resulted in different implementations choosing different encodings. Applications relying only on a V2.20 encoding
(e.g. the DER variant) other than the one specified now (raw) may not work with all V2.30 compliant tokens.

**Comment by dengert** [comment]
Here is one more possibility. With EC keys, The private key may not have the EC parameters. So you may need to use the https://docs.oracle.com/javase/8/docs/api/java/security/KeyPair.html KeyPair to combine them both. 
`ecdh.init(KeyPair(staticPrivateKey, staticPublicKey));`
(If my Java is correct.)

**Comment by CardContact** [comment]
I've tried it with the JCEProvider and it worked as expected.

```
Loading keystore
Loading static ECDH keys
Static Private: Label=Joe Doe (ECC-SECP256), KeyID=2, Size=256 bits
Static Public : EC Public Key
            X: bea5ed2ef34b23e0c9971a202b0ada5a206f8211f6a480c8200ebb97891b1fa9
            Y: dbba5a9158a304a1608a1fdb42591360fd37257f45df8c0fb386ea1217ee0e7

Generating ephemeral ECDH keys
Ephemeral Priv: sun.security.ec.ECPrivateKeyImpl@37d1
Ephemeral Pub : Sun EC public key, 256 bits
  public x coord: 113059443468351265291203160559273294169653299911116207318166106260997710481459
  public y coord: 41952920334797325830034476320969269642937943572533643235628014685908791666609
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Performing ECDH key agreement
Derived shared secret: 04EA8536EB1A5904AA31A9207511CFECBB2357572696F35BEBD9808A41EB6F0113517A2CB38F1E816F81B3A574ECC55EB46D033A32A099742D6A04E2DD4E872D94
```

I've generated the EC key and certificate using the [testcert](https://github.com/CardContact/scsh-scripts/blob/master/sc-hsm/examples/issuecert.js) script.

**Comment by NeilMadden** [comment]
@CardContact yes, I already tried with the custom JCEProvider and verified that it works there (see original bug description). But most of our customers will just use the built-in PKCS#11 provider, so it would be good to ensure it works with that too if possible.

@dengert The KeyAgreement init() method requires an argument of type java.security.Key, and java.security.KeyPair does not implement that interface. In practice the Sun PKCS#11 implementation wants an ECPrivateKey for that method. At the point it is failing it has both a private and a public key available though, so it should be able to perform the operation.

You can see the parameters that the Sun provider uses here (this is a Java wrapper, but the constants should make sense): http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/security/pkcs11/P11ECDHKeyAgreement.java#P11ECDHKeyAgreement.engineGenerateSecret%28%29

```java
            CK_ATTRIBUTE[] attributes = new CK_ATTRIBUTE[] {
                new CK_ATTRIBUTE(CKA_CLASS, CKO_SECRET_KEY),
                new CK_ATTRIBUTE(CKA_KEY_TYPE, CKK_GENERIC_SECRET),
            };
            CK_ECDH1_DERIVE_PARAMS ckParams =
                    new CK_ECDH1_DERIVE_PARAMS(CKD_NULL, null, publicValue);
            attributes = token.getAttributes
                (O_GENERATE, CKO_SECRET_KEY, CKK_GENERIC_SECRET, attributes);
            long keyID = token.p11.C_DeriveKey(session.id(),
                new CK_MECHANISM(mechanism, ckParams), privateKey.keyID,
                attributes);
```

NB: `mechanism` here is initialised to `CKM_ECDH1_DERIVE`.

So it is using `CKD_NULL` as the `CK_EC_KDF_TYPE`, which is what I would expect (Java's KeyAgreement.generateSecret() is documented as returning the raw shared secret).

Aha! This has made me realise what the issue might be though. The derived key of class CKO_SECRET_KEY and type CKK_GENERIC_SECRET is not supported by NitrokeyHSM, as it only supports RSA and EC keys. They claim to support ECDH though, so presumably that must work somehow? 

If I run the test with Java PKCS#11 debugging enabled (thanks for the hint) we can see that the provider is first probing the driver to see what mechanisms it supports. It looks like it never actually attempts the `C_DeriveKey` call—presumably the wrapper is already determining that the derived key type is not supported and so not trying it at all. I'll see if I can dig out the native source code.

```
$ java -Djava.security.debug=sunpkcs11 ecdh 210118
Loading keystore
SunPKCS11 loading /Users/neil/hsm.conf
sunpkcs11: Initializing PKCS#11 library /usr/local/opt/opensc/lib/opensc-pkcs11.so
Information for provider SunPKCS11-NitrokeyHSM
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.17
All slots: 0
Slots with tokens: 0
Slot info for slot 0:
  slotDescription: Nitrokey Nitrokey HSM                                           
  manufacturerID: Nitrokey                        
  flags: CKF_TOKEN_PRESENT | CKF_REMOVABLE_DEVICE | CKF_HW_SLOT
  hardwareVersion: 1.01
  firmwareVersion: 0.00
Token info for token in slot 0:
  label: UserPIN (SmartCard-HSM)         
  manufacturerID: www.CardContact.de              
  model: PKCS#15 emulated
  serialNumber: DENK0100908     
  flags: CKF_RNG | CKF_LOGIN_REQUIRED | CKF_USER_PIN_INITIALIZED | CKF_TOKEN_INITIALIZED
  ulMaxSessionCount: CK_EFFECTIVELY_INFINITE
  ulSessionCount: 0
  ulMaxRwSessionCount: CK_EFFECTIVELY_INFINITE
  ulRwSessionCount: 0
  ulMaxPinLen: 15
  ulMinPinLen: 6
  ulTotalPublicMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePublicMemory: CK_UNAVAILABLE_INFORMATION
  ulTotalPrivateMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePrivateMemory: CK_UNAVAILABLE_INFORMATION
  hardwareVersion: 24.13
  firmwareVersion: 2.05
  utcTime: 
Mechanism CKM_SHA_1:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA256:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA384:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA512:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_MD5:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_RIPEMD160:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism Unknown 0x0000000000001210:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_ECDSA:
  ulMinKeySize: 192
  ulMaxKeySize: 320
  flags: 30410753 = CKF_HW | CKF_SIGN | CKF_EC_F_P | CKF_EC_ECPARAMETERS | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDSA_SHA1:
  ulMinKeySize: 192
  ulMaxKeySize: 320
  flags: 30410753 = CKF_HW | CKF_SIGN | CKF_EC_F_P | CKF_EC_ECPARAMETERS | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDH1_COFACTOR_DERIVE:
  ulMinKeySize: 192
  ulMaxKeySize: 320
  flags: 30932993 = CKF_HW | CKF_DERIVE | CKF_EC_F_P | CKF_EC_ECPARAMETERS | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDH1_DERIVE:
  ulMinKeySize: 192
  ulMaxKeySize: 320
  flags: 30932993 = CKF_HW | CKF_DERIVE | CKF_EC_F_P | CKF_EC_ECPARAMETERS | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_EC_KEY_PAIR_GEN:
  ulMinKeySize: 192
  ulMaxKeySize: 320
  flags: 30474241 = CKF_HW | CKF_GENERATE_KEY_PAIR | CKF_EC_F_P | CKF_EC_ECPARAMETERS | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_RSA_X_509:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10753 = CKF_HW | CKF_DECRYPT | CKF_SIGN | CKF_VERIFY
Mechanism CKM_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10753 = CKF_HW | CKF_DECRYPT | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA1_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA256_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA384_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA512_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_MD5_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_RIPEMD160_RSA_PKCS:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 10240 = CKF_SIGN | CKF_VERIFY
Mechanism CKM_RSA_PKCS_KEY_PAIR_GEN:
  ulMinKeySize: 1024
  ulMaxKeySize: 2048
  flags: 65536 = CKF_GENERATE_KEY_PAIR
sunpkcs11: login succeeded
Loading static ECDH keys
Static Private: SunPKCS11-NitrokeyHSM EC private key, 256 bits (id 140554127039168, token object, sensitive, unextractable)
Static Public : Sun EC public key, 256 bits
  public x coord: 23919995184559860976253713360680914112848079777551416149635514637024520745309
  public y coord: 17120898397917041930631477206293964934850084751907000036557497273114856567487
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Generating ephemeral ECDH keys
Ephemeral Priv: sun.security.ec.ECPrivateKeyImpl@ffffefaf
Ephemeral Pub : Sun EC public key, 256 bits
  public x coord: 34803811340908410975352660460047930787112640920533957256718234154400925851826
  public y coord: 46284418886604911738067988014486748822464388900520542716448343547253098485393
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
Performing ECDH key agreement
java.security.ProviderException: Could not derive key
	at sun.security.pkcs11.P11ECDHKeyAgreement.engineGenerateSecret(P11ECDHKeyAgreement.java:144)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:586)
	at ecdh.main(ecdh.java:52)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_KEY_TYPE_INCONSISTENT
	at sun.security.pkcs11.wrapper.PKCS11.C_DeriveKey(Native Method)
	at sun.security.pkcs11.P11ECDHKeyAgreement.engineGenerateSecret(P11ECDHKeyAgreement.java:133)
	... 2 more
```

**Comment by metsma** [comment]
Try to add this to java config, this fixes EstEID key derive
```
attributes(*,CKO_SECRET_KEY,*) = {
  CKA_TOKEN = false
}
```

**Comment by NeilMadden** [comment]
@metsma Just tried, makes no difference.

**Comment by metsma** [comment]
anything in opensc log?

**Comment by dengert** [comment]
See: https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC
to turn on OpenSC debugging and OPenSC SPY  PKCS\#11 debugging.

SPY would pin down if the problem is in Java or OpenSC. 




 

And also turn on OpenSC debugging. Same URL.

**Comment by dengert** [comment]
For what it is worth, using a PIV with ECDH shows these mechananisms 

pkcs11-tool -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  ECDSA, keySize={256,384}, hw, sign, other flags=0x1800000
  ECDH1-COFACTOR-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  ECDH1-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  RSA-X-509, keySize={1024,3072}, hw, decrypt, sign, verify
  RSA-PKCS, keySize={1024,3072}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA256-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA384-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA512-RSA-PKCS, keySize={1024,3072}, sign, verify
  MD5-RSA-PKCS, keySize={1024,3072}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={1024,3072}, sign, verify

The other flags are: 
CKF_EC_UNCOMPRESS	(1UL << 24)
CKF_EC_NAMEDCURVE	(1UL << 23)

The PIV only supports named curves, thus 
CKF_EC_F_P and   CKF_EC_ECPARAMETERS are not set

**Comment by NeilMadden** [comment]
I'm very sorry - I've worked out the problem, and it is my fault entirely! It seems when I initially generated the key (also via the Sun PKCS#11 interface) it was generated with only `CKA_SIGN` and *not* `CKA_DERIVE`. Oh dear...

After adding the following to my Java PKCS#11 configuration and re-generating the key, everything now works perfectly. Please feel free to close this issue as a "PEBKAC"

```
attributes(*,CKO_PRIVATE_KEY,CKK_EC) = {
    CKA_DERIVE = true
    CKA_SIGN = true
}
```

**Comment by NeilMadden** [comment]
@metsma Thank you, by the way - after I fixed the "derive" bit on my key, then I do indeed need your fix to ensure secret keys are not created on the token for ECDH derive to work.
