### ISSUE TITLE
Using OpenSC over OpenSC.tokend does not cache PIN

### ISSUE THREAD

**Issue by dfuhrmann** [OpenSC/OpenSC#1229]
### Problem Description

I'm using macOS 10.13.2 and the OpenSC 0.17.0 release from this site.
On the card (in this case Yubikey 4) there is a private key stored, which I want to use for codesign operations with the macOS codesign tool. This tool can only access the key on the card over the OpenSC.tokend bridge, by using the entries populated to the mac OS keychain.

This setup works as expected for single signing operations. Before the signing, the OS keychain (?) pops up a UI prompt asking for the PIN to authorize the operation.
Now, hundreds of files need to be signed one by one with the codesign tool, and for each file, the UI prompt popups again asking for the PIN. This makes the usage of the card practically useless, as one cannot enter the PIN hundrets of times. So far, there seem to be no way to pass the PIN on command line.

Yubikeys page describes usage of different slots here: https://developers.yubico.com/PIV/Introduction/Certificate_slots.html
The private key is stored in slot 9a on purpose (and not in slot 9c), to allow PIN caching as described: "Once the PIN has been provided successfully, multiple private key operations may be performed without additional cardholder consent."

### Steps to reproduce
- Setup keys and certificate on yubikey slot 9a
- in opensc.conf, use_pin_caching is set to true and pin_cache_counter is set to 50
- other settings are left to default
- try to codesign 2 files: `codesign -s "identity" -f testfile testfile2`
- It is expected to enter the PIN only once, but the PIN needs to be entered twice, for each sign operation

### Logs
Output of debug log with debug level 3 can be found here. It should show the two codesign operations as described above:
https://gist.github.com/dfuhrmann/ed3ee1bbf286304959805c3bf2051c5f

**Comment by dengert** [comment]
I don't see the pin ever sent to the card, and don't see two sets of calls to opensc, only one. 

Is the problem that opensc.tokend just assumes that a pin is needed? 

The prompt may be from opensc.tokend which prompts every time it is called without checking the state of the card.  @mouse07410 ?  It starts over every time and loses any cached pin. 

Opensc.conf has
 `# disconnect_action = unpower;` 
 read the comments above this and try 
`disconnect_action = leave;` (no \# and chang to leave)
This may allow for one application to verify the pin once and leave the card in the logoed in state. 

There is another option that might work if opensc. tokend only prompts for a PIN if needed. The 9E key and associated certificate can be used without the PIN. NIST defined it that way so the the card could authenticate the card to the host rather than the user. NIST policy define how his should be used. 
OpenSC supports this via PKCS\#11 but not clear if OpenSC.tokend does.   If OpenSC sees that the card has a non-government CHUID (which it looks like is true in your log), the keyUsage is taken from the certificate so the keyUsage could be for code signing. 

 **USING THE 9E KEY THIS WAY COULD BE A SECURITY RISK** Anyone with physical access to the computer could remove the card and uses in a different computer to do code signing. Anyone who could login to the computer could also use the card without a PIN.  

(This is a repost of a comment I thought I sent earlier today but do not see.)

**Comment by mouse07410** [comment]
For the signing key (slot 9c, `SIGN%20key`) `ALWAYS_AUTHENTICATE` is usually set. Definitely so for Yubikey tokens. The implication is that *every* time an operation with this key is requested, PIN verification has to be done a-fresh. 

When the key is in 9a (which is *not* a good idea, IMHO, but...) I don't know, unless it's been set with `ALWAYS_AUTHENTICATE` (@dengert what's the best way to tell if it's the case?).

Regarding OpenSC.tokend - my fork diverged, and I didn't keep track of the mainstream well enough to know for sure whether it works OK with PIV tokens, or not.

Try this: find the line `#pin_cache_ignore_user_consent = ...;` in `/Library/OpenSC/etc/opensc.conf`, uncomment it and change to
```
   pin_cache_ignore_user_consent = true;
```

Let us know whether that helped with your problem.

**Comment by dengert** [comment]
@mouse07410 
Yubico has a way to set which keys require `ALWAYS_AUTHENTICATE` or no PIN but the OpenSC PIV driver justs assumes the token is following the NIST standard which is the default for the Yubkey. So 9C is `ALWAYS_AUTHENTICATE`, 9E requires no pin and the others require the pin to have been entered once. 

If you look at the opensc log, you will see that the pin was never given to the opensc code. And I don't see it in the opensc.tokend either. Better debug logs are needed to track down where and why the prompt for the pin is done. I suspect it is opensc.tokend is doing it each time the  token is used. 

I do not have a Mac so can not test the opensc.tokend.

**Comment by dfuhrmann** [comment]
> the keyUsage is taken from the certificate so the keyUsage could be for code signing.

Key usage looks like this, so this could be the case indeed:
```
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: critical
                Code Signing
```

I moved the private key + certificate to slot 9e for testing, and even here a PIN is required every time. Maybe your assumption is right that the card slot just does not matter here with this certificate?

I understand that the PIN should be entered every time for code signing, main problem is that there is just no command line option or otherwise automated way to pass the PIN.

I also tried to set `disconnect_action = leave;` (default was reset), no change here.
Setting `pin_cache_ignore_user_consent = true;` does not help either.

After all changes above, I tried signing 3 files again with one command, and signing 1 additional file with an extra command call, here is the resulting log:
https://gist.github.com/dfuhrmann/fa9f81cf7013ee99ea52f4f667fa136a

**Comment by mouse07410** [comment]
> Yubico has a way to set which keys require `ALWAYS_AUTHENTICATE` or no PIN, but the OpenSC PIV driver justs assumes the token is following the NIST standard which is the default for the Yubkey.

I see. But I don't know how @dfuhrmann put the key on the token in the first place.

> Key usage looks like this...

That's now what I'd like to see. What I'm asking is something like this:
```
$ p11tool --login --list-all "pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;token=Uri%20the%20Great"
Enter PIN: 
Re-using cached PIN for token 'Uri the Great'
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=xxxxxx;token=Uri%20the%20Great;id=%01;object=PIV%20AUTH%20key;type=private
	Type: Private key
	Label: PIV AUTH key
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 01
. . . . .
Object 28:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=xxxxxx;token=Uri%20the%20Great;id=%02;object=SIGN%20key;type=private
	Type: Private key
	Label: SIGN key
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_ALWAYS_AUTH; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 02
. . . . .
```

Also, I wonder how you informed MacOS of the signer identity, i.e., what value you have with `-s ...` flag (that probably won't help solving this problem, asking for myself to duplicate your experiment).

**Comment by dengert** [comment]
@dfuhrmann,  The logs you have sent do not show any prompts for pins and it appears to be cut short. 
This appears to not be a pin caching problem, but a problem of opensc.tokend or the codesign doing the prompt for each operation. Thus the OpenSC pin caching never gets used. 

Also did you try and obfuscate the certificate but replacing parts of it with ...?


@mouse07410, 
The issue does not appear to be the certificate, but how opensc.tokend may prompt before ever knowing if a pin is needed or not.

**Comment by mouse07410** [comment]
@dengert, I'm trying to understand what flags have been set on the *private keys* on the token in question. Don't care for certificates at the moment (that would probably come later).

@dfuhrmann please try to answer my questions. Also, you might want to try my fork of the token https://github.com/mouse07410/opened.tokend.git . Build it yourself with the current OpenSC master, rather than using the pre-built 0.17 binaries. If after all that it still doesn't work - change PIN to something like 12345678 and post log with DEBUG=9.

**Comment by dfuhrmann** [comment]
@mouse07410 I followed the following guide to copy the certificate + key on the token: https://developers.yubico.com/PIV/Guides/Mac_code_signing.html
So I used:
```
yubico-piv-tool -s 9e -a import-key -i key.pem
yubico-piv-tool -a import-certificate -s 9e -K DER -i mac_app.cer
```
Listing the items with p11tool does not show any special flags:
```
$ p11tool --list-tokens
Token 2:
	URL: pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV
	Label: YubiKey PIV
	Type: Hardware token
	Manufacturer: Yubico
	Model: YubiKey YK4
	Serial: 1234
	Module: libykcs11.so

$ p11tool --login --list-all "pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV"
Token 'YubiKey PIV' with URL 'pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV' requires user PIN
Enter PIN: 
[Omitting the unknown types which are the empty slots]
Object 29:
	URL: pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=X.509%20Certificate%20for%20Card%20Authentication%00;type=cert
	Type: X.509 Certificate
	Label: X.509 Certificate for Card Authentication
	ID: 01

Object 30:
	URL: pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=Private%20key%20for%20Card%20Authentication%00;type=private
	Type: Private key
	Label: Private key for Card Authentication
	ID: 01

Object 31:
	URL: pkcs11:model=YubiKey%20YK4;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=Public%20key%20for%20Card%20Authentication%00;type=public
	Type: Public key
	Label: Public key for Card Authentication
	ID: 01
```

> Also, I wonder how you informed MacOS of the signer identity

I'm testing with a developer certificate from apple, so the codesign command could be `codesign -s "Mac Developer" -f testfile testfile2`. But any (sub)string should work which uniquely points to the certificate. If you have an apple developer account, you should be able to reproduce by following the steps in the yubico document linked above, and requesting a Mac Developer certificate from Apple.

> This appears to not be a pin caching problem, but a problem of opensc.tokend or the codesign doing the prompt for each operation.

The prompt comes from a process named coreautha, which seems to be part of macs security or keychain frameworks.

>Build it yourself with the current OpenSC master

I'll try that later.

In any way, thanks for the help.

**Comment by mouse07410** [comment]
> Listing the items with p11tool does not show any special flags:...

Your listing does not show the one item that matters - your **private key** at the slot 9e (or wherever you placed it).

So please:
1. Do **not** use the buggy Yubico YKCS11 library - use OpenSC `opensc-pkcs11.dylib` (or `opensc-pkcs11.so`) instead.
2. Re-do the `p11tool --login --list-all ...` part. Unless/until you get objects with `Type: Private key`, there's nothing to talk about.

**Comment by dfuhrmann** [comment]
Here is the output with opensc-pkcs11.dylib:
```
$ p11tool --provider /usr/local/lib/opensc-pkcs11.so --login --list-all "pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=5df55f53c1412841;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29"
Token 'PIV Card Holder pin (PIV_II)' with URL 'pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=5df55f53c1412841;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=5df55f53c1412841;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%01;object=PIV%20AUTH%20key;type=private
	Type: Private key
	Label: PIV AUTH key
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 01

Object 1:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=5df55f53c1412841;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%01;object=PIV%20AUTH%20pubkey;type=public
	Type: Public key
	Label: PIV AUTH pubkey
	Flags: CKA_WRAP/UNWRAP; 
	ID: 01
```

Regarding the overall issue, I tried to compile the newest master from @mouse07410 repo, and tried to get more logs. After digging around more, I finally found out that the actual sign request was handled through apples PIV token (com.apple.CryptoTokenKit.pivtoken), not even OpenSC. I am very sorry for that, it explains why you found log entries missing.

Afterwards, I tried to run it through OpenSC.tokend (both stable and newest compiled version).
Once I disabled Apples implementation with `sudo defaults write /Library/Preferences/com.apple.security.smartcard DisabledTokens -array com.apple.CryptoTokenKit.pivtoken`, I found out signing was not working at all with OpenSC.tokend, similar to the report here: https://github.com/OpenSC/OpenSC/issues/1210
codesign was returning -1, and the mac logging output contained error CSSMERR_CSP_ACL_ENTRY_TAG_NOT_FOUND.

Finally, I tried to compile the CryptoTokenKit wrapper from here: https://github.com/frankmorgner/OpenSCToken
This indeed worked with codesign, and indeed, this wrapper respected the slot specifications (requesting the PIN once for slot 9a, 9e, always for 0c and never for 9e).
So import the certificate into slot 9a, and codesign only asks for the PIN once and signs the other artefacts without repeated PIN dialog. I needed to plug in the key twice in a row sometimes, I am also not sure if or what of the opensc.conf settings apply here for this plugin.

**Comment by mouse07410** [comment]
Great! Could you please show how *exactly* you specified your certificate/identity on the token for the `codesign`?

**Comment by dfuhrmann** [comment]
@mouse07410 I used `codesign -s "Mac Developer: Dav Fuhrmann" -f testfile1` for signing (as I said, its for testing only). Codesign tries to find a certificate with matching common name in keychain. Then it uses the associated private key for signing.

There is nothing you can change on the fields of the certificate itself, this is fully generated / forced by the apple server.

**Comment by mouse07410** [comment]
> this is fully generated / forced by the apple server while its signs the certificate request

I see, thanks. *I still think they're screwing up by forcing certificate processing to abort if these extensions aren't recognized, but that's their problem.*

**Comment by frankmorgner** [comment]
@dfuhrmann does the error description still apply? In the above thread looks like it's only a misconfiguration of the card...

**Comment by dfuhrmann** [comment]
@frankmorgner Regarding the actual use of OpenSC with Opensc.tokend, I cannot verify if the bug description still applies or not. I'm still stuck a step before with the error as in #1210.

So I would propose to close this bug for now.
