### ISSUE TITLE
[feat-request] eid-env support for other EU countries

### ISSUE THREAD

**Issue by jarodium** [OpenSC/OpenSC#1236]
### Problem Description
I would like to request that eid-env could be able to work with other EU countries besides Estonia and Belgium.

**Comment by frankmorgner** [comment]
Could you please be more specific on what you're missing (data/card)?

**Comment by jarodium** [comment]
Portuguese Eid for example

**Comment by frankmorgner** [comment]
did you try `pkcs15-tool --list-data-objects`?

**Comment by jarodium** [comment]
Yes. It works as it should. But from the source code ( https://github.com/OpenSC/OpenSC/blob/master/src/tools/eidenv.c#L411 ) I can see there is only support for the Belgian and Estonian ( i think ) Eids.

**Comment by frankmorgner** [comment]
`eidenv` is broken. It works completely different for estid and beid and lacks documentation. You're better off using `pkcs15-tool` using your shell to parse the output.

**Comment by frankmorgner** [comment]
If you want to unify its usage (and add the portuguise id), you're welcome. Otherwise, I think that nobody will do this.

**Comment by martinpaljak** [comment]
The original goal of eidenv was to be able to integrate in a "unixy way" with an eID card (the wait option and using environment variables for key-value pairs) and was done for Estonian eID. The data on the card, how to read it, how and what to export, varies enormously.

One way to unify it would be to have key-value pairs for card(drivers) and ability to list the keys and query values?

**Comment by jarodium** [comment]
@frankmorgner I understand. My usage of the openSC toolkit was to access my card in a command line kind of way ( read "unixy way" as @martinpaljak  said :D ) and not having to decrypt data myself.

Thanks for the help :D

**Comment by frankmorgner** [comment]
Please don't get me wrong, I understand that eidenv adds some value. However, overall it should be portable (the estid implementation may also work on Windows, but the beid will not), maintainable (currently we have two completely different implementations in one binary) and it should be user-visible what the tool does. Then it makes sense to continue developing `eidenv`!

Instead of extending `eidenv` you could also add some functionality to `pkcs15-tool` to export the data segments... This would then also be a way of dissolving `eidenv` into `pkcs15-tool`.

**Comment by jarodium** [comment]
Why not eidenv use pkcs15-tool in a "scripted" fashion? I mean, for Beid, pkcs15-tool is called differently than PtEid ( for example ). Adding cards should be fairly simple to add a configuration file to map the card and sort out differences.
For the end user it will be transparent and will not require any in-depth knowledge of pkcs15-tool.

**Comment by frankmorgner** [comment]
I'm not sure if I understand what you mean. Maybe submitting a pull request with your suggestions will make this clearer...

**Comment by jarodium** [comment]
I will try to explain as best as I can with an example map:
```json
{
    "name" : "belgian ID",
    "auth-pin-address-id" : 02,
    "auth-pin-identify" : 01,
    "getAddress" : {
        "apdu" : "XXXXX",
        "default-pin" : "pin to pass to program, maybe not that safe",
        "file" : "location of the data file in the card",
        "fields" : {
            "streetname" : "location of the streetname on the data returned"
        }
    },
   "getName" : {
     "apdu" : "XXXXXX",
     "file" : "location of the data file in the card",
     "fields" : {
            "name" : "location of the name on the data returned"
     }
   }
}
```
Basically, eid-env reads a map file, such as the above and outputs requested data:

eid-env --getAddress --pin XXXX 
eid-env --getName --pin YYYY

Don't know if this can be done, since I don't know much from other EU ID Cards, but I think its sound to think they can be automatically mapped like this.
