### ISSUE TITLE
pkcs15-init with OpenPGP Card: "Failed to store private key" instead cert

### ISSUE THREAD

**Issue by techge** [OpenSC/OpenSC#1237]
### Problem Description
When trying to copy key-cert pair on id 1 or 2, pkcs15-init states that it can not store private key although it should state that it can not store certificate

### Proposed Resolution
Let user know that storing cert on id 1 and id 2 is not supported as it is done when trying to store cert only.

### Steps to reproduce
Based on [OpenPGP card wiki entry](https://github.com/OpenSC/OpenSC/wiki/OpenPGP-card#6-import-key-resp-certificate)
1. Have a .p12 key-cert pair available or create one like described on wiki page
2. Try to store key-cert pair on id 1 or id 2 instead of id3
`pkcs15-init --delete-objects privkey,pubkey --id 2 --store-private-key myprivate.p12 --format pkcs12 --auth-id 3 --verify-pin`

### Terminal output
```
    nitrokey@nitrokey-arch ~$ pkcs15-init --id 3 --store-private-key myprivate.p12 --format pkcs12 --auth-id 3 --verify-pin
Using reader with a card: Nitrokey Nitrokey Pro (0000320E0000000000000000) 00 00
User PIN required.
Please enter User PIN [Admin PIN]: 
error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
Please enter passphrase to unlock secret key: 
Importing 1 certificates:
  0: /C=DE/ST=Berlin/L=Berlin/O=Nitrokey/OU=Support/CN=nitrokey.com/emailAddress=support@nitrokey.com
nitrokey@nitrokey-arch ~$ pkcs15-init --id 2 --store-private-key myprivate.p12 --format pkcs12 --auth-id 3 --verify-pin
Using reader with a card: Nitrokey Nitrokey Pro (0000320E0000000000000000) 00 00
User PIN required.
Please enter User PIN [Admin PIN]: 
error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
Please enter passphrase to unlock secret key: 
Importing 1 certificates:
  0: /C=DE/ST=Berlin/L=Berlin/O=Nitrokey/OU=Support/CN=nitrokey.com/emailAddress=support@nitrokey.com
Failed to store private key: Not supported
nitrokey@nitrokey-arch ~$ pkcs15-tool -k                                                      [return: 1 - 19:55:21]
Using reader with a card: Nitrokey Nitrokey Pro (0000320E0000000000000000) 00 00
Private RSA Key [Encryption key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x22], decrypt, unwrap
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 2048
	Key ref        : 1 (0x1)
	Native         : yes
	Auth ID        : 02
	ID             : 02
	MD:guid        : 79f8d738-6b5b-7109-866c-972936519237

Private RSA Key [Authentication key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x222], decrypt, unwrap, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 2048
	Key ref        : 2 (0x2)
	Native         : yes
	Auth ID        : 02
	ID             : 03
	MD:guid        : e9e7c78b-52b0-3595-723d-8846bba1ab83

nitrokey@nitrokey-arch ~$ pkcs15-tool -c                                                      [return: 0 - 19:55:31]
Using reader with a card: Nitrokey Nitrokey Pro (0000320E0000000000000000) 00 00
X.509 Certificate [Cardholder certificate]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 3f007f21
	ID             : 03
	Encoded serial : 02 09 00C13761E000E31821

nitrokey@nitrokey-arch ~$ 
```

**Comment by frankmorgner** [comment]
So the description in the wiki is correct, but you'd like to see a better error description?

I think the user would be informed best if you'd update the wiki page!

It's possible that the card specific problem that you encountered in `pkcs15-init` is only visible if the debug output is turned on. I don't have a good suggestion for making it more visible here...

**Comment by techge** [comment]
Well it is already said in the wiki that one can only save one certificate. But people naturally try arround a bit and did not read everything (which they surely should 😉 

I just thought it is always best practive to have a error message which actually states what is wrong? I do not insist to change anything, I merely would suggest to change 'Failed to store **private key**: Not supported' to 'Failed to store **certificate**: Not supported'?

What do you think? To be honest I can not see where it is in source code yet 🤔

**Comment by techge** [comment]
> It's possible that the card specific problem that you encountered in pkcs15-init is only visible if the debug output is turned on.

Forget to answer: I did not enable any specific output message, this is standard output.

**Comment by frankmorgner** [comment]
Yes, the error message is irritating. Please make a pull request to change this!
