### ISSUE TITLE
Cannot post to issue #1226

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1238]
### Problem Description

As the subject says - tried to post the following text to #1226, and Github silently discarded it. ;-)

So here it goes:

> ... have you tried High Sierra?

I've been using High Sierra for quite a while now, with my fork of OpenSC.tokend. Just logged in to a Tomcat server via Safari 11.0.2 (13604.4.7.1.6) and Chrome 63.0.3239.132 to make sure (PIV AUTH and SIGN key/cert on a Yubikey NEO), selecting the cert from the keychain.  I didn't disable `pivtoken` (that could explain Safari, but not Chrome).

`macOS 10.13.2 (17C205)`

**Update**
Tested with Chrome connecting to a TLS-protected RabbitMQ 3.6.14 server (management port). Seemed to work fine.

Will do more tests next week, as I don't login to web sites using token from here too often.

**Comment by frankmorgner** [comment]
will copy the comment
