### ISSUE TITLE
PKCS#11: OpenPGP keys listed in two different slots

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1253]
### Problem Description

OpenPGP driver misses the first subkey on the card. If the card has three subkeys (Signature, Encryption, Authentication), OpenSC will see/list/use only two (Encryption, Authentication).

### Proposed Resolution

If I knew, I'd submit a PR. :-(

### Steps to reproduce

Initialize a token with OpenPGP applet, generate a GPG key, generate 3 subkeys restricting each to one of the above operations.

Do `OPENSC_DRIVER=openpgp pkcs11-tool -O` and observe the bad result (one subkey missing). Then do `gpg --card-status` and observe the correct result (all the subkeys are listed correctly).

### Logs

```
$ OPENSC_DRIVER=openpgp pkcs11-tool -O
Using slot 0 with a present token (0x0)
Public Key Object; RSA 4096 bits
  label:      Encryption key
  ID:         02
  Usage:      encrypt, wrap
Public Key Object; RSA 4096 bits
  label:      Authentication key
  ID:         03
  Usage:      encrypt, verify, wrap
$ gpg --card-status

Reader ...........: Yubico Yubikey 4 OTP U2F CCID
Application ID ...: D276000124010201000xxxxxxxxxx
Version ..........: 2.1
Manufacturer .....: Yubico
Serial number ....: 0xxxxxx
Name of cardholder: XXXXXX
. . . . .
Signature key ....:  . . . . . 2168
      created ....: 2017-07-18 19:44:03
Encryption key....:  . . . . . 6F45
      created ....: 2017-07-18 19:43:22
Authentication key:  . . . . . AFB0
      created ....: 2017-07-18 19:52:49
General key info..: sub  rsa4096/48D4424D . . . . .
sec   rsa4096/xxxx595A  created: 2015-02-20  expires: 2018-08-19
ssb>  rsa4096/xxxx6F45  created: 2017-07-18  expires: 2018-08-19
                                card-no: 0006 0xxxxxx
ssb>  rsa4096/xxxx2168  created: 2017-07-18  expires: 2018-08-19
                                card-no: 0006 0xxxxxx
ssb>  rsa4096/xxxxAFB0  created: 2017-07-18  expires: 2018-08-19
                                card-no: 0006 0xxxxxx
$ 
```

[opensc-debug.log.zip](https://github.com/OpenSC/OpenSC/files/1665725/opensc-debug.log.zip)

This problem is mentioned in https://github.com/OpenSC/OpenSC/pull/1232#issuecomment-360522820

**Comment by frankmorgner** [comment]
Thanks!

@hongquan did you see this problem before?

**Comment by hongquan** [comment]
@frankmorgner Before (OpenPGP card v2.1), the driver still saw 3 keys (sign, enc, auth).
I haven't tested since OpenPGP card v3 was released, so I don't know what happened.

**Comment by mouse07410** [comment]
And...? 

Anything you need from my end to make progress on this bug?

**Comment by hongquan** [comment]
@mouse07410 
Could you please get the log of `pkcs15-tool --list-keys`?

**Comment by mouse07410** [comment]
Interestingly, `pkcs15-tool` seems to see all the three keys...

```
$ OPENSC_DEBUG=9 OPENSC_DRIVER=openpgp pkcs15-tool --list-keys
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
Private RSA Key [Signature key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x20C], sign, signRecover, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 4096
	Key ref        : 0 (0x0)
	Native         : yes
	Auth ID        : 01
	ID             : 01
	MD:guid        : d4948f7e-6a07-1682-9244-67ffef9e0d09

Private RSA Key [Encryption key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x22], decrypt, unwrap
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 4096
	Key ref        : 1 (0x1)
	Native         : yes
	Auth ID        : 02
	ID             : 02
	MD:guid        : fc7c82f5-b377-cda9-2217-0f2527c941f5

Private RSA Key [Authentication key]
	Object Flags   : [0x3], private, modifiable
	Usage          : [0x222], decrypt, unwrap, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 4096
	Key ref        : 2 (0x2)
	Native         : yes
	Auth ID        : 02
	ID             : 03
	MD:guid        : d06624d0-afb3-3633-cef4-4641da95412e

$ 
```

Here's the log:
[pgp-debug.log.txt](https://github.com/OpenSC/OpenSC/files/1674031/pgp-debug.log.txt)

Also, I think I found one problem:
```
$ $ OPENSC_DRIVER=openpgp pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 OTP+U2F+CCID
  token label        : User PIN (OpenPGP card)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 00060xxxxxxx
  pin min/max        : 6/127
Slot 1 (0x1): Yubico Yubikey 4 OTP+U2F+CCID
  token label        : User PIN (sig) (OpenPGP card)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 00060xxxxxxx
  pin min/max        : 6/127
$ OPENSC_DRIVER=openpgp pkcs11-tool --slot 0 -O
Public Key Object; RSA 4096 bits
  label:      Encryption key
  ID:         02
  Usage:      encrypt, wrap
Public Key Object; RSA 4096 bits
  label:      Authentication key
  ID:         03
  Usage:      encrypt, verify, wrap
$ OPENSC_DRIVER=openpgp pkcs11-tool --slot 1 -O
Public Key Object; RSA 4096 bits
  label:      Signature key
  ID:         01
  Usage:      verify
$ 
```

There should be a way to stop treating a single applet on a single token as two slots...

**Comment by frankmorgner** [comment]
@mouse07410 for each PIN we're creating a slot. As far as I can see, there is no real problem, right? Did you see a problem in some application?

**Comment by frankmorgner** [comment]
You may want to read the PKCS#11 section about Sessions, which doesn't really support multiple PINs (it only distinguishes between user and admin PIN)...

**Comment by mouse07410** [comment]
> for each PIN we're creating a slot

And there is only one PIN (named *User PIN*, as opposed to *Admin PIN*). The problem is that Signature key is `ALWAYS_AUTHENTICATE`, so it requires entering that PIN again. Quite similar to what's going on with the PIV applet. That additional `(sig)` is probably coming from the driver that misunderstand something, not from the token itself.

> Did you see a problem in some application?

Yes, as shown here: https://github.com/OpenSC/libp11/issues/204

In fact, OpenSC seems unable to do anything useful with the OpenPGP applet, except for listing its content (please correct me if I'm wrong). It claims to create some kind of a signature that no software can validate. It does not interoperate with other software like OpenSSL/libp11... 

> ...read the PKCS#11 section about Sessions, which doesn't really support multiple PINs ...

There **is** only one PIN - it's OpenSC OpenPGP driver that somehow does that. Note that `pkcs15-tool` seems to display things/items correctly.

Oh, and GnuPG has no problem dealing with this token.

**Comment by mouse07410** [comment]
Here's the current problem: https://github.com/OpenSC/libp11/issues/205
Only `pkcs11-tool` (aka CLI) can login to OpenPGP applet. libp11 that uses OpenSC library, fails to login.

**Comment by dengert** [comment]
There was a SCARD_W_RESET_CARD.   line 1159 

then next outpoing cmmand is in line 1402 and is the verify

The Yubico does not have a default application, and I do not see any attempt to reselect the OpenPGP AID. The verify fails with '6D00'

I see you are using p11-kit. What PKCS#11 modules are you loading? Anyone of them could have done the reset. 

That is the point  #1243 is to make sure the AID is selected. are you running with it?

**Comment by mouse07410** [comment]
> There was a `SCARD_W_RESET_CARD` line 1159. Then next outgoing cmmand is in line 1402 and it is the `VERIFY`. The Yubico does not have a default application, and I do not see any attempt to reselect the OpenPGP AID. The verify fails with `6D00`.

I understand now. Thank you!

> I see you are using p11-kit. 

Yes.

> What PKCS#11 modules are you loading? Anyone of them could have done the reset.

Module list:
- *opensc.module* - OpenSC (good, main workhorse)
- *yhsm2.module* - driver for YubiHSM2 (good, works only with the HSM device)
- *ykcs11.module* - Yubico PKCS11 driver for YubiKey, buggy, only needed for tricky things like setting "touch" capability on the keys, etc.

It turned out that `ykcs11.module` was the one that did the reset. After removing it, `C_Login` and subsequent signature started working.

> That is the point #1243 is to make sure the AID is selected. are you running with it?

Not at this time - I'm still waiting for the dust to settle, and for the green light from you to start experimenting with #1243 and #1256.  Is #1243 *in its current shape* likely to take care of this issue? Or should I try it with #1256...?

And @dengert, a **big thank you** for finding the problem (and so quickly!). It was driving me nuts.

**Comment by dengert** [comment]
@mouse07410 
#1256 only address the PIV issues.  See comment https://github.com/OpenSC/OpenSC/pull/1243#issuecomment-361399468

It looks like #1234  should address RESET  but you need to try it with the p11-kit configuration you have from above. That would be a good test.  If you specify the SC_CARD_FLAG_KEEP_ALIVE it should work for other interference too.
 You and @Jakuje  need to test  and late @frankmorgner  know. 

I will try and rebase #1256 later tonight.

**Comment by mouse07410** [comment]
> #1256 only address the PIV issues.

Frankly, at this time I care most for PIV and OpenPGP (all of my tokens support PIV, and some *also* support OpenPGP). Do you know what would fix OpenPGP in a way similar to what #1256 does for PIV? 

It would be nice if EstID worked, but that's secondary. ;-)

> It looks like #1243 should address RESET but you need to try it with the p11-kit configuration you have from above

I've tried the current #1243 and confirm that it addressed this issue with the above p11-kit configuration (that included the offending YKCS11 module):
```
$ OPENSC_DRIVER=openpgp ~/openssl-1.1/bin/openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:token=User%20PIN%20%28sig%29%20%28OpenPGP%20card%29;id=%01;type=private" -out /tmp/t3200.dat.sigpkcs -sigopt rsa_padding_mode:pkcs1 -sha384 /tmp/t3200.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for User PIN (sig) (OpenPGP card):
$ OPENSC_DRIVER=openpgp ~/openssl-1.1/bin/openssl dgst -engine pkcs11 -keyform engine -verify "pkcs11:token=User%20PIN%20%28sig%29%20%28OpenPGP%20card%29;id=%01;type=public" -signature /tmp/t3200.dat.sigpkcs -sigopt rsa_padding_mode:pkcs1 -sha384 /tmp/t3200.dat
engine "pkcs11" set.
Verified OK
$
```

> If you specify the `SC_CARD_FLAG_KEEP_ALIVE` it should work for other interference too.

Could you please clarify - where should/can I put that flag?

> You and @Jakuje need to test and let @frankmorgner know.

@frankmorgner, I assume you're following this. So far, test results of #1243 are encouraging.

> I will try and rebase #1256 later tonight.

Thanks!

P.S. It still does not make sense to separate Signature key into a separate slot, especially since it uses the same PIN. Instead of specifying a different key id, now it's a whole new URL. @frankmorgner, is it possible to fix?

**Comment by dengert** [comment]
@mouse07410  I did a rebase of  https://github.com/OpenSC/OpenSC/pull/1256 on top of #1243 i.e.

git fetch frankmorgner
git checkout -b frank-applets frankmorgner/applets
git rebase frank-applets piv-aid-discovery

It went cleanly, and I did some tests using `pkcs11-tool --test -l ` Mouse, if you want to try it you could do the rebase. 

I went to push the rebase to github, but frankmorgner/applets is 2 commits behind master, and I was at master. 


@frankmorgner  How do you want to proceed?

**Comment by frankmorgner** [comment]
As usual, I'll leave the PRs open for reviews for a while. The final changes of #1243 are 4 days old; I'll give it at least a week. #1256 also looks good, but still received some fine tuning recently, so it will need a bit longer...

If there's only a single PIN, then allocating a single slot is reasonable. However, since there's no actual problem and applications should be able to cope with multiple slots, I don't consider this a priority. If you find a good fix, I'll be happy to review it!

**Comment by mouse07410** [comment]
> The final changes of #1243 are 4 days old; I'll give it at least a week.

OK, fair enough. So unless something happens, we should have #1243 merged around early- to mid-next week?

>  #1256 also looks good, but still received some fine tuning recently, so it will need a bit longer...

OK, understood.

> ...since there's no actual problem and applications should be able to cope with multiple slots, I don't consider this a priority.

OK, fair enough...

> If you find a good fix, I'll be happy to review it!

I don't understand what logic made the driver to allocate multiple slots to begin with. Could you point me at the relevant file(s) and maybe even functions that are responsible for that? I'll try to work the fix from there...

**Comment by mouse07410** [comment]
Question: `card-openpgp.c` around https://github.com/OpenSC/OpenSC/blob/a7b066cc839dad61adae62af6139445e5cbc1348/src/libopensc/card-openpgp.c#L343 tries to retrieve a file from the card. What file is it? In case of YubiKey 4 4.3.7 (the latest) the operation returns `SC_SUCCESS`, but the returned `file->namelen` is 0, and `file->name` is empty.

Is there another way to determine OpenPGP card/applet version?

**Comment by dengert** [comment]
select AID is really a select file using DF name. 00 A4 04 00 Lc AID It has special meaning as it also switches the active application.  on my Yubico 4.2.6 I see:
`00 A4 04 00 06 D2 76 00 01 24 01 00` 
Lc=6, AID=`D2 76 00 01 24 01` and Le=256
ISO 7816-4  8.2.1.2 Application identifier talks about AIDs. The OpenPGP starts with `D` so it is a  

"'D' National National (ISO 3166-1[1]) registration of application providers according to ISO/IEC 7816-5[4]"

ISO 7816-4 Section:
"8.2.2.2 Application selection using AID as DF name
In a multi-application environment, the card shall respond positively to a SELECT command specifying any
application identifier (AID, see 8.2.1.2) as DF name. The interface device may thus explicitly select an
application without previously checking the presence of the application in the card.
The card shall support a SELECT command with CLA INS P1 P2 set to '00A4 0400' for the first selection with a
given and preferably complete application identifier in the command data field (see Table 39). Depending on
whether the application is present or not, the card shall either complete or abort the command. In the case of
a selection with a truncated DF name, the full DF name will be made available in the response data field as
the file control parameter referenced by tag '84' (see Table 12). If the card supports selection with a truncated
DF name, then the first selection is implementation-dependent, e.g., the first occurrence in a static list or the
last activated application in a previous session. For the next selections, if any, the card shall support a SELECT
command with CLA INS P1 P2 set to '00A4 0402' with the same command data field."

And I would have expected the card to return the full DF with Tag '84'  But it looks like it did not.

**Comment by mouse07410** [comment]
> And I would have expected the card to return the full DF with Tag '84' But it looks like it did not.

I see your point. What in your opinion can/should be done in this case (when the card doesn't return the full DF)? I'd still want to at least extract/determine the applet version?

**Comment by dengert** [comment]
Live with it. The Yubico devices have a lot of issues The response to a SELECT AID is one of them. 
Both the OIV and OpenPGP applates have their own set of issues. The script was designed to be a tool to show the issues and help spot new ones without having to write code. 

For example sending SELECT AID for OpenPGP:
Sending: 00 A4 04 00 06 D2 76 00 01 24 01 00 
Received (SW1=0x90, SW2=0x00)
(no data returned) 
Then sending to read the '4F'  file/template"
Sending: 00 CA 00 4F 00 
Received (SW1=0x90, SW2=0x00):
D2 76 00 01 24 01 02 01 00 06 04 03 54 48 00 00 

It has the  AID  without a tag or length, for 6 bytes followed by 02 01 00 which could be OpenPGP version, followed by  06 04 03 54 48 00 00
My Yubico serial number is 4035448  which is part of the above. 
So the 06 could be a length and the card serial could be  04 03 54 48 00 00. 

The newer Yubico returns:
D2 76 00 01 24 01 02 01 00 06 07 08 69 58 00 00
And that has a serial number of 7086958  so the last few bytes look like a serial number.

But the above only works for the OpenPGP AID.

**Comment by mouse07410** [comment]
> Live with it.

I will if I must - but I'm sure there are more palatable options. ;-)

Especially after you explained the format of the data returned for `00 CA 00 4F 00` (after `SELECT AID` returned `90 00`).

I'm pretty sure (at least for YubiKey) that if `filelen` returned was 0, one can issue `00 CA 00 4F 00`, and take bytes 6 and 7 (indexing from 0) as major and minor version of the OpenPGP applet.

I wonder if @frankmorgner would accept such a patch.

> But the above only works for the OpenPGP AID.

Oh yes. But this specific question is about getting OpenPGP applet version correctly.

> The script was designed to be a tool to show the issues and help spot new ones without having to write code.

And it's a very nice and convenient tool, thank you!

**Comment by frankmorgner** [comment]
>I don't understand what logic made the driver to allocate multiple slots to begin with. Could you point me at the relevant file(s) and maybe even functions that are responsible for that?

@mouse07410, here is the technical explanation from the [OpenPGP card's manual](https://www.g10code.com/p-card.html) why we have two "slots" for the user PIN:

>With P1 = 00 and password data in the command one of the passwords of the application 
is verified. PW1 has two modes and can be used with 2 different numbers (in P2). PW 1 
with P2 = 81 sets the access conditions for a PSO:CDS command only. Depending on the 
PW1 status byte (see Extended Capabilities) this access condition is only valid for one 
PSO:CDS command or remains valid for several attempts. PW1 with P2 = 82 sets the 
access condition for several other functions and remains valid up to a reset or SELECT of 
a different application.

If you want to look at code, you may want to start [here](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-openpgp.c#L65-L72)...

**Comment by mouse07410** [comment]
@frankmorgner, thank you. I understand now.

I'll constrain myself then to just making the OpenPGP applet version available even if the card doesn't behave 100% correctly.

**Comment by dengert** [comment]
@mouse07410  It is in #1243  https://github.com/OpenSC/OpenSC/pull/1243/commits/fea49f3baaf834556a339a16b620976f887f9f36
card-opensc.c line 2884 `r = sc_get_data(card, 0x004F, aid, sizeof aid);`

That ends up calling the openpgp version of get_data  `pgp_get_data`

Note that card-piv.c and  card-openpgp.c each define their version of get_data, and used different ISO get data commands. 

So the  `r = sc_get_data(card, 0x004F, aid, sizeof aid);` only works when the openpgp application is active. It is a way to test if the openpgp application is active.

**Comment by mouse07410** [comment]
@dengert, thank you! With your help, https://github.com/OpenSC/OpenSC/pull/1262 is there to retrieve OpenPGP applet version from a YubiKey token.

**Comment by Jakuje** [comment]
I searched through the OpenPGP specifications, but I didn't find any reference to PW2, PIN2 nor CHV2 after the OpenPGP v1.1 [1]. The important part is this one (and few more notes all over the specs):

>  PW1 is used as access condition for the command PSO:CDS, PSO:DEC, INT-AUT, GET DATA and PUT DATA. The command PSO:CDS uses PW1 in a different mode then the other commands.

This basically means we have really only one PIN, but depending on the operation, we issue different commands (different mode). I suspect, it was the simplest/only way to implement it in the way that there are two same PINs -- the PIN operation type is probably not passed to the `pgp_pin_cmd()` function. It could be considered it an implementation detail, but unfortunately it has the conseqence of showing the object in different virtual slot in PKCS#11.

If we would like to fix it, we would have to either find/create a way for the `pgp_pin_cmd()` know, what operation on what key we do or make one of the PINs somehow shadowing the other. Both of it would require some/significant changes to the framework around.

[1] https://g10code.com/p-card.html#sec-5

**Comment by dengert** [comment]
Yes, v2.0 says in the History section: "Change in VERIFY command and password management."
Also reading it looks like PW1 is the user PIN, and PW3 is the PUK, i.e. SO_PIN.  That should be much easier to modify as this is the usual way most cards do it. 

It is almost like CKA_ALWAYS_AUTHENTICATE, and a C_Login(CKU_CONTEXT SPECIFIC) situation. 

The lower levels have no other way to know what operation PKCS#11 is going to request when C_Login is done so the pgp_pin_cmd  can set the reference in the verify command. 
 
Yes looks messy. 
Could issue 2 verifies using the same pin one with 81 and one with 82?
But that would not work well with a pin pad, but the verify could be postponed if pin pad  is used to just before crypto operation.
