### ISSUE TITLE
Allow card-insert events of empty cards for provisioning

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#1265]
### Problem Description
The ESC needs to receive card-insert events about inserted empty cards for provisioning. So far this functionality was provided by coolkey. We would be interested in something similar for OpenSC and this issue is mostly to discuss possibilities and preferred solution.

### Proposed Resolution
So far, the Coolkey PKCS#11 library was used and was using the [`pReserved` pointer in the end of the `CK_C_INITIALIZE_ARGS`](https://github.com/elmarco/coolkey/blob/master/src/coolkey/coolkey.cpp#L223) structure to enable this feature. The first possibility is to mimic this behavior and implement something similar in OpenSC PKCS#11. This argument [SHOULD be NULL in PKCS#11 2.40](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959692) and therefore is correctly checked in OpenSC, but not used to anything else yet. I agree that this might be non-standard and therefore not wanted.

The other possibility that we discussed was the implementation of bogus `blank` card driver, that would be disabled by default and would "match" also for empty cards. Turning this on would require passing environment variable `OPENSC_CONF` which would include also this driver in the end, but it would require ensuring that the second configuration file is in sync with the current.

Other possibility could be some configuration option, that would turn it on and off. That might be the cleanest and simplest way.

Or do you thing about some other way how the similar thing can be achieved, that would be acceptable by OpenSC?

**Comment by CardContact** [comment]
What is ESC ?

Do you mean to report card insertion via C_WaitForSlotEvent ? How is the card identified if it's empty and how do you differentiate it from other cards inserted ?

**Comment by Jakuje** [comment]
ESC is https://apps.fedoraproject.org/packages/esc

Yes. We talk about the events in `C_WaitForSlotEvent()`. The event, for empty cards is coming from pcsc-lite, regardless the content of the card. The code in there now propagates the event to PKCS#11 layer only if the new card was matched by some of existing drivers. Details are still probably up to discuss.

**Comment by dengert** [comment]
What constitutes an empty card?  It must at least have an ATR. 

There is the "default" driver that just does ISO 7816 commands. You can do some testing with it
using opensc-tool -c default  then add some -s parameters with APDUs you would like to test. 
like try selecting an AID. -s "00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00" is the PIV AID. 
Running the above, opensc-debug.log shows it is the only APDU sent to the card.

Running the following
```
OPENSC_DRIVER=default /opt/ossl-1.1/bin/pkcs11-tool --module /opt/ossl-1.1/lib/opensc-pkcs11.so -L 
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 OTP+U2F+CCID 00 00
C_GetTokenInfo() failed: rv = CKR_TOKEN_NOT_PRESENT
```
 show that OpenSC can use the default card driver, but that the PKCS15 
layer will still try and look for PKCS15 files on the card. With Yubico, neithe the PIV or OpenPGP AID is active after insertion, so it ios not clear what AID if any is active, so all attempts to do any APDUs fails.
OpenSC might need a pkcs15-default.c module, or use the opensc.conf  `pkcs15emu =` for the pkcs15-coolkey.c 

Using OPENSC_DRIVER= cause teh opensc.conf to not be parsed. There is (or will be ) an issue on this.

**Comment by frankmorgner** [comment]
Have you looked at the `hide_empty_tokens = false;` option in `opensc.conf`?

**Comment by frankmorgner** [comment]
Have you looked at the use of the `USE_PKCS15_INIT` define? It seems to allow using the pkcs15init stuff in PKCS#11...

**Comment by Jakuje** [comment]
The empty card in this case is a Java Card without any applet to my understanding. I have one here:
```
$ pcsc_scan 
PC/SC device scanner
[...]
1: OMNIKEY AG CardMan 3121 01 00

Thu Feb  8 14:58:30 2018
Reader 0: Yubico Yubikey NEO OTP+CCID 00 00
  Card state: Card inserted, 
  ATR: 3B FA 13 00 00 81 31 FE 15 59 75 62 69 6B 65 79 4E 45 4F A6
```
The option `hide_empty_tokens` can be something I can be looking for, but I do not see this configuration option used anywhere in the code. Just defined, loaded from configuration file and then dumped in debug log. Setting it to false does not change the behavior at all. Or do I miss anything?

Also the `USE_PKCS15_INIT`, might be a way to go. Thank you for pointers. I will investigate further.

**Comment by frankmorgner** [comment]
You most likely need to enable the default driver, because without an applet on the card, there is no internal driver that will match. After provisioning the applet to the card, you also need to reconnect to the PKCS#11 module so that an Applet-specific card driver can be loaded. This procedure seems really non-standard PKCS#11; I think you should at least have the applet on the card if you want to personalize the card via PKCS#11.

**Comment by Jakuje** [comment]
> After provisioning the applet to the card, you also need to reconnect to the PKCS#11 module so that an Applet-specific card driver can be loaded. 

I believe this is somehow handled by the ESC with some PCSC call.

What about the `hide_empty_tokens` option? It looks like it is another unused configuration option. Shall we remove it to clean up the configuration file further?

**Comment by CardContact** [comment]
Is ESC only for coolkey cards or does it support other cards as well ?

We are currently working on a cloud based PKI provisioning service. ESC might be something to integrate with.

**Comment by Jakuje** [comment]
At this moment, It is used for provisioning only Coolkey cards and I do not know about any plans to support anything else. Unfortunately, there is not a lot of documentation around this project, but feel free to get in touch with the developers (Jack Magne) if you have more questions.

**Comment by dengert** [comment]
Looking at the card-coolkey.c 
It looks like it will not match if the select AID fails, which might mean it does not have the applet loaded. 

If that works, in coolkey_initialiaze, it calls  coolkey_get_life_cycle that could fail,
and finally there is a loop to read the objects from the card. 
It looks like if there are no objects on the card,  that could fail 
```
2208         if (r != SC_ERROR_FILE_END_REACHED) {
2209                 goto cleanup;
2210         }
```
```
2229 cleanup:
2230         if (priv) {
2231                 coolkey_free_private_data(priv);
2232         }
2233         return r;
```
If r is not SC_SUCCESS then coolkey_init fails. 

So the fix might be in coolkey_initialize to return  SC_SUCCESS even if no objects are found.

An opensc-debug.log should show if the above is correct or not.

**Comment by Jakuje** [comment]
At this moment, I am not really sure if the applet is on the card or not at the time of initialization, But I suspect it is not and we are only matching on the empty Java Card and applet is also loaded during the provisioning phase.

When I try to list the slots with coolkey, I am getting also empty slot, unless I turn the vendor-specific option on:
```
$ pkcs11-tool -L --module /usr/lib64/pkcs11/libcoolkeypk11.so 
Available slots:
Slot 0 (0x1): OMNIKEY AG CardMan 3121 00 00
  (empty)
```

This could be a generic question, if token with no object on it is a valid token, since such token basically can not do anything useful. I would prefer it to stay this way, unless it will show as an issue someplace. I don't have a such a card to try.

**Comment by Jakuje** [comment]
Thank you for the comments. We are still more in the research phase what needs to be done and how. If there will be some more issues, I will come back.

**Comment by frankmorgner** [comment]
You could write a card driver for the GlobalPlatform Manager. Via the driver it should be possible to view an empty card in PKCS#11. This would then be yet an other case of having multiple applets (and card drivers) for a single token.

In `src/smm/sm-global-platform.c` it looks like GP's SM is already implemented, which should be handy when installing a new applet.

**Comment by Jakuje** [comment]
I finally got back to this one. I can confirm, that setting the following options makes it better:

    enable_default_driver = true;
    card_drivers = coolkey, cac, piv, default;

But there are still issues:
 * When the card is hot-plugged while blocking `C_WaitForSlotEvent()` is called, it is not detected at all (see the first attachment)
* When the card is in slot before, the `C_GetSlotInfo()` is working, but `C_GetTokenInfo()` already fails, because there is no `p11card` in the `slot` structure.

I am not particularly sure if that is intended or where should the `p11card` structure be assigned (clearly not where the match and init functions were invoked). I will have a look into that later, but other pointers are welcomed.

The issue is probably the assigning of the pkcs15 emulator backend here:

    3131 0x7f48a803a740 16:28:36.438 [opensc-pkcs11] slot.c:338:card_detect: OMNIKEY AG CardMan 3121 00 00: cannot bind 'generic' token: rv 0xE1

[Uploading opensc_debug_empty_inserted.log…]()
[opensc_debug_empty_hotplug.log](https://github.com/OpenSC/OpenSC/files/1856371/opensc_debug_empty_hotplug.log)

**Comment by Jakuje** [comment]
Also from time to time, I can see the following error:

0x7fdc41387740 11:33:27.450 [opensc-pkcs11] reader-pcsc.c:556:pcsc_connect: OMNIKEY AG CardMan 3121 00 00:SCardConnect failed: 0x80100001

It looks like some issue with the pcsc, since it does not go away until I reconnect the reader. PCSC trace does not show anything useful either.

For the record, I figured out that the missing bit was the `pkcs11_enable_InitToken` configuration option, which is parsed only in the ATR blocks. The following snippet made the card working as expected from OpenSC (for my SafeNet card):

	card_atr 3B:FF:14:00:FF:81:31:FE:45:80:25:A0:00:00:00:56:57:53:43:36:35:30:03:03:38 {
		pkcs11_enable_InitToken = yes;
	}

Now, even `pkcs11-tool` is able to list the card information:

```
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): OMNIKEY AG CardMan 3121 00 00
  token state:   uninitialized
```
