### ISSUE TITLE
PKCS11-Spy - how to log and can it help me with the error CKR_ATTRIBUTE_TYPE_INVALID?

### ISSUE THREAD

**Issue by victorqedu** [OpenSC/OpenSC#1268]
Hello, I'm not sure I write in the right place.

I have a JAVA app and I use many models of PKCS11 tokens. This week I found a model that gives me the error CKR_ATTRIBUTE_TYPE_INVALID when I execute "keystorePkcs11.getKey(alias, pass);". This token works well with other pograms made in other programming languages.

I read that this means that JAVA is requesting a property that is not present in the object returned.
Can OpenSC help me find this property / diagnose this issue?

I tried to use PKCS11-Spy but nothing  gets logged in the file configured in the windows registry.
I configured: HKLM\Software\OpenSC Project\PKCS11-Spy\Module with th DLL I use to  acces the token.
File %TEMP%\pkcs11-spy.log is not created. How can I activate PKCS11-Spy?

Thank you,
Victor S.

**Comment by Jakuje** [comment]
If I read the code right, you need to configure two keys under PKCS11-Spy registry:
 * `Module` with the PKCS#11 module you want to inspect
 * `Output` with the path to the file, where you want the output logged

If you don't specify the second, the output goes to `stderr`, which is probably discarded from your java application.
