### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by victorqedu** [OpenSC/OpenSC#1270]
Hello

I have a PKCS11 token that I can't acces from Java because I receive the error CKR_ATTRIBUTE_TYPE_INVALID when I try to get the key (RSA/2048 bits).
I debugged the problem and the attribute that causes error CKR_ATTRIBUTE_TYPE_INVALID is CKA_MODULUS.

Can I use OpenSC to fix this attribute on the token?

Thank you
VIctor S.

**Comment by dengert** [comment]
Depends on the token.  You also did not say what module you are using to access the token. Is it OpenSC?

In you other issue, did you get SPY to work? What is the output? 

CKA_MODULUS should be valid for an RSA public or private key. 

Do you need to login first to see the private key?

Does the token work with any other software?

**Comment by victorqedu** [comment]
Token is MTOKEN CRYPTOID model E manufacturerID LONGMAI and I access it using a DLL provided by Longmai named **cryptoide_pkcs11.dll**.

I need to login to see my keys. Login is succesfull, error appears when I execute "keystore.getKey()". 
The token works in other applications: it works in apps made in NetFramework and it works in IE and Chrome. 

I think these apps that work with the token don't use the DLL **cryptoide_pkcs11.dll** but they use Windows drivers and Windows store.

I think there is a BUG in **cryptoide_pkcs11.dll**. I tried to contact LONGMAI but without succes until now.

This is what I tried until now:
* I tried to access it using the DLL provided by LONGMAI and the result was CKR_ATTRIBUTE_TYPE_INVALID.
* I tried to access it using directly **opensc-pkcs11.dll** but my Java application simply exits without any message.
* I tried to use **pkcs11-spy.dll** with registry module value **%SystemRoot%\system32\opensc-pkcs11.dll** but the result was the same.
  The result of the spy is here http://cc123.caido.ro/pkcs11spy.log
* I tried to use **pkcs11-spy.dll** with registry module value **D:\temp\cryptoide_pkcs11.dll** and the result was the same but I can see in the PKCS11SPY log that the wrong DLL was loaded "Loaded: **C:\Windows\system32\opensc-pkcs11.dll**". 
  I rebooted the computer to reload the registry but PKCS11SPY logger stil indicates that **opensc-pkcs11.dll** was loaded instead **cryptoide_pkcs11.dl**l.
* I tried to use PKCS11 logger from here https://github.com/Pkcs11Interop/pkcs11-logger with the DLL provided by LONGMAI and I obtained a log that identified the cause of the problem: the attribute CKA_MODULUS.
  The full log is here http://cc123.caido.ro/pkcs11.txt and the section with the error is under this line:
```

0x00001940 : 0x000018ac : ****************************** 2018-02-19 08:53:54 ***
0x00001940 : 0x000018ac : Calling C_GetAttributeValue
0x00001940 : 0x000018ac : Input
0x00001940 : 0x000018ac :  hSession: 359468400
0x00001940 : 0x000018ac :  hObject: 359469048
0x00001940 : 0x000018ac :  pTemplate: 1505A548
0x00001940 : 0x000018ac :  ulCount: 1
0x00001940 : 0x000018ac :   *** Begin attribute template ***
0x00001940 : 0x000018ac :   Attribute 0
0x00001940 : 0x000018ac :    Attribute: 288 (CKA_MODULUS)
0x00001940 : 0x000018ac :    pValue: 00000000
0x00001940 : 0x000018ac :    ulValueLen: 0
0x00001940 : 0x000018ac :   *** End attribute template ***
0x00001940 : 0x000018ac : Output
0x00001940 : 0x000018ac :  pTemplate: 1505A548
0x00001940 : 0x000018ac :  ulCount: 1
0x00001940 : 0x000018ac :   *** Begin attribute template ***
0x00001940 : 0x000018ac :   Attribute 0
0x00001940 : 0x000018ac :    Attribute: 288 (**CKA_MODULUS**)
0x00001940 : 0x000018ac :    pValue: 00000000
0x00001940 : 0x000018ac :    ulValueLen: 4294967295
0x00001940 : 0x000018ac :   *** End attribute template ***
0x00001940 : 0x000018ac : Returning 18 (**CKR_ATTRIBUTE_TYPE_INVALID**)
```

This is my full description of the problem at Java level: https://community.oracle.com/message/14714466#14714466
Thank you.

**Comment by dengert** [comment]
I don't see the problem.  But I do see a 4  `ulDeviceError` responses from C_GetSessionInfo. That may be a clue as to why the device or the library is having problems. (Could also be uninitialized memory)

You may also want to try running the OpenSC `pkcs11-tool --module  D:\temp\cryptoide_pkcs11.dll`

The OpenSC Spy may be having a problem in Windows with the D:\. try moving to C: and drop the drive letter. 

With pkcs11-tool  there are a number of options such as -L and -O that might be helpful. You can also 
use OpenSC SPY. 

In your oracle.com post, you said you got the certificate from some other location. Did you generate the key on the device?

**Comment by victorqedu** [comment]
Probably I interpreted wrong the pkcs11 log. 
At the end of the pkcs11 log I have a line "Returning 18 (**CKR_ATTRIBUTE_TYPE_INVALID**)" and this is exactly the error that I can see in Java so an attribute must be the problem.
Because the last attribute was CKA_MODULUS and pValue was 00000000 I imagined that this was the invalid attribute. Probably I got it wrong, I don't know now. :)

I can read the certificates and public keys using pkcs11-tool(works on C and D drives):
```
C:\Program Files (x86)\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --module C:\temp\cryptoide_pkcs11.dll -I -O
Cryptoki version 2.20
Manufacturer     Longmai Technology
Library          Logmai PKCS11# Library (ver 2.0)
Using slot 0 with a present token (0x0)
Public Key Object; RSA 2048 bits
  label:      A public object
  ID:         436572744469676974616c5f3135313830393037363335343900
  Usage:      encrypt, verify, wrap
Certificate Object; type = X.509 cert
  label:      A certificate object
  ID:         436572744469676974616c5f3135313830393037363335343900
Public Key Object; RSA 2048 bits
  label:      A public object
  ID:         7465737400
  Usage:      encrypt, verify, wrap
Certificate Object; type = X.509 cert
  label:      A certificate object
  ID:         7465737400
```
  
I generated a certificate and the keys in my Java application and imported them on this token.
When I try to retrieve the private key handler of the new certificate I receive the same error - CKR_ATTRIBUTE_TYPE_INVALID.

I did generate a pair of keys successfully with pkcs11tool and I deleted them with pkcs11-tool
`pkcs11-tool --module=D:\temp\cryptoide_pkcs11.dll --login --pin ***** --keypairgen --key-type rsa:2048 --id 01 --label zone_key 
`
The problem appears only when I try to retrieve the private key from the token. 
The certificate is read successfully.

I will try again to use PKCS11-SPY.
But I wrote the value "C:\temp\cryptoide_pkcs11.dll" in the key "HKLM\Software\OpenSC Project\PKCS11-Spy\Module" and PKCS11-SPY doesn't seems to read this key.
PKCS11-SPY is still loading "C:\Windows\system32\opensc-pkcs11.dll"
Where could he read this value?

**Comment by dengert** [comment]
So you can not read the key from any application?
Can you use the key? 

`pkcs11-tool --module=D:\temp\cryptoide_pkcs11.dll --login --pin ***** --test`

The problem maybe the --keypairgen did not do what was expected. 
How did the vendor say to create a keypair?

It may also be other applications to not request the CKA_MODULUS of the private. They can get it 
from the Public key, or the certificate. 

Is it only your Java program that is failing? Do you have any other Java program that works? 

I have no way to tell if OpenSC could fix your problem. It may have to do the vendor's  module. 

Another possible issue, is the CKA_ID if the private key, public key and certificate are usually the same. 
I see that when you created with --id 01. But in the trace it looks like it is 
`980076612F7574696C2F4C6F63616C652443617465676F72792E`
Do you know where this came from.

**Comment by victorqedu** [comment]
I found something new: when I executed the command suggested by you `pkcs11-tool --module=D:\temp\cryptoide_pkcs11.dll --login --pin ***** --test` I received the same error that appears in Java(CKR_ATTRIBUTE_TYPE_INVALID).
Down is the full output. 

```
C:\Program Files (x86)\OpenSC Project\OpenSC\tools>pkcs11-tool --module=D:\temp\cryptoide_pkcs11.dll --login --pin ******* --test
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
Signatures (currently only for RSA)
  testing key 0 (A private object)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (2048 bits, label=A private object) with 1 signature mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (A private object)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
  testing key 1 (A private object) with 1 mechanism
    RSA-X-509: OK
Key unwrap (currently only for RSA)
  testing key 0 (A private object)
    DES-CBC: OK
    DES-EDE3-CBC: OK
    BF-CBC: OK
    CAST5-CFB: OK
  testing key 1 (A private object)
    DES-CBC: OK
    DES-EDE3-CBC: OK
    BF-CBC: OK
    CAST5-CFB: OK
Decryption (currently only for RSA)
  testing key 0 (A private object)
    RSA-PKCS: OK
    RSA-X-509: OK
    DES-ECB: error: PKCS11 function C_DecryptInit failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)
Aborting.
```

The vendor didn't say to create a keypair. This USB token is brought from a local certificate authority and cames with a already generate keypair.
I should just use this certificate to access some SOAP services and produce some signatures.

I know no other Java applications that work with this device.
The id 980076612F7574696C2F4C6F63616C652443617465676F72792E seems to be auto generated by the vendor dll library - the "--id 01" from my command line is ignored.

Thank you @dengert, you've been more than patient 
:)

**Comment by dengert** [comment]
That final error looks like the token says it can do DES_ECB, but it can't. I would not worry about that. DES should not be used these days. 

You said: "This USB token is brought from a local certificate authority and cames with a already generate keypair." That does not sound secure. They know the key, why would anyone want to use it?

Is the intent to use the pre existing key on the device to request other keys be generated and to get other certificates?

It also looks like no other software is requesting the CKA_MODULUS of the private key. So what is Java doing?

**Comment by victorqedu** [comment]
This is how all certificate authorities are selling PKCS11 devices in Romania. 
- Key pairs are already generated and written on the device. 
- Clients receive this device by postal mail. 
- When the original certificate expires client can buy another and write it on a special site or he can send the device to the authority.

All health specialists must use it in legal matters(it is mandatory). I talked a few years ago at a calling center and they told me the private key is random generated and is not saved on their database.

The intent of these already generated keypair is to be used exactly like this, not to generate others. Only these keypairs that are already on the token are legaly recognized.

I'll try again with PKCS11 SPY.

**Comment by victorqedu** [comment]
I obtained the PKCS11 SPY log like this:
- I searched the registry for opensc-pkcs11.dll and found this value in a new location: Computer\HKLM\SOFTWARE\Wow6432node\OpenSC Project\PKCS11-SPY\module
- I changed the value here and I obtained the log under this line.

Problem is I can't see any error here but in java I have error CKR_ATTRIBUTE_TYPE_INVALID.
```
*************** OpenSC PKCS#11 spy *****************
Loaded: "C:\temp\cryptoide_pkcs11.dll"

0: C_GetFunctionList
2018-02-21 09:49:20.501
Returned:  0 CKR_OK

1: C_Initialize
2018-02-21 09:49:20.501
[in] pInitArgs = 00000000
Returned:  0 CKR_OK

2: C_GetSlotList
2018-02-21 09:49:20.501
[in] tokenPresent = 0x1
[out] pSlotList: 
Count is 1
[out] *pulCount = 0x1
Returned:  0 CKR_OK

3: C_GetSlotList
2018-02-21 09:49:20.517
[in] tokenPresent = 0x1
[out] pSlotList: 
Slot 0
[out] *pulCount = 0x1
Returned:  0 CKR_OK

4: C_GetTokenInfo
2018-02-21 09:49:20.517
[in] slotID = 0x0
[out] pInfo: 
      label:                  '                 mToken CryptoID'
      manufacturerID:         '                         Longmai'
      model:                  'E               '
      serialNumber:           'AE09D489D590D7E6'
      ulMaxSessionCount:       0
      ulSessionCount:          0
      ulMaxRwSessionCount:     0
      ulRwSessionCount:        0
      ulMaxPinLen:             32
      ulMinPinLen:             6
      ulTotalPublicMemory:     131072
      ulFreePublicMemory:      109312
      ulTotalPrivateMemory:    131072
      ulFreePrivateMemory:     109312
      hardwareVersion:         4.0
      firmwareVersion:         3.11
      time:                   '                '
      flags:                   18060d
        CKF_RNG                          
        CKF_LOGIN_REQUIRED               
        CKF_USER_PIN_INITIALIZED         
        CKF_DUAL_CRYPTO_OPERATIONS       
        CKF_TOKEN_INITIALIZED            
        CKF_USER_PIN_TO_BE_CHANGED       
        CKF_SO_PIN_COUNT_LOW             
Returned:  0 CKR_OK

```

**Comment by victorqedu** [comment]
I crypted and decrypted succesfuly using vendor DLL and pkcs11-tool. I guess this a Java problem after all.

**Comment by dengert** [comment]
Maybe.  It looks like Java tries to read the CKA_MODULUS for the private key.  The vendor library returns CKR_ATTRIBUTE_TYPE_INVALID. This could be a vendor library problem or the token does not expose the modules. 

Some PKCS\#11 modules can simulate reading the CKA_MODULE from the private key by actually getting it from the matching certificate (SubjectPublicKeyInfo) that is the public key or a public key object on the token. 

But most applications do not need to read the CKA_MODULUS from the private key, because it is also in the Public Key and in the certificate.  (Java maybe so it can verify that the modulus is the same i teh certificate, public key and private key. PKCS\#11 recommends that the CKA_ID attribute of these should be the same. )  

If you were to run the pkcs11-tool   using SPY and the vendor module I would **not** expect to see a  C_GetAttibutes call for the CKA_MODULUS of the private key object. 

So the problem may be in the Java code doing  C_GetAttibutes call for the CKA_MODULUS of the private key object which should work, but the vendors module does not support it because they don't think it is needed. 

Maybe you should not experiment with the government health token.

**Comment by victorqedu** [comment]
I did use PKCS11 SPY, the log is in one of my 3 posts from today. There is no error in the PKCS11 SPY log.
These are not governments tokens, all tokens are personal, they are used in legal and personal matters.
And the tokens are not generated by the government, they are 4 national companies that do this in the private sector.
I'm testing in personal matter and I broke no law it this is what you were thinking. :) 

Thank you.

**Comment by dengert** [comment]
I did not meant to hint that you were breaking any laws, just that you might break your device that you may need for other purposes.

**Comment by victorqedu** [comment]
It's fine, this device is already not working since it seems to be incompatible with Java.

**Comment by dengert** [comment]
There is nothing for OpenSC to do. 

If you would like to write a driver for the device please reopen the issue. 
To write a driver, you need so very low level specifications from the token vendor, which may not be available.

**Comment by victorqedu** [comment]
Good news for me, Longmai provided new DLL files that solved the problem.

**Comment by gatokino** [comment]
Hi, we have the same problem and we are not able to get the latest version for the dll.
can you help us with this dll version
