### ISSUE TITLE
SEGV in ASN1 code with GIDS card

### ISSUE THREAD

**Issue by fishsoupisgood** [OpenSC/OpenSC#1273]
### Problem Description

with current master [1d4f59ea51dd1713a3b99186498cb8fe074abc4c](https://github.com/OpenSC/OpenSC/commit/1d4f59ea51dd1713a3b99186498cb8fe074abc4c) and current master of the GidsApplet [7ba0d7b8ad5368cbdbe988164c90fc26744c5e0c](https://github.com/vletoux/GidsApplet/commit/7ba0d7b8ad5368cbdbe988164c90fc26744c5e0c) on a J3A081 I encounter a SEGV when running pkcs11-tool.

[gids_get_pin_status](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-gids.c#L533) calls (reading upto 100 bytes into buffer)

       r = gids_get_DO(card, GIDS_APPLET_EFID, dataObjectIdentifier, buffer, &buffersize);

APDU: 00 CB 3F FF 04 5C 02 7F 71 00
SW: 7F 71 06 97 01 03 93 01 03 90 00

after which buffer is: 97 01 03 93 01 03 00
and buffersize is 6

it then calls 

        p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_COUNTER_OLD_TAG, &datasize);

giving sizeof(buffer) rather than 6 as the length of data to parse.

[sc_asn1_find_tag](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/asn1.c#L473) which parses the ASN1 in a loop:

* iteration 0 finds: 97 01 03  (class 0x80, tag= 0x17, length=1, value=3)
* iteration 1 finds: 93 01 03 (class 0x80, tag=0x13, length=1, value=3)
* iteration 2: *p is now 00 (by luck, we've read past the end of initialized data), and the call to [sc_asn1_read_tag](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/asn1.c#L71)  sets p to be NULL and returns. left now gets set to a ludicrous value
* iteration 3: p is now NULL and the call to sc_asn1_read_tag SEGVs.

<pre>
(gdb) run -L
Starting program: /usr/bin/pkcs11-tool -L
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff754d6df in sc_asn1_read_tag (buf=0x7fffffffb398, buflen=140737488335988, cla_out=0x7fffffffb384, tag_out=0x7fffffffb388, taglen=0x7fffffffb390)
    at asn1.c:71
71              if (*p == 0xff || *p == 0) {
(gdb) print p
$1 = (const u8 *) 0x0
(gdb) up
#1  0x00007ffff754e5e3 in sc_asn1_find_tag (ctx=0x55555577db70, buf=0x0, buflen=100, tag_in=40727, taglen_in=0x7fffffffb400) at asn1.c:478
478                     if (sc_asn1_read_tag(&p, left, &cla, &tag, &taglen) != SC_SUCCESS)
(gdb) up
#2  0x00007ffff767ad4f in gids_get_pin_status (card=0x5555557a9090, pinreference=128, tries_left=0x7fffffffc3bc, max_tries=0x7fffffffc3b8) at card-gids.c:536
536             p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_COUNTER_OLD_TAG, &datasize);
(gdb) list
531                     SC_FUNC_RETURN(card->ctx, SC_LOG_DEBUG_NORMAL, SC_ERROR_OBJECT_NOT_FOUND);
532             }
533             r = gids_get_DO(card, GIDS_APPLET_EFID, dataObjectIdentifier, buffer, &buffersize);
534             SC_TEST_RET(card->ctx, SC_LOG_DEBUG_NORMAL, r, "unable to update the masterfile");
535
536             p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_COUNTER_OLD_TAG, &datasize);
537             if (p && datasize == 1) {
538                     if (tries_left)
539                             *tries_left = p[0];
540             }
(gdb) print buffer
$2 = "\227\001\003\223\001\003\000\000\360\264\377\377\377\177\000\000\060\264\377\377\377\177\000\000\000\212\316\b` \273\352\000\000\000\377\377\377\377\377", '\000' <repeats 59 times>
(gdb) print buffersize
$4 = 6
(gdb) print sizeof(buffer)
$5 = 100
(gdb) down
#1  0x00007ffff754e5e3 in sc_asn1_find_tag (ctx=0x55555577db70, buf=0x0, buflen=100, tag_in=40727, taglen_in=0x7fffffffb400) at asn1.c:478
478                     if (sc_asn1_read_tag(&p, left, &cla, &tag, &taglen) != SC_SUCCESS)
(gdb) down
#0  0x00007ffff754d6df in sc_asn1_read_tag (buf=0x7fffffffb398, buflen=140737488335988, cla_out=0x7fffffffb384, tag_out=0x7fffffffb388, 
    taglen=0x7fffffffb390) at asn1.c:71
71              if (*p == 0xff || *p == 0) {
(gdb) where
#0  0x00007ffff754d6df in sc_asn1_read_tag (buf=0x7fffffffb398, buflen=140737488335988, cla_out=0x7fffffffb384, tag_out=0x7fffffffb388, 
    taglen=0x7fffffffb390) at asn1.c:71
#1  0x00007ffff754e5e3 in sc_asn1_find_tag (ctx=0x55555577db70, buf=0x0, buflen=100, tag_in=40727, taglen_in=0x7fffffffb400) at asn1.c:478
#2  0x00007ffff767ad4f in gids_get_pin_status (card=0x5555557a9090, pinreference=128, tries_left=0x7fffffffc3bc, max_tries=0x7fffffffc3b8) at card-gids.c:536
#3  0x00007ffff767d01e in gids_get_pin_policy (card=0x5555557a9090, data=0x7fffffffc350) at card-gids.c:957
#4  0x00007ffff767d106 in gids_pin_cmd (card=0x5555557a9090, data=0x7fffffffc350, tries_left=0x0) at card-gids.c:971
#5  0x00007ffff7554904 in sc_pin_cmd (card=0x5555557a9090, data=0x7fffffffc350, tries_left=0x0) at sec.c:172
#6  0x00007ffff76aef98 in sc_pkcs15emu_gids_init (p15card=0x5555557a9aa0) at pkcs15-gids.c:179
#7  0x00007ffff76af3bc in sc_pkcs15emu_gids_init_ex (p15card=0x5555557a9aa0, aid=0x0, opts=0x7fffffffe6f0) at pkcs15-gids.c:242
#8  0x00007ffff75884c4 in sc_pkcs15_bind_synthetic (p15card=0x5555557a9aa0, aid=0x0) at pkcs15-syn.c:151
#9  0x00007ffff756c946 in sc_pkcs15_bind (card=0x5555557a9090, aid=0x0, p15card_out=0x5555557a9840) at pkcs15.c:1281
#10 0x00007ffff692cee6 in pkcs15_bind (p11card=0x5555557a7040, app_info=0x0) at framework-pkcs15.c:317
#11 0x00007ffff6927b6a in card_detect (reader=0x5555557a74e0) at slot.c:328
#12 0x00007ffff69272ce in initialize_reader (reader=0x5555557a74e0) at slot.c:182
#13 0x00007ffff6920695 in C_Initialize (pInitArgs=0x0) at pkcs11-global.c:278
#14 0x000055555555c669 in main (argc=2, argv=0x7fffffffeb78) at pkcs11-tool.c:894
(gdb) 
</pre>

### Proposed Resolution

I think two changes are needed, one to set the correct length of data to parse in card-gids.c and
not parse the uninitialised data.

<pre>
--- a/src/libopensc/card-gids.c
+++ b/src/libopensc/card-gids.c
@@ -533,17 +533,19 @@ static int gids_get_pin_status(sc_card_t *card, int pinreference, int *tries_lef
        r = gids_get_DO(card, GIDS_APPLET_EFID, dataObjectIdentifier, buffer, &buffersize);
        SC_TEST_RET(card->ctx, SC_LOG_DEBUG_NORMAL, r, "unable to update the masterfile");
 
-       p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_COUNTER_OLD_TAG, &datasize);
+       buffersize = buffersize > sizeof(buffer) ? sizeof(buffer) : buffersize;
+
+       p = sc_asn1_find_tag(card->ctx, buffer, buffersize, GIDS_TRY_COUNTER_OLD_TAG, &datasize);
        if (p && datasize == 1) {
                if (tries_left)
                        *tries_left = p[0];
        }
-       p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_COUNTER_TAG, &datasize);
+       p = sc_asn1_find_tag(card->ctx, buffer, buffersize, GIDS_TRY_COUNTER_TAG, &datasize);
        if (p && datasize == 1) {
                if (tries_left)
                        *tries_left = p[0];
        }
-       p = sc_asn1_find_tag(card->ctx, buffer, sizeof(buffer), GIDS_TRY_LIMIT_TAG, &datasize);
+       p = sc_asn1_find_tag(card->ctx, buffer, buffersize , GIDS_TRY_LIMIT_TAG, &datasize);
        if (p && datasize == 1) {
                if (tries_left)
                        *max_tries = p[0];
</pre>

and the other to guard against SEGVs in sc_asn1_find_tag

<pre>
--- a/src/libopensc/asn1.c
+++ b/src/libopensc/asn1.c
@@ -477,6 +477,10 @@ const u8 *sc_asn1_find_tag(sc_context_t *ctx, const u8 * buf,
                /* read a tag */
                if (sc_asn1_read_tag(&p, left, &cla, &tag, &taglen) != SC_SUCCESS)
                        return NULL;
+
+               if (!p)
+                       return NULL;
+
                left -= (p - buf);
                /* we need to shift the class byte to the leftmost
                 * byte of the tag */
</pre>

[patches here](https://gist.github.com/fishsoupisgood/f4575d7cc8db2e48dae1bac356e9e0b6)

### Steps to reproduce

I used debian stretch and centos 7

install GidsApplet [7ba0d7b8ad5368cbdbe988164c90fc26744c5e0c](https://github.com/vletoux/GidsApplet/commit/7ba0d7b8ad5368cbdbe988164c90fc26744c5e0c) on a card (I used a J3A081)

build current master [1d4f59ea51dd1713a3b99186498cb8fe074abc4c](https://github.com/OpenSC/OpenSC/commit/1d4f59ea51dd1713a3b99186498cb8fe074abc4c)

initialize the card with gids-tool -X

then run

test@test:~$ pkcs11-tool -L
Segmentation fault

expected result is
test@test:~$ pkcs11-tool -L
Slot 0 (0x0): Gemalto PC Twin Reader 00 00
  token label        : UserPIN (GIDS card)
  token manufacturer : www.mysmartlogon.com
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 8514e5fff6b123f4
  pin min/max        : 4/15

### Logs

Here's a debug log, but I'm not sure how useful it's going to be 
[debug log here](https://gist.github.com/fishsoupisgood/0b0d20daf54c616085c375c89563d1ec)

**Comment by frankmorgner** [comment]
- I think `sc_asn1_find_tag()` should better check for `tag == SC_ASN1_TAG_EOC`.
- `gids_get_DO()` already performs a length check, so all you have to do in `gids_get_pin_status()` is to change `sizeof(buffer)` with `buffersize`

What do you think, @vletoux?

**Comment by fishsoupisgood** [comment]
I did a quick look for similar problems where an evil card could trigger this behaviour by placing an SC_ASN1_TAG_EOC tag unexpectedly. 

* card-openpgp.c: [pgp_enumerate_blob](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-openpgp.c#L923) and [pgp_parse_and_set_pubkey_output](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-openpgp.c#L2132) have the same issue.

* card-mcrd.c: [process_arr](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-mcrd.c#L609) again has the issue.

* card-isoApplet.c: checks the tag type before proceeding so is fine.
* ef-gdo.c: eplicitly checks for SC_ASN1_TAG_EOC and is fine.
* iso7816.c: [iso7816_process_fci](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/iso7816.c#L346) and [iso7816_select_file](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/iso7816.c#L602) have the issue.
* pkcs15-pubkey.c: explicity checks for SC_ASN1_TAG_EOC and is fine.
* pkcs15-sc-hsm.c: doesn't use the subsequent value of the argument as is fine.
* card-piv.c seems to have quite a few: [piv_general_io](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-piv.c#L566) will return a ludicrous value for recvbuflen, and on 32 bit machines the malloc might not fail. [piv_generate_key](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-piv.c#L671) will SEGV, piv_read_obj_from_file doesn't check but isn't reading untrusted data, piv_get_data is safe, piv_process_discovery has an explicit check, piv_process_history has an explicit check for the first 2 calls, but the [3rd](https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/libopensc/card-piv.c#L2811) is vulnerable.
  
Out of interest has any fuzzing been done against opensc?

**Comment by fishsoupisgood** [comment]
oh and I missed unwrap_key in tools/sc-hsm-tool.c and sc_hsm_generate_key in pkcs15init/pkcs15-sc-hsm.c.

**Comment by vletoux** [comment]
I agree with @frankmorgner proposal.
I’m in travel for 10 days so I won’t be able to make a PR.

**Comment by dengert** [comment]
Interesting observation. 

Reading: "A Layman's Guide to a Subset of ASN. 1, BER, and DER" 1993  (Many copies can be found online)  it looks  like the SC_ASN1_TAG_EOC is only valid when used in "BER  Constructed indefinite-length method" to identify the end of the value of a BER-TLV where the length is a single octet `0x80`.
The "BER  Constructed indefinite-length method" says EOC has tag 00 and length 00. 

It is further complicated by ISO7816-4 "6.2 BER-TLV data objects" which says:
"The value '00' is invalid for the first byte of tag fields." and "a) precludes the use of the “indefinite length” (coded '80'), according to the DER encoding rules;"

And in section: "6.1 SIMPLE-TLV data objects" says: The values '00' and 'FF' are invalid for tag fields.

And in section: "8.4.6 Resolving an extended header" Says: "A tag indicating a constructed encoding followed by '80' means that the complete constructed DO/complete template is included in the byte string." This starts to sound like  "BER  Constructed indefinite-length method" but there is no "00 00" 
to indicate the end. 

Some cards (I can't find the reference) may pad deleted objects with zeros. 

The OpenSC asn1 parsing routines don't appear to make the distinction between "BER Constructed indefinite-length method", "BER Constructed definite-length method" or restrictions of 7816-4 . 

The code in sc_asn1_read_tag appears to be checking for the SIMPLE-TLV  `if (*p == 0xff || *p == 0) {`
and not the  "BER  Constructed indefinite-length method" which would be `if (*p == 0 && *(p+1) == 00)` So it should not be returning SC_SUCCESS but rather SC_ERROR_ASN1_END_OF_CONTENTS.

Correct me if I am wrong, but I don't see any code in OpenSC that is expecting "BER  Constructed indefinite-length method" which is the only place  where SC_ASN1_TAG_EOC  is considered valid.

**Comment by frankmorgner** [comment]
@fishsoupisgood I've fuzzed `opensc-asn1` for a couple of days that didn't reveal any problems. However, that doesn't say anything about the actual use of the ASN.1 data that you've pointed to. However, these pieces of code are harder to fuzz...

@dengert Although I generally agree with your analysis, the impact is quite big. Keeping and coping with `SC_ASN1_TAG_EOC` should be safer, I think.

**Comment by frankmorgner** [comment]
@fishsoupisgood could you try https://github.com/OpenSC/OpenSC/pull/1289 if this fixes your issue?

**Comment by frankmorgner** [comment]
I've created https://github.com/OpenSC/OpenSC/pull/1291, to fix a problem in the above PR.
