### ISSUE TITLE
OpenSC confuses OpenFIPS201's implementation of command chaining.

### ISSUE THREAD

**Issue by fishsoupisgood** [OpenSC/OpenSC#1274]
### Problem Description

with current master [1d4f59ea51dd1713a3b99186498cb8fe074abc4c](https://github.com/OpenSC/OpenSC/commit/1d4f59ea51dd1713a3b99186498cb8fe074abc4c) and current master of OpenFIPS201 [580bb5cd36c41c38d38eb86c985f05dbd38be0d5](https://github.com/makinako/OpenFIPS201/tree/580bb5cd36c41c38d38eb86c985f05dbd38be0d5) opensc is unable to read the certificates on the card

OpenSC send INS_PIV_GET_DATA to  read the certificate from the card

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 08 

and the card responds with 

SW: 53 82 02 A4 70 82 02 9B 61 FF 

as card-piv.c is only probing for the length of the file at this point it doesn't want to read the whole
certificate, and as SC_APDU_FLAGS_NO_GET_RESP in apdu.flags is set, sc_transmit_apdu doesn't read the rest of the data.

the next apdu opensc sends attempts to read the certificate in full.

APDU: 00 CB 3F FF 05 5C 03 5F C1 02 08 

but the card is still waiting for opensc to complete reading the previous INS_PIV_GET_DATA and so responds with

SW: 68 83  (SW_LAST_COMMAND_EXPECTED)

OpenSC then assumes the slot is empty as it failed to read the cert

with the attached patch opensc completes the first read in full

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 08 
SW: 53 82 02 A4 70 82 02 9B 61 FF 
APDU: 00 C0 00 00 FF 
SW: 30 ... 61 FF 
APDU: 00 C0 00 00 FF 
SW: 5B ... 61 A2 
APDU: 00 C0 00 00 FF 
SW: 4A ... 90 00 

and the subsequent read now succeeds.

APDU: 00 CB 3F FF 05 5C 03 5F C1 05 00 
SW: 53 ..  61 FF 
etc.

### Proposed Resolution

If this is a bug in OpenSC rather than an implementation error in OpenFIPS201 then the following patch fixes it. Although the solution is not optimal, as it causes lots of data to be read twice over the 
slow smartcard interface.

<pre>
--- opensc-0.17.1.orig/src/libopensc/apdu.c
+++ opensc-0.17.1/src/libopensc/apdu.c
@@ -424,7 +424,7 @@ sc_set_le_and_transmit(struct sc_card *c
 
 
 static int
-sc_get_response(struct sc_card *card, struct sc_apdu *apdu, size_t olen)
+sc_get_response(struct sc_card *card, struct sc_apdu *apdu, size_t olen, int complete_reads)
 {
 	struct sc_context *ctx  = card->ctx;
 	size_t le, minlen, buflen;
@@ -497,6 +497,11 @@ sc_get_response(struct sc_card *card, st
 			le = minlen;
 	} while (rv != 0 && minlen != 0);
 
+	while ( complete_reads && (rv > 0)) {
+		unsigned char resp[256];
+		size_t resp_len;
+		rv=card->ops->get_response(card, &resp_len, resp);
+	}
 	/* we've read all data, let's return 0x9000 */
 	apdu->resplen = buf - apdu->resp;
 	apdu->sw1 = 0x90;
@@ -512,7 +517,7 @@ sc_get_response(struct sc_card *card, st
  *  @return SC_SUCCESS on success and an error value otherwise
  */
 static int
-sc_transmit(sc_card_t *card, sc_apdu_t *apdu)
+sc_transmit(sc_card_t *card, sc_apdu_t *apdu, int complete_reads)
 {
 	struct sc_context *ctx  = card->ctx;
 	size_t       olen  = apdu->resplen;
@@ -536,8 +541,8 @@ sc_transmit(sc_card_t *card, sc_apdu_t *
 	 *    Unless the SC_APDU_FLAGS_NO_GET_RESP is set we try to read as
 	 *    much data as possible using GET RESPONSE.
 	 */
-	if (apdu->sw1 == 0x61 && (apdu->flags & SC_APDU_FLAGS_NO_GET_RESP) == 0)
-		r = sc_get_response(card, apdu, olen);
+	if (apdu->sw1 == 0x61 && (((apdu->flags & SC_APDU_FLAGS_NO_GET_RESP) == 0) || complete_reads))
+		r = sc_get_response(card, apdu, olen, complete_reads);
 	LOG_TEST_RET(ctx, r, "cannot get all data with 'GET RESPONSE'");
 
 	LOG_FUNC_RETURN(ctx, SC_SUCCESS);
@@ -609,7 +614,7 @@ int sc_transmit_apdu(sc_card_t *card, sc
 				break;
 			}
 
-			r = sc_transmit(card, &tapdu);
+			r = sc_transmit(card, &tapdu, 1);
 			if (r != SC_SUCCESS)
 				break;
 			if (last != 0) {
@@ -629,7 +634,7 @@ int sc_transmit_apdu(sc_card_t *card, sc
 		}
 	} else
 		/* transmit single APDU */
-		r = sc_transmit(card, apdu);
+		r = sc_transmit(card, apdu, 0);
 	/* all done => release lock */
 	if (sc_unlock(card) != SC_SUCCESS)
 		sc_log(card->ctx, "sc_unlock failed");
</pre>

[patch here](https://gist.github.com/fishsoupisgood/1c1b7a80ed8feb03d64ef1a57962ee76)

### Steps to reproduce

Build and install OpenFIPS201 on a smartcard (I had to s/RSAPrivateKey/RSAPrivateCRTKey/g s/ALG_RSA/ALG_RSA_CRT/g to get it to work on a J3A081 ), use the example script to populate the PIV objects. Inject a Key for 9B. Then use yubico-piv-tool to populate slot 9a with a key and selfsigned certitifcate. Finally run

<pre>
root@box:~# pkcs11-tool --type cert --list-objects
Using slot with index 2 (0x8)
</pre>

with the above patch

<pre>
root@box:~# pkcs11-tool --type cert --list-objects
Using slot with index 2 (0x8)
Certificate Object; type = X.509 cert
  label:      Certificate for PIV Authentication
  ID:         01
</pre>

### Logs

```
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] pkcs15.c:2344:sc_pkcs15_read_file: called
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] pkcs15.c:2345:sc_pkcs15_read_file: path=0101cece, index=0, count=-1
[...]
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit:
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 05 08 ..?..\._...
0x7f1a6ef58700 15:34:45.688 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit:
Incoming APDU (10 bytes):
53 82 02 A4 70 82 02 9B 61 FF S...p...a.
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
[...]
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit:
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 05 00 ..?..\._...
0x7f1a6ef58700 15:34:45.708 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f1a6ef58700 15:34:45.720 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit:
Incoming APDU (2 bytes):
68 83 h.
0x7f1a6ef58700 15:34:45.720 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
```

[Full log in gist](https://gist.github.com/fishsoupisgood/2bec0d6b5c0a7fd9472c530fc1192b58)

**Comment by dengert** [comment]
Also posted as:https://github.com/makinako/OpenFIPS201/issues/4

I would argue that this is a bug in the OpenFIPS201. There is no requirement that the application complete reading the block (i.e. only accept a get response) when another command is issued to the card. 

The OpenSC code has worked for years with NIST approved PIV cards using the two step process of reading the first part to get the length then starting over and reading the whole object.     

ISO7816-4  "7.4.2 GET DATA command" says:

"NOTE If the information is too long for a single response data field, then the card shall return the beginning of the information followed by SW1-SW2 set to '61XX'. Then a subsequent GET RESPONSE provides 'XX' bytes of information. **The process may be repeated until** the card sends SW1-SW2 set to '9000'."

Note the "may be repeated".

In the trace using a NIST Demo card (Oberthur ID-One PIV (type A)  
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 02 08
Incoming APDU (10 bytes):
53 82 0B 1B 30 19 D6 50 61 00
(8 bytes read)

(Then starting over after buffer allocated)
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 02 00
Incoming APDU (258 bytes):
53 82 0B 1B 30 19 D6 50 18 58 28 9D 6D C4 64 9C ... 61 00
followed by multiple GET RESPONSE commands to read the rest of the certificate

I could see the  OpenFIPS returning '6883', but from you example, it looks like it will not
accept any other command other the get response, and keep sending '6883'. In other words the card is forcing the middleware to read the whole object. I have not seen any card that tries to force this type of action. 

I am also surprised that the the card is returning '61FF' which would indicate that there are
only 255 more bytes to read, rather then '6100' indication 256 or more bytes.
 
OpenSC is not likely to make any changes in  `libopensc/apdu.c` for a single card (OpenFIPS)
When other implementations of a PIV applet do not have this issue.

**Comment by fishsoupisgood** [comment]
Ah! thank you for doing the standards diving - that seems pretty clear it's their bug (and that the NIST test suite doesn't find it!). I'll have a go at fixing their code, although I'm definitely not a java programmer :)

**Comment by dengert** [comment]
Have a look at this as a fix:

https://github.com/makinako/OpenFIPS201/issues/4#issuecomment-368339028
