### ISSUE TITLE
OpenSC Supported Browser Authentication Using Feitian ePass2003Auto USB Tokens

### ISSUE THREAD

**Issue by mndar** [OpenSC/OpenSC#1276]
I use Feitian ePass2003Auto tokens with GnutLS for my C/C++ applications. They work great. 
Now, I want to use them for client authentication view browsers (Just Firefox & Chrome will do).

I have my libsoup based web server configured for authenticating clients. It works correctly with file based certificates set in Firefox or Chrome but not with opensc-pkcs11.so supported tokens.

With USB tokens, my web server reports that the peer did not send any certificate.  The exact error message is "TLS connection peer did not send a certificate".

Is this some configuration issue or is it just not supported? I think the configuration is fine because I get prompted for the USB token PIN and it accepts/rejects correct/incorrect PINs there.

Does the label of the certificate matter when authenticating via browsers?

Here is a dump of all the contents of the token.
---
```
$ p11tool --provider /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --list-all --login pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29
Token 'Company1SView (User PIN)' with URL 'pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%72%b2%2a%ed%6c%77%29%80%20%7a%df%78%21%f3%ed%99%87%f8%cf%ae;object=SViewClientKey;type=private
	Type: Private key
	Label: SViewClientKey
	Flags: CKA_PRIVATE; 
	ID: 72:b2:2a:ed:6c:77:29:80:20:7a:df:78:21:f3:ed:99:87:f8:cf:ae

Object 1:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%72%b2%2a%ed%6c%77%29%80%20%7a%df%78%21%f3%ed%99%87%f8%cf%ae;object=SViewClientKey;type=public
	Type: Public key
	Label: SViewClientKey
	Flags: CKA_SENSITIVE; 
	ID: 72:b2:2a:ed:6c:77:29:80:20:7a:df:78:21:f3:ed:99:87:f8:cf:ae

Object 2:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%96%ef%10%a9%fe%b8%49%43%9c%10%f1%51%ea%df%77%71%04%9a%a0%96;object=SViewClientKey;type=cert
	Type: X.509 Certificate
	Label: SViewClientKey
	ID: 96:ef:10:a9:fe:b8:49:43:9c:10:f1:51:ea:df:77:71:04:9a:a0:96

Object 3:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%96%ef%10%a9%fe%b8%49%43%9c%10%f1%51%ea%df%77%71%04%9a%a0%96;object=SViewClientKey;type=public
	Type: Public key
	Label: SViewClientKey
	Flags: CKA_SENSITIVE; 
	ID: 96:ef:10:a9:fe:b8:49:43:9c:10:f1:51:ea:df:77:71:04:9a:a0:96

Object 4:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%c3%3e%36%dd%96%e3%3e%b0%d3%7d%8f%71%22%14%3a%5e%5e%c0%ca%6e;object=CACertificate;type=cert
	Type: X.509 Certificate
	Label: CACertificate
	ID: c3:3e:36:dd:96:e3:3e:b0:d3:7d:8f:71:22:14:3a:5e:5e:c0:ca:6e

Object 5:
	URL: pkcs11:model=PKCS%2315;manufacturer=EnterSafe;serial=21231F1B8005000C;token=Company1SView%20%28User%20PIN%29;id=%c3%3e%36%dd%96%e3%3e%b0%d3%7d%8f%71%22%14%3a%5e%5e%c0%ca%6e;object=CACertificate;type=public
	Type: Public key
	Label: CACertificate
	Flags: CKA_SENSITIVE; 
	ID: c3:3e:36:dd:96:e3:3e:b0:d3:7d:8f:71:22:14:3a:5e:5e:c0:ca:6e
```
---

Regards
Mandar Joshi

**Comment by FeitianSmartcardReader** [comment]
Hi Mandar Joshi

This is Hongbin, from Feitian. 

Your feedback already forward to our team to check, we will back to you soon, thanks

**Comment by dengert** [comment]
What does Firefox show when you look at the the security devices and certificates?  
Windows: tools->options->Privacy&Security->Security Devices
Linux: 3 bars->Preferences->Privacy&Security->Security Devices

Most likely the server sent over a list of CAs it is willing to accept users from.  But none of your certificates are signed by one of these.

**Comment by mndar** [comment]
It shows me the connected token but does not list the certificates in it.
I've attached a screenshot
![feitian](https://user-images.githubusercontent.com/10995098/36652339-2bf59084-1ad4-11e8-8819-2ca45e627ef0.png)

**Comment by dengert** [comment]
OK, then close that window and go to the View Certificates.

You may need to load the `opensc-pkcs11-onepin.so`  (I may have the name wrong, but it has onepin in the name).

**Comment by mndar** [comment]
I tried /usr/lib/x86_64-linux-gnu/onepin-opensc-pkcs11.so 
Firefox says "Unable to add module"

**Comment by mndar** [comment]
Had to unload opensc-pkcs11.so before loading onepin-opensc-pkcs11.so

But that didn't change anything. Nothing is listed in 'Your Certificates' or 'Other'

**Comment by FeitianSmartcardReader** [comment]
@mndar sorry for late reply. R&D check and found there is no same ID in your key, for example, the Public key, private key and certificate should have same ID, when you do SSL authentication, need matching id(cka_id), like below:

$pkcs11-tool -O --login 

Using slot 0 with a present token (0x0)
Logging in to "User PIN (epass2003)".
Please enter User PIN: 
Private Key Object; RSA 
label: Users's ESCA ID
ID: 37326233653334612d323163382d313165382d613161332d633831663636313366316532
Usage: sign
Certificate Object; type = X.509 cert
label: Users's ESCA ID
ID: 37326233653334612d323163382d313165382d613161332d633831663636313366316532
Public Key Object; RSA 1024 bits
label: Users's ESCA ID
ID: 37326233653334612d323163382d313165382d613161332d633831663636313366316532
Usage: encrypt, verify

**Comment by mndar** [comment]
Thanks for the insight. I'll configure my token the way you have mentioned and revert back.

**Comment by mndar** [comment]
Apologies for the delay in response. The solution you suggested worked. Thank You

For those facing the same problem as me, all you have to do is specify id with "--id" option while writing the certificate.

**Comment by frankmorgner** [comment]
It's never too late, thanks for the update!
