### ISSUE TITLE
PKCS#11: Multithreading support in OpenSC

### ISSUE THREAD

**Issue by sahilnxp** [OpenSC/OpenSC#1279]
Hi All,

I was looking at the code on how OpenSC handles multithreading and I am confused about a case.
Please correct me where ever I am wrong, I am new to this.

Suppose there are 2 thread A and B.
A just callled C_Finalize(), and got the lock at 
https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/pkcs11/pkcs11-global.c#L311
and is in between C_Finalize just before sc_release_context(context);

and at the same time B called C_GetInfo().
B will try to take the lock and will be looping on the while statement in below code after checking the context and global locks variable.
https://github.com/OpenSC/OpenSC/blob/1d4f59ea51dd1713a3b99186498cb8fe074abc4c/src/pkcs11/pkcs11-global.c#L783

And then C_Finalize cleaned the context & global lock locking variable and exit.

Now B was looping in the while statement, First of all I think there will be crash in this while statement, because we have cleared the **global_lock** and **global_locking**.

Lets assume we handled this situation and got out of this sc_pkcs11_lock() function, It will return CKR_OK only, since B have already checked if (context == NULL).
So B will continue its execution even if library is finalized by another thread.
I think B should return CKR_CRYPTOKI_NOT_INITIALIZED in this case and exit.

Please check this scenario, may be I am totally wrong about it.

Thanks.
Sahil

**Comment by frankmorgner** [comment]
Your analysis, in general, is correct, I think. However, this undefined behavior is specified by PKCS#11 (see description of `C_Finalize`, my emphasis):

> ''Despite the fact that the parameters supplied to C_Initialize can in general allow for safe multi-threaded access to a Cryptoki library, **the behavior of C_Finalize is nevertheless undefined if it is called by an application while other threads of the application are making Cryptoki calls**. The exception to this exceptional behavior of C_Finalize occurs when a thread calls C_Finalize while another of the application's threads is blocking on Cryptoki's C_WaitForSlotEvent function. When this happens, the blocked thread becomes unblocked and returns the value CKR_CRYPTOKI_NOT_INITIALIZED.''
