### ISSUE TITLE
Feature request: tool that senses card presence

### ISSUE THREAD

**Issue by Telefonorosso** [OpenSC/OpenSC#1281]
### Problem Description

In Linux I use this command to check whether a card in inserted:

> opensc-tool -l  |  grep -q Yes  &&  c=1  ||  c=0

But to do its job it performs lots of operations, eg. talk to the card, parse all the supported ATR, etc.

### Proposed Resolution

Isolate the

> static int pcsc_detect_card_presence(sc_reader_t *reader)

routine in a compact, dedicated binary to be bundled in OpenSC

### Steps to reproduce (Linux)

strace opensc-tool -l

**Comment by martinpaljak** [comment]
What does the "presence" mean? If a card is inserted? Which card? What if I have many readers? What would be the command line interface? What is the purpose? Why don't you make a dedicated small script with, say, pyscard?

**Comment by Telefonorosso** [comment]
Hello.
For presence I mean the card is physically inserted in the reader, any kind of card.
Example:

> detectcard -v 001:003
> Card is PRESENT

> detectcard 001:003
> echo $?
> 0

> detectcard -h
> usage: detectcard [-v] BUS:DEV
> [-v] verbose operation: print a human-readable message to stdout. Otherwise exit status will be provided:
> 0 -> card present
> 1 -> card NOT present
> 255 -> reader non recognised or general error

**Comment by Telefonorosso** [comment]
closed in an error

**Comment by martinpaljak** [comment]
This is *very* low level (USB ID-s do not make sense on OpenSC layer). Bring this over to pcsc-lite for a PC/SC layer tool (part of pcsc_scan ?) or maybe CCID. But your use case seems to call for something homegrown.

**Comment by Telefonorosso** [comment]
Thank you for your advice, pcsc_scan seems the right tool. Regards
