### ISSUE TITLE
RFE: make EC_POINT_NO_ASN1_OCTET_STRING a runtime option in pkcs11-tool

### ISSUE THREAD

**Issue by aalba6675** [OpenSC/OpenSC#1286]
### Problem Description

Version: RHEL packaging opensc-0.16.0-5.20170227git777e2a3.el7.x86_64

For pkcs11-tool --write of EC public keys SafeNet HSM requires the full DER (including TAG, LENGTH). Depending on packagers option we send full DER or just content bytes. 

### Proposed Resolution
Command line option for pkcs11-tool to enable or disable DER TAG/LENGTH on writing EC public keys

### Steps to reproduce
1. opensc compiled without EC_POINT_NO_ASN1_OCTET_STRING; e.g. CentOS/RHEL packaging
2. pkcs11-tool --write ec_public_key.der will fail with SafeNet HSM with invalid EC_POINT
3. rebuild package with EC_POINT_NO_ASN1_OCTET_STRING defined, then the --write works

### See also
https://github.com/OpenSC/OpenSC/issues/1285

**Comment by mouse07410** [comment]
Does it even make sense to write EC keys *not* in DER?

**Comment by aalba6675** [comment]
Agreed - strange that RHEL made the decision to send content bytes instead of DER. Can I propose that the workaround be removed altogether?  Maybe the naming of the define is confusing: it sounds like if you define it you will send "NO_ASN1" (which means content bytes?), therefore the packager chose not to define it. Just speculating here.

**Comment by frankmorgner** [comment]
With accepting #1287, I think we can close this issue, right?

**Comment by aalba6675** [comment]
@frankmorgner Yes, thank you.
