### ISSUE TITLE
Infinite loop when using spice/qemu smartcard emulation

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#1294]
Hi,

When using opensc instead of coolkey (as advised by the documentation) to use a smartcard inside a VM, I see that trying to list the certificates on the guest something is going into an infinite loop.

libcacard is displaying this in loop:
```
(remote-viewer:23079): libcacard-DEBUG: 11:25:52.083: vreader_xfr_bytes: CLS=0x0,INS=0x84,P1=0x0,P2=0x0,Lc=0,Le=8 get challenge
(remote-viewer:23079): libcacard-DEBUG: 11:25:52.083: vreader_xfr_bytes: status=26880 sw1=0x69 sw2=0x0 len=0 (total=2)
```
That's maybe related to #1278 ?

Edit: opensc 0.17.0

**Comment by frankmorgner** [comment]
@Jakuje?

**Comment by Jakuje** [comment]
Do you have updated libcacard?

**Comment by bigon** [comment]
I've libcacard 2.5.3 on my host

**Comment by Jakuje** [comment]
It looks like that patch should be there.

The #1278 is a Firefox/NSS bug. Where do you list certificates? In `pkcs11-tool` or in Firefox 60+?
