### ISSUE TITLE
Smartcard HSM: PIN length not checked when initializing PIN

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1299]
### Problem Description

For Smartcard HSM a user PIN can have only 15 or less ASCII numeric. This is checked when changing PIN, but not when initializing PIN, so that users get no feedback of failing PIN setting, although it did.

### Proposed Resolution
It looks like this something like this [if-clause](https://github.com/OpenSC/OpenSC/blob/fe0d6f9187f1460863271e51dc4040167ffe10e3/src/pkcs11/framework-pkcs15.c#L1769) is needed in [this function](https://github.com/OpenSC/OpenSC/blob/fe0d6f9187f1460863271e51dc4040167ffe10e3/src/pkcs11/framework-pkcs15.c#L1931) as well.

### Steps to reproduce
Compare results of 
```
pkcs11-tool --login --pin 648219 --change-pin --new-pin 1234567812345678
```
with
```
pkcs11-tool --login --login-type so --init-pin --new-pin 1234567812345678
```
and
```
sc-hsm-tool --initialize --so-pin 3537363231383830 --pin 1234567812345678
```

### Logs
```
$ pkcs11-tool --login --pin 648219 --change-pin --new-pin 1234567812345678
Using slot 0 with a present token (0x0)
error: PKCS11 function C_SetPIN failed: rv = CKR_PIN_LEN_RANGE (0xa2)
Aborting.
$ pkcs11-tool --login --login-type so --init-pin --new-pin 1234567812345678
Using slot 0 with a present token (0x0)
Logging in to "UserPIN (SmartCard-HSM)".
Please enter SO PIN:
User PIN successfully initialized
$ sc-hsm-tool --initialize --so-pin 3537363231383830 --pin 1234567813245678
Using reader with a card: Nitrokey Nitrokey HSM (010000000000000000000000) 00 00
```

**Comment by cdanger** [comment]
Furthermore, if you don't specify the PINs on the initialize command line, the prompt wrongly says `Enter initial User-PIN (6 - 16 characters):`

```
$ sc-hsm-tool --initialize 
Using reader with a card: Nitrokey Nitrokey HSM (010000000000000000000000) 00 00
Enter SO-PIN (16 hexadecimal characters) : 

Enter initial User-PIN (6 - 16 characters) :
```

**Comment by CardContact** [comment]
This is a little more complex: The SmartCard-HSM supports a User-PIN in the range 6 to 16. Unfortunately Class-3 readers (in particular the common Reiner SCT) only support displays with 16 characters and consequently allow only 15 digit entries (one column reserved for the cursor).

The reader also rejects a VERIFY PIN command if the maximum PIN length specified in the command exceeds 15 characters. That was the reason we changed the advertised range in OpenSC from 6-16 to 6-15.

One solution would be to change the PC/SC code and make some reader specific additions to limit the maximum number of PIN digits to the range supported by the reader. This can be a daunting task, as almost every Class-3 reader has quirks and testing with various firmware version would be needed.

We could also limit the number of digits in sc-hsm-tool, but that would limit the use of the full PIN range in other applications.

**Comment by frankmorgner** [comment]
I think pkcs15_init_pin doesn't check the length, because most cards don't have the length predefined. This limit get set in the PKCS#15 profile (which is what you want to initialize with pkcs15_init_pin). It would be possible to add some card specific addition in pkcs15_init_pin, but that looks like an ugly solution to an unimportant problem.
