### ISSUE TITLE
MacOS: need to lock the token when screensaver starts

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1305]
### Problem Description

MacOS X 10.13.4.

We use tokens to authenticate login and screensaver unlock (among other things). Tokens like [YubiKey Nano](https://www.yubico.com/product/yubikey-4-series/?gclid=EAIaIQobChMIhOjuybCa2gIVR7jACh10RwwiEAAYASAAEgKK9fD_BwE#yubikey-4-nano) can be conveniently left inserted in the USB port (imitating TPM that Apple doesn't put in their computers). Our users love that. *And this differs from how smart cards would be used. "Normal" smartcards would be removed when the user steps away from the computer, while Nano and such would stay inserted.*

The problem is - if somebody else walks to a computer with locked screen and attempts to unlock it, he gets only the "OK" prompt instead of being prompted for a PIN. Thus, anybody would be able to unlock screensaver.

### Proposed Resolution

Lock the token ("UNVERIFY", "LOGOUT") when screensaver starts. Probably tokend's job.

### Steps to reproduce

1. Insert a token. YubiKey Nano is the best example because that's the type designed to stay in, but you can demonstrate this behavior with any smart card.
2. Login to the computer, do whatever. The token remains unlocked.
3. Start screensaver. Screen/computer is locked, but the token is still in "PIN VERIFIED" state.
4. Move the mouse or wake the display up in any other manner. 
5. Observe that you are *not* prompted for your PIN - but just whether it's OK to unlock.

@dengert, you probably know - is there a command to "unverify" the PIN (to lock the token)? Could you show it to me? You had a script to check the card status - it could probably be adopted to "unverifying" the card as well? Would you mind re-posting it?

**Comment by frankmorgner** [comment]
Forcing a logout could be done by `sc_reset()`...

Note that, I personally will not go into detailed debugging with Tokend. Please check if the problem also exists with [OpenSCToken](https://github.com/frankmorgner/OpenSCToken), which is all I will improve in the future.

**Comment by dengert** [comment]
The same problem, with screensaver and the token still in the reader,  may exist on other systems too.
The main issue is smart cards are not designed to be left in the reader when you lock the screen. Most systems have just the opposite option, lock the screen when you remove the smartcard.  

This creates problems if other applications  (running or not) that have a cached PIN or a PIN in a script. 
Even if you reset the card or "UNVERIFY"  these applications could cause a verify to be done and you are back with the original problem. 

Something to look at: Have screensaver require exclusive access to the card via PCSC so no other application can access it.  (You did not say if it was a requirement to have the card active for other processes while screen saver is active.)  

Also look at screensaver doing the reset upon wake up.  You will need to have some fall back if you can not get exclusive access or can not  reset the card. 

You could also look at what other options screensaver gives you to login to the local machine.  A local password first?

You could also look at screensaver using a key with CKA_ALWAYS_AUTHENTICATE which would  require a PIN entry. 

A side effect of leaving the card in the reader, is someone could by accident (or on purpose) try multiple wrong pins which would lock your card.

**Comment by mouse07410** [comment]
> The same problem, with screensaver and the token still in the reader, may exist on other systems too.

Understood.

> This creates problems if other applications (running or not) that have a cached PIN or a PIN in a script. Even if you reset the card or "UNVERIFY" these applications could cause a verify to be done and you are back with the original problem.

Correct, and unpleasant. I'm not sure I know of a good way of addressing this, short of hoping that there aren't any user applications that use smartcard other that "hit and forget", and the only system applications are `pivtoken`, `OpenSC.tokend`, and screensaver.

> Something to look at: Have screensaver require exclusive access to the card via PCSC so no other application can access it. (You did not say if it was a requirement to have the card active for other processes while screen saver is active.)

I'm cringing at the thought of making the access exclusive, especially after we spent so much effort allowing multiple apps to work concurrently (sort of) with a multi-applet token. But I'll do that if it turns out to be the only solution. Though no, when the screensaver is active - no other app should be allowed to use the token.

> Also look at screensaver doing the reset upon wake up. You will need to have some fall back if you can not get exclusive access or can not reset the card.

This sounds like a better option. I will look into this, thanks!

> You could also look at what other options screensaver gives you to login to the local machine. A local password first?

Since we moved *from* password-based auth to smartcards, this probably won't fly...

> You could also lock screensaver using a key with CKA_ALWAYS_AUTHENTICATE which would require a PIN entry.

Possibly. But the only such key is Digital Signature, and we currently use PIV Auth... I'll consider this idea, thanks!

> A side effect of leaving the card in the reader, is someone could by accident (or on purpose) try multiple wrong pins which would lock your card.

Oh yes! I'm willing to risk this, at least for now.

> The main issue is smart cards are not designed to be left in the reader when you lock the screen. Most systems have just the opposite option, lock the screen when you remove the smartcard.

Yes I realize that. This use case goes against how a normal smartcard would be normally used. Here's a somewhat longish explanation that hopefully would make what I need appear more sensible.

With normal smartcards: 
- You carry it with *you* (rather than with a computer);
- You connect it to a computer only to perform a set of operations, and remove it as soon as they are completed.

Some users complain (this is an incomplete list, and I'm not commenting on or judging these complaints) that:
- Smartcard is yet another token they have to carry and worry about;
- It is inconvenient to insert/remove it multiple times, especially with portable/pocket readers;
- It's easy to forget and leave in the computer at the end of day.

Vendors apparently heard these cries and came up with products that mitigate the above inconveniences, albeit at a price. I'm aware of two solution classes:
- Virtual Smart Card (exclusively on Windows)
- Physical tokens (e.g., YubiKey Nano) designed for "long-term insertion"  :-)

Virtual Smart Cards are already available starting with MS Windows 8 (AFAIK). There is plenty of info on the 'Net about Virtual Smart Cards:
- [Virtual Smart Card Overview](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview)
- [Deploy Virtual Smart Cards](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-deploy-virtual-smart-cards)
- [Setting up Virtual Smart Card for logon...](https://blogs.technet.microsoft.com/askds/2016/05/11/setting-up-virtual-smart-card-logon-using-virtual-tpm-for-windows-10-hyper-v-vm-guests/)

We're trying to replicate at least some of those "comfort features" for Mac and Linux users, with devices like YubiKey Nano and ACS CryptoMate Nano. These products are not the "normal" smartcards - they are devices of a very small form-factor, designed to be inserted into a USB port and stay there for a reasonably long time, almost like a built-in security chip. You don't worry about leaving them plugged in - they're designed for that. 

I use YubiKey Nano, because plenty of software works with it, including important Open Source packages like OpenSC, OpenSSL, and libp11. The fact that Yubico support is pretty responsive also helps. In short, I can use Nano for everything I can use a normal PIV for (except for badging in, or using it as a photo ID ;). *We also tried ACS CryptoMate Nano, but could find no useful software support whatsoever.*

And it all works well - with one notable exception: when the user locks the computer by starting a screensaver and leaves it for a while, anybody can walk in to that computer and unlock the screensaver by just pressing any key on the keyboard and then clicking "OK" on the unlock confirmation popup.

That was a very long-winded way to explain what problem exactly I'm trying to solve, and why. My apologies for not being succinct here.

> Forcing a logout could be done by `sc_reset()`...

Thank you! Will try it. @frankmorgner is there a particular place in the tokend code that in your opinion would be best for this call?

> Note that, I personally will not go into detailed debugging with Tokend. Please check if the problem also exists with `OpenSCToken`, which is all I will improve in the future.

Understood - but at this time OpenSCToken (as far as I understand the services it provides) doesn't satisfy our needs, aka it does not help with:
- Providing a reasonably convenient GUI for checking the tokens and the certs on them (aka Keychain Access)
- Enabling apps such as MS Office (and especially Outlook), Google Chrome, Adobe Acrobat to use keys on the token

If I'm wrong here, please do correct me. I in general would like to understand what capabilities OpenSCToken provides that the native `pivtoken` doesn't.

**Also, I'd appreciate your comments on the parameter `transaction_end_action = reset;` in the `opensc.conf`.**

**Comment by dengert** [comment]
From what you describe above, you and the user are expecting to enter the PIN to unlock the computer.

Maybe the solution is in the screensaver. 
Why doesn't the screensaver always prompt for the PIN? 
Is this some feature of the Yubico and its button?
Does your screensaver use PAM? 

You should not have to depend on the card being "unverified", You could force screensaver to always prompt for the pin. Then do verify command to the card, and if it fails it was the wrong pin, if its correct card is unlocked, and so is the computer.

Don't depend on the login state of the card, always do a verify from screensaver. 

`pkcs11-tool --login -I` could be used. (Need to look at return codes, and make sure it tells you if
the login worked or not. ) you need to specify some operation to get the --login to prompt.

**Comment by frankmorgner** [comment]
@mouse07410 look into `void OpenSCToken::unverifyPIN(int pinNum)`

**Comment by mouse07410** [comment]
Thank you - will check and report.

**Comment by mouse07410** [comment]
Checked: adding `sc_reset(mScCard, 1);` to `OpenSCToken::unverifyPIN()` did not cause any problem - but did not help either. The system did not prompt for the PIN, but otherwise behaved fine.

Setting `transaction_end_action = reset;` in `opensc.conf` accomplished what I wanted - but at the cost of breaking Keychain Access. With this setting Keychain Access is unable to unlock the token.

Here's the complete log: 
[opensc-lock-debug.txt](https://github.com/OpenSC/OpenSC/files/1885693/opensc-lock-debug.txt)
Maybe you could figure what's going wrong there.

> Maybe the solution is in the screensaver.

Maybe, but it doesn't appear very configurable. :-(

> Why doesn't the screensaver always prompt for the PIN?

I don't know. :-(

> Is this some feature of the Yubico and its button?

Nope.

> Does your screensaver use PAM?

Yes I think so.

> You could force screensaver to always prompt for the pin

I wish I knew how.

**Comment by frankmorgner** [comment]
I don't know what you've tried. I would go with the following:
```diff
diff --git a/OpenSC/OpenSCToken.cpp b/OpenSC/OpenSCToken.cpp
index d31686e..30a2ecd 100644
--- a/OpenSC/OpenSCToken.cpp
+++ b/OpenSC/OpenSCToken.cpp
@@ -209,8 +209,10 @@ void OpenSCToken::unverifyPIN(int pinNum)
 {
        sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, "In OpenSCToken::unverifyPIN(%d)\n", pinNum);
 
-       if (pinNum != -1)
-               CssmError::throwMe(CSSM_ERRCODE_SAMPLE_VALUE_NOT_SUPPORTED);
+       sc_pkcs15_pincache_clear(mScP15Card);
+       if (sc_logout(mScCard) != SC_SUCCESS) {
+               sc_reset(mScCard, 1);
+       }
 
        mLocked = true;
 }
```

**Comment by mouse07410** [comment]
Yes I tried this code. The result of it is - the user is prompted with the "OK" popup (not a PIN prompt), but with this patch the screen unlock fails. In fact, with this patch after the screensaver was started for the second time, the token became unusable until removed and re-inserted.

So far the only working solution appears to be `transaction_end_action = reset;` in `opensc.conf`.

**Comment by frankmorgner** [comment]
As said above, I won't go into more debugging. If you see the same problem in OpenSCToken, please let me know.

**Comment by frankmorgner** [comment]
So far its a good enough solution to have a workaround in place

**Comment by mouse07410** [comment]
> If you see the same problem in OpenSCToken, please let me know.

Unfortunately I cannot use OpenSCToken because it does not address our main need - to allow applications like MS Office and Chrome use keys on a hardware token. The fact that it doesn't display the token as a keychain is also an inconvenience, albeit a secondary one.

So until all the "big" apps move from CDSA framework to CTK, I cannot abandon tokend.

> So far its a good enough solution to have a workaround in place

Yes, but... It looks like I need to pick one - either the ability to have the Nano token stay in the USB port securely for a long time, or the ability to use CAC. For OpenSC tools like `pkcs11-tool` I can probably work around this by having two `opensc.conf` files - one that locks, and the other one that's CAC-friendly. But I've no idea how I'd pass that `OPENSC_CONF` to, e.g., MS Outlook or Adobe Acrobat. Is it possible?

**Comment by mouse07410** [comment]
> Use scripts to start the applications with environment variable OPENSC_CONF= could work

Thanks - I'll experiment with this for "normal" apps.

> Could work with screensaver too.

I doubt it - because (as I understand) screensaver relies on tokend. And tokend starts when the card is inserted - and keeps running until the card is removed. So whatever config the tokend started with, is going to stay "active" until the card is removed from the reader. Thus, I don't see how I couldd start screensaver with anything that could affect the running tokend.

**Comment by mouse07410** [comment]
@frankmorgner @dengert would you see a problem if tokend listens for a signal/message/notification that screensaver started, and performs `unverifyPIN()` upon receiving it?

**Comment by frankmorgner** [comment]
If it's a hack (sounds like one!), I would not accept it. Tokend has long been deprecated, OpenSC.tokend should receive nothing but fixes. Users and Developers should make the transition to CTK.

**Comment by dengert** [comment]
The other option you may want to explore, is PCSC SCardConnect and SCardReconnect  use of the dwShareMode parameter. 

https://pcsclite.alioth.debian.org/api/group__API.html
https://pcsclite.alioth.debian.org/api/pcsclite_8h.html#aedc5ddb6c12dd0e9f522d4c669ca9135

opensc.conf has a "connect_exclusive" parameter used by both. 
See reader-pcsc.c and `pcsc_connect()` and `pcsc_reconnect()`. Note  the comment
`/* Try again to compete with Tokend probes */`

You could actually write your own program independent of OpenSC to connect to the reader in 
SCARD_SHARE_EXCLUSIVE or SCARD_SHARE_DIRECT and hold it as long as screensaver is running. 

(Never tried this, or what effect this would have.)

**Comment by frankmorgner** [comment]
https://github.com/OpenSC/pam_pkcs11/ has [such](https://opensc.github.io/pam_pkcs11/doc/pam_pkcs11.html#eventmgr) a [tool](https://github.com/OpenSC/pam_pkcs11/blob/master/src/tools/pkcs11_eventmgr.c)
