### ISSUE TITLE
Clicking on notifications generated by opensc-notify may cause desktop to hang indefinitely

### ISSUE THREAD

**Issue by dpward** [OpenSC/OpenSC#1309]
### Problem Description

`opensc-notify` was introduced after 0.17.0 was released. When I run the current development version of OpenSC on RHEL 7.4, I now see desktop notifications appear in GNOME 3 when my smart card is inserted or removed, or when the card is unlocked after entering the PIN.

Clicking these notifications though will often cause my desktop to hang indefinitely. When this happens, I can move the mouse but cannot click on anything. I cannot use the keyboard, except that rarely it still allows me to switch to another TTY using Ctrl+Alt+F<#>. The hang will persist even after I remove my smart card. It often requires a cold reboot to use my system again.

### Proposed Resolution

Other applications running in GNOME 3 can cause an action to be performed when a desktop notification is clicked. For example: open GNOME Terminal, run the command `sleep 10`, and then minimize the window. Soon, a "Command completed" desktop notification will appear; clicking it before it disappears will open the GNOME Terminal window where the command was run.

Not every type of desktop notification triggers an action when it is clicked. If it does not, the notification is just removed from the screen.

It would seem just from observation that `opensc-notify` is unintendedly handling events when a notification it produces is clicked, and unfortunately it is doing it in a way that is hanging the desktop.

### Logs

I'm unsure where exactly to start collecting logs for this issue (journald, OpenSC, etc) but can post anything that is helpful.

**Comment by frankmorgner** [comment]
could you test with master? I think its fixed already...

**Comment by dpward** [comment]
This issue was actually happening with master when I opened it. Please let me know if there's logging or other testing that would be helpful.

**Comment by frankmorgner** [comment]
@dpward could you try https://github.com/OpenSC/OpenSC/pull/1312?

**Comment by dpward** [comment]
@frankmorgner #1312 seems to fix it. Thanks!
