### ISSUE TITLE
SmartCard-HSM does not login with SO-PIN on command line

### ISSUE THREAD

**Issue by johndoe31415** [OpenSC/OpenSC#1318]
I'm using OpenSC that's included in Ubuntu Artful on x86_64, i.e., 0.17.0-1 together with a NitroKey HSM (SmartCard-HSM) version 2.6.

I want to check if a given SO-PIN is correct for the HSM on the command line. Fir this, I do:

```
$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --login --list-objects --login-type so --so-pin 3537363231383999
Using slot 0 with a present token (0x0)
```

The command always comes back as successful and the SO-PIN fail counter is not reduced on wrong SO-PIN values. It's my impression that the command is a no-op.

When I omit the "--so-pin" parameter on the command line, however, it does prompt for entering a SO-PIN value. If this value is incorrect, pkcs11-tool correctly fails and the SO-PIN counter is decremented.

Please advise if this is something I'm doing wrong of if the problem lies with OpenSC.
Thank you,
Joe

**Comment by CardContact** [comment]
The SmartCard-HSM supports only one role for login, the plain user. The SO-PIN can not be used for login, but only to reinitialize the device or to unblock/reset the user PIN.

Specifying the SO-PIN on the command line has only an effect, if the token is initialized or the User PIN is reset in the same command. Internally the sc-hsm driver will cache the SO-PIN until a subsequent RESET RETRY COUNTER or INITIALIZE is received. At that point in time, the SO-PIN is checked and the retry counter updated accordingly.
