### ISSUE TITLE
PivTool generation of 2048-bit (0x07) and 3072-bit (0x05) keys fails with incorrect parameters error

### ISSUE THREAD

**Issue by forensicsguy817** [OpenSC/OpenSC#1323]
### Problem Description

The piv-tool.exe generation of 2048-bit (0x07) and 3072-bit (0x05) keys fails with incorrect parameters error. Using 1024-bit (0x06) seems to work. Command output of failure is below:

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>piv-tool -A A:9B:03 -G 9A:07 -o pubkey.pem**
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0
**gen_key failed -1205**

I was following the example from the Wiki here https://github.com/OpenSC/OpenSC/wiki/PivTool#generate-a-key-pair but trying to generate a 2048/3072 bit key instead using 0x05 and 0x07 for the algorithm.

The operating system is:  **Windows 10-64-bit**
The PIV card being tested is: **Gemalto IDPrime PIV Card 2.0 C1070904**

Information on Current OpenSC/Card/Drivers:

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -l**
#Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             SCM Microsystems Inc. SCR33x USB Smart Card Reader 0

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -a**
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0
3b:7d:96:00:00:80:31:80:65:b0:83:11:11:e5:83:00:90:00

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -n**
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0
PIV-II card

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool --info**
OpenSC 0.17.0 [Microsoft 1800]
Enabled features:pcsc openssl zlib

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>pkcs15-tool -D**
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0
PKCS#15 Card [PIV_II]:
        Version        : 0
        Serial number  : 00000000
        Manufacturer ID: piv_II
        Flags          :
PIN [PIV Card Holder pin]
        Object Flags   : [0x1], private
        Auth ID        : 02
        ID             : 01
        Flags          : [0x32], local, initialized, needs-padding
        Length         : min_len:4, max_len:8, stored_len:8
        Pad char       : 0xFF
        Reference      : 128 (0x80)
        Type           : ascii-numeric

PIN [PIV PUK]
        Object Flags   : [0x1], private
        ID             : 02
        Flags          : [0xF2], local, initialized, needs-padding, unblockingPin, soPin
        Length         : min_len:4, max_len:8, stored_len:8
        Pad char       : 0xFF
        Reference      : 129 (0x81)
        Type           : ascii-numeric

Data object 'Card Capability Container'
        applicationName: Card Capability Container
        applicationOID:  2.16.840.1.101.3.7.1.219.0
        Path:            db00
Data object read failed: File not found
Data object 'Card Holder Unique Identifier'
        applicationName: Card Holder Unique Identifier
        applicationOID:  2.16.840.1.101.3.7.2.48.0
        Path:            3000
Data object read failed: File not found
Data object 'Unsigned Card Holder Unique Identifier'
        applicationName: Unsigned Card Holder Unique Identifier
        applicationOID:  2.16.840.1.101.3.7.2.48.2
        Path:            3010
Data object read failed: File not found
Data object 'X.509 Certificate for PIV Authentication'
        applicationName: X.509 Certificate for PIV Authentication
        applicationOID:  2.16.840.1.101.3.7.2.1.1
        Path:            0101
Data object read failed: File not found
Data object 'Cardholder Fingerprints'
        applicationName: Cardholder Fingerprints
        applicationOID:  2.16.840.1.101.3.7.2.96.16
        Path:            6010
        Auth ID:         01
Data object 'Printed Information'
        applicationName: Printed Information
        applicationOID:  2.16.840.1.101.3.7.2.48.1
        Path:            3001
        Auth ID:         01
Data object 'Cardholder Facial Image'
        applicationName: Cardholder Facial Image
        applicationOID:  2.16.840.1.101.3.7.2.96.48
        Path:            6030
        Auth ID:         01
Data object 'X.509 Certificate for Digital Signature'
        applicationName: X.509 Certificate for Digital Signature
        applicationOID:  2.16.840.1.101.3.7.2.1.0
        Path:            0100
Data object read failed: File not found
Data object 'X.509 Certificate for Key Management'
        applicationName: X.509 Certificate for Key Management
        applicationOID:  2.16.840.1.101.3.7.2.1.2
        Path:            0102
Data object read failed: File not found
Data object 'X.509 Certificate for Card Authentication'
        applicationName: X.509 Certificate for Card Authentication
        applicationOID:  2.16.840.1.101.3.7.2.5.0
        Path:            0500
Data object read failed: File not found
Data object 'Security Object'
        applicationName: Security Object
        applicationOID:  2.16.840.1.101.3.7.2.144.0
        Path:            9000
Data object read failed: File not found
Data object 'Discovery Object'
        applicationName: Discovery Object
        applicationOID:  2.16.840.1.101.3.7.2.96.80
        Path:            6050
        Data (20 bytes): 7E124F0BA0000003080000100001005F2F026010
Data object 'Key History Object'
        applicationName: Key History Object
        applicationOID:  2.16.840.1.101.3.7.2.96.96
        Path:            6060
        Data (10 bytes): 5308C10100C20100FE00
Data object 'Cardholder Iris Image'
        applicationName: Cardholder Iris Image
        applicationOID:  2.16.840.1.101.3.7.2.16.21
        Path:            1015
Data object read failed: File not found

**C:\Program Files (x86)\OpenSC Project\OpenSC\tools>piv-tool -n**
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0
PIV-II card

### Proposed Resolution

Unknown

### Steps to reproduce

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>**piv-tool -A A:9B:03 -G 9A:07 -o pubkey.pem**

### Logs

Attached the default unsuccessful as well as a log for the successful 1024 0x06 key generation:

[opensc-debug.log](https://github.com/OpenSC/OpenSC/files/1895309/opensc-debug.log)
[opensc-debug_1024_0x06_successful.log](https://github.com/OpenSC/OpenSC/files/1895398/opensc-debug_1024_0x06_successful.log)

**Comment by forensicsguy817** [comment]
I just tried a 2048/0x07 gen on the other certificate slots, and they appear to work. For some reason, I'm having an issue with 9A or “X.509 Certificate for PIV Authentication”.

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>piv-tool -A A:9B:03 -G 9C:07 -o pubkey.pem
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>piv-tool -A A:9B:03 -G 9D:07 -o pubkey.pem
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>piv-tool -A A:9B:03 -G 9E:07 -o pubkey.pem
Using reader with a card: SCM Microsystems Inc. SCR33x USB Smart Card Reader 0

**Comment by dengert** [comment]
The NIST 800-73 versions and  NIST 800-78  versions specify the key references and alg id  and key sizes.
800-73-1 listed 1024(06), 2048(07) and 3072(05) and also listed 6 ECC curves. Only RSA 1024 was required.  800-73-2 listed RSA 1024 adn 2048 and only 2 ECC curves, and 800-78 was introduced. 

NIST SP 800-78-4 (May 2015) (Current version) (in "Table 6-2. Identifiers for Supported Cryptographic Algorithms" only lists 1024 and 2048. 

The PIV driver can support cards that might have 1024, 2048 or 3072.  

You card  [Gemalto IDPrime PIV Card 2.0](https://safenet.gemalto.com/multi-factor-authentication/idprime-piv-card/) says:
"ECC (256-, 384-bit), RSA (1024-, 2048-bit) using an **on-card security controller with key pair generation** and true random number generator. 

So the card does not support 3072, but it does say it supports 2048.
The debug log show:
00 47 00 9A 05 AC 03 80 01 07
which should work. for 2048. 

A few things could be going on here:
- Card does not follow NIST 800-73-x for generate key of size 2048
- Card looks to see if there is a certificate on the card  that matches this key. 
- Card expects extended length APDU for generate key. NIST 800-73 expects short APDU

So if you generated a 1024 byte key for 9A then loaded a certificate for ID=01. If you then tried to generate a different key, it might fail. Delete the certificate, then try the generate key again.

You appear to have the admin key from the vendor, if you have teh manuals for the card you may want to look at what other commands they have to load, generate or delete a key.

The piv-tool was written to help populate test cards. Key generation is normally only done by a Card Management System and the commands to populate the card may be different for different cards. 
I have not had problems in the past to generate 2048 RSA keys, although I don't have your card.

**Comment by forensicsguy817** [comment]
This card was provided to me as a PIV test card so I was thinking this tool would work. I did try the delete as mentioned on the Wiki page but had no success with subsequent 2048 key gen.

It accepts 2048 key gen on C, D, and E without error. I only seem to be having issues with A which is odd.

I'll try to contact the vendor and see what support I can get and if there are any manuals available. Thanks for the help. Is this better served for the mailing list? I couldn't find a list for support. I'll move it over if there's a better place.

**Comment by dengert** [comment]
Yes that is strange. 

https://www.idmanagement.gov/approved-products-list-piv/
Lists a number of IDPrime Approved cards. 

https://safenet.gemalto.com/multi-factor-authentication/idprime-piv-card/

https://safenet.gemalto.com/resources/data-protection/idprime-piv-smart-cards-product-brief/oval 
says:
"IDPrime PIV 2.1 card is based on a Java Card platform (TOP DL v2.1) with 144 KB EEPROM memory and the PIV 2.1 applet loaded on the Java Card platform"

So there may be some GP or Java platform requirenments too. 

And somewhere, I saw that they offer a CMS too. 

You may want to contact them.

**Comment by forensicsguy817** [comment]
Are there steps for configuring openssl to operate with the correct engine? 

I don't see SO_PATH:/usr/lib/engines/engine_pkcs11.so on my RHEL install and I also see that the engine_pkcs11.so was merged with libp11. I was attempting to perform the CSR step from the wiki but can't get the openssl modules to load. Do I need to build/install libp11?

**Comment by dengert** [comment]
Its complicated. First look at:
https://github.com/OpenSC/libp11/blob/master/README.md
You can use it with or with or without p11-kit. 

If need be I  suggest that you submit an issue at https://github.com/OpenSC/libp11
Include the OS, and versions of OpenSSL and libp11 you have. 

@mouse07410  You use this a lot, maybe you can help with using OpenSC with OpenSSL engine.

**Comment by mouse07410** [comment]
@dengert unfortunately, I never tried to actually *generate* keys on the token using OpenSSL+libp11. CAC comes with its keys already installed, and for Yubikey I used `yubico-piv-tool`. I've a couple of unprovisioned Yubikeys, could try with them...

@forensicsguy817 am I correct that it's just one slot on the token that fails to generate what you need, and you can generate keys for the other slots as you need? If so, it definitely sounds like the card/vendor problem to me (`pkcs11-tool` cannot care what slot it is that it passes commands to). @dengert you concur?

**Comment by dengert** [comment]
As I said, `00 47 00 9A 05 AC 03 80 01 07` should work. I also said NIST left up to card vendors how to provision their cards. This is a new  card that says it supports 800-73-4, and the vendor may require additional authentication or use of SM that is optional in 800-73-4 to generate the 9A key. It could also require some GP of Java platform commands as well.  

Only the vendor's documentation would define how to do it, and the vendor may only release that  documentation under a NDA. They are in the business of selling cards and card management system with improved security including during provisioning. Their web page says:
"Gemalto’s IDPrime PIV (Personal Identity Verification) Card is a FIPS 201 standards-based card for government agencies, state and local government organizations to issue users credentials that the federal government can trust."
