### ISSUE TITLE
Regression: current master fails to verify PIN on CAC/PIV (MacOS)

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1328]
### Problem Description

OpenSC lost the ability to login to (some) PIV tokens. The problem appears to be somewhere in the libopensc. This problem manifests itself only with `transaction_end_action = reset;`.

The current code works for Yubikey, but fails for CAC.

### Proposed Resolution

Don't know yet, exploring.

### Steps to reproduce

1. Insert CAC or PIV card
2. Do `pkcs11-tool --module /Library/OpenSC/lib/pkcs11-spy.dylib -l -O`
3. Being prompted for the PIN, enter it
4. Observe `CKR_DATA_INVALID` response

Or, do `opensc-tool -s "00 20 00 80 08 3x 3x 3x 3x 3x 3x 3x FF`  (surprisingly, `opensc-tool -s "00 20 00 00 08 3x 3x 3x 3x 3x 3x 3x FF` appears to work correctly).

### Logs

```
$ $ pkcs11-tool --module /Library/OpenSC/lib/pkcs11-spy.dylib -l -O


*************** OpenSC PKCS#11 spy *****************
Loaded: "/Library/OpenSC/lib/opensc-pkcs11.dylib"

0: C_GetFunctionList
2018-04-13 13:50:58.222
Returned:  0 CKR_OK
. . . . .
6: C_GetTokenInfo
2018-04-13 13:51:00.647
[in] slotID = 0x0
[out] pInfo: 
      label:                  'PIV_II                          '
      manufacturerID:         'piv_II                          '
      model:                  'PKCS#15 emulated'
      serialNumber:           '00000000        '
      ulMaxSessionCount:       0
      ulSessionCount:          0
      ulMaxRwSessionCount:     0
      ulRwSessionCount:        0
      ulMaxPinLen:             8
      ulMinPinLen:             4
      ulTotalPublicMemory:     -1
      ulFreePublicMemory:      -1
      ulTotalPrivateMemory:    -1
      ulFreePrivateMemory:     -1
      hardwareVersion:         0.0
      firmwareVersion:         0.0
      time:                   '                '
      flags:                   40d
        CKF_RNG                          
        CKF_LOGIN_REQUIRED               
        CKF_USER_PIN_INITIALIZED         
        CKF_TOKEN_INITIALIZED            
Returned:  0 CKR_OK
Logging in to "PIV_II".
Please enter User PIN: 

7: C_Login
2018-04-13 13:51:07.746
[in] hSession = 0x7fabd7d0aa60
[in] userType = CKU_USER
[in] pPin[ulPinLen] 00007fabd7e15de0 / 7
    00000000  3x 3x 3x 3x 3x 3x 3x                             xxxxxxx         
Returned:  32 CKR_DATA_INVALID
```

Here's the `/tmp/opensc-debug.log`:
```
. . . . .
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] reader-pcsc.c:485:pcsc_reconnect: SCR3310 Smart Card Reader:SCardReconnect returned: 0x00000000
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] reader-pcsc.c:612:pcsc_lock: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card-piv.c:3576:piv_card_reader_lock_obtained: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card-piv.c:3622:piv_card_reader_lock_obtained: returning with: 0 (Success)
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card.c:443:sc_lock: returning with: 0 (Success)
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] sec.c:170:sc_pin_cmd: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card-piv.c:3436:piv_pin_cmd: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card-piv.c:3437:piv_pin_cmd: piv_pin_cmd tries_left=-1, logged_in=-1
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] apdu.c:554:sc_transmit_apdu: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card.c:403:sc_lock: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] card.c:443:sc_lock: returning with: 0 (Success)
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] apdu.c:521:sc_transmit: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] apdu.c:371:sc_single_transmit: called
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] apdu.c:378:sc_single_transmit: CLA:0, INS:20, P1:0, P2:80, data(8) 0x7fff5e456850
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] reader-pcsc.c:283:pcsc_transmit: reader 'SCR3310 Smart Card Reader'
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit:
Outgoing APDU (13 bytes):
00 20 00 80 08 3x 3x 3x 3x 3x 3x 3x FF . ...xxxxxxx.
0x7fff96a1d3c0 14:01:55.875 [opensc-pkcs11] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] reader-pcsc.c:293:pcsc_transmit:
Incoming APDU (2 bytes):
6A 86 j.
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] apdu.c:543:sc_transmit: returning with: 0 (Success)
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] card.c:453:sc_unlock: called
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] iso7816.c:124:iso7816_check_sw: Incorrect parameters P1-P2
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] card-piv.c:3540:piv_pin_cmd: piv_pin_cmd tries_left=-1, logged_in=0
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] card-piv.c:3541:piv_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] sec.c:217:sc_pin_cmd: returning with: -1205 (Incorrect parameters in APDU)
0x7fff96a1d3c0 14:01:56.519 [opensc-pkcs11] pkcs15-pin.c:449:sc_pkcs15_verify_pin_with_session_pin: PIN cmd result -1205
. . . . .
```

Without `transcation_end_action = reset;` (having the default ` = leave;`) results in the same PIN being verified correctly:
```
$ OPENSC_DEBUG=9 pkcs11-tool --module /Library/OpenSC/lib/pkcs11-spy.dylib -l -O


*************** OpenSC PKCS#11 spy *****************
Loaded: "/Library/OpenSC/lib/opensc-pkcs11.dylib"

0: C_GetFunctionList
2018-04-13 14:12:07.644
Returned:  0 CKR_OK

1: C_Initialize
2018-04-13 14:12:07.645
[in] pInitArgs = 0x0
0x7fff96a1d3c0 14:12:07.647 [opensc-pkcs11] ctx.c:703:process_config_file: Used configuration file '/Library/OpenSC/etc/opensc.conf'
Returned:  0 CKR_OK
. . . . .
Please enter User PIN: 

7: C_Login
2018-04-13 14:12:14.166
[in] hSession = 0x7facca7004b0
[in] userType = CKU_USER
[in] pPin[ulPinLen] 00007facca500ea0 / 7
    00000000  x         
Returned:  0 CKR_OK

8: C_FindObjectsInit
2018-04-13 14:12:14.209
[in] hSession = 0x7facca7004b0
[in] pTemplate[0]: 
Returned:  0 CKR_OK

9: C_FindObjects
2018-04-13 14:12:14.209
[in] hSession = 0x7facca7004b0
[in] ulMaxObjectCount = 0x1
[out] ulObjectCount = 0x1
Object 0x7facca404250 matches
Returned:  0 CKR_OK
. . . . .
244: C_FindObjectsFinal
2018-04-13 14:12:14.222
[in] hSession = 0x7facca7004b0
Returned:  0 CKR_OK

245: C_CloseSession
2018-04-13 14:12:14.222
[in] hSession = 0x7facca7004b0
Returned:  0 CKR_OK

246: C_Finalize
2018-04-13 14:12:14.222
Returned:  0 CKR_OK
```

**Comment by frankmorgner** [comment]
If you reset an applet-based card, it looses its authentication status. My guess is that the transactions are not as broad as you'd like to have them, for example, spanning only a single call to C_Login. After that call, the card is reset and looses its ability to sign something.

In https://github.com/OpenSC/OpenSC/issues/1305 you wrote that you need this setting for the macOS screen saver, i.e. for tokend. Please try to move this setting into the tokend section or to use two different configuration files, one for tokend (with `transaction_end_action` configured as above) and an other one for PKCS#11 (leaving `transaction_end_action` at its default value).

**Comment by frankmorgner** [comment]
I just noticed that the PIN verification doesn't work... The problem I've described above also holds when PIV is not the default selected applet, which means that the VERIFY doesn't go to the PIV applet, which is why it is failing. Please try the suggestions above to fix it.

**Comment by dengert** [comment]
As Frank said, transaction_end_action is not going to work try without it. 


Need more info:
Is this a PIV only card?
Is it a PIV+CAC card?
Does you card use the global or piv pin? 
-s "00 20 00 80 08 3x 3x 3x 3x 3x 3x 3x FF (surprisingly, opensc-tool -s "00 20 00 00 08 3x 3x 3x 3x 3x 3x 3x FF appears to work correctly).

Please post the full debug log. as the code is designed to do read the Discovry object to test for active AID then do a SELECT AID for PIV if needed.  So would not suspect Discovery object would set Global pin and the card would not accept it. 


card-piv.c has:
```
2175 /*
2176  * NIST 800-73-3 allows the default pin to be the PIV application 0x80
2177  * or the global pin for the card 0x00. Look at Discovery object to get this.
2178  * called by pkcs15-piv.c  via cardctl when setting up the pins.
2179  */
```
You said:  opensc-tool  -s "00 20 00 **80** 08 3x 3x 3x 3x 3x 3x 3x FF"
 (surprisingly, opensc-tool -s "00 20 00 **00** 08 3x 3x 3x 3x 3x 3x 3x FF appears to work correctly).
i.e. PIV fails, Global works. 

Look at card-piv.c:
The discovery object sets the pin reference.
```
2638                                         if (*pinp == 0x60 && *(pinp+1) == 0x20) { /* use Global pin */
2639                                                 sc_log(card->ctx, "Pin Preference - Global");
2640                                                 priv->pin_preference = 0x00;
```








What we need to see is what happens after the reset. All the recent cards to PIV are designed to make sure the PIV applet is selected, by testing for  Discovery object  with 7E then doing a select AID.

What other processes are running. they are also notified of the card reset, as is any other driver loaded by p11kit.

**Comment by dengert** [comment]
Can you test against 0.18.0-rc1 without any local changes.

**Comment by mouse07410** [comment]
> you wrote that you need this setting for the macOS screen saver, i.e. for tokend.

Unfortunately, yes. I'd love to find another way to accomplish that goal, but so far whatever else I tried, failed.

> Please try to move this setting into the tokend section

Tried this in `OpenSCToken.cpp`:
```
void OpenSCToken::unverifyPIN(int pinNum)
{
        sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, "In OpenSCToken::unverifyPIN(%d)\n", pinNum);

        mCurrentPIN = pinNum;
        mLocked = true;

        /* Does not seem to work as I'd like */
        int rv = SC_SUCCESS;
        sc_pkcs15_pincache_clear(mScP15Card);
        rv = sc_logout(mScCard);
        if (rv != SC_SUCCESS) {
                sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, "sc_logout() returned %d (not SC_SUCCESS)", rv);
                // Somehow doing sc_reset() here makes the token unusable until re-inserted
                rv = sc_reset(mScCard, 1); // 0 = warm reset, 1 = cold reset (unpower)
                if (rv != SC_SUCCESS)
                        sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL,
                                "In OpenSCToken::unverifyPIN(%d) sc_reset returned %d (not SC_SUCCESS)\n",
                                pinNum, rv);
        }
}
```
and this in `opensc.conf`:
```
# Used by OpenSC.tokend on Mac OS X only
app tokend {
        # The file to which debug log will be written
        # Default: /tmp/opensc-tokend.log
        #
        # debug_file = /Library/Logs/OpenSC.tokend.log
                #
        # What to do at the end of a transaction (SCardEndTransaction)
        # Valid values: leave, reset, unpower.
        # Default: leave
        transaction_end_action = reset;

        framework tokend {
                # Score for OpenSC.tokend
                # The tokend with the highest score shall be used.
                # Default: 300
                #
                score = 1000;
                # Tokend ignore to read PIN protected certificate that is set SC_PKCS15_CO_FLAG_PRIVATE flag.
                # Default: true
                #
                # ignore_private_certificate = false;
                #
                # What to do at the end of a transaction (SCardEndTransaction)
                # Valid values: leave, reset, unpower.
                # Default: leave
                transaction_end_action = reset;
        }
}
```


> As Frank said, `transaction_end_action` is not going to work try without it

Without it everything works - **except** for locking the screen. Which would prevent us from using Nano tokens. With it - Nano works as we'd like, but other important things don't.

> Please post the full debug log.

Sure. Some of the following are with Yubikey NEO, some - with Yubikey 4.

Here's the log with `transaction_end_action` in the `driver_pcsc` section of `opensc.conf`: 
[opensc-screenlock1.txt](https://github.com/OpenSC/OpenSC/files/1909936/opensc-screenlock1.txt)
First attempt to unlock the screen works fine (prompted for the PIN, PIN accepted, A.O.K.). Subsequent attempts prompt only for "OK" (no offer to enter PIN), but clicking OK does not unlock. There's no way to unlock the screen until the token is removed and re-inserted - at which point the PIN is prompted for and accepted. `OpenSCToken::unverifyPIN()` is as shown above.

Here's the log with `transaction_end_action` moved into the `tokend` section (`OpenSCToken::unverifyPIN()` is as shown above): 
[opensc-screenlock2.txt](https://github.com/OpenSC/OpenSC/files/1909944/opensc-screenlock2.txt)

Here's the log with `transaction_end_action` commented out. In this case, Keychain Access unlocks the token fine (the first set of logged transactions), the first screen unlock succeeds - but then it gives the "OK" popup instead of a PIN prompt, and refuses to unlock when clicked. Even when I remove and re-insert the token, it doesn't unlock the screen (I had to unlock it with a password).
[opensc-screenlock3.txt](https://github.com/OpenSC/OpenSC/files/1909953/opensc-screenlock3.txt)

> Is this a PIV only card? Is it a PIV+CAC card?

Yubikey (NEO and 4) are PIV cards (somewhat compliant ;). CAC is a PIV+CAC.

> Does you card use the global or piv pin?

To the best of my knowledge - PIV PIN.

**Comment by frankmorgner** [comment]
`opensc.conf` should look something like this:
```
app tokend {
	reader_driver pcsc {
		transaction_end_action = reset;
	}
}
```
If it still doesn't work, check if the configuration is honored in `reader-pcsc.c` and try to find out what workflow is actually going on when the screensaver locks the computer.

**Comment by mouse07410** [comment]
@frankmorgner thank you - your suggested fix appears to work. It still breaks Keychain Access, but most likely I'd be able to live with it.

Need to test with a real CAC to be sure. Will test and report.

**Comment by mouse07410** [comment]
Tests with CAC were more problematic. First, it used to recognize the CAC as PIV-II. Now it doesn't. `pkcs11-tool -l --test` sometimes fails at the login, more often it passes OK:
```
$ OPENSC_DEBUG=9 opensc-tool -lian
OpenSC 0.18.0 [gcc  4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Enabled features: locking zlib readline openssl pcsc(/System/Library/Frameworks/PCSC.framework/PCSC)
0x7fffcafbe3c0 10:26:27.193 [opensc-tool] ctx.c:703:process_config_file: Used configuration file '/Library/OpenSC/etc/opensc.conf'
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             SCR3310 Smart Card Reader
Using reader with a card: SCR3310 Smart Card Reader
3b:7a:18:00:00:73:66:74:65:20:63:64:31:34:34
Common Access Card (CAC)
$ OPENSC_DEBUG=9 pkcs11-tool -l --test
0x7fffcafbe3c0 10:26:36.040 [opensc-pkcs11] ctx.c:703:process_config_file: Used configuration file '/Library/OpenSC/etc/opensc.conf'
Using slot 0 with a present token (0x0)
Logging in to "<my_name>".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CAC ID Certificate) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (2048 bits, label=CAC Email Signature Certificate) with 1 signature mechanism
    RSA-X-509: OK
  testing key 2 (2048 bits, label=CAC Email Encryption Certificate) with 1 signature mechanism -- can't be used to sign/verify, skipping
  testing key 3 (2048 bits, label=CAC Cert 3) with 1 signature mechanism
    RSA-X-509: OK
Verify (currently only for RSA)
  testing key 0 (CAC ID Certificate)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
  testing key 1 (CAC Email Signature Certificate) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (CAC Email Encryption Certificate) with 1 mechanism -- can't be used to sign/verify, skipping
  testing key 3 (CAC Cert 3) with 1 mechanism
    RSA-X-509: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (CAC ID Certificate)  -- can't be used to decrypt, skipping
  testing key 1 (CAC Email Signature Certificate)  -- can't be used to decrypt, skipping
  testing key 2 (CAC Email Encryption Certificate) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 3 (CAC Cert 3)  -- can't be used to decrypt, skipping
No errors
$ 
```
and the log: 
[opensc-lock-cac1.txt](https://github.com/OpenSC/OpenSC/files/1920266/opensc-lock-cac1.txt)

Safari and Keychain Access, however, do not even see the certificates on the token, let alone allow me to use them. Scenario:
1. Inserted the CAC.
2. Started Keychain Access to view the token. Token appears as a keychain, but no certs/keys are visible. Attempted to unlock, clicked on the "Lock" icon, prompted for the PIN, entered it, nothing changed (and the token was not unlocked). Token stays in the reader.
3. In Safari attempt to access CAC-protected Web site. CAC certificates are not offered.

Here's the log for the above: 
[opensc-lock-cac2.txt](https://github.com/OpenSC/OpenSC/files/1920332/opensc-lock-cac2.txt)

**Comment by mouse07410** [comment]
> I can have a fix later today.

Yes please!!!

> But also note the the VERIFY PIN command is done its its own transaction, which `disconnect=reset` will cause the login state to be lost. Cached pin can recover from this. So it must be on.

I see. I guess it's not too bad.

**Comment by dengert** [comment]
I have pushed  https://github.com/OpenSC/OpenSC/pull/1334/commits/5f4cd435fd35ccc2056311bd9bf3127c50f43c15 on to #1334 

This should fix the problem with disconnect=reset and the CAC/PIV card.  The login state is still lost but it should respond better. It may need pin caching on so it can recover from the lost login state caused by the reset.

**Comment by mouse07410** [comment]
I've applied #1334. Will try with CAC tomorrow - but even with YubiKey I cannot get Keychain Access to unlock the token (`pkcs11-tool` has no problem). `disconnect=leave`, and PIN caching is enabled. Here's the log: 
[opensc-lock-cac4.txt](https://github.com/OpenSC/OpenSC/files/1921778/opensc-lock-cac4.txt)

The first time I start Keychain Access, when I request unlocking of the token I'm prompted for the PIN - but it does not unlock. Subsequent requests to unlock the token result in nothing, not even the PIN prompt...

**Comment by mouse07410** [comment]
> You have `disconnect=reset`, so after every transaction the card is reset. This causes the default AID to be reset too.

Probably `transaction_end_action=reset;` would cause the same effect, aka resetting the default AID? Is it necessary? 

I'm trying to figure if there's a way to sorta "have the wolves fed and sheep intact", paraphrasing an old saying... I'd like to be always prompted for the PIN - like I am when `transaction_end_action=reset;` is set, but at the same time I'd like Keychain Access and Safari to be able to work (aka be able to unlock and perform operations) with tokens. I really hope it is possible.

**Comment by dengert** [comment]
Yes, `transaction_end_action=reset`. In the above comments, I should have said `transaction_end_action` and not `disconnect`.  The opensc-lock-cac4.txt shows on line 3: `connect_exclusive=0 disconnect_action=0 transaction_end_action=1 reconnect_action=0 enable_pinpad=1 enable_pace=1`

There were 21 lines like:
`0x7fffa9f86380 18:09:59.541 [tokend] reader-pcsc.c:463:pcsc_reconnect: Reconnecting to the card...`
indicating the card was reset 21 times. In order to allow multiple applications, each application needs to keep its transactions short, so other applications don't end up waiting for long time. They do this by grouping several related APDUs in one transaction. A `C_Login` would  have a VERIFY PIN in one transaction, because it does not know when the next command will come from its application. The  `transaction_end_action=reset` clears the login state when the verify is done. 

I don't think you can "have your cake and eat it too". The card has only one login state. If any application resets the card, the login state is lost. Every application using the card gets notified  of a reset when it tries to start the next transaction.  Each application can then take action to get back to a state it wants.

**Comment by mouse07410** [comment]
> I don't think you can "have your cake and eat it too". The card has only one login state.

In that case I need to find a way to somehow emulate card removal and re-insertion, that would be "convincing" to tokend. 

I know I can easily kill tokend process - but it will not restart unless I re-insert the card, and I've no idea what the parameters are that passed to the tokend at invocation. Here's what the process looks like:
```
_tokend          80810   0.0  0.0  2528432   4692   ??  S    12:43PM   0:00.08 /Library/Security/tokend/OpenSC.tokend/Contents/MacOS/OpenSC 5 Yubico Yubikey 4 OTP+U2F+CCID 40355917d57f0000f00c5917d57f00000000000022000000120000003bf81300008131fe15597562696b657934d4000000000000000000000000000000
```

**Comment by mouse07410** [comment]
@frankmorgner @dengert in https://github.com/mouse07410/OpenSC.tokend/blob/e9151522984ce1011185ff42c7b70d9600bd79d0/OpenSC/OpenSCToken.cpp#L358-L381 after `sc_reset()`, is it possible to immediately re-select PIV AID? If so - how do to it, ideally with one function call? Could you show such a call, please?

Thanks!

**Comment by frankmorgner** [comment]
In `sc_lock()` we're checking whether the card was reset and we're calling `card->ops->card_reader_lock_obtained()` accordingly. When performing the reset within OpenSC, this may be a corner case that we didn't look at previously. You may try the following patch:
```diff
diff --git a/src/libopensc/card.c b/src/libopensc/card.c
index 724e73b8..db44b00a 100644
--- a/src/libopensc/card.c
+++ b/src/libopensc/card.c
@@ -379,6 +379,9 @@ int sc_reset(sc_card_t *card, int do_cold_reset)
 
        r = card->reader->ops->reset(card->reader, do_cold_reset);
        sc_invalidate_cache(card);
+       if (r == SC_SUCCESS) {
+               r = card->ops->card_reader_lock_obtained(card, 1);
+       }
 
        r2 = sc_mutex_unlock(card->ctx, card->mutex);
        if (r2 != SC_SUCCESS) {
```

**Comment by frankmorgner** [comment]
... this will re-select the applet!

**Comment by mouse07410** [comment]
@frankmorgner thank you, trying it now.

In the meanwhile, could you show how an app would call `sc_reset()`? The absolutely smallest example? That does not do anything else but performs `sc_reset()` on the token?

**Comment by mouse07410** [comment]
That patch seemed to work!

I did *not* define `transaction_end_action=reset;`, either for the whole OpenSC, or for the tokend alone. Before starting the screensaver, I performed `opensc-tool --reset`. And every time screensaver was prompting me for the PIN!

But it uncovered a problem: before employing `opensc-tool --reset`, OpenSC kept track of all the connected smartcard readers - with tokens inserted, and without. Now, after `opensc-tool --reset` it lost the SCR 3310 reader (that did not have a card in it when reset was done).

How can I "wake up" this reader, if just inserting the card does not accomplish that? Is there a way to do so programmatically (I really hope so)?

**Comment by dengert** [comment]
Most drivers do not have a  `card->ops->card_reader_lock_obtained`.  8 drivers do. So you need to check for `card->ops->card_reader_lock_obtained == NULL`

I would also expect at the next sc_lock call  that calls pcsc_lock, will cause 
 `card->ops->card_reader_lock_obtained(card, 1);`  to be called because there was a card reset. 
(Not clear if the driver that did the reset also  gets notified that the card was reset. I suspect it does. )
A opensc-debug.log would show what really happens.

**Comment by mouse07410** [comment]
This seems to be working fine. With these changes `opensc-tool --reset warm` does exactly what I need. So `transaction_end_action=reset;` doesn't have to be set, so CAC is back in business. ;-)

Thanks!

P.S. Now - to figure how to get screensaver start notification while not running under the user account (so the user doesn't just kill this process ;).

**Comment by mouse07410** [comment]
In general, the regression seems to have been taken care of, and the screensaver unlock works as expected if `opensc-tool --reset warm` (or its analog) is done after locking. So let me close this, and re-open if needed.
