### ISSUE TITLE
Expression is always false

### ISSUE THREAD

**Issue by AppChecker** [OpenSC/OpenSC#1330]
Hi!
Please take a look at [this expression:](https://github.com/OpenSC/OpenSC/blob/b4bc6de81bb70101eed716a67b893e5a90c3ac29/src/libopensc/card-piv.c#L2875)

`(*keyref < 0x82 && *keyref > 0x95)`
it is always false.
Probably  it should be:
`(*keyref < 0x82 || *keyref > 0x95)`

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by frankmorgner** [comment]
@dengert ?

**Comment by dengert** [comment]
Yes its an error. It is trying to catch an invalid key ref in the history object. An invalid key ref would be caught by the card later.  History objects rarely used and would have to be malformed.   Its a minor error, that could wait till after 0.18.0
