### ISSUE TITLE
Please use addnotated tags to make 'git describe' work correctly

### ISSUE THREAD

**Issue by marschap** [OpenSC/OpenSC#1355]
### Problem Description
Calling
  $ git describe
in OpenSC's HEAD yields
  0.16.0-554-g99eed0aa
which in my opinion is not what it should show, as 0.16.0 is not the latest version.
In my opinion it should either show something like
  0.18.0-rc2-xx-yyyyyyyy
or - less preferred - something like
  0.17.0-xx-yyyyyyyy

### Proposed Resolution
Using annotated tags should solve the issue.

The script  annotate_tags.sh  at
  https://gist.github.com/ATenderholt/6ea241e0b68ab03518a3
should help converting 
I do not know whether converting lightweight tags to annotated tags may break things.
My - admittedly very limited - tests did not hint at any big breakage, but YMMV.

Extending the script to give fixed desciption names, might not be unwise:
.. .git tag .... -m "OpenSC $tag"

### Steps to reproduce
1) Run 'git describe' at HEAD
2) Calll 'annotate_tags.sh 0.17.0'
3) Run 'git describe'  at HEAD
Compare outputs of 1) and 3)

**Comment by frankmorgner** [comment]
done
