### ISSUE TITLE
C_CreateObject fails with Bad Arguments

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1357]
I have a C_CreateObject PKCS#11 API call to generate a 128 bit AES-key that fails with bad arguments.

Can anyone please help me figuring out what is wrong with the template ?

                            CK_OBJECT_HANDLE hKey;
                            CK_OBJECT_CLASS keyClass = CKO_SECRET_KEY;
                            CK_KEY_TYPE keyType = CKK_AES;
                            CK_BBOOL _true = TRUE;
                            CK_BBOOL _false = FALSE;                              
                            CK_BYTE key_value[] = { 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef};

                            CK_ATTRIBUTE keyTemplate[] = {
                               {CKA_CLASS, &keyClass, sizeof(keyClass)},
                               {CKA_KEY_TYPE, &keyType, sizeof(keyType)},
                               {CKA_ENCRYPT, &_true, sizeof(_true)},
                               {CKA_DECRYPT, &_true, sizeof(_true)},
                               {CKA_TOKEN, &_true, sizeof(_true)},      /* token object  */
                               {CKA_PRIVATE, &_false, sizeof(_false)},  /* public object */
                               {CKA_VALUE, key_value, sizeof(key_value)},
                               {CKA_LABEL, CK_VOID_PTR("key"), sizeof("key")}
                             };

                             rv =  pfunc11->C_CreateObject(session, keyTemplate, sizeof (keyTemplate)/sizeof (CK_ATTRIBUTE), &hKey);
                             if (rv != CKR_OK) {
                                printf("ERROR: rv=0x%08X: C_CreateObject:\n", (unsigned int)rv);
                                return false;
                             }

**Comment by frankmorgner** [comment]
Please create a debug log of your problem as described in the [comments of our issue template](https://raw.githubusercontent.com/OpenSC/OpenSC/master/.github/ISSUE_TEMPLATE.md)

**Comment by CardContact** [comment]
key_value is too short...

**Comment by RohanKurane** [comment]
Thanks. Yes it was the key length issue. I mad it 16bytes and it works now.
