### ISSUE TITLE
PKCS#11 C_Encrypt fails with Bad Arguments for 128 bit AES key

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1358]
I generate a 128-bit AES object using "C_CreateObject". I then do the following to encrypt a piece of clear text data and get a "Bad Arguments" error on the call to "C_Encrypt" to get the encrypted data length. C_EncryptInit is successful for the session handle and object handle. 

           char clear[] = "My name is Rohan!";
           buf_len = sizeof(clear) -1;

           rv = pfunc11->C_EncryptInit(session, pMechanism, hObject);
           if (rv != CKR_OK)    
          {
               printf("ERROR: rv=0x%08X: initializing encryption:\n", (unsigned int)rv);
                return false;
           }

           rv = pfunc11->C_Encrypt(session, (CK_BYTE_PTR)clear, (CK_ULONG)buf_len, NULL, pulEncryptedDataLen);
            if (rv != CKR_OK) 
            {                                   
                  printf("ERROR: rv=0x%08X: derror getting encryption data buffer length:\n", (unsigned int)rv);
                  return false;
            }

And here is my mechanism definition -

 CK_MECHANISM myMechanism = {CKM_AES_CBC_PAD,     (CK_VOID_PTR)"01020304050607081122334455667788", (CK_ULONG)16};

 CK_MECHANISM_PTR pMechanism = &myMechanism;

Clearly the length of the clear text is not the issue here according to this article - cryptsoft.com/pkcs11doc/v211/… .. The mechanism CKM_AES_CBC_PAD allows for any input length and will round it up to next block size. 

What could be the bad argument here ?

@CardContact 
@frankmorgner

**Comment by dengert** [comment]
Are you using the OpenSC PKCS\#11 module? 
It does not look like you are. 
If you are get an opensc-debug.log.

**Comment by RohanKurane** [comment]
@dengert  No. I am using AWS CloudHSM PKCS#11 module in my application.

**Comment by dengert** [comment]
Then you should be asking them why their C_Encrypt is returning "Bad Arguments"

You could also estimate the size of the buffer "input length rounded up to multiple of the block size" and just do the real C_Encrypt and see if the problem is estimating the size of the output. 

Also look at the the attributes of the key.  Is CKA_ENCRYPT == True?

OpenSC PKCS\#11 module does not  support the mechanism you are trying to use. 

The OpenSC pkcs11-tool can be used with other PKCS\#11 modules in some cases. 
For example to list the mechanisms supported by the module. 

OpenSC SPY can be used with other modules to trace PKCS\#11 calls and responses.

**Comment by RohanKurane** [comment]
@dengert 
Here is the key template used to create the key
 
  CK_ATTRIBUTE keyTemplate[] = {
       {CKA_CLASS, &keyClass, sizeof(keyClass)},
       {CKA_KEY_TYPE, &keyType, sizeof(keyType)},
       {CKA_ENCRYPT, &_true, sizeof(_true)},
       {CKA_DECRYPT, &_true, sizeof(_true)},
       {CKA_TOKEN, &_true, sizeof(_true)},      /* token object  */
       {CKA_PRIVATE, &_false, sizeof(_false)},  /* public object */
       {CKA_VALUE, key_value, sizeof(key_value)},
       {CKA_LABEL, label, sizeof(label)-1}
  };

As you see, CKA_ENCRYPT is true. 

AWS CloudHSM supports the CKM_AES_CBC_PAD mechanism. 

I printed the info for it,
AES-CBC-PAD, keySize={16,32}, encrypt, decrypt, other flags=0x1

And the key I generate is a 16byte (128-byte) AES key. 

  CK_OBJECT_HANDLE hKey;
  CK_OBJECT_CLASS keyClass = CKO_SECRET_KEY;
  CK_KEY_TYPE keyType = CKK_AES;
  CK_BBOOL _true = TRUE;
  CK_BBOOL _false = FALSE;
  CK_BYTE key_value[] = {0x01,0x23,0x45,0x67,0x89,0xab,0xcd,0xef,
                         0xCA,0xFE,0xBE,0xEF,0xCA,0xFE,0xBE,0xEF};

rv =  pfunc11->C_CreateObject(session, keyTemplate, sizeof (keyTemplate)/sizeof (CK_ATTRIBUTE), &hKey);

I have asked the AWS CloudHSM support team but they have been really slow in responding. I was hoping someone here could point out a code flaw and direct me in the right direction.

**Comment by RohanKurane** [comment]
@dengert 

Good one....

I did that and can encrypt the data..So looks like the error is for the call to C_Encrypt to determine the encrypted data length. 

Here is my code now (I have a few hardcoded lengths. What do you think of those ?) 

                                     char clear[200] = "My name is Rohan"; 

                                     CK_ULONG plEncryptedDataLen = 256;
                                     CK_BYTE_PTR pEncryptedData = (CK_BYTE *)malloc(256);

                                     rv =pfunc11->C_Encrypt(session, (CK_BYTE_PTR)clear, 200, pEncryptedData, &plEncryptedDataLen);
                                     if (rv != CKR_OK) {
                                         printf("ERROR: rv=0x%08X: during encryption:\n", (unsigned int)rv);
                                         return false;
                                     }
                                     
                                     printf("Encrypted data successfully ");

**Comment by RohanKurane** [comment]
@dengert 

Thanks ! 

Another question unrelated to this if you dont mind -  :)

I am trying to list all SECRET_KEY class objects and print their Labels. I run into an error for the buffer being too small on the 2nd call to C_GetAttributeValue. Here is my code - 

        rv = pfunc11->C_GetAttributeValue(hsession, object, dataTemplate, 1);
        if(rv != CKR_OK)
        {
           printf("ERROR: rv=0x%08X: C_GetAttributeValue failed to get length\n", (unsigned int)rv);
           break;
        }
        else
        {
           printf("Length of key is %lu\n", dataTemplate[0].ulValueLen);
        }
        dataTemplate[0].pValue = (CK_BYTE_PTR)malloc(dataTemplate[0].ulValueLen);

        rv = pfunc11->C_GetAttributeValue(hsession, object, dataTemplate, 1);
        if(rv != CKR_OK)
        {
            printf("ERROR: rv=0x%08X: C_GetAttributeValue failed to get value\n", (unsigned int)rv);
        }

The length of each label is 13 and is correctly displayed in "dataTemplate[0].ulValueLen"

I then malloc the same amount of memory for dataTemplate[0].pValue and and then call C_GetAttributeValue but get the buffer too small error.  The call to malloc is successful. 

My dataTemplate is : 
  CK_ATTRIBUTE dataTemplate[] = {
        {CKA_LABEL, NULL_PTR, 0}
  };

Any idea ? 

Error is:
C_GetAttributeValue failed with error CKR_BUFFER_TOO_SMALL : 0x00000150

**Comment by frankmorgner** [comment]
Please use your PKCS#11 module's support.
