### ISSUE TITLE
Recent change in NPA driver wrongly matches Portuguese eID Card

### ISSUE THREAD

**Issue by agrr** [OpenSC/OpenSC#1360]
### Problem Description

I think the following change in npa_match_card() breaked driver matching for PT card and possibly others:
OpenSC/OpenSC@90a5b262d0e4d7206d071e469cb656f771e209c6
Probably the new check for EF_CARDACCESS file is at fault here, the response '6D 00' should be treated as error.

### Logs
Here's the relevant log from opensc-explorer -vvv

```
0x7ff13de71880 11:50:09.313 [opensc-explorer] reader-pcsc.c:283:pcsc_transmit: reader 'Gemalto PC Twin Reader (1804CEBE) 00 00'
0x7ff13de71880 11:50:09.313 [opensc-explorer] reader-pcsc.c:284:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 B0 9C 00 DF .....
0x7ff13de71880 11:50:09.313 [opensc-explorer] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7ff13de71880 11:50:09.352 [opensc-explorer] reader-pcsc.c:293:pcsc_transmit: 
Incoming APDU (2 bytes):
6D 00 m.
0x7ff13de71880 11:50:09.352 [opensc-explorer] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
0x7ff13de71880 11:50:09.352 [opensc-explorer] apdu.c:543:sc_transmit: returning with: 0 (Success)
0x7ff13de71880 11:50:09.352 [opensc-explorer] card.c:451:sc_unlock: called
0x7ff13de71880 11:50:09.352 [opensc-explorer] reader-pcsc.c:662:pcsc_unlock: called
0x7ff13de71880 11:50:09.361 [opensc-explorer] card.c:283:sc_connect_card: matched: German ID card (neuer Personalausweis, nPA)

```

**Comment by agrr** [comment]
Yes, applying that change it correctly matches the GemsafeV1 driver.

**Comment by frankmorgner** [comment]
I'm puzzled, the gemsafe driver [should match earlier](https://github.com/OpenSC/OpenSC/blob/5abe99d228e73a3e2a0786c7029917ca502ca3e8/src/libopensc/ctx.c#L123) than the npa driver. So an error in npa should not affect your card... Could you post the whole log?

**Comment by agrr** [comment]
Here's the opensc-explorer log after applying #1362 
[opensc-explorer.log](https://github.com/OpenSC/OpenSC/files/2016511/opensc-explorer.log)
