### ISSUE TITLE
outdated information in {egk,npa}-tool* & opensc-{asn1,notify}*

### ISSUE THREAD

**Issue by marschap** [OpenSC/OpenSC#1365]
### Problem Description

The files
  src/tools/egk-tool.1
  src/tools/npa-tool.1
  src/tools/opensc-asn1.1
  src/tools/opensc-notify.1
contain outdated version information: 0.16.0 resp. 0.17.0; this should be 0.18.0
In addition, the files
  src/tools/npa-tool-cmdline.c
  src/tools/opensc-asn1-cmdline.c
  src/tools/egk-tool.1
  src/tools/opensc-notify-cmdline.c
  src/tools/npa-tool.1
  src/tools/opensc-asn1.1
  src/tools/opensc-notify.1
  src/tools/egk-tool-cmdline.c
contain references to the - in my opinion - outdated - address for reporting bugs:
opensc-devel@lists.sourceforge.net;
this should better be https://github.com/OpenSC/OpenSC/issues

### Proposed Resolution

I am not sure, what the correct solution is, especially with the man pages.
The man pages affected are special as  they are 
* created via help2man, and nor from an XML file
* located in src/tools/ instead of doc/tools/

A quick one-time fix could be - after applying https://github.com/OpenSC/OpenSC/pull/1356 - to:
- remove the files above
- regenerate the affected src/tools/*-cmdline.c via gengetopt from the corresponding *.ggo.in
- recomplile the binary tools
- regenerate the affected man pages via help2man & the tools just recompiled
A more complete fix would be to code this into the Makefile.am

I am not sure whether this is the most practical approach, as it requires a full compilation cycle
before being able to provide updated files.
Maybe 
* creating XML files for the man pages 
* manually updating the wrong bug reporting location once
would be better and in line with the other tools.

@frankmorgner If you are interested in the latter alternative, this is my offer to do it.
Just drop me a note.

### Steps to reproduce

$ grep -rl -e 0.16.0 -e 0.17.0 src/tools/
$ grep -rl lists.sourceforge src/tools/

**Comment by frankmorgner** [comment]
I've regenerated the files as short term fix.

I'd prefer the XML description for all tools to drop the dependency to help2man, so yes please.
