### ISSUE TITLE
SmartCardHSM - Cannot Unwrap Key, "Invalid wrapped key format (Key binary)."

### ISSUE THREAD

**Issue by CampinCarl** [OpenSC/OpenSC#1371]
### Problem Description
Following the instructions in the [SmartCardHSM Wiki - Key Backup and Restore](https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM#using-key-backup-and-restore), I'm seeing a ```Invalid wrapped key format (Key binary).``` error message when attempting to unwrap a private key. The ```sc-hsm-tool.exe``` wraps the key without error but then errors out when attempting to unwrap. I've attempted unwrapping to a secondary card (same DKEK) or the same card; the same error message is displayed in both cases.

I'm not sure if this would affect the wrap/unwrap procedures but I deviated from that section of the wiki in the length of the user PIN, i.e., 8 digits instead of 6.

**Environment Information**
- **Platform**: Windows 10 - Version 1803
- **OpenSC Version**: OpenSC 0.18.0 [Microsoft 1800] (32-Bit) - Enabled features:pcsc openssl zlib
- **Reader**: Broadcom Corp Contacted SmartCard
- **Card** : SmartCard-HSM version 2.5

### Proposed Resolution
Unknown

### Steps to reproduce
Per the Wiki entry mentioned above, I'm using the following commands when I encounter the error.
```
sc-hsm-tool --wrap-key wrap-key.bin --key-reference 1
sc-hsm-tool --unwrap-key wrap-key.bin --key-reference 10
```

### Logs
Debug log from the command line, i.e., using the ```-vvv``` parameter.
https://gist.github.com/CampinCarl/d26f92dd7dde8d06252754e98aac2189#file-gistfile1-txt-L93

**Comment by CardContact** [comment]
I can reproduce this with 0.18.0.

Seems to be introduced by 45ad44e31.
