### ISSUE TITLE
Add sha256 checksums for release

### ISSUE THREAD

**Issue by leebrian** [OpenSC/OpenSC#1383]
### Problem Description

Would you please add sha256 checksums as part of the release process? There are two related issues #1129 (open, wishlist) and #1338 (closed, dupe of 1129) that bundle signatures and checksums together. Adding a checksum is not as costly as getting signatures, so I thought a simpler request just for checksums would be a worthy separate issue that could be done.

I couldn't figure out how you generate the release notes or I would submit a PR with the make changes to generate sha256 checksums.

### Proposed Resolution
Include sha256 checksum for each asset in the release

### Steps to reproduce
N/A

### Logs
N/A

**Comment by frankmorgner** [comment]
What you really want is #1129! How does a hash value improve the situation when you download it from the same source as the binary?

The release notes are a hand-written summary of all the changes compared to the last release.

**Comment by leebrian** [comment]
Thanks for looking at this, I do want 1129, but that is more effort, as you described in the item. Without a signature to verify it was really you who made the release, a checksum is still useful to me so at least I know the integrity of the file that I downloaded and that it wasn’t changed by my browser or something in between me and Github. 

Since they’re hand written, it probably won’t help you if make a pull request with changes to start a release notes file that includes the checksums. But if it does, I’ll make one.
