### ISSUE TITLE
PIV should use sc_asn1_put_tag instead of put_tag_and_len

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1394]
As far as I can see, a card driver based implementation is not needed.

@dengert, could you have a look, please?

**Comment by Jakuje** [comment]
FYI as I integrated PIV corpus into the oss-fuzz, I started seeing OOB accesses in the PIV driver so I took it as an opportunity to remove the internal implementation and use the asn1 version which properly checks bounds and we will hopefully be able to close this long standing issue.

**Comment by dengert** [comment]
Looks, OK. Thanks.
