### ISSUE TITLE
CAC: cac_match_card should not initialize drv_data

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1395]
### Problem Description

cac_init and cac_match_card are both calling cac_find_and_initialize which initializes card->drv_data. During card detection (sc_connect_card) it is possible for some bogus card to successfully pass cac_match_card, but lead to some error in cac_init. In this case, the next card driver may at best overwrite drv_data, which leads to some memory lost. In the worst case, this leads to some memory corruption when the next card driver tries to reuse this memory when accessing the memory out of bounds.

### Proposed Resolution

Don't call cac_find_and_initialize in cac_match_card

@Jakuje could you have a look?

**Comment by Jakuje** [comment]
`cac_match_card()` calls the `cac_find_and_initialize()` with the second argument set to 0, which means that the [following branches](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-cac.c#L1968) got hit before going to any structures initialization:
```
1549                 if (!initialize) /* match card only */
1550                         return r;
```
Is even this a problem?

**Comment by frankmorgner** [comment]
Sorry for the noise, I missed this bit.
