### ISSUE TITLE
OSX installation error

### ISSUE THREAD

**Issue by SmallRoomLabs** [OpenSC/OpenSC#1398]
### Problem Description

The MacOS dmg image can't be opened on a machine still running the OSX El Capitan or older.

<img width="378" alt="screen shot 2018-06-16 at 14 50 14" src="https://user-images.githubusercontent.com/325326/41498714-a1973206-7174-11e8-9b42-2d9f15bb7a48.png">

From what I understand the default filesystem for dmg's have changed to APFS - something that apparently El Capitan can't read.

### Proposed Resolution

Make the dmg's with the old UDIF format which I believe is compatible with the newer MacOS and the old OSX versions.

**Comment by frankmorgner** [comment]
We are (and always have been) creating the image with something like `hdiutil create -srcfolder "${imagedir}" -volname "@PACKAGE_NAME@" OpenSC-@PACKAGE_VERSION@.dmg`. There have been some changes to `hdiutil` lately (see https://github.com/OpenSC/OpenSC/issues/1198), which may also be the reason for a change of the default format. Please make a pull request with your changes and we can test/integrate them for the next release.

**Comment by rajramasawmy** [comment]
Hi,
I am also using El Capitan and having the same issue. 
Is it possible to install from the opensc-0.18.0.tar.gz?
I tried running the install-sh script, but I am not sure what input files it wants, running with no input arguments returns: "no input file specified".
Thanks

**Comment by frankmorgner** [comment]
We could explicitly specify e.g. HFS+. This, however, would make the image [incompatible with Sierra and later](https://forum.qt.io/topic/86672/qt-dmg-no-mountable-file-systems-on-el-capitan-backwards-compatibility-issue/3). It seems like we need to create two images (or drop backward compatibility)...

**Comment by martinpaljak** [comment]
I don't understand why a HFS+ DMG should not work on Sierra or later?

**Comment by SmallRoomLabs** [comment]
Yea, that seems very unlikely that Sierra can't open DMGs from the previous OSX release - then basically all software installations would have failed for the first year or so until the developers made new ones.

I can't test this - but it should be easy for @frankmorgner  to make a dmg with hfs+ and test on his machine. If it works then why not use hfs+ for the next few years until the El Capitan and older have died of old age?

**Comment by rajramasawmy** [comment]
In the end, I just used 0.17.0 version, which installs fine on El Capitan, and which works for my purposes.

**Comment by franton** [comment]
Correct, hdiutil now defaults on 10.12 or better to using APFS as it's filesystem. Adding the switch `-fs JHFS+` to the existing hdiutil command should fix this issue.

**Comment by frankmorgner** [comment]
Please check whether the binaries at https://github.com/OpenSC/Nightly/tree/2018-08-24_5a25bd33 are fixing your issue

**Comment by SmallRoomLabs** [comment]
Yes, that works just fine.... I can open that dmg on my old El Capitan laptop.  Thanks!

**Comment by frankmorgner** [comment]
works also in High Sierra
