### ISSUE TITLE
MacOS build in CI fails to find dependencies

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#1400]
### Problem Description

During the investigation in the #1389, I was trying to make the Mac build the testsuite against cmocka installed from brew. But the [`MacOSX/build-package`](https://github.com/OpenSC/OpenSC/blob/318329d5b7fb4c69fa0601fc877f2f5656fb2c61/MacOSX/build-package.in#L20) is setting `-isysroot` option to `$CFLAGS`, which prevents the compiler from searching the `/usr/local/include`, where the header files are installed (see the log in https://github.com/OpenSC/OpenSC/pull/1389#issuecomment-397216903 ).

The thing I do not understand here is that the configure is ran three times for MacOS build, the first two runs detect everything correctly (do not have `-isysroot`, but the last one fails. It generally produces pretty weird logs also for other header files:
```
checking openssl/crypto.h presence... no
configure: WARNING: openssl/crypto.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: openssl/crypto.h: proceeding with the compiler's result
checking for openssl/crypto.h... yes
[...]
checking pcsclite.h presence... no
configure: WARNING: pcsclite.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: pcsclite.h: proceeding with the compiler's result
checking for pcsclite.h... yes
```
But for some reason, the same trick does not work for cmocka (actually, here is used the `AC_CHECK_HEADER` instead of `AC_CHECK_HEADERS`, if it could make difference):
```
checking for cmocka >= 1.1.0... yes
checking setjmp.h usability... yes
checking setjmp.h presence... yes
checking for setjmp.h... yes
checking for cmocka.h... no
```

### Proposed Resolution
I am not familiar with the MacOS so I am not sure what is the correct solution.

### Steps to reproduce
 * Extend CFLAGS and LDFLAGS to have `-v` switch in `MacOSX/build-package.in`
 * schedule a CI build.
### Logs
The full log from CI from #1389:
[travis-ci.log](https://github.com/OpenSC/OpenSC/files/2119159/travis-ci.log)

**Comment by frankmorgner** [comment]
on macos, `configure` should be run twice. first, to generate/fill `MacOSX/build-package`, second as part of the build process of the dmg file.

in order to run your tests on macos, simply skip the scripts in `MacOSX`, and just run the standard build commands that are also used on Linux

**Comment by mouse07410** [comment]
It would be great if you could give an example - sequence of commands that, e.g., user can type to build the binaries _and_ run the tests.

**Comment by Jakuje** [comment]
It looks like this is expected from what you write. Maybe one more question, I see now that first we run the first configure, then we install openssl and then we run the other configure.  Would it make sense to install openssl first? And maybe one more, would it work to update to OpenSSL 3.0 on MacOS?
