### ISSUE TITLE
[PATCH] Fix completiondir

### ISSUE THREAD

**Issue by stanislav-brabec** [OpenSC/OpenSC#1403]
### Problem Description
Recent versions of bash is leaving /etc/bash_completion.d. The correct directory is specified by `pkg-config --variable completionsdir bash-completion`.

### Proposed Resolution
If possible, use pkg-config to determine the correct directory.

### Steps to reproduce
Install opensc with the latest bash.

### Logs
N/A

**Comment by stanislav-brabec** [comment]
[0001-Use-correct-bash-completion-path.patch.gz](https://github.com/OpenSC/OpenSC/files/2128022/0001-Use-correct-bash-completion-path.patch.gz)

**Comment by frankmorgner** [comment]
can you make a pull request?

**Comment by stanislav-brabec** [comment]
https://github.com/OpenSC/OpenSC/pull/1408
