### ISSUE TITLE
p11test does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#1405]
### Problem Description

    ./configure --enable-tests
    make

fails with unresolved links to cmocka.

### Proposed Resolution

Replace CMOCKA_LDFLAGS in p11test/Makefile.am with CMOCKA_LIBS
Allow version of CMOCKA to be 1.0.1 in configure.ac

**Comment by frankmorgner** [comment]
can you make a pull request?
