### ISSUE TITLE
CKR_DATA_LEN_RANGE error occurs when signing a large size data.

### ISSUE THREAD

**Issue by redblueshin** [OpenSC/OpenSC#1428]
### Problem Description
OpenSC : 0.15.0 [gcc  5.3.1 20160413]
System : Ubuntu 16.04
HSM : Nitrokey HSM
When signing a large size data (eg. 4KB), it returns CKR_DATA_LEN_RANGE error.
Please let me know how to fix it.

### Proposed Resolution
N/A

### Steps to reproduce
Try to sign a large size data greater than 512 bytes (eg. ECDSA)

I have revised the source code as follows but I've got another errros respectively.
1) Increase the signature buffer size of “signature_data” structure in "mechanism.c".
    - CK_BYTE buffer[4096/8]; -> CK_BYTE buffer[6000];
    - I've got "error: PKCS11 function C_SignFinal failed: rv = CKR_BUFFER_TOO_SMALL (0x150)".
2) Increase the input buffer size in "sing_data" function in "pkcs11-tool.c".
    - unsigned char	in_buffer[1025] -> unsigned char	in_buffer[6000] 
    - I've got "error: PKCS11 function C_SignInit failed: rv = CKR_OPERATION_ACTIVE (0x90)".

### Logs
root@server:/media/sf_shared/securerom/EC public key# pkcs11-tool --module /usr/lib/pkcs11/opensc-pkcs11.so --login --pin 648219 --sign --id 20 --input 2.in --output 2.sig
Using slot 1 with a present token (0x1)
Using signature algorithm ECDSA
error: PKCS11 function C_SignUpdate failed: rv = CKR_DATA_LEN_RANGE (0x21)

Aborting.

"2.in" size is 4KB.

**Comment by frankmorgner** [comment]
You should use a newer release of OpenSC.

**Comment by redblueshin** [comment]
Thank you. As far as I know, 0.15.0 is the latest one in Ubuntu 16.04 as follows.
[](url)

If it is not the latest one, would you please let me know the latest one ?

**Comment by frankmorgner** [comment]
https://github.com/OpenSC/OpenSC/wiki#download

**Comment by redblueshin** [comment]
Thank you ! I have already downloaded and installed the opensc-0.18.0.tar.gz at the link however, I've got the same error. Anyway, I will try it again.

**Comment by redblueshin** [comment]
I have installed and compiled OpenSC according to the link below but it returns the same error.
The log is attached.
[Uploading errlog.txt…]()
https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors

**Comment by frankmorgner** [comment]
The (default) signature mechanism operates on the raw data. You need to make the input smaller or use a different mechanism for signing (`--mechanism`), which includes hashing.

**Comment by redblueshin** [comment]
Thank you for reminding me of using hash algorithm. I think this is what I want to find. Thanks again.

**Comment by mouse07410** [comment]
And I was saying - for most tokens you won't find a mechanism (discoverable via "pkcs11-tool -M" to be used via "pkcs11-tool -m ...") that would include (automatic) hashing of the data. I'm pretty sure it applies to RSA-based signatures as well.

**Comment by dengert** [comment]
PKCS\#11 2.40 only defines CKM_ECDSA  and CKM_ECDSA_SHA1.  OpenSC extended this:
```
#define CKM_ECDSA			(0x1041UL)
#define CKM_ECDSA_SHA1			(0x1042UL)
#define CKM_ECDSA_SHA224		(0x1043UL)
#define CKM_ECDSA_SHA256		(0x1044UL)
#define CKM_ECDSA_SHA384		(0x1045UL)
#define CKM_ECDSA_SHA512		(0x1046UL)
```
https://wiki.oasis-open.org/pkcs11/Definitions implies V2.30 defined these, but they are not in 2.40
So try  `pkcs11-tool -M` and see what it says your card supports. `card-sc-hsm.c` implies it can support 
SC_ALGORITHM_ECDSA_HASH_SHA256, but maybe not via PKCS\#11.

In any case, you can do what Frank and Mouse suggested and do the hash in a separate step which should always work.

**Comment by redblueshin** [comment]
Thank you all.
