### ISSUE TITLE
opensc-tool gives --atr result, but "Unsupported card" for --name for new SLE4442 smart card

### ISSUE THREAD

**Issue by ljbrown238** [OpenSC/OpenSC#1431]
I'm attempting to use the OpenSC version 0.18.0 library on my Mac OS High Sierra 10.13.5 to communicate with an ACR38U-I1 reader, connected via USB.

Inserting a brand new SLE4428 smart card into the reader, and then executing the following command  

    opensc-tool --reader 0 --atr

yields this (obfuscated) output:  

    XX:04:92:XX:10:91

The reader is clearly reading information from the card itself.

However, this command to get the name of the card

    opensc-tool --reader 0 --name

yields this output:  

    Unsupported card

I have a stack of brand new SLE4428 and SLE4442 cards, and they give the same result.

Is this a bug, or are there configuration changes I should make to correct this issue so `opensc-tool` recognizes either the SLE4428 or SLE4442 cards?

**Comment by CardContact** [comment]
The card is a simple memory card that uses a proprietary communication interface rather than ISO 7816. Those cards are not supported by OpenSC.

**Comment by ljbrown238** [comment]
Thank you, for the prompt and precise direction!
