### ISSUE TITLE
How To Report Bugs wiki page is outdated, where to get support?

### ISSUE THREAD

**Issue by thw0rted** [OpenSC/OpenSC#1433]
### Problem Description

The [How To Report page](https://github.com/OpenSC/OpenSC/wiki/How-to-report-bugs-so-that-they-can-be-fixed) linked in the project issue template (where I'm writing right now!) has not been updated since 2012.  As far as I can tell the project no longer uses Trac and the user-help mailing list is [marked as deprecated here](https://github.com/OpenSC/OpenSC/wiki/Mailing-lists).

### Proposed Resolution

Someone connected with the project should update the wiki to remove outdated references to SourceForge, unused mailing lists, etc, and provide new instructions for seeking OpenSC *end-user* support.

As an aside: I posted [a question on SuperUser](https://superuser.com/questions/1341599/firefox-shows-multiple-pin-prompts-for-smartcard-using-opensc) but had to create the `opensc` tag myself because it didn't exist yet.  Nobody has seen my question yet, as far as I can tell.  Maybe users are expected to request support here?

**Comment by frankmorgner** [comment]
your in the right spot here. additionally, the mailing list is still alive, though not very active. feel free to update the wiki

**Comment by dengert** [comment]
I answered your [a question on SuperUser](https://superuser.com/questions/1341599/firefox-shows-multiple-pin-prompts-for-smartcard-using-opensc) In effect get more info and submit an issue here.

**Comment by thw0rted** [comment]
Thanks, Frank and Douglas.  I'll leave this issue open to make sure the Wiki page gets attention (maybe I can fix some parts myself?) and open a separate issue for my multiple-PIN-entry problem.

**Comment by martinpaljak** [comment]
I’d sai tihe wiki is out of order - too many pages and many of them severely outdated. Would be nice if it got some shepherding:)

**Comment by frankmorgner** [comment]
I think the pages are up to date now
