### ISSUE TITLE
Is Le not logged [Query]

### ISSUE THREAD

**Issue by amitkumar50** [OpenSC/OpenSC#1444]
### Problem Description

I see this after connecting Atos card 5.3
`# /usr/local/bin/opensc-tool -a -vvv`
0x7fd485e77880 17:20:53.811 [opensc-tool] apdu.c:378:sc_single_transmit: CLA:0, INS:CA, P1:1, P2:8D, data(0) (nil)
0x7fd485e77880 17:20:53.811 [opensc-tool] reader-pcsc.c:284:pcsc_transmit: reader 'Gemalto PC Twin Reader 00 00'
0x7fd485e77880 17:20:53.811 [opensc-tool] reader-pcsc.c:285:pcsc_transmit:
Outgoing APDU (5 bytes):
00 CA 01 8D 02 .....
0x7fd485e77880 17:20:53.811 [opensc-tool] reader-pcsc.c:213:pcsc_internal_transmit: called
0x7fd485e77880 17:20:53.815 [opensc-tool] reader-pcsc.c:294:pcsc_transmit:
Incoming APDU (4 bytes):
01 80 90 00 ....

What is 02 in CAPDU (00 CA 01 8D 02)? Is this Le?
  P1=01(1st parameter), P2=8D(2nd parameter)

Is RAPDU correct?  (01 80 90 00)
a. Asked P2 was 8D, but came=80. Does this mean card does not have data starting from 01 8D?
b. Do I need to ask communication specs from manufacturer of card for same.

Too early to say but sorry I  feel there is lot of repetitive code we can optimize it.

**Comment by martinpaljak** [comment]
You can try stackoverflow for generic smart card discussion. Or is there a bug in OpenSC? Having specs for a productg is always a good thing and usually required to do development for a specific card.
