### ISSUE TITLE
eGK G2 egk-tool read error

### ISSUE THREAD

**Issue by RBEGamer** [OpenSC/OpenSC#1451]
### Problem Description

Since this week the new eGK Cards will be distributed to the citizens. The card is the new generatation marked with "G2". The egk-tool command cant display the base data of the card holder.

### Steps to reproduce
* Insert a G2 eGK and run the egk-tool command. Tested under Ubuntu 16.4 and Mac OSX 10.13

### Test

EGK G1:
$ egk-tool --pd
<UC_PersoenlicheVersichertendatenXML xmlns="http://ws.gematik.de/fa/vsdm/vsd/v5.2" CDM_VERSION="5.2.0"><Versicherter><Versicherten_ID>...

EGK G2:
$ egk-tool --pd
-- no output --

Tested with various G1 and G2 Cards.

**Comment by frankmorgner** [comment]
please add a debug log with `debug = 3` in `opensc.conf`

**Comment by RBEGamer** [comment]
Here are the first information:
$ opensc-tool -f
Using reader with a card: Generic Smart Card Reader Interface
SELECT FILE failed: Incorrect parameters in APDU

$ opensc-tool --atr
3b:d3:96:ff:81:b1:fe:45:1f:07:80:81:05:2d

$ opensc-tool --name
**German ID card (neuer Personalausweis, nPA)**

> seems to that the egk g2 will be loaded as German ID Card

$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Generic Smart Card Reader Interface


I will provide more as soon as possible

**Comment by frankmorgner** [comment]
This is fixed upstream.

Editing the `opensc.conf` to something like the example below should also work:
```
app default {
	card_atr 3b:d3:96:ff:81:b1:fe:45:1f:07:80:81:05:2d {
		type = 7002;
		driver = "starcos";
		name = "STARCOS";
	}
}
```
