### ISSUE TITLE
Should yubico-piv-tool still be able to initialize a simulated PIV smart card?

### ISSUE THREAD

**Issue by mgramigna** [OpenSC/OpenSC#1469]
### Problem Description

Looking for more clarity on using `yubico-piv-tool` for a simulated smart card. Do we expect it to be able to work for a simulated smart card using [these instructions](https://github.com/arekinath/PivApplet#installing)? If so, `yubico-piv-tool` is unable to connect to BixVReader.

### Proposed Resolution

Perhaps the use of `yubico-piv-tool` is unnecessary for simulated smart cards?

### Steps to reproduce

1) Follow [these instructions](https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Simulation) to simulate a PIV smart card using BixVReader on Windows.

2) Running `yubico-piv-tool -r '' -a list-readers` results in the console saying "Failed to connect to reader"

**Comment by mouse07410** [comment]
yubico-piv-tool is not a part of OpenSC, and *must* not be used with simulated cards such as SoftHSM. or BixVReader. This tool is written specifically for Yubikey devices (which are very nice).

**Comment by frankmorgner** [comment]
It appears that either your simulated reader isn't working correctly or that the emulated card is not correctly registered. Try starting with some more generic commands, like:
```
opensc-tool --list-readers
opensc-tool -n -vvv
```

**Comment by dengert** [comment]
This is really a Yubico issue, not OpenSC. OpenSC's card-piv.c is really only for read access to initialized and provisioned cards. NIST leaves up to the vendor (Yubico) how to initialize and provision their cards, and has a minimal incomplete commands for initializing and provisioning cards.  The OpenSC `piv-tool`
can uses some of them, and can also use the `--send-apdu` option for others, but is not designed to be a card management station. 

If you are writing your own simulator, you don't have to use APDUs.  

I suspect that the first thing `yubico-piv-tool` does is test for a Yubico device which your emulator can't handle it.  So if you want to use `yubico-piv-tool` you need to emulate a Yubico device running their PIV applet.  

Are you writing your own simulated PIV applet? Or using the [arekinath PivApplet](https://github.com/arekinath/PivApplet) ?

**Comment by mgramigna** [comment]
@frankmorgner The first command results in the following:

```
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Fabio Ottavi Pipe Reader 0
```

I also ran `opensc-tool -vv -n` and got the following:

```
C:\Users\IEUser>opensc-tool -vv -n
Using reader with a card: Fabio Ottavi Pipe Reader 0
Connecting to card in reader Fabio Ottavi Pipe Reader 0...
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card.c:196:sc_connect_card: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-entersafe.c:138:entersafe_match_card: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-rutoken.c:103:rutoken_match_card: called
P:1312; T:2164 2018-09-06 05:55:35.804 SELECT AID: 6D00
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-muscle.c:817:muscle_card_reader_lock_obtained: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] muscle.c:276:msc_select_applet: returning with: -1200 (Card command failed)
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-piv.c:3576:piv_card_reader_lock_obtained: called
P:1312; T:2164 2018-09-06 05:55:35.804 PIV_STATE_MATCH
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-piv.c:2681:piv_find_discovery: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-piv.c:998:piv_get_cached_data: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.804 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.814 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.814 [opensc-tool] card-piv.c:2681:piv_find_discovery: called
P:1312; T:2164 2018-09-06 05:55:35.814 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.814 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.814 [opensc-tool] card-piv.c:2938:piv_finish: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:3162:piv_init: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:3576:piv_card_reader_lock_obtained: called
P:1312; T:2164 2018-09-06 05:55:35.834 PIV_STATE_MATCH
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:2681:piv_find_discovery: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:998:piv_get_cached_data: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:2681:piv_find_discovery: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.834 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.844 [opensc-tool] card-piv.c:2742:piv_process_history: called
P:1312; T:2164 2018-09-06 05:55:35.874 [opensc-tool] card-piv.c:998:piv_get_cached_data: called
P:1312; T:2164 2018-09-06 05:55:35.874 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.874 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.874 [opensc-tool] card-piv.c:494:piv_general_io: called
P:1312; T:2164 2018-09-06 05:55:35.884 [opensc-tool] card-piv.c:998:piv_get_cached_data: called
Using card driver Personal Identity Verification Card.
P:1312; T:2164 2018-09-06 05:55:35.914 [opensc-tool] card-piv.c:3576:piv_card_reader_lock_obtained: called
P:1312; T:2164 2018-09-06 05:55:35.954 [opensc-tool] card-piv.c:2681:piv_find_discovery: called
P:1312; T:2164 2018-09-06 05:55:35.954 [opensc-tool] card-piv.c:927:piv_get_data: called
P:1312; T:2164 2018-09-06 05:55:35.954 [opensc-tool] card-piv.c:494:piv_general_io: called
Card name: Personal Identity Verification Card
P:1312; T:2164 2018-09-06 05:55:35.974 [opensc-tool] card-piv.c:2938:piv_finish: called
P:1312; T:2164 2018-09-06 05:55:35.974 [opensc-tool] ctx.c:903:sc_release_context: called
```

**Comment by mgramigna** [comment]
@dengert I am using arekinath PivApplet with BixVReader following the Piv section of [these instructions](https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Simulation)

Thank you for the insight about Yubico. That's useful information for sure.

**Comment by dengert** [comment]
I posted some questions on https://github.com/arekinath/PivApplet as the subject of this discussion is not related to OpenSC but to the use of the Applet.

**Comment by frankmorgner** [comment]
I've created a [PR that integrates PIV simulation and testing](https://github.com/OpenSC/OpenSC/pull/1568). The only change I'm using was the APDU for installation:
```
opensc-tool --card-driver default --send-apdu 80b80000120ba000000308000010000100050000020F0F7f
```
I've changed the wiki page accordingly.
