### ISSUE TITLE
problems with the ACS ACR38U reader and pkcs11 token in a smart card

### ISSUE THREAD

**Issue by efferre79** [OpenSC/OpenSC#1473]
### Problem Description

I am using opensc with the opensc-pkcs11.so plugin with firefox to use a pkcs11 token in a smart card protected by a PIN. Here is the software stack I am using under Linux:

pcsc-lite 1.8.23
opensc 0.19.0_rc1
firefox 61
nss 3.38

I am trying to enter into a website where the access is protected by a smartcard. Almost at the end of the procedure firefox hangs and also it's impossible to use other software (e.g. chromium) to access the Web (I guess the nss library is blocked). 

What happens is repeatable every time. In the past the card was working but I cannot reproduce anymore the successfully software versions combination I was using at that time :-(

### Steps to reproduce

Here are the steps:
1) start the pcscd daemon
2) the card is inserted in the smart card and recognized by using pcsc_scan
3) configure firefox to use opensc-pkcs11.so, the card reader and the card are visible in the "security devices" section of firefox after the configuration
4) go to the web page where the security token is needed
5) as soon as I try to enter the protected website firefox asks to me for the PIN and I insert it
6) I am then prompted with a User Identification Request saying that the website has requested to identify myself with a certificate, I select the only available certificate and press OK
7) firefox hangs 

The only way to unlock firefox is to stop the pcscd daemon.

### Logs

opensc.conf is not changed, it has the default values

I have started firefox with the following command line:

`$ OPENSC_DEBUG=3 PKCS11SPY=/usr/lib/pkcs11/opensc-pkcs11.so PKCS11SPY_OUTPUT=pkcs11spy.log  firefox 2>&1 | tee opensc-pkcs11.log `

Here are the two [logs](https://gist.github.com/efferre79/eed814ccbefbb0fc4dffbf067163055d) produced. In the log files there are indicated key events described in the step list above. I hope to have removed all private data.

**Comment by dengert** [comment]
The logs do not show the OpenSC version. 
Is the opensc 0.19.0_rc1 opensc-pkcs11.so  installed in `/usr/lib/pkcs11/opensc-pkcs11.so`?

Looks like card driver is `card-itacns.c`

In line 897, a C_Sign was started, for 36 bytes,  OpenSC used the decrypt function for some reason. 
The data to be sent is 1 line 985 and pkcs1 padding but the user has hidden the data and the 32 bytes returned. 
line 1003:
23:06:56.269 [opensc-pkcs11] iso7816.c:133:iso7816_check_sw: Unknown SWs; SW1=EF, SW2=85

So it looks like the card did not like the command, and returned 32 bytes for some reason, and the 
unknown SW1=EF and SW2=85

This looks like it may have caused problems internally to the card so then later
in line 1022:
23:06:56.270 [opensc-pkcs11] card-itacns.c:246:itacns_restore_security_env: called
The card sends `00 22 F3 03 00` It looks like it matches the code from 2010. With this comment:
```
* The Italian CNS requires a 0-valued Lc byte at the end of the APDU
* (see paragraph 13.14 of the Functional Specification), but since
* it is invalid, we "cheat" and pretend it's a Le byte.
```
The card then hangs, user  killed  pcsc and in line 1048:
23:07:56.248 [opensc-pkcs11] reader-pcsc.c:291:pcsc_transmit: unable to transmit

But earlier the same command worked `00 22 F3 03 00`

So it looks like the OpenSC sign routines was trying to do raw RSA, sending the padded data, but the card only returned 32 bytes and the card got hung up.

**Comment by efferre79** [comment]
@dengert 

Yes, I confirm 0.19.0-rc1 version of opensc I am using. I have stripped down the log only to what I considered interesting for the debug, if you need I can upload the remaining initial part too.
 
>0x7f8e1567a740 23:04:33.160 [opensc-pkcs11] ctx.c:708:process_config_file: Used configuration file '/etc/opensc.conf'
>0x7f8e1567a740 23:04:33.160 [opensc-pkcs11] ctx.c:831:sc_context_create: ===================================
>0x7f8e1567a740 23:04:33.160 [opensc-pkcs11] ctx.c:832:sc_context_create: opensc version: 0.19.0

Yes, I am using an Italian CNS so the driver you're pointing seems correct.
 
I have hidded the data related to C_Sign but I don't know if it's sensitive data. If you don't think so I can upload also what is now hidden.

**Comment by dengert** [comment]
One of the changes in 0.19.0 is a minimal opensc.conf. Do you have the previous version of opensc.conf?
maybe something was left out that is need for your card.  For example max_send_size or max_recv_size. 

It looks like the set_security_env  `00 22 F1 B8 03 83 01 01`  could be wrong. I don't have one of these cards and don't know if that is correct or not. 

Or the crypto command sent to the card have a problem. What is really strange is in lines 997 to 999 where it only returned 32 bytes it should have been 128 bytes and the SW1 and SW2. 

Can you send lines 985 to 1000. The outgoing is a padded hash and is not sensitive. 
The  response should have been  encrypted and 128 bytes + SW1 and SW2.  It should look random.
if not then it maybe the card has returned something that may be sensitive.  But in any case what are the last 2 bytes? 

The SW1=EF  should not be produced by the card.  The reader may have. Or the reader is broken. 

The PCSC logs could also show this command and its response. If they don't match to what is in the log would indicate some software problem overwriting some data. 
 
You said: "In the past the card was working but I cannot reproduce anymore the successfully software versions combination I was using at that time :-(" 

The reader broke? Do you have a different reader?
The card broke? Is there any machine were it still works?

Can you use any other software to see if it works?
for example `pkcs11-tool --test --login`  

 I assume this is a government issued card. Can you get it tested or replaced?

**Comment by efferre79** [comment]
First of all, some replies to your questions. I have tested also opensc-0.16 and opensc-0.18 with their default opensc.conf file, same result. I have updated the log files to include the requested hidden data now. No, the reader is the same and it is still working, tested also in the past days on Windows when I discovered the problem under Linux. The card works too, tested with the same reader on Windows with the same website. In the past I made them to work under Linux, I tried reinstalling the same software combination but without luck. Do you think something is changed in the website, i.e. the website can ask for a different cryptography mechanism?

When I issue the command you suggest it seems replicating the same behaviour as with firefox:

> \# pkcs11-tool --test --login
> Using slot 0 with a present token (0x0)
> Logging in to "PIN CNS0 (xxxxx xxxxx)".
> WARNING: user PIN locked
> Please enter User PIN: 
> C_SeedRandom() and C_GenerateRandom():
>   seeding (C_SeedRandom) not supported
>   seems to be OK
> Digests:
>   all 4 digest functions seem to work
>   MD5: OK
>   SHA-1: OK
>   RIPEMD160: OK
> Signatures (currently only for RSA)
>   testing key 0 (CNS0) 

then the application hangs (the full log is [here](https://gist.github.com/efferre79/cae57aee37fa6650ec4bc85f69352bbb), it seems tha the sc_decipher() function is called twice with the same payload, the first time it completes correctly while the second returns less bytes and fails). I compared the log with the one obtained from pcscd and the data is not overwritten. As soon as I kill pcscd I get:

> error: PKCS11 function C_Sign failed: rv = CKR_GENERAL_ERROR (0x5)
> Aborting.

You are right that something is screwed in the card reader because retrying with the same command (restarting pcscd) I get

> \# pkcs11-tool --test --login
> No slot with a token was found.

If I remove the card and reinsert in the reader I get the same result. I need to disconnect the reader from the USB (power cycle) to have it again working. 

Finally some investigations about the specifications of the CNS cards.

The latest documentation about the Italian CNS I have found is version [1.1.6](https://www.agid.gov.it/sites/default/files/repository_files/documentazione_trasparenza/cns_functional_specification_1.1.6_02042011.pdf) where the source code refers to 1.1.5 which is not anymore available.

Moreover I have found another [document](https://www.agid.gov.it/sites/default/files/repository_files/leggi_decreti_direttive/specifiche_tecniche_del_documento_digitale_unificato_v.0.0.pdf) (let's call it **draft**), which unfortunately is only in Italian, that still refers to the spec 1.1.6 cited above where at page 25 it describes the electronic signature with 2048 bit RSA keys. There is a **final** version [here](https://www.agid.gov.it/sites/default/files/repository_files/leggi_decreti_direttive/specifiche_tecniche_del_documento_digitale_unificato_v.1.0.0.pdf) where the same paragraph is now at page 24 but is shortened moving some technical details to the "Card Capabilities" chapter in an English document available [here](https://www.agid.gov.it/sites/default/files/repository_files/leggi_decreti_direttive/ddu_-_functional_specification_v.1.0.0.pdf).

I'll try to summarize but I don't know anything about smart cards and what is behind opensc. From what I can understand in the draft document they say that different smart cards may handle in a different way RSA cryptography with 2048 bit keys. The documents define a solution to overcome that problem and have the CNS application working. Basically the pkcs11 library should query for the card capabilities and sent the right commands based on the results of that preliminary check. They discourage a direct use of APDU commands to use the private key of authentication certificate because different CNS cards can adopt different commands for the 2048 bits RSA cryptography. If someone wants to use anyway the APDU commands then it's needed to detect the chip with ATR analysis and apply the right commands specific to it. I hope it make sense to you.

If the RSA signature uses 128 bytes than it is using 1024 bits so probably it's not related to the problem I am facing. Is it correct?

It would be nice to have an automatic way to hide sensitive data in the logs, it would save a lot of time without making errors especially if you don't know the protocol :-)

**Comment by frankmorgner** [comment]
```
Outgoing APDU (5 bytes):
00 22 F3 03 00 ."...
0x7f8df3ffd700 23:06:56.270 [opensc-pkcs11] reader-pcsc.c:213:pcsc_internal_transmit: called

*****************************************
*** Here firefox hangs, I then stop pcscd
*****************************************

0x7f8df3ffd700 23:07:56.248 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: ACS ACR38U 00 00:SCardTransmit/Control failed: 0x80100013
0x7f8df3ffd700 23:07:56.248 [opensc-pkcs11] reader-pcsc.c:412:pcsc_detect_card_presence: called
0x7f8df3ffd700 23:07:56.248 [opensc-pkcs11] reader-pcsc.c:320:refresh_attributes: ACS ACR38U 00 00 check
0x7f8df3ffd700 23:07:56.248 [opensc-pkcs11] reader-pcsc.c:342:refresh_attributes: ACS ACR38U 00 00:SCardGetStatusChange failed: 0x8010001d
```
If this command hangs, there's nothing OpenSC can do about it, there is no way of aborting `SCardTransmit()`. You have the same symptom when, for example, a card simply takes very long to respond. 

Theoretically, we could run each I/O operation in a seperate thread, to be able to keep the application alive even when the card/reader doesn't respond. But honestly, this would be the job of `pcscd`. Are you having the same problem on Windows?

Maybe @LudovicRousseau could discuss in the PC/SC group whether assuming some reasonable time restrictions could be useful in the future...

**Comment by LudovicRousseau** [comment]
@efferre79  Please provide a pcscd log as described in https://pcsclite.apdu.fr/#support

@frankmorgner IIRC ISO7816 does not define a maximum communication time. The card card ask for more time for ever if needed. A timeout of 1 hour would not help.

**Comment by frankmorgner** [comment]
ISO 7816-3 (as well as ISO 14443) defines a *waiting time*. However, with a *waiting time extension*, this could indeed be extended to one hour. However, I'd like to point out that

1. The PC/SC forum could allow the application to configure a upper bound for the communication time 
2. `pcscd` could check whether the card/reader ignores the waiting time without sending a WTX. This should indicate a problem which allows killing the transaction.

**Comment by LudovicRousseau** [comment]
1. The PC/SC forum is dead. Do no expect any change in the PC/SC specification. Even if a change is accepted do not expect Microsoft to implement it in Windows.

2. If the reader does not enforce the timeouts defined by ISO 7816 then it is a bug in the reader. I do not know such readers.
If the card fails to ask for time extension then the reader will/should report an error and the PC/SC transmit will return with an error.

I can't say more without having a pcscd log trace with all the CCID exchanges.

**Comment by efferre79** [comment]
@dengert I have finally discovered what was working in the past, the software stack is the same, only the card was different, last year I changed the old card (that was working) with a new one because the old one expired. The new card doesn't work with the driver acr38u-1.7.11 I have been using up to today.

@LudovicRousseau Today I have found a more recent driver for the same reader from ACS. The package was not available for my distribution but I didn't know that. I have then removed the old binary-only driver acr38u-1.7.11 and installed the source-code-based driver acsccid-1.1.5 found on ACS website [here](https://www.acs.com.hk/download-driver-unified/9184/ACS-Unified-Driver-Lnx-Mac-115-P.zip). Its sources are also available on [github](https://github.com/acshk/acsccid) or [sourceforge](http://acsccid.sourceforge.net), it is a fork of ccid-1.4.28 package. Despite the name, it covers both CCID and non-CCID readers from ACS. Were you aware of that? As you are the main author of ccid, maybe it would be a good idea to contact ACS to merge their changes in the official ccid package. What do you think?

I have edited the title to describe properly the support request for future references.

Thanks to all for the help!!!

**Comment by martinpaljak** [comment]
IIRC ACS "CCID driver" also contained code for seriously non-CCID readers by the vendor.

**Comment by mouse07410** [comment]
I've had devil's luck trying to use an ACS card as PIV (with ACS reader, and with SCM reader). The only system it worked on was Windows with ACS proprietary drivers.

Ended up abandoning the idea, and getting a real PIV (which happened to work with SCM and other readers). Success on Linux, Mac, Windows.

**Comment by LudovicRousseau** [comment]
Yes I know this CCID driver fork. I sponsor its Debian package for example. https://packages.debian.org/sid/libacsccid1

No I do not plan to merge ACS patches. I am happy to let ACS maintain their own patches and provide support.
