### ISSUE TITLE
OpenPGP testing results (release testing 0.19)

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1475]
I am not sure, if this is the right way to do it. Please don't be mad at me. If I should handle this differently, please tell me.

I present my testing results of current master branch for release of 0.19. I will update the results after test accordingly, as I couldn't manage to test everything yet.

### Test Results OpenPGP Card (v2.1 and v3.3) and Gnuk (1.2.6)

* [x] PKCS#11
  * [x] pkcs11-tool 
    * Windows (pass, besides note 1)
    * Other Operating Systems (pass, besides note 1)
  * [x] Firefox
    * Load OpenSC PKCS#11 Module (pass, Gnuk not tested, see note 2)
    * PIN Verification (pass)
    * TLS Client Authentication (**won't test** for this time)
  * [x] OpenSSH
    * Without ssh-agent (pass, Gnuk not tested, see note 2)
    * With ssh-agent (**won't test** for this time)
* [x] Windows Minidriver
  * certutil -scinfo (pass for OPC, but not for Gnuk, see note 3)
  * Windows Login or Unlock (**won't test** for this time)
  * TLS Client Authentication with Internet Explorer, Edge or Chrome (**won't test** for this time)
  * Change PIN (pass for OPC, but not for Gnuk)
* [x] macOS Tokend
  * Keychain Access (pass, Gnuk login works, but no cert installed, see note 2)
  * TLS Client Authentication with Safari or Chrome (**won't test** for this time)

Notes:
1) Seems to work for every device except the fact that decryption does not work for AUT-slot on devcies other than OPC3.3 (see [here](https://gist.github.com/alex-nitrokey/8cffefb4ad161dfed0fa2cb79363a5c5)). This problem exists at least since version 0.17. The test-case needs to be changed eventually to not test AUT-slot for encryption on devices older than OpenPGP Card v3.3, because they are not able to perform this task. (see [this PR](https://github.com/OpenSC/OpenSC/pull/1446) for further detail of this topic)
2) Currently there are problems with Gnuk and Cardholder certificates. Fix for 0.19 is unlikely, therefore no tests where done (see #1282)
3) certutil fails with ```Cannot retrieve Provider Name for SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)```

**Comment by frankmorgner** [comment]
It's just fine.

Please check if the certutil problem is fixed with https://github.com/OpenSC/OpenSC/commit/ad47cb4afca2d756d2151fa4efa05b1d9545d937

The rest looks OK, I think.

**Comment by alex-nitrokey** [comment]
> Please check if the certutil problem is fixed with ad47cb4

This indeed fixes the problem for OPC3.3. Unfortunately, it does not fix the issue with Gnuk. I actually have an different ATR anyway. As I mentioned in #1282 I think that the Gnuk is not identified correctly, presumably because of a firmware update. I just hadn't time to track it down yet.

The ATR which is shown for my Gnuk device (firmware 1.2.6) is
```
{TEXT("Gnuk v1.0.x (OpenPGP v2.0)"), {0x3b,0xda,0x11,0xff,0x81,0xb1,0xfe,0x55,0x1f,0x03,0x00,0x31,0x84,0x73,0x80,0x01,0x80,0x05,0x90,0x00,0xe1},
```
It differs in the last part (e1 instead of e4) and the forth-last (05 instead of 00).

**Comment by frankmorgner** [comment]
shouldn't this be the [nitrokey](https://smartcard-atr.appspot.com/parse?ATR=3bda11ff81b1fe551f0300318473800180059000e1)? Anyway, I've pushed 7dff82bc4893cd613a8d27e246fbcec18e89898d, which should catch your token.

**Comment by frankmorgner** [comment]
It would be nice to see a specification how the ATR of the GNUK/Nitrokey changes with firmware updates...

**Comment by alex-nitrokey** [comment]
> shouldn't this be the nitrokey?

Yes, the Nitrokey Start is bascially a Gnuk, which act like an OpenPGP Card, but is implemented in Software. Therefore handling it as a Gnuk device is just fine, thank for the commit.

> It would be nice to see a specification how the ATR of the GNUK/Nitrokey changes with firmware updates...

I plan to have a deeper look into the specifics and if this actually changed with firmware or what else happened and try to react/contribute accordingly.
