### ISSUE TITLE
Missing documentation: Load PKCS module into Firefox 63 

### ISSUE THREAD

**Issue by MHacker9404** [OpenSC/OpenSC#1482]
Followed the steps in the wiki - file location is under Program Files (x86).  Get message unable to load module.

**Comment by frankmorgner** [comment]
Isn't the new firefox a x64 application? If so, you need to load it from Program Files. Please update the wiki!

**Comment by jariq** [comment]
Seems to be related: https://stackoverflow.com/questions/52550385/firefox-quantum-esr-pkcs11-how-to-load-via-script-or-configuration-settings

**Comment by frankmorgner** [comment]
pkcs11-register will do this automatically for 0.20.0
