### ISSUE TITLE
Issue while creating a data object in the SmartCard from a hex string 

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1493]
Hi, 

I have a hex string (64 bytes char buffer), that I want to store in the SmartCard HSM.  

I am trying the following - 
- Create a data object using C_CreateObject with the contents being the contents of the buffer. This seems OKAY and the data object is created. 
- Now when I do a C_GetAttributeValue to make sure the value is the same as the buffer I tried to store, it was not the same. 

This is what I try to store - 
173cc5257942e19ac366e99a59d4aded9021e818c964edcbd92ab73ac649a61b

This is what C_GetAttributeValue shows after C_CreateObject. 
3137336363353235373934326531396163333636653939613539643461646564

Am I expecting something incorrect ? 

How can I do what I want to accomplish using the SmartCard HSM ?

Thank you for your help. 

P.S: I can paste code if needed.

**Comment by dengert** [comment]
More than a transformation, both strings are length 64.  I would look at the Smartcard HSM  and see what is written to the card and what is read from the card. An opensc-debug.log should show something. look for the length.

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
There is no transformation in the process. We store binary data as passed in CKA_VALUE in C_CreateObject. I suspect, that this is a problem in the client application.

**Comment by RohanKurane** [comment]
Thanks @CardContact 

Let me take a look and get back to you.

**Comment by RohanKurane** [comment]
You're right @CardContact . 
It is indeed the Hex conversion of the original buffer. My application converts it to ascii before I printed the old before which I why we see one in Ascii and the new in Hex.

The hex is what I want anyways.
