### ISSUE TITLE
CKM_MD5_RSA_PKCS no longer supported by OpenSC for verification 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#1497]
Recent changes in `pkcs11/openssl.c` for PSS no longer supports CKM_MD5_RSA_PKCS  when used from `C_Verify* ` routines. `pkcs11-tool`  tries to test it and  `framework-pkc15.c ` registers:
```
rc = sc_pkcs11_register_sign_and_hash_mechanism(p11card, CKM_MD5_RSA_PKCS, CKM_MD5, mt);
rc = sc_pkcs11_register_sign_and_hash_mechanism(p11card, CKM_RIPEMD160_RSA_PKCS, CKM_RIPEMD160, mt);
```

MD5 is supported as a digest and with signatures, just not for verify. 

### Proposed Resolution

Either drop MD5 support, live with the error or add support for all the MD5 mechanisms. 

### Steps to reproduce
With current master: a8db9cb4f03e112ceb9d69557b18567ef578aad7 run 
```
pkcs11-tool --test --login
...
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS:   ERR: C_Verify() returned CKR_ARGUMENTS_BAD (0x7)
...
```

Problem appears to be in `pkcs11/openssl.c`  where only 2 old mechanisms and the new PSS mechanisms are supported:
 
```
479                 switch (mech->mechanism) {
480                 case CKM_RSA_PKCS:
481                         pad = RSA_PKCS1_PADDING;
482                         break;
483                 case CKM_RSA_X_509:
484                         pad = RSA_NO_PADDING;
485                         break;
486                 case CKM_RSA_PKCS_PSS:
487                 case CKM_SHA1_RSA_PKCS_PSS:
488                 case CKM_SHA224_RSA_PKCS_PSS:
489                 case CKM_SHA256_RSA_PKCS_PSS:
490                 case CKM_SHA384_RSA_PKCS_PSS:
491                 case CKM_SHA512_RSA_PKCS_PSS:
492                         pad = RSA_NO_PADDING;
493                         break;
494                 default:
495                         EVP_PKEY_free(pkey);
496                         return CKR_ARGUMENTS_BAD;
```
gdb shows that line 496 is executed. 

There may be a problem around line 451 as well as the logic now only supports selected digests. 

Looks like `CKM_RIPEMD160_RSA_PKCS` would have the same problem.

**Comment by frankmorgner** [comment]
These lines haven't been edited since 3 years... Maybe @Jakuje could look into this.

**Comment by dengert** [comment]
Original code was was written in 2015, but only committed to master 2018-09-30  `gitk` shows for e5707b545e5a2dc33b0ca52a8bf63f36f71b3d85 in #1435
```
Author: Nicholas Wilson <nicholas.wilson@realvnc.com>  2015-08-25 06:45:27
Committer: Frank Morgner <frankmorgner@gmail.com>  2018-09-30 14:23:27
Parent: be2cc38565c040af0a36b671d59877984678aa19 (p11test: Add missing CKM_SHA224_RSA_PKCS_PSS)
Child:  9a853176b8d74e88d6ebef069b7e70f4ae4d6130 (pkcs11-tool: Support for signature verification)
Branches: master, piv-realloc-buf-3, remotes/origin/master, remotes/upstream/master
Follows: 0.19.0
Precedes: 
```

This patch [pkcs11/openssl.c.diff.txt](https://github.com/OpenSC/OpenSC/files/2456082/openssl.c.diff.txt)
This appears to fix the problem I see, but may not be complete.

**Comment by Jakuje** [comment]
The patch looks correct. The verification was quite limited initially and hard to test since it was not even exposed on the `pkcs11-tool`. Thank you for catching the missing hash algorithms. If it would be on me, I would advocate removing the `CKM_RIPEMD160_RSA_PKCS` and keeping the SHA1 since that still might be used for some time.

**Comment by dengert** [comment]
Even if a mechanism is not used for signatures the routine is for verify and using OpenSSL to do it. (User may be testing old old signature.)

OpenSC still supports CKM_RIPEMD160_RSA_PKCS and I believe OpenSSL does too.
I would argue, the code should accept all PKCS\#11 mechanisms and only handle cases that need special handling like PSS and pass all others to OpenSSL which can still return an error if it can not handle a mechanism. 

But is short term, the patch solved the problem where pkcs11-tool was testing  CKM_MD5_RSA_PKCS verify.

**Comment by frankmorgner** [comment]
@dengert would you care to make a pull request?
