### ISSUE TITLE
Floating-point division by zero in SimCList

### ISSUE THREAD

**Issue by vvp2014** [OpenSC/OpenSC#1509]
SimCList implements `list_append()` through the use of `list_findpos()` where (see `src/common/simclist.c:422`) it performs division by zero whenever a new item is appended to an empty list.

Being a floating-point division by zero, it does not raise an SIGFPE unless the process is set up for that specifically. Please consider the following example (it is the file `samples/ex1.c` from the latest distribution of SimCList with all but two lines added):

```
#include <stdio.h>

#include <fenv.h>

#include <simclist.h>   /* use the SimCList library */


int main() {
    list_t mylist;      /* declare a list */
    int userval;

    feenableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);

    list_init(& mylist);    /* initialize the list */

    printf("Insert your number: ");
    scanf("%d", & userval);

    list_append(& mylist, & userval);       /* add an element to the list */
    
    printf("The list now holds %u elements.\n", \
            list_size(& mylist));           /* get the size of the list */

    printf("Your number was: %d\n", \
            * (int*)list_get_at(& mylist, 0));  /* extract the first element of the list */

    list_destroy(&mylist);
    
    return 0;
}
```

Please copy this code into an OpenSC's source tree as `src/common/ex1.c` and compile it as follows
(having `src/common` as your current working directory):
```
cc -D_GNU_SOURCE -I . -o ex1 ex1.c simclist.c -lm
```
then execute the example:
```
user@host> ./ex1
Insert your number: 1
Floating point exception
```

I practice, the issue described above causes the process to dump core whenever OpenSC attempts to add the first reader to the list of readers, _when_ the process has SIGFPE handling set up as described above, otherwise `list_append()` works by a chance.

I notified mij, the author of SimCList, regarding that issue.

**Comment by vvp2014** [comment]
I noted that the issue remains unresolved for several years and the Web site of SimCList does not seem to be actively maintained.

To resolve the issue, please replace the line `422` of `src/common/simclist.c` with
```
    x = l->numels ? (float)(posstart+1) / l->numels : 0;
```

Thank you.

**Comment by vvp2014** [comment]
I cannot really recall when, but my teacher told me that division by zero is a big no-no. Especially when counting real things (contiguous regions of computer memory,  smart card readers, people, cats and dogs). Checking the denominator in the same expression where the division happens makes code compact and readable.  Having the same number of lines before/after the fix is good. Immediately seeing that the first branch is taken when the list is empty makes less reading&mdash;busy people like that.

The rest is negligible.  A USB hub serves 127 devices (that is in theory, power consumption aside). The length of the list changes when a device is attached or detached. Humans cannot attach/detach USB devices faster than maybe twice a second. pcsclite is slow. Therefore, readability and predictability are very much more important in this case while performance, code paths, etc. are not.

Having linked lists (esp. implemented *this* way) instead of a static array of pointers to reader structures (1K of RAM per maximal capacity of a hub), lsearch(3), and trivial bounds checking is beyond me.

**Comment by dengert** [comment]
Submit a PR.

**Comment by vvp2014** [comment]
Thank you.
