### ISSUE TITLE
OpenSC formatted Starcos 2.3 smartcard cannot be initialized

### ISSUE THREAD

**Issue by arges** [OpenSC/OpenSC#151]
I've reported a regression against Ubuntu, but this bug is also present with
e8eb4cd7ed230aff08e4bb1c777f3d6d0c3fe24a.

The issue copied here is:
* What happened
Erasing and initializing a Starcos 2.3 smartcard returns the error:
Error -1211: Security status not satisfied

* Test case
$ pkcs15-init -E
$ pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 0000 --puk 111111 --label "Test"

I've bisected the issue with the OpenSC git project and found that the first bad commit is:
1d82e8ababab85480aeffb955cad27267a938883

Here is a link to the Launchpad bug:
https://bugs.launchpad.net/ubuntu/+source/opensc/+bug/1166500

pscs_scan output will be attached to the Launchpad bug.

Thanks,
--chris j arges

**Comment by frankmorgner** [comment]
Please re-open the issue if it is still relevant or if you have news about possible fixes.
