### ISSUE TITLE
GPL x LGPL licensing issue

### ISSUE THREAD

**Issue by stanislav-brabec** [OpenSC/OpenSC#1527]
### Problem Description
OpenSC is declared as LGPL 2.1 or later

But following files declare GPL (without version specification), which is more strict than GPL:
    opensc-0.19.0/src/tools/egk-tool-cmdline.c
    opensc-0.19.0/src/tools/npa-tool-cmdline.c
    opensc-0.19.0/src/tools/opensc-asn1-cmdline.c
    opensc-0.19.0/src/tools/opensc-notify-cmdline.c

I think that the claim is incorrect. The comment explicitly says that the code was copied from glibc-2.3.6. Looking at original glibc-2.3.6/posix/getopt.c, I see LGPL 2.1 or later there.

### Proposed Resolution
If the comment is correct, and author of OpenSC modification agrees with the license change, I propose to change:
`Licensed under the GPL as per the whole glibc source tree.`
to
`Licensed under the LGPL 2.1 or later as per the whole glibc source tree.`

### Steps to reproduce
Read openSUSE Licensedigger results at [https://build.opensuse.org/request/show/638216](https://build.opensuse.org/request/show/638216)

### Logs
N/A

**Comment by frankmorgner** [comment]
Those files are generated with [`gengetopt`](http://savannah.gnu.org/projects/gengetopt). I think this is caused by `gengetopt --include-getopt` and [*should not* generate neither GPL nor LGPL code](https://www.gnu.org/software/gengetopt/gengetopt.html#Copying):

>The code that Gengetopt generates is also free software; however it is licensed with a simple all-permissive license instead of the GPL or LGPL. You are free to do anything you like with the generated code, including incorporating it into or linking it with proprietary software.

Could you post your question at the gengetopt support?

**Comment by stanislav-brabec** [comment]
Posted to the gengetopt bug tracker [https://savannah.gnu.org/bugs/index.php?54996](url)
Feel free to perform the license fix in your code. I am afraid that gengetopt is a dead project, as the last change is 6 years old and nobody responds to bugs.
