### ISSUE TITLE
Wiki points to a domain seemingly owned by someone else

### ISSUE THREAD

**Issue by v6ak** [OpenSC/OpenSC#1530]
### Problem Description

The domain opensc-project.org seems to have been taken over by someone else. However, I have found some links at https://github.com/OpenSC/OpenSC/wiki/Quick-Start-with-OpenSC . On this specific page, I have removed all the links to this domain. 

### Proposed Resolution

* [ ] Add correct links on https://github.com/OpenSC/OpenSC/wiki/Quick-Start-with-OpenSC .
* [ ] Check other pages for bad links.

### Steps to reproduce

N/A

### Logs

N/A

**Comment by frankmorgner** [comment]
please edit the page accordingly, it's a wiki!

**Comment by v6ak** [comment]
I hope I will have a time for that. For now, I have just applied the first aid (removal of links to someone else's server). The page not looks poorer, but those links did not work anyway.

**Comment by Jakuje** [comment]
There will be more issues like that in other wiki pages, fortunately the search works: 

https://github.com/OpenSC/OpenSC/search?q=%22opensc-project.org%22&unscoped_q=%22opensc-project.org%22&type=Wikis

But the referenced website is gone for years and there is no replacement, better than the the Wiki here (which should have most of the content migrated from that site), other links should point to other related projects under the OpenSC organization on GitHub.

I added back the links to respective github repositories to the page https://github.com/OpenSC/OpenSC/wiki/Quick-Start-with-OpenSC  but there are still the others to work on.

**Comment by Jakuje** [comment]
I cleaned up few more pages, but the rest is mostly unused old pages of unclear value.
