### ISSUE TITLE
pkcs15-tool doesn't work with recent portuguese eID card

### ISSUE THREAD

**Issue by nfgb** [OpenSC/OpenSC#1546]
### Problem Description
pkcs15-tool doesn't work with recent portuguese eID cards. 
I've tested with card issued in 2014 and it works ok.
On a 2018 id card this is the output of pkcs15-tool --dump --short:
"Failed to connect to card: Card is invalid or cannot be handled"

### Steps to reproduce
pkcs15-tool --dump --short

**Comment by frankmorgner** [comment]
If you're planning to make a contribution to the project, we'd love to add a new card to OpenSC. We would be happy to get you going and to comment on your code. However, please have in mind that in lack of hardware, documentation and manpower, we can't do this on our own.

**Comment by frankmorgner** [comment]
please run `pkcs15-tool --dump --short -vvv` with both, the new and the old card. Maybe it's as simple as registering the new card somewhere. Note that your certificates may be contained in the log...

**Comment by nfgb** [comment]
Hi,
Sorry for the delay.
I'm not sure which information is relevant and which is private (and should not be posted).
The one thing I've noticed when comparing both logs is the following lines on the new card:
...
«trying driver 'trying driver 'gemsafeV1'» ...
...
«trying driver 'default'»..
«Failed to connect to card: Card is invalid or cannot be handled»..

Apparently it tries all the drivers and all fail. But the card is valid (it works with the official software). 

 On the old card it matches gemsafeV1 driver:
«trying driver 'gemsafeV1'» ...
«matched: Gemalto GemSafe V1 applet»

**Comment by frankmorgner** [comment]
the requested output is still missing.

please do the following:
1. run opensc-tool -a
2. use the output (ATR) to configure your card for the gemsafe driver in opensc.conf: 
```
app default {
	card_atr OUTPUT_ATR {
		name = "recent portuguese eID card ";
		driver = "gemsafeV1";
	}
}
```
Given the card's behavior didn't change, this should select the correct driver.

**Comment by nfgb** [comment]
Hi,

Still the same behavior with pkcs15-tool after changing the opensc.conf (and opensc-tool -a no longer works after the change: "Failed to connect to card: Card is invalid or cannot be handled").
I don't know if it is relevant but the output is already on the source code OpenSC/src/libopensc/card-gemsafeV1.c on line 65: 
{"3B:FF:96:00:00:81:31:FE:43:80:31:80:65:B0:85:04:01:20:12:0F:FF:82:90:00:D0"

**Comment by frankmorgner** [comment]
OK, thanks for looking into this. Then you should finally run `pkcs15-tool --dump --short -vvv`, which will print a more detailed error message.

**Comment by nfgb** [comment]
Here is the output:

P:6952; T:6912 2019-07-02 14:51:51.059 [pkcs15-tool] sc.c:275:sc_detect_card_presence: called
P:6952; T:6912 2019-07-02 14:51:51.060 [pkcs15-tool] reader-pcsc.c:412:pcsc_detect_card_presence: called
P:6952; T:6912 2019-07-02 14:51:51.063 Lenovo Lenovo USB Smartcard Keyboard 0 check
P:6952; T:6912 2019-07-02 14:51:51.065 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
P:6952; T:6912 2019-07-02 14:51:51.065 [pkcs15-tool] reader-pcsc.c:417:pcsc_detect_card_presence: returning with: 1
P:6952; T:6912 2019-07-02 14:51:51.065 [pkcs15-tool] sc.c:280:sc_detect_card_presence: returning with: 1
Connecting to card in reader Lenovo Lenovo USB Smartcard Keyboard 0...
P:6952; T:6912 2019-07-02 14:51:51.067 [pkcs15-tool] card.c:196:sc_connect_card: called
P:6952; T:6912 2019-07-02 14:51:51.068 [pkcs15-tool] reader-pcsc.c:534:pcsc_connect: called
P:6952; T:6912 2019-07-02 14:51:51.068 Lenovo Lenovo USB Smartcard Keyboard 0 check
P:6952; T:6912 2019-07-02 14:51:51.069 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
P:6952; T:6912 2019-07-02 14:51:51.070 Initial protocol: T=1
P:6952; T:6912 2019-07-02 14:51:51.070 ATR     : 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00:d0
P:6952; T:6912 2019-07-02 14:51:51.075 ATR try : 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00:d0
P:6952; T:6912 2019-07-02 14:51:51.076 matching configured ATRs
P:6952; T:6912 2019-07-02 14:51:51.078 trying driver 'gemsafeV1'
P:6952; T:6912 2019-07-02 14:51:51.078 ATR     : 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00:d0
P:6952; T:6912 2019-07-02 14:51:51.079 ATR try : 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00:d0
P:6952; T:6912 2019-07-02 14:51:51.080 matched driver 'Gemalto GemSafe V1 applet'
P:6952; T:6912 2019-07-02 14:51:51.080 ATR     : 3b:ff:96:00:00:81:31:fe:43:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00:d0
P:6952; T:6912 2019-07-02 14:51:51.082 ATR try : 3B:7B:94:00:00:80:65:B0:83:01:01:74:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.082 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.083 ATR try : 3B:6B:00:00:80:65:B0:83:01:01:74:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.087 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.088 ATR try : 3b:6d:00:00:80:31:80:65:b0:83:01:02:90:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.091 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.092 ATR try : 3B:6B:00:00:80:65:B0:83:01:03:74:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.092 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.093 ATR try : 3B:7A:94:00:00:80:65:A2:01:01:01:3D:72:D6:43
P:6952; T:6912 2019-07-02 14:51:51.094 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.097 ATR try : 3B:7D:94:00:00:80:31:80:65:B0:83:01:01:90:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.099 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.101 ATR try : 3B:7D:96:00:00:80:31:80:65:B0:83:11:48:C8:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.101 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.102 ATR try : 3B:7D:95:00:00:80:31:80:65:B0:83:11:C0:A9:83:00
P:6952; T:6912 2019-07-02 14:51:51.103 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.103 ATR try : 3B:7D:95:00:00:80:31:80:65:B0:83:11:C0:A9:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.103 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.104 ATR try : 3B:7D:95:00:00:80:31:80:65:B0:83:11:00:C8:83:00
P:6952; T:6912 2019-07-02 14:51:51.105 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.106 ATR try : 3B:7D:95:00:00:80:31:80:65:B0:83:11:00:C8:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.110 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.112 ATR try : 3B:7D:96:00:00:80:31:80:65:B0:83:11:00:C8:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.113 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.115 ATR try : 3b:7d:96:00:00:80:31:80:65:b0:83:02:01:f3:83:00:90:00
P:6952; T:6912 2019-07-02 14:51:51.116 ignored - wrong length
P:6952; T:6912 2019-07-02 14:51:51.116 driver 'Gemalto GemSafe V1 applet' match_card() failed: Success (will continue anyway)
P:6952; T:6912 2019-07-02 14:51:51.117 [pkcs15-tool] card-gemsafeV1.c:162:gemsafe_init: called
P:6952; T:6912 2019-07-02 14:51:51.122 [pkcs15-tool] card-gemsafeV1.c:127:gp_select_applet: called
P:6952; T:6912 2019-07-02 14:51:51.122 [pkcs15-tool] apdu.c:554:sc_transmit_apdu: called
P:6952; T:6912 2019-07-02 14:51:51.123 [pkcs15-tool] card.c:415:sc_lock: called
P:6952; T:6912 2019-07-02 14:51:51.123 [pkcs15-tool] card.c:455:sc_lock: returning with: 0 (Success)
P:6952; T:6912 2019-07-02 14:51:51.124 [pkcs15-tool] apdu.c:521:sc_transmit: called
P:6952; T:6912 2019-07-02 14:51:51.125 [pkcs15-tool] apdu.c:371:sc_single_transmit: called
P:6952; T:6912 2019-07-02 14:51:51.125 CLA:0, INS:A4, P1:4, P2:0, data(16) 000001EAF954BC50
P:6952; T:6912 2019-07-02 14:51:51.125 reader 'Lenovo Lenovo USB Smartcard Keyboard 0'
P:6952; T:6912 2019-07-02 14:51:51.127 [pkcs15-tool] reader-pcsc.c:285:pcsc_transmit:
Outgoing APDU (22 bytes):
00 A4 04 00 10 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00                               ......
P:6952; T:6912 2019-07-02 14:51:51.127 [pkcs15-tool] reader-pcsc.c:213:pcsc_internal_transmit: called
P:6952; T:6912 2019-07-02 14:51:51.132 [pkcs15-tool] reader-pcsc.c:294:pcsc_transmit:
Incoming APDU (2 bytes):
6A 82 j.
P:6952; T:6912 2019-07-02 14:51:51.134 [pkcs15-tool] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
P:6952; T:6912 2019-07-02 14:51:51.136 [pkcs15-tool] apdu.c:543:sc_transmit: returning with: 0 (Success)
P:6952; T:6912 2019-07-02 14:51:51.137 [pkcs15-tool] card.c:465:sc_unlock: called
P:6952; T:6912 2019-07-02 14:51:51.138 File or application not found
P:6952; T:6912 2019-07-02 14:51:51.139 [pkcs15-tool] card-gemsafeV1.c:141:gp_select_applet: returning with: -1201 (File not found)
P:6952; T:6912 2019-07-02 14:51:51.140 applet selection failed
P:6952; T:6912 2019-07-02 14:51:51.141 driver 'Gemalto GemSafe V1 applet' init() failed: Card is invalid or cannot be handled
P:6952; T:6912 2019-07-02 14:51:51.142 Lenovo Lenovo USB Smartcard Keyboard 0:SCardDisconnect returned: 0x00000000
P:6952; T:6912 2019-07-02 14:51:51.142 [pkcs15-tool] card.c:345:sc_connect_card: returning with: -1210 (Card is invalid or cannot be handled)
Failed to connect to card: Card is invalid or cannot be handled
P:6952; T:6912 2019-07-02 14:51:51.146 [pkcs15-tool] ctx.c:906:sc_release_context: called
P:6952; T:6912 2019-07-02 14:51:51.150 [pkcs15-tool] reader-pcsc.c:900:pcsc_finish: called

**Comment by dengert** [comment]
`git blame card-gemsafeV1.c`  shows line 65 was added by  e3ff3be4f 

It looks like its match routine accepts the card, but then gemsafe_init() does a SELECT AID using  `gemsafe_pteid_aid` in line 193:
```
00 A4 04 00 10 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00
```
which fails:
`P:6952; T:6912 2019-07-02 14:51:51.141 driver 'Gemalto GemSafe V1 applet' init() failed: Card is invalid or cannot be handled`

The AID looks wrong. 
If the card is really SC_CARD_TYPE_GEMSAFEV1_PTEID the AID should have been set from: 
`static const u8 gemsafe_pteid_aid[] = {0x60, 0x46, 0x32, 0xFF, 0x00, 0x00, 0x02};` in lines 181-182

What version of OpenSC are you using? Can you build from git clone?

**Comment by dengert** [comment]
With Frank's opensc.conf from above  and your current version of the OpenSC code you try adding `type = "21002";`  (with  OUTPUT_ATR set to your ATR.)  21002 is  `SC_CARD_TYPE_GEMSAFEV1_PTEID`

Without the type, looks like the the old code defaults to using 16 bytes of zeros as AID.

OUTPUT_ATR set to your ATR. 
```
app default {
	card_atr  OUTPUT_ATR  {
		name = "recent portuguese eID card ";
		driver = "gemsafeV1";
                type = "21002";
 
 	}
}
```

None of the above would be needed with code in git master.

**Comment by nfgb** [comment]
I'm using the latest realease: OpenSC-0.19.0. I've looked at the wiki and I doubt if I've the skills or tools to build it from git in Windows (where I need it).

**Comment by dengert** [comment]
Then try the `type = "21002";` from above with your current version. No code changes, just opensc.conf

**Comment by nfgb** [comment]
Sorry its working after all with the recent card. 
However I've tried with a 3rd card (with and an age between the two other cards) and I get the error above.

I added another line in the conf with the new ATR and it worked. I wonder how many ATR are there... 

Thank you all

**Comment by nata1i-e** [comment]
Hello, I have the same problem with new belgium eID, could you please help me read it?

opensc-tool --atr
Using reader with a card: ACS ACR 38U-CCID 00 00
3b:7f:96:00:00:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00

this type de card is unknown even in the most recent driver:
opensc-tool -n -v
Using reader with a card: ACS ACR 38U-CCID 00 00
Connecting to card in reader ACS ACR 38U-CCID 00 00...
Using card driver Default driver for unknown cards.
Card name: Unsupported card

pkcs15-tool --dump --short -vvv > out
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] sc.c:275:sc_detect_card_presence: called
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:412:pcsc_detect_card_presence: called
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:320:refresh_attributes: Alcor Micro AU9560 00 00 check
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:417:pcsc_detect_card_presence: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] sc.c:280:sc_detect_card_presence: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] sc.c:275:sc_detect_card_presence: called
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:412:pcsc_detect_card_presence: called
0x7f729847e1c0 11:50:16.875 [pkcs15-tool] reader-pcsc.c:320:refresh_attributes: ACS ACR 38U-CCID 01 00 check
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:417:pcsc_detect_card_presence: returning with: 1
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] sc.c:280:sc_detect_card_presence: returning with: 1
Using reader with a card: ACS ACR 38U-CCID 01 00
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] sc.c:275:sc_detect_card_presence: called
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:412:pcsc_detect_card_presence: called
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:320:refresh_attributes: ACS ACR 38U-CCID 01 00 check
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:417:pcsc_detect_card_presence: returning with: 1
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] sc.c:280:sc_detect_card_presence: returning with: 1
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:196:sc_connect_card: called
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:534:pcsc_connect: called
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:320:refresh_attributes: ACS ACR 38U-CCID 01 00 check
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:340:refresh_attributes: returning with: 0 (Success)
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] reader-pcsc.c:566:pcsc_connect: Initial protocol: T=0
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:221:sc_connect_card: matching configured ATRs
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:265:sc_connect_card: matching built-in ATRs
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:283:sc_connect_card: trying driver 'cardos'

than 
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:1088:match_atr_table: ATR     : 3b:7f:96:00:00:80:31:80:65:b0:85:04:01:20:12:0f:ff:82:90:00
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:1099:match_atr_table: ATR try : 3b:e2:00:ff:c1:10:31:fe:55:c8:02:9c
0x7f729847e1c0 11:50:16.876 [pkcs15-tool] card.c:1102:match_atr_table: ignored - wrong length

it looks ATR we seeking is not defined yet :(
Could you please help to solve the problem?

Thank you in advice,
Natalie

**Comment by dengert** [comment]
https://smartcard-atr.apdu.fr/ with your ATR says:
```
Belgian eID v1.8 (eID)

https://github.com/Fedict/eid-mw
```
https://github.com/Fedict  looks like is official Belgian open source implementation
with instructions on how to build on Windows, Linus and MacOS.
You could use it.

Or try and force the driver:  `OPENSC_DRIVER=belpic     pkcs15-tool --dump --short -vvv > out`  to see if adding the ATR to `card-belpic.c` would work. Most likely the card has new features, so may need more work.

**Comment by nata1i-e** [comment]
thank you for reply,
the problem is official Belgian open source implementation supports 2 last debian releases only,
eid-mv uses libs which are not back compatible :(

**Comment by tasism** [comment]
Hi @nata1i-e did you figure out how to solve this? Thanks a lot
