### ISSUE TITLE
openpgp: pkcs11-tool --test feature not working

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1551]
### Problem Description

`pkcs11-tool --login --test` fails to test decryption of OpenPGP Card (at least v2.1 and 3.3). Does anybody see why?
```
$ pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "User PIN (OpenPGP card)".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (Encryption key)  -- can't be used for signature, skipping
  testing key 1 (Authentication key)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
  testing key 1 (2048 bits, label=Authentication key) with 1 signature mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (Encryption key) -- can't be used to sign/verify, skipping
  testing key 1 (Authentication key) with 1 mechanism
    RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (Encryption key)
    RSA-PKCS: Encryption failed, returning
  testing key 1 (Authentication key)
    RSA-PKCS: Encryption failed, returning
No errors
```
### Proposed Resolution
This seems to be kind of regression [somewhere between](https://github.com/OpenSC/OpenSC/compare/a5daaaf...ac276b1) a5daaaf (working) and ac276b1. I just couldn't find the reason. The test fails to encrypt so that the decryption doesn't even start.

### Steps to reproduce
Compile master and see yourself. Use a5daaaf or just v0.19.0 which works fine to compare the behaviour, too.

### Logs
* [how it looks like when it is working](https://gist.github.com/alex-nitrokey/f5f7035b63882b7e63194c94f5f721ae)
* [how it looks like now](https://gist.github.com/alex-nitrokey/80a60343eb77283cd4d1d515d8bc6a65)

**Comment by dengert** [comment]
https://github.com/OpenSC/OpenSC/commit/a5daaaff0c0de4e92f36c354bbbd151ee0ba698e
is for the piv-tool.c and has nothing to do with pkcs11-tool.c which is uses in your example.

**Comment by alex-nitrokey** [comment]
That's right. I didn't found out the actual commit that caused this yet, therefore I can only claim, that it is in between. I did not test every commit.

**Comment by Jakuje** [comment]
I think the fix to unbreak the OpenPGP signing in master is this:
```
diff --git a/src/libopensc/padding.c b/src/libopensc/padding.c
index 047b3bc8..57ad70f8 100644
--- a/src/libopensc/padding.c
+++ b/src/libopensc/padding.c
@@ -503,7 +503,7 @@ int sc_get_encoding_flags(sc_context_t *ctx,
 		/* A corner case - the card can partially do PKCS1, if we prepend the
 		 * DigestInfo bit it will do the rest. */
 		*sflags = SC_ALGORITHM_RSA_PAD_PKCS1 | SC_ALGORITHM_RSA_HASH_NONE;
-		*pflags = iflags & SC_ALGORITHM_RSA_HASHES;
+		*pflags = SC_ALGORITHM_RSA_PAD_NONE | (iflags & SC_ALGORITHM_RSA_HASHES);
 
 	} else if ((iflags & SC_ALGORITHM_AES) == SC_ALGORITHM_AES) { /* TODO: seems like this constant does not belong to the same set of flags used form asymmetric algos. Fix this! */
 		*sflags = 0;
```
But I would like to give it some more testing on Monday.

For the encryption, issue you see, according to the source code, it happens in the `EVP_PKEY_encrypt_old()` function, which is proably related to the OpenSSL Secure memory issue #1515.

But I just tested what the decryption does if I will give it some correctly encrypted data and it looks like there is some another issue with the APDU construction, which creates too long APDU (2k RSA key) for the short version and does not know how to chain it?
```
sec.c:43:sc_decipher: called
card-openpgp.c:2087:pgp_decipher: called
apdu.c:554:sc_transmit_apdu: called
apdu.c:261:sc_check_apdu: failed length check for short APDU
apdu.c:339:sc_check_apdu: Invalid Case 4 short APDU:
cse=04 cla=00 ins=2a p1=80 p2=86 *****lc=257***** le=256
resp=0x7fffc09ff110 resplen=512 data=0x5586e351afc0 datalen=257
card-openpgp.c:2141:pgp_decipher: APDU transmit failed: -1300 (Invalid arguments)
sec.c:47:sc_decipher: returning with: -1300 (Invalid arguments)
card.c:465:sc_unlock: called
pkcs15-sec.c:285:sc_pkcs15_decipher: use_key() failed: -1300 (Invalid arguments)
```

**Comment by Jakuje** [comment]
>  Is there an issue with both SC_ALGORITHM_RSA_RAW and SC_ALGORITHM_RSA_PAD_NONE being defined as 1?

Without explicit explanation what these flags mean it is hard to say. The original commit implementing the RSA-PSS had also this line (not sure why it did not land in the current master though):
```
#define SC_ALGORITHM_RSA_PAD_NONE	SC_ALGORITHM_RSA_RAW /* alias for RAW */
```
My understanding is that the `SC_ALGORITHM_RSA_PAD_NONE` is not supposed to be set for the card capabilities (before the PSS commit, it was zero, so setting it as capability did not make any sense), but says what padding should be used in the signing process. In this case, it would really be an alias (no padding == RAW RSA operation).

**Comment by dengert** [comment]
Actually this looks better:
```
diff --git a/src/libopensc/padding.c b/src/libopensc/padding.c
index 047b3bc..f33cee7 100644
--- a/src/libopensc/padding.c
+++ b/src/libopensc/padding.c
@@ -410,6 +410,9 @@ int sc_pkcs1_encode(sc_context_t *ctx, unsigned long flags,
 
        hash_algo = flags & SC_ALGORITHM_RSA_HASHES;
        pad_algo  = flags & SC_ALGORITHM_RSA_PADS;
+       if (pad_algo == 0)
+               pad_algo = SC_ALGORITHM_RSA_PAD_NONE;
+
        sc_log(ctx, "hash algorithm 0x%X, pad algorithm 0x%X", hash_algo, pad_algo);
 
        if ((pad_algo == SC_ALGORITHM_RSA_PAD_PKCS1 || pad_algo == SC_ALGORITHM_RSA_PAD_NONE) &&

**Comment by dengert** [comment]
In regard to the decipher failure -
The problem comes from `pgp_parse_hist_bytes` making the assumption:
```
703                 /* category indicator 0x00, 0x10 or 0x80 => compact TLV (ISO) */
```
But with a Yubico, the history bytes are "Yubikey" with a "Y" being the 0x59 as the category. So the parsing falls apart, and thing like `card->caps |= SC_CARD_CAP_APDU_EXT` are never set. 
ATR is :"3b:f8:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:34:d4"

```
Thread 1 "`pkcs11-tool" hit Breakpoint 2, pgp_parse_hist_bytes (card=0x66e3b0, ctlv=0x66c9ca "ubikey", <incomplete sequence \324>, 
    ctlv_len=4) at ../../../src/src/libopensc/card-openpgp.c:625
```

Got further after setting  `card->caps |= SC_CARD_CAP_APDU_EXT`  which used an extended APDU,  outgoing worked, but incoming was 258 bytes ending in `6581` 
Using `priv->ext_caps |= EXT_CAP_CHAINING;` also looked like it worked, but still got a `6581`

 `iso7816.c:128:iso7816_check_sw: Memory failure` So I may have a bad card

**Comment by Jakuje** [comment]
I tried to add the appropriate flags to my local OpenSC:
```
--- a/src/libopensc/card-openpgp.c
+++ b/src/libopensc/card-openpgp.c
@@ -625,6 +625,8 @@ pgp_parse_hist_bytes(sc_card_t *card, u8 *ctlv, size_t ctlv_len)
 	struct pgp_priv_data *priv = DRVDATA(card);
 	const u8 *ptr;
 
+	card->caps |= SC_CARD_CAP_APDU_EXT;
+	priv->ext_caps |= EXT_CAP_APDU_EXT | EXT_CAP_CHAINING;
 	/* IS07816-4 hist bytes: 3rd function table */
 	if ((ptr = sc_compacttlv_find_tag(ctlv, ctlv_len, 0x73, NULL)) != NULL) {
 		/* bit 0x40 in byte 3 of TL 0x73 means "extended Le/Lc" */
```
But I am getting a different error now:
```
iso7816.c:128:iso7816_check_sw: Conditions of use not satisfied
card-openpgp.c:2146:pgp_decipher: Card returned error: -1209 (Not allowed)
sec.c:47:sc_decipher: returning with: -1209 (Not allowed)
card.c:465:sc_unlock: called
pkcs15-sec.c:285:sc_pkcs15_decipher: use_key() failed: -1209 (Not allowed)
```
Let me know if there is something else I should try. My Yubkey 4 has the same ATR as yours.

**Comment by dengert** [comment]
I think the Yubico 4 may not be following all the OpenPGP standards and the driver may be reading or trying to read DOs that may not be correct. I don't use the OpenPGP applet, so don't look at the code very much.  

Also look at #1552. This or something similar could be the problem with the Yubico.

**Comment by Jakuje** [comment]
@dengert would you like to submit a PR fixing the signing and flags? Your solution is probably more elegant and better than fixing each and every case where we could count with the NONE value throughout the code.

**Comment by Jakuje** [comment]
@dengert to comment on your previous questions:

> If I read the following code in padding correct, it looks like if iflags & SC_ALGORITHM_RSA_PAD_PSS is true, padding will assume the card can do SC_ALGORITHM_RSA_RAW even if it can not? (not this issue but a different issue.)

You are probably right. All of the options should be in the bracket together and match only with the if the capability `SC_ALGORITHM_RSA_RAW` is there. Not sure how this slipped into the code, but I do not think this would cause any real-problems since the supported algorithms are already reported and this function is used only for the signature itself.

Anyway, I will submit a PR with the issues. Thank you for pointing that out.

**Comment by dengert** [comment]
Your patch looks good and thanks for writing it. 

But I suspect there are other issues. The openpgp driver does not do enough error checking assuming that a card is in full compliance of the OpenPGP specs and is provisioned correctly. Anyone can write a OpenPGP applet (I see about 6 on github) and anyone can force the openpgp driver to be selected, with any ATR. The ATR history checks do not go far enough. 

I have seen problems like this in PIV applets, that they only implement part of the specs and miss some important features needed in a multi-card environment or where the card has multiple applets. 

The openpgp driver depends on many DOs on the card that must be provisioned correctly. There may be problems in this area as well. 

I don't do anything with OpenPGP other then cards with both a PIV and OpenPGP applet. And then it is to make sure the PIV applet gets selected when needed.

**Comment by Jakuje** [comment]
ok, I do not have encryption key on my openpgp applet for whatever reason so what I saw was attempt to decrypt with the authentication key, which is fine that it does not work.

@alex-nitrokey Do the proposed changes in #1556 help to resolve your issue?

Or could it be related to the #1515 too? It looks like your pkcs11-tool is failing somewhere in the following code, after getting the CKA_PUBLIC_EXPONENT of the key and before asking for the CKA_VALUE:
https://github.com/OpenSC/OpenSC/blob/01287e393ebeed1db7ef2f45ee133b2cd3f069ae/src/tools/pkcs11-tool.c#L4499-L4530
Checking what is going on there with gdb would be helpful.

**Comment by alex-nitrokey** [comment]
> @alex-nitrokey Do the proposed changes in #1556 help to resolve your issue?

It does. Thanks.

> Or could it be related to the #1515 too?

I doubt it, as the OpenSSL version does not change for my system and I tried the two referenced commits. In any case, I indeed have the newest OpenSSL version installed (Arch Linux).

> ok, I do not have encryption key on my openpgp applet for whatever reason so what I saw was attempt to decrypt with the authentication key, which is fine that it does not work.

Iirc it should skip the test at all if there is no key, so I am not sure if this is true. It fails after testing the encryption key in your case. So either you have no key and it tests anyway or you have one and it fails. Or am I wrong?

**Comment by alex-nitrokey** [comment]
Works for OP (me), so should be fixed?!
