### ISSUE TITLE
openpgp: pkcs11-tool --test should not test to decrypt with slot 3 on OPC2

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1552]
Since v0.19.0 (afaik) the `pkcs11-tool --login --test` command tests the decryption of the authentication key (slot 3) as well. This is fine for OPC3 cards as we did [implement this new feature](https://github.com/OpenSC/OpenSC/pull/1446). The former OPC2 card still can only decrypt with the decryption key (slot 2).

I do not know how the tool is getting the information what should be tested. It would be good if it would only test slot 3 if a OPC3 is tested. How can I change the current behaviour?

**Comment by frankmorgner** [comment]
You should remove `SC_PKCS15_PRKEY_USAGE_DECRYPT` (i.e. `PGP_ENC_PRKEY_USAGE`) from this key:
https://github.com/OpenSC/OpenSC/blob/01287e393ebeed1db7ef2f45ee133b2cd3f069ae/src/libopensc/pkcs15-openpgp.c#L78-L99

**Comment by alex-nitrokey** [comment]
Okay, I see. We provide the authentication key with decryption properties a long time ago to use the cert stored in card for authentication to decryption as well (e.g. for S/MIME email encryption). This is a well documented workaround where the private key of auth slot is the same as the encryption slot. Thus, the tests are only working if you ensure this kind of setup.

I don't see any way to work around that without breaking the feature. Therefore, I am closing this now. I just need to keep this in mind when testing :wink:
