### ISSUE TITLE
Aventra MyEID: pkcs15-init --erase-card - Failed to erase card: Authentication method blocked

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1560]
### Problem Description

When attempting to erase a MyEID card, I am asked for the security officer PIN, which always fails:

    Little-Net:~ minfrin$ pkcs15-init --erase-card
    Using reader with a card: ACS ACR 38U-CCID
    PIN [Security Officer PIN] required.
    Please enter PIN [Security Officer PIN]: 
    Failed to erase card: Authentication method blocked

### Proposed Resolution

When attempting to erase a MyEID card, the erasure should succeed.

### Steps to reproduce

    pkcs15-init --erase-card
    pkcs15-init --create-pkcs15 --use-default-transport-keys --profile pkcs15+onepin --label "Mercury" --pin 1111 --puk 1111
    pkcs15-init --store-pin --auth-id 1 --label "Basic PIN"
    pkcs15-init --finalize

Enter the PIN incorrectly to block the card:

    pkcs11-tool --test --pin 0000

Using a raspberry pi (0.16.0-3+deb9u1), try and erase the card. This fails:

    pi@raspberrypi:~ $ pkcs15-init --erase-card
    Using reader with a card: ACS ACR 38U-CCID 00 00
    Failed to erase card: Security status not satisfied

Using opensc v0.19.0, try and erase the card. This time we're asked for the SO PIN:

    Little-Net:~ minfrin$ pkcs15-init --erase-card
    Using reader with a card: ACS ACR 38U-CCID
    PIN [Security Officer PIN] required.
    Please enter PIN [Security Officer PIN]: 
    Failed to erase card: Authentication method blocked

**Comment by minfrin** [comment]
From Aventra support:

You have to unblock your SO-PIN before erasing the card. You can do it like this:

pkcs15-tool --unblock-pin --auth-id ff
Using reader with a card: ACS ACR39U ICC Reader 01 00
Enter PUK [Security Officer PIN]: 
Enter new PIN [Security Officer PIN]: 
Enter new PIN again [Security Officer PIN]:

You can then erase the card:
pkcs15-init -E --so-pin <your new SO-PIN>

**Comment by frankmorgner** [comment]
Does this need to be integrated in some way? Would you care to make a PR?
