### ISSUE TITLE
Current master stopped working with openpgp driver

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1561]
### Problem Description

Attempts to access OpenPGP applet on Yubikey (4 and NEO) via OpenSC now fail.

This is what I expect (and get with `OpenSC-0.19.0-669-gbe801ffa, rev: be801ffa`):
```
$ OPENSC_DRIVER=openpgp pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico Yubikey NEO OTP+U2F+CCID
  token label        : User PIN (OpenPGP)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 2.0
  firmware version   : 2.0
  serial num         : 000xxxxxxxxxx
  pin min/max        : 6/127
Slot 1 (0x1): Yubico Yubikey NEO OTP+U2F+CCID
  token label        : User PIN (sig) (OpenPGP)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 2.0
  firmware version   : 2.0
  serial num         : 00xxxxxxxxx
  pin min/max        : 6/127
$ 
```
Below is what I'm getting with the current master.

### Proposed Resolution

Fix it?

### Steps to reproduce

```
$ OPENSC_DRIVER=openpgp pkcs11-tool -O
No slot with a token was found.
$ OPENSC_DRIVER=openpgp pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico Yubikey NEO OTP+U2F+CCID
  (empty)
$  pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico Yubikey NEO OTP+U2F+CCID
  token label        : xxxxxxx
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : xxxxxxx
  pin min/max        : 4/8
$ opensc-tool -D
Configured card drivers:
  PIV-II           Personal Identity Verification Card
  openpgp          OpenPGP card
  cac              Common Access Card (CAC)
  default          Default driver for unknown cards
$  gpg --card-status

Reader ...........: Yubico Yubikey NEO OTP U2F CCID
Application ID ...: D27600012401020000060xxxxxxxxxx0000
Version ..........: 2.0
Manufacturer .....: Yubico
Serial number ....: 038xxxxxxxxxx
. . . . .
```

**Comment by Jakuje** [comment]
Current master works for my yubikey just fine:
```
$ OPENSC_DRIVER=openpgp ./src/tools/pkcs11-tool --module ./src/pkcs11/.libs/opensc-pkcs11.so  -L
Available slots:
Slot 0 (0x0): Yubico Yubikey 4 OTP+U2F+CCID 00 00
  token label        : User PIN (OpenPGP)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 000606917085
  pin min/max        : 6/127
Slot 1 (0x1): Yubico Yubikey 4 OTP+U2F+CCID 00 00
  token label        : User PIN (sig) (OpenPGP)
  token manufacturer : Yubico
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 2.1
  firmware version   : 2.1
  serial num         : 000606917085
  pin min/max        : 6/127
```
Providing some logs when it fails for you would be helpful.

**Comment by marschap** [comment]
Owning a Yubikey NEO, I am suffering from this issue too.

After some tests, I found that the offending commit, that broke it for some Yubikeys, is 4d8b2c12 by Jakuje.

@Jakuje I consider commit 4d8b2c12 a rather blunt instrument to deal with some Yubikeys.
I'd rather revert it, as it breaks existing setups and replace it with a better solution that also solves your issues.

Feature detection  based on hist_bytes in the OpenPGP card driver works in two steps
1. The driver tries to parse the hist_bytes returned in the card's ATR.
   This is where Yubikeys fail to provide ISO conformant values, but instead tell their name & type.
   This is where you added the hard-coded capabilties for Yubikeys.
2. The driver parses "hist_bytes" DO 5F52, a DO required to exist by the OpenPGP card spec.
   In my Yubikeys this DO exists and contains sensible values, i.e. those really matching the card's capabilities.

Any feature detected in these steps is added to the capabilities.
This way the driver initialization tries to get as exactly as possible the capabilities the card supports.
Of course, hard coding capabilities that some cards do not support will break those cards.

I am relatively sure that your Yubikeys also contain correct values.
Can you provide me with two values to test my hypothesis?
1. the ATR as returned by `opensc-tool -a`
2. the contents of the "hist_bytes" DO 5F52 as returned by `echo "cat 5F52" | opensc-explorer`

Please don't be cross if I create a PR that reverts 4d8b2c12. 
With your information from above, I can then extend it / resp. create another one that also fixes your issues.

Best
Peter

**Comment by Jakuje** [comment]
@marschap thank you for having a look into that. I do not know a lot about openpgp cards so feel free to submit a revert my commit and add some better way how to improve the detection, if it is possible. I would be happy to test with my yubikey.

For some reason, my yubikey does not have the DO file (the reporters of #1551/#1552 had the same problem that the capabilities were not detected at all):
```
$ opensc-tool -a
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 00 00
3b:f8:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:34:d4
$ echo "cat 5F52" | opensc-explorer
OpenSC Explorer version 0.18.0
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 00 00
unable to select MF: File not found
```
Not sure if the version is going to help:
```
$ gpg2 --card-status 

Reader ...........: Yubico Yubikey 4 OTP U2F CCID 00 00
Application ID ...: D2760001240102010006069170850000
Version ..........: 2.1
Manufacturer .....: Yubico
```

**Comment by marschap** [comment]
@Jakuje thanks for the quick answer & the ATR.
Hmmm, for the contents of DO 5F52 I was relying on some newer `opensc-explorer` features not available in 0.18.0.  I think this is the reason for the error reported.
May I ask you to call `opensc-explorer` interactively and to the `cat 5F52` at `opensc-explorer`'s internal prompt? 

In addition, please also describe the issues you had and wanted to fix with your patch.

Thanks in advance
Peter

**Comment by Jakuje** [comment]
OK, I probably forgot to select the openpgp driver. Now I have some output:
```
$ OPENSC_DRIVER=openpgp ./src/tools/opensc-explorer 
OpenSC Explorer version 0.19.0
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 00 00
OpenSC [3F00]> cat 5F52
00000000: 00 73 00 00 80 05 90 00 .s......
OpenSC [3F00]> 
```
The issue that I tried to fix was that the APDU was failing when openpgp attempted to decrypt as described from the second part of the https://github.com/OpenSC/OpenSC/issues/1551#issuecomment-445502348 (using short APDU with 257 bytes) and missing capabilities in my yubikey (because of failed detection on the hist_bytes).

**Comment by mouse07410** [comment]
Among other things - @Jakuie tested with Yubikey 4 and OpenPGP applet 2.1, while my example was with NEO with applet 2.0. 

I fully concur with @marschap opinion, and second the proposal to revert the offending commit (besides, *my* Yubikey 4 and NEO work just fine without it).

**Comment by marschap** [comment]
@mouse07410 Would you be so kind to provide me with the following info for your Yubikeys:
*  the ATR as returned by `opensc-tool -a`
*  the contents of the "hist_bytes" DO 5F52 as returned by `echo "cat 5F52" | opensc-explorer`
   resp. the result of `cat 5F52` entered at `opensc-explorer`'s internal prompt
* the output of `gpg --card-status` [at least the first 5 lines]

I am trying to find patterns

Thanks
Peter

**Comment by mouse07410** [comment]
@marschap here's the stuff.

For NEO:
```
$ OPENSC_DRIVER=openpgp opensc-tool -a
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
3b:fc:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:4e:45:4f:72:33:e1
$ opensc-tool -a
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
3b:fc:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:4e:45:4f:72:33:e1
$ echo "cat 5F52" | opensc-explorer
OpenSC Explorer version 0.19.0
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
unable to select MF: File not found
$ echo "cat 5F52" | OPENSC_DRIVER=openpgp opensc-explorer
OpenSC Explorer version 0.19.0
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
OpenSC [3F00]> cat 5F52
00000000: 00 73 00 00 80 00 00 00 00 00 00 00 00 00 00 .s.............
OpenSC [3F00]> 
$ $ gpg --card-status

Reader ...........: Yubico Yubikey NEO OTP U2F CCID
Application ID ...: D2760001240102000006038xxxxx0000
Version ..........: 2.0
Manufacturer .....: Yubico
Serial number ....: 038xxxxx
Name of cardholder: <yeah, it's me>
. . . . .
```
Note that `opensc-explorer` talks to the **default** applet by default (which on the majority of the reasonable systems run by reasonable people is PIV ;), so if you want to talk to the OpenPGP applet (which is **not** selected by default) you need to either select it first, or force the driver via, e.g., `OPENSC_DRIVER=openpgp`.

Yubikey 4:
```
$ opensc-tool -a
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
3b:f8:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:34:d4
$ echo "cat 5F52" | opensc-explorer
OpenSC Explorer version 0.19.0
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
unable to select MF: File not found
$ echo "cat 5F52" | OPENSC_DRIVER=openpgp opensc-explorer
OpenSC Explorer version 0.19.0
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
OpenSC [3F00]> cat 5F52
00000000: 00 73 00 00 80 05 90 00 .s......
OpenSC [3F00]>

$ gpg --card-status

Reader ...........: Yubico Yubikey 4 OTP U2F CCID
Application ID ...: D2760001240102010006069xxxxx0000
Version ..........: 2.1
Manufacturer .....: Yubico
Serial number ....: 069xxxxx
Name of cardholder: <truly me>
. . . . .
```
Again, same observation about `opensc-explorer`. 

P.S. I personally think that hard-coding things, unless the card absolutely doesn't work without it, is a very bad idea. I strongly suggest reverting that commit (and making sure it won't rear its ugly head again).

**Comment by mouse07410** [comment]
@marschap I confirm that your #1562 fixes OpenPGP for NEO. 
```
Testing YubiKey Digital Signature in RSA-PKCS1 mode...
Signing...
OPENSC_DRIVER=openpgp openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:model=PKCS%2315%20emulated;manufacturer=Yubico;serial=0006038xxxxx;token=User%20PIN%20%28sig%29%20%28OpenPGP%29;id=%01;object=Signature%20key;type=private" -sha384 -sigopt rsa_padding_mode:pkcs1 -out t6400.dat.sighsmpkcs t6400.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for User PIN (sig) (OpenPGP):
YubiKey: OpenPGP signed OK in RSA-PKCS1 mode

Verifying signature using YubiKey...
OPENSC_DRIVER=openpgp ~/openssl-1.1/bin/openssl dgst -engine pkcs11 -keyform engine -verify "pkcs11:model=PKCS%2315%20emulated;manufacturer=Yubico;serial=0006038xxxxx;token=User%20PIN%20%28sig%29%20%28OpenPGP%29;id=%01;object=Signature%20key;type=public" -sha384 -sigopt rsa_padding_mode:pkcs1 -signature t6400.dat.sighsmpkcs t6400.dat
engine "pkcs11" set.
YubiKey: OpenPGP verified signature OK in RSA-PKCS1 mode
```

However, to my surprise, using OpenSSL with keys from the OpenPGP applet fails to do, e.g., RSA-PSS:
```
OPENSC_DRIVER=openpgp ~/openssl-1.1/bin/openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:model=PKCS%2315%20emulated;manufacturer=Yubico;serial=0006038xxxxx;token=User%20PIN%20%28sig%29%20%28OpenPGP%29;id=%01;object=Signature%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -out t6400.dat.sighsmpss t6400.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for User PIN (sig) (OpenPGP):
Error Signing Data
4571960768:error:8207A070:PKCS#11 module:pkcs11_private_encrypt:Mechanism invalid:p11_rsa.c:116:
```

With the same token using PIV applet, OpenSSL happily does RSA-PSS:
```
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out /tmp/derive.57559.text.sig /tmp/derive.57559.text
engine "pkcs11" set.
Enter PKCS#11 token PIN for XXXXXX:
Signature is stored in /tmp/derive.57559.text.sig

Verifying signature:
openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=public" -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature /tmp/derive.57559.text.sig  /tmp/derive.57559.text
engine "pkcs11" set.
Verified OK
```

**Comment by mouse07410** [comment]
#1562 fixes this issue.
