### ISSUE TITLE
Segmentation fault in PIV's piv_general_io

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1581]
### Problem Description

Fed with the following test data:
```
> 00 cb 3f ff 05 5c 03 5f c1 07 63
< 61 84 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 05 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
> 00 c0 00 00 61
< 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
```

This results in the following backtrace:
```
#0  0x000055555586b844 in sc_simpletlv_read_tag (buf=buf@entry=0x7fffffffd728, buflen=1633645655, tag_out=tag_out@entry=0x7fffffffd70b "", taglen=taglen@entry=0x7fffffffd738) at simpletlv.c:83
#1  0x00005555556db942 in piv_parse_ccc (card=0x5555558fa640, card=0x5555558fa640, rbuflen=<optimized out>, rbuf=<optimized out>) at card-piv.c:2747
#2  piv_process_ccc (card=0x5555558fa640) at card-piv.c:2787
#3  piv_match_card_continued (card=card@entry=0x5555558fa640) at card-piv.c:3272
#4  0x00005555556dc930 in piv_match_card (card=0x5555558fa640) at card-piv.c:3107
#5  piv_match_card (card=0x5555558fa640) at card-piv.c:3076
#6  0x000055555559f79c in sc_connect_card (reader=reader@entry=0x5555558fa4a0, card_out=card_out@entry=0x7fffffffddc0) at card.c:295
#7  0x000055555557c169 in util_connect_card_ex (ctx=0x5555558f9260, cardp=0x5555558f2220 <card>, reader_id=<optimized out>, do_wait=<optimized out>, do_lock=0, verbose=0) at util.c:154
#8  0x00005555555672e3 in main (argc=<optimized out>, argv=<optimized out>) at pkcs15-tool.c:2303
```
The problem is the automatic parsing of the data, which saves the **big** ASN.1 length in `bodylen`

https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L615-L623

and returns it as result of `piv_general_io` although `sc_asn1_read_tag` has previously errored with `SC_ERROR_ASN1_END_OF_CONTENTS`:

https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L637-L640

### Proposed Resolution

I don't see an obvious fix. The whole magic around caching and parsing data in `card-piv.c` is a big mess, that's repeatedly breaking OpenSC. If it doesn't see any serious rework, I'll disable PIV driver by default. It needs to become readable and maintainable, sacrificing simplicity for saving a couple of lines of code should be avoided. Given the fact that macOS and Windows include proprietary default drivers, the impact of disabling PIV in OpenSC is hopefully limited. @dengert, please have a look.

### Steps to reproduce

https://github.com/OpenSC/OpenSC/pull/1580

**Comment by mouse07410** [comment]
PIV driver had been working fine, and is required on MacOS by Firefox, all OpenSSL-based applications, and MS Office. 

Apple provides only "pivtoken" - a tokend analog that only helps apps, which are written to Apple-specific CTK API (that isn't useful anywhere else, so app portability guess like goes out of the window).

The impact of disabling PIV duvet would not be "limited" - but devastating, turning a useful software into something on the fringe, not serving the majority of it's users any more.

Better drop tests for now that can't deal with CCC - because "real" (paid) software like Centrify and Thursby PKard not only can parse CCC, they **require** it to talk to PIV cards.

**Comment by frankmorgner** [comment]
1. I don't think you're aware of the implications: This kind of problem risks the security of all users running with a default confiugration, especially those that are using it for login (root privileges).
2. The problem is not limited to the CCC parsing; the problem is rooted on a driver specific low level routine that's used for every I/O operation of the PIV driver.

**Comment by dengert** [comment]
Do you have the full debug log for this? 

I would like to see if it is limited to the CCC parsing.

**Comment by mouse07410** [comment]
You are correct - I wasn't aware. 

What exactly is your proposal? To disable the driver in opens.conf, so those who don't need it won't have it enabled/loaded by default (this would be acceptable)? Or disabling something in the code (I would object against this)?

**Comment by frankmorgner** [comment]
[log.txt](https://github.com/OpenSC/OpenSC/files/2760189/log.txt)

**Comment by frankmorgner** [comment]
The idea would be to move the PIV driver to the old drivers.

**Comment by frankmorgner** [comment]
Sorry, I've already disabled the PIV driver. However, this also gives some useful information: CAC driver is equally vulnerable. @Jakuje please review `cac_apdu_io`, it's equally broken as `piv_apdu_io` (see comments above).

Here's a log for PIV:
[log_piv.txt](https://github.com/OpenSC/OpenSC/files/2760375/log_piv.txt)

**Comment by dengert** [comment]
Thanks.

The piv driver  use GET DATA (CB) that returns BER. But with the PIV, the only way to determine the size of the object to be returned is to read the beginning of the object to look at the tag and length. So the PIV driver first reads 8 bytes in line 603:
```
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 07 08 ..?..\._...
P:5455; T:0x83887936 16:58:13.317 [pkcs15-tool] reader-pcsc.c:213:pcsc_internal_transmit: called
P:5455; T:0x83887936 16:58:13.323 [pkcs15-tool] reader-pcsc.c:294:pcsc_transmit: 
Incoming APDU (258 bytes):
61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 aaaaaaaaaaaaaaaa
61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 aaaaaaaaaaaaaaaa
... skipped to end...
61 61  
```
This appears to be valid ASN1 with a tag=61 and len=61 with sw1 and sw2 saying do a GET RESPONSE of length 61. GWT RESPONSE is skipped when only reading the length for first 8 bytes. 

In  line 630 `card-piv.c:1009:piv_get_data: buffer for #0 *buf=0x(nil) len=99` 
 says read again for 99 bytes.  which is the expected tag=0x61, length=0x61 and value of size=0x61. 1+1+97 = 99

In line 643  GET DATA is done a second time to read the full object, expecting it to be 99 bytes:
```
Outgoing APDU (11 bytes):
00 CB 3F FF 05 5C 03 5F C1 07 63 ..?..\._..c
P:5455; T:0x83887936 16:58:13.333 [pkcs15-tool] reader-pcsc.c:213:pcsc_internal_transmit: called
P:5455; T:0x83887936 16:58:13.339 [pkcs15-tool] reader-pcsc.c:294:pcsc_transmit: 
Incoming APDU (258 bytes):
61 84 61 61 61 61 61 61 61 61 61 61 61 61 61 61 a.aaaaaaaaaaaaaa
61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 aaaaaaaaaaaaaaaa
... skipping...
61 61
```
The code is getting a different TLV with "L" being 4 bytes of 61616161
and went ahead and cached the large object, even with the -1403 SC_ERROR_ASN1_END_OF_CONTENTS
line 703: `card-piv.c:616:piv_general_io: r_tag:-1403 body:0x5017a26`
line 705: `card-piv.c:644:piv_general_io: returning with: 1633771879`
line: 708: `card-piv.c:1092:piv_get_cached_data: added #0  0x5017a20:1633771879 (nil):0`
line 709: `card-piv.c:1104:piv_get_cached_data: returning with: 1633771879`

So there are a number of issues:

- The tag should have been "53" for most objects.
- The TLV returned by both reads should have been the same.
- The data actually read in the second read was based on the size from the first read. 

The Discovery object was also read earlier. But the same TLV of 6161 was received in the GET DATA to get the length and the second GET DATA to read the full object. 

I will work on a fix that:
- Looks for a reasonable length for data from a smart card with 65K being the max.
- Looks that the same TLV is returned in both cases
- The second GET DATA reads the correct amount of data as the TLV says. 
- probably puts the changes in piv_general_io routine that is used by other routines not just GET DATA. 

So this in not just a CCC issue.  it got caught with trying to handle a Length  of 84 61 61 61 61

**Comment by Jakuje** [comment]
Frank, as written already in the other PR, thank you for the work of adding the opensc into OSS-Fuzz to make OpenSC more secure. I had it in my mind some weeks ago, but unfortunately, I did not managed to find a time to proceed on this.

I am probably too tired today but I do not see the same error in the CAC driver. Indeed, there is a valgrind warning in the log, but it does not come from the CAC driver itself, but from the fuzzer driver if I see right.
The CAC driver does not parse the ASN1 tags, but only the simpletlv later on, which I do not see ignoring the return values (end of contents). Can you clarify what is the issue you see in the CAC driver?

**Comment by mouse07410** [comment]
I would be against moving the PIV driver to "old drivers"

**Comment by frankmorgner** [comment]
@Jakuje yes, you're right there doesn't seem to be a erroneous behavior of the cac driver. Since I was already in the process of fixing things, I only skimmed through the generated log. However, I still think that both, cac_general_io and piv_general_io should do less homebrewing. For example, the following lines
https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L547-L554
as well as these lines
https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L574-L582
as well as those lines
https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L592-L640
could be completely avoided if the caller would simply write 
```
u8 rbuf[CAC_MAX_SIZE];
u8 sbuf[CAC_MAX_SIZE];
sc_format_apdu(card, &apdu, apdu_case, ins, p1, p2);
apdu.resp = rbuf;
apdu.resplen = sizeof rbuf;
apdu.data = sendbuf;
apdu.datalen = sendbuflen;
apdu.lc = sendbuflen;
```
Isn't this way more readable?! (note that the current implementation doesn't even save memory, because `cac_general_io` *always* throws `rbufinitbuf[CAC_MAX_SIZE]` onto the stack, no matter if the caller provided a buffer or not).

The PIV driver makes matters worse by throwing ASN.1 parsing into the mix, which actually led to the bug in question. I'm just asking for keeping it simple, for example
- use short functions that do a single job, name them accordingly
- reuse and improve existing functionality
  - replace `put_tag_and_len` with existing parsers
  - remove driver based file caching in favor of pkcs15-cache
  - improve the default driver instead of working around its limitations
  - repeatedly calling a card command if data could not be transmitted should be done outside the card driver to enable this for all cards if possible (think like sc_read_binary or sc_get_challenge) )

All these hacks we have long lived with, are simply getting too much. This needs to get better. I'm not asking for more opinions here, @mouse07410. I'm asking for someone who actually works on the code.

**Comment by Jakuje** [comment]
Frank, I agree with this initiative, but I know that we can not rewrite the code from day to day to match these requirements.

Where we need to start is the new code that gets in to have good quality using some linter, that could point out some of the issues with the new code (code climate looks nice, but does not support c, coala does not have nice integration with github and that is all I know). I know we are trying to do that with pull request reviews and CI so far, but having this also formally written in some contribution and code style guide might help new contributors as well as with disagreements.

Analyzing existing code base and gradually improving it by refactoring really needs to make sure the existing functionality is preserved and no regressions are introduced. You did a good start with here with the virtual smart cards, but it needs to be extended. To figure out what parts need to be refactored, the help of some automated tools would be good as pointed out in the previous paragraph, unless you want to go through the code manually and fill an issue for each and every place that could make use of some love.

I will check what can be done with the CAC driver. I see that the `recvbuf` is never NULL in the calls from CAC driver, so this is indeed one step for improvement. Problem with `sc_read_binary()` is that in CAC it does not read the raw certificate, but SimpleTLV structure from where we can parse the certificate. But I see there a space to improve by moving the certificate decompression to the calling function for an additional price of additional argument that would have to be passed from the driver.

**Comment by frankmorgner** [comment]
Here's an other log where the same error happens when the PIV driver tries to read a certificate:
[log2_piv.txt](https://github.com/OpenSC/OpenSC/files/2764525/log2_piv.txt)
If you run the script from #1580, I can give you the test cases so you can reproduce the problems.

**Comment by dengert** [comment]
I will have a look at the script.

**Comment by dengert** [comment]
Can you try #1583 that should handle the cases as seen in [log_piv.txt](https://github.com/OpenSC/OpenSC/files/2760375/log_piv.txt)

I still need to add some code in match that will treat an Invalid Discovery or select_AID as Not a PIV card. 
I will look at the script later today.

**Comment by dpward** [comment]
>     1. I don't think you're aware of the implications: This kind of problem risks the security of all users running with a default confiugration, especially those that are using it for login (root privileges).
> 
>     2. The problem is not limited to the CCC parsing; the problem is rooted on a driver specific low level routine that's used for every I/O operation of the PIV driver.

Has anyone requested a CVE ID for this issue / related issues?

**Comment by dengert** [comment]
The PIV specs do not define a way to determine the length of an object until the object is read. The GET DATA command and related commands always start at the beginning of the  object. So in order to determine the length of an object a partial read is done of the first few bytes then the length is determined and a large enough buffer is allocated  and the operation is done again to read the full object. The fuzzing code pointed out that if the BER-TLV at the start of the object was not the same in both GET DATA commands there could be a problem.  

I would like to point out that I submitted #1583 Jan 16 in response to this issue to address the basic problem.  Frank closed https://github.com/OpenSC/OpenSC/pull/1583#issuecomment-454811977 on Jan 16 because it added 20 lines of code. 

I then submitted #1585 on Jan 19. Frank then closed this one https://github.com/OpenSC/OpenSC/pull/1585#issuecomment-459110841 on Jan 30 (while I was recovering from surgery)  via 2709e3dac8fd712f768a191e0f78ca2d71d5b799  on Jan 22.

I later submitted #1723 on Jun 28 which removed the requirement to read the block twice by dynamically allocating the buffer while reading the response data via GET RESPONSE. Frank then commented https://github.com/OpenSC/OpenSC/pull/1723#pullrequestreview-256063348. And I closed it.

**Comment by mouse07410** [comment]
> The fuzzing code pointed out that if the BER-TLV at the start of the object was not the same in both GET DATA commands there could be a problem.

I'd it even possible that a card would return different TLVs for two subsequent commands? What is the threat vector here? 
Or is it about code cleanliness? If not, are other parts of the OpenSC code robust enough to deal with a malicious token whose responses are deliberately crafted to break OpenSC?

I disagreed with the handling of this issue, but Frank said that he didn't ask for my opinion (https://github.com/OpenSC/OpenSC/issues/1581#issuecomment-454584473).

**Comment by dengert** [comment]
Another solution is to use a large buffer big enough to read any object with with one APDU + multiple GET RESPONSES.  PIV early gave max object sizes But in later versions these are changed to the minimum size a card must support.  (NIST sp800-73-4 Part 1, Appendix A, Table 7 and footnote 21.) Minimum size of largest object is 12710.  

PRO:    Simpler. 
CONS: Large buffer is used, and if not large enough the operation will fail. 

To fix the CON above: 
 - If buffer to small, get large buffer and read again This is almost the same code that is in question, and could be a performance issue. 

 - Add opensc.conf  option to specify the size of buffer to use. Allows for future cards with larger objects.

Another solution is dynamic allocation of buffer during GET Response in OpenSC core code. (#1723 did this within `card-piv.c`. I have an experimental version of this but never submitted it. 

PRO:  Only one APDU + GET RESPONSE. Could be used by other drivers. 
CON: changes at the heart of OpenSC.

**Comment by mouse07410** [comment]
I like the idea of statically allocated buffer, with `opensc.conf` specifying how big that buffer should be. It seems more reliable/easier-to-track than getting involved with dynamic memory management.

If we can guarantee no memory leak, i.e., whatever is allocated is guaranteed to get freed - dynamic solution could be interesting.

Is there any issue with multi-threading? AFAIK, OpenSC was supposed to be a single-threaded library - that hasn't changed, right?

**Comment by dengert** [comment]
Not really a static buffer. A large buffer is allocated and passed as `resp` and `resplen`. It could then be reallocated to the correct size of a new correct size buffer is allocated and `memcpyed`. Original large buffer is then freed. 

There are no new multi-threading issues with this approach.
