### ISSUE TITLE
Configure ACS ACR 38U Card reader with opensc -> Showing Unsupported card while run opensc-tool -n command on ubuntu

### ISSUE THREAD

**Issue by amitdrana** [OpenSC/OpenSC#1588]
### Problem Description

Hi,
  I want to configure openvpn server with  ACS ACR 38U smart card reader in ubuntu 18 . 
Smart Card reader  is detected  but getting error while running command :- 

opensc-tool -n
Using reader with a card: ACS ACR 38U-CCID 00 00
Unsupported card

 opensc-tool -l
Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             ACS ACR 38U-CCID 00 00

I am using OpenSC 0.17.0 [gcc  7.3.0]

Detail of the card reader:-
 https://www.acs.com.hk/en/products/199/acr38u-i1-smart-card-reader/

ANy suggestion??

**Comment by frankmorgner** [comment]
the reader seems to work OK. However, OpenSC doesn't know the card, that's why it says *"Unsupported card"*. I think the reader has an integrated SAM. You need to configure the reader accordingly. Please use ACS support for that.

**Comment by amitdrana** [comment]
Hi ,

I confirmed that there is no issue with the reader.
Still showing unsupported card. 

I check the logs via OPENSC_DEBUG=9 pkcs11-tool --list-slots command
find this:-

APDU transmit failed: -1107
SCardTransmit/Control failed: 0x80100016

Also, Attaching the logs

Any suggestion

[logs.txt](https://github.com/OpenSC/OpenSC/files/2813520/logs.txt)

**Comment by amitdrana** [comment]
Thanks for the frequent reply @frankmorgner really appreciate.   :)

can you suggest me anything to verify my reader and card are working as expected?

because as per the vendor reader does not have an integrated SAM module.

**Comment by frankmorgner** [comment]
Please ask your vendor on how to get started with your reader in Ubuntu.
