### ISSUE TITLE
pkcs11-tool --test decryption not working for CKM_RSA_PKCS_OAEP

### ISSUE THREAD

**Issue by AlexandreGonzalo** [OpenSC/OpenSC#1594]
Hi,

I am trying to use the pkcs11-tool in order to test my own implementation of the PKCS#11 library.
It is a great tool, thank you for providing it.
I have two issues with the decryption test when I am trying to use the CKM_RSA_PKCS_OAEP mechanism.
The first issue is that the CK_RSA_PKCS_OAEP_PARAMS parameter is not set in
encrypt_decrypt(). I don't think that this parameter is optional.
My proposed solution is to do the same as decrypt_data().
The second issue is the encryption with OpenSsl which is done with EVP_PKEY_encrypt_old() in encrypt_decrypt(). This is not using the OAEP padding but the default one, PKCS#1.5.
My proposal is to use EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_OAEP_PADDING) in this case.
I have attached a patch to this ticket.
[oaep.txt](https://github.com/OpenSC/OpenSC/files/2795354/oaep.txt)

Best Regards,
Alexandre.

**Comment by Jakuje** [comment]
Please, submit a pull request and I would be happy to review your code.
Indeed, this mechanism requires parameter but I do not have any use case for that so it is probably not properly tested yet. Adding an automated test case into `tests` directory would also make sense to make sure it works and it will work also for future releases.

**Comment by AlexandreGonzalo** [comment]
Hi,
I created the pull request:
https://github.com/OpenSC/OpenSC/pull/1600
I haven't had a look at the tests directory yet.
Regards,
Alexandre.

**Comment by AlexandreGonzalo** [comment]
FYI, I pushed more changes to my branches as I noticed that you are using tabs for the indentation.
I also fixed a bug.
