### ISSUE TITLE
Unused selection of padding mechanism in pkcs15_prkey_unwrap

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1595]
### Problem Description

There's an assignment to the variable `flags`, which doesn't get used:

https://github.com/OpenSC/OpenSC/blob/70d690ace7a5ddc5a534e7455bdc1800e26cb807/src/pkcs11/framework-pkcs15.c#L4031-L4041

### Proposed Resolution

@hhonkanen please check what's going on there... and/or if the above sniplet can be removed.

**Comment by hhonkanen** [comment]
I think we should not remove this code, but rather pass flags to sc_pkcs15_unwrap(). Looks like we have just forgotten to pass it forward, and it works fine in our tests regardless of this. We now just pass zero to flags.  

Both mechanisms should be tested after fixing this. I have tested the code only with CKM_RSA_PKCS, and it works correctly event though flag SC_ALGORITHM_RSA_PAD_PKCS1 is not passed forwards.

**Comment by Jakuje** [comment]
@hhonkanen The code is commented out since 2019. Do you have some particular idea why these flags would be used in `sc_pkcs15_unwrap()`? If not, I would propose to remove the commented code in
https://github.com/OpenSC/OpenSC/blob/a00ead5bcaeef9761287572f7b62065d62c211d9/src/pkcs11/framework-pkcs15.c#L4308-L4321

**Comment by hhonkanen** [comment]
@Jakuje I would prefer to not remove the code, but rather pass the flags to sc_pkcs15_unwrap() at lines 4329-4330. The idea of the flags argument is to pass details about the RSA encrypted key data to the card, for example which padding has been used. 
The cards that implement unwrap operation may need this information from the software that is using them. Two flags have been defined there, but there might be need to extend this and support more mechansisms/flags in future. 

The flags argument should be passed after targetKeyObj->p15_object like this:

	/* Call the card to do the unwrap operation */
	rv = sc_pkcs15_unwrap(fw_data->p15_card, prkey->prv_p15obj, targetKeyObj->p15_object, flags,
		pWrappedKey, ulWrappedKeyLen, NULL, 0);

The reason why the flags argument is unused is that I have just forgotten to pass it too sc_pkcs15_unwrap, and it happens to work anyway, with flags being zero, with MyEID and the test data we used. 

My opensc dev environment is currently out of order, and I haven't installed the tools yet on my new workstation. Could you please fix the code and commit it? 

sc_pkcs15_unwrap passes flags to sc_get_encoding_flags, we should test that it still works when flags can be nonzero. It looks it will probably be ok, but should be ensured.  I can provide test cards or test it myself when I get time to set up opensc dev tools and get the environment up and running.

**Comment by Jakuje** [comment]
ok. I changed the commit to pass the flags. Unfortunately, I do not have physical MyEID card to try with. Tests with oseid look fine so far.

**Comment by hhonkanen** [comment]
Thanks @Jakuje. If you would like to test with MyEID, please send me an email with your address, and we can send test cards. You can find my contact info at https://aventra.fi/company/
