### ISSUE TITLE
Signature with softhsm

### ISSUE THREAD

**Issue by benoiton** [OpenSC/OpenSC#1603]
### Problem Description

It seems pkcs11-tool cannot sign with sofhsm2.

### Steps to reproduce

Token initialization:

> $ softhsm2-util --init-token --label testtoken --free --pin 0000 --so-pin 1234      
> Slot 0 has a free/uninitialized token.
> The token has been initialized and is reassigned to slot 292943381

Token test:

> $ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so -l -t
> Using slot 0 with a present token (0x1175f615)
> Logging in to "testtoken".
> Please enter User PIN: 
> C_SeedRandom() and C_GenerateRandom():
>   seems to be OK
> Digests:
>   all 4 digest functions seem to work
>   MD5: OK
>   SHA-1: OK
> Signatures: not implemented
> Verify (currently only for RSA)
>   No private key found for testing
> Unwrap: not implemented
> Decryption (currently only for RSA)
> No errors

Signature is "not implemented".

Add a RSA key:

> pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so --token-label testtoken --keypairgen --key-type rsa:2048 --usage-sign --label rsakey --pin 0000
> Key pair generated:
> Private Key Object; RSA 
>   label:      rsakey
>   Usage:      decrypt, sign, unwrap
> Public Key Object; RSA 2048 bits
>   label:      rsakey
>   Usage:      encrypt, verify, wrap

New test:

> $ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so -l -t
> Using slot 0 with a present token (0x1175f615)
> Logging in to "testtoken".
> Please enter User PIN: 
> C_SeedRandom() and C_GenerateRandom():
>   seems to be OK
> Digests:
>   all 4 digest functions seem to work
>   MD5: OK
>   SHA-1: OK
> Signatures: not implemented
> Verify (currently only for RSA)
>   testing key 0 (rsakey)
>     RSA-X-509: OK
>     RSA-PKCS: OK
>     SHA1-RSA-PKCS: OK
>     MD5-RSA-PKCS: OK
> Unwrap: not implemented
> Decryption (currently only for RSA)
>   testing key 0 (rsakey) 
>     RSA-PKCS: OK
>     RSA-X-509: OK
> error: PKCS11 function C_DecryptInit failed: rv = CKR_ARGUMENTS_BAD (0x7)
> Aborting.
>     RSA-PKCS-OAEP: 

No more signature. And there is a failure.

Another test to verify softhsm capabilities:

> $ cat engine.conf 
> openssl_conf = openssl_init
> 
> [openssl_init]
> engines = engine_section
> 
> [engine_section]
> pkcs11 = pkcs11_section
> 
> [pkcs11_section]
> engine_id = pkcs11
> dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so
> MODULE_PATH = /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
> init = 0
> 
> [ req ]
> distinguished_name = req_dn
> 
> [ req_dn ]
> commonName = foobar
> 
> $ openssl req -engine pkcs11 -new -days 1 -subj '/CN=test' -keyform engine -key 'pkcs11:token=testtoken;object=rsakey'

Signing does work with openssl+engine+softhsm

### Versions

SoftHSM

> $ softhsm2-util --version
> 2.4.0

PKCS11 tool

> $ pkcs11-tool -I
> Cryptoki version 2.20
> Manufacturer     OpenSC Project
> Library          OpenSC smartcard framework (ver 0.19)
> No slots.

OpenSSL

> $ openssl version
> OpenSSL 1.1.1a  20 Nov 2018

**Comment by Jakuje** [comment]
This is a problem of the detection of the mechanisms in the `pkcs11-tool --test`, requiring the mechanism to have the HW flags:

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L4699-L4702

If you try to use the signatures directly, it will work, see

https://github.com/OpenSC/OpenSC/blob/master/tests/test-pkcs11-tool-sign-verify.sh

**Comment by Jakuje** [comment]
The discussion if the softhsm should or should not present the HW flag was there already, but it does not look like it should fake the HW up to this extent. Probably, the pkcs11-tool should not require the hw flags for testing.

**Comment by benoiton** [comment]
I've just tested test-pkcs11-tool-sign-verify.sh, and I confirm signature is OK with softhsm2.

For the record, this script calls "pkcs11-tool" with a "--verify" option that is not yet released.  Once the few lines commented out, it's OK. Signature is verified by OpenSSL.

**Comment by benoiton** [comment]
I also tested ECDSA signature.

The two available signature mechanisms in softhsm2 for ECDSA are ECDSA and ECDSA-KEY-PAIR-GEN. But, as I understand the [openssl pkeyutil manpage](https://www.openssl.org/docs/man1.1.1/man1/pkeyutl.html), the only mechanism supported by OpenSSL is ECDSA-SHA1.

I did not succeed in verifying any signature.

I tested with
```
openssl pkeyutl -verify -pubin -inkey EC.pub -in data -sigfile data.sig
```
and
```
openssl dgst -verify EC.pub -signature data.sig data
openssl dgst -sha1 -verify EC.pub -signature data.sig data
```

(I also tested with a Nitrokey HSM that supports ECDSA-SHA1, without any success either.)

**Comment by Jakuje** [comment]
> The two available signature mechanisms in softhsm2 for ECDSA are ECDSA and ECDSA-KEY-PAIR-GEN. But, as I understand the openssl pkeyutil manpage, the only mechanism supported by OpenSSL is ECDSA-SHA1.

The `ECDSA-KEY-PAIR-GEN` is key generation mechanism and not a signature mechanism, as you can notice from the flags next to the mechanism in the list in `pkcs11-tool -M`.

The `ECDSA` method already accepts the hash instead of doing the hash inside of the mechanism. See the PKCS#11 specifiction and the section related to this method:

http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399398884

This means, that for signature, you need to do the has in advance, for example as follows:

```
pkcs11-tool --id 03 -s -p 123456 -m ECDSA \
    --input-file data.hash --output-file data.sig.openssl \
    --signature-format openssl

openssl dgst -keyform PEM -verify 03.pub -sha256 \
           -signature data.sig.openssl data
```

I plan to add also the test also to the testsuite soon.

**Comment by mouse07410** [comment]
I'm confused by "... OpenSSL only supports ECDSA-SHA1..."

I've performed a lot of ECDSA signature with SHA256 and SHA384, using OpenSSL-1.0.2.

Could you clarify please where this "SHA-1 only" limitation really coming from, and if it is even correct?

**Comment by benoiton** [comment]
@mouse07410 : Quoted from https://www.openssl.org/docs/man1.1.1/man1/pkeyutl.html

> EC ALGORITHM
> 
> The EC algorithm supports sign, verify and derive operations. The sign and verify operations use ECDSA and derive uses ECDH. Currently there are no additional options other than digest. Only the SHA1 digest can be used and this digest is assumed by default.

I can be wrong when interpreting this statement.

**Comment by mouse07410** [comment]
Obviously the docs are wrong, because ECDSA with (e.g.) SHA384 works perfectly well with OpenSSL-1.0.2r and PIV token (Yubikey 4 in this case):
```
Retrieving public key from the token...
$ pkcs15-tool --read-public-key 02 -o /tmp/derive.12636.der
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID

read EC key
Discovered that CURVE=secp384r1, setting HASH=sha384

Generating a random file (hex-encoded to allow experiments) to sign...
$ openssl rand -hex -out /tmp/derive.12636.data 2500

$ openssl dgst -engine pkcs11 -keyform engine -sha384 -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;object-type=private" -out /tmp/derive.12636.sig /tmp/derive.12636.data
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri:
Signature for /tmp/derive.12636.data is stored in /tmp/derive.12636.sig

Extracting pubkey (again) - now for signature verification...
$ pkcs11-tool --module /Library/OpenSC/lib/opensc-pkcs11.dylib -r -y pubkey -d 02 -o /tmp/derive.12636.der
Using slot 0 with a present token (0x0)

Verifying digital signature - should print "Verified OK"...
$ openssl dgst -verify /tmp/derive.12636.der -keyform DER -sha384 -signature /tmp/derive.12636.sig /tmp/derive.12636.data
Verified OK

Same as above, using pubkey directly from the token...
$ openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;object-type=public" -signature /tmp/derive.12636.sig /tmp/derive.12636.data
engine "pkcs11" set.
Verified OK
```

If you insist on testing with `openssl pkeyutl`:
```
$ openssl version
OpenSSL 1.0.2r  26 Feb 2019
$ openssl rand -out t.dat 340
$ openssl pkeyutl -engine pkcs11 -keyform engine -sign -inkey "pkcs11:manufacturer=piv_II;object=SIGN%20key;object-type=private" -pkeyopt digest:sha384 -in t.dat -out t.dat.sig
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri:
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -pubin -inkey "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;object-type=public" -pkeyopt digest:sha384 -in t.dat -sigfile t.dat.sig 
engine "pkcs11" set.
Signature Verified Successfully
$
```

Please remove that restriction from the code.

**Comment by mouse07410** [comment]
```
$ openssl version
OpenSSL 1.0.2r  26 Feb 2019
$ openssl rand -out t.dat 360
$ openssl pkeyutl -engine pkcs11 -keyform engine -sign -inkey "pkcs11:manufacturer=piv_II;object=SIGN%20key;object-type=private" -pkeyopt digest:sha384 -in t.dat -out t.dat.sig
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri:
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -pubin -inkey "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;object-type=public" -pkeyopt digest:sha384 -in t.dat -sigfile t.dat.sig
engine "pkcs11" set.
Signature Verified Successfully
$ 
```

```
$ pkcs11-tool -r -y pubkey -d 02 > t-pub.der
Using slot 0 with a present token (0x0)
$ openssl version
OpenSSL 1.0.2r  26 Feb 2019
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;object-type=private" -sha384 -out t.dat.sig t.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri:
$ openssl dgst -keyform DER -verify t-pub.der -sha384 -signature t.dat.sig t.dat
Verified OK
$ 
```
I think that restriction should be removed.

**Comment by mouse07410** [comment]
FYI: https://github.com/openssl/openssl/pull/8432/commits/be8a913d8c00cfa55ad34fea361eff05c5ff98b3

**Comment by benoiton** [comment]
Thanks to you. I can make it working as expected.

My final test:
```
LIB='/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so'
echo test > myfile

softhsm2-util --init-token --label mytoken --free --pin 0000 --so-pin 1234
pkcs11-tool --module $LIB --token-label mytoken --login --pin 0000 --keypairgen --key-type EC:prime256v1 --usage-sign --label mykey
pkcs11-tool --module $LIB --token-label mytoken --label mykey --read-object --type pubkey --output mykey.pub

pkcs11-tool --module $LIB --token-label mytoken --hash --mechanism SHA256 --input-file myfile --output-file myfile.hash
pkcs11-tool --module $LIB --token-label mytoken --login --pin 0000 --label mykey --sign --mechanism ECDSA --signature-format openssl --input-file myfile.hash --output-file myfile.sig

openssl dgst -sha256 -verify mykey.pub -keyform DER -signature myfile.sig myfile
```

**Comment by mouse07410** [comment]
And your post made me review how "pkcs11-tool --test" works, and in my fork fix testing digest, adding support for the SHA2 family.

Next step for me - repair "--test-ec", which currently behaves in a totally different way from "--test" (and IMHO with no good reason for that).
