### ISSUE TITLE
opensc‑pkcs11.dll missing in system32

### ISSUE THREAD

**Issue by VVisniowy** [OpenSC/OpenSC#1611]
Hi, 

Just to make an introduction I'm not a programmer neither someone strongy attached to IT

I did follow all the steps here:
https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start
and simply wated to use in the way described here
https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

The problem is, I could not find opensc‑pkcs11.dll in windows-system32  just does not exist.
I've tried on 3 different computers (all of them Win10) I tried to reinstall/repair installation but doesn't fly.
Whereas on latest Mac OS works perfectly without any issue. 

Could you pelase help me with that?

**Comment by frankmorgner** [comment]
please look in `C:\Program Files\OpenSC Project\OpenSC\pkcs11`

**Comment by dengert** [comment]
Looks like Wiki page needs updating. both for how to find "Load PKCS\#11 Device driver" and the location of the `opensc-pkcs11.dll`.  
On Windows 10 64bit, with a 32 bit Mozilla application, you will need to install the 32 bit version of OpenSC. Then look in: `C:\Program Files (x86)\OpenSC Project\OpenSC\pkcs11`

**Comment by VVisniowy** [comment]
Hi, 
Thanks for promp reply!

I did try it from both sources (c:\Program Files (86)\OpenSC Project\OpenSC\pkcs11 and c:\Program Files\OpenSC Project\OpenSC\pkcs11 but doesn't fly. 

With 1st option I got an error 'Can't load this module'- (polish translation), whereas the 2nd - I can see that modul is attached in Mozilla, however it gives me no result, so the card certificate is not identified.

**Comment by dengert** [comment]
OK if second so looks like you are running both Windows and FireFox in 64 bit or both in 32bit. 

If certificate is not identified there are some debugging steps you can try:

- With FireFox, look at "tools->Options->Privacy&Security->View Certificates" to see if it
has any certificates. 

- Use `pkcs11-tool -O` to see if the card is seen, and if there are any certificates and keys . Look at other pkcs11-tool options too. You may need --login. This will show if the opensc-pkcs11.dll is working. 

- Modify the `opensc.conf`  `debug = 3;` and `debug_file = "path to debug file";`  This will give low level output.  

- Use SPY to see the PKCS\#11 calls between FireFox and opensc-pkcs11.dll

See: [Windows-Quick-Start](https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start) and [Using-OpenSC](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC)
