### ISSUE TITLE
PKCS#11 Raw ECDSA and IsoApplet with OpenSSL

### ISSUE THREAD

**Issue by rileyg98** [OpenSC/OpenSC#1647]
### Problem Description
C_SignInit in PKCS11_object throws a CKR_MECHANISM_INVALID when attempting to sign data with a CKM_ECDSA mechanism and matching private key, loaded from card. Smartcard is a NXP P60D144 (i think), it's a Vivokey I've installed IsoApplet on (and definitely supports EC keys). Reader is an ACR122U and doesn't appear to be an issue with the reader (although it does seem to have issues with generating long RSA keys), and it doesn't appear to be an issue with the OpenSSH build I'm using (a nightly build of the new 8.0 release as it supports ECDSA). I've tried tracing this error through to a particular list of valid mechanisms, but can't find it as yet. IsoApplet needs raw ECDSA sent to it as JavaCard only recently added ECDSA hash signing, so IsoApplet will sign the key with SHA2 as part of the key . Key is in format ECDSA_SHA2_NISTP256. As I don't understand the code enough, I haven't been able to track down where the list of valid/invalid formats are. I've imported the ECDSA key into the smartcard. I went and attempted to change the mechanism type in openssh to SHA1 and it got further along (until it hit a "function not supported" by IsoApplet).

### Proposed Resolution
Ensure CKM_ECDSA is considered a valid mechanism for an ECDSA_SHA2 key? 
### Logs

Paste Log output with less than 10 lines here (between the backticks)

P:16017; T:0x139913248765760 17:45:57.714 [opensc-pkcs11] mechanism.c:250:sc_pkcs11_sign_init: called
P:16017; T:0x139913248765760 17:45:57.714 [opensc-pkcs11] mechanism.c:256:sc_pkcs11_sign_init: mechanism 0x1041, key-type 0x3
P:16017; T:0x139913248765760 17:45:57.715 [opensc-pkcs11] mechanism.c:259:sc_pkcs11_sign_init: returning with: 112
P:16017; T:0x139913248765760 17:45:57.715 [opensc-pkcs11] pkcs11-object.c:667:C_SignInit: C_SignInit() = CKR_MECHANISM_INVALID
(Above is OpenSC-debug, below is PKCS11-spy
25: C_SignInit
2019-03-30 17:45:57.714
[in] hSession = 0x55e1fa0f62e0
pMechanism->type=CKM_ECDSA                    
[in] hKey = 0x55e1fa0f3cf0
Returned:  112 CKR_MECHANISM_INVALID
-->

**Comment by rileyg98** [comment]
Oops, forgot the steps to reproduce. As below:

Initialise PKCS#15 filesystem on IsoApplet card
Import/generate ECDSA_SHA2_NISTP256 key
Import the pubkey into a SSH authorized keys file on a server
Attempt to connect to server with openssh 8.0 preview compiled from nightly release (-vvv will also tell you the signature fails)

**Comment by dengert** [comment]
A full opensc debug log would help answer mos of the question below.

`pkcs11-tool -M` would show what mechanisms OpenSC supports for your card. and which ones are supported by hardware. 

`pkcs11-tool -O` would show the  objects including the public keys and the namedCurve for the EC keys.
(You may need --login to see the private keys.)
 
The `C_SignInit` looks valid and the [card-isoApplet.c](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-isoApplet.c)  looks like it should support CKM_ECDSA.  So something else may have gone wrong.
What is the card version number  [card-isoApplet.c line 213](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-isoApplet.c#L213) ? Does the card actually support ECC? 

You said you imported the key as ECDSA_SHA2_NISTP256 This is a combination of the key type: ECDSA namedCurve:  NISTP256 and the HASH:SHA2. It might be that the card is then saying it only supports doing the HASH on the card and **not** the CKA_ECDSA (SC_ALGORITHM_ECDSA_RAW). It looks like to me that [card-isoApplet.c lines 235 and 236](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-isoApplet.c#L235) says the card can only support SC_ALGORITHM_ECDSA_RAW and SC_ALGORITHM_ECDSA_HASH_SHA1. 

But later in the code, card-iso_Applet.c says it only supports CKA_ECDSA (SC_ALGORITHM_ECDSA_RAW) on the card. [card-isoApplet.c#L1120](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-isoApplet.c#L1120)

If you really want the SHA2 hashs done on the card, can you submit a PR?

**Comment by rileyg98** [comment]
Alright, https://gist.github.com/rileyg98/8536ab60ff0d7864832f897e78ae0540 is a full opensc-debug log of the commands requested (and a ssh command appended to the end). To clarify on the ecdsa_sha2_nistp256, that's the format for ssh-keygen, apologies. I'll try updating the isoapplet driver to say it supports sha2.

**Comment by philipWendland** [comment]
I don't think that's right. The current implementation only supports ECDSA
with SHA1 and limited input data length. There is some work to support
offcard hashes for newer Java cards on the llogar branches at my opensc and
IsoApplet repos if you want to try it, but that's not ready to merge yet.

My ultimate plan is to remove the oncard SHA1 features and require Java
cards v3+ for ECDSA, which will then be offcard sha2. But it will take
time, as I am notoriously short of spare time :-(

rileyg98 <notifications@github.com> schrieb am So., 31. März 2019, 03:19:

**Comment by rileyg98** [comment]
Thank you for the reply, Philip. I appreciate the response. Looks like I'll have to move to one of those test branches, or wait until my reader that supports RSA (ACR122U doesn't play nice with extended apdus) arrives.

**Comment by philipWendland** [comment]
FYI you don't need extended APDUs fur RSA. There is an configuration option
in IsoApplet.java to disable ext.Apdus, in which case it will use command
chaining with short APDUs.



rileyg98 <notifications@github.com> schrieb am So., 31. März 2019, 13:30:

**Comment by rileyg98** [comment]
I might have to try again, I had an issue with my reader crashing out with a "card sent unknown data" after about 3 seconds, it could well be a timeout issue when generating. I could load 256-bit ECDSA keys but not 384, and Libusb was timing out with the CCID drivers for the card. I could only generate 192-bit keys on card without it crashing. The ACR122U doesn't support time extension requests.

**Comment by rileyg98** [comment]
I really appreciate your help, Philip. I've managed to load a pre-generated RSA key onto it with the extended APDUs disabled.

**Comment by xaduha** [comment]
@rileyg98 

Hi, I suspect that I have a similar problem with ACR122U. Do I understand it correctly that you managed to get it to work? I've used IsoApplet for quite some time now, but with a contact CCID reader.

**Comment by dengert** [comment]
Just a thought. The ACR122U is also a NFC reader. You may have some other driver being loaded.
See: [linux-nfc-driver-conflicts-with-ccid](https://ludovicrousseau.blogspot.com/2013/11/linux-nfc-driver-conflicts-with-ccid.html)

**Comment by xaduha** [comment]
I did at first, without blacklisting `pn533` pcscd shows errors when starting. It's problems that I'm seeing after that are more worrying. It's ACR122U-A9, response to FF00480000 is "4143523132325532 3135" so ACR122U215, which should mean firmware 2.15.

I tried it with another distro, same deal. I probably should try it in Windows and macOS, see if it works there.

**Comment by rileyg98** [comment]
No, I've got a Feitian reader as well as an ACR122U. I believe my issue was
the ACR122U not supporting time extension requests, and IsoApplet not
supporting ECDSA properly.

**Comment by dengert** [comment]
The time extension should not be an issue, as ECDSA should be rather quick.  RSA generation of a key would be a problem. 

Can you run `pkcs11-tool -M` to see what  mechanisms the card says it supports? It should say
at least these: CKM_ECDSA, CKM_ECDSA_SH1,  CKM_ECDSA_SHA256

You said it got further when  when you tried CKM-ECDSA-SH1. 
  
I dont think you have gotten this far. But if you did, do you have an opensc-debug output file showing what the card returned? There is a chance that the DER results from the card have a leading 0x00 in r and/or s which is added so the leading bit is always zero. Look at the `card-piv.c`  `piv_compute_signature`  code that handles this situation.  It would be helpfull to see what the card returns. Do you get any  SC_ERROR_BUFFER_TOO_SMALL errors?

**Comment by rileyg98** [comment]
I'll be honest, I abandoned IsoApplet for my particular project in favour
of PivApplet, which you appeared to be referencing in your statement. It's
got some more features we can take advantage of (note isoapplet's author
has stated ECDSA is not supported and won't be until he has time to get the
testing branch into stable).

Time extension was with RSA.

Riley

**Comment by rileyg98** [comment]
Apologies, my info was slightly wrong. ECDSA is supported in sha1 on IsoApplet, so generation is fine. My issue wasn't an issue with OpenSC - it appeared to be something else.

**Comment by xaduha** [comment]
Do you use PivApplet with OpenSSH somehow? Because that would be my main use for IsoApplet.

But anyway, I managed to unfuck my ACR122U with FF0041FF00 APDU, maybe not entirely though, still checking.

**Comment by dengert** [comment]
Two comments: 

I see the OpenSC card-isoApplet.c sets: 
```
flags |= SC_ALGORITHM_ECDSA_RAW;
flags |= SC_ALGORITHM_ECDSA_HASH_SHA1;
```
which implies the card can do `ECDSA_RAW`.

But every other card that can do ` SC_ALGORITHM_ECDSA_RAW` also sets `SC_ALGORITHM_ECDSA_HASH_NONE;`
This could explain why the mechanism is not being found.

For security reasons the PIV specs:  NIST SP800-73-4 (and earlier versions) do not allow crypto operations over a contactless interface. SP800-73-4 defines optional SM that is not yet implemented in OpenSC for PIV that could be used. 

True PIV cards enforce this the restrictions on the card. So use at your own risk.

**Comment by philipWendland** [comment]
> > which implies the card can do ECDSA_RAW.

IsoApplet can't. Do you think setting this flag is an error?
It has been some years since I wrote this code. But I think maybe this
flag was required so that OpenSC sends the RAW data to the card,
instead of providing the SHA. Maybe the handling of the flags has
changed in the meantime.
Kind regards,Philip

**Comment by dengert** [comment]
Try removing the `flags |= SC_ALGORITHM_ECDSA_RAW;` and have caller use `CKM_ECDSA_SHA1` as a test. 

The import of the key should not depend on the hash i.e. `ECDSA_SHA2_NISTP256.` is really saying import a ECDSA key with the named curve of  NISTP256. 

Then if you try  CKM_ECDSA_SHA256, opensc will do SHA256 hash in software and pass it to card as the data. If the isoApplet can really only do CKM_ECDSA_SHA1 on the card then it will always do a SHA1 hash of what ever you pass it. 

If you try CKM_ECDSA_SHA1, opensc will just pass it to the card and let it do the SHA1. Si you may be stuck with only CKM_ECDSA_SHA1.
