### ISSUE TITLE
SmartCard HSM C_Login fails when length of User PIN is 16 or greater

### ISSUE THREAD

**Issue by scolby33** [OpenSC/OpenSC#1655]
### Problem Description
I am using opensc-0.16.0-3+deb9u1 on Raspbian Stretch.

All login attempts to my newly-initialized SmartCard HSM fail like so:

```shell
$ pkcs11-tool --login --test-ec
Using slot 0 with a present token (0x0)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN:
error: PKCS11 function C_Login failed: rv = CKR_ARGUMENTS_BAD (0x7)

Aborting.
```

This happens whether I enter the correct pin or not. (I have it set to `1234567812345678` for testing this issue.)

```shell
$ pkcs11-tool --login --test-ec
Using slot 0 with a present token (0x0)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN: 1234567812345678
error: PKCS11 function C_Login failed: rv = CKR_ARGUMENTS_BAD (0x7)

Aborting.
$ pkcs11-tool --login --test-ec
Using slot 0 with a present token (0x0)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN: 8765432187654321
error: PKCS11 function C_Login failed: rv = CKR_ARGUMENTS_BAD (0x7)

Aborting.
$ pkcs11-tool --login --test-ec
Using slot 0 with a present token (0x0)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN: tooshort
error: PKCS11 function C_Login failed: rv = CKR_DATA_LEN_RANGE (0x21)

Aborting.
$ sc-hsm-tool
Using reader with a card: Identiv uTrust 3512 SAM slot Token [CCID Interface] (55511725602942) 00 00
Version              : 2.6
Config options       :
  User PIN reset with SO-PIN enabled
SO-PIN tries left    : 15
User PIN tries left  : 3
DKEK shares          : 2
DKEK key check value : 78F93793341215A0
```

Interestingly, the PIN tries do not decrement when an incorrect pin is entered.

### Proposed Resolution
I'm not sure what exactly `--test-ec` should look like (it's never worked!) but I would like that to happen. Similar attempts to generate keypairs (`pcks11-tool --module opensc-pkcs11.so --login --keypairgen --key-type ec:prime256v1`) fail with the same error.

### Steps to reproduce
The HSM was initialized with two DKEK shares according to the instructions here: https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM
Then, the commands shown above were issued.

### Logs
Logs at `debug = 3` from the following command are here: https://gist.github.com/scolby33/14ddf2d222e8e99b64b2f3a187910fc7

```shell
$ pkcs11-tool --login --test-ec 2> >(tee stderr.log)
```

**Comment by mouse07410** [comment]
In my opinion based on the experience I had, I recommend against using `pkcs11-tool --test-ec` because IMHO the tests are screwed up for ECC. And yes, unlike RSA tests, these require a blank writable token.

**Comment by scolby33** [comment]
Perhaps I picked a bad example command, then--I assumed `--test-ec` would be something relatively simple to try and isolate the problem. As I mentioned briefly, the same error happens with `--keypairgen` as well.

**Comment by mouse07410** [comment]
I usually provision tokens/devices via vendor mechanisms (for you it would probably mean "sc-hsm-tool"?).

Initializing a device should include setting the appropriate PINs *and* provisioning keys. Can you generate a key pair using sc-hsm-tool?

Also, try to collect SPY information (use module opensc-spy.so). I don't really know this device, unfortunately - but others do, and SPY log might be helpful to them.

**Comment by scolby33** [comment]
Unfortunately, it doesn't seem like `sc-hsm-tool` has the capability to generate key pairs. The manufacturer recommends using OpenSC for this, as far as I can tell.

Thanks for the tip on the SPY module! I ran with that: `$ PKCS11SPY=opensc-pkcs11.so pkcs11-tool --module pkcs11-spy.so --login --keypairgen --key-type rsa:2048 --id 10 --label 'test RSA key'` and updated my Gist: https://gist.github.com/scolby33/14ddf2d222e8e99b64b2f3a187910fc7#file-pkcs11-spy-log

Everything looks as I would expect there, but maybe someone with more than just a passing experience with the internals of OpenSC can interpret better than I.

**Comment by mouse07410** [comment]
Probably somebody with sc-card-hsm needs to comment. I've no idea what can make it reject the correct PIN - except that it didn't even try to validate it. Add if it expected some different kind of login...

**Comment by scolby33** [comment]
I think I've found it!
https://github.com/OpenSC/OpenSC/blob/7eeba1fba80d43c3595632dbd45fdfd2ebc19977/src/pkcs11/framework-pkcs15.c#L1467-L1469

Based on the logging from `debug = 3`, this is (I think) the only place the `CKR_ARGUMENTS_BAD` return value could be coming from. Investigating with `pkcs15-tool --list-pins` shows
```
PIN [UserPIN]
	Object Flags   : [0x3], private, modifiable
	ID             : 01
	Flags          : [0x812], local, initialized, exchangeRefData
	Length         : min_len:6, max_len:15, stored_len:0
	Pad char       : 0x00
	Reference      : 129 (0x81)
	Type           : ascii-numeric
	Path           : e82b0601040181c31f0201::
	Tries left     : 3
```

The library thinks the maximum length of the user pin is 15.

Using `opensc-explorer` and `verify chv129` (as shown here https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM#using-opensc-explorer), I get "Code correct." when entering my whole 16-character pin and "Unable to verify PIN code: Wrong length" when entering the simplest truncation I can think of (`12345678123456781` vs. `123456781234567`).

So, I think there is an improper definition about the SmartCard HSM, at least the version I have, where parts of OpenSC think that the User PIN must be 15 characters or less while the device and other parts of the software handle the 16-character pin just fine. I have re-titled this issue to reflect what I think the actual problem here is.

**Comment by scolby33** [comment]
I have confirmed that after re-initializing the card with a 15-character User PIN, this command works:
```shell
$ pkcs11-tool --module opensc-pkcs11.so --login --keypairgen --key-type EC:prime256v1 --label "test-key" 
Using slot 0 with a present token (0x0)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN: 
Key pair generated:
Private Key Object; EC
  label:      test-key
  ID:         bcb13a1b282ada2f2efc18025bf6682500f86edb
  Usage:      sign, derive
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   0441040ad7006746bb79ef0342cb7b5b4b7b52854af2ddb2db16d78163604d887aa045a8ddda8047e2494c5f6e610347a890737900332bdec84b001ea87decd8582c03
  EC_PARAMS:  06082a8648ce3d030107
  label:      test-key
  ID:         bcb13a1b282ada2f2efc18025bf6682500f86edb
  Usage:      verify
```

**Comment by CardContact** [comment]
Your observation is correct. While the SmartCard-HSM supports a PIN length up to 16 digit, the length in OpenSC is limited to 15 digits (Done in 440289a).

The reason for this limitation is, that PIN PAD reader often support only 15 digits (on a 2 * 16 character display) and setting a maximum PIN length of 16 would cause the PIN reader command to fail.

**Comment by scolby33** [comment]
Thank you for the information!

For reference to future travelers, this is a similar issue: https://github.com/OpenSC/OpenSC/issues/1299

**Comment by CardContact** [comment]
That was the one I was looking for...
