### ISSUE TITLE
Initializing OpenPGP card with OpenSC

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1659]
### Problem Description

In order to extend the CI tests, I'm trying to initialize and use a OpenPGP card (i.e. https://github.com/Yubico/ykneo-openpgp/).

- The [wiki page](https://github.com/OpenSC/OpenSC/wiki/OpenPGP-card#3-generating-keys) suggests `openpgp-tool --verify CHV3 --pin 12345678 --gen-key 3` for generating keys, which doesn't work. It also promotes the argument `--key-len` which has been replaced by `--key-type`.
- `pkcs15-init --generate-key rsa/2048 --auth-id 3 --verify --pin 12345678` doesn't work either, although the tool should have some support for OpenPGP...

### Proposed Resolution

Ideally, fix OpenSC for a self sustained solution. Alternatively use gpg --card-edit (is this scriptable?).

### Logs

- with openpgp-tool: https://travis-ci.org/frankmorgner/OpenSC/jobs/519471598#L5675-L5678
- with pkcs15-init: https://travis-ci.org/frankmorgner/OpenSC/jobs/519582301#L5674-L5678

**Comment by Jakuje** [comment]
The `gpg --card-edit` would be painful in the way that it would require also the `scd-pkcs11` to go through the OpenSC, otherwise it would be testing the OpenPGP only (at least for initialization).

**Comment by dengert** [comment]
Any chance the RSA 1024 is not supported in ykneo-openpgp/applet/bin,  jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar or com.licel.jcardsim.remote.VSmartCard openpgp_jcardsim.cfg?

Does it work with 2024?

**Comment by alex-nitrokey** [comment]
The [changes in the openpgp-tool](https://github.com/OpenSC/OpenSC/pull/1508) are not in any release yet. Therefore, it might not be good to reference to the new commands in the wiki already. On the other side, this indeed needs to be changed in future. I don't know why the command is not working right now, but it does work in 0.19.

`pkcs15-init --generate-key rsa/2048 --auth-id 3 --verify --pin 12345678` is working for 0.19 as well, but not on current master. (tested on ZeitControl with OpenPGP Card 3.3 with Nitrokey Pro).
I get the following output:
```
Using reader with a card: Nitrokey Nitrokey Pro (00005F120000000000000000) 00 00
Unable to find PIN code: Requested object not found
Failed to verify User PIN : Requested object not found
```

So these tests are doing a good job already :smile:

Using gpg is not an option as Jakuje said. Plus, people say it is a pain for scripting in general.

**Comment by frankmorgner** [comment]
If possible, please check what's going on there. I'd like to include personalization of OpenPGP to the CI tests.

**Comment by alex-nitrokey** [comment]
I try to have a look next week, sorry.

**Comment by frankmorgner** [comment]
thanks

**Comment by alex-nitrokey** [comment]
It is [this simple commit](https://github.com/OpenSC/OpenSC/commit/ec176443e2b4fa14461ab71ef7ed130a8b7e6e5a) that introduced the problems. Somehow the sc_pkcs15_verify_pin is not called anymore because of the change.

I am a bit short of time these days. Thus, I can not find out what the reason behind the commit is and how to fix both, this issue and the other.

**Comment by alex-nitrokey** [comment]
Okay, I at least found the [commit](https://github.com/OpenSC/OpenSC/commit/0abe9d11c75f8d9de32e862a5a9775aa70a44cc3) that caused the troubles. Honestly, I do not know what this commit is about and thus I don't feel like I could effectively fix the issue.

pkcs15-init is not using the pin provides by argument `--pin` anymore and is therefore aborting. See the differences in both logs:

[log0abe9d1.txt commit that breaks it](https://github.com/OpenSC/OpenSC/files/3182099/log0abe9d1.txt)
[log9ba8f56.txt previous commit](https://github.com/OpenSC/OpenSC/files/3182100/log9ba8f56.txt)

**Comment by frankmorgner** [comment]
Sorry to bug you again, but both versions, [9ba8f56](https://travis-ci.org/frankmorgner/OpenSC/builds/535986208) ([raw log](https://api.travis-ci.org/v3/job/535986210/log.txt)) and [0abe9d1](https://travis-ci.org/frankmorgner/OpenSC/builds/535985743) ([raw log](https://api.travis-ci.org/v3/job/535985753/log.txt)), are failing to run `pkcs15-init --generate-key rsa/2048 --id 3 --auth-id 3 --verify --pin 12345678 -vvv` with the same error "Record not found".

**Comment by frankmorgner** [comment]
btw, PIN verification works as expected in both cases

**Comment by dengert** [comment]
pkcs15-init has a --verify-pin option but no --verify option. it the command really:
```
pkcs15-init --generate-key rsa/2048 --id 3 --auth-id 3 --verify --pin 12345678 -vvv
```
in [log0abe9d1.txt](https://github.com/OpenSC/OpenSC/files/3182099/log0abe9d1.txt)  in line 1597 everything appears to match whats in the good log but then the two messages from pkcs15-tool.c appear and the next debug message is the unbind. It looks like a lot of the debug log is missing.
```
P:6008; T:0x139868017514368 12:12:14.014 [pkcs15-init] pkcs15-lib.c:484:sc_pkcs15init_set_p15card: sc_pkcs15init_set_p15card() returns
Unable to find PIN code: Requested object not found
Failed to verify User PIN : Requested object not found
P:6008; T:0x139868017514368 12:12:14.014 [pkcs15-init] pkcs15-lib.c:431:sc_pkcs15init_unbind: called
```

**Comment by dengert** [comment]
Looking closer, at current master, this problem looks similir to #1684 
and there maybe no missing debug output. 

pkcs15-init.c has:
```
3158                 struct sc_pkcs15_id auth_id;
3159 
3160                 sc_pkcs15_hex_string_to_id(auth_id_str, &auth_id);
3161                 r = sc_pkcs15_find_pin_by_auth_id(p15card, &auth_id, &pin_obj);
3162                 if (r) {
3163                         fprintf(stderr, "Unable to find PIN code: %s\n", sc_strerror(r));
```
`sc_pkcs15_hex_string_to_id` has:
```
2470 sc_pkcs15_hex_string_to_id(const char *in, struct sc_pkcs15_id *out)
2471 {
2472         out->len = sizeof(out->value);
2473         return sc_hex_to_bin(in, out->value, &out->len);
```

`sc.c` has:
```
fd20ffe60 (Frank Morgner    2019-04-04 12:52:08 +0200  102)     /* for ease of implementation we only accept completely hexed bytes. */
 103 fd20ffe60 (Frank Morgner    2019-04-04 12:52:08 +0200  103)     if (byte_needs_nibble) {
 104 fd20ffe60 (Frank Morgner    2019-04-04 12:52:08 +0200  104)             r = SC_ERROR_INVALID_ARGUMENTS;
 105 fd20ffe60 (Frank Morgner    2019-04-04 12:52:08 +0200  105)             goto err;
```

This looks like a single byte character string such as `--auth-id 3` will fail because of the above test. 

Try with `--auth-id 03`

**Comment by alex-nitrokey** [comment]
> Sorry to bug you again, but both versions, 9ba8f56 (raw log) and 0abe9d1 (raw log), are failing to run

You are right, I retested and it worked for both then. I have no idea why it didn't before, I tested both step by step.

> This looks like a single byte character string such as --auth-id 3 will fail because of the above test.

Looks good, thanks! Testing a broken version with 3 and 03 respectively shows that this approach seems to be right. :+1:

**Comment by frankmorgner** [comment]
I've identified two problems:
1. 09a594d0f0 changed the code to require definition of an RSA exponent when generating a key, but openpgp-tool wasn't adjusted accordingly.
2. The same PR introduced the regression to handle cards without changable algorithm information (i.e. cards that are fixed to, for example, rsa2048), which happens to be the case for https://github.com/Yubico/ykneo-openpgp/.

https://github.com/OpenSC/OpenSC/pull/1770 should fix the problems above
