### ISSUE TITLE
Problem signing with feitian epass2003

### ISSUE THREAD

**Issue by vitormc1** [OpenSC/OpenSC#1663]
### Problem Description

Im trying to sign a certificate sign request (CSR) (created with openssl) with my ePass2003 usb token. To generate a signed certificate.

I install the feitian driver and set the dll at the module parameter.

### Steps to reproduce

When i use:

pkcs11-tool --pin XXXXXXXX --module "C:\Windows\System32\DriverStore\FileRepository\eps2003csp11.inf_amd64_0b911697d3fbfbad\eps2003csp1164.dll" -s --input-file csr-test-17042019.csr --output-file data.sig

Return:
```
Using slot 0 with a present token (0x1)
Using signature algorithm RSA-PKCS-KEY-PAIR-GEN
error: PKCS11 function C_SignInit failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

And when i use:

pkcs11-tool --id DF353675 -s -p XXXXXXXX -m RSA-PKCS --module "C:\Windows\System32\DriverStore\FileRepository\eps2003csp11.inf_amd64_0b911697d3fbfbad\eps2003csp1164.dll" --input-file csr-teste-17042019.csr --output-file data.sig

Return:

```
Using slot 0 with a present token (0x1)
Using signature algorithm RSA-PKCS
error: PKCS11 function C_SignUpdate failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

Any ideas to solve this?

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by dengert** [comment]
Looks like a number of problems.

You said OpenSSL created the CSR. That implies that the CSR is signed by the private key matching the public in the CSR. You are then trying to sign the whole CSR with the private key from the token. This will not create a valid CSR or a certificate. 

The mechanism you picked   `RSA-PKCS` can only sign limited size of data. The CSR is way to big. `SHA256-RSA-PKCS` should work (run pkcs11-tool -M to see what is supported) but this will still have the problem from above, its not a valid CSR. 

To use openssl  to create a CSR, you need to use the opensc engine. See: [libp11](https://github.com/OpenSC/libp11)

If you were trying to sign the CSR to create a certificate, (i.e. the token is acting as the CA), you need to use the OpenSSL CA.pl script. (Google for OpenSSL DemoCA) and the [libp11](https://github.com/OpenSC/libp11) so the CA.pl will use the token as the CA's private key.

**Comment by vitormc1** [comment]
@dengert thanks a lot for your explanation, maybe im doing confusion, i will explain my scenario:

Im part of a students group, we make educacional social projects involving helper classes, hire teachers, etc.

We have a student ID card, its a common pvc card with the student photo, code, name, and a qrcode, this qrcode point to a url like: https://www.validstudent.org/ABCDE12345

When we enrool a new student, we create a CERTIFICATE (actually using openssl) to this student using our A1 certificate (direct access to public and private key), using the code above:

`openssl req -new -sha256 -key privateA1key-decrypted.key -subj \"/C=BR/O=ICP-BRASIL/CN=JHON DOE/OU=STUDENT COLLEGE\" -config configfile.conf -extensions myca_extensions -out sign-request.csr 2> errors.txt`

after:

`openssl.exe x509 -req -days 365 -in sign-request.csr -signkey privateA1key-decrypted.key -out certificate.crt 2> errors2.txt`

and finishing setting -days and -Attribute and signing:

`openssl x509AT -days 365 -AA publicA1key.crt -AAkey privateA1key-decrypted.key -User certificate.crt -out certificate.pem -Attribute attributes.txt -extfile extensions.txt  -HolderT 1 2> errors3.txt`

after all this, i have this content in certificate.pem:

`-----BEGIN CERTIFICATE----- 
MIIDOzCCAiMCAQEwbaBrMF6kXDBaMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQ
LUJSQVNJTDElMCMGA1UEAwwcTUFUSEVVUyBBUkxBTSBST01FUk8gUEVSRUlSQTEP
MA0GA1UECwwGVUVFU0dPAgkA4RUWuX+QacGggfkwgfakgfMwgfAxCzAJBgNVBAYT
AkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTQwMgYDVQQLEytBdXRvcmlkYWRlIENl
cnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhIHYyMRIwEAYDVQQLEwlBQyBTT0xV
VEkxGzAZBgNVBAsTEkFDIFNPTFVUSSBNdWx0aXBsYTEaMBgGA1UECxMRQ2VydGlm
aWNhZG8gUEogQTMxSTBHBgNVBAMTQFVOSUFPIEVTVEFEVUFMIERPUyBFU1RVREFO
VEVTIFNFQ1VOREFSSVNUQVMgREUgR086MjI2NTIxNzQwMDAxNzEwDQYJKoZIhvcN
AQEEBQACAmyRMCIYDzIwMTkwNDE3MTkwOTM1WhgPMjAyMDAzMzAxOTA5MzVaMHww
PQYFYEwBCgExNBMyMjcwNDIwMDMwMDAwMDAwMDAwMDAwMDAwMDAwMDAyNTQxMDAw
MDAwMDAwMDAwMDAwMAAwOwYFYEwBCgIxMhMwQ0VQTUdEUkNFU0FSVE9MRURPRU5T
SU5PTUVESU8yb1NFUklFSEFOQVBPTElTR08AMA0GCSqGSIb3DQEBBAUAA4IBAQBa
yq0bwlLnTK8+BpXqtCxvCBoWhlgLOr7bpELuTYyxuzFWRz/OituXbDRfHBKPKcIR
l+ef8HF0wO1kMbYuIXStNaCRxxEPqAFshrt7u/djZLuyleZgW1Hc0MsCQ0PAq4cs
+OlV96QeP2T54DDi0VtG7gPpAGJffObLafAO6TWMTSMNFH/NyEHXclJhYxW3XB04
5BWVg3qOYxowEThghVlIZvP/pPlCTsC08XNuDMAFDbI0KeO8B1fQIkqhERcFlqLI
gyM6NUQOqbSMDMgMnI0DHlUP8dnASr/SRnLXXwjoWYrD5NK+CRDlmVDd5nU9B/s6
i1RlUPvEQVOnLrQG+YPk
 -----END CERTIFICATE-----`

Can be readed using this link:
[lapo asn1](https://lapo.it/asn1js/#MIIDOzCCAiMCAQEwbaBrMF6kXDBaMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJSQVNJTDElMCMGA1UEAwwcTUFUSEVVUyBBUkxBTSBST01FUk8gUEVSRUlSQTEPMA0GA1UECwwGVUVFU0dPAgkA4RUWuX-QacGggfkwgfakgfMwgfAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTQwMgYDVQQLEytBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhIHYyMRIwEAYDVQQLEwlBQyBTT0xVVEkxGzAZBgNVBAsTEkFDIFNPTFVUSSBNdWx0aXBsYTEaMBgGA1UECxMRQ2VydGlmaWNhZG8gUEogQTMxSTBHBgNVBAMTQFVOSUFPIEVTVEFEVUFMIERPUyBFU1RVREFOVEVTIFNFQ1VOREFSSVNUQVMgREUgR086MjI2NTIxNzQwMDAxNzEwDQYJKoZIhvcNAQEEBQACAmyRMCIYDzIwMTkwNDE3MTkwOTM1WhgPMjAyMDAzMzAxOTA5MzVaMHwwPQYFYEwBCgExNBMyMjcwNDIwMDMwMDAwMDAwMDAwMDAwMDAwMDAwMDAyNTQxMDAwMDAwMDAwMDAwMDAwMAAwOwYFYEwBCgIxMhMwQ0VQTUdEUkNFU0FSVE9MRURPRU5TSU5PTUVESU8yb1NFUklFSEFOQVBPTElTR08AMA0GCSqGSIb3DQEBBAUAA4IBAQBayq0bwlLnTK8-BpXqtCxvCBoWhlgLOr7bpELuTYyxuzFWRz_OituXbDRfHBKPKcIRl-ef8HF0wO1kMbYuIXStNaCRxxEPqAFshrt7u_djZLuyleZgW1Hc0MsCQ0PAq4cs-OlV96QeP2T54DDi0VtG7gPpAGJffObLafAO6TWMTSMNFH_NyEHXclJhYxW3XB045BWVg3qOYxowEThghVlIZvP_pPlCTsC08XNuDMAFDbI0KeO8B1fQIkqhERcFlqLIgyM6NUQOqbSMDMgMnI0DHlUP8dnASr_SRnLXXwjoWYrD5NK-CRDlmVDd5nU9B_s6i1RlUPvEQVOnLrQG-YPk)


Then i need the exactly same result, using a A3 certificate (usb token), instead a A1 certificate.

Using opensc, can i do it?

Thanks a lot!

**Comment by FeitianSmartcardReader** [comment]
Sorry for late reply. Was busy for other projects. Will talk to R&D and back to you guys tomorrow. Keep in touch,

**Comment by dengert** [comment]
It looks like you are using openssl x509AT to create an attribute certificate. Are you sure this is what you want? My versions of OpenSSL do not have the x509AT program. 

Most X509 certificates are Version 3. Yours looks like version 2. (on line 3 of dump has Integer 1). This may be a problem as most applications expect version 3 and the ASN.1 code is different. 

in any case, to get OpenSSL to use a private key on a token for any sign option requires the use of an OpenSSL engine. [ibp11](https://github.com/OpenSC/libp11) is an OpenSC package this includes an OpenSSL engine. [README.md](https://github.com/OpenSC/libp11/blob/master/README.md) explains how to use the engine with OpenSSL. 

For most openssl commands, you can add `-engine pkcs11 -key pkcs11:<parameters from RFC 7512>`
https://tools.ietf.org/html/rfc7512

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader any updates?

**Comment by FeitianSmartcardReader** [comment]
Hi Frank

This issue still under handle by R&D, I will check with them next week, we all got holiday this week.

**Comment by frankmorgner** [comment]
I just realized that this is not about the OpenSC pkcs#11 module, but about the proprietary feitian driver... Next time, please use the official support channel from their site then, @vitormc1

**Comment by vitormc1** [comment]
Thanks @frankmorgner , i until not solve my problem, i will try to contact @FeitianSmartcardReader

**Comment by frankmorgner** [comment]
for now, just leave it as is since your request was already picked up.

**Comment by FeitianSmartcardReader** [comment]
@vitormc1 just back from holiday, could you please send me mail to hongbin@ftsafe.com. I forward to sales and engineer to do follow up, thanks
