### ISSUE TITLE
FT epass2003Auto - Cannot create pkcs15 structure with pkcs15-init

### ISSUE THREAD

**Issue by SohamG** [OpenSC/OpenSC#1669]
### Problem Description

The command `pkcs15-init --create-pkcs15` fails with a message `P:12669; T:0x140409682076096 14:00:37.251 [pkcs15-init] ePass2003 doesn't support SO-PIN and SO-PUK. You can unblock key with PUK. `

Ubuntu MATE 18.04 running the latest git master branch compiled, version 0.19.0

I have downloaded and ran as root the fix binary from the wiki page after which i could erase the card with `-E`. However, even after intense googling, I am unable to create a pkcs15 structure hence cannot use the card.
Using the --no-so-pin option gives the same result, just without prompting for a new pin

My guess - It seems like the card is locked with a default pin, however i am unable to unblock it with `pkcs15-tool --unblock-pin` which returns "unsupported card", probably cause it has no pkcs15 structure on it

### Proposed Resolution
Dont know
### Steps to reproduce
Using opensc 0.19.0, plug a FT ePass2003Auto into a usb, run the fix binary provided in the wiki as root, unplug/replug, erase the card with -E and then try to make a new pkcs15 structure

(I'm sorry if this is the wrong place to ask, I've spent a lot of time sifting through opensc docs and related epass2003 articles to no avail)

CC - @FeitianSmartcardReader

**Comment by FeitianSmartcardReader** [comment]
@SohamG you can use below command to erasing the card and re-create your p15 file system, please make sure you want to reset the token.
echo "Erasing the card..."
pkcs15-init -vvvvvvv -E -T

echo "Creating the PKCS15 (onepin) structure.."
pkcs15-init -vvvvvvvvv -C -p pkcs15+onepin --pin 1234 --puk 123456

#echo "Generating RSA keypair "                  
pkcs15-init --generate-key rsa/2048 --auth-id 01 --pin 1234

or

#echo "Importing p12 certificate"
#pkcs15-init --store-private-key ben.test.p12 --format pkcs12 --auth-id 01 --pin 1234   

#check your token objectives 
#pkcs15-tool -vvvvvvvvv -D

If got below error: 
Failed to erase card: Security status not satisfied

Download below tools to reset the token:
Linux tool: https://download.ftsafe.com/files/ePass/Fix_Tool.tar.gz
Windows tool: https://download.ftsafe.com/files/reader/opensc/format_tool_2003.zip
https://github.com/OpenSC/OpenSC/wiki/Feitian-ePass2003

**Comment by SohamG** [comment]
@FeitianSmartcardReader On the second command `pkcs15-init -vvvvvvvvv -C -p pkcs15+onepin --pin 1234 --puk 123456` I get `Failed to create PKCS #15 meta structure: Not allowed`

Logs from that command - https://gist.github.com/SohamG/b61ad7652f57983835717c809a8548a6

**Comment by FeitianSmartcardReader** [comment]
@SohamG could you please download https://download.ftsafe.com/files/ePass/Fix_Tool.tar.gz this tool, run it to reset the token? 
The reason for unsatisfactory security status is that when MF is deleted, the deletion permission of MF is found to be unsatisfactory.
The deletion permission of MF initialized with OpenSC key is 0x90, which is the lowest permission; the deletion permission of the problematic key is 0x9f, which is the highest permission.

You can use the fix tool to reset the token, thanks

**Comment by SohamG** [comment]
@FeitianSmartcardReader I have downloaded the tool from your link and ran it as root.

Now, when I use the command `pkcs15-init -vvvvvvvvv -C -p pkcs15+onepin --pin 1234 --puk 123456` I get the error `Failed to create PKCS #15 meta structure: Invalid ASN.1 object` The command runs for some time before giving this error.

I appreciate the quick replies

**Comment by SohamG** [comment]
@FeitianSmartcardReader Here is the log for the results above https://gist.github.com/SohamG/41674a36c1fdd6d7fc52846b121e9f23

**Comment by FeitianSmartcardReader** [comment]
@SohamG today is late for me, will do test tomorrow and back to you then, keep in touch,

**Comment by SohamG** [comment]
@FeitianSmartcardReader sorry i could not reply earlier, no issues you can take your time. Thanks a lot

**Comment by SohamG** [comment]
@FeitianSmartcardReader Hey, do you have any update for me? Any things i can try to fix the `Invalid ASN.1 object` error?

**Comment by FeitianSmartcardReader** [comment]
@SohamG We got holiday in this week, should back to office next week, the issue already forward R&D to handle, I am waiting their reply, once I got their answer will back to you ASAP.

Sorry for the delay,

**Comment by SohamG** [comment]
@FeitianSmartcardReader sorry to disturb you on a holiday but I just got all the commands/key generation to work by downloading the official release of opensc 0.19.0 from the wiki home page 
(release date 13.09.2018)

I was using the current master branch till now, which makes me think that this may be a bug(?) in the current master release. I had decided to use the master branch after seeing issues with the epass2003 with the opensc version in my linux distro repositories (ie ubuntu 18.04 opensc version 0.17.0-03).

I'd be more than happy to provide logs/such if needed.

**Comment by popovec** [comment]
I am not sure if this is similar or different error.. I have problem to upload keys into MyEID card (opensc from git/master branch). After I have downgraded `src/libopensc/sc.c`  to commit 0abe9d11c75f8d9de32e862a5a9775aa70a44cc3, key upload is functional again.

Seems, there is wrong function `sc_hex_to_bin()`, new code need hex string for example "0F\0" not only "F\0".

@SohamG can you check OpenSC from master, with backported sc.c file (git checkout master;git checkout  0abe9d11c75f8d9de32e862a5a9775aa70a44cc3 src/libopensc/sc.c) ?

@frankmorgner can you please review commit fd20ffe6081c3bc4b0c207f16787f353cd21c61f ? 
Is function  `sc_hex_to_bin()` really correct? If input to this function is string "1\0" then return value is `SC_ERROR_INVALID_ARGUMENTS`. IMHO, this hex string is valid, and function must return `SC_SUCCESS`

**Comment by dengert** [comment]
Using GDB with commands (/opt/ossl-1.1/bin is where I installed it):
`gdb --args /opt/ossl-1.1/bin/opensc-tool -c default -s "3"`
and setting `break sc_hex_to_bin` then `run` then single steping show `sc_hex_to_bin` returns SC_ERROR_INVALID_ARGUMENTS and does not set out or outlen. The loop does not accounf for a single digit input correctly. 

Doing the same with:
`gdb --args /opt/ossl-1.1/bin/opensc-tool -c default -s "03"`
shows`sc_hex_to_bin` sets out[0]=0x03 and outlen=1 and returns 0 as expected. 

So any single digit use of `sc_hex_to_bin` will fail. 

`opensc-tool` was chosen as a simple test of  `sc_hex_to_bin` with any number of digits.
`sc_bytes2apdu` will fail as a single digit is not a valid APDU.
```
521                 sc_hex_to_bin(opt_apdus[c], buf, &len0);
522 
523                 r = sc_bytes2apdu(card->ctx, buf, len0, &apdu);
```

**Comment by frankmorgner** [comment]
Actually, this behavior was intended to force hexed bytes to be two characters long. However, I've overlooked a special case in the old code that allows a single character (without separator or whitespace!) to be parsed as expected. I'll try to add this to the new code.

**Comment by frankmorgner** [comment]
Thanks for the analysis, Doug! A fix is available here https://github.com/OpenSC/OpenSC/pull/1685.
