### ISSUE TITLE
Getting 'No slot with a token was found' for ePass2003Auto

### ISSUE THREAD

**Issue by abrbhat** [OpenSC/OpenSC#1670]
### Problem Description

I am new to PKCS11 and using Smartcards for signing. I have got a ePass2003Auto with loaded certificate and key. I am trying to use pkcs11-tool to sign some data but keep getting the error 
'No slot with a token was found'. I am not sure how to resolve it. Any help is much appreciated!

Here are some commands that I ran and their outputs:
https://gist.github.com/abrbhat/e60a096e87ef3f0e4f44657e13959678

Thanks!

@FeitianSmartcardReader

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader any updates?

**Comment by singhtej1981** [comment]
Hello Amit,

We are using ePass2003Auto token to generate keypair and CSR. Could you please advise how to achieve this using OpenSC libraries either in Windows or CentOS (we are open to platform), whichever is easier/known method. 

I have tried configuring in both environments but facing the same message as below:

**CentOS**:
[root@localhost ~]# pkcs11-tool --module /usr/lib/ePass2003-Linux-x64/x86_64/redist/libcastle_v2.so.1.0.0 --login --pin 12345678 -k --id 10 --label "Test key" --key-type rsa:2048 --read-object --id 10 --type pubkey --output-file pub.spki
No slot with a token was found.
[root@localhost ~]#

**Windows**:
error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.

It would be a great help as we need to implement this urgently. Appreciate if any good literature could be shared that works with PHP. We have openssl, opensc-pkcs11.dll, libp11.dll, eps2003csp11.dll available with us for Win64. So, it is possible to use command line in PHP but the step-by-step technical flow is not known to us.

Best Regards,
Tejinder

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by singhtej1981** [comment]
> @FeitianSmartcardReader ?

Hello, I have posted this issue as I am facing the same problem. Can you please advise how should we get the slots and proceed for key pair generation in token.

Best Regards,
Tejinder

**Comment by dengert** [comment]
@singhtej1981 Note: Your are using the Fetian pkcs11 module, `/usr/lib/ePass2003-Linux-x64/x86_64/redist/libcastle_v2.so.1.0.0`  not OpenSC, you need to contact them **OR** try the OpenSC -pkcs11 module which is the default for the OpenSC pkcs11-tool.   The module and libs it is linked with communicate with the pcscd daemon.  Make sure pcscd it is running. 

Also start with opensc-tool:
```
No Git revision info available
OpenSC 0.17.0 [gcc  7.3.0]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
```
If it detects the reader and says `yes` with token try:
`opensc-tool -a` if that does not work try `opensc-tool -c default -a`

Then try `pkcs11-tool -O` to list objects.

**Comment by FeitianSmartcardReader** [comment]
> > @FeitianSmartcardReader ?
> 
> Hello, I have posted this issue as I am facing the same problem. Can you please advise how should we get the slots and proceed for key pair generation in token.
> 
> Best Regards,
> Tejinder

@singhtej1981 sorry for my late reply, you are using our private P11 lib, please send mail to hongbin@ftsafe.com, and I will forward to right person contact you, and from the behaviour, looks the lib hasn't detect your token, can please run lsusb show me your VID and PID, better send mail to me, since the issue not relate of OpenSC, thanks
