### ISSUE TITLE
MacOS: Agent refused after resuming from sleep

### ISSUE THREAD

**Issue by clong** [OpenSC/OpenSC#1675]
### Problem Description

OS: (MacOS 10.14.4 - 2017 MacBook Pro 13-inch) 

This issue is largely a carryover from https://github.com/OpenSC/OpenSC/issues/1060 which was closed without resolution due to what appears to be a lack of debug logs. 

After a fresh reboot everything works fine. After it has slept for awhile, I'm unable to add my key any under circumstances and opensc tools are unable to detect it and hang.

For me, it appears that everything is hanging after `reader-pcsc.c:1070:detect_reader_features: Requesting reader features ...` in the debug logs.

### Proposed Resolution

I'm unsure of what the exact problem is, so I can't suggest any resolutions

### Steps to reproduce

1. Reboot
2. Successfully add smartcard to agent via:
```
     eval $(ssh-agent -t 1d -P /usr/local/lib/opensc-pkcs11.so)
     ssh-add -s /usr/local/lib/opensc-pkcs11.so
```
3. Put computer to sleep for awhile
4. Wake computer
5. Yubikey no longer responds to anything and gives `agent refused operation` messages. `opensc-tool -l` hangs indefinitely. Unplugging and replugging in the key doesn't make any difference.

Things I've tried with no luck:
- Using brew's openssh tools
- Unplugging/replugging
- Disabling SIP entirely
- Changing which USB port the yubikey is plugged into

### Logs
Running ssh-agent in debug mode:
```
$ ssh-agent -d -a ~/.agent.socket
SSH_AUTH_SOCK=/Users/clong/.agent.socket; export SSH_AUTH_SOCK;
echo Agent pid 13430;
debug2: fd 3 setting O_NONBLOCK
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 20
debug1: process_add_smartcard_key: add /usr/local/lib/opensc-pkcs11.so
```
Other window where it's being added:
```
$ SSH_AUTH_SOCK="/Users/clong/.agent.socket" ssh-add -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11:
<hangs after passcode added>
```

Debug logs from opensc-debug.txt:
```
0x114c755c0 10:54:41.939 [opensc-pkcs11] ctx.c:831:sc_context_create: ===================================
0x114c755c0 10:54:41.940 [opensc-pkcs11] ctx.c:832:sc_context_create: opensc version: 0.19.0
0x114c755c0 10:54:41.940 [opensc-pkcs11] reader-pcsc.c:819:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
0x114c755c0 10:54:41.942 [opensc-pkcs11] reader-pcsc.c:1300:pcsc_detect_readers: called
0x114c755c0 10:54:41.942 [opensc-pkcs11] reader-pcsc.c:1313:pcsc_detect_readers: Probing PC/SC readers
0x114c755c0 10:54:41.942 [opensc-pkcs11] reader-pcsc.c:1341:pcsc_detect_readers: Establish PC/SC context
0x114c755c0 10:54:41.969 [opensc-pkcs11] reader-pcsc.c:1257:pcsc_add_reader: Adding new PC/SC reader 'Yubico Yubikey 4 OTP+U2F+CCID 01'
0x114c755c0 10:54:41.969 [opensc-pkcs11] reader-pcsc.c:320:refresh_attributes: Yubico Yubikey 4 OTP+U2F+CCID 01 check
0x114c755c0 10:54:41.972 [opensc-pkcs11] reader-pcsc.c:348:refresh_attributes: current  state: 0x00000012
0x114c755c0 10:54:41.972 [opensc-pkcs11] reader-pcsc.c:349:refresh_attributes: previous state: 0x00000000
0x114c755c0 10:54:41.972 [opensc-pkcs11] reader-pcsc.c:404:refresh_attributes: card absent
0x114c755c0 10:54:41.973 [opensc-pkcs11] reader-pcsc.c:1421:pcsc_detect_readers: Yubico Yubikey 4 OTP+U2F+CCID 01:SCardConnect(DIRECT): 0x00000000
0x114c755c0 10:54:41.973 [opensc-pkcs11] reader-pcsc.c:1068:detect_reader_features: called
0x114c755c0 10:54:41.974 [opensc-pkcs11] reader-pcsc.c:1070:detect_reader_features: Requesting reader features ...
```

**Comment by frankmorgner** [comment]
Your system hangs when calling [SCardControl](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1102). Most likely, this is a problem in Apple's driver (PC/SC, CTK or libccid) or Yubico's hardware.

Try to reproduce the problem with [this example](https://github.com/LudovicRousseau/CCID/blob/master/examples/scardcontrol.c), which is independant from OpenSC. Try to suspend the program at various points of execution for reproducing the problem by using some calls to `sleep()`. This example should then be added to the bug report at Yubico and Apple.

Maybe @LudovicRousseau wants to have a look at this.

**Comment by LudovicRousseau** [comment]
You can generate smart card logs as documented in https://ludovicrousseau.blogspot.com/2017/11/debug-smart-card-application-on-sierra.html
```
sudo log config --mode "private_data:on"
log stream --predicate 'process == "com.apple.ifdreader"' --debug
```
Maybe the logs will show something useful.

**Comment by clong** [comment]
Oddly enough this seems to have resolved itself after I reset the NVRAM on my host. I also removed the brew installed libusb while compiling https://github.com/LudovicRousseau/CCID/blob/master/examples/scardcontrol.c , so I'm not sure if that may have had something to do with it as well. I'm no longer having this issue, so I'll go ahead and close this.

**Comment by clong** [comment]
One more quick update here - I believe the root cause for this was actually an issue with ifdreader on MacOS. I ran into this problem again today and noticed that the MacOS logs generated with `log stream` were from a PID mapping to ifdreader:
```
2019-05-29 14:10:02.540962-0700 0x15b47c   Debug       0x0                  285    0    com.apple.ifdreader: (CryptoTokenKit) [com.apple.CryptoTokenKit:token] Yubico Yubikey 4 OTP+U2F+CCID: slot was set up
```

However, no yubikey was plugged in while that was running. I restarted ifdreader using these instructions and everything works as expected again: https://ludovicrousseau.blogspot.com/2015/02/debug-smart-card-reader-driver-on.html

**Comment by frankmorgner** [comment]
Thanks for the update. Maybe you could report this problem to Apple...
