### ISSUE TITLE
help w/ SmartCafe Expert 7 card

### ISSUE THREAD

**Issue by ebbimish** [OpenSC/OpenSC#1676]
### Problem Description

I am new to the world of smart cards.  I apologize in advance if I'm mistaken in my terminology or the location I'm posting this question in.

I have a Xilinx ZCU102 dev board running petalinux w/ OpenSC.  I've got a USB smartcard reader attached to the board with a G&D SmartCafe 7 card.  The G&D is running an applet that simply outputs a 16-byte random number on command.  This behavior has been confirmed on a Maxim dev board (i.e. we know for a fact the applet works and outputs the random number).  The difference is that the Maxim dev board isn't using OpenSC with a USB smartcard reader, but rather some higher level drivers meant for interfacing with smartcards along w/ a standardized smartcard interface (i.e. no USB).  However, I have the APDU commands it outputs to the smartcard.

The card responds to an ATR request using the default driver, so I edited opensc.conf and added the ATR as a new card and forced it to use the default driver and forced the protocol to T0 (which is correct for this particular card).  I next send the following APDU to choose the applet:
# opensc-tool -c default --send-apdu "00 a4 04 00 0e d1 76 00 00 04 15 ff 80 00 00 07 00 04 04 00"
Using reader with a card: CCID Compatible
Sending: 00 A4 04 00 0E D1 76 00 00 04 15 FF 80 00 00 07 00 04 04 00
Received (SW1=0x90, SW2=0x00)

As you can see, that responds correctly.

Finally, I send a discrete command to give me the random number:
# opensc-tool -c default --send-apdu "80 84 00 00 10"
Using reader with a card: CCID Compatible
Sending: 80 84 00 00 10
Received (SW1=0x6D, SW2=0x00)

I've spent a couple days now debugging this and digging in and have come up empty handed...if there was something wrong w/ my message format or the USB interface, then I don't think the ATR or the first APDU command above would work.  I know this is a valid APDU...but the response is always 6D/00.

I again apologize if I have pasted this in the wrong place.  If that's the case, I would greatly appreciate direction as to where I can get help with this issue.  Thank you very much...

### Logs

../../../opensc-0.16.0/src/libopensc/sc.c:259:sc_detect_card_presence: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:182:openct_reader_detect_card_presence: called
../../../opensc-0.16.0/src/libopensc/sc.c:264:sc_detect_card_presence: returning with: 1
Using reader with a card: CCID Compatible
../../../opensc-0.16.0/src/libopensc/sc.c:259:sc_detect_card_presence: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:182:openct_reader_detect_card_presence: called
../../../opensc-0.16.0/src/libopensc/sc.c:264:sc_detect_card_presence: returning with: 1
Connecting to card in reader CCID Compatible...
../../../opensc-0.16.0/src/libopensc/card.c:196:sc_connect_card: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:208:openct_reader_connect: called
../../../opensc-0.16.0/src/libopensc/card-default.c:47:default_init: called
../../../opensc-0.16.0/src/libopensc/card-default.c:52:default_init: returning with: 0 (Success)
../../../opensc-0.16.0/src/libopensc/card.c:307:sc_connect_card: card info name:'Unsupported card', type:-1, flags:0x0, max_send/recv_size:255/256
../../../opensc-0.16.0/src/libopensc/card.c:1330:sc_card_sm_check: called
../../../opensc-0.16.0/src/libopensc/card.c:1331:sc_card_sm_check: card->sm_ctx.ops.open (nil)
../../../opensc-0.16.0/src/libopensc/card.c:978:match_atr_table: ATR     : 3b:f9:96:00:00:80:31:fe:45:53:43:45:37:20:00:00:20:20:27
../../../opensc-0.16.0/src/libopensc/card.c:989:match_atr_table: ATR try : 3b:f9:96:00:00:80:31:fe:45:53:43:45:37:20:00:00:20:20:27
../../../opensc-0.16.0/src/libopensc/card.c:1339:sc_card_sm_check: returning with: 0 (Success)
../../../opensc-0.16.0/src/libopensc/card.c:319:sc_connect_card: returning with: 0 (Success)
Using card driver Default driver for unknown cards.
../../../opensc-0.16.0/src/libopensc/card.c:394:sc_lock: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:402:openct_reader_lock: called
../../../opensc-0.16.0/src/libopensc/apdu.c:749:sc_bytes2apdu: Case 2 short APDU, 5 bytes:      ins=84 p1=00 p2=00 lc=0000 le=0010
Sending: 80 84 00 00 10
../../../opensc-0.16.0/src/libopensc/apdu.c:550:sc_transmit_apdu: called
../../../opensc-0.16.0/src/libopensc/card.c:394:sc_lock: called
../../../opensc-0.16.0/src/libopensc/apdu.c:517:sc_transmit: called
../../../opensc-0.16.0/src/libopensc/apdu.c:371:sc_single_transmit: called
../../../opensc-0.16.0/src/libopensc/apdu.c:376:sc_single_transmit: CLA:80, INS:84, P1:0, P2:0, data(0) (nil)
../../../opensc-0.16.0/src/libopensc/reader-openct.c:311:openct_reader_transmit:
Outgoing APDU (5 bytes):
80 84 00 00 10 .....
../../../opensc-0.16.0/src/libopensc/reader-openct.c:319:openct_reader_transmit:
Incoming APDU (2 bytes):
6D 00 m.
../../../opensc-0.16.0/src/libopensc/apdu.c:386:sc_single_transmit: returning with: 0 (Success)
../../../opensc-0.16.0/src/libopensc/apdu.c:539:sc_transmit: returning with: 0 (Success)
../../../opensc-0.16.0/src/libopensc/card.c:434:sc_unlock: called
Received (SW1=0x6D, SW2=0x00)
../../../opensc-0.16.0/src/libopensc/card.c:434:sc_unlock: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:431:openct_reader_unlock: called
../../../opensc-0.16.0/src/libopensc/card.c:336:sc_disconnect_card: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:257:openct_reader_disconnect: called
../../../opensc-0.16.0/src/libopensc/card.c:357:sc_disconnect_card: returning with: 0 (Success)
../../../opensc-0.16.0/src/libopensc/ctx.c:842:sc_release_context: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:162:openct_reader_release: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:162:openct_reader_release: called
../../../opensc-0.16.0/src/libopensc/reader-openct.c:149:openct_reader_finish: called

**Comment by CardContact** [comment]
Because the card is reset during each invocation, the first SELECT APDU has no effect, thus in the second command you send the GENERATE RANDOM APDU to the default selected applet (probably the card manager), which doesn't understand it.

Try sending the APDUs in the same command with multiple --send-apdu parameter.

**Comment by ebbimish** [comment]
HA!!!  That worked!!!

Thank you SO MUCH!!!

How did you know the card was being reset during each invocation?  Is that standard for smartcards or were you able to tell from the log I pasted?  Again, thank you so much.

**Comment by CardContact** [comment]
Our own card (SmartCard-HSM) is a Java Card and 6D 00 usually means that the command has not reached the applet.
