### ISSUE TITLE
RSA_PKCS_OAEP support for opengpg?

### ISSUE THREAD

**Issue by LinkTed** [OpenSC/OpenSC#1678]
### Problem Description
I use a opengpg card (Nitrokey) and try to decrypt a file with opensc pkcs11 module with the  RSA_PKCS_OAEP mechanism:
```
$ pkcs11-tool --id 02 --decrypt -p 123456 -m RSA-PKCS-OAEP  --input-file test                                  
Using slot 0 with a present token (0x0)
Using decrypt algorithm RSA-PKCS-OAEP
OAEP parameters: hashAlg=SHA-1, mgf=MGF1-SHA1, source_type=0, source_ptr=(nil), source_len=0
error: PKCS11 function C_DecryptInit failed: rv = CKR_MECHANISM_INVALID (0x70)
```
It seems that the operngpg driver does not support that. 
Should the driver support OAEP, because there is no other safe alternativemechanism  which I can use? The only decrypt mechanism is RSA_PKCS:
```
$ pkcs11-tool --id 02 -M                                                                                         1 ↵
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  RSA-PKCS, keySize={4096,4096}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA256-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA384-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA512-RSA-PKCS, keySize={4096,4096}, sign, verify
  MD5-RSA-PKCS, keySize={4096,4096}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={4096,4096}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={4096,4096}, generate_key_pair
```
Is there any reason why the OAEP mechanism is not implemented?
### Proposed Resolution
Implement OAEP mechanism.

**Comment by szszszsz** [comment]
Hi!
This might be solved with #1600. Have you tried nightly build?

**Comment by LinkTed** [comment]
Hi,
i not tried the nightly build. I will try it and notify you if it has work.

Thanks

**Comment by LinkTed** [comment]
Hi,
i tried it with [Nightly-2019-06-03_3a192e2c](https://github.com/OpenSC/Nightly/tree/2019-06-03_3a192e2c), but only `RSA-PKCS` was available for decryption algorithm:
```
$ pkcs11-tool --id 02 -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA224, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  RSA-PKCS, keySize={4096,4096}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA224-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA256-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA384-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA512-RSA-PKCS, keySize={4096,4096}, sign, verify
  MD5-RSA-PKCS, keySize={4096,4096}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={4096,4096}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={4096,4096}, generate_key_pair
```

**Comment by Jakuje** [comment]
Searching through the OpenPGP card specification, there is no mention of OAEP:

https://openpgpcard.org/resources/openpgp-card-3.3.pdf

Generally, there is no support for OAEP decryption in the OpenSC PKCS #11 module and RSA-PSS was added just recently. But if the card does not support this scheme and does not support the RAW-RSA either, there is nothing OpenSC could do for you.

**Comment by LinkTed** [comment]
Thank you for the information. I did not know that.

**Comment by zachliu** [comment]
afaik, [OpenPGP](https://www.rfc-editor.org/rfc/rfc4880) itself doesn't support OAEP.

**Comment by popovec** [comment]
OAEP is already available for all cards that support RAW RSA operation. 

https://github.com/OpenSC/OpenSC/pull/2475
https://github.com/OpenSC/OpenSC/pull/2484

**Comment by zachliu** [comment]
yeah :+1:  i meant the original standard
