### ISSUE TITLE
Link Broken http://pcsclite.alioth.debian.org/section.html

### ISSUE THREAD

**Issue by amitkumar50** [OpenSC/OpenSC#1679]
### Problem Description
On page:
https://github.com/OpenSC/OpenSC/wiki/Smart-card-readers-%28Linux-and-Mac-OS-X%29

Link in CCID section:
http://pcsclite.alioth.debian.org/section.html..  is broken.

**Comment by frankmorgner** [comment]
As with all Wikis, feel free to fix this.

**Comment by suttod** [comment]
External links updated on the referred wiki page.

**Comment by frankmorgner** [comment]
thanks!
