### ISSUE TITLE
Data object read failed: Security status not satisfied

### ISSUE THREAD

**Issue by nunojpg** [OpenSC/OpenSC#1684]
Since fd20ffe6081c3bc4b0c207f16787f353cd21c61f, I get error "Data object read failed: Security status not satisfied" when reading a object that requires authentication. Eg on my pteid:

./src/tools/pkcs15-tool --dump

Before this commit:

...
Data object 'Citizen Address Data'
	applicationName: Citizen Address Data
	Path:            3f005f00ef05
	Auth ID:         03
...

After this commit:

...
Data object 'Citizen Address Data'
	applicationName: Citizen Address Data
	Path:            3f005f00ef05
Data object read failed: Security status not satisfied
...

Thanks,
Nuno

**Comment by nunojpg** [comment]
@frankmorgner

**Comment by dengert** [comment]
May be problem in `sc_hex_to_bin` with single digit ID number such as `3` rather then `03`. See #1659

**Comment by popovec** [comment]
Please check my last comment in #1669 - this seems to be a similar problem.

**Comment by popovec** [comment]
I tested this patch, key upload to MyEID card  was fixed by this patch.
