### ISSUE TITLE
GlobalSign smart card enrollment not working

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#1688]
### Problem Description

As described [here](https://support.nitrokey.com/t/globalsign-no-cryptographic-service-provider-listed-nitrokey-hsm2-install-cert-via-csp-in-internet-explorer/1791), certificate enrollment using Internet Explorer does no work with OpenSC.

Most common causes are already ruled out, but maybe someone has a working setup or a test service that can be used to further diagnose the root cause of the problem.

### Steps to reproduce

Enroll for a GlobalSign e-mail certificate

### Logs

[log](https://gist.github.com/CardContact/6dd9af7f090b254c3f9b334d63af36ec)

**Comment by szszszsz** [comment]
cc @alex-nitrokey @jans23

**Comment by frankmorgner** [comment]
please try #1685

**Comment by shivan** [comment]
Tried that. Now I get one step further. I can enter the pin. But it stops here:

![image](https://user-images.githubusercontent.com/1827692/58784738-68468300-85e4-11e9-9c76-01251d62c733.png)

Can be reproduced with free 30 day mail certificates, using Microsoft Internet Explorer at:
https://secure.comodo.net/products/frontpage?area=SecureEmailCertificate

**Comment by szszszsz** [comment]
Linking here additional logs from the discussion on the forum: [logs]

[logs]: https://ametrasrentconcept-my.sharepoint.com/personal/markus_stein_remoso_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmarkus%5Fstein%5Fremoso%5Fcom%2FDocuments%2FHSM%2Fmd%2Dmaster%2Dbuild%2Elog&parent=%2Fpersonal%2Fmarkus%5Fstein%5Fremoso%5Fcom%2FDocuments%2FHSM&cid=69602225-df7a-4a29-92f1-8c67bf6197a9

**Comment by frankmorgner** [comment]
@szszszsz seems to require some MS account

**Comment by szszszsz** [comment]
Works for me. Perhaps Javascript / some browser extension? I will reupload it to Github in a minute.

**Comment by shivan** [comment]
Any useful informations in the log?

**Comment by shivan** [comment]
Hi,

I currently cannot see any progress on that issue since 20 days.

Is there anything missing from my side? Or can I do anything else to support?

**Comment by Jakuje** [comment]
Do you see some errors related to smart cars in the "event log" of windows?

**Comment by shivan** [comment]
Hi,

nothing at 

- application
- security
- system

:-(

I read for event logging this must be enabled first, according to: https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/enabling-smart-card-event-logging-in-the-registry, but here do we really have a smart card driver in ".sys" format? As I can see, there is only the minidriver dll?!

**Comment by frankmorgner** [comment]
low level OpenSC log messages are only captured with something like `debug = 3;` in `opensc.conf`. Maybe this shows the problem?

In the md log, there's the following:
```
HANDLES CHANGED from 0x00000002 0x00000000
```
This causes the card to be reinitialized, which may destroy some state of the card that's needed for making the change persistent on the card...

**Comment by shivan** [comment]
Hi,

so I changed the opensc.conf and uncommented

    debug = 3;
    debug_file = opensc-debug.txt;

and set in the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\OpenSC Project\OpenSC` the value `MiniDriverDebug=1`

But where is that opensc-debug.txt ? It is not in c:\tmp there I only have the md.log there.

Attached the file.
[md-debug3.log](https://github.com/OpenSC/OpenSC/files/3349290/md-debug3.log)

**Comment by frankmorgner** [comment]
That depends on the working directory of your process :wink: . On Windows, you may want to use an absolute path.

**Comment by frankmorgner** [comment]
You may also want to wipe your PIN from the log...

**Comment by shivan** [comment]
Ok, tried now with

    debug_file = "C:/tmp/opensc-debug.txt";

and got a log file. See attached. I could not find the PIN there. Neither in decimal nor in hex. Maybe that is because in the last test I even had not to enter it, as it was unlocked from the previous test.

[opensc-debug-level-3.txt](https://github.com/OpenSC/OpenSC/files/3349794/opensc-debug-level-3.txt)

**Comment by dengert** [comment]
I see a lot of `card-sc-hsm.c:719:sc_hsm_pin_cmd: Verification failed: -1216 (Data object not found)`
for `00 20 00 85` and `00 20 00 86` commands. Has the card been initialized yet? Has the PIN been set on the card yet? 

Is this an issue with the `Nitrokey Nitrokey HSM 0` card?

**Comment by frankmorgner** [comment]
85/86 is a special PIN object for on-card-finger-print comparison that's optional.

**Comment by shivan** [comment]
@dengert: Card has been initialized and pin has been set. 

I already added a private key and self signed certificate manually. And I also was able to use that successfully in the signing process of jarsigner and signtool.

So I would say, the token is set up correctly.

Yes, the device is `Nitrokey Nitrokey HSM 0`

**Comment by shivan** [comment]
Any news here?

**Comment by dogweather** [comment]
@frankmorgner This is holding up the `0.20.0` release, but there's no plan for it. What do you think about removing it from release cycles until it can be confirmed and a dev plan made?
I'd like to help get 0.20.0 out the door.

**Comment by dengert** [comment]
https://github.com/OpenSC/OpenSC/issues/1688#issuecomment-507245639 says:
https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/enabling-smart-card-event-logging-in-the-registry  "but here do we really have a smart card driver in ".sys" format? As I can see, there is only the minidriver dll?!"   

I read this as: Define path to a "%SystemRoot%\System32\Drivers\SmartCardDriver.sys.sys" file which will be the event log.  It is warning the if the file exists for some other reasons, it will be overwritten. And "SmartCardDriver" would be "opensc-minidriver" or maybe in your system it is "minidriver"
 So path would be:
 "%SystemRoot%\System32\Drivers\opensc-minidriver.sys"

(I have not tried this.)
Can you try to get the an event log?

**Comment by dengert** [comment]
Please disregard the comments above about the event log. It will not work.  

Would an approach similar to https://github.com/OpenSC/OpenSC/issues/1763#issuecomment-526842531 work for you?

**Comment by shivan** [comment]
As there is no copy and paste possible, sorry no.
It is only possible to enroll a certificate through that active x control. 
But I wonder why it is so hard to fix, as it is very easy to reproduce (at no cost)

**Comment by dengert** [comment]
It hard to fix if one does not have the environment or card to reproduce the problem. The fact that Microsoft does not support the Active X controls in Edge looks like they may be dropping this capability.  

Using a nighty build https://github.com/OpenSC/Nightly/tree/2019-08-30_f6213051,  32 and 64 bit and an older SmartCard-HSM,  I have gotten to the point where "Windows Security" Smart Card" says"The smart card is read-only".  

The issues Comodo had and selling off parts of the company and name change to Sectigo  make it confusing.

**Comment by dengert** [comment]
I have not gotten anywhere on this problem and not able to spend anymore time on it. I agree with https://github.com/OpenSC/OpenSC/issues/1688#issuecomment-526391687 

There is an alternative to a "cut-and-paste" option that could be used. Request a certificate that loads the key into the software certstore. Mark it as exportable. Export the certificate and private key. Use other utilities to load the key and certificate on the smart card. But this may not meet your security requirements. 

Testing was done using a recent branch from https://github.com/OpenSC/Nightly/branches  `2019-08-30_6f40e9c5`. Both 64 and 32 bit on Windows 10. 64 bit. Also tried on a 32 bit Windows 10.  with `opensc.conf`:
```
app default {
	# debug = 3;
	debug = 3;
	debug_file = c:\tmp\opensc-debug.txt;
	# debug_file = opensc-debug.txt;
	
	# SmartCard-HSM 
	card_atr  3b:fe:18:00:00:81:31:fe:45:80:31:81:54:48:53:4d:31:73:80:21:40:81:07:fa {
		driver = "sc-hsm";
		read_only = false;
		md_read_only = false;
		md_supports_X509_enrollment = true;
		md_supports_container_key_gen = true;
		md_guid_as_label = true;
	}
	
	framework pkcs15 {
		# use_file_caching = true;
	}
}
```

Looking at the logs, I only see a call to CardGetProperty('Read Only Mode',cbData=4,dwFlags=0) once from `CertEnrollCtrl.exe` so it looks OK as it returns:
```
returns 'Read Only Mode' --- 000001D04EB77120:4
 0000  00000000 
```
So why it still says card is read only is not clear. 

Some things that could be looked at include:
- In registry for `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Defaults\Provider\Microsoft Base Smart Card Crypto Provider`
TransactionTimeoutMilliseconds      000005dc (1500  1.5 seconds) Is this to short?

- In registry `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Defaults\Provider\OpenSC CSP` should it have copies of all the name=value pairs from `Microsoft Base Smart Card Crypto Provider`

- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/smart-cards/smart-card-debugging-information.md has some interesting debugginh info. 

- https://github.com/OpenSC/OpenSC/blob/master/src/minidriver/minidriver.c#L422 may be overly protective. If just the `pCardData->hScard != vs->hScard` has changed, maybe just the new handle should be used without calling `reinit_card_for()` as this might be a different thread calling the minidriver. Better debugging messages would be needed. 

- Testing with Comodo or GlobalSign with a non OpenSC card should be done. I do not have such a card. The only "non read only" card I have is the one listed above.

**Comment by shivan** [comment]
> Request a certificate that loads the key into the software certstore. Mark it as exportable. Export the certificate and private key. Use other utilities to load the key and certificate on the smart card. But this may not meet your security requirements.

You're right, globalsign does not allow selecting a software provider. And the "Minimum Requirements for the Issuance and Management of Publicly-Trusted Code Signing Certificates" (https://casecurity.org/wp-content/uploads/2016/09/Minimum-requirements-for-the-Issuance-and-Management-of-code-signing.pdf) state on chapter "16.3 Subscriber Private Key Protection" that a hardware crypto module must be used. So the CAs aren't able to allow software key stores.

Using a Gemalto eToken 5110 the enrollment works without problems, but this token is extremely slow. And that is why I want to switch to another token. The nitrokey is much much faster. (tried with self signed code sign certificate)

**Comment by jans23** [comment]
For reference, the best workaround seems to be using a different browser. [See here](https://support.globalsign.com/customer/en/portal/articles/2374828-in-browser-installation-of-client-certificates). Note that this doesn't solve this issue but is a workaround only.

**Comment by shivan** [comment]
Hey, great idea. I did not know that firefox is supported, too. I thought only IE.

I'll try with firefox.

**Comment by shivan** [comment]
Hi,

that seems to be a wrong information on that documentation page.

Using latest firefox, it tells me:
![image](https://user-images.githubusercontent.com/1827692/64696436-b0f0c080-d49e-11e9-8f60-510f6a613eb4.png)
... my browser is not supported and I have to use IE.

**Comment by jans23** [comment]
@shivan please ask GlobalSign.

**Comment by shivan** [comment]
Ok, now new way. Globalsign allows to generate Codesign EV certificates via CSR.

But now I fail on generating a CSR. 
I tried:

```
openssl
OpenSSL>engine dynamic -pre ID:pkcs11 -pre SO_PATH:c:\windows\system32\engine_pkcs11.dll -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:c:\windows\system32\opensc-pkcs11.dll
```

But I don't have a file named engine_pkcs11.dll.

**Comment by dengert** [comment]
engine_pkcs11.dll is part of libp11. See:

https://github.com/OpenSC/libp11/blob/master/INSTALL.md

**Comment by shivan** [comment]
Great. 

I was able to compile 0.4.10 (downloaded from latest release - https://github.com/OpenSC/libp11/releases) with x64 native command prompt for visual studio with

    nmake -f Makefile.mak OPENSSL_DIR=C:\OpenSSL-Win64 BUILD_FOR=WIN64

Then I got the pkcs11.dll.
And now OpenSSL was able to load the dlls.

    engine dynamic -pre ID:pkcs11 -pre SO_PATH:C:\Tools\pkcs11\pkcs11.dll -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\Tools\pkcs11\opensc-pkcs11.dll

and with something like that, I was able to create a test CSR

    
    req -engine pkcs11 -new -key xxxxxx -keyform engine -out c:\temp\CodeSign.csr -text

But that only worked with a private key with a long id. A private key with id 01 or 02 however did not work.

:smile:

Now I'm a big step further and can continue...

**Comment by frankmorgner** [comment]
@shivan could you check whether the changes from https://github.com/OpenSC/OpenSC/pull/1848 make any difference when enrolling with IE?

**Comment by shivan** [comment]
I think there is no chance for a solution via IE browser. I solved it by ordering a HSM certificate (my used token fulfilled the requirements). So I was able to send globalsign my csr and they return me the certificate.

All must be done via commandline, but it then works. So issue can be closed.
