### ISSUE TITLE
Emulating a security chip using ARM TrustZone.

### ISSUE THREAD

**Issue by jonsmirl** [OpenSC/OpenSC#1690]
Most current ARM CPUs (not microcontrollers) support ARM TrustZone.  TrustZone is a mechanism for running code in a hardware protected environment. For example it is used in every Android phone for secure key storage. The main project for the code: https://github.com/OP-TEE/optee_os

Lately the various Cloud IOT services (Google, AWS, Azure, Baidu) have been pushing for everyone to increase their login security by using hardware security chips. For example the ATECC608. These chips work, but they cost money.  

So a proposal has been made to use ARM TrustZone to provide similar services to a hardware chip.  Initial work on a Linux implementation has started here, user space library.  https://github.com/etienne-lms/optee_client/tree/sks/libsks   and here, trusted application (TA) https://github.com/etienne-lms/optee_os/tree/sks/ta/secure_key_services

The user space library implements the PKCS#11 API so that it can be used from OpenSSL.  The TA (trusted app) has started implementing some of the necessary features. 

The problem is that none of us are encryption experts and we have no knowledge of PKCS#11. And the Cloud IOT vendors are all asking for ECC support.

1) Can OpenSC function as the user space PKCS#11 library?
2) Does it work to think of the TA as a smart card equivalent?
2) What is the minimal API that the Trust App would need to implement?

optee supports the Raspberry Pi. So hardware is easily accessible.
https://blog.crysys.hu/2018/06/op-tee-default-build-and-installation-on-the-raspberry-pi/
how to fix for 3B+
https://github.com/dkarnikis/rpi3bplus-optee

**Comment by CardContact** [comment]
OpenSC as a middleware exposes functionality available at the ISO 7816-4 interface of a modern smart card via a PKCS#11 abstraction. It does this with three layers,

* a PKCS#11 layer at the top,
* a PKCS#15 layer in the middle and
* a card driver layer at the botton.

While PKCS#11 is the API, PKCS#15 defines the encoding of meta-data that describes keys and other meta data on a smart card. The card driver layer unifies variations in the implementation of ISO 7816-4.

The ISO 7816-4 API is pretty restricted, as it allows only small data units (called APDUs) to be exchanged with the chip. APDUs are in the range of 4 to 1K (some more, some less) and follow a command / response pattern.

If the interface to the TEE has a similar characteristic, then of course the TEE could implement a subset of ISO 7816 and PKCS#15 and have that exposed via OpenSC.

It would be something similar to the SmartCard-HSM, which is a generic key store in a smart card that can be accessed using ISO 7816 APDUs. The command set is implemented in a card driver that exposes a file system containing the PKCS#15 meta data. This is picked up by the PKCS#15 framework and makes objects and operations available at the PKCS#11 layer.

**Comment by jonsmirl** [comment]
This is a minimal example of user space and a TA
https://github.com/linaro-swg/optee_examples/tree/master/hello_world/host

With the ATECC508 crytoauthlib support, cryptoauthlib implements PKCS#11. Then openssl uses libp11 to call it.  The IOT app uses openssl to establish a connection. The first step is a ECC exchange. The ATECC508 is used for that step via libp11. The output from that step is a per session DES/AES key. That DES/AES key is used with the SOC's encryption hardware for high speed exchange.

Does the OpenSC library work as a plug in for OpenSSL?

**Comment by frankmorgner** [comment]
- Yes, you could implement a "card driver" in OpenSC so that your security module is usable via all APIs that OpenSC implements (PKCS#11, minidriver, tokend).

- Yes, there are other PKCS#11 implementations for different kind of "security modules", e.g. https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-library-install.html or http://trousers.sourceforge.net/pkcs11.html and https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11, which you mentioned.

- The OpenSC projects maintains libp11, which implements engine_pkcs11 for OpenSSL. (However, OpenSSL has started to add native PKCS#11 support lately.)

- There is some PKCS#11 example code in pkcs11-tool.c or in src/p11test.

I'm not sure what your request actually is about.
