### ISSUE TITLE
Upload PR builds to Nightly

### ISSUE THREAD

**Issue by szszszsz** [OpenSC/OpenSC#1692]
### Problem Description

PR builds seem to not be uploaded anywhere, thus these cannot be tested quickly before merging, without setting up the development environment locally first.

### Proposed Resolution
Upload build artefacts to OpenSC Nightly.

Could be used instead of #1691 (for this purpose).

**Comment by frankmorgner** [comment]
I think its OK to only have builds of OpenSC/OpenSC in OpenSC/Nightly. PRs are available via the AppVeyor build artifact, again.
