### ISSUE TITLE
Abuse of SC_FUNC_CALLED?

### ISSUE THREAD

**Issue by nunojpg** [OpenSC/OpenSC#1698]
Since fbb4d1f84326b31d3b00f8a317389bd0d818f644, when calling pkcs-tool --verbose I get a arguably too verbose message:

P:6716; T:0x140409995595648 14:11:34.265 [pkcs15-tool] pkcs15-itacns.c:866:sc_pkcs15emu_itacns_init_ex: called

I wonder if this commit is just exposing the abuse of SC_FUNC_CALLED(card->ctx, 1) at pkcs15-itacns, and if this calls should be replaced with LOG_FUNC_CALLED(ctx);

If so I can submit a pull request.

**Comment by dengert** [comment]
`pkcs15-itacns.c` shoud not be using `SC_FUNC_CALLED(p15card->card->ctx, 1);`
It should use at least use `SC_FUNC_CALLED(card->ctx, SC_LOG_DEBUG_VERBOSE);` like 32 other `card-<driver>.c` or `pkcs15-<card>.c`  files do.

For some reason the base files and some driver related files use  `LOG_FUNC_CALLED(ctx);` where most driver  related files use `SC_FUNC_CALLED(card->ctx, SC_LOG_DEBUG_VERBOSE);`

```
cd libopensc
$ grep LOG_FUNC_CALLED * | wc
    507    1016   20283
grep SC_FUNC_CALLED * | wc
     226     682   14261
```

Another issue with https://github.com/OpenSC/OpenSC/commit/fbb4d1f84326b31d3b00f8a317389bd0d818f644
is some of the utilites had the line:
`if (verbose > 1 && ctx->debug == 0) {`

Would you consider changing  `src/tools/util.c to do the same thing?

**Comment by frankmorgner** [comment]
Feel free to fix this by consistently using the short version, `LOG_FUNC_CALLED(ctx);`. It's very unlikely that this information is needed by the average user that enables a medium debug level. Or quite the opposite, sometimes you want to make this information appear even with a higher log level, as done in `sm-common.c`, for example.

**Comment by frankmorgner** [comment]
@dengert control of the debug output has already been moved to [util.c](https://github.com/OpenSC/OpenSC/blob/master/src/tools/util.c#L62-L65).
