### ISSUE TITLE
Log return value in winscard_svc.h for debug purpose

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1700]
Hello, 
I was wondering if it would be possible to log the return value in winscard_svc.c while calling Client Die for debugging purposes ? Or is there a way to see that today ?
Thanks!

**Comment by frankmorgner** [comment]
Sorry, there is no `winscard_svc.c` in OpenSC. If you want to debug Windows' winscard service, you could try one of the various winscard.dll proxies or use something like https://www.mysmartlogon.com/download/#APDUTrace

**Comment by frankmorgner** [comment]
OpenSC's debug messages are written in reader-pcsc.c (which sometimes includes the PC/SC return value)
