### ISSUE TITLE
MyEID unable to upload EC key

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#1701]
### Problem Description

pkcs15-init  --store-private-key key.pem --auth-id=1 --pin XXXX  --key-usage sign
Failed to store private key: Wrong length

Opensc from git, commit 94388f9538e6ea1c1cd853663d8a14705398475a, MyEID card version 4.0.1  (Bug is MyEID specific, no other card are affected)

### Proposed Resolution

Partial revert of commit  3688dfe2382cfaf091fe3da17d7495013ca94e4a (MyEID: simplify key component loading), proposed patch below.

### Logs
````
Outgoing APDU (30 bytes):
00 DA 01 87 19 00 A5 53 13 D0 D0 14 7C D5 2D 16 .......S....|.-.
8B 3B C8 19 3A 68 9D D6 B4 69 69 FA A6 C9       .;..:h...ii...

Incoming APDU (2 bytes):
67 00 g.
````

Old, working  code send APDU:
````
00 DA 01 87 18  A5 53 13 D0 D0 14 7C D5 2D 8B 3B C8 19 3A 68 9D D6 B4 69 69 FA A6 C9
````

### FIX

````
diff --git a/src/libopensc/card-myeid.c b/src/libopensc/card-myeid.c
index f43add0d..717f459c 100644
--- a/src/libopensc/card-myeid.c
+++ b/src/libopensc/card-myeid.c
@@ -1478,6 +1478,11 @@ static int myeid_loadkey(sc_card_t *card, unsigned mode, u8* value, int value_le
                memset(&sbuf, 0, SC_MAX_APDU_BUFFER_SIZE);
                memcpy(sbuf,value + 128, value_len - 128);
        }
+       else if (mode == LOAD_KEY_EC_PUBLIC || mode == LOAD_KEY_EC_PRIVATE)
+       {
+               memcpy(sbuf, value, value_len);
+               len = value_len;
+       }
        else
        {
                memcpy(sbuf + len, value, value_len);
````

@fabled @hhonkanen  - please review.

**Comment by fabled** [comment]
Thanks for the report. I really hope this specialization is not needed. The problem seems to be in the code that adds the zero prefix. It probably should apply to RSA components only. Would the following patch fix the issue?
``` diff
--- a/src/libopensc/card-myeid.c
+++ b/src/libopensc/card-myeid.c
@@ -1444,8 +1444,7 @@ static int myeid_loadkey(sc_card_t *card, unsigned mode, u8* value, int value_le
                return 0;
 
        if (value[0] != 0x0 &&
-           mode     != LOAD_KEY_PUBLIC_EXPONENT &&
-           mode     != LOAD_KEY_SYMMETRIC)
+           ((mode & 0xff) == 0 && mode != LOAD_KEY_PUBLIC_EXPONENT))
                sbuf[len++] = 0x0;
 
        if (mode == LOAD_KEY_MODULUS && value_len == 256 && !priv->cap_chaining)
```

**Comment by popovec** [comment]
Patch  tested (opensc from git, commit 94388f9538e6ea1c1cd853663d8a14705398475a) - **OK**.
Please create PR ....

I tested RSA key upload (512,768,1024,1536,2048), key generate (only 1024 bit key), sign/decrypt with keys 512,768,1024,1536,2048 - **OK**. EC key generate/upload and sign with NIST 192/256 bit keys - **OK**. ECDH is still not working (waiting for #1677), but if I use patch proposed in #1609, ECDH pass all tests. AES 128 and 256 bit key upload - **OK**, 2DES/3DES  key upload - **OK**, 56/64 bit DES key upload failed, but this is for now not important.
