### ISSUE TITLE
CardOS 5.3 Decrypt Issue with Mac Outlook 2016

### ISSUE THREAD

**Issue by Ragnar-von-Detroit** [OpenSC/OpenSC#1703]
### Problem Description
All, has there been any solutions or work around with decrypting emails with CardOS 5.3 cards? Currently I can encrypt with OpenSC, but the decryption part isn't working. It says the public key is missing or invalid. It appears back in 2017 there was a lot of issues when the newer CardOS came out. I'm just curious if there has been any more development on this end? Also that if I could be of any help to try to resolve this?

Thanks,

**Comment by frankmorgner** [comment]
@Jakuje ?

**Comment by Jakuje** [comment]
This depends on what mechanism is being used. The cardos 5 supports only RSA with PKCS#1.5 padding on the card just fine. The CKM_RSA_X509 signature mechanism can be simply emulated using this by stripping the padding and doing the CKM_RSA_PKCS (if the padding is done by calling application), but this does not work for decryption (we do not know the potentially-random padding).

This popped up several times already that the current opensc api does not allow to express that the card supports only the padded signature & decryption so the mechanism list shows both of the mechanisms. I am not sure what mechanisms are used with Mac Outlook, but since the CardOS specification is nowhere to be found and nowhere close to open-source so I would not expect any breakouts here.

**Comment by frankmorgner** [comment]
@Jakuje , please have a look at [`pkcs15_prkey_can_do`](https://github.com/OpenSC/OpenSC/blob/94388f9538e6ea1c1cd853663d8a14705398475a/src/pkcs11/framework-pkcs15.c#L4291-L4339). It looks at the `p15card`'s [struct sc_supported_algo_info](https://github.com/OpenSC/OpenSC/blob/94388f9538e6ea1c1cd853663d8a14705398475a/src/libopensc/opensc.h#L219-L226). In PKCS#11, the key's properties are checked by the application before usage, this could also be added for Minidriver/Tokend/CTK (where it is currently ignored).

**Comment by hurric4ne777** [comment]
Would something like this help? I'm just thinking out loud here... https://www.motechno.com/buy/cardos-api/

**Comment by Jakuje** [comment]
Maybe it could could help, but I am not going to pay that money just to try. But recently I worked with some other smart card (which is going to land in opensc some time soon) and did some reading of the ISO 7816 so I might get back to this and try to guess some magic numbers to support different signature types, but nothing is guaranteed.

**Comment by dengert** [comment]
@hurric4ne777  Can you get a PKCS spy log and/or an OpenSC log of the failing application. See: [Using-OpenSC](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC)

You also said: "It says the public key is missing or invalid." This could be the application is accessing the wrong key or the public key is not on the card. The public key is also in the certificate.  The pubkey can be stored in multiple formats. One is "SPKI" that matches the pubkey as stored in the certificate. Maybe the application is not parsing it correctly.  

Maybe you could buy the CD and look for decipher. Based on the OpenSC code,  a "padding byte" precedes the block of data to be deciphered.  Three drivers do  `sc_format_apdu(card, &apdu, SC_APDU_CASE_4, 0x2A, 0x80, 0x86);` in their `*__decipher` routines to pass in a padding indicator byte. These are `card-starcos.c`. `card-mcrd.c` and `iso7816.c` which is called by `card-cardos.c`  `iso7816.c` sends "0x00" but one of the others sends "0x81".  This might answer some other questions.

**Comment by Jakuje** [comment]
@Ragnar-von-Detroit can you check the PR#1867 whether it solves your problem?

**Comment by frankmorgner** [comment]
@Ragnar-von-Detroit ?

**Comment by Ragnar-von-Detroit** [comment]
Hello Frank, I did test the new code. However it still doesn't work. I think this is due to Catalina. As I have had a user report that the .20 infact does work with Mojave. However I have yet to test personally on Mojave. I will try to get some time in the near future and test on Mojave. But there still remains the problem of Catalina and this driver set. As it appears to no function correctly. Per the Catalina, I can see the token in Outlook, but it doesn't prompt me for my pin. It's worth mentioning that webpage PKI works well with Firefox and Catalina.

**Comment by frankmorgner** [comment]
Could you check whether webpage authentication also works in Safari or Chrome (this uses CTK rather than PKCS#11 as in Firefox)

**Comment by Ragnar-von-Detroit** [comment]
Hello Frank. It's failing in Safari. It works with Firefox. 

It did prompt for the pin, but didn't decrypt.

**Comment by frankmorgner** [comment]
Your description looks similar to https://github.com/frankmorgner/OpenSCToken/issues/14 or https://github.com/frankmorgner/OpenSCToken/issues/20...

And indeed, the cardos driver doesn't support SC_ALGORITHM_RSA_RAW for 5.0 and later! Basically, we need to figure out how to support more of the other signature/decryption algorithms requested by CTK. Unfortunately, I currently don't have a lot of time debugging this on my mac...

**Comment by Jakuje** [comment]
It does not support raw. We can try to hack it again using decryption, but it has its own downsides. As windows is not the main platform for me, it is low priority to tweak that beside being busy with other things at this moment.

**Comment by Jakuje** [comment]
There were couple of changes related to CardOS 5 cards in last year which might have addressed your issue. Can you check with the latest release candidate?

**Comment by Jakuje** [comment]
After almost three years without update, it looks like either the error is gone or there is no interest. If it is still an issue, please, open a new issue with the debug logs.
