### ISSUE TITLE
inconsistent use of option -r in opensc tools

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#1704]
### Problem Description
**-r** switch is used in inconsistent way (info from manual pages, not from sources):

pkcs15-tool:
--reader arg
--read-certificate cert, -r cert

pkcs15-crypt:
--reader arg, -r arg

pkcs15-init:
--reader arg, -r arg

opensc-tool:
--reader arg, -r arg

opensc-explorer:
--reader arg, -r arg

other tools, that respect `--reader` and `-r` to specify reader:
cardos-tool, cryptoflex-tool, dnie-tool, eidenv, netkey-tool, openpgp-tool, piv-tool, sc-hsm-tool,westcos-tool 

iasecc-tool allows only long option `--reader`

### Proposed Resolution

Alternatives:
1. change pkcs15-tool, use `-r` to specify reader (same change for iasecc-tool )
2. remove `-r` from all tools 

Both alternatives may affect some user scripts, maybe new release of opensc may generate a warning if `-r` is used (i.e.  switch will be removed/changed in future release..).

**Comment by frankmorgner** [comment]
using -r for the reader only, should be the way to go. I think we can already hard code the migration with something like this:
```c
#if OPENSC_MAJOR == 0 &&  OPENSC_VERSION_MINOR == 19
// add warning about -r
#elif OPENSC_MAJOR == 0 &&  OPENSC_VERSION_MINOR == 20
// remove -r if it didn't specify the reader to produce a hard failure of scripts
#elif (OPENSC_MAJOR > 0) || (OPENSC_MAJOR == 0 && OPENSC_VERSION_MINOR > 20)
// add -r to specify the reader
#endif
```
