### ISSUE TITLE
 pkcs11_eventmgr not reacting to card removal 

### ISSUE THREAD

**Issue by c3ph3us** [OpenSC/OpenSC#1706]
when i use **pkcs11_eventmgr** nodaemon debug

DEBUG:pkcs11_eventmgr.c:613: loading pkcs #11 module...
DEBUG:pkcs11_lib.c:973: PKCS #11 module = [/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so]
DEBUG:pkcs11_lib.c:990: module permissions: uid = 0, gid = 0, mode = 644
DEBUG:pkcs11_lib.c:999: loading module /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so
DEBUG:pkcs11_lib.c:1007: getting function list
DEBUG:pkcs11_eventmgr.c:638: initialising pkcs #11 module...
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
<------------ yubikey removed 
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
DEBUG:pkcs11_eventmgr.c:439: Found 1 token(s)
^C

i can't get removal events executed ( the command shows found tocken even when removed) 

config : 

pkcs11_eventmgr {

	# Run in background? Implies debug=false if true
	daemon = true;

	# show debug messages?
	debug = true;
	
	# polling time in seconds
	polling_time = 5;

	# expire time in seconds
	# default = 0 ( no expire )
	expire_time = 10;
	
	# pkcs11 module to use
	pkcs11_module =  /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so;

	#
	# list of events and actions

	# Card inserted
	event card_insert {
		# what to do if an action fail?
		# ignore  : continue to next action
		# return  : end action sequence
		# quit    : end program
		on_error = ignore ;

		# You can enter several, comma-separated action entries
		# they will be executed in turn
		action = "play /usr/share/sounds/warning.wav",
			"xscreensaver-command -deactivate";
	}

	# Card has been removed
	event card_remove { 
		on_error = ignore;
		action = "play /usr/share/sounds/error.wav",
			"xscreensaver-command -lock";
	}

	# Too much time card removed
	event expire_time { 
		on_error = ignore;
		action = "/bin/false";
	}
}

when i use **card_eventmgr** with following config 
i get exit on removal and no action executed 

DEBUG:card_eventmgr.c:386: Scanning present readers
DEBUG:card_eventmgr.c:443: 0: Yubico Yubikey NEO OTP+U2F+CCID 00 00
DEBUG:card_eventmgr.c:502: Reader 0 (Yubico Yubikey NEO OTP+U2F+CCID 00 00)
DEBUG:card_eventmgr.c:506: Card state: 0x00000014
DEBUG:card_eventmgr.c:509: Reader unknown
DEBUG:card_eventmgr.c:386: Scanning present readers
DEBUG:card_eventmgr.c:389: SCardListReader: 8010002E
DEBUG:card_eventmgr.c:405: SCardListReader: 8010002E
DEBUG:card_eventmgr.c:443: 0:  ��SV
DEBUG:card_eventmgr.c:529: SCardGetStatusChange: 80100009
DEBUG:card_eventmgr.c:73: Exitting

config : 

card_eventmgr {

	# Run in background? Implies debug=false if set to true
	daemon = true;

	# show debug messages?
	debug = true;
	
	# polling time in milliseconds
	timeout = 1000;
	
	#
	# list of events and actions

	# Card inserted
	event card_insert {
		# what to do if an action fail?
		# ignore  : continue to next action
		# return  : end action sequence
		# quit    : end program
		on_error = ignore ;

		# You can enter several, comma-separated action entries
		# they will be executed in turn
		action = "play /usr/share/sounds/warning.wav",
			"xscreensaver-command -deactivate";
	}

	# Card has been removed
	event card_remove { 
		on_error = ignore;
		action = "play /usr/share/sounds/error.wav",
			"xscreensaver-command -lock";
	}

	# Too much time locked session
	event timeout { 
	}
}

how to keep ps of card_eventmgr  to be notified about card insert ?

**Comment by frankmorgner** [comment]
please use https://github.com/OpenSC/pam_pkcs11/issues

**Comment by frankmorgner** [comment]
I just realized that this is about `opensc-pkcs11.so`. Please try to reproduce the problem with `pkcs11-tool --test-hotplug`.

**Comment by frankmorgner** [comment]
I think I was able to reproduce and fix the problem, check out https://github.com/OpenSC/OpenSC/pull/1707
