### ISSUE TITLE
pkcs#15 written as pcks#15

### ISSUE THREAD

**Issue by amitkumar50** [OpenSC/OpenSC#1708]
### Problem Description
On page:
https://github.com/OpenSC/OpenSC/wiki/Card-personalization
section: PKCS#15

See: PCKS written
So a "PCKS#15 card" is nothing but any other card on which the right set of files has been added. In short: PKCS#15 allows you to describe where to find PINs, keys, certificates and data on a card, plus all the info that is needed to use them.

**Comment by frankmorgner** [comment]
It's a wiki, please feel free to correct the spelling yourself.

**Comment by Jakuje** [comment]
Fixed
