### ISSUE TITLE
opensc-notify: no notifications on Manjaro Cinnamon

### ISSUE THREAD

**Issue by halocaridina** [OpenSC/OpenSC#1709]
### Steps to reproduce
Running up-to-date cinnamon 4.0.10-1.2 on Manjaro 4.19.49-1-MANJARO.

1. Start opensc-notify 0.19.0 in one terminal
2. Start tail -f ~/.xsession-errors in another terminal
3. Insert/remove Openpgp smart card into reader; no notification(s) received
4. Error (paste log below) appears in ~/.xsession-errors

### Logs

`(cinnamon:8523): Cjs-WARNING **: 08:27:17.070: JS ERROR: GLib.ConvertError: The pathname “contact-new” is not an absolute path`
`NotificationDaemon.prototype._iconForNotificationData@/usr/share/cinnamon/js/ui/notificationDaemon.js:166:48`
`NotificationDaemon.prototype._notifyForSource@/usr/share/cinnamon/js/ui/notificationDaemon.js:408:25`
`NotificationDaemon.prototype.NotifyAsync/<@/usr/share/cinnamon/js/ui/notificationDaemon.js:397:13`
`_proxyInvoker/asyncCallback@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:78:13`

-->

**Comment by frankmorgner** [comment]
Not sure, why the icon should be specified with an absolute path. `contact-new` [is part of the standard icons](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), so it should be available in every icon set...

**Comment by frankmorgner** [comment]
According to Wikipedia, Cinnamon is derived from Gnome 3, which I'm using, too, without any problems...

Please open a bug report at your distribution, maybe they have some more input...

**Comment by Jakuje** [comment]
no response for 3 years, closing. If the issue still persist, please open a new one.
