### ISSUE TITLE
PIV sign fails with Yubikey 4 Neo

### ISSUE THREAD

**Issue by pmvr** [OpenSC/OpenSC#1710]
### Problem Description

pkcs15-crypt RSA signature generation (PIV) fails with version 0.19/0.18 and succeeds with 0.17/0.16 with [Yubikey 4 Neo](https://support.yubico.com/support/solutions/articles/15000006494-yubikey-neo).

Attached are the log files for version 0.19 and 0.17.

The error message of version 0.19 is:
`Compute signature failed: Security status not satisfied`

The PIN is successfully checked in both cases.

### Proposed Resolution

I noticed that for failing version 0.19 before PIN verification and after PIN verification the same APDU is send:

> Outgoing APDU (9 bytes):
> 00 CB 3F FF 03 5C 01 7E 00 ..?..\.~.
> Incoming APDU (22 bytes):
> 7E 12 4F 0B A0 00 00 03 08 00 00 10 00 01 00 5F ~.O............_
> 2F 02 40 00 90 00

Not sure whether this helps.

### Steps to reproduce
version 0.19
`/usr/bin/pkcs15-crypt --sign --pkcs1 --input test.txt --output sig.bin`

version 0.17
`/usr/local/bin/pkcs15-crypt --sign --pkcs1 --input test.txt --output sig.bin`

File test.txt contains three bytes "abc" only.

### Logs

Logs are attached complete with debug level 3 and APDUs only.
[opensc-0.17-apdus.log](https://github.com/OpenSC/OpenSC/files/3302154/opensc-0.17-apdus.log)
[opensc-0.17.log](https://github.com/OpenSC/OpenSC/files/3302155/opensc-0.17.log)
[opensc-0.19-apdus.log](https://github.com/OpenSC/OpenSC/files/3302156/opensc-0.19-apdus.log)
[opensc-0.19.log](https://github.com/OpenSC/OpenSC/files/3302157/opensc-0.19.log)

**Comment by dengert** [comment]
Your token appears to be a Yubico NEO (Not a Yubikey 4). 
`card-piv.c:3181:piv_init: Yubico card->type=14003, r=0x00000000 version=0x00010004` 1.0.4
This is a very old token. (I do not have one of these.) Newer tokens have versions starting with 4. 

0.19.0 introduced a number of changes to make sure the PIV applet is selected when a token has multiple applets being used by multiple host applications like a browser and an email application.  PIV and OpenPGP are the two Yubico applets supported by OpenSC.  This is done by doing a SELECT AID or by reading the PIV DISCOVERY object `00 CB 3F FF 03 5C 01 7E 00` to see if PIV applet is the active applet.  

Some tokens, mostly Yubico, do not implement the NIST PIV spec correctly, and thus need special handling. See the `CI_*` defines in `card-piv.c`. `card-piv.c:3240:piv_init: PIV card-type=14003 card_issues=0x00020313` and possible the `CI_DISCOVERY_USELESS` which does not appear to be set. 

`Security status not satisfied` is being returned because the PIV  `9C` key enforces `user_consent`, `CKA_ALWAYS_AUTHENTICATE` and `PIN_ALWAYS` on the card by requiring the PIN VERIFY command to be done immediately before the sign operation and the PIV DISCOVERY operation is between them. The PKCS\#11 code handles this, but it could be the `pkcs15-crypt.c` is not passing enough information to  `card-piv.c` to make sure the  PIV DISCOVERY will not be done in this case. 

One way to get around this is to use the `pin_cache_ignore_user_consent = true;`  in `opensc.conf`. See
`opensc.conf.example.in` in 0.19.0 for how to set this. 

 Another way is to use `pkcs11-tool` to sign. 

There are a number of changes in card-piv.c in the master branch. I believe your problem may have been solved by setting `CI_DISCOVERY_USELESS` thus avoiding trying to handle multiple applets when the token does not handle them very well. 

In any case can you try using building from the git source or use one of the night builds?

**Comment by mouse07410** [comment]
I concur with @dengert, but have one suggestion to try.

I personally don't like how the main OpenSC tries to enforce decisions that rightly belong to the card/token itself. So, my fork removed them. 
If you can, please try to build and run https://GitHub.com/mouse07410/OpenSC.git and report here whether it works better for your Yubikey NEO. 

I've been using Yubikeys for ages, and a few of mine are probably add old as yours, so in MHO the chance is good.

**Comment by pmvr** [comment]
@dengert: Thanks a lot for the the detailed explanations.
Cloning the repository and building solved the issue.

@mouse07410: I got a compile error:
```
  CC       opensc-tool.o
In file included from opensc-tool.c:21:0:
../../config.h:14:0: error: "DEFAULT_PKCS11_PROVIDER" redefined [-Werror]
```

**Comment by mouse07410** [comment]
@pmvr could you do me a favor and try my current master again?

**Comment by pmvr** [comment]
@mouse07410: Sorry, I got the same compiling error:
```
  CC       opensc-tool.o
In file included from opensc-tool.c:21:0:
../../config.h:14:0: error: "DEFAULT_PKCS11_PROVIDER" redefined [-Werror]
 #define DEFAULT_PKCS11_PROVIDER "${exec_prefix}/lib64/opensc-pkcs11.so"
```

**Comment by mouse07410** [comment]
@pvmr I think the compiler errors are fixed now.

**Comment by pmvr** [comment]
@mouse07410: Sorry, still the same error:

```
  CC       opensc-tool.o
In file included from opensc-tool.c:21:0:
../../config.h:14:0: error: "DEFAULT_PKCS11_PROVIDER" redefined [-Werror]
 #define DEFAULT_PKCS11_PROVIDER "${exec_prefix}/lib64/opensc-pkcs11.so"

```

**Comment by dengert** [comment]
I can get the same error on Ubuntu 18.04 using your clone.

like "DEFAULT_PKCS11_PROVIDER" error comes from  a mod to `configure.ac`  line 908 `AC_DEFINE_UNQUOTED([DEFAULT_PKCS11_PROVIDER], ["${DEFAULT_PKCS11_PROVIDER}"], [Default PKCS11 provider])` 

What is the purpose of this line?

**Comment by mouse07410** [comment]
> What is the purpose of this line?

Comes from the attempt to fix #1443 
https://github.com/mouse07410/OpenSC/commit/578e03c32036b697dbc3408027ce385d7699ca9c

**Comment by mouse07410** [comment]
Commented that line out - and was immediately reminded why it was there:
```
. . . . .
clang -DHAVE_CONFIG_H -I. -I../..  -I../../src -D'DEFAULT_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"'  -I/Users/ur20980/src/OpenSC/openssl_bin/Library/OpenSC/include  -pthread -O2 -g -Wall -Wextra -Wno-unused-parameter -Werror -c -o pkcs11-tool.o pkcs11-tool.c
pkcs11-tool.c:244:41: error: expected '}'
        "Specify the module to load (default:" DEFAULT_PKCS11_PROVIDER ")",
                                               ^
pkcs11-tool.c:243:36: note: to match this '{'
static const char *option_help[] = {
                                   ^
pkcs11-tool.c:322:34: error: use of undeclared identifier 'DEFAULT_PKCS11_PROVIDER'
static const char *     opt_module = DEFAULT_PKCS11_PROVIDER;
                                     ^
. . . . .
```

**Comment by dengert** [comment]
Using your clone, and running make with -k shows that 36 files (mostly tools) do not compile (Ubuntu 18.04 with gcc) because of DEFAULT_PKCS11_PROVIDER is  defined twice, once on command line and once in config.h 

```
gcc -DHAVE_CONFIG_H -I. -I../../../src/src/tools -I../..  -I../../../src/src -D'DEFAULT_PKCS11_PROVIDER="/opt/ossl-1.1/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/opt/ossl-1.1/lib/on     epin-opensc-pkcs11.so"' -DDEBUG -I/opt/ossl-1.1/include  -pthread -g -Werror -Wall -Wextra -Wno-unused-parameter -Werror -MT opensc-tool.o -MD -MP -MF .deps/opensc-tool.Tpo -c -o opensc-tool.o ../.     ./../src/src/tools/opensc-tool.c
In file included from ../../../src/src/tools/opensc-tool.c:21:0:
../../config.h:14:0: error: "DEFAULT_PKCS11_PROVIDER" redefined [-Werror]
 #define DEFAULT_PKCS11_PROVIDER "${exec_prefix}/lib/opensc-pkcs11.so"
 
<command-line>:0:0: note: this is the location of the previous definition
cc1: all warnings being treated as errors
```

Is this a clang issue?  

With the command line that adds -D'DEFAULT_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"': 
```
clang -DHAVE_CONFIG_H -I. -I../..  -I../../src -D'DEFAULT_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"'  -I/Users/ur20980/src/OpenSC/openssl_bin/Library/OpenSC/include  -pthread -O2 -g -Wall -Wextra -Wno-unused-parameter -Werror -c -o pkcs11-tool.o pkcs11-tool.c
```
Clang still says it is not defined:
```
pkcs11-tool.c:322:34: error: use of undeclared identifier 'DEFAULT_PKCS11_PROVIDER'
```
Can you run this to get the preprocessing output to see what is actual doing:
```
clang -DHAVE_CONFIG_H -I. -I../..  -I../../src -D'DEFAULT_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"'  -I/Users/ur20980/src/OpenSC/openssl_bin/Library/OpenSC/include  -pthread -O2 -g -Wall -Wextra -Wno-unused-parameter -Werror -E -o pkcs11-tool.o.CPP  pkcs11-tool.c
```
This replaces -c with -E and the output file is  pkcs11-tool.o.CPP. 

Is this an issue with using single quotes with -D?

**Comment by mouse07410** [comment]
> Using your clone, and running make with -k shows that 36 files (mostly tools) do not compile (Ubuntu 18.04 with gcc) because of DEFAULT_PKCS11_PROVIDER is defined twice, once on command line and once in config.h

Yes. The question is how to remedy it without breaking it (again) for MacOS (especially with the new crazy Xcode-10.2+).

> Is this a clang issue?

I don't know. I personally find this extremely convoluted, and would **much** prefer if the defines were confined to `config.h`. IMHO, this mix of command-line defines with `config.h` defines is pure crazy.

> Can you run this to get the preprocessing output...?

Sure:
```
$ clang -DHAVE_CONFIG_H -I. -I../..  -I../../src -D'DEFAULT_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/Library/OpenSC/lib/opensc-pkcs11.so"'  -I/Users/ur20980/src/OpenSC/openssl_bin/Library/OpenSC/include  -pthread -O2 -g -Wall -Wextra -Wno-unused-parameter -Werror -E -o pkcs11-tool.o.CPP  pkcs11-tool.c
$ ll *.CPP
-rw-r--r--  1 ur20980  MITLL\Domain Users  748776 Jul 17 08:27 pkcs11-tool.o.CPP
$ zip pkcs11-tool.o.CPP.zip pkcs11-tool.o.CPP
  adding: pkcs11-tool.o.CPP (deflated 84%)
$ 
```
[pkcs11-tool.o.CPP.zip](https://github.com/OpenSC/OpenSC/files/3401818/pkcs11-tool.o.CPP.zip)

> Is this an issue with using single quotes with -D?

I wish I knew.

**Comment by dengert** [comment]
Does not look like a problem with -D.  pkcs11-tool.o.CPP has line 14607:
```
 static const char *option_help[] = {
 "Specify the module to load (default:" "/Library/OpenSC/lib/opensc-pkcs11.so" ")",
 "Show global token information",
```
and later line 14686:
```
static const char * opt_module = "/Library/OpenSC/lib/opensc-pkcs11.so";
```
So the -E output looks correct.

As another test I installed clang  1:6.0-41-exp5-ubuntu1  and set CC=clang before configure and running against your clone I get:
```
make[3]: Entering directory '/afs/anl.gov/appl/OpenSC-dev/build/opensc-git-mouse7410/amd64_linux26-1.1/src/tools'
clang -DHAVE_CONFIG_H -I. -I../../../src/src/tools -I../..  -I../../../src/src -D'DEFAULT_PKCS11_PROVIDER="/opt/ossl-1.1/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/opt/ossl-1.1/lib/onepin-opensc-pkcs11.so"' -DDEBUG -I/opt/ossl-1.1/include  -pthread -g -Werror -Wall -Wextra -Wno-unused-parameter -Werror -MT opensc-tool.o -MD -MP -MF .deps/opensc-tool.Tpo -c -o opensc-tool.o ../../../src/src/tools/opensc-tool.c
In file included from ../../../src/src/tools/opensc-tool.c:21:
../../config.h:14:9: error: 'DEFAULT_PKCS11_PROVIDER' macro redefined [-Werror,-Wmacro-redefined]
#define DEFAULT_PKCS11_PROVIDER "${exec_prefix}/lib/opensc-pkcs11.so"
        ^
<command line>:2:9: note: previous definition is here
#define DEFAULT_PKCS11_PROVIDER "/opt/ossl-1.1/lib/opensc-pkcs11.so"
```

So your mod introduced a different bug.  The command line parameter looks correct, but the config.h has `${exec_prefix}` which can only be used in the Makefile and not in a config.h file.   

Further testing without your `AC_DEFINE_UNQUOTED([DEFAULT_PKCS11_PROVIDER], ["${DEFAULT_PKCS11_PROVIDER}"], [Default PKCS11 provider])` line in configure.ac 

and running the compile in 2 steps first is -E to do preprocessing:
```
clang -DHAVE_CONFIG_H -I. -I../../../src/src/tools -I../..  -I../../../src/src -D'DEFAULT_PKCS11_PROVIDER="/opt/ossl-1.1/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/opt/ossl-1.1/lib/onepin-opensc-pkcs11.so"' -DDEBUG -I/opt/ossl-1.1/include  -pthread -g -Werror -Wall -Wextra -Wno-unused-parameter -Werror -MT pkcs11-tool.o -MD -MP -MF .deps/pkcs11-tool.Tpo -E -o pkcs11-tool.o.CPP.c ../../../src/src/tools/pkcs11-tool.c
```
Step2 takes pkcs11-tool.o.CPP.c and compiles it:

```
clang -DHAVE_CONFIG_H -I. -I../../../src/src/tools -I../..  -I../../../src/src -D'DEFAULT_PKCS11_PROVIDER="/opt/ossl-1.1/lib/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/opt/ossl-1.1/lib/onepin-opensc-pkcs11.so"' -DDEBUG -I/opt/ossl-1.1/include  -pthread -g -Werror -Wall -Wextra -Wno-unused-parameter -Werror -MT pkcs11-tool.o -MD -MP -MF .deps/pkcs11-tool.Tpo -c -o pkcs11-tool.o pkcs11-tool.o.CPP.c
```
The pkcs11-tool.o has the path:
```
strings pkcs11-tool.o | grep 1.1
`Specify the module to load (default:/opt/ossl-1.1/lib/opensc-pkcs11.so)
```

I would conclude that when clang does a combined preprocessor and compile it is not passing the -D parameters. But when doing preprocessing using -E as one step it does pass the -D parameters  so they get into the preprocessed output which is then compiled by the the -c in the second step.

This sounds like a clang bug not related to MacOS. 
Could be all the quoting of the -D parameters is part of the issue.

Some simple tests cases could be submitted to the clang group.

**Comment by dengert** [comment]
@mouse07410 Disregard the problems with clang listed above. 

Just noticed that your pkcs11-tool.c has  line 21: `#undef DEFAULT_PKCS11_PROVIDER`  which in effect looks like why the clang -D parameter was not defined!

This also  explains the behaviour of the split preprocessor and compile.  The preprocessor  step defines the `DEFAULT_PKCS11_PROVIDER` via a parameter then undefines it so it is not defined when passed to the compiler.  But the split compiler also had the -D`DEFAULT_PKCS11_PROVIDER...` parameter so when compiling the preprocesser output it does defines from the -D parameter. So it works.

I strongly suggest that you remove from configure.ac:

`AC_DEFINE_UNQUOTED([DEFAULT_PKCS11_PROVIDER], ["${DEFAULT_PKCS11_PROVIDER}"], [Default PKCS11 provider])`

and remove from pkcs11-tool.c:
`#undef DEFAULT_PKCS11_PROVIDER`

@pmvr you may want to try this. Note you need to run the ./bootstrap after modifying configure.ac

**Comment by mouse07410** [comment]
@dengert thank you very much for looking into this, and proposing a fix. I did what you suggested, and everything appears to work fine on my Macs. 

I'm waiting now for Travis CI report, but hopefully it will be fine too.

BTW, do you think #1723 is ready for merging? And do you think #1727 can be merged?

**Comment by dengert** [comment]
https://github.com/OpenSC/OpenSC/pull/1727 looks OK. Does it fix one of your problems?

See: 
https://github.com/OpenSC/OpenSC/pull/1723#issuecomment-512629743 from response on #1723 question above.

**Comment by mouse07410** [comment]
Re. #1727 - I can't tell, because on my machines I did not (thankfully) experience those problems. And for those that complained, #1727 did not seem to make a difference: Pulse Secure VPN reliably fails in the given scenario, with the only workaround being remove-and-reinsert the token.

But if in general #1727 can't hurt and might help - perhaps it's worth incorporating regardless???

**Comment by mouse07410** [comment]
@dengert I think this problem is fixed the way you suggested. 
@pmvr please feel free to try my fork again - it *should* compile fine on Ubuntu now (at least it does on mine ;).
