### ISSUE TITLE
Where does libopensc.so get installed ?

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1712]
Hello,

I tried the following steps in the wiki
```
tar xfvz opensc-*.tar.gz
cd opensc-*
./bootstrap
./configure --prefix=/usr --sysconfdir=/etc/opensc
make
sudo make install
```

But I could not find a libopensc*.so library.  I did see a opensc-pkcs11.so. 
Is there anyway to install the libopensc*.so library ?

@frankmorgner

**Comment by Jakuje** [comment]
I have it under `/usr/lib64/libopensc.so.6`. Note, that there is no unversioned so file since the libopensc is internal library not supposed to be used by external applications.

**Comment by frankmorgner** [comment]
use the tool of your choice, e.g. `find / -name 'libopensc.so'`. Given your prefix, this should be in `/usr/lib/libopensc.so`.

Note, that you should only link against `libopensc.so` if you know what you're doing

**Comment by RohanKurane** [comment]
Thanks @Jakuje and @frankmorgner 

When I tried to load libopensc.so and then try to use the CK_C_GetFunctionList() to load the function list, It said none could be found and failed. 

Do I also need PCSC-Lite for this ? 
https://pcsclite.apdu.fr/

```
        static const char *module = "/usr/lib/libopensc.so.6.0.0"; 
        pDynLib = dlopen(module, RTLD_NOW | RTLD_LOCAL);

        if ( pDynLib == NULL )
        {
            printf("Could not open PKCS11 module %s %s\n", module, dlerror());
            return -1;
        }

        pGetFunctionList = (CK_C_GetFunctionList) dlsym(pDynLib, "C_GetFunctionList");
        if (!pGetFunctionList)
        {
            printf("ERROR: Could not load the OpenSC PKCS#11 function list:\n");
            return -1;
        }

```

```
ls -lt /usr/lib/libopensc.*
-rw-r--r-- 1 root root 17125274 Jun 22 22:06 /usr/lib/libopensc.a
-rwxr-xr-x 1 root root      959 Jun 22 22:06 /usr/lib/libopensc.la
lrwxrwxrwx 1 root root       18 Jun 22 22:06 /usr/lib/libopensc.so -> libopensc.so.6.0.0
lrwxrwxrwx 1 root root       18 Jun 22 22:06 /usr/lib/libopensc.so.6 -> libopensc.so.6.0.0
-rwxr-xr-x 1 root root  8673640 Jun 22 22:06 /usr/lib/libopensc.so.6.0.0
ubuntu@ip-172-31-51-192:~/opensc-0.19.0$ 
```

**Comment by Jakuje** [comment]
For using PKCS#11 API, you do not need libopensc, but opensc-pkcs11.so, which will have all the PKCS#11 functions (`C_GetFunctionList`).
