### ISSUE TITLE
What is the wget link for opensc-*.tar.gz file ?

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1713]
Hi, 

What is the wget link to download the opensc-*.tar.gz file ? 
I want to automate this in a script and not click on the download button to download the tar.gz file. 

@frankmorgner

**Comment by Jakuje** [comment]
Something like this should do that:
```
https://github.com/OpenSC/OpenSC/releases/download/%{version}/%{name}-%{version}.tar.gz
```
For latest version:
```
https://github.com/OpenSC/OpenSC/releases/download/0.19.0/OpenSC-0.19.0.tar.gz
```
