### ISSUE TITLE
00d1501ae666b08fb62403cfa2da2c7669f0eda5 breaks EstEID ECDH derive

### ISSUE THREAD

**Issue by metsma** [OpenSC/OpenSC#1719]
### Problem Description
After change 00d1501ae666b08fb62403cfa2da2c7669f0eda5 does not allow to create temporary derived key when card is readonly

### Proposed Resolution
As my PKCS11 understanding readonly cards and sessions support derive temporary keys

### Steps to reproduce
Derive ECDH key

### Logs
```
P:11345; T:0x4598863296 11:40:16.764 [opensc-pkcs11] pkcs11-object.c:393:C_FindObjectsInit: Object 0/105553143943776: Attribute 0x0 does NOT match.
P:11345; T:0x4598863296 11:40:16.764 [opensc-pkcs11] pkcs11-object.c:424:C_FindObjectsInit: 1 matching objects
P:11345; T:0x4598863296 11:40:16.764 [opensc-pkcs11] misc.c:290:session_get_operation: called
P:11345; T:0x4598863296 11:40:16.764 [opensc-pkcs11] misc.c:290:session_get_operation: called
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] framework-pkcs15.c:3675:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] pkcs11-object.c:100:sc_create_object_int: called
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] pkcs11-object.c:110:sc_create_object_int: C_CreateObject(): CKA_TOKEN = FALSE
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] pkcs11-object.c:110:sc_create_object_int: C_CreateObject(): CKA_CLASS = CKO_SECRET_KEY
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] pkcs11-object.c:110:sc_create_object_int: C_CreateObject(): CKA_KEY_TYPE = 0x10
P:11345; T:0x4598863296 11:40:16.767 [opensc-pkcs11] pkcs11-session.c:347:C_Logout: C_Logout(hSession:0x600001548770)
P:11345; T:0x4598863296 11:40:16.768 [opensc-pkcs11] pkcs15-pin.c:838:sc_pkcs15_pincache_clear: called
P:11345; T:0x4598863296 11:40:16.768 [opensc-pkcs11] pkcs11-session.c:161:C_CloseSession: C_CloseSession(0x600001548770)
P:11345; T:0x4598863296 11:40:16.768 [opensc-pkcs11] pkcs11-session.c:109:sc_pkcs11_close_session: real C_CloseSession(0x600001548770)
```

**Comment by metsma** [comment]
I think there should be additional checks
```
	if (session->slot->token_info.flags & CKF_WRITE_PROTECTED) {
		rv = CKR_TOKEN_WRITE_PROTECTED;
		goto out;
	}
```
If attribute CKA_TOKEN == true is requested, then we need readwrite session and token to able write info

**Comment by frankmorgner** [comment]
PKCS#11 states that
>Only session objects can be created during a read-only session.

So indeed checking for `CKA_TOKEN == TRUE` should be enough to fix this.

However, reviewing 00d1501ae666b08fb62403cfa2da2c7669f0eda5, I think I took the lazy approach of checking `CKF_WRITE_PROTECTED` early, which would not be working anymore considering `CKA_TOKEN` from the user input. An application could `CKA_TOKEN := FALSE`, which is ignored in, for example, `pkcs15_create_public_key()`, resulting in writing the card in `sc_pkcs15init_store_public_key()`. In essence, the ideal fix would check the input parameters in pkcs15_create_private_key pkcs15_create_public_key pkcs15_create_certificate pkcs15_create_data pkcs15_create_secret_key (see also [this comment](https://github.com/OpenSC/OpenSC/blob/229dd32e3affd3fbe7bdaae9fea213d400435073/src/pkcs11/framework-pkcs15.c#L2778-L2784)).

**Comment by dengert** [comment]
PKCS\#11-2.4.0 says: "Exactly what the CKF_WRITE_PROTECTED flag means is not specified in Cryptoki. An application may
be unable to perform certain actions on a write-protected token; these actions can include any of the
following, among others:
 Creating/modifying/deleting any object on the token.
 Creating/modifying/deleting a token object on the token.
  Changing the SO’s PIN.
 Changing the normal user’s PIN.
 
The token may change the value of the CKF_WRITE_PROTECTED flag depending on the session state
to implement its object management policy"

So I agree with you. 

I believe the check in `pkcs1-object.c` `sc_create_object_int` lines 117-120  should be done in 
`framework-pkcs15.c` `pkcs15_create_object` which already is doing some tests for `CKA_TOKEN` and ` CKO_SECRET_KEY`. It has access to the the `slot->token_info.flags`. See the two "TODO" comments. 

Something similar could be done  for the `slot->token_info.flags`.

In any case, the user should have logged in to the token and a `CKS_RW_USER_FUNCTION` session to be able to create the derived secret key.

**Comment by dengert** [comment]
I agree with Frank too.

**Comment by metsma** [comment]
 Creating/modifying/deleting any object on the token.
 Creating/modifying/deleting a token object on the token.
 Changing the SO’s PIN.
 Changing the normal user’s PIN.



> PKCS#11-2.4.0 says: "Exactly what the CKF_WRITE_PROTECTED flag means is not specified in Cryptoki. An application may
> be unable to perform certain actions on a write-protected token; these actions can include any of the
> following, among others:
>  Creating/modifying/deleting any object on the token.
>  Creating/modifying/deleting a token object on the token.
>  Changing the SO’s PIN.
>  Changing the normal user’s PIN.

And I am not doing none of these, only derive temporary key on readonly session with template CKA_TOKEN == FALSE.

**Comment by dengert** [comment]
Yes I see you are not doing any of these. See Frank's comment: "I think I took the lazy approach of checking CKF_WRITE_PROTECTED early" and othr places that may need checks. Also see the TODO comments in `pkcs15_create_object` going back to 2012.

**Comment by dengert** [comment]
Here is something you could try. It looks  CKF_WRITE_PROTECTED is set in `framework-pkcs15.c`   It also looks like you could add an atrblock (`card_atr`) to `opensc.conf` to override any default with `read_only = false;` Look at opensc.conf.example.in for "read_only".

**Comment by dengert** [comment]
And it looks like only `pkcs15-esteid2018.c` , `pkcs15-esteid.c` and `pkcs15-pteid.c` set `SC_PKCS15_TOKEN_READONLY`.  **The question is why.** If these are really government issued cards, there should be no way a user could change the card i.e. the card requires some other authentication to allow writing. There are many other government cards that require some other authentication and don't need to set `SC_PKCS15_TOKEN_READONLY`. Setting `SC_PKCS15_TOKEN_READONLY` in the above 3 drivers may not be needed.

**Comment by metsma** [comment]
They are government issued and I have no clue what SC_PKCS15_TOKEN_READONLY really does.
Right now we have regression compared 0.19.0 release and it needs to be fixed

**Comment by metsma** [comment]
I found from PKCS#15
> Read-Only and Read-Write cards
> Access conditions for files in the PKCS15 application can be set up differently depending on if the > > application is to be read-only or read-write. A read-only card might be desired for high-security > > > purposes, for example when it has been issued using a secure issuing process, and it is to be certain > that it can not be manipulated afterwards. 
> ...
> It is recommended that all cards be personalized with the read-write access control settings, unless > they are issued for an environment with high security requirements.

They are issued by government and user has no access to write there.

**Comment by martinpaljak** [comment]
> And it looks like only `pkcs15-esteid2018.c` , `pkcs15-esteid.c` and `pkcs15-pteid.c` set `SC_PKCS15_TOKEN_READONLY`. **The question is why.** If these are really government issued cards, there should be no way a user could change the card i.e. the card requires some other authentication to allow writing. There are many other government cards that require some other authentication and don't need to set `SC_PKCS15_TOKEN_READONLY`. Setting `SC_PKCS15_TOKEN_READONLY` in the above 3 drivers may not be needed.

@dengert the flag is arbitrary metadata that should help the internal OpenSC code to deduce things like ability to create objects via PKCS#11 or pkcs11-tool. Indeed, the cards can be modified with appropriate authentication, but not in the context of OpenSC driver, which only exposes a read-only interface. So the additional check for CKA_TOKEN=true in the context of SC_PKCS15_TOKEN_READONLY or even CKF_WRITE_PROTECTED seems like an easy fix.

**Comment by frankmorgner** [comment]
@metsma could you suggest a change with a pull request?
