### ISSUE TITLE
YubiKey Pkcs#11 not working since 0.18

### ISSUE THREAD

**Issue by Ichigo85** [OpenSC/OpenSC#1733]
I am using windows, and I noticed a regression for signing documents using openSC pkcs#11 from 0.17 to 0.18 and also 0.19. 
When I try to sign a document (I use [NexU ](http://nowina.lu/solutions/java-less-browser-signing-nexu/) application to sign), the application asks me for pin and when it's about to sign it, it shows the error CKR_USER_NOT_LOGGED_IN, which should not happen and, reading various logs, I presumed is not NexU's fault but OpenSC's. 
On version 0.17 everything works as expected. I send OpenSC debug logs of both versions, hoping it can help to solve the issue.

[opensc0.17-debug.log](https://github.com/OpenSC/OpenSC/files/3377279/opensc0.17-debug.log)
[opensc0.19-debug.log](https://github.com/OpenSC/OpenSC/files/3377280/opensc0.19-debug.log)

**Comment by dengert** [comment]
Please see:  #1710 It sounds like the same problem that has been fixed in current github master.

**Comment by Ichigo85** [comment]
Just tried that using `pin_cache_ignore_user_consent = true;`  flag in `opensc.conf` and it worked! Thank you very much!
