### ISSUE TITLE
How to initialize ePass2003 using pkcs11-tool?

### ISSUE THREAD

**Issue by ghost** [OpenSC/OpenSC#1736]
I'm trying to initialize a token using epass2003 in order to offload some cryptographic operations onto device. However, I wasn't successful.

OpenSC 0.19.0 - default conf
Ubuntu 19.04

Here is what I tried:
```
$ pkcs11-tool --module=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -L

Available slots:
Slot 0 (0x0): Feitian ePass2003 00 00
  (empty)


$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --slot 0 --init-token --label test_token

error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.
```
Detailed debug log is here: [Debug log](https://gist.github.com/batuhanceylan/aa55ed93a1cf2a4ad3130f0906901c55)

Then, I tried initializing PKCS15 by

```
$ pkcs15-init -E -T

Using reader with a card: Feitian ePass2003 00 00

$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --slot 0 --init-token --label test_token

error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.
```

But it failed as well. Lastly, I tried:

```
$ pkcs15-init -E -T

Using reader with a card: Feitian ePass2003 00 00

$ pkcs15-init -C -p pkcs15+onepin --pin 1234 --puk 123456

Using reader with a card: Feitian ePass2003 00 00

$ pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so --slot 0 --init-token --label test_token

Please enter the new SO PIN: 
Please enter the new SO PIN (again): 
error: PKCS11 function C_InitToken failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
Aborting.
```

This time there was an Ubuntu notification saying Smart card is ready to use and asked for SO pin, only to fail after setting SO_PIN. The debug log writes:

```
[opensc-pkcs11] framework-pkcs15.c:1909:pkcs15_initialize: init token error -1408
[opensc-pkcs11] misc.c:61:sc_to_cryptoki_error_common: libopensc return value: -1408 (Not supported)
[opensc-pkcs11] pkcs11-global.c:639:C_InitToken: C_InitToken(pLabel='test_token                      ') returns 0x54
```

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by Djalmar** [comment]
@batuhanceylan did you find any solution to this issue ?

**Comment by batuhanceylan** [comment]
> @batuhanceylan did you find any solution to this issue ?

Nor really, sorry.

**Comment by frankmorgner** [comment]
please contact the vendor directly, @FeitianSmartcardReader seems to be non-responsive.

**Comment by frankmorgner** [comment]
hongbin@ftsafe.com

**Comment by akirashimosoeda** [comment]
I think is a module issue. It should work fine with the module given by the manufacturer (Feitian). The specific module you need from them is `libcastle.so.1.0.0`.

**Comment by FeitianSmartcardReader** [comment]
Missed this issue, will check engineer after CNY, should be back on 3th, Feb, will follow up on this issue, thanks

**Comment by xaqfan** [comment]
I have checked opensc code. This function should be that opensc module has not been added。

**Comment by youssou** [comment]
If you're using the gp isoaplet, one solution is to delete and reinstall the application. and then you are able to use pkcs15-init
```

- gp -list
ISD: A000000151000000 (OP_READY)
     Privs:   SecurityDomain, CardLock, CardTerminate, CVMManagement

APP: A0000006472F0001 (SELECTABLE)
     Privs:   

APP: 4845494D44414C4C2E415050 (SELECTABLE)
     Privs:   

APP: F276A288BCFBA69D34F31001 (SELECTABLE)
     Privs:   CardReset

PKG: A000000647 (LOADED)
     Applet:  A0000006472F0001

PKG: 4845494D44414C4C (LOADED)
     Applet:  4845494D44414C4C2E415050

**PKG: F276A288BCFBA69D34F310 (LOADED)
     Applet:  F276A288BCFBA69D34F31001**


- gp --delete F276A288BCFBA69D34F310 
#(do not forget the remove the last 01 in the apdu)
- gp -install workspace/IsoApplet/IsoApplet.cap
#Then
- pkcs15-init --create-pkcs15
```

**Comment by Edward2k** [comment]
Is there any update on this? I am running into similar issues

**Comment by popovec** [comment]
@Edward2k 

This issue is quite old. Try to specify where exactly the problem occurs... Which version of OpenSC are you using? (`opensc-tool -i` )

Most of the token reinitialization issues were resolved using the  commit 5a369a8f31bb4b3bb05b38149fb349a1cda99e5c (commit date  Wed Sep 23 08:37:09 2020 +0200).  This commit is part of OpenSC version 0.21 and later.

The following procedure should work without problems:

1. try to erase epass2003 token.. `pkcs15-init -E -T`  
2. initialization: `pkcs15-init -C -T -p pkcs15+onepin --pin 1234 --puk 123456`
3. generate a RSA key `pkcs15-init --generate-key rsa/2048 --key-usage sign,decrypt --pin 1234 --auth-id 01`

Thanks for testing.

**Comment by Edward2k** [comment]
Hey @popovec,

Thanks for getting back to me so quickly. The problem occurs when trying to initialize the token with `pkcs15-init`. When calling `pkcs15-init -C -T -p pkcs15+onepin --pin 1234 --puk 123456`, I get the following error:
> $ pkcs15-init -C -T -p pkcs15+onepin --pin 1234 --puk 123456
> sing reader with a card: Feitian ePass2003 00 00
> PKCS#15 binding failed: Unsupported card

I have the latest OpenSC version from apt (v0.20.0-3). I'll try building from source and see if that resolves my problems :).

Thanks again and I'll keep you posted.

**Comment by Edward2k** [comment]
@popovec

Well, now I feel like a fool. It works. Always check versions and never trust aptitude to use the most up-to-date version. I do have one question: epass2003 supports rsa4096. It seems even this newer version of OpenSC does not present this. Any idea as to why?

**Comment by popovec** [comment]
I have no information about epass2003 being able to use an RSA key longer than 2048 bits. Newer epass2003 tokens, however, support elliptical keys. You can try to generate an elliptical key as follows:

`pkcs15-init --generate-key ec/prime256v1 --pin 1234 --auth-id 01`

Unfortunately, my epass2003 key does not support elliptic keys (over all, OpenSC signalize support for elliptic cryptography for epass2003, which is bad, but due to the lack of epass2003 documentation, I don't know how to fix it).

**Comment by Edward2k** [comment]
I'm afraid that I have to use rsa4096. The epass2003 documentation is lacking and somewhat contradictory---I've seen some spec sheets mention 4096 and other 2048 for the exact same hardware. Regardless, thanks for the help. I really appreciate it.
