### ISSUE TITLE
OpenSC + Remote Desktop: SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1740]
### Problem Description

When accessing a Windows machine remotely using Microsoft Remote Desktop with smartcard forwarding enabled, an attempt to get smartcard info fails.

### Proposed Resolution

When accessing a Windows machine remotely using Microsoft Remote Desktop with smartcard forwarding enabled, an attempt to get smartcard info should be successful.

### Steps to reproduce

- Connect to a Windows 10 machine using Microsoft Remote Desktop for MacOS Mojave.
- Connect a MyEID smartcard plugged into a Gemalto CT710 reader.
- Run certutil -scinfo

### Logs

```
C:\Users\docuware>certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Gemalto Ezio Shield
--- Reader: Gemalto Ezio Shield
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
--- Status: The card is being shared by a process.
---   Card:
---    ATR:
        3b f5 18 00 00 81 31 fe  45 4d 79 45 49 44 9a      ;.....1.EMyEID.


=======================================================
Analyzing card in reader: Gemalto Ezio Shield
SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for
--------------===========================--------------
CertUtil: -SCInfo command FAILED: 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
```

**Comment by dengert** [comment]
Do you have OpenSC  installed on Windows 10 system with MyEID listed in the registry?

Can you reproduce problem by running same command on the Widows 10 without using RDC?

Using Google search of:  "scardgetcardtypeprovidername file not found" 
shows  related problems has been around for some time. 

Can you look  https://sourceforge.net/p/opensc/mailman/message/36300644/

**Comment by minfrin** [comment]
I have no native windows machine available, so cannot reproduce the problem without using RDC.

Opensc is installed on Windows 10.

pkcs15-tool --dump works fine.

Firefox with the opensc pkcs11 driver works fine.

How do I confirm that MyEID is listed in the registry? There are many cards listed under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards but nothing called "MyEID".

**Comment by minfrin** [comment]
Not seeing anything relevant in https://sourceforge.net/p/opensc/mailman/message/36300644/ - the paths are all the full path.

**Comment by minfrin** [comment]
There is also no "smart cards" entry under the Device Manager.

**Comment by dengert** [comment]
In addition to some utilities, OpenSC provides:  PKCS\#11 for every platform, and the minidriver  as a module for the Microsoft CSP.   Microsoft programs only use the CSP. Microsoft looks up the ATR in the Registry to find the module to use with a smartcard. (It also has some builtin drivers too.)

[customactions.cpp](https://github.com/OpenSC/OpenSC/blob/master/win32/customactions.cpp) is used to add many of the cards supported by OpenSC  to the registry. I don't see MyEID listed in the source.  If the following work, you could submit a PR to add the following to [customactions.cpp](https://github.com/OpenSC/OpenSC/blob/master/win32/customactions.cpp)

But on my Windows 10 pro 64bit I have: 
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\Aventra MyEID]
"ATR"=hex:3b,00,00,00,00,00,00,00,00,4d,79,45,49,44,00
"ATRMask"=hex:ff,00,00,00,00,00,00,00,00,ff,ff,ff,ff,ff,00
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"80000001"="myeiddrv.dll"
```

I had a demo card from them a few years ago, and I think Microsoft  loaded their driver. 

So you could the following to see if you can get it working. (Note 4d,79,45,49,44 is MyEID)

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\MyEID]
"ATR"=hex:3b,00,00,00,00,00,00,00,00,4d,79,45,49,44,00
"ATRMask"=hex:ff,00,00,00,00,00,00,00,00,ff,ff,ff,ff,ff,00
"Crypto Provider"="OpenSC CSP"
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"80000001"="C:\\Program Files\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"
```
Check the path.

This may also be needed: 
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Cryptography\Calais\SmartCards\MyEID]
"ATR"=hex:3b,00,00,00,00,00,00,00,00,4d,79,45,49,44,00
"ATRMask"=hex:ff,00,00,00,00,00,00,00,00,ff,ff,ff,ff,ff,00
"Crypto Provider"="OpenSC CSP"
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"80000001"="C:\\Program Files (x86)\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"
'''

**Comment by frankmorgner** [comment]
I think OpenSC doesn't register the minidriver for myeid, because the vendor provides a [preferred proprietary software](https://www.aventra.fi/downloads/).

**Comment by frankmorgner** [comment]
If you prefer OpenSC, please modify your registry as suggested above

**Comment by minfrin** [comment]
I modified the registry as recommended above, and the opensc minidriver now responds to the requests.

Is there a way in the installer to be able to select which cards you want opensc to be a driver for (with a warning I guess if an existing driver wants to support that card)?

**Comment by dengert** [comment]
Surprisingly, while answering #1758 I ran `certutil -v SCInfo` and it worked fine using the Aventra mindriver.  Now while looking at this issue, I reinserted the card and ran `certutil -v SCInfo` again and it failed with:
```
C:\Users\Doug>certutil -v SCInfo
CertUtil: -dump command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
```
Internet Options certificate shows "John Smith"  certificate signed by "Aventra Test CA 1".  I removed it. But `certutil -v SCInfo` still fails.  

Will try and restart windows.

**Comment by dengert** [comment]
Restart did not help. But with Aventra MyEID card inserted, updating the smart card driver using Device Manager from version 1.2.3.0 (4/16/2013) to driver found by Windows to version 2.1.3.0 (2/8/2019) appears to fix the problem.  `certutil -v -SCInfo` using their driver appears to work.

**Comment by frankmorgner** [comment]
@minfrin sure, that can be built. But I'm afraid there is not much incentive to do so. I'm not comfortable with unexperienced users modifying their Registry; while the experienced user should be able to do so based on some documentation. So I think the best *you* could do (if you're not a programmer) is to document your solution [here](https://github.com/OpenSC/OpenSC/wiki/Aventra-MyEID-PKI-card)
