### ISSUE TITLE
Gemalto CT710 - Broken pinpad support in Firefox

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#1741]
### Problem Description

When using a Gemalto CT710 reader with built in pinpad, Firefox doesn't let you enter the PIN on the pinpad.

### Proposed Resolution

When using a Gemalto CT710 reader with built in pinpad, Firefox should let you enter the PIN on the pinpad correctly.

### Steps to reproduce

See the attached video.

**Comment by minfrin** [comment]
[Screen Recording 2019-07-14 at 16.19.47.zip](https://github.com/OpenSC/OpenSC/files/3390001/Screen.Recording.2019-07-14.at.16.19.47.zip)

**Comment by minfrin** [comment]
[Screen Recording 2019-07-14 at 16.36.31.zip](https://github.com/OpenSC/OpenSC/files/3390011/Screen.Recording.2019-07-14.at.16.36.31.zip)

This video shows Firefox startup.

**Comment by minfrin** [comment]
This behaviour is triggered if a MyEID smartcard is inserted that has been configured but not yet finalised with:

`pkcs15-init --finalize`

**Comment by frankmorgner** [comment]
please send the output of
```
OPENSC_DEBUG=3 pkcs11-tool --test --login
```

**Comment by frankmorgner** [comment]
finalize needs to be called, to, well, finalize the card. The behavior is by design and [documented](https://github.com/OpenSC/OpenSC/wiki/Aventra-MyEID-PKI-card#initialization).
