### ISSUE TITLE
SHA-2 Support for CSP minidriver

### ISSUE THREAD

**Issue by thetechguy86** [OpenSC/OpenSC#1749]
### Problem Description
Does the OpenSC 0.19 CSP minidriver supports SHA-2 hash algorithms? When trying to use the SmartCard-HSM with Microsoft Certificate Services I only see an option for sha1.

### Steps to reproduce
1. Install OpenSC-win64_0.19.0.msi
2. Install ADCS
3. Configure ADCS
     a. When prompted, select "OpenSC CSP" from the drop-down
     b. sha1 is listed but not SHA256 or SHA512

**Comment by marcoh00** [comment]
All log messages until the crypto provider selection dialog: https://gist.github.com/marcoh00/dcc197c6c9b8ff138ad9ee426f0f464b

**Comment by frankmorgner** [comment]
Yes, we're supporting [up to SHA-512 if requested by the application](https://github.com/OpenSC/OpenSC/blob/12218d4b0b295d01b81c1e915282b06da438a7f1/src/minidriver/minidriver.c#L4672-L4698). I suppose ADCS is using some older interface that doesn't support the new mechanisms.
