### ISSUE TITLE
x86_64 not Recognized when ./configure

### ISSUE THREAD

**Issue by evso9816** [OpenSC/OpenSC#1759]
I have been installing p11-kit 0.23.16.1 on a Ubuntu 16.04 amd64.
Running ./configure --prefix=/path/to/prefix ... , I got the following:

checking whether it is safe to define EXTENSIONS... yes
checking build system type... x86_64-unknown-none
checking host system type... Invalid configuration ...': machine ...' not recognized
configure: error: /bin/bash build/litter/config.sub ... failed

Question: How may I solve it? Is there a problem with config.sub file?
I also tried the following, but didn't make a difference: ./configure --build=x86_64 --prefix=/path/to/prefix ..
[log.txt](https://github.com/OpenSC/OpenSC/files/3465431/log.txt)

**Comment by frankmorgner** [comment]
you're at the wrong place, use https://github.com/p11-glue/p11-kit/issues
