### ISSUE TITLE
Example code for opensc using Smart Card Authentication 

### ISSUE THREAD

**Issue by RohanKurane** [OpenSC/OpenSC#1765]
Hi, 

This is more of a research question than a software question. I am looking for some example code that does smart card Authentication using OpenSSL and X509 certificates stored on the smart card. 

I am thinking of using smart cards for user authentication and was wondering if there are any examples I can refer to ? This would include the PAM module as well. 

Thanks

**Comment by popovec** [comment]
https://github.com/OpenSC/   pam_p11, pam_pkcs11 

google -> pkcs11 examples

**Comment by dengert** [comment]
You asked about Smart Card Authentication amd OpenSSL. Along with OpenSC, build  https://github.com/OpenSC/libp11 which includes `engines-1.1/libpkcs11.so` where the 1.1 depends on the OpenSSL version.)  (OpenSC/engine_pkcs11 used to be a separate repository but is now part of libp11.)

The `libpkcs11.so`  engine can then be used with any OpenSSL command which supports an OpenSSL engine. `libpkcs11.so` loads the OpenSC pkcs11 module by default. 

Also see `openssl s_client` which is a simple SSL/TLS client that can use the engine.  `openssl s_server` is a simple SSL/TLS server which could use a smart card for the server key.

But there is more then just OpenSSL. 

FireFox and Thunderbird can use the OpenSC PKCS11 module as a "security Device". Under Tools->Options search for Security Devices or Certificates. Your web server needs to be setup to accept certificates and do the Authorization. 


On Windows, Internet Explorer, Edge and Chrome can use smart cards. You can install the OpenSC minidriver or use some vendor's middleware. 

As mentioned above there is pam_p11, pam_pkcs11 for local login.

OpenSSH has some support for PKCS11 too. 

 Windows login can use smart cards to authenticate to AD using the Kerberos PKINIT protocols. https://tools.ietf.org/html/rfc4556 and https://web.mit.edu/kerberos/krb5-1.13/doc/admin/pkinit.html

As mentioned above there is pam_p11, pam_pkcs11 for local login. 

 There are also a number of pam_krb5 packages that can use smart cards via PKINIT to authentication to a Kerberos KDC.  https://www.eyrie.org/~eagle/software/pam-krb5/  was the one we used. 

Before I retired, we used AD as the Kerberos KDC, with smart cards registered in AD, so one could used their PIV smartcard to login to AD from Linux, Windows or Mac, and access AFS or use OpenSSH with Kerberos, including delegated credentials. 

We also ran Shibboleth. The IDP used TLS for authentication  and used AD as its back end authorization database. A number of critical people were required to use smart cards to access some Shibboleth sites.  Google for: Shibboleth smart cards.

And if you want to delegate certificates see: https://www.ietf.org/rfc/rfc3820.txt This was used with the Globus Project. OpenSSL has support for proxy certificates.

**Comment by RohanKurane** [comment]
Thanks @popovec!

Thanks @dengert! - Here is what I want to do as starters - 
Use a Linux box. Have a user insert a smart card. Enter user login name. Enter user PIN. 
Get slot on smart card where X509 certificate exists. The X509 will be created previously by the user on the card. Get the X509 cert from the card and using the login info passed entered by the user, see if it is a match. If not, fail the login authentication request. 

Is there anything additional to the above that I may be missing ? 

Looks like pam_pkcs11 might be useful here. 

Thanks

**Comment by dengert** [comment]
"Is there anything additional to the above that I may be missing ?" If the user creates the X509, on a card provided by the user, the user could impersonate any one. You do not say how the user creates the key or the certificate. The only only way this will work is if the first time the certificate is seen by the host it is saved by the host and no other certificate is using the same key pair. (This is more like the OpenSSH keys with the private key on the card being associated with some user. )

Normally during the creation of a certificate  the key pair is generated on the card by the card. The public key is sent as part of a certificate request to a CA. The request has some identification of the user as part of subject usually CN. The CA then makes up the certificate and signs it and returns it to the user. The user would then write it on the card. 

Problem is if the user is in control of the card, there is no way to know the key was generated on the card or a copy of the key exists off the card. (User could have generated the key off the card then written it and the certificate to a number of cards and handed them out. There is also the possibility  the user is not using a smart card at all. 

Only way to guarantee a smart card is being used it to have the CA create the key on the card, finalize the card and give card to the user. A CA can also make sure all certificates have a different public key. 

The host would then only accept cards created bu the CA as the host would have the CA's certificate and verify the user's certificate. 

Consider what is your trust model.  google for: trust model pki
pam_pkcs11 should be OK.

**Comment by RohanKurane** [comment]
@dengert - Interesting. Im new to the smart card world and had not thought about this scenario. Thanks!

I will dig into pam_pkcs11 and see what it has to offer. PKCS#15 seems to provide functionality to generate keys and certs on the card itself. Is that something you have worked with ?

**Comment by dengert** [comment]
Have not done much with provisioning PKCS15 cards. My interest has been with PIV cards. 

What are you really trying to do. I don't expect answers to any of these but you need to look at what you are trying to do.  Is this just a learning exercise? Are you an individual trying to protect login to your own computers? Are you trying to setup a corporate environment? Are you looking to setup a service for customers, and don't really have to worry about their identity? Are you working for some government or agency to setup access for citizens? 


OpenSC supports PKCS15 smart cards, and cards that do not support PKCS15. These have card drivers that emulate PKCS15 internally.  Some of them have some form of tool to help with the provisioning.

For learning, look at some cards that are well documented, available in quantities of one and where the vendor has tools or has provided tools via OpenSC.

**Comment by RohanKurane** [comment]
@dengert Thanks!
I am trying to learn and implement login authentication using smart cards for an organization. 

I was thinking of integrating my application with OpenSC PKCS15 along with pam_pkcs11.  Am I on the right path thinking that ?

**Comment by dengert** [comment]
I don't know. This is getting into consulting, not smart card development. Good luck.

**Comment by RohanKurane** [comment]
Thanks for your help @dengert

**Comment by mouse07410** [comment]
With the abundance of PIV-compatible tokens and smart cards on the market, I think it's ~~stupid~~ a bad idea to choose a card for an organization that only speaks PKCS#15.

**Comment by RohanKurane** [comment]
@mouse07410 This is more of an experiment at this point. PKCS#15 seems widely accepted so I thought it might be a good starting point with the experiment. Thoughts ?

**Comment by mouse07410** [comment]
I already told you what I think.
