### ISSUE TITLE
Should C_GetSessionInfo be calling get_pin_info?

### ISSUE THREAD

**Issue by massey101** [OpenSC/OpenSC#1771]
### Problem Description

Trying to track down a problem with the smartcard plugin for gnome-settings-daemon and I'm unsure if the issue is in NSS or OpenSC. NSS opens a long lived session with the token as soon as it is added. It then polls `C_GetSessionInfo` in order to determine if the token has been quickly removed and then added, thus invalidating the session. When the session is invalidated it will open it again.

The problem comes in from the fact that `C_GetSessionInfo` calls `sc_pkcs15_get_pin_info` which hits the smartcard and causes the light to flicker constantly forever.

### Proposed Resolution

1. Determine that C_GetSessionInfo shouldn't be doing that and fix it.
2. Determine that C_GetSessionInfo is operating correctly and file the bug report with NSS to stop polling it.

**Comment by Jakuje** [comment]
I think NSS is trying to use `WaitForSlotEvent()` to detect these occasions and only if it fails, it tries to use the C_GetSessionInfo fallback.

**Comment by frankmorgner** [comment]
Just to be clear, NSS/gnome-settings-daemon are working as expected, i.e. they are detecting slot events correctly. But you think they shouldn't send any commands to the card to detect that, correct?

As pointed out, NSS should then use `WaitForSlotEvent` instead of `C_GetSessionInfo`. If you already have a debug session, you could check why OpenSC's implementation of `WaitForSlotEvent` errors, which leads NSS to use the polling instead.

**Comment by frankmorgner** [comment]
I think you need to look into `SECMOD_WaitForAnyTokenEvent`, what's going wrong. The code also has a comment that initializing nss with `NSS_INIT_NOPK11FINALIZE` will cause WaitForSlotEvent to be emulated instead of calling the function of the PKCS#11 module.

**Comment by massey101** [comment]
Yep. You are all right. After some further investigation NSS will try and call WaitForSlotEvent. This calls out to p11-kit which calls out to OpenSC and SoftHSM (which is also installed). SoftHSM hasn't implemented the WaitForSlotEvent function and returns CKR_FUNCTION_NOT_SUPPORTED which p11-kit passes back to NSS. NSS then goes into a fallback polling mode. Since strictly speaking it's not necessary for a module to supply WaitForSlotEvent it seems like no one is technically doing anything wrong.

Best bet might be to be implement WaitForSlotEvent in SoftHSM, but what happens when another module comes along that doesn't support it? Maybe it should be a required part of the PKCS11 spec?

**Comment by massey101** [comment]
> If all they want is card_removed, they could use other PKCS#11 calls.

Any ideas on what calls other than `C_WaitForSlotEvent` and 'C_GetSessionInfo` that could be used for determining if the card has been removed? A fallback that doesn't hit the smartcard would be a great addition as well.

**Comment by Jakuje** [comment]
Thank you for investigation. As a workaround, you can remove the softhsm module from p11-kit before the softhsm will get the needed functionality.

I don't think it is a good idea to invent new means for figuring out if the card was removed.

Do you plan to work on the needed SoftHSM changes?

**Comment by Jakuje** [comment]
FYI, I just modified my `/usr/share/p11-kit/modules/softhsm2.module` to list also
```
disable-in: gnome-settings-daemon
```
which prevents yubikey blinking all the time. In the long term, I think we should implement the SoftHSM WaitForSlotEvent.

**Comment by massey101** [comment]
> Do you plan to work on the needed SoftHSM changes?

Yep. It's looking pretty easy: https://github.com/opendnssec/SoftHSMv2/issues/370

@dengert Yeah. It's `secmod_HandleWaitForSlotEvent()` that causes the blinking.
