### ISSUE TITLE
Please cut a new release - it's been a year

### ISSUE THREAD

**Issue by dogweather** [OpenSC/OpenSC#1774]
There are lot of fixed bugs in master reported against 0.19.0, still the current version, [which is almost one year old](https://github.com/OpenSC/OpenSC/releases/tag/0.19.0).

Thanks for giving this some consideration!

**Comment by frankmorgner** [comment]
To speed up the process, please help fixing the blocking issues, see https://github.com/OpenSC/OpenSC/projects/6
