### ISSUE TITLE
MacOS: current master hangs or delays

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1775]
### Problem Description

Now access to a token takes multiple `C_GetSLotList()` calls on one system (where it still works).

On another system (using the current master with `libp11` engine and OpenSSL-1.1.1c) OpenSSL simply hangs when it's supposed to prompt me for a PIN during signing.

### Proposed Resolution

Don't know yes.

### Steps to reproduce

Build and install OpenSC and libp11. Try something like
```
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out /tmp/derive.60215.text.sig /tmp/derive.60215.text
```
and then
```
openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=publi
c" -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature /tmp/derive.60215.text.sig  /tmp/derive.60215.text
```

### Logs

SPY: 
[pss-out.txt](https://github.com/OpenSC/OpenSC/files/3548959/pss-out.txt)

On another machine, it simply hangs up:
```
$ openssl cms -engine pkcs11 -keyform engine -aes256 -decrypt -binary -inform PEM -in /tmp/derive.4113.text.cms -out /tmp/derive.4113.text.dec -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;object-type=private" 2>&1 ossl-out.txt
engine "pkcs11" set.


*************** OpenSC PKCS#11 spy *****************
Loaded: "/Library/OpenSC/lib/opensc-pkcs11.dylib"

0: C_GetFunctionList
2019-08-27 23:25:08.659
Returned:  0 CKR_OK

1: C_Initialize
2019-08-27 23:25:08.660
[in] pInitArgs = 0x7f91f3c276e0
     flags: 2
       CKF_OS_LOCKING_OK
Returned:  0 CKR_OK


```
There's nothing more on the screen, and despite `opensc_debug = 9;` in `opensc.conf`, `/tmp/opensc-debug.log` remains empty.

**Comment by frankmorgner** [comment]
Without logging, it's hard to say. Sounds like some locking problem. Try the standard configuration and run:
```
env OPENSC_DEBUG=9 openssl cms -engine pkcs11 -keyform engine -aes256 -decrypt -binary -inform PEM -in /tmp/derive.4113.text.cms -out /tmp/derive.4113.text.dec -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;object-type=private" 2>&1 ossl-out.txt
engine "pkcs11" set.
```
which should print debug information on stderr.

Also try reproducing the problem with
- OpenSC's pkcs11-tool
- libp11's examples (e.g. `listkeys` or `decrypt`)

**Comment by mouse07410** [comment]
The problem magically disappeared. `libp11` works, and so does `pkcs11-tool`. I'll re-open if it re-appears.
