### ISSUE TITLE
Cannot load engine in OpenSSL on Windows

### ISSUE THREAD

**Issue by supreetd21** [OpenSC/OpenSC#1777]
### Problem Description
OS: Windows 10 
OpenSSL version: 1.0.2 
Precompiled from https://slproweb.com/products/Win32OpenSSL.html

### Steps to reproduce
I want to sign a CSR using the private key in the Yubikey.
This works well on Linux based OS.

I followed the WIndows download steps to install OpenSC
https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start - 64bit

I have followed the Msys2 based installation for libp11

I have this issue with other OpenSSL versions:
https://github.com/OpenSC/libp11/issues/298 

### Logs
```
OpenSSL> version
OpenSSL 1.0.2s  28 May 2019
OpenSSL> engine -t dynamic -pre SO_PATH:/c/msys64/usr/lib/engines-1.1/libpkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/c/Program\ Files/OpenSC\ Project/OpenSC/pkcs11/opensc-pkcs11.dll
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/c/msys64/usr/lib/engines-1.1/libpkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(/c/msys64/usr/lib/engines-1.1/libpkcs11.dll)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
[Failure]: MODULE_PATH:/c/Program\
17440:error:260AC089:engine routines:INT_CTRL_HELPER:invalid cmd name:.\crypto\engine\eng_ctrl.c:131:
17440:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:.\crypto\engine\eng_ctrl.c:311:
     [ unavailable ]
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(\usr\local\ssl\lib\engines\Files\OpenSC\\)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
17440:error:2606A074:engine routines:ENGINE_by_id:no such engine:.\crypto\engine\eng_list.c:391:id=Files/OpenSC\
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(\usr\local\ssl\lib\engines\Project\OpenSC\pkcs11\opensc-pkcs11.dll)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
17440:error:2606A074:engine routines:ENGINE_by_id:no such engine:.\crypto\engine\eng_list.c:391:id=Project/OpenSC/pkcs11/opensc-pkcs11.dll
```
Is this an issue because OpenSSL, OpenSC & libp11 have been compiled with different toolchains?

I tried compiling libp11 using MSVC as well, it resulted in the following error.
nmake /f Makefile.mak OPENSSL_DIR=c:\OpenSSL-Win64 BUILD_FOR=WIN64
```
libpkcs11.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
````
I've been trying to compile OpenSSL 1.0.2 on Msys2 without much luck. Could you help me with a way to move forward?

**Comment by frankmorgner** [comment]
For your problem with libp11, please open an issue [here](https://github.com/OpenSC/libp11). Please beware that libraries generated from VC and Mingw64 are incompatible with each other, see https://github.com/OpenSC/OpenSC/issues/607

**Comment by supreetd21** [comment]
Sure, will open another issue in libp11.
The OpenSC libraries for Windows have been created by VC or Mingw64?

**Comment by supreetd21** [comment]
I could find a workaround wherein I installed 32bit versions of OpenSSL, OpenSC & compiled libp11 for 32 bit. 
It worked on Windows. I had faced some issues with MacOS earlier, though.

Closing the issue. Thank you @frankmorgner for your response.
