### ISSUE TITLE
MacOS many times the card is not recognized until I reboot

### ISSUE THREAD

**Issue by gbil** [OpenSC/OpenSC#1787]
### Problem Description

Many times the card is not recognized anymore and nothing helps eg. re-insert the reader, re-insert the card, kill opensc process, kill ifd process etc., I have to reboot the device

tried current 0.19 and beta 0.20 with the same result

this seems to happen randomly, initially it works and then stops 
 

### Logs

what I see in console when it doesn't work is:

No token driver found for card <TKSmartCardATR: 0x7fb0f80033a0 3b 18-00 T=1:--- T=1:fe58-;c903> ATR bytes: <3bd21800 8131fe58 c90316>

**Comment by frankmorgner** [comment]
Could you try the [updated release candidate](https://github.com/OpenSC/OpenSC/releases/tag/OpenSC-0.20.0-rc3), which fixed https://github.com/OpenSC/OpenSC/issues/1798#issuecomment-534856556?

**Comment by gbil** [comment]
I need to bump this as it still happens with Catalina and 0.20.0rc3 and nightlies 
every couple of days at most the card is no longer recognized under the CTK environment, I don't get the pairing notification when I insert my card but only the plain notification that I inserted the card. In PKSC11 applications the card still works but for everything else I need to reboot my system first

**Comment by frankmorgner** [comment]
let's start with the basics: What card do you have? Could you generate a debug log (see https://github.com/frankmorgner/OpenSCToken/#configuring-opensctoken)?
