### ISSUE TITLE
Travis vsmartcard checks broken

### ISSUE THREAD

**Issue by akemnade** [OpenSC/OpenSC#1792]
### Problem Description

During submission of PR #1791 the travis vsmartcard check did the following error:
++export LD_LIBRARY_PATH=/usr/local/lib
++LD_LIBRARY_PATH=/usr/local/lib
++sleep 5
++java -noverify -cp IsoApplet/src/:jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard isoapplet_jcardsim.cfg
Error: Could not find or load main class com.licel.jcardsim.remote.VSmartCard
++opensc-tool --card-driver default --send-apdu 80b800001a0cf276a288bcfba69d34f310010cf276a288bcfba69d34f3100100
Card not present.

That clearly does not look like a problem with my code but with the build test configuration.
Full log is here:
https://travis-ci.org/OpenSC/OpenSC/jobs/584216874

**Comment by Jakuje** [comment]
I think there is some non-determinism in the Travis runs. Mine failed there too (1772), while 1784 and 1788 passed just fine. This is already happening for some time and I was not able to figure out what is wrong there. But indeed it is good to track it.

**Comment by frankmorgner** [comment]
seems to work again
