### ISSUE TITLE
Token allows access with empty pin

### ISSUE THREAD

**Issue by jupa1986** [OpenSC/OpenSC#1801]
### Problem Description
I have a token  with  8 digit's pin, I used for signature and I try login with empty pin and all work, I did tests with windows, linux and mac, and with opensc 19 and 18.
### Steps to reproduce
```
pkcs15-tool --verify-pin
```

**Comment by frankmorgner** [comment]
What is the actual problem, what is your expected behavior?

@FeitianSmartcardReader ?

**Comment by jupa1986** [comment]
I think you just have to log in with the correct pin, in this case it works with the pin placed when initializing the token and empty.
