### ISSUE TITLE
Italian health insurance card: hints to read the public data

### ISSUE THREAD

**Issue by francescm** [OpenSC/OpenSC#1802]
### Problem Description

I have found some docs about Italian health insurance card (tessera sanitaria) a SmartCard/contactless card that belongs to the CNS family (https://github.com/OpenSC/OpenSC/wiki/Italian-CNS-and-CIE).

My docs are about the public data on the card: https://github.com/francescm/tessera_sanitaria

Do you think is worth to merge the tessera_sanitaria in OpenSC wiki?

**Comment by frankmorgner** [comment]
The ruby script, that you've referenced is not compatible with OpenSC. Also, it only shows how to read some personal data from the card, whereas OpenSC's main purpose is to make the card usable as security token with keys and certificates. If adding the card to the italian card driver, allows you using some keys from the card, then we happily merge your contribution.

**Comment by francescm** [comment]
no, it's something different and less dauntling. What I have found is not about certificates or private keys, it's only about public data (*).
Thank you for reading and triaging.

(*) nevertheless also public data can be useful, like for the kiosk where you pay the health services' fees. It shows you the fees related to a given tax payer number read from the public sectors of the tessera sanitaria.
