### ISSUE TITLE
FT ePass2003 - cannot create pkcs15 structure, again

### ISSUE THREAD

**Issue by faceless2** [OpenSC/OpenSC#1803]
I have what superficially looks like the same issues as https://github.com/OpenSC/OpenSC/issues/1669, except that it's 4 months since a fix for that was committed. I am running the nightly build from 20190916 on macOS, and the problem I have is that `pkcs15-init -C` gives "Not Allowed".

I've put the output of 
```
opensc-tool --version
echo "Erasing the card..."
pkcs15-init -vvvvvvv -E -T

echo "Creating the PKCS15 (onepin) structure.."
pkcs15-init -vvvvvvvvv -C -p pkcs15+onepin --pin 1234 --puk 123456
```
online at https://gist.github.com/faceless2/492b7db9d181920815b822a780c2710f. I also tried running the "FIX_TOOL" referenced in that issue - the logs *after* running that command are online at https://gist.github.com/faceless2/0f149fcae187973a59361cc6e06f9645: they look pretty similar to me so I'm not sure if it made a difference.

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by FeitianSmartcardReader** [comment]
@faceless2 MIke, already forward our engineer to check, we will get back to you soon, keep in touch,

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader, please hurry with the response so we can get any fixes which may arise into the new release. please also [make sure that your card works as expected](https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing) with the new release.

**Comment by faceless2** [comment]
Happy to provide more diagnostic information if that will help, just let me know.

(unrelated @frankmorgner - other than this we are thrilled with what will become 0.20, which is [working](https://bfo.com/blog/2019/09/23/perfect_pdf_digital_signatures_eu_style/ ) perfectly for us).

**Comment by majkrzak** [comment]
@FeitianSmartcardReader I have also encounterd similar problem, and I'm not able to reset token with FIX_TOOL due to 
```
Cannot find MF, please create P15 filesystem.
```
and erase it by pkcs15-init cause
```
P:5655; T:0x139656513173312 18:54:29.390 [pkcs15-init] card-epass2003.c:192:epass2003_check_sw: Security status not satisfied
```

**Comment by FeitianSmartcardReader** [comment]
@faceless2 it would be better to arrange remote session, let our engineer to double check, currently, they cannot reproduce the issue, so don't know how to solve it, thanks and looking forward to your rely

you can send mail to hongbin@ftsafe.com too for future communication.

THX

**Comment by FeitianSmartcardReader** [comment]
@faceless2 
Just back from R&D, we take a look the issue, and still cannot reproduce the issue, attachment is our build version, please take a look. and it will be good to have remote session to check the issue, thanks 
[OpenSC-0.19.0.dmg.zip](https://github.com/OpenSC/OpenSC/files/3797269/OpenSC-0.19.0.dmg.zip)

**Comment by IvanovAndrei1980** [comment]
Also having problems with my ePass2003 from Feitian.

.\pkcs15-init.exe --erase-card
Using reader with a card: FS USB Token 0
Failed to erase card: Security status not satisfied

.\pkcs15-init.exe --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 0000 --puk 111111 --label "ePass2003"
Using reader with a card: FS USB Token 0
Failed to create PKCS #15 meta structure: Not allowed

$ ./FIX_TOOL
[]===================================================[]
 |              FIX_TOOL_ePass2003/2003Auto         |
 |                                      FT V2.0     |
[]===================================================[]

Fixing.............

Cannot find MF, please create P15 filesystem.

**Comment by rindhane** [comment]
@FeitianSmartcardReader could you share 32-bit binaries for armv7l architecture of tool present here : [Fixtool](http://download.ftsafe.com/files/ePass/Fix_Tool.tar.gz). I am also facing the error “Failed to erase card: Security status not satisfied”  and unable to move forward with the solution indicated in [FAQ section](https://github.com/OpenSC/OpenSC/wiki/Feitian-ePass2003#faq) as the provided binaries are only for x86/x64. 
So please share the <ins>arm 32-bit</ins> binary of the [Fixtool](http://download.ftsafe.com/files/ePass/Fix_Tool.tar.gz).

**Comment by FeitianSmartcardReader** [comment]
@rindhane do you have cross compiler toolchain?

**Comment by FeitianSmartcardReader** [comment]
@rindhane if you are using windows, please use our private tool to do format.
http://download.ftsafe.com/files/reader/opensc/format_tool_2003.zip

**Comment by rindhane** [comment]
> @rindhane if you are using windows, please use our private tool to do format.
> http://download.ftsafe.com/files/reader/opensc/format_tool_2003.zip

@FeitianSmartcardReader Format tool doesn't work. Check out the enclosed screenshot of the initialization error thrown by the tool. 
![format Screenshot](https://user-images.githubusercontent.com/29147602/80989202-3cfe9080-8e52-11ea-9b38-c651c6a77b9f.jpg)

**Comment by rindhane** [comment]
> @rindhane do you have cross compiler toolchain?

@FeitianSmartcardReader, will you elaborate on the steps to cross-compile the [Fixtool]( http://download.ftsafe.com/files/ePass/Fix_Tool.tar.gz) ? As I understand, these are already compiled binaries and not source code files, so I am not sure how to make them work on armhf architecture.

**Comment by FeitianSmartcardReader** [comment]
@rindhane our engineer working on it, will give to you in these days, keep in touch,

**Comment by FeitianSmartcardReader** [comment]
[Fix_Tool_20200604.zip](https://github.com/OpenSC/OpenSC/files/4728394/Fix_Tool_20200604.zip)
@rindhane here you are, have a test, any questions, contact me anytime, thanks

**Comment by FeitianSmartcardReader** [comment]
BTW, update wiki and armhf architecture.
https://github.com/OpenSC/OpenSC/wiki/Feitian-ePass2003

**Comment by rindhane** [comment]
@FeitianSmartcardReader Thanks for providing the FIXTOOL for armhf architecture. Tried using the new fix tool but the problem still persists. 

` Using reader with a card: FT ePass2003Auto 00 00 
Failed to erase card: Security status not satisfied. `

I have attached the fixtool's terminal output for all three cases of delete, restore & format by the tool. 

[DELETE_FIX_TOOL.txt](https://github.com/OpenSC/OpenSC/files/4741641/DELETE_FIX_TOOL.txt)
[FORMAT_FIX_TOOL.txt](https://github.com/OpenSC/OpenSC/files/4741643/FORMAT_FIX_TOOL.txt)
[RESTORE_FIX_TOOL.txt](https://github.com/OpenSC/OpenSC/files/4741644/RESTORE_FIX_TOOL.txt)

**Comment by FeitianSmartcardReader** [comment]
@rindhane Will back tomorrow and back to you then, keep in touch, 

BTW, do you have your running command and pcscd log for us? that may helpful, thanks

**Comment by rindhane** [comment]
@FeitianSmartcardReader , I have attached the logs. Check if that helps.  
The pcscd log is for `echo 3 | ./fix_tool_armhf`  and `pkcs15-init -E` commands.

Logs:
[1_FORMAT.txt](https://github.com/OpenSC/OpenSC/files/4742054/1_FORMAT.txt)
[pcscd_log.txt](https://github.com/OpenSC/OpenSC/files/4742055/pcscd_log.txt)
[pkcs15-init -E -vvv.txt](https://github.com/OpenSC/OpenSC/files/4742056/pkcs15-init.-E.-vvv.txt)

**Comment by FeitianSmartcardReader** [comment]
Noted, back to you tomorrow, thanks

**Comment by FeitianSmartcardReader** [comment]
[Fix_Tool_20200611.zip](https://github.com/OpenSC/OpenSC/files/4768471/Fix_Tool_20200604.zip)
@rmartinc try the new version, thanks

**Comment by colombin** [comment]
I got the same problem. When i try to delete the card with "pkcs15-init -E" i get the error "Failed to erase card: Security status not satisfied". Tried to to fix it with the fix_tool too without success. I'm using ubuntu 20.10.

**Comment by FeitianSmartcardReader** [comment]
what's your opensc version? the latest 0.21.0 fix the security status failure issue, have a look https://github.com/OpenSC/OpenSC/issues/2061

**Comment by colombin** [comment]
oh ok. i have 0.20.0 installed. i will try the new version later that day. thank you very much!

**Comment by colombin** [comment]
It work for me with the new version. Great work guys. Thanks

**Comment by FeitianSmartcardReader** [comment]
Good, thanks

**Comment by Jakuje** [comment]
This looks like it is resolved for some time. If you still have the issue, please open a new one.
