### ISSUE TITLE
PIVKey ATR string for OpenSC

### ISSUE THREAD

**Issue by noloader** [OpenSC/OpenSC#1806]
I'm working with [Taglio PIVKey cards](https://pivkey.com/). I noticed Ubuntu 18.04 and OpenSC 0.19.0's [`opensc.conf`](https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in) do not appear to have support/card_atr for the C910 and C980 cards.

You can find the card ATR string at [PIVKey on Linux](https://pivkey.zendesk.com/hc/en-us/articles/203578629-PIVKey-on-Linux):

```
card_atr 3B:9F:95:81:31:FE:9F:00:66:46:53:05:10:00:11:71:DF:00:00:00:00:00:02 {
    name = "PIVKey";
    driver = "piv";
}
```

**Comment by dengert** [comment]
In the opensc.conf you could add `type = 14014;` which would set `SC_CARD_TYPE_PIV_II_PIVKEY`
See `cards.h` for other values.  Not sure if this will work in 0.19.0. 

If you have additional PIVKey type cards you can submit a PR. 
See card-piv.c in master which already has:
```
232         /* PIVKEY from Taligo */
 233         /* PIVKEY T600 token and T800  on Feitian eJAVA */
 234         { "3B:FC:18:00:00:81:31:80:45:90:67:46:4A:00:64:2D:70:C1:72:FE:E0:FE", NULL, NULL, SC_CARD_TYPE_PIV_II_PIVKEY, 0, NULL },
 235 
 236         /* PIVKEY C910 */
 237         { "3b:fc:18:00:00:81:31:80:45:90:67:46:4a:00:64:16:06:f2:72:7e:00:e0", NULL, NULL, SC_CARD_TYPE_PIV_II_PIVKEY, 0, NULL },
 238 
 239         /* PIVKEY C980 */
 240         { "3B:f9:96:00:00:81:31:fe:45:53:50:49:56:4b:45:59:37:30:28", NULL, NULL, SC_CARD_TYPE_PIV_II_PIVKEY, 0, NULL },
```
Your ATR for 910 does not match what is in current `card-piv.c`

Note the `SC_CARD_TYPE_PIV_II_PIVKEY`  is used set card issues for cards which do not  fully follow the NIST standards.  Grep for `SC_CARD_TYPE_PIV_II_PIVKEY` to see where it is used. 

If needed `SC_CARD_TYPE_PIV_II_PIVKEY-2` can be defined to set different card issues.

**Comment by noloader** [comment]
@dengbert,

Thanks.

Forgive my ignorance... is `opensc.conf` no longer used to identify cards?

(I thought I got that off the wiki, but I may be mistaken).

**Comment by frankmorgner** [comment]
It is, but the idea is to remove everything from `opensc.conf` that should work by default. That's why the default ATRs were moved into the code.

**Comment by dengert** [comment]
For a PIV card the ATR is not required. A card is considered a PIV card if it responds to a 
SELECT FILE for the PIV AID. This allows other PIV like cards to work without having to list the ATR in the code. 

The ATRs in the code are there to help identify cards that differ from the standard, may have extensions to the PIV standards or may have multiple applets on the card, like CAC+PIV or OpenPGP+PIV.

The code will also look for vendor specific files, such as the Yubico version. 



To support new PIV cards that are similar to known PIV cards, you can still add a card_atr to opensc.conf

For example, I can uncomment this for some testing:
```
# make card 8004 look like generic to test reading CCC
#       card_atr 3b:df:96:00:81:b1:fe:45:1f:83:80:73:cc:91:cb:f9:a0:00:00:03:08:00:00:10:00:79 {
#               driver = "PIV-II";
#               type = 14001;
#       }
```
