### ISSUE TITLE
Common Access Card misidentifed as PIV

### ISSUE THREAD

**Issue by candrews** [OpenSC/OpenSC#1811]
### Problem Description
OpenSC misidentifies my CAC as a PIV card.

I'm not able to login to anything using Firefox or Chome (in both, I get prompted for a PIN, enter it, but then the certificate selection dialog doesn't show any certificates from the smartcard, only those from client certificate files I have), but I'm unsure if that issue is caused by this one.

I'm using opensc 0.19.0 on Fedora 31.

### Steps to reproduce
```
$ opensc-tool --atr
Using reader with a card: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
3b:db:96:00:80:1f:03:00:31:c0:64:b0:f3:10:00:07:90:00:80

$ opensc-tool --reader 0 --name -v
Connecting to card in reader Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00...
Using card driver Personal Identity Verification Card.
Card name: Personal Identity Verification Card

$ pcsc_scan 
Using reader plug'n play mechanism
Scanning present readers...
0: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
 
Thu Sep 26 14:41:00 2019
 Reader 0: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
  Card state: Card inserted, 
  ATR: 3B DB 96 00 80 1F 03 00 31 C0 64 B0 F3 10 00 07 90 00 80

ATR: 3B DB 96 00 80 1F 03 00 31 C0 64 B0 F3 10 00 07 90 00 80
+ TS = 3B --> Direct Convention
+ T0 = DB, Y(1): 1101, K: 11 (historical bytes)
  TA(1) = 96 --> Fi=512, Di=32, 16 cycles/ETU
    250000 bits/s at 4 MHz, fMax for Fi = 5 MHz => 312500 bits/s
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 1F --> Y(i+1) = 0001, Protocol T = 15 - Global interface bytes following 
-----
  TA(3) = 03 --> Clock stop: not supported - Class accepted by the card: (3G) A 5V B 3V 
+ Historical bytes: 00 31 C0 64 B0 F3 10 00 07 90 00
  Category indicator byte: 00 (compact TLV data object)
    Tag: 3, len: 1 (card service data byte)
      Card service data byte: C0
        - Application selection: by full DF name
        - Application selection: by partial DF name
        - EF.DIR and EF.ATR access services: by GET RECORD(s) command
        - Card with MF
    Tag: 6, len: 4 (pre-issuing data)
      Data: B0 F3 10 00
    Mandatory status indicator (3 last bytes)
      LCS (life card cycle): 07 (Operational state (activated))
      SW: 9000 (Normal processing.)
+ TCK = 80 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B DB 96 00 80 1F 03 00 31 C0 64 B0 F3 10 00 07 90 00 80
	DoD CAC, Oberthur ID One 128 v5.5 Dual
```
The card is really CAC.

### Logs

Output of `opensc-tool --reader 0 --name -v ` with `debug=3`: [opensc.log](https://github.com/OpenSC/OpenSC/files/3659415/opensc.log)

**Comment by dengert** [comment]
You appear to have a  dual CAC PIV card.  From https://www.cac.mil/Common-Access-Card/Developer-Resources/    "Listing of all DoD Token platforms/configurations (as of July 2019)"

Click on the download button to get:
https://www.cac.mil/Portals/53/Documents/DoD%20Token%20utilziation%20and%20variation%20matrix%20v2_05_30July2019.docx?ver=2019-09-13-084729-920

See: The second column in the Current-Platforms. 

You can force OpenSC to select the CAC driver before the PIV driver in a number of ways. To see the list of drivers by running `opensc-tool ---list-drivers` 
You can then  change in opensc.conf to only use the drivers you want on your system and change the order. 
Or use the env "OPENSC_DRIVER=cac" to force the use of the CAC driver. 

The DUAL CAC/PIV cards share some of the common keys and certificates between the CAC and PIV applets on the card. Is you card a new issue? Normally if your card is a CAC only card there would be no PIV applet on the card, so the PIV driver would not be selected. 

There where some changes made to OpenSC that might address this issue that are not in 0.19.0
Can you try the [0.20.0-rc1](https://github.com/OpenSC/OpenSC/releases/tag/0.20.0-rc1)

**Comment by candrews** [comment]
> Is you card a new issue?

Yes, issued September 9, 2019.



> There where some changes made to OpenSC that might address this issue that are not in 0.19.0
> Can you try the [0.20.0-rc1](https://github.com/OpenSC/OpenSC/releases/tag/0.20.0-rc1)

Sure, I can try that - however, before I go down the rabbit hole of building it myself, do you happen know if there is a package for Fedora I could use?

**Comment by dengert** [comment]
Easiest thing to try today is the env variable or change opensc.conf

**Comment by dengert** [comment]
You said it was issued  September 9, 2019. 
The tests above do not read any certificates on the card  accept for using a browser. 
It could be the certificates on the card have changed so no acceptable certificate is found. 

When you enter the PIN does complain about a bad PIN?

Can you try `pkcs11-tool -O`  with `debug=3;` This will will force it to try and read certificates (with the public key)  and show objects it has on the card.  ` pkcs11-tool -O --login` will also show there are private keys and objects on the card. (But not the actual key.)

Does anyone you know with a new issued card have the same problem?
Does it always fail? 
Does it fail on other machines?
Did your previous card work as CAC? 
Does it work on Windows? Microsoft has builtin support for PIV.

Some other possibilities:
1. old cards were CAC only but new cards are dual CAC and PIV as that was the intent of HSPD-12  
2. new certificates have changed so are not recognized by the web server, i.e. maybe a different CA certificate chain.  
3. new cards for everyone in your group are not fully populated
4. your individual card was not fully populated 

I suspect this could be a combination of 1 and 2. 

To read the certificate(s) you can use this. change the 01 to 02, 03, 04 t see all four:
`pkcs15-tool --read-certificate 01 | openssl x509 -text -noout`

**Comment by mouse07410** [comment]
I'm using CAC with PIV driver and Firefox successfully.

Firefox had a config option to automatically select certificates. You want to find it and turn it **off**.

**Comment by candrews** [comment]
> Easiest thing to try today is the env variable or change opensc.conf

No change; Firefox still doesn't show show any certificates from the smart card. (I actually changed `/etc/opensc.conf` setting `card_drivers = cac` under `app default`).

> When you enter the PIN does complain about a bad PIN?

No, the PIN is accepted without complaint.



> Can you try `pkcs11-tool -O` with `debug=3;` This will will force it to try and read certificates (with the public key) and show objects it has on the card. ` pkcs11-tool -O --login` will also show there are private keys and objects on the card. (But not the actual key.)

```
$ pkcs11-tool -O 
Using slot 0 with a present token (0x0)
Data object 831397392
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 831397488
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 831397584
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 831397680
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 831398064
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 831398160
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 831398256
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 831398352
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>
```
debug log output for that: [pkcs11-tool-O-opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/3660289/pkcs11-tool-O-opensc-debug.txt)

```
$ pkcs11-tool -O --login
Using slot 0 with a present token (0x0)
Logging in to "PIV_II".
Please enter User PIN: 
Data object 3045531536
  label:          'Cardholder Fingerprints'
  application:    'Cardholder Fingerprints'
  app_id:         2.16.840.1.101.3.7.2.96.16
  flags:           private
Data object 3045531632
  label:          'Printed Information'
  application:    'Printed Information'
  app_id:         2.16.840.1.101.3.7.2.48.1
  flags:           private
Data object 3045531728
  label:          'Cardholder Facial Image'
  application:    'Cardholder Facial Image'
  app_id:         2.16.840.1.101.3.7.2.96.48
  flags:           private
Data object 3045531152
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 3045531248
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 3045531344
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 3045531440
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 3045531824
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 3045531920
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 3045532016
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 3045532112
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>
```
debug log output for that: [pkcs11-tool-O--login-opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/3660292/pkcs11-tool-O--login-opensc-debug.txt)

> Does anyone you know with a new issued card have the same problem?

Unfortunately no... all of my colleagues use Windows or Mac.

> Does it always fail?

Yes.

> Does it fail on other machines?

I don't know; I don't have any other systems to test.

> Did your previous card work as CAC?

Yes, my previous card (which I don't have as DoD confiscates expired one) did work as a CAC and worked without trouble on this system.

> Does it work on Windows? Microsoft has builtin support for PIV.

Yes, this CAC works on Windows (I have Windows in a VM on this system, so it's even using the same smart card reader).



>     1\. old cards were CAC only but new cards are dual CAC and PIV as that was the intent of HSPD-12

Since my old card was detected as a CAC, I suspect you're right. (I really wish I still had the old one!)



>     2\. new certificates have changed so are not recognized by the web server, i.e. maybe a different CA certificate chain.

I don't believe so. The same CAC on the same computer with the same card reader works with the same web sites on Windows.



>     3\. new cards for everyone in your group are not fully populated
>     4\. your individual card was not fully populated

Is there a way I can tell? I'm also skeptical of these possibilities, as the CAC works in Windows. But I'm more than happy to do testing!


> To read the certificate(s) you can use this. change the 01 to 02, 03, 04 t see all four:
> `pkcs15-tool --read-certificate 01 | openssl x509 -text -noout`

There seems to be a problem with that:
```
$ pkcs15-tool --read-certificate 01 | openssl x509 -text -noout
Using reader with a card: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
Certificate with ID '01' not found.
unable to load certificate
140098756077376:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
$ pkcs15-tool --read-certificate 02 | openssl x509 -text -noout
Using reader with a card: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
Certificate with ID '02' not found.
unable to load certificate
139981491316544:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
$ pkcs15-tool --read-certificate 03 | openssl x509 -text -noout
Using reader with a card: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
Certificate with ID '03' not found.
unable to load certificate
139749641484096:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
$ pkcs15-tool --read-certificate 04 | openssl x509 -text -noout
Using reader with a card: Identiv SCR3500 A Contact Reader [CCID Interface] (54301709612490) 00 00
Certificate with ID '04' not found.
unable to load certificate
140369658423104:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```
Here's the opensc debug log: 
[pkcs15-tool--read-certificate-01-opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/3660310/pkcs15-tool--read-certificate-01-opensc-debug.txt)


> Firefox had a config option to automatically select certificates. You want to find it and turn it **off**.
![Screenshot from 2019-09-26 19-52-47](https://user-images.githubusercontent.com/194713/65732315-51e29c80-e097-11e9-9996-d08e9fda440f.png)

I already have that off :)

**Comment by mouse07410** [comment]
Delete site data and browser cache, and try again... Unless you had that config fixed before even trying to access a DoD site (presumably OWA or mail.mil).

**Comment by dengert** [comment]
Aah!
Your new card has 3 compressed certificates but OpenSC was built without zlib, so they are read but can not be used. 

```
Line 1941 0x7f298f515740 19:44:52.536 [opensc-pkcs11] card-piv.c:1123:piv_cache_internal_data: PIV compression not supported, no zlib
Line 2222 0x7f298f515740 19:44:54.226 [opensc-pkcs11] card-piv.c:1123:piv_cache_internal_data: PIV compression not supported, no zlib
line 2500 0x7f298f515740 19:44:55.830 [opensc-pkcs11] card-piv.c:1123:piv_cache_internal_data: PIV compression not supported, no zlib
```

You need a new build of OpenSC.

**Comment by candrews** [comment]
> You need a new build of OpenSC.

I've reported this to Fedora at https://bugzilla.redhat.com/show_bug.cgi?id=1756326

Thank you!

**Comment by candrews** [comment]
I can confirm that building opensc with zlib fixed my problem.

Thank you very much for your help!

**Comment by Jakuje** [comment]
I already fixed the Fedora package so I think this can be closed @dengert ?

**Comment by dengert** [comment]
Yes it can be closed. Some PIV cards need zlib, and I suspect most new gov issued certificates will be zipped.
