### ISSUE TITLE
is Titan key possible to custom like Yubikey can custom ssh or write by OpenSC ?

### ISSUE THREAD

**Issue by athlona64** [OpenSC/OpenSC#1812]
### Problem Description

is Titan key possible to custom like Yubikey can custom ssh or write by OpenSC ?

**Comment by frankmorgner** [comment]
No. According to the docs, the titan key only supports FIDO, which is not supported by OpenSC. (There is, however, some module to integrate FIDO with ssh, but that's beyond the scope of OpenSC...)
