### ISSUE TITLE
pkcs11-register is inconsistent across browsers

### ISSUE THREAD

**Issue by jimmytheneutrino** [OpenSC/OpenSC#1818]
### Problem Description

Currently the default OpenSC setup fails for Chrome and esteid cards:
on authentication it asks for all certificates (including signing) and their pins.

This is because by default pkcs11-register is setting up (suitable for esteid) onepin-opensc-pkcs11 provider for Firefox but just opensc-pkcs11 provider for Chrome.

See https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-register.c#L234
and note the lack of this hack in `add_module_chrome` function in the same file.

Note that even if one manually sets the nssdb/pkcs11.txt correctly for Chrome, by default it will be again misconfigured on the start of the user session, because of the `pkcs11-register.desktop` file residing in `/etc/xdg/autostart`.
 
### Proposed Resolution
Although this problem can be fixed on the distro level by appending `-m /usr/lib/onepin-opensc-pkcs11.so` to the `Exec` line of `/etc/xdg/autostart/pkcs11-register.desktop` (or just removing the file altogether), IMO a more general solution is preferable.

Several different variants of resolution are possible:
1. Just use onepin-opensc-pkcs11 provider in `add_module_chrome` by default in the same way as it is done in `add_module_firefox`.
2. Allow specifiying the default pkcs11 provider in OpenSC configuration. 

### Steps to reproduce
As I said, the problem can be fixed by distro with patches. So let us try on Archlinux (where it is not currently fixed) 
installing the current version (0.20.0+rc1+6+gd4a97c69-1) of the package via AUR's opensc-git.
1. Install opensc-git.
2. Insert esteid id-card (I have a newer one issued since 2018, but I am not sure if this is relevant).
3. Open Chrome and try to login via id-card (e.g., to eesti.ee). You will be asked PIN2 (PIN for the signing certificate not for the authentication certificate). Here a normal user should stop but if we proceed we will be asked PIN1 (for authentication certificate) then a dialog to choose the certificate, then again PIN1.
4. Close Chrome and fix the problem by deleting ~/.pki/nssdb/pkcs11.txt
and doing e.g., 
```modutil -force -dbdir sql:$HOME/.pki/nssdb -add opensc-pkcs11 -libfile /usr/lib/onepin-opensc-pkcs11.so -mechanisms FRIENDLY```
Now trying to login in Chrome will work smoothly asking only for PIN1.
~/.pki/nssdb/pkcs11.txt will contain something like
```
library=/usr/lib/onepin-opensc-pkcs11.so
name=opensc-pkcs11
NSS=slotParams={0x00000000=[slotFlags=PublicCerts ] 0x00000001=[slotFlags=PublicCerts ] }
```
5. Do a reboot.
6. GOTO 2-3. This is because pkcs11-register invoked on startup added lines
```
library=/usr/lib/opensc-pkcs11.so 
name=OpenSC smartcard framework (0.20)
```
to `~/.pki/nssdb/pkcs11.txt`.

**Comment by frankmorgner** [comment]
Hmm, I was not aware that Chrome suffers from the same problem as Firefox. Are there more Browsers affected?

Also, the NSS DB in `~/.pki/nssdb` may be used my more programs than just Chrome, e.g. some Mail program that needs the signature PIN/key. Could you request some feedback from the distro maintainers?

Maybe a better solution would be to just disable the automatic configuration of Chrome...

**Comment by jimmytheneutrino** [comment]
> Could you request some feedback from the distro maintainers?

I mean, as I said, this is easily fixable on the distro level. But why not solve it upstream?

If you think it is dangerous to enable onepin by default there, then 
> Maybe a better solution would be to just disable the automatic configuration of Chrome...

seems like the easiest approach. It would certainly keep the status quo with the latest released version.

Maybe another (a bit more involved) possibility would be for the script to check if 
some (onepin-)opensc-pkcs11 provider is already present and in that case do nothing.
This would probably require the addition of some `--force` or `--overwrite` flag to the util.

**Comment by frankmorgner** [comment]
I'd like to fix this upstream, therefor I need to know whether the nss DB in `~/.pki/nssdb` is used for anything else than Chrome. If so, it would be impossible to use a non-auth key by hard-wiring onepin-opensc-pkcs11.so here. If not, I'd happily use onepin-opensc-pkcs11 here as well.

**Comment by frankmorgner** [comment]
`apt-rdepends -r libnss3` lists evolution and OpenJDK as direct dependents, but I'm not sure whether they're capable of using PKCS#11 modules that are exposed via NSS.

**Comment by jimmytheneutrino** [comment]
This may useless info, but

In archlinux, direct dependents on `nss` are:
`389-ds-base  badvpn  bluegriffon  ceph  ceph-libs  ceph-mgr  chromium  chrony  cinnamon-settings-daemon  discord  ecryptfs-utils  electron  electron2  electron4
                  evolution-data-server  firefox  firefox-developer-edition  flashplugin  gnome-settings-daemon  jre-openjdk-headless  jre10-openjdk-headless
                  jre11-openjdk-headless  jre7-openjdk-headless  jre8-openjdk-headless  lib32-nss  libcacard  libfprint  libnm  liboauth  libpurple  libreoffice-fresh
                  libreoffice-still  mate-settings-daemon  opera  pesign  pkcs11-helper  poppler  qca  qcef  qt5-webengine  seamonkey  sssd  steam  thunderbird  volume_key  xmlsec`,
but it cannot tell which of them actually use `~/.pki/nssdb`. E.g. `firefox` does not, although it uses `nss`.

**Comment by Samcro6160** [comment]
Iò

**Comment by frankmorgner** [comment]
Please try https://github.com/OpenSC/OpenSC/pull/1828

**Comment by jimmytheneutrino** [comment]
Please see comment in #1828

**Comment by jimmytheneutrino** [comment]
#1828 seems to be working fine
