### ISSUE TITLE
secp384r1 does not work.

### ISSUE THREAD

**Issue by jc-lab** [OpenSC/OpenSC#1824]
OpenSC Version : 0.20.0-rc1 (Applied #1696)

```bash
> pkcs11-tool.exe --list-slots
Available slots:
Slot 0 (0x0): Generic Smart Card Reader Interface 0
  token label        : 
  token manufacturer : www.CardContact.de
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 24.13
  firmware version   : 2.5
  serial num         : 
  pin min/max        : 6/15

> pkcs11-tool.exe -l -p xxxxxxxx --keypairgen --key-type=EC:secp384r1 --id xxxxxxxx
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GenerateKeyPair failed: rv = CKR_DATA_INVALID (0x20)
Aborting.
```
prime128v1, secp256r1, secp521r1 work fine. Only secp384r1 doesn't work.

**Comment by popovec** [comment]
Seems this is card specific issue. Latest commit eac516f  CI tests on travis: https://travis-ci.org/OpenSC/OpenSC/jobs/593030382 line 1988 -  here secp384r1 generation is fully working on simulated MyEID card.


What about `opensc-tool --list-algorithms`  is ec key length 384 listed for your token ? 
```
Algorithm: ec
Key length: 384
Flags: onboard key generation
```

Is this issue specific for pkcs11-tool ? Please recheck generation by pkcs15-init:

`pkcs15-init --generate-key ec-secp384r1 --auth-id 1 --pin xxxxxxxx --label gen_secp384r1`

**Comment by jc-lab** [comment]
@popovec 

opensc-tool --list-algorithms comes with support.

```bash
Algoruthm: ec
Key length: 384
Flags: onboard key generation
```

pkcs15 does not work for me..

```
> pkcs15-init --store-pin --auth-id 01 --label "NAME"
Using reader with a card: Generic Smart Card Reader Interface 0
New User PIN.
Please enter User PIN: Please type again to verify: Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK):
Failed to store PIN: Invalid arguments

> pkcs15-init.exe --generate-key ec-secp256r1 --auth-id 01 --label test_01
Using reader with a card: Generic Smart Card Reader Interface 0
Failed to generate key: Security status not satisfied

> pkcs15-init.exe --generate-key ec-secp384r1 --auth-id 01 --label test_02
Using reader with a card: Generic Smart Card Reader Interface 0
Failed to generate key: Security status not satisfied
```

**Comment by CardContact** [comment]
Your device is a SmartCard-HSM EA+ version 2.5. That variant only supports RSA keys up to 2048 bit and ECC keys up to 320 bit.

For larger keys you need the SmartCard-HSM 4K version that supports RSA keys up to 4096 and ECC keys up to 521 bit.

For initialization you need to use the sc-hsm-tool. The --store-pin mechanism is not supported.

**Comment by popovec** [comment]
some things are not clear ..  from 1st post: "prime128v1, secp256r1, secp521r1 work fine. Only secp384r1 doesn't work."

Is secp521r1 really working ? 


ec 384 is announced - and is not working .. 

Card driver init function should check the token version,  and only really available ec algorithms should be announced.

**Comment by jc-lab** [comment]
@popovec @CardContact 
Thank you for answer.
And sorry for the confusion.
secp521r1 also should not.
I was confused because I created a secp521r1 key pair with NitroKey HSM 2 before.
