### ISSUE TITLE
"ASN.1 parsing of algo ID failed" while listing public keys from PIV card

### ISSUE THREAD

**Issue by z4yx** [OpenSC/OpenSC#1837]
### Problem Description

When I use `pkcs15-tool --list-public-keys` or `pkcs15-tool -D` on my PIV card, it shows the certificate in slot 9A, but no public keys. It seems that pkcs15-tool failed to parse the algorithm fields from cert.

The card works fine with `yubico-piv-tool -s 9a -a read-certificate` and `yubico-piv-tool -s 9a -a verify-pin -a test-signature`.

### Steps to reproduce

```
# Ubuntu 19.10
# opensc 0.19.0-2
# yubico-piv-tool 1.7.0
yubico-piv-tool -a generate -s 9a
yubico-piv-tool -s 9a -a verify-pin -a selfsign-certificate -S '/CN=CertAtSlot9a/'
yubico-piv-tool -a import-certificate -s 9a
pkcs15-tool --list-public-keys
```

The certificate in slot 9A is:

```
-----BEGIN CERTIFICATE-----
MIIDBDCCAeygAwIBAgIJAPC48VqYkLqMMA0GCSqGSIb3DQEBCwUAMBcxFTATBgNV
BAMMDENlcnRBdFNsb3Q5YTAeFw0xOTEwMjYxMDIyNDBaFw0yMDEwMjUxMDIyNDBa
MBcxFTATBgNVBAMMDENlcnRBdFNsb3Q5YTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBANfenj2TCn0mlF+VX9x20vldozT8F8Knc3duyp3q+Rq+FdkLnTKN
QbzmCmdeDWMSINJpGqGfPdfiHI10nZRO2euDUwDPYIm6FqD5snX58GXkUgszBU/s
QsH0MZpBqV6j4aBfNLgIA1T/gtzhHmbbWCq8N3pShwBTmRQEcpocdGzk7IVXLxzM
/clVexCPsnQ/tuSFU1CFXgK9VB0HE63lupRwmc15rXA4/JKN9gnxDdot939wpHdV
YzcWQXaZEDFbYzlFqo3qJcftUg1wtZwbjBY8gWfihKpCiaP+azqLV4R8dEkJSfhQ
yCtL4yFH5nkCwD5S+Inktd06Ma4Lt1mYUfcCAwEAAaNTMFEwHQYDVR0OBBYEFP/Z
6jyfBJbH+h5IZZquEWWC38r5MB8GA1UdIwQYMBaAFP/Z6jyfBJbH+h5IZZquEWWC
38r5MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAInf2I9LvVJE
2QUp4zMdxbtspu28kCP7HyKws4Rv7dC7WbMQ8j5VZC28bmqO0yf/o64KkZFpX3d9
4YrVLvtqWHF/GEFo4bAuTPF6p9pcNZXKGGlpshOTOmUvvCP6MRmSpBflp4ZbAJ3Y
+G9IUVxRLyNRP1xsTbnLXROqyQNoFX6zUprgmE5do64cgtYX8Wlv7abYZ7CgtdcB
Zey4vXvSsXyVV3zRNWbmjVJfvb7u4+DLmS+QKRFtFesAe+XSl2e6zGMICyZ8TPvg
WP1enuCu8kdErB3cb31xgg4Zr6ZFO6hnRmyW3qrFYbKzhHTXRKBCA2dINGenLEe0
ICWAv4LBcgg=
-----END CERTIFICATE-----
```
which can be recognized by `openssl x509 -text`

### Logs

```
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-cert.c:370:sc_pkcs15_read_certificate: called
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-pubkey.c:1329:sc_pkcs15_pubkey_from_spki_fields: sc_pkcs15_pubkey_from_spki_fields() called: 0x55850e6cb85d:290
300D06092A864886F70D010101050003 82010F003082010A0282010100D7DE9E 3D930A7D26945F955FDC76D2F95DA334
FC17C2A773776ECA9DEAF91ABE15D90B 9D328D41BCE60A675E0D631220D2691A A19F3DD7E21C8D749D944ED9EB835300
CF6089BA16A0F9B275F9F065E4520B33 054FEC42C1F4319A41A95EA3E1A05F34 B8080354FF82DCE11E66DB582ABC377A
52870053991404729A1C746CE4EC8557 2F1CCCFDC9557B108FB2743FB6E48553 50855E02BD541D0713ADE5BA947099CD
79AD7038FC928DF609F10DDA2DF77F70 A4775563371641769910315B633945AA 8DEA25C7ED520D70B59C1B8C163C8167
E284AA4289A3FE6B3A8B57847C744909 49F850C82B4BE32147E67902C03E52F8 89E4B5DD3A31AE0BB7599851F7020301
0001 
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-algo.c:491:sc_asn1_decode_algorithm_id: called
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-algo.c:499:sc_asn1_decode_algorithm_id: decoded OID '1.2.840.113549.1.1.1'
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-algo.c:516:sc_asn1_decode_algorithm_id: returning with: 0 (Success)
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-pubkey.c:1366:sc_pkcs15_pubkey_from_spki_fields: DEE pk_alg.algorithm=0
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-pubkey.c:578:sc_pkcs15_decode_pubkey_rsa: called
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-pubkey.c:589:sc_pkcs15_decode_pubkey_rsa: returning with: 0 (Success)
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-pubkey.c:1413:sc_pkcs15_pubkey_from_spki_fields: returning with: 0 (Success)
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-algo.c:491:sc_asn1_decode_algorithm_id: called
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-algo.c:497:sc_asn1_decode_algorithm_id: ASN.1 parsing of algo ID failed: -1402 (Required ASN.1 object not found)
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-cert.c:104:parse_x509_cert: ASN.1 parsing of certificate failed: -1402 (Required ASN.1 object not found)
0x7fb1000a60c0 11:40:09.141 [pkcs15-tool] pkcs15-cert.c:392:sc_pkcs15_read_certificate: returning with: -1401 (Invalid ASN.1 object)
```

**Comment by z4yx** [comment]
I guess that opensc may mistakenly interpret the X.509 extension field as an algorithm identifier.

[ASN.1 decoding of my certificate](https://lapo.it/asn1js/#MIIDBDCCAeygAwIBAgIJAPC48VqYkLqMMA0GCSqGSIb3DQEBCwUAMBcxFTATBgNVBAMMDENlcnRBdFNsb3Q5YTAeFw0xOTEwMjYxMDIyNDBaFw0yMDEwMjUxMDIyNDBaMBcxFTATBgNVBAMMDENlcnRBdFNsb3Q5YTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANfenj2TCn0mlF-VX9x20vldozT8F8Knc3duyp3q-Rq-FdkLnTKNQbzmCmdeDWMSINJpGqGfPdfiHI10nZRO2euDUwDPYIm6FqD5snX58GXkUgszBU_sQsH0MZpBqV6j4aBfNLgIA1T_gtzhHmbbWCq8N3pShwBTmRQEcpocdGzk7IVXLxzM_clVexCPsnQ_tuSFU1CFXgK9VB0HE63lupRwmc15rXA4_JKN9gnxDdot939wpHdVYzcWQXaZEDFbYzlFqo3qJcftUg1wtZwbjBY8gWfihKpCiaP-azqLV4R8dEkJSfhQyCtL4yFH5nkCwD5S-Inktd06Ma4Lt1mYUfcCAwEAAaNTMFEwHQYDVR0OBBYEFP_Z6jyfBJbH-h5IZZquEWWC38r5MB8GA1UdIwQYMBaAFP_Z6jyfBJbH-h5IZZquEWWC38r5MA8GA1UdEwEB_wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAInf2I9LvVJE2QUp4zMdxbtspu28kCP7HyKws4Rv7dC7WbMQ8j5VZC28bmqO0yf_o64KkZFpX3d94YrVLvtqWHF_GEFo4bAuTPF6p9pcNZXKGGlpshOTOmUvvCP6MRmSpBflp4ZbAJ3Y-G9IUVxRLyNRP1xsTbnLXROqyQNoFX6zUprgmE5do64cgtYX8Wlv7abYZ7CgtdcBZey4vXvSsXyVV3zRNWbmjVJfvb7u4-DLmS-QKRFtFesAe-XSl2e6zGMICyZ8TPvgWP1enuCu8kdErB3cb31xgg4Zr6ZFO6hnRmyW3qrFYbKzhHTXRKBCA2dINGenLEe0ICWAv4LBcgg)

**Comment by dengert** [comment]
Can you rerun the  `pkcs15-tool` test again with OpenSC "DEBUG=9;" This will show the ASN1 parsing.  
 
I note that your cert does not have a keyUsage field, but does have a basic Constraints: critical CA:TRUE This may be the problem, as the PIV 9A was never expected to be used as a CA, and 
unknown critical extensions are to be treated as an error. This may be the problem.

Since the PIV does not store a public key as a separate object, `card-piv.c` reads the certificate to parses the certificate to get the public key from the SPKI. It looks like the public key is OK.

**Comment by dengert** [comment]
If your intent is to use the certificate as a CA, it must have a keyUsage with keyCertSign See:

https://tools.ietf.org/html/rfc5280#section-4.2.1.9

Without a keyUsage in a certificate, the PIV driver uses the NIST defined key usages for a key. See 
[PIV keyUsage for non goverment cards](https://github.com/OpenSC/OpenSC/issues/1835#issuecomment-546611741)

There is a way to use the OpenSC `piv-tool`  on Yubico devices to generate a key, save the pubkey to be used later  with OpenSSL libp11 engine to generate a certificate request, or self signed certificate and then load the certificate on the card, The Yubico-piv-tool might be able to do it in a multi step process too.

**Comment by dengert** [comment]
I believe your problem is fixed in the  0.20.0 release candidate rc3.

I loaded your certificate onto a Yubico 4  as 9E cert using `piv-tool`.  `pkcs15-tool --list-public-keys`  listed 4 public keys. This was built from github tag OpenSC-0.20.0-rc3.

The following equivalent debug trace `DEBUG = 3` shows new debug messages  Note the line `sc_pkcs15_read_certificate: returning with: 0 (Success)`.  In your debug output it never got this far. 

OID 1.2.840.113549.1.1.11 is "sha256WithRSAEncryption"

The `sc_pkcs15_get_extension: returning with: -1402 (Required ASN.1 object not found)` is where `pkcs15-piv.c` tries to get the `keyUsage` extension which is not present in your certificate. Using `DEBUG = 7` shows the calls to get the extension.)  

```
P:12441; T:0x140189840805760 06:28:50.041 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-cert.c:372:sc_pkcs15_read_certificate: called
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-pubkey.c:1339:sc_pkcs15_pubkey_from_spki_fields: sc_pkcs15_pubkey_from_spki_fields() called: 0x55d03642616d:290
300D06092A864886F70D010101050003 82010F003082010A0282010100D7DE9E 3D930A7D26945F955FDC76D2F95DA334
FC17C2A773776ECA9DEAF91ABE15D90B 9D328D41BCE60A675E0D631220D2691A A19F3DD7E21C8D749D944ED9EB835300
CF6089BA16A0F9B275F9F065E4520B33 054FEC42C1F4319A41A95EA3E1A05F34 B8080354FF82DCE11E66DB582ABC377A
52870053991404729A1C746CE4EC8557 2F1CCCFDC9557B108FB2743FB6E48553 50855E02BD541D0713ADE5BA947099CD
79AD7038FC928DF609F10DDA2DF77F70 A4775563371641769910315B633945AA 8DEA25C7ED520D70B59C1B8C163C8167
E284AA4289A3FE6B3A8B57847C744909 49F850C82B4BE32147E67902C03E52F8 89E4B5DD3A31AE0BB7599851F7020301
0001
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:487:sc_asn1_decode_algorithm_id: called
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:495:sc_asn1_decode_algorithm_id: decoded OID '1.2.840.113549.1.1.1'
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:512:sc_asn1_decode_algorithm_id: returning with: 0 (Success)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-pubkey.c:1376:sc_pkcs15_pubkey_from_spki_fields: DEE pk_alg.algorithm=0
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-pubkey.c:590:sc_pkcs15_decode_pubkey_rsa: called
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-pubkey.c:601:sc_pkcs15_decode_pubkey_rsa: returning with: 0 (Success)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-pubkey.c:1423:sc_pkcs15_pubkey_from_spki_fields: returning with: 0 (Success)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:487:sc_asn1_decode_algorithm_id: called
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:495:sc_asn1_decode_algorithm_id: decoded OID '1.2.840.113549.1.1.11'
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-algo.c:512:sc_asn1_decode_algorithm_id: returning with: 0 (Success)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-cert.c:399:sc_pkcs15_read_certificate: returning with: 0 (Success)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-cert.c:307:sc_pkcs15_get_extension: returning with: -1402 (Required ASN.1 object not found)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/pkcs15-cert.c:328:sc_pkcs15_get_bitstring_extension: Get extension error: -1402 (Required ASN.1 object not found)
P:12441; T:0x140189840805760 06:28:50.042 [pkcs15-tool] ../../../src/src/libopensc/card.c:1016:sc_card_ctl: called
```

**Comment by z4yx** [comment]
Thanks for the reply.

I also did some research to find out what caused the problem exactly. The cert generated by the latest yubico-piv-tool (or OpenSSL inside) contains a `NULL` tag after the `Signature Algorithm Identifier`, which results in the wrong signatureAlgorithm data retrieved by opensc. (062A864886F70D01010B050003 in log)

```
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1609:asn1_decode: Looking for 'signatureAlgorithm', tag 0x1000010
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1400:asn1_decode_entry: decoding 'signatureAlgorithm', raw data:062A864886F70D01010B050003
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] pkcs15-algo.c:491:sc_asn1_decode_algorithm_id: called
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1585:asn1_decode:  called, left=13, depth 1
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1609:asn1_decode: Looking for 'algorithm', tag 0x6
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1623:asn1_decode: 'algorithm' not present
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1628:asn1_decode: mandatory ASN.1 object 'algorithm' not found
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1638:asn1_decode: next tag: 06 2A 86 48 86 F7 0D 01 01 0B 
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] asn1.c:1640:asn1_decode: returning with: -1402 (Required ASN.1 object not found)
0x7f9e06c680c0 21:03:48.380 [pkcs15-tool] pkcs15-algo.c:497:sc_asn1_decode_algorithm_id: ASN.1 parsing of algo ID failed: -1402 (Required ASN.1 object not found)
```

So the workaround would be creating a certificate with older OpenSSL. Good to hear that the latest RC of opensc has fixed the bug, but it's hard to upgrade opensc on every computer I use.

**Comment by dengert** [comment]
After further review, I don't thing 0.20.0 fixed the problem because the problem is in the creation of the certificate with bad ASN.1  The cert posted in https://github.com/OpenSC/OpenSC/issues/1837#issue-512918950 is valid, and 
`openssl verify --verbose -CAfile orig.cert.pem orig.cert.pem` verifies it is self signed. 

And it looks like the "ASN.1 JaveScript" you posted fails at this point but does not say it found an error. 

A NULL tag after the Signature Algorithm Identifier is normal. 

The problem looks like the OID in  "062A864886F70D01010B050003" is incorrect, the OID is missing the length. it should be:  "06 **09** 2A 86 48 86 F7 0D 01 01 0B" followed by "05 00" the NULL is part  the  signatureAlgorithm.   The "30" is actually the sequence after and since the 09 is missing, the 30 is assumed to be the last byte of the   signatureAlgorithm

[RFC 5754 Page 7](https://tools.ietf.org/html/rfc5754#page-7) says:
'''
sha256WithRSAEncryption: 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 
                                             05 00
'''
I do't see how the 09 could be missing in your test. You could look at the opensc-debug.log were the cert is read from the card, to see if it has the 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00

`od -t x1 < orig.cert.der`
outputs:
0000760 03 01 01 ff **30 0d 06 09 2a 86 48 86 f7 0d 01 01**
0001000 **0b 05 00** 03 82 01 01 00 89 df d8 8f 4b bd 52 44
...

Could the `yubico-piv-tool -a import-certificate -s 9a` have a problem?

**Comment by z4yx** [comment]
Oh, you are right. It's not an OpenSC issue at all.

After analysis of the chaining APUDs, I found that my card responded to the GET RESPONSE command with extra bytes. For example(Le=255, however, 256 bytes returned):

```
Outgoing APDU (5 bytes):
00 C0 00 00 FF .....
0x7fbeaef39740 14:09:24.128 [pkcs15-tool] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7fbeaef39740 14:09:24.188 [pkcs15-tool] reader-pcsc.c:293:pcsc_transmit: 
Incoming APDU (258 bytes):
A3 E1 A0 5F 34 B8 08 03 54 FF 82 DC E1 1E 66 DB ..._4...T.....f.
58 2A BC 37 7A 52 87 00 53 99 14 04 72 9A 1C 74 X*.7zR..S...r..t
6C E4 EC 85 57 2F 1C CC FD C9 55 7B 10 8F B2 74 l...W/....U{...t
3F B6 E4 85 53 50 85 5E 02 BD 54 1D 07 13 AD E5 ?...SP.^..T.....
BA 94 70 99 CD 79 AD 70 38 FC 92 8D F6 09 F1 0D ..p..y.p8.......
DA 2D F7 7F 70 A4 77 55 63 37 16 41 76 99 10 31 .-..p.wUc7.Av..1
5B 63 39 45 AA 8D EA 25 C7 ED 52 0D 70 B5 9C 1B [c9E...%..R.p...
8C 16 3C 81 67 E2 84 AA 42 89 A3 FE 6B 3A 8B 57 ..<.g...B...k:.W
84 7C 74 49 09 49 F8 50 C8 2B 4B E3 21 47 E6 79 .|tI.I.P.+K.!G.y
02 C0 3E 52 F8 89 E4 B5 DD 3A 31 AE 0B B7 59 98 ..>R.....:1...Y.
51 F7 02 03 01 00 01 A3 53 30 51 30 1D 06 03 55 Q.......S0Q0...U
1D 0E 04 16 04 14 FF D9 EA 3C 9F 04 96 C7 FA 1E .........<......
48 65 9A AE 11 65 82 DF CA F9 30 1F 06 03 55 1D He...e....0...U.
23 04 18 30 16 80 14 FF D9 EA 3C 9F 04 96 C7 FA #..0......<.....
1E 48 65 9A AE 11 65 82 DF CA F9 30 0F 06 03 55 .He...e....0...U
1D 13 01 01 FF 04 05 30 03 01 01 FF 30 0D 06 09 .......0....0...
61 FF                                           a.
```
At last, some bytes were lost after chaining data combined togetther.

I didn't realize that before, because `yubico-piv-tool -a read-certificate` tolerants such behavior, and gives me the correct result.

Sorry to bother you.

**Comment by dengert** [comment]
I would still like to know where is the bug.

When you say: "my card responded to the GET RESPONSE command with extra bytes." Are you saying that you are developing another "PIV look-a-like" card or applet? 

If you are not developing a card or applet, is this a Yubico device or some other device? If so what version. 
A quick test of a Yubikey 4  version 04.02.06 returns 255 data + 2 status of 61FF
```
Outgoing APDU (5 bytes):
00 C0 00 00 FF .....
P:15467; T:0x140349560745856 14:48:19.010 [opensc-pkcs11] ../../../src/src/libopensc/reader-pcsc.c:216:pcsc_internal_transmit: called
P:15467; T:0x140349560745856 14:48:19.022 [opensc-pkcs11] ../../../src/src/libopensc/reader-pcsc.c:306:pcsc_transmit: 
Incoming APDU (257 bytes):
```

OpenSC should have caught the problem of too much data returned and consider it an error or handled it.  This would have been done in apdu.c that handles the incoming data.  But most cards would return 6100 indicating it as 256 or more bytes remaining.
in that case the outgoing APDU would have been 00 C0 00 00 00 to read the next 256 bytes.

**Comment by z4yx** [comment]
Yes, we are developing an open source alternative to Yubikey: https://github.com/canokeys/canokey-core  It currently runs on STM32 MCU.

The bug was in the GET RESPONSE handling, where the card may reply more data than expected(Le). The status code 61XX you mentioned is not a problem. We choose the same strategy as Yubikey, return 61FF. And OpenSC sends `00 C0 00 00 FF` on the next time, which is also correct.

**Comment by dengert** [comment]
While you are working on your PIV applet, could I ask you to have a look at the OpenSC `card-piv.c` driver. Many of the "PIV like" applets do not follow the NIST standards as closely as they should. The driver has a set of  `#define CI_*`  for [Card Issues](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L252) If you can make sure you do not have these issues that would be great. Lose of login state is a big issue.

Thanks.

**Comment by z4yx** [comment]
Of course, I want my applet to be compliant. And I'll check whether we have these issues.
