### ISSUE TITLE
openpgp: fixing key usage flags for slot 3 (S/MIME Usage)

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#1843]
### Problem Description

[Since a long time](https://github.com/OpenSC/OpenSC/commit/e34866f18819e05f6c89a50c9c3b69929887e580) it is possible to use OpenPGP Cards for S/MIME decryption. To enable this, it was necessary to [announce encryption capabilities for slot 3](https://github.com/OpenSC/OpenSC/blame/424ebf8ed13d804246ba0c8a5e2576009b3c3f7b/src/libopensc/pkcs15-openpgp.c#L98) although the card *does not* support decrypting with this slot. To overcome this, the user needs to [import the very same private key to slot 2](https://github.com/OpenSC/OpenSC/wiki/OpenPGP-card#pairs-of-key--certificate-from-p12-file) (encryption key) to the card. OpenSC/the card uses this slot instead of slot 3 for decryption. 

The certificate on the other hand is bound to slot 3 which is the reason why it was not possible to just use slot 2 in the first place. Furthermore, slot 2 can not authenticate (sign a message) so that both slots are needed.

To make the situation even more complicated: Newer cards (v3.3 and higher) are able to decrypt and authenticate with both slots, [so that this isn't needed on these cards anymore](https://github.com/OpenSC/OpenSC/pull/1446).

However, on old cards the `pkcs11-tool --test` fails, if there is not the same key in slot 2 and slot 3, because slot 3 is announcing decryption capabilities that need to have the key on slot 2. Thus, the automatic tests for CI and releases do fail if you do not know exactly what to do.

### Proposed Resolution
Find a solution to address both - older and newer cards. Or to put it in different words: find a cleaner solution than the current if possible. Furthermore, make the tests of travis reflect these specifics.

As said in #1835 this is an issue for future development, as I can not fix this right now. If anyone has a good idea right away, it is very much welcome :)

(idea: only set [key usage "encryption" for slot 3](https://github.com/OpenSC/OpenSC/blob/424ebf8ed13d804246ba0c8a5e2576009b3c3f7b/src/libopensc/pkcs15-openpgp.c#L98) if v3.3 card with MSE or slot 2==slot 3)

**Comment by frankmorgner** [comment]
For older cards, it should be easy to emulate/detect. Whenever slot 2 and 3 have the same key (can be detected via the same pubkey), only emulate a single key to the upper layers. Then differentiate the cases for decryption/authentication in the lower levels again to choose the correct slot.

However, I think we may just live with the current limitations for cards before OpenPGP 3.3 (as we did already), because 3.3 allows a simple clean solution without much hassle.

**Comment by frankmorgner** [comment]
if you plan to implement this and need further guidance, please re-open this issue
