### ISSUE TITLE
Too much readers on system (PKCS11, yubikey FIPS, Win10)

### ISSUE THREAD

**Issue by mti-sk** [OpenSC/OpenSC#1846]
### Problem Description
If there are more than four card readers in the system(win10), the pkcs11-tool command does not work with them.
using the pkcs11-tools --slots 8 -L command will not access the card. The only option is to disable other card readers in the system. If the reader is now required among the first four readers, then it is usable.

### Proposed Resolution
I suggest removing the restriction that is now on the first four readers, or checking the effectiveness of the slots parameter on the pkcs11-tool --slot 8 -L command

### Steps to reproduce
$opensc-tool.exe --list-readers
Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             AKS ifdh 0
1    Yes             AKS ifdh 1
2    Yes             AKS VR 0
3    Yes             Broadcom Corp Broadcom NFP 0
4    Yes             Broadcom Corp Contacted SmartCard 0
5    Yes             Broadcom Corp Contactless SmartCard 0
6    Yes             Rainbow Technologies iKeyVirtualReader 0
7    Yes             Rainbow Technologies iKeyVirtualReader 1
8    Yes             Yubico Yubikey 4 OTP+U2F+CCID 0

$pkcs11-tool.exe -L  (show only four empty slots, but on slot 8 is usable card)
Available slots:
Slot 0 (0x0): AKS ifdh 0 (empty)
Slot 1 (0x4): AKS ifdh 1 (empty)
Slot 2 (0x8): AKS VR 0 (empty)
Slot 3 (0xc): Broadcom Corp Broadcom NFP 0  (empty)

#After disable all other reader in device manager:
$pkcs11-tool.exe -L
Available slots:
Slot 0 (0x0): Rainbow Technologies iKeyVirtualReader 0  (empty)
Slot 1 (0x4): Rainbow Technologies iKeyVirtualReader 1 (empty)
Slot 2 (0x8): Yubico Yubikey 4 OTP+U2F+CCID 0
  token label        : my_key
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 5487cadbc1234965
  pin min/max        : 4/8

**Comment by frankmorgner** [comment]
If I'm not mistaken, we're using lists most of the time rather than arrays with static sizes.

can you show the output of `OPENSC_DEBUG=3 pkcs11-tool.exe -L` with all readers enabled?

**Comment by frankmorgner** [comment]
What's the *Rainbow Technologies iKeyVirtualReader*, by the way?

**Comment by mti-sk** [comment]
All other reader was instaled with Gemalto eToken 5110cc (Czech post )

**Comment by mti-sk** [comment]
I'm not sure howto use param OPENSC_DEBUG=3 on win10 command line...

**Comment by frankmorgner** [comment]
Oh, on Windows you need to use `set`:
```
set OPENSC_DEBUG=3
pkcs11-tool.exe -L
```

**Comment by dengert** [comment]
Looks like this is controlled by opensc.conf. See [opensc.conf.example.in](https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in#L986) and [misc.c](https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/misc.c#L459)


Also note Windoes has a limit too:
[limitation-of-10-smart-card-readers-in-windows-server-2012-r2-windows](https://support.microsoft.com/en-us/help/3144446/limitation-of-10-smart-card-readers-in-windows-server-2012-r2-windows)

**Comment by mti-sk** [comment]
Ok, 
Thank you very much.
these settings resolved my issue:  (now I see all reader on system)
app opensc-pkcs11 {
	pkcs11 {
	max_virtual_slots = 40;
	 slots_per_card = 4;
	}
}
But now I have new Issue: 
# Yubikey is known to have the PIV applet and the OpenPGP applet. OpenSC
# can handle both to access keys and certificates, but only one at a time.

**Comment by dengert** [comment]
Please open "Yubikey is known to have the PIV applet and the OpenPGP applet. OpenSC
can handle both to access keys and certificates, but only one at a time."  as a separate issue.
