### ISSUE TITLE
opensc version: 0.19.0.7 PC/SC reader stops properly working

### ISSUE THREAD

**Issue by Counter178** [OpenSC/OpenSC#1847]
PC used: IBM T490s
In the log, there is used smart card reader (Microsoft UICC ISO Reader 447e143c 0) but actually it is built-in Fibocom L850-GL (by device manager info) 4g modem (where there is sim card).

Upon disabling everything works just fine in device

but enabling makes it crash:
Enable PCSC11# loader in Mozilla Firefox 69.0.2 (x64 en-US) (69.0.2)
Id card (idemia) isn't in the reader
Trying to log in to portal https://www.eesti.ee/en/

Attaching debug logs.
[joeorg_debug.zip](https://github.com/OpenSC/OpenSC/files/3809316/joeorg_debug.zip)

**Comment by frankmorgner** [comment]
The code has changed quite a lot, please try if the problem persists with https://github.com/OpenSC/OpenSC/releases/tag/OpenSC-0.20.0-rc3

Microsoft UICC ISO Reader doesn't respond to any of the APDUs, this seems to cause the problem. If you can reproduce the problem with `pkcs11-tool --test --login`, you could produce a more meaningful backtrace of the problem.
