### ISSUE TITLE
Yubikey 5 is not supported in OpenPGP mode

### ISSUE THREAD

**Issue by ya-isakov** [OpenSC/OpenSC#1850]
### Problem Description
I'm trying to use Yubikey 5 NFC with OpenPGP driver in OpenSC, but `pkcs15-tool --list-keys` shows `PKCS#15 binding failed: Unsupported card`

### Proposed Resolution
Fix this problem :)

### Steps to reproduce

1. Switch to OpenPGP mode:
> card_atr 3b:fd:13:00:00:81:31:fe:15:80:73:c0:21:c0:57:59:75:62:69:4b:65:79:40 {
>                 name = "Yubikey 5";
>                 # Select the PKI applet to use ("PIV-II" or "openpgp")
>                 driver = "openpgp";
>                 # Recover from other applications accessing a different applet
>                 flags = "keep_alive";
> }

2. Run `pkcs15-tool --list-keys`

### Logs
Here are two logs, first was captured while trying to use smartcard features in XCA, and second one is when I'm run `pkcs15-tool -k`
https://gist.github.com/ya-isakov/21e798bb4020e4708f637dcb5f5bffb3

My opinion that pkcs15-openpgp detection failed because of this line in logs:
`pkcs15-openpgp.c:262:sc_pkcs15emu_openpgp_init: finger print bytes have unexpected length (expected 60, got 70)`

P.S. The problem is the same on both OpenSC 0.19 and 0.20rc3. Provided logs are from 0.20rc3

**Comment by Jakuje** [comment]
The log says also:
```
card.c:387:sc_connect_card: card info name:'OpenPGP card v3.4 (0006 11333535)', type:9003, flags:0x4, max_send/recv_size:65535/65536
```
But as far as I know, only the 3.3 specification is (partially implemented). The version 3.4 is very new (the only link I found):

https://github.com/Nitrokey/openpgp-card/blob/master/OpenPGP%20Card%20Specification%203.4.pdf

Reading through that, shows that this should really return strictly 60 bytes (20 bytes for each key) and so opensc does not know how to handle this response.

Reading actually the APDUs, the tag and length representing this file looks like this:

C5 50

Which would be `80` in decimal, meaning that we can cover 4 keys here (there is hard limit of 70 bytes in the code). But that does not change it is not following the specification.

It can be worked around with this simple patch which should let you progress with using the card, but other things might break later:

```
diff --git a/src/libopensc/pkcs15-openpgp.c b/src/libopensc/pkcs15-openpgp.c
index c506809e..28b2b70f 100644
--- a/src/libopensc/pkcs15-openpgp.c
+++ b/src/libopensc/pkcs15-openpgp.c
@@ -166,7 +166,7 @@ sc_pkcs15emu_openpgp_init(sc_pkcs15_card_t *p15card)
 	sc_context_t	*ctx = card->ctx;
 	char		string[256];
 	u8		c4data[10];
-	u8		c5data[70];
+	u8		c5data[100];
 	int		r, i;
 	const pgp_pin_cfg_t *pin_cfg = (card->type == SC_CARD_TYPE_OPENPGP_V1)
 	                               ? pin_cfg_v1 : pin_cfg_v2;
@@ -257,7 +257,7 @@ sc_pkcs15emu_openpgp_init(sc_pkcs15_card_t *p15card)
 	 */
 	if ((r = read_file(card, "006E:0073:00C5", c5data, sizeof(c5data))) < 0)
 		goto failed;
-	if (r != 60) {
+	if (r < 60) {
 		sc_log(ctx, 
 			"finger print bytes have unexpected length (expected 60, got %d)\n", r);
 		return SC_ERROR_OBJECT_NOT_VALID;
```

**Comment by ya-isakov** [comment]
Yeah, it worked, but new issues appeared :) Interesting thing that GnuPG supports fingerprint more than 60 bytes for more than 15 years :) And this check had a nice TODO... https://github.com/gpg/gnupg/commit/9f9a18c011cba01c043a50b326b767e19b07019d#diff-dddf176a37f31b93434f905ef4eeca2aL809
