### ISSUE TITLE
Hyperlinks does not have content

### ISSUE THREAD

**Issue by amitkumar50** [OpenSC/OpenSC#1855]
### Problem Description
https://github.com/OpenSC/openct/wiki/Resources,-Links

1. defines the PC/SC standard that is used on windows, but
thanks to PC/SC-Lite software also on Linux, Mac OS X and BSD. 
You can download ->http://www.pcscworkgroup.com/specifications/overview.php
Oops! That page can’t be found.

2.  The Multifunctioanal Card Terminal specification suite includes CT-API and
it’s co-specification CT-BCS. The whole suite is available for download
in english->http://www.teletrust.de/publikat.asp?id=41220&Sprache=E_&HomePG=0
Redirects to French

3. The M.U.S.C.L.E.->http://www.linuxnet.com/
Page not found

**Comment by Jakuje** [comment]
Thank you for the report. It is a wiki so anyone can update the links if they got broken. The opensc has almost 20 years of history [1], and by that time, websites and links come and go.

I think this is a nice first issue to handle for somebody interested in contributing to OpenSC.

[1] https://www.openhub.net/p/open_sc

**Comment by marschap** [comment]
I took the time to update the links and fix a few typos on that page.
From my pointof view, the issue can be closed.

**Comment by Jakuje** [comment]
Thank you for help. It looks good to me now.

**Comment by frankmorgner** [comment]
thanks
