### ISSUE TITLE
Error signing PDF with latest portuguese eID cards

### ISSUE THREAD

**Issue by AdriaoNeves** [OpenSC/OpenSC#1858]
Using OpenSC-0.20.0-rc3 to sign a PDF file returns the error "RSA key must be at most 2048 bits" when using the latest portuguese eID card (citizen card). This only happens with the latest cards, older cards can sign with no issues.

I think this issue is related to the fact portuguese eID cards from 2019 are now using a 3072 bits RSA key, but  card-gemsafeV1.c only supports up to 2048:

`	_sc_card_add_rsa_alg(card,  512, flags, 0);
	_sc_card_add_rsa_alg(card,  768, flags, 0);
	_sc_card_add_rsa_alg(card, 1024, flags, 0);
	_sc_card_add_rsa_alg(card, 2048, flags, 0);`

Maybe related with:
#1764 
#1776

**Comment by Jakuje** [comment]
Yes. Most probably there is just the missing definition for the new key size. What driver is your card using? Can you share debug log?

**Comment by AdriaoNeves** [comment]
Thank you for answering.
It's using opensc-pkcs11.dll, unfortunately I can't compile openSC so I don't have a debug log.

**Comment by Jakuje** [comment]
I think you do not need to recompile OpenSC to get debug log. Only thing needed is the environment variable or modification of configuration file. See 

https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by AdriaoNeves** [comment]
Meanwhile, I setup a Visual Studio environment and compiled OpenSC for Windows.
Before compiling, I added the following code to file card-gemsafeV1.c:
`_sc_card_add_rsa_alg(card, 3072, flags, 0);
    _sc_card_add_rsa_alg(card, 4096, flags, 0);`
After that, it was possible to sign a PDF file with no error.

**Comment by Jakuje** [comment]
Nice. Do you want to submit a pull request? I think this is worth getting also to the 0.20.0 release.

**Comment by AdriaoNeves** [comment]
Done, thank you :)
