### ISSUE TITLE
PKCS #11 3.0 in OpenSC

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#1860]
In regards of #1854, I would like to bump version of PKCS #11 library to 3.0 and implement the new required interfaces in coming months.

The public review drafts are already available on OASIS website and I assume there will be no significant changes before the final version:

https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/pkcs11-base-v3.0.html

So far, these are my thoughts about advantages of 3.0:
 * Support for new key types (ed25519 -- see #1854)
 * It is backward compatible -- new functions are available through `C_GetInterfaceList` and `C_GetInterface`
 * Profile objects can resolve the issues with NSS and its handling of OpenSC as non-friendly by announcing the `CKP_PUBLIC_CERTIFICATES_TOKEN` profile (from https://docs.oasis-open.org/pkcs11/pkcs11-profiles/v3.0/pkcs11-profiles-v3.0.html )
 * SHA3 support
 
I will probably go through the draft and try to create issues for particular tasks if it will be easy to separate them so anyone can help. I would probably like to create it as a project, but it looks like I do not have appropriate permissions to do that.

Any thoughts?

**Comment by frankmorgner** [comment]
Although we're currently often using 2.4 as reference for PKCS#11, we're announcing compatibility with 2.20 only:
https://github.com/OpenSC/OpenSC/blob/ee1c8073c2ecd0d7644d64ef3f2a2be4b5752c6e/src/pkcs11/pkcs11-global.c#L408-L409

I'm not sure what's the implication in terms of backward compatibility...

**Comment by Jakuje** [comment]
I think this is mostly done now. We might need some implementation of the function stubs, we might bring more algorithms as needed, but the base is in place.
