### ISSUE TITLE
macOS: OpenSC not completelty removed after uninstall

### ISSUE THREAD

**Issue by joegoerlich** [OpenSC/OpenSC#1862]
### Problem Description

Uninstalled OpenSC using the uninstaller app on macOS catalina, but some fragments seem to be left over.

### Steps to reproduce

Run OpenSC uninstaller.app using sudo. Rebooted the Macbook Pro.

Verification

```
$ pluginkit -vv -m -p com.apple.ctk-tokens
     com.apple.CryptoTokenKit.setoken(1.0)
	            Path = /System/Library/Frameworks/CryptoTokenKit.framework/PlugIns/setoken.appex
	            UUID = 860EB069-15EF-472A-B21A-AE3811379906
	       Timestamp = 2019-11-20 16:42:21 +0000
	             SDK = com.apple.ctk-tokens
	    Display Name = Secure Enclave Private Key Storage
	      Short Name = setoken

     com.apple.CryptoTokenKit.pivtoken(1.0)
	            Path = /System/Library/Frameworks/CryptoTokenKit.framework/PlugIns/pivtoken.appex
	            UUID = 65E1FA9B-8B10-40B9-8D8F-1DBA343887C4
	       Timestamp = 2019-11-20 16:42:21 +0000
	             SDK = com.apple.ctk-tokens
	    Display Name = Personal Identity Verification token driver
	      Short Name = pivtoken

 (2 plug-ins)
```
Looks good though.

```
$ security list-smartcards    
org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344
```
Uhhh, whats that?! 

```
$ system_profiler SPSmartCardsDataType
SmartCards:

    Readers:

    Reader Drivers:

      #01: org.debian.alioth.pcsclite.smartcardccid:1.4.31 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
      #02: com.scmmicro.drivers.scmccid:(null) (/usr/local/libexec/SmartCardServices/drivers/scmccid.bundle)

    Tokend Drivers:

    SmartCard Drivers:

      #01: com.apple.CryptoTokenKit.pivtoken:1.0 (/System/Library/Frameworks/CryptoTokenKit.framework/PlugIns/pivtoken.appex)

    Available SmartCards (keychain):

        com.apple.setoken:

        com.apple.setoken:aks:

    Available SmartCards (token):

        com.apple.setoken:

        com.apple.setoken:aks:

```
There is no smart card physically connected, not even a reader.

```
$ security export-smartcard           

==== private key #1
	crtr : 0
	esiz : 0
	decr : 1
	persistref : <>
	atag : ""
	kcls : 1
	agrp : "com.apple.token"
	pdmn : "dk"
	bsiz : 2.048
	type : 42
	klbl : <b7 1b 09 53 0a 87 1d da 86 08 2f e4 20 4d 31 76 a0 f4 fa c1>
	edat : 2001-01-01 00:00:00 +0000
	sign : 1
	mdat : 2019-11-20 16:00:50 +0000
	drve : 0
	labl : "Auth 20.02.18 08:05:59 - 20.02.21 (My Name replaced)"
	sync : 0
	musr : <>
	sha1 : <7d 94 d5 3d 45 12 92 d6 51 d4 31 b4 73 71 ad a1 15 9c 21 ae>
	cdat : 2019-11-20 16:00:50 +0000
	tkid : "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344"
	sdat : 2001-01-01 00:00:00 +0000
	tomb : 0
	priv : 1
	accc : constraints: {
			od : <01>,
			osgn : <01>
		}
		protection: {
			tkid : "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344"
		}
	unwp : 1
====

==== private key #2
	crtr : 0
	esiz : 0
	decr : 1
	persistref : <>
	atag : ""
	kcls : 1
	agrp : "com.apple.token"
	pdmn : "dk"
	bsiz : 2.048
	type : 42
	klbl : <b0 44 81 e4 bf e9 5d 27 ed b8 92 fa 19 02 7f 85 5c 6e 37 37>
	edat : 2001-01-01 00:00:00 +0000
	sign : 1
	mdat : 2019-11-20 16:00:50 +0000
	drve : 0
	labl : "Encr 20.02.18 09:06:00 - 20.02.21 (My Name replaced)"
	sync : 0
	musr : <>
	sha1 : <c3 71 81 4b da 20 95 d1 4e 9b e9 ba 4e 52 0c 78 56 e4 59 7f>
	cdat : 2019-11-20 16:00:50 +0000
	tkid : "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344"
	sdat : 2001-01-01 00:00:00 +0000
	tomb : 0
	priv : 1
	accc : constraints: {
			od : <01>,
			osgn : <01>
		}
		protection: {
			tkid : "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344"
		}
	unwp : 1
====
```

Still org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken listed here?!

Where does that "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344" come from or belong to? Any idea how to clean that up?

**Comment by frankmorgner** [comment]
Which file, do you think is left over? I think you're seeing cached data. insert a smart card and let apple do its house keeping.

**Comment by joegoerlich** [comment]
Is there a way to force the housekeeping? Inserting a smart card has no effect as well as reboot/shutdown doesn't change anything...

**Comment by frankmorgner** [comment]
looks like, I've forgot OpenSCToken, see https://github.com/OpenSC/OpenSC/pull/1868 for a fix. You may also manually move OpenSCTokenApp remove from *Applications* to the *Trash*.

**Comment by joegoerlich** [comment]
I removed the files as listed in the changelog and rebooted, but no changes.

I created a fresh user account and tested with my smart card and everything was fine. so i asume the issue is user related.
After searching a while i found a fragment for my user here:

```
$ defaults read ~/Library/Preferences/com.apple.security.ctkd-db.plist
{
    classes -string '"com.apple.pivtoken" = "65E1FA9B-8B10-40B9-8D8F-1DBA343887C4";
        "com.apple.setoken" = "860EB069-15EF-472A-B21A-AE3811379906";'
        "org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken" = "53029251-FD1E-467D-A326-04BF0CD32249";
    };
    tokens =     {
        "com.apple.setoken" = {length = 428, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000132 };
        "com.apple.setoken:aks" = {length = 432, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000136 };
    };
}
```

I deleted the ~/Library/Preferences/com.apple.security.ctkd-db.plist and rebooted so it was recreated without `org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken`.
But `security list-smartcards` is still listing `org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:5A3030315357335536345A4755574344`.

I'm still looking how to get rid of it.

**Comment by tstevens** [comment]
@joegoerlich I seem to be having the exact same issues... Did you ever figure out a solution to finally get rid of it?

**Comment by joegoerlich** [comment]
@tstevens still have no solution. Just found out that if i create a new user this user doesn't have that issue. So the issue seems to be account related.

**Comment by frankmorgner** [comment]
What https://github.com/OpenSC/OpenSC/commit/78548a93944a495215bd85c8bd583c0713a504ae does is, it additionally deletes the token *driver*. After this, the driver should still be listed in
```
pluginkit -v -m -D -i org.opensc-project.mac.opensctoken.OpenSCTokenApp
```
However, if the system tries to acces the non-existent driver, it should automatically clean up the reference. Could you check if that's the case? If it isn't, you could manually delete it by:
```
pluginkit -r -i org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken
```
please also check whether the token driver is still running in RAM even though it has been deleted from disk:
```
ps xa |grep -i opensc
```
And last but not least, I'm not familiar with Apple's house keeping related to the user's certificates. Those may be loaded into some user related cache that's causing the persitency. To some extent that's reasonable, because the token doesn't get invalidated only because the driver is installed. Hence, for example, a token should still stay paired with the user account after deletion of the driver.

**Comment by tstevens** [comment]
@joegoerlich found a fix and posted the steps in frankmorgner/OpenSCToken#38

**Comment by joegoerlich** [comment]
@tstevens thanks for the hint. In the meantime i upgraded to Big Sur and it seems during the upgrade the keychains have been cleaned up.
