### ISSUE TITLE
Not getting a PIN prompt on macOS 10.15.1 in Chrome

### ISSUE THREAD

**Issue by jmastr** [OpenSC/OpenSC#1865]
### Problem Description

OS: macOS 10.15.1
OpenSC: 0.20.0-rc3
Chrome: Version 78.0.3904.108 (Official Build) (64-bit)

I am trying to auth against an SSL Client Cert protected URL. I am getting the prompt to select the certificate, but I am not prompted for the PIN, but I get the error: `ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED`

### Steps to reproduce

The URL is in cooperate network :|

### Logs

Chrome logs:
```
[50210:145415:1122/170406.094279:ERROR:ssl_platform_key_mac.cc(311)] Code: -2 Domain: CryptoTokenKit Desc: The operation couldn’t be completed. (CryptoTokenKit error -2.)
```

Console logs:
```
TKClientToken operation failed but did not fill any error, substituting TKErrorCodeCommunicationError
```

Any ideas why this might be happening? Help is much appreciated.

**Comment by jmastr** [comment]
Most probably related to #1869

**Comment by frankmorgner** [comment]
Can you create an OpenSC debug log? see https://github.com/frankmorgner/OpenSCToken#configuring-opensctoken

**Comment by frankmorgner** [comment]
TCOS hasn't been touched for a while, there are some known limitations. Maybe you're hitting one of those...

**Comment by frankmorgner** [comment]
I've just tested PKCS#11 in firefox and CTK in Safari (which is also used in Chrome) for sc-hsm. This works as expected...

**Comment by jmastr** [comment]
> Can you create an OpenSC debug log? see https://github.com/frankmorgner/OpenSCToken#configuring-opensctoken

https://gist.github.com/jmastr/70eea75add9f609f636e28d8761d5dfe

**Comment by frankmorgner** [comment]
The log indicates a problem with the actual card rather than, for example, a macOS- or Chrome-based problem. I don't have much experience with TCOS, but let's continue the discussion at #1869...
