### ISSUE TITLE
Decryption doesn't work on Windows GIDs devices

### ISSUE THREAD

**Issue by el-oso** [OpenSC/OpenSC#1866]
### Problem Description

Windows 10 has a functionality in which you can create a [virtual smart card ](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview) on a TPM. I'm trying to use OpenSC to decrypt  using a RSA key over PKCS11. However, when I try to decrypt I get a  CKR_GENERAL_ERROR (Card command failed).

I already tried over 3 different computers with 3 different TPMs.

### Proposed Resolution

Should be able to use HW descryption

- Most likely an incorrect configuration option is the problem.
- Otherwise there is a problem with the driver.

### Steps to reproduce

Prerequisites: 
- Windows 10
- a TPM 

1) Create a VSC using the following command:
tpmvscmgr create /name "TestVSC" /pin default /AdminKey default /puk default /attestation AIK_AND_CERT  /generate

The default pins are all '12345678'

2) Generate a keypair. I used [pkcs11admin](http://pkcs11admin.net/) to generate it.
3) Run: pkcs11-tool.exe -t --login --login-type user --pin 12345678

Output below:
```
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 ()
error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

### Logs

For a run using python-pkcs11 see this [opensc-debug.txt ](https://gist.github.com/el-oso/1c3c0251ebb8664fee8a91497d606517)

[opensc.conf.txt](https://github.com/OpenSC/OpenSC/files/3884048/opensc.conf.txt)

**Comment by dengert** [comment]
card-gids.c uses buffers  of size SC_MAX_EXT_APDU_BUFFER_SIZE = 65538. But the code but does not set `SC_CARD_CAP_APDU_EXT` and looks like and max_send_size is set to 255:
`P:2076; T:2064 2019-11-24 20:32:50.710 card info name:'GIDS Smart Card', type:30001, flags:0x0, max_send/recv_size:255/256`

So Decipher uses chaining with short APDUs: 
```
P:2076; T:2064 2019-11-24 20:32:51.231 [opensc-pkcs11] iso7816.c:972:iso7816_decipher: called
...
Outgoing APDU (260 bytes):
10 2A 80 86 FF 00 90 BA 6B C3 DD 0B F2 31 B5 F3
...
Incoming APDU (2 bytes):
90 00 
...
Outgoing APDU (8 bytes):
00 2A 80 86 02 2C AD 00
...
Incoming APDU (2 bytes):
65 00
```
65 00 is "State of non-volatile memory changed" "No information given" This is a strange status which may mean the card does not like the chaining, but Microsoft docs say: "11.5.1 GIDS Commands Supporting Command Chaining"  and "14.3 Sending More than 255 bytes to the ICC" This may be a limitation of the TPM, or a configuration error in the opensc.conf. 

You could try adding to the `card-grids.c`  function `gids_init` 
`card->caps = SC_CARD_CAP_APDU_EXT;`

**Comment by el-oso** [comment]
Hi Doug,

At first I thought that it was a limitation of the TPM too, but as I mentioned I tested on other 2 systems with different TPM chips, so I think that I ruled that one out.

Thanks for the suggestion. Currently I'm using the Windows binary from the website. I will have to setup a build environment to test your suggestion. I will report back as soon as I have it.

However, you mentioned a possible configuration error in opensc.conf, I also attached my conf file in the post. My guess is that it needs some extra arguments, but which ones is really not clear to me.
Do you have any suggestion on that front?

**Comment by dengert** [comment]
For what looks like a simple change, you can submit a PR to get  binaries.  For example look at #1848 The submission runs the Appvoyer Checks and under the "details" you will see "JOBS" . Click on one like [VSVER=12 ... X64](https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/28743424/job/t1wn1liei3db9f8o)
Then click on "Artifacts" where you will find the msi files.

(I did setup an environment for #1848, which took 2 weeks and I never got it to use openpace, but it was enough to test what I needed untill I submitted a PR.)  

There may be other issues with a TPM, but you could start a PR with this: 
```
diff --git a/src/libopensc/card-gids.c b/src/libopensc/card-gids.c
index 27576f99..fd0ab392 100644
--- a/src/libopensc/card-gids.c
+++ b/src/libopensc/card-gids.c
@@ -642,6 +642,8 @@ static int gids_init(sc_card_t * card)
        data->cmapfilesize = sizeof(data->cmapfile);
        data->masterfilesize = sizeof(data->masterfile);
 
+       card->caps = SC_CARD_CAP_APDU_EXT;
+
        /* supported RSA keys and how padding is done */
        flags = SC_ALGORITHM_RSA_PAD_PKCS1 | SC_ALGORITHM_RSA_HASH_NONE | SC_ALGORITHM_ONBOARD_KEY_GEN | SC_ALGORITHM_RSA_RAW;
        /* fix me: add other algorithms when the gids specification will tell how to extract the algo id from the FCP */
```

**Comment by dengert** [comment]
You might get around the problem with opensc.conf changes but in  `card.c` `sc_get_max_send_size` looks like it expects SC_CARD_CAP_APDU_EXT  to use extended APDUs anyway and MS says it must support extended APDUs and/or chaining.

**Comment by el-oso** [comment]
WOW! I didn't know about Appvoyer. It's quite useful, thanks for the hint!

I forked OpenSC and added the line that you mentioned. However, the problem persists. 
To be honest I'm not sure that the build from Appvoyer is generating the msi using the changes.

I will try to debug and play with the settings from opensc.conf and report back.

**Comment by dengert** [comment]
This may not be a chaining problem, but a problem of setting the "PI" in the "(Pl || cryptogram)" as defined [gids.docx](http://download.microsoft.com/download/3/0/2/3027d574-c433-412a-a8b6-5e0a75d5b237/gids.docx)  section "12.11.3 P1-P2 Parameters"  The document does not define what is acceptable.  ISO-7816-4-2013  calls this "PCI" "The Padding Indicator Byte" or "Padding-content indicator byte"  and "Table 52" indicates it values.  00- No further indicator. 
But [gids.docx](http://download.microsoft.com/download/3/0/2/3027d574-c433-412a-a8b6-5e0a75d5b237/gids.docx) does not define the values. 

This may be a [TPM](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf)  issue. It says in "14.3.1 General Description"  "It will then validate the padding
according to the selected scheme"  But this could then be a problem of passing in to the TPM module what is the the padding scheme.  Could be related to Microsoft issues with extending CAPI to handle SHA256. To verify this, try encrypting something using SHA1 and see if decrypt works.  

OpenSC by default sets it to "00" in  `iso7816.c` `iso7816_decipher`. Some other cards use the propriety values "80-8E". 


If the above is not the problem:
I see you forked OpenSC and added the change and pushed to your repos. But I don't see where you submitted a PR. As far as I know, Appvoyer is only run when a PR is submitted or changed.  Did you manage to build OpenSC using some other method?  

If the change was made, I would have expected see the lines I sited above:
```
P:2076; T:2064 2019-11-24 20:32:50.710 card info name:'GIDS Smart Card', type:30001, flags:0x0, max_send/recv_size:255/256
10 2A 80 86 FF 00 90 BA 6B C3 DD 0B F2 31 B5 F3
```
look something like:
```
 P:2076; T:2064 2019-11-24 20:32:50.710 card info name:'GIDS Smart Card', type:30001, flags:0x0, max_send/recv_size:65535/65536
00 2A 80 86 00 01 00 00 90 BA 6B C3 DD 0B F2 31 B5 F3
```

**Comment by dengert** [comment]
@el-oso Does #1873 fix the decryption problem? 

@vletoux can you comment on this fix. Is it good enough? [gids.docx](http://download.microsoft.com/download/3/0/2/3027d574-c433-412a-a8b6-5e0a75d5b237/gids.docx) says both extended APDUs and chaining must be supported. And  also says the EF.ATR  has  "Card capabilities data byte 3 ->Miscellaneous" must be "0xCC" i.e supporting both.  

But it appears the [virtual-smart-cards](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-overview) does not support chaining. (Microsoft or TPM bug?)

Does card-gids.c need to read the EF.ATR and set the Extended and chaining flags?  
Or is it OK to always set `SC_CARD_CAP_APDU_EXT` The one situation I could see would be using a real card in a reader which does not support extended, or where T=0 is being used. (The solution would be to get a reader that supports extended.) 

Personally I thing this fix is good enough but want your comments.

**Comment by vletoux** [comment]
Last time I tested (1-2 years ago) it was working with the virtual smart card.

It's not that simple because if I remember correctly some real readers force APDU chaining.
Example: the shared VMWare smart card reader.
Most of the GIDS smart card (that I designed based on existing javacard) does not support extended APDU.
The MS driver does support both chained APDU & extended APDU.

I think we may use the DF FCI to differenciate the cards.
See DF FCI here
https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/windows-inbox-smart-card-minidriver
And my implementation here:
https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L143

**Comment by dengert** [comment]
@vletoux, Thanks for the comments that Virtual Smart Card supports chaining.  Can you explain the APDU sequence in https://github.com/OpenSC/OpenSC/issues/1866#issuecomment-557971943 Why would it it fail with "65 00"?

Could this be a SHA-1 vs SHA-256 digestinfo problem?
@el-oso  can you try a decryption using SHA-1 for the digest when encrypting? 

@el-oso, you said you tried multiple TPMs? What versions are these?  

(I do not have any TPMs in any of my machines to try any of these tests.)

**Comment by el-oso** [comment]
I tested in one of my systems and it seems to be getting along further.

```
P:2296; T:10500 2019-11-28 07:00:31.093 [opensc-pkcs11] card info name:'GIDS Smart Card', type:30001, flags:0x0, max_send/recv_size:65535/65536
```
However, the command is still failing (see new log file). I thought that it was from my implementation side, but pkscs11-tool is also giving an error. Later I will test on the other two.

@vletoux  Thanks for the link to the implementation, will take a look.
@dengert All of my TPMs are version 2.0, from 2 manufacturers.

[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/3900139/opensc-debug.txt)

**Comment by vletoux** [comment]
If that can help I designed APDUTrace (https://www.mysmartlogon.com/knowledge-base/trace-apdu-on-windows/ and https://www.mysmartlogon.com/download/#APDUTrace) so see the real operations made by the system (and especially debug the VMWare shared smart card reader).

You can use it to compare the virtual smart card APDU, for example when running certutil -scinfo

**Comment by dengert** [comment]
@el-oso the last debug log shows:

```
Outgoing APDU (11 bytes):
00 22 41 B8 06 80 01 47 84 01 81  (set security env) which looks correct to me)
Incoming APDU (2 bytes):
90 00
...
Outgoing APDU (266 bytes):
00 2A 80 86 00 01 01 00 4D 27 06 4F F9 73 7D 52 
Incoming APDU (2 bytes):
65 00
```
This is an extended APDU (Lc is 3 bytes 00, 01, 01) to send 257 bytes of data. But it also gets a "6500" status, the same as with chaining. So the issue may not be the extended or chaining as it has to support at least one of these. The 6500 may be for some other reason. 

Could this be an issue with key usage being enforced on the TPM? 
You said you created a key pair using pkcs11admin. I am not familiar with it and wonder if it set
some restrictions on the key usage. Do you know what PKCS\#11 module it called?
Do you have a SPY trace of the generation?  It might show show what is doing. 

I found I have a Windows 10 ASUS laptop with a TPM 2.0. I will see if I can get it to do something next week. Will have a look at APDUTrace too.

**Comment by vletoux** [comment]
If I remember correctly there is no way the GIDS card send 257 (not 256) bytes of data.
Maybe the common problem  if the public key starts with 0x80 (you know, signed big num) that need to be prefixed.

Does recreating another public key (aka remove this one) fixes the problem ?

**Comment by dengert** [comment]
Good point. It may be a bad public and/or private key. May also be a problem with pkcs11-tool. A SPY trace might also show something. 

But with the proposed fix to set SC_CARD_CAP_APDU_EXT it will send 257 bytes. (But based on your comment, the  fix is a bad idea as some cards do not support extended. So going back to chaining,
255 are sent first then last 2 are sent.)  But the crypto operation fails in both cases. 

The GIDS specs talk about the ""PI" in the "(Pl || cryptogram)"  ISO-7816-4-2013 calls this "PCI" "The Padding Indicator Byte" or "Padding-content indicator byte" and "Table 52" indicates it values.  a value of 00 is  No further indicator.
`card-gids.c` uses the `iso_ops->decipher` in `iso7816.c` which does: `sbuf[0] = 0; /* padding indicator byte, 0x00 = No further indication */`

I would still like to see how the key pair was created and if it has some extra attributes. 

`minidriver.c` CardSignData` has this:  `/*revert data only for RSA (Microsoft uses the big endian version while everyone is using little endian*/` is this somehow related?

**Comment by dengert** [comment]
@el-oso  you said you ran: `tpmvscmgr create /name "TestVSC" /pin default /AdminKey default /puk default /attestation AIK_AND_CERT /generate`

[virtual-smart-card-get-started](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started) leads to [virtual-smart-card-tpmvscmgr](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-tpmvscmgr)  which leads to [Attestation Identity Key](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/719b890d-62e6-4322-b9b1-1f34d11535b4#gt_bc38c2e6-0740-4556-a595-a8902f14c867) which says: 'The private portion of an AIK can never be revealed or used outside the TPM and can only be used inside the TPM for a limited set of operations. Furthermore, it can only be used for signing, and only for limited, TPM-defined operations.

Running `pkcs11-tool --test --login` may be trying to use the Attestation Key for a decipher operation, which should fail some how and this may be "6500". 

One way to test this is to run `pkcs11-tool -O --login` to see the objects and what attributes they may have. 

You said you had other keys ion the card. If you have a key you want to test, then use `pkcs15-tool` to read the pubkey or certificate, then use openssl to encrypt something with the pubkey or certificate, then use `pkcs15-crypt --decipher`

Or as a test modify pkcs11-tool to not stop if it gets CKR_GENERAL_ERROR but continue to run other tests to test the other keys you have on the card. 

Or delete the virtial smart card, and create a new one without the Attestation key.

If it appears the failure is trying to use the Atestation key, we can add some code to `card-gids.c` to handle '6500' and return some reasonable return code that can be handled by pkcs11.

**Comment by vletoux** [comment]
I tested it with my own virtual smart card.
`pkcs11-tool --test --login` is failing
`certutil -scinfo` is working
I'm looking at it to understand

**Comment by vletoux** [comment]
It also fails with a javacard with the [GIDS applet](https://github.com/vletoux/GidsApplet) installed on it

```
Using slot 0 with a present token (0x0)
Logging in to "UserPIN (GIDS card)".
Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (07cc67a2-e725-4f97-aa4c-6d1a00886da9)
error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

**Comment by vletoux** [comment]
For the GIDS card, the request fails because the 2 APDU doesn't start by the same P1 & P2
APDU1:
```
10 2A 9E 9A FF 00 8B 1F DA B0 CA 99 02 B9 72 9D .*............r.
49 2C 80 7E C5 99 D5 E9 80 B2 EA C9 CC 53 BF 67 I,.~.........S.g
D6 BF 14 D6 7E 2D DC 8E 66 83 EF 57 49 61 FF 69 ....~-..f..WIa.i
8F 61 CD D1 1E 9D 9C 16 72 72 E6 1D F0 84 4F 4A .a......rr....OJ
77 02 D7 E8 39 2C 53 CB C9 12 1E 33 74 9E 0C F4 w...9,S....3t...
D5 D4 9F D4 A4 59 7E 35 CF 32 22 F4 CC CF D3 90 .....Y~5.2".....
2D 48 D3 8F 75 E6 D9 1D 2A E5 C0 F7 2B 78 81 87 -H..u...*...+x..
44 0E 5F 50 00 D4 61 8D BE 7B 05 15 07 3B 33 82 D._P..a..{...;3.
1F 18 70 92 DA 64 54 CE B1 85 3E 69 15 F8 46 6A ..p..dT...>i..Fj
04 96 73 0E D9 16 2F 67 68 D4 F7 4A 4A D0 57 68 ..s.../gh..JJ.Wh
76 FA 16 BB 11 AD AE 24 88 79 FE 52 DB 25 43 E5 v......$.y.R.%C.
3C F4 45 D3 D8 28 CE 0B F5 C5 60 59 3D 97 27 8A <.E..(....`Y=.'.
59 76 2D D0 C2 C9 CD 68 D4 49 6A 79 25 08 61 40 Yv-....h.Ijy%.a@
14 B1 3B 6A A5 11 28 C1 8C D6 A9 0B 87 97 8C 2F ..;j..(......../
F1 15 1D 9A 95 C1 9B E1 C0 7E E9 A8 9A A7 86 C2 .........~......
B5 54 BF 9A E7 D9 23 D1 55 90 38 28 D1 D9 6C A1 .T....#.U.8(..l.
66 5E 4E E1

67 00

00 22 41 B6 06 80 01 57 84 01 81

68 84
```
It fails here:
https://github.com/vletoux/GidsApplet/blob/d83dd46374eb8a67737c7f251cd6d031086edc58/src/com/mysmartlogon/gidsApplet/TransmitManager.java#L141

**Comment by dengert** [comment]
I am not much of a java programmer, but it  looks like "67 00" is SW_WRONG_LENGTH so the "01 2A 9E 9A" is failing.  But the only reference to  SW_WRONG_LENGTH in the applet is in a comment. 
So who sent the "67 00".  (A reader that can not handle sending 255 bytes?)

The application looks like it is trying to recover from the "67 00" by starting a new operation with a MSE "22" command. 

But the applet still thinks it is in the middle of a chaining operation  because  Line 141 is returns SW_COMMAND_CHAINING_NOT_SUPPORTED "68 84"

**Comment by dengert** [comment]
I can reproduce the problem using an ASUS laptop with a builtin TPM 2.0, pkcs11-tool --test --login fails C_Sign operation to fails with chaining with status  "65 00" called from `card-gids.c` 
Certutil -v -scinfo says the key verifies.
 
New-SelfSignedCertificate says:

"If the private key is managed by a legacy CSP, the value is KeyExchange or Signature. If the key is managed by a Cryptography Next Generation (CNG) KSP, the value is None." 

Interesting problem, will look closer this week.

**Comment by vletoux** [comment]
The KeyExchange or Signature slot has nothing to do with the problem.
This is a legacy of CSP (which separated key type based on the former US regulation)

The wrong APDU is sent to the card. That's all.
APDUTrace does not work with MS Virtual smart card.
I've to use my test program and a good old breakpoint to see the real instruction sent to the card.

**Comment by vletoux** [comment]
Here is a right APDU sequence dialog.
Captured with certutil -scinfo & API Monitor (focus on SCardTransmit - capture started just after the pin prompt)
```
00 22 41 b8 06 80 01 47 84 01 81

90 00

00 2a 80 86 00 01 00 72 06 9c e9 c8 82 f5 48 5e 33 6b 19 7b fa e7 5f dc d4 80 52 e8 18 70 4b c0 c0 0a 7b 61 6e 3b da 8d 2d 72 6a e9 7e 70 e8 7c 92 89 09 26
7c 9e ad 97 7f 06 28 3b 26 78 27 4f f5 ff 32 3a 93 c1 de 66 f1 3f ca 54 8a f7 94 a5 22 6d c0 4a 10 ed 0e 1c 2a b1 4a 7b 1a 04 d7 d5 eb d8 1a 26 8b 6a 81 03
e3 1e 20 31 eb 62 e7 3c b6 ca 7b 9b 45 cf 42 a1 04 b6 d4 30 42 6b 3f 9c 3d 51 af 63 7e e0 19 9d fc 79 f1 25 7e b4 a4 70 b1 a7 11 a5 af 3a 20 01 82 c4 17 62
d7 e4 6d bb f4 d9 64 23 7b cf d5 b1 17 fb 87 80 b2 71 24 27 a6 42 8f 64 65 a8 39 92 92 de 47 eb ae a4 1f 8b 55 a8 80 59 f3 a6 0f 6c 27 27 d8 4f 5a 4a 96 f2
4c 00 45 00 a7 a1 70 f6 22 e2 dc 3c 2e 14 ce b5 51 24 c9 de 7a 1d 0c f4 ee e5 1c bf d8 09 65 bd d1 e1 d0 0d 25 4a fd 6d fd 32 4c 49 4b f1 67 07 18 c3 49 2f
51 78 3b 00 00 

51 f0 39 ab c5 23 bc 45 cb e8 3c 4b e3 76 31 dc 90 00
```
The additional byte seems to be wrong. Sorry for my implementation.

**Comment by vletoux** [comment]
And the right APDU sequence with a card

```
00 22 41 b8 06 80 01 47 84 01 81

90 00

10 2a 80 86 f0 45 77 98 0b ae 39 5d 32 51 46 e3 f0 1e b5 b2 67 65 e7 b7 a1 e8 f1 2e 4d df 64 35 41 a6 42 73 bb ff 98 c0 25 76 2a 37 ec db 87 0f 35 e4 14 fc
29 de 98 0a b2 1c e7 96 f6 5d c1 fa 63 44 f2 fb a5 31 83 aa 1f 65 11 52 96 d6 26 b7 63 0b f8 99 75 0a 84 11 cb e3 cc 92 8a f9 a7 5c 30 11 91 74 47 2f a3 24
81 bb 3e d3 a7 92 2f a9 fc 34 d8 ce fa 2b 64 3f a1 ee 2c 27 03 26 3b ba 5b 26 b5 77 f4 ac b5 70 6a af 77 f7 8f f7 78 62 6e e9 e6 4b 6b 8c d8 78 01 14 32 7a
9c 59 3e ac 8c 93 8a c2 59 fc 53 cc a7 12 1b f9 14 5a 2b 9e f3 60 9c 30 67 8d 25 43 65 1a 8f 8e 17 a2 9c 85 76 1b 66 05 13 cb 89 32 49 a1 24 60 f2 91 90 fa
7b ad df a3 bf 01 fc ab 3b 97 34 3b 1b 57 a8 7b 87 40 e9 35 bb ab 93 ec 90 e3 3c b0 d4 3b e3 fb 19 30 a6 4b 89

90 00

00 2a 80 86 10 2b f4 8e 11 a9 45 44 90 7c a0 e2 4f 8a 35 5d 53 00 

5f ef 38 f2 1a c8 d4 66 9f b0 42 67 13 72 54 78 90 00 
```
As I said, the Windows minidriver does handle chained & extended APDU without any problem

**Comment by dengert** [comment]
The "00 2a 80 86 00 01 00 ..." is using extended APDU for a sign operation, and is sending 256 bytes. 

The   "10 2a 80 86 f0 ..."  is using chaining for a sign operation and sending 240 bytes. 
Then "00 2a 80 86 10 ..." sends the remaining 16 bytes for total of 256. 
This implies max_send_size should be 240 when not using extended. 

 All the failed chaining has assumed max_send_size = 255. One of the failed is for decipher:
 "10 2A 80 86 FF 00 ..." is sending 255 bytes, and is for a decrypt that needs the PI byte the "00" after "FF" 
 "00 2A 80 86 02 2C AD" is sending the last 2 bytes for total of 257.

So it is starting to look like extended works and  non-extended is limited to 240 bytes?

**Comment by dengert** [comment]
Well here is another problem.  PKCS#11 appear to be doing a CKM_RSA_X509  i.e. RAW RSA,
passing in data of length 256  starting with  "00 8B 1F DA B0 ...

But  what is sent to the card  ( with mode to force max_send_size= 240) is "10 2A 9E 9A F0 00 8B 1F DA B0 ..." with total of 256 bytes. 

GIDs docs says in Table 60:  


|Function | P1 | P2 | Command data field | Response data field|
|-- | -- | -- | -- | --|
|PSO: COMPUTE DIGITAL   SIGNATURE | 9E | 9A | DER-encoded digest information (PKCS 1.5 only) \|\| data   to be signed (precomputed hash value) | Plain signature without further TLV coding
PSO: ENCIPHER | 86 | 80 | Data to be   enciphered (plain value) | Enciphered value without   further TLV coding
PSO: DECIPHER | 80 | 86 | Data to be deciphered    (Pl \|\|   cryptogram) | Deciphered value without   further TLV coding

Using P1=9A P2=9Eis the wrong way to do CKM_RSA_X509.  The caller has done its own padding. 
 It might be possible to emulate  CKM_RSA_X509 using   PSO: ENCIPHER  P1=86 P2=80  as Data to be enciphered is just (plain value)

By dropping CKM_RSA_X509  not setting flags = SC_ALGORITHM_RSA_RAW, Signatures now work by sending DigestInfo and Hash and let card do padding.

Decipher is still failing with "6D00": with using 240 or 255 with chaining.

**Comment by dengert** [comment]
Did Decipher ever work with the card-gids.c? Table 60 above implies that the data sent is always one byte bigger then the cryptogram `#define P1_DECIPHERMENT_INTERNAL_AUTHENTICATE_KEY_AGREEMENT 0x41`
implies there was some secure messaging key agreed upon.  But in the example in https://github.com/OpenSC/OpenSC/issues/1866#issuecomment-560098040 it is only sending 256 bytes which would mean the "PI" is null.  

`iso7816.c` is where the leading PI=00 is added. 

@vletoux  said: "The additional byte seems to be wrong. Sorry for my implementation." I assume you mean the PI byte. But GIDs docx says it should be there, but the windows APDU trace does not have the PI byte. Thus the Microsoft implementation is not following their own standard. Or is is possible the PI byte could be NULL and is only needed if Secure messaging is being used. 

ISO 7816-4-2013 hints at the PI may be missing in 10.2.2 SM DOs for confidentiality:
"For computing a cryptogram not to be preceded by a padding indication, the default mechanism is a stream cipher.  What other APDUs are in the trace? In this case, the cryptogram is the exclusive-or of the string of data bytes to conceal with a concealing string of the same length. Concealment thus requires no padding and the string of data bytes is recovered by the same operation." Is GIDs doing some type of stream cipher?"

I have been reading "Generic Identity Device Specification, Version 2.0", October 19, 2012 Is there a newer version?

**Comment by dengert** [comment]
With some hacking of `card-gids.c`,  `iso7816.c` and `opensc.conf`  I can get `pkcs11-tool --test --login` to work on Windows 10 using a TPM 2.0 using a Microsoft "Virtual Smart Card". 

[opensc-debug-noPI.240-20191202.txt](https://github.com/OpenSC/OpenSC/files/3913874/opensc-debug-noPI.240-20191202.txt)
[PKCS11_SPY.txt](https://github.com/OpenSC/OpenSC/files/3913873/PKCS11_SPY.txt)
[gids-test.diff.txt](https://github.com/OpenSC/OpenSC/files/3913886/gids-test.diff.txt)

This required:

-  remove SC_ALGORITHM_RSA_RAW as the GIDs don't support this.
-  set max_send_size = 240 @vletoux 's examples appears to do this. More testing is needed.
- With a decrypt command, don't send a Padding Indicator byte before the cryptogram. `iso7816.c`  does this as it appears to be needed and GIDs docs talk about it, but it looks like if not doing SM it is not needed, and should not be sent. 

Some of these may be restrictions of the TPM or "Virtual Smart Card" code and some GIDs cards may need the PI byte. 

So we may end up trying to support multiple implementations of GIDS applets. Much like multiple PIV applets or OpenPGP applets. How to identify the differences is going to be a problem.

**Comment by vletoux** [comment]
Doug,
Just to be clear, I designed the GIDS applet based on the specification AND the Windows implementation. The minidriver does work with the Windows implementation and I then based the OpenSC on my Gids implementation.
So the opensc driver was working with the card.
What was difficult to me if that I was at the time missing a TPM and thus couldn't test on the MS virtual smart card.
What's clear is that the current OpenSC driver doesn't work with both, so I made an appologize about that. I'm not a master at OpenSC stuff, so I suppose my test cases were not complete.

I'm super super busy with my new position as CERT manager (CERT to create from scratch) and in parallele with my activities at My Smart Logon & PingCastle.
I can do testing and a few debugging, but now is a very bad time for coding.

If you managed to fix my code, I'll be happy to test.

**Comment by dengert** [comment]
I did not mean to question your applet implementation of GIDs, but to question why did your applet and OpenSC driver work, but OpenSC driver did not work against the Microsoft Virtual Smart Card and TPM. There could be many reasons including ambiguities in  GIDs docs or what subset of GIDs is implemented in the Virtual Smart Card code. The main issue appears to be iso7816 says there is a PI byte and OpenSC `iso7816.c` will always include one, but it might be optional. GIDs says there is a PI byte, but does not say it is optional.  The `card-gids.c` may need to have its own `gids_decipher` routine to not send a PI byte. 

I got involved with this issue because it was interesting and complicated and I found I did have a laptop with a TPM. But I don't have any GIDs cards.  

I tried to use APDUtrace, but it would do nothing and `certutil` would say smart card service not running. So I took your suggestion to not send the PI byte in decipher and it worked! And that is where we are at today.

What might be going on, is the Microsoft "Virtual Smart Card" code, used only with a TPM, does not fully implement GIDs as indicated using chaining with max_send_size=240  and missing PI.

Microsoft also has some Virtual TPM, where they uses Hyper-V to isolate the virtual TPM. That too could cause additional problems. 

The VMWARE smart card reader appears to have some issues too. (I do not have VMWARE but use VirtualBox hosted on Windows 10 to support a virtual Ubuntu system.) 

In my tests, certutil was used to load a P12 file using the builtin Microsoft drivers for GIDs and no OpenSC code. The OpenSC minidriver was not used. Only PKCS11, and opensc-tools would use OpenSC after the cert, public and private key where loaded. 

After showing it was possible to get PKCS11 decipher to work with TPM, I was hoping that someone who has a TPM and GIDs cards would want to work on this. @el-oso ?

There are still a lot of unanswered questions like how does RDC work with any of this. How to know if the card is a TPM or GIDS card if there are any differences. What DOs are really needed? Is a EF.ATR needed? Does the OpenSC driver need to support SM? and many more. 

I also want to say: "If you managed to fix my code, I'll be happy to test."

**Comment by vletoux** [comment]
You miss a point: the decipher is not working on the GIDS card (anymore?)

**Comment by dengert** [comment]
I hinted at that with: "How to know if the card is a TPM or GIDS card if there are any differences."
If we can tell from any DOs on the card if it wants a PI byte or not, we can accommodate the difference by not sending PI to TPM but send it to GIDS applet. This should work with existing cards.

The question I would like to ask of you, Does certutil using microsoft drivers work today with decipher to current GIDS applet? Do you have APDU trace showing what it sends? 

I suspect it would fail because: [GidsApplet.java#L694](https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L694) tests for a PI and it must be 0x00. 

If Microsoft sends PI = 0x00 to the card but not to a TPM, then Microsoft is treating them differently. 
We could use the same trick, or some other way to tell the difference. 

We could also use a failed decipher with "6D00" to set a flag to not send PI to this device and retry the decipher without PI. 

The GIDS applet could also be changed to look at the decipher length. If its even, there is no PI, if odd there is a PI. (But this does not fix any problems with existing cards.)  

I would suggest that for GIDS cards and TPM we use the built in Microsoft minidriver and not OpenSC, using OpenSC only for PKCS11 and OpenSC tools. That is what my laptop is doing.

**Comment by el-oso** [comment]
Hi guys, 

Sorry that I have been a little bit absent for the last round of discussions. It has been hectic on this side ...

@dengert I am very interested on getting this code to work and I would be very happy to test and fix whatever I can. However, I have almost zero knowledge about TPMs, GIDS and sending raw bytes, so I am at a loss here. I'm trying to catch up, but will take some time. I just involved in these kind of things like a month ago, so don't expect too much for now ... I'm afraid.

Just to be clear I have 3 different models of TPMs where I can try this, but I don't have a GIDS card. 

Personally, I'm only interested of getting SmartCS to work with PKCS11 from python, but of course I would do my best to keep it functional for other things as well. @dengert How can I access the Microsoft minidriver?

**Comment by dengert** [comment]
Minidrivers are called from CAPI or CAPI2, i.e. the Microsoft PKI  which also includes the certificate store. Used by all Microsoft products and some others too. certutil is a utility on Windows to access the cert store and smart cards. certuril -scinfo  

 PKCS11 is a different API used on non Microsoft systems. OpenSC's PKCS11 (and others) can also be used on Windows. When smart cards are used they endup using PCSC from both  Microsoft PKI  and PKCS11. PCSC is built into Windows, and PCSClite is used on other platforms.

I don't know anything about SmartCS.   Ask them.

I think @vletoux and I may have some ideas on how to get the TPM vs GIDS applet working.

**Comment by el-oso** [comment]
I don't know why I wrote SmartCS (is that even a thing? :) ) ... I meant OpenSC obviously

**Comment by el-oso** [comment]
@dengert A bit late, but I also tested it on my TPM and it works! Thanks for fixing this and all your help.
