### ISSUE TITLE
Authenticated using blank pin

### ISSUE THREAD

**Issue by rvanlieshout** [OpenSC/OpenSC#1870]
### Problem Description

I'm really not sure if this is te place to place this possible issue. Feel free to guide me in other directions.

We've created tokens using:

```
pkcs15-init --create-pkcs15 --profile pkcs15+onepin --label %{key_name} --pin %{pin} --puk %{puk}
pkcs15-init --generate-key rsa/2048 --key-usage sign --auth-id 01 --label '%{key_name}'
```

And added a public key to our severs:

```
pkcs15-tool --read-ssh-key %{key_id}
```

Howver:

### Invalid pin

```
OpenSSH_7.9p1, LibreSSL 2.7.3
...
debug1: Connecting to server [1.2.3.4] port 22.
debug1: Connection established.
debug1: provider /usr/local/lib/opensc-pkcs11.so: manufacturerID <OpenSC Project> cryptokiVersion 2.20 libraryDescription <OpenSC smartcard framework> libraryVersion 0.20
debug1: provider /usr/local/lib/opensc-pkcs11.so slot 0: label <ePass Rene (User PIN)> manufacturerID <EnterSafe> model <PKCS#15> serial <248256330003801> flags 0x40d
...
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
...
debug1: Will attempt key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
...
debug1: Next authentication method: publickey
...
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Offering public key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
debug1: Server accepts key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
Enter PIN for 'ePass Rene (User PIN)': [**** invalid]
C_Login failed: 160
sign_and_send_pubkey: signing failed: error in libcrypto
debug1: No more authentication methods to try.
user@server: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

### Valid pin

```
...
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Offering public key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
debug1: Server accepts key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
Enter PIN for 'ePass Rene (User PIN)': [**** valid]
debug1: pkcs11_provider_unref: 0x7fa52b7036f0 refcount 2
debug1: Authentication succeeded (publickey).
```

### Blank pin (or ctrl+d)

```
...
...
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Offering public key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
debug1: Server accepts key: /usr/local/lib/opensc-pkcs11.so RSA SHA256:cpMI08pr/Qrh0knMtWzeg5gIcJNHInYeIA0vzM5EUvI token
Enter PIN for 'ePass Rene (User PIN)': [enter]
debug1: pkcs11_provider_unref: 0x7f8340e0c280 refcount 2
debug1: Authentication succeeded (publickey).
```

**Comment by rvanlieshout** [comment]
Note: this is a epass2003.

**Comment by Jakuje** [comment]
Did you remove the token from USB between the attempts? Do you have opensc.conf configured to reset the card once it leaves it? Indeed, this looks like a bug @FeitianSmartcardReader ?

**Comment by rvanlieshout** [comment]
@jakuje, 

> Did you remove the token from USB between the attempts

Not initially, but it does also work with a blank pin after a reboot

> Do you have opensc.conf configured to reset the card once it leaves it?

I have both a /usr/local/etc/opensc.conf and a /Library/OpenSC/etc/opensc.conf. They are the same and contain:

```
$ cat /Library/OpenSC/etc/opensc.conf
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
	framework pkcs15 {
		# use_file_caching = true;
	}
}
```

```
$ diff /usr/local/etc/opensc.conf /Library/OpenSC/etc/opensc.conf

```

**Comment by rvanlieshout** [comment]
Maybe somebody with an epass2003 can verify this behaviour?

**Comment by FeitianSmartcardReader** [comment]
It has solved in below, the code is not good enough, our R&D working on review the code internally, hasn't merge yet.
https://github.com/OpenSC/OpenSC/pull/1859

**Comment by rvanlieshout** [comment]
@FeitianSmartcardReader, So basically this means that whomever gets their hands on an ePass2003 could use the current version to bypass PIN protection. Isn't that a flaw in the ePass2003 itself?

**Comment by frankmorgner** [comment]
You should try using the key after verifying the "blank PIN". Only then it would be a security issue with the token itself. C_Login may return success though the ePass2003 may still lock usage of the key...

**Comment by rvanlieshout** [comment]
@frankmorgner, I was able to authenticate an SSH session using a blank pin, so the ePass2003 clearly allowed me to use it

We're now using Yubikey's and they don't have the same problem. Using the version from OpenSC I had I was able to authenticate using a blank pin, but only AFTER a successful pin entry before WHILE NOT removing the token from the USB port in between

**Comment by frankmorgner** [comment]
OpenSC performs some PIN caching, that can be disabled with
```
framework pkcs15 {
		# Use PIN caching?
		# Default: true
		use_pin_caching = false;
		#
		# How many times to use a PIN from cache before re-authenticating it?
		# Default: 10
		# pin_cache_counter = 3;
}
```
The cached PIN is automatically re-validated when the security status is not satisfied on the first try.

**Comment by rvanlieshout** [comment]
That makes sense, but the security issue then remains, right? @frankmorgner

**Comment by frankmorgner** [comment]
It depends... The card doesn't differentiate the different process that may or may not have validated the PIN. So every card (also the Yubikey) has the problem that process A may use a correct PIN while Process B is performing a signature in the right moment.

The only way to avoid this would be to either lock the token for a whole session (which doesn't allow a card to be used from a different application at all) or to de-authenticate every time you're finished with the card. The latter can be done in OpenSC's PKCS#11 module with `atomic = true;`, but that introduces many redundant card commands, which make the use of your card quite slow. Equally, Apple (CTK) and MS (Minidriver) have built this kind of PIN-separation into their OS to enforce the Process boundaries also for using the authenticated card, but depending on the card this only hides the problem for the well behaved processes instead of solving it entirely.

The only hardware based solution would be to enforce the PIN verification right before *every* signature. Most cards have the capabilities to do so, but it's very annoying for the user...

**Comment by rvanlieshout** [comment]
True, but the ePass didn't require a valid pin any time; not even after a reboot

**Comment by frankmorgner** [comment]
That's a problem! @FeitianSmartcardReader
