### ISSUE TITLE
How do I transfer needed files compiled on cygwin to other systems?

### ISSUE THREAD

**Issue by kaoscoach** [OpenSC/OpenSC#1884]
This is not a bug and I am unsure if this is the correct to ask questions or not?

I followed the directions to compile on cygwin here, https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Cygwin The good news is that it works perfectly. My question is how do I transfer  this solution to another system? I am guessing that I do not have to follow the same process of compiling on every system?  Or do I? I am unsure if I have to create some sort of package or copy some specific files. I appreciate any assistance on how to proceed.

**Comment by frankmorgner** [comment]
just copy the created DLL and EXE files

**Comment by frankmorgner** [comment]
that should work for other cygwin installations as well

**Comment by kaoscoach** [comment]
Thanks for replying. I am not sure which files need to be transferred though. In my tests on my local system, I am able to connect using the command, ssh -I /usr/local/lib/opensc-pkcs11.dll user@system However if I copy that dll to another system and try it, I get the message, "open /usr/local/lib/opensc-pkcs11.dll failed: No such file or directory". I also tried adding it to an ssh-agent by running, ssh-add -s /usr/local/lib/opensc-pkcs11.dll, but I get the message, "Could not add card "/usr/local/lib/opensc-pkcs11.dll": agent refused operation"

I tried copying the /usr/local directory but I get additional errors. pkcs11_get_key failed, sign_and_send_pubkey: error in libcrypto

I want to limit the number of files I need to copy, likewise I do not think I want to put the compiled opensc tools such as pkcs15-tool on these other systems because they are probably not needed. However I do not know what other files are missing. Also how do I know which additional cygwin packages might be needs by these other systems? The link for compiling opensc just seemed to need development tools which I do not think are needed on these other systems. Thanks again for your help.

**Comment by dengert** [comment]
You can use http://www.dependencywalker.com/  (also Google for: depends windows tool) to see what dlls you may need to copy.

**Comment by frankmorgner** [comment]
The most sustainable solution would be to create a dedicated package for OpenSC and submit that to Cygwin, see https://cygwin.com/packaging-contributors-guide.html! You're not the only one who was requesting this...

**Comment by kaoscoach** [comment]
I wasn't able to get it working and on the other system. It is currently beyond my expertise. I resolved it by installing ssh-pageant from cygwin and integrating it with pageant. Thanks anyway.
