### ISSUE TITLE
Have a predictable scheme for version numbers and file names

### ISSUE THREAD

**Issue by LeSpocky** [OpenSC/OpenSC#1886]
### Problem Description

When experimenting with building OpenSC with ptxdist (see #1885), I noticed the following. Your version numbers and file names are not predictable. These are the last Git tags:

* 0.20.0-rc2
* OpenSC-0.20.0-rc3
* 0.20.0-rc34

The release here on Github however:

* OpenSC-0.20.0-rc4 (this is for tag 0.20.0-rc34)

The filename for this:

* opensc-0.20.0.tar.gz

But only for Linux, for other systems the filename is CamelCase …

### Proposed Resolution

Please make life of packagers easier. Choose **one** scheme and stick to it!

**Comment by dpward** [comment]
@frankmorgner This was closed but not fixed. Can you please at a minimum fix the Git repository tags for the 0.20.0 release candidates?

**Comment by dpward** [comment]
@frankmorgner This was closed without being addressed.

At a very minimum, can you please:
- [ ] add a repository tag *0.20.0-rc3* which points to commit 01678e8
- [ ] add a repository tag *0.20.0-rc4* which points to commit 17d9d84
- [ ] edit the *OpenSC-0.20.0-rc3* release in GitHub, and simply change its repository tag to *0.20.0-rc3*
  ([described here](https://help.github.com/en/github/administering-a-repository/editing-and-deleting-releases#editing-a-release))
- [ ] edit the *OpenSC-0.20.0-rc4* release in GitHub, and simply change its repository tag to *0.20.0-rc4*

Then I would recommend:
- [ ] delete the repository tag *OpenSC-0.20.0-rc3*
- [ ] delete the repository tag *0.20.0-rc34*

This is not a moot issue with the final release. For regressions that were introduced between 0.19.0 and 0.20.0, the release candidates are still useful for bisection (there were nearly 4 months and 141 commits between rc1 and the final release). On platforms such as Windows and OS X where building OpenSC from source is more complicated, the rc builds are an easy way to somewhat narrow down when a regression was introduced. For individuals who are conducting an actual source code bisection using Git, fixing the mislabeled repository tags will avoid needless confusion when following the history (including use of `git describe`).

Thank you for fixing the tags above.

**Comment by LudovicRousseau** [comment]
I just checked. It looks like all your issues are fixed.
Am I wrong?

**Comment by dpward** [comment]
Yes, it appears to be fixed now. Thanks!
