### ISSUE TITLE
Please provide .dmg for OpenSC-0.20.0-rc4

### ISSUE THREAD

**Issue by jmastr** [OpenSC/OpenSC#1887]
### Problem Description

Other releases provide a MacOS package for OpenSC, but v0.20.0-rc4 misses it.

### Proposed Resolution

Upload `OpenSC-0.20.0.dmg` to the release page.

### Steps to reproduce

https://github.com/OpenSC/OpenSC/releases/tag/0.20.0-rc34

### Logs

**Comment by jmastr** [comment]
@frankmorgner could you do it please?

**Comment by frankmorgner** [comment]
It's now available
