### ISSUE TITLE
C_UnwrapKey CKR_GENERAL_ERROR in latest version

### ISSUE THREAD

**Issue by larssilven** [OpenSC/OpenSC#1888]
### Problem Description
C_UnwrapKey returns CKR_GENERAL_ERROR in latest code of the repository OpenSC-0.19.0-647-g17d9d845 (tag 0.20.0-rc34). The wrapping/unwrapping mechanism on card has been working before. It was introduced some year ago. The latest working commit that I have tested is  OpenSC-0.19.0-535-geac516fd.

### Environment
Debian testing on armhf (32bit).

Card: MyEID 4.0.18

### Proposed Resolution
Fix the regression.

### Steps to reproduce
See logs.

### Logs
I have attached logs for both the working and none working commit. Only thing changed between the tests is the OpenSC binaries.

#### Old commit that is working
[OpenSC-0.19.0-535-geac516fd-debug.log](https://github.com/OpenSC/OpenSC/files/3944578/OpenSC-0.19.0-535-geac516fd-debug.log)
[OpenSC-0.19.0-535-geac516fd-p11.log](https://github.com/OpenSC/OpenSC/files/3944600/OpenSC-0.19.0-535-geac516fd-p11.log)

The working C_UnwrapKey is on line 601 in the p11 log.

#### New commit that is NOT working
[OpenSC-0.19.0-647-g17d9d845-debug.log](https://github.com/OpenSC/OpenSC/files/3944604/OpenSC-0.19.0-647-g17d9d845-debug.log)
[OpenSC-0.19.0-647-g17d9d845-p11.log](https://github.com/OpenSC/OpenSC/files/3944605/OpenSC-0.19.0-647-g17d9d845-p11.log)

The failing C_UnwrapKey is on line 511 in the p11 log.

**Comment by frankmorgner** [comment]
fail:
```
[opensc-pkcs11] profile.c:356:sc_profile_load: Using profile directory '/home/lars/local/share/opensc'.
[opensc-pkcs11] profile.c:364:sc_profile_load: Trying profile file /home/lars/local/share/opensc/pkcs15.profile
[opensc-pkcs11] profile.c:369:sc_profile_load: profile /home/lars/local/share/opensc/pkcs15.profile loaded ok
[opensc-pkcs11] profile.c:373:sc_profile_load: returning with: -1201 (File not found)
[opensc-pkcs11] pkcs15-lib.c:376:sc_pkcs15init_bind: Failed to load profile 'pkcs15': File not found
[opensc-pkcs11] pkcs15-lib.c:393:sc_pkcs15init_bind: Load profile error: -1201 (File not found)
[opensc-pkcs11] card.c:523:sc_unlock: called
[opensc-pkcs11] reader-pcsc.c:709:pcsc_unlock: called
[opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1201 (File not found)
```
ok:
```
[opensc-pkcs11] profile.c:356:sc_profile_load: Using profile directory '/opt/opensc/share/opensc'.
[opensc-pkcs11] profile.c:364:sc_profile_load: Trying profile file /opt/opensc/share/opensc/myeid.profile
[opensc-pkcs11] profile.c:369:sc_profile_load: profile /opt/opensc/share/opensc/myeid.profile loaded ok
[opensc-pkcs11] profile.c:383:sc_profile_load: returning with: 0 (Success)
[opensc-pkcs11] profile.c:395:sc_profile_finish: called
[opensc-pkcs11] profile.c:403:sc_profile_finish: finish profile with 'MyEID' application profile
[opensc-pkcs11] profile.c:408:sc_profile_finish: Look for file by path 'a000000063504b43532d3135::'
[opensc-pkcs11] profile.c:410:sc_profile_finish: returned DF info (nil)
[opensc-pkcs11] profile.c:438:sc_profile_finish: returning with: 0 (Success)
[opensc-pkcs11] pkcs15-lib.c:417:sc_pkcs15init_bind: sc_pkcs15init_bind() select application path(type:2) '3f005015'
[opensc-pkcs11] card.c:819:sc_select_file: called; type=2, path=3f005015
[opensc-pkcs11] card-myeid.c:377:myeid_select_file: called
[opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
[opensc-pkcs11] card.c:475:sc_lock: called
[opensc-pkcs11] card.c:515:sc_lock: returning with: 0 (Success)
[opensc-pkcs11] apdu.c:513:sc_transmit: called
[opensc-pkcs11] apdu.c:363:sc_single_transmit: called
[opensc-pkcs11] apdu.c:367:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:C, data(2) 0xb5cfd52e
[opensc-pkcs11] reader-pcsc.c:296:pcsc_transmit: reader 'ACS ACR83U 00 00'
[opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: 


[opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
[opensc-pkcs11] reader-pcsc.c:306:pcsc_transmit: 


[opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
[opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
[opensc-pkcs11] card.c:525:sc_unlock: called
[opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Incorrect parameters P1-P2
[opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
[opensc-pkcs11] card.c:475:sc_lock: called
[opensc-pkcs11] card.c:515:sc_lock: returning with: 0 (Success)
[opensc-pkcs11] apdu.c:513:sc_transmit: called
[opensc-pkcs11] apdu.c:363:sc_single_transmit: called
[opensc-pkcs11] apdu.c:367:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:0, data(2) 0xb5cfd52e
[opensc-pkcs11] reader-pcsc.c:296:pcsc_transmit: reader 'ACS ACR83U 00 00'
[opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: 


[opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
[opensc-pkcs11] reader-pcsc.c:306:pcsc_transmit: 

15 86 03 11 o%......8..P....
00 00 00 63 ...............c
            PKCS-15..
[opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
[opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
[opensc-pkcs11] card.c:525:sc_unlock: called
[opensc-pkcs11] iso7816.c:571:iso7816_select_file: returning with: 0 (Success)
[opensc-pkcs11] card-myeid.c:383:myeid_select_file: returning with: 0 (Success)
[opensc-pkcs11] card.c:854:sc_select_file: returning with: 0 (Success)
[opensc-pkcs11] pkcs15-lib.c:422:sc_pkcs15init_bind: returning with: 0 (Success)
```
Could it be that the card isn't correctly initialized in the error case?

**Comment by larssilven** [comment]
Yes you are right.
I have been building for installation at /home/lars/local in both cases.
Then moved it to /opt/opensc on the target host (I am cross compiling).
Could it be that the old working version is using relative path to the config file and that the new not working version is using absolute path?
I believe that I used the installation path /home/lars/local in both cases. But I will check this.
I will also configure for /opt/opensc and see if it is working.

**Comment by larssilven** [comment]
./configure --host=arm-linux-gnueabihf --prefix=$HOME/local --with-completiondir=$HOME/local/share/bash-completion/completions'

was used for both versions.

**Comment by larssilven** [comment]
I was probably wrong in last comment must have used --prefix=/opt and then forgot all about it.
With --prefix=/opt it is working now for the latest version.

Sorry for bothering and thanks for the help.
Looking forward for the 0.20 release so I don't have to build myself.
