### ISSUE TITLE
Certificate information change in 0.20.0?

### ISSUE THREAD

**Issue by tzs** [OpenSC/OpenSC#1901]
### Problem Description

I'm not actually sure that this is an OpenSC issue rather than an issue with OpenVPN, but it showed up immediately after a Homebrew update on my Mac that updated OpenSC to 0.20.0, and did not update OpenVPN, and involves something OpenVPN gets via opensc-pkcs11.so, so that's my first guess.

Before 0.20.0, the OpenVPN command "openvpn --show-pkcs11-ids /usr/local/lib/pkcs11/opensc-pkcs11.so" which produces a serialized ID for each available certificate was producing this for my certificate:

OpenPGP\x20project/PKCS\x2315\x20emulated/<REDACTED>/User\x20PIN\x20\x28OpenPGP\x20card\x29/03

Now it produces this:

OpenPGP\x20project/PKCS\x2315\x20emulated/<REDACTED>/OpenPGP\x20card\x20\x28User\x20PIN\x29/03

With the \xNN decoded to make that readable and the differences bolded, those are:

OpenPGP project/PKCS#15 emulated/<REDACTED>/**User PIN (OpenPGP card)**/03

OpenPGP project/PKCS#15 emulated/<REDACTED>/**OpenPGP card (User PIN)**/03

**Comment by frankmorgner** [comment]
Yes, we fixed https://github.com/OpenSC/OpenSC/issues/1612 with 0.20.0, hence the change.
