### ISSUE TITLE
gnupg driver always loaded even if not listed in card_drivers

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#1904]
Hello,

Since version 0.20.0 (on linux), it seems that the gnupg driver is aways loaded meaning that when firefox is running it will lock my gnupg card and then it cannot be used with `gpg` CLI

With the previous versions it was working flawlessly

My config:
```
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
	framework pkcs15 {
		# use_file_caching = true;
	}
	card_drivers = belpic, cardos;
}
```

**Comment by frankmorgner** [comment]
That's a long standing gpg issue, which didn't get solved in years by the GNUPG team. We can't do anything about that, you should go to the gpg support to discuss that.

**Comment by frankmorgner** [comment]
by the way, the gpg behavior affects all previous versions of OpenSC as well.

**Comment by bigon** [comment]
The fact that gpg requires an exclusive lock was was worked around by NOT enabling the gnupg driver in opensc, so gpg can do whatever it wanted

This was working fine with opensc << 0.20.0

**Comment by frankmorgner** [comment]
Maybe we're talking about two different problems.

If you can provide some more input (GnuPG debug output and OpenSC debug output), feel free to reopen this issue yourself.

**Comment by bigon** [comment]
FTR, it seems that the debian package is installing the `opensc.conf` file in `/etc/opensc/` directory instead of `/etc/ directly

Has the patch changed between 0.19 and 0.20

**Comment by frankmorgner** [comment]
Not on our side. You should file an issue at Debian's support if this bugs you
