### ISSUE TITLE
Possible problems with sc_decompress_zlib_alloc()

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1905]
### Problem Description

I think we need to have a closer look at `sc_decompress_zlib_alloc()` It looks like there's are multiple problems with:
- calling realloc with size 0 (possible double free)
- missing length checks when calculating the buffer sizes
- possible misconception of realloc (afaik, "shrinking down" a buffer is not possible)

**Comment by Jakuje** [comment]
I think I was fixing some of the issues with the decompress in #1830. If we are going to change something there, it should be already covered with unit tests to make sure it works.

**Comment by frankmorgner** [comment]
There are unit tests, yes, but I didn't notice any changes to `src\libopensc\compression.c`...

**Comment by Jakuje** [comment]
They were already merged in 07d3d8e. But I agree there might be more issues that I missed

**Comment by frankmorgner** [comment]
I see, but that doesn't fix the points above. I hope to find time later for some fixes...
