### ISSUE TITLE
Safenet tool occupy begining three slots without connecting any token over windows

### ISSUE THREAD

**Issue by ashwaniksoni** [OpenSC/OpenSC#1909]
If I install safenet tool over windows, it occupies initial three slots. So when I connect oseid token it get detected over third slot not at zeroth slot. It happens even in case when safenet token is not connected.

**Comment by frankmorgner** [comment]
Sorry, I don't understand your setup. What card do you have, what software, I don't even know if you're using OpenSC...

**Comment by popovec** [comment]
probably it's about https://safenet.gemalto.com/multi-factor-authentication/security-applications/authentication-client-token-management/  and probably  safenet uses pkcs11 interface -> opensc -> OsEID card/token  (MyEID)

**Comment by frankmorgner** [comment]
There is no evidence for your assumption, please contact the vendor for more information.

**Comment by ashwaniksoni** [comment]
I am using opensc0.19 and Oseid token in windows 7. when opensc is installed as well as safenet tool(available online- SafeNetAuthenticationClient) is installed. Installed safenet tool by default shows in device manager Aladdin IFD Handler (three time), Rainbow iKey Enumerator (one time) and Rainbow  iKey Virtual Reader (two times). (Without connecting any token)
When without connecting any token in system, run pkcs11-tool -L it displays:
Available Slots:
Slot 0 <0x0>: AKS ifdh 0
 <empty>  
Slot 1 <0x4>: AKS ifdh 1
<empty> 
Slot 2 <0x8>: AKS VR 0
<empty> 
Slot 3 <0xc>: Rainbow Technologies iKeyVirtualReader 0
<empty> 

If I connect any token further, it takes next slot.

**Comment by frankmorgner** [comment]
For every empty card reader, OpenSC creates an empty slot. This behavior is intended.

**Comment by ashwaniksoni** [comment]
But No empty card reader is connected. In that situation when safenet tool is not installed it shows:
Available Slots:
No Slots.
 
I don't know probably if safenet is creating any internal virtual slot (which is a soft token slot) and opensc is detecting it.

**Comment by stavpup** [comment]
I have a spare safenet 5110 token I could provide for testing  purposes for some time,  provided it is returned to me.  I have tried to make it work in Debian but I have not succeeded.

**Comment by dengert** [comment]
Sounds like the safenet  code has defined more readers then OpenSC will look at. OpenSC has a configured limit in opensc.conf: 

max_virtual_slots = num;
           Maximum Number of virtual slots (Default: 16). If there are more slots than defined
           here, the remaining slots will be hidden from PKCS#11.

       slots_per_card = num;
           Maximum number of slots per smart card (Default: 4). If the card has fewer keys than
           defined here, the remaining number of slots will be empty.

The output of `pkcs11-tool -L` above show this. You can have 16/4= 4 readers. The last reader has
" Slot 3 <0xc>: Rainbow Technologies iKeyVirtualReader 0" where Slot 3 (The 4th reader) has a CK_SLOT_ID of 0x0c i.e. 12 where virtual slots 13, 14, 15 are hidden.

So try changing in opensc.conf  "max_virtual_slots = 32;"  and see if you can see any additional readers.  Add or modify this section in your opensc.conf from [opensc.conf.example](https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in#L971)

When the application calls C_GetSlotList, the PKCS11 module returns a list of slots. The term "Slot 3" is misnamed and is really the index into the  listg application from C_GetSlotList can see, with or without cards.

**Comment by frankmorgner** [comment]
Please re-open this topic if there's new input available.
