### ISSUE TITLE
STARCOS 3.5 support

### ISSUE THREAD

**Issue by piraatooo** [OpenSC/OpenSC#1912]
### Problem Description
Hello :-) 

I am trying to get a STARCOS 3.5 SmartCard to work under linux (Gentoo), I noticed version 3.5 was not supported, but now is getting some support now.

Actually, I have not managed to get any usefull info from the card.

I can provide feedback and testing, maybe some easy development.

### Proposed Resolution
SmartCard STARCOS 3.5 beeing able to use PKCS11 for signing and encryption.

### Steps to reproduce
The output of `/usr/bin/pcsc_scan` is :
```
Thu Jan 23 14:31:36 2020
 Reader 0: Bit4id miniLector-s 00 00
  Card state: Card inserted, 
  ATR: 3B DA 96 FF 81 31 FE 45 80 56 31 B8 53 49 43 41 81 05 7B

ATR: 3B DA 96 FF 81 31 FE 45 80 56 31 B8 53 49 43 41 81 05 7B
+ TS = 3B --> Direct Convention
+ T0 = DA, Y(1): 1101, K: 10 (historical bytes)
  TA(1) = 96 --> Fi=512, Di=32, 16 cycles/ETU
    250000 bits/s at 4 MHz, fMax for Fi = 5 MHz => 312500 bits/s
  TC(1) = FF --> Extra guard time: 255 (special value)
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 45 --> Block Waiting Integer: 4 - Character Waiting Integer: 5
+ Historical bytes: 80 56 31 B8 53 49 43 41 81 05
  Category indicator byte: 80 (compact TLV data object)
    Tag: 5, len: 6 (card issuer's data)
      Card issuer data: 31 B8 53 49 43 41
    Tag: 8, len: 1 (status indicator)
      LCS (life card cycle): 05
+ TCK = 7B (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B DA 96 FF 81 31 FE 45 80 56 31 B8 53 49 43 41 81 05 7B
        STARCOS 3.5 ID ECC C1R (PKI)
        https://www.gi-de.com/fileadmin/user_upload/MS/Certificates/STARCOS35_ID_ECC_TABLES.pdf
```

The output of `opensc-tool -c starcos --list-algorithms` seems to work:
```
Using reader with a card: Bit4id miniLector-s 00 00
Algorithm: rsa
Key length: 512
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 768
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 1024
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 )
RSA public exponent: 65537
```
But trying `opensc-tool -c starcos -f`:
```
Using reader with a card: Bit4id miniLector-s 00 00
3f00 type: DF, size: 0
select[N/A] lock[N/A] delete[N/A] create[N/A] rehab[N/A] inval[N/A] list[N/A] 

sc_list_files() failed: Not supported
```
or `pkcs11-tool --login -M`:
```
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GetMechanismList failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.
```

**Comment by frankmorgner** [comment]
As starting point, you could try to add the following patch:
```diff
diff --git a/src/libopensc/card-starcos.c b/src/libopensc/card-starcos.c
index 85d11811..ee059c82 100644
--- a/src/libopensc/card-starcos.c
+++ b/src/libopensc/card-starcos.c
@@ -45,6 +45,7 @@ static const struct sc_atr_table starcos_atrs[] = {
        { "3B:D9:96:FF:81:31:FE:45:80:31:B8:73:86:01:E0:81:05:22", NULL, NULL, SC_CARD_TYPE_STARCOS_V3_5, 0, NULL },
        { "3B:D0:97:FF:81:B1:FE:45:1F:07:2B", NULL, NULL, SC_CARD_TYPE_STARCOS_V3_4, 0, NULL },
        { "3b:df:96:ff:81:31:fe:45:80:5b:44:45:2e:42:41:5f:53:43:33:35:32:81:05:b5", NULL, NULL, SC_CARD_TYPE_STARCOS_V3_5, 0, NULL },
+       { "3B:DA:96:FF:81:31:FE:45:80:56:31:B8:53:49:43:41:81:05:7B", NULL, NULL, SC_CARD_TYPE_STARCOS_V3_5, 0, NULL },
        { NULL, NULL, NULL, 0, 0, NULL }
 };
```
Basically, there have been some hacks to support some Starcos 3.5 cards, but so far no developer took the time to implement this in a general way to support all/other possible Starcos configurations. We would be happy to take pull requests, if you're interested...

**Comment by piraatooo** [comment]
Thank you for reaction and the first step.

What i got now for `opensc-tool -c starcos --list-algorithms` is:
```
Using reader with a card: Bit4id miniLector-s 00 00
Algorithm: rsa
Key length: 512
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 768
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 1024
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 1728
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 1976
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537

Algorithm: rsa
Key length: 2048
Flags: onboard key generation padding ( pkcs1 iso9796 ) hashes ( sha1 MD5 md5-sha1 ripemd160 sha256 sha384 sha512 sha224 )
RSA public exponent: 65537
```
which seems to be more real than the previous answer. Also, reading the serial number and card name seem to work.

However, the rest is the same ... do you have any clues, how to proceed ?

**Comment by frankmorgner** [comment]
pkcs11-tool should not say `CKR_TOKEN_NOT_PRESENT` anymore. You could provide a debug log for further analysis (`OPENSC_DEBUG=3 pkcs11-tool --test --login`).

Please note that doing remote debugging here in issue is very hard. Most likely, you will still need to get your hands dirty and fix the card driver to get this fixed properly (or you find someone who does this for you)!

**Comment by piraatooo** [comment]
So I spent some time with the card, the original windows app, the ISO standard and OpenSC :-)

The log from the suggested command is attached.

The strange thing for me is that a PKCS15 framework tries a bind ... the card should be using PKCS11.
[starcos_3.5_log.txt](https://github.com/OpenSC/OpenSC/files/4127505/starcos_3.5_log.txt)

Furthermore, the card seems not to support listing the files, so recursive listing does not work.

I haven't tried to do a APDUTrace of signing a document in Windows yet ...

**Comment by frankmorgner** [comment]
The starcos cards I've seen do have PKCS#15 compliant meta data to announce PINs, keys and certificates that are on the card. OpenSC looks for this meta data, but can't find it, e.g. in the ESIGN application. Maybe your card isn't correctly initialized or the propriatary driver has some internal information about the structure of your card. In either case, it's hard to say how to add support for your card in OpenSC...

**Comment by fdelapena** [comment]
The new Certum Open Source Certificate cards are STARCOS 3.5 based and return similar results (debug log posted at #2009).

**Comment by larskanis** [comment]
I successfully use Certum Open Source Signing Certificate since 2018 for the [RubyInstaller](https://rubyinstaller.org/) project on Linux. It makes use of the OpenSSL engine implementation of OpenSC and the PKCS#11 library provided by Certum. The process is documented [here](https://github.com/oneclick/rubyinstaller2/wiki/CertumCodeSigning). Maybe this is helpful for someone.
