### ISSUE TITLE
Crescendo 144K FIPS failure with "Alcor Micro AU9560 00 00"

### ISSUE THREAD

**Issue by jamescassell** [OpenSC/OpenSC#1925]
### Problem Description
With certain Crescendo 144K FIPS smart card and the "Alcor Micro AU9560 00 00" reader, `pkcs11-tool -L` shows as `(empty)` even though the card is plugged in.  The program returns instantly as if no card were inserted, rather than pausing to read it.  (If I insert a card backwards, it still pauses and tries to read it, but obviously fails.)

With the "Alcor Micro AU9520 00 00" reader, the same card is read normally as would be expected.

Strangely, other cards also labeled "144K FIPS" work fine in both readers.

The AU9560 reader is a laptop-embedded reader, whereas the AU9520 is an external reader.

https://www.hidglobal.com/sites/default/files/resource_files/crescendo-smart-card-ds-en_0.pdf

### Steps to reproduce
Plug problematic card into the laptop reader and observe failure.  Plug it into the external reader connected to the same laptop.

### Logs

opensc version 0.19.0

**Comment by frankmorgner** [comment]
please use 0.20.0

To create a log, run `opensc-tool --list-readers -vvv`. Maybe you can already spot the error there...

**Comment by jamescassell** [comment]
I'll work around it for now by using the external reader.  I'll re-open the issue if I get time to troubleshoot.

**Comment by dengert** [comment]
Look at:
https://ccid.apdu.fr/ccid/section.html#4 
https://ccid.apdu.fr/ccid/section.html#5

one can do extended APDU the other can not. One has dwMaxCCIDMessageLength 271 bytes the other 272.  
What can the card do? 
A debug log would show what OpenSC thinks of the reader.
