### ISSUE TITLE
macOS: tools built with --enable-cryptotokenkit fail to detect reader

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1932]
### Problem Description

```
$ ll /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/opensc-tool
-rwxr-xr-x  1 ur20980  admin  1690400 Feb  4 23:20 /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/opensc-tool*
$ /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/opensc-tool -l
No smart card readers found.
$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Yubico Yubikey 4 OTP+U2F+CCID
$
```

### Proposed Resolution

No idea. My workaround is to only use tools and `opensc-pkcs11.dylib` that were built with `--enable-pcsc --disable-cryptotokenkit`.

### Steps to reproduce

Build `OpenSCToken`, locate OpenSC tools it built (after installation they should be in `/Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/`), try them, observe the result.

**Comment by mouse07410** [comment]
@frankmorgner ping?

This is a bad one, as it prevents all the use of the OpenSC tools (and libraries) with CryptoTokenKit.

**Comment by mouse07410** [comment]
@frankmorgner have you ever build OpenSC with `--enable-cryptotokenkit` on Mojave or Catalina? If so, were you able to detect/access a token with `pkcs11-tool`? E.g., `pkcs11-tool -L`?

Because in my case (as listed above), building with `--enable-cryptotokenkit --disable-pcsc` guarantees that the tools won't be able to detect/access *any* physical token.

**Comment by mouse07410** [comment]
Just to report that this problem persists for me thorough the current Macias Monterey.

**Comment by frankmorgner** [comment]
There are two problems...

First, the code signature of the binaries packaged with OpenSCTokenApp has a conflict. It is signed with `com.apple.security.app-sandbox` whereas it should only be signed with `com.apple.security.inherit` (see [this explanation](https://developer.apple.com/forums/thread/679940?answerId=674564022#674564022)). To fix this, create `opensctoken_binaries.entitlements` with the following content:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.inherit</key>
    <true/>
    <key>com.apple.security.smartcard</key>
    <true/>
</dict>
</plist>
``` 
Then use these commands to create the correct code signature and list your yubikey:
```
sudo codesign --force --sign "${CODE_SIGN_IDENTITY}" --entitlements opensctoken_binaries.entitlements /Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/opensc-token
/Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/opensc-token -n
```

Second, if you're configuring OpenSC to use cryptotokenkit, then you need to add the `com.apple.security.smartcard` entitlement. Use the codesigning command from above with the following entitlements:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <false/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.smartcard</key>
    <true/>
  </dict>
</plist>
```

That should be enough to fix your use case, although I'm currently not sure how to fix this confusion for the OpenSC builds
