### ISSUE TITLE
Firefox:  Stuck on invalidated PKCS#11 session handles

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#1935]
### Problem description
In NSS there is a problem with handling CKR_SESSION_HANDLE_INVALID as result of some PKCS#11 operation. When NSS opens a session and asks for the password, then CKR_SESSION_HANDLE_INVALID as result of C_Login correctly sets the internal state to CK_INVALID_SESSION. However, the opened (and invalidated) session is still used for further operation with the PKCS#11 module. This results in (a potentially infinite) number of password prompts although a token has long been removed.

Steps to reproduce:

1.   Configure PKCS#11 module in Firefox
2.   Insert token (it's shown in "Security Devices" as "not logged in")
3.   Go to a Website that requests a client certificate and wait for the password prompt for the token
4.    Remove the token
5.    Enter a password or abort it to close the password prompt
6.    Go to a Website that requests a client certificate and wait for the password prompt for the token
7.    Go to step 5. and repeat.

This bug reproduces with Firefox 72, OpenSC and a Yubikey, for example. After Step 4, the slot for the token still exists and the token is correctly shown as "not present" in the list of "security devices". However, the open (but invalid) session is never closed and PK11_Authenticate constantly tries to use the session to verify a password.

Note, that in Step 4, the PKCS#11 module is forced to invalidate all existing PKCS#11 sessions to a slot:

>(quote PKCS#11 v2.30 "Session events":)
>When the device is removed, all sessions of all applications are automatically logged out. Furthermore, all sessions any applications have with the device are closed (this latter behavior was not present in Version 1.0 of Cryptoki)"an application cannot have a session with a token that is not present. Realistically, Cryptoki may not be constantly monitoring whether or not the token is present, and so the token's absence could conceivably not be noticed until a Cryptoki function is executed. If the token is re-inserted into the slot before that, Cryptoki might never know that it was missing.
>(quote end)

Hence, all further operation with existing sessions to a removed token result in CKR_SESSION_HANDLE_INVALID

### Actual results:

Depending on the number of open TLS session, the user cannot get rid of constantly popping password prompts and is forced to close Firefox.

### Expected results:

If the PKCS#11 module returns CKR_SESSION_HANDLE_INVALID, NSS needs to close the session and re-open a new one.

**Comment by frankmorgner** [comment]
I believe this problem needs to be solved in Firefox/NSS and created https://bugzilla.mozilla.org/show_bug.cgi?id=1613632

I don't know whether newer versions are affected.

**Comment by dengert** [comment]
The spy log posted in https://bugzilla.mozilla.org/show_bug.cgi?id=1613632 fails on C_CloseSession 
 for a session that was valid at one time. If the session no longer exists, but was already closed, would the following (untested) patch to OpenSC solve the problem?   

Usually after a close of any kind an application can not really do anything. 

```
diff --git a/src/pkcs11/pkcs11-session.c b/src/pkcs11/pkcs11-session.c
index c6b271b7..a4d262cb 100644
--- a/src/pkcs11/pkcs11-session.c
+++ b/src/pkcs11/pkcs11-session.c
@@ -110,7 +110,7 @@ static CK_RV sc_pkcs11_close_session(CK_SESSION_HANDLE hSession)
 
        session = list_seek(&sessions, &hSession);
        if (!session)
-               return CKR_SESSION_HANDLE_INVALID;
+               return CKR_OK;
 
        /* If we're the last session using this slot, make sure
         * we log out */
```

**Comment by frankmorgner** [comment]
Nice idea, but unfortuantely that doesn't change the outcome. If this patch is applied, the session handle is changed to NULL after C_CloseSession, but Firefox doesn't really delete the session, i.e. it C_GetSessionInfo with NULL and asks the PIN for a non-existent card.  :disappointed:

**Comment by dengert** [comment]
OK, looking at source from https://github.com/mozilla/gecko-dev in 
gecko-dev/security/nss/lib/util/pkcs11t.h they added: `#define CK_INVALID_SESSION 0` and do many tests for this before every call to CK_CloseSession  and then set `session->handle = CK_INVALID_SESSION;`  (I may have missed the some.)

Your original spy trace shows the session->handle is not NULL and was valid at some time.   
Can you get a back trace where CKR_SESSION_HANDLE_INVALID is set before the patch?

What looks strange is entry 61 C_GetSlotList where 0 slots are returned. Entry 62 C_GetSlotInfo  should not be called as there are no slots. 
 PKCS11 has some restrictions on changing the slot list, so why is   C_GetSlotList returning pulCount = 0?

**Comment by frankmorgner** [comment]
I don't think I'll investigate further. I think the problem is easily producible with any card that has a PIN. I'll wait for response from the Firefox team if they have an idea what's going wrong here.

**Comment by dengert** [comment]
Here are comments:
 
- OpenSC pkcs11 says its version is 2.20.

- Firefox   [pk11util.c#L996](https://github.com/mozilla/gecko-dev/blob/master/security/nss/lib/pk11wrap/pk11util.c#L996)  says:

```
 995 /*
 996  * check to see if the module has added new slots. PKCS 11 v2.20 allows for
 997  * modules to add new slots, but never remove them. Slots cannot be added
 998  * between a call to C_GetSlotLlist(Flag, NULL, &count) and the subsequent
 999  * C_GetSlotList(flag, &data, &count) so that the array doesn't accidently
1000  * grow on the caller. It is permissible for the slots to increase between
1001  * successive calls with NULL to get the size.
1002  */
1003 SECStatus
1004 SECMOD_UpdateSlotList(SECMODModule *mod)
```

- OpenSC  debug log, nspr_log_file and gdb sessions show many calls to C_GetStolList, from mulitiple threads. 

- Before removal of a smart card from reader C_GetStolList returns *pulCount = 0x1 i.e. only one slot.

- After removal of smart card from reader C_GetStolList returns *pulCount = 0x1 Still only one slot. 

- **But** after **reader and card**  are removed together subsequent C_GetStolList returns *pulCount = 0x0  (stimulating  a Yubikey or any token with built in reader.)

- `SECMOD_UpdateSlotList(SECMODModule *mod)` does not update the slot list as it is expecting PKCS11 v2.20 handling of slot lists. So it still had the original slotlist with the session handle in it. Note there appears to be multiple copies of slot lists in Firefox, each has the invalid original session handle the session handle.  is changed to 0x00 which is still invalid. 

- So Firefox continues to use the original slot list and get into the loop.

- Firefox appears to recover if only the card and both card and reader are removed. 

Possible solutions:

- Fix OpenSC to follow v2.20 restrictions even if reader is removed.  

- Modify FireFox to remove slots, remove  v2.20 restrictions. 


Environment:
Ubuntu-18.4 Firefox 72.0.2 VirtualBox with Windows 10 host and OpenSSL s_server to simulate web site using my own CA certificates for s_server and smart card (PIV card)  


- 



-

**Comment by frankmorgner** [comment]
I've found an old copy of v2.20, which shows that OpenSC behaves as required while Firefox's interpretation is an error, see https://www.cryptsoft.com/pkcs11doc/STANDARD/pkcs-11v2-20.pdf page 107. Please check and, if positive, report this back to Mozilla.

We could, of course, violate the standard for Firefox. I think you only need to remove these lines https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11-global.c#L491-L504 to do this to do so in order of checking if this fixes the problem...

**Comment by dengert** [comment]
I think you are right.  Page 107 says: "If an application calls C_GetSlotList with a non-NULL pSlotList,
and then the user **adds or removes a hardware device**, the changed slot list will only be
visible and effective if C_GetSlotList is called again with NULL."

It looks like the only calls to C_GetSlotList are in ./pk11load.c, debug_module.c  and ./pk11util.c so 
a change could be implemented in  [SECMOD_UpdateSlotList](https://github.com/mozilla/gecko-dev/blob/master/security/nss/lib/pk11wrap/pk11util.c#L1004)

I will comment on https://bugzilla.mozilla.org/show_bug.cgi?id=1613632 tomorrow. 

TODO
- add a test to pkcs11-tool (or separate program) to print the list of CK_Slot_IDs and C_Slot_Info, when user changes a token. 
- check if OpenSC is creating Slot_ID consistently. 
- look at what p11kit does.
