### ISSUE TITLE
Software RSA-PSS with OpenPGP card

### ISSUE THREAD

**Issue by rufoa** [OpenSC/OpenSC#1936]
I'm trying to use an OpenPGP 2.0 card in my web browser through PKCS#11.
This works great with TLS 1.2 (which uses PKCS#1 v1.5), but fails with TLS 1.3 (which uses RSA-PSS).

The OpenPGP card hardware does not support RSA-PSS, but I understand OpenSC added support for software-based RSA-PSS in v0.20.0 (https://github.com/OpenSC/OpenSC/pull/1435).

However, it appears the `*-PSS` machanisms are still not available:

```
$ pkcs11-tool -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA224, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  RSA-PKCS, keySize={4096,4096}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA224-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA256-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA384-RSA-PKCS, keySize={4096,4096}, sign, verify
  SHA512-RSA-PKCS, keySize={4096,4096}, sign, verify
  MD5-RSA-PKCS, keySize={4096,4096}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={4096,4096}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={4096,4096}, generate_key_pair
```

This also fails, as expected:
```
$ pkcs11-tool --sign --mechanism RSA-PKCS-PSS --hash-algorithm SHA256 --input data.sha256. --pin $PIN
Using slot 0 with a present token (0x0)
Using signature algorithm RSA-PKCS-PSS
PSS parameters: hashAlg=SHA256, mgf=MGF1-SHA256, salt_len=32 B
error: PKCS11 function C_SignInit failed: rv = CKR_KEY_TYPE_INCONSISTENT (0x63)
Aborting.
```

Could you please tell me where I'm going wrong, if this is a known problem, or how I might troubleshoot the issue further? Many thanks.

(I'm running v0.20.0 on Fedora)

**Comment by frankmorgner** [comment]
OpenPGP doesn't support RSA-RAW as well, hence RSA-PSS is not available.

Is the usage of RSA-PSS in TLS 1.3 the only option or does it also allow the older mechanisms to be used?

**Comment by rufoa** [comment]
Ah, I didn't realise that. That makes sense.

The TLS 1.3 spec now mandates RSA-PSS for TLS handshake messages (PKCS#1 v1.5 is now only permitted for signatures in the cert chain, not in the handshake)

**Comment by frankmorgner** [comment]
OK, good to know.

- For other cards, we are emulating the unpadded RSA signature with the RSA decipher command, That would be an option for the key on slot 3 or in OpenPGP 3.3 for all slots, see https://github.com/OpenSC/OpenSC/issues/1843
- I suspect that browsers know how to makre RSA-PSS from a raw RSA key as well, or do you know some browser that actually requires us to implement RSA-PSS for TLS 1.3?

**Comment by rufoa** [comment]
> I suspect that browsers know how to makre RSA-PSS from a raw RSA key as well, or do you know some browser that actually requires us to implement RSA-PSS for TLS 1.3?

I'm not sure, but [one source](https://mailarchive.ietf.org/arch/msg/tls/u4nWhgQnF0v8HTJvlSiQk2uaLxg) says both Chrome and Firefox (NSS) will revert to using raw RSA if available :+1:

> For other cards, we are emulating the unpadded RSA signature with the RSA decipher command, That would be an option for the key on slot 3 or in OpenPGP 3.3 for all slots, see #1843

...so this approach sounds like a good fit for the problem!

**Comment by kwinz** [comment]
I have the same problem with Windows 10 "virtual smartcard": it doesn't support RSA-PSS so it fails with current OpenVPN versions using TLS 1.2 or 1.3.

I was hoping that by using the PKCS11 backend with OpenSC instead of the CAPI backend RSA-PSS could then be emulated from RSA-RAW by OpenSC. Everything looks good, I enter my PIN succesfully, but then I still get this error:
```Thu Feb 04 00:09:15 2021 PKCS#11: Cannot perform signature 112:'CKR_MECHANISM_INVALID'
Thu Feb 04 00:09:15 2021 OpenSSL: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib
Thu Feb 04 00:09:15 2021 TLS_ERROR: BIO read tls_read_plaintext error
Thu Feb 04 00:09:15 2021 TLS Error: TLS object -> incoming plaintext read error
Thu Feb 04 00:09:15 2021 TLS Error: TLS handshake failed
```

Do I need to activate something to enable Software RSA-PSS?

[1] https://community.openvpn.net/openvpn/ticket/1296
[2] https://superuser.com/questions/1611572/how-can-i-create-a-virtual-smart-card-on-my-tpm-without-joining-my-windows-com

**Comment by kwinz** [comment]
PS: An example output for the Windows 10 "virtual smartcard" is this:

```
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe -O
Using slot 0 with a present token (0x0)
Public Key Object; RSA 2048 bits
  label:      client-xps15-892f8191-e384-4465-a-26720
  ID:         00
  Usage:      encrypt, verify
  Access:     none
Certificate Object; type = X.509 cert
  label:      client-xps15-892f8191-e384-4465-a-26720
  subject:    DN: CN=client-xps15
  ID:         00
```

```
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA224, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  RSA-PKCS, keySize={1024,4096}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,4096}, sign, verify
  SHA224-RSA-PKCS, keySize={1024,4096}, sign, verify
  SHA256-RSA-PKCS, keySize={1024,4096}, sign, verify
  SHA384-RSA-PKCS, keySize={1024,4096}, sign, verify
  SHA512-RSA-PKCS, keySize={1024,4096}, sign, verify
  MD5-RSA-PKCS, keySize={1024,4096}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={1024,4096}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={1024,4096}, generate_key_pair
```

```
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool -L
Available slots:
Slot 0 (0x0): Microsoft Virtual Smart Card 0
  token label        : GIDS card (UserPIN)
  token manufacturer : www.mysmartlogon.com
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 8ef553487aadf787
  pin min/max        : 4/15
```

**Comment by frankmorgner** [comment]
@kwinz , please open a seperate ticket. You're using a GIDS card rather than an OpenPGP card. But as with OpenPGP, we don't support raw RSA for GIDS:
https://github.com/OpenSC/OpenSC/blob/0d693f63cbebda1440f1468eb30c35b7a278f7e9/src/libopensc/card-gids.c#L667

**Comment by Jakuje** [comment]
I am not sure if there is anything to do right now from our side -- either the card supports RAW or PSS so it can be used for TLS 1.3 or it does not and it can not be used. If there will be some follow-up needed, please open a new issue.
