### ISSUE TITLE
OpenSC 0.19 unable to interact with Gemalto IDBridge CT700

### ISSUE THREAD

**Issue by juuldiks** [OpenSC/OpenSC#1943]
I am developing a web application that uses the Gemalto IDBridge CT710 card reader. I am unable to use openSC in combination with this reader when deploying the web application to the server (Windows Server 2019). However it all does seem to work when running the application locally on a laptop.

The issue occurs as soon as the web application contact the reader for a `GetSlotInfo()` function call. See the log for more detailed information.

I have checked that both the openSC versions match (0.19) and that both system have the same Gemalto drivers.

 Any help is very much appriciated.

[openSC-log2.txt](https://github.com/OpenSC/OpenSC/files/4190938/openSC-log2.txt)

**Comment by dengert** [comment]
From you log, -1900 is SC_ERROR_UNKNOWN, and most likely came from `pcsc_to_opensc_error()` in reader-pcsc.c. i.e. pcsc returned some SCARD_* return that was not mapped. A pcscd trace would help.

You did not say what OS you are using, this could be an issue. 

When you say "web application" worked on single laptop but not on the servers it is not clear what you expect to happen.  The smart card reader is normally on the client side, but the web application is run on the web server side. So server has no access to the client's reader and card using pkcs11.

Smart card access in web applications is usually done by the browser as part of some HTTPS client authentication using SSL/TLS.

(Windows Remote Desktop Connection allows client to allow access to "local devices and resources" under "More" including "Smart cards"  from a remote server done at the PCSC level which OpenSC uses. But I don't think that is what you are trying to do.)

**Comment by juuldiks** [comment]
The laptop is running Windows 10, the server is running Windows Server 2019.

The web application we are developing is used by production machines. We'd like to connect the Gemalto card reader (class 3 card reader) to the server (via a remote USB hub that is connected to the server via IP). The smart card, which must be inserted and unlocked before the production machine can operate is controlled by the web application. In this case there is no browser involved.

As far as my knowledge goes pcscd is only available for Linux. I will try to find a similar tools to get some PC/SC traces.

**Comment by juuldiks** [comment]
I cannot find a similar tracing tool. But did find an interesting fact. When I open the PC/SC Tracker 1.2.2 by Mounir Idrassi. The card reader is oonly shown on the Windows laptop, but not shown in the list when running on the Windows Server.

![image](https://user-images.githubusercontent.com/25709763/74349727-ee8ea800-4db4-11ea-89d4-bb439d005e2f.png)

**Comment by dengert** [comment]
OpenSC on Windows provides both a minidriver  for use with Micrsoft programs like login, certutil, Certificate Store, EDGE. And also provides PKCS11 for use other applications. 
In both cases the builtin Microsoft PC/SC is used. 

I have no knowledge of a "remote USB hub that is connected to the server via IP" But it sounds like it can not handle smart cards. 

You may want to look at an security risks of using such a device with smart cards. For example
exposure of the PIN to the server then misuse of the user's card from the server which should never see the PIN.  SSL/TLS or even SSH do not send the PIN over the network.

**Comment by dengert** [comment]
This does not sound like an OpenSC problem.

**Comment by frankmorgner** [comment]
Your log contains the following line:
```
P:956; T:2888 2020-02-12 09:58:32.755 Gemalto IDBridge CT7xx 0:SCardGetStatusChange failed: 0x00000005
```
0x00000005 is not known to PC/SC, see https://pcsclite.apdu.fr/api/pcsclite_8h.html for possible status codes. I also think that this is a problem related to your remote USB solution.

I've written `pcsc-relay` (https://frankmorgner.github.io/vsmartcard/pcsc-relay/README.html) and `vicc --type=relay` (https://frankmorgner.github.io/vsmartcard/virtualsmartcard/README.html) to forward a card to a virtual smart card reader on a remote host. This worked for me on all major OSs.

**Comment by juuldiks** [comment]
An update in case others might run into similar issues in the future.

The error code 0x00000005 is not known by PC/SC as it is no error defined by PC/SC. 0x00000005 is the general Windows access denied error. The issue was caused by the web application running under a user that did not have permission to access USB devices. The issue was resolved by running the web application under a user that did have these permissions.
