### ISSUE TITLE
Supporting 3DES and DES 

### ISSUE THREAD

**Issue by uae1972** [OpenSC/OpenSC#1950]
Hi,
I believe that the SC-HSM does not support the DES/3DES operation, correct?
I think it only supports the following mechanism:
CKM_SHA_1
CKM_SHA256
CKM_SHA384
CKM_SHA512
CKM_MD5
CKM_RIPEMD160
CKM_GOSTR3411
CKM_ECDSA
CKM_ECDSA_SHA1
CKM_ECDH1_COFACTOR_DERIVE
CKM_ECDH1_DERIVE
CKM_ECDSA_KEY_PAIR_GEN
CKM_RSA_X_509
CKM_RSA_PKCS
CKM_SHA1_RSA_PKCS
CKM_SHA256_RSA_PKCS
CKM_SHA384_RSA_PKCS
CKM_SHA512_RSA_PKCS
CKM_MD5_RSA_PKCS
CKM_RIPEMD160_RSA_PKCS
CKM_RSA_PKCS_KEY_PAIR_GEN
I am using it to personalize Java card, and I need to calculate the session keys using the DES/3DES Key Key Derivation mechanism Any suggestion?

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
The SmartCard-HSM supports only RSA, EC and AES keys. DES keys are not supported.
