### ISSUE TITLE
Import Key from another HSM to SC-HSM (WRAP/UNWRAP)

### ISSUE THREAD

**Issue by uae1972** [OpenSC/OpenSC#1951]
Hi,
I have some RSA keys in **SoftHSM** and **SafeNet HSM**, and I would like to import them to SC-HSM.
Usually, I should be able to export  "WRAP" them under another 3DES transport key (secret key)  and then, Import "UN-WRAP" them to any other HSM, but I am not sure that I can do this with SC-HSM, any suggestion?

**Comment by frankmorgner** [comment]
That's implemented in the Vendor's [Smart Card Shell](https://www.openscdp.org/scsh3/) for SC-HSM, but not directly in OpenSC. Please contact @CardContact for details.
