### ISSUE TITLE
OpenSC MiniDriver PIN Pad Dialog Messages

### ISSUE THREAD

**Issue by commonism** [OpenSC/OpenSC#1953]
### Problem Description

I'm trying to customize the pin pad dialog messages using the md_pinpad_ options on Windows 10 using OpenSC 0.20.

Even though I verified my card_atr block matches, it does not work.

I figured I should see the logging of the md_get_config_icon (https://github.com/OpenSC/OpenSC/blob/0.20.0/src/minidriver/minidriver.c#L550) when setting md_pinpad_dlg_icon - yet there is nothing. 
The pin dialog (where you have to enter the pin) is unchanged.

### Steps to reproduce

```
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
	framework pkcs15 {
		# use_file_caching = true;
	}
}

app cardmod {
	# SmartCard-HSM with contact-based interface or USB-Stick
	card_atr 3B:FE:18:00:00:81:31:FE:45:80:31:81:54:48:53:4D:31:73:80:21:40:81:07:FA {
		driver = "sc-hsm";
		read_only = false;
		md_supports_X509_enrollment = true;
		md_supports_container_key_gen = true;
		md_guid_as_label = true;

		# Window title of the PIN pad dialog
		# Default: "Windows Security"
		md_pinpad_dlg_title = "Title";
		#
		# Filename of the icon for the PIN pad dialog; use "" for no icon
		# Default: Built-in smart card icon
		md_pinpad_dlg_icon = "theicon";
	}
}
```

**Comment by frankmorgner** [comment]
Are you sure that the ATR block matches? Do you have a debug log?

**Comment by commonism** [comment]
The ATR matches the ATR for the Smartcard-HSM from the opensc.conf.example.in.
I used driver = "npa"; to cause an effect based on the ATR (effect is the card does not work as I use Smartcard-HSM).

I test using "certutil /scinfo", resulting debug log is massive, which level would you need?

**Comment by commonism** [comment]
I do not have access to any of requirements to reproduce anymore.

**Comment by dengert** [comment]
Do you have a SC-HSM token (built in USB) or a smart card which is inserted into a reader. Most readers do not have a pin pad.
What reader do you have?

These might help:  
- https://github.com/OpenSC/OpenSC/wiki/Pinpad-Readers
- Google for: Windows smart card pin pad readers

**Comment by commonism** [comment]
As I said, it's been 2 years, I do not have access to the equipment any more.
