### ISSUE TITLE
"error: card type 7533: not an OpenPGP card" / programatic precedence of GIDS in OpenSC 0.20.0

### ISSUE THREAD

**Issue by ckahlo** [OpenSC/OpenSC#1971]
### Problem Description

When using a multi-application card, like JavaCard, with GIDS and OpenPGP installed the openpgp-tool refuses to work. The tool claims to have only found a "GIDS card" but does not even try to detect the OpenPGP application.
The card is correctly detected if GIDS is removed (which is not an option besides of testing) and
is correctly detected by gpg, openkeychain and others.

### Proposed Resolution

Availability of an enforcement command line switch as in opensc-explorer -c / implicitly enforce use of openpgp card driver when openpgp-tool is called.
(there are also FIDO U2F, OATH and other applications on the card)

### Steps to reproduce

Any JavaCard with both GIDS and an OpenPGP applet installed.

### Logs
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\openpgp-tool.exe -r 5 -C -U -K -v
Connecting to card in reader REINER SCT cyberJack wave 0...
Using card driver GIDS Smart Card.
error: card type 7533: not an OpenPGP card

P:21508; T:5960 2020-03-03 15:05:01.417 [openpgp-tool] ===================================
P:21508; T:5960 2020-03-03 15:05:01.418 [openpgp-tool] opensc version: 0.20.0-0.20.0
P:21508; T:5960 2020-03-03 15:05:01.418 [openpgp-tool] PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:21508; T:5960 2020-03-03 15:05:01.419 [openpgp-tool] reader-pcsc.c:1347:pcsc_detect_readers: called
P:21508; T:5960 2020-03-03 15:05:01.419 [openpgp-tool] Probing PC/SC readers
P:21508; T:5960 2020-03-03 15:05:01.419 [openpgp-tool] Establish PC/SC context
[....other readers...]
P:21508; T:5960 2020-03-03 15:05:01.463 [openpgp-tool] Adding new PC/SC reader 'REINER SCT cyberJack wave 0'
P:21508; T:5960 2020-03-03 15:05:01.463 [openpgp-tool] REINER SCT cyberJack wave 0 check
P:21508; T:5960 2020-03-03 15:05:01.463 [openpgp-tool] current  state: 0x00010422
P:21508; T:5960 2020-03-03 15:05:01.463 [openpgp-tool] previous state: 0x00000000
P:21508; T:5960 2020-03-03 15:05:01.464 [openpgp-tool] card present, changed
P:21508; T:5960 2020-03-03 15:05:01.824 [openpgp-tool] REINER SCT cyberJack wave 0:SCardConnect(SHARED): 0x00000000
P:21508; T:5960 2020-03-03 15:05:01.824 [openpgp-tool] reader-pcsc.c:1114:detect_reader_features: called
P:21508; T:5960 2020-03-03 15:05:01.824 [openpgp-tool] Requesting reader features ... 
P:21508; T:5960 2020-03-03 15:05:01.827 [openpgp-tool] reader-pcsc.c:1515:pcsc_detect_readers: returning with: 0 (Success)

**Comment by dengert** [comment]
OpenSC only supports one applet per reader  per application at this time.

Use opensc-tool --list-drivers to see the list.

You can force a driver using environment variable OPENSC_DRIVER=  or some commands have an option or you can modify opensc.conf to limit the list or reorder it. 

Even trying to use more then one applet on the same card  from different applications can be problematic because some applets will drop the login state when another applet is selected.

**Comment by ckahlo** [comment]
`OPENSC_DRIVER=openpgp`
did the trick. Thanks a lot, thats all I needed to know.

I am aware of the rest, I am pre-testing OpenSC for our Linux guys and normally don't use OpenSC by myself. Using my own code instead over decades.

All transactions are atomic, so we're fine with the environment variable.

Best regards,
Christian
