### ISSUE TITLE
Cannot add /usr/lib64/pkcs11/opensc-pkcs11.so module into firefox

### ISSUE THREAD

**Issue by youidzero** [OpenSC/OpenSC#1981]
### Problem Description
I am unable to load the PKCS11 module into firefox. I created a bug a mozilla here https://bugzilla.mozilla.org/show_bug.cgi?id=1622310

I was recommended to post this here about not being able to load the OpenSC module /usr/lib64/pkcs11/opensc-pkcs11.so into my Firefox browser. 

### Steps to reproduce

Steps to reproduce:

Launch Firefox -> Preferences -> Privacy & Security -> Security Devices -> Load ->

Module Name: OpenSC
Module filename: /usr/lib64/pkcs11/opensc-pkcs11.so

Actual results:

Unable to add module

Expected results:

The module should have loaded.

**Comment by frankmorgner** [comment]
how did you install or build OpenSC?

**Comment by Jakuje** [comment]
According to the mozilla bug, the reported did not answer any question there either. But they are running Fedora, which has opensc automatically loaded through `p11-kit-proxy` and adding it again can obviously cause issues. Closing as it does not look like anything we could address.

**Comment by Jakuje** [comment]
No follow-up -- no bug. It looks like the opensc is loaded through p11-kit already and loading it again correctly fails.
