### ISSUE TITLE
Allow PKCS11SPY_OUTPUT to specify a filename template

### ISSUE THREAD

**Issue by dpward** [OpenSC/OpenSC#1984]
When encountering deadlock issues between PKCS #⁠11 enabled applications, I find it helpful to run [PKCS #⁠11 Spy](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC#pkcs-11-spy). It would be useful to be able to set `PKCS11SPY` and `PKCS11SPY_OUTPUT` at the operating system level (e.g. in */etc/environment*), particularly in order to trace background processes such as *gsd-smartcard* that are not invoked directly by the user. However, this would cause different processes to clobber the same output file.

I would suggest allowing `PKCS11SPY_OUTPUT` to specify a filename template instead, which could contain a subset of the [format specifiers](http://man7.org/linux/man-pages/man5/core.5.html) that are allowed in the `kernel.core_pattern` sysctl parameter.

Thoughts?

**Comment by dengert** [comment]
Good idea. It could also be used in `opensc.conf` for debug_file=.

A subset of "%p" and "%t" might be all that is needed.  And it can all be done within OpenSC code, so should work on any system. 

OpenSC logs already have PID, Thread, time and a name of program if provided in each. But pkcs11 programs show up as "opensc-pkcs11" and "minidriver" shows up as minidriver. 

 A "%e" would be nice if it is easy to get the actual executable name. 

On windows pkcs11-spy  and ctx.c can do some expansions:
https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11-spy.c#L166
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/ctx.c#L387

It could be expanded after expanding with a PR like you propose.

**Comment by frankmorgner** [comment]
I think that using the environment variables is powerful enough. Did you try modifying the startup scripts to "diversify" the output file?
