### ISSUE TITLE
How to load pkcs11 modules via conf file

### ISSUE THREAD

**Issue by pbdeuchler** [OpenSC/OpenSC#1990]
### Problem Description
I am trying to load the yubihsm 2 module via configuration file with opensc. The goal is to emulate the `module` command line flag in the following example command (which works with a real path and a yubihsm configuration file):
```
pkcs11-tool --module /path/to/lib/yubihsm_pkcs11.dylib --login --pin 0001password  --keypairgen --key-type rsa:2048 --label "my_fancy_key" --usage-sign
```

Is this possible? I do not see a variable to change within the [documented pkcs11 block](https://htmlpreview.github.io/?https://github.com/OpenSC/OpenSC/blob/master/doc/files/files.html#pkcs11) and adding module blocks like so:
```
module lib/yubihsm_pkcs11.dylib {
	ports = 1;
}

module yubihsm {
	module = "yubihsm2";
	module_path = "lib/yubihsm_pkcs11.dylib";
}
```
Seems to trigger no change in my opensc debug output.

**Comment by pbdeuchler** [comment]
For further reference I am trying to use https://github.com/miekg/pkcs11 with OpenSC

**Comment by dengert** [comment]
`pkcs11-tool` is designed to load any PKCS11 module even if not not from OpenSC. 

`opensc-pkcs11.dylib` is a PKCS11 module just like `yubihsm_pkcs11.dylib` Each of these is self contained and does not load any other module.  

The `opensc.conf` is used to configure the OpenSC and its pkcs11 module, not other modules. 

OpenSC `pkcs11-spy.dylib` is a special PKCS11 module that loads just one PKCS11 module to log   PKCS11 calls  by the application to the the loaded module.   It can be used between any application and any  pkcs11 module. 

Sounds like you want [p11-kit](https://p11-glue.github.io/p11-glue/p11-kit.html) which can load  multiple PKCS11 modules and present them as one module to  calling application. 

Mozilla's NSS uses in firefox and Thunderbird can also use multiple multiple pkcs11 modules.

**Comment by pbdeuchler** [comment]
Thank you, I really appreciate that explanation. Trying to reverse engineer this tooling to be used in a golang stack has been a real struggle for me.

**Comment by mouse07410** [comment]
You absolutely can use YubiHSM2 with OpenSC tools. Add you correctly surmised, instead of `opensc-pkcs11.dylib` you'll use `yubihsm_pkcs11.dylib`.

You realize that you have to have `yubihsm-connector` running on the machine where YubiHSM2 is inserted, regardless. (Well, there *is* one exception, but we won't go there for now.)

I'll post here the module you need for p11-kit. It's simple. 

I use YubiHSM2 with `pkcs11-tool` and with OpenSSL (using `libp11`). I've no idea what that miekg/pkcs11 repo is that you referred to, or what it does - you're on your own there.

**Comment by pbdeuchler** [comment]
@mouse07410 thank you for your reply as well... I've actually gotten this working by abandoning my use of opensc tooling and just calling the dylib directly from golang. I'm still using OpenSC tooling to interact with the yubihsm manually for testing and exploration, but my end goal is a self contained package that I can lay down on airgapped machines
