### ISSUE TITLE
Feature Request: automatic updates on non-*nix platforms

### ISSUE THREAD

**Issue by thw0rted** [OpenSC/OpenSC#2001]
### Problem Description

This driver had two major security-relevant updates in the last two years, and I had no idea until I came by to see if another issue I was having had been resolved.

### Proposed Resolution

Provide an optional automatic check for important updates and prompt the user to install them.

### Additional Information

I also don't see anything in the wiki / FAQ about the update process.  I assume it's probably fine to just run the newer version's MSI and have it replace the old files, but if you don't want to provide an automatic update option, it would be nice to at least include a short section in the wiki explaining this.

**Comment by frankmorgner** [comment]
this boils down to integrating into the OS's distribution channels (Apple/Microsoft Store). This issue is related to #1129. It is solved for most Unix distributions.

**Comment by thw0rted** [comment]
While I agree that distributing updates via Windows Update or Microsoft Store would be nice to have, I'd rather have an update check that runs in user space than no automatic updates at all.

There has been no movement on #1129 in a year, and I don't see a clear path to success -- if Microsoft has a plan for applying their software-signing model to the open source community, I haven't seen it.  In the meantime, a number of high-profile projects (like the official Git distro for Windows) ship with an update checker that functions as I've described, and will ensure that users aren't stuck with vulnerable software.  I think it might be a good fit for OpenSC on Windows, at least in the medium-term.

**Comment by frankmorgner** [comment]
I think the platform stores are most user friendly with built-in security features, that's why we should take advantage of them, in my opinion. However, for open source projects, however, it's typically easier to maintain a single (and free) solution, hence one updater for all platforms. Anyway, in OpenSC, nobody seems to have the resources to go either way... (contributions welcome!).

**Comment by thw0rted** [comment]
Hey man, I get it, I appreciate all the work any contributors have done and nobody owes me anything.  I'd just like to leave this issue here as an idea that somebody could come along and add if they have the time.  It seems like something that could be stolen wholesale from a similar project without a ton of integration effort 😁
