### ISSUE TITLE
FYI: OpenSC (2018 version) detected as malware by Avira Free Antivirus

### ISSUE THREAD

**Issue by R-Adrian** [OpenSC/OpenSC#2002]
### Problem Description

This morning, just after i started my PC, Avira free AV popped up a warning that my OpenSC installation was detected as Malware... HEUR/AGEN.1110013
hmmmmm... i will reboot and try the latest OpenSC version after that.

![image](https://user-images.githubusercontent.com/16319504/78856623-ec04a380-7a2f-11ea-8d75-008c895af8ae.png)

![image](https://user-images.githubusercontent.com/16319504/78856669-06d71800-7a30-11ea-89a2-55876e8512a8.png)

### Proposed Resolution
 ... ?  (get a coffee? probably i won't be the only one to report this issue today)

### Steps to reproduce
-have OpenSC installed on Windows 10 x64 (pro) (i had an older version, installed with OpenSC-0.18.0-rc2-win64_vs12-Release.msi)
-have Avira Free Antivirus installed

### Logs
```
04/09/2020,06:38:15.434 [INFO] FP reports status 'NO False Positive' for file 'C:\Program Files\OpenSC Project\OpenSC\tools\npa-tool.exe' [I:10, S:111]
04/09/2020,06:38:15.434 [DETECTION] Contains suspicious code HEUR/AGEN.1110013!
  C:\Program Files\OpenSC Project\OpenSC\tools\npa-tool.exe
      [INFO] The file will be copied to quarantine!
```

**Comment by R-Adrian** [comment]
after a reboot i decided to try and reinstall of that same version
(OpenSC-0.18.0-rc2-win64_vs12-Release.msi,
SHA-256 checksum: 995d25fdf517cfe70050214a2cf26fdc1c610e6fcf65eb7a5c203662dede6aab  )

and... Avira decided to nuke the entire .\tools\ subfolder... it's gone :(

![image](https://user-images.githubusercontent.com/16319504/78858212-5ddeec00-7a34-11ea-8aaa-139632a9fabf.png)

![image](https://user-images.githubusercontent.com/16319504/78858231-74854300-7a34-11ea-8b74-2ee3d7db681f.png)

**Comment by R-Adrian** [comment]
and after another reboot... i installed the latest release version, OpenSC-0.20.0_win64.msi SHA-256: 614e727efdb62958cae05c12fb5d3f046c6a98d1bbdb11df259a8e2b8b8acb04

Looks OK so far, no complaints from my antivirus.

**Comment by frankmorgner** [comment]
I'm not an expert on Snakeoil, but would an preemptive upload to virustotal put the binary on some whitelist?

**Comment by R-Adrian** [comment]
the files from OpenSC-0.18.0-rc2-win64_vs12-Release have been uploaded to virustoal since 2018... but Avira suddenly decided today to consider them icky.. Anyway, updating OpenSC to the latest version solved for me the problem with Avira nuking that older version.

since that older version is affected by some significant CVEs (see https://github.com/OpenSC/OpenSC/wiki/OpenSC-security-advisories ) it is possible that those OpenSC binaries were included in some other piece of real malware that was processed by Avira and they decided to "toss the baby out with the bathwater".

**Comment by R-Adrian** [comment]
P.S. Here's the VirusTotal link too
https://www.virustotal.com/gui/file/83346e167aec147b9a98720fe7b7b65c71065f4139b3d60cb862ddf1746a7126/detection

![image](https://user-images.githubusercontent.com/16319504/78910060-0882f900-7a8d-11ea-95a6-1dcc031b8ead.png)

**Comment by R-Adrian** [comment]
update: the 2018 version is no longer detected as malware by Avira or flagged on Virusotal.
Avira and F-Secure seem to have fixed their detections.
