### ISSUE TITLE
trunk-as-of-2020-04-09 fails to compile on debian/testing

### ISSUE THREAD

**Issue by VelinPavlov** [OpenSC/OpenSC#2003]
Hello,
I am trying to compile opensc/trunk as of 2020-04-09 on a debian/testing system. I've done this for months already and it normally succeeds. Since about a week ago, I'm getting build-errors; most recent is included. I believe the reason is a programming error / bad practice in opensc-notify.c (not handling write () return code). I'm ready to provide as much info on my build system as I possibly can, if requested.

... ... 
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src -D'DEFAULT_PKCS11_PROVIDER="/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"' -D'DEFAULT_ONEPIN_PKCS11_PROVIDER="/usr/lib/x86_64-linux-gnu/onepin-opensc-pkcs11.so"' -Wdate-time -D_FORTIFY_SOURCE=2 -I../../src -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-unused-but-set-variable  -Wall -Wextra -Wno-unused-parameter -Werror -g -O2 -fdebug-prefix-map=/home/vel/lirex/opensc/20200409125703/OpenSC=. -fstack-protector-strong -Wformat -Werror=format-security -c -o opensc_notify-opensc-notify.o `test -f 'opensc-notify.c' || echo './'`opensc-notify.c
opensc-notify.c: In function ‘sig_handler’:
opensc-notify.c:192:2: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
  192 |  write(cancellation_fd[1], &sig, sizeof sig);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
... ...

**Comment by frankmorgner** [comment]
should be fixed with 5e79a2a4abdd523cfff19824718bbb0d8ced7320
