### ISSUE TITLE
META: bug reporting instructions are broken

### ISSUE THREAD

**Issue by thw0rted** [OpenSC/OpenSC#2007]
### Problem Description
The template that was in this text box when I clicked "New Issue" reads
````
<!--
Please read about [reporting bugs](https://github.com/OpenSC/OpenSC/wiki/How-to-report-bugs-so-that-they-can-be-fixed) before opening an issue.
-->
````

but the linked page does not exist.

### Proposed Resolution

Document the bug-reporting process.

**Comment by frankmorgner** [comment]
could you change that to https://github.com/OpenSC/OpenSC/wiki/How-to-write-a-good-bug-report?

**Comment by thw0rted** [comment]
Could who change it?  I'm not a project member, I can't edit the template.

**Comment by frankmorgner** [comment]
you can make a PR to .github/ISSUE_TEMPLATE.md

**Comment by thw0rted** [comment]
I was going to update it but when I clicked through to edit it, Github put up a notice that this template is in the "old" format and they've since changed to a [different system](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates). I haven't had time to read the whole thing yet, I'll have to put a pin in this and come back to it. Sorry!

**Comment by frankmorgner** [comment]
The new format looks promising, but to solve your problem just make a PR using the old format. For the new one, you may open a new issue...

**Comment by ValZapod** [comment]
This can be closed then?
