### ISSUE TITLE
Add support for the ACS ACR101 ICC Reader, used by Certum's Open Source Code Signing program

### ISSUE THREAD

**Issue by CyberShadow** [OpenSC/OpenSC#2009]
Hello, and sorry if I am filing this in the wrong place.

Certum provides Microsoft Authenticode Code Signing certificates (for signing Microsoft Windows executables and installation packages) to open-source developers at a reduced price. As far as I know, this service is the most affordable way for open-source developers to sign their Windows release binaries.

As of a few years ago, due to changes in Microsoft Authenticode policies, Certum only issues code signing certificates on hardware tokens (they sell a bundle which includes a token and a certificate which can be activated online). The token seems to be a ACS ACR101 ICC Reader (USB ID 072f:1204).

I am trying to get code signing working on Linux, as it is my main development platform and I can perform all aspects of the Windows builds on it, except for code signing. As I understand, the process would be as follows:

1. A PC/SC driver for the token is needed. I see that the [ACSCCID project](http://acsccid.sourceforge.net/) provides a driver for this token; the manufacturer also seems to [provide some open-source drivers for download](https://www.acs.com.hk/en/products/141/acr101i-simicro-ccid/#downloads).
2. A PC/SC implementation makes the device available to applications using the installed driver. For Linux, that would be pcsclite.
3. OpenSC can talk to the device through the PC/SC daemon, and can export this functionality via an OpenSSL engine.
4. OpenSSL provides the interface for applications wishing to perform cryptographic operations.
5. Finally, the osslsigncode tool [can be used to sign PE files through libp11](https://github.com/mtrojnar/osslsigncode/issues/34#issuecomment-595688457).

(Edit: I have since realized that there are two devices involved, the reader and the card, so the above isn't accurate.)

Following the [guide on the wiki](https://github.com/OpenSC/OpenSC/wiki/Quick-Start-with-OpenSC) yields:

```console
$ opensc-tool --reader 0 --atr
3b:9f:96:81:b1:fe:45:1f:07:00:64:05:1e:b2:00:31:b0:73:96:21:db:05:90:00:5c

$ opensc-tool --reader 0 --name
Unsupported card
```

and, `pkcs11-tool` shows:

```console
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): ACS ACR101 ICC Reader 00 00
C_GetTokenInfo() failed: rv = CKR_TOKEN_NOT_PRESENT
```

So, if I understand correctly, the missing link is OpenSC's support for this device.

I'm happy to help with what I can to aid its inclusion, though unfortunately I'm not well versed in cryptography or hardware tokens.

**Comment by frankmorgner** [comment]
According to your ATR, this [should be a starcos card](https://smartcard-atr.apdu.fr/parse?ATR=3b%3A9f%3A96%3A81%3Ab1%3Afe%3A45%3A1f%3A07%3A00%3A64%3A05%3A1e%3Ab2%3A00%3A31%3Ab0%3A73%3A96%3A21%3Adb%3A05%3A90%3A00%3A5c). Could you try the changes suggested in https://github.com/OpenSC/OpenSC/pull/2006?

**Comment by frankmorgner** [comment]
Can you share a link for the open source code signing?

**Comment by CyberShadow** [comment]
> Could you try the changes suggested in #2006?

Yes! I get much further along with that:

```console
$ bin/opensc-tool --reader 0 --name 
STARCOS 3.2

$ bin/pkcs11-tool -L           
Available slots:                      
Slot 0 (0x0): ACS ACR101 ICC Reader 00 00
  token label        : profil standardowy (User Pin)
  token manufacturer : Unizeto Technologies SA
  token model        : PKCS#15
  token flags        : login required, rng, token initialized, PIN initialized, user PIN locked
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 4601781501171226
  pin min/max        : 4/8
Slot 1 (0x1): ACS ACR101 ICC Reader 00 00
  token label        : profil bezpieczny (User Pin)
  token manufacturer : Unizeto Technologies SA
  token model        : PKCS#15
  token flags        : login required, rng, token initialized, PIN initialized, user PIN locked
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 4601781501171226
  pin min/max        : 4/8

$ osslsigncode sign -certs ~/Downloads/62602869cdafc234227550034ae89fbf.pem -pkcs11engine /usr/lib64/engines-1.1/pkcs11.so -pkcs11module ./lib/opensc-pkcs11.so -in ~/work/Digger/digger.exe -out ~/work/Digger/digger-signed.exe   
Enter PKCS#11 token PIN for profil standardowy (User Pin):
Signing failed(PKCS7_dataFinal)
140454764689216:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
140454764689216:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:290:Type=PKCS7
140454764689216:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:
140454764689216:error:8207A005:PKCS#11 module:pkcs11_private_encrypt:General Error:p11_rsa.c:116:

Failed
```

> Can you share a link for the open source code signing?

Certainly. here is their product page: https://en.sklep.certum.pl/open-source-code-signing.html

**Comment by CyberShadow** [comment]
Not sure if I'm doing anything wrong or it's not working for some other reason - with `-key 'pkcs11:token=profil standardowy (User Pin);object=Open Source Developer, Vladimir Panteleev'` I get the same output as above. `OPENSC_DEBUG=3` shows:

```
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] card.c:523:sc_unlock: called
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] card-starcos.c:2130:starcos_check_sw: sw1 = 0x6a, sw2 = 0x88
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Referenced data not found
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] card-starcos.c:2024:starcos_compute_signature: returning with: -1216 (Data object not found)
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] sec.c:63:sc_compute_signature: returning with: -1216 (Data object not found)
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] card.c:523:sc_unlock: called
P:1252957; T:0x140175323223872 11:30:32.228 [opensc-pkcs11] pkcs15-sec.c:707:sc_pkcs15_compute_signature: use_key() failed: -1216 (Data object not found)
```
etc.

**Comment by frankmorgner** [comment]
One criticism of #2006 is that it's tied to a specific card profile. Your profile may be different and thus lead to an error. @rumpelsepp

Could you try `pkcs11-tool --test --login` as self-test without external components?

**Comment by CyberShadow** [comment]
> Could you try `pkcs11-tool --test --login` as self-test without external components?

Yes, here is the output:

```console
bin/pkcs11-tool --test --login
Using slot 0 with a present token (0x0)
Logging in to "profil standardowy (User Pin)".
WARNING: user PIN locked
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_DATA_LEN_RANGE (0x21)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (Open Source Developer, Vladimir Panteleev) 
error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

**Comment by frankmorgner** [comment]
Then it's confirmed that it's a limitation inside OpenSC, that's reproducable with `pkcs11-tool`, thank you.

We already have a lot of tested code for starcos, so I assume there isn't a lot of things to be done, but unfortunately, I cannot give you a timeline when someone (@rumpelsepp?) has the opportunity to look deeper into the issues of your card.

Maybe, you may want to have a look at the source code yourself, by, for example, comparing the smart card communication with the vendor provided module...

**Comment by andrewlukoshko** [comment]
As a workaround it's possible to use module from proCertumCardManager software that Certum provides.
```
# pkcs11-tool -L --module /opt/proCertumCardManager/sc30pkcs11-3.0.5.60-MS.so 
Available slots:
Slot 0 (0x1): ACS ACR101 ICC Reader 00 00
  token label        : profil standardowy
  token manufacturer : Unizeto Technologies SA
  token model        : cryptoCertum 3.2
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 3.3
  firmware version   : 3.3
  serial num         : XXXXXXXXXXXXXXXXXX
  pin min/max        : 4/8
```

**Comment by CyberShadow** [comment]
It seems that as of May 24, the 3.2 cards are no longer usable:
https://www.support.certum.eu/en/technical-news/code-signing-and-intruduction-of-new-key-lenght/
So, the practical merit described in the issue description no longer applies for supporting this particular card.

**Comment by dengert** [comment]
OpenSC has support for 3.5 cards, but not with 3072 or 4096 bit keys. Does anyone  have the new card? 
The changes needed may by as simple as add the ATR and the 3072 and 4096 key sizes {and check that any buffers are large enough} to https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-starcos.c#L330

**Comment by fdelapena** [comment]
I've acquired a 3.5 card:

```
[fdelapena@fedora ~]$ pkcs11-tool -L --module /usr/lib64/libcrypto3PKCS.so
Available slots:
Slot 0 (0x1): ACS ACR101 ICC Reader 00 00
  token label        : profil standardowy
  token manufacturer : Certum common profile v.1
  token model        : cryptoCertum 3.5
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 3.3
  firmware version   : 3.3
  serial num         : XXXXXXXXXXXXXXXX
  pin min/max        : 4/32
```

As expected, with stable 0.22 returns token not recognized:

```
[fdelapena@fedora ~]$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): ACS ACR101 ICC Reader 00 00
  (token not recognized)
```

The ATR matches the currently listed in the in the pcsc database:

```
Possibly identified card (using /home/fdelapena/.cache/smartcard_list.txt):
3B DD 96 FF 81 31 FE 45 80 59 5F 53 74 64 5F 49 6E 69 74 81 05 9B
	Karta kryptograficzna cryptoCertum 3.5 (PKI)
	https://www.certum.pl/pl/karty-do-czytnikow/
```

I could try the suggested patch later and see if that works.

**Comment by dengert** [comment]
Can you run `OPENSC_DEBUG=7 pkcs11-tool -L` to produce debug output and send output.

**Comment by fdelapena** [comment]
[output.log](https://github.com/OpenSC/OpenSC/files/7034507/output.log)

Here's with 0.22.0 from Fedora downstream.

**Comment by dengert** [comment]
The ATR in the original post was: 3b:9f:96:81:b1:fe:45:1f:07:00:64:05:1e:b2:00:31:b0:73:96:21:db:05:90:00:5c
https://smartcard-atr.apdu.fr/parse?ATR=3b%3A9f%3A96%3A81%3Ab1%3Afe%3A45%3A1f%3A07%3A00%3A64%3A05%3A1e%3Ab2%3A00%3A31%3Ab0%3A73%3A96%3A21%3Adb%3A05%3A90%3A00%3A5c
says it is:
SignTrust (www.signtrust.de)
Infinion SLE66CX680PE with Starcos 3.2
http://www.deutschepost.de/dpag?xmlFile=link1015459_49595

@fdelapena, your card is different:
Karta kryptograficzna cryptoCertum 3.5 (PKI)
https://www.certum.pl/pl/karty-do-czytnikow/

It is not clear what type of card this is. The vendor's pkcs11 modules are different too.

One thing you can do is try and force the use of a driver.
`opensc-tool -D` will list the drivers.

You can then try and force the use of a driver with most OpenSC tools for example try this:
`OPENSC_DRIVER=starcos  pkcs11-tool -L`

**Comment by fdelapena** [comment]
Yes, the new card is different, they use the same card reader and just mount a different SIM-sized (2FF) card inside, the old one won't work for certificate reissuing because the 3.2 version does not support 3072/4096 key sizes as @CyberShadow pointed.

Explained at https://shop.certum.eu/open-source-code-signing.html and links to https://shop.certum.eu/cryptographic-card-cryptocertum-3-5.html where it says it has an Infineon M7820 A11 chip and the OS is Starcos 3.5.

Tried the `OPENSC_DRIVER=starcos  pkcs11-tool -L` also with all other drivers, it does not get recognized by any.

I could try building a patched OpenSC for testing.

Because the card reader is supported by pcscd and works without issues with the proprietary module, I could provide APDU logs if that helps (and if allowed).

**Comment by larskanis** [comment]
I successfully use Certum Open Source Signing Certificate since 2018 for the [RubyInstaller](https://rubyinstaller.org/) project on Linux. It makes use of the OpenSSL engine implementation of OpenSC and the PKCS#11 library provided by Certum. The process is documented [here](https://github.com/oneclick/rubyinstaller2/wiki/CertumCodeSigning). Maybe this is helpful for someone.

**Comment by CyberShadow** [comment]
@larskanis Can you use that process to sign Windows executables? I believe Microsoft may have more stringent standards towards current signatures, so hardware issued by Certum in 2018 might no longer be suitable for that purpose (the one I got in 2021 was no longer suitable in 2022, so I switched to "Code Signing").

**Comment by larskanis** [comment]
@CyberShadow In 2021 I had to buy a new smart card with the 3.5 chip due to the changed requirements for the RSA key size. But this didn't change the process, I just had to update their PKCS#11 library file.

**Comment by larskanis** [comment]
@CyberShadow In 2021 I had to buy a new smart card with the 3.5 chip due to the changed requirements for the RSA key size. But this didn't change the process, I just had to update their PKCS#11 library file.
