### ISSUE TITLE
Show warning about secrets being stored in the debug log

### ISSUE THREAD

**Issue by szszszsz** [OpenSC/OpenSC#2014]
### Problem Description
As a user I would like to get a visible warning about my secrets being printed/stored in the debug log.

Instead of mentioning it on every ticket, where the user is asked to provide logs, it could be written just after the command execution, when the log level was increased. What's more, writing it is prone to human error, and it sometimes could be forgotten, thus revealing the user secrets.
Ideally instead all sensitive data would be masked, including the APDU trace - would this be possible?

I have made a brief search in the tickets, and not found any related. Linking recent mention to user about secrets being shown in the log: https://github.com/OpenSC/OpenSC/issues/1916#issuecomment-579721140

Source: [Nitrokey Support Forum](https://support.nitrokey.com/t/key-generation-with-nitrokey-start-on-debian-buster-fails-rsa4096/2339/7?u=szszszsz)

### Proposed Resolution
Print warning at the start and end of the execution of the OpenSC features with an increased debug level. To discuss, whether this should be standard output or error output, or both.

### Steps to reproduce
Run any tool with `OPENSC_DEBUG=9`, which involves passing secrets.

### Logs

None.

cc @Nitrokey

**Comment by Jakuje** [comment]
This a good idea.

Grepping through the code a bit, there is already `SC_LOG_DEBUG_PIN` log level (8), which is logging the PIN commands. If you set OPENSC_DEBUG=7, the PIN should be excluded.

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/sec.c#L204

This was actually introduced quite recently  in d06f23e8 by @frankmorgner who probably had similar idea. It works fine for me but as I heard about this feature for the first time today, I am always suggesting value 9 (rather more than less):
```
$ OPENSC_DEBUG=7 ./src/tools/pkcs11-tool -O --pin 111111 --module ./src/pkcs11/.libs/opensc-pkcs11.so 2>&1 | grep 111111
$ OPENSC_DEBUG=8 ./src/tools/pkcs11-tool -O --pin 111111 --module ./src/pkcs11/.libs/opensc-pkcs11.so 2>&1 | grep 111111
00 20 00 81 06 31 31 31 31 31 31 . ...111111
```
Showing the warning if log level > DEBUG_PIN would be also good idea. Pull requests welcomed.

**Comment by mouse07410** [comment]
How about making `DEBUG_LEVEL=9` log everything *except* did the PIN, and make another level 10 that would include the PIN too?

**Comment by dengert** [comment]
PIN is already at the top. 
```
	SC_LOG_DEBUG_VERBOSE_TOOL = 1,	/* tools only: verbose */
	SC_LOG_DEBUG_VERBOSE,		/* helps users */
	SC_LOG_DEBUG_NORMAL,		/* helps developers */
	SC_LOG_DEBUG_RFU1,		/* RFU */
	SC_LOG_DEBUG_SM,		/* secure messaging */
	SC_LOG_DEBUG_ASN1,		/* asn1.c */
	SC_LOG_DEBUG_MATCH,		/* card matching */
	SC_LOG_DEBUG_PIN,		/* PIN commands */
```

How about debug not just a level, but a level plus and some flags. SM, ASN1, MATCH and PIN which be the flags. 4 bits for level, 4 or more bits for the flags. something like:
```
--- a/src/libopensc/log.c
+++ b/src/libopensc/log.c
@@ -85,6 +85,8 @@ static void sc_do_log_va(sc_context_t *ctx, int level, const char *file, int lin
 
        if (!ctx || ctx->debug < level)
                return;
+       if (level > 16 && (ctx->debug & level) == 0)
+               return;
 
 #ifdef _WIN32
```
If trying to debug a PIN problem, do you really need the ASN1 and MATCH output?

User might also consider strings in certificates as sensitive. So parsing any strings in ASN1 might be considered sensitive too.  In  #1987, some users were obfuscating the labels in the Token info too as they might show a company name.  If 2 chars in a row replace with  XX in hex dump, and no character part.

**Comment by frankmorgner** [comment]
First of all, please consider that this kind of issue wasen't fixed for decades in OpenSC until just recently I've tied it to the most detailed log level. Second, there is other stuff that may not be wanted in a debug log, for example certificates with personal data or secret keys from SM or even hashes from signed documents. I think it's very difficult to handle this complexity, not only from a developer's but also from a user's point of view.

If you have a good solution to this complexity problem, please let me know. If not, I think we should keep it simple and complete the documentation about the possible issues when creating a debug log. We should extend the wiki and man pages and the developer information in `log.h`. It might also be helpful to have a GUI tool for users, which allows editing and explaining each configuration option...
