### ISSUE TITLE
No PIV option in Chromium/FireFox

### ISSUE THREAD

**Issue by kjelderg** [OpenSC/OpenSC#2016]
### Problem Description

When I visit the military OWA which now requires the PIV for authentication, I only see the other 2 certificates stored on the CAC.

Based on #1811 , it seems that perhaps PIV has worked on CACs with this library.  [https://militarycac.com/linux.htm](https://militarycac.com/linux.htm) also indicates that this should work.

I have the same behaviour in both Chromium and Firefox on both a Raspberry Pi (both stock build and a custom-compiled to ensure that zlib support was enabled) and Ubuntu.

### Proposed Resolution
N/A

### Steps to reproduce
1) Insert CAC into reader.
2) Visit https://web.mail.mil
3) Observe that the PIV is not an option in the dialogue.

### Logs

https://gist.github.com/kjelderg/723e37800f815e3e9a497b0906cc7f58

**Comment by dengert** [comment]
You have a dual PIV and CAC. OpenSC 0.19.0 had a problem with these if the card did not support the PIV Discovery Object, and you card does not, so it failed.

This was fixed in OpenSC 0.20.0. e13c0b83ef9dddb7294c10be37367071b69209f4 Can you try OpenSC 0.20.0?

**Comment by kjelderg** [comment]
Brilliant.

0.20.0 works to present the PIV in both raspbian (buster with the package pulled in from bullseye) and ubuntu (Focal).  On raspbian (but not Ubuntu) I had to modutil -delete and -add the opensc-pkcs11.so.

Interestingly, only my PIV and Email certificate are presented as options on either platform.  For me this is desirable, but it was unexpected.

**Comment by dengert** [comment]
OpenSC can only handle one applet on a card at a time. PIV applet or CAC applet. (They actually share some of the files.) If you wanted to use the CAC applet, you can use the environment variable OPENSC_DRIVER=cac or modify the opensc.conf file, to force one driver, or change driver list. First driver to match  the card is selected.
