### ISSUE TITLE
Support for Feitian ePass2003 on Ubuntu 18.04

### ISSUE THREAD

**Issue by johughes99** [OpenSC/OpenSC#2018]
I have just obtained a Feitian ePass2003 token and I'm trying to test out its PKCS#11 support on Ubuntu 18.04. I cant get it to work,

Im using OpenSC 20.0 and its not clear from the WIki whether this token is supported and the driver code has been subsumed into this version. The link to www.gooze.eu is broken - and Goose seems to no longer exist.

opensc-tool does "see" the token. For instance:

` opensc-tool --info
OpenSC 0.20.0 [gcc  8.4.0]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

opensc-tool --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Feitian ePass2003 00 00
`

However, the problem lies in the PKCS#11 interface.  The opensc-pkcs11.so loads fine (as expected) and the call to C_Initialize also works fine,  But subsequent calls fail with CKR_TOKEN_NOT_RECOGNIZED.  e,g

`ERROR: Expected 0 (CKR_OK) from C_GetTokenInfo, received rv = e1 (CKR_TOKEN_NOT_RECOGNIZED)
`
This sort of implies that a driver needs to be installed. If so where do I get it from?

**Comment by johughes99** [comment]
Decided to turn on OpenSC logging.  I went through the log and the output below seems to be the most telling where it cant find a particular file.

I also noticed that similar issues have been raised  last year and @FeitianSmartcardReader  has been involved in resolving the issues



P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card.c:523:sc_unlock: called
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:1008:epass2003_sm_free_wrapped_apdu: called
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:975:epass2003_sm_unwrap_apdu: called
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:192:epass2003_check_sw: File not found
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:996:epass2003_sm_unwrap_apdu: unwrapped APDU: resplen 0, SW 6A82
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:997:epass2003_sm_unwrap_apdu: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:1029:epass2003_sm_free_wrapped_apdu: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] sm.c:173:sc_sm_single_transmit: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card.c:523:sc_unlock: called
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:192:epass2003_check_sw: File not found
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] iso7816.c:571:iso7816_select_file: returning with: -1201 (File not found)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card-epass2003.c:1419:epass2003_select_aid: APDU transmit failed: -1201 (File not found)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card.c:839:sc_select_file: 'SELECT' error: -1201 (File not found)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] pkcs15-syn.c:153:sc_pkcs15_bind_synthetic: trying esteid2018
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] pkcs15-syn.c:162:sc_pkcs15_bind_synthetic: searching for 'emulate foo { ... }' blocks
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] pkcs15-syn.c:164:sc_pkcs15_bind_synthetic: Blocks: 0x55ef7ae1fd40
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] pkcs15-syn.c:187:sc_pkcs15_bind_synthetic: returning with: -1413 (Unsupported card)
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] card.c:523:sc_unlock: called
P:2893; T:0x139916791367488 10:54:32.467 [opensc-pkcs11] reader-pcsc.c:709:pcsc_unlock: called
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] pkcs15.c:1286:sc_pkcs15_bind: returning with: -1413 (Unsupported card)
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] framework-pkcs15.c:326:pkcs15_bind: sc_pkcs15_bind failed: -1413
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: -1413 (Unsupported card)
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] slot.c:331:card_detect: Feitian ePass2003 00 00: cannot bind 'generic' token: rv 0xE1
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] misc.c:71:sc_to_cryptoki_error_common: libopensc return value: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.469 [opensc-pkcs11] card.c:414:sc_disconnect_card: called
P:2893; T:0x139916791367488 10:54:32.471 [opensc-pkcs11] reader-pcsc.c:642:pcsc_disconnect: Feitian ePass2003 00 00:SCardDisconnect returned: 0x00000000
P:2893; T:0x139916791367488 10:54:32.471 [opensc-pkcs11] card.c:436:sc_disconnect_card: returning with: 0 (Success)
P:2893; T:0x139916791367488 10:54:32.471 [opensc-pkcs11] pkcs11-session.c:97:C_OpenSession: C_OpenSession() = CKR_TOKEN_NOT_RECOGNIZED

**Comment by dengert** [comment]
I dug out my old ePass2003 and running  from master (with cardos mods) `pkcs11-tool --test --login` works as expected. 
You partial dump does not show what it is looking for. It just shows `sc_select_file` failed, but does not show where in the `card-epass2003.c` it called `sc_select_file`. 

Start with line showing `sc_connect_card: trying driver 'epass2003'` or  `epass2003_init: called`

It may be the card is not initialized. With the card from 2011 there was a CD which says:
"GOOZE unofficial documentation is a documentation written by GOOZE. 
This documentation is not endorsed nor reviewed by Feitian."

TheOpenSC source  `card-epass2003.c` has copyrights:
 4  * Copyright (C) 2008, Weitao Sun <weitao@ftsafe.com>
 5  * Copyright (C) 2011, Xiaoshuo Wu <xiaoshuo@ftsafe.com>
and ftsafe.com is still in business with much newer devices.

**Comment by johughes99** [comment]
Here is the extract from the log  file.  Seems to indicate it does recognize the card as a Feitian ePass2003.

I bought the token from a UK reseller - but didn't come with any s/w.  I thought the epass2003 was still a current product - and indeed only got its FIPS rating in 2018.

The error occurs on the call to `C_GetTokenInfo.`  In most "normal" PKCS#11 tokens you should be able to get a valid response from this call - even if you not issued a `C_InitToken` call.  

I tried `pkcs11-tool --test --login` and again got a CKR_TOKEN_NOT_PRESENT.

I noticed on the OpenSC wiki mention about GOOZE - but that organization no longer seems to exist


P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:341:sc_connect_card: trying driver 'epass2003'
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card-epass2003.c:1143:epass2003_match_card: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:1147:match_atr_table: ATR     : 3b:9f:95:81:31:fe:9f:00:66:46:53:05:33:02:25:71:df:00:00:00:00:00:17
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:1158:match_atr_table: ATR try : 3B:9F:95:81:31:FE:9F:00:66:46:53:05:10:00:11:71:df:00:00:00:6a:82:5e
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:1165:match_atr_table: ATR mask: FF:FF:FF:FF:FF:00:FF:FF:FF:FF:FF:FF:00:00:00:ff:00:ff:ff:00:00:00:00
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:355:sc_connect_card: matched: epass2003
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card-epass2003.c:1161:epass2003_init: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card-epass2003.c:1113:get_data: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:473:sc_lock: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] reader-pcsc.c:657:pcsc_lock: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:CA, P1:1, P2:86, data(0) (nil)
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] reader-pcsc.c:297:pcsc_transmit: reader 'Feitian ePass2003 00 00'
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] reader-pcsc.c:298:pcsc_transmit: 
Outgoing APDU (5 bytes):
00 CA 01 86 00 .....
P:5502; T:0x140175750899520 14:39:58.700 [opensc-pkcs11] reader-pcsc.c:216:pcsc_internal_transmit: called
P:5502; T:0x140175750899520 14:39:58.709 [opensc-pkcs11] reader-pcsc.c:307:pcsc_transmit: 
Incoming APDU (34 bytes):
80 01 01 81 02 01 D5 82 01 03 83 02 00 00 84 01 ................
01 85 0A 00 10 24 AF 55 EC 00 06 00 11 86 01 00 .....$.U........
90 00

**Comment by FeitianSmartcardReader** [comment]
@johughes99 let me forward our engineer take a look, will back to you tomorrow, thanks

**Comment by FeitianPKIToken** [comment]
@johughes99 
The original file system of ePass2003 is not compatible with PKCS15, need to initialize first, please try with below commands:
1. pkcs15-init -E 
2. pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 12345678 --puk entersafe (of course you could set your own pin and puk)

**Comment by johughes99** [comment]
Absolutely brilliant - that sorted it.  Now I can start testing the device.

**Comment by johughes99** [comment]
@FeitianPKIToken  - if I have any issues with the PKCS#11 interface - how should I raise them. Through Github - or some other means?

**Comment by FeitianPKIToken** [comment]
@johughes99 
Besides through github, you can also send email to me directly, leon@ftsafe.com.

**Comment by johughes99** [comment]
many thanks
