### ISSUE TITLE
onepin-opensc-pkcs11 slows down TLS handhake

### ISSUE THREAD

**Issue by yuzvir** [OpenSC/OpenSC#2019]
I have a problem with Firefox, OpenSC smartcard framework 0.20 and connected AKS ifdh [eToken 5110 SC] on my PC with Manjaro Linux. Sometimes it slows down TLS connection really bad and I have to unload onepin module. I don't need this module in firefox at all, but it reappears every time after reboot. Is it possible to disable it?

**Comment by dengert** [comment]
Don't know about Manjaro Linux, but look at /usr/lib/firefox/browser/defaults/preferences or /etc/firefox and see if there is a pkcs11.txt file which may have been set by an admin, or some install script. 

Normally ~/.mozilla/firefox/*.default has the user profile and a pkcs11.txt which is the info for "Security Devices"  
and would have a lines like:
```
library=/opt/ossl-1.1/lib/opensc-pkcs11.so
name=OpenSC - ossl-1.1
```
When I unload OpenSC,. the lines are removed. Check the permissions, maybe you can not write it.

**Comment by frankmorgner** [comment]
We can't do anything about Firefox's logic to check for client certificates. You could try to improve the performance by using `use_file_caching = true;` in `opensc.conf`.

If asyncrouneous and abortable I/O is what you're looking at, this would be a useful feature. I'd happy to review a pull request on this.

A different approach would be to sandbox PKCS#11 module itself (*and* making it abortable at the same time) with https://github.com/google/sandboxed-api, for example. However, this would be something to implement in Firefox itself or PKCS#11 wrappers such as https://github.com/p11-glue/p11-kit...

**Comment by frankmorgner** [comment]
There has been an improvement in pcscd to speed up connections, see https://ludovicrousseau.blogspot.com/2020/05/your-pcsc-application-200-faster.html

**Comment by yuzvir** [comment]
Seems like I don't have any problems with it after update.
