### ISSUE TITLE
openpgp: pkcs11-tool --keypairgen ec keys not working

### ISSUE THREAD

**Issue by alex-nitrokey** [OpenSC/OpenSC#2020]
### Problem Description

While generating ecc keys works with pkcs15-init on OpenPGP Card based cards, pkcs11-tool does not, e.g.

```
pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:nistp256 --id 03
```
in comparison to
```
pkcs15-init --verify --auth-id 3 --pin 12345678 --delete-objects privkey,pubkey --id 1 --generate-key ec/nistp256
```

### Proposed Resolution
Fix whatever stops pkcs11-tool to work here. Honestly, I did not had the time to look into it yet, but wanted to have the problem noted here, to not forget to look into it. If somebody already spots the problem, fine :)

### Steps to reproduce
Try above pkcs11-tool command with a OpenPGP Card v3.3 device (e.g. Nitrokey Pro 2 or Nitrokey Storage 2). OpenSC 0.20 on ArchLinux

### Logs
[logs](https://gist.github.com/alex-nitrokey/55bc2abf748c5891993fab5bf72a4531)

**Comment by szszszsz** [comment]
Potentially similar: https://github.com/OpenSC/OpenSC/pull/1960 https://github.com/OpenSC/OpenSC/issues/1982
Perhaps one of the unmerged solutions would work?

**Comment by dengert** [comment]
"nistp256" is not listed in `pkcs11-tool.c`  `ec_curve_info`  but other names for the curve are:
```
 94         {"prime256v1",   "1.2.840.10045.3.1.7", "06082A8648CE3D030107", 256},
  95         {"secp256r1",    "1.2.840.10045.3.1.7", "06082A8648CE3D030107", 256},
  96         {"ansiX9p256r1", "1.2.840.10045.3.1.7", "06082A8648CE3D030107", 256},
```
You could also use          --key-type   EC:1.2.840.10045.3.1.7

**Comment by alex-nitrokey** [comment]
This is not working for me (opensc master and opensc 0.20.0). It keeps stating that it is not supported:

```
$ pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:1.2.840.10045.3.1.7 --id 03
Using slot 0 with a present token (0x0)
error: Generate EC key mechanism not supported

Aborting.
$ pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:prime256v1 --id 03         
Using slot 0 with a present token (0x0)
error: Generate EC key mechanism not supported

Aborting.
```

**Comment by Jakuje** [comment]
I have only Nitrokey start (now loaded with eddsa keys). This sounds like there are missing mechanisms provided by the driver. What is the output of `pkcs11-tool -M`?

**Comment by szszszsz** [comment]
Indeed, it looks like mechanism are not listed. What's more, Nitrokey Pro and Storage devices use the same OpenPGP card version, but have different output from `pkcs11-tool -M`.
Logs attached.
- [opensc-2020-pkcs11-m-nitrokey-pro-2.log](https://github.com/OpenSC/OpenSC/files/4657864/opensc-2020-pkcs11-m-nitrokey-pro-2.log)
- [opensc-2020-pkcs11-m-nitrokey-pro-and-storage-1.log](https://github.com/OpenSC/OpenSC/files/4657891/opensc-2020-pkcs11-m-nitrokey-pro-and-storage-1.log)

**Comment by Jakuje** [comment]
From your logs I see the Pro2 uses version OpenPGP 3.3, while the others use 2.1. Or do I miss something?

Certainly it looks like the missing mechanisms is a bug. The logs and outputs are from 0.20.0? Can you try with master or #1960 ?

**Comment by szszszsz** [comment]
Hi! Sorry for the delay.
1. That's right. The smart cards were upgraded in the next hardware release (Nitrokey Pro 2, Nitrokey Storage 2) to OpenPGP v3.3. 
2. Correct, the logs are from the stock OpenSC v0.20. Will check with #1960 again.

**Comment by szszszsz** [comment]
Retest done with: [0.20.0-332-ge6e70d67](https://github.com/OpenSC/OpenSC/pull/1960/commits/e6e70d67717dabdad86e20c8fe05be793102f071) (current tip of #1960). Supported mechanisms show up, but the `CKR_FUNCTION_NOT_SUPPORTED` error is still present on the actual key generation call unfortunately. Full log: [opensc1960-full.txt](https://github.com/OpenSC/OpenSC/files/4740474/opensc1960-full.txt)

**Comment by Jakuje** [comment]
The first error looks like coming from here:

> P:6253; T:0x140172670891840 14:55:45.895 [opensc-pkcs11] pkcs15-lib.c:1481:sc_pkcs15init_generate_key: Non unique ID of the private key
 object: -1505 (Non unique object ID)

The other log does no list the mechanisms again. It could be that the current version derives mechanisms from existing objects and after factory reset, no keys are present and therefore no (keygen) mechanisms are enabled. That is indeed wrong as keygen mechanisms should not depend on key objects. Let me check.

**Comment by Jakuje** [comment]
@szszszsz it is this condition that makes it working inside of pkcs15-init, but not from pkcs11 module:

https://github.com/OpenSC/OpenSC/blob/1bb2547abca12f3ce22d48c3c171ea5e44ab4c4a/src/libopensc/card-openpgp.c#L487

It was introduced by @alex-nitrokey in b572b383 so maybe he will be able to comment on some logic behind this.

**Comment by alex-nitrokey** [comment]
Oh dear, now I remember -- more or less. I think I was asked by @frankmorgner to add this to limit the function to pkcs15-init indeed, as other tools would not work otherwise (regarding the past state of OpenSC and ECC). I couldn't find the old discussion and that is all I remember for now...

Good catch! Well then, @szszszsz will test without this line of code, let's see how it is working.

**Comment by alex-nitrokey** [comment]
Ah, okay, I found it:
https://github.com/OpenSC/OpenSC/pull/1442#issuecomment-415530380

The problem here is that OpenPGP Cards are not able to actually list all supported algorithms, so what we are doing is to deduce the most likely algorithms supported by the card's specification. If one is not actually working the card will just fail gracefully. @frankmorgner asked to add this make sure that this is not breaking anything. Maybe he can let us know if he still thinks we should keep this in.

**Comment by jans23** [comment]
> The problem here is that OpenPGP Cards are not able to actually list all supported algorithms

BTW, this should not be the case anymore with OpenPGP Card 3.4.

**Comment by Jakuje** [comment]
What is the status of this issue? From what I see the current behavior is intentional and there is no better way to do that for OpenPGP <3.4 so I am closing the issue.

**Comment by rickflowexe** [comment]
It is not solved:

~$ pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:nistp256 --id 03
Using slot 1 with a present token (0x4)
error: Unknown EC key params 'nistp256'
Aborting.

System Ubuntu
opensc Version: 0.20.0-3

**Comment by dengert** [comment]
Have you tried: `pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:prime256v1 --id 03`

An EC curve is defined by its OID. For various reasons the curve may have multiple curve names as curve names were added late in EC development. 

The curve you are looking for is defined here: http://oid-info.com/get/1.2.840.10045.3.1.7   it says:  "also known as National Institute of Standards and Technology (NIST) P-256". 

pkcs11-tool 0.20.0 and 0.22.0 map the `--key-type EC:...` to an OID using this table: https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L103-L142 as the OID is passed in pkcs11 calls.  These mapping of curve name to OID are based on various standards documents.  
Do you know of a standards document that refers to `nistp256` as a curve name?

The error message is from: https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L2885-L2886

**Comment by Jakuje** [comment]
> It is not solved:
> 
> ~$ pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:nistp256 --id 03 Using slot 1 with a present token (0x4) error: Unknown EC key params 'nistp256' Aborting.

With the code mentioned in the comment https://github.com/OpenSC/OpenSC/issues/2020#issuecomment-640623861 it can not even work. Please read, both of you through the comments above.

**Comment by Niklap97** [comment]
> Have you tried: `pkcs11-tool -l --login-type so --so-pin 12345678 --keypairgen --key-type EC:prime256v1 --id 03`

Unfortunately, that doesn't work either.
```
Using slot 0 with a present token (0x0)
error: Generate EC key mechanism not supported

Aborting.
```

**Comment by Jakuje** [comment]
I am not saying this is solved and it works with pkcs11-tool, but it works only with pkcs15-init, because there were some concerns against its usage from pkcs11-tool, which are described in https://github.com/OpenSC/OpenSC/pull/1442#issuecomment-415530380

If you can come up with better solution or find a good reasoning why the code limiting the potentially non-supported mechanisms is not an issue and remove the condition, it should start working out of the box. I think it might be possible to create the mechanism list only with the "keygen" attribute or something to avoid/minimize pollution.
