### ISSUE TITLE
Creating keys on OpenPGP smartcard v3.3 creates no objects

### ISSUE THREAD

**Issue by vmotion0x** [OpenSC/OpenSC#2022]
### Problem Description

I'm trying to generate keys on my OpenPGP v3.3 smartcard, but after the operation, which ends generally without errors, there are no keys on the smartcard.

Whatever the tool being used to generate the key (openpgp-tool, pkcs15-init or pkcs11-init) the result is the same.

For instance, I run:

```
pkcs15-init -G rsa/2048 --id 3 --auth-id 3 --verify-pin
```

But after the command, no objects are available on the smartcard:
```
c:\>pkcs11-tool -O -l
Using slot 0 with a present token (0x0)
Logging in to "OpenPGP card (User PIN)".
Please enter User PIN:
```
Or with:
```
c:\>pkcs15-tool -C --verify-pin
Using reader with a card: ACS ACR38U 0
Please enter PIN [User PIN]:

```

To be noted that importing an object (for example a certificate) from a file works a charm, and then I get all the objects listed.
I'm using the latest nightly: OpenSC-0.20.0-5-ga422ec5d, rev: a422ec5d, commit-time: 2020-05-02 11:03:46 +0200

I've tried to on an older version, and there it works perfectly (OpenSC-0.19.0, rev: f1691fc9, commit-time: 2018-09-13 13:47:21 +0200), after running `pkcs15-init` the card contains the correct objects:

```
c:\>pkcs11-tool -O -l
Using slot 0 with a present token (0x0)
Logging in to "User PIN (OpenPGP card)".
Please enter User PIN: Private Key Object; RSA
  label:      Authentication key
  ID:         03
  Usage:      decrypt, sign, non-repudiation, unwrap
Public Key Object; RSA 2048 bits
  label:      Authentication key
  ID:         03
  Usage:      encrypt, verify, wrap
```

### Proposed Resolution
No idea, I'm just a user.
### Steps to reproduce

Liked mentionned in the description:
```
pkcs15-init -G rsa/2048 --id 3 --auth-id 3 --verify-pin
pkcs15-tool -C --verify-pin
```
### Logs

Log of key creation: https://gist.github.com/vmotion0x/e18b78da167bd51b7a91e3ca3bdaad78
Log of object listing: https://gist.github.com/vmotion0x/cbfbdf285280243b0850476463647c9f
(pkcs15-tool -C --verify-pin)

**Comment by Jakuje** [comment]
It would be helpful to generate logs of key generation also from the old version, which worked for you for comparison. Recently, there were many changes to the opengpg driver and test coverage is still not ideal.

**Comment by Jakuje** [comment]
As there was no answer for more than two years, closing.
