### ISSUE TITLE
javacard simulation CI target broken

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#2028]
### Problem Description

Recently, all builds using javacard simulation fail to run PivApplet. I started investigating what is going on and it turns out (after unrolling the raw log in travis), that the build of PivApplet fails since some changes in upstream repository
```
BUILD FAILED
/home/travis/build/Jakuje/OpenSC/PivApplet/build.xml:66: Compile failed; see the compiler error output for details.
```
Investigating further, it looks like also the build of `yubico-piv-tool` fails later:
```
ykcs11.c:1838:5: error: â€˜forâ€™ loop initial declarations are only allowed in C99 mode
     for (CK_ULONG j = 0; j < ulCount; j++) {
     ^
make[2]: *** [ykcs11.lo] Error 1
make[2]: Leaving directory `/home/travis/build/Jakuje/OpenSC/yubico-piv-tool/ykcs11'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/Jakuje/OpenSC/yubico-piv-tool/ykcs11'
make: *** [install-recursive] Error 1
travis_time:end:2ae5cfef:start=1588869529247751602,finish=1588869598104316046,duration=68856564444,event=before_script
```
But both of these failures are ignored and we see only the failure of the jcardsim to start the applet.

The javacard simulation runs on oldes Ubuntu (14.04) -- the rest was already migrated to bionic (18.04). I did not update last time, because the jcardsim was not able to build with anything newer. There are some commits in https://github.com/arekinath/jcardsim which allow me to build it on my Fedora, but it still fails on Ubuntu for unknown reasons.

I put together few commits in the way to address this issue, but can not continue fiddling with that right now so if somebody would like to continue, feel free to do so:

https://github.com/Jakuje/OpenSC/commits/travis-kill

For others, this is a note that the javacard tests are broken now and its not your code that broke it :)

**Comment by Jakuje** [comment]
For the record, now I got up to the place where ecdsa keygen fails with the above branch:
```
++yubico-piv-tool -v 9999 -r 'Virtual PCD 00 00' -P 123456 -s 9a -a generate -A ECCP256
Connect reader 'Virtual PCD 00 00' matching 'Virtual PCD 00 00'.
00098606 APDU: 00 A4 04 00 05 A0 00 00 03 08 
00044676 SW: 61 3A 4F 0B A0 00 00 03 08 00 00 10 00 01 00 79 0D 4F 0B A0 00 00 03 08 00 00 10 00 01 00 50 09 50 69 76 41 70 70 6C 65 74 AC 11 80 01 03 80 01 06 80 01 07 80 01 11 80 01 14 06 00 90 00 
00002305 APDU: 00 20 00 80 00 
00042180 SW: 63 C5 
00000105 APDU: 00 FD 00 00 00 
00043761 SW: 05 03 00 90 00 
00000108 APDU: 00 F8 00 00 00 
00043890 SW: D1 37 3E 8B 90 00 
Authenticating since action 'generate' needs that.
00008874 APDU: 00 87 03 9B 04 7C 02 80 00 
00044088 SW: 7C 0A 80 08 C1 53 8C D4 FE CB DB 59 90 00 
00001447 APDU: 00 87 03 9B 16 7C 14 80 08 5B 16 A0 8C 7A 0C 5F 15 81 08 9E 25 45 B3 CB 51 6D 0C 
00042474 SW: 7C 0A 82 08 39 0B D4 35 3D 04 F6 B9 90 00 
Successful application authentication.
Now processing for action 'generate'.
00004926 APDU: 00 47 00 9A 05 AC 03 80 01 11 
00098615 SW: 7F 49 81 43 86 41 04 CD 11 CE 63 E3 31 D1 96 B0 F0 DC C6 00 2A 1E F1 38 A9 7F ED 27 4D 35 58 74 4F 8F 85 C7 A8 0D D6 FF 04 94 73 AC 95 AB 43 75 06 C0 EB D4 A5 8C F0 8D 14 86 97 53 60 9E 98 E4 69 BF 36 3A 77 8A BA 90 00 
Failed to parse public key structure.
Key generation failed.
Disconnect card #3510058635.
```
This is broken since the following commit in PivApplet: https://github.com/arekinath/PivApplet/commit/6a0a79865cda88969557cc7d1ae73842e5561220

Playing a bit around with that locally to see what is the actual difference of the keygen results pre and post this commit.

**Comment by dengert** [comment]
Return info looks like BER, not DER
NIST 800-73-3 part 2 Table 10. Data Objects in the Template (Tag '7F49')
Public key data objects for ECDSA Point '86'

```
7F 49 81 43 86 41 04 CD 11 CE 63 E3 31 D1 96 B0 F0 DC C6 00 2A 1E F1 38 A9 7F ED 27 4D 35 58 74 4F 8F 85 C7 A8 0D D6 FF 04 94 73 AC 95 AB 43 75 06 C0 EB D4 A5 8C F0 8D 14 86 97 53 60 9E 98 E4 69 BF 36 3A 77 8A BA 90 00
```
A real PIV card returns to  opensc piv-tool:   
```
7F 49 43 86 41 04 71 07 58 6F 1C 89 45 76 5B 4C 7C 52 C7 32 40 63 1E 81 3D DA ED 79 6F 43 E8 17 
55 91 20 CF 6D 9A 9C 99 7E 44 ED FB 2E E7 17 91 3C CC 45 47 A2 5A 46 6F 17 48 4C 3C C5 AD E5 56B1 03 E9 9E 22 23 90 00     
```
The difference is the third byte, 81. This may be valid BER, but not DER, and not what the Yubico-piv-tool is expecting. 

I suspect the applet was expecting to return an RSA key, and added the 81 which is the tag for modulus, which also happens to be a TLV way of saying there is one length byte so 8143 is the same as 43.

**Comment by Jakuje** [comment]
@dengert thanks for digging into that. I set up everything to reproduce the issue locally to figure out the current master of PivApplet works fine. Let me check if I can now make the CI in OpenSC working again.
