### ISSUE TITLE
Identive uTrust Token Pro Mini getting Unsupported card

### ISSUE THREAD

**Issue by sanaullah82** [OpenSC/OpenSC#2031]
Hi,

I have some new tokens model "Identive uTrust Token Pro Mini", trying to initialize the token using OpenSC 0.20.0, I am getting Unsupport Card error but the token is detected as Identive SCT3522CC.

opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Identive SCT3522CC token
opensc-tool --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Identive SCT3522CC token

opensc-tool --reader 0 --atr
3b:f8:96:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:32

 opensc-tool --reader 0 --name
Unsupported card

opensc-explorer
OpenSC Explorer version 0.20.0
Using reader with a card: Identive SCT3522CC token
unable to select MF: Incorrect parameters in APDU

pkcs15-init --create-pkcs15
Using reader with a card: Identive SCT3522CC token
Failed to connect to card: Card is invalid or cannot be handled

 pcsctest 

MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange 
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: Identive SCT3522CC token
Enter the reader number          : 01
Waiting for card insertion         
                                 : Command successful.
Testing SCardConnect             : Command successful.
Testing SCardStatus              : Command successful.
Current Reader Name              : Identive SCT3522CC token
Current Reader State             : 0x54
Current Reader Protocol          : 0x1
Current Reader ATR Size          : 18 (0x12)
Current Reader ATR Value         : 3B F8 96 00 00 81 31 FE 45 4A 43 4F 50 76 32 34 31 32 
Testing SCardDisconnect          : Command successful.
Testing SCardReleaseContext      : Command successful.
Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange 
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: Identive SCT3522CC token
Enter the reader number          : 

is this card supported by opensc? or i am missing something to configure before initialize the token

**Comment by frankmorgner** [comment]
The ATR of your card indicates that it's either not fully personalized or that it contains a java card applet unknown to OpenSC

**Comment by ridicolos** [comment]
@sanaullah82 did you ever figure out on how to use that smartcard?

**Comment by sanaullah82** [comment]
No, i couldnt figure out as these cards are not personalized.
