### ISSUE TITLE
ePass2003 : Client authentication using web broser

### ISSUE THREAD

**Issue by mitz-20** [OpenSC/OpenSC#2038]
### Client Authentication using web browser

I have bought epass2003Auto e token to implement two factor authentication in my office. I was able to generate RSA 2048 Private Key and CSR in php using following command

// Save your private key, CSR and self-signed cert for later use
openssl_csr_export($csr, $csrout);// and var_dump($csrout);
openssl_x509_export($x509, $certout);// and var_dump($certout);
openssl_pkey_export($privkey, $pkeyout, "1234");// and var_dump($pkeyout);

I was able to load x509 Certificate using epass2003 driver into my token.

Now my isssue is how to access certificate by client using browers. Is there any javascript API to read public and private key from token for authentication purpose at client end.

Any help will be grateful.

Thanks

Mitz
![owncert](https://user-images.githubusercontent.com/60191479/82585265-5c681e00-9bb3-11ea-8a0d-dc4db4ddedf8.png)

**Comment by Jakuje** [comment]
There is no standardized javascript API that could access smart cards and certificates (there are some browser extensions though, but they are not very stable).

In browsers, certificates in smart cards are usually used for TLS client authentication, which is happening one layer below your PHP/Javascript application, but the outcome of this authentication should be visible in some environmnent variables.

**Comment by mitz-20** [comment]
Hi Jakuje,

Thanks for the reply, Will certainly look for environment variables for TLS. However, that may not give me private key from hardware token which is required for authentication. Can you please suggest client end api for accessing token and its credentials. I had seen PKCS#11 standard, but could not get hold of working example.  

> There is no standardized javascript API that could access smart cards and certificates (there are some browser extensions though, but they are not very stable).
> 
> In browsers, certificates in smart cards are usually used for TLS client authentication, which is happening one layer below your PHP/Javascript application, but the outcome of this authentication should be visible in some environmnent variables.

**Comment by Jakuje** [comment]
Yes, the PKCS#11 module from OpenSC can be used in browsers to do TLS client authentication. But the API is used by browser so it is nothing you would need to care about (just make sure that the opensc pkcs11 module is loaded in Security -> Security devices in Firefox (or other browser) preferences).

**Comment by dengert** [comment]
@mitz-20  You said :"that may not give me private key from hardware token". The point of a smart card is the private key can not be read from the card. The card can use the private key to sign, encrypt, decrypt or derive normally after entering a PIN. That is what PKCS11 allows one to do. OpenSSL engine can use PKCS11, and on MacOS and Windows there
are vendor and OpenSC alternatives to PKCS11.

**Comment by frankmorgner** [comment]
@mitz-20 please describe your use case, what do you want to do?

**Comment by mitz-20** [comment]
@frankmorgner,
 

I am trying to establish PKI based web messaging system in my office i.e client will access application through web browser. I have procured ePass2003 Auto tokens and install self signed certificate inside token. Since Java Applets are not supported by browser. I am stuck up in how to use private key inside my token for encryption purpose in my messaging application. Through ePass2003 Drivers(C Files), i have seen that encryption and decryption is supported by token. However, the same needs to be done through web interface at client end. Hence, i was looking for some web interface(Javascript API) to interact with ePass2003 Auto token and use crypto functions for my messaging application.

**Breakthrough Achieved**  I have install PKCS11(.so) Shared objects as module in firefox addon and now i can see my self signed certificates in browser (view certificate).

**Issue**: However the method of using private key for encryption is still not resolved.

Thanks for taking interest.

Mitz

**Comment by frankmorgner** [comment]
With 0.20.0 this kind of configuration should happen automatically for Firefox on Windows and mac (and even for native browsers)...

Encryption will not be possible in this Setup, only X.509 Client Authentication. There are some non-standardized solutions to achieve this in the browser, but there's none available from the OpenSC project...

If you want to use OpenSC for encryption, your best bet would be using a native application using one of the standardized APIs (PKCS#11, CNG, CryptoTokenKit, ...)

**Comment by suryareddy-2000** [comment]
for me also have the same purpose i need to communicate with epass2003auto  from my webapplication through extension.

**Comment by metsma** [comment]
You might be interested of this project https://web-eid.eu/
