### ISSUE TITLE
New issue 22766 by ClusterFuzz-External: opensc:fuzz_pkcs15_reader: Direct-leak in cardos_init

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2046]
### Problem Description
New issue 22766 by ClusterFuzz-External: opensc:fuzz_pkcs15_reader: Direct-leak in cardos_init
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22766

Detailed Report: https://oss-fuzz.com/testcase?key=5171166682808320

Project: opensc
Fuzzing Engine: libFuzzer
Fuzz Target: fuzz_pkcs15_reader
Job Type: libfuzzer_asan_opensc
Platform Id: linux

Crash Type: Direct-leak
Crash Address: 
Crash State:
  cardos_init
  sc_connect_card
  fuzz_pkcs15_reader.c
  
Sanitizer: address (ASAN)

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_opensc&range=202005090305:202005100513

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5171166682808320

### Proposed Resolution (untested) 
```
diff --git a/src/libopensc/card-cardos.c b/src/libopensc/card-cardos.c
index 4ef6ead0..b1bcf42d 100644
--- a/src/libopensc/card-cardos.c
+++ b/src/libopensc/card-cardos.c
@@ -385,7 +385,7 @@ static int cardos_finish(sc_card_t *card)
 {
        int r = 0;
 
-       if (card)
+       if (card == NULL)
                return 0;
 
        SC_FUNC_CALLED(card->ctx, SC_LOG_DEBUG_VERBOSE);
```

**Comment by frankmorgner** [comment]
Done in 38474739b30cec84232e54921f967aed94e23f5d
