### ISSUE TITLE
How to create debug-file on Windows?

### ISSUE THREAD

**Issue by Niklas-Nitrokey** [OpenSC/OpenSC#2058]
Hello, I am using OpenSC version 0.20.0 on Windows 10 and fail to create a debug file. 
I followed [these instructions](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC), set the debug settings in opensc.conf, verified the registry entries, and set the environment variables (knowing they shouldn't be required for Windows). I use opensc-pkcs11.dll with two 3rd party applications and successfully unlocked the smart card. Still no debug file and no PKCS#11 Spy log file are created.

Are the instructions up to date or am I'm missing something?

**Comment by dengert** [comment]
There are  Program Files and a Program Files (x86)  versions of OpenSC, You may need to opensc.conf in both. 
There are also  HKEY_LOCAL_MACHINE\SOFTWARE\OpenSC Project and HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\OpenSC Project registry entries

**Comment by dengert** [comment]
And the directory must be writeable by the current user. This is important if you are testing login as there is no current user and parts of login run under LSA.

**Comment by Niklas-Nitrokey** [comment]
Setting opensc.conf in both versions solved my problem.
Thank you.
