### ISSUE TITLE
pkcs11-register not recognizing symbolic links

### ISSUE THREAD

**Issue by henning-schild** [OpenSC/OpenSC#2060]
### Problem Description

I observed the problem on a Linux machine that already has opensc modules in my various `pkcs11.txt`. The helper does not detect that and writes to the file without using `modutil` - the _only_ allowed tool to mess with that stuff.

Multiple issues occur. First i get the module entered twice. Second newlines are missing so the file is corrupted and `modutil` can not find/remove entries anymore.

The helper does not seem to know that there are conflicts between modules.  `onepin-opensc-pkcs11.so` vs ` opensc-pkcs11.so` vs. `p11-kit-proxy.so`

### Proposed Resolution

The tool should make use of `modutil` instead of writing to those files itself. It should not overwrite previously existing entries if unsure. It should know about conflicting modules ... Or it should just stay away from those files!

### Steps to reproduce

Just one example here.

`.pki/nssdb/pkcs11.txt` before
```
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:/home/henning/.pki/nssdb' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription='' 
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

library=/usr/lib64/pkcs11/p11-kit-trust.so
name=my-p11-kit-trust.so
NSS=trustOrder=100    

library=/usr/lib64/pkcs11/onepin-opensc-pkcs11.so
name=my-onepin-opensc-pkcs11.so

```
after `pkcs11-register`

```
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:/home/henning/.pki/nssdb' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription='' 
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

library=/usr/lib64/pkcs11/p11-kit-trust.so
name=my-p11-kit-trust.so
NSS=trustOrder=100    

library=/usr/lib64/pkcs11/onepin-opensc-pkcs11.so
name=my-onepin-opensc-pkcs11.so

library=/usr/lib64/onepin-opensc-pkcs11.so
name=OpenSC smartcard framework (0.20)

```

Now i have this twice, in this case the symlink was not detected (which `modutil` would have done ... in a weird way ... but still)

```
henning@md1za8fc ~/data/las $ modutil -dbdir sql:/home/henning/.pki/nssdb/ -add foo -libfile /usr/lib64/onepin-opensc-pkcs11.so 

WARNING: Performing this operation while the browser is running could cause
corruption of your security databases. If the browser is currently running,
you should exit browser before continuing this operation. Type 
'q <enter>' to abort, or <enter> to continue: 

ERROR: Failed to add module "foo". Probable cause : "Unknown code ___P 3".
henning@md1za8fc ~/data/las $ modutil -dbdir sql:/home/henning/.pki/nssdb/ -add foo-link -libfile /usr/lib64/onepin-opensc-pkcs11.so 

WARNING: Performing this operation while the browser is running could cause
corruption of your security databases. If the browser is currently running,
you should exit browser before continuing this operation. Type 
'q <enter>' to abort, or <enter> to continue: 

ERROR: Failed to add module "foo-link". Probable cause : "Unknown PKCS #11 error.".
```

**Comment by henning-schild** [comment]
I guess the helper should at least detect the symlink case and know about `p11-kit-proxy.so` as a competing library. Otherwise it is a huge improvement to enable the lib by default. Using `modutil` would be safer ... but if you are sure you get it right ... no need to do so.

**Comment by henning-schild** [comment]
I do have a shell implementation for adding nss libs on Linux using `modutil`. That can probably be shared or contributed.

**Comment by frankmorgner** [comment]
Unfortunately, Firefox (and the like) doesn't come with modutil included on Windows or macOS. And even on Linux we can't be sure to have it installed. I think there's not way around bringing this functionality with OpenSC as standalone application. Unfortunately NSS doesn't bring it in a way we can include it in OpenSC, that's why I've decided to implement this myself.

Also, I didn't find a "formal" or informal specification. How did you get to know about the format?

As far as I can tell, we are adding all the newlines necessary:
https://github.com/OpenSC/OpenSC/blob/223a0949e88612eb8e441031e62206aaff7e7b48/src/tools/pkcs11-register.c#L144-L147

Regarding two "competing" installations of OpenSC in different locations, I'd like to reject your request, because this combination doesn't really make sense. When called without arguments (i.e. with the default values), we are already making sure that we don't add the onepin module where the normal module is already present (note that we're using the absolute path!). If the user specifies a module, then we don't try to be sophisticated and just add the specified module. I think this is the most sane behavior, do you agree?

I've thought about p11kit as well and I think there is no easy way of detecting whether p11kit announces OpenSC already. If some system uses p11kit, then calling `pkcs11-register` on login is of little use, because p11kit already handles the configuration process. If so, OpenSC should be configured with `--disable-autostart-items` to avoid this problem. Do you have a suggestion where we could make the documentation clearer in this regard? What distribution are you experiencing this problem on? You should file a bug there so that the OpenSC configuration options are chosen correctly.

**Comment by henning-schild** [comment]
> Regarding two "competing" installations of OpenSC in different locations, I'd like to reject your request, because this combination doesn't really make sense. When called without arguments (i.e. with the default values), we are already making sure that we don't add the onepin module where the normal module is already present (note that we're using the absolute path!). If the user specifies a module, then we don't try to be sophisticated and just add the specified module. I think this is the most sane behavior, do you agree?

Right it does not make sense whatsoever, still the tool will create a second entry (without args) because it does not detect the symlink and that the module is already in my config ... entered another way though ...

My distro is gentoo, which has the "autostart" enabled i guess ... Having a distro disable a feature because its buggy ... is that what you suggest? Note that the entries in my pkcs11 config have nothing to do with my disto, they are just entries that happened to appear with me calling modutil or manually going the GUI way ...

I know that i mentioned several issues, let us focus on the symlink! When you match whether an entry exists you should in reality not match its path but the "readlink" of it. Maybe even think about hardlinks.

If the config looks remotely like it contains opensc related entries, the tool should warn and not do anything.

I do not know where the spaces error came from, but you are writing to a file that you are not allowed to. `modutil` is very explicit that the browsers must not be running, i doubt you check that and might get into a race with two writers changing the same file at a time.

**Comment by henning-schild** [comment]
> Unfortunately, Firefox (and the like) doesn't come with modutil included on Windows or macOS. And even on Linux we can't be sure to have it installed. I think there's not way around bringing this functionality with OpenSC as standalone application. Unfortunately NSS doesn't bring it in a way we can include it in OpenSC, that's why I've decided to implement this myself.

Sound like a feature that simply can not be implemented then ... Write good documentation and a linux tool that uses modutil when available. Maintainers will include it as optional runtime dep.

> Also, I didn't find a "formal" or informal specification. How did you get to know about the format?

There is none, you are supposed to use the tool ...

**Comment by frankmorgner** [comment]
@Jakuje, do you know about the autoconfiguration status with p11kit in the linux distros?

**Comment by Jakuje** [comment]
I don't think it is widely adopted. We did it in Fedora and RHEL, but I do not have any information how it is handled in other distributions.

**Comment by frankmorgner** [comment]
Maybe we could add a seperate switch for adding pkcs11-register to the autostart objects. It should still be enabled by default, but the help message can be made clear about its relation to p11kit...

@henning-schild can you reproduce the syntax problem you had?

**Comment by henning-schild** [comment]
> @henning-schild can you reproduce the syntax problem you had?

I do not know how i got there and am too lazy to try it. You are probably just asking so you can keep doing it without the tool, which i do not want to support.

**Comment by frankmorgner** [comment]
I'm sorry, but your favourite solution is not viable on most systems. I won't build this kind of exception.

If there is no syntax problem, then the only thing left to do is a refinement of the documentation and maybe a seperate autostart switch for pkcs11-register...

**Comment by henning-schild** [comment]
You are forgetting about the symlink ... which is the only thing i would want you to take away from this.

**Comment by henning-schild** [comment]
Let us make this issue just about the symlink, i will open more issues if i ever see those other problems again. The syntax error i can probably not reproduce, so let us forget it. The offending p11kit proxy, forget it as well.

**Comment by frankmorgner** [comment]
I see, thanks for the reminder

**Comment by henning-schild** [comment]
ping

**Comment by henning-schild** [comment]
I guess we could also drop the autostart and acknowledge that the tool is not in a shape where it can run non-interactive and unconditional without breaking peoples configs.

**Comment by dengert** [comment]
Modutil is in Ubuntu, and has been since 16.04.  It is  part of libnss-tools package and on 20.04 is version:    2.3.49.1-1ubuntu1.5

Don't know if this is still valid: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests
It talks about FireFox 64 and above, and latest FireFox in 82. But is a way to install PKCS11 if OpenSC installed a JSON file on MacOS, Linux or Windows. Looks like user has to install an extension to use the JSON file.

**Comment by henning-schild** [comment]
I guess the tool could detect that "modutil" is installed and try to use it when available. For Linux one could simply add it as an optional runtime dependency.

But even if "modutil" was used, the tool is very invasive and can break peoples configuration. And will keep doing that on every single xdg-autostart. My conclusion is that the tool for sure is very handy and having it do "the right thing" automatically would be really nice, but it is impossible to know what "the right thing" is.

There are offending plugins, "p11kit proxy" just being one OSS example. In my company some people use a proprietary plugin to use their smartcard in some applications, while still potentially having opensc installed, maybe for other applications.

The tool can never know "the right thing" (offending plugins, symlinks, no-config for certain apps), and it currently does not use "the right way" (modutil). It should be included but must not ever run automatically, not once ... not automatically on every single login.

Do Windows and MacOS have an autostart? If not having it in Linux is an inconsistency that needs to be dealt with anyways. And i bet on the other platforms offending proprietary plugins will also be an issue.

**Comment by frankmorgner** [comment]
1. xdg-autostart is the right place to put it. there are a variety of tools to configure startup icons which enable users to simply untick unwanted (disabled) tools. This is possible for admins as well as for users.
2. If this feature conflicts with your distribution's way of handling PKCS#11, please file a bug there so that they ship their opensc without auto-configuration (i.e. disabled at compile time)
3. If the people in your company are requiring a certain configuration, you may want to distribute a package handcrafted for your purposes.

As we've already ruled out most of your objections, all that's left is the lack of recognizing a symbolic link.

**Comment by henning-schild** [comment]
We have not rules out anything, we have downplayed to divide and conquer. The symlink is just a nice example where opensc breaks its own legacy configs where we do not have to talk about other packages.
Not being able to package it to coexist nicely is not something that you can just push to distributions and organizations, see "p11kit proxy", or "no pkcs11" for some browsers as examples that break.

I am still convinced that the tool it incredibly useful yet incredibly broken at the same time, and xdg-autostart is the wrong place to put it. (opensc-notify should go there!)

**Comment by henning-schild** [comment]
I think it could be a good idea to change the title back and derive an issue just for the symlink ... which i am not even sure is automake or the way same distros work ... so who cares

**Comment by henning-schild** [comment]
i am absolutely willing to help and send patches, i.e. one to use "modutil" on Linux (maybe where available or unconditionally)

**Comment by henning-schild** [comment]
> If the people in your company are requiring a certain configuration, you may want to distribute a package handcrafted for your purposes.

Good solutions are always best implemented upstream. I do not care about my org too much, i want to help improve an excellent piece of OSS. And i want to help distros to bring it to users in a working shape ... probably 99.9% of your Linux users ...

**Comment by henning-schild** [comment]
> I don't think it is widely adopted. We did it in Fedora and RHEL, but I do not have any information how it is handled in other distributions.

@Jakuje you do not https://src.fedoraproject.org/rpms/opensc/c/7cf6069f073b27264b6c43439b84a197e7985e48?branch=master "--disable-autostart-items"

**Comment by henning-schild** [comment]
@LunaSquee

**Comment by frankmorgner** [comment]
pkcs11-register is in autostart since 0.20.0. Most users I am confronted with, are happy with the autoconfiguration in its current state. I'm open to improve it, e.g. by using modutil, but currently I don't see a convincing argument going back to disabling it by default.

**Comment by henning-schild** [comment]
mind checking how many big distros already are on 0.20, especially the "enterprise" ones that cater to many smartcard users?

Let us wait for them to find "--disable-autostart-items" and wrap their heads around the issues they get without, maybe they will come here as well eventually.

**Comment by Jakuje** [comment]
> > I don't think it is widely adopted. We did it in Fedora and RHEL, but I do not have any information how it is handled in other distributions.
> 
> @Jakuje you do not https://src.fedoraproject.org/rpms/opensc/c/7cf6069f073b27264b6c43439b84a197e7985e48?branch=master "--disable-autostart-items"

This was answer to the question about p11-kit autoconfig:

> @Jakuje, do you know about the autoconfiguration status with p11kit in the linux distros?

I am following this change from the beginning, but as we use different way of configuring pkcs11 modules through p11-kit, it was an obvious solution to disable this conflicting mechanism.

I discussed recently the reliability of reading and writing `pkcs11.txt` by hand and it should be reliable in newer systems or databases in `sql:` format. But there are still legacy DBs (`dbm:`, still default for example in RHEL7), which store this information inside of `secmod.db`, a binary file that can be read and modified (reliably) only with `modutil`. For this reason, I would recommend using `modutil` when possible, but as I do not have any use case where I would use this, I have no strong opinions.

**Comment by henning-schild** [comment]
@Jakuje ok i misunderstood, maybe because of the past-tense ... Thanks for the clarification.

Can you go into detail on that other way, maybe a link to a manual and code?

**Comment by Jakuje** [comment]
No problem. The official page of this change is here:

https://fedoraproject.org/wiki/Changes/NSSLoadP11KitModules

It is done by registering opensc in the p11-kit (as part of opensc packge):

```
$ cat /usr/share/p11-kit/modules/opensc.module
# [..comments...]
module: opensc-pkcs11.so
```

and a small configuration file in nss package:

```
$ cat /etc/crypto-policies/local.d/nss-p11-kit.config
name=p11-kit-proxy
library=p11-kit-proxy.so
```

There is no other magic, as far as I know.

**Comment by henning-schild** [comment]
This is simply great! So opensc could opt for `/etc/crypto-policies/local.d/opensc.config`. Will work directly after package install, not only after re-login. And will be done once.

Last time i looked into browser configuration with a snippet based ".d"-folder there was not sane way, so i did not even dream about that good mainline solution.

**Comment by frankmorgner** [comment]
feel free to add support for modutil/p11-kit detection, that would be a useful improvement.

**Comment by Jakuje** [comment]
> feel free to add support for modutil/p11-kit detection, that would be a useful improvement.

I did not see it as a common way of doing that so I am not sure how much value would it provide.

In any case, if the `pkcs11-register` would switch to modutil to check/modify the db (the only "supported" way of modifying/querying nss db), it is pretty trivial to do something like this:
```
modutil -list -dbdir sql:$NSSDB | grep 'library name: p11-kit-proxy.so'
if [ "$?" = "1" ]; then
    modutil -force -add 'OpenSC PKCS #11 module' -dbdir sql:$NSSDB -libfile $P11LIB"
fi
```
taken from one of the [test script](https://src.fedoraproject.org/rpms/opensc/blob/master/f/tests/pkcs11-tool/runtest.sh#_113) in here when installing SoftHSM into NSS DB



You can not do this without modultil and only with grepping and modifying `pkcs11.txt` file.
