### ISSUE TITLE
Potential unhandled race condition in pcsc_detect_readers

### ISSUE THREAD

**Issue by misterzed88** [OpenSC/OpenSC#2078]
### Problem Description

The reader list is retrieved with multiple calls to SCardListReaders:
1. Get the list size
2. Allocate memory
3. Get the list data

There is a potential race condition if a reader is added after (1) but before (3), which results in a buffer too small error in (3).

### Proposed Resolution

A simple solution would be to read the list in a single call by using SCARD_AUTOCALLOCATE for the size. This is supported on Windows and in pcsc-lite on Linux, but I am not sure about OS X support (the latest Apple PCSC framework does not seem to have this option).

**Comment by Jakuje** [comment]
I am wondering how large the data can be, but I assume just couple of bytes. If I remember pcsc-lite has some upper limit how many readers it can handle, defined in some constant at build time (`PCSCLITE_MAX_READERS_CONTEXTS` is 16 by default, but available in `pcsclite.h`). Having always allocated that many should allow us avoiding this rain dance completely.

**Comment by misterzed88** [comment]
Since the buffer is for reader names, I assume that a solution with a static maximum size is not flexible enough, since we can not expect a limited number of installed readers, especially not on Windows.

Maybe this situation is rare enough and its consequences are not serious enough to warrant any changes in the code (using the maxim "don't fix what's not broken"). I will take a deeper look at what the consequences are if/when this situation happens.

**Comment by dengert** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows/win32/limitation-10-smart-card-readers
says a MAX of 10 readers on Windows 8 and above. Note last update is 03/16/2020

**Comment by misterzed88** [comment]
@dengert: Thanks for the clarification.

After doing a bit more analysis and testing of the code I would say that it's not worth the effort and risk to do anything about this potential issue.

Motivations:
- The potential race condition is estimated to be very rare (maybe even close to non-existant in practice).
- If it happens it only results in a temporary failure to locate the readers. They will be found when doing a new attempt (for PKCS #11, when doing a new call to C_GetSlotList).
- To the user, for example through an application like Firefox, this results in a rare (non-existant?), intermittent error, which is easily remediated by trying again.
- There are no security implications of this potential problem.
