### ISSUE TITLE
Commit c4d7bb1 does not do what it claims to do

### ISSUE THREAD

**Issue by marschap** [OpenSC/OpenSC#2081]
Hi,

commit https://github.com/OpenSC/OpenSC/commit/c4d7bb1a7ba80d155021f7a311b7fa6b1ce54e15 does not do what it claims to do.

It embraces a `LOG_TEST_RET()` with an `if` clause that triggers on a condition which `LOG_TEST_RET()` ignores:
* `LOG_TEST_RET()` only exits a function if its parameter `r` is lower than zero.
* trying to call it with the OR-ed condition `obj.data == NULL` will not cause `LOG_TEST_RET()` to do anything as long as `r >= 0`.

### Proposed Resolution

If the function should be exited at that point based on the condition `obj.data == NULL`, the correct way to do it, is to set `r` to a negative value **before** the call to `LOG_TEST_RET()`, e.g. by 
`if (obj.date == NULL)
      r = SC_ERROR_OBJECT_NOT_FOUND;`

**Comment by Jakuje** [comment]
Thank you for the review. Your suggestion sounds good to me. Please, submit a PR.

**Comment by Jakuje** [comment]
oh, I see it is already in #2082. Sorry for the noise.

**Comment by Jakuje** [comment]
Fixed by #2082.
