### ISSUE TITLE
ePass FIDO-NFC -  Failed to erase card

### ISSUE THREAD

**Issue by KRunchPL** [OpenSC/OpenSC#2084]
### Steps to reproduce

1. Insert key (with CCID enabled and initialized according to https://www.rcdevs.com/docs/howtos/epass/epass/)
2. Run pkcs15-init -E

### Expected behavior

Key is erased

### Actual behavior

Failed to erase card: Not supported

### Logs
```
> pkcs15-init -E -v
Using reader with a card: FT CCID 0
Connecting to card in reader FT CCID 0...
Using card driver GIDS Smart Card.
About to erase card.
Failed to erase card: Not supported
```

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by frankmorgner** [comment]
maybe related to #2085 

@FeitianSmartcardReader ?

**Comment by frankmorgner** [comment]
please contact the vendor
