### ISSUE TITLE
ePass FIDO-NFC - cannot delete key

### ISSUE THREAD

**Issue by KRunchPL** [OpenSC/OpenSC#2085]
It seems that after deletion of a private key, the key file is deleted, but it's "metadata" is still there, when trying to read it's public key error `Public key enumeration failed: Reference data not usable` is shown.

### Steps to reproduce

1. Insert key (with CCID enabled and initialized according to https://www.rcdevs.com/docs/howtos/epass/epass/)
1. Run `pkcs15-init  --verify-pin --auth-id 80 --generate-key rsa/2048 --key-usage sign,decrypt --label "TESTKEY"`
1. Run `pkcs15-tool.exe --list-key` to get ID of created key
1. Run `pkcs15-init.exe -D privkey --verify-pin --auth-id 80 --id 1` (with ID get in prev step)
1. Run `pkcs15-tool.exe --list-key`

### Expected behavior

Key TESTKEY is not on the list

### Actual behavior

Key TESTKEY is still on the list. It's pub key cannot be read anymore with `pkcs15-tool.exe --read-public-key 00`.

### Logs

[Logs](https://gist.githubusercontent.com/KRunchPL/d9f70e948237c00cd5049396f313580c/raw/62986467f793f4adb3a6fb0c782ad1c9b5d64942/epass-fido-pkcs15.log)

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by FeitianSmartcardReader** [comment]
@KRunchPL I forward your message to martin@ftsafe.com, he is right person for our FIDO product, he will send you mail later today, any questions, send mail to him.

@frankmorgner looks the token doesn't load GIDS applet, so it cannot be use with OpenSC, our engineer will keep in touch with Jacek Chałupka and give a solution, thanks for your reminder.

**Comment by frankmorgner** [comment]
any update?

**Comment by FeitianSmartcardReader** [comment]
Thanks Frank 

Engineer will starting working on this in the next few days, will keep update, thanks

**Comment by superskybird** [comment]
ePass FIDO-NFC has optional feature of GIDs, but this feature was not proposed. Now ePass FIDO-NFC has removed this feature and adding FIDO2 feature . So please ignore GIDs now.
