### ISSUE TITLE
pkcs11-register incorrectly handles profiles with spaces in their path

### ISSUE THREAD

**Issue by jaakristioja** [OpenSC/OpenSC#2087]
### Problem Description

Firefox profiles with spaces in their paths are not updated.

### Proposed Resolution

Fix broken `sscanf` logic in `get_next_profile_path()` ([src/tools/pkcs11-register.c:110](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-register.c#L110)).

On first sight there seem to be other bugs in the profile parser as well, hence I'd recommend implementing a better INI parser. For example, all the `strstr()` logic will probably break in case any other `key=value` contain the searched strings:
```
[Profile33]
Name=Path=IsRelative=1
IsRelative=0
Path=what ever
```

### Steps to reproduce

1. Create a Firefox profile with spaces in its name (automatically creates profile with space in its name **and path**)
2. Run `pkcs11-register`

### Logs

Excerpt from output of `strace -f -s 90 pkcs11-register`:
```
openat(AT_FDCWD, "/home/user/.mozilla/firefox/profiles.ini", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=1470, ...}) = 0
read(3, "[Profile21]\nName=id kaardi test\nIsRelative=1\nPath=dfx8pav7.id kaardi test\n\n[Profile18]\nNam"..., 4096) = 1470
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/home/user/.mozilla/firefox/dfx8pav7.id/pkcs11.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by frankmorgner** [comment]
when using `%s` for reading the path it reads everything until it hits a whitespace (usually `\n`), so it does *not* recognize paths with spaces. I think this should not be an issue with profiles that are created automatically.

The logic is more complicated if you want to support spaces (using regex?). In the worst case, the opensc module isn't added to a valid profile. Feel free to make a pull request if this bugs you...
