### ISSUE TITLE
Minidriver rejecting exportable flag

### ISSUE THREAD

**Issue by elipsion** [OpenSC/OpenSC#2088]
### Problem Description
Calling key generation from CNG via the minidriver causes the error `NTE_INVALID_PARAMETER` if the export policy isn't `XCN_NCRYPT_ALLOW_EXPORT_NONE`

### Proposed Resolution
Passing the appropriate flags down to card driver. 

### Steps to reproduce
```powershell
PS C:\> $pin = ConvertTo-SecureString -String "hunter2" -AsPlainText -Force
PS C:\failure\> New-SelfSignedCertificate -KeyExportPolicy Exportable -Provider "Microsoft Smart Card Key Storage Provider" -Subject "CN=test" -CertStoreLocation cert:\CurrentUser\My -pin $pin
PS C:\success\> New-SelfSignedCertificate -KeyExportPolicy NonExportable -Provider "Microsoft Smart Card Key Storage Provider" -Subject "CN=test" -CertStoreLocation cert:\CurrentUser\My -pin $pin
```
### Logs
Best results on a SmartCard-HSM. Other applets (IsoApplet, PivApplet) give the same error, but fail because of applet limitations (read-only, unsupported method).
```powershell
New-SelfSignedCertificate : CertEnroll::CX509Enrollment::_CreateRequest: The parameter is incorrect. 0x80090027
(-2146893785 NTE_INVALID_PARAMETER)
At line:1 char:1
+ New-SelfSignedCertificate -Provider "Microsoft Smart Card Key Storage ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SelfSignedCertificate], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand
```

**Comment by dengert** [comment]
Are you saying that you want to generate on the card an exportable key? 
This may not be possible with many (if not all) because it is counter intuitive for a smart card. You can accomplish the same thing by generating the key and certificate in software, then downloading the key to the card. 

What do you mean by: "Best results on a SmartCard-HSM." Does it generate a key and a self signed certificate?

An opensc-debug.log migh show if the problem is with the card, minidriver, CertEnroll or the  New-SelfSignedCertificate.

**Comment by elipsion** [comment]
> Are you saying that you want to generate on the card an exportable key?

The reason for hitting this issue is that I'm dealing with software (MS ADCS) that tries to create a key with this flag set. Sadly this is not configurable. The PowerShell commands are the minimal way I've found for reproducing the error, in leu of trying to install an ADCS CA.

> This may not be possible with many (if not all) because it is counter intuitive for a smart card. You can accomplish the same thing by generating the key and certificate in software, then downloading the key to the card.

This is not the same, in my opinion. Keys can be extracted under wrap (with a KEK), but if they are generated in software and downloaded from a computer I would say there is some risk that the key could be compromised.
In any case, I'd say it's not the job of the minidriver to come to that conclusion, but rather pass the requests along down the chain for the driver or applet to make a decision upon.

> What do you mean by: "Best results on a SmartCard-HSM." Does it generate a key and a self signed certificate?

For the example with `NonExportable` as policy yes, a key and certificate shows up on the card, with a corresponding entry in Windows cert store. The two other applets produce various different errors because of limitations in their respective OpenSC drivers.
All applets I've tried generate the same error when calling `New-SelfSignedCertificate` with `-KeyExportPolicy Exportable`

> An opensc-debug.log migh show if the problem is with the card, minidriver, CertEnroll or the New-SelfSignedCertificate.

`pkcs11-tool` have several flags (`--private`, `--extractable`, and more) regarding key attributes, which are sometimes honoured by the underlying card driver, but the tool does not crash when they are specified. This is why I'm *fairly* certain that the error lies within the minidriver, though I could be wrong.
I have two opensc-debug log files (one working, one failing), if you really want the odd MB of reading.

**Comment by popovec** [comment]
Hi,

Some of the cards do not allows wrap/unwrap  operation for asymmetric key. There is for example operation: wrap generic secret/wrap symmetric key  by symmetric key  or by RSA key but there is no way to wrap (export) private part of asymmetric key. 

Overall, I would like to know which cards supports  wrapping/unwrapping operation at all .. (and what combinations are allowed)

some related issues: #1913 #1522 #1570 #1796

**Comment by elipsion** [comment]
SmartCard-HSM supports this according to the [project wiki](https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM#using-key-backup-and-restore). Access is controlled by enabling the algorithm WRAP (`0x92`) when generating the key.
Ping, @CardContact.

**Comment by dengert** [comment]
You said: "All applets I've tried generate the same error when calling New-SelfSignedCertificate with -KeyExportPolicy Exportable". That sounds like the New-SelfSignedCertificate may be returning the error and not the minidriver. 

Posting the opensc-debug.logs would help resolve were the error is coming from.

**Comment by dengert** [comment]
There is also a [New-SelfSignedCertificateEx](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) version 1.2 

As I recall from previous attempts last year (but not with `-KeyExportPolicy Exportable`) , you may need to use `-Provider "OpenSC CSP"`.  It was also not clear if the X509Enrollment  supported only CSP but not KSP.  This may have changed.

**Comment by elipsion** [comment]
> That sounds like the New-SelfSignedCertificate may be returning the error and not the minidriver.

It seems like we were both wrong; the error is thrown from `Microsoft Smart Card Key Storage Provider`. I've verified this with another card that has both a minidriver and CNG. When using the minidriver the same error is returned, but using the proprietary CNG (or the MS Software KSP) the keys are generated as expected, with whatever export policy.

I'll try to file the issue with Microsoft instead, it seems like an omission on their part, since the [minidriver specification](https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/file-system-requirements#-file-access-conditions) allows for these kinds of permissions.

**Comment by elipsion** [comment]
> As I recall from previous attempts last year (but not with `-KeyExportPolicy Exportable`) , you may need to use `-Provider "OpenSC CSP"`. It was also not clear if the X509Enrollment supported only CSP but not KSP. This may have changed.

The sad thing is that the CSP API only allows for RSA lengths of up to 2048, and no ECC at all. I think it also only has support for SHA-1. Microsoft has some [documentation](https://docs.microsoft.com/en-gb/windows/win32/seccng/cng-features) on the matter.

**Comment by dengert** [comment]
I ran into CSP vs KSP and SHA-1 limitations last year with trying to use TPM on a laptop.

https://docs.microsoft.com/en-us/windows/win32/api/certenroll/ne-certenroll-x509privatekeyexportflags lists the flags that could be passed. 

Minidriver specification 7.07 CardCreateContainer or   CardCreateContainerEx flags are CARD_CREATE_CONTAINER_KEY_GEN or CARD_CREATE_CONTAINER_KEY_IMPORT but I don't see any flags to set export policies.   So that is also a missing piece.
