### ISSUE TITLE
Broken key agreement in CWA 14890-1 of DNIe

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2120]
### Problem Description

The RSA based authentication with key agreement described in [CWA 14890-1](ftp://ftp.cenorm.be/PUBLIC/CWAs/e-Europe/eSign/cwa14890-01-2004-Mar.pdf) is implemented for the DNIe card. The *Asymmetric Key Transport Scheme Based on RSA* [has been analyzed by Ashar Javed](https://link.springer.com/content/pdf/10.1007%2F978-3-642-27257-8_20.pdf). Although the analysis doesn't look very solid from my experience, the point I want to make is a different one: The analysis models the secret keys from either party to be kept secret (surprise!) to conclude that there are no weaknesses. In reality, however, the IFD's secret key is available for the attacker by extracting it from the card's middleware (e.g. from OpenSC or from the official software). This breaks the security of the protocol.

Basically, the protocol is as follows:
1. IFD verifies ICC's certificate and thus trusts its public key PK.ICC.AUT
2. ICC verifies IFD's certificate and thus trusts its public key PK.IFD
Then there is stage 3 and 4:
![image](https://user-images.githubusercontent.com/1266577/94321895-3bfd0580-ff91-11ea-8fbb-f81abb52a932.png)

The session key is computed from the 4 least significant bytes of rnd.icc and the 4 least significant bytes of rnd.ifd. Since the an attacker knows rnd.icc (because he posses the IFD's private key SK.IFD.AUT), the security is soly based on 4 bytes of rnd.ifd. This means that an attacker only needs to brute force the 32 bits of rnd.ifd to derive the correct session key. This is easily feasable. The attacker can read and modify all data between card and terminal.

### Proposed Resolution

Maybe (hopefully) I got something wrong then please correct me. But if not, then someone should contact the authorities to replace the card's protocol with something more secure.

@rickyepoderi

**Comment by rickyepoderi** [comment]
I have just sent an email to the DNIe technical office about this.

**Comment by frankmorgner** [comment]
any response?

**Comment by rickyepoderi** [comment]
nope, no response I am aware of til now.
