### ISSUE TITLE
How to restart OpenSC CTK

### ISSUE THREAD

**Issue by the-docta** [OpenSC/OpenSC#2121]
### Problem Description
Hi,

my setup is a USB (Gemalto PC Twin Reader) based card reader on a Mac Book Pro. Works like a charm - in principle.
But every now and then (once a week, roughly), after replugging the card reader (because I changed location),
the card just "stops working". sometimes pulling/replugging usb helps, sometimes pulling/injecting the card helps.
sometimes it doesn't. When this happens, I need to restart my whole mac. 

when I say, it "stops working", it is not available to other applications like Google Chrome 

running opensc-explorer and verify CHV1 therein still works. 

So I rather think, it is not OpenSC itself, it is something on the integration layer to MacOS (does that make sense?)

### Proposed Resolution

Is there a way I can restart the "OpenSC system" without restarting my Mac? like restarting a deamon or something?
Thanks!

### Logs

I just enabled debugging. Will check logs the next time this happens. Don't think this is relevant for my question "how to restart" -- but if I it helps finding the actual issue, thats fine, too :)

**Comment by frankmorgner** [comment]
How did you install OpenSC?

**Comment by the-docta** [comment]
hmm. too long ago to remember, TBH. either brew or download from git (certainly did both in the past)
Is one of the ways preferred? should I reinstall? 

BTW, creating the opensc.conf file in /etc didnt seem to have any effect. is it expected somewhere else?

**Comment by frankmorgner** [comment]
please answer the following:
- are you using firefox?
- what's the output of `sc_auth identities`
- what's the output of `ps xa |grep -i opensc`
- can you see your smart card in the key chain access app?

**Comment by the-docta** [comment]
I am not using firefox. I use chrome and edge cromium currently. In the system state, where the isue didnt happen yet, there is a message/notification popping into the screen from the right, when I insert the actual card into card reader.
When the issue starts, this notification doesnt appear. I guess its an indication that something happens on "system level"

Output of both commands in the situation where everything is working as expected. Will add another output, when it happens again
```
----------------------------------------------------------------------------------------------------------------------------------------
~ » sc_auth identities
SmartCard: org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken:101050559960
Unpaired identities:
ABC...DEF	Digital Signature (Firstname Lastname ...)
123...456	Non Repudiation (Firstname Lastname ...)
----------------------------------------------------------------------------------------------------------------------------------------
~ » ps xa |grep -i opensc                                                                                  
86592   ??  Ss     0:00.08 /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/OpenSCToken
----------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by frankmorgner** [comment]
To restart OpenSC, you may just kill the CTK process (`kill 86592` in your example). However, on my mac book I've noticed that the reader disappears after sone suspend/resume cycles. This is a problem, which is not related to OpenSC, but to the underlying system components from Apple. In my case, just unplugging and reattaching (my yubikey) fixed the problem. When you're in the messed up state, try `opensc-tool --list-readers -a`, which will not list the reader anymore. You should contact Apple, if this is bugging you.

**Comment by the-docta** [comment]
Hi @frankmorgner, this just happened again. sc_auth identities justreturns with empty result (not a single line of output) and the process is not running. 

"just" trying to start the above process from the above path, tells me about an illegal hardware instruction

```
---------------------------------------------------------------------------------------------------------------------------------------------------------
» /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/OpenSCToken
[1]    67148 illegal hardware instruction  
---------------------------------------------------------------------------------------------------------------------------------------------------------
```

let me know if I can produce additional necessary log/output/whatever.

**Comment by the-docta** [comment]
PS: the opensc-tool still lists the reader
----------------------------------------------------------
~ » opensc-tool --list-readers -a   
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Gemalto PC Twin Reader
Using reader with a card: Gemalto PC Twin Reader
3b:d2:18:00:81:31:fe:58:c9:03:16
----------------------------------------------------------

**Comment by the-docta** [comment]
PPS: interestingly, the card still works with opensc-explorer, so USB and the actual hardware are fine:
```
----------------------------------------------------------------
~ » opensc-explorer      
OpenSC Explorer version 0.20.0
Using reader with a card: Gemalto PC Twin Reader
unable to change lifecycle: Security status not satisfied
OpenSC [3F00]> verify CHV1
Please enter PIN: 
Code correct.
OpenSC [3F00]> 

```

**Comment by the-docta** [comment]
Just did. Did NOT restart the Mac, though. 
```
~ » opensc-tool --version            
OpenSC-0.21.0-rc2, rev: c4a75eb, commit-time: 2020-11-12 11:14:17 +0100
------------------------------------------------------------------------------------------------------------
~ » /Applications/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex/Contents/MacOS/OpenSCToken      
[1]    69296 illegal hardware instruction  
------------------------------------------------------------------------------------------------------------
~ » sc_auth identities                                                                                                                                                   
------------------------------------------------------------------------------------------------------------
~ » ps ax|grep -i opensc                                                                                                                                              
69098   ??  S      0:00.03 /Library/OpenSC/bin/opensc-notify
69324 s002  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i opensc
------------------------------------------------------------------------------------------------------------
~ » opensc-notify --version                                                                                                                                        
opensc-notify 0.21.0-rc2
------------------------------------------------------------------------------------------------------------
~ »    
```
verifying PIN using opensc-explorer still works

**Comment by xtanon** [comment]
Hi,
i have the same card reader (Gemalto) and the exact same behavior. I'm also using the card read with MacOS.
```
➜  ~ opensc-tool --list-readers -a  
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Gemalto PC Twin Reader
Using reader with a card: Gemalto PC Twin Reader
3b:d2:18:00:81:31:fe:58:c9:03:16

➜  ~ opensc-tool --version          
OpenSC-0.20.0-rc2-5-g30c9e55, rev: 30c9e55, commit-time: 2019-10-18 00:41:10 +0200

```

(Just noticed it is really exactly the same reader :D  but I should def. update )

**Comment by the-docta** [comment]
hi @frankmorgner 

is there anything else I could try to narrow down the issue. I further noticed that the card still works fine in "remote" systems used via Citrix, which (presumably) forwards the card reader on USB level - or at least on same level `opensc-explorer` is working, which also works in "broken" state (see above comments)

**Comment by frankmorgner** [comment]
have you tried killing the process `OpenSCToken` and re-inserting the token?

**Comment by the-docta** [comment]
The process `OpenSCToken` is not running in "broken" state. And Trying to start it returns "illegal hardware instruction" message.

What do you mean by "reinserting the token"? re-inserting the Card? I tried that. The Process OpenSCToken is still not running

**Comment by frankmorgner** [comment]
1. remove card from reader or unplug the reader completely
2. `sudo killall OpenSCToken`
3. insert card into reader or plug the reader into your mac

**Comment by the-docta** [comment]
![image](https://user-images.githubusercontent.com/65647431/99973720-593b2e00-2da0-11eb-9249-23387873b70b.png)

the card works in opensc-explorer. It is not visible to browsers. OpenSCToken Process is not running.

The only solution found so far is rebooting MacOS

**Comment by frankmorgner** [comment]
If the issue still exists, please report it to Apple.
