### ISSUE TITLE
Any way to create a CA with 4096/SHA384 ?

### ISSUE THREAD

**Issue by thni1703** [OpenSC/OpenSC#2131]
### Problem Description

Were trying to setup a new CA and was told we could use a Nitrokey HSM 2 to setup the CA with 4095/SHA384-RSA but it seems that it can only Sigh and Verify this.

Any Way to do what we want with what we have?

We are using Opensc 0.19.0

**Comment by Jakuje** [comment]
What CA does it just the Sign, isn't it? 4096 bits should work according to Nitrokey. If not, try with a more current version of OpenSC.

**Comment by thni1703** [comment]
It should be used as encryption as extra security. When making the Root Certificate you can choose it as Encryption - But 4096 only supports SHA1 - since there are nobody here who can really help (it's ok, I don't know either) I'm going to close this.

**Comment by mouse07410** [comment]
One small thing to keep in mind: CA's job is **not** to encrypt/decrypt - but to sign certificates and Certificate Revocation Lists.

**Comment by dengert** [comment]
Looks like NitroKey HSM is using  the OpenSC card-sc-hsm.c driver.  
This says support for RSA 4096. :  `_sc_card_add_rsa_alg(card, 4096, flags, 0);`
But says cards supports on the up to SH256 on the card  `SC_ALGORITHM_ECDSA_HASH_SHA256`

grep'ing for Nitro or nitro in OpenSC finds no match. 

https://shop.nitrokey.com/shop/product/nk-hsm-2-nitrokey-hsm-2-7
Says card supports RSA 4096, 

https://www.nitrokey.com/documentation/applications#p:nitrokey-hsm&a:general

https://github.com/CardContact/sc-hsm-embedded/wiki/PKCS11
Is a little out of date, and does not say 4096 or SHA384. 

A sign operation can be broken into create the digest/hash, and then sign the digest. 
OpenSC can do the digest/hash in software, and then the card does the sign,
or if the card can do both it in, some cases. it will do bot on the card. 

It sounds like you got a CA to sign certificates with 4096 SHA384.  But then you say: " it can only Sigh and Verify." What else do you want the CA to do? 

You said: "It should be used as encryption as extra security. When making the Root Certificate you can choose it as Encryption - But 4096 only supports SHA1."  Encryption is usually done by encrypting with AES key, then hash of 384 is done in software, and finally the AES and HASH are encrypted with public key. Decryption is then done in reverse order decrypt on card if HASH and AES key, the use AES to decrypt in software. 

So it sounds like you want the SHA384 done on the card, and not in software. It looks like OpenSC sc-hsm does not support doing the SHA384 on the card. 


 




I
