### ISSUE TITLE
PIV Yubikey Authentication ECC-Certificate ERROR:pam_pkcs11.c:736 during verify_signature() step

### ISSUE THREAD

**Issue by tobiasjaster** [OpenSC/OpenSC#2136]
### Problem Description
When starting my Yubikeys, I wanted to enable my Linux to use the smart card authentication method via the built-in PIV interface. With an RSA4096-CA certificate and an RSA2048 personal certificate, everything worked wonderfully. Now I wanted to switch to ECC certificates and created a secp256r1 CA certificate and a prime256v1 personal certificate and transferred the personal certificate and key to the yubikey. For the test, I only switched sudo access to PAM (/etc/pam.d/sudo). When executing "sudo -i", the password for the Yubikey was requested as expected.
The following error message appeared during the authentication process:
```
ERROR:pam_pkcs11.c:736: verify_signature() failed: EVP_VerifyFinal() failed: error:0D078079:asn1 encoding routines:asn1_item_embed_d2i:field missing
Fehler 2342: Verifizierung der Signatur fehlgeschlagen.
```
The same error also occurred with a csr created by the Yubikey, which was signed by my CA and whose certificate was then transferred to the Yubikey

### Proposed Resolution
-

### Steps to reproduce
Copy ECC-Key and Certificate onto Yubikey (9a)
Copy CA.crt into /etc/pam_pkcs11/cacerts
pkcs11_make_hash_link inside /etc/pam_pkcs11/cacerts Folder
Add line "auth sufficient pam_pkcs11.so debug" to /etc/pam.d/sudo
(added "max_send_size = 65535; and "max_recv_size = 65536;" to /etc/opensc.conf to avoid possible other failure)
Insert Yubikey
open Terminal and send command "sudo -i"

PS.: I hope I haven't forgotten anything that I changed during my own debug attempts

### Logs
https://gist.github.com/tobiasjaster/207cd318ea973f6c22f627748138aba9

### Component
Using reader with a card: Yubico YubiKey OTP+FIDO+CCID 01 00
Personal Identity Verification Card

### Version Number
OpenSC 0.20.0 [gcc  9.2.1 20200130]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

### Operating System
cat /etc/os-release:
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

lsb_release -a:
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.1.1
Codename:	Mikah

**Comment by dengert** [comment]
Based on this line below from your log, which is the Subject Public Key Info (SPKI) from your certificate, it looks like it is missing the outer sequence, that would then include the ECPointQ as the bit string of length 66 . An openssl asn1parse of a certificate with a EC prime256v1 should look like this (from EC certificate I have on a PIV card):

193:d=2 hl=2 l= 89 cons: SEQUENCE
195:d=3 hl=2 l= 19 cons: SEQUENCE
197:d=4 hl=2 l= 7 prim: OBJECT :id-ecPublicKey
206:d=4 hl=2 l= 8 prim: OBJECT :prime256v1
216:d=3 hl=2 l= 66 prim: BIT STRING

P:37133; T:0x139947654784832 08:17:44.274 [opensc-pkcs11] pkcs15-pubkey.c:1341:sc_pkcs15_pubkey_from_spki_fields: sc_pkcs15_pubkey_from_spki_fields() called: 0x559f6bb4c9e5:89
301306072A8648CE3D020106082A8648 CE3D0301070342000403DEA16224AE5F B0E9E3DBEAB3741EBBFB0DCE7ED751B6
ED700B10AE85003336BAF6FE5B9CC19F BB6CCC7AB7AFDD4E75F12A338A580D98 139D463A3A7396889A

The BIT STRING (03) length 0x42 which looks correct is:
03 42 000403DEA16224AE5F B0E9E3DBEAB3741EBBFB0DCE7ED751B6
ED700B10AE85003336BAF6FE5B9CC19F BB6CCC7AB7AFDD4E75F12A338A580D98 139D463A3A7396889A

I suspect your or certificate was not created correctly by your CA.

You can use something like: ./pkcs15-tool --read-certificate 01 > /tmp/cert01.pem to get the certificate off the card,
then ./openssl asn1parse -i < /tmp/cert01.pem to see the ASN1

I suspect ./openssl x509 -noout -text -in /tmp/cert01.pem will also give you an error.

AN online ASN.1 parser like https://lapo.it/asn1js/ can be used to look at the ASN.1

You can also use OpenSSL verify to verify the certificate chain without having to use the card, which should show the problem as well.

**Comment by tobiasjaster** [comment]
```
  371:d=2  hl=2 l=  89 cons: SEQUENCE          
  373:d=3  hl=2 l=  19 cons: SEQUENCE          
  375:d=4  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
  384:d=4  hl=2 l=   8 prim: OBJECT            :prime256v1
  394:d=3  hl=2 l=  66 prim: BIT STRING        
```
Doesn't it actually correspond exactly to the output you described, right? 
The second command 
```
openssl x509 -noout -text -in /tmp/cert01.pem
```
also gives me the exact content of my certificate.

**Comment by dengert** [comment]
You are right. the _pkcs15_pubkey_from_spki_fields() called: 0x................:89 says length 89. which is the outer sequence. 

But the  you also said:" ERROR:pam_pkcs11.c:736: verify_signature() failed: EVP_VerifyFinal() failed: error:0D078079:asn1 encoding routines:asn1_item_embed_d2i:field missing Fehler 2342: Verifizierung der Signatur fehlgeschlagen."

So what version OpenSSL is pam_pkcs11 using? 
It should be at least 1.1. Older versions have different different ECDSA code the 1.1 and above.
There may also be a mismatch of version used by PAM and used by OpenSC and libp11.  

Can you debug pam_pkcs11 to see why it fails?
What field is missing. 

The OpenSC SPY might help see: https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by tobiasjaster** [comment]
I tried
```
PKCS11SPY=/usr/lib/pkcs11/opensc-pkcs11.so PKCS11SPY_OUTPUT=logfile sudo -i
```
But no logfile was created.

My openssl-Version is 
```
OpenSSL 1.1.1h  22 Sep 2020
```
For pam_pkcs11 I used 0.6.11-1 from AUR

**Comment by dengert** [comment]
Is this your problem?
https://github.com/OpenSC/pam_pkcs11/issues/44

**Comment by tobiasjaster** [comment]
Yes, you are right. I have included the patch in the PKGBUILD file and when I run sudo -i now, the verification works.
