### ISSUE TITLE
How to keygen a generic secret? pkcs11-tool error if using --keygen --key-type secrkey:512 -M GENERIC-SECRET-KEY-GEN

### ISSUE THREAD

**Issue by justincranfordedc** [OpenSC/OpenSC#2139]
### Problem Description

How can I use pkcs11-tool to generate a generic secret for use in HmacSHA256? Running --list-mechanisms on SoftHSM2 v2.5.0 for Windows, I see that PKCS#11 driver supports GENERIC-SECRET-KEY-GEN. However, when I run pkcs11-tool with --keygen --key-type secrkey:512 parameters I get "error: Unknown key type secrkey:512".

I am unclear if this error is a bug or limitation of pkcs11-tool, or if there is something missing from --help documentation.

### Proposed Resolution

The --help output for --key-gen parameter could add extra examples. This is the current output from pkcs11-tool for OpenSC:
- Specify the type and length of the key to create, for example rsa:1024 or EC:prime256v1 or GOSTR3410-2012-256:B

It would be useful to add more common examples like AES:32 and SECRKEY:512.

If bug or limitation related to --keygen of a secrkey, please fix the code.

### Steps to reproduce
From --help I figured out how to generate RSA-3027.
- "C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module C:\SoftHSM2\lib\softhsm2-x64.dll --slot-index 0 --pin 0000 --login --label rsa3072 --keypairgen --key-type rsa:3072 --mechanism RSA-PKCS-KEY-PAIR-GEN
Using slot with index 0 (0x1e94de1b)
Key pair generated:
Private Key Object; RSA
  label:      rsa3072
  Usage:      decrypt, sign, unwrap
  Access:     sensitive, always sensitive, never extractable, local
Public Key Object; RSA 3072 bits
  label:      rsa3072
  Usage:      encrypt, verify, wrap
  Access:     local

There was no AES example for --keygen, but --list-mechanisms shows AES-KEY-GEN with range 16-32 so I guessed aes:32.
- "C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module C:\SoftHSM2\lib\softhsm2-x64.dll --slot-index 0 --pin 0000 --login --label aes256 --keygen --key-type aes:32 --mechanism AES-KEY-GEN
Using slot with index 0 (0x1e94de1b)
Key generated:
Secret Key Object; AES length 32
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      aes256
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     never extractable, local

There was no SECRKEY example for --keygen, but --list-mechanisms shows GENERIC-SECRET-KEY-GEN with length up to 2048 so I guessed secrkey:512. It doesn't work.
- C:\SoftHSM2\bin>"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module C:\SoftHSM2\lib\softhsm2-x64.dll --slot-index 0 --pin 0000 --login --label hmacSha256 --keygen --key-type secrkey:512 --mechanism GENERIC-SECRET-KEY-GEN
**Using slot with index 0 (0x1e94de1b)
error: Unknown key type secrkey:512
Aborting.**

### Logs

I enabled debug logging for --keygen with --key-type secrkey:512, but debug log file is empty.

**Comment by dengert** [comment]
It looks like it would be easy to add support for the GENERIC-SECRET-KEY-GEN in pkcs11-tool.c the  gen_key routine
around line 2642. Something like this:

This compiles, but is untested, I do not have a device that supports the mechanism.
[gen-secret.diff.txt](https://github.com/OpenSC/OpenSC/files/5405718/gen-secret.diff.txt)

If it works you could submit a PR.

**Comment by dengert** [comment]
Oops, 
`key_type = CKK_DES3`; 
should read 
`key_type = CKK_GENERIC_SECRET;`

**Comment by dengert** [comment]
Installed softhsm2 2.5.0-1build1  on Ubuntu 20.04. 
`./pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so --login --label hmacSha256 --keygen --key-type secrkey:512 --mechanism GENERIC-SECRET-KEY-GEN`
(with pin entered interactivly)  works with above patch and corrected `key_type = CKK_GENERIC_SECRET;`

I ran the above 3 times while testing and token now shows 3 keys in token with same label (not what I would expect) :
```
./pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so -O --login
Using slot 0 with a present token (0x3b974305)
Logging in to "mytoken".
Please enter User PIN: 
Secret Key Object; Generic secret length 512
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      hmacSha256
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     never extractable, local
Secret Key Object; Generic secret length 512
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      hmacSha256
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     never extractable, local
Secret Key Object; Generic secret length 512
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      hmacSha256
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     never extractable, local
```
With current code in pkcs11-tool the key is created on the token and is sensitive and not extractable, and only usable within the token. It is not clear if that is what you intend to do. 

If your intent was to have token generate a secret and return it to be used by other software, PKCS\#11 also supports having the key extractable, so it could be read off the token and also supports session objects, such that the object is removed at the end of a session, or power off if hardware token. These attributes could be added to  pkcs11-tool. 
Also requires the pkcs11 module to understand extractable and session objects. 

Note pkcs11-tool is more of a test/example program. You can always write your own application and call PKCS11. 

Using OpenSC SPY can help in debugging/understanding PKCS11 calls when writing your own PKCS11 application. https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by justincranford** [comment]
My intention is to generate the HMAC secretkey inside the token. Sensitive and unextractable are perfect. Thank you!

The use case is Java SunPKCS11. I want HSM keys to protect data with confidentiality and integrity before persisted to a database.

Not all Java versions have same PKCS#11 feature set yet. OpenJDK community is actively playing catch up right now.
- Java 8u265 => AES-KEYGEN, AES-CBCPAD, HMAC => Sufficient, not missing HMAC keygen
- Java 13.0.0/11.0.8 SunPKCS11 => AES-KEYGEN, AES-GCM => Perfect, lack of HMAC keygen not a blocker

Java 8u272 is coming out soon and it backports AES-GCM support from Java 13. In the meantime, I am trying to fall back on AES-CBCPAD and HMAC.
- SunPKCS11 lets me call the token to do AES (or RSA keygen), but not HMAC keygen.
- The pkcs11-tool has the same AES+RSA keygen support, and same lack of HMAC keygen support.

Your patch will hopefully address the issue in pkcs11-tool. I am happy you responded so quick. For Java, I plan to open a ticket, but I see a ticket already open since 2005. I am hoping they can reprioritize it, since they are actively expanding support for PKCS#11 features right now.

**Comment by dengert** [comment]
@justincranford  if you want to test on windows, you can download one of the MSI files built to test PR  #2140 
In #2140, find the "Some checks were not successful" , click on "show all tests" 
on "continuous-integration/appveyor/pr — AppVeyor build succeeded" line click on "details"
there are  8 jobs at the end, click on one,
then on line with "Jobs", "Console", "Tests"and <"Artifacts" click on "Artifacts".
Download the MSI file.
Repeat on the other 7 if needed to get win32 and win64 MSI

**Comment by justincranford** [comment]
I tried this artifact.
- https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/35862741/job/8yaj26yitaae5918
- https://ci.appveyor.com/api/buildjobs/or8tf2up6fsba46l/artifacts/OpenSC-0.21.0-rc1_win32.msi

I retried my original command. It still fails with Unknown key type **secrkey**:512.

`
"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module C:\SoftHSM2\lib\softhsm2-x64.dll -login --label hmacSha256 --keygen --key-type secrkey:512 --mechanism GENERIC-SECRET-KEY-GEN
Using slot 0 with a present token (0x7e547986)
Logging in to "Token-0".
Please enter User PIN: error: Unknown key type secrkey:512
Aborting.
`

I noticed your test description for GENERIC-SECRET-KEY-GEN uses **generic**. Should it be **secrkey**? It might be confusing if import vs keygen use different values for the same thing.
- Import --type parameter calls it secrkey. Help description is "Specify the type of object (e.g. cert, privkey, pubkey, secrkey, data)". 
- Keygen --key-type parameter calls it generic.


`
"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module C:\SoftHSM2\lib\softhsm2-x64.dll -login --label hmacSha256 --keygen --key-type generic:512 --mechanism GENERIC-
SECRET-KEY-GEN
Using slot 0 with a present token (0x7e547986)
Logging in to "Token-0".
Please enter User PIN: Key generated:
Secret Key Object; Generic secret length 512
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      hmacSha256
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     never extractable, local
`

**Comment by justincranford** [comment]
This is what I see when my Java app logs in and lists the keys in slot 0.

INFO: Key alias=aes256, AES key, SunPKCS11-SoftHSM2 AES secret key, 32 bitstoken object, not sensitive, unextractable)
INFO: Key alias=hmacSha256, Generic Secret key, SunPKCS11-SoftHSM2 Generic Secret secret key, 512 bitstoken object, not sensitive, unextractable)

I can get the AES key and use it. However, I cannot get the generic secret, I get null instead. Not sure what is wrong. Investigating.

**Comment by justincranford** [comment]
Testing of SunPKCS11 HmacSha256 with the 512-bit generic secret worked.

Thank you so much for the quick turnaround and unblocking me. Much appreciated!

**Comment by dengert** [comment]
AES, DES3 and GENERIC are all secret keys. I  changed the --help  to show this.
```
--key-type <arg>          Specify the type and length (bytes if symmetric) of the key to create, for example rsa:1024, EC:prime256v1, GOSTR3410-2012-256:B, AES:16 or GENERIC:64
```

--keygen   generates a symmetric key like DES3, AES or GENERIC 
--keypairgen says generates  asymmetric key pairs like RSA or EC

You need to use --key-type GENERIC:nn  (in caps as the DES3 and AES were already in caps)

But the the PKCS11 standard says the CKA_VALUE_LEN attribute is in bytes 
So you really need to look if nn is being interpreted by your module as bytes or bits. 
So GENERIC:512 could be in bytes or bits. You may need GENERIC:64.

**Comment by justincranford** [comment]
It is good you pointed out the generic length is in bytes, like AES and 3DES. I did not notice that.

However, I was referring to the name "GENERIC". I found it confusing these two parameters have different names.

```
--key-type calls it GENERIC
--type calls it SECRKEY
```

Should the name be consistent in both parameters? Here are the descriptions side by side:

```
  -y, --type <arg>          Specify the type of object (e.g. cert, privkey, pubkey, **secrkey**, data)

  --key-type <arg>          Specify the type and length (bytes if symmetric) of the key to create, for example rsa:1024, EC:prime256v1, GOSTR3410-2012-256:B, AES:16 or **GENERIC**:64
```

This is just a minor usability thing. The main thing is keygen now supports generic secret which is great. Thank you.

**Comment by justincranford** [comment]
I uploaded an example Java Maven project to show how I tried using SunPKCS11 with SoftHSM2 and OpenSC.

https://github.com/justincranford/pkcs11

The integration tests show:
- Successful SunPKCS11 login to SoftHSM2 and list existing keys
- Successful AES keygen, encrypt, decrypt
- Successful HMAC mac, verify
- Failed HMAC keygen (because SunPKCS11 does not support GENERIC-SECRET-KEY-GEN mechanism yet)
