### ISSUE TITLE
PIN preference set incorrectly for PIV Card

### ISSUE THREAD

**Issue by dcooper16** [OpenSC/OpenSC#2141]
For PIV Cards, OpenSC does not set the PIN preference to the be the Global PIN if the card supports on-card biometric (OCC) comparison or the virtual contact interface (VCI).

Under SP 800-73-3, the first byte of the PIN Usage Policy in the Discovery object could only be 0x40 or 0x60. So, lines 2606 - 2608 of https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c set the pin_preference to be the Global PIN if byte 1 of the PIN Usage Policy is 0x60 and byte two is 0x20:
```
if (*pinp == 0x60 && *(pinp+1) == 0x20) { /* use Global pin */
    sc_log(card->ctx, "Pin Preference - Global");
    priv->pin_preference = 0x00;
}
```
However, this does not work with SP 800-73-4, since SP 800-73-4 allows for additional bits to be set in the first byte of the PIN Usage Policy.

In order to work with SP 800-73-4, OpenSC should only look at bit 6 of the first byte of the PIN Usage Policy. So, something like:
```
if ((*pinp & 0x20) == 0x20 && *(pinp+1) == 0x20) { /* use Global pin */
    sc_log(card->ctx, "Pin Preference - Global");
    priv->pin_preference = 0x00;
}
```

**Comment by dengert** [comment]
OK, I see it is a problem in the current implementation if used with newer cards. 

PR  #2053  "PIV Secure Messaging as defined in NIST 800-73-4" lines 4531-4536 should have the correct code. But this is not expected to be in the next release.  I will submit a separate PR for 0.21.0. 

```
if ((priv->pin_policy & (PIV_PP_PIN | PIV_PP_GLOBAL))
						== (PIV_PP_PIN | PIV_PP_GLOBAL)
						&& priv->pin_policy & PIV_PP_GLOBAL_PRIMARY) {
					sc_log(card->ctx, "Pin Preference - Global");
					priv->pin_preference = 0x00;
				}
```

@dcooper16  Have you had a chance to try  #2053? I have been using IDEMIA demo card to test the SM and VCI.
