### ISSUE TITLE
Minidriver skips Smartcard with ATR of length == 2

### ISSUE THREAD

**Issue by aryasenna** [OpenSC/OpenSC#2145]
### Problem Description

OpenSC's minidriver will return `SCARD_E_INVALID_PARAMETER/0x80100004` when presented with smartcard with Answer to Reset (ATR) length of 2.

The ISO/IEC 7816-3 says ATR may contain 2 to 33 characters, accordingly minidriver has the following check:
https://github.com/OpenSC/OpenSC/blob/8098b7de61cba16d500ca83eee0c3711760d26a9/src/minidriver/minidriver.c#L6873-L6875

However, Minidriver instead uses less or equal to 2 (`<= 0x2`) operator when checking the minimum length.
**Technically implementation that outputs 2 chars ATR _is_  conforming to standard, although quite uncommon.**

One good example is [Ledger's OpenPGP card implementation](github.com/LedgerHQ/openpgp-card-app):

https://github.com/LedgerHQ/openpgp-card-app/blob/f7fff68d329dd313278376af257f521e6c2b62e0/src/sdk/usbd_impl.c#L1339-L1345

In this case, all other OpenSC tools (e.g. pkcs15-init, openpgp-tools, etc) happily interact with Ledger, but the minidriver instead gives cryptic `0x80100004` message into the log.

It was not until I put a debugger to see what the heck is going on, I found out the root cause.

### Proposed Resolution

Replace 
```
if (pCardData->cbAtr >= 0x22 || pCardData->cbAtr <= 0x2)
```
with
```
if (pCardData->cbAtr >= 0x22 || pCardData->cbAtr < 0x2)
```

I have re-compiled OpenSC from source with above change, and OpenSC minidriver now plays nicely with Ledger, signing and encrypting with MS CAPI works.

### Steps to reproduce

1. Install OpenSC on Windows machine, includes the minidriver
2. Insert Smartcard that  outputs 2 character ATR by default.
3. Test using `pkcs15-init, openpgp-tools`, etc that card is accessible.
4. Test using `certutils -SCinfo`

### Logs

```
PS C:\Users\Arya Senna\> certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Ledger Nano X 0
--- Reader: Ledger Nano X 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
---   Card: Ledger Nano X OpenPGP Card
---    ATR:
        3b 00                                              ;.


=======================================================
Analyzing card in reader: Ledger Nano X 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Ledger Nano X 0
---   Card: Ledger Nano X OpenPGP Card
Provider = OpenPGP CSP
Key Container = (null) [Default Container]

Cannot open the AT_SIGNATURE key for reader: Ledger Nano X 0
Cannot open the AT_KEYEXCHANGE key for reader: Ledger Nano X 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Ledger Nano X 0
---   Card: Ledger Nano X OpenPGP Card
Provider = Microsoft Smart Card Key Storage Provider
Key Container = (null) [Default Container]

Cannot open the  key for reader: Ledger Nano X 0

--------------===========================--------------

Done.
CertUtil: -SCInfo command completed successfully.
```
Minidriver debugging log (c:\tmp\md.log) just contains repetition of:

```
********** DllMain Module(handle:0x00007FFCE7DD0000) 'C:\WINDOWS\system32\certutil.exe'; reason='Attach Process'; Reserved=0000000000000000; P:17668; T:43356
```

**Comment by frankmorgner** [comment]
I agree that we can skip the validation of ISO conformity. However, if the length restrictions are removed, then we need to adjust the minidriver code which copies the ATR around into the internal data structure. In particular, calling memcpy with lenght 0 is undefined behavior.

I'd be happy to review your pull request

**Comment by aryasenna** [comment]
>I agree that we can skip the validation of ISO conformity.

No, no. We should not skip. We should fix the check condition  .

ISO says ATR can consist of **2** to **33** characters. Your check _instead_ says it shall be from **3** to **32** characters.

To reiterate the obvious solution., we simply replace 
```
if (pCardData->cbAtr >= 0x22 || pCardData->cbAtr <= 0x2)
```
with
```
if (pCardData->cbAtr > 0x22 || pCardData->cbAtr < 0x2)
```
>In particular, calling memcpy with lenght 0 is undefined behavior.

So in this case the minimum length will be more than and including 2.

>I'd be happy to review your pull request

I mean two characters pull request would be quite funny, but if you like it then here you go: ;)
#2146

**Comment by frankmorgner** [comment]
thank you, the credit is yours in the git history ;-)
