### ISSUE TITLE
Spanish ID Card: Method to assign into the private data the secure channel Fails

### ISSUE THREAD

**Issue by derbic7** [OpenSC/OpenSC#2153]
I recently updated my Spanish ID card, so I have new one with the serial > BMP100001.

I have successfully compiled 0.21.0-rc1 and 0.21.0-rc2 and after executing the command _"pkcs11-tool -t -l"_ the log output is:
```
	....
	error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)

```
System: Linux Slackware 14.2
Card readers: Sveon SCT022 and Gemalto CT30 (both get the same result)

Looking at the log file (debug level 9) I'm getting:
```
....
P:13886; T:0x3067819776 23:29:19.378 [opensc-pkcs11] cwa-dnie.c:656:dnie_set_channel_data: assigning old data channel configuration
P:13886; T:0x3067819776 23:29:19.378 [opensc-pkcs11] cwa-dnie.c:662:dnie_set_channel_data: returning with: 0 (Success)
....
```

So it seems that the method of assign into the private data the secure channel Fails, because it should assign me the new one and not the old one.

After that, for testing purpose, I have roughly modified the the function "dnie_set_channel_data" in cwa-dnie.c file so that it always assigns the new data channel configuration, as follows:
.
```C
...
	if (buf && strcmp(buf, AC_RAIZ_COMPONENTES_2_ISSUER) == 0) {
		sc_log(card->ctx, "assigning new data channel configuration");
		priv_data->channel_data = &channel_data[AC_RAIZ_COMPONENTES_2_NEW_IDX];
	} else {
		sc_log(card->ctx, "assigning new data channel configuration");
		priv_data->channel_data = &channel_data[AC_RAIZ_COMPONENTES_2_NEW_IDX];
	}
...
```
With this temporary rough change, the result of testing the card was correct:
```
....
Using slot 0 with a present token (0x0)
Logging in to "DNI electrónico (PIN1)".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (KprivAutenticacion) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (KprivFirmaDigital) with 1 mechanism
    RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (KprivAutenticacion)
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
  testing key 1 (KprivFirmaDigital) with 1 mechanism
    RSA-PKCS: OK
Decryption (currently only for RSA)
  testing key 0 (KprivAutenticacion) -- can't be used to decrypt, skipping
  testing key 1 (KprivFirmaDigital) -- can't be used to decrypt, skipping
No errors
.....
```
It looks this is related to Issue [2105](https://github.com/OpenSC/OpenSC/pull/2109): Add new DNIe CA structure for the secure channel #2109, so if @rickyepoderi  were so kind as to review this section, it would be highly appreciated.

Thanks in advance, and many thanks to those who work on this project.

**Comment by rickyepoderi** [comment]
Hi, What is the issuer of your certificate? This [line](https://github.com/OpenSC/OpenSC/issues/2153) in the debuf...

**Comment by derbic7** [comment]
> Hi, What is the issuer of your certificate? This [line](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/cwa-dnie.c#L649) in the debug...
```
...
P:13886; T:0x3067819776 23:29:19.378 [opensc-pkcs11] cwa-dnie.c:649:dnie_set_channel_data: icc_intermediate_ca_cert issuer /C=ES/O=DIRECCION GENERAL DE LA POLICIA/OU=DNIE/2.5.4.97=VATES-S2816015H/OU=AC RAIZ COMPONENTES 2/CN=000000006573524449620018
...
```
This is the line, Thanks for the prompt response.

**Comment by rickyepoderi** [comment]
As you see your version of openssl doesn't recognize `organizationalUnitName` (OID `2.5.4.97`) so the comparison later fails. I see it was added by [this openssl commit](https://github.com/openssl/openssl/commit/4a8ab10dd205b0f8527f993e608ebe1b032768eb). What version of openssl are you using (`openssl version`)?

**Comment by derbic7** [comment]
I have openssl versión = 1.0.2
You are right but my question is: It is the full string really necessary for switching purposes between two ways? May be comparing only the last parts of the two chains would it be enough and more compatible? For example using only:
```

AC_RAIZ_COMPONENTES_ISSUER =   "/OU=AC RAIZ COMPONENTES/CN=000000006573524449600006"
AC_RAIZ_COMPONENTES_2_ISSUER = "/OU=AC RAIZ COMPONENTES 2/CN=000000006573524449620018"

```

**Comment by derbic7** [comment]
Or even easier:
If the AC_RAIZ_COMPONENTES_ISSUER string is used instead of AC_RAIZ_COMPONENTES_2_ISSUER and the "if" block is inverted:

```C
	if (buf && strcmp(buf, AC_RAIZ_COMPONENTES_ISSUER) == 0) {
		sc_log(card->ctx, "assigning old data channel configuration");
		priv_data->channel_data = &channel_data[AC_RAIZ_COMPONENTES_OLD_IDX];

	} else {
		sc_log(card->ctx, "assigning new data channel configuration");
		priv_data->channel_data = &channel_data[AC_RAIZ_COMPONENTES_2_NEW_IDX];
	}

```
This has worked for me, but I don't know if it makes the switch correctly with the previous dnie.
Can it be a solution ?

**Comment by rickyepoderi** [comment]
@derbic7 I just compare the whole thing because it worked and I didn't know that `organizationalUnitName` was going to be a problem. We can do a different thing for sure.

@frankmorgner It seems that `organizationalUnitName` has been recently added to openssl. It's only present in openssl since first 1.1.1 (not in previous 1.1.0 or 1.0.2). We can just do a `strstr` to search presence of `/OU=AC RAIZ COMPONENTES 2/` or we can compare the full issuer but constructing the X509_NAME with `X509_NAME_add_entry_by_OBJ(name, OBJ_txt2obj("2.5.4.97", 0), MBSTRING_ASC,
(const unsigned char *) "VATES-S2816015H", -1, -1, 1)`. If you don't say anything I'll do the first option (`strstr`) because it's easier. :smile:  

I'm giong to modify the issue ttle now that we know what happens here. I'll prepare the PR the weekend.

**Comment by derbic7** [comment]
@ Sounds really good. You are great. Sorry to cause you to have to work the weekend.
A round of beers for everyone.

**Comment by frankmorgner** [comment]
@rickyepoderi `strstr()` would be good enough.
