### ISSUE TITLE
No slot with a token was found. After running "pkcs11-tool --show-info" the second time

### ISSUE THREAD

**Issue by 13324bash** [OpenSC/OpenSC#2156]
### Problem Description
Hello, 
I am experiencing an issue where after running certain commands with the pkcs11-tool the card reader is no longer detected by opensc. This does not occur with a different model card reader. 

Here are the hardware details:

Smart card reader manufacturer name and reader model name:
Gemalto PC Twin Reader IDBridge CT30
Smart card name:
HID Crescendo 21Y

System information:
NAME="Raspbian GNU/Linux"
VERSION="10 (buster)"
5.4.72-v7+
Raspberry Pi 3 Model B Rev 1.2p

pi@raspberrypi:~ $ /usr/sbin/pcscd --version
pcsc-lite version 1.8.24.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2015 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
Enabled features: Linux arm-unknown-linux-gnueabihf libsystemd serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d

libccid (1.4.30-1).

### Steps to reproduce
Running the command:
pkcs11-tool --show-info
Appears to work as expected the first time it is run following a reboot, but the second time it is run the reader is no longer detected. 

pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
Using slot 0 with a present token (0x0)
pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
No slot with a token was found.

Similar behavior occurs when running other commands:
pi@raspberrypi:~ $ pkcs11-tool --test --login
Using slot 0 with a present token (0x0)
Logging in to "CAC II".
Please enter User PIN:
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
pi@raspberrypi:~ $ pkcs11-tool --test --login
No slot with a token was found.

### Logs
Running this command:
LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color
Prior to running:
pkcs11-tool --show-info
Produces these logs:
https://gist.github.com/13324bash/1a572a015cfbbc28723bf176c10804f1

Afterwards the logs look like this:
https://gist.github.com/13324bash/52835f938be07dcfc0cc45e3a828061c

If there's any more information or logs that I can provide which may help please let me know.

**Comment by dengert** [comment]
Does the Pi drop power to the reader on close? 
Is pcscd still running? 

Is it a bad reader?

**Comment by 13324bash** [comment]
> Does the Pi drop power to the reader on close?
It does not, the reader indicator light is still active. 
> Is pcscd still running?
> 
Yes, and restarting the service does not appear to change the behavior either. See the below steps I took to test. 
`pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
Using slot 0 with a present token (0x0)
pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
No slot with a token was found.
pi@raspberrypi:~ $ lsusb
Bus 001 Device 006: ID 413c:2113 Dell Computer Corp.
Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 004: ID 08e6:3437 Gemalto (was Gemplus) GemPC Twin SmartCard Reader
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
No slots.
pi@raspberrypi:~ $ htop
pi@raspberrypi:~ $ sudo service pcscd restart
pi@raspberrypi:~ $ pkcs11-tool --show-info
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.19)
No slots.`
> Is it a bad reader?
I tested it with two of the same model, one fresh out of the box with the same result.

**Comment by dengert** [comment]
Powered up my old Raspberry Pi 2 Model B rev 2 with OS versions 4.1.19+ from March 15 2016. I have not used it for a few years, when I had installed OpenSC 0.15.0 and it ran fine at that time with PIV card.
PCSCD was version 1.84

Also found an old GemPC Twin with faint label that looks like it says: 
P/N:HWP108760 B
B/N:R04A091445
RATING: 5V .100mA  
  
Suprisingly, I could reproduce a failure of pkcs11-tool -show-info works first time, then second time I get 
C_GetSlotInfo Failed CKR_DEVICE_ERROR

So I started to try using a more modern reader that I use all the time, but the Pi would not boot and attempts to run fsck on it and failed. Mounting it on a newer Pi that runs my model railroad and running fsck did not help.

Since this problem - Pi/OpenSC/PC Twin - goes back years, and no one else has this combination, I suspect that this has something to do with the PC Twin having some timeout or power issue and the PI being slow. 

 I would suggest you try a more modern reader.

**Comment by dengert** [comment]
Installed new raspberry Pi OS version 5.4.51 on old Raspberry Pi Model B rev 2 with 0.5GB memory with copyright from 2011

`apt-get install opensc` installed 0.19.0 and ccid, opensc-pkcs11 and pcscd. 

But when I plug in my good foldable SCR 3500 reader (says it is a SCR 331),
the RaspberryPi restarts. I suspect a power surge issue. After it comes up, I can insert and remove cards. I can also use a UCB 4 port hub, with the reader and it does not crash when reader is removed and inserted. I can actually have both readers plugged into hub with cards and pkcs11-tool still works. 

I had some problems with the old GemPC Twin not always being recognized. Works OK with the hub. This could also be a power surge issue. 

There does appear to be a software issue with pkcs11 with either reader:
```
pi@raspberrypi:~ $ pkcs11-tool -show-info
Using slot 0 with a present token (0x0)
Logging in to "Test Cardholder".
Please enter User PIN: 
Using signature algorithm ECDSA

error: PKCS11 function C_SignInit failed: rv = CKR_KEY_TYPE_INCONSISTENT (0x63)
Aborting.
```
This is with a card that does not have ECDSA.  but there is no crash.
and I can unplug and plug in the GemPC Twin, abd pkcs11-tool --test --login works.

**Comment by popovec** [comment]
@dengert 
There is typo error in Your command.. `-show-info` is translated to `-s` = sign some data.  Correct switch is `--show-info` .. 

@13324bash 
Although I also think it will be a power problem.. but you should run pcscd in foreground, in debug mode inclusive apdu logging (pcscd -f -d -a ). If pkcs11-tool is unable to find slot, you can then examine `pcscd` log ..(for example here reader disconnect and reconnect can be observed etc.).

**Comment by 13324bash** [comment]
@dengert
Thank you for putting in the effort to troubleshoot this. I purchased a Raspberry Pi 4 B and tested it with the same method and it does work as expected. The maximum total USB peripheral current draw is the same for both models, however the power supply on the 4 has a higher output.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md

@popovec 
Running `pcscd -f -d -a ` produces the below results:
https://gist.github.com/13324bash/f5fc7c2d7dea2512332fe49337e192f8
In the opening post I also have the logs from running `LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color` before and after running pkcs11-tool

**Comment by popovec** [comment]
Thank you, I looked at your log file:

`03000392 [1995730992] ccid_usb.c:1266:ControlUSB() control failed (1/4): -7 LIBUSB_ERROR_TIMEOUT`

This report shows, that the card reader is not able to complete the operation. The reader is unable at low level (USB transport) return a response. Most possible is the power problem that  is probably what makes it impossible to complete the USB operation. 

I'm sorry, but solving this problem is probably outside the scope of OpenSC...

**Comment by 13324bash** [comment]
@popovec
Not a problem. Thank you for your assistance.
