### ISSUE TITLE
Several token in Ubuntu server

### ISSUE THREAD

**Issue by SantiagoAndresHurtado** [OpenSC/OpenSC#2157]
### Problem Description
I have to sign/verify with several token in ubuntu server but OpenSC only recognize 8 of them. 

### Proposed Resolution
In some part of the system variables may be one that can be changed

### Steps to reproduce
I use epass2003 fetitian devices. 
Physically i know that there are more than 8 devices connected so i try the command: 
pkcs11-tool --module XXXXX --slot 9  -O

### Logs

> error: PKCS11 function C_OpenSession failed: rv = CKR_SLOT_ID_INVALID (0x3)
> Aborting.

**Comment by dengert** [comment]
the opensc.conf has a pkcs11 block where you can set max_virtual_slots and slots_per_card. 
See man opensc.conf  something like this will allow for 16 readers.  Note Windows 10 only allows 10 readers.  

```
app opensc-pkcs11 {
     pkcs11 {
         max_virtual_slots = 64;
         slots_per_card = 4;
     }
}
```

**Comment by frankmorgner** [comment]
Linux (PCSC-Lite), similarly, has a hard coded limit of 16 readers https://github.com/LudovicRousseau/PCSC/issues/13

**Comment by SantiagoAndresHurtado** [comment]
Thanks! 

@dengert it worked very well. 
@frankmorgner that info clarified the restriction. 

In my Ubuntu server 20.04 I edited **/etc/opensc/opensc.conf**, add the pkcs11 block and works fine!
