### ISSUE TITLE
Bus 001 Device 005: ID 096e:0703 Feitian Technologies, Inc. ePass3003Auto

### ISSUE THREAD

**Issue by sakoula** [OpenSC/OpenSC#2161]
### Problem Description

Hi There,

I am trying to connect an Feitian ePass3003Auto on a raspberry pi using OpenSC. I see that [ePass3003Auto is an older version of the supported ePass2003](https://github.com/OpenSC/OpenSC/wiki/Feitian-ePass2003). 

Has anyone tried that, or can I help to get it supported?

Thanks!

**Comment by dengert** [comment]
See if you are having problems similar to  https://github.com/OpenSC/OpenSC/issues/2156 which is also on Raspberry Pi but different device. 

If your question is how to install OpenSC, It is listed as one of the debian packages. You will also need pcsc and ccid which should be pre-reqs.

**Comment by dengert** [comment]
Installed new raspberry Pi OS version 5.4.51 on old Raspberry Pi Model B rev 2 with 0.5GB memory with copyright from 2011

`apt-get install opensc` installed 0.19.0 and ccid, opensc-pkcs11 and pcscd. 

Also see #2156.

**Comment by sakoula** [comment]
thanks!!! However is ePass3003Auto supported?

Thanks again!

**Comment by dengert** [comment]
a grep for "3003" in OpenSC source does not show anything for ePass. 

Ask Feitian. 

If it is a smart card/token, opensc-tool -a should show the ATR. 
then see if https://smartcard-atr.apdu.fr/ can identify it.

**Comment by dengert** [comment]
http://vietcard.com.vn/en/product/61/epass-3000 

has a chart. It sounds like the device comes with all the drivers and middleware,
installed from a virtual CD in the token.  

Says: 
32- bit and 64-bit Windows
Linux and Mac

But I bet it does not support Raspberry Pi on arm processors. So I doubt it opensc supports it. 

See if you can see this the CD on Windows.

**Comment by sakoula** [comment]
the linux driver has x86 binaries only plus a dynamically linked library plus a couple of utilities supporting 2.4 and 2.6 kernels only (latest linux driver is dated from 2016). I do not know why you require a specific kernel version. As I was looking I found opensc and thought I may use it in more recent OSes

**Comment by frankmorgner** [comment]
@FeitianSmartcardReader ?

**Comment by FeitianSmartcardReader** [comment]
ePass3003Auto doesn't support OpenSC, and the token is SCSI + HID protocol, not CCID compliance.
If you want use openSC with Feitian token, better go with epass2003

**Comment by sakoula** [comment]
@FeitianSmartcardReader thanks! Unfortunately I need to use ePass3003Auto . The Linux drivers I have found are dated 2013 and are i386 only. Can I still use it on a platform like raspberry or a newer linux distro?

sorry for and out of context (OpenSC) mail.

thanks again!

**Comment by FeitianSmartcardReader** [comment]
@sakoula noted, yes, we can support you for sure, our PKI expert leon@ftsafe.com, he will help you with this issue, thanks
