### ISSUE TITLE
MacOS Catalina:Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation

### ISSUE THREAD

**Issue by nishthasharma-byte** [OpenSC/OpenSC#2162]
### Problem Description

bash-3.2$ ssh-add -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11: 
Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation
bash-3.2$ 

I am not able to add my yubikey with ssh. Could anyone please help here. I have already tried copying and removing from Library folder.
I have also checked if there is any symlink for this file. But I could not find any.

**Comment by frankmorgner** [comment]
please read https://github.com/OpenSC/OpenSC/wiki/How-to-write-a-good-bug-report

**Comment by nishthasharma-byte** [comment]
I have got the resolution. Thankyou.

**Comment by mouse07410** [comment]
It would be nice if you shared your resolution - I often get this problem/error too. My inconvenient workaround is killing `ssh-agent` and restarting it.

**Comment by gagansuri** [comment]
how did you resolve it.?
