### ISSUE TITLE
OpenSC on Mac App Store

### ISSUE THREAD

**Issue by mohamedhafez** [OpenSC/OpenSC#2164]
It would be great if OpenSC could be distributed via the Mac App Store, so it would get automatically updated when new versions come out

**Comment by frankmorgner** [comment]
Same goes for Windows Store and various Linux distributions.

I'm not interested, managing the source code is time consuming enough. If someone else from the team is interested, I'm open for suggestions.

**Comment by rafa-as** [comment]
I agree with @mohamedhafez , would be great to have it on every SO Stores. If you need some help, I never published a Mac App Store app but I can investigate to do it

**Comment by frankmorgner** [comment]
You could use homebrew https://formulae.brew.sh/formula/opensc

For now, no integration in the macOS store is planned
