### ISSUE TITLE
Support for autonomous df size enlargement

### ISSUE THREAD

**Issue by carblue** [OpenSC/OpenSC#2165]
Applicable for SC_PKCS15_PRKDF..SC_PKCS15_DODF ?

First with EF.PrKDF I ran into this error
`sc_pkcs15init_update_file: Update file failed: -1510 (File too small)`
because my "initial" file size did set some arbitrary limit.
My card ACOS5-64 doesn't support simple file enlargement, but requires a delete and (re-)create file operation.

Maybe also other cards don't want to set an extreme large "initial" file size i.o. to avoid such errors,
but would like to set some reasonable "initial" file size, the actual file size requirement then to be satisfied by the OpenSC framework ("autonomous df size enlargement"),
e.g. by an heuristic like
`if remaining free/unused file size < x then enlarge file by y bytes`

I would have bet to have seen something like that already working in OpenSC, but actually didn't find it.

With enough input/discussion here, I could implement some PR proposal.

I don't know the capabilities of other cards referring to file size (enlarge? do all need a delete and (re-)create file op. ?)

**Comment by frankmorgner** [comment]
Hmm, not sure how often this would be used. rewrite of a card is not so common. maybe this automatic enlargement is best implemented in the card driver. Note that there's a risk of leaving the card in an undefined state when deletion is successful, but (re-) creation is not.

**Comment by carblue** [comment]
Hello @frankmorgner , thanks for Your comment,
actually I already implemented that in my driver, because required: An ACOS5 CryptoMate Nano operated with https://github.com/carblue/acos5 got stress-tested by @johughes99 (capacity for how many asym. keys are generatable, with different modulus length, turning every EEPROM byte available into an RSA keypair) and,
well, Your advice/Murphy's law: Having my card in an undefined EF.PrKDF state happened too during impl./testing, but I think, it's bullet-proof now.

I just thought it might make sense to move some of the impl. from card-driver to OpenSC framework, but I understand that might be overkill, hence I will close this issue within some reasonable time.
