### ISSUE TITLE
Problem with Athena AC2014 Italian CNS card

### ISSUE THREAD

**Issue by lscorcia** [OpenSC/OpenSC#2168]
### Problem Description
In Italy, citizens can request a smart card (called TS-CNS) for healthcare and authentication to the online services of the Public Administration. Some work has already been done in OpenSC itacns driver (https://github.com/OpenSC/OpenSC/wiki/Italian-CNS-and-CIE), and all cards share a common set of features and attributes, but it seems like the issued cards can be manufactured by different companies and therefore some work is still required.

In my case (card issued by the region of Apulia) the card is manufactured by Athena and the card type is "AC2014". When trying to access it via OpenSC 0.21 on Linux the card type is not recognized (I also tried v0.20, same result, and OpenSC for Windows, same result). The card works fine with the same reader device when read via the manufacturer Windows driver.
Please note that when I say Linux, i actually mean a Linux VM in a VirtualBox Windows machine.

Here is the output of pcsc_scan:

```
Using reader plug'n play mechanism
Scanning present readers...
0: Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00
 
Mon Nov 30 08:59:46 2020
 Reader 0: Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC

ATR: 3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC
+ TS = 3B --> Direct Convention
+ T0 = DF, Y(1): 1101, K: 15 (historical bytes)
  TA(1) = 18 --> Fi=372, Di=12, 31 cycles/ETU
    129032 bits/s at 4 MHz, fMax for Fi = 5 MHz => 161290 bits/s
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 7D --> Block Waiting Integer: 7 - Character Waiting Integer: 13
+ Historical bytes: 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80
  Category indicator byte: 00 (compact TLV data object)
    Tag: 6, len: B (pre-issuing data)
      Data: 02 0C 01 82 01 11 01 43 4E 53
    Mandatory status indicator (3 last bytes)
      LCS (life card cycle): 10 (Proprietary)
      SW: 3180 (Error not defined by ISO 7816)
+ TCK = FC (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC
	Italian healtcare card (TS) National Service Card (CNS) (HealthCare)
```

The last line seems to suggest that the card is read correctly, but then something doesn't work right  and it just hangs and never returns to the shell prompt.

### Steps to reproduce
I am available for any kind of testing you may suggest (except destructive ones!).

### Logs
Here is my opensc-debug.txt with level set to 3:
https://gist.github.com/lscorcia/04c43ea74581dc2a3c4a704632923590

**Comment by frankmorgner** [comment]
@resoli @puccia ?

**Comment by lscorcia** [comment]
It seems like the problem could be in VirtualBox USB stack, I found this link that seems to describe the very same issue: https://www.virtualbox.org/ticket/18902

I will try the suggested workaround tomorrow and if successful I'll close the issue.

**Comment by dengert** [comment]
The report was for VirtualBox 6.0.10 and is reported as fixed. 
I run Ubuntu 18.04 and 20.04 as guests under Windows 10 as host with VB 6.1.4 (and previously with 5.something) and do not have problems with PIV card or readers. 

I also note that the reader is identified as "Generic Smart Card Reader Interface [Smart Card Reader Interface]" which may also be a problem, as all the readers I have get the name from the reader.  This may be pcsc on guest  can not identify the reader either.  (But you also said pcsc_scan could read the ATR, so card is not dead.) 

This line from your debug output says:
"Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00:SCardConnect(SHARED): 0x80100066"  i.e. SCARD_W_UNRESPONSIVE_CARD 

So upgrading to 6.1 may fix the problem too. 
What is the reader?

**Comment by lscorcia** [comment]
The reader is an EWIENT EW1052 (https://www.amazon.it/gp/product/B01M0LSV8D/), VirtualBox 6.1.16. 

I can confirm that switching VirtualBox to the USB3 stack - as suggested in the VirtualBox report - lets the card work correctly under Linux with OpenSC 0.21. The report says fixed but reading the posts they really haven't, they just found that under USB3 it works and never investigated further. Maybe that's worth a note in the documentation?

Anyway thanks for your time, I will close the issue now :-)

**Comment by resoli** [comment]
> @resoli @puccia ?

I've read just now, sorry. Glad to see it was only VirtualBox related.
