### ISSUE TITLE
"Certificate no found" when import EC Key converted to PKCS#12 with option -nocerts

### ISSUE THREAD

**Issue by ygbillet** [OpenSC/OpenSC#2172]
Hi,

Smart Card Shell 3.17.453
Smart Card Shell Scripting Engine (scdp4j) 3.17.355

I generated an EC Key on another support (before getting an HSM Key).
I try to import this EC Key in Nitrokey HSM.

Steps so far :

1. I initialize the key
2. added a DKEK share
3. converted my EC Key to PKCS#12 with option `-nocerts`
4. Importing using Smart Card Shell

I converted EC Key using OpenSSL with option -nocerts : `openssl pkcs12 -export -nocerts -inkey privatekey.pem -out privatekey.p12`

### Logs
```
GPError: KeyStore (OBJECT_NOT_FOUND/0) - "Certificate not found" in C:\tools\smartcardshell\scsh3\keymanager\keymanager.js#2097
    at C:\tools\smartcardshell\scsh3\keymanager\keymanager.js#2097
    at C:\tools\smartcardshell\scsh3\keymanager\keymanager.js#2272
```

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
There is currently no direct way of importing an EC key without a certificate. You need to create and store a self-signed certificate first and have that imported as part of the PKCS#12 container.

You could also write your own script based in the keymanager.js,

**Comment by ygbillet** [comment]
Thanks for this response.
