### ISSUE TITLE
CardOS 5.3 PKCS15-init: Failed to create PKCS #15 meta structure: Security status not satisfied

### ISSUE THREAD

**Issue by eclhmf** [OpenSC/OpenSC#2174]
### Problem Description

- Windows 10 64-bit
- OpenSC 0.21.0
- CardOS 5.3 - ATR: **3B D2 18 00 81 31 FE 58 C9 03 16**

Hello,
I am trying to migrate our Smartcard Initializing automation scripts to work with CardOS 5.3 cards (migrating from CardOS 4.4).
The task of the scripts are:
1) Change factory key to default key
2) Change default key to company key (currently skipped for less friction in the migration, it will be added later)
3) Create MF (Executing command FORMAT)
4) Call pkcs15-init to initialize PKCS#15 on the cards
5) Adding keys etc. to card

Currently, it fails at step 4 with following error: 

> Failed to create PKCS #15 meta structure: Security status not satisfied

I tried to interpret the log output: It seems to me that pkcs15-init is selecting the master file (MF) and then checking the ACL. This fails because the ACL is **never allowed**, but is has been created/formatted with **always allowed**.

### Proposed Resolution
None

### Steps to reproduce

0) Take factory fresh card
1) Change factory key to default key
2) Format the card
3) pkcs15-init.exe -C --no-so-pin -v -v -v

Step: 1 and 2 can be reproduced with the official scripts (which are NDA protected).

### Logs

https://gist.github.com/eclhmf/da6f4cf221cb75db1e5c4b432ed845a3#file-gistfile1-txt

**Comment by Jakuje** [comment]
CardOS 5 initialization is not implemented now because we do not have any publicly available specification how this works. The current implementation is for CardOS 4, which is different.

**Comment by Jakuje** [comment]
Nobody stepped out to implement closed-specification of CardOS 5.3 initialization so closing. If you would be interested in working on that, please open a new issue or pull request.
