### ISSUE TITLE
Trying to delete Data Object on Feitian ePass2003 get CKR_USER_NOT_LOGGED_IN

### ISSUE THREAD

**Issue by johughes99** [OpenSC/OpenSC#2189]
### Problem Description

When trying to delete a data object get CKR_USER_NOT_LOGGED_IN error when using Feitian ePass2003.  Do not see this error when using Nitrokey HSM

### Proposed Resolution

None known

### Steps to reproduce

C_OpenSession
C_Login as CKU_USER
C_CreateObject of type CKO_DATA  (private token)
C_CreateObject of type CKO_DATA  (public token)
C_DestroyObject for private token data object
C_DestroyObject for public token data object

For both C_DestroyObject calls get error return CKR_USER_NOT_LOGGED_IN

I have a test program I can upload if required

### Logs

Attached are the logs for the Feitian when failing and for Nitro Key when working
[opensc-debug  OK - Nitrokey.log](https://github.com/OpenSC/OpenSC/files/5720748/opensc-debug.OK.-.Nitrokey.log)
[opensc-debug  FAILED Feitian.log](https://github.com/OpenSC/OpenSC/files/5720749/opensc-debug.FAILED.Feitian.log)

The relevant lines in the Feitian log show:

:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card.c:523:sc_unlock: called
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:1008:epass2003_sm_free_wrapped_apdu: called
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:975:epass2003_sm_unwrap_apdu: called
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:192:epass2003_check_sw: Security status not satisfied
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:996:epass2003_sm_unwrap_apdu: unwrapped APDU: resplen 0, SW 6982
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:997:epass2003_sm_unwrap_apdu: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:1029:epass2003_sm_free_wrapped_apdu: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] sm.c:173:sc_sm_single_transmit: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] apdu.c:374:sc_single_transmit: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card.c:523:sc_unlock: called
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:192:epass2003_check_sw: Security status not satisfied
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card-epass2003.c:2182:epass2003_delete_file: Delete file failed: -1211 (Security status not satisfied)
P:29055; T:0x140277083916096 09:37:29.921 [opensc-pkcs11] card.c:616:sc_delete_file: returning with: -1211 (Security status not satisfied)

**Comment by frankmorgner** [comment]
1. You entered your PIN incorrectly
2. The verification failed with 63C6, which is not correctly propagated from OpenSC

**Comment by frankmorgner** [comment]
There may be some other security condition that's not satisfied.

please contact @FeitianSmartcardReader directly
