### ISSUE TITLE
How to use Gemalto cards with Identive CLOUD 2700 R Smart Card Reader

### ISSUE THREAD

**Issue by rodrigoguariento** [OpenSC/OpenSC#2196]
I'm using OpenSC 0.20.0 [gcc  9.2.1 20200123]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
Ubuntu 20.04 LTS

My reader is: 
Identive CLOUD 2700 R Smart Card Reader (CIS SCR 3310 v2.0 RD1-X)

And I'm trying to read a Gemalto card ( from https://doccloud.com.br/ ).

Someone know how to read this sort of card? This card is largely used in Windows and Mac to authenticate in Gov's account websites. I'm not being able to use it with Google Chrome and Firefox in Ubuntu 20.04 LTS. Some idea? Thank you.

**Comment by dengert** [comment]
The card may not be supported by OpenSC.  
start with opensc-tool -a 
to get the ATR.  Use https://smartcard-atr.apdu.fr/ to parse the ATR.

Then try 
opensc-tool --card-driver default --list-files
and also try with  --list-algorithms,  --info, --serial and --name 

If that works  then try
opensc-explorer --card-driver default

**Comment by frankmorgner** [comment]
Please re-open this topic if there's new input available.
