### ISSUE TITLE
Pkcs11-spy version 3 loading version 2 fails

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2204]

**Comment by dengert** [comment]
While trying to run spy built from master, to load p11-kit to test #2199, spy tries to call the C_GetInterface in the p11-kit, but p11-kit is version 2, and does not have C_GetInterface.

Spy output show a call C_GetInterface, which appears to be an internal call?   

Temporary fix: 
[pkcs11-spy-po-bug.diff.txt](https://github.com/OpenSC/OpenSC/files/5823069/pkcs11-spy-po-bug.diff.txt)

I leave the problem up to those working on pkcs11 v3.

**Comment by Jakuje** [comment]
Thank you for the report. The detection of V3 API with presence or absence of functions in dynamic objects makes it more complicated for proxies such as pkcs11-spy or p11-kit as we can not hide a symbol in runtime.

As I thought about this, the most sensible way would be to always provide the interface functions, but if the underlying module does not support the V3 functions, emulate this by returning the function list with only V2 interfaces.

See the proposed patch in #2206
