### ISSUE TITLE
configure to fail because EAC_CTX_init_pace

### ISSUE THREAD

**Issue by PhoenixBaymax** [OpenSC/OpenSC#2218]
./configure PKG_CONFIG_PATH="$mydevenv/lib/pkgconfig:$PKG_CONFIG_PATH" --prefix=$mydevenv --disable-strict --enable-doc --enable-zlib ZLIB_CFLAGS="-I$mydevenv/include" ZLIB_LIBS="-L$mydevenv/lib" --enable-openssl OPENSSL_CFLAGS="-I$mydevenv/include" OPENSSL_LIBS="-L$mydevenv/lib" --enable-openpace OPENPACE_CFLAGS="-I$mydevenv/include" OPENPACE_LIBS="-L$mydevenv/lib" PCSC_CFLAGS="-I$mydevenv/include/PCSC" PCSC_LIBS="-L$mydevenv/lib"

①the latest version;
②the configure console log is
.....
checking eac/eac.h usability... yes
checking eac/eac.h presence... yes
checking for eac/eac.h... yes
checking for EAC_CTX_init_pace... configure: WARNING: Cannot link against libeac
configure: error: OpenPACE linkage required, but no OpenPACE was found
③the config.log log content is
configure:16580: checking for EAC_CTX_init_pace
configure:16600: gcc -o conftest -g -O2  -I/home/opsadmin1/Desktop/opensc_res/dev_env/include  conftest.c  -L/home/opsadmin1/Desktop/opensc_res/dev_env/lib >&5
/usr/bin/ld: /tmp/ccNgmtB4.o: in function `main':
/home/opsadmin1/Desktop/opensc_res/opensc-0.21.0/conftest.c:68: undefined reference to `EAC_CTX_init_pace'
collect2: error: ld returned 1 exit status

I see the configure file
#ifdef __cplusplus
extern "C"
#endif
char EAC_CTX_init_pace ();
int
main ()
{
return EAC_CTX_init_pace ();
  ;
  return 0;
}

the code is wrong because there is not the define of EAC_CTX_init_pace();

**Comment by frankmorgner** [comment]
your libs are consistently wrong. You're adding a library path (`-L...`), but you're not adding the actual library, e.g. `-leac -lcrpto`.... You would be better off if pkg-config would handle this stuff. `./configure PKG_CONFIG_PATH="$mydevenv/lib/pkgconfig` should be enough.

**Comment by PhoenixBaymax** [comment]
Thank you, it was my wrong configure, and I had solved the problem!
