### ISSUE TITLE
pkcs11: missing seed_random

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2229]
### Problem Description

The current `sc_pkcs11_framework_ops` structure does not have a support for a seed_random() callback.

In order to support it smoothly, I'll provide a specific pull request serie.

The new field to be added is:
```
  CK_RV (*seed_random)(struct sc_pkcs11_card *p11card,
        CK_BYTE_PTR, CK_ULONG);
```

**Comment by frankmorgner** [comment]
please don't, we are not using a PRNG. For C_GenerateRandom, we are either using the card's *real* RNG or we are returning an error.

**Comment by vjardin** [comment]
OK, I get the point. So this issue shall be closed and a new one will be open later on for a PRNG if it makes sense.
