### ISSUE TITLE
Yubikey 4 serial number is all zeroes

### ISSUE THREAD

**Issue by nickrbogdanov** [OpenSC/OpenSC#2235]
This shows the real serial number with ykcs11 but not with opensc 0.20.0-3:

```
# pkcs11-tool --list-slots
Available slots:
Slot 0 (0x0): Yubico YubiKey OTP+FIDO+CCID 00 00
  token label        : server
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 00000000
  pin min/max        : 4/8
```

**Comment by dengert** [comment]
Yubikey can have multiple applets, including PIV and OpenPGP. There are many other cards, tokens and software implementations of the PIV applet.  The PIV applet is based on [NIST sp800-73-3]( https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-73-3.pdf). This does not define a serial number.

The OpenSC PIV driver does not attempt to read a serial number directly from a card, but uses  
the required CHUID object to derive a "serial" number. (Also called a CHUI.) The CHUID includes a FASC-N for use with US government agencies and can also include a GUID for non government use. See: 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L2069-L2074
If the CHUID is found, a serial number (specific to the PIV applet)  will be derived from the FASC-N or GUID.  
 
The yubic-piv-tool can create a CHUI, using "set-chuid"
