### ISSUE TITLE
Is it possible to unblock the SOPIN (on an Aventra MyEID card)?

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#2237]
### Problem Description

According to the manual, the following command should unblock the SOPIN on an Aventra MyEID Card:

`pkcs15-tool --unblock-pin --auth-id ff
`

Using the correct SOPIN PUK number, the attempt fails, and counts down the retry counter:

```
[root@localhost ~]# pkcs15-tool --unblock-pin --auth-id ff
Using reader with a card: ACS ACR 38U-CCID 00 00
Enter PUK [Security Officer PIN]:
Enter new PIN [Security Officer PIN]:
Enter new PIN again [Security Officer PIN]:
PUK code incorrect; tries left: 9

```

### Proposed Resolution

Can you confirm whether this functionality exists at all?

Can you confirm if the functionality does exist, is the functionality broken?

### Steps to reproduce

Take working, finalised MyEID Aventra smartcard.

Delete an existing certificate with a view to replacing it, this works:

```
[root@localhost ~]# pkcs15-init --delete-objects cert --id 00d53dbe3736f3a68c81fb04bf9faaaf72ec26e2
Using reader with a card: ACS ACR 38U-CCID 00 00
User PIN [Smartcard PIN] required.
Please enter User PIN [Smartcard PIN]: 
Deleted 1 objects
```

Attempt to add a replacement certificate, despite the SOPIN being correct, this fails:

```
[root@localhost ~]# pkcs15-init --store-certificate intermediate3.cer --label "Globalsign Intermediate 2020"
Using reader with a card: ACS ACR 38U-CCID 00 00
Security officer PIN [Security Officer PIN] required.
Please enter Security officer PIN [Security Officer PIN]:
Failed to store certificate: PIN code or key incorrect

```

Eventually the card is locked, and so we try to unlock it, and despite the PUK code being correct, this also fails:

```
[root@localhost ~]# pkcs15-tool --unblock-pin --auth-id ff
Using reader with a card: ACS ACR 38U-CCID 00 00
Enter PUK [Security Officer PIN]:
Enter new PIN [Security Officer PIN]:
Enter new PIN again [Security Officer PIN]:
PUK code incorrect; tries left: 9

```

**Comment by popovec** [comment]
> Can you confirm whether this functionality exists at all?

I have here only OsEID  card, and I can confirm `pkcs15-tool --unblock-pin --auth-id ff` is working for me, and changing the SO-PIN is also fully working (`pkcs15-tool --change-pin --auth-id ff`). 
 
Are you really using the correct SO-PIN when uploading the certificate? Try if you can change both USER PIN and SO-PIN (`pkcs15-tool --change-pin --auth-id 01`,   `pkcs15-tool --change-pin --auth-id ff`).
