### ISSUE TITLE
Support for other SSL libs?

### ISSUE THREAD

**Issue by tx-opensc** [OpenSC/OpenSC#2239]
Hi,

actually *questions* like this belong to mailing lists but no mailing list is mentioned here.

Are there any plans to support other SSL libs than OpenSSL? Maybe mbed TLS?
(Like e.g. in libp11.)

**Comment by dengert** [comment]
OpenSC can be built with LibreSSL. Not sure if anyone still uses it with OpenSC. AFAIK the OpenSC test suits don't test if it works or not. 

Look at: https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/sc-ossl-compat.h which handles most for the differences between OpenSSL versions and LibreSSL. 

You could submit a PR to use mbed.

**Comment by tx-opensc** [comment]
Well, creating a PR... if I have some time left to do the coding I'll surely create a PR. :-)
I'll take a look into sc-ossl-compat.h.
Thank you for your quick answer!
"Issue" can be closed.

**Comment by frankmorgner** [comment]
`sc-ossl-compat.h` deals with the changes in OpenSSL and its derived library LibreSSL.

We don't have a good abstraction layer for a crypto implementation, so it would take a good amount of work to support mbedTLS as alternative. Please note that most of the OpenSC code is not optimized for embedded use (i.e. few system resources), Hence, I doubt that we will ever get support for mbedTLS, but as Doug stated, we are open for contributions.
