### ISSUE TITLE
Use Pinpad reader to test Spanish eID, but fail to input the CAN value with my pinpad reader

### ISSUE THREAD

**Issue by PhoenixBaymax** [OpenSC/OpenSC#2245]
### Problem Description

I have a spanish eid, and use dnie-tool that shows some infos:
Using reader with a card: ) 00 00
......
DNIe Version:  DNIe 04.21 A9 H 0155 EXP 2-(5.2-10)
.....

Then I use npa-tool to test PACE, as "npa-tool -c", when it requires me to input the CAN, I input with the keyboard, and last tool tips me "Established PACE channel with CAN."

### Proposed Resolution
I expect the CAN is input by my Pinpad reader not the keyboard.
### Logs
[tw-z-opensc-debug.log](https://github.com/OpenSC/OpenSC/files/6041755/tw-z-opensc-debug.log)

**Comment by frankmorgner** [comment]
most readers don't support PACE. which one are you using?

**Comment by PhoenixBaymax** [comment]
We are using Feitian R805, which support PACE, and working to debug with OpenSC to make it work !

**Comment by frankmorgner** [comment]
I suppose you are using libccid as driver, which (I believe) doesn't support the PACE commands according to PC/SC pt. 10. This means you need to set `enable_escape` to true in opensc.conf to pipe the PACE commands as pseudo APDUs throught the driver to the reader.

**Comment by frankmorgner** [comment]
FYI, @LudovicRousseau

**Comment by LudovicRousseau** [comment]
I am not familiar with PACE (Password Authenticated Connection Establishment?).
pcsc-lite has a define for `FEATURE_EXECUTE_PACE` in `PCSC/reader.h` but this value is not used anywhere. So I am not surprised it does not work for you.

**Comment by PhoenixBaymax** [comment]
My Reader supports PACE using Pseudo-APDU and I change the OpenSC source code, and it successes to run as expect that the PIN is input in my reader.
