### ISSUE TITLE
How many applications in the Spanish eID card (DNI 3.0)?

### ISSUE THREAD

**Issue by AKing23T** [OpenSC/OpenSC#2255]
### Problem Description
the site https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_104&id_menu=1 says the Spanish eID card(DNI 3.0) supports functions of eID, ePassport and eSign, so how many are applications in it, two or three?

**Comment by frankmorgner** [comment]
Maybe @germanblanco or @rickyepoderi know more...

**Comment by rickyepoderi** [comment]
Hi,

I don't see any of that information in the page you link (wrong link?), and I'm really not sure what you are asking about.

The Spanish DNIe for sure has some features of eID and ePassport (it stores some personal information like fingerprints, the citizen photograph and so on and so forth) but I really don't know if there are standards or specifications about that part and if the DNIe fulfills some of them. In OpenSC we just implement the part for the eSign (management of the two certificates that are placed inside the card, for signing and for identification).

I remember [this link](https://oc.ccn.cni.es/documentos/normativa-y-legislacion/57-the-evolution-of-the-spanish-eid-card/) about the history and the features about the DNIe.
But, in general, we are not the correct people to ask this information. Ask to the DGP using the mail that is in the same site you are linking. I have said this dozens o times, we are not related to DGP or FNMT or any of the governmental teams that manages the DNIe.

**Comment by AKing23T** [comment]
in BSI_TR-03110_Part-1_V2-2.pdf, there is a Authentication procedures for the ePassport Application on Page 11.
in 9303_p10.pdf, the full AID of the eMRTD application is ‘A0 00 00 02 47 10 01’.

If I want to do esign or  do eid, do I select the same AID or other AID?
