### ISSUE TITLE
How is data transmitted from PC to reader after establish PACE channel

### ISSUE THREAD

**Issue by PhoenixBaymax** [OpenSC/OpenSC#2256]
### Problem Description

My test reader supports FEATURE_EXECUTE_PACE, and my test card is Spanish DNI 3.0 card, I change some Opensc code to test.
After establishing pace channel with CAN, the data from PC to reader is still plaintext.
This point can see from the log 
.....
Outgoing APDU (12 bytes):
00 A4 04 0C 07 A0 00 00 02 47 10 01 .........G..
P:407212; T:0x140302673729344 17:26:41.414 [npa-tool] reader-pcsc.c:242:pcsc_internal_transmit: called
P:407212; T:0x140302673729344 17:26:41.414 [npa-tool] reader-pcsc.c:262:pcsc_internal_transmit: called
P:407212; T:0x140302673729344 17:26:41.718 [npa-tool] reader-pcsc.c:341:pcsc_transmit: 
Incoming APDU (2 bytes):
69 88 i.
....

When I select the epassport application, the CLA of the APDU is 00, I am not sure about that.
Should be the APDU crypted? 
If crypted, how be it crypted under there is not PACE key?
If not crypted, the data from PC to reader is not safe.

### Logs
[tw-z-opensc-debug.log](https://github.com/OpenSC/OpenSC/files/6114908/tw-z-opensc-debug.log)

**Comment by frankmorgner** [comment]
the reader is performing PACE, so the reader is the end point of the encrypted channel. all data to the reader is unencrypted. obviously, the designers of this security model don't consider a physical attack at the user's PC (USB sniffer) in their attack model.
