### ISSUE TITLE
PKCS11 function C_Login failed

### ISSUE THREAD

**Issue by N1ck01as** [OpenSC/OpenSC#2272]
### Problem Description
Hello, 
I'm a new user of OpenSC because our SmartCard provider has no MacOS driver...
When I try to identify my SmartCard, I've got an error : 

```
% pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "pr_xfbn7933_180-... (PIN_Global)".
Please enter User PIN: 
error: PKCS11 function C_Login failed: rv = CKR_PIN_INCORRECT (0xa0)
Aborting.
```

### Proposed Resolution
I'm not a developer but it's related to this issue: #1096 because I have the same card from "Imprimerie Nationale".

### Steps to reproduce
- Use OpenSC stable 0.21.0 or Nighly Builds
- type pkcs-11-tool --login --test or pkcs-15-tool --verify

### Logs
https://gist.github.com/N1ck01as/9069a7e526b1c686f272bdc2029e9b91

**Comment by dengert** [comment]
From the debug log, this appears to be  another iasecc card. But only a partial log was sent.  The problem maybe related to #2217, and others: 2262, 2264, 2267, 2270 2267. #2217 is a French Healthcare card. @vjardin can you look at this?

**Comment by vjardin** [comment]
You welcome. Please, which IASECC card are you using ? What is the output of PCSC scan ? Just in case, can you provide the logs of  `iasecc-tool --list-applications` and `iasecc-tool --list-info` ? Do you have any way to gather the logs on a Linux environment using the master ?

**Comment by N1ck01as** [comment]
Yes, of course!
Here are the logs of commands:

```
iasecc-tool --list-applications
Using reader with a card: ACS ACR39U ICC Reader
Application 'ECC Orange':
	AID: E828BD080FA00000050450524F200105
	DDO: 4F10E828BD080FA00000050450524F200105
```

```
pkcs15-tool --list-info
Using reader with a card: ACS ACR39U ICC Reader
PKCS#15 Card [pr_xfbn7933_180-111-309-815]:
	Version        : 1
	Serial number  : 6367610001392341688f
	Manufacturer ID: Imprimerie Nationale
	Last update    : 20180126124252Z
	Profile        : IN.pro.0183.01.04
	Flags          : Login required, PRN generation
		 sc_supported_algo_info[0]:
			 reference  : 1 (0x01)
			 mechanism  : [0x220] CKM_SHA_1                    
			 operations : [0x40], hash
			 algo_id    : 1.3.14.3.2.26
			 algo_ref   : [0x10]
		 sc_supported_algo_info[1]:
			 reference  : 2 (0x02)
			 mechanism  : [0x250] CKM_SHA256                   
			 operations : [0x40], hash
			 algo_id    : 2.16.840.1.101.3.4.2.1
			 algo_ref   : [0x40]
		 sc_supported_algo_info[2]:
			 reference  : 3 (0x03)
			 mechanism  : [0x06] CKM_SHA1_RSA_PKCS            
			 operations : [0x02], compute_signature
			 algo_id    : 1.2.840.113549.1.1.5
			 algo_ref   : [0x12]
		 sc_supported_algo_info[3]:
			 reference  : 4 (0x04)
			 mechanism  : [0x40] CKM_SHA256_RSA_PKCS          
			 operations : [0x02], compute_signature
			 algo_id    : 1.2.840.113549.1.1.11
			 algo_ref   : [0x42]
		 sc_supported_algo_info[4]:
			 reference  : 5 (0x05)
			 mechanism  : [0x01] CKM_RSA_PKCS                 
			 operations : [0x02], compute_signature
			 algo_id    : 1.2.840.113549.1.1.1
			 algo_ref   : [0x02]
		 sc_supported_algo_info[5]:
			 reference  : 6 (0x06)
			 mechanism  : [0x01] CKM_RSA_PKCS                 
			 operations : [0x20], decipher
			 algo_id    : 1.2.840.113549.1.1.1
			 algo_ref   : [0x1a]
```

I will try on Linux in a VM, I hope it will work ^^

**Comment by vjardin** [comment]
Please, can you add the output of:
```
pkcs15-tool -k --verify-pin  --pin abcd
```
?

Regarding the logs, I'd like to get for each command the content of opensc-debug.log too ?

**Comment by N1ck01as** [comment]
Here you'll find the log for the three commands: https://gist.github.com/N1ck01as/4ad4798a06893bfd860bad85af1c9a69

```
pkcs15-tool -k --verify-pin --pin 1234                     
Using reader with a card: ACS ACR39U ICC Reader
Operation failed: PIN code or key incorrect
```

**Comment by vjardin** [comment]
Thanks, you are lucky, your card was supported natively by @viktorTarasov few years ago:
```
 card-iasecc.c:373:iasecc_match_card: 'IAS/ECC v1.0.1 Sagem ypsID S3' card matched
 card-iasecc.c:565:iasecc_init_amos_or_sagem: called
```

I would be very interested to get a sample of a ypsID S3 card, could you DM me ?

I'd need to analyze the call flow from sc_pin_cmd:
```
 sec.c:200:sc_pin_cmd: called
 sec.c:256:sc_pin_cmd: returning with: -1214 (PIN code or key incorrect)
```

**Comment by N1ck01as** [comment]
@vjardin , yes, I used my PIN instead of 1234. I've just replaced my pin with 1234 in my comment.

**Comment by vjardin** [comment]
If you care concerned about posting the logs, you can DM to me directly. My email is vjardin à free POINT fr

**Comment by vjardin** [comment]
> Let me know what do you need. I'll post here or with DM, as you prefer :)

Hi @N1ck01as , I did not get any email from you, did you send it ?

**Comment by vjardin** [comment]
Hi @N1ck01as , any news ? I did not get anything.

**Comment by frankmorgner** [comment]
Please re-open this topic if there's new input available.
