### ISSUE TITLE
IASECC/CPX: RIPEMD160 - CKR_GENERAL_ERROR

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2273]
### Problem Description

When running:
```
$ pkcs11-tool --test --login --pin 1234
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
error: PKCS11 function C_DigestInit failed: rv = CKR_GENERAL_ERROR (0x5)
```

It fails on a CKR_GENERAL_ERROR due to:
```
static CK_RV sc_pkcs11_openssl_md_init(sc_pkcs11_operation_t *op)
 
        if (!(md_ctx = EVP_MD_CTX_create()))
                return CKR_HOST_MEMORY;
        if (!EVP_DigestInit(md_ctx, md)) {
                EVP_MD_CTX_destroy(md_ctx);
                return CKR_GENERAL_ERROR;
        }
```

In order to pass it, I would need to disable CKM_RIPEMD160:
```
--- a/src/tools/pkcs11-tool.c
+++ b/src/tools/pkcs11-tool.c
@@ -4977,7 +4977,7 @@ static int test_digest(CK_SESSION_HANDLE session)
        CK_MECHANISM_TYPE mechTypes[] = {
                CKM_MD5,
                CKM_SHA_1,
-               CKM_RIPEMD160,
+               //CKM_RIPEMD160,
                0xffffff
```

### proper fix ?

I guess it should not be enumerated from:
```
        if (!find_mechanism(sessionInfo.slotID, CKF_DIGEST, NULL, 0, &firstMechType)) {
                fprintf(stderr, "Digests: not implemented\n");
                return errors;
        }
```

which uses: `C_GetMechanismList()` under the hood because it returns that it can support:
```
CKM_RIPEMD160
    [ulMinKeySize] => 0
    [ulMaxKeySize] => 0
    [flags] => 1024
```
see:
```
$ pkcs11-tool -M                       
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA224, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  RSA-9796, keySize={512,2048}, hw, decrypt, sign, verify
  RSA-PKCS, keySize={512,2048}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={512,2048}, sign, verify
  SHA256-RSA-PKCS, keySize={512,2048}, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={512,2048}, generate_key_pair
```

I do not understand how the RIPEMD160 or GOSTR3411 shows up knowing that these capabilities (SC_ALGORITHM_RSA_HASH_RIPEMD160) are not registered by `iasecc_init()`:
```
#define IASECC_CARD_DEFAULT_FLAGS ( 0                   \
                | SC_ALGORITHM_ONBOARD_KEY_GEN          \
                | SC_ALGORITHM_RSA_PAD_ISO9796          \
                | SC_ALGORITHM_RSA_PAD_PKCS1            \
                | SC_ALGORITHM_RSA_HASH_NONE            \
                | SC_ALGORITHM_RSA_HASH_SHA1            \
                | SC_ALGORITHM_RSA_HASH_SHA256)
```

**Comment by dengert** [comment]
That is not the proper fix. OpenSC will call OpenSSL to do may of these digests in software. The card driver never see it. No other card I know of fails like this. 

Where is the debug log?

**Comment by vjardin** [comment]
Enclosed the logs:
[test.log.gz](https://github.com/OpenSC/OpenSC/files/6216098/test.log.gz)

**Comment by dengert** [comment]
The  dump does not show very much. But line 15012: ` [opensc-pkcs11] mechanism.c:200:sc_pkcs11_md_init: returning with: 5` does not matchup  with the OpenSC source code from master. Line 200 in `mechanism.c`  is not a line that would have returned a message. What version of the source are you using?

What version of OpenSSL are you using? Does it support  RIPEMD160?

Unfortunately, OpenSSL does not do a good job of logging OpenSSL errors.
Try testing with this:
[openssl-digest-error.diff.txt](https://github.com/OpenSC/OpenSC/files/6216235/openssl-digest-error.diff.txt)
The problem maybe the version of OpenSSL you have does not support the digest?
if so the return should not be CKR_GENERAL_ERROR;
but rather CKR_FUNCTION_NOT_SUPPORTED;

**Comment by vjardin** [comment]
The OpenSSL from my setup is broken. I'm rerunning the tests using a "fresh" Ubuntu 20.04 with its pristine OpenSSL and then I do not have any RIPEMD160 issue. Sorry for the "noises".
