### ISSUE TITLE
C_Sign for ECDSA fails if input is larger than key size

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#2283]
### Problem Description

When doing a routinely retest of the OpenSC master against the SmartCard-HSM we've come across a failing signature created with C_Sign using CKM_ECDSA_SHA1 on a secp192 curve. Apparently the produced signature fails verification if the input length exceeds 24 byte, which equals the key length.

This issue is not present in the latest 0.21.0 release, so it's probably introduced after that release.

### Proposed Resolution

Find and revise the commit that introduced the problem.

### Steps to reproduce

Using p11-test from the SmartCard-HSM workspace in the starterkit.

**Comment by CardContact** [comment]
Apparently the input is truncated along the way:

33: C_Sign
2021-03-31 17:26:59.092
[in] hSession = 0x7fef7807ad10
[in] pData[ulDataLen] 00007fef5ce00050 / 255
    00000000  00 C5 8B 5D EF 9D 12 77 4A 04 7B 02 03 36 05 D8  ...]...wJ.{..6..
    00000010  A5 92 D7 46 48 F0 E5 BD 68 2F EE 83 8D 48 29 62  ...FH...h/...H)b
    00000020  52 E1 09 EB 93 A8 4E A0 24 34 95 70 40 0F 15 87  R.....N.$4.p@...
    00000030  00 B2 8D 0A 40 B6 0C 19 44 23 C5 BF 5D E2 D6 A7  ....@...D#..]...
    00000040  81 AF FB 79 E7 DD E4 4D 0E E8 D3 46 9D A2 E8 77  ...y...M...F...w
    00000050  AD 22 E3 BE 87 44 4B 94 71 60 12 A1 DF 1E B6 71  ."...DK.q`.....q
    00000060  B7 01 E5 12 A4 FB 6D 55 45 79 B1 6F 78 47 84 E0  ......mUEy.oxG..
    00000070  45 F9 A4 3E 92 01 D5 89 83 F1 FE BC 57 25 2B 5D  E..>........W%+]
    00000080  44 88 91 09 B8 86 C1 39 B4 E0 FD CA 83 18 F1 A1  D......9........
    00000090  11 6F 33 EA 1C EE D6 80 01 C0 C3 6D EE 0A 6E D5  .o3........m..n.
    000000A0  61 D4 B3 14 9B F9 3E 98 71 CF 19 EB A0 B2 8B 8B  a.....>.q.......
    000000B0  E6 4D 85 D2 21 EF ED D7 FD AE C5 C8 2E 63 9F 21  .M..!........c.!
    000000C0  4A 48 E5 0F DE 78 EA A1 A8 36 9D DA 31 86 F7 5F  JH...x...6..1.._
    000000D0  36 BD C9 EC B2 F5 F3 2E 37 EF 04 5B 4A E7 EB 75  6.......7..[J..u
    000000E0  96 9F F1 18 9C 3F C5 A0 1D 31 77 87 7A 0E 99 5C  .....?...1w.z..\
    000000F0  9D D4 AE 22 97 A3 26 6B 02 E5 1A 06 84 6B 42     ..."..&k.....kB 
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] misc.c:290:session_get_operation: called
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] framework-pkcs15.c:3823:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] framework-pkcs15.c:3823:pkcs15_prkey_get_attribute: pkcs15_prkey_get_attribute() called
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] framework-pkcs15.c:3867:pkcs15_prkey_get_attribute: found friend certificate's public key 0x7fef78072a10
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] mechanism.c:524:sc_pkcs11_signature_size: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] mechanism.c:361:sc_pkcs11_sign_size: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] mechanism.c:293:sc_pkcs11_sign_update: called
P:11573; T:0x140666032105216 17:26:59.092 [opensc-pkcs11] misc.c:290:session_get_operation: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:439:sc_pkcs11_signature_update: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:440:sc_pkcs11_signature_update: data part length 255
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:452:sc_pkcs11_signature_update: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:309:sc_pkcs11_sign_update: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:319:sc_pkcs11_sign_final: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] misc.c:290:session_get_operation: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] mechanism.c:462:sc_pkcs11_signature_final: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] framework-pkcs15.c:4087:pkcs15_prkey_sign: Initiating signing operation, mechanism 0x1042.
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] card.c:473:sc_lock: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] reader-pcsc.c:685:pcsc_lock: called
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] framework-pkcs15.c:4238:pkcs15_prkey_sign: Selected flags 200. Now computing signature for 255 bytes. 48 bytes reserved.
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] pkcs15-sec.c:588:sc_pkcs15_compute_signature: called
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] pkcs15-sec.c:637:sc_pkcs15_compute_signature: supported algorithm flags 0x80312300, private key usage 0xC
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] padding.c:470:sc_get_encoding_flags: called
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] padding.c:474:sc_get_encoding_flags: iFlags 0x200, card capabilities 0x80312300
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] padding.c:528:sc_get_encoding_flags: pad flags 0x0, secure algorithm flags 0x200
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] padding.c:529:sc_get_encoding_flags: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] pkcs15-sec.c:710:sc_pkcs15_compute_signature: DEE flags:0x00000200 alg_info->flags:0x80312300 pad:0x00000000 sec:0x00000200
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] card.c:473:sc_lock: called
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] sec.c:105:sc_set_security_env: called
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] card-sc-hsm.c:1024:sc_hsm_set_security_env: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] sec.c:109:sc_set_security_env: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] sec.c:59:sc_compute_signature: called
P:11573; T:0x140666032105216 17:26:59.094 [opensc-pkcs11] apdu.c:548:sc_transmit_apdu: called
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] card.c:473:sc_lock: called
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] card.c:513:sc_lock: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] apdu.c:515:sc_transmit: called
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:80, INS:68, P1:1, P2:71, data(24) 0x7fef5cdfef60
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] reader-pcsc.c:323:pcsc_transmit: reader 'Identiv uTrust 3512 SAM slot Token [CCID Interface] (55511639600826) 00 00'
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (33 bytes):
80 68 01 71 00 00 18 00 C5 8B 5D EF 9D 12 77 4A .h.q......]...wJ
04 7B 02 03 36 05 D8 A5 92 D7 46 48 F0 E5 BD 02 .{..6.....FH....
00                                              .
P:11573; T:0x140666032105216 17:26:59.095 [opensc-pkcs11] reader-pcsc.c:242:pcsc_internal_transmit: called
P:11573; T:0x140666032105216 17:26:59.139 [opensc-pkcs11] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (57 bytes):
30 35 02 18 05 87 6D EA 46 2B 0A AF DC E9 97 90 05....m.F+......
98 68 1B 58 5F AE 40 F1 12 6A 69 A6 02 19 00 E8 .h.X_.@..ji.....
22 15 48 4C 95 FB F2 20 D5 2B 9B 6A 02 5A 56 B9 ".HL... .+.j.ZV.
75 38 82 AA 22 5F 36 90 00                      u8.."_6..
P:11573; T:0x140666032105216 17:26:59.139 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.139 [opensc-pkcs11] apdu.c:537:sc_transmit: returning with: 0 (Success)
P:11573; T:0x140666032105216 17:26:59.139 [opensc-pkcs11] card.c:523:sc_unlock: called

**Comment by CardContact** [comment]
Issue seems to be introduced by 6049cb9

**Comment by dengert** [comment]
It looks like https://github.com/OpenSC/OpenSC/commit/6049cb926c980754e18b16794e365a9370f4403e reverted some of the changes in 285db1ef2. 

285db1ef2  fixed some issues with card drivers such as card-myeid.c where setting:
```
      flags |= SC_ALGORITHM_ECDSA_HASH_NONE | SC_ALGORITHM_ECDSA_HASH_SHA1;
      flags |= SC_ALGORITHM_ECDSA_HASH_SHA224 | SC_ALGORITHM_ECDSA_HASH_SHA256;
      flags |= SC_ALGORITHM_ECDSA_HASH_SHA384 | SC_ALGORITHM_ECDSA_HASH_SHA512;
```

When a card driver sets flags, it is saying the card or the card driver will do the hash. If not set in the driver
then OpenSC will do the hashing.   (card-epass2003.c can do hashing in the card driver.)

It looks like card-sc-hsm.c sets these flags:
```
                SC_ALGORITHM_ECDSA_HASH_SHA1|
                SC_ALGORITHM_ECDSA_HASH_SHA224|
                SC_ALGORITHM_ECDSA_HASH_SHA256|
```
It looks like it can do the hash on the card or not. Can you verify what the card can do?
```
P:11573; T:0x140666032105216 17:26:59.093 [opensc-pkcs11] framework-pkcs15.c:4238:pkcs15_prkey_sign: Selected flags 200. Now computing signature for 255 bytes. 48 bytes reserved.
```
says input data is 256  with 48 bytes for the signature. But 
```
Outgoing APDU (33 bytes):
80 68 01 71 00 00 18 00 C5 8B 5D EF 9D 12 77 4A .h.q......]...wJ
04 7B 02 03 36 05 D8 A5 92 D7 46 48 F0 E5 BD 02 .{..6.....FH....
00 
```
looks like it is sending a hash. I don't see where the hash is being done. 

It looks like https://github.com/OpenSC/OpenSC/commit/6049cb926c980754e18b16794e365a9370f4403e is 
not checking first if the card will do the hash on the card or in card driver, doing hash when it should not. 

OpenSC should not do the to hash is software until after padding.c:474 has split up what should be done is software and what the card can do. (This routing should be rename, as it is called for EC keys too, and does more then look at padding.) 

If card-sc-hsm can not do the hash on the card can you try removing these lines: 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-sc-hsm.c#L1637-L1639

**Comment by dengert** [comment]
Looking closer, and from your comment: "Apparently the input is truncated along the way" and it is not doing the hash early. The truncation may be happening here: https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-sec.c#L733-L742
If you can uses a debugger and step through this and check logic. senv.flags  should by 0x200 i.e. do the sha1 in driver or card. and this truncation should not done.

**Comment by dengert** [comment]
The bug appears to be here. The wrong flags were being tested.
Tested with 401 bytes /tmp/input.txt file with this command:

```
pkcs11-tool --sign --login --pin 123456 --id 10 -m ECDSA-SHA1 -o /tmp/sig.rs -i /tmp/input.txt
```
The input data was truncated. With this change the full 401 bytes was passed to the card.
```
diff --git a/src/libopensc/pkcs15-sec.c b/src/libopensc/pkcs15-sec.c
index 249cb062..4fa623ff 100644
--- a/src/libopensc/pkcs15-sec.c
+++ b/src/libopensc/pkcs15-sec.c
@@ -737,7 +737,7 @@ int sc_pkcs15_compute_signature(struct sc_pkcs15_card *p15card,
         * But if card is going to do the hash, pass in all the data
         */
        else if (senv.algorithm == SC_ALGORITHM_EC &&
-                       (senv.flags & SC_ALGORITHM_ECDSA_HASHES) == 0) {
+                       (senv.algorithm_flags & SC_ALGORITHM_ECDSA_HASHES) == 0) {
                inlen = MIN(inlen, (prkey->field_length+7)/8);
        }
 ```

Tested with command  a 401 bytes /tmp/input.txt file, using 
```
pkcs11-tool --sign --login --pin 123456 --id 10 -m ECDSA-SHA1 -o /tmp/sig.rs -i /tmp/input.txt
```
using a SmartCard-HSM:
```
Slot 0 (0x0): SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
  token label        : SmartCard-HSM (UserPIN)
  token manufacturer : www.CardContact.de
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 24.13
  firmware version   : 1.2
  serial num         : DECC0100248
  pin min/max        : 6/15
```

The bug would only affect cards that could do ECDSA with hashing on the card, in_len was greated then ` (prkey->field_length+7)/8`

**Comment by CardContact** [comment]
The card supports both, plain ECDSA (Alg 70) and variants with hash in the card (Alg 71,72,73).

Your SmartCard-HSM is a pretty old (Version 1.2 from 2013). If you send me an address by PM, then I'll send you a current version. The API hasn't changed in that area.

**Comment by Jakuje** [comment]
Seems like we would like to get this into the next release. @CardContact does the proposed patch from Doug solve the issue for you?

**Comment by dengert** [comment]
`grep SC_ALGORITHM_ECDSA_HASH_SHA card-*` shows card-sc-hsm.c , card-epass2003.c and card-isoApplet.c  have support for the ECDSA  hashing on the card or in the driver and need the proposed fix. 

The code was introduced in 587a29b7f in 2016-04-25. An application could try and do a ECDSA signature of data which is larger then the key can handle.

**Comment by CardContact** [comment]
Tests passed after applying the fix. @dengert Will you create a pull-request for it ?

Btw. if the the problem was introduced in 587a29b, why does it still work in 0.21 ?

**Comment by Jakuje** [comment]
If I read it right, this code was touched in https://github.com/OpenSC/OpenSC/commit/285db1ef298bb7d78ccf16cbb644a0e6b79584e6#diff-9e226c919182bd11e4500559cbfcb1c0def82d629c18c7a7cc34e6f4bb14d01eL700 It probably did the right thing before, but after reshuffling of the flags it broke.

**Comment by dengert** [comment]
I will create a PR.
