### ISSUE TITLE
On Windows, use LoadLibraryEx with LOAD_WITH_ALTERED_SEARCH_PATH if absolute path is given

### ISSUE THREAD

**Issue by qpernil** [OpenSC/OpenSC#2291]
### Problem Description

If a PKCS11 module is specified with an absolute path on Windows, and it has dependencies in the same directory (i.e. other DLLs it uses) those will not be found by LoadLibrary, which only searches the standard library path plus the directory the application that loads it was launched from, so it will fail to load the PKCS11 module with no indication why. 

### Proposed Resolution

Use LoadLibraryEx with the LOAD_WITH_ALTERED_SEARCH_PATH flag if the path given is absolute (LOAD_WITH_ALTERED_SEARCH_PATH requires an absolute path according to docs), and with a 0 flag if not. This will work the same as now for non-absolute paths, but will fix the above problem.

### Steps to reproduce

See problem description

### Logs

See for example https://github.com/Pkcs11Interop/Pkcs11Interop/pull/143

**Comment by frankmorgner** [comment]
as far as I can see, this is only a problem for pkcs11-tool. OpenSC is linking all requirements statically to avoid these kinds of problems.

would you care to make a pull request?

**Comment by qpernil** [comment]
I fixed the pull request, it seems to build now (except the last build failed but that looks temporary)
