### ISSUE TITLE
BELPIC v1.8 not supported

### ISSUE THREAD

**Issue by francois4224** [OpenSC/OpenSC#2305]
The new BELPIC v1.8 is not supported

The main change is the replacement of RSA keys with ECDSA keys

More info:
[BELPIC v1.8](https://github.com/Fedict/eid-mw/blob/master/doc/sdk/documentation/Applet%201.8%20eID%20Cards/Public_Belpic_Applet_v1%208_Ref_Manual_v1%20.pdf)

**Comment by jim-6jf-be** [comment]
Question:

Commit  [9d6ddae] (https://github.com/OpenSC/OpenSC/commit/9d6ddaef13472cb7aaafc1b418937493f44bc422) on 30 Nov 2021added support to belpic v1.8 applet ATR.

Does it need someelse to support new BELPIC v1.8 eid ?
