### ISSUE TITLE
Can't install on Macbook

### ISSUE THREAD

**Issue by eugeis** [OpenSC/OpenSC#2310]
### Problem Description

Hello, I can't install the OpenSC 0.21.0.pkg on Macbook because of following message
“OpenSC 0.21.0.pkg” can’t be opened because Apple cannot check it for malicious software.

Also some workarounds, (Ctrl + Open), or open from Security & Privacy>General tab is not working, see screetshot.
I was also not able to find any other signed realeases.

Please some ideas, how to install. Thx
 
<img width="869" alt="Screenshot 2021-04-26 at 11 57 02" src="https://user-images.githubusercontent.com/609363/116065322-31216500-a687-11eb-9620-449995adc636.png">

**Comment by metsma** [comment]
Right click and select open from finder

**Comment by eugeis** [comment]
"Right click and select open from finder", unfortunately not working.

<img width="679" alt="Screenshot 2021-04-26 at 12 32 45" src="https://user-images.githubusercontent.com/609363/116069348-8f504700-a68b-11eb-9874-a85026fe5830.png">
<img width="545" alt="Screenshot 2021-04-26 at 12 32 32" src="https://user-images.githubusercontent.com/609363/116069354-90817400-a68b-11eb-9fc6-ee6ba8a3cf9f.png">

**Comment by eugeis** [comment]
It seems to be additionally blocked by some corporate settings on my Macbook.

**Comment by mouse07410** [comment]
You have the option of building it from the source yourself. That might work with the corporate config enforced on your machine.

**Comment by eugeis** [comment]
> You have the option of building it from the source yourself. That might work with the corporate config enforced on your machine.

thanks for info!

**Comment by stefanlasiewski** [comment]
For the record, I ran into this issue just today with OpenSC v0.25.0 and macOS Sonoma 14.2.1 (23C71).

Seems like the packages are missing some sort of metadata or certificate?

![image](https://github.com/OpenSC/OpenSC/assets/142752/e1c0c1d3-d2f9-4425-8160-29fc6bf449b4)

**Comment by metsma** [comment]
I think this is related that package is not notarized.
There is workaround to use right click and select open. Then it allows to execute the installer.

**Comment by al3xnag** [comment]
If "Right click and select open from finder" isn't working for you, follow this guide https://support.apple.com/guide/mac-help/mh40616/mac
