### ISSUE TITLE
pkcs11-register.exe command open

### ISSUE THREAD

**Issue by fabrizius86** [OpenSC/OpenSC#2312]
Good morning,
i have an issue on my pc when it starts, a windows command shows with pkcs11-register.exe and this window remains open.

The open sc doesn't work and firefox crash when i open it, any solution?

Thank you very much

**Comment by frankmorgner** [comment]
Could you paste the contents of `%APPDATA%/Mozilla/Firefox/profiles.ini`?

**Comment by fabrizius86** [comment]
In attach the file that you request.

Thank you

Fabrizio Ronzulli
Systems and Networking
ICT

***@***.******@***.***>
Phone +390321790388
Mobile +393346200948
Esseco
Via San Cassiano 99
28069 San Martino di Trecate
Novara - Italy
[http://www.essecogroup.com/cartellaimmagini/esseco.jpg]
www.esseco.it <http://www.esseco.it>

Da: Frank Morgner ***@***.***>
Inviato: mercoledì 28 aprile 2021 15:23
A: OpenSC/OpenSC ***@***.***>
Cc: Ronzulli Fabrizio ***@***.***>; Author ***@***.***>
Oggetto: [EXTERNAL] Re: [OpenSC/OpenSC] pkcs11-register.exe command open (#2312)


Could you paste the contents of %APPDATA%/Mozilla/Firefox/profiles.ini?

**Comment by frankmorgner** [comment]
It seems that this doesn't work via mail. please either paste the contents into the email text or upload it to the github issue directly

**Comment by frankmorgner** [comment]
Also, in the profiles directory there should be a file `pkcs11.txt`. Could you upload that as well?

**Comment by fabrizius86** [comment]
Ok.

Profiles.ini

--
[Install308046B0AF4A39CB]
Default=Profiles/0zfhyi3z.default-release-1619594447838
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=Profiles/uor6aomc.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/0zfhyi3z.default-release-1619594447838

[General]
StartWithLastProfile=1
Version=2
--

Pkcs11.txt

--
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:C:\\Users\\MONTOR~1\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\0ZFHYI~1.DEF' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription=''
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})
--


Fabrizio Ronzulli
Systems and Networking
ICT

***@***.******@***.***>
Phone +390321790388
Mobile +393346200948
Esseco
Via San Cassiano 99
28069 San Martino di Trecate
Novara - Italy
[http://www.essecogroup.com/cartellaimmagini/esseco.jpg]
www.esseco.it <http://www.esseco.it>

Da: Frank Morgner ***@***.***>
Inviato: mercoledì 28 aprile 2021 15:49
A: OpenSC/OpenSC ***@***.***>
Cc: Ronzulli Fabrizio ***@***.***>; Author ***@***.***>
Oggetto: [EXTERNAL] Re: [OpenSC/OpenSC] pkcs11-register.exe command open (#2312)


Also, in the profiles directory there should be a file pkcs11.txt. Could you upload that as well?

**Comment by frankmorgner** [comment]
that didn't work please go to the github website and do it there

**Comment by frankmorgner** [comment]
please re-open if you have more input
