### ISSUE TITLE
make distcheck failures

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2319]
### Problem Description

`make distcheck` fails
```
make[4]: Entering directory 'OpenSC/opensc-0.22.0-rc1/_build/sub/tests'
FAIL: test-manpage.sh
PASS: test-duplicate-symbols.sh
SKIP: test-pkcs11-tool-sign-verify.sh
SKIP: test-pkcs11-tool-test.sh
SKIP: test-pkcs11-tool-test-threads.sh
SKIP: test-pkcs11-tool-allowed-mechanisms.sh
============================================================================
Testsuite summary for OpenSC 0.22.0-rc1
============================================================================
# TOTAL: 6
# PASS:  1
# SKIP:  4
# XFAIL: 0
# FAIL:  1
```
because of
```
SKIP: test-pkcs11-tool-sign-verify.sh
=====================================

../../../tests/test-pkcs11-tool-sign-verify.sh: line 3: common.sh: No such file or directory
```
 since the commit 8c99e5076a829af618d0cb7ebb2b0b80e51831e1 from @Jakuje 

 - the path for common.sh is not properly set (main issue)
 - chmod 755 common.sh is missing (minor)

**Comment by vjardin** [comment]
If we enforce the path to `common.sh` , then it fails again on some more issues that seem to be related to this commit:
```
[...]
Missing manual page for 'westcos-tool'
FAIL test-manpage.sh (exit status: 1)

FAIL: test-pkcs11-tool-sign-verify.sh
=====================================

Testing /usr/local/lib/softhsm/libsofthsm2.so
Testing /usr/lib/softhsm/libsofthsm2.so
Setting P11LIB=/usr/lib/softhsm/libsofthsm2.so
=======================================================
Setup SoftHSM
=======================================================
mkdir: cannot create directory ‘.tokens’: File exists
The token has been initialized and is reassigned to slot 891755977
```

I do not understand the logic of this commit, please @Jakuje , can you check it again ?

**Comment by vjardin** [comment]
Please @LudovicRousseau , can you comment what should be done with `make distcheck` ? It seems to be a dead build capability.

**Comment by LudovicRousseau** [comment]
I don't know what you call a "dead build capability".

`make distcheck` does create the `.tar.gz` file and then tries to build the software from the extracted archive. An error will indicate a missing file in the archive or a incorrect path.

It looks like your problem is with `make check` and not `make distcheck`.

**Comment by vjardin** [comment]
Other folks from this community seems to push 'make dist'. What should the gold standard be ?

I understand they are not the same (https://www.gnu.org/software/automake/manual/html_node/Preparing-Distributions.html) but which ones should be used ? Since this last year commit that introduced common.sh, it got broken. I agree with you that if distcheck is required, it should be part of the CI. But if it is not used by the CI, does it mean that it should still be used ?

**Comment by Jakuje** [comment]
Thanks for testing this! Indeed, this should be in CI to prevent issues with missing files from release, which we already had before.

There are more issues with this that need to be fixed, for example out-of-the-tree build fails when clang-tidy can not find the source files. The `make dist` is already part of the travis build. The `distcheck` is complicated that it runs the build and tests all over again, which quite doubles the time
