### ISSUE TITLE
certutil -scinfo fails

### ISSUE THREAD

**Issue by vjardin** [OpenSC/OpenSC#2321]
### Problem Description

On windows, most tools work (pkcs11-tool --test OK, firefox OK, ssh-keygen -D + ssh -I OK), but `certutil -scinfo` fails with the following error:
```
C:\Program Files\OpenSC Project\OpenSC\pkcs11>certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Gemalto USB SmartCard Reader 0
--- Reader: Gemalto USB SmartCard Reader 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
--- Status: The card is being shared by a process.
---   Card:
---    ATR:
        3b ac 00 40 2a 00 12 25  00 64 80 00 03 10 00 90   ;..@*..%.d......
        00                                                 .


=======================================================
Analyzing card in reader: Gemalto USB SmartCard Reader 0
SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for
--------------===========================--------------
CertUtil: -SCInfo command FAILED: 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
```

I do not have any idea how to debug/trace it.

**Comment by dengert** [comment]
`./win32/customactions.cpp` needs to be updated with ATRs for your cards and driver.

**Comment by vjardin** [comment]
Thanks, I'll try it. For my information, why all drivers from OpenSC do not get their ATRs included automatically ? Is it on purpose ?

**Comment by dengert** [comment]
Windows is 74% of desktop market according to: https://gs.statcounter.com/os-market-share/desktop/worldwide so vendors will provide a windows driver. Some actually add support to OpenSC so they don't have to write their own! But most don't want to put in the effort to support anything but Windows and maybe Mac OS.  Microsoft provides a Microsoft PIV driver that looks for PIV AID  not the ATR.  MacOS also does or used to support PIV driver. (Someone else can comment on that.)  Gov issued ID or health smartcards have a vendor provided driver and users use or have access to a windows machine to uses these cards. 

So OpenSC is covering is filling the gap for the linix niche market and is a few cases provided support where the vendor does not.    

So if your card is one of these Gov issued ID or health card and works with the vendors driver. We should not be enabling it just because we can.

**Comment by frankmorgner** [comment]
It would be possible to customize this during installation (via WiX Toolset) so that the user can decide which cards to enable via minidriver. Unfortunately, we never had time to implement this...

**Comment by vjardin** [comment]
Good idea @frankmorgner : I just tried to install vcbuildtools 2015 like I did few days ago for another issue (but then I dropped it I needed some disk space), but it seems it has been deprecated :( , few others are complaining https://community.chocolatey.org/packages/vcbuildtools 

Does anyone know another way to get a community native Microsoft toolchain that works with OpenSC ?

**Comment by vjardin** [comment]
Back to this windows setup: it seems that the logic from https://github.com/OpenSC/OpenSC/blob/32004e74ceeb2ce346ef8e0cf37fbe663320ccf0/win32/customactions.cpp#L274 could be into a specific standalone application or script that would register or unregister any ATRs later after the finalization of the setup. It does not require to be part of the MSI, does it ?

**Comment by frankmorgner** [comment]
the visual studio community version should be good enough to build OpenSC.

Ideally, things should work out of box. But having a GUI interface would be very helpful, also for other things... We already have opensc-notify, which shows Insertion/Removal notifications along with a notification icon in the taskbar. This program could be extended to have some mission control panel...

**Comment by vjardin** [comment]
Thanks @frankmorgner , I was able to get it yesterday evening.
I noted that many tests from the minidriver are failed:
```
..\tests\opensc-minidriver-test.exe -r "Gemalto USB SmartCard Reader 0" -a
Calling CardAcquireContext() - 0 : Passed
Calling CardQueryFreeSpace() - 0 : Passed
Calling CardGetProperty(CP_CARD_FREE_SPACE) - 0 : Passed
Calling CardQueryCapabilities() - 0 : Passed
Calling CardGetProperty(CP_CARD_CAPABILITIES) - 0 : Passed
Calling CardQueryKeySizes() - 0 : Passed
Calling CardGetProperty(CP_CARD_KEYSIZES) - 0 : Passed
Calling CardGetProperty(CP_CARD_READ_ONLY) - 0 : Passed
Calling CardGetProperty(CP_CARD_CACHE_MODE) - 0 : Passed
Calling CardGetProperty(CP_SUPPORTS_WIN_X509_ENROLLMENT) - 0 : Passed
Calling CardGetProperty(CP_CARD_GUID) - 0 : Passed
Calling CardGetProperty(CP_CARD_SERIAL_NO) - 0 : Passed
Calling CardGetProperty(CP_CARD_PIN_INFO) - 0 : Passed
Calling CardGetProperty(CP_CARD_LIST_PINS) - 0 : Failed
Calling CardGetProperty(CP_CARD_AUTHENTICATED_STATE) - 80100004 : Failed
Calling CardGetProperty(CP_CARD_PIN_STRENGTH_VERIFY) - 80100004 : Failed
Calling CardGetProperty(CP_KEY_IMPORT_SUPPORT) - 0 : Passed
Calling CardReadFile(cardid) - 0 : Passed
Calling CardReadFile(cardcf) - 0 : Passed
Calling CardReadFile(cardapps) - 0 : Passed
Calling CardReadFile(mscp/cmapfile) - 0 : Passed
Calling CardReadFile(mscp/msroots) - 80100024 : Failed
Calling CardGetFileInfo(mscp/cmapfile) - 0 : Passed
Calling CardReadFile(mscp/kxc00) - 80100024 : Failed
Calling CardEnumFiles(root) - 0 : Passed
Calling CardGetContainerInfo(0) - 0 : Passed
Calling CardAuthenticatePin(wszCARD_USER_USER) - 8010006b : Failed
Calling CardGetProperty(CP_CARD_AUTHENTICATED_STATE) - 80100004 : Failed
Calling CardAuthenticatePin(wszCARD_USER_USER) - Wrong PIN - 8010006b : Failed
Calling CardGetProperty(CP_CARD_AUTHENTICATED_STATE) - 80100004 : Failed
Calling CardAuthenticatePin(wszCARD_USER_USER) - 8010006b : Failed
Calling CardGetProperty(CP_CARD_AUTHENTICATED_STATE) - 80100004 : Failed
Calling CardDeAuthenticate(wszCARD_USER_USER) - 0 : Passed
Calling CardGetProperty(CP_CARD_AUTHENTICATED_STATE) - 80100004 : Failed
Calling CardDeleteContext() - 0 : Passed
Unit test finished.
35 tests performed.
12 tests failed.
```

**Comment by vjardin** [comment]
I updated `customactions.cpp`, the outcome is available into the registry database:
![image](https://user-images.githubusercontent.com/8383368/117048064-de911a00-ad12-11eb-91f2-31ac9f8fe852.png)

But I keep having the same error:
```
# certutil -scinfo
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: Gemalto USB SmartCard Reader 0
--- Reader: Gemalto USB SmartCard Reader 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
---   Card:
---    ATR:
        3b ac 00 40 2a 00 12 25  00 64 80 00 03 10 00 90   ;..@*..%.d......
        00                                                 .
=======================================================
Analyzing card in reader: Gemalto USB SmartCard Reader 0
SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for SCardGetCardTypeProviderName: The system cannot find the file specified. 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
Cannot retrieve Provider Name for
--------------===========================--------------
CertUtil: -SCInfo command FAILED: 0x2 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
```

**Comment by dengert** [comment]
Something to look at:

Did you have a vendor minidriver installed on this system before? 
Or did Windows every see this card before? 
Windows caches certificates. Look at control panel ->internet options -> content->certificates  and see if the certificate is
in the cache with or without the card present. Delete it if you can. 

Try with -v option too. 

Did you install both 64 and 32 bit versions of OpenSC?
Certutil.exe on my system looks like it is 64 bit, but some 32 bit process might be looking at it too.

This might also help:
https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetcardtypeprovidernamea

**Comment by vjardin** [comment]
There is nothing prior to this setup. I try only the 64 bit verison of OpenSC.

I just notice that thru the "Device manager", when I update the inf file (see [opensc-minidriver.inf](https://github.com/OpenSC/OpenSC/files/6424412/opensc-minidriver_inf.txt) with the proper ATR, I get:
![image](https://user-images.githubusercontent.com/8383368/117081739-cc2dd500-ad40-11eb-9d8d-737d6ca1772f.png)

**Comment by dengert** [comment]
Google for: ""Data of this type is not supported" There are many hits. One I found was:

[data-of-this-type-not-supported](http://windowsbulletin.com/fix-download-update-error-0x8007065e-data-of-this-type-not-supported/)

I don't believe you needed to modify any lines in the ".inf" file. These were a template for some other install program.   

`HKLM, %SmartCardNameWOW64%,"ATRMask",0x00000001,FF,00,00,00,00,FF,FF,FF,FF,FF,FF,00,00,00,FF,FF,FF,` and
`HKLM, %SmartCardNameWOW64%,"ATRMask",0x00000001,FF,00,00,00,00,FF,FF,FF,FF,FF,FF,00,00,00,FF,FF,FF,`
have extra "," at end. 

Make sure your card is not plugged during the OpenSC install, as Windows might try and get a vendor driver for it. 
 
Also, did you modify  opensc-minidriver_inf: 
```
SmartCardName="SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\Cev Westcos"
SmartCardNameWOW64="SOFTWARE\Wow6432Node\Microsoft\Cryptography\Calais\SmartCards\Cev Westcos"
```
to 
```
SmartCardName="SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\IAS/ECC CPx"
SmartCardNameWOW64="SOFTWARE\Wow6432Node\Microsoft\Cryptography\Calais\SmartCards\IAS/ECC CPx"
```
Or did the install process modify it from what was opensc-minidriver_inf.in`?  That should be a place holder. 
The only thing that might have happened is the "/" in the name was treated as a directory separator or as a command like option during the substitutions by some install program.   

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
"The following reserved characters: ... / (forward slash) ..."

But we do have a "FTCOS/PK-01C" with a "/' in the name, but not listed in the "[strings]" section.

**Comment by vjardin** [comment]
I tried without the '/', but it does not help yet. Thanks for the "," from the inf file, yes I did remove it yesterday too before posting the comments, sorry for using the obsoleted file.

Currently, `win32/customactions.cpp` does update the registry:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\IASECC CPx]
"Crypto Provider"="OpenSC CSP"
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"80000001"="C:\\Program Files\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"
"ATR"=hex:3b,ac,00,40,2a,00,12,25,00,64,80,00,03,10,00,90,00
"ATRMask"=hex:ff,00,00,00,00,ff,ff,ff,ff,ff,ff,00,00,00,ff,ff,ff
```
while I guess it should update:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Cryptography\Calais\SmartCards\IASECC CPx]
```
shouldn't it ?

**Comment by dengert** [comment]
You said: "I just notice that thru the "Device manager", when I update the inf file with the proper ATR, I get..."
I don't think you should do that.

On my system in Device manager (With "Show hidden devices" checked) I see grayed out Smart cards devices for the vendor's drivers:
    "IDEMA Minidriver for PIV/COV Smart Card"
    "Oberthur Technologies Minidriver for PIV Smart Card"
    (and some others for xPass and Unknown when I have a Nitro installed)

When I plug in a card **not** supported by OpenSC, I see the vendor's driver  is not grayed out:
    "IDEMA Minidriver for PIV/CIV Smart Card"
 
When I  plug in a card supported by OpenSC, I don't not see a smart card device.

But in the  "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards" I see 5 entries for the IDEMA cards supported by the vendor's driver and 2 for the Oberthur driver and all the 30 or so OpenSC smart card entries.  

Task Manager -> startup  runs a "OpenSC command line tool" that runs "pkcs11-register.exe"  It runs one for 32 bit if you installed both 64 and 32bit OpenSC entries in the "Calais". 

I think what is going on is you are try to install a "device driver" uasing the OpenSC inf does not work for a device driver. It works for registering in the "Calais" part of the registry. This may be caused  the "Crypto Provider" is "OpenSC CSP" which is not a Microsoft provider and the device manager does not know how to install. Or there is something else the device manager does not like about the OpenSC .inf file.    

But pkcs11-register.exe updates the registry at every login to make sure the minidriver can be used even if not listed as a device. 

The vendor of your card may provide a smart card driver of its own i.e. Microsoft downloaded the driver and  you may be seeing that driver.  You may have to uninstall it first using device manager. then log off and on and see if pkcs11-register.exe added it.
It does not like to over write existing drivers. 
 
TODO maybe OpenSC should not change the "Crypto Provider" but find a better way to registry one "Smart card" device like ever other vendor and multiple "Calais" entries for all the different ATRs.  But then the driver would then need to be signed. 

P.S. 
Anyone know why Microsoft uses "Calais"?  Is it because the smart card was invented in France in 1974 by https://en.wikipedia.org/wiki/Roland_Moreno

**Comment by vjardin** [comment]
Thanks for your helps @dengert ; currently, I keep having "Unknown Smart Card" from the device manager. opensc-notify.exe does the job of detecting the insertion and removal of the cards but it seems that the probing (ATR ?) is not operating based on the entry from the registry (Calais\Smartcard). I am wondering if scfilter is "firewalling" something ?! I just read it:
  https://docs.microsoft.com/fr-fr/windows/security/identity-protection/smart-cards/smart-card-debugging-information
I am going to try it and I'll share my findings.

**Comment by dengert** [comment]
You ATRMask does not look correct correct.
```
Actual        3b ac 00 40 2a 00 12 25 00 64 80 00 03 10 00 90 00      
"ATR"=    hex:3b,ac,00,40,2a,00,12,25,00,64,80,00,03,10,00,90,00
"ATRMask"=hex:ff,00,00,00,00,ff,ff,ff,ff,ff,ff,00,00,00,ff,ff,ff
"&"           3b,00,00,00,00,00,12,25,00,64,80,00,00,00,00,90,00 
```
if  (ATR == (ATR & ATRMask)) then a match.

Most cards uses all FF.

https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/smart-card-plug-and-play
"The smart card ATR value that is stored in the registry should be the expected value after the ATRMask has been applied to an ATR read from a smart card."

**Comment by vjardin** [comment]
Good catch! **Congratulation**. I had tried to set to 0xff directly into the registry database, but it did not work, so I gave up that path. I retried but using a fresh installation and setting 0xff from `win32/customactions.cpp` => certutil works !

I'll work on a reasonable patch with the proper mask.
