### ISSUE TITLE
OpenSC smartcard in Firefox and load certificate from token

### ISSUE THREAD

**Issue by Quarantainenet-ITservices** [OpenSC/OpenSC#2325]
If I install OpenSC and Putty-CAC and add opensc-pkcs11.dll to Putty (Category: -> Connection -> SSH -> Certificate -> 'Set PKCS Cert…') and to Pageant under 'View Keys & Certs'.  Every time when I start Firefox I get the message that the token can be used. When I go to Tools -> Options -> Privacy & Security -> Certificates in Firefox and then to "View Certificates" I see the certificate that is on the token and under "Security Devices" I see OpenSC smartcard framework (0.20). 

I find this quite annoying and do you have a solution for this, that the certificate is not loaded when you start Firefox?

**Comment by dengert** [comment]
If you are saying you do not want to use any smartcard with FireFox, you can go to Tools -> Options -> Privacy & Security ->Security Devices click on `OpenSC smartcard framework (0.20)` then click on `Unload` to tell FireFox to not load the OpenSC PKCS11 module. For most users, they have only one smartcard and want to use it with a browser.

**Comment by Quarantainenet-ITservices** [comment]
Hello Dengert, That is an option for one time, after a reboot of the laptop/desktop the OpenSC PKCS11 module is then reloaded.

**Comment by frankmorgner** [comment]
on Windows you can kill opensc-notify.exe.

Depending on the installation type, the registry entry can be found either in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` or `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run`. Just remove `opensc-notify.exe` from there.

On installation, you could disable the `Autostart entries` to avoid this behavior.

**Comment by dengert** [comment]
You can also use Task manager->Startup to Disable opensc-notify.exe so it will not startup the next time you login. You can also use Task manager to end any running task.

Notify will tell you when Smart card detected or removed even if no application is using it. When an application is using OpenSC,  notify will send pin verified and card is ready messages and pin verified. 

I normally disable opensc-notify.exe using Task manager, but still let FireFox load certificates, but use Chrome for my default browser.

**Comment by Quarantainenet-ITservices** [comment]
@frankmorgner, the option: disable the 'Autostart entries', was the trick. Thanks!
