### ISSUE TITLE
TRAVIS CI  Ubuntu 20.4 build failed

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#2330]
### Problem Description

For a few days it is a problem to compile OpenSC on Travis CI:

https://travis-ci.org/github/OpenSC/OpenSC/builds/769567620

This only applies to Ubuntu version 20.4 (focal) and the reason is the problem with installing the clang-tidy.
```
The following packages have unmet dependencies:
 clang-tidy : Depends: clang-tidy-10 (>= 10~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
This problem is documented at:
https://travis-ci.community/t/clang-10-was-recently-broken-on-linux-unmet-dependencies-for-clang-10-clang-tidy-10-valgrind/11527

### Proposed Resolution
There are several possible solutions: 
1. temporarily not use Ubuntu 20.4 and do build on Ubuntu 18
2. use the solution mentioned in the URL above
3. wait for TRAVIS CI to repair the preinstalled image

**Comment by vjardin** [comment]
2. is required. One needs to keep Ubuntu users happy. If the build is disabled from the CI we'll loose the benefits of the CI.

**Comment by Jakuje** [comment]
Fixed with #2331. I found the same link and fixed it before noticing this issue.

**Comment by Jakuje** [comment]
I was hoping the Travis will be able to fix it in some time, but it doe snot look like the case ...

**Comment by frankmorgner** [comment]
merged, thanks
