### ISSUE TITLE
D-Trust Card V4.1/V4.4 Is not recognized

### ISSUE THREAD

**Issue by github-nvo** [OpenSC/OpenSC#2348]
The new D-Trust Card V4.1/V4.4 will not be recogniced.

opensc-tool --list-readers --verbose
Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes   PIN pad   REINER SCT cyberJack RFID komfort
     3b:88:80:01:00:00:c9:04:77:81:73:00:41 Unsupported card [IN USE]

->> The old one V3 will
 opensc-tool --list-readers --verbose
Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes   PIN pad   REINER SCT cyberJack RFID komfort
     3b:d8:18:ff:81:b1:fe:45:1f:03:80:64:04:1a:b4:03:81:05:61 STARCOS 3.4 [IN USE]

Any idea?
Regards
Norbert

**Comment by frankmorgner** [comment]
what version are you using? Please have a look at https://github.com/OpenSC/OpenSC/issues/2296

**Comment by github-nvo** [comment]
Version:
opensc-tool -i
OpenSC 0.22.0-rc1 [gcc  4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
Enabled features: locking zlib readline pcsc(/System/Library/Frameworks/PCSC.framework/PCSC)

**Comment by github-nvo** [comment]
#2296 does the job
Now all is working finw
THX a lot
N-))


 /usr/local/bin/opensc-tool --verbose -list
OpenSC 0.22.0-rc1 [gcc  4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
Enabled features: locking zlib readline pcsc(/System/Library/Frameworks/PCSC.framework/PCSC)
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes   PIN pad   REINER SCT cyberJack RFID komfort
     3b:d2:18:00:81:31:fe:58:c9:04:11 Atos CardOS 
Using reader with a card: REINER SCT cyberJack RFID komfort
Connecting to card in reader REINER SCT cyberJack RFID komfort...
Using card driver Siemens CardOS.
Invalid APDU: Invalid data
