### ISSUE TITLE
removal of neverExtract from do_store_private_key

### ISSUE THREAD

**Issue by wkk2wkk2** [OpenSC/OpenSC#2360]
### Problem Description

Is there a reason do_store_private_key no longer sets alwaysSensitive and neverExtract, when a private key is imported, as was done in older versions of pkcs15_init.c?

### Proposed Resolution
A change might not be necessary if there is a reason for the change.

### Steps to reproduce
Import a private key and dump to show status of Access Flags.  Only "sensitive" is shown in 0.21.0.

**Comment by dengert** [comment]
I can not pin it down to a a specific PR. But PKCS11  base-V2.40 Says in table 25:
"CKA_SENSITIVE 8,11     CK_BBOOL    CK_TRUE if key is sensitive 9" and look in Table 10 which says:
"9 Default value is token-specific, and may depend on the values of other attributes."

If you are importing a private key to a token, then the key exists outside the token, and so CKA_ALWAYS_SENSITIVE==TRUE and CKA_NEVER_EXTRACTABLE==TRUE would be a lie, as the key is known to whomever imported the key.

The meaning of these two flags when true are that private key exists only on the token and it does not exist anywhere else.
For example signature keys created on the token which could have the flags set vs decryption keys that maybe escrowed in case the token is damaged and the key is not totally lost.

We are dealing with PKCS11, PKCS15 and different smartcards.  

I think there was a cleanup of the code to return more meaningful results. 

So I would ask why you would expect these flags to be set when you import a private key?

**Comment by frankmorgner** [comment]
please re-open if you have more questions
