### ISSUE TITLE
Migrate travis-ci to generic scripts and run in Github Actions

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#2361]
### Problem Description

The free travis-ci is gone and the new one requires OSS projects to request OSS credits every time they run out (or pay your own):

https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

### Proposed Resolution

I am not very happy with this business model so I would suggest to rewrite the CI to github-ci, which is now free and we hope it will stay for some time.

At this moment, the CI is long spaghetti yaml file with a lot of conditions to satisfy several runs. We should break it to several runs, probably collect the commands to separate scripts and share what is common (probably with functions or running other scripts) executing the same tasks we used to have on travis-ci

Status after merging #2362:
 * [x] OSX
   * [X] Setup
   * [X] Build
   * [x] Package signing
 * [X] Linux (Ubuntu 20)
   * [X] Setup
   * [X] Build
   * [X] clang-tidy
 * [ ] Other Linux (or Ubuntu version)
   * [X] Ubuntu 18
   * [ ] Other (would require containers with some limitations)?
 * [ ] Windows
   * [X] wine/mingw
   * [ ] Real windows?
 * [X] Tests
   * [X] virt_cacard (CAC)
   * [X] OSEiD (myeid)
   * [X] Java Card simulation
     * [X]  PIV
     * [X] IsoApplet
     * [X] GidsApplet
     * [X] OpenPGP
 * [ ] Refactor github-only stuff from the shell scripts
 * [x] Remove the .travis.yml
 * [x] Integrate Coverity Scan

**Comment by frankmorgner** [comment]
The title suggests gitlab-ci, but I think you mean github actions, right?

**Comment by Jakuje** [comment]
Indeed, you are right. Too many CI systems everywhere.

**Comment by Jakuje** [comment]
Update with what does not work:
 * The artifacts pushing to the nightly repo does not work.
   * Probably bad or missing `GH_TOKEN`. I can not check where does it come from and how does it work.
   * The artrifacts are uploaded to the github actions "cache", where they can be downloaded from 
 * The MacOS build signing
   * I don't have MacOS nor the signing certificate and key to reupload encrypted tarballs and check if they work
   * In the meantime, the unsigned dmg packages are available in the github actions "cache". Uploading to nightly does not work. See above.
 * The javacard tests are very flaky
   * The openpgp fails almost always
   * From time to time, other tests fail without apparent reason

I saw so far the following jcardsim failures:
```
    [junit] Running com.licel.jcardsim.crypto.KeyAgreementImplTest
    [junit] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.104 sec
```
or
```
Error:  Errors: 
Error:    com.licel.jcardsim.crypto.KeyAgreementImplTest#testGenerateSecretECDH ArrayIndexOutOfBoundsException
[INFO] 
Error:  Tests run: 138, Failures: 0, Errors: 1, Skipped: 0
```
There might be some non-determinism in the jcardsim test, which probably needs to be hunted down.

One other option might be to use the github actions to cache this step for all the tests we have with javacards to save some time and resources.

**Comment by dengert** [comment]
You may also want to include this patch https://github.com/dengert/OpenSC/commit/fff82e1e434ae9c8b77e38b2574ec2abc32d186e to Travis.yml part of the [PIV-4-extensions PR](https://github.com/OpenSC/OpenSC/pull/2053)

**Comment by Jakuje** [comment]
> You may also want to include this patch [dengert@fff82e1](https://github.com/dengert/OpenSC/commit/fff82e1e434ae9c8b77e38b2574ec2abc32d186e) to Travis.yml part of the [PIV-4-extensions PR](https://github.com/OpenSC/OpenSC/pull/2053)

Thanks for reminder. I will add it just after the release.

I will also take in #2377, #2375 and #2368 as it involves random crashes and then I will do the release.

**Comment by frankmorgner** [comment]
I've added Coverity Scan to the above list.

**Comment by Jakuje** [comment]
I already removed the `travis.yml` from the repository. About the coverity, thanks for bringing this up. I think I do not have the keys/credentials for that and I completely forgot about that. I think the package signing for Mac is already in place (if so, please mark it in the above list).

**Comment by Jakuje** [comment]
I would consider this complete. Coverity scan now runs from #2487, package signing is in #2394. Other Linux and Windows targets are more like a stretch goals, that would be great, but we can live without for now.

**Comment by Jakuje** [comment]
Closing as solved.
