### ISSUE TITLE
'opensc-tool' and 'scriptor' generate different responses from NIST Version 1 PIV card

### ISSUE THREAD

**Issue by srsross** [OpenSC/OpenSC#2369]
### Problem Description

I am using the first PIV card from the set of 16 PIV cards supplied by the National Institute of Standards and Technology (NIST).  This is a card from the Verision **1** set (as opposed to the Version **2** set).

When I execute the `opensc-tool --send-apdu` command with the SELECT card command, the PIV card responds differently than when I use the `scriptor` command.  In particular, the card's response to `scriptor` shows that there are more bytes to be read, namely, the Application Property Template (APT).  This seems like the correct response.  In contrast, the card's response to `opensc-tool` is success (namely, `90 00`) without an indication of more bytes.  (See the log of my command-line interaction below.)

Why is the response different? 

For what it is worth, when I use the first card from the NIST Version **2** set of 16 cards, both `opensc-tool` and `scriptor` return `90 00`.  However, this response is confusing too, because (as I read the NIST document SP800-73-4), I expect the SELECT command to respond with the bytes for the APT (as the Version **1** card does with `scriptor`).

(On Fedora 32, I am using `opensc-0.20.0-6.fc32` for `opensc-tool` and `pcsc-tools-1.5.4-2.fc32` for `scriptor`.)

Thanks in advance for any insight that you can offer,
-- Steve Ross

### Proposed Resolution
_none_
### Steps to reproduce
_See log._
### Logs
```
$ scriptor
No reader given: using SCM Microsystems Inc. SCR 3310 [CCID Interface] (53311549211615) 00 00
Using T=0 protocol
Reading commands from STDIN
reset
> RESET
< OK: 3B 7D 96 00 00 80 31 80 65 B0 83 11 17 D6 83 00 90 00
# Send the SELECT card command with the PIV Card Application AID.
00 a4 04 00 09 a0 00 00 03 08 00 00 10 00
> 00 a4 04 00 09 a0 00 00 03 08 00 00 10 00
< 61 13 : 0x13 bytes of response still available.
# Note that the SW1 byte is 0x61.
# Retrieve 0x13 response bytes with the GET RESPONSE command.
00 C0 00 00 13
> 00 C0 00 00 13
< 61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00
00 03 08 90 00 : Normal processing.
# The above returned data is the Application Property Template (APT) with Tag 0x61.
^C
$ Send the same SELECT card APDU to the card by using "opensc-tool".
$ opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00"
Using reader with a card: SCM Microsystems Inc. SCR 3310 [CCID Interface] (53311549211615) 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00
Received (SW1=0x90, SW2=0x00)
$ # The response is "no error" and so  doesn't indicate the bytes of the APT should be available.
```

**Comment by dengert** [comment]
The opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00"
needs an extra 00 on the end. This would be the Le == 00 indicating wanting additional data.

Without the Le opensc-tool is ignoring the  '6113'  and saying '9000' This is a idiosyncrasy of opensc-tool. If you have opensc debugging turn on, you will see that the the '6113' is actually returned. 


I am not familiar with scriptor. 

Using the NIST Beta Test Card  card 1 from 2006(?)  (T=0) for example:
```
$ ./opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 
Received (SW1=0x90, SW2=0x00)

$ ./opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00 
Received (SW1=0x90, SW2=0x00):
61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00 a.O.......y.O...
00 03 08  
```                              
Using DEMO Card  card 2 (T=1) (Gemalto PIV 1.5.5 DLv1) '
```
$ ./opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 
Received (SW1=0x90, SW2=0x00)

$ ./opensc-tool --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00 
Received (SW1=0x90, SW2=0x00):
61 39 4F 0B A0 00 00 03 08 00 00 10 00 01 00 79 a9O............y
07 4F 05 A0 00 00 03 08 50 0E 49 44 2D 4F 6E 65 .O......P.ID-One
20 50 49 56 20 42 49 4F 5F 50 10 77 77 77 2E 6F  PIV BIO_P.www.o
62 65 72 74 68 75 72 2E 63 6F 6D 7F 66 08 02 02 berthur.com.f...
80 00 02 02 80 00 
```

**Comment by dengert** [comment]
Correction: the card 1 is the (T=0) (Gemalto PIV 1.5.5 DLv1)
Card 2 is an Oberthur ID-One PIV

**Comment by srsross** [comment]
Re-opening after accidentally closing.

**Comment by dengert** [comment]
I don't see any reason to change opensc's handling of the --send-apdu  presence or absence of the Le is up to the to the use. But the  https://github.com/OpenSC/OpenSC/blob/master/doc/tools/opensc-tool.1.xml could use some explanation of how Lc and Le are handled.

**Comment by srsross** [comment]
Hi @dengert ,

Thanks for your response.  And thanks for your work on OpenSC for PIV cards.

You wrote:
> Without the Le opensc-tool is ignoring the '6113' and saying '9000' This is a idiosyncrasy of opensc-tool. If you have opensc debugging turn on, you will see that the the '6113' is actually returned.

Thanks for the suggestion to turn on debugging.  Prior to your suggestion, I had naïvely assumed that the `opensc-tool --send-apdu` command would send **just** the bytes that I had specified on the command line.  But the debug logging showed me that (even after I specified the driver of `OPENSC_DRIVER=PIV-II` on the command line) that, before it sends my bytes, the command sends many, many other bytes.  I saw:

1. The sequence of GET DATA on the Discovery Object (DO) followed by GET RESPONSE.
2. The sequence of GET DATA on the Card Capability Container (CCC) followed by GET RESPONSE.
3. Repeat of the sequence for the CCC.
4. Repeat of the sequence for the DO.
5. Repeat of the sequence for the DO.
6. Repeat of the sequence for the DO.
7. Repeat of the sequence for the CCC.
8. Repeat of the sequence for the CCC.
9. Repeat of the sequence for the DO.
10. The sequence of GET DATA on the Key History Object followed by GET RESPONSE. 
11. Repeat of the sequence for the DO.
12. Repeat of the sequence for the DO.
13. The command sends the bytes that I want (namely, the SELECT command with the PIV Card Application AID).
14. The command receives the status bytes of `61 13` (as you mentioned) but reports the status bytes of `90 00`.

**Why** does the command repeat so many of the same operations? I agree that this **is** an "idiosyncrasy".  However, the fact that the command substitutes `90 00` for `61 13` seems more like a defect in my opinion.  This action completely confused me when I compared it to expected behavior that the `scriptor` utility showed.

> I am not familiar with scriptor.

`scriptor` is part of the `pcsct-tools` package provided by Ludovic Rousseau.  It sends **only** the specified bytes, no more, no less, and it reports the status bytes as the values received.

You wrote:
> I don't see any reason to change opensc's handling of the --send-apdu presence or absence of the Le is up to the to the use.

I know that any changes to `opensc-tool` are just my Pull Request away from consideration, but I agree that, at a minimum, the `opensc-tool` manual page for the `--send-apdu` option should be clarified to say that the command also sends many other bytes ahead of the specified bytes, and that the command might change the returned status bytes, depending on the presence or absence of the `Le` byte.

I don't know if it is easy to implement, but the introduction of another command-line option for `opensc-tool` that acts like `scriptor` in just sending the specified bytes and reporting the received bytes would be useful.  (Or maybe not, given that `scriptor` is available.)

Thanks again for all of your work on OpenSC for PIV,
-- Steve Ross

**Comment by dengert** [comment]
All the opensc tools try and select a card driver based on the ATR  and/or by sending an apdu (usually  to select the AID). Once the driver is selected, the driver may also send additional commands if needed. Tthe card may be used by other running applications which can cause interference or select a different applet.  (For example: PIV and CAC applets on same card. Yubio tokens may have PIV and OpenPGP applets.)

But if you  select the `default` driver, it does not send any additional APDUs to the card. `opensc-tool --list-drivers` will show the list of drivers.    

`./opensc-tool -v -v -v --card-driver default --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"`
run only sends  `00 A4 04 00 09 A0 00 00 03 08 00 00 10 00` and receives response `61 13` and because this is using the T=0 protocol, it sends a get-response `00 C0 00 00 13` and receives  `61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00 00 03 08 90 00`
 
The driver or list of drivers can also be set via environment variables or in opensc.conf 

The `piv-tool` also has the `--send-apdu` but always uses the PIV driver. This allows for doing authentication to the before sending the APDU or or multiple APDUs to the card.  (See: man piv-tool)
(PIV authentication and card management varies via card vendors.)

**Comment by srsross** [comment]
Hi @dengert,

Thanks for your quick response.

You wrote:
>  Once the driver is selected, the driver may also send additional commands if needed. 

Yes, my confusion is the multiple uses of the GET DATA command to get the same object multiple times.  Wouldn't once be enough?

You also wrote:
> Tthe card may be used by other running applications which can cause interference or select a different applet.

This is just a NIST PIV card so I don't think (but I don't know) that there is only the PIV Card Application applet running on it.
(The NIST Special Publication 800-73-4, Part 2, says for the SELECT command that "There shall be at most one PIV Card Application on any ICC."  That does not say that there are no other applets, just that there is only one PIV applet.  I'm no expert to know whether or not there are other applets on the card.)   I believe that there is no interference from other applications that might select a different applet, although I remain unclear about this.

And you wrote:
> But if you select the `default` driver, it does not send any additional APDUs to the card.

Ahh!  *Very* useful to know about the `default` driver.  It certainly does stop all of the extra APDUs and responses that are used to determine the type of smart card.  It is very helpful, and now I see from the logging of APDUs that it looks more like the minimalist approach of `scriptor`.

And you wrote:
> `opensc-tool -v -v -v`

The three uses of `-v` seems to produce the same level of debug logging as does `OPENSC_DEBUG=3`.  (I guess that it pays to read the manual page.   :-)  )  Thanks for pointing that out.

-- Steve Ross

**Comment by dengert** [comment]
In response to https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-883537251 that I missed:
The discovery object  is different then other PIV objects. The tag is 0x7E an interindustry tag (Discovery Object). 

As I said above: "The card may be used by other running applications which can cause interference or select a different applet." In order to make sure the PIV is the active applet the driver will either do a select of the PIV AID which will cause the PIV applet to be selected or it will read the Discover object. If the PIV applet is the active applet it will return the PIV AID, if not, the non PIV applet will not return the expected result. A select AID will then be done. Although NIST sp800-73-X says the login state will not change if a SELECT PIV AID is done, some early Yubico devices would reset the login state even for every SELECT PIV AID APDU. Thus the use of the Discovery object as a test.

There are many (what I like to call) "PIV-like" devices or software emulators out there. And anyone could load multiple applets on a Java card. The driver is making no assumptions about what applets are or are not on the card. Thus the multiple requests. 

When first connected, the driver reads all the certificate objects to find the SubjectPublicKeyInfo (SPKI) to get key sizes, RSA modulus and export or EC curveName and ECPoint. This is the only way to get these values from the card.  

What version of OpenSC are you using? 

If possible can you try the 0.22.0-rc2 version: https://github.com/OpenSC/OpenSC/releases

Or if you are willing to build from git, can you try https://github.com/OpenSC/OpenSC/pull/2053
This has a number of improvement to cut down overhead improve security and supports NIST sp800-73-4 Secure Messaging for newer cards. It also support all older cards. 

I am not sure why it is reading the CCC 3 times, it should be caching the data as it does for the other objects, accept the Discovery Object. 

Look close at the GET DATA objects, they may be asking for different objects.

**Comment by dengert** [comment]
I see you forked the OpenSC repro on Github, but it is 1265 commit behind current master. That was in 2018 and version 0.19.0.

The PIV driver prior to https://github.com/OpenSC/OpenSC/pull/2053 would  use GET DATA to read the first 8 bytes of of the object to get the DER TLV to determine the size of the object. It would then go back and use GET DATA with a buffer based on the size. This may be what you are seeing in you logs. #2053 uses a 16k buffer, larger then any NIST estimates. The buffer size can also be set in opensc.conf. This eliminates the extra GET DATA to get the size. 

The interaction of a card driver match routine and the card driver init routine was cleaned up to avoid some duplicate reads of data from the card.

**Comment by srsross** [comment]
Hi @dengert ,

Thanks for helping me to better understand....

You wrote:
> In order to make sure the PIV is the active applet the driver will either do a select of the PIV AID which will cause the PIV applet to be selected or it will read the Discover object. If the PIV applet is the active applet it will return the PIV AID, if not, the non PIV applet will not return the expected result. A select AID will then be done.

I see that the Discovery Object (returned in response to a GET DATA and then GET RESPONSE sequence) contains the complete (namely, NIST RID + PIX + Version) `0x0B` bytes of the  PIV Card Application AID:
```
7E 12 4F 0B A0 00 00 03 08 00 00 10 00 01 00 5F 2F 02 40 00 90 00
```
And also that the SELECT command (sending an `Le` byte too) returns the Application Property Template, which contains the same PIV Card Application ID, albeit broken into two pieces.
```
$ opensc-tool --card-driver default  --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"
Using reader with a card: SCM Microsystems Inc. SCR 3310 [CCID Interface] (53311549211615) 00 00
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00
Received (SW1=0x90, SW2=0x00):
61 11 4F 06 00 00 10 00 01 00 79 07 4F 05 A0 00 a.O.......y.O...
00 03 08                                        ...
```
But in the sequence that I described in https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-883537251, I never saw the SELECT command invoked, only the retrieval (multiple times) of the Discovery Object. Is the successful retrieval of that object enough to identify the card as a PIV card?

You wrote:
> There are many (what I like to call) "PIV-like" devices or software emulators out there. And anyone could load multiple applets on a Java card. The driver is making no assumptions about what applets are or are not on the card. Thus the multiple requests.

Makes sense.  Thanks.

You asked:
> What version of OpenSC are you using?
>
> If possible can you try the 0.22.0-rc2 version: https://github.com/OpenSC/OpenSC/releases

and 

> I see you forked the OpenSC repro on Github, but it is 1265 commit behind current master. That was in 2018 and version 0.19.0.

As I mentioned earlier, I'm using `opensc-0.20.0-6.fc32` on Fedora 32.  I have not tried with the release candidate nor with your changes in <https://github.com/OpenSC/OpenSC/pull/2053>  (and probably will not be able to do so any time in the next week or two, but I hope to try at some point).  I am not doing any work with my forked version.

You wrote:
> I am not sure why it is reading the CCC 3 times, it should be caching the data as it does for the other objects, accept the Discovery Object.

I just confirmed that, with the command line of
```
OPENSC_DRIVER=PIV-II OPENSC_DEBUG=3 opensc-tool  --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"
```
I see four repetitions of the GET DATA/GET RESPONSE for the Card Capability Container with the Version 1 NIST PIV #1 card.

> Look close at the GET DATA objects, they may be asking for different objects.

With the same command line and card, I see three different types of GET DATA commands: Discovery Object, Card Capability Container, and Key History Object.  The first two are repeated multiple times.  The sequence is similar (if not identical) to the one that I listed in https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-883537251 (which I generated from the `opensc-too --list-slots` command).

-- Steve Ross

**Comment by dengert** [comment]
You asked: "Is the successful retrieval of that object enough to identify the card as a PIV card?"

Yes. The only applet on the card that should return the PIV AID is the PIV applet. It also show the PIV is the active applet.  An applet that may return a response to the Discovery Object '7E' would return its own AID.  
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L2735-L2739

Also note that some "PIV-like" devices may not support the Discovery object correctly.  Look at  [card_issues](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L270-L285)

**Comment by srsross** [comment]
Hi @dengert,

In https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-883826295 you wrote:
> Or if you are willing to build from git, can you try #2053
This has a number of improvement to cut down overhead improve security and supports NIST sp800-73-4 Secure Messaging for newer cards. It also support all older cards.

> I am not sure why it is reading the CCC 3 times, it should be caching the data as it does for the other objects, accept the Discovery Object.

> Look close at the GET DATA objects, they may be asking for different objects.

and in https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-884206965, you wrote:
> The interaction of a card driver match routine and the card driver init routine was cleaned up to avoid some duplicate reads of data from the card.

I did try your "PIV-4-extensions" branch with commit 6d2063e61ee0ab5b250566ff6405402364fb17ad from Friday 16-Jul-2021.

This code behaves *much* better in terms of *not* sending the GET DATA command repeatedly for the Discovery Object and the Card Capability Container.

With the Version 1 NIST PIV #1 card, I sent the SELECT command with a payload of the PIV Card Application AID and an `Le` byte with the value of zero.
```
/usr/local/bin/opensc-tool -v -v -v --card-driver PIV-II --send-apdu "00 a4 04 00 09 a0 00 00 03 08 00 00 10 00 00"
```
The logging output showed:
1. GET DATA for the Discovery Object followed by GET RESPONSE.
2. GET DATA for the Card Capability Container followed by GET RESPONSE.
3. GET DATA for the Key History Object.
4. GET DATA for the Discovery Object followed by GET RESPONSE.  (The first and only repetition.)
5. SELECT with PIV Card Application AID followed by GET RESPONSE.

That is much better than the sequence that I described in https://github.com/OpenSC/OpenSC/issues/2369#issuecomment-883537251.  So, a thumbs-up from me for these changes.

-- Steve Ross

**Comment by frankmorgner** [comment]
I did not follow the discussion completely. Is there anything that should be fixed in OpenSC?

**Comment by srsross** [comment]
@frankmorgne, you asked:
> Is there anything that should be fixed in OpenSC?

In my opinion, the manual page for `opensc-tool` is strictly correct, but misleading with regard to the `--send-apdu` option.  The manual page says:
```
       --send-apdu apdu, -s apdu
           Sends an arbitrary APDU to the card in the format
           AA:BB:CC:DD:EE:FF....
```
Yes, the option does cause `opensc-tool` to send the arbitrary APDU as the text says, but the tool also sends many other APDUs to the card, even if I specify the card driver with OPENSC_DRIVER.  (@dengert has since, however, reduced the number of extra APDUs sent in the case of a PIV card.)  I had incorrectly assumed, based on the manual page, that the command would *only* sen the specified APDU. 

In addition, as shown in my initial post, the tool hid the real response to my card command and exchanged more APDUs.  @dengert called this an "idiosyncrasy": fair enough, but it should be documented.

Finally, earlier in this thread, @dengert wrote that using the `default` setting with the `--card-driver` option would eliminate all of these extra APDUs.  That behavior is not documented on the manual page, but it should be.

-- Steve Ross

**Comment by saper** [comment]
Coming from https://github.com/OpenSC/OpenSC/issues/2432 which is a different thing, I was wondering - is there any use case for opensc-tool needing to use the card driver to send APDUs? I can imagine interesting when it takes some strange things to send the APDU to the terminal, which is more a card terminal thing to me, but the card driver?

**Comment by dengert** [comment]
There maybe use cases for opensc-tool needing to use the card driver to send APDUs.

-  If a card uses Secure messaging that needs to be done via the driver. A card may only accept some APDUs if they sent with SM and the response are processed by SM.  The driver can do this  and may or may not wrap your ADPUs. 
- An AID may need to be selected, or a login may be needed. But these could be to be done by preceding additional -s options with these APDUs. 
- There may be other reasons depending on the card. 

OpenSC has many tools for specific cards and utilities for pkcs15 cards. Some may or may not also support a -s option.

For the PIV cards, there is the `piv-tool` which has the `-s` option. It was based on `opensc-tool`. It has some additional commands  to authenticate  using the "9B" admin key  and then generate keys on the card, write objects and certificates. NIST 800-73-* defines these. Certificates are contained in a certificate object with some additional flags and the `piv-tool` can gzip the certificate and set the flags if requested. 

(As I always say: The `piv-tool` was added for testing purposes. NIST left provisioning of PIV cards up to the card vendors. Some support authentication using the "9B" admin key, but others use Global Platform or their own provision utilities with or without some form of SM.)
