### ISSUE TITLE
Failed to connect to card: Unresponsive card (correctly inserted?)

### ISSUE THREAD

**Issue by twilight-wolf-pa** [OpenSC/OpenSC#237]
user@user:~$ opensc-tool --serial
Using reader with a card: SCM SCR 355 [CCID Interface] 00 00
Failed to connect to card: Unresponsive card (correctly inserted?)

I am using a SLE 4428 card I got off ebay. I believe the card is completely blank and has nothing on it. No matter what command I issue, if it tries to do anything with the card I get that error. I have spent hours on google and cant find any solutions. Anyone know how to fix this? Only used this for install "sudo apt-get install libpcsclite1 pcscd pcsc-tools
". 

OS: Ubuntu 12.04
Reader: SCM Microsystems SCR3310
Card: SLE 4428

**Comment by BLCKPSTV** [comment]
Could you tell me what the difference is? Kindly.

I want to use these cards and let the be read by standard smart card readers. 
But I want to put a text on it. 

Could you tell me which cards would be able to show a text with a picture when they put the card in? 
(If the software is installed on the computer ofcourse)

**Comment by dengert** [comment]
Start here:
http://www.smartcardbasics.com/smart-card-types.html
or search for memory card vs smart card

A smartcard can do the crypto operations like RSA or ECC on the card, thus the private key is never exposed. Memory cards only store information. To use a private key, it must be read off the card. Might as well use a flash drive. 

Some smart cards and memory cards may allow for a file or object with a picture as it is just data. 
An example is a PIV smart card that has image and fingerprint objects. 

Some smartcards can even do a fingerprint compare on the card.

**Comment by crusher72** [comment]
I have both types of cards and both give me the same error... I have a Smart Card reader that can read both memory and Smart Card types...what gives?? I have blanks as well, I am trying to program it with just "000 000 000"

Very simple with apu commands but any program I use can't read it or says reset failed/card unresponsive. The reader can read my credit cards I have without errors...

Any help is appreciated!
