### ISSUE TITLE
`sudo make uninstall` does not un-install all installed directories/files.

### ISSUE THREAD

**Issue by srsross** [OpenSC/OpenSC#2372]
### Problem Description
`sudo make uninstall` does not uninstall all the directories and files that it installed.

### Proposed Resolution
Un-install the directory and files listed below.

### Steps to reproduce

I followed (more or less) the directions on <https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors> to build OpenSC on Linux and then install it, namely, 
```
./bootstrap
./configure 
make
sudo make install
```
this put the installed files into `/usr/local`.  So far, so good.

The problem that I noticed is that not all of the installed directories/files are uninstalled by
```
sudo make uninstall
```
In particular, the leftover directories/files are:
```
/usr/local/lib/pkcs11/
/usr/local/lib/pkcs11/pkcs11-spy.so
/usr/local/lib/pkcs11/opensc-pkcs11.so
/usr/local/lib/pkcs11/onepin-opensc-pkcs11.so
```

**Comment by Jakuje** [comment]
The installation of these files happens through the following scriptlet in makefile:

https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/Makefile.am#L80

There is obviously missing the uninstall counterpart. Would you like to submit a PR adding these?

In real world, the installation is handled by package manager, which tracks the installed files, but for peace of mind, it would indeed make sense to clean stuff during uninstall.
