### ISSUE TITLE
Pin Query Fails On Macs

### ISSUE THREAD

**Issue by rbassett3** [OpenSC/OpenSC#2386]
OpenSC seems to be having some issue generating a query for my pin on Mac. I have a US Govt issued CAC card. Based on the terminal output of pkcs11-tool for other folks with a CAC (like what is posted here: https://github.com/OpenSC/OpenSC/issues/1533), I am expecting to have a pin query to login to the card and likely 4 additional queries for each certificate on the card. Instead I see the following.

```
pkcs11-tool --login --test 
Using slot 0 with a present token (0x0)
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

If I manually input my pin I get a step further.

```
pkcs11-tool --login --test --pin=xxxxxxx
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_GENERAL_ERROR (0x5)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CAC ID Certificate) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (CAC Email Signature Certificate) with 1 mechanism
error: PKCS11 function C_Sign failed: rv = CKR_FUNCTION_FAILED (0x6)
Aborting.
    RSA-X-509: %
```

I also tried the --always-auth option but with the same behavior.  In the logs, I see that --always-auth does not change the CKA_ALWAYS_AUTHENTICATE flag to TRUE as I expected it to, but that may be because I don't understand the internals well.

Relevant portion of a level 3 debug are here: https://pastebin.com/g6RP3xz6

I tried with version 22 and 21 and the result is the same. Also, this same issue (should ask for a pin but doesn't) is present when I try to digitally sign a pdf document in Adobe.

Any points on how to fix this is much appreciated.

Edit: I accessed the card on my Linux machine and confirmed my expected behavior (user login pin prompt and 4 context-specific prompts). Somehow this is mac specific.

**Comment by dengert** [comment]
Is this a new CAC card?
Does it work on  linux,  windows or older MacOS?

The "sw1=69 sw2=85" response to the `00 42 00 00 10 82 71 64 5F FF B7 EE C7 DB 4A 74 73 A1 C0 0B C1` crypto command says "Conditions of use not satisfied"

There maybe two problems: no prompt for the PIN that may be Mac only, (I can not address that.)

Or when pin is on command line, it is sent to the card and may or may not verify. But if the verify failed, it should have given a different message. It could be to many failures attempts have locked the PIN.    

Could you send more of the debug log. 
The verify command should look like `00 20 XX XX ...`  and  It has the pin, so obfuscate your pin in the log.
The verify should return `90 00`. 
Look for any routines with _pin_ in the name.  

It is also possible the verify worked but there was some command sent to the card that caused it to lose the login state. This could be from some other application using OpenSC or some other driver or via p11-kit having two CAC drivers, or the reader timing out and reseting the card. 

More of the debug log would help.

**Comment by rbassett3** [comment]
@dengert : Thanks for your reply.

Testing with pkcs11-tool works properly on Linux (same computer, same reader, same card, different OS), querying for pins as expected.

The log is massive, and because I don't understand it well I want to make sure I read through the portions that I post instead of just "find and replace" before dumping it. Are there any pieces of the log that you have in mind so that I can review them before posting?

**Comment by dengert** [comment]
I do not have MacOS or a CAC card, so can not be of much help. 

What version of MacOS? 

Are you dual booting the OS or running some VM system?
Is MacOS the host or the guest?

@mouse07410 any ideas on this?

**Comment by mouse07410** [comment]
All I can say is that my fork, which tracks this master, works on macOS Big Sur 11.5.2 and current CAC:
```
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): SCR3310 Smart Card Reader
  token label        : xxxxxxxxxxxxxxxxx
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : xxxxxxxxxxxxxxxxx
  pin min/max        : 4/8
Slot 1 (0x4): Yubico YubiKey OTP+FIDO+CCID
  token label        : xxxxxxxxxxxxx
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : xxxxxxxxxxxxxxxxxxx
  pin min/max        : 4/8
$ pkcs11-tool --slot 0x0 --test -l
Logging in to "xxxxxxxxxxxxxxxx".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
  SHA256: OK
  SHA384: OK
  SHA512: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (SIGN key) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (KEY MAN key) with 1 mechanism -- can't be used to sign/verify, skipping
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (SIGN key) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (KEY MAN key) with 1 mechanism -- can't be used to sign/verify, skipping
Decryption (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 1 (SIGN key)
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 2 (KEY MAN key)
    RSA-X-509: OK
    RSA-PKCS: OK
1 errors
$ 
```

You might want to give https://github.com/mouse07410/OpenSC.git a try? I know that `libp11` and (as I recall?) OpenSC tried to play some software-based enforcement of when to prompt the user for PIN, and it did not seem to work well for some applications. Also, you may need to edit `/Library/OpenSC/etc/opensc.conf` and enable `pin_cache_ignore_user_concent = true;`:
```
      framework pkcs15 {
                # Whether to use the cache files in the user's
                # home directory.
                #
                .  .  .  .  .
                # Older PKCS#11 applications not supporting CKA_ALWAYS_AUTHENTICATE
                # may need to set this to get signatures to work with some cards.
                # Default: false
                # But for silly applications like those using digital signatures from Java apps
                # this may be necessary to force to true
                pin_cache_ignore_user_consent = true;
```

**Comment by rbassett3** [comment]
@mouse07410. The information you provided was extremely helpful and led me to the culprit, which wasn't actually OpenSC. I'll quickly describe the issue and my solution in case anyone else finds it useful. 

My osX guest was being virtualized with virt-manager, but because a Debian guest was working as expected through virt-manager I didn't think the error was in the virtualization. Another reason I didn't think it was the virtualization was because I had partial access to my smartcard. It turned out it was an issue on the virtualization side, which became clear when comparing the output of mouse's pkcs11-tool -L command to my own. Strangely, the card reader that I was seeing (Gemalto) didn't match the model of my card reader (SCR-3500). I fixed it by doing a complete USB redirection in virt-manager (with spice) instead of just attaching the single smartcard device. Doing the USB redirect is slightly more annoying because I have to manually kill all of the host processes which use the smartcard, which means that I'm unable to use it on both devices simultaneously. Still, I'm happy with the outcome because I can now digitally sign pdfs from my linux machine (via the osX guest).

Thanks all!

**Comment by mouse07410** [comment]
@rbassett3 you're welcome.

I want to add that I've experimented with several PIV (and PIV-like) cards, and several readers. a "real" Gemalto reader was one of the worst. Among other quirks it would suddenly become unresponsive - removing and reconnecting it sometimes helped, and sometimes - didn't.

Re. signing PDFs - cannot it be done under Linux? Do you have to involve OS X virtual machine?

**Comment by rbassett3** [comment]
The crypto part of signing pdfs works wonderfully under linux (thanks in part to this project), but unfortunately there are no free pdf viewers that support this feature. I will be very happy if evince or okular ever support pdf signing. Adobe readers are a well-known option for signing pdfs, but Adobe doesn't release a linux pdf viewer and using a compatibility layer to run the windows binary makes it so that you cannot access a smartcard.
