### ISSUE TITLE
Opensc-0.22.0 is not installing CryptoTokenKit-based smart card driver on Mac

### ISSUE THREAD

**Issue by rajnikant12345** [OpenSC/OpenSC#2389]
### Problem Description
Opensc-0.22.0
OS: Mac 11.5.1
Opensc-0.22.0 is not installing CryptoTokenKit-based smart card driver.

Everything is fine with Opensc-0.21.0

### Proposed Resolution
Fix installation

### Steps to reproduce

Run : brew install --cask opensc
 and run:
$ ls -la /Applications/Utilities

OpenSCTokenApp.app is missing for Opensc-0.22.0

I compared dmg install form 0.21.0 and 0.22.0, I saw missing driver files.

<img width="1313" alt="Screenshot 2021-08-18 at 1 27 25 PM" src="https://user-images.githubusercontent.com/3829599/129872856-7488870f-1283-43cd-98bc-9607f3d3fa2c.png">

### Logs

NA

**Comment by frankmorgner** [comment]
Due to a change in our CI environment, we can't currently sign the binaries automatically (required for CTK). Some maintainer still needs to find the time to do this by hand...

**Comment by frankmorgner** [comment]
@Jakuje maybe it would be better to remove the macos binaries until they're complete (i.e. including code signing for macos)...

**Comment by Jakuje** [comment]
I just removed the dmg file from the release notes and wiki + added a link to this issue.

**Comment by frankmorgner** [comment]
I've uploaded a new version of the image, this time including a signed CTK. A quick test showed that it works as intended.
