### ISSUE TITLE
pkcs11-tool: `--extractable` switch is not honored for generated secret keys

### ISSUE THREAD

**Issue by manison** [OpenSC/OpenSC#2393]
### Problem Description

When generating secret keys with the `pkcs11-tool`, the `--extractable` command line switch is not honored and the newly generated key does not have the `CKA_EXTRACTABLE` se to `TRUE`.

### Proposed Resolution

Append the `CKA_EXTRACTABLE` attribute set to `TRUE` to the template when the `--extractable` switch is specified.

### Steps to reproduce

```
pkcs11-tool --module ... --slot-index 0 --login --keygen --key-type GENERIC:32 --extractable
```

**Comment by Jakuje** [comment]
This already works for private keys so adding this also for secrete keys template should be trivial. Something like this should do that:
```
diff --git a/src/tools/pkcs11-tool.c b/src/tools/pkcs11-tool.c
index a0ffcecd..1a92f098 100644
--- a/src/tools/pkcs11-tool.c
+++ b/src/tools/pkcs11-tool.c
@@ -2882,6 +2882,10 @@ gen_key(CK_SLOT_ID slot, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE *hSecretKey
 			FILL_ATTR(keyTemplate[n_attr], CKA_SENSITIVE, &_true, sizeof(_true));
 			n_attr++;
 		}
+		if (opt_is_extractable != 0) {
+			FILL_ATTR(keyTemplate[n_attr], CKA_EXTRACTABLE, &_true, sizeof(_true));
+			n_attr++;
+		}
 		else {
 			FILL_ATTR(keyTemplate[n_attr], CKA_SENSITIVE, &_false, sizeof(_false));
 			n_attr++;
```
can you try if it works for you?

**Comment by manison** [comment]
Yes, this is the exact solution I had on my mind.

Unfortunately I cannot test it at the moment since I'm on Windows and don't have the required build infrastructure handy. But it should definitely work because it already works for key pairs.

By comparing the `gen_key` and `gen_keypair` methods it seems to me that also the `CKA_PRIVATE` (`--private`) and `CKA_ALWAYS_AUTHENTICATE` (`--always-auth`) are being ignored for for secret keys.

**Comment by Jakuje** [comment]
Right, the CKO_PRIVATE might be useful too, but I am not sure about the ALWAYS_AUTH. It is mentioned only in the asymmetric  keys. Do you want to submit a PR with these changes or should I do that?

**Comment by manison** [comment]
You're right, `CKA_ALWAYS_AUTHENTICATE` seems to be applicable to asymmetric keys only. Then maybe warn if the `--always-auth` is used in conjunction with `--keygen`?

I'll try to prepare PR with these changes.

**Comment by Jakuje** [comment]
I already have a draft for this in https://github.com/OpenSC/OpenSC/pull/2381/commits/481a1449734fc9ac0927d5a4cf05b8e75ff41cec . Feel free to reuse it in your PR.

**Comment by manison** [comment]
OK, that seems fine to me. There's probably not much I can do on top of that 😄 I'm happy to test it.
