### ISSUE TITLE
Idea: Fuzzer for configuration file

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2402]
### Problem Description

We could write a fuzzer for parsing `opensc.conf`...

### Proposed Resolution

The fuzzer could be as simple as [`fuzz_asn1_print.c`](https://github.com/OpenSC/OpenSC/blob/master/src/tests/fuzzing/fuzz_asn1_print.c), but calling `scconf_parse_string()` instead.

**Comment by Jakuje** [comment]
I had in my mind something similar. I believe the configuration parser is simple enough to handle all the corner cases and not changing that frequently, but it should not certainly hurt to have something like this.
