### ISSUE TITLE
SmartCard-HSM V4.0 occasionally fails to generate secp521r1 signature

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#2421]
### Problem Description

Signing with an EC key on secp521r1 fails occasionally with CKR_DATA_INVALID. This issue only occurs with V4.0 devices.

### Proposed Resolution

Fix sc_hsm_decode_ecdsa_signature() to correctly separate 512 from 521 bit signatures.

### Steps to reproduce

Generate secp521r1 key

    pkcs11-tool --login --pin 648219 --keypairgen --key-type EC:nistp521 --id a1 --label a1 --usage-sign

Repeatably run

    echo "111111111111111111111111111111111111111111111111111111112345678" | pkcs11-tool --login --pin 648219 -s -o tmp

until the error shows up.

**Comment by rautammi** [comment]
I think the PR #2422 does not completely fix the issue. I have sometimes witnessed ASN.1/DER encoded secp521r1 signatures being 137 bytes of length, when both integers had 0 as the most significant byte.

**Comment by CardContact** [comment]
Implemented by #3157.
