### ISSUE TITLE
FT ePass2003 - "token not recognized"

### ISSUE THREAD

**Issue by alhashash** [OpenSC/OpenSC#2424]
I cannot use ePass2003 token with OpenSC v0.22.0:

```bash
$ pkcs11-tool --module /usr/lib64/opensc-pkcs11.so -L
Available slots:
Slot 0 (0x0): FT ePass2003Auto 00 00
  (token not recognized)

$ opensc-tool -i
OpenSC 0.22.0 [gcc  11.2.1 20210728 (Red Hat 11.2.1-1)]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

$ lsusb |grep Feitian
Bus 001 Device 035: ID 096e:080a Feitian Technologies, Inc. USB TOKEN
```

It does work using the FT binary driver `libcastle.so.1.0.0`

```
$ pkcs11-tool --module /tmp/libcastle.so.1.0.0  -L 
Available slots:
Slot 0 (0x1): ES SLOT 1
  token label        : <removed>
  token manufacturer : EnterSafe
  token model        : ePass2003
  token flags        : login required, rng, token initialized, PIN initialized, user PIN to be changed
  hardware version   : 16.50
  firmware version   : 16.50
  serial num         : <removed>
  pin min/max        : 8/255
```

The latest version of the FT driver (v2) does NOT work too!:
```
$ pkcs11-tool --module /tmp/libcastle_v2.so.1.0.0  -L 
Available slots:
Slot 0 (0x1): ES SLOT 1
C_GetTokenInfo() failed: rv = CKR_GENERAL_ERROR
```
I hope to use OpenSC as I need to run it on ARM architecture which is not supported by FT driver.

@FeitianSmartcardReader

**Comment by dengert** [comment]
Aah,
Google for: 1PAY.SYS.DDF01
Looks like it is EMV card, more like a credit card then a "smartcard"

The debug log has:
```
card-epass2003.c:1914:epass2003_process_fci: processing FCI bytes
card-epass2003.c:1918:epass2003_process_fci:   file identifier: 0x3F00
 card-epass2003.c:1989:epass2003_process_fci: type DF, EF structure 56
card-epass2003.c:1998:epass2003_process_fci: 
File name (16 bytes):
31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 00 00 1PAY.SYS.DDF01..
...
card.c:844:sc_select_file: called; type=2, path=3f005031
...
pkcs15.c:1050:sc_pkcs15_bind_internal: EF(ODF) not found in '3f005031'
```

You can also try and use the opensc-explorer
```
./opensc-explorer -c epass2003
OpenSC Explorer version 0.22.0
Using reader with a card: Feitian ePass2003 00 00
OpenSC [3F00]> help
(read the help, and then try:)
OpenSC [3F00]> ls
FileID	Type  Size
 2F00 	 wEF     0
[5015]	  DF     0	Name: \xA0\x00\x00\x00cPKCS-15
OpenSC [3F00]> cd 5015
OpenSC [3F00/5015]> ls
FileID	Type  Size
 9F00 	 wEF     2
 5031 	 wEF   512
 5032 	 wEF   128
 5033 	 wEF   128
 4401 	 wEF  4864
 4402 	 wEF  1024
 4403 	 wEF  1024
 4404 	 wEF  2048
 4405 	 wEF  4864
 4946 	 wEF   128
 3000 	 wEF   270
OpenSC [3F00/5015]>
```

You card is able to do Secure messaging, so it is somewhat compatible, but does not
have the PKCS15 structures the OpenSC expects.

**Comment by alhashash** [comment]
@dengert Your first assumption is right; I'm developing a middleware to sign invoices using the "government-issued tokens" to be run Raspberry Pi or similar SBCs. I'm not going to initialize any new tokens.

I can use the old binary driver to sign digests using the token private key but it is available only for i386 and x64 architectures. Is this use case outside the scope of OpenSC? is PKCS15 required to run OpenSC?

**Comment by alhashash** [comment]
@dengert 
```
$ tools/opensc-explorer -c epass2003
OpenSC Explorer version 0.22.0
Using reader with a card: FT ePass2003Auto 00 00
OpenSC [3F00]> ls
FileID	Type  Size
 2F01 	 wEF    15
[2003]	  DF     0	Name: ENTERSAFE-ESPK\x00\x00
OpenSC [3F00]> cd 2003
OpenSC [3F00/2003]> ls
FileID	Type  Size
 6F01 	 wEF  1500
 9F00 	 wEF     2
 2400 	 wEF  3072
 2420 	 wEF  1024
 2440 	 wEF    16
 2460 	 wEF    40
 8000 	 iEF     0
 2480 	 wEF   493
 24A0 	 wEF   526
 24C0 	 wEF  2041
```

**Comment by dengert** [comment]
Sounds similar to https://github.com/OpenSC/OpenSC/issues/1397

Your token appears to be outside the scope of OpenSC. The file structure does not agree with PKCS15. 
With documentation on what is in those file, it could be possible to write an OpenSC driver. Are you interested in becoming an OpenSC developer?

 @alhashash I see you have forked some Python based git repros. 

If the token is EMV based, have a look at https://pypi.org/project/emv/ 

Also Google for: emv open source

Also note the RaspberryPi 4 can run Ubuntu.

**Comment by frankmorgner** [comment]
please use your contact to the @FeitianSmartcardReader technican to solve this issue. if possible provide a fix via pull requests.

**Comment by M-Dahab** [comment]
Thank you very much @alhashash!

I've managed to extract `eps2003csp1164.dll` from `ePass2003-Setup 1 17.exe` which's available [here](https://egypttrust.com/wp-content/uploads/2022/10/ePass2003-Setup_2022.zip) and it's working fine for ePass2003 🥳

**Comment by alhashash** [comment]
@M-Dahab  To avoid confusing others who may read this issue, these old drivers are required only to access specific non-pkcs15 ePass2003 tokens (like those we have to use in Egypt to sign invoices). 

If you manage your own PKI, you should better reformat the tokens as pkcs15 for compatibility with standard OpenSC and recent Feitian drivers.
