### ISSUE TITLE
Prepare for release 0.23.0

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2426]
As proposed in note from OpenSC  developers, release 0.23.0 will follow a security release 0.22.1.

The intent is to add to master, current PRs and address issues long before a release is created. By adding these early they will get additional testing by developers and users. In the past we have waited until a release candidate was announced to add last minute changes   

The initial list of ToDo's include those that appear to be ready to add or need to be addressed. 

Please, let me know if we missed something or if there is something which should go in before release.
@OpenSC/opensc-maintainers, @OpenSC/core, @OpenSC/maintainers, 

---

Draft release notes (thanks Veronika!):

### General improvements
* Support signing of data with a length of more than 512 bytes (#2314)
* By default, disable support for old card drivers (#2391) and remove support for old drivers MioCOS and JCOP (#2374)
* Bump minimal required OpenSSL version to 1.1.1 and add support for OpenSSL 3.0 (#2438, #2506)
* Compatibility with LibreSSL (#2495, #2595)
* Remove support for DSA (#2503)
* Extend p11test to support symmetric keys (#2430)
* Notice detached reader on macOS (#2418)
* Support for OAEP padding (#2475, #2484)
* Fix for PSS salt length (#2478)
* Improve fuzzing by adding new tests (#2417, #2500, #2520, #2550)
* Fixed various issues reported by OSS-Fuzz and Coverity regarding card drivers, PKCS#11 and PKCS#15 init 
* Fix issues with OpenPACE (#2472)
* Containers support for local testing
* Add support for encryption using symmetric keys (#2473)
* Stop building support for Gost algorithms with OpenSSL 3.0 as they require deprecated API (#2586)

### PKCS#11
* Implement `C_CreateObject` for EC keys and fix signature verification for `CKM_ECDSA_SHAx` cards (#2420)

### pkcs11-tool
* Add more elliptic curves (#2301)
* Add support for symmetric encrypt and decrypt, wrap and unwrap operations, and initialization vector (#2268)
* Fix consistent handling of secret key attributes (#2497)
* Add support for signing and verifying with HMAC (#2385)
* Add support for SHA3 (#2467)
* Make object selectable via label (#2570)
* Do not require an R/W session for some operations and add `--session-rw` option (#2579)

### sc-hsm-tool
* Add options for public key authentication (#2301)

### Minidriver
* Fix reinit of the card (#2525)
* Add an entry for Italian CNS (e) (#2548)

### NQ-Applet
* Add support for the JCOP4 Cards with NQ-Applet (#2425)

### ItaCNS
* Add support for ItaCMS v1.1 (key length 2048) (#2371)

### Belpic
* Add support for applet v1.8 (#2455)

### Starcos
* Add ATR for V3.4 (#2464)
* Add PKCS#15 emulator for 3.x cards with eSign app (#2544)

### ePass2003
* Fix PKCS#15 initialization (#2403)
* Add support for FIPS (#2543)
* Fix matching with newer versions and tokens initialized with OpenSC (#2575)

### MyEID
* Support logout operation (#2557)

### GIDS
* Fix decipher for TPM (#1881)

### OpenPGP
* Get the list of supported algorithms from algorithm information on the card (#2287)

### nPA
* Fix card detection (#2463)

**Comment by dengert** [comment]
@frankmorgner @Jakuje  when do you expect to have the next release? It has been almost 5 months since this issue was created.

**Comment by dengert** [comment]
@dlegaultbbry  Are you compiling against a specific release or from github master.

**Comment by dlegaultbbry** [comment]
@dengert I'm using 0.22 currently but was doing so with openssl 1.1.1. We're moving to 3.0 which is now an official released and LTS version hence why I'm asking.

**Comment by Jakuje** [comment]
I think we should do it before the summer so in coming months, if possible. The last release was in August (time flies) and since then we had over 400 commits in master.

In https://github.com/OpenSC/OpenSC/projects/10 there are noteworthy changes around formatting and around PIV SM, which I agree that they should go in. I added also #2473 which would be great have, but I am not sure if I have enough expertise to decide the design is correct, but it looks reasonable.

**Comment by dengert** [comment]
@Jakuje  I agree it needs to be done, the sooner the better. I am not pushing for PIV SM to be in next release. I would rather have it committed after the next release. I don't like seeing big changes added just before a release. (But I am not doing the release and an happy with Frank and you doing it.)  

I would like to see #2506 and #2518 in next release. And maybe #2523 but  would like @metsma and @vletoux  to look at it closer as it deals with how the minidriver is installed which caused the ECC code not to work on Windows.

@dlegaultbbry was specifically asking about OpenSSL 3.0 changes. I think we have most of them committed accept for #2506.

**Comment by dlegaultbbry** [comment]
Any eta on the release of this new version?

**Comment by Jakuje** [comment]
> Any eta on the release of this new version?

I would love to get the RC out in coming weeks, rather earlier than later. I do not think there is any huge outstanding work, but just testing and possible small fixes if something will not work well.

**Comment by Jakuje** [comment]
@dengert oh, the 0.22.0 builds are from the CI invoked by the push, while the 0.23.0 are from the tag. I copied to https://github.com/OpenSC/OpenSC/releases/tag/0.23.0-rc1 the old ones, even though the code should be really the same. Let me fix that.

When I download the files from https://github.com/OpenSC/Nightly/archive/2022-10-11_a3b5f8d0.zip I got much larger files -- how did you download them?

**Comment by dengert** [comment]
I went to https://github.com/OpenSC/Nightly/tree/2022-10-11_a3b5f8d0 at 7:10 AM (GMT-5) and downloaded: https://github.com/OpenSC/Nightly/blob/2022-10-11_a3b5f8d0/OpenSC-0.23.0-rc1_win64.msi which was 211 KB.

Now at 10:13 AM I downloaded the same file and it is 16,339 KB. I must have caught it while it was being updated?

That matches what is in the zip file, and it installs.

**Comment by frankmorgner** [comment]
I think the confusion about the file naming is caused by using a lightweight tag for the RC. The [Release Howto](https://github.com/OpenSC/OpenSC/wiki/OpenSC-Release-Howto#build-and-test-binaries) explaines to use `git tag -a ...` for the final release to avoid this problem. I think for last RCs we manually pulled the correct files from CI, because we wanted `git describe` to show the last official release...

**Comment by frankmorgner** [comment]
for macos, the installer is available for download in this job https://github.com/OpenSC/OpenSC/actions/runs/3226517878

**Comment by Jakuje** [comment]
> for macos, the installer is available for download in this job https://github.com/OpenSC/OpenSC/actions/runs/3226517878

Thanks. I was not sure if it was supposed to work this way or not. Just pulled the dmg from the tarball and attached it to the release. But it is missing the `-rc1` suffix so I will try the next time with the annotated tag. I probably wrongly though that this was needed only for the final release.

**Comment by Jakuje** [comment]
FYI, the wiki is now open for anyone to edit. I already filled my test results in https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing#opensc-0230 and would appreciate others to fill their results too (especially windows and mac installers, but also other cards).

**Comment by dengert** [comment]
The windows install/uninstall was tested on Windows 11. Before the install, any previous OpenSC packages where uninstalled. 

NIST "Beta Test Cards" (from 2010) were used to test the minidriver. 
- Card 1 is a GemAlto "PIV 1.5.5 DLv1" with RSA 2048 keys
- Card 5 is a Oberthur ID-One PIV with EC p-256 authentication keys and EC p-384 for signature and key management keys. 

Commands used to list and/or test include:
- certutil -v -SCinfo  (which appears to try and test any certificates listed in user MY store that are from smartcards)
- certutil -store -user MY  (To list all the certificates in user's MY store)
- certutil -v -store -user MY ID (To test a specific certificate, where ID is the certificate number from previous command.  Windows will request the smart card be inserted. ID can be other fields. See: `certutil -store -?`)
- control panel->Internet Options->Content->Certificates->Personal (list certs in "MY") 
- mmc (as user)  with the snap-in for Certificates for "My user account" 
- mmc (as admin) with the snap-in for Certificates for other stores. 

The main changes to minidriver were from #2523. People provided suggested fixes, but no one reported testing the PR with other cards with ECC keys. I would hope vendors such as @CardContact would test this with their devices with EC keys. 

To test with PIV cards:
- I imported the registry entries listed at the end below. 
 
- I found an issue with "user-consent" when using PIV signature certificate.  So added `pin_cache_ignore_user_consent = true;` to `opensc.cnf` for 64 and 32 bit. This may apply to other cards as well.
```
app cardmod {
	framework pkcs15 {
		# use_file_caching = public;
		pin_cache_ignore_user_consent = true;
	}
```

- `P:8364; T:1500 2022-10-15 07:55:11.867 [cardmod] No ECC key found (keyspec=3)` would show up in output of  `certutil -v -store -user MY 0` with an all EC key card. This maybe it is looking for private keys before prompting for PIN.  The test did end with "Signature test passed".  Further investigation is needed.

Notes:
- To use ECC keys, #2523 modified the `card-piv.c` to add the curveName OID to calls to `_sc_card_add_ec_alg` but only for PIV. This may be needed by other drivers. (No one reported any problems with other cards, but no one reported testing #2523 either.) 
- OpenSC registry entries for minidriver are not added automatically for PIV cards. Most (if not all) card vendors provide their own minidrivers and support "Plug-and-Play" See: https://learn.microsoft.com/en-us/windows-hardware/drivers/smartcard/discovery-process Thus for most cards the OpenSC minidriver is not needed. Where the OpenSC minidriver may still be needed is when users load an applet on to some token or the vendor is depending on OpenSC for the minidriver. 
- Microsoft also provides a builtin PIV minidriver which uses SELECT AID command to test if card is PIV. But as best I can tell the built in PIV support does not support ECC keys. But as noted above most (if  not all) PIV card vendors provide "Plug-and-Play". 
- Windows fetched intermediate CA certificates and added them to "MY" store.  In real situations these should be moved to intermediate CA store and the Trusted stores (after verifying if these are correct or not.) 

Registry entries for the two types of cards. The cards used may be different in other sets of "Beta" or "Demo" cards. In my set, two were Gemalto, the rest  Oberthur ID-One PIV.
Use these as examples. "OpenSC-Comment" is not used by any code, but added as a comment with my initials DEE. The name of the registry entry will show up in some popup windows to insert a specific type of card. **And maybe used to verify the correct card is inserted.** 
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\NIST DEMO GemAlto 1.5.5 test cards]
    "ATR"=hex:3b,7d,96,00,00,80,31,80,65,b0,83,11,17,d6,83,00,90,00
"ATRMask"=hex:ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"OpenSC-Comment"="modified to use OpenSC CSP DEE"
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"80000001"="C:\\Program Files\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Cryptography\Calais\SmartCards\NIST DEMO GemAlto 1.5.5 test cards]
    "ATR"=hex:3b,7d,96,00,00,80,31,80,65,b0,83,11,17,d6,83,00,90,00
"ATRMask"=hex:ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"OpenSC-Comment"="modified to use OpenSC CSP DEE"
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"80000001"="C:\\Program Files (x86)\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"


[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\NIST DEMO Oberthur test cards]
    "ATR"=hex:3b,df,96,00,81,b1,fe,45,1f,83,80,73,cc,91,cb,f9,a0,00,00,03,08,00,00,10,00,79
"ATRMask"=hex:ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"OpenSC-Comment"="modified to use OpenSC CSP DEE"
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"80000001"="C:\\Program Files\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Cryptography\Calais\SmartCards\NIST DEMO Oberthur test cards]
    "ATR"=hex:3b,df,96,00,81,b1,fe,45,1f,83,80,73,cc,91,cb,f9,a0,00,00,03,08,00,00,10,00,79
"ATRMask"=hex:ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"OpenSC-Comment"="modified to use OpenSC CSP DEE"
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
"80000001"="C:\\Program Files (x86)\\OpenSC Project\\OpenSC\\minidriver\\opensc-minidriver.dll"
```

`pkcs11-tool -O` and `pkcs11-tool --test --login` both work as expected.

**Comment by Jakuje** [comment]
@dengert I read that it works ok for you. Can you update the release testing wiki page on https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing#opensc-0230

I did another RC today. Anyone who would like to test or provide a feedback is welcomed to do so. I would like to fix remaining fuzzing issues and do the release in coming weeks (rather earlier than later).

https://github.com/OpenSC/OpenSC/releases/tag/0.23.0-rc2

**Comment by dengert** [comment]
> @dengert I read that it works ok for you. Can you update the release testing wiki page on https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing#opensc-0230
Done for -.23.0-rc1.

**Comment by Jakuje** [comment]
Thanks. If there will be no other feedback, testing and comments nor objections, I would like to cut off and build the final release this week.

**Comment by Jakuje** [comment]
The new version was released today. Thanks everyone for the contributions, testing and reporting issues!

https://github.com/OpenSC/OpenSC/releases/tag/0.23.0
