### ISSUE TITLE
PIV: Uneccessary reads of CCC Discovery Object

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2434]
### Problem Description

From the Discovery object, `card-piv.c` only extract a single information is extracted: whether or not the global PIN should be preferred over the application pin. Nevertheless, multiple reads are performed, the first one even before the applet has even been selected. The PIN preference is used exactly once, when the PIV PKCS#15 emulator initially sets up the profile.

The Discovery object is also used to detect whether the PIV applet is still selected. Although I'm not sure whether this is the best approach, I think that
- ... the Card Holder Unique Identifier should be preferred over the discovery object, because the former is a mandatory object rather than an optional one
- ... parsing the received data is not needed to verify whether the applet is still selected.

@dengert 

### Proposed Resolution

- move reading/parsing discovery object to piv_init *after* the AID has been selected
- use CHUID for detection of selected applet

### Steps to reproduce

`pkcs11-tool --test --login`

### Logs

```
...
Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 08 ..?..\.~.
P:86211; T:0x140013415010624 10:53:39.222 [opensc-pkcs11] reader-pcsc.c:244:pcsc_internal_transmit: called
P:86211; T:0x140013415010624 10:53:39.223 [opensc-pkcs11] reader-pcsc.c:335:pcsc_transmit: 
Incoming APDU (2 bytes):
6D 00 m.
...
Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 08 ..?..\.~.
P:86211; T:0x140013415010624 10:53:39.225 [opensc-pkcs11] reader-pcsc.c:244:pcsc_internal_transmit: called
P:86211; T:0x140013415010624 10:53:39.225 [opensc-pkcs11] reader-pcsc.c:335:pcsc_transmit: 
Incoming APDU (10 bytes):
7E 12 4F 0B A0 00 00 03 61 0C ~.O.....a.
...
Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 08 ..?..\.~.
P:86211; T:0x140013415010624 10:53:39.238 [opensc-pkcs11] reader-pcsc.c:244:pcsc_internal_transmit: called
P:86211; T:0x140013415010624 10:53:39.239 [opensc-pkcs11] reader-pcsc.c:335:pcsc_transmit: 
Incoming APDU (10 bytes):
7E 12 4F 0B A0 00 00 03 61 0C ~.O.....a.
...
```

**Comment by mouse07410** [comment]
I think that on at least some PIV cards you cannot access CHUID without a PIN. It would be very bad if you'd need to login first.

As you pointed out yourself, PIV duvet is exceedingly complex. It took tons of time and efforts to get it working reasonably well. Please don't start fixing what isn't broken.

**Comment by frankmorgner** [comment]
OK, I think I understand now. Thank you
