### ISSUE TITLE
Mysterious firefox communication with yubikey

### ISSUE THREAD

**Issue by kjonca** [OpenSC/OpenSC#2443]
At first: sorry for contacting you that way, but I am not sure where to write my question.

https://lists.debian.org/debian-user/2021/11/msg00358.html

In short i have yubikey, after installing opensc-pkcs11 debian package, in my firefox (and thunderbird also) appeared "security device":

----------------
library=/usr/lib/x86_64-linux-gnu/onepin-opensc-pkcs11.so
name=OpenSC smartcard framework (0.22)
---------------
This makes that firefox try to communicate with my yubikey periodically (quite often)
Is it desired behaviour? 
What this library/firefox trying to do?
For now I simply deleted this "device" from firefox, but what If I decide to use piv (?) application of yubikey?

**Comment by frankmorgner** [comment]
In `opensc.conf`, please enable debug mode and write the log to a file.

**Comment by frankmorgner** [comment]
If you're using a single application only with your card (i.e. firefox), you could also try the `lock_login` option.

**Comment by kjonca** [comment]
[onepin-opensc-pkcs11.log.gz](https://github.com/OpenSC/OpenSC/files/7540154/onepin-opensc-pkcs11.log.gz)
[opensc.conf.txt](https://github.com/OpenSC/OpenSC/files/7540176/opensc.conf.txt)
Attached files: configuration + logs.
WIth uncommented lines 1-7 log was created but, empty.

**Comment by frankmorgner** [comment]
Your log only activity in the first 5 seconds of running firefox... how long did you run the program?

Just use
```
app default {
	debug = 20;
	debug_file = /tmp/opensc-debug.txt;
	pkcs11 {
		# lock_login = true;
	}
}
```
did you try uncommenting `lock_login`?

**Comment by frankmorgner** [comment]
Firefox constantly requests the PIN status (logged in/out), because status may change as other processes/threads are accessing the yubikey. OpenSC locks the card and
1. checks whether PIV is still selected (yubikey also supports PGP)
2. requests the PIN status from PIV

both steps are implemented as queries to the yubikey, which is why it is blinking all the time. with `lock_login` you can already avoid the first step (disallowing other processes or threads to access the yubikey). Additionally we could avoid the second step by only calling `sc_pkcs15_get_pin_info()` in `src/pkcs11/framework-pkcs15.c` when `lock_login` is disabled. Feel free to submit a pull request for that!

**Comment by dengert** [comment]
Does your Yubico have certificates and keys in the PIV applet? Or just in the GPG (OpenPGP) applet?

Right now, OpenSC  selects a card driver for a token. By default the PIV driver is selected before the GPG driver. It does not have a way to present 2 applets on the same token via PKCS11.   See #1263 
 
If you are not using the PIV applet Yubikey, but want to use GPG applet, you can tell OpenSC which card drivers and the order to use them in a number of ways. 
 https://github.com/OpenSC/OpenSC/wiki/Environment-variables#opensc_driver or https://htmlpreview.github.io/?https://github.com/OpenSC/OpenSC/blob/master/doc/files/files.html#opensc.conf with the card_drivers  option.

If you don't want to use either. you can modify the "Security Device" in Firefox or thunderbird to not use OpenSC.

**Comment by kjonca** [comment]
For now, I do not use PIV, so I can simply turn it off. (Security devices are deleted.)
I understand, that problem will return when I try to use PIV with firefox?

**Comment by dengert** [comment]
Yes, but if you are using the PIV with FireFox, you have to put up with FireFox calling the OpenSC PKCs11 module even when it is not needed. I would say this is a FireFox problem.

**Comment by Thaodan** [comment]
Any idea how to debug/log this so we can submit something to Mozilla? For me this still happens when using gpg-agent and Firefox.
Firefox constantly uses the card. Is the card supposed to be in use for any time a page is open that asks to use the card for authentication?

**Comment by dengert** [comment]
> Any idea how to debug/log this so we can submit something to Mozilla? For me this still happens when using gpg-agent and Firefox.

@Thaodan  See https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla
