### ISSUE TITLE
Removing DSA support

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#2454]
### Problem Description

There is a lot of generic DSA support throughout the library, but my fast grep shows that the DSA keys are *somehow* handled only in the GPK, epass2003 and oberthur drivers:
```
src/pkcs15init/pkcs15-epass2003.c:              case SC_PKCS15_TYPE_PUBKEY_DSA:
```
 * just pubkey template/names -- probably not working
```
src/pkcs15init/pkcs15-gpk.c:    case SC_PKCS15_TYPE_PRKEY_DSA:
src/pkcs15init/pkcs15-gpk.c:            algo = SC_ALGORITHM_DSA; break;
```
 * this looks almost like complete support
```
src/pkcs15init/pkcs15-oberthur.c:               case SC_PKCS15_TYPE_PUBKEY_DSA:
```
 * just public keys template/names -- probably not working
```
src/libopensc/cardctl.h:        SC_CARDCTL_OBERTHUR_KEY_DSA_PUBLIC,
src/libopensc/cardctl.h:        SC_CARDCTL_OBERTHUR_KEY_DSA_PRIVATE,
```
 * unused defines
```
src/libopensc/card-dnie.c:              case SC_ALGORITHM_DSA:
```
 * just used to say that it is not supported

I think this might work only in the GPK driver to some extent, but that one is unmaintained anyway since 207 or so and planned to be [deactivated](https://github.com/OpenSC/OpenSC/wiki/Removal-of-Old-Card-Drivers#card-driver-overview).

### Proposed Resolution

I am all for removing the support for the DSA in libopensc. It is for no use today and is just maintenance burden. It is not even supported by its creator, NIST in latest FIPS 140-3 release after 2023 so. Before submitting a PRs, I just wanted to check if there are some strong voices against doing so.

I am not about slashing all the occurrences of the DSA (I am fine if it can be detected in pkcs11-tool if needed or similar), but the internal handling this key type in libopensc is not useful.

**Comment by saper** [comment]
I have to deal with obsolete stuff found at various sites all the time... I can understand the lack of desire to clean things up and make them less difficult to maintain

**Comment by Jakuje** [comment]
I understand the handling of obsolete stuff, but I would fit the DSA into "broken" category. Even if the support in gpk driver would be working, there are applications that could use it as far as I know. There is no support for DSA in pkcs11-tool, nothing in OpenSSH, nothing in libp11.

Any other voices from @OpenSC/maintainers ?

**Comment by LudovicRousseau** [comment]
No objection from me.

**Comment by mouse07410** [comment]
My concern is legacy. I personally (and my organization) do not use DSA for a very long time, and I don't have any DSA keys on an HW token.

Ideally, I'd like to see removal of the ability to **sign**, but keeping the ability to **verify**.

If the above is way too hard, I guess DSA can go...

**Comment by Jakuje** [comment]
> My concern is legacy. I personally (and my organization) do not use DSA for a very long time, and I don't have any DSA keys on an HW token.
> 
> Ideally, I'd like to see removal of the ability to **sign**, but keeping the ability to **verify**.
> 
> If the above is way too hard, I guess DSA can go...

Thank you for checking.

Looking into this again, the `pkcs11-tool` does not support DSA at all. There is no support for dsa in framework-pkcs15 (except for displaying some constants) nor there is any support for verification with DSA keys using openssl implemented. The only parts are in pkcs15-init and pkcs15-tool (and there is no verification in these) so my guess is that the support was implemented only up to the pkcs15 layer and never into the pkcs11 one, which means there is really nothing useful to keep right now.
