### ISSUE TITLE
[0.22.0] npa card not detected

### ISSUE THREAD

**Issue by tuxmaster5000** [OpenSC/OpenSC#2461]
### Problem Description
The npa card are supported, but not detected, 

### Steps to reproduce
1. insert the card to the reader
2. call opensc-tool -n

using the card with the "Ausweisapp2" will work. So the reader and the card are ok.

### Logs

https://pastebin.com/wENAiFi8

**Comment by Jakuje** [comment]
The NPA card detection part is here:
```
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] card.c:341:sc_connect_card: trying driver 'npa'
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] dir.c:171:sc_enum_apps: called
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] card.c:844:sc_select_file: called; type=2, path=3f002f00
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] apdu.c:548:sc_transmit_apdu: called
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] card.c:473:sc_lock: called
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] reader-pcsc.c:685:pcsc_lock: called
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] card.c:513:sc_lock: returning with: 0 (Success)
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] apdu.c:515:sc_transmit: called
P:13372; T:0x140398909413184 16:44:49.124 [opensc-tool] apdu.c:363:sc_single_transmit: called
P:13372; T:0x140398909413184 16:44:49.125 [opensc-tool] apdu.c:367:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:0, data(2) 0x7ffe0f1cc082
P:13372; T:0x140398909413184 16:44:49.125 [opensc-tool] reader-pcsc.c:323:pcsc_transmit: reader 'REINER SCT cyberJack RFID komfort (XXXXXX) 00 00'
P:13372; T:0x140398909413184 16:44:49.125 [opensc-tool] reader-pcsc.c:324:pcsc_transmit: 
Outgoing APDU (8 bytes):
00 A4 08 00 02 2F 00 00 ...../..
 
P:13372; T:0x140398909413184 16:44:49.125 [opensc-tool] reader-pcsc.c:242:pcsc_internal_transmit: called
P:13372; T:0x140398909413184 16:44:49.140 [opensc-tool] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (4 bytes):
6F 00 90 00 o...
 
P:13372; T:0x140398909413184 16:44:49.140 [opensc-tool] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:13372; T:0x140398909413184 16:44:49.140 [opensc-tool] apdu.c:537:sc_transmit: returning with: 0 (Success)
P:13372; T:0x140398909413184 16:44:49.141 [opensc-tool] card.c:523:sc_unlock: called
P:13372; T:0x140398909413184 16:44:49.141 [opensc-tool] reader-pcsc.c:737:pcsc_unlock: called
P:13372; T:0x140398909413184 16:44:49.141 [opensc-tool] card.c:879:sc_select_file: returning with: 0 (Success)
P:13372; T:0x140398909413184 16:44:49.141 [opensc-tool] dir.c:184:sc_enum_apps: EF(DIR) is not a working EF.: -1210 (Card is invalid or cannot be handled)
```
I am not familar with the npa card, so hopefully @frankmorgner can have a better look into the issue.

**Comment by frankmorgner** [comment]
I've stumbled across this earlier and forgot to publish the fix... please try #2463

**Comment by tuxmaster5000** [comment]
Now nothing works any more.
 ./npa-tool -vvvv;echo $?
1
Is the only output, when I build it from the git master.

**Comment by frankmorgner** [comment]
you didn't specify an action. Try, for example, verifying the CAN:
```
npa-tool --can=123456
```

**Comment by frankmorgner** [comment]
With #2463, `opensc-tool -n` will show the correct card type. `npa-tool`, however doesn't rely on this kind of card detection, it uses the default card driver to allow using PACE or EAC also with different cards.

**Comment by tuxmaster5000** [comment]
Oh I have forgotten to use the patch :(
/opensc-tool -n
# After enter the pin in the reader
Using reader with a card: REINER SCT cyberJack RFID komfort (XXXX) 00 00
German ID card (neuer Personalausweis, nPA)
But the npa-tool  will not result anything.
./npa-tool -v;echo $?
1
./npa-tool -help;echo $?
1
./npa-tool --can=XXXXXX;echo $?
1

**Comment by frankmorgner** [comment]
please attach a log (user more debugging `-vvvvvvvvvvvvvvvvvvvvvvvvvv`); I' doing the same here and it works as expected.

**Comment by frankmorgner** [comment]
>After enter the pin in the reader
If I'm not mistaken, you should be prompted for the CAN instead of the PIN so that the signing application will be unlocked...

**Comment by tuxmaster5000** [comment]
The same result :(
./npa-tool -vvvvvvvvvvvvvvvvvvvvvvvvvv;echo $?
1
The prompt for the  CAN pin comes only at the "opensc-tool -n" call

**Comment by frankmorgner** [comment]
What is the output of ` /opensc-tool -n -vvvvvvvvvvvvvvvvvvvvvvvvvv`? does this show anything?

**Comment by tuxmaster5000** [comment]
Yes, see the attachment.
[log.txt](https://github.com/OpenSC/OpenSC/files/7698763/log.txt)

**Comment by tuxmaster5000** [comment]
Here I have uploaded the used sources and the compile result:
https://www91.zippyshare.com/v/zF5bPk6q/file.html

**Comment by frankmorgner** [comment]
You need to recompile with OpenPACE. I've added an error message now...

Next time, please also include a build log... this would speed up things...

**Comment by Jakuje** [comment]
I assume the reporter is the same one as I got a bug from in https://bugzilla.redhat.com/show_bug.cgi?id=2030739 which I closed because we don't have openpace in Fedora. I believe the OpenPACE can not work without the brainpool curves. @frankmorgner  Am I right or is there something that might work even without them and it would make sense to package the library in Fedora?

**Comment by frankmorgner** [comment]
I know some other european ID cards are using the NIST curves instead of the brainpool curves, but when it comes to the cards that are supported by OpenSC, brainpool curves are required to make the German card working.

**Comment by tuxmaster5000** [comment]
Try to build it with OpenPACE(1.1.1) fails,  with:
```
make[3]: Entering directory '/tmp/OpenSC/src/sm'
  CC       libsmeac_la-sm-eac.lo
sm-eac.c: In function 'perform_pace':
sm-eac.c:1167:66: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 1167 |                 r = eac_gen_auth_1_encrypted_nonce(card, (u8 **) &enc_nonce->data,
      |                                                                  ^~~~~~~~~~~~~~~~
sm-eac.c:1202:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 1202 |                                 (u8 **) &mdata_opp->data, &mdata_opp->length);
      |                                         ^~~~~~~~~~~~~~~~
sm-eac.c:1228:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 1228 |                                 (u8 **) &pub_opp->data, &pub_opp->length);
      |                                         ^~~~~~~~~~~~~~
sm-eac.c:1255:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 1255 |                                 (u8 **) &token_opp->data, &token_opp->length,
      |                                         ^~~~~~~~~~~~~~~~
sm-eac.c: In function 'eac_sm_pre_transmit':
sm-eac.c:2214:76: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 2214 |                                                         (unsigned char **) &eacsmctx->auxiliary_data->data);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:527: libsmeac_la-sm-eac.lo] Error 1
make[3]: Leaving directory '/tmp/OpenSC/src/sm'
make[2]: *** [Makefile:463: all-recursive] Error 1
make[2]: Leaving directory '/tmp/OpenSC/src'
make[1]: *** [Makefile:606: all-recursive] Error 1
make[1]: Leaving directory '/tmp/OpenSC'
make: *** [Makefile:514: all] Error 2

```

**Comment by frankmorgner** [comment]
strange that this doesn't show up with gcc 10.3.0 for me. I've pushed a change to #2463 which should fix the problem.

**Comment by Jakuje** [comment]
> strange that this doesn't show up with gcc 10.3.0 for me. I've pushed a change to #2463 which should fix the problem.

Does it show up for you if you use `-Wstrict-aliasing=2` (and `--enable-strict` configure option)? I was fixing this in some other code, but probably not this part as I do not have openpace. It might require newer gcc though -- I have 11.2.1.

**Comment by tuxmaster5000** [comment]
I have also 11.2.1
gcc --version
gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
#2463 failed today to apply on the master.
No I simple call:
PKG_CONFIG_PATH=/tmp/Bla_LIB/lib/pkgconfig ./configure --prefix=/tmp/bla_BIN
The PKG_CONFIG_PATH is for the openpace lib.
