### ISSUE TITLE
Inconsistent implementation and lack of documentation of key ID parameter parsing of pkcs11-tool

### ISSUE THREAD

**Issue by egassemcinatas** [OpenSC/OpenSC#2465]
The hex_to_bin() function in pkcs11-tool.c contains an inconsistency:  The
parsing tolerates colon separators, but the check for the number of hex digits
at the start of the function does not account for them.  As a consequence,
using the --id option of pkcs11-tool with an ID with an even number of bytes
separated by colons will result in a failed operation.

To reproduce, try for example a decryption operation with a key ID with an even
number of bytes given with colon separators:

    pkcs11-tool  -l --decrypt --id 12:34:56:78 -i infile -o outfile

Or run this test program showing the input and output of hex_to_bin():
https://volkerschatz.com/tmp/hex2bintest.c

    in: 12:34:56:78
    out: 01 02 34 56 78
    in: 1:234:56
    out: 01 23 04 56

The test program also demonstrates another issue, that hex_to_bin() tolerates
more than two hex digits between colons and produces a result that is probably
not expected by the user.

What type of input to accept is a design decision on you part.  But whatever
you choose, please document the valid parameter format for the -e and -d
options (which use hex_to_bin) in the pkcs11-tool manual page.

**Comment by dengert** [comment]
Looks like a bug. 
```
in: 12:34:56:78
out: 01 02 34 56 78
```
is definitely incorrect. 

OpenSC has a `sc_hex_to_bin`  and `pkcs11-tool.c` also has a `hex_to_bin` and pkcs11-tool.c uses both.
Other tools use the sc_hex_to_bin, that handles the ":" correctly. 

looks like the `hex_to_bin` should be removed, and `sc_hex_to_bin` used in its place.

**Comment by popovec** [comment]
sc_hex_to_bin() output:
`````
in: 12:34:56:78
out: 12 34 56 78 
in: 1:234:56
out: 12 34 56
`````

I am not sure if second input is valid and if we should report a warning/error in this case as well.

**Comment by dengert** [comment]
If the intent was ":" (or spaces?)  separates strings of hex digits which may have a missing leading "0" , then:
"in: 1:234:56" 
should be 
"out: 01 02 34 56"?

[code](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/sc.c#L102-L108) has special case for a single hex digit.  It is assumed to have a leading "0". (What ever we do we should make sure this still works.) 

So separators don't separate anything. They are for the user's readability. And accept for the 1 hex digit case, there must be an even number of digits.  

Should we change it?

**Comment by popovec** [comment]
Before uploading  a corrected PR #2476 (including a small hit to `sc_hex_to_bin()`), I would like to consult here, if the following test strings are appropriate.  I introduced a rule in the `sc_hex_to_bin()` function that requires that there always be an even number of characters between the separators.  It remains possible to specify the first byte with only one character (as it has been so far).


`````
                {1, "0", "\x00"},
                {1, " 0", "\x00"},
                {1, "00", "\x00"},
                {1, ":00", "\x00"},
                {1, ":0", "\x00"},      /* special case, the 1st byte can be specified by one char.. */
                {1, " :0 :", "\x00"},
                {1, "d", "\x0d"},
                {1, ":a", "\x0a"},
                {1, " :b :", "\x0b"},
                {1, " :c ", "\x0c"},
                {1, "01", "\x01"},
                {1, " 09", "\x09"},
                {1, ":0a", "\x0a"},
                {1, " :0b :", "\x0b"},
                {1, "10", "\x10"},
                {1, " 90", "\x90"},
                {1, ":a0", "\xa0"},
                {1, " :B0 :", "\xb0"},
                {1, " 11:", "\x11"},
                {1, " :11:", "\x11"},
                {1, ":a1", "\xa1"},
                {2, "1:10", "\x01\x10"},
                {2, "01:10", "\x01\x10"},
                {2, "10:10", "\x10\x10"},
                {2, " 12ab", "\x12\xab"},
                {3, "10:20:30", "\x10\x20\x30"},
                {3, "1020:30", "\x10\x20\x30"},
                {3, "1020: :30", "\x10\x20\x30"},
                {3, "102030", "\x10\x20\x30"},
                {3, ":102030", "\x10\x20\x30"},
                {3, ":102030:", "\x10\x20\x30"},
                {3, ":102030::", "\x10\x20\x30"},
                {3, "b2:11 :22", "\xb2\x11\x22"},
                {3, "b2 11 22", "\xb2\x11\x22"},
                {9, "10:203040:5060708090", "\x10\x20\x30\x40\x50\x60\x70\x80\x90"},
                {0, "::::", ""},
                {0, ":", ""},
                {0, " ", ""},
                {0, "", ""},
                {C_ERROR, " :b:2 :", ""}, /* only 1st byte is allowed to be specified by one char */
                {C_ERROR, " ::1:2:a:b", ""},
                {C_ERROR, "1:1", ""},
                {C_ERROR, " :1 1:", ""},
                {C_ERROR, "0:0 :", ""},
                {C_ERROR, "1:234:56", ""}, /* odd number of characters between delimiters  (234) */
                {C_ERROR, " :b:211 :", ""},
                {C_ERROR, "02030", ""}, /* one char missing (to have full byte) */
                {C_ERROR, "111", ""},
                {C_ERROR, "b:211 :2", ""},
                {C_ERROR, "G", ""},
                {C_ERROR, " z", ""},
                {C_ERROR, ":a1:1", ""},
`````
@jakuje thank you for the hints ...  
String "1:11" is handled as error, after applying PR it will be the correct string. 
String "1:234:56" is handled as correct, but  after applying PR this is wrong string .. 
Is this acceptable ? 
@frankmorgner I would also like to know your opinion, as you are the author of most lines of the `sc_hex_to_bin()` function.

**Comment by dengert** [comment]
Personally, I would consider  `{2, "1:10", "\x01\x10"},`  an error, as it is meant to be a hex string.

I had interpreted the special case of a single digit to apply only to 0 to 9 **and only with one character as input.** Thus a user did not care if they were providing a string or an integer in decimal or hex value.  (And this behavior should be kept as users may have scripts that depend on this.) 

`pkcs11-tool --help` or man page are a bit loose on the use of "id". Is it a hex string or integer.  For example `pkcs11-tool --help` says:

"--id id, -d id     Specify the id of the object to operate on." This uses `hex_to_bin`

 " --slot id     Specify the id of the slot to use." This is `OPT_SLOT` and uses `strtoul(optarg, NULL, 0);` which can accept decimal, octal (leading "0") or hex with leading "0x". can also accept leading "+" or "-". 

grep pkcs11-tool.c shows:
```
			opt_salt_len = (CK_ULONG) strtoul(optarg, NULL, 0);
			opt_slot = (CK_SLOT_ID) strtoul(optarg, NULL, 0);
			opt_slot_index = (CK_ULONG) strtoul(optarg, NULL, 0);
			opt_object_index = (CK_ULONG) strtoul(optarg, NULL, 0);
			opt_random_bytes = strtoul(optarg, NULL, 0);
		return strtoul(name, NULL, 0);
```

 We should clarify the arguments in `pkcs11-tool.c` 

`pkcs11-tool` is the only utility that uses `strtoul(optarg, NULL, 0);` others use it but set the base to 10 or 16.

**Comment by frankmorgner** [comment]
The [original code](https://github.com/OpenSC/OpenSC/blame/0abe9d11c75f8d9de32e862a5a9775aa70a44cc3/src/libopensc/sc.c#L64) dates back 20 years ago. I think pkcs11-tool.c had some older version to avoid linking to libopensc. [This old commit](https://github.com/OpenSC/OpenSC/commit/c83fa88ca86973fbb4fbd30e05f8d546b1c8f8ed) was done to allow an odd number of bytes. In all versions the inputs ` :` are just ignored (read: not treated as seperators between bytes). In my rewrite from 2019, I was fixing some inconsistencies with the code and didn't expect to actually fix the problem reported in this issue (but I feel relieved anyway). My goal back than was to keep the original *intended* behavior.

Having said that, I always felt uncomfortable allowing an odd number of hex strings. I think it's most likely that this would be a typo. Also, if I would be starting from scratch, I'd force *user supplied* hex strings to start with `0x`. Unfortunately, 20 years ago someone decided to display and edit the IDs with pkcs11-tool by using hex digits so we now have to live with that.

I think a good compromise (that hopefully doesn't break anything) could be
- to allow a single hex digit
- to allow seperators only iff `byte_needs_nibble` is `0`, i.e. when a full byte has been read

So this would mean that I think that the examples given above should be rejected as invalid...

**Comment by Jakuje** [comment]
Thank you for the git archeology. I totally agree that we should be more strict about what we accept. As of today, I think the `pkcs11-tool` links to libopensc anyway so this should not be an issue.

Its always "bad" to break or change commandline "API", but we can hope that nobody depends on the above corner cases.
