### ISSUE TITLE
Error signing with NitroKey HSM and opensc 0.22 with algorithm CKM_ECDSA_SHA256

### ISSUE THREAD

**Issue by xipki** [OpenSC/OpenSC#2469]
### Problem Description
Hardware: NotroKey HSM, opensc v0.22,
Signing over the PKCS#11 interface, with CKM_ECDSA_SHA256 (0x1044), and the data to sign 1047 bytes ends with erro CKR_DATA_LEN_RANGE

### Proposed Resolution
N/A

### Steps to reproduce
1. SIGN_INIT with CKM_ECDSA_SHA256
2. SIGN with 1047 bytes data

### Logs

See log file (the sign part is between line 3450 - 3473)
[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/7707446/opensc-debug.txt)

**Comment by frankmorgner** [comment]
Looks like your return buffer is too small...
https://github.com/OpenSC/OpenSC/blob/c902e1992195e00ada12d71beb1029287cd72037/src/pkcs11/pkcs11-object.c#L716-L720

**Comment by Jakuje** [comment]
this is different error than visible in the log. It says `CKR_DATA_LEN_RANGE`. Can you try with master version of opensc. I think this was fixed with 042f2d17bcabce16b96646aeb174ee671f984eea, which should allow signing unlimited data lengths.

**Comment by xipki** [comment]
Just tested the master version of OpenSC. It works for data up to 1222 bytes, for data with 1223+ bytes the C_SIGN returns CKR_DATA_INVALID.

I attached two log files for comparison:
[opensc-debug-data1222.txt](https://github.com/OpenSC/OpenSC/files/7711325/opensc-debug-data1222.txt): successful, sign with data of 1222 bytes (related sign operation is logged in lines 5922 - 6074)
[opensc-debug-data1223.txt](https://github.com/OpenSC/OpenSC/files/7711328/opensc-debug-data1223.txt): failed, sign with data of 1223 bytes (related sign operation is logged in lines 6174 - 6441).

**Comment by dengert** [comment]
card driver says card can do the hash on the card:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-sc-hsm.c#L1634-L1640

Outgoing APDU for 1222 is at line 5974 `80 68 12 73 00 04 C6 ...` and returns signnature at line 6056

Outgoing APDU for 1223 is at line 6227 `80 68 13 73 00 04 C7 ...` and returns `6A 80` at line 6309.

This may be a card limitation. Or it may be the card driver  should be sending chucks of data not all the data in one APDU.

**Comment by dengert** [comment]
In the APDUs
Outgoing APDU for 1222 is at line 5974 80 68 12 73 00 04 C6 ... and returns signature at line 6056
Outgoing APDU for 1223 is at line 6227 80 68 13 73 00 04 C7 ... and returns 6A 80 at line 6309
the key reference is not the same. It worked with "12" but not "13" so key "13" may not work with ECDSA. 

So this may not be a card limitation, but the wrong key.

@xipki  there may still be a practical limit on how much data can be sent to the card in one APDU based on the the 65K limit for extended APDUs or some card limitation but not 1223.  Do you have any documentation on what the device can handle?

You (or OpenSC) may need to do the SHA256 in software then send the hash to be signed, or if the card can handle it, send data in chucks, maybe with use command chaining.

The APDUs come from:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-sc-hsm.c#L1117-L1126
`#define ALGO_EC_SHA256                  0x73            /* ECDSA signature with SHA-256 hash */`

**Comment by xipki** [comment]
Thanks for the detailed analysis.
About the key, for each test (data1222 and data1223) I generate the keypair on the fly and then execute the sign operation. So they are different keys, and it shall not to do with the error (I also tested with the same key but with the same error).

Yes, the application can compute the hash value first and then call CKM_ECDSA (raw ECDSA) with the hash value as input. However I think it is better that the opensc driver computes the hash value in software, and then calls the raw ECDSA operation.

**Comment by Jakuje** [comment]
> Yes, the application can compute the hash value first and then call CKM_ECDSA (raw ECDSA) with the hash value as input. However I think it is better that the opensc driver computes the hash value in software, and then calls the raw ECDSA operation.

OpenSC can do that, but it does it only when the card does not support the hashing itself. This might be a requirement for passing some certifications (for example FIPS), to make sure both of the operations are done as part of the same context in the HW.

**Comment by frankmorgner** [comment]
maybe `card->max_send_size` should be adapted changed accordingly for this token. This way, we would see this limitation already before...

**Comment by dengert** [comment]
@CardContact   Can the size of the "internal APDU buffer" be read from the device? 

I see 7858f3cd0 from 2019 tries to set the `card->max_send_size = 1232 - 17;`  which the  debug log says is:` card.c:382:sc_connect_card: card info name:martCar'Sd-HSM version 3.4', type:26000, flags:0x0, max_send/recv_size:1215/65536`

Yet the  working apdu is `80 68 12 73 00 04 C6 ...` Lc=0x04C6=1222, and failing apdu has Lc=0x04C7=1223
i.e. 4 byte APDU, 3 byte Lc, 1222 data bytes and 2 byte Le.  

Do any of the cards support command chaining that could be used to send the data to be hashed in chunks? 
This would be similar to C_SignInit,  C_SignUpdate(s)  and  C_SignFinal. This would remove any length restrictions.

**Comment by xipki** [comment]
> When the hash must be calculated in the card, then the maximum message length is limited by the size of the internal APDU buffer. Larger messages should be hashed in the application and the result passed into the card using CKM_ECDSA.

The behavior for the RSA based mechanisms like CKM_SHA256_RSA_PKCS is different than ECDSA. opensc computes the hash value, adds the padding, and only sends the padded hash value to the card.

**Comment by xipki** [comment]
> Do any of the cards support command chaining that could be used to send the data to be hashed in chunks?
> This would be similar to C_SignInit, C_SignUpdate(s) and C_SignFinal. This would remove any length restrictions.
This sounds reasonable. I tested with C_SignUpdate, but received CKR_DATA_INVALID after calling C_SignFinal. It seems that opensc collects data received by all C_SignUpdate steps, and sends it in C_SignFinal to the card.

**Comment by Jakuje** [comment]
> > When the hash must be calculated in the card, then the maximum message length is limited by the size of the internal APDU buffer. Larger messages should be hashed in the application and the result passed into the card using CKM_ECDSA.
> 
> The behavior for the RSA based mechanisms like CKM_SHA256_RSA_PKCS is different than ECDSA. opensc computes the hash value, adds the padding, and only sends the padded hash value to the card.

This is, because the card does not support the Digest and Sign operation APDU or the driver is not configured to request this functionality from OpenSC. AFAIK for the CKM_SHA256_RSA_PKCS_PSS it is possible to do the digest and padding on the card directly.

> > Do any of the cards support command chaining that could be used to send the data to be hashed in chunks?
> > This would be similar to C_SignInit, C_SignUpdate(s) and C_SignFinal. This would remove any length restrictions.
> 
> This sounds reasonable. I tested with C_SignUpdate, but received CKR_DATA_INVALID after calling C_SignFinal. It seems that opensc collects data received by all C_SignUpdate steps, and sends it in C_SignFinal to the card.

Yes. This would need some modification to the driver to support chaining or support sending the bogus input blocks.

**Comment by dengert** [comment]
In response to CKM_SHA256_RSA_PKCS question, https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-sc-hsm.c#L1626 says the card only supports SC_ALGORITHM_RSA_RAW and SC_ALGORITHM_RSA_PAD_PSS on the card. So OpenSC will do everything else in software first. 

Sorry if I mislead you with the  "C_SignInit, C_SignUpdate(s) and C_SignFinal." comment. That was for the card developers. I was trying to say, if the card could support APDU command chaining, the first APDU in the chain has a flag set to expect more, data and it could start a hash operation, then the next APDU in the chain could provide more data to hash. This is repeated until the last APDU does not have the chaining bit set would provide that last part of the data and return the signature.

**Comment by saper** [comment]
SmartCard HSM docs for 3.5 firmware have a table
|Platform | APDU Size
| ----- | ---- | 
| JCOP 2.4.1r3 ('00', '01', '02') | 1462 |
| JCOP 2.4.2rx ('03', '04') | 1454 |
| JCOP 3 ('05') | 1232 ( < 3.4) 1234 ( >= 3.4) |

Table 11 - APDU Size

SmartCard-HSM 4.0 (newer than Nitrokey HSM) adds JCOP 4 ('06') with the limit of 1454

**Comment by frankmorgner** [comment]
sc-hsm doesn't support command chaining. if you need to sign BIG messages, you must perform the hash outside of the card.
