### ISSUE TITLE
./configure failed for OpenSC on Ubuntu 20.04

### ISSUE THREAD

**Issue by nshah2588** [OpenSC/OpenSC#2479]
### Problem Description

./configure command doesn't work without errors

### Proposed Resolution

I don't know how to do this:

Perhaps you should add the directory containing `libeac.pc'
to the PKG_CONFIG_PATH environment variable

### Steps to reproduce

Follow the steps to first download opensc and then run sudo ./configure after extraction of the file

### Logs

<script src="https://gist.github.com/nshah2588/bc1f6e62415de4fe53ba080cff566120.js"></script>

**Comment by popovec** [comment]
install all the packages you need to build opensc:
`````
sudo apt-get  build-dep opensc
`````

**Comment by Jakuje** [comment]
The OpenSC dependencies are described in the Wiki: https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors. The `libeac` is not mandatory and opensc works just fine without that. The error you got is
```
configure: error: winscard.h is required for pcsc
```
which is the missing pcsc-lite. You can install it on ubuntu as already suggested by @popovec.

There is nothing more we could do for you.
