### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by ugochirico** [OpenSC/OpenSC#2480]
I have to build OpenSC for Android. I've searched for days to find some instructions but I was not able to find anything that help me.
Are there some instructions?

**Comment by cyberneid** [comment]
Done! I was able to build on Android!

**Comment by ugochirico** [comment]
Done!

**Comment by dengert** [comment]
Where did you fine the instructions to build on Android? Others might be interested.

**Comment by ugochirico** [comment]
I didn't find any instructions. I do all myself. I do the following:
1) I created in Android studio an android project with NDK support, 
2) I created a config.h on Ubuntu20.04 by calling ./configure
3) I copied the config.h in the android project, 
4) I wrote a CMakeList.txt file (needed by NDK build) by merging the configurations in all Makefile.am in the various directories
5) I build all

**Comment by aleksame** [comment]
How do You use it in Android? Is it possible to use it to read PKI certificate from Smart card, from PKI applet stored on card?

**Comment by ugochirico** [comment]
Here is my CMakeList.txt
[CMakeLists.txt](https://github.com/OpenSC/OpenSC/files/9103333/CMakeLists.txt)

**Comment by thw0rted** [comment]
This probably isn't the place for it, but much like @aleksame I am an end user who would like to use PKI auth on Android.  I haven't been able to find much about it online and would really appreciate a for-dummies explainer showing how to do this (if it's possible at all).  I figured there's a slim chance that somebody watching this issue can help, so it doesn't hurt to ask.

**Comment by aleksame** [comment]
We ended up by doing custom SSL authentication using APDU commands, which
was successful and there was no need for OpenSC as we only use this for
reading PKI  cert from Smart card applet and use it to authenticate against
API.

**Comment by thw0rted** [comment]
Ah, OK, I guess you weren't actually trying the same thing I am.  I authenticate to websites (on desktop) using certificates from a smartcard, and would like to be able to do that in a mobile browser as well.  Apparently this is very poorly supported, at least on Android.  There's one company that charges a hundred bucks (!!!) for a PKI-capable web browser that they haven't even updated in over 2 years, and that's about it.

**Comment by aleksame** [comment]
It looks to me that we did the same thing, reading PKI certificate from
Smart Card in order to authenticate with it on API endpoint.
I also think that this is very poorly supported and that there is almost
zero documentation online regarding this. That can explain too why those
guys charge hundreds of dollars for that.

**Comment by Ossma1** [comment]
@ugochirico Would you be so kind to share your resulting the file *.so for android

**Comment by marsicdev** [comment]
Hey @aleksame I have the exact same use case as you here, ping me if you are available for expert consultation regarding this.
