### ISSUE TITLE
Huge macOS binaries

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2488]
### Problem Description

The macOS binaries generated during the CI process are huge. For example `/Library/OpenSC/bin/cardos-tool` is 4.4 MB big. Some files don't seem to be effected; for example `/Library/OpenSC/bin/openpgp-tool` is only 187 KB big. In total, the size of the installer is around 200MB what used to be around 40MB.

### Proposed Resolution

unknown

### Steps to reproduce

A current build with logs and installer for macOS can be found here, for example
https://github.com/OpenSC/OpenSC/actions/runs/1709309663

**Comment by frankmorgner** [comment]
This is the initial configuration for compiling:
```
2022-01-17T18:21:01.5072200Z Host:                    x86_64-apple-darwin19.6.0
2022-01-17T18:21:01.5072650Z Compiler:                gcc
2022-01-17T18:21:01.5073070Z Preprocessor flags:      
2022-01-17T18:21:01.5074110Z Compiler flags:          -Wall -Wextra -Wno-unused-parameter -Werror -Wstrict-aliasing=2  -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -arch x86_64 -arch arm64
2022-01-17T18:21:01.5074830Z Linker flags:             -arch x86_64 -arch arm64
2022-01-17T18:21:01.5076680Z Libraries:               
2022-01-17T18:21:01.5084500Z 
2022-01-17T18:21:01.5101540Z READLINE_CFLAGS:         
2022-01-17T18:21:01.5102250Z READLINE_LIBS:           -lreadline 
2022-01-17T18:21:01.5102700Z ZLIB_CFLAGS:             
2022-01-17T18:21:01.5103230Z ZLIB_LIBS:               -lz
2022-01-17T18:21:01.5104090Z OPENSSL_CFLAGS:          -I/Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/include
2022-01-17T18:21:01.5108190Z OPENSSL_LIBS:            -L/Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/lib -lcrypto
2022-01-17T18:21:01.5114430Z OPENPACE_CFLAGS:         -I/Users/runner/work/OpenSC/OpenSC/openpace_bin/Library/OpenSC/include -I/Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/include
2022-01-17T18:21:01.5121240Z OPENPACE_LIBS:           -L/Users/runner/work/OpenSC/OpenSC/openpace_bin/Library/OpenSC/lib -leac -lcrypto -L/Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/lib -lcrypto
2022-01-17T18:21:01.5137200Z OPENCT_CFLAGS:           
2022-01-17T18:21:01.5137660Z OPENCT_LIBS:             
2022-01-17T18:21:01.5138630Z PCSC_CFLAGS:             -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System
```
forcing the compiler to clang [shows the same problem](https://github.com/OpenSC/OpenSC/actions/runs/1712738958)

**Comment by mouse07410** [comment]
Offhand, I suspect that you're creating "fat" binaries that on top of that statically link all the libraries, like OpenSSL.

Whether that's sufficient to explain such an increase in size - I don't know.

**Comment by frankmorgner** [comment]
we don't use fat binaries anymore. we're just building 64 bits.

**Comment by frankmorgner** [comment]
The installer of 98f6d77 [was 40 MB](https://github.com/OpenSC/OpenSC/actions/runs/1167034444), the installer of 703183e [was 133 MB](https://github.com/OpenSC/OpenSC/actions/runs/1181550216). As far as I can see, the only difference on macOS is the code signing... https://github.com/OpenSC/OpenSC/compare/98f6d77...703183e

**Comment by frankmorgner** [comment]
A local build with code signing enabled also yields such a big installer, because only with this the CTK driver is built which contains an other copy of opensc linked against CTK instead of PC/SC.

Double checking the binaries, they indeed contain code for x64 and arm64, so that explains some increase in size.

However, looking at the individual files, I still wonder if we're doing anything wrong. As stated above, some files are way bigger than others (compare openpgp-tool and cardos-tool, for example)...

**Comment by frankmorgner** [comment]
```
bloaty ./cardos-tool                                                 /Library/OpenSC/bin
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  62.3%  2.73Mi  65.2%  1.53Mi    __TEXT,__text
   6.7%   299Ki   5.8%   139Ki    __TEXT,__const
   5.5%   247Ki   5.3%   126Ki    String Table
   4.6%   204Ki   4.5%   107Ki    Symbol Table
   4.5%   202Ki   4.2%   101Ki    __TEXT,__cstring
   3.8%   171Ki   3.6%  86.4Ki    Export Info
   3.5%   155Ki   6.5%   155Ki    __DATA,__const
   3.4%   151Ki   0.0%      10    __DATA_CONST,__const
   2.1%  92.6Ki   2.0%  48.3Ki    Code Signature
...
```
```
bloaty ./openpgp-tool                                                /Library/OpenSC/bin
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  20.8%  38.9Ki  37.1%  35.6Ki    Code Signature
  17.6%  33.0Ki  17.7%  17.0Ki    __TEXT,__text
  15.2%  28.5Ki  12.5%  12.0Ki    [__DATA]
  11.2%  21.1Ki   0.0%       0    [Unmapped]
   9.0%  16.8Ki   8.7%  8.39Ki    [__TEXT]
   7.5%  14.1Ki   0.0%       0    [__DATA_CONST]
   4.0%  7.46Ki   3.9%  3.73Ki    __TEXT,__cstring
   2.7%  4.97Ki   2.6%  2.47Ki    Symbol Table
...
```

**Comment by frankmorgner** [comment]
One difference between cardos-tool and openpgp-tool is that the former is statically linked to OpenSSL while the latter does not. Both tools, are using libopensc, which is also statically linked to OpenSSL. This problem may be transitive, when libopensc is statically linked to OpenPACE, which itself is also statically linked to OpenSSL.

My personal prejudice was that the compiler/linker optimization should throw out unused or duplicated functionality when being statically linked, but maybe there's something else we need to achieve this...

**Comment by dengert** [comment]
Is problem OpenSSL is built with: `+ ./config no-shared --prefix=/Library/OpenSC` so all tools are statically linked?

**Comment by dengert** [comment]
I have not built OpenSC on MacOS since 2009. Not sure what MacOS does these days., but when I built OpenSC I added  `DYLD_LIBRARY_PATH=<paths to the non-standard lib dirs>` even during configure. 
On other platforms I add an `LDFLAGS="$LDFLAGS -Wl,-rpath,$PREFIX/lib"`  so there is no question on where to look for shared libs.

**Comment by frankmorgner** [comment]
It seems that our binaries are indeed so big because
- we're producing fat binaries (arm64/x64) and
- OpenSSL is linked statically

Unfortunately, linking dynamically is not an option, because libtool doesn't know now to dynamically linking a module with static dependencies, see https://www.mail-archive.com/libtool@gnu.org/msg10581.html. We want this for the PKCS#11 module to be relocatable on macOS, because some applications can only load libraries from specific directories (ssh, I think). Also, we want to avoid clashes with other versions of linked dependencies.

An other option we could explore would be to build a minimal version of OpenSSL to reduce the overhead. However, that's not an easy task either, see https://github.com/openssl/openssl/issues/11308.

**Comment by mouse07410** [comment]
I can only say that on my MacOS systems I link OpenSC dynamically with Macports-installed OpenSSL (was 1.1.1, now 3.0.1).
Everything seems to be working fine, including apps that use OpenSSL and access keys on HW tokens via libp11+OpenSC.

**Comment by frankmorgner** [comment]
> I can only say that on my MacOS systems I link OpenSC dynamically with Macports-installed OpenSSL (was 1.1.1, now 3.0.1). Everything seems to be working fine, including apps that use OpenSSL and access keys on HW tokens via libp11+OpenSC.

If you have one single ecosystem, this will work. But if you have a PKCS#11 applications that ships some other dynamically linked OpenSSL, you may get a clash when "their" module provides the same symbols as "macport"'s module. I had this very same problem on Windows and let me tell you it is not easy to debug 😵 . That's why you want statically linked modules (.so files).

**Comment by mouse07410** [comment]
Yes, on all of my machines everything is either linked against the single Macports-provided dynamic (.dylib) OpenSSL, or MacOS-provided LibreSSL (only OS-provided binaries).

I don't know how hard it would be to enforce something like that on a "generic" installation.

**Comment by dengert** [comment]
https://www.finkproject.org/doc/porting/porting.en.html spells out the difference of a module vs a shared library. It may be out of date. (MacOS 10.4) But https://www.finkproject.org/doc/porting/porting.en.html#shared.lib-and-mod says:
"One Mach-O feature that hits many people by surprise is the strict distinction between shared libraries and dynamically loadable modules. On ELF systems both are the same;"
and
"Loadable modules are called "bundles" in Mach-O speak. ...  it is possible that a bundle is linked against real shared libraries; those will be loaded automatically when the bundle is loaded."

Sounds like the pkcs11 module should be a bundle i.e. `ld -bundle` It should only have one or two entry points, and should use any references from the calling application. 
(Ran across this with PAM loading a Kerberos module years ago. There are
