### ISSUE TITLE
Nitrokey Storage 2 problems with SSH and x509 certificate

### ISSUE THREAD

**Issue by Unb0rn** [OpenSC/OpenSC#2527]
### Problem Description

Hey! I'm not sure if this is an OpenSC issue but maybe someone will be able to help me.
I'm trying to use my Nitrokey Storage 2 with x509 certificate (RSA-2048 key) to login via ssh.

First I got my PKCS12 package with cert and privkey from Actalis (Free S/MIME one)
Then I loaded it to my nitrokey with pkcs15-init:

```
pkcs15-init --delete-objects privkey,pubkey --id 3 --store-private-key package.pfx --format pkcs12 --auth-id 3 --verify-pin --ignore-ca-certificates
pkcs15-init --delete-objects privkey,pubkey --id 2 --store-private-key package.pfx --format pkcs12 --auth-id 3 --verify-pin --ignore-ca-certificates
```
There was some problem with the second command but the official [doc](https://docs.nitrokey.com/storage/linux/smime.html) says its okay.

Now I can see those keys (slots 2 and 3) in `gpg --card-status` and in `pkcs15-tool --dump`, I can also get the public ssh key with `pkcs15-tool --read-ssh-key 3`

But after I added it to the remote host and tried to login I got the following problem:

> C_SignInit failed: 99
> pkcs11_get_key failed
> sign_and_send_pubkey: signing failed for RSA "Encryption key": error in libcrypto

I'm using opensc-pkcs11.so provider in ssh.
I have no idea if its my error, OpenSC's issue or Nitrokey's bug)

### Steps to reproduce

1. Get the certificate (at least with RSA key)
2. Load it to the token
3. Extract SSH public key
4. Try SSH login with opensc-pkcs11 provider

### Logs
ssh -vvv :
> 
> debug1: Offering public key: Encryption key RSA SHA256:K7i4V1Rb8oYGsEeQFC5XI6+uNPFzFuFncXdpHJ6qn6c token
> debug3: send packet: type 50
> debug2: we sent a publickey packet, wait for reply
> debug3: receive packet: type 60
> debug1: Server accepts key: Encryption key RSA SHA256:K7i4V1Rb8oYGsEeQFC5XI6+uNPFzFuFncXdpHJ6qn6c token
> debug3: sign_and_send_pubkey: using publickey with RSA SHA256:K7i4V1Rb8oYGsEeQFC5XI6+uNPFzFuFncXdpHJ6qn6c
> debug3: sign_and_send_pubkey: signing using rsa-sha2-512 SHA256:K7i4V1Rb8oYGsEeQFC5XI6+uNPFzFuFncXdpHJ6qn6c
> Enter PIN for 'OpenPGP card (User PIN)': 
> debug1: C_FindObjects failed (nfound 0 nattr 3): 0
> C_SignInit failed: 99
> pkcs11_get_key failed
> debug1: identity_sign: sshkey_sign: error in libcrypto
> sign_and_send_pubkey: signing failed for RSA "Encryption key": error in libcrypto
> debug1: pkcs11_k11_free: parent 0x55ab04c34b40 ptr (nil) idx 1

**Comment by Jakuje** [comment]
Is it Ubuntu? What OpenSSH version?

Does `pkcs11-tool --test` work for you?

**Comment by Unb0rn** [comment]
In Arch.
`OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022`

pkcs11-tool --test

> Using slot 0 with a present token (0x0)
> C_SeedRandom() and C_GenerateRandom():
>   seeding (C_SeedRandom) not supported
>   seems to be OK
> Digests:
>   all 4 digest functions seem to work
>   MD5: OK
>   SHA-1: OK
>   RIPEMD160: OK
> Signatures (currently only for RSA)
> Signatures: no private key found in this slot
> Verify (currently only for RSA)
>   No private key found for testing
> Decryption (currently only for RSA)
> No errors

In fact, I have another Nitrokey with GPG-created keys and have no problems using them with OpenSSH (The same machine with the same OpenSSH and OpenSC. Those GPG keys on this separate token are nistp521)

**Comment by dengert** [comment]
Try `pkcs11-tool --test --login`

**Comment by dengert** [comment]
Sorry, the previous comment was too short. `pkcs11-tool --test` does not test ECC keys.
Try `pkcs11-tool -O --login`
See if  IDs on matching certificates, public keys and private keys match. and 521 keys are listed. 

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-openpgp.c#L90-L115 shows 521 keys are supported on one version of openpgp tokens, but not on Gunk. 

Look at https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC and turn on debug level 3 at least. Could be done with OpenSSH.  

Try `pkcs11-tool --test-ec` with additional parameters as needed.

(I have not tried this with any  nistp521 keys.)

**Comment by Unb0rn** [comment]
Okay, first goes my first Nitrokey Storage 2 with x509 certificate and RSA 2048 key on it:
`pkcs11-tool --login --test`

> Using slot 0 with a present token (0x0)
> Logging in to "OpenPGP card (User PIN)".
> Please enter User PIN: 
> C_SeedRandom() and C_GenerateRandom():
>   seeding (C_SeedRandom) not supported
>   seems to be OK
> Digests:
>   all 4 digest functions seem to work
>   MD5: OK
>   SHA-1: OK
>   RIPEMD160: OK
> Signatures (currently only for RSA)
>   testing key 0 (Encryption key)  -- can't be used for signature, skipping
>   testing key 1 (Authentication key) 
>   all 4 signature functions seem to work
>   testing signature mechanisms:
>     RSA-PKCS: OK
>     SHA1-RSA-PKCS: OK
>     MD5-RSA-PKCS: OK
>     RIPEMD160-RSA-PKCS: OK
>     SHA256-RSA-PKCS: OK
>   testing key 1 (Authentication key) with 1 mechanism
>     RSA-PKCS: OK
> Verify (currently only for RSA)
>   testing key 0 (Encryption key) -- can't be used to sign/verify, skipping
>   testing key 1 (Authentication key) with 1 mechanism
>     RSA-PKCS: OK
> Decryption (currently only for RSA)
>   testing key 0 (Encryption key)
>     RSA-PKCS: OK
>   testing key 1 (Authentication key)
>     RSA-PKCS: OK
> No errors

And cryptographic objects on this token are:
`pkcs11-tool --login --list-objects`

> Using slot 0 with a present token (0x0)
> Logging in to "OpenPGP card (User PIN)".
> Please enter User PIN: 
> Private Key Object; RSA 
>   label:      Encryption key
>   ID:         02
>   Usage:      decrypt, unwrap
>   Access:     sensitive, always sensitive, never extractable, local
> Public Key Object; RSA 2048 bits
>   label:      Encryption key
>   ID:         02
>   Usage:      encrypt, wrap
>   Access:     none
> Private Key Object; RSA 
>   label:      Authentication key
>   ID:         03
>   Usage:      decrypt, sign, non-repudiation, unwrap
>   Access:     sensitive, always sensitive, never extractable, local
> Public Key Object; RSA 2048 bits
>   label:      Authentication key
>   ID:         03
>   Usage:      encrypt, verify, wrap
>   Access:     none
> Certificate Object; type = X.509 cert
>   label:      Cardholder certificate
>   subject:    DN: CN=unb0rn@unb0rnet.tk
>   ID:         03
> Profile object 3473207072
>   profile_id:          '4'

It's impossible to SSH login with this token as I've already mentioned above.

Now my second Nitrokey Storage 2 token with ECC keys created with GPG and no x509 cert at all (obviously =) ) has the following objects:
`pkcs11-tool --login --list-objects`

> Using slot 0 with a present token (0x0)
> Logging in to "OpenPGP card (User PIN)".
> Please enter User PIN: 
> Private Key Object; EC
>   label:      Encryption key
>   ID:         02
>   Usage:      derive
>   Access:     sensitive, always sensitive, never extractable, local
> Public Key Object; EC  EC_POINT 384 bits
>   EC_POINT:   0461042d3c4923d7d1e4f2c7966d9c46cced16bb3ea53a83814a53e57ef438638f2680b29ac09f371aa3d22b06fd80e8d630ee2451f64df30e76e8800bd2150cdc1a37ebc1a783e2e46a929976662454ee22b2803dc85bd761daf5b7c40cd7566b7ba9
>   EC_PARAMS:  06092b240303020801010b
>   label:      Encryption key
>   ID:         02
>   Usage:      derive
>   Access:     none
> Private Key Object; EC
>   label:      Authentication key
>   ID:         03
>   Usage:      sign
>   Access:     sensitive, always sensitive, never extractable, local
> Public Key Object; EC  EC_POINT 528 bits
>   EC_POINT:   048185040049c3d7b754611c7dd91a97d9b2e97a106886c77a6cbb5b7047c6375f94f35eed4a5ed343db218261a475f5876be04966ccdd127dbc44f9605e101ce52bcf75022c004dcc8cfbcf67b396b876f5bb991fc0d3ba55eadaf7406111b0146b5dd1145f395530a76738b0296887802fcf8c8d485d2b5c92e551fbcf9f3b365e46c1abc2a0c1
>   EC_PARAMS:  06052b81040023
>   label:      Authentication key
>   ID:         03
>   Usage:      verify
>   Access:     none
> Profile object 413186496
>   profile_id:          '4'

It works fine with OpenSSH.
Public keys of both tokens were made with pkcs15-tool --read-ssh-key 3. OpenSSH successfully detects if the destination server has a pubkey of the respective token and offers to login to card requireing to enter the PIN.
The problem is, ECC token passes me through, while RSA one raises an error I've specified above.

> debug1: C_FindObjects failed (nfound 0 nattr 3): 0
> C_SignInit failed: 99
> pkcs11_get_key failed

I've also tried to understand what is wrong with pkcss-spy, maybe its' log will be helpful
[pkcs11-spy.log](https://github.com/OpenSC/OpenSC/files/8355549/pkcs11-spy.log)

**Comment by dengert** [comment]
You have 2 private keys:
```
Private Key Object; RSA
label: Encryption key
ID: 02
Usage: decrypt, unwrap
Access: sensitive, always sensitive, never extractable, local

Private Key Object; RSA
label: Authentication key
ID: 03
Usage: decrypt, sign, non-repudiation, unwrap
Access: sensitive, always sensitive, never extractable, local
```

`pkcs11-spy.log` is helpful 

It shows both public key are read from token  CKA_ID 02 and 03:
```
11: C_GetAttributeValue
2022-03-26 16:44:44.408
[in] hSession = 0x55caef7645f0
[in] hObject = 0x55caef761d90
[in] pTemplate[3]: 
    CKA_ID                000055caef7646e0 / 1
    CKA_MODULUS           000055caef764700 / 256
    CKA_PUBLIC_EXPONENT   000055caef764810 / 3
[out] pTemplate[3]: 
    CKA_ID                000055caef7646e0 / 1
    00000000  02                                               .               

15: C_GetAttributeValue
2022-03-26 16:44:44.409
[in] hSession = 0x55caef7645f0
[in] hObject = 0x55caef762b00
[in] pTemplate[3]: 
    CKA_ID                000055caef764b60 / 1
    CKA_MODULUS           000055caef764b80 / 256
    CKA_PUBLIC_EXPONENT   000055caef764c90 / 3
[out] pTemplate[3]: 
    CKA_ID                000055caef764b60 / 1
    00000000  03      
```
Then it reads the certificate 03 as expected:
```
       22: C_GetAttributeValue
2022-03-26 16:44:44.410
[in] hSession = 0x55caef7645f0
[in] hObject = 0x55caef762d20
[in] pTemplate[3]: 
    CKA_ID                000055caef764fc0 / 1
    CKA_SUBJECT           000055caef764fe0 / 31
    CKA_VALUE             000055caef765010 / 1506
[out] pTemplate[3]: 
    CKA_ID                000055caef764fc0 / 1
    00000000  03                                               .               
```
But then after login it it looks for   CKA_ID  02 !!!
```
34: C_FindObjectsInit
2022-03-26 16:44:47.510
[in] hSession = 0x55caef7645f0
[in] pTemplate[3]: 
    CKA_CLASS             CKO_PRIVATE_KEY      
    CKA_ID                000055caef764890 / 1
    00000000  02                                               .               
    CKA_SIGN              True
Returned:  0 CKR_OK
```
Note the above says only look for a private key,  with ID 02 and CKA_SIGN. 


which then fails:
```
40: C_SignInit
2022-03-26 16:44:47.510
[in] hSession = 0x55caef7645f0
[in] pMechanism->type = CKM_RSA_PKCS                 
[in] pMechanism->pParameter[ulParameterLen] NULL [size : 0x0 (0)]
[in] hKey = 0x55caef760d70
Returned:  99 CKR_KEY_TYPE_INCONSISTENT
C_SignInit failed: 99
pkcs11_get_key failed
sign_and_send_pubkey: signing failed for RSA "Encryption key": error in libcrypto
```

The part before login find that id ID 03  should be used, but after login it tries to use ID 02. 
The same certificate and key is loaded in to ID 02 and ID 03, but the usage bits
are defined differently as defined on OpenPGP. (I am not sure if you can override these.) 

So I question why did SSH switch from using ID 03 to ID 02?
What version of OpenSSH? 

Do you need both keys? Does it work if you only load the 03 cert and key? 
Have you asked NitroKey about this?

**Comment by Unb0rn** [comment]
Oh, it looks like this is where the fun part starts) Yeah, I've [tried](https://support.nitrokey.com/t/ssh-with-valid-x509-fails/1761) asking them several years ago but got no answer... Then you and frankmorgner managed to solve another my issue #1906 and I've been happily using my token since that time. Now I got myself second one and I need it to have this S/MIME x509 cert, so here we are...
My OpenSSH version is stated above, it is `OpenSSH_8.9p1, OpenSSL 1.1.1n 15 Mar 2022`
And regarding those two keys - the problem is, I'm not that familiar with OpenPGP card specification, so I referred to the official [doc](https://docs.nitrokey.com/storage/linux/smime.html#import-existing-key-and-certificate)
It states I have to add those keys to the two (out of three) slots. So I added them exactly as it says, but only adding `--ignore-ca-certificates` as my PKCS#12 package has full chain with CA and intermediate certs. Resulting in:
`pkcs15-init --delete-objects privkey,pubkey --id 3 --store-private-key package.pfx --format pkcs12 --auth-id 3 --verify-pin --ignore-ca-certificates`
`pkcs15-init --delete-objects privkey,pubkey --id 2 --store-private-key package.pfx --format pkcs12 --auth-id 3 --verify-pin --ignore-ca-certificates`
Is there anyone from nitrokey who contributes to that project and who may want to help us?) Thanks!

**Comment by dengert** [comment]
[OpenSSH 8.9](https://www.openssh.com/txt/release-8.9) released February 23, 2022 So it needs to be looked at too.

I will try and look at: https://github.com/openssh/openssh-portable to see if something might have changed too.

**Comment by Unb0rn** [comment]
Yeah, but it looks like this problem has been there for a long time...

**Comment by dengert** [comment]
How long?
I find it strange that they would use the same key for signatures and encryption.

**Comment by Unb0rn** [comment]
As I've mentioned before, I asked Nitrokey here: https://support.nitrokey.com/t/ssh-with-valid-x509-fails/1761 the same question back in 2019...

**Comment by dengert** [comment]
@alex-nitrokey @niklas-nitrokey Any comments on why this fails?

**Comment by dengert** [comment]
@Unb0rn  I am trying to reproduce your problem using a NitroKey Pro, a certificate from Actalis and a build of OpenSSH from  https://github.com/openssh/openssh-portable
As you point out NitroKey says in: https://docs.nitrokey.com/storage/linux/smime.html "there will be problems." I see the "Failed to store private key: Not supported."

But my NitroKey Pro originally had an RSA key and an ECDSA key from some previous testing. 
It appears the ECDSA public key is still on the card and never replaced.  Can you try running:
 `ssh-keygen -D <path to opensc-pkcs11.so>` 
 and see if it produces 2 keys, and are they the same? 


If I run `./ssh-keygen -D /opt/ossl-1.1.1m/lib/opensc-pkcs11.so > /tmp/smartcard.pub` (using the opensc lib I build for OpenSSL 1.1.1m)
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCruDGZJm3wdCqAlrmkhtOhqGT2fEVgloTplsRhdLWs5Da4B96xI/gkFbcUuIBkBBoN2GvlntaxFAFNG3EdS7L4mw3Gpn5Jz5KQ+EiR6HRWBe4wuvuF4zXJ/CKUCWbcN1nRJ31HlOYsH3aCjcgNt5eZ0Wy7ndacjTQ    dbTe5C6S72U/vOWsjm/AG6Am1W1c6A+QRNbipxmMCcov51Czlyd/9UGpPDzaCZwftJG1CINWqSRiIiSZp2Kw5wSvq16fFtMwm2PGLmkJle83vGIAfXNkPv4pOTj5UDlEp79XylxvQ2Q3c6ZQ/7xmttIc9J4Lb9yVszYjCHESJc10FgmqRPd8l Encryption key
  2 ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBLkJo8BdhGr1DM7KaIR7SMyITaOwP2ftEKcofnkATJC5cgd93r/FlOrt1H/n/dQCxEXB5TrXERy4I1nPrGJzoaCWqOy+euBMmR0qk7ua5b+qBMv7AFTUvwbgzmZm4pA    OOg== Signature key
```

**Comment by mouse07410** [comment]
I don't know either NitroKey or the latest release of OpenSSH. But as far as I know, SSH works with certs in a PIV applet? If so, is there any reason why you installed your authentication key and cert into slot 3 instead of slot 1?

**Comment by Unb0rn** [comment]
@dengert For me it only produces the publey for "Encryption key" slot...
`ssh-keygen -D /usr/lib/opensc-pkcs11.so`                                                                                                                 

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQ7GTMwi60a3UKbJ6DRaXu3RwZzATtjSV9SZOCg7CmF5t0Pr92vhOrsZ7FPwLp+KFaq5wOQP/XVwBEX2nEwbCZoafP+bVxdfEzVRdjsLdo/N6dtqB25Z/DAmhST9P1opCJHzvcf1UIHPr3p0R8V5a87vtJzpYQnvFk0Ujr/UoeggKDxjv3j1H8ms7hezMXZJa4+ka7GIDzDiHqzhkOu8omIabxYOGV7k8GFRb+E2pJugEcyPhbEEDLGKbMOgWcxV8kpzzPcsr23/0wAqV2HejKWpg8BmNMB9CR0BLtMuagU3DCmjD6swGR5zYFpSgSdsIXe5BGhaUQKWAR3ZOZkYq7 Encryption key

@mouse07410 As I said I'm not that familiar with OpenPGP standard. It looks like Slot 1 is for Signing, Slot 2 for Encryption and Slot 3 for Authentication. I also referred to Nitrokey's [doc](https://www.nitrokey.com/documentation/applications#p:nitrokey-storage&os:linux) which states that the keys should be loaded in slots 2 and 3 (sections with s/mime, hard disk encryption and vpn) so it looks like slot 3 is indeed should be used for authentication operations... But I'm not sure anymore)

**Comment by mouse07410** [comment]
@Unb0rn are you sure your SSH expects the token to follow OpenPGP standard, rather than PIV standard? 

If it does follow OpenPGP - them wouldn't it need an encryption key/cert (OpenPGP slot 2) for the actual session key establishment?

**Comment by techge** [comment]
I am not working for NK anymore (hence not responding as @alex-nitrokey ), but I might be able to add some notes. I can not solve or investigate this issue furhter though.

As OpenPGP Cards (which are used in NK Storage 2 and many other models) only allow specific operations for specific key slots, it is necessary to put a S/MIME key on slot 2 and 3 for being able to use it for decrypting (slot 2) and signing (slot 3) mails (which most people will do with S/MIME keys). In the OpenPGP realm you would use subkeys for this task, it makes more sense there.

So putting one single keys to both slots is a workaround to get S/MIME keys working. As far as I can see, this is what @Unb0rn already got from the docu, so it might not be of much value, I just wanted to clarify a bit.

Honestly, I do not know, if/how I got OpenSC working with OpenSSH on an NK, I mostly preferred gnupg for this task. On hardware side this is definitely possible, but can only work when using slot 3. So it *is possible* that the pgp driver of OpenSC just is not using the correct key slot for this operation. But then again, I did not look at the code, and I'll probably won't have time to do so. I hope I could at least help a bit.

**Comment by dengert** [comment]
I think I now have my Nitro Pro with 2 keys (both the same value) and one certificate to match  @Unb0rn 's token. 
```
openpgp-tool -E`  /* was used to reset the card, delete all the keys and objects and reset the pins to 123456 and 12345678. */

/* the following shows there a re now no keys */
openpgp-tool -v -K
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
Connecting to card in reader Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00...
Using card driver OpenPGP card.
Aut Algorithm:   RSA2048
Aut Create Date: 1970-01-01 00:00:00
Aut Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Dec Algorithm:   RSA2048
Dec Create Date: 1970-01-01 00:00:00
Dec Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Sig Algorithm:   RSA2048
Sig Create Date: 1970-01-01 00:00:00
Sig Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
```

I then loaded a Actalis free certificate and key using the Nitro docs like @Unb0rn did in initial post.
```
/pkcs15-init --id 3 --store-private-key ~/t/PKCS12_Credential_deengert@gmail.com.pfx --format pkcs12 --auth-id 3 --verify-pin
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
User PIN required.
Please enter User PIN [Admin PIN]: 
error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
Please enter passphrase to unlock secret key:     /* this is the pkcs12 password Actalis sent by e-mail */
Importing 3 certificates:
  0: /CN=deengert@gmail.com
  1: /C=IT/L=Milan/O=Actalis S.p.A./03358520967/CN=Actalis Authentication Root CA
  2: /C=IT/ST=Bergamo/L=Ponte San Pietro/O=Actalis S.p.A./CN=Actalis Client Authentication CA G3
Security officer PIN [Admin PIN] required.
Please enter Security officer PIN [Admin PIN]: 
Failed to store private key: Not supported

/* as noted in NitroKey docs, there will be error messages, but the "Aut" key is updated as shown below */

openpgp-tool -v -K
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
Connecting to card in reader Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00...
Using card driver OpenPGP card.
Aut Algorithm:   RSA2048
Aut Create Date: 2022-03-27 12:06:57
Aut Fingerprint: 8f:63:8c:85:da:60:06:55:a6:fa:46:70:73:08:64:2f:b9:10:37:fc
Dec Algorithm:   RSA2048
Dec Create Date: 1970-01-01 00:00:00
Dec Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Sig Algorithm:   RSA2048
Sig Create Date: 1970-01-01 00:00:00
Sig Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00

/* now load it again as --id 2 as per the docs: */
./pkcs15-init --id 2 --store-private-key ~/t/PKCS12_Credential_deengert@gmail.com.pfx --format pkcs12 --auth-id 3 --verify-pin
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
User PIN required.
Please enter User PIN [Admin PIN]: 
error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
Please enter passphrase to unlock secret key: 
Importing 3 certificates:
  0: /CN=deengert@gmail.com
  1: /C=IT/L=Milan/O=Actalis S.p.A./03358520967/CN=Actalis Authentication Root CA
  2: /C=IT/ST=Bergamo/L=Ponte San Pietro/O=Actalis S.p.A./CN=Actalis Client Authentication CA G3
Failed to store private key: Not supported

/* The following shows the "Dec" key was loaded: */
doug@XUbuntu-20:/opt/ossl-1.1.1m/bin$ openpgp-tool -v -K
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
Connecting to card in reader Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00...
Using card driver OpenPGP card.
Aut Algorithm:   RSA2048
Aut Create Date: 2022-03-27 12:06:57
Aut Fingerprint: 8f:63:8c:85:da:60:06:55:a6:fa:46:70:73:08:64:2f:b9:10:37:fc
Dec Algorithm:   RSA2048
Dec Create Date: 2022-03-27 12:09:42
Dec Fingerprint: 02:3f:1a:87:0e:35:e7:21:0d:e9:20:c8:71:01:7c:7d:d0:b4:35:60
Sig Algorithm:   RSA2048
Sig Create Date: 1970-01-01 00:00:00
Sig Fingerprint: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
```

Then to see ehat OpenSC pkcs15 thisnks is in the card:
(Note the usage bits for each key) 
```
doug@XUbuntu-20:/opt/ossl-1.1.1m/bin$ ./pkcs15-tool -v --dump 
Using reader with a card: Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00
Connecting to card in reader Nitrokey Nitrokey Pro (0000000000000000000080B8) 00 00...
Using card driver OpenPGP card.
Trying to find a PKCS#15 compatible card...
Found OpenPGP card!
PKCS#15 Card [OpenPGP card]:
	Version        : 0
	Serial number  : 0005000080b8
	Manufacturer ID: ZeitControl
	Language       : de
	Flags          : PRN generation, EID compliant


Card has 3 Authentication object(s).

PIN [User PIN]
	Object Flags   : [0x03], private, modifiable
	Auth ID        : 03
	ID             : 02
	Flags          : [0x13], case-sensitive, local, initialized
	Length         : min_len:6, max_len:64, stored_len:64
	Pad char       : 0x00
	Reference      : 2 (0x02)
	Type           : UTF-8
	Path           : 3f00
	Tries left     : 3

PIN [User PIN (sig)]
	Object Flags   : [0x03], private, modifiable
	Auth ID        : 03
	ID             : 01
	Flags          : [0x13], case-sensitive, local, initialized
	Length         : min_len:6, max_len:64, stored_len:64
	Pad char       : 0x00
	Reference      : 1 (0x01)
	Type           : UTF-8
	Path           : 3f00
	Tries left     : 3

PIN [Admin PIN]
	Object Flags   : [0x03], private, modifiable
	ID             : 03
	Flags          : [0x9B], case-sensitive, local, unblock-disabled, initialized, soPin
	Length         : min_len:8, max_len:64, stored_len:64
	Pad char       : 0x00
	Reference      : 3 (0x03)
	Type           : UTF-8
	Path           : 3f00
	Tries left     : 3

Card has 2 Private key(s).

Private RSA Key [Encryption key]
	Object Flags   : [0x03], private, modifiable
	Usage          : [0x22], decrypt, unwrap
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	Algo_refs      : 0
	ModLength      : 2048
	Key ref        : 1 (0x01)
	Native         : yes
	Auth ID        : 02
	ID             : 02
	MD:guid        : d85c0417-97a1-1d74-c593-0305f9ec101a

Private RSA Key [Authentication key]
	Object Flags   : [0x03], private, modifiable
	Usage          : [0x222], decrypt, unwrap, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	Algo_refs      : 0
	ModLength      : 2048
	Key ref        : 2 (0x02)
	Native         : yes
	Auth ID        : 02
	ID             : 03
	MD:guid        : 0afc7d32-41d6-5d4c-15e8-f76cb7bd75cc

Card has 2 Public key(s).

Public RSA Key [Encryption key]
	Object Flags   : [0x02], modifiable
	Usage          : [0x11], encrypt, wrap
	Access Flags   : [0x02], extract
	ModLength      : 2048
	Key ref        : 0 (0x00)
	Native         : no
	Path           : b801
	ID             : 02

Public RSA Key [Authentication key]
	Object Flags   : [0x02], modifiable
	Usage          : [0x51], encrypt, wrap, verify
	Access Flags   : [0x02], extract
	ModLength      : 2048
	Key ref        : 0 (0x00)
	Native         : no
	Path           : a401
	ID             : 03

Card has 0 Secret key(s).

Card has 1 Certificate(s).

X.509 Certificate [Cardholder certificate]
	Object Flags   : [0x00]
	Authority      : no
	Path           : 3f007f21
	ID             : 03
	Encoded serial : 02 10 72F41337FE74C7E1783B6B48B5BB5AB5

Card has 0 Data object(s).
```

And what  OpenSC pkcs11-tool see on the card:
```
./pkcs11-tool -O --login
Using slot 0 with a present token (0x0)
Logging in to "OpenPGP card (User PIN)".
Please enter User PIN: 
Private Key Object; RSA 
  label:      Encryption key
  ID:         02
  Usage:      decrypt, unwrap
  Access:     sensitive, always sensitive, never extractable, local
Public Key Object; RSA 2048 bits
  label:      Encryption key
  ID:         02
  Usage:      encrypt, wrap
  Access:     none
Private Key Object; RSA 
  label:      Authentication key
  ID:         03
  Usage:      decrypt, sign, non-repudiation, unwrap
  Access:     sensitive, always sensitive, never extractable, local
Public Key Object; RSA 2048 bits
  label:      Authentication key
  ID:         03
  Usage:      encrypt, verify, wrap
  Access:     none
Certificate Object; type = X.509 cert
  label:      Cardholder certificate
  subject:    DN: CN=deengert@gmail.com
  ID:         03
Profile object 2641747360
  profile_id:          CKP_PUBLIC_CERTIFICATES_TOKEN (4)
```

Only Private key ID: 03 has " sign" which is CKA_SIGN and no key in ID: 01

**Comment by dengert** [comment]
@mouse07410 The NitroKey devices AFAIK do not support PIV.  @Unb0rn is using the OpenSSH PKCS11 support and I think that is where the problem is.

**Comment by dengert** [comment]
@techge  Thanks for the update on you status. Do you know if anyone at NitroKey follows OpenSC?

**Comment by dengert** [comment]
SSH is assuming that there are no duplicate keys by comparing the values of the keys at:
 https://github.com/openssh/openssh-portable/blob/master/ssh-pkcs11.c#L1289-L1292
which calls:
https://github.com/openssh/openssh-portable/blob/master/ssh-pkcs11.c#L688-L696

PKCS11 can allow duplicate keys, but  PKCS11 expects (but does not require) related pubkey, privkey  and certificate to each have the same CKA_ID, which is different from the CKA_ID of any other set of pubkey, privkey  and certificates.  OpenSSH reads the CKA_ID, but I don't see where they use it.  

OpenSSH is based on having unique keys, I doubt they would change it. 

The Actalis key has been loaded twice as the Nitro docs show for use of web browser, e-mail, etc.  Using the same key to encrypt and to sign does not sound like a good idea to me.

@Unb0rn I would suggest that if you goal is to use the token for login, then only load it once as 03 or in the 01 "slot" or add/generate a key in the 01 slot, which I thing will be found first and used by OpenSSH. You may have to use `openpgp-tool -E` and start over. 

It might be possible to reorder the way OpenSC presents the keys to PKCS11, so it would find the 03 before the 02.

I would say this is not an OpenSC issue.

**Comment by dengert** [comment]
As a follow up, Erasing the NitroPro, and installing the Actalis cert as id 03 with no other keys works:
```
 openpgp-tool -E
 openpgp-tool -v -K
 ./pkcs15-init --id 3 --store-private-key ~/t/PKCS12_Credential_deengert@gmail.com.pfx --format pkcs12 --auth-id 3 --verify-pin
 openpgp-tool -v -K
 ./ssh-keygen -D /opt/ossl-1.1.1m/lib/opensc-pkcs11.so > /tmp/xxx01
 ./ssh -v  doug@localhost
```
My ~/ssh/config has:
```
Host localhost 
  PKCS11Provider /opt/ossl-1.1.1m/lib/opensc-pkcs11.so
```

/tmp/xxx01 was added to my ~/.ssh/authorized_keys2 before doing the ./ssh above. 
(Note "Authentication key" is what the OpenSC  pkcs11  returns for an openpgp 03 key) 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCruDGZJm3wdCqAlrmkhtOhqGT2fEVgloTplsRhdLWs5Da4B96xI/gkFbcUuIBkBBoN2GvlntaxFAFNG3EdS7L4mw3Gpn5Jz5KQ+EiR6HRWBe4wuvuF4zXJ/CKUCWbcN1nRJ31HlOYsH3aCjcgNt5eZ0Wy7ndacjTQdbTe5C6S72U/vOWsjm/AG6Am1W1c6A+QRNbipxmMCcov51Czlyd/9UGpPDzaCZwftJG1CINWqSRiIiSZp2Kw5wSvq16fFtMwm2PGLmkJle83vGIAfXNkPv4pOTj5UDlEp79XylxvQ2Q3c6ZQ/7xmttIc9J4Lb9yVszYjCHESJc10FgmqRPd8l Authentication key
```


```

**Comment by frankmorgner** [comment]
Please re-open this topic if there's new input available.

**Comment by marek22k** [comment]
Hi, I have encountered the same problem. Is there a way to use SSH via PKCS#11? (when using multiple key slots) Nitrokey 3
