### ISSUE TITLE
non-RSA algos for MacOS version

### ISSUE THREAD

**Issue by cwoschek** [OpenSC/OpenSC#2533]
### Problem Description
I would like to use opensc under MacOS to support Yubico based SSH. I am not using RSA keys.
The non-rsa keys I am using under linux with yubikey in PIV mode for key based SSH are not supported in MacOX. 
Using MacOS 11.6.2 Big Sur

### Proposed Resolution
A config switch or something else to enable it or a compile switch whould solve it when not supported because not tested under macos.

### Steps to reproduce
Use ECCP algorithm for keys

### Logs
(base) MacBook-Air:~ me$ /Library/OpenSC/bin/pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "Yubico PIV Authentication".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key)  -- non-RSA, skipping
  testing key 1 (SIGN key)  -- non-RSA, skipping
  testing key 2 (KEY MAN key)  -- non-RSA, skipping
  testing key 3 (CARD AUTH key)  -- non-RSA, skipping
Signatures: no private key found in this slot
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key) -- non-RSA, skipping
  testing key 1 (SIGN key) with 1 mechanism -- non-RSA, skipping
  testing key 2 (KEY MAN key) with 1 mechanism -- non-RSA, skipping
  testing key 3 (CARD AUTH key) with 1 mechanism -- non-RSA, skipping
Decryption (currently only for RSA)
  testing key 0 (PIV AUTH key) -- non-RSA, skipping
  testing key 1 (SIGN key) -- non-RSA, skipping
  testing key 2 (KEY MAN key) -- non-RSA, skipping
  testing key 3 (CARD AUTH key) -- non-RSA, skipping
No errors

**Comment by frankmorgner** [comment]
ECC should be supported for PIV. It's just not tested in pkcs11-tool. Try to use SSH the way you're expecting it to work and log and report a problem if needed.

**Comment by dengert** [comment]
@mouse07410  any comments on MacOS, ECDSA, OpenSSH, Yubikey?

pkcs11-tool can do a sign  using a specific key. Try this simple test script [test.pkcs11-tool.sh.txt](https://github.com/OpenSC/OpenSC/files/8540514/test.pkcs11-tool.sh.txt)
 Save without the ".txt"

Run `test.pkcs11-tool.sh -M ECDSA -H SHA256 -ID 01

You also said: "The non-rsa keys I am using under linux with yubikey in PIV mode for key based SSH are not supported in MacOX."  Do you mean SSH does not support ECDSA?

**Comment by mouse07410** [comment]
Sorry for delayed response.

I used Yubikey with ECDSA on MacOS without problems - *by itself*. I.e., OpenSC works, OpenSSL (via libp11) works, etc.

Problems came when I tried to, e.g., sign or encrypt emails using ECC - neither MS Outlook nor Apple Mail did the right thing. They either rejected ECC certs, or treated ECC keys as (small) RSA keys. You can guess the consequences.

I don't recall trying OpenSSH with ECC keys, mainly because for me ECC is dead. I'll move from RSA straight to PQC.But based on my experience, OpenSSH should work with Yubikey keys, RSA or ECC, just fine.

**Comment by frankmorgner** [comment]
ECC has been tested previously via CTK, which is nowadays [supported by SSH](https://support.apple.com/guide/deployment/depc47f60521/1/web/1.0). If needed, https://github.com/frankmorgner/OpenSCToken/pull/40 needs to be applied, but I think this issue should be fixed by today.

**Comment by cwoschek** [comment]
Sorry, have not seen request for aditional data.
PLease find below debug data from ssh when trying to use yubikey for ssh connection. I use the lib /usr/local/lib/opensc-pkcs11.so and in .ssh/config there is an entry for pc1 to use this lib. 
The log shows that keys from the hw-key are not used. I use MacOS 12.6.6.

`Christophs-Air:~ me$ ssh pc1 -vvv
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/me/.ssh/config
debug1: /Users/me/.ssh/config line 44: Applying options for pc1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Connecting to pc1.domain.de port 22.
debug1: Connection established.
debug1: provider /usr/local/lib/opensc-pkcs11.so: manufacturerID <OpenSC Project> cryptokiVersion 2.20 libraryDescription <OpenSC smartcard framework> libraryVersion 0.23
debug1: provider /usr/local/lib/opensc-pkcs11.so slot 0: label <Yubico PIV Authentication> manufacturerID <piv_II> model <PKCS#15 emulate> serial <460a5aac0adc3ed> flags 0x40d
skipping unsupported key type
failed to fetch key
skipping unsupported key type
failed to fetch key
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
unknown certificate key type
failed to fetch key
unknown certificate key type
failed to fetch key
Enter PIN for 'Yubico PIV Authentication': 
skipping unsupported key type
failed to fetch key
skipping unsupported key type
failed to fetch key
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
unknown certificate key type
failed to fetch key
unknown certificate key type
failed to fetch key
debug1: pkcs11_provider_finalize: 0x600003c6c000 refcount 1 valid 1
debug1: pkcs11_provider_unref: 0x600003c6c000 refcount 1
debug1: pkcs11_add_provider: provider /usr/local/lib/opensc-pkcs11.so returned no keys
debug1: identity file /Users/me/.ssh/id_rsa type -1
debug1: identity file /Users/me/.ssh/id_rsa-cert type -1
debug1: identity file /Users/me/.ssh/id_dsa type -1
debug1: identity file /Users/me/.ssh/id_dsa-cert type -1
debug1: identity file /Users/me/.ssh/id_ecdsa type -1
debug1: identity file /Users/me/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/me/.ssh/id_ed25519 type -1
debug1: identity file /Users/me/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/me/.ssh/id_xmss type -1
debug1: identity file /Users/me/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
debug1: match: OpenSSH_8.9p1 Ubuntu-3ubuntu0.1 pat OpenSSH* compat 0x04000000
debug3: fd 5 is O_NONBLOCK
debug1: Authenticating to pc1.domain.de:22 as 'chris'
debug3: hostkeys_foreach: reading file "/Users/me/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /Users/me/.ssh/known_hosts:57
debug3: load_hostkeys: loaded 1 keys from pc1.domain.de
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:UqlAcH2CeU6itffUtiSEPqA6bn0V7u9IdMNPxc4btQw
debug3: hostkeys_foreach: reading file "/Users/me/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /Users/me/.ssh/known_hosts:57
debug3: load_hostkeys: loaded 1 keys from pc1.domain.de
debug3: hostkeys_foreach: reading file "/Users/me/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /Users/me/.ssh/known_hosts:57
debug3: load_hostkeys: loaded 1 keys from 34.75.194.184
debug1: Host 'pc1.domain.de' is known and matches the ECDSA host key.
debug1: Found key in /Users/me/.ssh/known_hosts:57
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /Users/me/.ssh/id_rsa 
debug1: Will attempt key: /Users/me/.ssh/id_dsa 
debug1: Will attempt key: /Users/me/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/me/.ssh/id_ed25519 
debug1: Will attempt key: /Users/me/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com (unrecognised)
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/me/.ssh/id_rsa
debug3: no such identity: /Users/me/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /Users/me/.ssh/id_dsa
debug3: no such identity: /Users/me/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /Users/me/.ssh/id_ecdsa
debug3: no such identity: /Users/me/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /Users/me/.ssh/id_ed25519
debug3: no such identity: /Users/me/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /Users/me/.ssh/id_xmss
debug3: no such identity: /Users/me/.ssh/id_xmss: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
chris@pc2.domain.de: Permission denied (publickey).
Christophs-Air:~ me$ 
`
