### ISSUE TITLE
unable to load private key on the smart card

### ISSUE THREAD

**Issue by samini3000** [OpenSC/OpenSC#2535]
### Problem Description
I have used bixVirtualReader with OpenSC-isoApplet
but I am unable to load private key on the smart card
### Proposed Resolution
I have tried 
1)
I tried this instruction after creating my 2048/rsa key generating
pkcs15-init --store-private-key key.pem --auth-id 01 --pin 1234
but it returns following error
Failed to store private key: Not allowed
I run this command which says does not have any certificate
pkcs15-tool -c
Using reader with a card: Bix VIRTUAL_CARD_READER 0
and also this command which says does not have any key
pkcs15-tool -k
Using reader with a card: Bix VIRTUAL_CARD_READER 0
2)
I also tried with these commands
pkcs15-init --create-pkcs15
pkcs15-init --store-certificate publickey.pem --label myKey --auth-id FF --id 01 --format pem --pin 1234
pkcs15-init --generate-key "rsa/2048" --auth-id "FF" --label "myKey" --id "1"
it works but when I run certutil -scinfo it gives the
No cert retrieved for reader: Bix VIRTUAL_CARD_READER 0

please guide me to find the solution how to add valid certificate to my virtual smart card
any help appreciated

**Comment by llogar** [comment]
For the first part of your question, have you enabled the key import in your isoApplet (`DEF_PRIVATE_KEY_IMPORT_ALLOWED = true`)?

**Comment by samini3000** [comment]
Many Thanks Luca the "unable to write private key problem" is solved
I am using these commands to make certificate
openssl genrsa -out key.pem 2048 : create 2048 rsa peivate key
openssl req -new -sha256 -key key.pem -out csr.csr : Generate a Certificate Signing Request:
openssl req -x509 -sha256 -days 365 -key key.pem -in csr.csr -out certificate.pem : Generate a self-signed x509 certificate
openssl. pkcs12 -export -out client-identity.p12 -inkey key.pem -in certificate.pem
openssl pkcs12 -in client-identity.p12 -nocerts -out privatekey.pem :create private key
openssl pkcs12 -in client-identity.p12 -clcerts -nokeys -out publickey.pem : create public key
and then I load the certificate.pem as certificate
and privatekey.pem as private key
but my certutil result says
The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
0: Bix VIRTUAL_CARD_READER 0
--- Reader: Bix VIRTUAL_CARD_READER 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
--- Card: Contactless Smart Card
--- ATR:
3b 80 80 01 01 ;....
=======================================================
Analyzing card in reader: Bix VIRTUAL_CARD_READER 0
--------------===========================--------------
================ Certificate 0 ================
--- Reader: Bix VIRTUAL_CARD_READER 0
--- Card: Contactless Smart Card
Provider = OpenSC CSP
Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
Cannot open the AT_SIGNATURE key for reader: Bix VIRTUAL_CARD_READER 0
Cannot open the AT_KEYEXCHANGE key for reader: Bix VIRTUAL_CARD_READER 0
--------------===========================--------------
================ Certificate 0 ================
--- Reader: Bix VIRTUAL_CARD_READER 0
--- Card: Contactless Smart Card
Provider = Microsoft Smart Card Key Storage Provider
Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
Cannot open the key for reader: Bix VIRTUAL_CARD_READER 0
--------------===========================--------------
Done.
CertUtil: -SCInfo command completed successfully.
Also this command pkcs15-init -F returns Failed to finalizing card: Not supported
I dont know if there is a problem here or not
Thanks for your guide

**Comment by dengert** [comment]
The output of the certutil shows a problem that is unrelated to your problem. https://github.com/OpenSC/OpenSC/pull/2523 is a fix primarily for ECC, but the trace shows it is also a problem for RSA. 

Certutil will try and use both the original smart card code named"CSP" that only supported RSA and then again using the newer "KSP" The also supports RSA and ECC and other features. 

Certutil tries to use CSP using "Provider = OpenSC CSP"  which it found in the registry. 
and then certutil will try "Provider = Microsoft Smart Card Key Storage Provider" and fails.

OpenSC installs its drivers which should have in registry: "Provider = Microsoft Base Smart Card Crypto Provider"  and also has "Smart Card Key Storage Provider = Microsoft Smart Card Key"

It appears that for drivers that that can support both CSP and KSP, the registry must have both 
Provider = Microsoft Base Smart Card Crypto Provider" and "Smart Card Key Storage Provider = Microsoft Smart Card Key"

**Comment by samini3000** [comment]
Thanks Doug,
I tested your solution and  change the registery value to this :
<img width="956" alt="image" src="https://user-images.githubusercontent.com/35727427/162560196-ecd01559-871f-4b15-90a9-3d1e6f38faf3.png">

but the output after running these commands still has this output:

     pkcs15-init --store-certificate certificate.pem --label testuser --auth-id 01 --id 01 --format pem --pin 1234
     Using reader with a card: Bix VIRTUAL_CARD_READER 0
     pkcs15-init --store-private-key privatekey.pem --label testuser --auth-id 01 --id 01 --pin 1234
     Using reader with a card: Bix VIRTUAL_CARD_READER 0
output of certutil -csinfo:

      certutil -scinfo
      The Microsoft Smart Card Resource Manager is running.
      Current reader/card status:
      Readers: 1
      0: Bix VIRTUAL_CARD_READER 0
      --- Reader: Bix VIRTUAL_CARD_READER 0
      --- Status: SCARD_STATE_PRESENT
      --- Status: The card is available for use.
      --- Card: Contactless Smart Card
      --- ATR:
      3b 80 80 01 01 ;....
      =======================================================
      Analyzing card in reader: Bix VIRTUAL_CARD_READER 0
      --------------===========================--------------
      ================ Certificate 0 ================
      --- Reader: Bix VIRTUAL_CARD_READER 0
      --- Card: Contactless Smart Card
      Provider = Microsoft Base Smart Card Crypto Provider
      Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
      Cannot open the AT_SIGNATURE key for reader: Bix VIRTUAL_CARD_READER 0
      Cannot open the AT_KEYEXCHANGE key for reader: Bix VIRTUAL_CARD_READER 0
      --------------===========================--------------
      ================ Certificate 0 ================
      --- Reader: Bix VIRTUAL_CARD_READER 0
      --- Card: Contactless Smart Card
      Provider = Microsoft Smart Card Key Storage Provider
      Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
      Cannot open the key for reader: Bix VIRTUAL_CARD_READER 0
      --------------===========================--------------
      Done.
      CertUtil: -SCInfo command completed successfully.
Could you tell me where is my fault?

**Comment by dengert** [comment]
A few thing to try:
Go to Control panel>Internet Options>Content>Certificates>Personal and look at any entry that points at previous attempts to install the certificate in question. If you click on it, then View then  "Details" look at "Valid from" and "Valid to".   

The delete the certificate from the cache.

(Windows may have cached an old version with different key in certificate that does not match the current key in the OpenSC-isoApplet.) 

Then restart windows, look at  Control panel>Internet Options>Content>Certificates>Personal  again.  Certificate should  not be present.

Run `certutil -v scinfo` again.

And look at Control panel>Internet Options>Content>Certificates>Personal  one more time and check for certificate and the times. 

If above did not fix the problem, then try:

Run `pkcs11-tool -O --login` and `pkcs11-tool --test --login`

**Comment by samini3000** [comment]
I  kept only last certificate and the problem still exists.
result of this command  (certutil -v scinfo) is:

    The Microsoft Smart Card Resource Manager is running.
    Current reader/card status:
    Readers: 1

     0: Bix VIRTUAL_CARD_READER 0
    --- Reader: Bix VIRTUAL_CARD_READER 0
    --- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
    --- Status: The card is available for use.
    ---   Card: Contactless Smart Card
    ---    ATR:
            3b 80 80 01 01                                     ;....
     =======================================================
    Analyzing card in reader: Bix VIRTUAL_CARD_READER 0
    --------------===========================--------------
     ================ Certificate 0 ================
     --- Reader: Bix VIRTUAL_CARD_READER 0
     ---   Card: Contactless Smart Card
     Provider = OpenSC CSP
      Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3

     Cannot open the AT_SIGNATURE key for reader: Bix VIRTUAL_CARD_READER 0
     Cannot open the AT_KEYEXCHANGE key for reader: Bix VIRTUAL_CARD_READER 0
     --------------===========================--------------
     ================ Certificate 0 ================
    --- Reader: Bix VIRTUAL_CARD_READER 0
    ---   Card: Contactless Smart Card
    Provider = Microsoft Smart Card Key Storage Provider
    Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
      Cannot open the  key for reader: Bix VIRTUAL_CARD_READER 0

    --------------===========================--------------

     Done.
     CertUtil: -SCInfo command completed successfully.
and  result of  pkcs11-tool -O --login is:

    Using slot 0 with a present token (0x0)
    Logging in to "testuser (User PIN)".
    Please enter User PIN: Public Key Object; RSA 2048 bits
    label:      testuser
     ID:         01
       Usage:      verify
       Access:     none
     Certificate Object; type = X.509 cert
       label:      testuser
       subject:    DN: C=TS, ST=Test, L=Test, O=ID, OU=IT, CN=saeede/emailAddress=sa@sa.c
       ID:         01
     Profile object 958244512
      profile_id:          '4'
result of pkcs11-tool --test --login is:

    Using slot 0 with a present token (0x0)
    Logging in to "testuser (User PIN)".
    Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
      seeding (C_SeedRandom) not supported
       seems to be OK
    Digests:
       all 4 digest functions seem to work
       MD5: OK
       SHA-1: OK
       RIPEMD160: OK
     Signatures (currently only for RSA)
     Signatures: no private key found in this slot
     Verify (currently only for RSA)
       No private key found for testing
     Decryption (currently only for RSA)
     No errors
Thanks in advance  for your guide. @llogar

**Comment by dengert** [comment]
What do you mean: "I kept only last certificate and the problem still exists."
The card must have the certificate and at least the private key. 

The certutil and pkcs11-tool  shows  there are no keys on the token.

In an earlier run of `pkcs15-tool -D` it showed there were keys on the token. 


If you can start over by clearing out any certificate for the Microsoft cache i.e. the  Control panel>Internet Options>Content>Certificates>Personal  instructions above. 

then try and log various steps during the process. Get OpenSC debug logs (debug = 7;) of the various commands. See https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC. (Debug level 7)


Note: you can not do both: 
```
pkcs15-init --store-certificate publickey.pem --label myKey --auth-id FF --id 01 --format pem --pin 1234
pkcs15-init --generate-key "rsa/2048" --auth-id "FF" --label "myKey" --id "1"
```
the pkcs15-init --generate-key creates a new key on the token, which will not match the key in the certificate. 

These should work:
```
openssl genrsa -out key.pem 2048 : create 2048 rsa peivate key
openssl req -new -sha256 -key key.pem -out csr.csr : Generate a Certificate Signing Request:
openssl req -x509 -sha256 -days 365 -key key.pem -in csr.csr -out certificate.pem : Generate a self-signed x509 certificate
openssl. pkcs12 -export -out client-identity.p12 -inkey key.pem -in certificate.pem
openssl pkcs12 -in client-identity.p12 -nocerts -out privatekey.pem :create private key
openssl pkcs12 -in client-identity.p12 -clcerts -nokeys -out publickey.pem : create public key
```
And log the steps to load the private key, public key and certificate. 

Log   `pkcs15-tool -D`

Log `pkcs11-tool --test --login`

don't even try the minidriver  until the pkcs11-tool works.

**Comment by samini3000** [comment]
I removed all of my built certificate, and set debug = 7
I ran these commands

     pkcs15-init --create-pkcs15 --use-default-transport-keys --label testuser --auth-id 01 --id 01 --so-pin 1234 --pin 1234 --puk 1234567887654321 --so-puk 1234567887654321
     pkcs15-init --store-certificate certificate.pem --label testuser --auth-id 01 --id 01 --format pem --pin 1234 
     pkcs15-init --store-private-key privatekey.pem --label testuser --auth-id 01 --id 01 --pin 1234 
result of pkcs15-tool -D

    Using slot 0 with a present token (0x0)
    Logging in to "testuser (User PIN)".
    Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
     seeding (C_SeedRandom) not supported
     seems to be OK
    Digests:
      all 4 digest functions seem to work
      MD5: OK
      SHA-1: OK
      RIPEMD160: OK
    Signatures (currently only for RSA)
    Signatures: no private key found in this slot
    Verify (currently only for RSA)
     No private key found for testing
    Decryption (currently only for RSA)
    No errors
result of pkcs11-tool --test --login

    PKCS#15 Card [testuser]:
            Version        : 0
            Serial number  : 0000
            Manufacturer ID: unknown
            Last update    : 20220411050427Z
            Flags          : EID compliant


    PIN [User PIN]
            Object Flags   : [0x03], private, modifiable
            ID             : ff
            Flags          : [0x31], case-sensitive, initialized, needs-padding
            Length         : min_len:4, max_len:16, stored_len:16
            Pad char       : 0x00
            Reference      : 1 (0x01)
            Type           : ascii-numeric

    Private RSA Key [testuser]
            Object Flags   : [0x03], private, modifiable
            Usage          : [0x04], sign
            Access Flags   : [0x01], sensitive
            Algo_refs      : 0
            ModLength      : 2048
            Key ref        : 0 (0x00)
            Native         : yes
            Path           : 3f005015
            Auth ID        : 01
            ID             : 01
            MD:guid        : 9508e905-48b0-440a-4a61-e5743b76c1e3

    Public RSA Key [testuser]
            Object Flags   : [0x02], modifiable
            Usage          : [0x40], verify
            Access Flags   : [0x00]
            ModLength      : 2048
            Key ref        : 0 (0x00)
            Native         : no
            Path           : 3f0050153300
            ID             : 01

    X.509 Certificate [testuser]
            Object Flags   : [0x02], modifiable
            Authority      : no
            Path           : 3f0050153400
            ID             : 01
            Encoded serial : 02 14 5A42CEDA2DCB5444FA491258F6830AC884A2F42B
result of certutil -scinfo

    The Microsoft Smart Card Resource Manager is running.
    Current reader/card status:
    Readers: 1
      0: Bix VIRTUAL_CARD_READER 0
    --- Reader: Bix VIRTUAL_CARD_READER 0
    --- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
    --- Status: The card is available for use.
    ---   Card: Contactless Smart Card
    ---    ATR:
            3b 80 80 01 01                                     ;....
    =======================================================
    Analyzing card in reader: Bix VIRTUAL_CARD_READER 0
    --------------===========================--------------
    ================ Certificate 0 ================
    --- Reader: Bix VIRTUAL_CARD_READER 0
    ---   Card: Contactless Smart Card
    Provider = OpenSC CSP
    Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
    Cannot open the AT_SIGNATURE key for reader: Bix VIRTUAL_CARD_READER 0
    Cannot open the AT_KEYEXCHANGE key for reader: Bix VIRTUAL_CARD_READER 0
    --------------===========================--------------
    ================ Certificate 0 ================
    --- Reader: Bix VIRTUAL_CARD_READER 0
    ---   Card: Contactless Smart Card
    Provider = Microsoft Smart Card Key Storage Provider
    Key Container = 9508e905-48b0-440a-4a61-e5743b76c1e3
    Cannot open the  key for reader: Bix VIRTUAL_CARD_READER 0
    --------------===========================--------------
    Done.
    CertUtil: -SCInfo command completed successfully.
Thanks for guide, I am still can't load certificate successfully. @dengert

**Comment by samini3000** [comment]
I loaded the certificate with this command and the problem solved.

     certutil -csp "OpenSC CSP" -importpfx client-identity.p12

**Comment by dengert** [comment]
We would still like to know what is going on, as it looks these did not work:
```
pkcs15-init --store-certificate certificate.pem --label testuser --auth-id 01 --id 01 --format pem --pin 1234 
pkcs15-init --store-private-key privatekey.pem --label testuser --auth-id 01 --id 01 --pin 1234 
```
but an alterative method to load the certificate and key did work:
```
certutil -csp "OpenSC CSP" -importpfx client-identity.p12
certutil -csp "Microsoft Smart Card Key Storage Provider" -importpfx client-identity.p12
```
What is output of `pkcs11-tool --test --login` 
If it now works, i.e. finds the private key, and uses  you should see some likes like:
```
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
```
If you are willing to help to find problem with using `pkcs15-init` can you send the OpenSC logs for the two  `pkcs15-init` commands?

**Comment by samini3000** [comment]
this the output
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/35727427/162733000-4999095c-892e-4227-b305-ef8a060196c5.png)

**Comment by dengert** [comment]
That looks good. So initial problem appears to be in the  pkcs15-init or pkcs12 files.

I don't use pkcs15-init or pkcs12 files very much, but man mages for pkcs15-init says:

"Downloading PKCS #12 bags

Most browsers nowadays use PKCS #12 format files when you ask them to export your key and certificate to a file. pkcs15-init is capable of parsing these files, and storing their contents on the card in a single operation. This works just like storing a private key, except that you need to specify the file format:
pkcs15-init --store-private-key okir.p12 --format pkcs12 --auth-id 01

This will install the private key contained in the file okir.p12, and protect it with the PIN referenced by authentication ID 01. It will also store any X.509 certificates contained in the file, which is usually the user certificate that goes with the key, as well as the CA certificate."

So it is not clear why you had to use these:
```
openssl pkcs12 -in client-identity.p12 -nocerts -out privatekey.pem :create private key
openssl pkcs12 -in client-identity.p12 -clcerts -nokeys -out publickey.pem : create public key
```
