### ISSUE TITLE
card unlocked without pin request after smartard reader/card was reconnected/reinserted (windows)

### ISSUE THREAD

**Issue by jarabizna** [OpenSC/OpenSC#2536]
### Problem Description

On windows OS:
I use external usb smartcard reader and firefofx (regulary updated) for PKI authentication to access cutomer'S internal systems.
I have installed oonepin-opensc-pkcs11.dll security module in firefox . Firefox itself use os client cert module to use windows opensc minidriver.

I noticed second time that whne I access customer's portal firefox (or windows minidriver) did not asked for card pin but opensc unlocked the card after I reconnected smartcard reader and newly inserted the card.

What I remember what happened in relation to smartcard from time card was inserted last time:
- smartcard was removed from reader after couple of hours when it was last used (redar was still connected)
- smartcard reader was disconnected
- windows went to sleep/resume/sleep several times
- smardcard reader was connected
- smartcard was inserted into reader
- customer's web portal page was reloaded. at first it failed, to connect - I guess ssl error, another refresh succeed, card unlocked without pin request

It seems that card pin remains somewhere in memory and card removal is not handled correctly. May be there is some issue with firefox (conflict between pkcs11 module and minidriver) sometime FF asked for PIn multiple times for one request, native FF message window (pkcs11 module) as well as by windows widow (minidriver).

### Proposed Resolution
check card removal PIN cache reset after card removal

### Steps to reproduce
irregular appearance of the issue

**Comment by dengert** [comment]
From your description it looks like firefox was never restarted.

There are a number of possible issues. 
FireFox introduced os Client on windows to use MS code that uses minidrivers.
See #2446 and #2459

It is not clear if PIN caching is done by Firefox and/or Windows. But by default OpenSC caches PINs which can be turned off in opensc.conf. (Personally I turn if off) opensc.conf can be found in `C:\Program Files\OpenSC Project\OpenSC` and `C:\Program Files (x86)\OpenSC Project\OpenSC`. Add a line like `use_pin_caching = false;` 

```
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
	framework pkcs15 {
                use_pin_caching = false;
		# use_file_caching = true;
	}
```
Also see:
https://github.com/OpenSC/OpenSC/wiki
http://htmlpreview.github.io/?https://github.com/OpenSC/OpenSC/blob/master/doc/files/files.html

https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in has examples of many of the opensc.conf options. the man pages for opensc.conf can be found on unix systems or google for "man opensc.conf"

**Comment by Jakuje** [comment]
> customer's web portal page was reloaded. at first it failed, to connect - I guess ssl error, another refresh succeed, card unlocked without pin request

Note, that the TLS 1.3 supports session resumption, which means that the server sends to the client some chunk of data, which can be used to resume the previous session.

To be sure, you would have to provide some more information of what the portal is using or ideally reproduce it with something simpler as `gnutls-serv` to create local testing HTTPS server and dump more information about the TLS connection. Or get some info about the TLS session from firefox, but I am not sure where it would be).
