### ISSUE TITLE
Add support for Croatian eID

### ISSUE THREAD

**Issue by dCubelic** [OpenSC/OpenSC#2537]
### Problem Description

How could I start with adding support for Croatian eID document?

Croatian government has released middleware for activating the ID and using the signing capabilities, but it is not open source. [eID Middleware](https://www.eid.hr/en/electronic-id/articles/activation-of-eoi)

On Mac I can see it is using `libEidPkcs11.dylib`, which i guess is installed together with the middleware.

I am actually only interested in using the document signing capabilities. And I can achieve that using [Europe's web demo app for document signing](https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/home) which is open source. It uses [nexu](https://github.com/nowina-solutions/nexu), which is also open source. But I do not understand how the communication is performed and how I can do it manually.

[This](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjqy8SosYL3AhXpiP0HHdWyApYQFnoECAoQAQ&url=https%3A%2F%2Fec.europa.eu%2Fdigital-building-blocks%2Fwikis%2Fdownload%2Fattachments%2F62885743%2FG1.v4.0%2520_%2520Overview%2520of%2520the%2520Croatian%2520eID%2520scheme.pdf%3Fversion%3D1%26modificationDate%3D1531761001841%26api%3Dv2&usg=AOvVaw0pSbrSOz7gqVGlW9lGkNNU) is the only specification I could find.

Any help would be appreciated, thanks!

**Comment by niksy** [comment]
Also looking for this, especially since eID middleware currently doesn’t support ARM64 so signing and authentication process is disabled.

**Comment by frankmorgner** [comment]
eOI should be supported as of 0.24.0 release

**Comment by msetina** [comment]
@frankmorgner this probably is not eOI as in the driver EOI that @llogar wrote. That one is for Slovenian eID, but since there is no spec noone can know.

**Comment by frankmorgner** [comment]
The first link in the issue description referes to the proprietary **eOI Middleware**, so I hope this is compatible with our eOI driver.

**Comment by msetina** [comment]
Slovenia, Croatia and Serbia I think all call their eID cards eOI(language and history). Slovenians were first to the line, so the driver name in OpenSC is EOI.
There is a page on WIki for Serbian eID cards. 
Croatian card has https://en.wikipedia.org/wiki/Croatian_identity_card, but there is no info what the HW is.

**Comment by frankmorgner** [comment]
ok, then lets see if we get complaints from anywhere

**Comment by niksy** [comment]
It doesn’t seem to work for Croatian eOI.

@dCubelic can you please verify?

**Comment by llogar** [comment]
I'd be very surprised if the Croatian eOI would work with my (Slovenian eOI) driver. My wild guess is that apart from the name the two eID cards don't have much in common...

**Comment by nsajko** [comment]
Reopen, the initial close above was due to a misunderstanding (conflating the Slovenian and the Croatian electronic ID).

**Comment by frankmorgner** [comment]
If you're planning to make a contribution to the project, we'd love to add a new card to OpenSC. We would be happy to get you going and to comment on your code. However, please have in mind that in lack of hardware, documentation and manpower, we can't do this on our own.

**Comment by nsajko** [comment]
Sorry, I was not trying to demand free labor of the contributors. It's just that I see that other feature requests for national ID cards do remain open here on the bug tracker, so reopening this issue seems like correct procedure? On the off chance I try to contribute support for the Croatian/AKD/Certilia card to OpenSC one day, there would be an issue to link from the hypothetical PR.

**Comment by frankmorgner** [comment]
I think reopening make sense once we do have some real efforts for adding support for the new card. Thanks for you understanding.
