### ISSUE TITLE
Cannot install OpenSC 0.22.0 dmg on MacOS

### ISSUE THREAD

**Issue by max-dfinity** [OpenSC/OpenSC#2545]
### Problem Description

When trying to install latest (0.22.0) MacOS does not let me continue, and gives an error message (see screenshot below).

My mac specs: 
![image](https://user-images.githubusercontent.com/100170574/165867053-d4e06f4c-f78d-4dc9-823e-227c68a01d28.png)

No such problem happens with version 0.2.1

### Proposed Resolution

No idea.

### Steps to reproduce

1. Download [OpenSC-0.22.0.dmg](https://github.com/OpenSC/OpenSC/releases/download/0.22.0/OpenSC-0.22.0.dmg) from https://github.com/OpenSC/OpenSC/releases/tag/0.22.0 

2. Open the file after downloading.

3. Double-click on OpenSC 0.22.0.pkg in window that opens

### Logs

![image](https://user-images.githubusercontent.com/100170574/165866993-24a4b2a4-ea00-4e8b-8eb8-05ffe24c0da1.png)

**Comment by frankmorgner** [comment]
try right click + open
