### ISSUE TITLE
Italian CNS not detected by the minidriver

### ISSUE THREAD

**Issue by funnydog** [OpenSC/OpenSC#2546]
### Problem Description

Hello, I'm trying to use the OpenSC minidriver to handle the Authentication to websites via smartcard but unfortunately the card is not recognized by the minidriver.

The opensc-tool program correctly identifies the card as you can see in the log below.

```
C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe -n
Using reader with a card: bit4id miniLector-EVO 0
CNS card
```

I also recorded the ATR output and the tests of pkcs11-tool below in the Logs section.

The bit4id manager identifies the card as "Oberthur Technologies, Cosmo ID ONE(T)"

### Proposed Resolution

Looking at the registry entries for the minidriver I wondered if I could simply change the ATR of an existing entry to match the one of the above smart card and so I did exactly that.

And it works, I can successfully authenticate to websites in Microsoft Edge and in Firefox: the system asks for the PIN and the authentication ends flawlessly.

However, given the error produced by the pkcs11-tool for the missing random generation/seeding (see below) I don't think that what I'm doing is exactly safe...

Should I avoid doing this and go back to the absymal bit4id driver?

Is there a simple way to add support for the card in the minidriver?

### Logs

This is the ATR of the card:
```
C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool.exe -a
Using reader with a card: bit4id miniLector-EVO 0
3b:ff:18:00:00:81:31:fe:45:00:6b:11:05:07:00:01:21:01:43:4e:53:10:31:80:4a
```

This is what I get if I run the tests with the pkcs11-tool:

```
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --login --test --module ..\pkcs11\opensc-pkcs11.dll
Using slot 0 with a present token (0x0)
Logging in to "XXXX XXXXXXX (PIN CNS0)".
WARNING: user PIN locked
Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_DATA_LEN_RANGE (0x21)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CNS0)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (CNS0)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
Decryption (currently only for RSA)
  testing key 0 (CNS0) -- can't be used to decrypt, skipping
1 errors
```

**Comment by dengert** [comment]
>  I wondered if I could simply change the ATR of an existing entry to match the one of the above smart card

Better choice is to add a new new entry, based on one of the "Italian CNS" entries. 

The way Microsoft picks a minidriver is based on the ATR and not as flexible as the  OpenSC non-minidriver code which can detect card types even if the ATR was not previously known. 

In the case of CNS cards, it looks at the ATR for CNS in the historical bytes. You can past in the ATR to this site https://smartcard-atr.apdu.fr/  to parse the ATR. 

Looks like:
https://github.com/OpenSC/OpenSC/blob/master/win32/customactions.cpp#L131-L138
may need another entry for this type of CNS card.

**Comment by funnydog** [comment]
Hello, I created a pull request with the new entry for the smartcard.

I recompiled everything with Visual Studio 2019 (I had to install tons of packages!) and it seems to work.
