### ISSUE TITLE
Firefox snap (Ubuntu 22.04) not working with SmartCard

### ISSUE THREAD

**Issue by jpbowling** [OpenSC/OpenSC#2552]
### Recently upgraded a 20.04 VM to 22.04 and found no longer able to authenticate with SmartCard.  Attempted to uninstall/reinstall OpenSC.  Tried FireFox and Chromium.  Created a fresh 20.04 VM and was able to add the security device and log in with no problems.    When attempting to add the module to FireFox an error message is returned.  Checked to verify that read permissions on the module are set. pcsc_scan shows the SmartCard's details.

Kindly request assistance with this issue.

### No logs recorded since the error seems to be happening before OpenSC is active.

![Screenshot from 2022-05-13 21-07-41](https://user-images.githubusercontent.com/78725923/168280119-a0fec5dc-279c-46f4-afe4-b31bdaadb92d.png)

**Comment by frankmorgner** [comment]
Please create a debug log of your problem as described in the [comments of our issue template](https://raw.githubusercontent.com/OpenSC/OpenSC/master/.github/ISSUE_TEMPLATE.md). You may also want to look at the hints on [how to write a good bug report](https://github.com/OpenSC/OpenSC/wiki/How-to-write-a-good-bug-report).

**Comment by jpbowling** [comment]
Frank,

I sure did give that a shot, but the debug file was blank. I certainly understand that logs are helpful. I didn't have a lot to work with so I reached out for help. If you have something specific I can try or you want to troubleshoot together I am happy to assist.

Thanks,
James

________________________________

**Comment by dengert** [comment]
I have just installed XUbuntu 22.04 also. First see if you can see the card reader:  
```
$ opensc-tool --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
```
If not, see:  https://bugs.launchpad.net/ubuntu/+source/pcsc-lite/+bug/1971984
and https://ludovicrousseau.blogspot.com/2011/11/pcscd-auto-start-using-systemd.html

Then see if you can read the ATR:
```
$ opensc-tool -a
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
3b:df:96:00:81:b1:fe:45:1f:83:80:73:cc:91:cb:f9:a0:00:00:03:08:00:00:10:00:79
```
If that works, then try `pkcs11-tool --login --test` and `pkcs11-tool --O`

The try firefox again. Let me know how far you get.

**Comment by dengert** [comment]
Using VirtualBox running on windows 10 pro host, I have  XUbuntu-20.04 and XUbuntu-22.04 running as guest. 

 XUbuntu-20.04 guest with Firefox 99.0 and a version of OpenSC-0.22.0-rc2 I built with OpenSSL-1.1.1k, Firefox asks for pin and can see the certificates. 

XUbuntu-22.04 system with Firefox 100.0 and the Ubuntu installed version of OpenSC 0.22.0 Firefox does not see the card at all.
Firxfor is now installed as via "snap" and There appears to be a lot of issues with "snap" installed apps and smartcards. 

Google for: ubuntu install firefox without snap

https://askubuntu.com/questions/1399383/how-to-install-firefox-as-a-traditional-deb-package-without-snap-in-ubuntu-22

https://fostips.com/ubuntu-21-10-two-firefox-remove-snap/

https://ubuntuhandbook.org/index.php/2022/04/install-firefox-deb-ubuntu-22-04/

**Comment by dengert** [comment]
@mozkeeler  Is this problem related to Ubuntu's use of snap? 

Can  https://github.com/mozkeeler/osclientcerts/  run on linux and use p11-kit?

If `osclientcerts.so` module was distributed as a snap module which appears to endup on my system in /snap/firefox/1300/usr/lib/firefox would this be a solution to this problem?

**Comment by mozkeeler** [comment]
I would guess this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1734371 (and I'm surprised this ever worked - is Ubuntu using snap new?)
osclientcerts doesn't work on linux at the moment. It's something I'd like to explore making work, but I don't know when I'll be able to look into it.

**Comment by dengert** [comment]
>  is Ubuntu using snap new?

Ubuntu-22.04 is using snap for firefox (100.0)  and (maybe thunderbird).  and https://bugzilla.mozilla.org/show_bug.cgi?id=1734371 looks like the bug and another has another circumvention, which may also work. (may try next week)

To get a working FireFox with OpenSC and a PIV card on XUbuntu-22.04 I followed https://ubuntuhandbook.org/index.php/2022/03/install-firefox-esr-ubuntu/ (and one that added the "echo to created the /etc/apt/preferences.d/mozilla-firefox" which may not be needed as it is called firefox-esr. 

```
sudo apt-get remove firefox 
sudo snap remove firefox
sudo add-apt-repository ppa:mozillateam/ppa
echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox
view /etc/apt/preferences.d/mozilla-firefox
sudo apt install firefox-esr
firefox-esr
```
It has an icon under applications, , but the "web-browser" icon does not find it. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1734371 looks like the bug.

So this does not look like an OpenSC problem, but a snap/Ubuntu/Mozilla problem that does not have all the need libs in the snap package to be able to use smartcards.

**Comment by jpbowling** [comment]
Doug,

After a bit of work, I was able to follow along and install FF according to your recommendations. It worked!! Odd that both FF and Chromium stopped working with SmartCards after the upgrade. At any rate thank you greatly for your assistance!

JPB

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dengert** [comment]
This is an Ubuntu/Mozilla/snap problem https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1967632 with any PKCS11 module. In this case it is  libaetpkss.so.3.5.4112"
```
[sáb abr 2 17:32:27 2022] audit: type=1400 audit(1648931547.646:115): apparmor="DENIED" operation="file_mmap" profile="snap.firefox.firefox" name="/run/user/1000/doc/e0bac853/libaetpkss.so.3.5.4112" pid=3680 comm="firefox" requested_mask="m" denied_mask="m" fsuid=1000 ouid=0
```
I am getting (on a freshly installed XUbuntu-22.04): 
```
May 15 13:36:15 test-22 kernel: [ 2491.815165] audit: type=1400 audit(1652639775.677:53): apparmor="DENIED" operation="file_mmap" profile="snap.firefox.firefox" name="/run/user/1000/doc/987ab150/p11-kit-client.so" pid=2608 comm="firefox" requested_mask="m" denied_mask="m" fsuid=1000 ouid=0
```

The snap version of Firefox copies the module to a `/run/user/<UID>/doc/<profile>/` directory so it can be readable, but then the apparmor denies it access. I have tried this with OpenSC module and p11-kit module. The apparmor profile is reported to be `snap.firefox.firefox`  but /etc/apparmor.d has a `usr.lib.snapd.snap-confine.real`. But  `/var/lib/snapd/apparmor/profiles/` does have a  snap.firefox.firefox.

**Comment by frankmorgner** [comment]
As far as I know, snap doesn't have a concept allowing I/O with a seperate shared library (i.e. outside of the snap)...

But there already is a solution for this which I've already outlined [here](https://github.com/OpenSC/OpenSC/pull/2528#issuecomment-1075234783): Just create the application's snap (Firefox) with a plug for pkcs11 proxy client. This allows connecting a pkcs11 snap of OpenSC with pkcs11 proxy server

Demo code is available here https://github.com/valentindavid/pkcs11-demo, pkcs11 proxy is part of p11-kit https://p11-glue.github.io/p11-glue/p11-kit/manual/sharing.html

**Comment by dengert** [comment]
The Snap version of firefox uses an apparmor profile  located in  `/var/lib/snapd/apparmor/profiles/snap.firefox.firefox`

A reported the first problem reported in https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1967632 and https://bugzilla.mozilla.org/show_bug.cgi?id=1734371 They did not allow file_mmap to access the p11-kit proxy or the opensc-pkcs11 modules.  

Once I did that I could at least modified `/var/lib/snapd/apparmor/profiles/snap.firefox.firefox` I stoped getting the file_mmap errors, and was able to at least get the 
~/snap/firefox/common/.mozilla/firefox/mo9gfu9i.default :
```
library=
name=NSS Internal PKCS #11 Module
parameters=configdir='sql:/home/doug/snap/firefox/common/.mozilla/firefox/mo9gfu9i.default' certPrefix='' keyPrefix='' secmod='secmod.db' flags=optimizeSpace updatedir='' updateCertPrefix='' updateKeyPrefix='' updateid='' updateTokenDescription='' 
NSS=Flags=internal,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[ECC,RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

library=/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
name=p11-kit

library=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
name=opensc
```
So in setting->Privacy & Security -> Security Devices I can see the paths. But it does not show anything it might have read for the module. 

I don't know if "snap doesn't have a concept allowing I/O with a seperate shared library" is the right term to use,
it looks like  it is able to load the modules. It looks like apparmor is on a process bases, (as apparmor is in the kernel). 

I added a  /etc/apparmor.d/abstractions/opensc:
# DEE modified to support loading of opensc-pkcs11.so and onepin-opensc-pkcs11.so

  abi <abi/3.0>,

  /etc/opensc/ r,
  /etc/opensc/opensc.conf r,

  /usr/lib{,32,64}/*.so mr,
  /usr/lib{,32,64}/*.so. mr,
  /usr/lib/@{multiarch}/*.so mr,
  /usr/lib/@{multiarch}/*.so.* mr,
  /run/pcscd/ r,


  # gnome-keyring pkcs11 module
  # owner @{run}/user/[0-9]*/keyring*/pkcs11 rw,

  # p11-kit also supports reading user configuration from ~/.pkcs11 depending
  # on how /etc/pkcs11/pkcs11.conf is configured. This should generally not be
  # included in this abstraction.

  # Include additions to the abstraction
  # include if exists <abstractions/p11-kit.d>
```

and in `/var/lib/snapd/apparmor/profiles/snap.firefox.firefox` added the line:
` #include <abstractions/opensc>`

Firefox does not say why it can not use the modules. It could be some file or directory or other shared library is not accessible too. 

It might be that it is the IPC interface to the system pcscd is the problem. The nss debugging may have changed and it is not clear how to pass  environment variables to turn on debugging. 

This is a can-of-worms and there are a lot of people complaining about Ubuntu-22.04 and snap. And not just about smartcard access.

**Comment by jpbowling** [comment]
Thanks for even more detail on this fellas.  It does explain the weird module path when trying to add it into FireFox.  I suppose it probably also explains why trying to add it into Chromium fails as well.

I'm not up to the level to be able to digest all of the potential impacts to other things, but it does sound like a pretty significant change that might affect the functionality of a lot of applications.

I hope that something comes along from the Ubuntu folks to help address this on a wider scope.

In the meantime I greatly appreciate the fantastic feedback you've given to help get me back on my feet.

Thanks!
JPB

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by choman** [comment]
I am now running into this problem.  so I am following

**Comment by techie66** [comment]
For the benefit of googlers, in 22.04 I found even installing the non-snap version had issues:
`sudo dmesg` may show something like 
`audit: type=1400 audit(1690847942.284:2068): apparmor="DENIED" operation="connect" profile="firefox" name="/run/pcscd/pcscd.comm" pid=181793 comm="firefox" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0`

To correct that, a workaround is to add
 `/run/pcscd/pcscd.comm rmw,`
 to the file 
`/etc/apparmor.d/local/usr.bin.firefox`

**This is intended to fix apparmor problems in the ppa version, not the snap**

**Comment by cpholt** [comment]
For the benefit of others who arrive here:  I upgraded from 20.04 to ubuntu 22.04.  I had  firefox with PIV card and an eToken that both stopped working.  Firefox didn't see the cards, and chrome just crashed if they were plugged in.  I tried firefox-esr (the non-snap solution above).  that fixed the eToken, but not the PIV card.  My surprising solution turned out to be this:

`sudo apt-get purge opensc-pkcs11 pcscd pcsc-tools`

Then both my PIV card and eToken worked automagically in Chrome with no further configuration.  previously (ubuntu 20.04) they ONLY worked in firefox with the opensc-pkcs11 packages.

If anyone has any follow up advice on WHY this worked, I'd love to hear it.

YMMV.  Good luck.

**Comment by LudovicRousseau** [comment]
@cpholt you now have your PIV card working on Chrome (without pcscd) but still not with Firefox. Exact?

**Comment by cpholt** [comment]
Yes.  That is correct.  I'm just thrilled it's working.

**Comment by cpholt** [comment]
@LudovicRousseau , just wanted to ping you to make sure you saw my updates that pcscd was requried after all.

**Comment by frankmorgner** [comment]
Mozilla now officially supports debian based distributions. remove the firefox snap and use their package
https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
