### ISSUE TITLE
Issue with YubiKey and ECC keys

### ISSUE THREAD

**Issue by CaptAintHere** [OpenSC/OpenSC#2559]
#### Environment

Operating System : **Windows 11 21H2**

OpenSC version : **0.22.0**
```
PS > & 'C:\Program Files\OpenSC Project\OpenSC\tools\opensc-tool.exe' --version
OpenSC-0.22.0-rc1-74-gc902e199, rev: c902e199, commit-time: 2021-08-10 11:09:03 +0200
```

OpenSSH version : **8.9p1**
```
PS > ssh.exe -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
```

#### Issue

I'm facing an issue with OpenSC and the use of a YubiKey 5. It seems that ECCP256 and ECCP384 keys are not supported by OpenSC. When I try to export the public key from the YubiKey the following errors are returned :
```
PS > ssh-keygen.exe -D 'C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll' -e
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
Enter PIN for 'SSH key':
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
cannot read public key from pkcs11
```

### Proposed Resolution

N/A

### Steps to reproduce

Generate an ECCP256 or ECCP384 on the YubiKey with the `yubico-piv-tool` ([source](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html)) :
```
PS > & 'C:\Program Files\Yubico\Yubico PIV Tool\bin\yubico-piv-tool.exe' -s 9a -a generate -A ECCP384 -o public.pem
PS > & 'C:\Program Files\Yubico\Yubico PIV Tool\bin\yubico-piv-tool.exe' -a verify-pin -a selfsign-certificate -s 9a -S "/CN=SSH key/" -i public.pem -o cert.pem
PS > & 'C:\Program Files\Yubico\Yubico PIV Tool\bin\yubico-piv-tool.exe' -a import-certificate -s 9a -i cert.pem
```

Then try to export the public key from the YubiKey with the following command :
`PS > ssh-keygen.exe -D 'C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll' -e`

### Logs

OpenSC debug logs : [Gist](https://gist.github.com/CaptAintHere/000e3d0103513ff76d884faec59bb8a3)

OpenSSH debug logs :
```
PS > .ssh-keygen.exe -vvv -D 'C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll' -e
debug1: provider C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll: manufacturerID <OpenSC Project> cryptokiVersion 2.20 libraryDescription <OpenSC smartcard framework> libraryVersion 0.22
debug1: provider C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll slot 0: label <SSH key> manufacturerID <piv_II> model <PKCS#15 emulate> serial <00000000> flags 0x40d
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
Enter PIN for 'SSH key':
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
debug1: pkcs11_provider_finalize: provider "C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll" refcount 1 valid 1
debug1: pkcs11_provider_unref: provider "C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll" refcount 1
debug1: pkcs11_add_provider: provider C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll returned no keys
cannot read public key from pkcs11
```

**Comment by Jakuje** [comment]
Can you provide the output of pkcs11 spy? This should do that:
```
PKCS11SPY='C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll' ssh-keygen.exe -D 'C:\Program Files\OpenSC Project\OpenSC\pkcs11\pkcs11-spy.dll'
```
I have same version of OpenSC, but a bit older version of OpenSSH with some patches and it works ok to me.

I assume this will most probably be an issue on the OpenSSH side.

**Comment by dengert** [comment]
I question the public.pem output from:
`PS > & 'C:\Program Files\Yubico\Yubico PIV Tool\bin\yubico-piv-tool.exe' -s 9a -a generate -A ECCP384 -o public.pem`

Try:
`openssl asn1parse -i -in public.pem`

It should look something like the following that was with a NIST demp card with ECC 256 key:
```
$ pkcs15-tool --read-public-key 01 | openssl asn1parse -i 
Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
    0:d=0  hl=2 l=  89 cons: SEQUENCE          
    2:d=1  hl=2 l=  19 cons:  SEQUENCE          
    4:d=2  hl=2 l=   7 prim:   OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim:   OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim:  BIT STRING     
```
these might also help:
```
pkcs15-tool --read-certificate 01 | openssl asn1parse -i 
pkcs15-tool --read-certificate 01 | openssl x509 -noout -text
pkcs15-tool --read-public-key 01 | openssl pkey -pubin -text
```
PIV card do not store the pubkey as separate object but  extracts it from the certificate. 
 
Also look at an on line asn1 parser at https://lapo.it/asn1js/

**Comment by CaptAintHere** [comment]
> Can you provide the output of pkcs11 spy? This should do that:
> 
> ```
> PKCS11SPY='C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll' ssh-keygen.exe -D 'C:\Program Files\OpenSC Project\OpenSC\pkcs11\pkcs11-spy.dll'
> ```
> 
> I have same version of OpenSC, but a bit older version of OpenSSH with some patches and it works ok to me.
> 
> I assume this will most probably be an issue on the OpenSSH side.

With the following commands :
```
$env:PKCS11SPY='C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll'
.\OpenSSH\ssh-keygen.exe -vvv -D 'C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll'
```
The following error is returned :
```
debug1: provider C:\\Program Files\\OpenSC Project\\PKCS11-Spy\\pkcs11-spy.dll: manufacturerID <OpenSC Project> cryptokiVersion 3.0 libraryDescription <OpenSC smartcard framework> libraryVersion 0.22
debug1: provider C:\\Program Files\\OpenSC Project\\PKCS11-Spy\\pkcs11-spy.dll slot 0: label <SSH key> manufacturerID <piv_II> model <PKCS#15 emulate> serial <00000000> flags 0x40d
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
Enter PIN for 'SSH key':
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
debug1: pkcs11_provider_finalize: provider "C:\\Program Files\\OpenSC Project\\PKCS11-Spy\\pkcs11-spy.dll" refcount 1 valid 1
debug1: pkcs11_provider_unref: provider "C:\\Program Files\\OpenSC Project\\PKCS11-Spy\\pkcs11-spy.dll" refcount 1
debug1: pkcs11_add_provider: provider C:\\Program Files\\OpenSC Project\\PKCS11-Spy\\pkcs11-spy.dll returned no keys
cannot read public key from pkcs11
```

**Comment by CaptAintHere** [comment]
> I question the public.pem output from: `PS > & 'C:\Program Files\Yubico\Yubico PIV Tool\bin\yubico-piv-tool.exe' -s 9a -a generate -A ECCP384 -o public.pem`
> 
> Try: `openssl asn1parse -i -in public.pem`
> 
> It should look something like the following that was with a NIST demo card with ECC 256 key:
> 
> ```
> $ pkcs15-tool --read-public-key 01 | openssl asn1parse -i 
> Using reader with a card: SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
>     0:d=0  hl=2 l=  89 cons: SEQUENCE          
>     2:d=1  hl=2 l=  19 cons:  SEQUENCE          
>     4:d=2  hl=2 l=   7 prim:   OBJECT            :id-ecPublicKey
>    13:d=2  hl=2 l=   8 prim:   OBJECT            :prime256v1
>    23:d=1  hl=2 l=  66 prim:  BIT STRING     
> ```
> 
> these might also help:
> 
> ```
> pkcs15-tool --read-certificate 01 | openssl asn1parse -i 
> pkcs15-tool --read-certificate 01 | openssl x509 -noout -text
> pkcs15-tool --read-public-key 01 | openssl pkey -pubin -text
> ```
> 
> PIV card do not store the pubkey as separate object but extracts it from the certificate.
> 
> Also look at an on line asn1 parser at https://lapo.it/asn1js/

```
PS > & 'C:\Program Files\Git\usr\bin\openssl.exe' asn1parse -i -in .\public.pem
    0:d=0  hl=2 l= 118 cons: SEQUENCE
    2:d=1  hl=2 l=  16 cons:  SEQUENCE
    4:d=2  hl=2 l=   7 prim:   OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   5 prim:   OBJECT            :secp384r1
   20:d=1  hl=2 l=  98 prim:  BIT STRING
```
```
PS > & 'C:\Program Files\OpenSC Project\OpenSC\tools\pkcs15-tool.exe' --reader 2 --read-certificate 01 | & 'C:\Program Files\Git\usr\bin\openssl.exe' asn1parse -i
    0:d=0  hl=4 l= 426 cons: SEQUENCE
    4:d=1  hl=4 l= 305 cons:  SEQUENCE
    8:d=2  hl=2 l=   3 cons:   cont [ 0 ]
   10:d=3  hl=2 l=   1 prim:    INTEGER           :02
   13:d=2  hl=2 l=   9 prim:   INTEGER           :ECF73BA5735EC894
   24:d=2  hl=2 l=  10 cons:   SEQUENCE
   26:d=3  hl=2 l=   8 prim:    OBJECT            :ecdsa-with-SHA256
   36:d=2  hl=2 l=  18 cons:   SEQUENCE
   38:d=3  hl=2 l=  16 cons:    SET
   40:d=4  hl=2 l=  14 cons:     SEQUENCE
   42:d=5  hl=2 l=   3 prim:      OBJECT            :commonName
   47:d=5  hl=2 l=   7 prim:      UTF8STRING        :SSH key
   56:d=2  hl=2 l=  30 cons:   SEQUENCE
   58:d=3  hl=2 l=  13 prim:    UTCTIME           :220530070424Z
   73:d=3  hl=2 l=  13 prim:    UTCTIME           :230530070424Z
   88:d=2  hl=2 l=  18 cons:   SEQUENCE
   90:d=3  hl=2 l=  16 cons:    SET
   92:d=4  hl=2 l=  14 cons:     SEQUENCE
   94:d=5  hl=2 l=   3 prim:      OBJECT            :commonName
   99:d=5  hl=2 l=   7 prim:      UTF8STRING        :SSH key
  108:d=2  hl=2 l= 118 cons:   SEQUENCE
  110:d=3  hl=2 l=  16 cons:    SEQUENCE
  112:d=4  hl=2 l=   7 prim:     OBJECT            :id-ecPublicKey
  121:d=4  hl=2 l=   5 prim:     OBJECT            :secp384r1
  128:d=3  hl=2 l=  98 prim:    BIT STRING
  228:d=2  hl=2 l=  83 cons:   cont [ 3 ]
  230:d=3  hl=2 l=  81 cons:    SEQUENCE
  232:d=4  hl=2 l=  29 cons:     SEQUENCE
  234:d=5  hl=2 l=   3 prim:      OBJECT            :X509v3 Subject Key Identifier
  239:d=5  hl=2 l=  22 prim:      OCTET STRING      [HEX DUMP]:0414E6EDC9A9A08AC8D8FEA65D57382578B26718E99C
  263:d=4  hl=2 l=  31 cons:     SEQUENCE
  265:d=5  hl=2 l=   3 prim:      OBJECT            :X509v3 Authority Key Identifier
  270:d=5  hl=2 l=  24 prim:      OCTET STRING      [HEX DUMP]:30168014E6EDC9A9A08AC8D8FEA65D57382578B26718E99C
  296:d=4  hl=2 l=  15 cons:     SEQUENCE
  298:d=5  hl=2 l=   3 prim:      OBJECT            :X509v3 Basic Constraints
  303:d=5  hl=2 l=   1 prim:      BOOLEAN           :255
  306:d=5  hl=2 l=   5 prim:      OCTET STRING      [HEX DUMP]:30030101FF
  313:d=1  hl=2 l=  10 cons:  SEQUENCE
  315:d=2  hl=2 l=   8 prim:   OBJECT            :ecdsa-with-SHA256
  325:d=1  hl=2 l= 103 prim:  BIT STRING
```
```
PS > & 'C:\Program Files\OpenSC Project\OpenSC\tools\pkcs15-tool.exe' --reader 2 --read-certificate 01 | & 'C:\Program Files\Git\usr\bin\openssl.exe' x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ec:f7:3b:a5:73:5e:c8:94
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = SSH key
        Validity
            Not Before: May 30 07:04:24 2022 GMT
            Not After : May 30 07:04:24 2023 GMT
        Subject: CN = SSH key
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:3b:5a:b2:0e:27:2b:f0:8d:61:4c:10:ef:0e:38:
                    0d:17:f3:28:34:eb:f7:ac:e5:65:80:30:53:f1:bf:
                    f9:b7:09:ed:22:79:e0:f0:11:f0:f0:4f:36:f8:1d:
                    e0:51:9b:87:28:32:6b:3b:2d:48:ff:01:da:3b:76:
                    76:8b:70:e8:37:99:51:8c:52:ed:ff:92:90:ba:30:
                    57:76:17:53:48:5e:d3:cc:98:a1:1a:42:92:33:0b:
                    59:32:4c:05:ce:a4:cc
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                E6:ED:C9:A9:A0:8A:C8:D8:FE:A6:5D:57:38:25:78:B2:67:18:E9:9C
            X509v3 Authority Key Identifier:
                keyid:E6:ED:C9:A9:A0:8A:C8:D8:FE:A6:5D:57:38:25:78:B2:67:18:E9:9C

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: ecdsa-with-SHA256
         30:64:02:30:22:6a:4b:96:60:5b:57:8d:92:74:ca:ed:16:9e:
         90:a3:37:c0:d9:fb:40:ec:d1:74:4b:e8:6c:ed:94:46:ae:dc:
         34:ce:55:f4:58:81:ba:a0:23:a1:3b:21:37:ad:9c:77:02:30:
         58:e6:fc:2d:b5:81:b8:29:5e:c5:67:26:66:2c:bc:e5:b2:17:
         b7:7b:ad:ba:30:8a:7b:a1:97:58:91:7c:e5:28:13:a2:55:39:
         57:58:6f:86:92:f2:04:30:d2:40:11:a3
```
```
PS > & 'C:\Program Files\OpenSC Project\OpenSC\tools\pkcs15-tool.exe' --reader 2 --read-public-key 01 | & 'C:\Program Files\Git\usr\bin\openssl.exe' pkey -pubin -text
-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEO1qyDicr8I1hTBDvDjgNF/MoNOv3rOVl
gDBT8b/5twntInng8BHw8E82+B3gUZuHKDJrOy1I/wHaO3Z2i3DoN5lRjFLt/5KQ
ujBXdhdTSF7TzJihGkKSMwtZMkwFzqTM
-----END PUBLIC KEY-----
Public-Key: (384 bit)
pub:
    04:3b:5a:b2:0e:27:2b:f0:8d:61:4c:10:ef:0e:38:
    0d:17:f3:28:34:eb:f7:ac:e5:65:80:30:53:f1:bf:
    f9:b7:09:ed:22:79:e0:f0:11:f0:f0:4f:36:f8:1d:
    e0:51:9b:87:28:32:6b:3b:2d:48:ff:01:da:3b:76:
    76:8b:70:e8:37:99:51:8c:52:ed:ff:92:90:ba:30:
    57:76:17:53:48:5e:d3:cc:98:a1:1a:42:92:33:0b:
    59:32:4c:05:ce:a4:cc
ASN1 OID: secp384r1
NIST CURVE: P-384
```
I don't see anything special here, where should I look?

**Comment by Jakuje** [comment]
For the PKCS11 spy, you will need a bit different steps as you are on windows. Please, see https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC#pkcs-11-spy
We would be interested in the trace of the pkcs11 calls issued by the OpenSSH. It is already written in the temporary file `TEMP\pkcs11-spy.log`, or you can adjust it with registry modification or again environment files (not sure about precedence in Windows).

**Comment by Jakuje** [comment]
From the above logs the key look ok to me. I am using `secp384r1` key on my yubikey without any issues.

**Comment by popovec** [comment]
I can confirm this issue, but this is outside opensc/ssh. This issue seems to be specific for windows port of openssh. I have tested ssh from https://github.com/PowerShell/Win32-OpenSSH/releases (V8.9.10p1-Beta). OsEID card, one RSA key, one ECC key .  ssh-keygen is able to read only RSA key, for EC key there is same error "skipping unsupported key type".

**Comment by CaptAintHere** [comment]
> For the PKCS11 spy, you will need a bit different steps as you are on windows. Please, see https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC#pkcs-11-spy We would be interested in the trace of the pkcs11 calls issued by the OpenSSH. It is already written in the temporary file `TEMP\pkcs11-spy.log`, or you can adjust it with registry modification or again environment files (not sure about precedence in Windows).

Thanks for the link. You can find the trace logs from the spy module [on this Gist](https://gist.github.com/CaptAintHere/fb880b87adc7f5e2b563a7daf87c2eb6).

**Comment by Jakuje** [comment]
Thanks.

From the openssh code, it looks like the windows OpenSSH builds do not come with ECDSA support or their OpenSSL implementation does not have `EC_KEY_method_new` defined. Otherwise I do not see a reason why it could fail like this:

https://github.com/PowerShell/openssh-portable/blob/ff6cfe6fdf19fe09de5cca1300f84ef751f21f5f/ssh-pkcs11.c#L1273

Unfortunately, it is not clear to me if they provide some information what is the openssl version they used to build the binaries, if the build log or config log is available somewhere or anything.

**Comment by mouse07410** [comment]
On top of all of the above, it seems that the certificate is created as a CA, but as a leaf node. That could contribute to the problem, though if the given build of OpenSSH doesn't support ECC, it probably stops right there.

**Comment by CaptAintHere** [comment]
It is indeed a problem with OpenSSH for Windows. A patch has been proposed and seems to work correctly. I guess we just have to wait for the release of a new version and the problem will be solved. Thanks to all for your help!
