### ISSUE TITLE
Key on token without a PIN code

### ISSUE THREAD

**Issue by mikhailnov** [OpenSC/OpenSC#2562]
Hello!

I am trying to use pam_p11 (https://github.com/OpenSC/pam_p11) with Rutoken ECP for 2-factor authentication in the operating system, but I want the key on token to not have a pin-code.

Code of pam_p11 can work with such case:

```c
static int key_login(pam_handle_t *pamh, int flags, PKCS11_SLOT *slot, const char *pin_regex)
{
	char *password = NULL;
	int ok;

	if (0 == slot->token->loginRequired
#ifdef HAVE_PKCS11_IS_LOGGED_IN
			|| (0 == PKCS11_is_logged_in(slot, 0, &ok)
				&& ok == 1)
#endif
	   ) {
		ok = 1;
		goto err;
	}
<ask for PIN>
```

But I cannot understand how to make pkcs15-init tool to make a key without a PIN.

My device in `lsusb` is:
`Bus 001 Device 005: ID 0a89:0030 Aktiv Rutoken ECP`

I run:

```
pkcs15-init --erase-card -p rutoken_ecp
pkcs15-init --create-pkcs15 --so-pin "87654321" --so-puk ""
pkcs15-init --store-pin --label "User PIN" --auth-id 02 --pin "12345678" --puk "" --so-pin "87654321" --finalize
pkcs15-init -G rsa/2048 --auth-id 02 --id 42 --label "SSH User's Key" --public-key-label "SSH User's Public Key"
ssh-keygen -D /usr/lib64/opensc-pkcs11.so -I 0:42 >> ~/.ssh/authorized_keys
```

Then pam_p11 asks for PIN.

The question is: how to make `slot->token->loginRequired` have value 0?

There is code in opensc that makes me suspect that opensc was never taught to work without a PIN:

```c
	/*  current PKCS#11 flags should be read from the token,
	 *  but for simplicity assume that user-pin is already initialised -- Andre 2010-10-05
	 */
	flags = COSM_TOKEN_FLAG_TOKEN_INITIALIZED
		| COSM_TOKEN_FLAG_USER_PIN_INITIALIZED
		| COSM_TOKEN_FLAG_LOGIN_REQUIRED
		| COSM_TOKEN_FLAG_PRN_GENERATION;
```

Thanks!

**Comment by mikhailnov** [comment]
Seems that it was done for compatibility with NIST standards and FIPS.

Commit https://github.com/OpenSC/OpenSC/commit/d7d674129ec021454b5f6285a213da912a50a39f by @dengert gave a clue saying:
"NIST 800-73 only requires PIN_Always on the Sign Key."

I also found the following text by searching the internet:
"The PKI cryptographic function (see Table 4b) is protected with a “PIN Always” or “OCC Always” access rule. In other words, the PIN or OCC data must be submitted and verified every time immediately before a digital signature key operation."

There is a strange comment in the code of opensc:
`src/libopensc/pkcs15.h:603:#define SC_PKCS15_TOKEN_LOGIN_REQUIRED			0x02 /* Don't use */`
Why "don't use"?

Do I understand correctly that:

1. technically it is possible to go without a PIN-code
2. but standatrds require a PIN-code
3. code of kdcs15-init does not allow to go without a PIN because of that?

**Comment by dengert** [comment]
@mikhailnov due to the recent actions of your government, this is the last reply you will receive from me.

**Comment by frankmorgner** [comment]
With respect to the technical support, I don't see a problem with having that question here. It's not like someone is suggesting to include a broken random number generator 🤓.  If someone doesn't want to take part in it, just don't do it.

**Comment by frankmorgner** [comment]
slot->token->loginRequired is set in libp11
https://github.com/OpenSC/libp11/blob/master/src/p11_slot.c#L516

The PKCS#11 flag CKF_LOGIN_REQUIRED is set here
https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/framework-pkcs15.c#L1207

pkcs15_init_slot is called by pkcs15_create_slot, which only seems to be called without an authentication object, if a special application should be initialized or if `create_slots_for_pins` is set to `all` (which is the default).

I think the "problem" with your commands is that you're supplying `--auth-id 02` when creating your RSA key, which essentially says that your PIN unlocks the key. Just omit that parameter.

I hope that you are aware that you don't have good control over the key while your token is plugged into any computer.

**Comment by mikhailnov** [comment]
Thanks a lot! I did not find myself when pkcs15_init_slot() is called. But there is a problem:

```bash
$ pkcs15-init --erase-card -p rutoken_ecp
Using reader with a card: Aktiv Rutoken ECP 00 00
$ pkcs15-init --create-pkcs15 --so-pin "87654321" --so-puk ""
Using reader with a card: Aktiv Rutoken ECP 00 00
$ pkcs15-init -G rsa/2048 --id 42 --label "SSH User's Key" --public-key-label "SSH User's Public Key"
Using reader with a card: Aktiv Rutoken ECP 00 00
error: no PIN given for key - either use --insecure or 
specify a PIN using --auth-id
error: no PIN given for key - either use --insecure or 
specify a PIN using --auth-id
Failed to generate key: Invalid arguments
$ pkcs15-init -G rsa/2048 --id 42 --label "SSH User's Key" --public-key-label "SSH User's Public Key" --insecure
Using reader with a card: Aktiv Rutoken ECP 00 00
error: Unknown algorithm "rsa/2048"
error: Invalid symmetric key spec: "rsa/2048"
Failed to generate key: Invalid arguments
```

That is a strange error. I will investigate it. Maybe the smartcard refuses to do that...

**Comment by mikhailnov** [comment]
man of pkcs15-init probably can be improved, we could mention this case more crearly in it. I will send a pull request if succeed in solving this.

**Comment by mikhailnov** [comment]
type becomes "dsa" instead of "rsa" inside `do_generate_skey()` when using `--insecure` for some reasons and this triggers this error, see the screenshot of gdb:

![image](https://user-images.githubusercontent.com/15802528/172151644-c3fadb58-a65a-4048-9b73-8fc80f4abe5c.png)

Code id from https://github.com/OpenSC/OpenSC/tree/0.22.0

**Comment by frankmorgner** [comment]
> type becomes "des" instead of "rsa" inside `do_generate_skey()` when using `--insecure` for some reasons and this triggers this error, see the screenshot of gdb:
> 
> ![image](https://user-images.githubusercontent.com/15802528/172151644-c3fadb58-a65a-4048-9b73-8fc80f4abe5c.png)
> 
> Code is from https://github.com/OpenSC/OpenSC/tree/0.22.0

You need to break at L747 to see which key spec was found

**Comment by frankmorgner** [comment]
Actually you need to find out why do_generate_key returns SC_ERROR_INVALID_ARGUMENTS, because do_generate_key is for RSA, do_generate_skey is for symmetric keys.

**Comment by mikhailnov** [comment]
sc_pkcs15init_generate_key() in the end of do_generate_key() returns -1300 which is SC_ERROR_INVALID_ARGUMENTS, that is why do_generate_skey() is called.

![image](https://user-images.githubusercontent.com/15802528/172332576-1edd3341-99b2-4b6d-9202-f907d9aecb6a.png)

`profile->ops->create_key(profile, p15card, object)` fails (returns -1300) inside sc_pkcs15init_generate_key():

![image](https://user-images.githubusercontent.com/15802528/172337309-8101484b-cd4b-4b29-b570-4a749563aa5b.png)

LOG_TEST_RET macro includes a return() which makes this function return after this error.

**Comment by frankmorgner** [comment]
why is create_key failing? a debug log might also help...

**Comment by frankmorgner** [comment]
It happens here:
```
P:189168; T:0x139884082702144 12:00:09.453 [pkcs15-init] pkcs15-rtecp.c:308:rtecp_create_key: called
P:189168; T:0x139884082702144 12:00:09.453 [pkcs15-init] pkcs15-lib.c:1519:sc_pkcs15init_generate_key: Cannot generate key: create key failed: -1300 (Invalid arguments)
```

**Comment by mikhailnov** [comment]
That is the same that I saw in GDB (yeah, it would be faster to first look into the log...)

**Comment by frankmorgner** [comment]
pkcs15-rtecp.c:313 requires the auth_id to be set (i.e. a PIN needs to be associated to the key). If you want an unprotected key, you may need to change this and the following lines...

**Comment by mikhailnov** [comment]
Oh, thanks for pointint to it!

**Comment by mikhailnov** [comment]
It was so:

```gdb
Breakpoint 1, rtecp_create_key (profile=0x434780, p15card=0x441e90, obj=0x436a60) at pkcs15-rtecp.c:312
312		if (obj->auth_id.len != 1)
(gdb) p obj->auth_id.len
$1 = 0
(gdb) p obj->auth_id.value[0]
$2 = 0 '\000'
(gdb) 
$3 = 0 '\000'
```

I created the following patch:

```diff
diff --git a/src/pkcs15init/pkcs15-rtecp.c b/src/pkcs15init/pkcs15-rtecp.c
index 35f62974..065bc4c6 100644
--- a/src/pkcs15init/pkcs15-rtecp.c
+++ b/src/pkcs15init/pkcs15-rtecp.c
@@ -295,7 +295,9 @@ static int rtecp_create_key(sc_profile_t *profile, sc_pkcs15_card_t *p15card,
 	/*                        AccessMode  - Update  Use  -  -  - Delete */
 	unsigned char prkey_sec[15] = { 0x46, 0,   '?', '?', 0, 0, 0,   '?' };
 	unsigned char pbkey_sec[15] = { 0x46, 0,   '?',   0, 0, 0, 0,   '?' };
-	unsigned char auth_id, paramset;
+	/* The same type as SC_AC_KEY_REF_NONE */
+	unsigned int auth_id;
+	unsigned char paramset;
 	sc_pkcs15_prkey_info_t *key_info;
 	sc_file_t *file;
 	int r;
@@ -309,10 +311,20 @@ static int rtecp_create_key(sc_profile_t *profile, sc_pkcs15_card_t *p15card,
 	if (obj->type != SC_PKCS15_TYPE_PRKEY_RSA
 			&& obj->type != SC_PKCS15_TYPE_PRKEY_GOSTR3410)
 		return SC_ERROR_NOT_SUPPORTED;
-	if (obj->auth_id.len != 1)
-		return SC_ERROR_INVALID_ARGUMENTS;
-	auth_id = obj->auth_id.value[0];
-
+	switch (obj->auth_id.len)
+	{
+		case 1:
+		// 0 when run with --insecure
+		case 0:
+			break;
+		default:
+			return SC_ERROR_INVALID_ARGUMENTS;
+	}
+	if (obj->auth_id.len == 0)
+		// TODO: probably log it?
+		auth_id = SC_AC_KEY_REF_NONE;
+	else
+		auth_id = obj->auth_id.value[0];
 	key_info = (sc_pkcs15_prkey_info_t *)obj->data;
 	assert(key_info);
 	if ((obj->type == SC_PKCS15_TYPE_PRKEY_RSA
```

(I don't know if `auth_id = SC_AC_KEY_REF_NONE` makes sense or just zero is ok)

Now PIN is asked:
```
$ pkcs15-init --erase-card -p rutoken_ecp
Using reader with a card: Aktiv Rutoken ECP 01 00
$ pkcs15-init --create-pkcs15 --so-pin "87654321" --so-puk ""
Using reader with a card: Aktiv Rutoken ECP 01 00
$ pkcs15-init -G rsa:2048 --insecure --id 42 --label "SSH User's Key" --public-key-label "SSH User's Public Key"
Using reader with a card: Aktiv Rutoken ECP 01 00
User PIN required.
Please enter User PIN:
```

It is asked in pkcs11-tool.c:1657. Seems that a check for (opt_insecure == 1) is needed there?

**Comment by mikhailnov** [comment]
Extended my patch:

```diff
diff --git a/src/pkcs15init/pkcs15-lib.c b/src/pkcs15init/pkcs15-lib.c
index 1269bd9c..da3e476e 100644
--- a/src/pkcs15init/pkcs15-lib.c
+++ b/src/pkcs15init/pkcs15-lib.c
@@ -3717,9 +3717,9 @@ sc_pkcs15init_verify_secret(struct sc_profile *profile, struct sc_pkcs15_card *p
 
 	pin_id = sc_pkcs15init_get_pin_reference(p15card, profile, type, reference);
 	sc_log(ctx, "found PIN reference %i", pin_id);
+	if (pin_id == -1)
+		LOG_FUNC_RETURN(ctx, SC_SUCCESS);
 	if (type == SC_AC_SYMBOLIC) {
-		if (pin_id == -1)
-			LOG_FUNC_RETURN(ctx, SC_SUCCESS);
 		reference = pin_id;
 		type = SC_AC_CHV;
 		sc_log(ctx, "Symbolic PIN resolved to PIN(type:CHV,reference:%i)", reference);
diff --git a/src/pkcs15init/pkcs15-rtecp.c b/src/pkcs15init/pkcs15-rtecp.c
index 35f62974..38d5e6ed 100644
--- a/src/pkcs15init/pkcs15-rtecp.c
+++ b/src/pkcs15init/pkcs15-rtecp.c
@@ -295,7 +295,9 @@ static int rtecp_create_key(sc_profile_t *profile, sc_pkcs15_card_t *p15card,
 	/*                        AccessMode  - Update  Use  -  -  - Delete */
 	unsigned char prkey_sec[15] = { 0x46, 0,   '?', '?', 0, 0, 0,   '?' };
 	unsigned char pbkey_sec[15] = { 0x46, 0,   '?',   0, 0, 0, 0,   '?' };
-	unsigned char auth_id, paramset;
+	/* The same type as SC_AC_KEY_REF_NONE */
+	unsigned int auth_id;
+	unsigned char paramset;
 	sc_pkcs15_prkey_info_t *key_info;
 	sc_file_t *file;
 	int r;
@@ -309,10 +311,20 @@ static int rtecp_create_key(sc_profile_t *profile, sc_pkcs15_card_t *p15card,
 	if (obj->type != SC_PKCS15_TYPE_PRKEY_RSA
 			&& obj->type != SC_PKCS15_TYPE_PRKEY_GOSTR3410)
 		return SC_ERROR_NOT_SUPPORTED;
-	if (obj->auth_id.len != 1)
-		return SC_ERROR_INVALID_ARGUMENTS;
-	auth_id = obj->auth_id.value[0];
-
+	switch (obj->auth_id.len)
+	{
+		case 1:
+		/* 0 when run with --insecure */
+		case 0:
+			break;
+		default:
+			return SC_ERROR_INVALID_ARGUMENTS;
+	}
+	if (obj->auth_id.len == 0)
+		/* TODO: probably log it? */
+		auth_id = SC_AC_KEY_REF_NONE;
+	else
+		auth_id = obj->auth_id.value[0];
 	key_info = (sc_pkcs15_prkey_info_t *)obj->data;
 	assert(key_info);
 	if ((obj->type == SC_PKCS15_TYPE_PRKEY_RSA
```

Now I get:
$ pkcs15-init -G rsa:1024 --insecure --id 42 --label "SSH User's Key" --public-key-label "SSH User's Public Key" -vvvvv
<...>
P:357846; T:0x140002913088384 12:17:19.212 [pkcs15-init] iso7816.c:128:iso7816_check_sw: Security status not satisfied
P:357846; T:0x140002913088384 12:17:19.212 [pkcs15-init] card-rtecp.c:752:rtecp_card_ctl: returning with: -1211 (Security status not satisfied)
P:357846; T:0x140002913088384 12:17:19.212 [pkcs15-init] card.c:1065:sc_card_ctl: returning with: -1211 (Security status not satisfied)
P:357846; T:0x140002913088384 12:17:19.212 [pkcs15-init] pkcs15-rtecp.c:633:rtecp_generate_key: returning with: -1211 (Security status not satisfied)
P:357846; T:0x140002913088384 12:17:19.213 [pkcs15-init] pkcs15-lib.c:1522:sc_pkcs15init_generate_key: Failed to generate key: -1211 (Security status not satisfied)
<...>

Wondering if I've met a hardware limitation or not...

**Comment by mikhailnov** [comment]
Seems that another problem is that set_acl_from_sec_attr() in acrd-rtecp.c sets a key reference in ACL ignoring SC_AC_KEY_REF_NONE:

`key_ref = sec_attr_to_key_ref(file->sec_attr[1 + 0]);` (line 184)

**Comment by frankmorgner** [comment]
What's the status of this topic, is there anything to do?

**Comment by frankmorgner** [comment]
In general, keys without a PIN are possible and tested with OpenSC. Doug configured the Yubikey for this, for example. The problem, however, seems to be that it is unknown how to configure your type of card to behave like this.

**Comment by mikhailnov** [comment]
Yes, it seems so. But in fact this behaviour is not much needed, so I gave up trying to do this. But its driver in opensc was written by the developer of this hardware many years ago, we are in contact with our colleagues from that company (Activ, developers of Rutoken), in theory it is possible to ask them for help.

**Comment by frankmorgner** [comment]
Please re-open this topic if there's new input available or you may directly open a pull request when the vendor has added support for this.

**Comment by mikhailnov** [comment]
Thanks for help!
