### ISSUE TITLE
Creating new Files in GIDS Cards

### ISSUE THREAD

**Issue by rayanboulares** [OpenSC/OpenSC#2568]
When we use gids-tool without any parameters, it lists the content of the card filesystem. Would it be possible to add some parameters to create a new file (or deleting them) within the filesystem of the card?

Since GIDS filesystem is not PKCS15 compliant, we can't achieve this with pkcs15-tool...

**Comment by vletoux** [comment]
see here, I think your issue is answered
https://github.com/vletoux/GidsApplet/issues/16

**Comment by rayanboulares** [comment]
Maybe I will work on it on my spare time. I think it would be a nice feature of the `gids-tool` to be able to create, read and delete files and directories on a GIDS card
