### ISSUE TITLE
pkcs11-tool --login always opens a R/W session

### ISSUE THREAD

**Issue by ulrichb** [OpenSC/OpenSC#2576]
When passing `--login` to `pkcs11-tool`, it unconditionally passes `CKF_RW_SESSION` to `C_OpenSession()` due to the following line.

https://github.com/OpenSC/OpenSC/blob/2762c44a96fbc4a49799cc79c983c0bbfd89857e/src/tools/pkcs11-tool.c#L856

I have a Cryptoki/PKCS#11 implementation where this is an issue, because it doesn't support any write-operations, and therefore `C_OpenSession()` immediately returns an `CKR_TOKEN_WRITE_PROTECTED` error. => I cannot run any authenticated operations with `pkcs11-tool`.

Is it on purpose that `--login` always opens the session in R/W mode? If not, can we change the referenced line above to `need_session |= NEED_SESSION_RO`?

**Comment by dengert** [comment]
You maybe right. http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759989 shows how login can be for either a R/O or R/W session.

pkcs11-tool sets NEED_SESSION_RW in a number of places, but there some places that it looks NEED_SESSION_RO should be set instead for example: https://github.com/OpenSC/OpenSC/blob/2762c44a96fbc4a49799cc79c983c0bbfd89857e/src/tools/pkcs11-tool.c#L891-L895
A signature operation does not modify the token. , 

What is the  Cryptoki/PKCS#11 implementation you have?

You are welcome to submit a PR.
