### ISSUE TITLE
pkcs11-register does not work for firefox-esr

### ISSUE THREAD

**Issue by mlegner** [OpenSC/OpenSC#2581]
### Problem Description

Depending on the package and installation method, the `pkcs11-register` tool does not work for `firefox-esr` under Linux because the configuration is located at `~/.mozilla/firefox-esr` instead of `~/.mozilla/firefox`. (In my case, I installed `firefox-esr` from the "official" [mozillateam PPA](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa) on Ubuntu 22.04.)

### Proposed Resolution

In [src/tools/pkcs11-register.c#L233](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-register.c#L233), add a line `{"HOME", ".mozilla/firefox-esr"},`.

### Steps to reproduce

1. Under Ubuntu, add the [mozillateam PPA](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa).
2. Install `firefox-esr`: `sudo apt update && sudo apt install firefox-esr`.
3. Run `pkcs11-register`.
4. Check that there is no output and `~/.mozilla/firefox-esr/XXXX/pkcs11.txt` does *not* contain the OpenSC library.

**Comment by dengert** [comment]
Also see the issues with Ubuntu's SNAP version of firefox (I assume that is why you are using firefox-esr):
https://github.com/OpenSC/OpenSC/issues/2552
https://bugzilla.mozilla.org/show_bug.cgi?id=1734371
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1967632/

So would fix work with either version, (i.e. firefox or firefox-esr) once the above is resolved?

**Comment by mlegner** [comment]
@dengert Yes, the problems with the SNAP version drove me to the mozillateam PPA and the `firefox-esr`. (As a side note, I first tried the `firefox` package from that PPA, but that flat-out ignored the `pkcs11.txt` file altogether. So far I have no idea why.)

On my system, the SNAP package of Firefox also has its configuration in `~/.mozilla/firefox`, so there shouldn't be a problem with `pkcs11-register` (just the general problem with SNAP).

**Comment by frankmorgner** [comment]
additionally checking `~/.mozilla/firefox-esr` should be easy, please try #2587
