### ISSUE TITLE
Can't pair Yubikey with macOS after installing OpenSC

### ISSUE THREAD

**Issue by brechtm** [OpenSC/OpenSC#2590]
### Problem Description

With OpenSC 0.22.0 installed through Homebrew (`brew install --cask opensc`), I could not pair my Yubikey 5 NFC with my user account. On inserting the Yubikey, the pairing notification pops up but clicking _pair_ has no effect.

After uninstalling OpenSC, pairing works again.

### Logs

Trying to pair from the command line, I got this error:

```
$ sudo sc_auth pair -v -u brechtm -h 70F649DEF078448C2BDD1D2BA3E138300E8D2EAD
Cannot pair user (public key hash: 70F649DEF078448C2BDD1D2BA3E138300E8D2EAD). The operation couldn’t be completed. (TKAuthenticationHintsProvider error -11 - SmartCard algorithm initialization error.)
```

This is on macOS Monterey 12.3.1 (21E258).

(Sorry for not providing debug logs. Since I already spent a lot of time to figure out that the brew-installed OpenSC was causing the issue, I don't feel up to spending more time on this. I still wanted to report this issue here, though.)

**Comment by frankmorgner** [comment]
I'm not sure why your token doesn't work with OpenSC. If I remember correctly, I did test OpenSCToken with a Yubikey. Just out of curiosity, does the token work as expected when you use the PKCS#11 interface (`pkcs11-tool --test --login`)?

If you want to disable OpenSC's macOS integration (but keep the PKCS#11 module), you can use this command:
```
pluginkit -r -i org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken
```
This should leave Apple's module as the only provider for your token and it should work again.

**Comment by mouse07410** [comment]
I'm not sure why you'd consider OpenSCToken with Yubikey. MacOS now (for the last few years) includes `pivtoken` that works fine with Yubikey-4 and up. 

IMHO, OpenSCToken comes handy (only) when your token is not PIV-compliant.

**Comment by brechtm** [comment]
> I'm not sure why your token doesn't work with OpenSC. If I remember correctly, I did test OpenSCToken with a Yubikey. Just out of curiosity, does the token work as expected when you use the PKCS#11 interface (pkcs11-tool --test --login)?

Sorry, I can't spend more time on this.

> If you want to disable OpenSC's macOS integration (but keep the PKCS#11 module), you can use this command.

That's very useful to know. Thanks!

> I'm not sure why you'd consider OpenSCToken with Yubikey. MacOS now (for the last few years) includes pivtoken that works fine with Yubikey-4 and up.

Because the [Yubico documentation isn't very good](https://github.com/Yubico/yubico-piv-tool/issues/158#issuecomment-1212158063) and I ended up reading articles that describe using OpenSC.

**Comment by mouse07410** [comment]
I have PIV and Yubikeys in PIV mode. 
FWIW, OpenSCToken app never worked for me, so I stopped trying around Catalina timeframe. 

Perhaps, OpenSC should consider installing OpenSCToken.app as an option, disabled by default? I have it disabled in my scripts.

**Comment by raylau1234** [comment]
I discovered one more oddity about the macOS/OpenSC/YubiKey combination.

Trying to use YubiKey manager's OTP applet to configure OTP reports an error communicating. Uninstalling OpenSC resolves.

But stopping the launch of pkcs11-register, e.g.

```
sudo mv /Library/LaunchAgents/org.opensc-project.mac.pkcs11-register.plist /Library/LaunchAgents/org.opensc-project.mac.pkcs11-register.plist.bak
```

and logging out/in also resolves. 

Not clear to me why as pkcs11-register seems to be adding support to specific apps like firefox, thunderbird, chrome, etc. -- yet the problem show up in YubiKey Manager.

And this does not prevent pkcs11-tool or VeraCrypt from accessing pkcs11.

Just putting this out there to hopefully help other macOS users.

**Comment by dengert** [comment]
I do not have a Mac. But if you are trying to use OpenSC and Yubikey software at the same time, they will both try and access the token at the same time and one could lock access for the other. Also the Yubikey token can have multiple applets, in particular PIV and OpenPGP. The locking is usually done by PCSC. 

 Google for pcsc macos. 

Yubikey is one of the few vendors that provides software for more systems then Windows.

**Comment by raylau1234** [comment]
Yup, but yubikey's pkcs11 support does not allow access to PIV data objects for use with veracrypt on macOS (at least).  That's why I still want opensc.  The challenge has been to get the 2 to  play nicely and after some trial and error and this thread, it ended up being the 2 changes:

- disable org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken but at startup
- don't run pkcs11-register at login

Now there is peaceful coexistence.

**Comment by raylau1234** [comment]
Yup, but yubikey's pkcs11 support does not allow access to PIV data objects for use with veracrypt on macOS (at least).  That's why I still want opensc.  The challenge has been to get the 2 to  play nicely and after some trial and error and this thread, it ended up being the 2 changes:

- disable org.opensc-project.mac.opensctoken.OpenSCTokenApp.OpenSCToken but at startup
- don't run pkcs11-register at login

Now there is peaceful coexistence.

**Comment by dengert** [comment]
**Yup,** but yubikey's pkcs11 support does not allow access to PIV data objects

As a side note what PIV data object are you trying to read? 

OpenSC card-piv.c will return "BER-TLV with the tag '53' containing in the value field of the requested data object" from a GET_DATA command. Technically the tag `53` and length are part of the GET_DATA. I believe Yubikey does not return the '53' and length.  When PUT_DATA is used by piv-tool it expects the `53` and length from the user. I believe Yubkey does not.

**Comment by raylau1234** [comment]
I am repurposing Cardholder Fingerprint for use as a VeraCrypt keyfile.

To me, it actually looked like it prepends 0x8253 <length>.  I thought it was DER (bec the length seems to be using a var length encoding), but now I know it's BER..!

**Comment by frankmorgner** [comment]
The original problem should be fixed with https://github.com/frankmorgner/OpenSCToken/pull/40
