### ISSUE TITLE
CardOS V5.3, 2014 from Charismathics GmbH unsupported

### ISSUE THREAD

**Issue by jrevillard** [OpenSC/OpenSC#2591]
### Problem Description

My company provides cards with token to sign documents but I cannot make it recognized by OpenSC.
```
>  opensc-tool --list-readers --verbose
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             OMNIKEY CardMan 1021 00 00
     3b:d2:18:00:81:31:fe:58:c9:03:16 Atos CardOS 
>  opensc-tool --serial
Using reader with a card: OMNIKEY CardMan 1021 00 00
02 00 1B CF 00 18 1F 40 .......@
>  opensc-tool -n
Using reader with a card: OMNIKEY CardMan 1021 00 00
Atos CardOS
> opensc-tool -i
OpenSC 0.22.0 [gcc  11.2.0]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
 >  opensc-tool --atr
Using reader with a card: OMNIKEY CardMan 1021 00 00
3b:d2:18:00:81:31:fe:58:c9:03:16
>  pkcs15-tool --list-info
Using reader with a card: OMNIKEY CardMan 1021 00 00
PKCS#15 binding failed: Unsupported card
```

### Logs

Here is the full log of the `pkcs15-tool --list-info ` command: https://gist.github.com/jrevillard/425f7a147f660099375d075d11a2c727

Also here is the output of pcs_scan:
```
Using reader plug'n play mechanism
Scanning present readers...
0: OMNIKEY CardMan 1021 00 00
 
Fri Aug 12 09:19:44 2022
 Reader 0: OMNIKEY CardMan 1021 00 00
  Event number: 0
  Card state: Card inserted, 
  ATR: 3B D2 18 00 81 31 FE 58 C9 03 16

ATR: 3B D2 18 00 81 31 FE 58 C9 03 16
+ TS = 3B --> Direct Convention
+ T0 = D2, Y(1): 1101, K: 2 (historical bytes)
  TA(1) = 18 --> Fi=372, Di=12, 31 cycles/ETU
    129032 bits/s at 4 MHz, fMax for Fi = 5 MHz => 161290 bits/s
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 58 --> Block Waiting Integer: 5 - Character Waiting Integer: 8
+ Historical bytes: C9 03
  Category indicator byte: C9 (proprietary format)
+ TCK = 16 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B D2 18 00 81 31 FE 58 C9 03 16
	Austrian "RKS-Card" issued by GlobalTrust (PKI)
	https://secure.globaltrust.eu/info-rksv.html
```

**Comment by dengert** [comment]
The log says it is a SC_CARD_TYPE_CARDOS_V5_3 and card driver was able to read the "date_field_length". 
But then tries to find the path to the PKCS15 files.  3 paths are tried, but none is found, so returns Unsupported card.

You say your  company provide cards. Have you talked to their IT staff about these cards.  It could be they are using the same card, but initialized it with different (or newer) software then what is supported in OpenSC.

Can you get any documentation on the card?

Does it work on Windows with some vendor provided drivers?

```
SC_CARD_TYPE_CARDOS_V5_3 1010

card-cardos.c:322:cardos_init: data_field_length:640 card->reader->max_send_size:65536 card->reader->max_recv_size:65536 SC_CARD_CAP_APDU_EXT
card.c:382:sc_connect_card: card info name:'Atos CardOS', type:1010, flags:0x0, max_send/recv_size:634/638


pkcs15-cardos.c:155:sc_pkcs15emu_cardos_init: called
card.c:844:sc_select_file: called; type=2, path=3f002f00

Outgoing APDU (8 bytes):
00 A4 08 00 02 2F 00 00 ...../..
6A 82

pkcs15.c:980:sc_pkcs15_bind_internal: unable to enumerate apps: File not found

pkcs15.c:1013:sc_pkcs15_bind_internal: application path '3f005015'

Outgoing APDU (7 bytes):
00 A4 08 0C 02 50 15 .....P.
6A 82

pkcs15.c:1039:sc_pkcs15_bind_internal: absolute path to EF(ODF) 3f005031
Outgoing APDU (8 bytes):
00 A4 08 00 02 50 31 00 .....P1.
6A 82

pkcs15-cardos.c:158:sc_pkcs15emu_cardos_init: sc_pkcs15_bind_internal failed: -1413 (Unsupported card)
```

**Comment by jrevillard** [comment]
Hello @dengert ,

Difficult to have accurate info actually because our IT department is not really linux minded ;-).

It seems that they use the Charismatic solution on Windows to use it so I guess that the used profile is: "Charismathics corporate profile" and this could be the problem if opensc is not able to read it ?

I will continue to gather more infos.

Best,
Jerome

**Comment by dengert** [comment]
Googling for "Charismathics Smart Security Interface" It looks like Charismathics supports everything multiple cards with or with    well known applets already on the card like CAC, PIV or their own applet loaded on to generic cards/tokens. The also appear to support Linux: https://www.esign.bg/_Code/UserFiles/Files/CSSI_Linux_5%200_User_Manual.pdf (I don't know how old this is as the examples look like Windows 7 to me.) 

So you may find a non-OpenSC solution for your linux system. 

Also Google for: Charismathics GmbH 

https://www.bloomberg.com/profile/company/0284063Z:GR says web site is  www.charismathics.com

**Comment by jrevillard** [comment]
Yep I did the same research and I will try to use there stuff.... I see that they have their own pkcs11 library: 

```
ldd libcmP11.so 
	linux-vdso.so.1 (0x00007ffd8ffcf000)
	libpcsclite.so.1 => /lib/x86_64-linux-gnu/libpcsclite.so.1 (0x00007fa119357000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa119352000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa11934d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa119348000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa11932c000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa1181d4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa1180ed000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa11930a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa117ec5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa11937e000)
```
Any way to integrate it with a standard tool ?

Thanks for your help !

**Comment by jrevillard** [comment]
It seems to work with there stuff!

```
❯ p11tool --provider $(pwd)/libcmP11.so --list-all   
Object 0:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%F2%EC%8C%D4%DD%2C%0E%1E%B5%00%F2%53%37%1C%76%5A%16%EA%77%57;object=REVILLARD%20JEROME%20jrevillard%2010;type=public
	Type: Public key (RSA-2048)
	Label: XXXXXXXXXXXXXXXXXXXXXXXXX 10
	Flags: CKA_WRAP/UNWRAP; 
	ID: f2:ec:8c:d4:dd:2c:0e:1e:b5:00:f2:53:37:1c:76:5a:16:ea:77:57

Object 1:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%DB%C8%59%E6%25%41%F8%27%7F%4B%16%FC%7C%49%96%7D%46%07%EA%6A;object=REVILLARD%20JEROME%20jrevillard%2013;type=public
	Type: Public key (RSA-2048)
	Label: XXXXXXXXXXXXXXXXXXXXXXXXX 13
	Flags: CKA_WRAP/UNWRAP; 
	ID: db:c8:59:e6:25:41:f8:27:7f:4b:16:fc:7c:49:96:7d:46:07:ea:6a

Object 2:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%52%A4%9C%8F%0B%D7%21%6A%4C%78%11%DD%93%75%F9%90%43%87%EE%57;object=ALMERYS%20ROOT%20CA%2010;type=cert
	Type: X.509 Certificate (RSA-4096)
	Expires: Sun Aug 24 08:55:53 2036
	Label: ALMERYS ROOT CA 10
	Flags: CKA_TRUSTED; 
	ID: 52:a4:9c:8f:0b:d7:21:6a:4c:78:11:dd:93:75:f9:90:43:87:ee:57

Object 3:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%F2%EC%8C%D4%DD%2C%0E%1E%B5%00%F2%53%37%1C%76%5A%16%EA%77%57;object=REVILLARD%20JEROME%20jrevillard%2011;type=cert
	Type: X.509 Certificate (RSA-2048)
	Expires: Thu Jun  6 10:58:49 2024
	Label: XXXXXXXXXXXXXXXXXXXXXXXXX 11
	Flags: CKA_TRUSTED; 
	ID: f2:ec:8c:d4:dd:2c:0e:1e:b5:00:f2:53:37:1c:76:5a:16:ea:77:57

Object 4:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%C4%19%E7%FE%4B%69%48%AA%2F%1A%52%61%10%BF%35%12%6C%53%AF%F6;object=BE%2012;type=cert
	Type: X.509 Certificate (RSA-4096)
	Expires: Wed Apr 10 15:58:22 2030
	Label: BE 12
	Flags: CKA_TRUSTED; 
	ID: c4:19:e7:fe:4b:69:48:aa:2f:1a:52:61:10:bf:35:12:6c:53:af:f6

Object 5:
	URL: pkcs11:model=CardOS%20V5.3;manufacturer=Siemens;serial=02001bcf00181f40;token=null;id=%DB%C8%59%E6%25%41%F8%27%7F%4B%16%FC%7C%49%96%7D%46%07%EA%6A;object=REVILLARD%20JEROME%20jrevillard%2013;type=cert
	Type: X.509 Certificate (RSA-2048)
	Expires: Thu Jun  6 10:58:50 2024
	Label: XXXXXXXXXXXXXXXXXXXXXXXXX 13
	Flags: CKA_TRUSTED; 
	ID: db:c8:59:e6:25:41:f8:27:7f:4b:16:fc:7c:49:96:7d:46:07:ea:6a
```

Now I need to learn how to deal with it...

**Comment by dengert** [comment]
Good to hear it works.  

The problem with OpenSC was finding the PKCS15 files. https://github.com/OpenSC/OpenSC/issues/2591#issuecomment-1213001492

If you want to look for the starting location, you can get a trace from the pcscd  to see the APDUs something like:
`sudo /usr/sbin/pcscd -f -d -a`

The look for the first APDU that has `00 A4 08 00 02  xx xx`

**Comment by jrevillard** [comment]
Sorry I'm not an expert at all in all this area.... 
Here is the requested output: https://gist.github.com/jrevillard/10dd9b071c21986c016b346b75f61dee

would you like more info ?

**Comment by dengert** [comment]
> would you like more info ?

Yes, the log looks like you ran an OpenSC program. What we need to to ruin one of their commands. 

Or try something like: `pkcs11-tool --provider $(pwd)/libcmP11.so -O` 

Take your time I am busy most of the rest of the day.

**Comment by jrevillard** [comment]
Hello @dengert,

Here is the command output:

```
❯ pkcs11-tool --module=$(pwd)/libcmP11.so -O                               
Using slot 0 with a present token (0x1)
Public Key Object; RSA 2048 bits
  label:      XXXX jrevillard 10
  ID:         f2ec8cd4dd2c0e1eb500f253371c765a16ea7757
  Usage:      encrypt, verify, wrap
  Access:     local
Public Key Object; RSA 2048 bits
  label:      XXXX jrevillard 13
  ID:         dbc859e62541f8277f4b16fc7c49967d4607ea6a
  Usage:      encrypt, verify, wrap
  Access:     local
Certificate Object; type = X.509 cert
  label:      XXXX ROOT CA 10
  subject:    XXXX
  ID:         52a49c8f0bd7216a4c7811dd9375f9904387ee57
Certificate Object; type = X.509 cert
  label:      XXXXX jrevillard 11
  subject:    XXXXX
  ID:         f2ec8cd4dd2c0e1eb500f253371c765a16ea7757
Certificate Object; type = X.509 cert
  label:      XXXX 12
  subject:    XXXXX
  ID:         c419e7fe4b6948aa2f1a526110bf35126c53aff6
Certificate Object; type = X.509 cert
  label:      XXXX jrevillard 13
  subject:    XXXX
  ID:         dbc859e62541f8277f4b16fc7c49967d4607ea6a

```

**Comment by dengert** [comment]
If their PKCS11 module works, I would suggest using it.  On any PKCS11 application you can point to their module. It would also mean that your IT people could help if you have problems, as they should provide support for the PKCS11 module and should work with all of their applications. 

It might be possible to get the card working with OpenSC. Any one else want to take a look at this?

The ATR 3b:d2:18:00:81:31:fe:58:c9:03:16 matches one found in card-cardos.c as SC_CARD_TYPE_CARDOS_V5_3. 

PKCS15 is defined in: RSA Laboratories, "The Public-Key Cryptography Standards
               - PKCS #15 v1.1:  Cryptographic token information syntax
               standard", June 6, 2000.  And more recently: ISO/IEC 7816-15

In these the default MF is defines as 3F00. Best I can tell from the traces and OpenSC log, your card may not default the MF to be 3F00 and the card-cardos.c module does not try to set the path to 3F00.    

You may want to look at `opensc-explorer` which can be used to look at directories on the card. 
It has a  ` -m, --mf <arg>                Selects path <arg> on start-up, or none if empty [3F00]`

and try specifying 3F00 or even 2F00 and see what it can find.

**Comment by jrevillard** [comment]
With 3F00:
```
OpenSC [3F00]> find
FileID	Type  Size
[2000]	  DF     0	Name: \xD2v\x00\x00\x98\xC0\x00\x00
```

With 2F00:
```
> opensc-explorer -m 2F00
OpenSC Explorer version 0.22.0
Using reader with a card: OMNIKEY CardMan 1021 00 00
unable to select DF: File not found
unable to select file 2F00: Unknown error
```

**Comment by dengert** [comment]
Some what helpful. It at lease says it is a "CardOS V5.3, 2014" But that just says what OS it has. It does not say how they initialized the file system and what they have written into the files. 

I don't use opensc-explorer, as I am most interested in non PKCS\#15 cards. But it looks like the find-tag is parsing the contents as ASN.1.   (A handy site to parse ASN.1 is: https://lapo.it/asn1js/)

OpenSC using the `pkcs15-init` would use this: https://github.com/OpenSC/OpenSC/blob/master/src/pkcs15init/pkcs15.profile#L119  They may have used other file_id names and may not follow strict PKCS\#15, as they do not expect anyone else to try and read their cards.    

Its not easy to find a version of PKCS15 on line. But Google for: rsa "pkcs15" or buy a copy of ISO 7816-15.

An early draft: https://www.foo.be/docs/opensst/ref/pkcs/pkcs-15/pkcs-15v11d1.pdf 

A paper on PKXS\#15: https://www.usenix.org/legacy/events/smartcard99/full_papers/nystrom/nystrom.pdf
A page showing how PKCS\#11, PKCS\#15 and OpenSC fit together: https://www.cardlogix.com/glossary/pkcs15-public-key-cryptography-standards/

All RSA PKCS standards: https://en.wikipedia.org/wiki/PKCS

**Comment by frankmorgner** [comment]
@Jakuje was working with Card OS 5.3, maybe he has some ideas...

**Comment by Jakuje** [comment]
I am sorry for a delay, but it took me some time to get back to this. The APDU trace is indeed useful. It says there is really no trap in unexpected APDUs or secure messaging. But unlike with my card, I do not see any directory listing (ODF) under the known path tried by the generic PKCS#15 code.

The keys/certificates are instead in the path `3F 00` -> `20 00`  and `20 01`, which already points to DF `D2 76 00 00 98 C0 00 00` and similar. In the trace, it is visible that the proprietary driver goes this path by default. I did not worked enough with the PKCS#15 cards to be able to put something working together or point you to the right direction what needs to be changed in OpenSC to make this working, but I think we will need some fallback in `sc_pkcs15emu_cardos_init()` when `sc_pkcs15_bind_internal()` fail to read the information from standard path. Probably by manually creating the DF structures to aid the standard PKCS#15 code to find the final keys/certificates. I have the annotated APDUs from the trace if you want to pursuit this challenge of getting your card working with OpenSC. I will probably not have much more time to do that now.

**Comment by jrevillard** [comment]
Thanks a lot @Jakuje for working into this. It would be indeed really interesting to have this card working with OpenSC. This is not really problematic anymore actually because I managed to make it working with the proprietary driver but if you need info from my side to make it working I will help of course.

**Comment by frankmorgner** [comment]
@Jakuje, what's the status of this topic, is there anything to do?

**Comment by Jakuje** [comment]
I did not have any progress here. I think supporting all the cards without directory listing is painful so I would probably close it now.
@jrevillard If you will want to improve opensc with the support for your cards, please open a PR (or new issue if you will need some helps/clarifications).
