### ISSUE TITLE
SmartCard-HSM occasionally fails to generate secp521r1 signature

### ISSUE THREAD

**Issue by rautammi** [OpenSC/OpenSC#2623]
### Problem Description

Signing with an EC key on secp521r1 fails occasionally with CKR_DATA_INVALID.
See https://github.com/OpenSC/OpenSC/issues/2421

Method used in https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-sc-hsm.c#L1051-L1055 does not work, as the case of datalen == 137 could be valid for both, 512 bit and 521 bit curves. 

### Proposed Resolution

Implement what was proposed by @dengert : https://github.com/OpenSC/OpenSC/issues/2421#issuecomment-1170049939

**Comment by frankmorgner** [comment]
@CardContact please have a look
