### ISSUE TITLE
SoftHSM2 drivers

### ISSUE THREAD

**Issue by fliot** [OpenSC/OpenSC#2631]
### More than an issue, a question

Does a SoftHSM2 driver for OpenSC exist ? The same way it's possible to write a new card driver, does it exist a driver to directly use SoftHSM2 ?

If not, is there some conceptual reason why it would not be possible ?

Thanks in advance,

Best regards.

**Comment by Jakuje** [comment]
The SoftHSM is software implementation of PKCS#11 module that stores private keys in files. The OpenSC is middleware to access keys on different real smart cards so it only implements interfaces to these cards one one side and a pkcs11 module on the other side. But it provides also various tools including a `pkcs11-tool`, which can work both with OpenSC pkcs11 as well as with softhsm2 pkcs11 module.

What are you trying to achive?

**Comment by fliot** [comment]
Hi @Jakuje ,

I fully agree with you, interaction with pkcs11-tool and SoftHSM2 works out of the box, and they are two great pieces of software.

My idea about having an OpenSC driver for SoftHSM2 was, beyond an already existing PKCS11 interface,
to benefit of CSP/Minidriver and Mac Tokend, immediate implementation.

Some “OS welcome” virtual smartcard solution.

Thanks in advance.

**Comment by Jakuje** [comment]
In that case, I would suggest you to look into some kind of virtual smart card solution such as we are using in CI, either https://github.com/Jakuje/virt_cacard/ which emulates CAC cards, https://github.com/frankmorgner/vsmartcard/tree/master/virtualsmartcard emulating smart card reader or https://popovec.github.io/OsEID/ emulating MyEID cards.

I am not familiar with the minidriver nor tokend so I can not help much here. But similar topic/questions come from time to time, but I never saw complete working solution. It might also help to raise the question on the mailing list.

**Comment by frankmorgner** [comment]
I fully agree with @Jakuje.

virt_cacard and OsEID are depending on an emulated smart card reader (with an emulated smart card). This however, is a little bit tricky to integrate in macOS. Over in the virtualsmartcard repository, I have [some details on this](https://frankmorgner.github.io/vsmartcard/virtualsmartcard/README.html#configuring-vpcd-on-mac-os-x). You'd also have this problem if using SoftHSM for emulation. Please let us know if you find a more elegant solution of integrating the emulated token (i.e. without depending on the plug-in-event of some physical device).

**Comment by frankmorgner** [comment]
You can find a fully virtual and persistent token here https://github.com/Purebred/CtkProvider
