### ISSUE TITLE
PIN retry counter wrong with `pkcs15-tool --list-pins`, but `sc-hsm-tool` is OK

### ISSUE THREAD

**Issue by ojo2000** [OpenSC/OpenSC#2647]
### Problem Description

Reading user PIN retry counter of a SmartCard-HSM v4.0 card via
```
$ pkcs15-tool --list-pins
```
always gives a wrong return value of `3`, which seems to be the default user PIN retry counter for the card.  However, retrieving user PIN retry counter via
```
$ sc-hsm-tool
```
returns the correct current value.

### Steps to reproduce

1. (optional) Reset user PIN counter by entering the correct PIN:
```
$ pkcs15-tool --use-pinpad --verify-pin
```
2. Enter a wrong PIN using the same command as above.
3. Retrieve user PIN retry counter via `sc-hsm-tool` (_this returns a correct value of `2`_):
```
$ sc-hsm-tool 
Using reader with a card: REINER SCT cyberJack RFID komfort (<ELIDED>) 00 00
Version              : 4.0
Config options       :
  User PIN reset with SO-PIN enabled
SO-PIN tries left    : 15
User PIN tries left  : 2
sc_card_ctl(*, SC_CARDCTL_SC_HSM_IMPORT_DKEK_SHARE, *) failed with Data object not found
DKEK shares          : 0
DKEK key check value : 0000000000000000
```
4. Retrieve user PIN retry counter via `pkcs15-tool` (_this returns a wrong value of `3`_):
```
$ pkcs15-tool --list-pins 
Using reader with a card: REINER SCT cyberJack RFID komfort (<ELIDED>) 00 00
PIN [UserPIN]
	Object Flags   : [0x03], private, modifiable
	Auth ID        : 02
	ID             : 01
	Flags          : [0x812], local, initialized, exchangeRefData
	Length         : min_len:6, max_len:15, stored_len:0
	Pad char       : 0x00
	Reference      : 129 (0x81)
	Type           : ascii-numeric
	Path           : <ELIDED>::
	Tries left     : 3

PIN [SOPIN]
	Object Flags   : [0x01], private
	ID             : 02
	Flags          : [0x9A], local, unblock-disabled, initialized, soPin
	Length         : min_len:16, max_len:16, stored_len:0
	Pad char       : 0x00
	Reference      : 136 (0x88)
	Type           : bcd
	Path           : <ELIDED>::
	Tries left     : 15
```

### System

* Ubuntu 20.04
* `opensc` package version: 0.20.0-3
* card reader: Reiner SCT cyberJack komfort
* driver: `libifd-cyberjack6` 3.99.5final.sp13+dfsg-2build1

AND

* Ubuntu 22.04
* opensc package version: 0.22.0-1ubuntu2
* driver: `libifd-cyberjack6` 3.99.5final.sp14-2

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
This is indeed an issue in sc_pkcs15emu_sc_hsm_init() from pkcs15-sc-hsm.c.

The function initializes the pin_info structure with fixed values rather than reading the current values from the card. That could be ported over from sc-hsm-tool.
