### ISSUE TITLE
French EID (carte nationale d'identité française) OpenSC support

### ISSUE THREAD

**Issue by ffries** [OpenSC/OpenSC#2649]
Dear all,

Is there plans for French EID support in OpenSC?
I recently received the card but of course it is not readable in OpenSC.

```
opensc-tool --atr
Using reader with a card: SCM Microsystems Inc. SPR 532 [Vendor Interface] (21221124201859) 01 00
3b:db:96:ff:80:b1:fe:45:1f:87:00:31:c1:64:09:37:72:13:0f:90:00:f4
```

Are you aware of Spec available somewhere?

I fond this but this is only blabla: 
https://france-identite.gouv.fr/

Kind regards,
Ffries

**Comment by frankmorgner** [comment]
The [ATR identifies the card as the 2021 version](https://smartcard-atr.apdu.fr/parse?ATR=3b%3Adb%3A96%3Aff%3A80%3Ab1%3Afe%3A45%3A1f%3A87%3A00%3A31%3Ac1%3A64%3A09%3A37%3A72%3A13%3A0f%3A90%3A00%3Af4) of a new id card introduced in 2019, which I don't know. Previous french cards were so called european citizen cards. @viktorTarasov has added extensive support in OpenSC for that. Maybe just adding the ATR to OpenSC can be enough to support your type of card.


( @LudovicRousseau the link in the "Smart card ATR parsing" app is broken, could be replaced with https://ants.gouv.fr/nos-missions/les-titres-produits-par-l-ants/les-documents-d-identite/la-puce-de-la-nouvelle-carte-nationale-didentite )

**Comment by LudovicRousseau** [comment]
@frankmorgner I fixed the URL. Thanks.
I guess many other URLs are now also invalid.

**Comment by vjardin** [comment]
Since the IAS-ECC standard is supported by OpenSC, so per
  https://ants.gouv.fr/nos-missions/les-solutions-numeriques/identite-numerique
it should read the new french ID cards, and likely the new driving licenses. Should you have one, you can try.

**Comment by ArnaudPalgen** [comment]
Hi,
I have a card with the same ATR, but it is not readable with OpenSC
Do you have any news on this issue?
Does anyone know how to read the information of this card with opensc ?
