### ISSUE TITLE
KeepassXC needs help how to implement PKCS#11 support

### ISSUE THREAD

**Issue by ffries** [OpenSC/OpenSC#2652]
Hello,

This is a cross-post and I hope this is allowed.

KeepassXC needs helps how to implement PKCS#11 tokens, at least some information.
See: https://github.com/keepassxreboot/keepassxc/issues/255

There is already (?) a bounty if anyone is interested.

Kind regards,
FFries

**Comment by popovec** [comment]
The link points to the password manager software solution. I don't think there is room to use the PKCS11 interface here. Even if yes, it is a solution where sensitive information is not stored on an external secure storage of the token/card type, when it is guaranteed that the private key cannot be exported from the given storage.

It's basically the opposite problem if someone implements the pkcs11 interface into such a password manager. In that case softhsm or opensc could be used as pkcs11 module.

**Comment by mouse07410** [comment]
A trivial idea is to keep the passwords etc. encrypted on computer disk under hybrid encryption together with random symmetric AES-SIV key that wrapped/encrypted via PKCS#11 by the token (e.g, RSA-OAEP). Every new re-encryption can be udder a new freshly-generated symmetric key that would be RSA-wrapped in turn.

**Comment by frankmorgner** [comment]
There are already plugins for Keepass (not XC), if someone wants to implement this, I suggest to look at the existing code. In https://github.com/keepassxreboot/keepassxc/issues/255, I've suggested what I consider to be the [best starting point](https://github.com/keepassxreboot/keepassxc/issues/255#issuecomment-1329095033).

**Comment by frankmorgner** [comment]
Other than that, I think there's not a lot to do here...
