### ISSUE TITLE
PIV external authentication fails with an internal error: Allocated and computed lengths do not match!

### ISSUE THREAD

**Issue by sosthene-nitrokey** [OpenSC/OpenSC#2658]
### Problem Description

Using `PIV_EXT_AUTH_KEY=path/to/key piv-tool -A A:9B:03` fails with internal error : `admin_mode failed -1400`.

On the other hand mutual authentication works with `PIV_EXT_AUTH_KEY=path/to/key piv-tool -A M:9B:03` works.

### Proposed Resolution

Looking at the  logs the issue comes from `piv_general_external_authenticate: Allocated and computed lengths do not match! Expected 12, found: 22`

It appears [this](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L2050) calculation is incorrect. Given that the `0x82` tag is embedded within `0x7C` the length should not be added. Since `tmplen` is already set to `sc_asn1_put_tag(0x82, NULL, cypher_text_len, NULL, 0, NULL)` (see a bit higher), I think the fix is to just use `tmplen = sc_asn1_put_tag(0x7C, NULL, tmplen, NULL, 0, NULL);`

### Steps to reproduce

Run `PIV_EXT_AUTH_KEY=path/to/key piv-tool -A A:9B:03` with `path/to/key` pointing to a 3des key for the piv smartcard being used.

### Logs

```
Outgoing APDU (10 bytes):
00 87 03 9B 04 7C 02 81 00 00 .....|....

P:9508; T:0x140519980476224 10:36:32.049 [piv-tool] reader-pcsc.c:242:pcsc_internal_transmit: called
P:9508; T:0x140519980476224 10:36:32.092 [piv-tool] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (14 bytes):
7C 0A 81 08 07 C1 2A F2 51 35 F0 C1 90 00 |.....*.Q5....

P:9508; T:0x140519980476224 10:36:32.093 [piv-tool] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:9508; T:0x140519980476224 10:36:32.093 [piv-tool] apdu.c:537:sc_transmit: returning with: 0 (Success)
P:9508; T:0x140519980476224 10:36:32.093 [piv-tool] card.c:523:sc_unlock: called
P:9508; T:0x140519980476224 10:36:32.093 [piv-tool] card.c:523:sc_unlock: called
P:9508; T:0x140519980476224 10:36:32.093 [piv-tool] card-piv.c:544:piv_general_io: returning with: 12
P:9508; T:0x140519980476224 10:36:32.094 [piv-tool] card-piv.c:2014:piv_general_external_authenticate: Allocated and computed lengths do not match! Expected 12, found: 22
P:9508; T:0x140519980476224 10:36:32.094 [piv-tool] card.c:523:sc_unlock: called
P:9508; T:0x140519980476224 10:36:32.094 [piv-tool] card-piv.c:2045:piv_general_external_authenticate: returning with: -1400 (Internal error)
P:9508; T:0x140519980476224 10:36:32.094 [piv-tool] card.c:1065:sc_card_ctl: returning with: -1400 (Internal error)
 admin_mode failed -1400
 ```

**Comment by dengert** [comment]
Yes its a bug See #2659 which uses your suggested fix and tested using NIST PIV card with gdb.
