### ISSUE TITLE
npa-tool does not read dg's

### ISSUE THREAD

**Issue by pc-bastler** [OpenSC/OpenSC#2667]
### Problem Description

I am trying to read data from my german NPA using the npa-tool.exe
I was able to verify the validity with the "--verify-validity=20221215" parameter.

When trying to read other information, e.g. "npa-tool.exe --read-dg5 -p" the PIN-entry dialog pops up, I enter my PIN, then the following is displayed: 

Established PACE channel with eID PIN.
Could not read DG 05 Family Names (File not found) 

I doublecheck that I entered the correct PIN for my NPA (using the Ausweis2-App). i also tried other dg's then #5.

I am using the latest version of OpenSC (as of 12/15/22). I am using a ReinerSCT komfort Card Reader with latest soft- and firmware.
I am running Windows 11 22H2, latest patches.

**Comment by frankmorgner** [comment]
Data groups are held in the eID application, which additionally requires authentication with a terminal certificate that has appropriate access rights. This is done in AusweisApp2 in the background. With npa-tool, you need to have the terminal credentials available locally (which is not typically the case). For the German ID card, this functionality will not be available, typically.
