### ISSUE TITLE
Unable to wrap a key with sc-hsm-tool: failed with Data object not found

### ISSUE THREAD

**Issue by rvdgracht** [OpenSC/OpenSC#2685]
### Problem Description

I'm trying to use the sc-hsm-tool to wrap a freshly generated key but it's refusing with the error:
`sc_card_ctl(*, SC_CARDCTL_SC_HSM_WRAP_KEY, *) failed with Data object not found`

### Steps to reproduce

1) Generate a new key
`pkcs11-tool --slot 0 -l --keypairgen --id 3 --label "testkey-ec" --key-type EC:prime256v1 --pin 000000`

2) Try to wrap the key
`sc-hsm-tool --reader 0 --wrap-key wrapped.bin --key-reference 3 --pin 000000`

I tried to do this for a rsa:4096 key as well with the same result.

### My HSM

I use a Nitrokey HSM 2 which has been initialized with 2 DKEK shares.
I replaced some numbers with 'X' below:
```
sc-hsm-tool --reader 0
Version              : 3.3
Config options       :
  User PIN reset with SO-PIN enabled
SO-PIN tries left    : 15
User PIN tries left  : 3
DKEK shares          : 2
DKEK key check value : XXXXXXXXXXXXXXXX
```
### Logs

I used opensc 0.23.0. I was unable to test with the latest development version <sorry>.

This is the output of the sc-hsm-tool wrap command with OPENSC_DEBUG=9
[opensc-wrap-key.log](https://github.com/OpenSC/OpenSC/files/10507750/opensc-wrap-key.log)

**Comment by CardContact** [comment]
You need to specify the key-reference, not the key id.

The key reference is the internal unique identifier of the key, while the key
id is the PKCS#11 CKA_ID value.

The sc-hsm-tool is a low-level tool that works at the APDU level, so any PKCS11 abstraction
has no relevance. You can determine the key reference using

    $ pkcs15-tool -D
    PKCS#15 Card [SmartCard-HSM]:
            Version        : 0
            Serial number  : DECC0900024
            Manufacturer ID: www.CardContact.de
            Flags          : 
    ...
    
    Private EC Key [label]
            Object Flags   : [0x01], private
            Usage          : [0x104], sign, derive
            Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
            Algo_refs      : 0
            FieldLength    : 384
            Key ref        : 1 (0x01)
            Native         : yes
            Auth ID        : 01
            ID             : 01
            MD:guid        : bd472e8e-9b66-a736-3f40-f3bafe5f3422

**Comment by rvdgracht** [comment]
Facepalm!
I used this command successfully in the past. I think the ID's must have been matching back then. That threw me off.
Thank you for your rapid responce.
Closing this (non) issue.
