### ISSUE TITLE
test-isoapplet.sh still failing

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2691]
### Problem Description
test-isoapplet-v0 is still failing.

See https://github.com/dengert/OpenSC/actions/runs/4058993046/jobs/6986720356

This last attempt to fix test-isoapplet.sh  https://github.com/OpenSC/OpenSC/pull/2053/commits/45e7589dd4d8266ab380511cbdec51d71f6ea3a2
which sets the directory path to the same. 
This was detected by cloning the repository https://github.com/philipWendland/IsoApplet
and checking out the three branches. 

So now it is failing later in the process. 

Someone else need to look at this closer.

**Comment by dengert** [comment]
Sorry, about blank Problem Description. It has been edited.

**Comment by swissbit-csteuer** [comment]
PR #2688 fixes the problem but it's not merged yet.

**Comment by Jakuje** [comment]
It passes now with master after merging #2688. Closing
