### ISSUE TITLE
pkcs11-tool --read-object with --object-index

### ISSUE THREAD

**Issue by hypp** [OpenSC/OpenSC#2697]
### Problem Description

I have tried using pkcs11-tool --read-object with --object-index, but it seems to me that --object-index is ignored.

In pkcs11-tool.c, in the function 
`static int read_object(CK_SESSION_HANDLE session)`
there is a call to find_object_with_attributes:
`rv = find_object_with_attributes(session, &obj, attrs, nn_attrs, 0);`

The last parameter in the function call is the object index, which is hardcoded to 0.

### Proposed Resolution

Use opt_object_index in the function call:
`rv = find_object_with_attributes(session, &obj, attrs, nn_attrs, opt_object_index);`

**Comment by frankmorgner** [comment]
currently the `opt_object_index` seems to be only used in `delete_object()`. As you pointed out, this should be added to read_object(). Please open a pull request with this change, thank you

**Comment by hypp** [comment]
I would be happy to, but I do not know how to open a pull request. Could you please provide instructions?

**Comment by bharsaklemukesh975** [comment]
Hello @hypp,

Please find below the steps needed to open PR.

- Fork the project and clone from the forked version
- Make a branch and commit changes
- Push changes to your fork
- Open a pull request: When you go to the GitHub project page, you will have the option to create PR.

Also check [OpenSC](https://github.com/OpenSC/OpenSC)/CONTRIBUTING.md

Let me know if you have more questions.

Thank you!

**Comment by hypp** [comment]
I have followed your instructions and opened a PR. I hope I got it right.
