### ISSUE TITLE
Add OpenSC to the winget package repository

### ISSUE THREAD

**Issue by RufusJWB** [OpenSC/OpenSC#2699]
### Problem Description

No OpenSC package is available in the [winget package repository](https://github.com/microsoft/winget-pkgs)

### Proposed Resolution

Add a step to create and publish a winget package to the [CI/CD pipeline](https://github.com/microsoft/winget-create/blob/main/README.md) which builds the OpenSC releases

### Steps to reproduce

```
> winget search opensc
Name     Id                Version Source
------------------------------------------
OpenSCAD OpenSCAD.OpenSCAD 2021.01 winget

```
### Logs

n/a

**Comment by frankmorgner** [comment]
Not sure what obligations are present in the COC and CLA from MS, but right now I don't have time to look into this, let alone that manifest and automation needs to be managed. With the lack of man power and user need, I don't see an OpenSC winget package soon.

Do you want to provide the initial work or become the package manager?

**Comment by RufusJWB** [comment]
> Do you want to provide the initial work or become the package manager?

Possibly I could try to but I'm currently struggling how you build the windows binary packages. I must be blind but I can't find a GitHub action for them. I only see OsX and Linux-

**Comment by frankmorgner** [comment]
look into .appveyor.yml

**Comment by RufusJWB** [comment]
Doesn't seem to be a quick-win. I'll close it for now
