### ISSUE TITLE
Wrong (legacy) IsoApplet version?

### ISSUE THREAD

**Issue by llogar** [OpenSC/OpenSC#2704]
Shouldn't 
https://github.com/OpenSC/OpenSC/blob/b53fc5cdb326d2a3f101980be2a0ae3537617037/src/libopensc/card-isoApplet.c#L36
be defined as

`#define ISOAPPLET_VERSION_V0 0x0006`

as the version in `IsoApplet.java` is/was defined as
```
/* API Version */
public static final byte API_VERSION_MAJOR = (byte) 0x00;
public static final byte API_VERSION_MINOR = (byte) 0x06;
```

**Comment by Jakuje** [comment]
thanks. I missed that @swissbit-csteuer, can you have a look?

**Comment by swissbit-csteuer** [comment]
@llogar is right, it should be `0x0006` and not `0x0060`. I created #2710 to address this (+ adding a missing whitespace in the log message :wink:)
