### ISSUE TITLE
C_Initialize called twice causes deadlock in futex_wait 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2708]
This is the same issue as https://github.com/latchset/pkcs11-provider/issues/187

**Describe the bug**
When an application that calls `C_Initialize` and also use OpenSSL where `openssl.cnf`  defines the `pkcs11-provider` the provider is initialized and calls C_Initialize a second time.

The `pkcs11-tool` loads  module `opensc-pkcs11.so` which uses `libopensc.so.8` which uses `libcrypto.so.3` 
which does 
The provider then load module `ossl-modules/pkcs11.so` that loads module `opensc-pkcs11.so`

If the deadlock did not occur this could lead to a loop. 

**To Reproduce**

`gdb --args ./pkcs11-tool -O` 

**Expected behavior**
`pkcs11-provider` does not initialize unless specifically requested, or is able to use existing PKCS11 initialized by application.  

**Operating environment (please complete the following information):**
 - OS: Xubuntu 22.04 as (VirtualBox guest with Windows 11 host)
 - Version 22.04
 - OpenSSL-3.0.8
 - OpenSC  form github master
 - pkcs11-provider from github main yesterday.

**Token and application used (please complete the following information):**
 - Device: Yubikey 5 NFC (PIV) 
 - PKCS11 Driver version: From OpenSC 
 - Application pkcs11-tool
 - Version OpenSC master 

**Additional context**

[pissue-opensc-debug.txt](https://github.com/latchset/pkcs11-provider/files/10698208/pissue-opensc-debug.txt)
Note that a few lines may be missing at end. 

[pissue-opensc-gdb.txt](https://github.com/latchset/pkcs11-provider/files/10698256/pissue-opensc-gdb.txt)

[pissue-openssl.cnf-diff.txt](https://github.com/latchset/pkcs11-provider/files/10698328/pissue-openssl.cnf-diff.txt)

Possible circumvention: only use openssl.cnf with provider when use with OpenSSL untilities.

**Comment by dengert** [comment]
I am posting it here too because OpenSSL 3.0  does not appear to use the env OPENSSL_CONFIG=  so if the default openssl.cnf has a provider it may be used.

The pkcs11-provider in development ends up loading the opensc-pkcs11 module. which has also been loaded by pkcs11-tool. Any pkcs11 application that loads opensc-pkcs11 module will have the same problem.

**Comment by Jakuje** [comment]
@dengert what is the status of this issue? Wasn't it fixed with #2711?

**Comment by dengert** [comment]
Yes it is fixed, by a combination of #2711 and changes in the provider to not load any PKCS11 modules during its initialization, but only when PKCS11 is requested.
