### ISSUE TITLE
Want to add support for smart card JDKey okPass

### ISSUE THREAD

**Issue by PIKACHUIM** [OpenSC/OpenSC#2709]
### Problem Description
JDKey okPass is a cheap USB smart card device that can store certificates and provide authentication.
Can OpenSC or OpenCT provide CCID or minidriver support, or can it provide the following steps? Thank you very much
Its SDK has been uploaded to [UKey-API](https://github.com/PIKACHUIM/UKey-API/tree/main/SDK/JDKey%20okPass)

**Comment by frankmorgner** [comment]
If you're planning to make a contribution to the project, we'd love to add a new card to OpenSC. We would be happy to get you going and to comment on your code. However, please have in mind that in lack of hardware, documentation and manpower, we can't do this on our own.
The project you've linked doesn't contain any documentation about the token and only includes some binaries. with that it would be quite hard to implement a proper integration in OpenSC

**Comment by PIKACHUIM** [comment]
Thank you for your kind reply and your willingness to provide support. I added the sample code and header file under the PKI folder. In addition, I am asking about the relevant information of this smart card. If there is any document, it will be supplemented. In addition, if you need hardware equipment to develop, I can send you some hardware equipment for free. If there is any need for help or provision, please reply. Thanks again!

**Comment by PIKACHUIM** [comment]
The official website of the device is located at http://www.jdkey.cn/product.php?id=24
Here, the device provides:
1. Standard CSP interface is provided
2. Standard PKCS # 11 interface is provided
I would like to ask if the standard CSP interface means that minidriver is officially provided?

**Comment by PIKACHUIM** [comment]
Thank you. I found that this hardware has officially supported minidriver and seems to be able to work normally. Now there is no need to support this hardware. Thank you very much!
If there is any plan to support it, I can still provide support. Here are some officially provided tools, including minidriver and registration program.

[okPass_Tools_Win32.zip](https://github.com/OpenSC/OpenSC/files/10927108/okPass_Tools_Win32.zip)

**Comment by PIKACHUIM** [comment]
However, EFS can NOT be used: 
_The EFS Rekey wizard encountered an error and cannot continue: the system cannot find the specified file.
Please contact your system administrator for assistance._
