### ISSUE TITLE
CardOS5 Card driver

### ISSUE THREAD

**Issue by mostafabarmshory** [OpenSC/OpenSC#271]
Dear friends,

I`m writing to inform you about my problem. I`m trying to personalize the CardOS5, but I face with an error. The ATR analysis of my card is as follow:

3B D2 18 00 81 31 FE 58 C9 01 14
        Atos CardOS5 (PKI)
        http://atos.net/NR/rdonlyres/17C7BDD0-225B-4A58-B9A4-438EA3F3238A/0/74743_20120830_160149_cardos_v5_0__datenblatt_en.pdf

But, the pkcs15-init does not known the card type. Would you help me please?

best regards.

**Comment by frankmorgner** [comment]
We would be happy to include Card OS 5 support. With #283 on hold we are still waiting for code contributions. Please make a PR if you have an alternative implementation (or revive #283).
