### ISSUE TITLE
OpenPGP: Signing with the encryption key

### ISSUE THREAD

**Issue by ebourg** [OpenSC/OpenSC#2713]
`pgp_compute_signature` is able to sign with the signature or the authentication, but not with the encryption key. However a call to MANAGE SECURITY ENVIRONMENT can assign the encryption key to the INTERNAL AUTHENTICATE operation, so technically `pgp_compute_signature` could use the encryption key. Has this been considered? When the card is accessed through PKCS#11 this would turn the card into a 3 slot keystore.

**Comment by martinpaljak** [comment]
Which pgp card implementation is it? I'd say this is oversight/issue with the implementation, one could argue that this can lead to unexpected/unwanted private key operations...

**Comment by ebourg** [comment]
MANAGE SECURITY ENVIRONMENT support was added to the OpenPGP specification 3.3 as an optional feature. It's supported by the Nitrokey 3.

**Comment by frankmorgner** [comment]
What problem are you trying to solve? We have some support for features from PGP 3+. In particular, https://github.com/OpenSC/OpenSC/pull/2103 allows storing 3 certificates on the card, which should allow Windows Authentication.

**Comment by ebourg** [comment]
@frankmorgner I'd like to be able to use all 3 keys for signing through PKCS#11. So far the `pgp_compute_signature`function in `card-openpgp.c` only support the signature and the authentication keys:

https://github.com/OpenSC/OpenSC/blob/6e2ea362949956dfb81cb78f595975889fcad6cb/src/libopensc/card-openpgp.c#L2283

**Comment by frankmorgner** [comment]
I don't believe this fulfills any meaningful purpose other than satisfying curiosity. As stated above, since this is likely unwanted, I don't believe we will adopt this in master. However, feel free to implement this in one of your branches of OpenSC.

**Comment by ebourg** [comment]
Well, if the OpenPGP card specification allows one to use the ENC and AUT keys interchangeably, I'd argue they should be handled similarly.

A not so absurd use case is to be able to have multiple signing keys for different email addresses on the same card. That's the reason why the upcoming version 4 of the spec is going to extend the maximum number of keys to 31.
