### ISSUE TITLE
minidriver with ECC signing failing

### ISSUE THREAD

**Issue by llogar** [OpenSC/OpenSC#2718]
### Problem Description
As already mentioned in https://github.com/OpenSC/OpenSC/pull/2646#issuecomment-1325438662, padding info is added in `CardSignData()` even when non-RSA keys are being used, which makes no sense.

As a consequence signing (when using minidriver and EC keys) fails 
### Proposed Resolution
I guess the padding info should be included only if RSA keys are being used, surrounding the padding code in 
`sc_pkcs15_compute_signature()` with
```
if (pkey->type == SC_PKCS15_TYPE_PRKEY_RSA) {
...
}
```
### Steps to reproduce
Try to sign data with EC keys using minidriver...
### Logs
```
P:20188; T:12200 2023-02-23 09:27:00.202 [cardmod] CardSignData dwVersion=2, bContainerIndex=0, dwKeySpec=7, dwSigningFlags=0x00000000, aiHashAlg=0x00000000
...
P:20188; T:12200 2023-02-23 09:27:00.214 [cardmod] CARD_PADDING_INFO_PRESENT not set
...
P:20188; T:12200 2023-02-23 09:27:00.227 [cardmod] pkcs15-sec.c:607:sc_pkcs15_compute_signature: called
P:20188; T:12200 2023-02-23 09:27:00.230 [cardmod] pkcs15-sec.c:660:sc_pkcs15_compute_signature: supported algorithm flags 0x100100, private key usage 0x104
P:20188; T:12200 2023-02-23 09:27:00.232 [cardmod] pkcs15-sec.c:718:sc_pkcs15_compute_signature: ECDSA using SC_ALGORITHM_ECDSA_RAW flags before 0x00000002
P:20188; T:12200 2023-02-23 09:27:00.235 [cardmod] padding.c:618:sc_get_encoding_flags: called
P:20188; T:12200 2023-02-23 09:27:00.238 [cardmod] padding.c:622:sc_get_encoding_flags: iFlags 0x100002, card capabilities 0x100100
P:20188; T:12200 2023-02-23 09:27:00.240 [cardmod] padding.c:678:sc_get_encoding_flags: pad flags 0x1, secure algorithm flags 0x102
P:20188; T:12200 2023-02-23 09:27:00.243 [cardmod] padding.c:679:sc_get_encoding_flags: returning with: 0 (Success)
P:20188; T:12200 2023-02-23 09:27:00.245 [cardmod] pkcs15-sec.c:731:sc_pkcs15_compute_signature: DEE flags:0x00100002 alg_info->flags:0x00100100 pad:0x00000001 sec:0x00000102
P:20188; T:12200 2023-02-23 09:27:00.248 [cardmod] padding.c:544:sc_pkcs1_encode: called
P:20188; T:12200 2023-02-23 09:27:00.250 [cardmod] padding.c:550:sc_pkcs1_encode: hash algorithm 0x0, pad algorithm 0x1
P:20188; T:12200 2023-02-23 09:27:00.253 [cardmod] padding.c:556:sc_pkcs1_encode: Unable to add digest info 0x0
P:20188; T:12200 2023-02-23 09:27:00.256 [cardmod] padding.c:557:sc_pkcs1_encode: returning with: -1400 (Internal error)
P:20188; T:12200 2023-02-23 09:27:00.258 [cardmod] pkcs15-sec.c:741:sc_pkcs15_compute_signature: Unable to add padding: -1400 (Internal error)
P:20188; T:12200 2023-02-23 09:27:00.260 [cardmod] pkcs15-sec.c:784:sc_pkcs15_compute_signature: returning with: -1400 (Internal error)
P:20188; T:12200 2023-02-23 09:27:00.263 [cardmod] sc_pkcs15_compute_signature return -1400
P:20188; T:12200 2023-02-23 09:27:00.266 [cardmod] sc_pkcs15_compute_signature error Internal error

```

**Comment by dengert** [comment]
Does this fail when using pkcs15-tool or pkcs11-tool to do a sign? Or just the minidriver. 

The SC_INTERNAL_ERROR comes from https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/padding.c#L330
 
`sc_pkcs1_add_digest_info_prefix(hash_algo, in, in_len, out, &tmp_len);"

The problem maybe in the in_len, out or tmp_len where it tests if they match. 
 a null hash should be acceptable: https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/padding.c#L78


Are you running with 0.23.0?  As suggested in https://github.com/OpenSC/OpenSC/pull/2646#issuecomment-1325216402
where your log at https://github.com/OpenSC/OpenSC/pull/2646#issuecomment-1325438662 appears to work.
and shows: 
```
P:8092; T:4076 2022-11-23 11:08:01.861 [cardmod] CARD_PADDING_INFO_PRESENT not set
P:8092; T:4076 2022-11-23 11:08:01.861 [cardmod] pInfo->cbSignedData = 96
P:8092; T:4076 2022-11-23 11:08:01.861 [cardmod] lg = 96
P:8092; T:4076 2022-11-23 11:08:01.861 [cardmod] Data to sign: 
```

Where as the log in this issue has ...

Can you compare these a little closer? I see the "private key uasge" is different which should not make a difference

Can you also try:
"In https://github.com/llogar/OpenSC/blob/eOI/src/libopensc/card-eoi.c#L264-L269
You may need to pass `ext_flags = SC_ALGORITHM_EXT_EC_NAMEDCURVE | SC_ALGORITHM_EXT_EC_UNCOMPRESES;` It looks like you are passing 0; They are used in PKCS11."

Look at card-piv that does set 'ect_flags`.

**Comment by dengert** [comment]
Also note SC_ALGORITHM_RSA_HASH_NONE and SC_ALGORITHM_ECDSA_HASH_NONE are the same 0x00000100
`#define SC_ALGORITHM_ECDSA_HASH_NONE            SC_ALGORITHM_RSA_HASH_NONE`

`padding.c` can add the `digest info` if needed, which it can do for ECDSA or RSA.

**Comment by dengert** [comment]
Have a look at #2722  which has the PIN ROLE_EVERYONE commit and a commit for the problem with padding.c

Flags SC_ALGORITHM_RSA_HASH_NONE and SC_ALGORITHM_ECDSA_HASH_NONE
use the same definition. But SC_ALGORITHM_RSA_HASH_NONE is over used.

The test in padding was changed  This gets around the problem. As with EC keys, the test will now fail. 

I have been testing with a PIV card, with all EC keys. Certutil  at times is rather dumb as it tries to test encryption with a EC key.
