### ISSUE TITLE
opensc v. 0.19 verification function avalibility

### ISSUE THREAD

**Issue by mshta** [OpenSC/OpenSC#2723]
### Problem Description

Hello, is digital signature verification function avaliable in ```pkcs11-tool``` from package ```opensc-pkcs11``` v. 0.19.0-1?

**Comment by popovec** [comment]
opensc 0.19.0, pkcs11-tool -M (MyEID/OsEID card), there is several mechanisms that provide verification (for RSA only):

 RSA-X-509, keySize={512,2048}, hw, decrypt, sign, verify
 RSA-PKCS, keySize={512,2048}, hw, decrypt, sign, verify
 SHA1-RSA-PKCS, keySize={512,2048}, sign, verify

During 2021 many fixes related to EC operation were added including EC signature verification/fixes.
Version 0.19 is quite old, I recommend using at least version 0.22.

here is a list of all operations that support "signature verification" for the MyEID/OsEID card (opensc 0.23):

  ECDSA, keySize={192,521}, hw, sign, verify, EC OID, EC uncompressed
  ECDSA-SHA1, keySize={192,521}, sign, verify
  ECDSA-SHA224, keySize={192,521}, sign, verify
  ECDSA-SHA256, keySize={192,521}, sign, verify
  ECDSA-SHA384, keySize={192,521}, sign, verify
  ECDSA-SHA512, keySize={192,521}, sign, verify
  RSA-X-509, keySize={512,2048}, hw, decrypt, sign, verify, wrap, unwrap
  RSA-PKCS, keySize={512,2048}, hw, decrypt, sign, verify, wrap, unwrap
  SHA1-RSA-PKCS, keySize={512,2048}, sign, verify
  SHA224-RSA-PKCS, keySize={512,2048}, sign, verify
  SHA256-RSA-PKCS, keySize={512,2048}, sign, verify
  SHA384-RSA-PKCS, keySize={512,2048}, sign, verify
  SHA512-RSA-PKCS, keySize={512,2048}, sign, verify
  MD5-RSA-PKCS, keySize={512,2048}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={512,2048}, sign, verify
  RSA-PKCS-PSS, keySize={512,2048}, hw, sign, verify, wrap, unwrap
  SHA1-RSA-PKCS-PSS, keySize={512,2048}, sign, verify
  SHA224-RSA-PKCS-PSS, keySize={512,2048}, sign, verify
  SHA256-RSA-PKCS-PSS, keySize={512,2048}, sign, verify
  SHA384-RSA-PKCS-PSS, keySize={512,2048}, sign, verify
  SHA512-RSA-PKCS-PSS, keySize={512,2048}, sign, verify


The list may differ for other cards.

**Comment by mshta** [comment]
Hello, Peter, thanks you very much for your answer.

Application ```pkcs11-tool``` from package ```opensc-pkcs11``` v. 0.21.0-1 have option ```--verify```, but application ```pkcs11-tool``` from package ```opensc-pkcs11``` v. 0.19.0-1 don't have this option or something similar. Is it means that ```pkcs11-tool``` v. 0.19.0-1 have no functionality to do digital signature verification?

**Comment by popovec** [comment]
opensc version 0.19 was released Thu Sep 13 13:47:21 2018 +0200

support for signature verification in pkcs11-tool was added as of September 30, 21:23:27 2018 +0200

Since the verification operation is an operation with a public key, it can be replaced by reading the public key from the card and performing the signature verification operation via openssl.

**Comment by mshta** [comment]
Peter (@popovec), thanks you very much!
