### ISSUE TITLE
NSS does not like colons in token label

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#2725]
### Problem Description

I was made aware of the following NSS bug https://bugzilla.mozilla.org/show_bug.cgi?id=1817553 with new CAC cards containing colons in CN of certificates, which is being propagated to the token labels.

From there the NSS composes the certificate "nicknames" in format of "token label":"certificate label" and depends on the "token label" not having any colons in it.

### Proposed Resolution
We are discussing some workarounds in NSS, but other option might be to provide a bit more flexibility using configuration options (on NSS quirks similar to #2681) to either replace colons from CN or use more generic "Common Access Card" or something.

### Steps to reproduce
* Have a card with token name containing colon
* Try to add it and use it from Firefox/Thunderbird or any NSS application

### Logs

no logs available

**Comment by mouse07410** [comment]
Replacing colons with e.g. "_" seems the best. Using more generic "CAC" instead seems acceptable, though not as good.
