### ISSUE TITLE
npa-tool fails during Terminal Authentication with Invalid ASN.1 object

### ISSUE THREAD

**Issue by marcoh00** [OpenSC/OpenSC#2726]
### Problem Description

npa-tool fails during Terminal Authentication with `Invalid ASN.1 object`:

```
P:11725; T:0x140341712424576 12:43:08.173 [npa-tool] sm-eac.c:251:encode_mse_cdata: Error encoding MSE:Set AT APDU data: -1401 (Invalid ASN.1 object)
P:11725; T:0x140341712424576 12:43:08.173 [npa-tool] sm-eac.c:1206:perform_terminal_authentication: Could not select protocol properties (MSE: Set AT failed).
```

### Proposed Resolution

The terminal authentication function performs the MSE:Set AT step only specifying a "Reference of a public key" and no "Cryptographic mechanism reference", which is correct behavior according to TR-03110 Part 3. However, the corresponding `capdu_eac_mse` struct does not specify the `SC_ASN1_OPTIONAL` flag for the latter.

I will open a PR in a few moments that adds the OPTIONAL flag.

### Steps to reproduce

Should be reproducible using any nPA or PersoSim.

**Comment by frankmorgner** [comment]
Regression since d9a426752. Also affects changing the PIN
