### ISSUE TITLE
ePass3000 MiniDriver doesn't seem to support SHA256

### ISSUE THREAD

**Issue by PIKACHUIM** [OpenSC/OpenSC#2728]
# ePass3000 MiniDriver doesn't seem to support SHA256
I imported the sha256 certificate on the epass 3000 device, and tried to use the minidriver to sign the sha256 certificate, but the signature failed. The digest algorithm is not supported. However, I learned from the query that epass3000's hardware supports sha256.
Please tell me how to ensure that I use the minidriver provided by opensc for signature, and how to find the reason for this problem. Thank you!

**Comment by dengert** [comment]
@xaqfan @FeitianSmartcardReader  can you comment on this too?

What version of Windows?
What version of OpenSC?

What command failed? 

> I imported the sha256 certificate on the epass 3000 device

Did you also import the matching private key? 



> However, I learned from the query that epass3000's hardware supports sha256.

The hardware may support doing the digest on the card.  But this may be card  can only do the final round of the digest on the card. This then requires the all other rounds to be done in software.  OpenSC is using OpenSSL to do digest in software for RSA.

> Please tell me how to ensure that I use the minidriver provided by opensc for signature, and how to find the reason for this problem. Thank you!

Using regedit, look for: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\ePass2003 and
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Cryptography\Calais\SmartCards\ePass2003

If you are using ECC keys card will do: 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-epass2003.c#L2167-L2210
which ends up calling https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-epass2003.c#L2786-L2795
The REVERSE_ORDER4 looks strange as input and output are `size_t` but in next line it is copying 4 bytes. So may only work on some machines.

**Comment by dengert** [comment]
Please disregard most of the last comment.  It was based on the epass2003, not the epass3000 which is support by   `card-entersafe.c`

**Comment by PIKACHUIM** [comment]
Thank you for your reply. I‘m using Windows 11 22H2，OpenSC 0.23.0 x64.

> What command failed?

I used a code signing software to try to sign the code. The software uses the storage area of the system certificate to sign the code. When the signature type is sha1, it can be used normally, but when the signature type is sha256, it prompts that the signature cannot be performed. Unable to see the log because it is not using my own code.

> Did you also import the matching private key?

Of course, as mentioned before, sha1 works normally.

> The hardware may support doing the digest on the card. But this may be card can only do the final round of the digest on the card. This then requires the all other rounds to be done in software. OpenSC is using OpenSSL to do digest in software for RSA.

Thank you. Is there any way to debug or see the error log? I'm not sure I'm using the minidriver provided by opensc.

**Comment by frankmorgner** [comment]
Please create a debug log of your problem as described in the [comments of our issue template](https://raw.githubusercontent.com/OpenSC/OpenSC/master/.github/ISSUE_TEMPLATE.md). You may also want to look at the hints on [how to write a good bug report](https://github.com/OpenSC/OpenSC/wiki/How-to-write-a-good-bug-report).

**Comment by PIKACHUIM** [comment]
Thank you, I have been quite busy lately. When I have time to test and obtain logs, I will create a log report
Additionally.

 I have learned that epass 3000 hardware does not support SHA256, but miniriver theoretically allows for the use of sha256 for summarization, followed by encryption using the private key of the token, thus enabling the implementation of sha256 signature summarization
