### ISSUE TITLE
Epass2003 incorrect CMAC subkey

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#2734]
### Problem Description
For some EPASS2003 tokens, AES CMAC is used to ensure the authenticity of secure messages. This code should probably correspond to the specification described in RFC4493. This specification describes the subkey derivation procedure.
`````
K1 is derived through the following operation:
If the most significant bit of L is equal to 0, K1 is the left-shift of L by 1 bit.

Otherwise, K1 is the exclusive-OR of const_Rb and the left-shift of L  by 1 bit.
`````
The "C" code used in the opensc driver implements this operation with the following sequence of commands:

`````
	check = out[0];
	enc1 = BN_new();
	lenc1 = BN_new();
	BN_bin2bn(out,16,enc1);
	BN_lshift1(lenc1,enc1);
	BN_bn2bin(lenc1,k1Bin);
	if(check > 0x80){
		offset = 1; 
		k1Bin[15+offset] ^= 0x87; 
	}
`````
I assume that there was a mistake in writing, where `if(check & 0x80)` should have been used instead of `if(check > 0x80)`. Both subkeys (k1,k2) are affected by this error. The error does not always occur. The CMAC calculation is incorrect only for some keys.

I can't say for sure that the code written like this wasn't just a workaround to the epass2003 token error. This CMAC calculation is used here only for a special APDU (00 82 01 00) where a different error is corrected (no initialization vector is used for MAC calculation for this APDU).

Code was introduced in commit 622e6e2469c67b4fdbbf7c9268bf865e77e61f85, @xaqfan as the author of this code, can you comment on it?

**Comment by Jakuje** [comment]
@FeitianSmartcardReader  can probably comment on this too. I unfortunately dont have this token to check.

**Comment by FeitianSmartcardReader** [comment]
@Jakuje let me forward to our team, and would you please send email to me with your address? I will ship few samples to you too. hongbin@ftsafe.com

**Comment by xaqfan** [comment]
I don't have the authority to merge. 
Of course,  with another question, I just submitted the request.
thanks

**Comment by xaqfan** [comment]
Sorry for the late reply.

**Comment by Jakuje** [comment]
Should be fixed with  #2759

**Comment by popovec** [comment]
I agree, using #2759 will fix this issue. Well thank you.

**Comment by popovec** [comment]
I am closing this issue. #2759 is already merged in master.
