### ISSUE TITLE
Integrate valgrind into CI tests

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2736]
### Problem Description

valgrind can exit with a non-zero exitcode for easy integration into CI scripts by using `--error-exitcode=1`. This would allow automatically detecting race conditions and memory leaks with something like this:
```
valgrind --error-exitcode=1 --leak-check=full pkcs11-tool --test --login --pin=123456
valgrind --error-exitcode=1 --tool=helgrind --error-limit=no --free-is-write=yes pkcs11-tool --use-locking --pin=123456 --test-threads LT --test-threads LT  --test-threads LT  --test-threads LT  --test-threads LT  --test-threads LT
```

### Proposed Resolution

- **Modify and integrate `runtest.sh`?** `src/tests/p11test/runtest.sh` already uses some `VALGRIND` environment variable if it is set, when running pkcs11-tool with tests. However, that script does not seem to be integrated into CI.
- **Modify `test-{isoapplet,openpgp,piv}.sh`?** Some Test scripts in `.github`  already use `pkcs11-tool -l -t -p 123456`, which could be run with valgrind as well.

@Jakuje , do you want to have a look at this?

**Comment by Jakuje** [comment]
> src/tests/p11test/runtest.sh already uses some VALGRIND environment variable if it is set, when running pkcs11-tool with tests. However, that script does not seem to be integrated into CI.

Correct. I used that script mostly with valgrind to debug issues during development and testing the test itself against different pkcs11 implementations.

**Comment by Jakuje** [comment]
WIP branch is here: https://github.com/Jakuje/OpenSC/commits/valgrind-ci with some vangrind issues to either fix/investigate/supress

**Comment by frankmorgner** [comment]
Thanks, looks promising. 40 bytes definitely lost when accessing PC/SC comes from a problem within PCSC-Lite - I see the same problem on my machine, but did not have the time to investigate this (it may be solved with a newer version of PCSC-Lite)... The rest (possibly lost bytes) can be ignored, I think.

**Comment by frankmorgner** [comment]
Adding `--keep-debuginfo=yes` to valgrind and installing `libpcsclite1-dbgsym` correctly prints the problem

**Comment by frankmorgner** [comment]
The problem in PC/SC is solved with https://salsa.debian.org/rousseau/PCSC/-/issues/1 which is integrated since pcsc-lite 1.9.8

**Comment by frankmorgner** [comment]
We can use LD_PRELPOAD to keep libpcsclite loaded while OpenSC exists (which hides the PC/SC memory leak):
```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpcsclite.so.1 valgrind --leak-check=full --keep-debuginfo=yes opensc-tool -n
```

**Comment by frankmorgner** [comment]
Great, it looks very good!

Ideally, I'd allso add a new test which checks the threading:
```
valgrind --error-exitcode=1 --tool=helgrind --error-limit=no --free-is-write=yes pkcs11-tool --use-locking --pin=123456 --test-threads LT --test-threads LT  --test-threads LT  --test-threads LT  --test-threads LT  --test-threads LT
```
The above test works for any card that is capable of performing `pkcs11-tool --test --login --pin=123456`. Do you know where to put that additional test?

**Comment by Jakuje** [comment]
> The above test works for any card that is capable of performing `pkcs11-tool --test --login --pin=123456`. Do you know where to put that additional test?

I would say for now into the `.github/test*.sh` scripts if the emulated card supports running tests (there are some without objects). 

Looks like my PR will still need some love as the supressions do not look like working good enough.
