### ISSUE TITLE
./.github/setup-java.sh fails on MacOS

### ISSUE THREAD

**Issue by bharsaklemukesh975** [OpenSC/OpenSC#2751]
### Problem Description
./.github/setup-java.sh fails on MacOS

### Proposed Resolution

The "update-java-alternatives" command is typically used on Linux systems that have multiple Java versions installed. We can ignore the "update-java-alternatives: command not found" error as it is not applicable to macOS.

### Logs
```
> sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
sudo: update-java-alternatives: command not found
```

**Comment by frankmorgner** [comment]
The CI scripts are meant to be run on Ubuntu 20.04

**Comment by Jakuje** [comment]
As mentioned by Frank, this is meant for Ubuntu CI images. If you want to run it on mac, it will certainly require some modifications. Pull requests and CI improvements are welcomed.
Is there anything else to add to this issue or can you close it now?
