### ISSUE TITLE
Some Gnuk OpenPGP cards broke in 0.23.

### ISSUE THREAD

**Issue by tzs** [OpenSC/OpenSC#2752]
### Problem Description

I have an unbranded Gnuk OpenPGP USB card. It fully worked in OpenSC 0.22. It does not in 0.23. I've verified this on Debian 11 and MacOS. I've grabbed the source and bisected between 0.22 and the latest. The commit where it stopped working was:

commit 9e33f53c82dd9d218eda194812ee7c48de5adb04

Debug logs are linked below, for the previous commit and that commit.

It knows something is there under both versions. "opensc-tool --reader --atr" and "opensc-tool --reader --name" give me the same information on both ("3b:da:11:ff:81:b1:fe:55:1f:03:00:31:84:73:80:01:80:05:90:00:e1" and "Gnuk v1.x.x (OpenPGP v2.0) (FFFE 87074241)", respectively).

Something that fails is "pkcs11-tool --list-slots". On the older commit that gives:

Available slots:
Slot 0 (0x0): VMware Virtual USB CCID 00 00
  token label        : OpenPGP card (User PIN)
  token manufacturer : OpenPGP project
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 2.0
  firmware version   : 2.0
  serial num         : fffe87074241
  pin min/max        : 6/127
Slot 1 (0x1): VMware Virtual USB CCID 00 00
  token label        : OpenPGP card (User PIN (sig))
  token manufacturer : OpenPGP project
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 2.0
  firmware version   : 2.0
  serial num         : fffe87074241
  pin min/max        : 6/127

and on the newer commit gives:

Available slots:
Slot 0 (0x0): VMware Virtual USB CCID 00 00
  (token not recognized)

"pkcs11-tool --test --login" works on the old, and on the new sees no card. Etc.

### Proposed Resolution

I got nothing.

### Steps to reproduce

1. Plug in a Gnuk v1.x.x (OpenPGP v2.0) card.
2. pkcs11-tool --list-slots

### Logs

https://gist.github.com/tzs/870f184f35930de3d5f112eb519ec999

That contains two fails, fail-log.txt and good-log.txt.

It looks like around line 1370 that things start to go different between them.

**Comment by frankmorgner** [comment]
This is the nitrokey start, which claims conformance to (OpenPGP version 2)[https://shop.nitrokey.com/de_DE/shop/product/nksa-nitrokey-start-6], but in your failed run it is detected with version 3. SELECT DATA fails with your token, because it is only supported in version 3.

according to the ATR, the token is detected as `SC_CARD_TYPE_OPENPGP_GNUK`, with conformance to version 2. I've created https://github.com/OpenSC/OpenSC/pull/2753 which should handle your token more gracefully

**Comment by tzs** [comment]
Thanks. That does indeed fix it my system.
