### ISSUE TITLE
with the new opensc 0.23.0 version in Debian testing/sid I am unable to use the new Italian CNS

### ISSUE THREAD

**Issue by CNSCIE** [OpenSC/OpenSC#2763]
### Problem Description

with the new opensc version found in Debian testing/sid I was unable to use the new Italian CNS.
I think that the wrong type card is selected (it is selected the CNS with type:23002), but I'm unable to force the use of the correct one (CNS with type:23003).

First I list all the differences I have found.
Then I will show what I have done to let the new Italian CNS work correctly in a .deb I have created months ago.

For the not working opensc I used the one distributed by Debian
$ opensc-tool --version
No Git revision info available
$ opensc-tool -i
OpenSC 0.23.0 [gcc  12.2.0]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

I show rows starting with OK for the working opensc and with KO for the not working opensc

KO Manufacturer ID: IC: Infineon; mask: Oberthur Card Systems
OK Manufacturer ID: IC: Infineon; mask: IDEMIA (Oberthur)

KO Key length: 1024
OK Key length: 2048

KO  token flags        : token initialized
OK  token flags        : login required, token initialized, PIN initialized, user PIN locked

KO  firmware version   : 0.0
OK  firmware version   : 32.0

KO  pin min/max        : 4/8
OK  pin min/max        : 5/8

KO [pkcs15-tool] card.c:sc_connect_card: card info name:'CNS card', type:23002, flags:0x0, max_send/recv_size:255/256
OK [pkcs15-tool] card.c:sc_connect_card: card info name:'CNS card', type:23003, flags:0x0, max_send/recv_size:65535/65536

I think that the problem is the type, the 23003 work and the 23002 do not work.

I have try to force the use of type:23003 in /etc/opensc/opensc.conf but I was unable to have it.
I have made some configuration, but no one work to force the type, I can
only force the card name to not check all possible cards.

I show here the log in witch the type is selected

KO) in this one it select the wrong type
[pkcs15-tool] apdu.c:sc_single_transmit: returning with: 0 (Success)
[pkcs15-tool] apdu.c:sc_transmit: returning with: 0 (Success)
[pkcs15-tool] card.c:sc_unlock: called
[pkcs15-tool] reader-pcsc.c:pcsc_unlock: called
[pkcs15-tool] iso7816.c:iso7816_check_sw: File or application not found
[pkcs15-tool] card-cac.c:cac_select_file_by_type: returning with: -1201 (File not found)
[pkcs15-tool] card.c:sc_connect_card: trying driver 'itacns'
[pkcs15-tool] card.c:match_atr_table: ATR     : 3b:ff:18:00:00:81:31:fe:45:00:6b:05:05:20:00:01:21:01:43:4e:53:10:31:80:79
[pkcs15-tool] card.c:match_atr_table: ATR try : 3b:f4:18:00:ff:81:31:80:55:00:31:80:00:c7
[pkcs15-tool] card.c:match_atr_table: ignored - wrong length
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 3b against atr[0] == 3b
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 31 against atr[6] == 31
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 0 against atr[9] == 0
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 6b against atr[10] == 6b
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 1 against atr[15] == 1
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 43 against atr[18] == 43
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 4e against atr[19] == 4e
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 53 against atr[20] == 53
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 31 against atr[22] == 31
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 80 against atr[23] == 80
[pkcs15-tool] card.c:sc_connect_card: matched: Italian CNS
[pkcs15-tool] card-itacns.c:itacns_init: called
[pkcs15-tool] card.c:match_atr_table: ATR     : 3b:ff:18:00:00:81:31:fe:45:00:6b:05:05:20:00:01:21:01:43:4e:53:10:31:80:79
[pkcs15-tool] card.c:match_atr_table: ATR try : 3b:f4:18:00:ff:81:31:80:55:00:31:80:00:c7
[pkcs15-tool] card.c:match_atr_table: ignored - wrong length
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 3b against atr[0] == 3b
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 31 against atr[6] == 31
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 0 against atr[9] == 0
[pkcs15-tool] card-itacns.c:itacns_match_card: Matching 6b against atr[10] == 6b
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 1 against atr[15] == 1
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 43 against atr[18] == 43
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 4e against atr[19] == 4e
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 53 against atr[20] == 53
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 31 against atr[22] == 31
[pkcs15-tool] card-itacns.c:itacns_match_cns_card: Matching 80 against atr[23] == 80
[pkcs15-tool] card.c:sc_connect_card: card info name:'CNS card', type:23002, flags:0x0, max_send/recv_size:255/256

OK) in this one it select the working type
[pkcs15-tool] apdu.c:sc_single_transmit: returning with: 0 (Success)
[pkcs15-tool] apdu.c:sc_transmit: returning with: 0 (Success)
[pkcs15-tool] card.c:sc_unlock: called
[pkcs15-tool] reader-pcsc.c:pcsc_unlock: called
[pkcs15-tool] iso7816.c:iso7816_check_sw: File or application not found
[pkcs15-tool] card-cac.c:cac_select_file_by_type: returning with: -1201 (File not found)
[pkcs15-tool] card.c:sc_connect_card: trying driver 'itacns'
[pkcs15-tool] card.c:match_atr_table: ATR     : 3b:ff:18:00:00:81:31:fe:45:00:6b:05:05:20:00:01:21:01:43:4e:53:10:31:80:79
[pkcs15-tool] card.c:match_atr_table: ATR try : 3b:f4:18:00:ff:81:31:80:55:00:31:80:00:c7
[pkcs15-tool] card.c:match_atr_table: ignored - wrong length
[pkcs15-tool] card.c:match_atr_table: ATR try : 3b:8b:80:01:00:31:c1:64:00:00:00:00:00:00:00:00
[pkcs15-tool] card.c:match_atr_table: ignored - wrong length
[pkcs15-tool] card.c:sc_connect_card: matched: Italian CNS
[pkcs15-tool] card-itacns.c:itacns_init: called
[pkcs15-tool] card.c:sc_connect_card: card info name:'CNS card', type:23003, flags:0x0, max_send/recv_size:65535/65536

Now I describe what I have done to use correctly the new Italian CNS.
I have done that probably the 21 March 2022 in what was the Debian testing at that date.
to have the opensc_0.22.0-2_amd64 working with new Italian CNS

# apt build-dep opensc
$ mkdir ~/src
$ cd /src
$ apt source opensc
$ git clone https://github.com/3v1n0/OpenSC.git
$ cd OpenSC
$ cp -R ../opensc-0.22.0/debian .
$ fakeroot debian/rules binary

If I do the same actually I obtain a .deb file don't working with new Italian CNS.
So I think that you need to build the .deb package using all package that was available at 21 March 2022 to obtain the working packages.

I noted also that in the working deb I will get, wrongly, that the PIN try left is zero, but this is not a problem because all work correctly.

If someone need the .deb I have compiled at 21 March 2022 I can send to him (write directly to me).

I have also try on more PC and have all the same results. I have
noted that with some PC (I think newer one) old card lectors don't work,
I need to use a new one more recent.

I also have try to do some debug with gdb, but the debug symbol of
the compiled driver 0.22.0 do not work...

I have try to force with the following /etc/opensc/opensc.conf but don't work
app default {
	# debug = 3;
	# debug_file = opensc-debug.txt;
card_atr 3b:8b:80:01:00:31:c1:64:00:00:00:00:00:00:00:00 {
                driver = itacns;
                type = 23003;
		
                }
	framework pkcs15 {
		# use_file_caching = public;
	}
}

Let me know if you need more info.

### Proposed Resolution
I don't have.

Can someone suggest me how to force the type = 23003 in the opensc.conf file?

Can someone suggest what to look to identify the problem?

Ciao
Davide

**Comment by dengert** [comment]
it looks like the ATR of your card is:  3b:ff:18:00:00:81:31:fe:45:00:6b:05:05:20:00:01:21:01:43:4e:53:10:31:80:79
https://smartcard-atr.apdu.fr/ can be used to parse this and the historical bytes  have  "CNS" 

It looks like this routine would return 1 indicating a match:
https://github.com/3v1n0/OpenSC/blob/master/src/libopensc/card-itacns.c#L89-L122

Where as this routine would fail:
https://github.com/3v1n0/OpenSC/blob/master/src/libopensc/card-itacns.c#L124-L143
As it is looking for "ITID" in the historical bytes. 
 
https://github.com/3v1n0/OpenSC/blob/master/src/libopensc/card-itacns.c#L140 is the only place where card->type 
 is set to SC_CARD_TYPE_ITACNS_CIE_V2

 SC_CARD_TYPE_ITACNS_CIE_V2 is defined here as 23003:
https://github.com/3v1n0/OpenSC/blob/master/src/libopensc/cards.h#L189-L194

So I don't see why you expect your card to be type 23003.

I also looked at the Debian  source: https://packages.debian.org/sid/opensc  http://deb.debian.org/debian/pool/main/o/opensc/opensc_0.23.0.orig.tar.gz
and card-itacns.c matches what is in github.com/OpenSC/OpenSC  master.

**Comment by CNSCIE** [comment]
thanks for your reply

dengert wrote:

> So I don't see why you expect your card to be type 23003.

because with my compiled 0.22.0 version all work correctly and with the new 0.23.0 it don't.
Also the real minimum pin length is 5 and in the type 23002 is 4. So something is wrong.

I found now something interesting, that I don't have noted before.
In the 0.22.0 version that I compile there is a different type 23003

SD_CARD_TYPE_ITACNS_CNS_IDEMIA_2021 that is the type 23003 in the working 0.22.0
So, I think that the 3v1n0 patch[0] don't have been applied correctly in 0.23.00 branch

So it is missing a card in cards.h
I also see that in card-itacns.c is missing some rows using the SD_CARD_TYPE_ITACNS_CNS_IDEMIA_2021

If I have time I will try to change the cards.h and card-itacns.c to see if this can solve my problems... I see that there are other modifications in this file...

Ciao
Davide

[0] https://github.com/3v1n0/OpenSC

**Comment by dengert** [comment]
It looks like your PR https://github.com/OpenSC/OpenSC/pull/2483 was merged into OpenSC 2 weeks ago https://github.com/OpenSC/OpenSC/pull/2483#event-8996996311 so it would not be in 0.23.0 or in Debian. 

Can you update your clone of OpenSC and compile from master.

**Comment by CNSCIE** [comment]
I have taken the new code:
$ git clone  https://github.com/OpenSC/OpenSC.git

and compiled it, but it don't work.
when I test it with  pkcs15-tool it seem good, it take the correct CNS, but when I try to authenticate with a public administration site it don't ask me the pin and it say that the connection is not secure.

Previously I have try to modify the source of Debian opensc-0.23.0,
I have modify the following file:
pkcs15-itacns.c
cards.h
card-itacns.c
itacns.h

trying to report the 3v1n0 working patch (I don't know if there are other files modified or if I made the correct modifications).
With that version I can login a public administrator file with my pin, but as soon as I have logged in I get an error of invalid certificate and I'm throw out.

As soon as I have some time I try to see what is different from my modifications and the opensc main tree

**Comment by dengert** [comment]
@CNSCIE you may also want to contact @3v1n0 directly as he provided the patch to OpenSC, and works for "Canonical Ltd" as an Ubuntu developer.  

Other things to look at are:

Where you installed the OpenSC libs and programs. 

Check your browser or application to make sure it is finding the new opensc-pkcs11.so.  The browser may be using p11-kit to load PKCS11 modules. Does p11-kit find the new opensc-pkcs11?

**Comment by CNSCIE** [comment]
With the git source I'm not asked to insert the pin and get the following error on the browser:

	Secure Connection Failed

	An error occurred during a connection to portal.inps.it. The operation failed because the PKCS#11 token is not logged in.

	Error code: SEC_ERROR_TOKEN_NOT_LOGGED_IN


If I check the Firefox Settings->privacy & security->security device->CNS PKCS#11 The log In is disable.
It uses the library: /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so present in the packaged I have compiled from git.
If I use the command
$ pkcs15-tool --verify-pin
to insert the pin the site don't work

I have check the source I have modify and the one in the git repository and there are a lot of differences... I don't know nearly nothing about smartcard and also for the Italian one (CNS). But with my version (taken from 3v1n0 patch) it ask me the pin and I can log in... but after log in I get the error of invalid certificate

I will write to 3v1n0 for help

**Comment by dengert** [comment]
@3v1n0  
Can you comment on this OpenSC issue and you patch?


@CNSCIE 
The git OpenSC master branch has many changes since 0.23.0 including the patch from  
@3v1n0  So just look at the changes to card-itacns.c and pkcs15-itacns.c


> If I use the command $ pkcs15-tool --verify-pin to insert the pin the site don't work

pkcs15-tool or any of the tools may or may not leave the card in a logged in state. So that is not a good test. 

SEC_ERROR_TOKEN_NOT_LOGGED_IN is a Mozilla/NSS/FIREFOX message. If the card is not logged it Firefox should prompt for it. 


Access to certificates on the card usually does not require a login. So application may try and read the certificates and check if web server will accept it, before prompting for pin in order to use private key on card.

You said the Debian Sid  OpenSC is not working... What OS are you using. What version of browser.  If using Ubuntu, try installing firefox-esr. Ubuntu "snap" install of Firefox has many issues with smartcards. 

A SPY trace of the PKCS11 calls between the browser an opensc-pkcs11.so would help.
Note if you post it, the PIN may be exposed, so XXXXXXX it out. It will also show your certificates being read. You may want to XXXXXX them out, but at least show it read a certificate.  

 https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by CNSCIE** [comment]
Hi dengert,

it work now.

I have make a lot of compilation to search for the problem...

What I have done:
1) I see if there are some missing library and try to install more then the mandatory libraries
# apt install libbsd-dev  libeac-dev openpace libeac3  
but I think this has not effect on the final result (am I correct?)

2) used the compile instructions present on the OpenSC wiki
./bootstrap
./configure --prefix=/usr --sysconfdir=/etc/opensc
make
su -c "make install"


So the problem was the compilation with the debian directory that I have taken from opens-0.22.0 Debian packages.
I noted that Debian put the library in /usr/lib/x86_64-linux-gnu.

I'm very sorry to have wasted your time.

Now I would like to understand why compiling with debian directory of the open-0.22.0 do not work. I prefer to have a Debian package. I have see that there is a debian rule in the sources, but they are outdated (I don't have try to use them).

Many thanks :-)

**Comment by dengert** [comment]
> Now I would like to understand why compiling with debian directory of the open-0.22.0 do not work

I think I answered that in https://github.com/OpenSC/OpenSC/issues/2763#issuecomment-1525424838

 As opensc developer, using Ubuntu, I build from https://github.com/OpenSC/OpenSC  or othr github source. I don't normally build any debian packages.
