### ISSUE TITLE
data type storage not supported by opensc?

### ISSUE THREAD

**Issue by oldtigerin** [OpenSC/OpenSC#2786]
### Problem Description

I want to use veracrypt (for container encryption with a yubikey. Veracrypt make use of keyfiles and allows to store a keyfile on a security token by using PKSC11. (opensc-pksc11.dll linked to veracrypt)  Therefor I have installed OpenSC on my windows 10 PC.
Veracrypt gives access to 3 PIV data objects of the yubikey: cardholder finger prints;printed information and cardholder facial image;
The gui way does not succeed (error: "Function not supported") to put a datafile in an object.
Therefor I tried it manally:

C:\Program Files\OpenSC Project\OpenSC\tools>.\pkcs11-tool --pin 123456 -d 5fc103 -w .\snmp.my -y data
Using slot 0 with a present token (0x0)
error: PKCS11 function C_CreateObject failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
Aborting.

### Proposed Resolution
Is this a problem in OpenSC or in the yubikey (serie 5)? I've read "this indicates that unmanaged PKCS#11 library does not support/implement particular function defined in PKCS#11 specification." 

C:\Program Files\OpenSC Project\OpenSC\tools>opensc-tool -lan
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Yubico YubiKey OTP+FIDO+CCID 0
Using reader with a card: Yubico YubiKey OTP+FIDO+CCID 0
3b:fd:13:00:00:81:31:fe:15:80:73:c0:21:c0:57:59:75:62:69:4b:65:79:40
Personal Identity Verification Card

### Steps to rep
object id 0x5fc103 is the object "cardholder fingerprints"

**Comment by oldtigerin** [comment]
I have found the following of someone who writing a  PKCS11 library (as I understood)
-------------------------------------------------------------------------------------------------------------------
If your library does not support C_CreateObject at all then the best choice IMO is CKR_FUNCTION_NOT_SUPPORTED.

Chapter 11 in [PKCS#11 v2.20](https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.20) states:

    A Cryptoki library need not support every function in the Cryptoki API. However, even an unsupported function must have a "stub" in the library which simply returns the value CKR_FUNCTION_NOT_SUPPORTED.
--------------------------------------------------------------------------------------------------------------

I did not find the function C_Create_Object in the pkcs folder files of opensc src. Does opensc not support C_Create_Object?
(sorry I'm not a developer)

**Comment by Jakuje** [comment]
The function `C_Create_Object()` is implemented in OpenSC:

https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11-object.c#L156

but not all card drivers support writing generic data objects (I think most of them do not support this). Specifically the PIV driver does not support any writing, as the PIV specification does not define how "card management" operations are done. With yubikey, you might have some luck with the yubico pkcs11 modules, but I did not check if they support writing data objects.

**Comment by dengert** [comment]
PIV driver can write objects, but only via `piv-tool` and only if administrative authentication is done, and card supports it. 

Yubikey piv tool can also write objects. 

Note: both use the PUT_DATA (odd) where object is wrapped in TLV as per IOS docs. PIV tool expects user to provide the TLV. Yubikey piv tool add the TLV.  (when reading the object, OpenSC PIV returns TLV to user. I don't know what yubico returns. This goes back to 2004 when PIV driver was first written.

**Comment by Jakuje** [comment]
I think we answered your questions. Please let us know if there is something else or we can close the issue.
