### ISSUE TITLE
Wiki Colaboration in dedicated repository?

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#2800]
### Problem Description

In OpenSC we heavily rely on external input regarding the use of certain tokens or smart cards, but with restricted access rights to the wiki pages this input cannot be added anymore.

- Freely editable Wiki pages may be a security risk, see https://github.com/OpenSC/OpenSC/issues/2554.
- Github doesn't support pull request for wiki repositories

### Proposed Resolution

1. Set up a dedicated Github repository with the content of https://github.com/OpenSC/OpenSC.wiki.git
2. Set up a CI pipeline which pushes any change of this new repository to also push this to the actual OpenSC wiki.
3. Accespted pull requests for the new repository will automatically be pushed to the OpenSC wiki

See https://nimblehq.co/blog/create-github-wiki-pull-request for an example

**Comment by Jakuje** [comment]
Thank you for having a look into this!

I think this will provide a barrier for new contributors, but I do not see any better way. This will certainly need some documentation and instructions in the wiki and in the README of the wiki repository to be understandable on the first sight. And the mirroring CI set up. Is there something I can help with now?

I see also a  lot of outdated stuff in there so some cleanup would also help there.

**Comment by Jakuje** [comment]
@frankmorgner whats the status of the wiki mirroring? I would like to update the old drivers with the #2832 issue to make sure we do not remove that driver. Should I open a PR or just modify the wiki to avoid some conflicts?

Or should I look into the automatic mirroring (not sure I have the right access to test the things out on that repo).

**Comment by frankmorgner** [comment]
Currently, this is a manual process. You can submit a PR and I'll handle synchronization/conflicts. I did not have the time looking into automation. If you are missing any access rights, please let me know.

**Comment by Jakuje** [comment]
I went through the links you posted and some more and got stuck with the need for write access token for the whole OpenSC repository to do just the wiki pushing (the fine-grained access tokens are not so fine grained), which is something I am not much happy with ...

**Comment by frankmorgner** [comment]
OK, then we leave it manually as is
