### ISSUE TITLE
ePass FIDO-NFC Plus - cannot init

### ISSUE THREAD

**Issue by ramon72** [OpenSC/OpenSC#2805]
Hello, people and fans of OpenSC.

I tried to init a generic ePass FIDO-NFC Plus (Feitian) but errors occurred: 
`~$ pkcs15-init --reader 1 --create-pkcs15 -v`
`Connecting to card in reader FT U2F CCID KB [CCID] 01 00...
Using card driver Personal Identity Verification Card.
Couldn't bind to the card: Not supported`

I don't like the name of the driver (I was expecting something like `entersafe`). Am I missing something? Is the card supported? Apparently, ePass FIDO it is. 
I am using OpenSC 0.22.0

I enclose a file with the output in verbose mode, i.e., the result of this command:

`~$ pkcs15-init --reader 1 --create-pkcs15 -vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv`

[ePassFIDO_NFC_Plus.log](https://github.com/OpenSC/OpenSC/files/11805766/ePassFIDO_NFC_Plus.log)

Thanks for reading!

**Comment by dengert** [comment]
PIV driver uses GET DATA (odd)  with `7E` to identify  the AID of the applet on the card. The card has responded 
with the NIST 800-73-4  defined AID of `A0 00 03 08 00 00 10 00 01 00`.  https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf
  
```
Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 08 ..?..\.~.

P:10787; T:0x139642896992256 20:43:27.704 [pkcs15-init] reader-pcsc.c:242:pcsc_internal_transmit: called
P:10787; T:0x139642896992256 20:43:27.751 [pkcs15-init] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (10 bytes):
7E 12 4F 0B A0 00 00 03 61 0C 

Outgoing APDU (9 bytes):
00 CB 3F FF 03 5C 01 7E 14 ..?..\.~.

P:10787; T:0x139642896992256 20:43:27.779 [pkcs15-init] reader-pcsc.c:242:pcsc_internal_transmit: called
P:10787; T:0x139642896992256 20:43:27.823 [pkcs15-init] reader-pcsc.c:333:pcsc_transmit: 
Incoming APDU (22 bytes):
7E 12 4F 0B A0 00 00 03 08 00 00 10 00 01 00 5F ~.O............_
2F 02 40 00 90 00
```
So the card has the PIV applet: 'A0 00 00 03 08 00 00 10 00 01 00'

PIV applet is not PKCS15. OpenSC `card-piv.c` and `pkcs15-piv.c` emulate a pkcs15 card when reading  a provisioned card. 

`pkcs15-init` will not work. 

The OpenSC `piv-tool` or  https://developers.yubico.com/yubico-piv-tool/ may work.

NIST only defines a limited subset of commands for provisioning the card and left it up to card vendors to provide additional **or alternate** ways to provision a card.

**Comment by ramon72** [comment]
Dear @dengert 

Thank you for pointing to interesting information. Now, after reading some of the NIST 800-73-4 details and afters some tests, as a rookie with OpenSC, I would like to throw some more questions: answer as much as you consider convenient, I'm just curious to see how the dongle/card works. 

Thus, I'm trying to load a X.509 certificate onto the dongle/card. After reading the man pages and some documentation, I issued this command:
`piv-tool --reader 1 --cert 9A --in ramon.pem`

Apparently, the load with `piv-tool` was fine. Then, to check, I issued the command:
`pkcs15-tool --reader 1 --dump`

This is part of the output of that command. Hence, I guess, I was not successful loading the certificate, as 'File not found' is shown:
`Data object 'X.509 Certificate for PIV Authentication'
	applicationName: X.509 Certificate for PIV Authentication
	applicationOID:  2.16.840.1.101.3.7.2.1.1
	Path:            0101
Data object read failed: File not found`

Another part of the output of this command is the following:
`Data object 'Card Holder Unique Identifier'
	applicationName: Card Holder Unique Identifier
	applicationOID:  2.16.840.1.101.3.7.2.48.0
	Path:            3000
	Data (61 bytes): 533B301...`

Thus, I guess that data is read correctly by pkcs15-tool

For the records, this is the output (with some certificate data trimmed) of:
`piv-tool --reader 1 --cert 9A --in ramon.pem -vvvvvvvvvvvvvv`
[piv_tool.log](https://github.com/OpenSC/OpenSC/files/11817213/piv_tool.log)

Maybe they are not important, but some parts of this log that caught my eye (errors in red):
[piv_tool_part.log](https://github.com/OpenSC/OpenSC/files/11817229/piv_tool_part.log)

As said, feel free to answer whatever you want, as I'm just doing experiments and learning. 
Thanks @dengert !

**Comment by dengert** [comment]
You also must know the 9B admin key a DES3 or AES key, and use other options of piv-tool to add certificates.
 `P:13546; T:0x140492698077184 11:54:36.257 [piv-tool] iso7816.c:128:iso7816_check_sw: Security status not satisfied`
Some PIV cards (maybe this one) can be provisioned in other ways. 

NIST 800-73 defines how to create keypair on card and extract publickey at same time. The certificate must contain this public key to work. 

You may have better luck using the yubico-piv-tool, or some Epass FIDO NFC tools.  

NIST left card provisioning up to card vendor. PIV was never designed to be end user provisioned, rather issued by some gov card management system.

**Comment by ramon72** [comment]
Dear @dengert 

Thanks for the comments. They were very useful! I have to say that eventually `piv-tool` worked like a charm. 

I was able to successfully upload the certificate `ramon.pem` with the vendor default admin key and afterwards I was able to use it on Firefox (hint: Firefox can easily export the installed certificates to .pem: just view the contents of the certificate in the Privacy menu and there is an option to export). 

So, explaining the procedure for the **ePass FIDO-NFC Plus**, obtained from the documentation and your comments:

- I created a text file `mkey.txt` with the admin key with numbers in the format `XX:XX:XX:XX...`
- The default admin key can be obtained from the [Feitian SK Manager Tool User Manual](https://fido.ftsafe.com/feitian-sk-manager-tool-user-manual/) (it is a 48-numbers called Management Key). 
- I created the required environment variable: `export PIV_EXT_AUTH_KEY="mkey.txt"`
- I loaded the certificate with: `piv-tool --cert 9A --admin M:9B:03 --in ramon.pem`
- No errors were reported. I checked the contents with: `pkcs15-tool --dump`

Now, the certificate is inside:
`Data object 'X.509 Certificate for PIV Authentication'
	applicationName: X.509 Certificate for PIV Authentication
	applicationOID:  2.16.840.1.101.3.7.2.1.1
	Path:            0101
	Data (2570 bytes): 538...`

I started Firefox, I was asked for the default PIN, also detailed in the aforementioned manual and, bingo! I can use the certificate! The key works as expected and I agree: it is not for the general user, but I like being able to manage the contents of the key with open software. 

Thank you very much!

**Comment by dengert** [comment]
> Thanks for the comments. They were very useful! I have to say that eventually piv-tool worked like a charm.

More like magic. `piv-tool` wrote **just** the certificate. But you never said anything about how the public and private key where created.    I suspect they were created (or generated on the card) by [Feitian SK Manager Tool User Manual](https://fido.ftsafe.com/feitian-sk-manager-tool-user-manual/) and Windows which signed the certificate.  So `piv-tool` just overwrote the certificate on the card, and yo never needed to use it.

For most users, windows never talks about the public and private key just certificates.  NIST 800-* only defines how to create a keypair on the card and left up to card vendors how to import a private key to the card.

**Comment by ramon72** [comment]
Hello @dengert

> So `piv-tool` just overwrote the certificate on the card, and yo never needed to use it.

I'm afraid you are right. I just overwrote the certificate, but didn't take care of the rest of the details. I noticed it because today I tried to sign something using the written certificate and an error appeared. So I had to pick the original .p12 certificate from a backup file, import to Firefox and sign properly. 

> For most users, windows never talks about the public and private key just certificates. NIST 800-* only defines how to create a keypair on the card and left up to card vendors how to import a private key to the card.

Fine... I have more stuff to read. Thanks for your insights!
