### ISSUE TITLE
ssh - Segmentation fault

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#2819]
### Problem Description

$ ssh xxxxxx
Enter PIN for 'MyEID': 
client_input_hostkeys: convert key: memory allocation failed
client_input_hostkeys: convert key: error in libcrypto
Segmentation fault

ssh config:
`````
Host xxxxxx
        ControlMaster auto
        ControlPath ~/.ssh/%r@%h:%p
        HostName xxxxxx
        IdentityFile ~/.ssh/xxxxxx.pub
        IdentitiesOnly yes
        PKCS11Provider  /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
`````

It does not matter whether EC or RSA keys are used.

This error was found on the system:
Debian 12 (bookworm)/amd64,  opensc compiled from git (1st commit with this error is 79bec702662f8f35f76b1cd15f61d81f7ca9ea66)

openssh-client 1:9.2p1-2    amd64
openssl        3.0.9-1      amd64

I have not yet found any other applications that would crash like this. For example, openvpn is not affected.

### Logs
``````
Enter PIN for 'MyEID': 
debug1: pkcs11_check_obj_bool_attrib: provider "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so" slot 0 object 94439246852608: attrib 514 = 0
debug3: send packet: type 50
debug1: pkcs11_k11_free: parent 0x55e459c49fc0 ptr (nil) idx 1
debug3: receive packet: type 52
debug1: pkcs11_k11_free: parent 0x55e459c43b90 ptr (nil) idx 1
debug1: pkcs11_k11_free: parent 0x55e459c30e90 ptr 0x55e459c37070 idx 1
debug1: pkcs11_provider_unref: provider "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so" refcount 3
Authenticated to xxxxxx ([xxx.xxx.xxx.xxx]:22) using "publickey".
debug1: check provider "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"
debug1: pkcs11_provider_finalize: provider "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so" refcount 2 valid 1
debug1: pkcs11_provider_unref: provider "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so" refcount 2
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /home/popovec/.ssh/popovec@xxxxxxxx:22.7wFlW4xxxxxxx
debug2: fd 8 setting O_NONBLOCK
debug3: fd 8 is O_NONBLOCK
debug3: fd 8 is O_NONBLOCK
debug1: channel 0: new mux listener [/home/popovec/.ssh/popovec@xxxxxxxxxx:22] (inactive timeout: 0)
debug3: muxserver_listen: mux listener channel 0 fd 8
debug1: channel 1: new session [client-session] (inactive timeout: 0)
debug3: ssh_session2_open: channel_new: 1
debug2: channel 1: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: id
debug3: client_repledge: enter
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
client_input_hostkeys: convert key: memory allocation failed
client_input_hostkeys: convert key: error in libcrypto
Segmentation fault
``````

**Comment by popovec** [comment]
Since the problem occurs after the introduction of 79bec702662f8f35f76b1cd15f61d81f7ca9ea66 (#2816),  I tried to modify this PR. With this modification the mentioned issue does not appear:
`````
#if defined(ENABLE_OPENSSL)
#if defined(OPENSSL_SECURE_MALLOC_SIZE) && !defined(LIBRESSL_VERSION_NUMBER)
        CRYPTO_secure_malloc_done();
#elif defined(LIBRESSL_VERSION_NUMBER)
        OPENSSL_cleanup();
#endif
#endif
`````
In the case of my compilation, neither `CRYPTO_secure_malloc_done();` nor `OPENSSL_cleanup();` is used. I don't know if it's OK if OPENSSL_SECURE_MALLOC_SIZE is not set when compiling on a Debian system...

**Comment by frankmorgner** [comment]
would it be possible to inspect the segmentation fault with OpenSC's and OpenSSL's debug symbols using gdb or valgrind?

**Comment by frankmorgner** [comment]
What https://github.com/OpenSC/OpenSC/commit/79bec702662f8f35f76b1cd15f61d81f7ca9ea66 changes, is a call to `OPENSSL_cleanup();`, which wasn't there before. OpenSSL's man page explains that we should not call OPENSSL_cleanup():
>The OPENSSL_cleanup() function deinitialises OpenSSL (both libcrypto and libssl). All resources allocated by OpenSSL are freed. Typically there should be no need to call this function directly as it is initiated automatically on application exit. This is done via the standard C library atexit() function. In the event that the application will close in a manner that will not call the registered atexit() handlers then the application should call OPENSSL_cleanup() directly. Developers of libraries using OpenSSL are discouraged from calling this function and should instead, typically, rely on auto-deinitialisation. This is to avoid error conditions where both an application and a library it depends on both use OpenSSL, and the library deinitialises it before the application has finished using it.

**Comment by frankmorgner** [comment]
And I think we should clearify that OPENSSL_SECURE_MALLOC_SIZE should only be set when linking OpenSSL statically against OpenSC.

**Comment by popovec** [comment]
Ideally, the author of the patch should comment on this, as long as I followed it well, it is a port from OpenBSD security. 

I would like to understand how it came to be that the OpenBSD port of OpenSC needs the `OPENSSL_cleanup()` call ...

@klemensn does openssh work for you without problems if you have opensc compiled against libressl? Have you tried openssh against some version compiled against openssl?

**Comment by botovq** [comment]
Apologies for the breakage. I suggested during review of some other patches that `OPENSSL_cleanup()` might be needed for LibreSSL since unlike OpenSSL, LibreSSL does not install `OPENSSL_cleanup()` as an atexit handler. However, looking at the code again and the symptoms described in this issue this was a mistake and it was most certainly incorrect, also for LibreSSL.

It should be reverted.

**Comment by klemensn** [comment]
> @klemensn does openssh work for you without problems if you have opensc compiled against libressl? Have you tried openssh against some version compiled against openssl?

I have not used OpenSSH linked against OpenSSL with PKCS#11.

I have not set up ssh(1) with PKCS#11, but a quick test does prompt me for a YubiKey's PIN without crashing:
```
$ ssh -F none -o IdentitiesOnly=Yes -I /usr/local/lib/pkcs11/opensc-pkcs11.so  -o PubkeyAuthentication=No -o PasswordAuthentication=No localhost   
Enter PIN for 'PIV_II': 
PKCS#11 login failed: PIN incorrect
login failed
kn@localhost: Permission denied (publickey,password,keyboard-interactive).
```
Another smart card with two slots needs more configuration to pick a slot in the first place, but does not crash either:
```
$ ssh -F none -o IdentitiesOnly=Yes -I /usr/local/lib/pkcs11/opensc-pkcs11.so  -o PubkeyAuthentication=No -o PasswordAuthentication=No -v localhost
OpenSSH_9.3, LibreSSL 3.8.1
debug1: Connecting to localhost [::1] port 22.
debug1: Connection established.
debug1: provider /usr/local/lib/pkcs11/opensc-pkcs11.so: manufacturerID <OpenSC Project> cryptokiVersion 2.20 libraryDescription <OpenSC smartcard framework> libraryVersion 0.23
debug1: provider /usr/local/lib/pkcs11/opensc-pkcs11.so slot 0: label <xxx... (PIN1> manufacturerID <xxx> model <PKCS#15 emulate> serial <xxx> flags 0x40e
debug1: have 1 keys
debug1: pkcs11_k11_free: parent 0x6f5edb33410 ptr 0x6f50801e800 idx 1
debug1: pkcs11_provider_unref: provider "/usr/local/lib/pkcs11/opensc-pkcs11.so" refcount 2
debug1: provider /usr/local/lib/pkcs11/opensc-pkcs11.so slot 1: label <xxx... (PIN2> manufacturerID <xxx> model <PKCS#15 emulate> serial <xxx> flags 0x40e
debug1: have 2 keys
debug1: pkcs11_k11_free: parent 0x6f56af0de60 ptr 0x6f55b208c60 idx 1
debug1: pkcs11_provider_unref: provider "/usr/local/lib/pkcs11/opensc-pkcs11.so" refcount 3
[...]
kn@localhost: Permission denied (publickey,password,keyboard-interactive).
```
