### ISSUE TITLE
`pkcs11-tool --list-objects` doesn't list private keys with some PKCS#11 tokens

### ISSUE THREAD

**Issue by McLaynV** [OpenSC/OpenSC#2821]
### Problem Description

Command `pkcs11-tool --module "C:\Windows\System32\p11rss.dll" -l --list-objects` returns only certificates and not private keys when called on some tokens.

When you call `C_FindObjectsInit` on some tokens (for example Entrust Desktop Virtual Card) without specifying `CKA_CLASS`, they return only the public objects (X509 certificates) and they do not return private keys. 

> Desktop Virtual Card can return private keys and certificates through PKCS#11, but the call you send without specifying the type of object only returns the certificates. In order to get the private keys, you should specify the type of object you are looking for. Therefore, the application must explicitly set `CKA_CLASS = CKO_PRIVATE_KEY` in the search template of the `C_FindObjectsInit` function to list the private keys. 

### Proposed Resolution

Ensure all types of objects are queried from the token when calling `pkcs11-tool --list-objects`.

### Steps to reproduce

* Particular token: Entrust Virtual Desktop Card - version 2.3.0
* OS: Windows 10 x64
* OpenSC: version 0.23.0 https://github.com/OpenSC/OpenSC/releases/download/0.23.0/OpenSC-0.23.0_win64.msi
* Command: `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Windows\System32\p11rss.dll" -l --list-objects`

### Logs

See `pkcs11-spy` logs from the call below: https://gist.github.com/McLaynV/0afb1a8d94352e8a7b6c3ae0bb202db2

```
C:\Users\mclayn>"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll" -l --list-objects
Using slot 0 with a present token (0x1)
Certificate Object; type = X.509 cert
  label:      podepisovac 2 keyUsages
  subject:    DN: OU=Test, CN=podepisovac 2 keyUsages
  serial:     644949EA
  ID:         61393730386c766f746b6773613567366c756d6d6b6974307432
```

The output is the same (without private keys) when I use the DLL directly without `pkcs11-spy`:
```cmd
"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Windows\System32\p11rss.dll" -l --list-objects`
```

**Comment by Jakuje** [comment]
I think this behavior is against the PKCS #11 specification, which explicitly says:

> To find all objects, set ulCount to 0.

We can probably workaround it in the pkcs11 tool, but I think it would be better to report it to the developers of the offending pkcs11 module.

**Comment by dengert** [comment]
Module indicates it supports a CKF_PROTECTED_AUTHENTICATION_PATH   where the pin does not need to be provided by PKCS11 calling application. (pkcs11-tool).

```
7: C_Login
2023-07-07 15:22:47.105
[in] hSession = 0x1
[in] userType = CKU_USER
[in] pPin[ulPinLen] NULL [size : 0x0 (0)]
Returned:  0 CKR_OK
```


Did you receive a prompt for the pin? 
Did you just hit enter?


Can you try adding --pin (with your pin)`  to the command.  Note spy log may  show the pin. 
This might show if there is a problem with  CKF_PROTECTED_AUTHENTICATION_PATH.

**Comment by McLaynV** [comment]
Hello @dengert, 
I was already logged in the DVC token and there was no prompt for PIN. 

There even is no PIN. There is only 
* login to the token (general authentication flow which is SAML2 identity federation in this case)
* authorization of private key use (over OAuth)
Both of them are done by user interaction with a browser window.

Here is what the Desktop Virtual Card token developers wrote to me in previous communication regarding the PIN: 
> After consulting our development team, regarding the PIN, the PKCS#11 login state depends on the user's session in the DVC application but the PKCS#11 module still requires a call to the C_Login function without a PIN, as specified by the standard for tokens with CKF_PROTECTED_AUTHENTICATION_PATH.

**Comment by McLaynV** [comment]
Hello @Jakuje, 
sorry, I'm not familiar with PKCS#11 from the API implementation point of view, nor with the format of `pkcs11-spy` output. Do I understand correctly, that 

```
8: C_FindObjectsInit
2023-07-07 15:22:47.107
[in] hSession = 0x1
[in] pTemplate[0]: 
Returned:  0 CKR_OK
```

implies that `ulCount = 0`?

**Comment by mouse07410** [comment]
What happens if you do
```
pkcs11-tool -l --list-objects
```

**Comment by dengert** [comment]
> without specifying CKA_CLASS,

PKCS11 does say that ulCount = 0 should list all objects and if you are logged in, as the C_login returning CKR_OK implies, it should list private keys too.  

If you add `-y privkey`  does it list the private keys? 

As you pointed out above: "Therefore, the application must explicitly set CKA_CLASS = CKO_PRIVATE_KEY in the search template of the C_FindObjectsInit function to list the private keys."

**Comment by Jakuje** [comment]
> Hello @Jakuje, sorry, I'm not familiar with PKCS#11 from the API implementation point of view, nor with the format of `pkcs11-spy` output. Do I understand correctly, that
> 
> ```
> 8: C_FindObjectsInit
> 2023-07-07 15:22:47.107
> [in] hSession = 0x1
> [in] pTemplate[0]: 
> Returned:  0 CKR_OK
> ```
> 
> implies that `ulCount = 0`?

Correct. It might not be completely visible from this output, but the pkcs11-spy source can confirm that the 0 is really the `ulCount`:

https://github.com/OpenSC/OpenSC/blob/681c780fbafd48af53b491e562e6b2b435c06e10/src/pkcs11/pkcs11-spy.c#L965

**Comment by McLaynV** [comment]
Hello @mouse07410 
When I run `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" -l --list-objects` without specifying the module, the output is: 
```
Using slot 0 with a present token (0x0)
Logging in to "GIDS card (UserPIN)".
Please enter User PIN:
```
I'm not sure if `GIDS` is any of the tokens I have in my computer. So then I just press `Enter` and the command doesn't output anything else and just exits with exit code `1`.

**Comment by McLaynV** [comment]
Hello @dengert 
Regarding the command with `-y privkey`: When I call `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Windows\System32\p11rss.dll" -l --list-objects -y privkey`, the output is just: 
```
Using slot 0 with a present token (0x1)
```
and exit code `0`.

**Comment by McLaynV** [comment]
Thanks to all of you. To sum it up: 
* `pkcs11-tool` calls `C_FindObjectsInit` on the token with `ulCount = 0`
* [The PKCS#11 specification of `C_FindObjectsInit`](https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#:~:text=To%20find%20all%20objects,%20set%20ulCount%20to%200) says `To find all objects, set ulCount to 0.` 
* Therefore it looks like a bug in the token DLL implementation

Before closing this issue, the last thing that could be interesting is the behavior of `-y privkey`. Should it query `C_FindObjectsInit` with `CKA_CLASS = CKO_PRIVATE_KEY` in its template? It seems to me that it queries all the object using `ulCount = 0` and then filters them to only show private keys. See the [`pkcs11-spy` log](https://gist.github.com/McLaynV/823b8a9179ae247a5da802c463447068).

**Comment by mouse07410** [comment]
@McLaynV are you saying that instead of entering your card PIN, you Judy press Enter???

**Comment by McLaynV** [comment]
> are you saying that instead of entering your card PIN, you Judy press Enter???

Hello @mouse07410, I don't recognise the `GIDS card (UserPIN)` token, so I wasn't able to provide its PIN. There was no physical card or token plugged in my PC, so it must have been some internal device or some software token.

**Comment by McLaynV** [comment]
> The spy did not look any different. Did you have both -y privkey and --list-obiects
> 
> `pkcs11-tool --module "C:\Windows\System32\p11rss.dll" -l -y privkey --list-objects`

Hello @dengert, I tried once more calling `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll" -l -y privkey --list-objects` and I confirm that the `pkcs11-spy` output is exactly the same as the second `pkcs11-spy` gist (just different times and IDs).

**Comment by mouse07410** [comment]
> I don't recognise the GIDS card (UserPIN) token, so I wasn't able to provide its PIN.

If you're unable to provide the correct PIN, I don't see how you can possibly hope to retrieve info on private keys that (obviously) are PIN-protected.

**Comment by McLaynV** [comment]
@mouse07410 if I understood correctly, you wanted to know what happens when i call the command without specifying any DDL. 
What happens is that it asks me for a PIN of a token I don't recognize. Therefore, I'm unable to provide a PIN for this token

**Comment by mouse07410** [comment]
> if I understood correctly, you wanted to know what happens when i call the command without specifying any DDL

No. I wanted to merely point out that it is 100% expected to receive no output about private keys on a token when no PIN is given.

**Comment by Jakuje** [comment]
> > The spy did not look any different. Did you have both -y privkey and --list-obiects
> > `pkcs11-tool --module "C:\Windows\System32\p11rss.dll" -l -y privkey --list-objects`
> 
> Hello @dengert, I tried once more calling `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll" -l -y privkey --list-objects` and I confirm that the `pkcs11-spy` output is exactly the same as the [second `pkcs11-spy` gist](https://gist.github.com/McLaynV/823b8a9179ae247a5da802c463447068) (just different times and IDs).

Thats weird. The pkcs11-tool should add at least different template for `C_FindObjectsInit()` when you call it with `-y privkey`:

https://github.com/OpenSC/OpenSC/blob/681c780fbafd48af53b491e562e6b2b435c06e10/src/tools/pkcs11-tool.c#L4688

**Comment by dengert** [comment]
The was added by: https://github.com/OpenSC/OpenSC/commit/2655e9e01bc58062d2f9cd83384fa0355e4bed4b
which follows 0.23.0.

@frankmorgner  where are the latest Windows MSI files? 

look like  https://github.com/OpenSC/Nightly  is not being updated.


BRANCH=`git log --max-count=1 --date=short --abbrev=8 --pretty=format:"%cd_%h"`
today is 2023-08-08_a70dea5f
 2023-08-08_a70dea5f
 2023-08-08_a70dea5f

But by going to the last commit which was:  https://github.com/OpenSC/OpenSC/pull/2820
then clicking on "view Details and looking for "continuous-integration/appveyor/pr"
then clicking on "Details" which leads to: https://ci.appveyor.com/project/frankmorgner/opensc/builds/47604568
with the "jobs".  Under each of the jobs are the "Artifacts" with the MSI files.

**Comment by frankmorgner** [comment]
> @frankmorgner where are the latest Windows MSI files?
> 
> look like https://github.com/OpenSC/Nightly is not being updated.

please use [AppVeyor's artifacts directly](https://ci.appveyor.com/project/frankmorgner/opensc/build/job/hwxepap4ab7fmu8k) while I'm checking

**Comment by McLaynV** [comment]
Hello @Jakuje and @dengert, 
I installed the 0.23.0.72 build from https://ci.appveyor.com/project/frankmorgner/opensc/build/job/hwxepap4ab7fmu8k/artifacts - `OpenSC-0.23.0_win32.msi` with SHA256: `a1cb9ac80a94d3bbaf5c4cc35079c21c190b74b26a832c92dc69474227d8a010`

However, the `pkcs11-spy` output of `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll" -l -y privkey --list-objects` is still exactly the same as the [second `pkcs11-spy` gist](https://gist.github.com/McLaynV/823b8a9179ae247a5da802c463447068) (just current times and different IDs).

**Comment by dengert** [comment]
OpenSC on Windows has both a 64 bit and a 32 bit install. https://ci.appveyor.com/project/frankmorgner/opensc/build/job/hwxepap4ab7fmu8k/artifacts
has https://ci.appveyor.com/api/buildjobs/hwxepap4ab7fmu8k/artifacts/OpenSC-0.23.0_win32.msi which is the 32 bit version. 
and you are running `C:\Program Files\` so picking up the previous 64 bit version. 

On  https://ci.appveyor.com/project/frankmorgner/opensc/build/job/hwxepap4ab7fmu8k/artifacts click on "jobs" which shows the 8 versions built: 2 different Visual Studio,  32 and 64 and release or debug. 

Under each is an "artifacts" you may want to try  https://ci.appveyor.com/api/buildjobs/5pj87sltpa4sw6io/artifacts/OpenSC-0.23.0_win64.msi    64 bit, release, built with VS 2015


On Ubuntu the spy shows:
```
 8: C_FindObjectsInit
 P:1187590; T:0x140737353666048 2023-08-09 08:10:14.532
 [in] hSession = 0x5555555dc9b0
 [in] pTemplate[1]: 
     CKA_CLASS             CKO_PRIVATE_KEY      
 Returned:  0 CKR_OK
```
and listed only private keys.

**Comment by McLaynV** [comment]
Hello @dengert, 
thanks and sorry for that. I was even trying to check the version using `--version`, but no such option exists in `pkcs11-tool`. 

I uninstalled the 32-bit version (kept the 64-bit version), downloaded and installed [`OpenSC-0.23.0_win64.msi`](https://ci.appveyor.com/api/buildjobs/5pj87sltpa4sw6io/artifacts/OpenSC-0.23.0_win64.msi) with SHA256 `72ba09a3d683bbcf0e9a53a55fe53653768795fbbc8a0613a2f21cfb16602ab7`.

During the installation I got an error `The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2753`. After that, I had 2 64-bit versions installed. So I uninstalled them both and did another install - without any errors this time. I also had to set again the registry for `pkcs11-spy`.

Here is the command and the output: 

```
C:\Users\miklin>"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" --module "C:\Program Files\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll" -l -y privkey --list-objects
Using slot 0 with a present token (0x1)
Private Key Object; RSA
  label:      podepisovac 2 keyUsages
  ID:         61393730386c766f746b6773613567366c756d6d6b6974307432
  Usage:      sign
  Access:     sensitive, always sensitive, never extractable, local
  Allowed mechanisms: RSA-PKCS-KEY-PAIR-GEN,RSA-X-509
```

It correctly shows the private key. And the important part of [`pkcs11-spy` log](https://gist.github.com/McLaynV/cc3e389d83037fffd791b1041f4300eb) is: 

```
8: C_FindObjectsInit
P:13588; T:13672 2023-08-09 17:09:28.868
[in] hSession = 0x1
[in] pTemplate[1]: 
    CKA_CLASS             CKO_PRIVATE_KEY      
Returned:  0 CKR_OK
```

So I confirm that in this nightly build, listing the private keys behaves as I would expect it. 

Should i just close this issue, or do you want to somehow link it to the next version?

**Comment by dengert** [comment]
The real problem is the vendor's pkcs11 module. The OpenSC modification is more for user convenience to list only a subset of objects. 

> Should I just close this issue, or do you want to somehow link it to the next release version?

That is up to you.
