### ISSUE TITLE
RFC: code signing certificates to be stored on hardware certified as FIPS 140 Level 2

### ISSUE THREAD

**Issue by fgeorgatos** [OpenSC/OpenSC#2823]
Hi. This is not a bug report, rather a request for comments.

It comes under attention the following industry wide development - since digicert is an important player, this highlighted item should not be skipped, i.e. **to require private keys for standard code signing certificates to be stored on hardware certified as FIPS 140 Level 2**: https://knowledge.digicert.com/generalinformation/new-private-key-storage-requirement-for-standard-code-signing-certificates-november-2022.html

Some more info is also findable at: https://en.wikipedia.org/wiki/FIPS_140-2 ## Levels & Reception are worthy sections to check

The RFC here is 1) if there is a discussion going on regarding this topic in relation to OpenSC, 2) if there is any timeline involved and 3) what are the expected communication channels in relation to this topic for OpenSC going forward.

In effect, the aim is to pin releases and have something additional to using hashes which communicate information such as:

```
% md5 OpenSC-0.23.0.dmg
MD5 (OpenSC-0.23.0.dmg) = 6a52f3c5a9dafc0a56cac3446eaea235
% shasum OpenSC-0.23.0.dmg
a87edbfdc6f52033482ebd6095161c8ff48ff599  OpenSC-0.23.0.dmg
```

P.S.
before anyone shoots about the merits and adequacy of the `FIPS 140 Level 2` standard, my own personal preference for software would have been to have at least two not-too-overlapping-by-scope-and-domain standards being available and compliant to, as a matter of user prerogative to chose that; Hereby, I am merely asking for (any) pointers to information relevant to this issue.

**Comment by frankmorgner** [comment]
First, AFAIK, no OpenSC release has been subnitted for a FIPS validation, nor is this planned. Second, if Digicert requires you to store private keys on a hardware token, OpenSC may enable you to do so with one of its supported tokens. However, I don't see how any change of some Digicert policy would have any impact on OpenSC.

I'm not sure if I fully understand your question, since you seem to be targetting some release management or planning issue...

**Comment by fgeorgatos** [comment]
for the most recent and next opensc releases, which measures are taken in relation to signing keys for `.msi` & `.dmg`?

**Comment by frankmorgner** [comment]
msi is signed, dmg is not

**Comment by fgeorgatos** [comment]
Hello Frank,

In order to understand if `opensc` is fit for purpose in relation to `FIPS 140 Level 2` it is important to know if the signing keys for opensc packages are themselves protected. Is there *any* standard followed in relation to that, i.e. for the `dmg` package being signed? is the build happening under the developers' team full control?

also, what are the communication channels in relation to this topic for OpenSC?
