### ISSUE TITLE
Support for RSA-PSS with SmartCard-HSM broken in 0.22 and 0.23

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#2826]
See #2802

**Comment by CardContact** [comment]
Changing to

    if (pad_flags & SC_ALGORITHM_RSA_PADS) {

fixes the issue, but I'm not sure if this has side effects on other cards.

I'm wondering why this issue didn't surface before, as all cards supporting PSS padding internally are affected.

**Comment by CardContact** [comment]
Apparently the bug only affects the CKM_SHA*_RSA_PKCS_PSS mechanisms.

The CKM_RSA_PKCS_PSS mechanism, where the caller supplies the hash, works as expected. This is the predominant version, used for example by Firefox in MTLS.

**Comment by dengert** [comment]
What about the problem with  with the DigestInfo being added for PSS when it should not. See:  
https://github.com/OpenSC/OpenSC/discussions/2802#discussioncomment-6670679

```
--- a/src/libopensc/padding.c
+++ b/src/libopensc/padding.c
@@ -664,7 +664,7 @@ int sc_get_encoding_flags(sc_context_t *ctx,
                        (iflags & SC_ALGORITHM_RSA_PAD_PSS)) {
                *sflags |= SC_ALGORITHM_RSA_PAD_PSS;
                *sflags |= iflags & SC_ALGORITHM_MGF1_HASHES;
-               *pflags = iflags & ~(iflags & (SC_ALGORITHM_MGF1_HASHES | SC_ALGORITHM_RSA_PAD_PSS));
+               *pflags = iflags & ~(iflags & SC_ALGORITHM_MGF1_HASHES);
 
        } else if ((caps & SC_ALGORITHM_RSA_RAW) &&
                                (iflags & SC_ALGORITHM_RSA_PAD_PKCS1
```

**Comment by frankmorgner** [comment]
We're tracking this [here](https://github.com/OpenSC/OpenSC/projects/12#card-90192900). Feel free to open a new pull request for review, ideally with some test code.
