### ISSUE TITLE
cannot init feitian ePass2003 with 0.23

### ISSUE THREAD

**Issue by mcku** [OpenSC/OpenSC#2829]
### Problem Description
I would like to use a Feitian A22CR card with ePass2003 driver in Fedora linux. 

pkcs15-init returns some errors.
 
Even an older version such as 0.16.0 yields the same error in the log, even though it does not return error on the command line. 

Also note that the card can be accessed using vendor tool on windows. But the vendor mgmt tool's linux version does not work, either.  When I run the ePassManager_2003 tool, which uses libcastle.so.1.0.0, an empty slot called "ES Slot 1" appears, regardless of the card being inserted or not. 

### Proposed Resolution
I would be happy to see a working configuration with the latest opensc.

### Steps to reproduce
OPENSC_DRIVER=epass2003 pkcs15-init -E -vvv

### Logs
[pkcs-init.log](https://github.com/OpenSC/OpenSC/files/12318797/pkcs-init.log)
Multiple errors are there. The first one is:
```
[pkcs15-init] card-epass2003.c:1745:epass2003_select_fid_: returning with: -1201 (File not found)
[pkcs15-init] card-epass2003.c:1790:epass2003_select_fid: APDU transmit failed: -1201 (File not found)
[pkcs15-init] card-epass2003.c:1945:epass2003_select_path: SELECT FILE (DF-ID) failed: -1201 (File not found)
[pkcs15-init] card.c:873:sc_select_file: 'SELECT' error: -1201 (File not found)
```

**Comment by Jakuje** [comment]
I just had similar issue and asked #2835 -- can you try to erase the card with `-T` to use default transport keys as suggested by Peter?

**Comment by mcku** [comment]
The proposed solution in the #2835 works.
