### ISSUE TITLE
Athena ASE III gets CKR_TOKEN_NOT_RECOGNIZED

### ISSUE THREAD

**Issue by manu0401** [OpenSC/OpenSC#2832]
### Problem Description

Athena ASE IIIe USB token ceased to work  between OpenSC 0.22.0 and 0.23.0

With OpenSC 0.23.0, pkcs11-tool -vL gets
```
pkcs11-tool -L gets
Available slots:
Slot 0 (0x0): Athena ASE IIIe 00 00
  (token not recognized)
```
With prior OpenSC the token works. pkcs11-tool -vL says
```
Available slots:
Slot 0 (0x0): Athena ASE IIIe 00 00
  manufacturer:  Athena
  hardware ver:  16.2
  firmware ver:  0.0
  flags:         token present, removable device, hardware slot
  token label        : OpenSC Card (manu)
  token manufacturer : OpenSC Project
  token model        : PKCS#15
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0105523190192129
  pin min/max        : 4/16
```
### Proposed Resolution

This change caused the regression: https://github.com/OpenSC/OpenSC/commit/f44564b2e9cdc9baf67914f1e5b7c2da6f007862

Moving back asepcos from old_card_drivers to internal_card_drivers  fixes the problem

```
--- src/libopensc/ctx.c.orig    2023-08-14 10:34:40.772689358 +0200
+++ src/libopensc/ctx.c 2023-08-14 10:34:47.435926078 +0200
@@ -100,8 +100,9 @@
 static const struct _sc_driver_entry internal_card_drivers[] = {
        { "cardos",     (void *(*)(void)) sc_get_cardos_driver },
        { "cyberflex",  (void *(*)(void)) sc_get_cyberflex_driver },
        { "gemsafeV1",  (void *(*)(void)) sc_get_gemsafeV1_driver },
+       { "asepcos",    (void *(*)(void)) sc_get_asepcos_driver },
        { "starcos",    (void *(*)(void)) sc_get_starcos_driver },
        { "tcos",       (void *(*)(void)) sc_get_tcos_driver },
 #ifdef ENABLE_OPENSSL
        { "oberthur",   (void *(*)(void)) sc_get_oberthur_driver },
@@ -157,9 +158,8 @@
 };
 
 static const struct _sc_driver_entry old_card_drivers[] = {
        { "akis",       (void *(*)(void)) sc_get_akis_driver },
-       { "asepcos",    (void *(*)(void)) sc_get_asepcos_driver },
        { "atrust-acos",(void *(*)(void)) sc_get_atrust_acos_driver },
        { "flex",       (void *(*)(void)) sc_get_cryptoflex_driver },
 #ifdef ENABLE_OPENSSL
     { "gpk",        (void *(*)(void)) sc_get_gpk_driver },
```

### Steps to reproduce

pkcs11-tool -L

### Logs

https://dl.espci.fr/ticket/746c382a3d8f5fd8cf13319b3042d67e

**Comment by Jakuje** [comment]
The old drivers are disabled as they are mostly unmaintained over the last years and they open potential security issues in default installations. If you need to use this driver, you can configure `card_drivers = old` in your `opensc.conf` as hinted in the manual page and previously discussed in

https://github.com/OpenSC/OpenSC/projects/2
https://github.com/OpenSC/OpenSC/pull/2391
https://github.com/OpenSC/OpenSC/wiki/Removal-of-Old-Card-Drivers

If you are still using this card and are interested in keeping the card working in OpenSC, we would appreciate at least some testing before releases:

https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing

**Comment by manu0401** [comment]
On Mon, Aug 14, 2023 at 02:28:53AM -0700, Jakub Jelen wrote:
> If you are still using this card and are interested in keeping the card working in OpenSC, we would appreciate at least some testing before releases:
> 
> https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing

Should I edit the page to report asepcos success on NetBSD with 0.23.0?

-- 
Emmanuel Dreyfus
***@***.***

**Comment by Jakuje** [comment]
> On Mon, Aug 14, 2023 at 02:28:53AM -0700, Jakub Jelen wrote: If you are still using this card and are interested in keeping the card working in OpenSC, we would appreciate at least some testing before releases: https://github.com/OpenSC/OpenSC/wiki/Smart-Card-Release-Testing
> Should I edit the page to report asepcos success on NetBSD with 0.23.0?

Unfortunately, wiki edits are not possible directly, see #2800, only through pull requests to https://github.com/OpenSC/Wiki because of phishing malware/attacks. For 0.23.0 it probably does not make much sense, but if you could give a test to master (and ideally report results of `p11test` (under `src/tests/p11test`), it would be great. I would suggest to post results to the release issue #2792, ideally in the json format. If you have some spare/test cards that could be provided to opensc team to be able to run the release tests or CI it would be even better.

**Comment by manu0401** [comment]
On Mon, Aug 14, 2023 at 11:59:38AM -0700, Jakub Jelen wrote:
> Unfortunately, wiki edits are not possible directly, see #2800, only through pull requests to https://github.com/OpenSC/Wiki because of phishing malware/attacks. For 0.23.0 it probably does not make much sense, but if you could 
> give a test to master (and ideally report results of `p11test`

There are four tests: softhsm, opencryptoki, myeid  and readonly.
opencryptoki requires a pkcsslotd I never heard about, the others
pass. Which json should I supply?

> If you have some spare/test cards 

Sorry, I don't have much functionnal cards left. SO PIN was forgotten on 
a few of them.

-- 
Emmanuel Dreyfus
***@***.***

**Comment by Jakuje** [comment]
the runtest is just a wrapper so the test can be running against various implementations including software tokens.  I run the p11test like this:
https://gitlab.com/redhat-crypto/OpenSC/-/blob/master/.gitlab-ci.yml?ref_type=heads#L74
```
./p11test -v [-s SLOT_ID] -p [PIN] -o results.json
```
The slot id is not mandatory and you need to replace the PIN with your pin.

**Comment by Jakuje** [comment]
Are you ok with the driver for your card being kept in legacy/old drivers list (as it looks like you are the second user in last ~10 years using this card with opensc #285) or do you prefer to move it back to the default?

**Comment by manu0401** [comment]
On Tue, Aug 22, 2023 at 01:55:09AM -0700, Jakub Jelen wrote:
> Are you ok with the driver for your card being kept in legacy/old drivers list (as it looks like you are the second user in last ~10 years using this card with opensc #285) or do you prefer to move it back to the default?

Both are fine, I just so not want it to vanish. Perhaps default is
a better protection against someone doing some cleanup?

-- 
Emmanuel Dreyfus
***@***.***

**Comment by kenpb** [comment]
Hello,

I've been also struggling with this, I have two cards

- [3B DC 18 FF 80 91 FE 1F C3 80 73 C8 21 13 66 01 0B 03 52 00 05 39](https://smartcard-atr.apdu.fr/parse?ATR=3B+DC+18+FF+80+91+FE+1F+C3+80+73+C8+21+13+66+01+0B+03+52+00+05+39)
- [3B DF 18 FF 81 91 FE 1F C3 00 31 B8 64 0C 01 EC C1 73 94 01 80 82 90 00 B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

Both are used as eID cards in Costa Rica, the later being the current one since 2019; after this renewal and switching to Fedora I'm unable to make them work.

I've enabled the old drivers in the `/etc/opensc.conf `

```
app default {
        debug = 3;
        card_drivers = old,internal;
...
```

And also tried matching the ATR's manually with the driver

```
        framework pkcs15 {
                use_file_caching = public;
        }
        card_atr 3b:dc:18:ff:80:91:fe:1f:c3:80:73:c8:21:13:66:01:0b:03:52:00:05:39 {
                name = "Costa Rican eSignature";
                driver = "asepcos";
        }
        card_atr 3b:df:18:ff:81:91:fe:1f:c3:00:31:b8:64:0c:01:ec:c1:73:94:01:80:82:90:00:b3 {
                name = "Costa Rican eSignature 2019";
                driver = "asepcos";
        }
       reader_driver pcsc {
....
```

The opensc-tool seems to recognize the reader

```
opensc-tool --card-driver asepcos -a --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Athena ASE IIIe [SCR Interface] 00 00
Using reader with a card: Athena ASE IIIe [SCR Interface] 00 00
```

But any attempt to log into token fails

```
pkcs11-tool --module ./libASEP11.so --test --login
Using slot 0 with a present token (0x0)
error: PKCS11 function C_OpenSession failed: rv = CKR_TOKEN_NOT_RECOGNIZED (0xe1)
Aborting.
```

I've also attached the logs [here](https://gist.github.com/kenpb/d8719e64ec1360085d4b39a039be1a4a)

Appreciate any ideas,
Salutations

**Comment by dengert** [comment]
`pkcs11-tool --module ./libASEP11.so --test --login`  is using their module so any changes to opensc.conf will not be used. 

**But** the log show you are the OpenSC pkcs11 module. The card-asepocs.c supports two types of cards, SC_CARD_TYPE_ASEPCOS_GENERIC  (17001)  and SC_CARD_TYPE_ASEPCOS_JAVA (17002)

So try adding to you `opensc.conf` after each `card_atr`  `type = 17002;` to see if it is a java type card.

**Comment by kenpb** [comment]
Hello @dengert,

That made it work, thank you!, it is a java type card indeed, I've also found out that the driver file I was using was corrupted somehow.
