### ISSUE TITLE
yubikey: not able to sign when token has CKA_ALWAYS_AUTHENTICATE

### ISSUE THREAD

**Issue by mmoraga** [OpenSC/OpenSC#2833]
OpenSC Version: 0.23.0
Token: Yubikey 5Ci
OS: macOS Ventura 13.4.1

### Problem Description
I'm developing an application that interacts with smartcards using opensc pkcs11. The other card slots work as intended for signing, and 9c also works on windows where we use a different API for PIV communication. Following the Cryptoki spec we do the following for slot 9c (which has CKA_ALWAYS_AUTHENTICATE enabled)
```
C_Login with CKU_USER
C_SignInit
C_Login with CKU_CONTEXT_SPECIFIC
C_Sign
```
but the last call to C_Sign keeps returning CKR_DATA_INVALID
Same data using another keyslot returns a valid Signature and CKR_OK.

### Steps to reproduce
plugin fidokey with certificate in slot 9C 
Load `opensc-pkcs11.so` shared library.
C_Login (CKU_USER)
C_SignInit
C_Login (CKU_CONTEXT_SPECIFIC)
C_Sign

Signing without C_Login (CKU_CONTEXT_SPECIFIC) works as expected if the same certificate is loaded in another card slot.
### Logs

```
0x00008b24 : 0x000000000014997a : ****************************** 2023-08-03 14:29:49 ***
0x00008b24 : 0x000000000014997a : Calling C_Sign
0x00008b24 : 0x000000000014997a : Input
0x00008b24 : 0x000000000014997a :  hSession: 105553116705584
0x00008b24 : 0x000000000014997a :  pData: 0x18e3cc650
0x00008b24 : 0x000000000014997a :  *pData: HEX(323032332D30382D30335431323A32393A34392E333836393036305A)
0x00008b24 : 0x000000000014997a :  ulDataLen: 28
0x00008b24 : 0x000000000014997a :  pSignature: 0x18e411708
0x00008b24 : 0x000000000014997a :  pulSignatureLen: 0x30d5fce38
0x00008b24 : 0x000000000014997a :  *pulSignatureLen: 256
0x00008b24 : 0x000000000014997a : Returning 32 (CKR_DATA_INVALID)
```

Full logs: https://gist.github.com/mmoraga/badcdf7b968110b86a398afcac594e59

 

I also created an issue with the wrapping library we use: https://github.com/Pkcs11Interop/Pkcs11Interop/issues/224

**Comment by Jakuje** [comment]
You are using `CKM_SHA512_RSA_PKCS` mechanism. The `CKR_DATA_INVALID` does not indicate issue with the login. It sounds more like you would have small RSA key that is not able to handle the SHA512 digest.

**Comment by mouse07410** [comment]
How is it possible for an RSA key that on Yubikey can't be smaller than 1024 bits, to be unable to handle 512-bit digest?

**Comment by popovec** [comment]
Is it something similar to this problem?

https://github.com/OpenSC/OpenSC/issues/2173

**Comment by mmoraga** [comment]
As I mentioned:
> Signing without C_Login (CKU_CONTEXT_SPECIFIC) works as expected if the same certificate is loaded in another card slot.

Loading the SAME certificate in card slot 9a (where CKA_ALWAYS_AUTHENTICATE is false)
Using the following functions:
```
C_Login with CKU_USER
C_SignInit
C_Sign
```
works as expected.  The key size is 2048 bits.

**Comment by mmoraga** [comment]
Correct, the PkcsWrapper implementation calls C_Sign twice to get the size of the buffer. Because of this I also later tried setting the buffer to 256 as I suspected the two calls causing issues - again with the same result.

When am I supposed to press the button if it's flashing? Is it before or after `C_Login (CONTEXT_SPECIFIC)`, `C_SignInit` or `C_Sign` operation?

I can try to get `opensc-debug.log` for the use-case when C_Sign is only called once if that helps?

This was tested with opensc 0.23. I thought it would be included in the pkcs11-logger log so I'll update my original post with that info.

**Comment by dengert** [comment]
If the single call to C_Sign also fails get the opensc-debug. log  with single C_sign. 

The card-piv.c goes to great lengths to handle no intervening apdus, by locking via PCSC so no other application can interfere.

**Comment by mmoraga** [comment]
Here is the opensc11-spy log from using only a single call to C_Sign: https://gist.github.com/mmoraga/03c6021f444fde83ef77575a68904676

**Comment by Jakuje** [comment]
Regarding the APDUs it looks ok as the sign APDU is the first one after login.

But I am wondering if the following line might be an issue:
```
P:45034; T:0x6168866816 17:01:31.564 [opensc-pkcs11] card-piv.c:3516:piv_check_sw: Clearing CONTEXT_SPECIFIC lock
```
Because of the data size, the APDU is split into two, but after the first one we already clear the lock, which sounds wrong. Its a question if the lock in opensc could be an issue or if the token itself messes the  state up with the APDU chaining. Can you try with the following (hackish) patch if it changes something?:
```
diff --git a/src/libopensc/card-piv.c b/src/libopensc/card-piv.c
index 4a2196ed5..954bbcf2b 100644
--- a/src/libopensc/card-piv.c
+++ b/src/libopensc/card-piv.c
@@ -176,6 +176,7 @@ typedef struct piv_private_data {
 	int pstate;
 	int pin_cmd_verify;
 	int context_specific;
+	int sign_in_progress;
 	unsigned int pin_cmd_verify_sw1;
 	unsigned int pin_cmd_verify_sw2;
 	int tries_left; /* SC_PIN_CMD_GET_INFO tries_left from last */
@@ -562,6 +563,7 @@ static int piv_general_io(sc_card_t *card, int ins, int p1, int p2,
 	}
 	apdu.resp =  recvbuf;
 
+	priv->sign_in_progress = 1;
 	/* with new adpu.c and chaining, this actually reads the whole object */
 	r = sc_transmit_apdu(card, &apdu);
 
@@ -570,6 +572,7 @@ static int piv_general_io(sc_card_t *card, int ins, int p1, int p2,
 		goto err;
 	}
 
+	priv->sign_in_progress = 0;
 	r = sc_check_sw(card, apdu.sw1, apdu.sw2);
 
 	if (r < 0) {
@@ -3518,6 +3521,8 @@ static int piv_check_sw(struct sc_card *card, unsigned int sw1, unsigned int sw2
 		if (priv->pin_cmd_verify) {
 			priv->pin_cmd_verify_sw1 = sw1;
 			priv->pin_cmd_verify_sw2 = sw2;
+		} else if (priv->sign_in_progress) {
+			/* noop -- we can not clear the context specific lock before we complete chained operation */
 		} else {
 			/* a command has completed and it is not verify */
 			/* If we are in a context_specific sequence, unlock */
```

**Comment by dengert** [comment]
2048 key operations will always use chaining. 

When  context specific is used An extra lock is is added before the verify command so 
the card will remain locked after the verify to prevent other applications for accessing the card
before the sign operation starts which also sets its own lock. It also keeps the card driver for checking  the login state and if PIV applet is still active
 
The extra lock is removed when the next command is sent whatever it happens to be. 
(In case the calling application does not do the sign operation  when it should.)  

 The signature operation sets its own lock too so the PCSC lock is  active from the c_login verify untill the signature operation

PCSC lock is set here:
5534 P:45034; T:0x6168866816 17:01:30.796 [opensc-pkcs11] reader-pcsc.c:688:pcsc_lock: called
which also tells card driver it should check for active PIV applet here: 
Line 5535 P:45034; T:0x6168866816 17:01:30.796 [opensc-pkcs11] card-piv.c:3779:piv_card_reader_lock_obtained: called. 

line 5803 is when the PCSC lock is released. P:45034; T:0x6168866816 17:01:31.569 [opensc-pkcs11] reader-pcsc.c:740:pcsc_unlock: called

So it does not look like a a locking problem. 


It could also be a mismatch of the key type or size. The PIV Card drive  card-piv.c and pkcs15-piv.c have to read the matching certificate to find the public key in the certificate to get the type and size of the private key.  

When a key is generated is the only time a PIV card will return the public key. (I believe Yubico will at that time create a dummy certificate.) PIV specs expect the public key returned during generation will be by sent to a CA in a certificate request where the CA will issue a certificate that will then be loaded on to the card.  PIV specs don't call for card parsing a certificate to confirm if private key on the card matches the public key in certificate.   

It is possible that you may have gotten out of sync where key size or type (RSA vs ECC) key was changed on card but certificate not written? thus leading to a possible mismatch.

Is a certificate being cached somewhere?

**Comment by dengert** [comment]
Could you have deleted the key from the card but not the certificate?  The certificate says there is a key on the card. The error message could mean the card can not find the private key.

**Comment by mmoraga** [comment]
Yes it turns out there was an issue with the certificate I was testing. I had tried double-checking with a known working certificate to make sure it wasn't an issue with the cert but I must have messed that up somehow. I made a new check again now with a fresh certificate and I finally got CKA_ALWAYS_AUTHENTICATE working properly. Thanks for all the help and sorry for wasting your time.
