### ISSUE TITLE
ASEPCOS card driver does not support pinpads

### ISSUE THREAD

**Issue by promovicz** [OpenSC/OpenSC#285]
It seems to me that pinpad support is unimplemented/broken for ASEPCOS cards.

Whatever I do: I always get asked for the PIN on the host system.

The problem occurs in many different situations:

- during initialization (using pkcs15-init)
- while exploring the card (using pkcs15-tool)
- while trying to use the token (using pkcs11-tool)
- while trying to solve the issue with "pintest",
  which I had to modify to even accept an empty PIN
  that would let the rest of the stack try the pinpad

While exploring the issue I found that the ASEPCOS card driver does not seem
to support the hackery required for using pinpads
(using reader->verify_pin() instead of transmitting the APDU verbatim).

Since I am not really into the OpenSC codebase I had a hard time fixing the issue,
although I do have partial patches that might serve as a starting point.

My devices:
- Athena ASECard Crypto
- Reiner SCT cyberJack RFID standard

Versions (all are distro packages from debian unstable):
pcsc-lite 1.8.11
opensc 0.14.0-1
pcsc-cyberjack / libifd-cyberjack 3.99.5final.sp05-2

**Comment by frankmorgner** [comment]
@promovicz please reopen the issue if it's still relevant.
