### ISSUE TITLE
pkcs11-tool: object usage - secret key + getSIGN

### ISSUE THREAD

**Issue by dlegaultbbry** [OpenSC/OpenSC#2851]
### Problem Description

Secret keys can also be used to sign such as HMAC/CMAC algorithms. Found while writing some tests related to HMAC implementation and testing with pkcs11-tool from the command line.

### Proposed Resolution

object printing code probably needs to change from !pub, to !pub || sec on this line: https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L5201

It should say:

Usage:      sign, verify

### Steps to reproduce

echo -n "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b" | xxd -r -p - > key.bin
pkcs11-tool --module=... --write-object key.bin --usage-sign --type secrkey --label hmackey --id 1234
Using slot 0 with a present token (0x0)
Created secret key:
Secret Key Object; Generic secret length 20
  VALUE:      0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b
  label:      hmackey
  ID:         1234
  Usage:      verify
  Access:     never extractable

### Logs

See above

**Comment by Jakuje** [comment]
Yes, this sounds as a reasonable change. Do you want to propose a PR with the change? It would be good to have this in the next release.

**Comment by dlegaultbbry** [comment]
Sure, let me prepare the change and I'll try to have it up this week.

**Comment by mouse07410** [comment]
> Yes, this sounds as a reasonable change. Do you want to propose a PR with the change? It would be good to have this in the next release.

No, this is not a reasonable change because MAC is not a signature. 

Read any modern cryptography textbook for a longer explanation.

**Comment by Jakuje** [comment]
Regardless what you write, in the PKCS#11 specification, MAC has Sign operation defined so I do not see a valid reason why the attribute should not be printed in the pkcs11-tool:

http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399398925

**Comment by dengert** [comment]
In addition, https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/csprd01/pkcs11-base-v3.0-csprd01.html#_Toc10472611  "4.10 Secret key objects" lists CKA_SIGN and CKA_VERIFY with "CK_TRUE if key supports verification (i.e., of authentication codes) where the signature is an appendix to the data9"

Footnote 9 says "Default value is token-specific, and may depend on the values of other attributes."
