### ISSUE TITLE
pkcs11-tool: CKO_SECRET_KET + CKA_ALWAYS_AUTHENTICATE

### ISSUE THREAD

**Issue by dlegaultbbry** [OpenSC/OpenSC#2852]
### Problem Description

Reading the 3.0 spec, this attribute is not mentioned under CKO_SECRET_KEY object types (only private key ones). The tool assumes that this value should always be present even for CKO_SECRET_KEY objects for operations like signing.

Example location of the check: https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L2299

### Proposed Resolution

Maybe the spec is unclear and it should mention this attribute for secret keys (would make sense since it's sensitive material).

Else the tool should check to see if the key type is secret and never query this attribute in that case. Alternatively, just set the attribute to false by default for secret keys when importing/creating them unless the user uses the --always-auth option.

### Steps to reproduce

```
echo -n "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b" | xxd -r -p - > key.bin
# pkcs11-tool --module=... --write-object key.bin --usage-sign --type secrkey --label hmackey --id 1234
echo -n "Hi There" | pkcs11-tool --module=... --sign --mechanism SHA256-HMAC --label hmackey | xxd -p -c 0
Using slot 0 with a present token (0x0)
Using signature algorithm SHA256-HMAC
warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x202)

warning: PKCS11 function C_GetAttributeValue(ALWAYS_AUTHENTICATE) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x202)

b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7
```

### Logs

See above for the spurious warnings about this attribute missing.

**Comment by dengert** [comment]
pkcs11-base-v3.0 "4.9 Private key objects" says:
"The CKA_ALWAYS_AUTHENTICATE attribute can be used to force re-authentication (i.e. force the user to provide a PIN) for each use of a private key." 

"Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key has been initiated (e.g. after C_SignInit).

Here is a possible fix. Compiles but not tested. 
[pkcs11-tool.diff.txt](https://github.com/OpenSC/OpenSC/files/12481136/pkcs11-tool.diff.txt)

What PKCS11 module are you using?

But are you suggesting it should work with  SHA256-HMAC where key is not CKO_PRIVATE_KEY
That question should be directed to:  

https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=pkcs11

**Comment by dlegaultbbry** [comment]
PKCS11 module is a homegrown one for QNX systems. The patch works fine.

Yes, I'm aware I can provide the feedback to the pkcs11 committee. Trying to search their list archives but the website is dead right now. I was just stating that in light of what I read in the spec, the behaviour of the tool seemed wrong. The alternative being that perhaps I had read the spec wrong.

After looking some more, I did find this thread from 11-15 years ago (on which you have commented) which states this exact problem that ALWAYS_AUTHENTICATE isn't specified for secret keys and perhaps other operations. https://bugzilla.mozilla.org/show_bug.cgi?id=357025

**Comment by Jakuje** [comment]
@dengert do you want to submit a PR with the changes proposed in the previous comment? @dlegaultbbry do they solve your issue?

**Comment by dlegaultbbry** [comment]
I'm fine with the patch and it fixes my issue.

**Comment by dengert** [comment]
> @dengert do you want to submit a PR with the changes proposed in the previous comment? 

OK, submitted https://github.com/OpenSC/OpenSC/pull/2864
