### ISSUE TITLE
how to disable secure messaging for epass2003?

### ISSUE THREAD

**Issue by sachindia86** [OpenSC/OpenSC#2856]
### Problem Description

I want to disable secure messaging for epass2003 token. 
I have tried to undef macro ENABLE_SM & ENABLE_OPENSSL in configure.ac but epass2003 driver is getting disabled from compilation altogether.

This is the bug in the epass2003 driver.

### Steps to reproduce
Just disable the secure messagaing from configure.ac and build.

**Comment by popovec** [comment]
If epass2003 announces support for SM (see APDU get capabilities 00 CA 01 86, look for TAG 0x84 in the response), it is necessary to use it, otherwise mutual auth will not take place and the token will reject any operation.

**Comment by dengert** [comment]
Why are you trying to turn off Secure Messaging? 

If its for debugging, you could uses a debugger. Look at `epass2003_sm_wrap_apdu`  the input apdu  is `plain`  . And look at  `epass2003_sm_unwrap_apdu` where it returns `plain`.  You could also add some calls to  `sc_dump_hex`. `grep` for `sc_debug(ctx, SC_LOG_DEBUG_SM` in the code to see how to do this.

**Comment by sachindia86** [comment]
Thanks @popovec @dengert for the guidance. I will try.
