### ISSUE TITLE
opensc-notify: is there a way to integrate with ssh-agent (on macos)

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#2857]
### Problem Description

The opensc-notify tool responds to smartcard insertion and removal.

Is there a way for opensc-notify to trigger ssh-add -s on smartcard insertion, with the option of prompting the end user for a PIN interactively in an easy way.

The need is for an ordinary non technical user to use a smartcard to access sftp over Mountain Duck.

**Comment by frankmorgner** [comment]
I just noticed that you're on macOS. Here, we are using an external program to display the notifications ([`/Library/OpenSC/Applications/NotificationProxy.app/Contents/MacOS/NotificationProxy`](https://github.com/frankmorgner/NotificationProxy)). I'm not sure how the macOS infrastructure (`NSUserNotification`) integrates into SSH.

In OpenSC, we could certainly use the notification code for forking and execl into a seperate program to allow custom scripts for showing notifications. That, however, would require a change in the existing code.

**Comment by Jakuje** [comment]
The problem with ssh-agent is that it can not handle card removal. The bug with patches already celebrated his 5th birthday:

https://bugzilla.mindrot.org/show_bug.cgi?id=2890

With this implemented, the agent should use the askpass for the pin when the card is reinserted and asked to be used, but it was largely ignored by the upstream developers. If you find this functinality useful, please, comment in the upstream issue so it can get more attention.
