### ISSUE TITLE
openpgp-tool-helpers.c missing include for strnlen

### ISSUE THREAD

**Issue by jmroot** [OpenSC/OpenSC#2863]
### Problem Description

On a system that doesn't have strnlen:
```
openpgp-tool-helpers.c:200:24: warning: implicit declaration of function 'strnlen' is invalid in C99 [-Wimplicit-function-declaration]
                size_t used_length = strnlen(src, length) >> 1;
                                     ^
```

### Proposed Resolution

Looks like it needs to `#include "common/compat_strnlen.h"` like other files in the repo that use `strnlen`.

### Steps to reproduce

Build on a system that doesn't have strnlen.

**Comment by Jakuje** [comment]
Thank you for the report. I think you are right and this is overlook as most of the systems we use have `strnlen`.

Two things:
 * Do you have some system that does not have `strnlen` that could be integrated to the CI?
 * Do you want to submit a PR with your proposed change?

**Comment by jmroot** [comment]
> * Do you have some system that does not have `strnlen` that could be integrated to the CI?

Unfortunately no.

> * Do you want to submit a PR with your proposed change?

Sure.
