### ISSUE TITLE
Generate Key Pair command?

### ISSUE THREAD

**Issue by nshah2588** [OpenSC/OpenSC#2879]
Hello,

We are using the PKCS11-tool to generate a key pair and as per our understanding the command to generate a Key pair is:

pkcs11-tool -k

However, when we run it we are getting this error:

`/Documents/OpenSC$ pkcs11-tool -k
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GenerateKeyPair failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)
Aborting.
`
Hence we tried other options to add a PIN but even that failed

`pkcs11-tool -p $PIN -k
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GenerateKeyPair failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)
Aborting.
`
Not sure what we are missing.
Can you please advice?

**Comment by popovec** [comment]
What card do you use?

Example with MyEID card:

`````
$ pkcs11-tool -k --key-type RSA:2048 -l
Using slot 0 with a present token (0x0)
Logging in to "MyEID".
Please enter User PIN: 
Key pair generated:
Private Key Object; RSA 
  label:      Private Key
  ID:         fb537f1d7907d2ff576962fb869e3eee7e7ed384
  Usage:      decrypt, sign
  Access:     none
Public Key Object; RSA 2048 bits
  label:      Private Key
  ID:         fb537f1d7907d2ff576962fb869e3eee7e7ed384
  Usage:      encrypt, verify
  Access:     none
`````

**Comment by Jakuje** [comment]
At least the `--login` switch will be needed as already pointed out by Peter. But card management and enrollment depends very much on the card and driver, which means you might need to use so-pin or completely different command to create the keys. Please, provide more information about your card, driver used or debug logs as recommended in the issue template.

**Comment by nshah2588** [comment]
Thank you! We are looking into it.

**Comment by Jakuje** [comment]
@nshah2588 did you get any progress on this issue? Did If you want us to look into that further, please provide more information, at least the card type and what results you get with `--login`.

**Comment by nshah2588** [comment]
`The ATR is matched by the card-entersafe.c match routine and so the card driver is  card-entersafe.cand the card type is 19004 which matchesSC_CARD_TYPE_ENTERSAFE_FTCOS_EPASS2003which is only listed incard-epass2003.c.  grep SC_CARD_TYPE_ENTERSAFE_FTCOS_EPASS2003 src/libopensc/* `

Thank you for pointing it out. We were not aware of the that the card type is 19004 which matches with EPASS2003. We have not modified the below. In fact we noticed it only now when you have mentioned it

'SC_CARD_TYPE_ENTERSAFE_BASE = 19000'

We have made some modifications in the entersafe file to temporarily accept our card as an entersafe device. We made several modifications to the entersafe.profile and the pkcs15.profile files as well again to force the entersafe driver to work with our card.

Our opensc.conf is an empty file

Yes we forced the enterface driver

Yes we made some modifications mainly around the file IDs in the card-enterface.c

We really wanted to use the entersafe driver and not the card-epass2003.c since it more closely mimics the behaviour of our card

**Comment by dengert** [comment]
One more thing, set `debug = 8`  so it will show everything:
from `log.h`
```
        SC_LOG_DEBUG_VERBOSE_TOOL = 1,  /* tools only: verbose */
        SC_LOG_DEBUG_VERBOSE,           /* helps users */
        SC_LOG_DEBUG_NORMAL,            /* helps developers */
        SC_LOG_DEBUG_RFU1,              /* RFU */
        SC_LOG_DEBUG_SM,                /* secure messaging */
        SC_LOG_DEBUG_ASN1,              /* asn1.c */
        SC_LOG_DEBUG_MATCH,             /* card matching */
        SC_LOG_DEBUG_PIN,               /* PIN commands */
```

**Comment by nshah2588** [comment]
Dear @dengert 

Attached is the log with debug=8

[debug.log](https://github.com/OpenSC/OpenSC/files/13042940/debug.log)

Let me know if you need anything else from our end to help with the PIN verification issue.

**Comment by dengert** [comment]
https://smartcard-atr.apdu.fr/parse?ATR=3b%3Ad5%3A18%3Aff%3A81%3A91%3Afe%3A1f%3Ac3%3A80%3A73%3Ac8%3A21%3A10%3A0a repots your ATR as: "ComSign digital signature card (eID) https://www.comsign.co.uk/" You may want to add historical bytes to make it unique.

Your mods must have added your ATR as  type "SC_CARD_TYPE_ENTERSAFE_FTCOS_EPASS2003" you should define in cards.h a new SC_CARD_TYPE_ENTERSAFE_* for example SC_CARD_TYPE_ENTERSAFE_AMBIMAT" so you can use it in "if" statement cards other cards will continue to work with the driver. If you have many changes consider defining a new card driver. 

Without seeing your changes and  documentation on the card/applet there is not much anyone one can do. (You have appeared to have dropped the "/* MSE */" code from `entersafe_gen_key`.) 

If your intent is to submit your changes to OpenSC, then use github and make your fork of OpenSC visible to others. 

If your intent is to modify OpenSC and distribute a modified version, read and abide by the licenses in OpenSC. 

It the later is the case, you may want to hire someone else to assist you.

**Comment by nshah2588** [comment]
Dear @dengert 

The ATR is a generic ATR for a card from NXP. So it is possible someone must have recorded it as a "ComSign digital signature card (eID)" We will see how to change the Historical bytes of the ATR on our end.

Yes we do intend to define a new card driver at some point in the near future. At present we are only working towards proving a concept that our card follows the basic principles of PKCS11 and PKCS15 and can work with a MW.

We are not thinking of distribution at this time whether we will distribute it via OpenSC or in our own way. We are expecting our partners to deal with that. We only want a quick demonstration of the capabilities of the card we have using a MW.

As far as the MSE goes our card works a bit differently. We don't perform the MSE DST until we have the key pair generated and we associate the MSE DST with the generated private key as should be the case. Entersafe driver sets the MSE prior to generating the key pair.

Hope this helps understand where we are coming from.

I would sincerely request that you do help us move the inclusion of PIN authentication.

**Comment by Jakuje** [comment]
As already mentioned by Doug, without the applet/card specification and without seeing your changes to the code, this is very hard to help. The `Security status not satisfied` error coming from the card/chip/applet is generic error, usually reporting wrong ACL configured or that the ACL is not satisfied for the given operation. Again, based on the ACLs, the card might need a user PIN or different kind of authentication (SO pin?, external authentication?, secure messaging?).

**Comment by frankmorgner** [comment]
If I understand your comments, @nshah2588, in https://github.com/OpenSC/OpenSC/issues/2580 correctly, then you are actually talking about some new card. When you have implemented basic support for that card, that can be verified with pkcs15-tool or opensc-tool, please let us know so we can review your code.
