### ISSUE TITLE
Generate .dll, .so and .dylib

### ISSUE THREAD

**Issue by nshah2588** [OpenSC/OpenSC#2883]
Hello,

We made some modifications to the OpenSC code to suit our requirements and we are able to compile and run it fine using these commands:

`./configure --prefix=/usr --sysconfdir=/etc/opensc

sudo make

sudo make install`

However, we want to be able to generate the .dll, .so and .dylib files as well.

Can you please advice on where can we find the steps to do that?

**Comment by dengert** [comment]
If you submit your changes as a Pull Request,  Windows MSI and MacOS DMG files are created automatically on github and you changes will be kept up to date.

So all you need are:
https://github.com/OpenSC/OpenSC/blob/master/README.md
https://github.com/OpenSC/OpenSC/wiki/
https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start
https://github.com/OpenSC/OpenSC/wiki/macOS-Quick-Start
https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-on-Unix-flavors

If you want to do it yourself see:
https://github.com/OpenSC/OpenSC/wiki#license
https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows
https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Cygwin

And to see how the Windows and  MacOS files are built see:
https://github.com/OpenSC/OpenSC/tree/master/.github

**Comment by nshah2588** [comment]
Hello,

I followed the steps on Compiling-on-Cygwin and got stuck at one of the steps:

`/usr/src/opensc_mw/OpenSC
$ ./configure --disable-strict
**configure: error: Tests required, but cmocka is not available**
`

**Comment by nshah2588** [comment]
Thank you!
