### ISSUE TITLE
Signing documents with more than one token device on the same machine

### ISSUE THREAD

**Issue by ali7ussein** [OpenSC/OpenSC#2890]
### Problem Description

We have a machine with two signing token devices attached always sign function uses only one of the two devices while the login function is run on the other one so every time it tries to sign to the same token, Do you have a solution for this issue.

**Comment by frankmorgner** [comment]
If multiple tokens are available, the choice is up to the applications which to choose. This choice can typically be configured by selecting the signing certificate (which implies usage of a particular token). You should contact the vendor of your signing application or your login functionality respectively. What applications are you using?

**Comment by ali7ussein** [comment]
Hi @frankmorgner 

Many thanks for your quick response, We updated the signing certificate selection from the application side and every thing is working fine now.

Best Regards
