### ISSUE TITLE
flag SC_ALGORITHM_ECDSA_HASH_NONE 

### ISSUE THREAD

**Issue by popovec** [OpenSC/OpenSC#2896]
### Problem Description

Can someone explain to me the difference between SC_ALGORITHM_ECDSA_HASH_NONE and SC_ALGORITHM_ECDSA_RAW ? I looked at all the driver cards that support elliptic encryption and it seems to me that these two flags are exactly the same. 

In case it is a duplication, I would like to remove the SC_ALGORITHM_ECDSA_HASH_NONE flag.

src/pkcs11/framework-pkcs15.c, line 6108: 
`````
        if (flags & SC_ALGORITHM_ECDSA_RAW) {
                mt = sc_pkcs11_new_fw_mechanism(CKM_ECDSA, &mech_info, CKK_EC, NULL, NULL, NULL);
                if (!mt)
                        return CKR_HOST_MEMORY;
                if (flags & SC_ALGORITHM_ECDSA_HASH_NONE) {
                        rc = sc_pkcs11_register_mechanism(p11card, mt, &registered_mt);
                        sc_pkcs11_free_mechanism(&mt);
                        if (rc != CKR_OK)
                                return rc;
                }

#ifdef ENABLE_OPENSSL
                /* if card supports RAW add sign_and_hash using RAW for mechs  card does not support */
                sc_pkcs11_mechanism_type_t *sign_type = mt ? mt : registered_mt;
                if (flags & SC_ALGORITHM_ECDSA_RAW) {
`````
There is no reason to test `if (flags & SC_ALGORITHM_ECDSA_HASH_NONE) {` if we know that the card supports ECDSA_RAW.

Most card drivers set both flags, however, the card-npa.c driver only sets SC_ALGORITHM_ECDSA_RAW, which results in the CKM_ECDSA mechanism not being registered??  Only CKM_ECDSA_SHA* mechanisms are registered. 

In this code, at the same time, a duplicate condition for the `if (flags & SC_ALGORITHM_ECDSA_RAW)' test was created, which can also be removed.

The code from the drivers also documents the duplication well, for example:
src/libopensc/card-sc-hsm.c
`````
   } else if (env->algorithm_flags & SC_ALGORITHM_ECDSA_HASH_NONE) {
                        priv->algorithm = ALGO_EC_RAW;
                } else if (env->algorithm_flags & SC_ALGORITHM_ECDSA_HASH_SHA1) {
                        priv->algorithm = ALGO_EC_SHA1;
                } else if (env->algorithm_flags & SC_ALGORITHM_ECDSA_HASH_SHA224) {
                        priv->algorithm = ALGO_EC_SHA224;
                } else if (env->algorithm_flags & SC_ALGORITHM_ECDSA_HASH_SHA256) {
                        priv->algorithm = ALGO_EC_SHA256;
                } else if (env->algorithm_flags & SC_ALGORITHM_ECDSA_RAW) {
                        priv->algorithm = ALGO_EC_RAW;
`````

**Comment by mouse07410** [comment]
I don't know - just guessing. But perhaps, the difference is that one provides only the signature itself (aka, NONE), and the other one provides the ASN.1 block with hash OID being NULL?

**Comment by popovec** [comment]
The result of ECDSA is still only the R and S coordinate ... neither digest info nor any type of padding is used there.. Yes, the signature can be further changed according to the required output format (man pkcs11-tool, --signature-format Format for ECDSA signature : rs (default), sequence, openssl.) but this does not apply to the flags we use in src/libopensc/pkcs15-sec.c, src/pkcs11/framework-pkcs15.c or in the drivers of individual cards.

**Comment by dengert** [comment]
> Can someone explain to me the difference between SC_ALGORITHM_ECDSA_HASH_NONE and SC_ALGORITHM_ECDSA_RAW ? 

Some of the  `_HASH_` flags are used by RSA and  ECDSA  and other algos.  For SC_ALGORITHM_RSA_RAW and  SC_ALGORITHM_RSA_HASH_NONE there is a difference because or digests and padding issues.

But as you point out: " I looked at all the driver cards that support elliptic encryption and it seems to me that these two flags are exactly the same." 

opensc.h:
```
#define SC_ALGORITHM_RSA_RAW            0x00000001
#define SC_ALGORITHM_RSA_HASH_NONE      0x00000100 /* only applies to PKCS1 padding */
#define SC_ALGORITHM_RSA_HASHES         0x0001FF00

#define SC_ALGORITHM_ECDSA_RAW          0x00100000
#define SC_ALGORITHM_ECDSA_HASH_NONE            SC_ALGORITHM_RSA_HASH_NONE
#define SC_ALGORITHM_ECDSA_HASH_SHA1            SC_ALGORITHM_RSA_HASH_SHA1
#define SC_ALGORITHM_ECDSA_HASH_SHA224          SC_ALGORITHM_RSA_HASH_SHA224
#define SC_ALGORITHM_ECDSA_HASH_SHA256          SC_ALGORITHM_RSA_HASH_SHA256
#define SC_ALGORITHM_ECDSA_HASH_SHA384          SC_ALGORITHM_RSA_HASH_SHA384
#define SC_ALGORITHM_ECDSA_HASH_SHA512          SC_ALGORITHM_RSA_HASH_SHA512
#define SC_ALGORITHM_ECDSA_HASHES               (SC_ALGORITHM_ECDSA_HASH_SHA1 | \
                                                         SC_ALGORITHM_ECDSA_HASH_SHA224 | \
                                                         SC_ALGORITHM_ECDSA_HASH_SHA256 | \
                                                         SC_ALGORITHM_ECDSA_HASH_SHA384 | \
                                                         SC_ALGORITHM_ECDSA_HASH_SHA512)
```

When card driver in `*_init`  sets flags with `SC_ALGORITHM_ECDSA_HASH_SHA*` it says it can do that hash on card (or driver) When pkcs11-framework.c looks at the flags, it is trying to say what hashes can be done in software outside the card driver.  

>Most card drivers set both flags, however, the card-npa.c driver only sets SC_ALGORITHM_ECDSA_RAW, which results in the CKM_ECDSA mechanism not being registered?? Only CKM_ECDSA_SHA* mechanisms are registered.

That would then indicate to caller card can only accept data that is hashed by OpenSC. Looks like 
a bug in pkcs11-framework.c which should set CKM_ECDSA if  SC_ALGORITHM_ECDSA_RAW is set. 

So I thing a PR to remove SC_ALGORITHM_ECDSA_HASH_NONE could be done. But would suggest after 0.24.0  which appears to be working without OK.

**Comment by frankmorgner** [comment]
@popovec , did this answer your question?

**Comment by popovec** [comment]
I'm closing this issue. When I find some free time, I'll prepare a PR, and any ambiguities will be discussed in this PR.
