### ISSUE TITLE
Fail to logon Windows 11 with opensc-minidriver.dll(0.23.0).

### ISSUE THREAD

**Issue by CooperTsai** [OpenSC/OpenSC#2917]
### Problem Description
I have a PIV card that can be used to log in to Windows 10 with opensc-minidriver.dll. However, when I attempt to log in to Windows 11, WinLogonUI displays the certificates. After entering the PIN, I encounter the following error message: 'This smart card could not be used. Additional details may be available in the system event log. Please report this error to your administrator.' I've noticed Event ID 4625 and 5 related to smart card logon in the event log.

###### Event ID 4625:
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          10/25/2023 10:24:44 AM
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      DESKTOP-GFM3C74.test
Description:
An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		DESKTOP-GFM3C74$
	Account Domain:		IDEM
	Logon ID:		0x3E7

Logon Type:			2

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		
	Account Domain:		-

Failure Information:
	Failure Reason:		An Error occured during Logon.
	Status:			0xC000006D
	Sub Status:		0xC0000321

Process Information:
	Caller Process ID:	0x74c
	Caller Process Name:	C:\Windows\System32\svchost.exe

Network Information:
	Workstation Name:	DESKTOP-GFM3C74
	Source Network Address:	127.0.0.1
	Source Port:		0

Detailed Authentication Information:
	Logon Process:		User32 
	Authentication Package:	Negotiate
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon request fails. It is generated on the computer where access was attempted.

The Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).

The Process Information fields indicate which account and process on the system requested the logon.

The Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The authentication information fields provide detailed information about this specific logon request.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.
								
###### Event ID 5:
Log Name:      Application
Source:        Smart Card Logon
Date:          10/25/2023 10:24:44 AM
Event ID:      5
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-GFM3C74.test
Description:
An error occurred while retrieving a digital certificate from the inserted smart card. Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

### Proposed Resolution
opensc-minidriver.dll should support Windows 11 smart card logon.

### Steps to reproduce
1. Use a PIV card which can logon windows.
2. Use this card to logon Windows 11.
3. WinLogUI shows verify PIN UI
4. Enter PIN
5. Show error: "This smart card could not be used. Additional details may be available in the system event log. Please report this error to your administrator."

**Comment by dengert** [comment]
Installing the OpenSC minidriver does not register the PIV cards to use OpenSC.  Microsoft has built in PIV driver and most (if not all) PIV card vendors provide their own PIV minidriver. You should not need to use the OpenSC minidriver for PIV.   

Use regedit.exe and look at Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais
 The sub directores:
 "PIV Device ATR Cache" lists the ATRs of PIV cards that are ussing the built in Microsoft minidriver.
 "SmartCards" lists the ATRs and ATR Masks and "80000001" lists the minidriver that will be used.   
  The OpenSC minidriver would look like: "C:\Program Files\OpenSC Project\OpenSC\minidriver\opensc-minidriver.dll"

 "Identity Device (Microsoft Generic Profile)" and "Identity Device (NIST SP 800-73 [PIV])" are Microsoft builtin PIV driver and have  "80000001"    "C:\Windows\System32\msclmd.dl"

With whatever minidriver you are using, "An error occurred while retrieving a digital certificate from the inserted smart card. Windows cannot verify the digital signature for this file." sounds like  your administrator needs to install the CA or intermediate CA certificates that signed the certificate that is not trusted.

**Comment by frankmorgner** [comment]
What's the output of `certutil -scinfo`? this should show whether the OpenSC minidriver is used and it may show some problems with the certificates or with the key verification.

**Comment by CooperTsai** [comment]
I'm using Windows 11. When I run 'certutil -scinfo,' it shows errors, while Windows 10 has different errors.
When using the same key with the same certificate, Windows 10 can log into the system, but Windows 11 cannot.

### Windwos 11 'certutil -scinfo,' error info:
================ Certificate 0 ================
--- Reader: VMware Virtual USB CCID 0
---   Card: PIV Key
Provider = Microsoft Smart Card Key Storage Provider
Key Container = 00000000000000010000000000000000

Serial Number: 2b0000007297e5bb2e0cc456b5000000000072
Issuer: CN=TESTCA-CA, DC=TEST, DC=TEST
 NotBefore: 10/17/2023 11:32 PM
 NotAfter: 10/16/2024 11:32 PM
Subject: CN=cooper, CN=Users, DC=TEST, DC=TEST
Non-root Certificate
Template: Template-New
Cert Hash(sha1): f5598fc2c9212b717f83364186131bd37a27893f

Performing  public key matching test...
Public key matching test succeeded
  Key Container = 00000000000000010000000000000000
  Provider = Microsoft Smart Card Key Storage Provider
  ProviderType = 0
  Flags = 1
    0x1 (1)
  KeySpec = 0 -- XCN_AT_NONE
Private key verifies
Microsoft Smart Card Key Storage Provider: KeySpec=0
AES256+RSAES_OAEP(RSA:CNG) test FAILED: An internal consistency check failed. 0x80100001 (-2146435071 SCARD_F_INTERNAL_ERROR)


### Windwos 10 'certutil -scinfo,' has different error:
================ Certificate 0 ================
--- Reader: VMware Virtual USB CCID 0
---   Card: PIV Key
Provider = Microsoft Smart Card Key Storage Provider
Key Container = 00000000000000010000000000000000

Serial Number: 2b0000007297e5bb2e0cc456b5000000000072
Issuer: CN=TESTCA-CA, DC=TEST, DC=TEST
 NotBefore: 10/17/2023 11:32 PM
 NotAfter: 10/16/2024 11:32 PM
Subject: CN=cooper, CN=Users, DC=TEST, DC=TEST
Non-root Certificate
Template: Template-New
Cert Hash(sha1): f5598fc2c9212b717f83364186131bd37a27893f

Performing  public key matching test...
Public key matching test succeeded
  Key Container = 00000000000000010000000000000000
  Provider = Microsoft Smart Card Key Storage Provider
  ProviderType = 0
  Flags = 1
    0x1 (1)
  KeySpec = 0 -- XCN_AT_NONE
Private key verifies
Microsoft Smart Card Key Storage Provider: KeySpec=0
AES256+RSAES_OAEP(RSA:CNG) test FAILED: Cannot find the certificate and private key to use for decryption. 0x8009200c (-2146885620 CRYPT_E_NO_DECRYPT_CERT)

---

The question is, why can Windows 10 log in, but Windows 11 cannot?
Do you have any suggestions for this issue?

**Comment by dengert** [comment]
It looks like you did not create a 9D key and certificate:  W10 says: `AES256+RSAES_OAEP(RSA:CNG) test FAILED: Cannot find the certificate and private key to use for decryption. 0x8009200c (-2146885620 CRYPT_E_NO_DECRYPT_CERT)`

But W11 says: `AES256+RSAES_OAEP(RSA:CNG) test FAILED: An internal consistency check failed. 0x80100001 (-2146435071 SCARD_F_INTERNAL_ERROR)`

W11 may have improved login security by using the 9D key and certificate; 

Did you look at the registry to see what minidriver is being used? 

Certutil reports: "Card: PIV Key".  This is taken from the registry. I don't think OpenSC  ever use "PIV Key" in the registry.
Did you manually edit the registry to add this? 

If you did please provide a regedit export of the changes you made.

On my Windows 11 with a PIVKey C910 card from Taglio regedit shows:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\PIVKey Feitian (E0)]
"ATRMask"=hex:ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,\
  ff
"80000001"="tagliov70px.dll"
"ATR"=hex:3b,fc,18,00,00,81,31,80,45,90,67,46,4a,00,64,16,06,f2,72,7e,00,e0
"Smart Card Key Storage Provider"="Microsoft Smart Card Key Storage Provider"
"Crypto Provider"="Microsoft Base Smart Card Crypto Provider"
```
Note the minidriver they use is "tagliov70px.dll"
OpenSC minidriver would be: "C:\Program Files\OpenSC Project\OpenSC\minidriver\opensc-minidriver.dll"

How did you create the certificates?
Did you create a CHUI PIV object? OpenSC uses this to create a serial number as NIST PIV docs says nothing about a card serial number. `Key Container = 00000000000000010000000000000000` should be unique. This looks like it defaulted  to 0 as no serial number was available.

**Comment by frankmorgner** [comment]
Maybe your smart card reader has a problem as indicated by the return code in certutil, see
https://stackoverflow.com/questions/61745827/smart-card-validation-pin-error-0x80100001

**Comment by frankmorgner** [comment]
The other error code 0x8009200c, as pointed out by Doug, indicates that the certificate for verifying the decryption is missing.

In any case, the problem appears to be with the configuration of your card or reader, not with OpenSC

**Comment by Antimatterr** [comment]
hey @frankmorgner I was facing this issue while running `certutil.exe -scinfo`

"The Microsoft Smart Card Resource Manager is not running.
WaitForSingleObject: Service is in an unknown state.
CertUtil: -SCInfo command FAILED: 0x80070102 (WIN32/HTTP: 258 WAIT_TIMEOUT)
CertUtil: The wait operation timed out."

**Comment by frankmorgner** [comment]
> "The Microsoft Smart Card Resource Manager is not running. 

please read the error message and start the missing service

**Comment by redflitzi** [comment]
I have the same problem on a github Windows-Runner 2022.

But which one exactly is the missing service?

I did:
```     
Set-Service SCardSvr -StartupType Manual
net start SCardSvr
Set-Service ScDeviceEnum -StartupType Manual
net start ScDeviceEnum
```
I got:
```
The Smart Card service is starting.
The Smart Card service was started successfully.

The Smart Card Device Enumeration Service service is starting.
The Smart Card Device Enumeration Service service was started successfully.
```
and then I did

`CertUtil -SCInfo`

and then got 
```
The Microsoft Smart Card Resource Manager is not running.
WaitForSingleObject: Service is in an unknown state.
CertUtil: -SCInfo command FAILED: 0x80070102 (WIN32/HTTP: 258 WAIT_TIMEOUT)
CertUtil: The wait operation timed out.
```
Apparently the same error as @Antimatterr .

Is there anything else that might be missing, can be checked, or done?
Thank you very much!
