### ISSUE TITLE
libopensc.so not found when using non-default install prefix

### ISSUE THREAD

**Issue by jclc** [OpenSC/OpenSC#2923]
### Problem Description

Building from source and installing with a non-default prefix such as /usr/local makes the binaries (at least pkcs11-tool) not link properly to the libopensc.so library. libopensc.so is properly installed to /usr/local/lib. Adding symbolic links to /usr/lib, /usr/lib64 and /usr/local/bin does not help.

Using the default prefix /usr works properly.

Tested on Rocky Linux 8

### Steps to reproduce

```
# ./configure --prefix=/usr/local --sysconfdir=/etc/opensc
# make
# make install
```

### Logs
```
[root@machine opensc-0.23.0]# ldd /usr/local/bin/pkcs11-tool
        linux-vdso.so.1 (0x00007ffce3b27000)
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007fe8bab18000)
        libopensc.so.8 => not found
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fe8ba517000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fe8ba2f7000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007fe8b9f32000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007fe8b9d1a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe8bb002000)
```
(note: not the exact print since reconfiguring and rebuilding opensc cleared the terminal history, recreated from memory)

**Comment by dengert** [comment]
I regularly build OpenSC on against multiple versions of OpenSSL  and set `PREFIX=/opt/ossl-n.n.n` and configure with `--prefix=$PREFIX`  
But  also set  `LDFLAGS="$LDFLAGS -Wl,-rpath,$PREFIX/lib"` on linux. Other OS may use `-R`

**Comment by frankmorgner** [comment]
use LD_LIBRARY_PATH=/usr/local/lib or edit your /etc/ld.so.conf accordingly
