### ISSUE TITLE
OpenSC 0.24.0 broken on Windows 10 and 11 both at 22H2 for some devices

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#2964]
### Problem Description
Using `OpenSC-0.24.0_win64.msi` on Windows 11 Pro 22H2 or Windows 10 Pro 22H2  with SC-HSM device fails when using  
 `certutil -v -scinfo` or  `pkcs11-tool -O`

This appears to be the same problem as https://github.com/OpenSC/OpenSC/issues/2944 when building with  CygWin. And may apply to any device which uses extended APDUs.

May have been introduced in aadd82bb07  or  a06abbf5a7 where  `rv = gpriv->SCardControl(card_handle, CM_IOCTL_GET_FEATURE_REQUEST, NULL, 0, buf, sizeof(buf), &rcount);` does not return any features. With #2944 CygWin the above fails with rv = 0x00000001, in my tests rv = 0 and rcount = 0.

@frankmorgner I recall you saying Microsoft has dropped PIN PAD  readers. Could they have dropped more then that?

### Proposed Resolution

Circumvention:  edit  C:\Program Files\OpenSC Project\OpenSC\opensc.conf to contain a "reader_driver pcsc" section something like:
  
```
app default {
	# debug = 7;
	# debug_file = c:\tmp\opensc-debug.txt;
	 
        reader_driver pcsc {
                max_send_size = 65535;
                max_recv_size = 65536;
        }
}
```

### Steps to reproduce

 `certutil -v -scinfo` and `pkcs11-tool -O` both fail. 

### Logs
P:6768; T:16636 2023-12-18 08:48:08.977 [opensc-pkcs11] ===================================
P:6768; T:16636 2023-12-18 08:48:08.977 [opensc-pkcs11] OpenSC version: 0.24.0
P:6768; T:16636 2023-12-18 08:48:08.977 [opensc-pkcs11] Configured for opensc-pkcs11 (C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe)
P:6768; T:16636 2023-12-18 08:48:08.977 [opensc-pkcs11] PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:6768; T:16636 2023-12-18 08:48:08.978 [opensc-pkcs11] reader-pcsc.c:1399:pcsc_detect_readers: called
P:6768; T:16636 2023-12-18 08:48:08.978 [opensc-pkcs11] Probing PC/SC readers
P:6768; T:16636 2023-12-18 08:48:08.979 [opensc-pkcs11] Establish PC/SC context
P:6768; T:16636 2023-12-18 08:48:08.982 [opensc-pkcs11] Adding new PC/SC reader 'SCM Microsystems SCx35xx v2.0 USB SC Reader 0'
P:6768; T:16636 2023-12-18 08:48:08.982 [opensc-pkcs11] SCM Microsystems SCx35xx v2.0 USB SC Reader 0 check
P:6768; T:16636 2023-12-18 08:48:08.982 [opensc-pkcs11] current  state: 0x00010422
P:6768; T:16636 2023-12-18 08:48:08.983 [opensc-pkcs11] previous state: 0x00000000
P:6768; T:16636 2023-12-18 08:48:08.983 [opensc-pkcs11] card present, changed
P:6768; T:16636 2023-12-18 08:48:09.133 [opensc-pkcs11] SCM Microsystems SCx35xx v2.0 USB SC Reader 0:SCardConnect(SHARED): 0x00000000
P:6768; T:16636 2023-12-18 08:48:09.133 [opensc-pkcs11] reader-pcsc.c:1146:detect_reader_features: called
P:6768; T:16636 2023-12-18 08:48:09.133 [opensc-pkcs11] Requesting reader features ... 
P:6768; T:16636 2023-12-18 08:48:09.135 [opensc-pkcs11] Assuming that the reader supports sending short length APDUs only
P:6768; T:16636 2023-12-18 08:48:09.135 [opensc-pkcs11] Assuming that the reader supports receiving short length APDUs only

**Comment by frankmorgner** [comment]
> @frankmorgner I recall you saying Microsoft has dropped PIN PAD readers.

They simply don't support the CCID extension for PIN entry (and never did).

Regarding SCardControl, I think it returns `0x00000001` if one of the input parameters are bad (see https://github.com/LudovicRousseau/pyscard/issues/19 for a similar issue) - in this case I assume it doesn't know `GET_FEATURE_REQUEST`. But as said before, we need more analyis, maybe with pyscard...

**Comment by dengert** [comment]
@frankmorgner
@LudovicRousseau 
 Using tip from  https://github.com/LudovicRousseau/pyscard/issues/19 with x86 version of `pkcs11-tool -O` 
shows:

```
2023-12-20 10:21:36.639 (Thread = 0x000054E0) - SCardControl( hCard = 0xEA010000 on reader "SCM Microsystems SCx35xx v2.0 USB SC Reader 0", dwControlCode = 0x00313520, lpOutBuffer = 0x00F3F298, nOutBufferSize = 256, lpBytesReturned = 0x00F3F284 ):
 Input command = 
 
2023-12-20 10:21:36.649 (Thread = 0x000054E0) - SCardControl Response   = 
 
 Duration = 1 ms
```
this looks correct, as on Windows dwControlCode is 0x0031<<16 | 3600<<2 but it looks like it is not returning anything.
