### ISSUE TITLE
Prevents gnupg to work with a smartcard/yubikey

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#2980]
Hello,

### Problem Description

I'm running on debian unstable. I've issue for a long time to use my gpg card and/or my yubikey to sign messages with gpg.

It seems that the problem comes from the opensc-pkcs11 module being loaded by GNOME

I need to restart pcscd to be able to use my gpg card.

I tried to use `ignored_readers` and `card_drivers` to ignore my yubikey but it seems that opensc is still locking it?

### Steps to reproduce

1.  Install the opensc package on debian
2. Reboot, and login in GNOME, `pkcs11-register` will add the module to the user configuration and browser (which is a good thing!)
3. Plug the yubikey
4. Run `gpg --card-status`

`gpg --card-status` complains that:
```
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device
```

### Logs

Is that a bug? Any advises here would be nice

**Comment by mouse07410** [comment]
Does it look like another burp of the exclusive open that GnuPG deamons do?

**Comment by bigon** [comment]
Yes maybe, but I would expect that if the reader is ignored, opensc wouldn't take a lock on it at all

**Comment by popovec** [comment]
When I tried to use MyEID card with gpg I found this page.. gpg can be used with any pkcs#11 token so it can also be used with Yubikey

https://sztsian.github.io/2022/02/20/Using-PKCS11-Token-With-GPG.html

**Comment by Jakuje** [comment]
One more option is to use `pcsc-shared` option to the scdaemon, that should prevent it using the exclusive access to the pcscd. Unless the Debian builds the gnupg with the bundled ccid driver which makes things much more ugly:

https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=configure.ac;h=c21138641f031d425fbca8b46a0471e77e51b644;hb=HEAD#l452

**Comment by bigon** [comment]
gnupg in debian is indeed built with the internal ccid driver, but it can be disabled with an option at runtime: https://sources.debian.org/src/gnupg2/2.2.40-1.1/doc/scdaemon.texi/?hl=273#L273

**Comment by bigon** [comment]
`pcsc-shared` doesn't seems to work either ?!

**Comment by frankmorgner** [comment]
Since this topic regularely comes up, I've created some information in the wiki:

https://github.com/OpenSC/OpenSC/wiki/GnuPG-and-OpenSC

Feel free to add or modify.

**Comment by bigon** [comment]
@frankmorgner Thanks for the document.

Unfortunately none of the options are working for me

But the real question for opensc, is why doesn't the `ignored_readers` or `card_drivers` without openpgp is still locking the reader

**Comment by frankmorgner** [comment]
Please add a log from OpenSC with ignored_readers and/or card_drivers set. I doubt that the options are ignored and/or that OpenSC is permanently locking the token.

**Comment by bigon** [comment]
OK I think I found something

If the yubikey is plugged when the process is starting/at boot and then I'm running `gpg --card-status`, it's working file: 
[opensc-debug_already_plugged.txt](https://github.com/OpenSC/OpenSC/files/13936264/opensc-debug_already_plugged.txt)

But if I'm plugging the Yubikey while opensc is already loaded by a process/after boot, it's not: 
[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/13936273/opensc-debug.txt)


Configuration of opensc is the following:

```
app default {
        debug = 9;
        debug_file = /home/bigon/opensc-debug.txt;
        ignored_readers = "Yubico YubiKey";
}
```

**Comment by bigon** [comment]
Thanks for your time, I'll continue to debug this and let you know

**Comment by bigon** [comment]
Hello

FTR: http://lists.infradead.org/pipermail/pcsclite-muscle/2024-January/001449.html
