### ISSUE TITLE
epass2003 RSA/2048 Failed to Generate Key on OSX, VirtualBOX

### ISSUE THREAD

**Issue by rvalle** [OpenSC/OpenSC#301]
Hi!
I am having trouble generating RSA 2048 keys on epass2003.
I get:
```
./pkcs15-init --auth-id 1 --generate-key rsa/2048 --key-usage sign,decrypt --label "MyRSAKey"
Using reader with a card: Feitian ePass2003 00 00
Failed to generate key: Transmit failed
```
The problem does not seem to happen when generating an RSA/1024 key

I am testing by building the tag: 0.14.0 and the HEAD
I have tried to include also configure with --enable-sm

Any idea what could be about?

**Comment by rvalle** [comment]
Here is the summary:

Token: epass2003

Working configurations:

*) Metal amd64 server
  - OS: Debian 7
  - OpenSC: 0.14.0
  - PCSC-LITE: 1.8.13
  - LIBCCID: 1.4.18

*) Metal arm6 server (Raspberry PI)
  - OS: Debian 7
  - OpenSC: 0.14.0
  - PCSC-LITE: 1.8.13
  - LIBCCID: 1.4.18

Failing Configurations:

*) Metal OSX (Macbook Pro late 2013)
  - OS: OSX 10.9 Mavericks
  - OpenSC: 0.14.0

*) Virtual amd64 server:
  - HOST OS: OSX 10.9.5 
  - HOST HW: MacBook Pro, late 2013.
  - Hypervensor: VirtualBOX 4.3.20
  - GUEST OS: Debian 7.
  - OpenSC: 0.14.0
  - PCSC-LITE: 1.8.13
  - LIBCCID: 1.4.18

**Comment by dengert** [comment]
Looks like a problem with the MAC version of pcscd and long operations...

I have no way to test this, but VirtualBox runs well under Windows 7


On 1/2/2015 1:24 AM, Rafael wrote:
> Here is the summary:
>
> Token: epass2003
>
> Working configurations:
>
> *) Metal amd64 server
>
>   * OS: Debian 7
>   * OpenSC: 0.14.0
>   * PCSC-LITE: 1.8.13
>   * LIBCCID: 1.4.18
>
> *) Metal arm6 server (Raspberry PI)
>
>   * OS: Debian 7
>   * OpenSC: 0.14.0
>   * PCSC-LITE: 1.8.13
>   * LIBCCID: 1.4.18
>
> Failing Configurations:
>
> *) Metal OSX (Macbook Pro late 2013)
>
>   * OS: OSX 10.9 Mavericks
>   * OpenSC: 0.14.0
>
> *) Virtual amd64 server:
>
>   * HOST OS: OSX 10.9.5
>   * HOST HW: MacBook Pro, late 2013.
>   * Hypervensor: VirtualBOX 4.3.20
>   * GUEST OS: Debian 7.
>   * OpenSC: 0.14.0
>   * PCSC-LITE: 1.8.13
>   * LIBCCID: 1.4.18
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/301#issuecomment-68511910>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by LudovicRousseau** [comment]
@rvalle you can get pcscd debug on Mac OS X. For that 
- connect your smart card reader
- kill any running pcscd process
- start pcscd in a terminal using "sudo LIBCCID_ifdLogLevel=0x000F /usr/sbin/pcscd -dfa"

Then attach the last ~50 lines of logs.

**Comment by rvalle** [comment]
@LudovicRousseau here you have the logs.

If it is a HW issue, you have workarround it in the past.
I have had tokens running on this MacBook since I got it.
The older token: epassPKI is working fine generating RSA 2048, while the epass2003 fails.

So I have captured both logs, from working and failing token, here are those:

epass2003RSA2048KeyGenFailure: http://pastebin.com/nwvAEzZf
epassPKIRSA2048KeyGenOK: http://pastebin.com/3D2SXrdB

the epassPKI is super-low, but it finally gets a working RSA2048 key. (I have verified it by using it with SSH).

**Comment by rvalle** [comment]
@LudovicRousseau also, for your information, not only KeyGeneration is failing on epass2003@MyMacbook.

I have also tried to use the generated RSA2048 keys on other working environments on this macbook, by using them with SSH, and I get a Signature Error like:

ssh user@server.lan
Enter PIN for '(User PIN)': 
C_Sign failed: 5
ssh_rsa_sign: RSA_sign failed: unknown err

**Comment by LudovicRousseau** [comment]
Line 694:
```
-> 000000 6F 26 00 00 00 00 C0 00 00 00 8C B4 02 00 20 87 11 01 F0 5D 17 5C 7E 97 D9 0D 43 46 04 8C 71 4B 65 B7 97 01 00 8E 08 1C 5E 1F 3A E8 2D 54 8C 00
07562197 ccid_usb.c:798:ReadUSB() read failed (20/8): -7 Operation timed out
SW:
/SourceCache/SmartCardServices_Executables/SmartCardServices-55111/src/PCSC/ifdwrapper.c:741:IFDTransmit() Card not transacted: 612
/SourceCache/SmartCardServices_Executables/SmartCardServices-55111/src/PCSC/winscard.c:1325:SCardTransmit() IFDControl_v2/IFDTransmit result: 0x80100016, received: 0
```
The driver timed out after 7.56 seconds.

In lines 647-664 you have:
```
APDU: 0C 46 00 00 1D 87 11 01 DB 09 8B DD 18 00 10 19 CE 43 01 1A 0D 4B 18 53 8E 08 7A 5F 96 A3 E4 4B 34 77 00
00280137 ifdhandler.c:1283:IFDHTransmitToICC() Feitian ePass2003 (lun: 0)
00000007 commands.c:1590:CmdXfrBlockAPDU_extended() T=0 (extended): 35 bytes
-> 000000 6F 23 00 00 00 00 BE 00 00 00 0C 46 00 00 1D 87 11 01 DB 09 8B DD 18 00 10 19 CE 43 01 1A 0D 4B 18 53 8E 08 7A 5F 96 A3 E4 4B 34 77 00
<- 000000 80 00 00 00 00 00 BE 80 03 00
01067065 commands.c:1519:CCID_Receive() Time extension requested: 0x03
00000006 commands.c:1525:CCID_Receive() New timeout: 9000 ms
<- 000000 80 00 00 00 00 00 BE 80 03 00
01101870 commands.c:1519:CCID_Receive() Time extension requested: 0x03
00000007 commands.c:1525:CCID_Receive() New timeout: 9000 ms
<- 000000 80 00 00 00 00 00 BE 80 03 00
01099680 commands.c:1519:CCID_Receive() Time extension requested: 0x03
00000006 commands.c:1525:CCID_Receive() New timeout: 9000 ms
<- 000000 80 00 00 00 00 00 BE 80 03 00
01093607 commands.c:1519:CCID_Receive() Time extension requested: 0x03
00000013 commands.c:1525:CCID_Receive() New timeout: 9000 ms
<- 000000 80 10 00 00 00 00 BE 00 00 00 99 02 90 00 8E 08 68 D6 48 8A AB EC 2A AB 90 00
SW: 99 02 90 00 8E 08 68 D6 48 8A AB EC 2A AB 90 00 
```
So the token is correctly sending "time extension requests" in some cases.

I guess it is the same problem you talked about in https://github.com/OpenSC/OpenSC/issues/301#issuecomment-59890750

I am surprised that the same token works fine on Debian and Raspberry Pi.
How have you solved the problem described in https://github.com/OpenSC/OpenSC/issues/301#issuecomment-59661481 ?

**Comment by rvalle** [comment]
I haven't fixed anything, I have just tested on different environments. 
I am, in fact, considering to deploy this token in our company, so I am  an end user.
What I can do is get you similar logs on the working environments.

**Comment by marcrt** [comment]
Could you give the serial number of failling ePass2003. Only the first 4 digits written on the USB connector YYMM. According to Feitian ePass2003 COS had an update which improved the support of 2048 certificate in Mac OS.

Currently I have got a similar problem on OSX 10.9 and 10.10 with Feitian proprietary middleware and old 1210 ePass2003. I will try with a recent one on OSX with both Feitan middleware and OpenSC and keep you informed.

The same ePass2003 is working fine with 2048 certificates on other plateforms 
xubuntu 14.4 with OpenSC 0.14.0
Windows7 with both Feitan Middleware and OpenSC

My Company Logidata is distributor of Feitian in France we may also help with hardware or latest beta drivers.

**Comment by rvalle** [comment]
@marcrt I got this Feitian SDK quite recently.
The YYMM on my tokens is: 1409

**Comment by rvalle** [comment]
@LudovicRousseau , @marcrt 
Some more information on the OSX environment,
I just performed a Clean install of my Macbook with OSX 10.10.1 Yosemite: that is format the HD drive and reinstall from the scratch.
And the epass2003 continues to fail generating RSA/2048.
This time, however, the error message is slightly different:

pkcs15-init --auth-id 1 --generate-key rsa/2048 --key-usage sign,decrypt --label "My first RSA key pair"
Using reader with a card: Feitian ePass2003
Failed to generate key: Card removed

**Comment by marcrt** [comment]
@rvalle 
Firefox TLS user authentication with 2048 bits certificate works on my side (certificate generated on another environment. Same transaction was failing with old ePass2003)
ePass2003 serial nb 1409xxxx
Feitian middleware 20141209
MacBook pro with OSX 10.10.1 Yosemite
@LudovicRousseau
I agree the problem is at low level. Recent COS is necessary for 2048 operations on Mac only, less chance to get a CCID error. I am also a bit confused with apple ctkpcsd implementation compared to pcsc-lite.
What version of ePass2003 hardware did you test in http://pastebin.com/nwvAEzZf ?

**Comment by rvalle** [comment]
@LudovicRousseau after some correspondence with ftsafe, they seem to have fixed this problem.

**Comment by FeitianSmartcardReader** [comment]
@LudovicRousseau The problem has fixed in firmware, and i just check web http://pcsclite.alioth.debian.org/ccid/section.html,It showed below,  could you please change status of epass2003? thanks
"The device may fail at generating keys onboard. See https://github.com/OpenSC/OpenSC/issues/301"

**Comment by LudovicRousseau** [comment]
@FeitianSmartcardReader have you changed the firmware release bcdDevice to a value > 1.00 to differentiate from the bogus version?

**Comment by martinpaljak** [comment]
Yes, this is a common problem - no change in observable attributes if behaviour changes. This is a must have.

**Comment by FeitianSmartcardReader** [comment]
Yes, our engineer already changed bcdDevice vaule, thanks
