### ISSUE TITLE
segmentation fault on linux using cherry reader with pinpad

### ISSUE THREAD

**Issue by tlahn** [OpenSC/OpenSC#3022]
### Problem Description

Using Cherry card reader with pin via pinpad on Linux causes segmentation fault for current master branch.

Test command and result on master:

```
$ pkcs11-tool --test --login
Using slot 0 with a present token (0x0)
Segmentation fault (core dumped)
```

When specifying pin on commandline it does not show the segfault. It fails **expectedly** with a different error, which will be fixed by https://github.com/OpenSC/OpenSC/pull/2943

```
$ pkcs11-tool --test --login -p 111111111111
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  RIPEMD160: OK
  SHA-1: OK
  SHA256: OK
Ciphers: not implemented
Signatures (currently only for RSA)
  testing key 0 (Authentisierungsschluessel)
error: PKCS11 function C_SignFinal failed: rv = CKR_USER_NOT_LOGGED_IN (0x101)
Aborting.
```

Running the commands on git tag 0.24.0 does not show a segfault, whether I set pin on commandline or not.

Using git bisect I could identify these commits as the change from ok to error:

* cec92640c0d1a2c4fdda3b585eedeace69bffdca: ok
* 4015eac38a50faf78d0a8d5468972f64c85818b7: compile error
* 22e4ebcfc5d22fd07a4a98af5e78f2e16da25c11: Segmentation fault (core dumped)

### Steps to reproduce

```
$ ./bootstrap && ./configure --prefix=/usr/local --sysconfdir=/etc/opensc && make && sudo make install
$ pkcs11-tool --test --login
```

### Details on hardware and config

Reader and card info:

```
$ opensc-tool -n
Using reader with a card: Cherry GmbH SmartTerminal ST-2xxx [CCID Interface] (55952134200215) 00 00
Atos CardOS
```

The card is a `D-TRUST Card 4.1 Std. RSA 2ca`.

Config:

```
$ cat $OPENSC_CONF
app default {
  debug = 9;
  debug_file = /tmp/tmp.cKWXxeUgGb/opensc-debug.txt;
}
```

### Logs

Log file from execution on master without specifying pin on commandline is attached: [opensc-debug-master-pinpad-redacted.txt](https://github.com/OpenSC/OpenSC/files/14236877/opensc-debug-master-pinpad-redacted.txt).

I redacted personal details returned by the card as far as I found them. Logs should not contain pin, as the process failed before entering it, but it would not matter as I changed it for testing purposes.

I could also provide similar logs for any of the other code revisions if this is helpful. Just let me know.

dmesg shows the following error: `pkcs11-tool[104048]: segfault at 0 ip 0000000000000000 sp 00007fffd93b8d28 error 14 in pkcs11-tool[5634feed4000+7000] likely on CPU 1 (core 1, socket 0)`

**Comment by Jakuje** [comment]
:facepalm: obviously the conditions are negated: Can you verify this is fixed with #3023 ?

**Comment by tlahn** [comment]
The problem is fixed with #3032 for me. Thanks for your fast response.

**Comment by Jakuje** [comment]
I think rebasing would be good to make sure it works ok, but there is very little chance it will have some effect to each other.

**Comment by hamarituc** [comment]
> I think rebasing would be good to make sure it works ok, but there is very little chance it will have some effect to each other.

Sorry, my last comment was meant to go to #2943. Nevertheless, I did a rebase.
