### ISSUE TITLE
doc: Python wrapper

### ISSUE THREAD

**Issue by msetina** [OpenSC/OpenSC#3057]
Python wrapper PyKCS11 has broken link.
Can python-pkcs11 be added to Python wrappers. It looks good and has nice documentation.

**Comment by frankmorgner** [comment]
Feel free to open a pull request for a change at https://github.com/OpenSC/Wiki

**Comment by msetina** [comment]
I feel free. Now I am wondering why I see <pre><code> blocks insted of bc.
Is there a reason?

**Comment by Jakuje** [comment]
> I feel free. Now I am wondering why I see `\<pre\><code>` blocks insted of bc. Is there a reason?

Can you clarify where? I do not see this in the page referencing PyPKCS11: https://github.com/OpenSC/Wiki/blob/1faa5165bb397b5c5f6d85344bf153801174e882/Creating-applications-with-smart-card-support.textile?plain=1#L24

**Comment by msetina** [comment]
Here:
https://github.com/OpenSC/Wiki/blob/1faa5165bb397b5c5f6d85344bf153801174e882/Compiling-and-Installing-on-Unix-flavors.textile?plain=1
If it is a mistake, I have it fixed and will be in with my PR.
The one you mention has indentations with ** which my previewer does not understant and should not be indented.

**Comment by Jakuje** [comment]
Its likely converted from some older format. I am not familiar with the textile format so if you want, changing it to markdown can help the readability.

**Comment by msetina** [comment]
PR on Wiki project done.
