### ISSUE TITLE
docbook-utf8.xsl missing from release archive

### ISSUE THREAD

**Issue by freswa** [OpenSC/OpenSC#3062]
### Problem Description
Release 0.25.0 docs do not compile from release tarball.

### Proposed Resolution
Add `docbook-utf8.xsl` to release tarball.
### Steps to reproduce
Run make with docs enabled for the release tarball. `tools.html` will fail with error 5.
### Logs
```
warning: failed to load external entity "../docbook-utf8.xsl"
compilation error: file ./../html.xsl line 6 element import
xsl:import : unable to load ../docbook-utf8.xsl
```

**Comment by Jakuje** [comment]
Thank you for the report! This was unfortunately missed as we do not have any CI run `distcheck` with documentation enabled. The fix is easy, but still looking into preperly testing  this to avoid similar issues in the future.
