### ISSUE TITLE
When configuring the ECCP256 algorithm certificate, XShell directly crashes when using PKCS11 for authentication connection.

### ISSUE THREAD

**Issue by ghost** [OpenSC/OpenSC#3073]
### Problem Description
I am using yubikey 5 key for ssh connection. 
When configuring the ECCP256 algorithm certificate, XShell directly crashes when using PKCS11 for authentication connection.
But in the same environment, everything works fine when configuring the RSA2048 certificate.

### Proposed Resolution
Support ECCP256 algorithm for PKCS11.

### Steps to reproduce
Steps like [SSH Connections with YubiKey PKCS#11 User Authentication(PIV)](https://netsarang.atlassian.net/wiki/spaces/ENSUP/pages/796426271/SSH+Connections+with+YubiKey+PKCS+11+User+Authentication+PIV).
The difference is that yubikey generates the key.
RSA2045 : 
```bash
ykman piv keys generate -a RSA2048 --pin-policy=once --touch-policy=always 9a pubkey.pem
ykman piv certificates generate --subject "yubico" 9a pubkey.pem
```
ECCP256 :
```bash
ykman piv keys generate -a ECCP256 --pin-policy=once --touch-policy=always 9a pubkey.pem
ykman piv certificates generate --subject "yubico" 9a pubkey.pem
```

Using ECCP256 will directly crash or become unresponsive when xshell connects.

**Comment by dengert** [comment]
PIV type cards determine the type and size of a key from the certificate that is stored on the card in the Subject PublicKeyInfo. Some possible problems:
- ykman has not updated the certificate if one is already present. 
- OpenSC's certificate cache on disk is being used and it is out of date and cert has the wrong SPKI.  See `man opensc.conf` "use_file_caching"
- The SSH host has the wrong public key. 

An OpenSC debug log would help as would `./pkcs15-tool  --read-certificate  01 | openssl x509 -text -noout`

**Comment by Jakuje** [comment]
OpenSC 0.20.0 is some years old. Can you try with more recent version or master?

Do you have some backtrace from the crash? The operations look successful in all the examples you provided.

**Comment by dengert** [comment]
@Z1Turn0 in the output from https://github.com/OpenSC/OpenSC/issues/3073#issuecomment-2002934891 did you blank out  the "Serial Number", "pub:" and "Signature:" ?  if not it looks like ykman only wrote the minimal information to let PIV driver know there is a private key.

What is output of `pkcs15-tool.exe --read-ssh-key 01`

https://netsarang.atlassian.net/wiki/spaces/ENSUP/pages/2086437094/SSH+access+via+PIV+smart+card+using+CAPI
says: "Select ‘RSA2048’ or ‘RSA1024’ as the algorithm. As of November 20, 2023, ECCP256 is not supported by Xshell", so testing using certutil (which uses CAPI)  is not a part of this problem. Also Windows uses the Microsoft built-in PIV driver for CAPI. 

Do you see any indications that XShell using PKCS11 supports using ECC keys? All examples I have seen are RSA.

**Comment by dengert** [comment]
What is output of `pkcs15-tool.exe --read-ssh-key 01`

Can you try using putty. 

>thought that the certificate algorithm is handled by opensc middleware, so I didn't consider whether xshell supports ecc ...

That is not clear. 

Also try using OpenSC SPY to get trace of PKCS11 calls and get opensc debug log. See: https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by Jakuje** [comment]
I would say its a bug in the xshell. I do not see any indication of opensc functions in the backtrace and as the key can be used ok with the pkcs15-tool, there is not much we can do, except for recommending to use other ssh client. There is Putty-CAC, which (regardless of the name), should work with any smart cards and PKCS#11.

**Comment by Jakuje** [comment]
This looks more promissing. Can you get a OpenSC debug log from this operation?

**Comment by dengert** [comment]
Also run `pkcs11-tool  -O`   look for usage on each key.  (And please provide a OpenSC debug log from the failing operation.) 

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-piv.c#L534 list the default usage for the 01 cert i.e. 9A key.

If this is a non government PIV then here is where the certificate's keyUsage is obtained:  
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-piv.c#L812-L827
Here is where the usage is set for EC keys:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-piv.c#L888-L927



You may also want to try Yubico's PKCS11 module:
https://developers.yubico.com/yubico-piv-tool/Releases/
https://support.yubico.com/hc/en-us/articles/360021606180-Using-YubiKey-PIV-with-Windows-native-SSH-client
https://developers.yubico.com/yubico-piv-tool/YKCS11/ 

https://github.com/Yubico/yubico-piv-tool/issues/223 it is old  but points out  you may need to generate a CSR, have it signed by a CA so it has the correct correct keyUsage.
