### ISSUE TITLE
Building without openpace but with openssl on Windows

### ISSUE THREAD

**Issue by nshah2588** [OpenSC/OpenSC#3074]
Dear OpenSC team,

We have been able to successfully build OpenSC on Windows but by default the build happens with OpenPACE which we don't support at the moment and want to be able to build with OpenSSL but without OpenPACE.

Can you please guide us on that?

Neel.

**Comment by Jakuje** [comment]
Does `./configure --disable-openpace` solves the issue for you?

**Comment by frankmorgner** [comment]
On Windows, you need to adapt `Make.rules.mak` to your needs (only some parameters are taken from nmake's CLI). However, OpenPACE is disabled by default, so you should not run into any problems:
https://github.com/OpenSC/OpenSC/blob/d2cbd63a25c73882ee0fbcc9d2d3d72140d2aa57/win32/Make.rules.mak#L122
