### ISSUE TITLE
Minidriver function CardRSADecrypt returns SCARD_F_INTERNAL_ERROR despite sc_pkcs15_decipher was successful

### ISSUE THREAD

**Issue by jozsefd** [OpenSC/OpenSC#3085]
### Problem Description

Minidriver function CardRSADecrypt returns SCARD_F_INTERNAL_ERROR despite sc_pkcs15_decipher was successful. The function compares the return value of sc_pkcs15_decipher (or sc_pkcs1_strip_02_padding_constant_time) agains 0, but these functions return the length of decrypted data on success, not 0.

### Proposed Resolution

minidriver.c:4713
```C
//good = constant_time_eq_i(r, 0);
good = constant_time_lt(0, r);
```

### Steps to reproduce

Create a windows application, which calls API CryptDecrypt(). 

### Logs

The return value is not logged, as 
"/* do not log return value to not leak it */"
but it will be received by the calling Windows API.

**Comment by Jakuje** [comment]
Can you check the #3077 solves your issue?

**Comment by jozsefd** [comment]
Actually #3077 seems to fix my #3086 report and not this issue. The return value check agains 0 is incorrect, as the pre Marvin code looked like:
```C
	if ( r < 0)   {
                ...
		goto err;
	}
```

**Comment by xhanulik** [comment]
Before changes fixing Marvin, the `CardRSADecrypt` called `sc_pkcs1_strip_02_padding` returning the length of depadded message `r` and checked it for error - the length of the depadded message is >= 0.

https://github.com/OpenSC/OpenSC/blob/a22908285ef205f7b7fa2b00366898a435c789f3/src/minidriver/minidriver.c#L4714-L4720

So for Marvin, using `good = constant_time_eq_i(r, 0);` is not correct, but in #3077 this is changed to `good = constant_time_ge(r, 0);` which I think should solve this issue as it checks that `r >= 0`.

**Comment by jozsefd** [comment]
Oh sorry, I have only checked the last commit of #3077, the change of minidriver.c in de257184a8b6df215a9fbf2ae686985eb4f099be is OK.

On the other hand, a 0 length output of decryption or unpadding seems to be a little bit odd for me.

**Comment by jozsefd** [comment]
I have tested #3077 with various cards, it fixes this issue.
