### ISSUE TITLE
JPKI SELECT AID  not following ISO standards 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#3111]
#3108 reports that when `card-jpki.c` does a SELECT AID against an unknown card, it causes problems. 

ISO 7816-4 says SELECT AID  is `00 A4 04 00`  and optionally will return an FCI. `card-jpki.c` appears to  use `00 A4 04 0C` where `0C` says no data is to be returned or data returned is proprietary.  

Here is proposed untested PR:

[card-jpki.c.diff.txt](https://github.com/OpenSC/OpenSC/files/14963805/card-jpki.c.diff.txt)

@hamano can you or anyone else with a JPKI card test this or create other PR.

**Comment by frankmorgner** [comment]
`00 A4 04 0C` is fully conformant with iso 7816-4
