### ISSUE TITLE
SmartCard-HSM issue with Windows AD Smart Card Logon & Micrsoft Encrypting File System

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#3114]
Bonjour community,

i am using SmartCard-HSM with a RSA 2048 digital certificate for Windows AD Smart Card Logon with SC-HSM Starter kit, sc-hsm-middleware-x64-2.12 and opensc-0.20.0/0.25.0

for Windows logon: It stucks on "**checking status...**"

for certutil -scinfo it shows following output and stucks

The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 1
  0: OMNIKEY CardMan 3x21 0
--- Reader: OMNIKEY CardMan 3x21 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
--- Status: The card is being shared by a process.
---   Card: SmartCard-HSM
---    ATR:
        3b fe 18 00 00 81 31 fe  45 80 31 81 54 48 53 4d   ;.....1.E.1.THSM
        31 73 80 21 40 81 07 fa                            1s.!@...

=======================================================
**Analyzing card in reader: OMNIKEY CardMan 3x21 0**

**Comment by frankmorgner** [comment]
There has been a bug in 0.25.0, please try 0.25.1.

**Comment by scottthomas007** [comment]
I have tried OpenSC 0.25.1 but the issue is the same... i also have installed SC-HSM PKCS11 module but still no success

**Comment by frankmorgner** [comment]
Please generate a debug log for OpenSC 0.25.1, i.e.
```
set OPENSC_DEBUG=3
certutil -scinfo
```

If you have problems with https://github.com/CardContact/sc-hsm-embedded, please open an issue there.

**Comment by scottthomas007** [comment]
Hi ,
the issue has been resolved. maybe we were missing some steps I think the opensc.conf file changes. anyhow thanks
