### ISSUE TITLE
SmartCard-HSM issue with Microsoft Word 2019 & Outlook 2019 

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#3115]
Bonjour community,

i am using SmartCard-HSM with a RSA 2048 digital certificate for **S/MIME in Outlook** and **Digital signing in Microsoft Word**. I am getting the following error:

"**the smart card cannot perform the requested operation or the operation requires a different smart card**"

Cheers
Scotty

**Comment by CardContact** [comment]
I'm not a regular Windows uses, but the last time I saw that issue, it was caused by an 64-bit of OpenSC installed and access from a 32-bit application.

Is Word 2019 a 64-bit application  and do you have the 64-bit version of OpenSC installed ?

**Comment by scottthomas007** [comment]
Thanks for the answer. My office was 32-bit version. Initially i had installed 32-bit OpenSC version 1st and 64-bit OpenSC version later. I installed the 32-bit again and now Outlook 2019 and Word 2019 are seamlessly working with OpenSC smart card.

Cheers
Scotty
