### ISSUE TITLE
pkcs11-tool should provide an option to get slot information as pkcs11-uri

### ISSUE THREAD

**Issue by sarroutbi** [OpenSC/OpenSC#3123]
### Problem Description

It would be great if pkcs11-tool could include a function to dump slot information as a PKCS#11 URI

### Proposed Resolution

pkcs11-tool already dumps information related to each of the detected devices. For example:

```bin
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico YubiKey OTP+CCID 00 00
  token label        : clevis
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0123456789abcde
  pin min/max        : 4/8
```
An option like `-u, --uri` would be nice, to dump this information as a supported PKCS#11 URI:

```bash
$ pkcs11-tool -u
Slot 0 (0x0): Yubico YubiKey OTP+CCID 00 00: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=0123456789abcde;token=clevis 
```

**Comment by Jakuje** [comment]
The PKCS#11 URI identifies not only the slots, but also objects, so if we should have it, I would say it should be just printed in the output where we list slots or objects. It has also several non-mandatory parts, such as PIN, module path, which should probably not be used in the default print.

```
$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): Yubico YubiKey OTP+CCID 00 00
  token label        : clevis
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 0123456789abcde
  pin min/max        : 4/8
  uri:               : pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=0123456789abcde;token=clevis 
```

The reason why it was not implemented so far is likely nobody needed that so far. Every time I needed a PKCS#11 URI in the output, I usually used p11tool from gnutls or p11-kit, which prints these.

So if you are (or anyone else) interested in implementing this, we would be happy to accept patches.
