### ISSUE TITLE
Unable to generate RSA key using piv-tool

### ISSUE THREAD

**Issue by invis-z** [OpenSC/OpenSC#3156]
### Problem Description

Unable to generate RSA key using piv-tool since version 0.23.0.
Works with OpenSC version 0.22.0 on Ubuntu 22.04.
ECC key also works.

Tested with OpenSC versions:
|Distro|Version of OpenSC|Able to generate RSA key|Note|
|-|-|-|-|
|OpenSUSE Tumbleweed|0.25.1(0.25.1-1.1)|N||
|Ubuntu 24.04|0.25.0(0.25.0~rc1-1build2)|N||
|OpenSUSE Tumbleweed|0.24.0|N|First encountered this issue, this is the old version number I remembered. Could be inaccruate.|
|Debian 12.5|0.23.0(0.23.0-0.3+deb12u1)|N|with `-A M:9B:0C` to avoid admin error|
|Ubuntu 22.04|0.22.0(0.22.0-1ubuntu2)|Y|with `-A M:9B:0C` to avoid admin error|

Tested with:

- NXP J3H145 with [arekinath/PivApplet v0.9.0](https://github.com/arekinath/PivApplet/releases/tag/v0.9.0) with AES256 9B key
- NXP J3R180 with [makinako/OpenFIPS201 v1.10.2](https://github.com/makinako/OpenFIPS201/releases/tag/v1.10.2) with AES256 9B key
- YubiKey 5 NFC with default 3DES 9B key (only tested with 0.25.1 on Tumbleweed)

### Steps to reproduce

1. Setup keys through `PIV_EXT_AUTH_KEY`
2. `piv-tool -v -A A:9B:0C -G 9E:07`

### Logs

```
$ piv-tool -v -A A:9B:0C -G 9E:07
Using reader with a card: Generic EMV Smartcard Reader (ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ) 00 00
Connecting to card in reader Generic EMV Smartcard Reader (ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ) 00 00...
Using card driver Personal Identity Verification Card.
gen_key unable to gen RSA
```

**Comment by dengert** [comment]
Can you get an OpenSC debug log  See https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

What version of OpenSSL?

**Comment by dengert** [comment]
Maybe BN_free(newkey_n) and BN_free(newkey_e)  need to be moved.

**Comment by dengert** [comment]
@invis-z please have a look at:   https://github.com/OpenSC/OpenSC/pull/3167#issuecomment-2156204455
