### ISSUE TITLE
RSA padding in release 0.25.1

### ISSUE THREAD

**Issue by dwhjames** [OpenSC/OpenSC#3166]
@xhanulik You released

https://github.com/OpenSC/OpenSC/releases/tag/0.25.1
stating that it includes
- https://github.com/OpenSC/OpenSC/pull/3077

This release does appear to have a copy of those commits on the the `stable-0.25` branch
https://github.com/OpenSC/OpenSC/compare/master...stable-0.25

---

But unfortunately, it does not include a previous related fix
- https://github.com/OpenSC/OpenSC/pull/3075

Here’s the diff
https://github.com/OpenSC/OpenSC/compare/stable-0.25...6953cc1872f8aa42efc237d6a1318ada41a1a658

---

As a result, the 0.25.1 patch release resolved
- https://github.com/OpenSC/OpenSC/issues/3076

but _didn’t_ resolve
- https://github.com/OpenSC/OpenSC/issues/3072

(which affects 0.25 as well as 0.25.1, the regression occurred after the 0.24 release)

**Comment by xhanulik** [comment]
Yes, changes from #3075 slipped out of the 0.25.1 release, so that they will be included in the next one (0.26.0).

**Comment by dwhjames** [comment]
@xhanulik thanks for the reply.

This initially caused some confusion 😄  307x were very close together and we missed that there were multiple changes related to padding.

Do you have any sense for timing on the next release?

**Comment by xhanulik** [comment]
I think it could be out in following months, like 2 or so - the current progress is tracked in [OpenSC 0.26.0 project](https://github.com/OpenSC/OpenSC/projects/14).

**Comment by dwhjames** [comment]
@xhanulik, following up to say that I see
- https://github.com/OpenSC/OpenSC/releases/tag/0.26.0

and that
- https://github.com/OpenSC/OpenSC/pull/3075

was included
