### ISSUE TITLE
Current master fails to build (problem with man pages?)

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#3191]
### Problem Description

```
libtool: link: clang  -o .libs/libsmm-local.11.so -bundle  .libs/smm-local.o .libs/sm-global-platform.o .libs/sm-cwa14890.o .libs/sm-card-authentic.o .libs/sm-card-iasecc.o   -Wl,-force_load,../../src/sm/.libs/libsm.a -Wl,-force_load,../../src/common/.libs/libcompat.a  -L/opt/local/libexec/openssl3/lib ../../src/libopensc/.libs/libopensc.dylib -L/Users/ur20980/src/OpenSC/openpace_bin/Library/OpenSC/lib -ldl -lcrypto -lz  -g -O3 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -O2 -g  
libtool: link: (cd ".libs" && rm -f "libsmm-local.so" && ln -s "libsmm-local.11.so" "libsmm-local.so")
libtool: link: ( cd ".libs" && rm -f "libsmm-local.la" && ln -s "../libsmm-local.la" "libsmm-local.la" )
make[3]: Nothing to be done for `all-am'.
Making all in win32
make[2]: Nothing to be done for `all'.
Making all in doc
Making all in tools
sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < cardos-tool.1.xml \
	| xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o cardos-tool.1 man.xsl - 2>/dev/null
sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < cryptoflex-tool.1.xml \
	| xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o cryptoflex-tool.1 man.xsl - 2>/dev/null
sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < dnie-tool.1.xml \
	| xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o dnie-tool.1 man.xsl - 2>/dev/null
sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < dtrust-tool.1.xml \
	| xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o dtrust-tool.1 man.xsl - 2>/dev/null
make[3]: *** [cardos-tool.1] Error 4
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [dnie-tool.1] Error 4
make[3]: *** [cryptoflex-tool.1] Error 4
make[3]: *** [dtrust-tool.1] Error 4
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

### Proposed Resolution

I don't know (fix whatever is causing this...?).

### Steps to reproduce

Clone, configure, run build, observe the above. Complete logs are below.

### Logs

[opensc-config-log.txt](https://github.com/user-attachments/files/15959022/opensc-config-log.txt)
[config.log](https://github.com/user-attachments/files/15959023/config.log)
[opensc-total-build.txt.gz](https://github.com/user-attachments/files/15959025/opensc-total-build.txt.gz)

### Update
Trying to get something more meaningful than the messages visible above, I got this:
```text
$ pwd
/Users/ur20980/src/OpenSC/doc/tools
$ make
sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < cardos-tool.1.xml \
	| xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o cardos-tool.1 man.xsl - 2>/dev/null
make: *** [cardos-tool.1] Error 4
$ sed -e 's|@pkgdatadir[@]|/Library/OpenSC/share/opensc|g' < cardos-tool.1.xml | xsltproc --nonet --path "./..:/opt/local/share/xsl/docbook-xsl-nons/manpages" --xinclude -o cardos-tool.1 man.xsl -
I/O error : failed to load "man.xsl": No such file or directory
cannot parse man.xsl
$
```
It seems to tell that `man.xsl` is needed by something now, but it doesn't exist?

**Comment by Jakuje** [comment]
The `man.xsl` is in the `doc` directory: https://github.com/OpenSC/OpenSC/blob/master/doc/man.xsl but not in the `doc/tools` nor `doc/files` where it is used. I think either xsltproc manages to include the file from relative directory or there is one in some system directory that makes it working in CI and other devs machines.

I think the correct solution should be to provide absolute paths to the man.xsl also in the `doc` and `tools` directories.

**Comment by Jakuje** [comment]
I don't think there was any significant changes around docs over last couple of weeks so I would assume some change on your machine.

**Comment by frankmorgner** [comment]
there was https://github.com/OpenSC/OpenSC/commit/09d70b5399f207b40b20abbb9b5fa1a57fe9661c, but I don't think that is related

Regarding the (absolute) path, it seems that your xsltproc doesn't handle the `--path` as we expect it to. We are specifying `$(srcdir)/..` as directory for searching `man.xsl`... Could you please try `$(abs_srcdir)` here instead in doc/tools/Makefile.am and in doc/files/Makefile.am?

**Comment by frankmorgner** [comment]
`--path "$(abs_srcdir)/..:$(xslstylesheetsdir)/manpages"` is what I meant (untested)

**Comment by frankmorgner** [comment]
I think you need file a bug at your distribution. In CI, specifying the path works fine, e.g.
https://github.com/OpenSC/OpenSC/actions/runs/9690231008/job/26739715561#step:5:1227

xsltproc is used in fedora and ubuntu CI builds.
