### ISSUE TITLE
An arrow next to governments with no other section issue 

### ISSUE THREAD

**Issue by Fayrouz173** [OpenSC/OpenSC#3211]
When the user clicks on traveling from and chooses the city he wants to travel from, an arrow is placed next to some towns that have no more stations than one.

Environment: honer 8x
Frequently: always 
Severity: medium
Priority: medium

Steps:
1- Open the Go Bus app
2- Click on traveling from to choose a city
3- Choose Qena city
4- Click on the arrow

Actual result:
The arrow opens another empty page

Expected result:
The system should not contain an arrow next to the city that has no more than one station

Image:
![Screenshot_74](https://github.com/user-attachments/assets/d878a4c4-0e19-4152-8691-8463510697b7)

**Comment by Jakuje** [comment]
This does not look like related to OpenSC at all. Closing.
