### ISSUE TITLE
Back button in map page

### ISSUE THREAD

**Issue by Fayrouz173** [OpenSC/OpenSC#3213]
When the user clicks on maps and chooses a specific map (nasr city), then click on the back button. the button go back to steps back

Environment: honer 8x
Frequently: always 
Severity: medium
Priority: medium
 
Steps:
1- Open the Go Bus app
2- Click profile button
3- Click on cities map
4- Click on nasr city map
5- Click on back button

Actual result:
The app goes back two steps (pages)
 
Expected result:
The app should go back one step only
 
Image:
![Screenshot_75](https://github.com/user-attachments/assets/a59a962e-04cb-4534-b16f-979684102fc3)
![Screenshot_76](https://github.com/user-attachments/assets/69049ce7-b463-4cf3-9111-b74e25a94135)

**Comment by Jakuje** [comment]
This does not look like related to OpenSC at all. Closing.
