### ISSUE TITLE
sc-hsm-tool: plaintext dkek_share not cleansed in create_dkek_share()

### ISSUE THREAD

**Issue by strongX509** [OpenSC/OpenSC#3224]
### Problem Description

The function [create_dkek_share()](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L1194) assigns the sensitive 256 bit DKEK plaintext key share  [produced](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L1241) by the HSM's random generator to the **`dkek_share[32]`** variable on the stack. The plaintext key share is then[ AES-256-encrypted ](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L1249 )with the custodian's password and the encrypted key share is temporarily stored in **`filebuff[64]`** before it is written to the file system.

Surprisingly the **`filebuff[64]`** variable which contains the encrypted key share is [cleansed](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L1274) but not the much more sensitive plaintext key share **`dkek_share[32]`** .

### Proposed Resolution

Cleanse the sensitive **`dkek_share[32]`** variable instead of **`filebuff[64]`**:
````
-	OPENSSL_cleanse(filebuff, sizeof(filebuff));
+	OPENSSL_cleanse(dkek_share, sizeof(dkek_share));
````
BTW - In the  companion [import_dkek_share()](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L809) function only the sensitive plaintext key share in **`outbuff[64]`** is [cleansed](https://github.com/OpenSC/OpenSC/blob/21ba386091b6d8e992439d6b04f577fe46d0e190/src/tools/sc-hsm-tool.c#L887) but not the encrypted key share in the input **`filebuff[64]`**. Thus the proposed patch for create_dkek_share() would be consistent with the approach in import_dkek_share().

**Comment by CardContact** [comment]
Thanks for reporting this. That needs to be fixed. I'll have a look.

However, there are other places where the GET CHALLENGE response (and thus the DKEK share) traverses APIs and buffers. I'm not sure if all buffers are cleansed along the way. A better solution would be to enable secure messaging between the key management application and the HSM. Or even better to setup an air-gap'ed system for key management operations.

**Comment by strongX509** [comment]
Actually we are setting up the key management system on an air-gapped system without network access. At least two custodians will generate the private key for our Root CA on-site on this stand-alone system, so the reported potential vulnerability is not much of an issue for this use case. But generally it is good practice to cleanse all raw key material.
