### ISSUE TITLE
Support for DGN cards

### ISSUE THREAD

**Issue by DeEskalator** [OpenSC/OpenSC#3229]
### Problem Description

The DGN businessCard seems to be not supported by OpenSC

### Proposed Resolution
It would be great if this card would be possible to use with OpenSC.

### Steps to reproduce
Try to sign some data: 
```
echo "Sign me" | .\pkcs11-tool.exe --slot 0 -a Signaturzertifikat -s -m RSA-PKCS -p XXXX
error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.

Trying to get info about the card in [Pcks11Admin ](https://www.pkcs11admin.net/) using opensc-pkcs11.dll also yields CKR_TOKEN_NOT_PRESENT 

```
### Logs
Card Type
```
.\opensc-tool.exe --name
Using reader with a card: Cherry KC 1000 SC 0
STARCOS 3.4
```

Card Infos:
```
.\cardos-tool.exe -i
Using reader with a card: Cherry KC 1000 SC 0
Failed to connect to card: Unsupported CLA byte in APDU

```

OpenSC-Version
```
opensc-tool --version
OpenSC-0.25.1, rev: 0a4b772d, commit-time: 2024-04-04 16:21:38 +0200
```

**Comment by frankmorgner** [comment]
What is the output of `opensc-tool -a`?

**Comment by CardContact** [comment]
We have some support for DGN cards in the [sc-hsm-embedded](https://github.com/CardContact/sc-hsm-embedded) PKCS#11 module.

Those cards don't have a PKCS#15 structure, so you would need an emulation driver in OpenSC.

**Comment by DeEskalator** [comment]
> What is the output of `opensc-tool -a`?

There you go: 
```
.\opensc-tool.exe -a
Using reader with a card: Cherry KC 1000 SC 0
3b:d3:96:ff:81:b1:fe:45:1f:07:80:81:05:2d
```

**Comment by DeEskalator** [comment]
> We have some support for DGN cards in the [sc-hsm-embedded](https://github.com/CardContact/sc-hsm-embedded) PKCS#11 module.
> 
> Those cards don't have a PKCS#15 structure, so you would need an emulation driver in OpenSC.

That's great. I installed it but it only found the C.CH.AUT and C.CH.ENC key. Since this is an eIDAS compliant card for electronic signatures, there should be a C.CH.SIG which isn't found

![grafik](https://github.com/user-attachments/assets/15ed98db-db34-4204-b42b-b1e3647c1b11)

**Comment by CardContact** [comment]
If memory serves me right, then the module should provide two slots, one for QES and one for CH.AUT and ENC.

We integrated support 9 years ago, so changes are that DGN is using a different card profile by now.

**Comment by DeEskalator** [comment]
Alright. Are you planning to implement support for newer DGN cards?

**Comment by frankmorgner** [comment]
please re-open if you plan to implement support for the token within OpenSC. or, alternatively, move the discussion to https://github.com/CardContact/sc-hsm-embedded
