### ISSUE TITLE
Etoken works on MacOs M1 - with Monterey version ? I'm using a hub and I can't get the etoken driver to work 

### ISSUE THREAD

**Issue by icomenezes** [OpenSC/OpenSC#3237]

**Comment by frankmorgner** [comment]
Please create a debug log of your problem as described in the [comments of our issue template](https://raw.githubusercontent.com/OpenSC/OpenSC/master/.github/ISSUE_TEMPLATE.md). You may also want to look at the hints on [how to write a good bug report](https://github.com/OpenSC/OpenSC/wiki/How-to-write-a-good-bug-report).
