### ISSUE TITLE
Improve PKCS#11 compliance

### ISSUE THREAD

**Issue by tc-anssi** [OpenSC/OpenSC#335]
As mentioned in 
http://comments.gmane.org/gmane.comp.encryption.opensc.devel/15647, OpenSC has
several issues related to the PKCS#11 standard.  For instance, the
standard specify the value of attributes such as `CKA_LOCAL` to reflect a specific state of objects. The
current implementation hard-code this value to `TRUE`. This is an issue in the case of imported objects (generated off-board) were it must be set to `FALSE`. Other important values such as `CKA_ALWAYS_SENSITIVE`
and `CKA_NEVER_EXTRACTABLE` are similarly set to a hard-coded value.

OpenSC should fetch real values from the underlying cards and expose them to PKCS#11 client applications.

**Comment by viktorTarasov** [comment]
Also discussed in #336, #338;
applied in 4915eaa56b4e81346e1696b2cb38a0f2df14db5b, bbedd4ef00bf457fdf11be7899c64579248885e1, facaf5969bc80ac82395fa2789df32c48e373085.
