### ISSUE TITLE
how to use pkcs11-spy

### ISSUE THREAD

**Issue by saratchandraprasadg** [OpenSC/OpenSC#347]
Hi,
I'm able to work on with pkcs11-tool, can some body let me know how can I use pkcs11-spy to get to know the flow of pkcs11 API calls.

root@nilotpal:/usr/lib# pkcs11-tool --module /usr/lib/opensc-pkcs11.so  --hash --input-file /home/sarat/Desktop/input --output-file /home/sarat/output
For the above operation how can I use pkcs11-spy to track the flow.
If any information is needed from my end please let me know.
Thank you.
Regards,
Sarat G

**Comment by dengert** [comment]
On 1/2/2015 2:23 AM, saratchandraprasadg wrote:
> Hi,
> I installed opensc, I would like test the API's of pkcs11, for that when I ran pkcs11-tool commands it's not displaying any thing.

More information...

With what parameters?

What card are you using? (It may not be supported)


start with opensc-tool to list readers and the ATR of the card.





>
> Can some one let me know, will there exists any dependencies to tun pkcs11-tool, if so please explain me. Can you also please help me in letting know how can I verify whether pkcs11-tool is properly
> installed and running fine in my desktop.


>
> As pkcs11-tool has commands like --hash and --sign is it compulsory to install engine_pkcs11 before I start with pkcs11-tool?

pkcs11-tool does not use engine_pkcs11.
Engine_pkcs11 is an OpenSSL plugin so OPenSSL can use PKCS#11.



> If any information is needed from my end please let me know.
> Thank you.
> Regards,
> Sarat G
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/347>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
How to use spy, its in the Wiki:

https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by saratchandraprasadg** [comment]
Hi Engert,
Thank you, now I could able to log the info on the card. 
By enabling OPENSC_DEBUG=9 I'm getting lot of debug info, so is there anyway I can limit that debug information by getting only functional calls when I perform some operation.

Regards,
Sarat G

**Comment by frankmorgner** [comment]
grep is your friend
