### ISSUE TITLE
on OpenSC/wiki/TCOS-based-preformatted-cards email adress wrong.

### ISSUE THREAD

**Issue by reviscan** [OpenSC/OpenSC#350]
on:
https://github.com/OpenSC/OpenSC/wiki/TCOS-based-preformatted-cards
you refernce a mail adress: 
pk@opensc-project.org
<pk@opensc-project.org>: connect to opensc-project.org[46.226.140.17]:25:
    Connection refused

How can I contact this person?

**Comment by martinpaljak** [comment]
Try this: http://smartcard-auth.de/impressum-de.html

**Comment by frankmorgner** [comment]
should the wiki be updated with the new email adress?

**Comment by martinpaljak** [comment]
You can't write an e-mail address of someone else onto the "permanent" web without his/her consent or initiative. No, only removing it would be OK.

**Comment by frankmorgner** [comment]
done
