### ISSUE TITLE
IAS-ECC: Cannot segregate key usage

### ISSUE THREAD

**Issue by tc-anssi** [OpenSC/OpenSC#353]
I had previously reported (opensc-devel) that IAS-ECC cards with the current implementation did not allow to segregate key usage. I have located that the issue lies in `src/pkcs15init/pkcs15-iasecc.c` in the `iasecc_pkcs15_fix_private_key_attributes` function.
From what I understood, the code fetch the card ACLs and maps that to key usage regardless of the key usage that was specified. This leads to an overwrite of the key usage the user required (or an union with them).
For instance, if I require a private key to be restricted to signature operations, I end up with all key usage bits enabled which is wrong.

The quick workaround below comments the `key_usage` overwrite, with which the card is still fully functional and keeps the key usage that was required by the application.

Viktor, I did not find something in the IAS-ECC specification that mandates to do such mapping, what is your opinion ?
```
--- a/src/pkcs15init/pkcs15-iasecc.c
+++ b/src/pkcs15init/pkcs15-iasecc.c
@@ -937,9 +937,9 @@ iasecc_pkcs15_fix_private_key_attributes(struct sc_profile *profile, struct sc_p
                                        IASECC_ALGORITHM_RSA_PKCS | IASECC_ALGORITHM_SHA2);
                        LOG_TEST_RET(ctx, rv, "Cannot add RSA_PKCS SHA2 supported mechanism");
 
-                       key_info->usage |= SC_PKCS15_PRKEY_USAGE_SIGN;
+                       //key_info->usage |= SC_PKCS15_PRKEY_USAGE_SIGN;
                        if (sdo_prvkey->docp.non_repudiation.value && sdo_prvkey->docp.non_repudiation.value[0])   {
-                               key_info->usage |= SC_PKCS15_PRKEY_USAGE_NONREPUDIATION;
+                               //key_info->usage |= SC_PKCS15_PRKEY_USAGE_NONREPUDIATION;
                                object->user_consent = 1;
                        }
                }
@@ -947,14 +947,14 @@ iasecc_pkcs15_fix_private_key_attributes(struct sc_profile *profile, struct sc_p
                        rv = iasecc_pkcs15_add_algorithm_reference(p15card, key_info, IASECC_ALGORITHM_RSA_PKCS);
                        LOG_TEST_RET(ctx, rv, "Cannot add RSA_PKCS supported mechanism");
 
-                       key_info->usage |= SC_PKCS15_PRKEY_USAGE_SIGN | SC_PKCS15_PRKEY_USAGE_SIGNRECOVER;
+                       //key_info->usage |= SC_PKCS15_PRKEY_USAGE_SIGN | SC_PKCS15_PRKEY_USAGE_SIGNRECOVER;
                }
                else if (ii == IASECC_ACLS_RSAKEY_PSO_DECIPHER)   {
                        rv = iasecc_pkcs15_add_algorithm_reference(p15card, key_info,
                                        IASECC_ALGORITHM_RSA_PKCS_DECRYPT | IASECC_ALGORITHM_SHA1);
                        LOG_TEST_RET(ctx, rv, "Cannot add decipher RSA_PKCS supported mechanism");
 
-                       key_info->usage |= SC_PKCS15_PRKEY_USAGE_DECRYPT | SC_PKCS15_PRKEY_USAGE_UNWRAP;
+                       //key_info->usage |= SC_PKCS15_PRKEY_USAGE_DECRYPT | SC_PKCS15_PRKEY_USAGE_UNWRAP;
                }
        }
```

**Comment by viktorTarasov** [comment]
@tc-anssi : Nothing like this in IAS/ECC specification. The key usages are set from the real key-slot attributes .

Does the <i>all key usage bits enabled</i> correspond to the format of your card ?
In the IAS/ECC card profiles that I know there are no keys-slots where all key usages are enabled .

In general the key-slots in IAS/ECC have enabled different usages.
When importing/generating key a key-slot with (at least) the asked key usages is looked for.
Then the final key usages are set from the real attributes of the selected key-slot .
I agree that this last stage can be disputed.

**Comment by tc-anssi** [comment]
Hi @viktorTarasov,

>Does the all key usage bits enabled correspond to the format of your card ?

How can I make sure about that ? I am using a Gemalto IAS-ECC card (profile A05) and I did not perform the personalization step myself.

Is there an easy way to display the current key-slots and their respective key usages ? (OPENSC_DEBUG is rather cryptic about that).

**Comment by viktorTarasov** [comment]
Hi @tc-anssi, 
As it usual for IAS/ECC cards, in A05 profile the COMPUTE DIGITAL usage is allowed only for one key-slot in <i>protected</i> application (destinated to hold the <i>qualified signature</i> key). In that application there is/are also slots with INT.AUTHENTICATE usage.
In <i>generic</i> application there are slots with INT.AUTHENTICATE and DECIPHER usages.

With IAS/ECC specification you can decrypt the SDO attributes.  <i>Iasecc-tool</i> from OpenSC distribution can help to found out the pre-formatted SDOs of a given type and to print some of its attributes. To see complete SDO attribute data I used the opensc debug .

Contact me if you are looking for specification or profile .

**Comment by tc-anssi** [comment]
I will have a look at this next week and I will update the bug report accordingly.
