### ISSUE TITLE
Build problem with Homebrew in MacOSX, claims that winscard.h is missing

### ISSUE THREAD

**Issue by henrik242** [OpenSC/OpenSC#355]
See https://github.com/Homebrew/homebrew/issues/35979

**Comment by LudovicRousseau** [comment]
Maybe you should document exactly what you did to get this error.

**Comment by henrik242** [comment]
Sure: it was just a ``brew install opensc``.  Should I copy some more of the info from the other issue?

**Comment by martinpaljak** [comment]
On 17/01/15 20:09, henrik242 wrote:
> Sure: it was just a ``brew install opensc``.  Should I copy some more of the info from the other issue?
I don't know much about homebrew internals, but I know it works well
with components from homebrew:

cat OpenSC/MacOSX/build-package.in
#!/bin/bash
# Building the installer is only tested and supported on 10.9+ with
Xcode 6.0.1
# Built package targets 10.9+
# Building should also work on older versions with older revisions or
slight changes, YMMV

# You need to have  the following from homebrew or macports or fink:
# autoconf automake libtool pkg-config


If you insist on using homebrew you need to make sure you install the
tokend, if you intend to use native apps.


-- 
Martin
+372 5156 495

**Comment by henrik242** [comment]
@martinpaljak I don't quite understand what you just said.  OpenSC builds and works just fine with Homebrew after editing ``winscard.h``.

**Comment by LudovicRousseau** [comment]
@henrik242, Editing a system file is not a good idea.

I can't reproduce your problem on Mavericks (10.9).
``brew install --build-from-source opensc`` works fine for me.

I did not know OpenSC was available on Hombrew. That is a good news.

**Comment by henrik242** [comment]
> Editing a system file is not a good idea.

Not at all, that's why I created this issue in the first place :)

> I can't reproduce your problem on Mavericks (10.9).

I  tried reproducing this issue on a different machine (also running Yosemite), and there it worked like a charm.  So it seems to be a local problem with my machine.

I'll just close this, then.  Thanks for all your feedback!  (And if anyone figures out what made my install fail, feel free to speak out.)
