### ISSUE TITLE
Add a way to not load a driver

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#358]
Hello,

On my laptop with one integrated reader, I'm trying to use both my id card (belpic) in firefox and my gpg card via the gpg command. This is ATM unfortunately not working because as soon as I insert the gpg card opensc loaded in firefox is taking a lock on it.

Would it be possible to add a way to not load a driver (and then not taking a lock) on a specific card type? Maybe adding a "disabled" driver that could be set via a "card_atr" block?

**Comment by dengert** [comment]
On 1/20/2015 5:48 AM, Laurent Bigonville wrote:
> Hello,
>
> On my laptop with one integrated reader, I'm trying to use both my id card (belpic) in firefox and my gpg card via the gpg command. This is ATM unfortunately not working because as soon as I insert
> the gpg card opensc loaded in firefox is taking a lock on it.
>
> Would it be possible to add a way to not load a driver (and then not taking a lock) on a specific card type? Maybe adding a "disabled" driver that could be set via a "card_atr" block?

Have you looked at the lock options on opensc.conf?

You could also have two opensc.conf files, a modified one for firefox and set the OPENSC_CONF env variable
before starting firefox.

In the opensc.conf, you can use the card_driver= to limit which driver or drivers are loaded.
So if the driver is not loaded, OpenSC will not use the card.


>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/358>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martinpaljak** [comment]
Disabling drivers is a good way of doing it. But it would also be cool if one could disable applications (PKCS11/tokend/minidriver) based on reader names and/or ATR-s.

The lock options does not help here, gnupg insists on having exclusive access to readers, which means it conflicts with OpenSC that normally tries to keep them in shared mode (which what the lock options adjusts)

**Comment by bigon** [comment]
Wouldn't it be a good idea to be able to negate a driver?

ie. card_drivers = !openpgp, internal;

**Comment by bigon** [comment]
Or being able to not load a driver per atr?

Something like:
        card_atr XX:XX:XX {
                driver = "none";
        }

**Comment by frankmorgner** [comment]
You may explicitly list all names of the internal drivers except the openpgp one. This effectively does what you're intending.

**Comment by bigon** [comment]
being able to set the driver to "none" in a card_atr would give more granularity. Setting a nonexisting driver is not working, but setting a wrong driver to the card atr is doing what I'm looking for (not loading a driver) but this feels not really OK
