### ISSUE TITLE
MacOS X build Error "No such file or directory"

### ISSUE THREAD

**Issue by gautric** [OpenSC/OpenSC#359]
No  "OpenSC.tokend (OpenSC.tokend/build/OpenSC.tokend)" sub directory created after 
 Build and copy OpenSC.tokend
 xcodebuild -configuration Deployment -project OpenSC.tokend/Tokend.xcodeproj

Output : 
"+ mkdir -p target/System/Library/Security/tokend
+ mv OpenSC.tokend/build/OpenSC.tokend target/System/Library/Security/tokend
mv: rename OpenSC.tokend/build/OpenSC.tokend to target/System/Library/Security/tokend/OpenSC.tokend: No such file or directory"

Mac OS X : 10.10.1
XCode : 6.1.1

**Comment by frankmorgner** [comment]
See this log https://travis-ci.org/OpenSC/OpenSC/jobs/60940275 how we are building on OS X with tokend which seems to work just fine
