### ISSUE TITLE
Bad implementation of DNIe's UI

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#362]
1. The configure option `--disable-openssl` doesn't work with `--enable-dnie-ui`

  The problem is that `sc_ask_user_pin` and `sc_ask_user_consent` depend on internal structures of the DNIe driver. However, this card driver is only compiled if OpenSSL is present.

  Possible solutions:
  - Merge the content of `user-interface.c` into `card-dnie.c`
  - Make the user interface implementation standalone

2. user_consent_app in opensc.conf should be documented in opensc.conf and *not* be hardcoded in card-dnie.c

3. Also, the code in `user-interface.c` is quite messy and needs some cleanup. For example, sc_ask_user_pin is useless because ui_ask_user_pin is not implemented.

**Comment by germanblanco** [comment]
Hello Frank,
I thought that the entire dnie implementation depended on OpenSSL. If I am right with that, "enable-dnie-ui" doesn't make any sense together with "disable-openssl". In any case, the cleanup suggestions sound good to me too, so I will propose some fixes if nobody else volunteers.
Regards,
/German

**Comment by frankmorgner** [comment]
If so, you may want to surround the UI implementation with `#ifdef ENABLE_OPENSSL` to disable compilation when OpenSSL is not available.

**Comment by germanblanco** [comment]
Yes, thank you, it should have been done like that! In fact, the entire card-dnie.c is surrounded by those. I will make a Pull request for that.

**Comment by frankmorgner** [comment]
These problems are still open:

2. user_consent_app in opensc.conf should be documented in opensc.conf and not be hardcoded in card-dnie.c
3. Also, the code in user-interface.c is quite messy and needs some cleanup. For example, sc_ask_user_pin is useless because ui_ask_user_pin is not implemented.

**Comment by germanblanco** [comment]
I am working on it now

**Comment by rickyepoderi** [comment]
@germanblanco I had a look to this file and it is currently used only for displaying the warning that DNIe displays before performing a signature. It is only used if --enable-dnie-ui is used at configure time. It uses OS methods in windows and mac and pinentry in linux. There are two options  that are placed in "card_driver dnie" section, user_consent_app (the pinentry command) and user_consent_enabled (a flag to disable the warning).

The other method sc_ask_user_pin is not used by DNIe (it is not implemented) and can be removed. 

What I don't understand is why those methods are called sc_* and have a .h file, you know, like if they were general opensc methods. If those methods are only for dnie and they are not going to be used by other drivers we can even integrate the sc_ask_user_consent into card-dnie.c as a private function. But I don't know, maybe you want the methods to be available to the rest of cards.

**Comment by germanblanco** [comment]
Pull request proposed, please take a look. 
DNIe user interface moved into card-dnie.c. Handles: Bad implementation of DNIe's UI #362 #602
