### ISSUE TITLE
ePass2003 concurrency/session issues

### ISSUE THREAD

**Issue by martin-css** [OpenSC/OpenSC#364]
PKCS11 support for the Feitian ePass2003 token currently has major concurrency issues that prevent effective use of this token in real life application (at least in an Ubuntu environment). This relates to version 0.13 of OpenSC which is the latest version in the official Ubuntu repositories.

PKCS11 functionality will work fine when only a single application has initialised a session. When another application uses the library, this will also work as expected. However, the first applications session will now be invalid and any functions called will fail.

I've created a [Vagrant test image](https://github.com/martin-css/epass2003-test) that allows easy replication of this issue for diagnosis.

Please see the following PKCS11 spy logs that illustrate the test case in the above test environment.

[SSH Agent Initiailsation] (http://pastebin.com/WTXbfymC)
[Successful SSH signing](http://pastebin.com/taEVr6Wg)

The PKCS11 utility is then used as a simple way of causing another application to use the library. This is allowed to complete successfully. Subsequent calls by ssh-agent will now fail as per the example log below:

[Failed SSH signing](http://pastebin.com/Z6iwq1fr)

**Comment by martin-css** [comment]
Please note this issue is still active as per latest master state at time of writing - commit b13bb3cbf53fede96e5d397329fd2ece18b98d0c.

**Comment by martinpaljak** [comment]
PKCS#11 spy log is useful, but not enough to debug OpenSC. Please provide a (failing, at least) OpenSC debug log at sufficient level (try 9).

**Comment by martin-css** [comment]
As far as I can see from the source code, the PKCS11 library does not have any option to specify a higher debug level. It's not a OpenSC tool that's failing, it's any application that uses the library, in my example ssh-agent.

I can provide a log of the pcscd daemon run in debug mode if this is helpful?

Alternatively, anyone who owns one of these tokens can use the test environment linked in the first post to replicate the issue.

**Comment by frankmorgner** [comment]
use the environment variable OPENSC_CONF to specify a configuration file with a higher debug level

**Comment by martin-css** [comment]
I've created level 9 debug log output for the initialisation, successful signing and failed signing so these can be compared. I've also re-included the spy log for this run in case this is useful.

## SSH Agent Initialisation

[OpenSC Debug Log](http://pastebin.com/wnTw3PQS)
(PKCS11 Spy Log)[http://pastebin.com/Hgab3eEV]

## Successful SSH signing

[OpenSC Debug Log](http://pastebin.com/NbMDzLz8)
(PKCS11 Spy Log)[http://pastebin.com/daTJrN9f]

## Failed SSH signing

[OpenSC Debug Log](http://pastebin.com/qv3xHwBg)
(PKCS11 Spy Log)[http://pastebin.com/ebZwGdyM]

**Comment by dengert** [comment]
On 1/26/2015 4:57 AM, Martin Campbell wrote:
> PKCS11 support for the Feitian ePass2003 token currently has major concurrency issues that prevent effective use of this token in real life application (at least in an Ubuntu environment).
>
> PKCS11 functionality will work fine when only a single application has initialised a session. When another application uses the library, this will also work as expected. However, the first
> applications session will now be invalid and any functions called will fail.

What is the other application?


 From your opensc-debug logs, it looks like the failing session has:
45.0x7f394a8af740 09:08:39.500 [opensc-pkcs11] reader-pcsc.c:413:pcsc_reconnect: Reconnecting to the card...
the ePass2003 is using secure messaging :
card-epass2003.c:873:epass2003_sm_get_wrapped_apdu: called

Some things that could be going on:
  Card was reset when other application finished, thus the pcsc_reconnect.

  Card's and ssh agent's SM state don't agree because other application reset the SM state of card when it stated using SM
  so ssh agent state does not match the card now. It could be that the SM needs to be reset  if pcsc_reconnect needs to be called.

  SM and card locking (see opensc.conf) don't play well together.

  SSH agent is expecting exclusive use of the card, and keeps pkcs11 session open, rather then closing it after each use.

Some things to try:

  Change the locking in opensc.conf

  Try using a different smart card that does not use SM. This could be a SM issuer, or a more general issue for other cards too.


(You have also edited the logs, by only shown part of the logs. Operation 17 is the first entry is each log.
It is not clear what the ssh agent is doing.)


>
> I've created a Vagrant test image <https://github.com/martin-css/epass2003-test> that allows easy replication of this issue for diagnosis.
>
> Please see the following PKCS11 spy logs that illustrate the test case in the above test environment.
>
> SSH Agent Initiailsation <http://pastebin.com/WTXbfymC>
> Successful SSH signing <http://pastebin.com/taEVr6Wg>
>
> The PKCS11 utility is then used as a simple way of causing another application to use the library. This is allowed to complete successfully. Subsequent calls by ssh-agent will now fail as per the
> example log below:
>
> Failed SSH signing <http://pastebin.com/Z6iwq1fr>
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/364>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martinpaljak** [comment]
I think that p11-kit should be suggested for such uses, where a single
daemon would marshal the PKCS#11 calls to a single module instance,
together with secure messaging, if any.

--
Martin
+372 515 6495

**Comment by martin-css** [comment]
>What is the other application?

In the test environment created above, a run of the `pkcs11-tool` is used to simulate another application accessing the card. However, the actual application is immaterial, the issue occurs when two or more applications are attempting to use the PKCS11 module concurrently. In a real life example, Mozilla Thunderbird is running to access email with a client certificate on the smart card and the smart card is then used to authenticate for SSH access. Thunderbird will no longer work until restarted and the PKCS11 module logged into again due to this concurrency issue.

> SSH agent is expecting exclusive use of the card, and keeps pkcs11 session open, rather then closing it after each use.

This is the root cause, the library is not handling the case when multiple applications have concurrent PKCS11 sessions active.

>Try using a different smart card that does not use SM. This could be a SM issuer, or a more general issue for other cards too.

I can't state if it's a secure messaging issue or not but I can confirm this issue does not occur with other cards. For example, we have some older Feitian PKI cards using the Entersafe driver that will happily work with multiple concurrent PKCS11 sessions. These cards will pass the test devised in the first issue comment. If it helps, I can check if these support secure messaging.

>(You have also edited the logs, by only shown part of the logs. Operation 17 is the first entry is each log. It is not clear what the ssh agent is doing.)

I had split these into separate sections to go with the OpenSC debug logs. However, please see this [complete PKCS11 spy output](http://pastebin.com/40htFDt5) for an example of all operations, the first 21 being carried out in sequence, another application then using the card and then operation 22 onwards being the attempted use by ssh-agent again which fails.

**Comment by martin-css** [comment]
>Change the locking in opensc.conf

I can confirm that explicitly setting `lock_login` to `false`,setting the all relevant `reader_driver pcsc` actions to `leave` and `connect_exclusive` to `false` all had no effect, the problem still occurs.

Let me know if there are any other configuration settings you would like me to try.

>Card's and ssh agent's SM state don't agree because other application reset the SM state of card when it stated using SM so ssh agent state does not match the card now. It could be that the SM needs to be reset  if pcsc_reconnect needs to be called.

I've never looked at the OpenSC source before now so am greatly unfamiliar with the code base but something like this would sound the most likely culprit to me. I suspect there is a card driver issue.

**Comment by dengert** [comment]
It looks when it fails reader-pcsc.c pcsc_lock() may return SC_ERROR_READER_REATTACHED or SC_ERROR_CARD_RESET
to "return failure so that upper layers will be notified and try to lock again"

card.c sc_lock() will invalidate a cache, I would assume it also need to reopen any SM.

card-epass2003.c has card->sm_ctx.ops.open = epass2003_refresh;

This may be a shot in the dark and has not been compiled, but try something like this:

diff --git a/src/libopensc/card.c b/src/libopensc/card.c
index 9a33172..9a691bf 100644
--- a/src/libopensc/card.c
+++ b/src/libopensc/card.c
@@ -334,6 +334,8 @@ int sc_lock(sc_card_t *card)
                                 /* invalidate cache */
                                 memset(&card->cache, 0, sizeof(card->cache));
                                 card->cache.valid = 0;
+                               if (card->sm_ctx.ops.open)
+                                   card->sm_ctx.ops.open(card);
                                 r = card->reader->ops->lock(card->reader);
                         }
                 }


On 1/27/2015 9:32 AM, Martin Campbell wrote:
>     Change the locking in opensc.conf
>
> I can confirm that explicitly setting |lock_login| to |false|,setting the all relevant |reader_driver pcsc| actions to |leave| and |connect_exclusive| to |false| all had no effect, the problem still
> occurs.
>
> Let me know if there are any other configuration settings you would like me to try.
>
>     Card's and ssh agent's SM state don't agree because other application reset the SM state of card when it stated using SM so ssh agent state does not match the card now. It could be that the SM
>     needs to be reset if pcsc_reconnect needs to be called.
>
> I've never looked at the OpenSC source before now so am greatly unfamiliar with the code base but something like this would sound the most likely culprit to me. I suspect there is a card driver issue.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/364#issuecomment-71667107>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martin-css** [comment]
Sadly didn't work. The [failure log](http://pastebin.com/p9q7wbJw) shows that the mutual authentication is being called with these modifications but it then seems to die halfway through the process without returning any errors.

**Comment by martin-css** [comment]
I've got this fixed thanks to Douglas's help.

pcsc_lock() was returning `C_ERROR_CARD_RESET`. The subsequent attempted use of the card was failing because of the secure messaging support, the mutual authentication needed re-established.

I added the code suggested by Douglas but noticed from the log that this was failing because it was still attempting to wrap the APDU wrapped in the previous secure messaging context. I updated the ePass2003 driver to disable the `SM_MODE_TRANSMIT` flag when re-establishing mutual authentication and then re-apply once complete.

This fixes all the concurrency issues I've tested and does not cause any problems with the initial use of the token.  I can be confident the change to `card-epass2003.c` will have no adverse effects but you would need to check if the `card.c` changes would have any unexpected consequences.

**Comment by dengert** [comment]
Any card using SM may have the same issues.

./card-authentic.c  has: card->sm_ctx.ops.open = authentic_sm_open;
so it may benefit from this change, but authentic_sm_open needs to be looked at.





On 1/28/2015 6:05 AM, Martin Campbell wrote:
> I've got this fixed thanks to Douglas's help.
>
> pcsc_lock() was returning |C_ERROR_CARD_RESET|. The subsequent attempted use of the card was failing because of the secure messaging support, the mutual authentication needed re-established.
>
> I added the code suggested by Douglas but noticed from the log that this was failing because it was still attempting to wrap the APDU wrapped in the previous secure messaging context. I updated the
> ePass2003 driver to disable the |SM_MODE_TRANSMIT| flag when re-establishing mutual authentication and then re-apply once complete.
>
> This fixes all the concurrency issues I've tested and does not cause any problems with the initial use of the token. I can be confident the change to |card-epass2003.c| will have no adverse effects
> but you would need to check if the |card.c| changes would have any unexpected consequences.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/364#issuecomment-71824944>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
fixed with #365
