### ISSUE TITLE
OpenUSBByName() Can't claim interface 003/006: Device or resource busy

### ISSUE THREAD

**Issue by jtreubig** [OpenSC/OpenSC#370]
Hi guys,

Attempting to get OpenSC going on my machine and it works sporadically - with card inserted at boot, the device is claimed by OpenSC.  After I remove the card and reinsert, it can't reclaim the device.  Appears I've got a competing process claiming the device, but I don't know how to track down the competing process.  Ran pcscd --foreground --debug --apdu with the output below.  Then afterward is a copy of the system log boot that the reader is functional.

O/S: CentOS 6.6
OpenSC-0.14.0

user@localhost Desktop]$ sudo /usr/sbin/pcscd --foreground --debug --apdu
00000000 pcscdaemon.c:267:main() pcscd set to foreground with debug send to stderr
00000010 debuglog.c:239:DebugLogSetLevel() debug level=debug
00000003 debuglog.c:268:DebugLogSetCategory() Debug options: APDU
00000153 pcscdaemon.c:506:main() pcsc-lite 1.5.2 daemon ready.
00248076 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x058F, PID: 0x9540
00000008 hotplug_libhal.c:342:HPAddDevice() Adding USB device: usb_device_58f_9540_noserial_if0
01001145 readerfactory.c:1024:RFInitializeReader() Attempting startup of Alcor Micro AU9540 00 00 using /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00000361 readerfactory.c:877:RFBindFunctions() Loading IFD Handler 3.0
00000054 ifdhandler.c:1377:init_driver() Driver version: 1.3.9
00000936 ifdhandler.c:1390:init_driver() LogLevel: 0x0003
00000808 ifdhandler.c:1410:init_driver() DriverOptions: 0x0000
00000017 ifdhandler.c:81:IFDHCreateChannelByName() lun: 0, device: usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0
00060035 ccid_usb.c:236:OpenUSBByName() Manufacturer: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000825 ccid_usb.c:246:OpenUSBByName() ProductString: Generic CCID driver
00000798 ccid_usb.c:252:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00066257 ccid_usb.c:402:OpenUSBByName() Can't claim interface 003/006: Device or resource busy
00000004 ifdhandler.c:102:IFDHCreateChannelByName() failed
00000004 readerfactory.c:1050:RFInitializeReader() Open Port 200000 Failed (usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0)
00000002 readerfactory.c:914:RFUnloadReader() Unloading reader driver.
00000021 readerfactory.c:233:RFAddReader() Alcor Micro AU9540 init failed.
00000360 hotplug_libhal.c:432:HPAddDevice() trying libusb scheme with: usb:058f/9540:libusb:003:006
00000005 readerfactory.c:1024:RFInitializeReader() Attempting startup of Alcor Micro AU9540 00 00 using /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00000072 readerfactory.c:877:RFBindFunctions() Loading IFD Handler 3.0
00000012 ifdhandler.c:1377:init_driver() Driver version: 1.3.9
00000188 ifdhandler.c:1390:init_driver() LogLevel: 0x0003
00000160 ifdhandler.c:1410:init_driver() DriverOptions: 0x0000
00000003 ifdhandler.c:81:IFDHCreateChannelByName() lun: 0, device: usb:058f/9540:libusb:003:006
00000287 ccid_usb.c:236:OpenUSBByName() Manufacturer: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000157 ccid_usb.c:246:OpenUSBByName() ProductString: Generic CCID driver
00000155 ccid_usb.c:252:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00063958 ccid_usb.c:402:OpenUSBByName() Can't claim interface 003/006: Device or resource busy
00000004 ifdhandler.c:102:IFDHCreateChannelByName() failed
00000003 readerfactory.c:1050:RFInitializeReader() Open Port 200000 Failed (usb:058f/9540:libusb:003)
00000002 readerfactory.c:914:RFUnloadReader() Unloading reader driver.
00000012 readerfactory.c:233:RFAddReader() Alcor Micro AU9540 init failed.
00000002 hotplug_libhal.c:439:HPAddDevice() Failed adding USB device: usb_device_58f_9540_noserial_if0
00000005 utils.c:213:CheckForOpenCT() Remove OpenCT and try again
00012655 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x8087, PID: 0x8000
00000430 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x1D6B, PID: 0x0002
00001524 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x8087, PID: 0x8008
00000430 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x1D6B, PID: 0x0002
00000885 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x0B95, PID: 0x1790
00000450 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x1D6B, PID: 0x0003
00000431 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x0403, PID: 0x6011
00000323 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x0403, PID: 0x6011
00000348 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x0403, PID: 0x6011
00000324 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x0403, PID: 0x6011
00000449 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x04CA, PID: 0x7034
00000331 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x04CA, PID: 0x7034
00000431 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x138A, PID: 0x003F
00000456 hotplug_libhal.c:307:get_driver() Looking a driver for VID: 0x1D6B, PID: 0x0002

Here's a copy of the system log where the reader is functional from boot.

Feb  2 14:02:53 localhost pcscd: pcscdaemon.c:581:signal_trap() Preparing for suicide
Feb  2 14:02:54 localhost pcscd: readerfactory.c:1267:RFCleanupReaders() entering cleaning function
Feb  2 14:02:54 localhost pcscd: pcscdaemon.c:531:at_exit() cleaning /var/run
Feb  2 14:02:54 localhost pcscd: pcscdaemon.c:506:main() pcsc-lite 1.5.2 daemon ready.
Feb  2 14:03:14 localhost pcscd: hotplug_libhal.c:342:HPAddDevice() Adding USB device: usb_device_58f_9540_noserial_if0
Feb  2 14:03:15 localhost pcscd: readerfactory.c:1024:RFInitializeReader() Attempting startup of Alcor Micro AU9540 00 00 using /usr/lib64/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
Feb  2 14:03:15 localhost pcscd: readerfactory.c:877:RFBindFunctions() Loading IFD Handler 3.0
Feb  2 14:03:15 localhost pcscd: ifdhandler.c:1377:init_driver() Driver version: 1.3.9
Feb  2 14:03:15 localhost pcscd: ifdhandler.c:1390:init_driver() LogLevel: 0x0003
Feb  2 14:03:15 localhost pcscd: ifdhandler.c:1410:init_driver() DriverOptions: 0x0000
Feb  2 14:03:15 localhost pcscd: ifdhandler.c:81:IFDHCreateChannelByName() lun: 0, device: usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0
Feb  2 14:03:15 localhost pcscd: ccid_usb.c:236:OpenUSBByName() Manufacturer: Ludovic Rousseau (ludovic.rousseau@free.fr)
Feb  2 14:03:15 localhost pcscd: ccid_usb.c:246:OpenUSBByName() ProductString: Generic CCID driver
Feb  2 14:03:15 localhost pcscd: ccid_usb.c:252:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
Feb  2 14:03:15 localhost pcscd: ccid_usb.c:408:OpenUSBByName() Found Vendor/Product: 058F/9540 (Alcor Micro AU9540)
Feb  2 14:03:15 localhost pcscd: ccid_usb.c:410:OpenUSBByName() Using USB bus/device: 003/006
Feb  2 14:03:17 localhost pcscd: ccid_usb.c:780:get_data_rates() IFD does not support GET_DATA_RATES request: Connection timed out
Feb  2 14:03:17 localhost pcscd: ifdhandler.c:334:IFDHGetCapabilities() tag: 0xFB0, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:17 localhost pcscd: readerfactory.c:249:RFAddReader() Using the pcscd polling thread
Feb  2 14:03:17 localhost pcscd: ifdhandler.c:334:IFDHGetCapabilities() tag: 0xFAE, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:17 localhost pcscd: ifdhandler.c:377:IFDHGetCapabilities() Reader supports 1 slot(s)
Feb  2 14:03:17 localhost pcscd: ifdhandler.c:964:IFDHPowerICC() action: PowerUp, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: Card ATR: 3B F5 18 00 00 81 31 FE 45 4D 79 45 49 44 9A 
Feb  2 14:03:18 localhost pcscd: prothandler.c:128:PHSetProtocol() Attempting PTS to T=1
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:522:IFDHSetProtocolParameters() protocol T=1, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1505:extra_egt() Extra EGT patch applied
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1131:IFDHControl() ControlCode: 0x42000D48, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: Control TxBuffer: 
Feb  2 14:03:18 localhost pcscd: Control RxBuffer: 
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:18 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:19 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:19 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:19 localhost pcscd: ifdhandler.c:1091:IFDHTransmitToICC() usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)
Feb  2 14:03:19 localhost pcscd: ifdhandler.c:964:IFDHPowerICC() action: Reset, usb:058f/9540:libhal:/org/freedesktop/Hal/devices/usb_device_58f_9540_noserial_if0 (lun: 0)

**Comment by martinpaljak** [comment]
This is not a problem with OpenSC but with PC/SC. More precisely, there'
s an answer in the log:

00000005 utils.c:213:CheckForOpenCT() Remove OpenCT and try again


You also have OpenCT competing for the device, apparently. Remove OpenCT (openct*)

**Comment by jtreubig** [comment]
Martin,

Had to remove pcsc-lite-openct and openct and now works like a charm.  

Thanks,
John
