### ISSUE TITLE
No header files are included in installation

### ISSUE THREAD

**Issue by darconeous** [OpenSC/OpenSC#378]
I wanted to use OpenSC APIs for an open-source PKI-based PACS that I am developing (A quick prototype which uses the OpenSC command-line tools can be found [here](https://plus.google.com/112605652687169110943/posts/3Czxg4fkTgo).). However, I noticed that the header files don't appear to be a part of a normal install.

This is pretty easy to work around on my end, but I'm curious if there is any reason why you wouldn't install the header files so that other projects could easily build against your library.

**Comment by dengert** [comment]
On 2/12/2015 6:59 PM, Robert Quattlebaum wrote:
> I wanted to use OpenSC APIs for an open-source PKI-based PACS that I am developing (A quick prototype which uses the OpenSC command-line tools can be found here
> <https://plus.google.com/112605652687169110943/posts/3Czxg4fkTgo>.). However, I noticed that the header files don't appear to be a part of a normal install.
>
> This is pretty easy to work around on my end, but I'm curious if there is any reason why you wouldn't install the header files so that other projects could easily build against your library.
>

PKCS#11 is the normal way to use OpenSC. The internal header files can change at any time, use at your own risk.


> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/378>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martinpaljak** [comment]
If you have PKI/crypto oriented application, *that is supposed to work with different cards* in a standards-compliant way, use PKCS#11. If you have something that is closer to a specific card and specific commands (that expect fast processing) use PC/SC directly. 

Or you can include code from OpenSC in your project, as long as you fulfill LGPL but don't expect API/ABI compatibility.

**Comment by darconeous** [comment]
My trouble with using PKCS#11 is that it always asks for my PIN, even to simply use the Card Authentication Key (Which should never require a PIN). At least, that is how `pkcs11-tool` behaves. Is that just a `pkcs11-tool` quirk?

In any case, why not at least include PKCS#11 headers?

**Comment by martinpaljak** [comment]
If you thrive for speed, I suggest to have card-specific PC/SC code. If you want interoperability, use PKCS#11. Making the overall architecture faster (think: callbacks instead of population of all the data) you are free to start the quest but this is quite an undertaking, IMHO.

Your application, if supporting PKCS#11, must have the headers no matter if you use OpenSC or some other PKCS#11 provider. So I don't think it would make sense to have a separate copy with OpenSC.

**Comment by dengert** [comment]
On 2/13/2015 12:11 PM, Robert Quattlebaum wrote:
> My trouble with using PKCS#11 is that it always asks for my PIN, even to simply use the Card Authentication Key (Which should never require a PIN). At least, that is how |pkcs11-tool| behaves. Is that
> just a |pkcs11-tool| quirk?

Yes its a quirk in pkcs11-tool or the pkcs11/framework-pkcs15.c I don't know of any other cards
that have a key that does not require a PIN, so most code assums you need a PIN.

Try this with a PIV card:
echo "Hello world!" > hello.text
pkcs15-crypt -s -k 04 -i hello.text -o hello.sig --pkcs1

No PIN is required and roduces the same output as:
pkcs11-tool -pkcs11-tool --slot 1 --module /opt/smartcard/lib/opensc-pkcs11.so -s -d 04 -i hello.text -o hello-p11.sig -m RSA-PKCS



With pkcs15-crypt with a random nonce to be signed,
and


>
> In any case, why not at least include PKCS#11 headers?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/378#issuecomment-74298766>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by arrowd** [comment]
I also bumped into the need to use libopensc directly, altough my problem seems to be quite common. Maybe I just missing something.

I need to programmatically to perform a factory reset, like what `openpgp-tool --erase` does. The documentation of the PKCS11 `C_InitToken` function says:

> If the SO PIN is lost, then the card MUST be reinitialized using a mechanism outside the scope of this standard.

So I can't do this with PCKS11 API, but I also can't access libopensc API directly. Any ideas what should I do?

**Comment by dengert** [comment]
> So I can't do this with PCKS11 API, but I also can't access libopensc API directly. Any ideas what should I do?

With OpenPGP cards, there is more then `reset` needed. OpenPGP has a lot of info not accessible from PKCS11. 

For Yubikey tokens see: https://support.yubico.com/hc/en-us/articles/360013790259-Using-Your-YubiKey-with-OpenPGP

I like GnuPG's  `gpg-card` command that will let you set all the OpenPGP data and use `factory-reset` and respond to prompts. 
To generate keys use something like this:
```
generate --algo=rsa2048 OPENPGP.3
generate --algo=ed25519 OPENPGP.1
generate --algo=cv25519 OPENPGP.2
```
The OpenSC `openpgp-tool` is out of date, and only supports OpenPGP 2.0

OpenSC `pkcs11-tool` does support deleting privkey and pubkey objects and generating new keys. 
I have been trying to add/fix some of the missing pieces in  https://github.com/dengert/OpenSC/tree/X25519-improvements-2
