### ISSUE TITLE
OpenSC does not support OAEP which is defined in PKCS#11 v2.20

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#386]
PKCS#11 v2.20 [1] defines the CKM_RSA_PKCS_OAEP mechanism  for using OAEP [2] with
decryption, but OpenSC does not support it. 

Issue #384 says they were:"forcing the MiniDriver version to 6 because we don't support card padding yet." After further discussion and reasearch, Microsoft will use OAEP padding with RSA in the Minidriver specification 7. 

There would be at least two ways to address this:
 (1) Microsoft Minidriver 7 specification [3] Section 3.2.3.2  PFN_CSP_UNPAD_DATA 
      offers a way for a minidriver to use routines in the KSP to remode the padding. 
      But this is only for the minidriver, and when run under the KSP. The Base CSP 
      never supported OAEP. 
 
 (2) Implement the  PKCS#11 padding in OpenSC, so it could be used from PKCS#11
      on machines other then windows. 

ALso see RFC 3447 [4]  Public-Key Cryptography Standards (PKCS) #1: RSA Cryptography 
Specifications Version 2.1

Anyone want to take a look at this?

 [1] http://www.emc.com/emc-plus/rsa-labs/standards-initiatives/pkcs-11-cryptographic-token-interface-standard.htm
  [2] http://en.wikipedia.org/wiki/Optimal_asymmetric_encryption_padding
  [3] https://msdn.microsoft.com/en-us/library/windows/hardware/dn631754(v=vs.85).aspx
  [4] https://www.ietf.org/rfc/rfc3447.txt

**Comment by martinpaljak** [comment]
Cards that deal with padding need to support OAEP as well, so it shall depend on the card capability.

**Comment by dengert** [comment]
Agreed, but we do hashing (via OpenSSL) and padding is software in OpenSC. The minidriver version 7 specs expected it to emulate a card that can do OAEP, or to call the Microsoft call back
to remove or add the padding. A card would either have to support OAEP (do any?) or support RAW RSA so the padding could be removed in software.

In the related issue, they back-leveled the minidriver to say it was version 6 to avoid the issue.
So it looks like Windows is basing the capability to do OAEP on the version of the minidriver.
When the data was encrypted a certificate, or pub key was used to to encrypt the data with OAEP.
Has the industry changed in that OAEP is now required? If not how does the one encrypting data know
if the card or software decrypting the data can support OAEP?

If Windows requires it with version 7, and a card does not support OAEP or RAW RSA, we can not
support the card under windows.

On 2/25/2015 5:39 AM, Martin Paljak wrote:
> Cards that deal with padding need to support OAEP as well, so it shall depend on the card capability.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/386#issuecomment-75946482>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
closing this as wontfix. if anyone is willing to work on this, please re-open.
