### ISSUE TITLE
Morpho ypsid S3/IAS ECC not recognized by OpenSC 0.14

### ISSUE THREAD

**Issue by estieux-tehtri-security** [OpenSC/OpenSC#396]
I'm able to use this Morpho IAS/ECC smartcard with opensc 0.13 (shipped in Ubuntu or from tgz) but with opensc 0.14 (or from a github clone), I always get a "Failed to connect to card: Incorrect parameters in APDU"

You will find the log of the command `pkcs15-tool --list-applications -vvv` at https://gist.github.com/estieux-tehtri-security/1053e9b012877de05b04#file-gistfile1-txt

I use these smart card reader
opensc-tool -l
  # Detected readers (pcsc)  
  Nr.  Card  Features  Name
  0    No    PIN pad   Gemalto Ezio Shield (S1470138570755) 00 00
  1    Yes             Gemalto PC Twin Reader (4BA86842) 01 00

**Comment by viktorTarasov** [comment]
try the latest *master* (with c0c8a89126a0a11d315badcd778670d757b60f4c)

**Comment by estieux-tehtri-security** [comment]
Perfect, it's working now.
