### ISSUE TITLE
Enhancement: add "allowed_readers" parameter to OpenSC PKCS11 module

### ISSUE THREAD

**Issue by anstein** [OpenSC/OpenSC#397]
Unfortunately "ignored_readers" can't be used in the following case:

"reader-name"                           <=== to be ignored
"reader-name (serial)"           <=== to be used

Using an "allowed_readers" parameter neatly fixes this.

Patch for opensc-0.14.0:
https://gist.github.com/anstein/eb1ed5f0f91ddd5f051c

**Comment by martinpaljak** [comment]
Could you make it into a proper pull request, so that it would also get author information ?

**Comment by anstein** [comment]
On Sa, 2015-03-21 at 15:11 -0700, Martin Paljak wrote:
> Could you make it into a proper pull request, so that it would also
> get author information ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 
Sorry, I'd need a git 101 first :-(
-- 
Andreas Steinmetz

**Comment by frankmorgner** [comment]
please use a PR
