### ISSUE TITLE
sc_wait_for_event don't wait for next event

### ISSUE THREAD

**Issue by hadogenes** [OpenSC/OpenSC#401]
Hi,
I've wrote a code which should wait for card insert, but when insert sc_wait_for_event don't wait it  loops infinity. But when I remove card it stops and wait.
```c++
unsigned int ev = 0;
unsigned int eventMask = SC_EVENT_CARD_INSERTED;
int err;
sc_reader_t *eventReader;

sc_context_t *ctx = NULL;
sc_context_param_t *ctx_param = new sc_context_param_t();

ctx_param->ver = 0;
ctx_param->app_name = "AppName";

err = sc_context_create( &ctx, ctx_param );

while (true) {
	cout << "Waiting for event..." << endl;
	err = sc_wait_for_event( ctx, eventMask, &eventReader, &ev, -1,0 );
	cout << "Opensc out: " << sc_strerror(err) << endl;
}
```
and I have out
```
Waiting for event... 
Event: 1 expect: 1   
Opensc out: Success  
Waiting for event... 
Event: 1 expect: 1   
Opensc out: Success  
Waiting for event... 
Event: 1 expect: 1   
Opensc out: Success  
Waiting for event... 
Event: 1 expect: 1   
Opensc out: Success  
Waiting for event... 
Event: 1 expect: 1   
Opensc out: Success
...
```

**Comment by dengert** [comment]
This does not look complete.  Can you stat with using one of the utilities,
like opensc-tool which has a -wait option and calls util_connect_card that calls
sc_wait_for_event.

GDB might help show what is going on.

On 3/25/2015 5:58 AM, Jacek Szafarkiewicz wrote:
> Hi,
> I've wrote a code which should wait for card insert, but when insert sc_wait_for_event don't wait it loops infinity. But when I remove card it stops and wait.
>
> unsigned  int  ev =0;
> unsigned  int  eventMask = SC_EVENT_CARD_INSERTED;
> int  err;
> sc_reader_t  *checkReaders[SC_MAX_AID_SIZE];
>
> sc_context_t  *ctx =NULL;
> sc_context_param_t  *ctx_param =new  sc_context_param_t();
>
> ctx_param->ver =0;
> ctx_param->app_name ="AppName";
>
> err = sc_context_create( &ctx, ctx_param );
>
> while  (true) {
>      cout <<"Waiting for event..."  << endl;
>      err =sc_wait_for_event( ctx, eventMask, checkReaders, &ev, -1,0  );
>      cout <<"Opensc out:"  <<sc_strerror(err) << endl;
> }
>
> and I have out
>
> |Waiting for event...
> Event: 1 expect: 1
> Opensc out: Success
> Waiting for event...
> Event: 1 expect: 1
> Opensc out: Success
> Waiting for event...
> Event: 1 expect: 1
> Opensc out: Success
> Waiting for event...
> Event: 1 expect: 1
> Opensc out: Success
> Waiting for event...
> Event: 1 expect: 1
> Opensc out: Success
> ...
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/401>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by hadogenes** [comment]
The opensc-tool with -wait works, but this isn't a problem:
this program works
CODE:. wait for card 
ME: insert card
CODE: event 'card inserted'
CODE: event 'card inserted'
CODE: event 'card inserted'
... (infinity events)
ME: remove card
CODE:. wait for card 

How it should work
CODE:. wait for card
ME: insert card
CODE: event 'card inserted' (only one)
CODE:. wait for card

**Comment by hadogenes** [comment]
I'm running this program on Windows 7 64-bit

**Comment by dengert** [comment]
Yes, I was suggesting that you look at what opensc-tool does,
and compare to what your program is doing.

I assume "this program" is the program you had in the previous note?


I have a feeling is it has to do with not waiting for a reader first but waiting
for a card to be inserted. i.e. the code can not associate the reader with the event
of a card being inserted.

The tool/util.c:util_connect_card() is used by all the tools, waits for the reader, then for the card.

In your program, the number of readers, has nothing to do with the size of an AID.
sc_reader_t *checkReaders[SC_MAX_AID_SIZE];

You only posted part of the program, so it is hard to see what you are doing.
What code produced the "Event: 1 expect: 1" output?

Can you try and use the util_connect_card()?




On 3/25/2015 7:39 AM, Jacek Szafarkiewicz wrote:
> The opensc-tool with -wait works, but this isn't a problem:
> this program works
> CODE:. wait for card
> ME: insert card
> CODE: event 'card inserted'
> CODE: event 'card inserted'
> CODE: event 'card inserted'
> ... (infinity events)
> ME: remove card
> CODE:. wait for card
>
> How it should work
> CODE:. wait for card
> ME: insert card
> CODE: event 'card inserted' (only one)
> CODE:. wait for card
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/401#issuecomment-86009437>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by hadogenes** [comment]
Ok, it was my mistake. The last argument of sc_wait_for_event (reader_states) should be pointer which I store somewhere, but I filled with null.
