### ISSUE TITLE
OpenSC doesn't work correctly when working with multiple PIV card.

### ISSUE THREAD

**Issue by mohsenMgh** [OpenSC/OpenSC#413]
Hi everybody,
I use OpenSC 0.14.0 on Windows XP SP3. First when i insert PIV card to reader, OpenSC minidriver transfers certificates from PIV card to Windows store correctly. Then i remove PIV card and insert another PIV card  (which has new certificates) to reader but new certificates from new PIV card isn't transfered to Windows store. I delete old certificate from Windows store and reconnect new PIV card to computer but old certificate is show in store again. I repeated this, several times but every time, old certificates is showed.
When i restart windows, new certificate is transferred to Windows store. This means for every new card i must restart windows to can access to it certificates.

Questions:
1- why this is happend?
2- Does OpenSC cash certificates?
3- Can anyone help me to solve this problem?

Thanks in advance,

Mohsen

**Comment by dengert** [comment]
On 3/29/2015 5:26 AM, mohsenMgh wrote:
> Hi everybody,
> I use OpenSC 0.14.0 on Windows XP SP3. First when i insert PIV card to reader, OpenSC minidriver transfers certificates from PIV card to Windows store correctly. Then i remove PIV card and insert
> another PIV card (which has new certificates) to reader but new certificates from new PIV card isn't transfered to Windows store. I delete old certificate from Windows store and reconnect new PIV card
> to computer but old certificate is show in store again. I repeated this, several times but every time, old certificates is showed.
> When i restart windows, new certificate is transferred to Windows store. This means for every new card i must restart windows to can access to it certificates.
>

Are these U.S. gov officially issued PIV cards?
If not how were they initialized?

Does the card have a CHUID? Windows and OpenSC use this to derive a serial number, that must be different for each card.
The CHUID must be different on each card. If the cards do not have a CHUID or the CHUID is the same on the cards
both cards may look like the same card to Windows.

Do you have any other vendor PIV or CAC card drivers on the system?

> Questions:
> 1- why this is happend?

It should not happen, if the cards are different.

> 2- Does OpenSC cash certificates?

Not in this situation, Windows caches the certificates.

> 3- Can anyone help me to solve this problem?

An OpenSC debug trace would be helpful.
The output of a certutil.exe -v -scinfo

Windows 7 has a Microsoft PIV driver, so OpenSC is not needed when using Microsoft
programs like login or IE. Does W7 have the same problem with your multiple cards?

Also try
certutil.exe -v -scinfo

(I don't have an XP system at the moment to try anything on.)

>
> Thanks in advance,
>
> Mohsen
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/413>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
P.S.
Not sure if these are needed, but I think they are on XP:

http://support.microsoft.com/en-us/kb/909520

On 3/29/2015 5:26 AM, mohsenMgh wrote:
> Hi everybody,
> I use OpenSC 0.14.0 on Windows XP SP3. First when i insert PIV card to reader, OpenSC minidriver transfers certificates from PIV card to Windows store correctly. Then i remove PIV card and insert
> another PIV card (which has new certificates) to reader but new certificates from new PIV card isn't transfered to Windows store. I delete old certificate from Windows store and reconnect new PIV card
> to computer but old certificate is show in store again. I repeated this, several times but every time, old certificates is showed.
> When i restart windows, new certificate is transferred to Windows store. This means for every new card i must restart windows to can access to it certificates.
>
> Questions:
> 1- why this is happend?
> 2- Does OpenSC cash certificates?
> 3- Can anyone help me to solve this problem?
>
> Thanks in advance,
>
> Mohsen
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/413>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mohsenMgh** [comment]
Hi dengert
Thanks for your answer. It was very helpful. My problem was solved. You were right and cards CHUID serial numbers are same. Thanks a lot again.
Mohsen
