### ISSUE TITLE
MyEID: failed to import EC private key bignum with length less then key size.

### ISSUE THREAD

**Issue by viktorTarasov** [OpenSC/OpenSC#433]
Following key cannot be imported:
```
   0   94: SEQUENCE {
   2    1:   INTEGER 1
   5   23:   OCTET STRING
         :     7B 0C DA D3 F8 AA 7B 9B 13 DD 2A 1C 36 73 E7 6B
         :     69 40 EF 1C 4E CC 0E
  30   10:   [0] {
  32    8:     OBJECT IDENTIFIER ansiX9p192r1 (1 2 840 10045 3 1 1)
         :     }
  42   52:   [1] {
  44   50:     BIT STRING
         :       04 6E 92 D8 B3 B6 46 26 EB 96 0C A6 10 79 C3 50
         :       10 C7 99 68 A1 FC D1 55 31 18 14 B7 56 F1 E4 60
         :       A4 4D C1 ED 05 EF EA DF 6A 22 D7 90 AB F1 56 C8
         :       10
         :     }
         :   }
```

**Comment by dengert** [comment]
Sounds like it is related to:
http://openssl.6102.n7.nabble.com/openssl-dev-Reminder-OpenSSL-s-EC-private-key-encoding-is-broken-tt57165.html#none

where the length of a bignum is used to create the OCTETSTRING, and leading zeros are lost. Note the patch has been applied to OpenSSL. It might take a while  for the patch to make it into the field.

Something similar could be used in OpenSC to pad the short string where the length is gotten from the curve. For a 192 bit curve, the octes string should  be 24.

**Comment by dengert** [comment]
The field length in bits may not be a multiple of 8. openssl ecapram -list_curve
show  curves with field lengths of  521, 571, 239, 233 and many more. 

dst->params.field_length = EC_GROUP_get_degree(grp);

buf_len= (dst->params.field_length +7) / 8;

would support these curves too,and dst->params.field.length set correctly.


buf_len = (EC_GROUP_get_degree(a->group) + 7) / 8;

**Comment by viktorTarasov** [comment]
@dengert 
> The field length in bits may not be a multiple of 8 ...

In this line it's forced to be multiple of 8:
https://github.com/OpenSC/OpenSC/commit/96556dea7bff431e794641fcae6b732395e00854#diff-9640be6a2410e9f891deff03f1013247R709

**Comment by dengert** [comment]
There is the field length in bits, and there is the length of an OCTETSTRING in bytes that can
hold the data. If  dst->params.field_length is used later, its not the field length, it may be 1 to 7 bits to big.

With 521 bit curve, 66 bytes are need in the OCTSTRING.  66*8 = 528, which is not the field_length
it 7 bits to large.







On 4/13/2015 10:13 AM, viktorTarasov wrote:
> @dengert <https://github.com/dengert>
>
>     The field length in bits may not be a multiple of 8 ...
>
> In this line it's forced to be multiple of 8:
> 96556de#diff-9640be6a2410e9f891deff03f1013247R709 <https://github.com/OpenSC/OpenSC/commit/96556dea7bff431e794641fcae6b732395e00854#diff-9640be6a2410e9f891deff03f1013247R709>
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/433#issuecomment-92395969>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
@dengert 
Have you looked on the code?

*field_length* in OpenSC pkcs#15 data is not EC key size. 

```
buflen = EC_POINT_point2oct(EC_KEY_get0_group( ...
field_length = (buflen - 1) / 2 * 8; 
```
For 521bits it gives buflen = 133, and field_length = 528 (66*8)

**Comment by dengert** [comment]
Yes, In most places in opensc field_length is the number of bits in the curve.
and to get the size of the buffer to use, is done like in pkcs15-sec.c
  *poutlen = (prkey->field_length +7) / 8;


EC_POINT_point2oct returns the size of the buffer to hold the X and Y of a point, with
a leading byte usually 0x04. It will return the correct size or add the extra bytes
to the X and Y for curves with non multiples of 8.

But
    field_length = (buflen - 1) / 2 * 8;
is not the field length.

./pkcs15-pubkey.c
		{"secp521r1",		"1.3.132.0.35", "06052B81040023", 521},
		{"nistp521",		"1.3.132.0.35", "06052B81040023", 521},

If you are using the name field_length for something else that is quite confusing.

Can you try your code with one of the above curves?


On 4/13/2015 11:03 AM, viktorTarasov wrote:
> @dengert <https://github.com/dengert>
> Have you looked on the code?
>
> /field_length/ in OpenSC pkcs#15 data is not EC key size.
>
> |buflen = EC_POINT_point2oct(EC_KEY_get0_group( ...
> field_length = (buflen - 1) / 2 * 8;
> |
>
> For 521bits it gives buflen = 133, and field_length = 528 (66*8)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/433#issuecomment-92411526>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
@dengert 
1.
In my example above I was talking about results of tests with secp521r1.
It was also tested with the key presented in the head message. 

2.
> If you are using the name field_length for something else that is quite confusing.

The
```
 key->field_length = (ecpoint_len - 1)/2 * 8;
```
was introduced in
```
commit c34caeb6625fe80550b22f8e5740f9d8a6f198da
Author: dengert <dengert@c6295689-39f2-0310-b995-f0e70906c6a9>
Date:   2010-11-30 19:13:48 +0000

    Support for ECC keys (part 1) header files and
    support routines. Add definitions for EC keys,
    parameters and extensions to structures.
    Add the sc_card_find_ec_alg, sc_pkcs15_decode_pubkey_ec,
    sc_pkcs15_encode_pubkey_ec, sc_pkcs15emu_add_ec_prkey,
    sc_pkcs15emu_add_ec_pubkey routines.
    Only EC named curves are currently supported.
```

**Comment by dengert** [comment]
5 years ago. Then no cards were dealing with non multiple of 8 ec keys, or
had to deal with importing or exporting keys with leading zero bytes in some keys.

I will look at a fix.

On 4/14/2015 2:31 AM, viktorTarasov wrote:
> @dengert <https://github.com/dengert>
> 1.
> In my example above I was talking about results of tests with secp521r1.
> It was also tested with the key presented in the head message.
>
> 2.
>
>     If you are using the name field_length for something else that is quite confusing.
>
> The
>
> |  key->field_length = (ecpoint_len - 1)/2 * 8;
> |
>
> was introduced in
>
> |commit c34caeb6625fe80550b22f8e5740f9d8a6f198da
> Author: dengert <dengert@c6295689-39f2-0310-b995-f0e70906c6a9>
> Date:   2010-11-30 19:13:48 +0000
>
>      Support for ECC keys (part 1) header files and
>      support routines. Add definitions for EC keys,
>      parameters and extensions to structures.
>      Add the sc_card_find_ec_alg, sc_pkcs15_decode_pubkey_ec,
>      sc_pkcs15_encode_pubkey_ec, sc_pkcs15emu_add_ec_prkey,
>      sc_pkcs15emu_add_ec_pubkey routines.
>      Only EC named curves are currently supported.
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/433#issuecomment-92676107>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>
