### ISSUE TITLE
unblock pin with a pinpad: why opensc is asking for the puk twice ?

### ISSUE THREAD

**Issue by vletoux** [OpenSC/OpenSC#441]
While testing the pinpad functionnality, I discovered some lines of code I don't understand.

**1) Why testing for the PUK twice ?**
I personally tested it so yes, it is asked twice by the pinpad.

Number one is done here: (sc_pkcs15_verify_pin)
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-pin.c#L506-509
Number two is done here: (sc_pin_cmd)
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-pin.c#L572

I don't understand why sc_pkcs15_verify_pin is called here.
Shouldn't be a call to _validate_pin instead of sc_pkcs15_verify_pin ?

My implementation of pin_cmd is verifying the PUK. Maybe I totally misunderstood this function.

**2) puk length**
Why the length  of the new PIN (pin2) is limited by the PUK info (puk_info) ?
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-pin.c#L534-537

Shouldn't auth_info and puk_info be switched here ?
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-pin.c#L528-537

**Comment by vletoux** [comment]
**3) the pinpad messages are incorrects if the flag SC_PIN_CMD_IMPLICIT_CHANGE is set on a modify request**
The flag SC_PIN_CMD_IMPLICIT_CHANGE is set when the pinpad needs to ask only for the new PIN
The messages sent by the current code are "Enter PIN" "Enter new PIN"
instead of "Enter new PIN" "Confirm new PIN"
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1498-1500

The code should be fixed by adding a test on the flag SC_PIN_CMD_IMPLICIT_CHANGE and change the message id from 0x00 to 0x01 and 0x01 to 0x02

The proposed patch fixes the issue: https://gist.github.com/vletoux/f9f59f524c6f439cd71c

**Comment by viktorTarasov** [comment]
@vletoux 
1) yes, it's a bug --  PUK is verified twice.
2) yes, it has to be switched

**Comment by vletoux** [comment]
ok, I'll fix it in my working branch
( the patch for 3 was already added in my working branch)
