### ISSUE TITLE
windows setup improvement

### ISSUE THREAD

**Issue by vletoux** [OpenSC/OpenSC#447]
I'd like to work on the setup program.
I need your feedback about this proposition
(I can spend some time tomorrow about that)

**1) look & feel**
I'd like to change the default red background provided by wix to another one.
(like this one: https://raw.githubusercontent.com/vletoux/OpenSC/7a7f8fb27471719a32f0cdcf819170771589791b/win32/dlgbmp.bmp)
If you have some logo / graphic, I can improve the proposed design.

**2) registering minidriver**
I'd like to add the registration of the minidriver for all cards (except piv - I can find the ATR & mask for all other drivers)
Indeed the minidriver needs a proper inf file to be install, but the driver will be unsigned and hard to design for each card (extract the historical bytes).
There is a trick to use a minidriver (including the ctrl-alt-del changing pin screen) on Windows 7 without having a driver install. You set exactly the same registry than for a minidriver installation, but the CSP points to another one (like OpenSC CSP) and this new CSP has been registered with the same dll than the Base CSP. I'll add the Base KSP registration data which is missing in existing files.

**optionally**
If you like, I can donate the source code for the program we called "smart card manager" & used in several of our projects (see http://download.mysmartlogon.com/EIDVirtual/EIDVirtual%20-%20User%20Documentation.pdf page 11 to 13). The user will be able to manage its card using the minidriver interface and check quickly if everything is fine for Windows. It is indeed more user friendly than "certutil -scinfo".

I'm waiting for your feedback.

regards,
Vincent

**Comment by dengert** [comment]
On 4/23/2015 4:39 AM, vletoux wrote:
> I'd like to work on the setup program.
> I need your feedback about this proposition
> (I can spend some time tomorrow about that)
>
> ++1) look & feel++
> I'd like to change the default red background provided by wix to another one.
> (like this one: https://raw.githubusercontent.com/vletoux/OpenSC/7a7f8fb27471719a32f0cdcf819170771589791b/win32/dlgbmp.bmp)
> If you have some logo / graphic, I can improve the proposed design.

OK, red background bug me too.  Google for: red background color intimidating

>
> ++2) registering minidriver++
> I'd like to add the registration of the minidriver for all cards (except piv - I can find the ATR & mask for all other drivers)
> Indeed the minidriver needs a proper inf file to be install, but the driver will be unsigned and hard to design for each card (extract the historical bytes).
> There is a trick to use a minidriver (including the ctrl-alt-del changing pin screen) on Windows 7 without having a driver install. You set exactly the same registry than for a minidriver
> installation, but the CSP points to another one (like OpenSC CSP) and this new CSP has been registered with the same dll than the Base CSP. I'll add the Base KSP registration data which is missing in
> existing files.

This is a nice goal, but:

(1) Not all cards supported by OpenSC can be used from the minidriver.
See this note and thread on which cards can not come up with a GUID:

    http://permalink.gmane.org/gmane.comp.encryption.opensc.devel/15926

The problem needs to be addressed for these cards before adding any registry changes for these cards.

(2) The way each OpenSC driver tests a card to see if it can support it is a mess. Most use the ATR, some look for for the default applet.
This is quite different from what Windows does and trying to keep the two in sync will be a big job.
In my option, the code in OpenSC that looks for ATRs should be in one module, so the list of ATRs and ATR_MASKs could be processed
similar to Windows thus making it easier to keep the minidriver install in sync with what the OpenSC drivers can support.

(3)  Card vendors supply CSPs for their cards. Microsoft has the built in PIV driver (and Microsoft may support other drivers in the future).
Any OpenSC install needs to be flexible to avoid conflicts with existing CSPs, or allow the user/admin to choose.

>
> ++optionally++
> If you like, I can donate the source code for the program we called "smart card manager" & used in several of our projects (see
> http://download.mysmartlogon.com/EIDVirtual/EIDVirtual%20-%20User%20Documentation.pdf page 11 to 13). The user will be able to manage its card using the minidriver interface and check quickly if
> everything is fine for Windows. It is indeed more user friendly than "certutil -scinfo".

Sounds good.

>
> I'm waiting for your feedback.
>
> regards,
> Vincent
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/447>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
What I can propose is that:
- a new branch is created for this work (not by me ....)
- I add a minidriver registration skeleton which can be copy/pasted (I can add support for the OpenPGP card, because I made the "other" minidriver). Only card maintainers will add ATR/ATR Mask to the minidriver setup. That should solve the conflict with existing minidrivers.
- I'll add our code, adapted to the OpenSC built. Which directory should be created ?   src\wincardmanager ? Or something else ?
- are there any graphical material ? I took some time searching for the Opensc logo but the old logo seems to be decommissioned..

**Comment by dengert** [comment]
Can someone else respond?

On 4/23/2015 7:48 AM, vletoux wrote:
> What I can propose is that:
>
>   * a new branch is created for this work (not by me ....)
>   * I add a minidriver registration skeleton which can be copy/pasted (I can add support for the OpenPGP card, because I made the "other" minidriver). Only card maintainers will add ATR/ATR Mask to
>     the minidriver setup. That should solve the conflict with existing minidrivers.
>   * I'll add our code, adapted to the OpenSC built. Which directory should be created ? src\wincardmanager ? Or something else ?
>   * are there any graphical material ? I took some time searching for the Opensc logo but the old logo seems to be decommissioned..
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/447#issuecomment-95574768>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
1. looks good, I'd use it 

2. There are already some registry entries for the minidriver https://github.com/OpenSC/OpenSC/tree/master/src/minidriver. These cards are expected to work with the minidriver and should automatically be registered. Developers should add more cards when tested.

3. From the documentation I don't really understand the purpose of the "smart card manager". From your description I figure that its used for activating/deactivating minidriver integration for a certain card if it is not activated by default. That indeed would be good to have with OpenSC.

**Comment by frankmorgner** [comment]
1. In https://github.com/OpenSC/OpenSC/tree/master/MacOSX/resources you can find the templates that are used for the Mac OS X installer. That should be reused if possible.

**Comment by frankmorgner** [comment]
Here is how the Mac OS X installer looks like:
https://www.opensc-project.org/opensc/attachment/wiki/MacInstaller/OpenSC_Installer_screenshot.png

**Comment by vletoux** [comment]
- 1, I extracted the logo from the macosx setup. I do not think the image can be used as is because on macosx it is a background image with a textbox above while in windows the text is written directly on it. **The text will be hard to read if the background is reused as is**
- 2 I can integrate the existing registry entries in the setup. The trick is to replace ["Crypto Provider"="Microsoft Base Smart Card Crypto Provider"] to avoid Windows to ask to install a driver each time the card is inserted
- 3, the tool I proposed is used to:
 - show the certificate on the card (double click)
 - generate new self signed certificates
 - import p12/pfx file
 - request a smart card logon certificate from a domain

There is nothing new in the tool that cannot be accomplished somewhere (certificate.msc or certutil -scinfo) but I think this is more user friendly for new comers on Windows. This is proposition - you are free to decline it ;-)

If you need a tool to register a card from the minidriver, we have one in stock:
![conf1](https://cloud.githubusercontent.com/assets/10632326/7298641/2cfc256a-e9d1-11e4-9b8f-01f6908b8538.png)
![conf2](https://cloud.githubusercontent.com/assets/10632326/7298644/32118f68-e9d1-11e4-83c3-ffdf465e30c1.png)

Just asks ;-)

**Comment by vletoux** [comment]
I've pushed my commit into the minidriver branch.
Build is failing because it cannot find the .bmp. Should the pull request be accepted to see the new files ?

In short: **please help me** to create the new dll on the build machine from the new file : win32\opensc-setup-custom-action.c
I'm not a build machine expert and I do not know how to fix these compilation problems ;-(

**Comment by dengert** [comment]
In a clone of your repository, running  grep across multiple directories
shows that license.rtf and bannrbmp.bmp are not being handled the same.

$ G license.rtf

     <WixVariable Id="WixUILicenseRtf" Value="license.rtf"/>
./win32/OpenSC.wxs.in
		$(srcdir)/OpenSC.iss $(srcdir)/OpenSC.wxs $(srcdir)/OpenSC.ico $(srcdir)/license.rtf
dist_noinst_HEADERS = versioninfo.rc winconfig.h OpenSC.iss OpenSC.wxs license.rtf OpenSC.ico
./win32/Makefile.am


$ G bannrbmp.bmp

     <WixVariable Id="WixUIBannerBmp" Value="$(var.SOURCE_DIR)\win32\bannrbmp.bmp"/>
./win32/OpenSC.wxs.in

$ G dlgbmp.bmp

     <WixVariable Id="WixUIDialogBmp" Value="$(var.SOURCE_DIR)\win32\dlgbmp.bmp"/>
./win32/OpenSC.wxs.in


Looks like the Makefile.am copies a number of files including license.rtf but not the .bmp files.
The OpenSC.wxs.in is trying to point back to the source for the .bmp files, but not for license.rtf
license.rtf


Did you add the "$(var.SOURCE_DIR)\win32\"?



On 4/24/2015 9:01 AM, vletoux wrote:
> I've pushed my commit into the minidriver branch.
> Build is failing because it cannot find the .bmp. Should the pull request be accepted to see the new files ?
>
> In short: *please help me* to create the new dll on the build machine from the new file : win32\opensc-setup-custom-action.c
> I'm not a build machine expert and I do not know how to fix these compilation problems ;-(
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/447#issuecomment-95943122>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
thanks for pointing my mistake.
Last time I edited makefiles was years ago ...

**Comment by vletoux** [comment]
@dengert if you can show me what's I'm doing wrong, especially about the .exports file:
`make[1]: Entering directory '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'
 make[1]: *** No rule to make target 'customactions.exports', needed by 'distdir'.  Stop.
 make[1]: Leaving directory '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'`

I'm trying to built a dll from the source here win32\customactions.c (and .exports).
I did a copy/paste from the minidriver makefiles but there is some magic I do not understand

Build: https://opensc.fr/jenkins/job/OpenSC-pr-ubuntu/473/console
Pull request: https://github.com/OpenSC/OpenSC/pull/443

Thanks in advance

**Comment by dengert** [comment]
Your rename is missing an "s"

rename win32/{opensc-setup-custom-action.exports => customactions.export}



On 4/24/2015 3:03 PM, vletoux wrote:
> @dengert <https://github.com/dengert> if you can show me what's I'm doing wrong, especially about the .exports file:
> |make[1]: Entering directory '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'
> make[1]: *** No rule to make target 'customactions.exports', needed by 'distdir'. Stop.
> make[1]: Leaving directory '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'|
>
> I'm trying to built a dll from the source here win32\customactions.c (and .exports).
> I did a copy/paste from the minidriver makefiles but there is some magic I do not understand
>
> Build: https://opensc.fr/jenkins/job/OpenSC-pr-ubuntu/473/console
> Pull request: #443 <https://github.com/OpenSC/OpenSC/pull/443>
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/447#issuecomment-96047959>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
thanks, i didn't see it

2015-04-24 23:20 GMT+02:00 Doug Engert <notifications@github.com>:

> Your rename is missing an "s"
>
> rename win32/{opensc-setup-custom-action.exports => customactions.export}
>
>
>
> On 4/24/2015 3:03 PM, vletoux wrote:
> > @dengert <https://github.com/dengert> if you can show me what's I'm
> doing wrong, especially about the .exports file:
> > |make[1]: Entering directory
> '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'
> > make[1]: *** No rule to make target 'customactions.exports', needed by
> 'distdir'. Stop.
> > make[1]: Leaving directory
> '/home/jenkins/jenkins_home/ws/jenkins-OpenSC-pr-ubuntu-473/win32'|
> >
> > I'm trying to built a dll from the source here win32\customactions.c
> (and .exports).
> > I did a copy/paste from the minidriver makefiles but there is some magic
> I do not understand
> >
> > Build: https://opensc.fr/jenkins/job/OpenSC-pr-ubuntu/473/console
> > Pull request: #443 <https://github.com/OpenSC/OpenSC/pull/443>
> >
> > Thanks in advance
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/OpenSC/OpenSC/issues/447#issuecomment-96047959>.
>
> >
>
> --
>
> Douglas E. Engert <DEEngert@gmail.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/issues/447#issuecomment-96068566>.
>



-- 
---
Vincent

**Comment by vletoux** [comment]
it was painful, but the minidriver registration is now working with the setup.

**Comment by vletoux** [comment]
screenflow:
![screen1](https://cloud.githubusercontent.com/assets/10632326/7334965/bc298e16-eba3-11e4-8555-ab70d8f167ed.png)
![screen2](https://cloud.githubusercontent.com/assets/10632326/7334968/bf7ef0b0-eba3-11e4-934c-e00e37cfae23.png)
![screen3](https://cloud.githubusercontent.com/assets/10632326/7334969/c160914a-eba3-11e4-81d6-fba24bbfe859.png)
![screen4](https://cloud.githubusercontent.com/assets/10632326/7334972/c3a85fdc-eba3-11e4-8357-6e5f3efa2823.png)
![screen5](https://cloud.githubusercontent.com/assets/10632326/7334973/c52edb92-eba3-11e4-863d-13212ad52def.png)
![screen6](https://cloud.githubusercontent.com/assets/10632326/7334974/c6d286f6-eba3-11e4-876b-c6b3ae418ed0.png)

**Comment by frankmorgner** [comment]
I think it's not really clear what the difference between "typical" and "complete" is, but I it definitely looks better. Thanks for the work!

**Comment by vletoux** [comment]
If you want to replace the "Typical / custom" dialog by a feature selection, just replace WixUI_Mondo by WixUI_FeatureTree in the code.

Moreover if you request that the setup register the pkcs11 library in Firefox / Chrome, it can be done inside a custom action.

Something which may be improved in the future:
packaging both 32 & 64 bits version for the x64 installer and restrict the x86 installer to 32 bits systems. This will solve the problem "needs 32 bits for internet explorer and 64 bits for smart card logon" on x64 plateforms.
I can solve it on the setup side, but not on the build side.
