### ISSUE TITLE
pkcs11-tool test failing because of uninitialized variable

### ISSUE THREAD

**Issue by llagosan** [OpenSC/OpenSC#469]
In encrypt_decrypt function, the CK_MECHANISM mech variable is not zeroized properly, only the type is set. Depending on the pkcs11 implementation, the call to C_DecryptInit with a random parameter length may fail.

**Comment by frankmorgner** [comment]
Sounds like it could be fixed easily. Could you provide a patch in a pull request?

**Comment by llagosan** [comment]
Will check tomorrow with my management, I'll push for it.
Will keep you posted.

-
Laurent

**Comment by frankmorgner** [comment]
@llagosan please re-open if you have any updates
