### ISSUE TITLE
Memory leaks in DNIe module

### ISSUE THREAD

**Issue by germanblanco** [OpenSC/OpenSC#472]
Using 0.15.0, I get the following report from valgrind:
==2524== LEAK SUMMARY:
==2524==    definitely lost: 12,982 bytes in 35 blocks
==2524==    indirectly lost: 11,085 bytes in 272 blocks
==2524==      possibly lost: 0 bytes in 0 blocks
==2524==    still reachable: 32,532 bytes in 923 blocks
==2524==         suppressed: 0 bytes in 0 blocks
==2524== 
==2524== For counts of detected and suppressed errors, rerun with: -v
==2524== ERROR SUMMARY: 38 errors from 37 contexts (suppressed: 0 from 0)
This is the command line:
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -l -O -pin APIN
I am already working on it.

**Comment by frankmorgner** [comment]
closed with #474
