### ISSUE TITLE
dnie login triggers a lock in the card

### ISSUE THREAD

**Issue by rickyepoderi** [OpenSC/OpenSC#475]
Hi,

Checking the dnie I have discovered that the any process that uses the pkcs11 library locks the card and no other process can use it. The issue happens when the you perform the login into the library. 

After some testing and recompiling it seems that the problem is the following:

1.- When the library performs a C_Login it calls to cwa_create_secure_channel (cwa14890.c).
2.- This method finally calls to sc_reset(card,0) 
3.- This method finally calls to pcsc_reset (reader-pcsc.c) which performs another lock.
4.- This second lock creates 2 locks in the shared pcsc.
5.- Finally only one lock is deleted (so another one remains).

This way the library is locked by this application and no other one can operate over the pkcs11 library until this application is disconnected.

I don't know why pcsc_reset(card,0) supposes that the lock in pcsc is removed and the reader should be locked again. It seems that, at least with do_cold_reset=0, pcsc does not remove the lock and it should not be added again. 

My pcsc-lite is 1.8.13 just in case this is a change in behavior of a recent version.

**Comment by rickyepoderi** [comment]
The second and problematic lock is the one in reader-pcsc.c line 588:

 576 static int pcsc_reset(sc_reader_t *reader, int do_cold_reset)
 577 {
 578         struct pcsc_private_data *priv = GET_PRIV_DATA(reader);
 579         int r;
 580         int old_locked = priv->locked;
 581 
 582         r = pcsc_reconnect(reader, do_cold_reset ? SCARD_UNPOWER_CARD : SCARD_RESET_CARD);
 583         if(r != SC_SUCCESS)
 584                 return r;
 585 
 586         /* pcsc_reconnect unlocks card... try to lock it again if it was locked */
 587         if(old_locked)
 588                 r = pcsc_lock(reader);
 589 
 590         return r;
 591 }
 592

**Comment by dengert** [comment]
On 5/27/2015 4:22 PM, rickyepoderi wrote:
> Hi,
>
> Checking the dnie I have discovered that the any process that uses the pkcs11 library locks the card and no other process can use it. The issue happens when the you perform the login into the library.
>

Is that a feature or a bug? How should the secure_channel work if another process or user wants access to the card?


> After some testing and recompiling it seems that the problem is the following:
>
> 1.- When the library performs a C_Login it calls to cwa_create_secure_channel (cwa14890.c).
> 2.- This method finally calls to sc_reset(card,0)
> 3.- This method finally calls to pcsc_reset (reader-pcsc.c) which performs another lock.
> 4.- This second lock creates 2 locks in the shared pcsc.
> 5.- Finally only one lock is deleted (so another one remains).
>
> This way the library is locked by this application and no other one can operate over the pkcs11 library until this application is disconnected.
>
> I don't know why pcsc_reset(card,0) supposes that the lock in pcsc is removed and the reader should be locked again. It seems that, at least with do_cold_reset=0, pcsc does not remove the lock and it
> should not be added again.
>
> My pcsc-lite is 1.8.13 just in case this is a change in behavior of a recent version.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rickyepoderi** [comment]
I don't know Doug.

But each time you log in one more lock is lock (1 login -> 1 lost lock, logout and login again -> 2 lost locks and so on).

I realized about this issue because of the testing page of the dnie:

https://av-dnie.cert.fnmt.es/compruebacert/compruebacert

You need user certificate to enter to this https (one lock is established bacause you have to login). Inside that page there is a java applet to test signing, when it starts it does not work because the card is locked. Indeed you cannot perform any command to the card cos no pcsc command (from another process) works, not even a dnie-tool.

**Comment by rickyepoderi** [comment]
Only one more comment, the issue is triggered because the pcsc_reset tries to lock the card as before (the code is, more or less, if it was locked then pcsc_lock again to re-establish the previous situation). My impression is that pcsc does not lose the lock in a soft reset (I did not test if  do_cold_reset is 1), so re-adding the lock just adds a second lock that blocks the card.

I mean that it does not seem to be a wanted behavior.

**Comment by dengert** [comment]
On 5/28/2015 3:26 AM, rickyepoderi wrote:
> Only one more comment, the issue is triggered because the pcsc_reset tries to lock the card as before (the code is, more or less, if it was locked then pcsc_lock again to re-establish the previous
> situation). My impression is that pcsc does not lose the lock in a soft reset (I did not test if do_cold_reset is 1), so re-adding the lock just adds a second lock that blocks the card.
>
> I mean that it does not seem to be a wanted behavior.



./reader-pcsc.c starting at 639 defines connect_exclusive and sets from the opensc.conf file.
Does this help explain what is going on?


>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475#issuecomment-106229617>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rickyepoderi** [comment]
No, my configuration is the default one, so it is in shared mode:

                # Connect to reader in exclusive mode?
                # Default: false
                # connect_exclusive = true;

If you see the code at pcsc_reset function contains the following comment:

        /* pcsc_reconnect unlocks card... try to lock it again if it was locked */
        if(old_locked)
                r = pcsc_lock(reader);

The problem is that internal counter when shared in pcsc-lite is not removed, so this second lock increments (rContext->LockCount) to 2. And when the login is finished only one is decremented at SCardEndTransaction. So the card is still locked although it is in shared configuration.

Are you sure you have to call pcsc_lock again in pcsc_reset? Maybe people in pcsc-lite (Ludovic) can confirm if this is necessary or not, or in what circumstances... If you want I can post a question in the pcsc-lite list.

Thanks.

**Comment by dengert** [comment]
On 5/28/2015 12:16 PM, rickyepoderi wrote:
> No, my configuration is the default one, so it is in shared mode:
>
> |             # Connect to reader in exclusive mode?
>              # Default: false
>              # connect_exclusive = true;
> |
>
> If you see the code at pcsc_reset function contains the following comment:
>
> |     /* pcsc_reconnect unlocks card... try to lock it again if it was locked */
>      if(old_locked)
>              r = pcsc_lock(reader);
> |
>
> The problem is that internal counter when shared in pcsc-lite is not removed, so this second lock increments (rContext->LockCount) to 2. And when the login is finished only one is decremented at
> SCardEndTransaction. So the card is still locked although it is in shared configuration.


Sounds like it could be bug.

As best I can tell, sc_reset is only used by two cards, card-dnie.c via cwa14890.c and cwa_create_secure_channel
and card-mcrd.c (I don't have either.)

You may also want to read:
  http://www.pcscworkgroup.com/specifications/files/pcsc7_v2.01.01.pdf
  3.3 Device Sharing and Control


or any of the other docs:
  http://www.pcscworkgroup.com/specifications/specdownload.php

to see if there is anything in the specifications that might says what to do.



>
> Are you sure you have to call pcsc_lock again in pcsc_reset? Maybe people in pcsc-lite (Ludovic) can confirm if this is necessary or not, or in what circumstances... If you want I can post a question
> in the pcsc-lite list.

Yes, post to pcsc-lite.


>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475#issuecomment-106499918>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rickyepoderi** [comment]
Finally I sent a question to the pcsc-lite mailing list:

http://lists.alioth.debian.org/pipermail/pcsclite-muscle/Week-of-Mon-20150601/000385.html

And, for the moment, it seems that the problem is in pcsc-lite implementation.

In my tests in Windows the SCardReconnect function re-initializes the connection (cleaning all the previous locks). So the opensc code seems to be OK, the lock should be re-established after a reset if you want to maintain the card in exclusive mode. But pcsc-lite implementation does nothing with locks in the same function, triggering the issue explained here.

Let's see what finally happens.

**Comment by rickyepoderi** [comment]
After a long talk with Ludovic (the main pcsc-lite developer) there is a proposal about this issue. You can follow the conversation in  the thread list link. The following link is the message with the proposal:

http://lists.alioth.debian.org/pipermail/pcsclite-muscle/Week-of-Mon-20150601/000393.html

First I want to summarize the issue just to clarify the situation:

* The SCardReconnect PCSC function in Windows implementation releases the locks. My personal opinion is that this function is similar to a SCardDisconnect + SCardConnect. Besides there is a direct description of this behavior in the windows API (but in the SCardEndTransaction):

https://msdn.microsoft.com/es-es/library/windows/desktop/aa379477%28v=vs.85%29.aspx

* I suppose that opensc pcsc_reset function was tested with Windows implementation and, therefore, the lock was re-established after the reconnect (it should be this way in Windows).

* The pcsc-lite implementation does not release the locks (locks are not modified in the SCardReconnect). Therefore, if opensc uses pcsc-lite (Linux for example), each time the pcsc_reset is called a lock is added and not released. As the dnie driver calls this method in C_Login, once you log in the card it is locked until the process finishes (SCardDisconnect or SCardReleaseContext is called).

* As Doug commented before only two cards uses this method in opensc, so the problem remained hidden for a long time.

The proposal to fix the problem is the following:

* pcsc-lite is not going to change the SCardReconnect. It is a change in how the function manages the locks and changing the behavior can generate problems with other projects. Besides, if pcsc-lite modified the SCardReconnect function opensc should still manage two situations (if version is greater or equal to the fixed one => add the lock; if version less than the fixed one => do not add the lock). The pcsc-lite is going to just document the different behavior with windows.

* So opensc has to use some "ifdef _WIN32" to add the lock again in case of windows and do nothing in case of pcsc-lite (all the rest). 

I have done a little patch (I have just seen that GitHub is very clever and it is referenced just above this comment) with this idea. At the moment I tested it with pcsc-lite and works (the locks are released ok now). I want to test it in windows too, but this will be more complicated to me (give me some days). My intention is to provide a pull request after the solution works in both environments (linux and windows).

What do you think? Do you agree with our decisions?

**Comment by dengert** [comment]
On 6/3/2015 12:12 PM, rickyepoderi wrote:
> After a long talk with Ludovic (the main pcsc-lite developer) there is a proposal about this issue. You can follow the conversation in the thread list link. The following link is the message with the
> proposal:
>
> http://lists.alioth.debian.org/pipermail/pcsclite-muscle/Week-of-Mon-20150601/000393.html
>
> First I want to summarize the issue just to clarify the situation:
>
>   * The SCardReconnect PCSC function in Windows implementation releases the locks. My personal opinion is that this function is similar to a SCardDisconnect + SCardConnect. Besides there is a direct
>     description of this behavior in the windows API (but in the SCardEndTransaction):
>
> https://msdn.microsoft.com/es-es/library/windows/desktop/aa379477%28v=vs.85%29.aspx

The above implies that SCardEndTransaction with dwDisposition = SCARD_RESET_CARD
could return SCARD_W_RESET_CARD indicating the card may have been reset, but is still locked.
Or it could return SCARD_S_SUCCESS indicating the card was reset and is is not locked.

  http://pcsclite.alioth.debian.org/pcsc-lite/node16.html

SCardEndTransaction says: The disposition action is not currently used in this release.

Should the OpenSC not use pcsc_reset at all?
When used with the cardmod driver, the function is NULL.

It looks like Windows has two types of locks one for transactions: SCardBeginTransaction and SCardEndTransaction (exclusive)
and one for SCardConnectand  SCardDisconnect (shared or exclusive). Both SCardDisconnect and SCardEndTransaction can accept SCARD_RESET_CARD



>
>   *
>
>     I suppose that opensc pcsc_reset function was tested with Windows implementation and, therefore, the lock was re-established after the reconnect (it should be this way in Windows).
>
>   *
>
>     The pcsc-lite implementation does not release the locks (locks are not modified in the SCardReconnect). Therefore, if opensc uses pcsc-lite (Linux for example), each time the pcsc_reset is called
>     a lock is added and not released. As the dnie driver calls this method in C_Login, once you log in the card it is locked until the process finishes (SCardDisconnect or SCardReleaseContext is called).
>
>   *
>
>     As Doug commented before only two cards uses this method in opensc, so the problem remained hidden for a long time.
>
> The proposal to fix the problem is the following:
>
>   *
>
>     pcsc-lite is not going to change the SCardReconnect. It is a change in how the function manages the locks and changing the behavior can generate problems with other projects. Besides, if pcsc-lite
>     modified the SCardReconnect function opensc should still manage two situations (if version is greater or equal to the fixed one => add the lock; if version less than the fixed one => do not add
>     the lock). The pcsc-lite is going to just document the different behavior with windows.

I agree. It looks like reader-pcsc.c is trying to do a reset in reconnect, rather then on SCardDisconnect or SCardEndTransaction.
This sounds like a logic error in how OpenSC implemented sc_reset.
Rather then trying to do a sc_reconnect, should it be doing a SCardBeginTransaction, SCardEndTransaction(SCARD_RESET_CARD)


>
>   *
>
>     So opensc has to use some "ifdef _WIN32" to add the lock again in case of windows and do nothing in case of pcsc-lite (all the rest).
>
> I have done a little patch (I have just seen that GitHub is very clever and it is referenced just above this comment) with this idea. At the moment I tested it with pcsc-lite and works (the locks are
> released ok now). I want to test it in windows too, but this will be more complicated to me (give me some days). My intention is to provide a pull request after the solution works in both environments
> (linux and windows).
>
> What do you think? Do you agree with our decisions?

Do the standards say anything about how this should be done?

It sounds like there is still an issue with Windows, pcsc-lite and maybe Mac. Which is doing it correctly?

How will this work with rdesktop on Linux, Remote Desktop on Windows, and whatever is on Mac? Where is the lock held?

Is there anyway to query what the lock count is?

Does the DNIe driver really need to call pcsc_reset?



>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475#issuecomment-108527588>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by LudovicRousseau** [comment]
@dengert the Doxygen documentation was wrong and is fixed in https://github.com/LudovicRousseau/PCSC/commit/040a4fa25e2896e80d341c5e1a822d1d04c57e55
I will update the online version soon. Thanks for the notice.

- On pcsc-lite the lock is managed by pcscd.
- You can't query the lock count.
- ``SCardDisconnect()`` will remove any lock.

To reset a card and continue using it the simplest may be to use a pair of ``SCardBeginTransaction()``/``SCardEndTransaction(SCARD_RESET_CARD)``. I guess the same code will work on Windows and Unix.

**Comment by dengert** [comment]
@rickyepoderi
Can you try something like this?
It has not been tested, or even compiled.


In effect pcsc_lock does a SCardBeginTransaction
and ups the internal lock count inside OpenSC.

pcsc_unlock does a SCardEndTransaction(priv->pcsc_card, priv->gpriv->transaction_end_action);
and decrements the internal lock count in OpenSC.

pcscd is doing its own lock counts


diff --git a/src/libopensc/reader-pcsc.c b/src/libopensc/reader-pcsc.c
index 7382452..ac058a2 100644
--- a/src/libopensc/reader-pcsc.c
+++ b/src/libopensc/reader-pcsc.c
@@ -577,15 +577,15 @@ static int pcsc_reset(sc_reader_t *reader, int do_cold_reset)
  {
  	struct pcsc_private_data *priv = GET_PRIV_DATA(reader);
  	int r;
-	int old_locked = priv->locked;
+	int old_transaction_end_action = priv->gpriv->transaction_end_action;;

-	r = pcsc_reconnect(reader, do_cold_reset ? SCARD_UNPOWER_CARD : SCARD_RESET_CARD);
+	r = pcsc_lock(reader);
  	if(r != SC_SUCCESS)
  		return r;
-
-	/* pcsc_reconnect unlocks card... try to lock it again if it was locked */
-	if(old_locked)
-		r = pcsc_lock(reader);
+	
+	priv->gpriv->transaction_end_action = SCARD_RESET_CARD;
+	r = pcsc_unlock(reader);
+	priv->gpriv->transaction_end_action = old_transaction_end_action;

  	return r;
  }




On 6/4/2015 4:31 AM, Ludovic Rousseau wrote:
> @dengert <https://github.com/dengert> the Doxygen documentation was wrong and is fixed in LudovicRousseau/PCSC@040a4fa
> <https://github.com/LudovicRousseau/PCSC/commit/040a4fa25e2896e80d341c5e1a822d1d04c57e55>
> I will update the online version soon. Thanks for the notice.
>
>   * On pcsc-lite the lock is managed by pcscd.
>   * You can't query the lock count.
>   * |SCardDisconnect()| will remove any lock.
>
> To reset a card and continue using it the simplest may be to use a pair of |SCardBeginTransaction()|/|SCardEndTransaction(SCARD_RESET_CARD)|. I guess the same code will work on Windows and Unix.
>



> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475#issuecomment-108807028>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>


diff --git a/src/libopensc/reader-pcsc.c b/src/libopensc/reader-pcsc.c
index 7382452..ac058a2 100644
--- a/src/libopensc/reader-pcsc.c
+++ b/src/libopensc/reader-pcsc.c
@@ -577,15 +577,15 @@ static int pcsc_reset(sc_reader_t *reader, int do_cold_reset)
 {
 	struct pcsc_private_data *priv = GET_PRIV_DATA(reader);
 	int r;
-	int old_locked = priv->locked;
+	int old_transaction_end_action = priv->gpriv->transaction_end_action;;
 
-	r = pcsc_reconnect(reader, do_cold_reset ? SCARD_UNPOWER_CARD : SCARD_RESET_CARD);
+	r = pcsc_lock(reader);
 	if(r != SC_SUCCESS)
 		return r;
-
-	/* pcsc_reconnect unlocks card... try to lock it again if it was locked */
-	if(old_locked)
-		r = pcsc_lock(reader);
+	
+	priv->gpriv->transaction_end_action = SCARD_RESET_CARD;
+	r = pcsc_unlock(reader);
+	priv->gpriv->transaction_end_action = old_transaction_end_action;
 
 	return r;
 }

**Comment by rickyepoderi** [comment]
Hi Doug,

I have tested your change and it does not work with the dnie in Linux. 

static int pcsc_reset(sc_reader_t *reader, int do_cold_reset)
{
        struct pcsc_private_data *priv = GET_PRIV_DATA(reader);
        int r;
        int old_transaction_end_action = priv->gpriv->transaction_end_action;

        r = pcsc_lock(reader);
        if(r != SC_SUCCESS)
                return r;

        priv->gpriv->transaction_end_action = SCARD_RESET_CARD;
        r = pcsc_unlock(reader);
        priv->gpriv->transaction_end_action = old_transaction_end_action;

        return r;
}

When you try to log there is an error and it always results in a login failed message (using firefox). I have not checked the problem deeply but for example the variable "priv->locked" is set to 0 before the final release is executed (although it seems that this var is not used for anything else).

I don't know, I propose to follow a minimal change solution for the moment. Yesterday I was compiling opensc in windows (a fucking hell I have to say) and I finally have a working environment to test also in windows. I think that this weekend I will have the time to test my "ifdef _WIN32" solution in deep.

Please if you don't like this solution just advise me because I don't want to waste my time testing in something that will not be considered.

Thanks!

**Comment by dengert** [comment]
I don't hve a way to test any of this, and don't have any DNIe documents related to why a card reset is needed
and what it does to the card, or why it is be required.

If you have any information on that, that would help.

That said it looks like OpenSC with its lock/unlock is trying to mirror what pcsc is doing.
The OpenSC code was trying to use disconnect to reset the card, where as pcsc has two ways
to specify a card reset, one on disconnect and one from SCardEndTransaction.

pcsc is also trying to control access to the card from multiple processes, where a process
during connect can ask for shared or exclusive access. See:

http://www.pcscworkgroup.com/specifications/specdownload.php
http://www.pcscworkgroup.com/specifications/files/pcsc3_v2.01.09.pdf
http://www.pcscworkgroup.com/specifications/files/pcsc5_v2.01.01.pdf

says:
RESPONSECODE Disconnect:
"Any application may reset the card, even in shared access mode."

RESPONSECODE EndTransaction:
"Any application may reset the card, even in shared access mode."

I believe the OpenSC process is really trying to use card reset, but keep it connected.

Someone added the card reset code for the DNIe card, as it must serve some purpose, and your change
using the #ifdef may open up some security issues if the card reset is not done.
Yet only two cards appear to call sc_reset, so why don't other cards need this?

The use of the card reset may work but there may be a better way to do what ever is needed.
The DNIe documentation might show this.

What would be helpful is a OpenSC debug trace showing the lock state and a pcscd trace of what is sent to the card.

My approach may be wrong, anyone else have any ideas?


On 6/5/2015 4:40 AM, rickyepoderi wrote:
> Hi Doug,
>
> I have tested your change and it does not work with the dnie in Linux.
>
> static int pcsc_reset(sc_reader_t *reader, int do_cold_reset)
> {
> struct pcsc_private_data *priv = GET_PRIV_DATA(reader);
> int r;
> int old_transaction_end_action = priv->gpriv->transaction_end_action;
>
> |     r = pcsc_lock(reader);
>      if(r != SC_SUCCESS)
>              return r;
>
>      priv->gpriv->transaction_end_action = SCARD_RESET_CARD;
>      r = pcsc_unlock(reader);
>      priv->gpriv->transaction_end_action = old_transaction_end_action;
>
>      return r;
> |
>
> }
>
> When you try to log there is an error and it always results in a login failed message (using firefox). I have not checked the problem deeply but for example the variable "priv->locked" is set to 0
> before the final release is executed (although it seems that this var is not used for anything else).
>
> I don't know, I propose to follow a minimal change solution for the moment. Yesterday I was compiling opensc in windows (a fucking hell I have to say) and I finally have a working environment to test
> also in windows. I think that this weekend I will have the time to test my "ifdef _WIN32" solution in deep.
>
> Please if you don't like this solution just advise me because I don't want to waste my time testing in something that will not be considered.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/475#issuecomment-109219904>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by rickyepoderi** [comment]
Doug, my change is so little that I'm not changing anything:

* If it is windows exactly the same code as before is executed.
* If it is pcsc-lite the extra lock is avoided (Ludovic confirmed that pcsc-lite does not release locks after a reconnect, so the add is not needed and the current implementation is buggy) .

Your patch is trying to change how the reset is performed in opensc. It's not a bad idea but (at least for me) is much more intrusive than mine. That's why I prefer my patch.

DNIe uses cwa 14890:

ftp://ftp.cenorm.be/PUBLIC/CWAs/e-Europe/eSign/cwa14890-01-2004-Mar.pdf

I have downloaded the standard but I need time to understand what the hell is going on there (it is not an easy reading, I tried to read it quickly and I have understood nothing). I think the reset is needed to start a proper trusted channel.

Thanks again!

**Comment by rickyepoderi** [comment]
Hi Doug,

As this issue seems not to move forward I am going to close this issue. I going to open another issue with another test case that can be tested with any card (not DNIe). I hope the new issue will be more easy to test and understand.

Thanks!
