### ISSUE TITLE
C_Initialize called twice

### ISSUE THREAD

**Issue by meuter** [OpenSC/OpenSC#477]
Hi,

I'm using OpenSC as a glue between a specific pkcs11 library and openssl. I use pkcs11-tool to generate some RSA key, and openssl req to generate a self signed certificate. In a first attempt I passed the proper command line parameter to openssl to make it use engine_pkcs11 with my library and it all worked like a charm. 

I then tried to modify /etc/ssl/openssl.cnf to specify all necessary info for openssl to find the pkcs11 engine without having to pass it via CLI all the time. As soon as I did that, pkcs11-tool would not generate RSA key anymore and returned CKR_CRYPTOKI_ALREADY_INITIALIZED.

I investigated a bit from the sources (https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c), with the help of my trusty old gdb and I think I have found the cause of the problem. At some point, pkcs11-tool performs a call to OPENSSL_config(NULL). This function call seems to initialize all engine specified in openssl.cnf which causes a first call to C_Initialize. (at least that's what the gdb stack trace seems to indicate). The tool then proceeds with the requested operation (RSA keypair generation in my case) which in turn causes a second call to C_Initialize. I suspect that this is the cause of the issue.

Using "OPENSSL_no_config()" instead of "OPENSSL_config(NULL)" would probably fix this but before doing a pull request, I would like to have your input on the matter :-)

Anyway, thanks for developing and maintaining OpenSC! 

Kind regards

-Cédric

**Comment by dengert** [comment]
On 6/4/2015 9:15 AM, Cédric Meuter wrote:
> Hi,
>
> I'm using OpenSC as a glue between a specific pkcs11 library and openssl. I use pkcs11-tool to generate some RSA key, and openssl req to generate a self signed certificate. In a first attempt I passed
> the proper command line parameter to openssl to make it use engine_pkcs11 with my library and it all worked like a charm.

What did you add?
But this is what I can use. (OpenSSL-1.0.2a, and OpenSC-0.15.0)

/tmp/genreq.2338.openssl.conf has added on the end:

[ openssl_def ]
engines = engine_scction

[ engine_scction ]

pkcs11 = pkcs11_section

[ pkcs11_section ]

engine_id = pkcs11
dynamic_path = /opt/smartcard/lib/engines/engine_pkcs11.so
MODULE_PATH = /opt/smartcard/lib/opensc-pkcs11.so
init = 0
VERBOSE = EMPTY

-------------------
Then to do a request:
OPENSSL_CONF=/tmp/genreq.2338.openssl.conf
export OPENSSL_CONF

openssl << EOT
req $SSLEAY_CONFIG -engine pkcs11 -keyform engine -sha256 -new -key slot_1-id_$ID -out cards/$1.myreq.$KEYID.pem  -text
EOT

/opt/smartcard/bin/pkcs11-tool --slot 1 --module /opt/smartcard/lib/opensc-pkcs11.so -O

Note the init = 0 and the OPENSSL_CONF env.

does not have the problem.

>
> I then tried to modify /etc/ssl/openssl.cnf to specify all necessary info for openssl to find the pkcs11 engine without having to pass it via CLI all the time. As soon as I did that, pkcs11-tool would
> not generate RSA key anymore and returned CKR_CRYPTOKI_ALREADY_INITIALIZED.
>
> I investigated a bit from the sources (https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c), with the help of my trusty old gdb and I think I have found the cause of the problem. At
> some point, pkcs11-tool performs a call to OPENSSL_config(NULL). This function call seems to initialize all engine specified in openssl.cnf which causes a first call to C_Initialize. (at least that's
> what the gdb stack trace seems to indicate). The tool then proceeds with the requested operation (RSA keypair generation in my case) which in turn causes a second call to C_Initialize. I suspect that
> this is the cause of the issue.
>
> Using "OPENSSL_no_config()" instead of "OPENSSL_config(NULL)" would probably fix this but before doing a pull request, I would like to have your input on the matter :-)
>
> Anyway, thanks for developing and maintaining OpenSC!

>
> Kind regards
>
> -Cédric
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/477>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by meuter** [comment]
I was missing the init=0 :-)

Thanks for the quick response!
