### ISSUE TITLE
user pin tries_left

### ISSUE THREAD

**Issue by MaryamSD** [OpenSC/OpenSC#478]
Is there any solution to get tries_left of user pin in pkcs11 project?
I can set it in libopensc project, but I need it in pkcs11 level. is there a flag in token_info that exactly related to this case?

**Comment by dengert** [comment]
There are the CKF_USER_PIN_COUNT_LOW and CKF_USER_PIN_FINAL_TRY flags. I don't think
OpenSC sets these. It would take some hardware instructions to get these from the
previous use of the token.

If those don't work, PKCS#11 allows for some _vendor_defined objects, keys, attributes, mechanisms, return codes
hardware features and callbacks.
grep for _VENDOR_DEFIND in the PKCS#11 docs. OpenSC could be modified. Keep in mind that some applications
and vendors uses these such as Netscape. Picking values that don't conflict with these could be
a challenge. Maybe if they start with 0xCF, 0x53, 0x43 OSC fo OpenSC, with the x80 bit on the O.


On 6/7/2015 1:38 AM, MaryamSD wrote:
> Is there any solution to get tries_left of user pin in pkcs11 project?
> I can set it in libopensc project, but I need it in pkcs11 level.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/478>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
Please reopen if you think the question is not answered

**Comment by dengert** [comment]
Have a look at #530 and #531 that address the issue for PIV/NEO and the use of SC_PIN_CMD_GET_INFO
to query a card, and the sw1=63, sw2=CX return code from verify.

Only some cards allow the use of a case 1 VERIFY command, and OpenSC only supports SC_PIN_CMD_GET_INFO
for some cards.

But PKSC#11 defines in CK_TOKEN_INFO these flags:
CKF_USER_PIN_COUNT_LOW, CKF_USER_PIN_FINAL_TRY and CKF_USER_PIN_LOCKED
(Also SO_PIN versions). the definition of LOW (pin_info.max_tries) is left up to the card driver to determine.

OpenSC's C_GetTokenInfo will try and set CKF_USER_PIN_COUNT_LOW, CKF_USER_PIN_FINAL_TRY or CKF_USER_PIN_LOCKED
flags if the card supports the SC_PIN_CMD_GET_INFO

I don't see any other PKCS#11 way to retrieve the actual retry counts.

Does the above meet your need?

On 6/7/2015 1:38 AM, MaryamSD wrote:
> Is there any solution to get tries_left of user pin in pkcs11 project?
> I can set it in libopensc project, but I need it in pkcs11 level.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/478>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>
