### ISSUE TITLE
Windows installer: missing files

### ISSUE THREAD

**Issue by riccainfo** [OpenSC/OpenSC#488]
Hello,
I'm trying to use OpenSC on Windows 8.1 (64 bit) but I can't use engine_pkcs11 because it no longer exists. 
I can't run the following instruction without engine_pkcs11:

engine -t dynamic -pre SO_PATH:engine_pkcs11 -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\System32\engine_pkcs11.dll

How can I do? 

Thank you very much,
Riccardo.

**Comment by dengert** [comment]
Looks like the ./src/win32/OpenSC.iss.in file uses with Inno Setup will include the engine_pkcs11
but the ./src/win32/OpenSC.wxs.in used with WiX does not.

I don't know why inclusion of engine_pkcs11 was not carried over in the conversion to using WiX.
I believe it should have been.

I have no way to test this, maybe someone does?

Also see:
https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer



On 6/22/2015 2:17 PM, riccainfo wrote:
> Hello,
> I'm trying to use OpenSC on Windows 8.1 (64 bit) but I can't use engine_pkcs11 because it no longer exists.
> I can't run the following instruction without engine_pkcs11:
>
> engine -t dynamic -pre SO_PATH:engine_pkcs11 -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\System32\engine_pkcs11.dll
>
> How can I do?
>
> Thank you very much,
> Riccardo.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/488>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
Also `flex.profile` is missing in the installer, see #517

The wxs installer definitely needs to be reviewed.

**Comment by Genbox** [comment]
There are also no instructions for building engine_pkcs11 on Windows. It would be great if someone could provide the engine_pkcs11 DLL file until this issue is fixed.

**Comment by ian-csis** [comment]
Just tried building engine_pkcs11 from scratch, and it does not work on windows. It requires libp11 as a dependency, so I tried building that first, but it fails due to a missing "versioninfo.rc". I then built the source on Linux, which works and generates a versioninfo.rc file. Moving this file to Windows just gives another error related to _snprintf, which is deprecated as I understand it. I'm not keen on trying to figure out how to build this whole thing for windows, and the Wiki (and the OpenSC Windows installer link provided above) seems outdated.

OpenSC is kinda the only solution in my case, would it be possible to fix this bug and release the fixed version sometime soon? I can donate a Yubikey NEO (worth $50) if someone would fix this bug.

**Comment by vletoux** [comment]
How to fix this:
in win32/OpenSC.wxs.in

in `<Directory Id="INSTALLDIR_TOOLS" Name="tools">`
add a Component entry
`<Component Id="engine_pkcs11.dll" Guid="*" Win64="$(var.Win64YesNo)">
                <File Source="$(var.SOURCE_DIR)\src\libopensc\engine_pkcs11.dll" Vital="yes"/>
              </Component>`

in `<Feature Id="Complete" Level="1" Title="OpenSC software suite" Display="expand">`
add a new esture referencing this new component
`<Feature Id="Engine_PKCS11" Level="1" Title="PKCS#11 Engine" Description="Module of the Engine PKCS#11" Absent="allow">
        <ComponentRef Id="engine_pkcs11.dll"/>
      </Feature>`

That's all
(you'll get it in the nigthly build)

Note: you do not need to test it on your computer.
When doing the pull request, the compilation of the msi will be done.
If there are any error, you'll get an error message in the log.

**Comment by vletoux** [comment]
Seems stupid but is the engine_pkcs11.dll produced by the compilator ?
I checked the makefile and exports files and I couldn't find any reference to this file.
Moreover I couldn't find the entry point in the source code published on github (the function bind_engine)

**Comment by frankmorgner** [comment]
@vletoux you're right, https://github.com/OpenSC/engine_pkcs11 is a separate project that is not built anymore together with OpenSC. It used to be included with Innosetup when it was lying around somewhere, see https://github.com/OpenSC/OpenSC/blob/master/win32/installer_from_build.sh#L26-L27.

I think we should eventually include it again in the installer...

**Comment by martinpaljak** [comment]
Not so sure. If there is an application that depends on the engine, it would be the responsibility of that application to bundle the OpenSSL-specific integration thingy with it. OpenSC should advocate for "standard", interchangeable and interoperable interfaces, where on Windows there are only two meaningful ones: PKCS#11 and Minidriver.

While it is easier to add back the engine DLL, it would be more interesting to have an OpenSC build on Windows *without OpenSSL* instead. Eventually the question is if the default installer is a mixed bag of everything or targets some specific user. End-users (Joe-s and Grandma-s) probably don't require the engine, while Developers and PowerUsers do. Maybe it makes sense to have different bundles ?

**Comment by frankmorgner** [comment]
I think engine_pkcs11 should get its own installer since it already has its own release cycles. There are already some nmake files in engine_pkcs11, bootstrapping an installer from this should not be too hard.

@martinpaljak, yes, OpenSSL is a problem because we can't make sure that we are always shipping with a safe version (let alone that AFAIK the msi is built with a binary from here https://slproweb.com/products/Win32OpenSSL.html which we don't have any control over). Disabling OpenSSL disables verification via PKCS\#11 and ECDSA with SHA1 (and of course some otherwise supported cards); would this be a problem?

**Comment by vletoux** [comment]
Making a MSI file, I can do that. But if the installer provide only one file (a dll), I do not think this is very efficient.
Why not implement the same "build tools" that OpenSC have (build the .dll file each time a pull request is done) and set the ".dll file" as the deliverable (instead of a msi file) ?

**Comment by Genbox** [comment]
At the very least, the build instructions for the DLL should be clear. However, it would be great if the DLL is precompiled and made available. Not sure if an installer would make any sense since it is just a single DLL.

**Comment by dengert** [comment]
Note: engine_pkcs11 requires libp11. So more then just one dll.

**Comment by frankmorgner** [comment]
scrolling through the code of libp11 and engine_pkcs11, there seems to be no dependency to OpenSC. And given the limited user base of engine_pkcs11, I agree with @martinpaljak  that it should not be included in OpenSC anymore but in a separate bundle.

@nmav is working on improving the state of both spin off projects. I hope that documentation and CI will get better soon, too.

**Comment by frankmorgner** [comment]
@vletoux could you add the missing profile files to the WiX installer?

**Comment by vletoux** [comment]
Is a patch ok for you ?

I'm busy adding ECC and code source management is not my speciality ;-(

Le mardi 15 septembre 2015, Frank Morgner <notifications@github.com> a
écrit :

> @vletoux <https://github.com/vletoux> could you add the missing profile
> files to the WiX installer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/issues/488#issuecomment-140407285>.
>


-- 
---
Vincent

**Comment by frankmorgner** [comment]
a patch would be great, thanks!

**Comment by vletoux** [comment]
Have you a list of the profile file missing ?
I see : jcop.profile

Example of modifications for this file:
In the OpenSC.wxs.in, in `<Directory Id="INSTALLDIR_PROFILES" Name="profiles">` 
add:
`<Component Id="jcop.profile" Guid="*" Win64="$(var.Win64YesNo)">	<File Source="$(var.SOURCE_DIR)\src\pkcs15init\jcop.profile"/>	</Component>`

Then in `<Feature Id="OpenSC_tools" Level="1" Title="Tools and profiles" ...` add:
`<ComponentRef Id="jcop.profile"/>`

Do the same with the other files missing.

That's all ;-)

**Comment by deekshith565** [comment]
Hi can anyone please help me in how to build engine_pkcs11 dll in Windows?

**Comment by frankmorgner** [comment]
@deekshith565 go to https://github.com/OpenSC/libp11

**Comment by deekshith565** [comment]
@frankmorgner Thanks but I get following error,

I'm using MSYS2 installation procedure to install libp11 in windows, I have done following steps without any error,

To build libp11, download and install msys2-i686-*.exe from https://msys2.github.io

then start a MSYS2 MSYS console from the Start menu and use:

pacman -S git pkg-config libtool autoconf automake make gcc openssl-devel

git clone https://github.com/OpenSC/libp11.git

cd libp11

autoreconf -fi

./configure --prefix=/usr/local

After this when I run make command I get below error,

$ make
Making all in src
make[1]: Entering directory '/home/chowdar1/libp11/src'
make all-am
make[2]: Entering directory '/home/chowdar1/libp11/src'
CCLD pkcs11.la
libtool: error: can't build x86_64-pc-msys shared library unless -no-undefined is specified
make[2]: *** [Makefile:546: pkcs11.la] Error 1
make[2]: Leaving directory '/home/chowdar1/libp11/src'
make[1]: *** [Makefile:417: all] Error 2
make[1]: Leaving directory '/home/chowdar1/libp11/src'
make: *** [Makefile:465: all-recursive] Error 1

Can anyone please help me?
