### ISSUE TITLE
BaseCSP and minidriver

### ISSUE THREAD

**Issue by MaryamSD** [OpenSC/OpenSC#489]
I have a problem with minidriver and BaseCSP in detection two usb smart card token that have same brand. Now, two smart card driver installed on my computer. Each usb smart card token has a unique serial number. Also they have certificate for signing. I’m using a csp test application with this code: https://drive.google.com/file/d/0BwuMibx8Rg66QUJjYUdKS2FSaU0/edit 

Application only detects first token with “The Card is being shared by another process” message. 
It doesn’t detect Second token and displayes “A Smart card was detected but is not the one required for the current operation. The smart card you are using may be missing required driver software or a required certificate” message.
If we select first token, signing will passed. All things seem to be correct, Minidriver log file for this scenario:https://drive.google.com/file/d/0BwuMibx8Rg66MXJIeVpzQjdlT3c/edit

Is there a wrong CspParameters at CSPTest code?
 
I see #384 post that is same problem but I don’t find clear result.
Also I see this link with description about smart card architecture and BaseCsp: 
https://technet.microsoft.com/en-us/library/ff404300%28v=ws.10%29.aspx  
It’s correct that we say “BaseCSP has a caching operation related to first smart card attached”? 
Is there any solution or idea?

**Comment by dengert** [comment]
Both of the files you list below are not readable... "You need permission Want in? Ask the owner for access, or switch to an account with permission"

On 6/24/2015 3:55 AM, MaryamSD wrote:
> I have a problem with minidriver and BaseCSP in detection two usb smart card token that have same brand. Now, two smart card driver installed on my computer. Each usb smart card token has a unique
> serial number. Also they have certificate for signing. I’m using a csp test application with this code: https://drive.google.com/file/d/0BwuMibx8Rg66QUJjYUdKS2FSaU0/edit
>
> Application only detects first token with “The Card is being shared by another process” message.
> It doesn’t detect Second token and displayes “A Smart card was detected but is not the one required for the current operation. The smart card you are using may be missing required driver software or a
> required certificate” message.
> If we select first token, signing will passed. All things seem to be correct, Minidriver log file for this scenario:https://drive.google.com/file/d/0BwuMibx8Rg66MXJIeVpzQjdlT3c/edit
>
> Is there a wrong CspParameters at CSPTest code?
>
> I see #384 <https://github.com/OpenSC/OpenSC/issues/384> post that is same problem but I don’t find clear result.
> Also I see this link with description about smart card architecture and BaseCsp:
> https://technet.microsoft.com/en-us/library/ff404300%28v=ws.10%29.aspx
>
> It’s correct that we say “BaseCSP has a caching operation related to first smart card attached”?
> Is there any solution or idea?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
Please read: https://support.google.com/drive/answer/2494886?hl=en&ref_topic=2525251

On 6/24/2015 3:55 AM, MaryamSD wrote:
> I have a problem with minidriver and BaseCSP in detection two usb smart card token that have same brand. Now, two smart card driver installed on my computer. Each usb smart card token has a unique
> serial number. Also they have certificate for signing. I’m using a csp test application with this code: https://drive.google.com/file/d/0BwuMibx8Rg66QUJjYUdKS2FSaU0/edit
>
> Application only detects first token with “The Card is being shared by another process” message.
> It doesn’t detect Second token and displayes “A Smart card was detected but is not the one required for the current operation. The smart card you are using may be missing required driver software or a
> required certificate” message.
> If we select first token, signing will passed. All things seem to be correct, Minidriver log file for this scenario:https://drive.google.com/file/d/0BwuMibx8Rg66MXJIeVpzQjdlT3c/edit
>
> Is there a wrong CspParameters at CSPTest code?
>
> I see #384 <https://github.com/OpenSC/OpenSC/issues/384> post that is same problem but I don’t find clear result.
> Also I see this link with description about smart card architecture and BaseCsp:
> https://technet.microsoft.com/en-us/library/ff404300%28v=ws.10%29.aspx
>
> It’s correct that we say “BaseCSP has a caching operation related to first smart card attached”?
> Is there any solution or idea?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
Now, Both of them are readable.
Thanks

**Comment by dengert** [comment]
The minidriver and OpenSC signed a sha1 hash.

Data to sign: --- 001CED28:35
  0000  30213009 06052B0E 03021A05 00041467  423EBFA8 454F19AC 6F4686D6 C0DC731A
  0020  3DDD6B

$ openssl asn1parse -i -inform DER < tosign.der
     0:d=0  hl=2 l=  33 cons: SEQUENCE
     2:d=1  hl=2 l=   9 cons:  SEQUENCE
     4:d=2  hl=2 l=   5 prim:   OBJECT            :sha1
    11:d=2  hl=2 l=   0 prim:   NULL
    13:d=1  hl=2 l=  20 prim:  OCTET STRING      [HEX DUMP]:67423EBFA8454F19AC6F4686D6C0DC731A3DDD6B

The cert subject was:
cert->subject 0 --- 04CB6198:106
  0000  31153013 060A0992 268993F2 2C640119  16056C6F 63616C31 15301306 0A099226
  0020  8993F22C 64011916 056B6579 6133310E  300C0603 55040313 05557365 7273310C
  0040  300A0603 55040313 03616C69 311C301A  06092A86 4886F70D 01090116 0D616C69
  0060  406B6579 61332E63 6F6D

$  openssl asn1parse -i -dlimit 30 -inform DER < subject.der
     0:d=0  hl=2 l=  21 cons: SET
     2:d=1  hl=2 l=  19 cons:  SEQUENCE
     4:d=2  hl=2 l=  10 prim:   OBJECT            :domainComponent
    16:d=2  hl=2 l=   5 prim:   IA5STRING         :local
    23:d=0  hl=2 l=  21 cons: SET
    25:d=1  hl=2 l=  19 cons:  SEQUENCE
    27:d=2  hl=2 l=  10 prim:   OBJECT            :domainComponent
    39:d=2  hl=2 l=   5 prim:   IA5STRING         :keya3
    46:d=0  hl=2 l=  14 cons: SET
    48:d=1  hl=2 l=  12 cons:  SEQUENCE
    50:d=2  hl=2 l=   3 prim:   OBJECT            :commonName
    55:d=2  hl=2 l=   5 prim:   PRINTABLESTRING   :Users
    62:d=0  hl=2 l=  12 cons: SET
    64:d=1  hl=2 l=  10 cons:  SEQUENCE
    66:d=2  hl=2 l=   3 prim:   OBJECT            :commonName
    71:d=2  hl=2 l=   3 prim:   PRINTABLESTRING   :ali
    76:d=0  hl=2 l=  28 cons: SET
    78:d=1  hl=2 l=  26 cons:  SEQUENCE
    80:d=2  hl=2 l=   9 prim:   OBJECT            :emailAddress
    91:d=2  hl=2 l=  13 prim:   IA5STRING         :ali@keya3.com


Things to watch out for:

Each card needs a unique serial number.
(unique among all the cards seen on the local system)
This maybe used by OpenSC to derive a unique identifier for each certificate/key pair.

Windows caches the certificates in the Microsoft cert store with the unique identifier above.
This allows Windows to find a certificate in the store, then ask for the card to be inserted.

You did not give any output of your program, so it is not clear if it ran or not, or is waiting for:
Console.WriteLine("Press any key to exit");


I think part of the problem is in the program.

The rsa.VerifyData needs to use a public key to verify, which could be in the certificate.

OpenSC found these objects on the card:
Found 1 certificate(s) in the card.
Found 1 private key(s) in the card.
Found 1 pin(s) in the card.

Although the public key is in the certificate, OpenSC will not automatically pull out the public
key from a certificate, although some OpenSC cards will do that.

It is not clear if the "Microsoft Base Smart Card Crypto Provider" will do that, or if it will look in the
certificate store. Also look at  "Microsoft Smart Card Key Storage Provider"

OpenSC does not do any of the verify operations, as this can be done without the card by standard software.
OpenSC is there for retrieval of data from the card and card based crypto operations (and will do hashing and padding if needed).



On 6/24/2015 3:55 AM, MaryamSD wrote:
> I have a problem with minidriver and BaseCSP in detection two usb smart card token that have same brand. Now, two smart card driver installed on my computer. Each usb smart card token has a unique
> serial number. Also they have certificate for signing. I’m using a csp test application with this code: https://drive.google.com/file/d/0BwuMibx8Rg66QUJjYUdKS2FSaU0/edit
>
> Application only detects first token with “The Card is being shared by another process” message.
> It doesn’t detect Second token and displayes “A Smart card was detected but is not the one required for the current operation. The smart card you are using may be missing required driver software or a
> required certificate” message.
> If we select first token, signing will passed. All things seem to be correct, Minidriver log file for this scenario:https://drive.google.com/file/d/0BwuMibx8Rg66MXJIeVpzQjdlT3c/edit
>
> Is there a wrong CspParameters at CSPTest code?
>
> I see #384 <https://github.com/OpenSC/OpenSC/issues/384> post that is same problem but I don’t find clear result.
> Also I see this link with description about smart card architecture and BaseCsp:
> https://technet.microsoft.com/en-us/library/ff404300%28v=ws.10%29.aspx
>
> It’s correct that we say “BaseCSP has a caching operation related to first smart card attached”?
> Is there any solution or idea?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
As I said, I think the problem is with your test program.

try from command prompt: certutil -Scinfo -v


On 6/24/2015 7:22 AM, MaryamSD wrote:
> Now, Both of them are readable.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489#issuecomment-114849017>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
Now I have questions, in the next post I will explain about details that you mentioned above.  
Is it necessary for each token a separate driver installed?
Is it necessary to run certificate propagation service of windows in detection readers step?(before signing data and verifying), First token detected successful while this service was stop.

**Comment by dengert** [comment]
On 6/25/2015 1:39 AM, MaryamSD wrote:
> Now I have questions, in the next post I will explain about details that you mentioned above.
>
> Is it necessary for each token a separate driver installed?

Windows finds drivers by looking at card ATRs (with masks) listed in registry.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards
This has the 80000001 key that has the dll to be loaded.
Multiple entries can use the same dll. i.e. the OpenSC minidriver)

If you have multiple tokens each with the same ATR, you only need one registry entry.

> Is it necessary to run certificate propagation service of windows in detection readers step?(before signing data and verifying), First token detected successful while this service was stop.

Sounds like a locking problem.
Are you writing your own OpenSC card-*.c?

Are you using the sc_reset function?
If so see https://github.com/OpenSC/OpenSC/pull/487

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489#issuecomment-115124511>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
>Windows finds drivers by looking at card ATRs (with masks) listed in registry.
>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards
>This has the 80000001 key that has the dll to be loaded.
>Multiple entries can use the same dll. i.e. the OpenSC minidriver)
>If you have multiple tokens each with the same ATR, you only need one registry entry.

It is correct. We have same ATR and one registry entry for multiple tokens. So, It's OK.

>Sounds like a locking problem.
>Are you writing your own OpenSC card-*.c?
>Are you using the sc_reset function?

Yes, We have our card-*.c. 
No, We are not using this function.

>try from command prompt: certutil -Scinfo -v

result of running the command:
**First Reader:**
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
--- Status: The card is being shared by a process.

**Second Reader:**
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.

>Each card needs a unique serial number.
>(unique among all the cards seen on the local system)
>This maybe used by OpenSC to derive a unique identifier for each certificate/key pair.

serial number for each token is unique. So, It's OK.

> You did not give any output of your program, so it is not clear if it ran or not, or is waiting for:
>Console.WriteLine("Press any key to exit");

Application detects smart cards first via bellow line code (it's successful for first token and failed for second) and displays result in dialog .
*RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(csp);*

*step1: https://drive.google.com/file/d/0BwuMibx8Rg66Z3pjOGVoY3dpRXM/view?usp=sharing
*step2: https://drive.google.com/file/d/0BwuMibx8Rg66aTQ4c0cwNmpjbjQ/view?usp=sharing
*step3: If We select first token: https://drive.google.com/file/d/0BwuMibx8Rg66Y1I4QkxKMXpKcTg/view?usp=sharing
*step4: Signing for first token passed: https://drive.google.com/file/d/0BwuMibx8Rg66VDBDY2dremJKbWs/view?usp=sharing

**Comment by dengert** [comment]
looking at your screen shots, it looks like there are 3 readers?

To trace any locking problems, modify the opensc.conf file and turn on debugging.
  debug = 9;
  debug_file = c:\tmp\opensc-debug.log

Don't use %TEMP% in file name as system processes may not have TEMP set
and each user has a different TEMP in environment.  Use an absolute path.
The system will call the minidriver when the card is inserted.

If needed create a c:\tmp directory and c:\tmp\opensc-debug.log file that is writable by everyone.

reboot the system, then with only one card try certutil.exe

Then look at opensc-debug.log for all the sc_lock and sc_unlock calls, especially any made by
your card-*.c code.

Your code may be leaving a lock set, when the system reads the card when inserted.


On 6/26/2015 10:27 AM, MaryamSD wrote:
>     Windows finds drivers by looking at card ATRs (with masks) listed in registry.
>     HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards
>     This has the 80000001 key that has the dll to be loaded.
>     Multiple entries can use the same dll. i.e. the OpenSC minidriver)
>     If you have multiple tokens each with the same ATR, you only need one registry entry.
>
> It is correct. We have same ATR and one registry entry for multiple tokens. So, It's OK.
>
>     Sounds like a locking problem.
>     Are you writing your own OpenSC card-*.c?
>     Are you using the sc_reset function?
>
> Yes, We have our card-*.c.
> No, We are not using this function.
>
>     try from command prompt: certutil -Scinfo -v
>
> result of running the command:
> *First Reader:*
> --- Status: SCARD_STATE_PRESENT | SCARD_STATE_INUSE
> --- Status: The card is being shared by a process.
>
> *Second Reader:*
> --- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
> --- Status: The card is available for use.
>
>     Each card needs a unique serial number.
>     (unique among all the cards seen on the local system)
>     This maybe used by OpenSC to derive a unique identifier for each certificate/key pair.
>
> serial number for each token is unique. So, It's OK.
>
>     You did not give any output of your program, so it is not clear if it ran or not, or is waiting for:
>     Console.WriteLine("Press any key to exit");
>
> Application detects smart cards first via bellow line code (it's successful for first token and failed for second) and displays result in dialog .
> /RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(csp);/
>
> *step1: https://drive.google.com/file/d/0BwuMibx8Rg66Z3pjOGVoY3dpRXM/view?usp=sharing
> *step2: https://drive.google.com/file/d/0BwuMibx8Rg66aTQ4c0cwNmpjbjQ/view?usp=sharing
> *step3: If We select first token: https://drive.google.com/file/d/0BwuMibx8Rg66Y1I4QkxKMXpKcTg/view?usp=sharing
> *step4: Signing for first token passed: https://drive.google.com/file/d/0BwuMibx8Rg66VDBDY2dremJKbWs/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/489#issuecomment-115729685>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
>looking at your screen shots, it looks like there are 3 readers?

There are 4 smart card readers installed. First token set in reader3, Second token set in reader2. (This is way that BaseCSP follows and doesn't related to our minidriver) 
Now, We need 2 tokens to test, 4 token is the next scenario.

**Comment by vletoux** [comment]
Hi,

Your problem is located into the test program.
Indeed, you are asking the Base CSP to use the default container, and because the CSP covers both smart cards, it selects only one.

To solve it, you have to put the name of the smart card reader into the container to open.
Please read https://msdn.microsoft.com/en-us/library/bb905527.aspx and especially the table 3.
You should call it with "\\.\reader1" to open the default container on the reader 1 and "\\.\reader2" for the second one.

CspParameters csp = new CspParameters(1, provider, containerName);

To have this value programatically, you should do a couple pinvoke to the winscard library (scardestablishcontext, ...). You can also get an alternative CSP if the card doesn't have a minidriver. Also since 0.15, the CSP has been default to the "OpenSC" one to avoid the digital signature of the minidriver.

regards,
Vincent

**Comment by MaryamSD** [comment]
I'm testing my dlls by smart card logon in windows 7 x86. All things are ok and successfull with 2 tokens have different user pins.
Also I was test in Microsoft Word to add digital signature, here there is exactly same problem with csp test application.

@vletoux
> To have this value programatically, you should do a couple pinvoke to the winscard library (scardestablishcontext, ...). 

I don't understand, can you explain more?

**Comment by vletoux** [comment]
You can ask the user to insert a specific card with this dialog:
SCardUIDlgSelectCard  (https://msdn.microsoft.com/en-us/library/windows/desktop/aa379805%28v=vs.85%29.aspx)
(this dialog has an option to be displayed only when there is more than one smart card - select the current card automatically else)

Then using the reader name, you can build the special container name which includes the reader, and submit it as input to CspParameters.

**Comment by MaryamSD** [comment]
@vletoux 
>SCardUIDlgSelectCard (https://msdn.microsoft.com/en-us/library/windows/desktop/aa379805%28v=vs.85%29.aspx)
>(this dialog has an option to be displayed only when there is more than one smart card - select the current card >automatically else)

SelectCard dialog is exactly my problem. This dialog box only detect First smart card, displaying Second smart card failed. So, I can not select smart card that is not display successful.  
I can Explicitly set container name and password key of CspParameters in cspTest application, So sign Data is successful. But if i want to select smart card via dialog ,all things go to failed.

I got something: By testing data sign via minidriver in Microsoft World and Adobe Acrobat, If we attach tokens first and then select certificate from certificate list, token related to selected certificate can be find and pin dialog displayed, sign document successful. If we select certificate from certificate list first without tokens that are attached, select card dialog displayed, If I attach tokens, they did not detect.     
Smart card Logon is successful for both test case !!

**Comment by dengert** [comment]
On 6/30/2015 5:57 AM, MaryamSD wrote:
    
    
      @vletoux 
      
        SCardUIDlgSelectCard (https://msdn.microsoft.com/en-us/library/windows/desktop/aa379805%28v=vs.85%29.aspx)
          (this dialog has an option to be displayed only when there is
          more than one smart card - select the current card
          >automatically else)
      
      SelectCard dialog is exactly my problem. This dialog box only
        detect First smart card, displaying Second smart card failed.
        So, I can not select smart card that is not display successful.
        
        I can Explicitly set container name and password key of
        CspParameters in cspTest application, So sign Data is
        successful. But if i want to select smart card via dialog ,all
        things go to failed.
      I got something: By testing data sign via minidriver in
        Microsoft World and Adobe Acrobat, If we attach tokens first and
        then select certificate from certificate list, token related to
        selected certificate can be find and pin dialog displayed, sign
        document successful. If we select certificate from certificate
        list first without tokens that are attached, select card dialog
        displayed, If I attach tokens, they did not detect.
      
    
    
    That sounds like a problem with what is stored in the Microsoft
    certificate cache.  With the certificate is cached information to
    find the correct card.
    To get the correct information to store with the certificate the
    minidriver has provide it when the certificate is first cache. The
    minidriver has to 
    provide the same information from the card so the card can be
    associated with the cache certificate. 
    
    In src/libopensc/pkcs15.c look at the sc_pkcs15_get_object_guid This
    will produce a GUID for an object, such as a certificate.
    But it depends on the card and pkcs15 driver to provide the data. 
    Note that a card can provide its own routine to do this, if
    p15card->ops.get_guid is defined. (only the pkcs15-piv.c
    currently uses this.)
    The minidriver uses sc_pkcs15_get_object_guid
    
    You should also look at minidriver.c for CardGetProperty()  and
    CP_CARD_SERIAL_NO, CP_CARD_GUID
    Then in src/libopensc, grep for SC_CARDCTL_GET_SERIALNR 
    
    
      
        Smart card Logon is successful for both test case !!
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
>In src/libopensc/pkcs15.c look at the sc_pkcs15_get_object_guid This
 > will produce a GUID for an object, such as a certificate.
 >But it depends on the card and pkcs15 driver to provide the data.
 >Note that a card can provide its own routine to do this, if
 >p15card->ops.get_guid is defined. (only the pkcs15-piv.c
 >currently uses this.)
 >The minidriver uses sc_pkcs15_get_object_guid

Yes, return value for any token is unique. I trace it, there isn't any problem in GUID.   

>You should also look at minidriver.c for CardGetProperty()  and
>  CP_CARD_SERIAL_NO, CP_CARD_GUID
>Then in src/libopensc, grep for SC_CARDCTL_GET_SERIALNR

minidriver doesn't call CardGetProperty() !!!

**Comment by dengert** [comment]
On 7/1/2015 2:14 AM, MaryamSD wrote:
    
    
      
        In src/libopensc/pkcs15.c look at the
          sc_pkcs15_get_object_guid This
          will produce a GUID for an object, such as a certificate.
          But it depends on the card and pkcs15 driver to provide the
          data.
          Note that a card can provide its own routine to do this, if
          p15card->ops.get_guid is defined. (only the pkcs15-piv.c
          currently uses this.)
          The minidriver uses sc_pkcs15_get_object_guid
      
      Yes, return value for any token is unique. I trace it, there
        isn't any problem in GUID. 
    
    
    Its an object (certificate) GUID, which may be based on the token
    GUID, but each certificate on the token
    needs a globally unique value. 
    
    
      
        You should also look at minidriver.c for CardGetProperty()
          and
          CP_CARD_SERIAL_NO, CP_CARD_GUID
          Then in src/libopensc, grep for SC_CARDCTL_GET_SERIALNR
      
      minidriver doesn't call CardGetProperty() !!!
    
    
    Correct mindriver does not call CardGetProperty but Windows may call
    it. This may be a holdover from cardmod specifications.
    There as a big discussion last year on why some cards did not work
    on windows. It came down to the object guid not being created
    correctly. 
    
    Also clear out any certificates in the cache if you change  how the
    GUID is generated.  
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by MaryamSD** [comment]
I must thank @vletoux for pointing out CspParameters.DefaultKeyContainerName in test csp application.
minidriver has a good operation, but the application is wrong. Now, I list certificates first, by selecting certificate, only related token detected, It's true. I was in a wrong assumption.

Dear dengert, Thank you very much.
