### ISSUE TITLE
OpenVPN fails to authenticate with ePass2003 token: CKR_DATA_INVALID (OS X 10.10.3 Yosemite)

### ISSUE THREAD

**Issue by chepaika** [OpenSC/OpenSC#490]
Strange behavior is observed when using ePass2003 token on OS X 10.10.3, OpenSC 0.15.0 (works fine on Windows 8.1 and Ubuntu 14.04): CKR_DATA_INVALID error occurs during the authentication (right after the PIN request).

# PKCS tool log excerpt
pkcs11-tool --login --test --module /usr/lib/opensc-pkcs11.so --pin 123456

```
Using slot 1 with a present token (0x1)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only RSA signatures)
  testing key 0 (client) 
error: PKCS11 function C_SignFinal failed: rv = CKR_DATA_INVALID (0x20)

Aborting.
```

# OpenVPN log

openvpn --config config.ovpn 
```
....
Fri Jun 26 19:07:28 2015 us=563282   pkcs11_providers = /usr/lib/opensc-pkcs11.so
Fri Jun 26 19:07:28 2015 us=563292   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563297   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563303   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563309   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563314   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563320   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563325   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563331   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563336   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563341   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563347   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563353   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563358   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563363   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563369   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563374   pkcs11_protected_authentication = DISABLED
Fri Jun 26 19:07:28 2015 us=563401   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563413   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563423   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563433   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563442   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563452   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563462   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563471   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563482   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563492   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563501   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563511   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563521   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563531   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563540   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563550   pkcs11_private_mode = 00000000
Fri Jun 26 19:07:28 2015 us=563560   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563570   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563579   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563589   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563598   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563608   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563618   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563627   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563638   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563647   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563657   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563666   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563741   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563754   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563764   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563775   pkcs11_cert_private = DISABLED
Fri Jun 26 19:07:28 2015 us=563785   pkcs11_pin_cache_period = -1
Fri Jun 26 19:07:28 2015 us=563798   pkcs11_id = 'EnterSafe/PKCS\x2315/1013311623031301/test\x20\x28User\x20PIN\x29/E6170AFDB28CEA41188B8938ADCED630BF5BEEDC'
Fri Jun 26 19:07:28 2015 us=563862   pkcs11_id_management = DISABLED
Fri Jun 26 19:07:28 2015 us=563898   server_network = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563912   server_netmask = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563927   server_network_ipv6 = ::
Fri Jun 26 19:07:28 2015 us=563935   server_netbits_ipv6 = 0
Fri Jun 26 19:07:28 2015 us=563943   server_bridge_ip = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563950   server_bridge_netmask = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563956   server_bridge_pool_start = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563965   server_bridge_pool_end = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563975   ifconfig_pool_defined = DISABLED
Fri Jun 26 19:07:28 2015 us=563984   ifconfig_pool_start = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=563995   ifconfig_pool_end = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=564004   ifconfig_pool_netmask = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=564012   ifconfig_pool_persist_filename = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=564018   ifconfig_pool_persist_refresh_freq = 600
Fri Jun 26 19:07:28 2015 us=564024   ifconfig_ipv6_pool_defined = DISABLED
Fri Jun 26 19:07:28 2015 us=564030   ifconfig_ipv6_pool_base = ::
Fri Jun 26 19:07:28 2015 us=564901   ifconfig_ipv6_pool_netbits = 0
Fri Jun 26 19:07:28 2015 us=564913   n_bcast_buf = 256
Fri Jun 26 19:07:28 2015 us=564923   tcp_queue_limit = 64
Fri Jun 26 19:07:28 2015 us=564932   real_hash_size = 256
Fri Jun 26 19:07:28 2015 us=564942   virtual_hash_size = 256
Fri Jun 26 19:07:28 2015 us=564952   client_connect_script = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=564963   learn_address_script = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=564973   client_disconnect_script = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=564983   client_config_dir = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=564992   ccd_exclusive = DISABLED
Fri Jun 26 19:07:28 2015 us=565001   tmp_dir = '/tmp'
Fri Jun 26 19:07:28 2015 us=565015   push_ifconfig_defined = DISABLED
Fri Jun 26 19:07:28 2015 us=565028   push_ifconfig_local = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=565039   push_ifconfig_remote_netmask = 0.0.0.0
Fri Jun 26 19:07:28 2015 us=565050   push_ifconfig_ipv6_defined = DISABLED
Fri Jun 26 19:07:28 2015 us=565066   push_ifconfig_ipv6_local = ::/0
Fri Jun 26 19:07:28 2015 us=565077   push_ifconfig_ipv6_remote = ::
Fri Jun 26 19:07:28 2015 us=565087   enable_c2c = DISABLED
Fri Jun 26 19:07:28 2015 us=565110   duplicate_cn = DISABLED
Fri Jun 26 19:07:28 2015 us=565121   cf_max = 0
Fri Jun 26 19:07:28 2015 us=565128   cf_per = 0
Fri Jun 26 19:07:28 2015 us=565134   max_clients = 1024
Fri Jun 26 19:07:28 2015 us=565185   max_routes_per_client = 256
Fri Jun 26 19:07:28 2015 us=565196   auth_user_pass_verify_script = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=565205   auth_user_pass_verify_script_via_file = DISABLED
Fri Jun 26 19:07:28 2015 us=565215   port_share_host = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=565244   port_share_port = 0
Fri Jun 26 19:07:28 2015 us=565254   client = ENABLED
Fri Jun 26 19:07:28 2015 us=565262   pull = ENABLED
Fri Jun 26 19:07:28 2015 us=565271   auth_user_pass_file = '[UNDEF]'
Fri Jun 26 19:07:28 2015 us=565283 OpenVPN 2.3.6 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Jun 12 2015
Fri Jun 26 19:07:28 2015 us=565294 library versions: OpenSSL 1.0.1o 12 Jun 2015, LZO 2.08
Fri Jun 26 19:07:28 2015 us=565453 PKCS#11: Adding PKCS#11 provider '/usr/lib/opensc-pkcs11.so'
....
Enter test (User PIN) token Password:
Enter test (User PIN) token Password:
Fri Jun 26 19:07:41 2015 us=954737 PKCS#11: Cannot perform signature 32:'CKR_DATA_INVALID'
Fri Jun 26 19:07:41 2015 us=954795 TLS_ERROR: BIO read tls_read_plaintext error: error:14099004:SSL routines:SSL3_SEND_CLIENT_VERIFY:RSA lib
Fri Jun 26 19:07:41 2015 us=954807 TLS Error: TLS object -> incoming plaintext read error
Fri Jun 26 19:07:41 2015 us=954815 TLS Error: TLS handshake failed
Fri Jun 26 19:07:41 2015 us=955026 TCP/UDP: Closing socket
Fri Jun 26 19:07:41 2015 us=955105 SIGUSR1[soft,tls-error] received, process restarting`
```

# conf.ovpn
```
dev tun
proto udp
remote 192.168.1.10 8232
client
pkcs11-providers /usr/lib/opensc-pkcs11.so
pkcs11-id 'EnterSafe/PKCS\x2315/1013311623031301/test\x20\x28User\x20PIN\x29/E6170AFDB28CEA41188B8938ADCED630BF5BEEDC'
tls-auth ta.key 1
ca ca.crt
resolv-retry infinite
remote-cert-tls server
tls-client
persist-key
persist-tun
cipher AES-256-CBC
auth sha256
comp-lzo
verb 6
```

**Comment by dengert** [comment]
An opensc-debug.log would help a lot. See:

https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

or just add -v -v -v -v -v to the pcs111-tool to get debug output on stderr.

On 6/26/2015 11:32 AM, chepaika wrote:
> Strange behavior is observed when using ePass2003 token on OS X 10.10.3, OpenSC 0.15.0 (works fine on Windows 8.1 and Ubuntu 14.04): CKR_DATA_INVALID error occurs during the authentication (right
> after the PIN request).
>
>
>   PKCS tool log excerpt
>
> pkcs11-tool --login --test --module /usr/lib/opensc-pkcs11.so --pin 123456
>
> |Using slot 1 with a present token (0x1)
> C_SeedRandom() and C_GenerateRandom():
>    seeding (C_SeedRandom) not supported
>    seems to be OK
> Digests:
>    all 4 digest functions seem to work
>    MD5: OK
>    SHA-1: OK
>    RIPEMD160: OK
> Signatures (currently only RSA signatures)
>    testing key 0 (client)
> error: PKCS11 function C_SignFinal failed: rv = CKR_DATA_INVALID (0x20)
>
> Aborting.
> |
>
>
>   OpenVPN log
>
> openvpn --config config.ovpn
>
> |....
> Fri Jun 26 19:07:28 2015 us=563282   pkcs11_providers = /usr/lib/opensc-pkcs11.so
> Fri Jun 26 19:07:28 2015 us=563292   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563297   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563303   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563309   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563314   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563320   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563325   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563331   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563336   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563341   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563347   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563353   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563358   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563363   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563369   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563374   pkcs11_protected_authentication = DISABLED
> Fri Jun 26 19:07:28 2015 us=563401   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563413   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563423   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563433   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563442   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563452   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563462   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563471   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563482   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563492   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563501   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563511   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563521   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563531   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563540   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563550   pkcs11_private_mode = 00000000
> Fri Jun 26 19:07:28 2015 us=563560   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563570   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563579   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563589   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563598   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563608   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563618   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563627   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563638   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563647   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563657   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563666   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563741   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563754   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563764   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563775   pkcs11_cert_private = DISABLED
> Fri Jun 26 19:07:28 2015 us=563785   pkcs11_pin_cache_period = -1
> Fri Jun 26 19:07:28 2015 us=563798   pkcs11_id = 'EnterSafe/PKCS\x2315/1013311623031301/test\x20\x28User\x20PIN\x29/E6170AFDB28CEA41188B8938ADCED630BF5BEEDC'
> Fri Jun 26 19:07:28 2015 us=563862   pkcs11_id_management = DISABLED
> Fri Jun 26 19:07:28 2015 us=563898   server_network = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563912   server_netmask = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563927   server_network_ipv6 = ::
> Fri Jun 26 19:07:28 2015 us=563935   server_netbits_ipv6 = 0
> Fri Jun 26 19:07:28 2015 us=563943   server_bridge_ip = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563950   server_bridge_netmask = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563956   server_bridge_pool_start = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563965   server_bridge_pool_end = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563975   ifconfig_pool_defined = DISABLED
> Fri Jun 26 19:07:28 2015 us=563984   ifconfig_pool_start = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=563995   ifconfig_pool_end = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=564004   ifconfig_pool_netmask = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=564012   ifconfig_pool_persist_filename = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=564018   ifconfig_pool_persist_refresh_freq = 600
> Fri Jun 26 19:07:28 2015 us=564024   ifconfig_ipv6_pool_defined = DISABLED
> Fri Jun 26 19:07:28 2015 us=564030   ifconfig_ipv6_pool_base = ::
> Fri Jun 26 19:07:28 2015 us=564901   ifconfig_ipv6_pool_netbits = 0
> Fri Jun 26 19:07:28 2015 us=564913   n_bcast_buf = 256
> Fri Jun 26 19:07:28 2015 us=564923   tcp_queue_limit = 64
> Fri Jun 26 19:07:28 2015 us=564932   real_hash_size = 256
> Fri Jun 26 19:07:28 2015 us=564942   virtual_hash_size = 256
> Fri Jun 26 19:07:28 2015 us=564952   client_connect_script = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=564963   learn_address_script = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=564973   client_disconnect_script = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=564983   client_config_dir = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=564992   ccd_exclusive = DISABLED
> Fri Jun 26 19:07:28 2015 us=565001   tmp_dir = '/tmp'
> Fri Jun 26 19:07:28 2015 us=565015   push_ifconfig_defined = DISABLED
> Fri Jun 26 19:07:28 2015 us=565028   push_ifconfig_local = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=565039   push_ifconfig_remote_netmask = 0.0.0.0
> Fri Jun 26 19:07:28 2015 us=565050   push_ifconfig_ipv6_defined = DISABLED
> Fri Jun 26 19:07:28 2015 us=565066   push_ifconfig_ipv6_local = ::/0
> Fri Jun 26 19:07:28 2015 us=565077   push_ifconfig_ipv6_remote = ::
> Fri Jun 26 19:07:28 2015 us=565087   enable_c2c = DISABLED
> Fri Jun 26 19:07:28 2015 us=565110   duplicate_cn = DISABLED
> Fri Jun 26 19:07:28 2015 us=565121   cf_max = 0
> Fri Jun 26 19:07:28 2015 us=565128   cf_per = 0
> Fri Jun 26 19:07:28 2015 us=565134   max_clients = 1024
> Fri Jun 26 19:07:28 2015 us=565185   max_routes_per_client = 256
> Fri Jun 26 19:07:28 2015 us=565196   auth_user_pass_verify_script = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=565205   auth_user_pass_verify_script_via_file = DISABLED
> Fri Jun 26 19:07:28 2015 us=565215   port_share_host = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=565244   port_share_port = 0
> Fri Jun 26 19:07:28 2015 us=565254   client = ENABLED
> Fri Jun 26 19:07:28 2015 us=565262   pull = ENABLED
> Fri Jun 26 19:07:28 2015 us=565271   auth_user_pass_file = '[UNDEF]'
> Fri Jun 26 19:07:28 2015 us=565283 OpenVPN 2.3.6 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Jun 12 2015
> Fri Jun 26 19:07:28 2015 us=565294 library versions: OpenSSL 1.0.1o 12 Jun 2015, LZO 2.08
> Fri Jun 26 19:07:28 2015 us=565453 PKCS#11: Adding PKCS#11 provider '/usr/lib/opensc-pkcs11.so'
> ....
> Enter test (User PIN) token Password:
> Enter test (User PIN) token Password:
> Fri Jun 26 19:07:41 2015 us=954737 PKCS#11: Cannot perform signature 32:'CKR_DATA_INVALID'
> Fri Jun 26 19:07:41 2015 us=954795 TLS_ERROR: BIO read tls_read_plaintext error: error:14099004:SSL routines:SSL3_SEND_CLIENT_VERIFY:RSA lib
> Fri Jun 26 19:07:41 2015 us=954807 TLS Error: TLS object -> incoming plaintext read error
> Fri Jun 26 19:07:41 2015 us=954815 TLS Error: TLS handshake failed
> Fri Jun 26 19:07:41 2015 us=955026 TCP/UDP: Closing socket
> Fri Jun 26 19:07:41 2015 us=955105 SIGUSR1[soft,tls-error] received, process restarting`
> |
>
>
>   conf.ovpn
>
> |dev tun
> proto udp
> remote 192.168.1.10 8232
> client
> pkcs11-providers /usr/lib/opensc-pkcs11.so
> pkcs11-id 'EnterSafe/PKCS\x2315/1013311623031301/test\x20\x28User\x20PIN\x29/E6170AFDB28CEA41188B8938ADCED630BF5BEEDC'
> tls-auth ta.key 1
> ca ca.crt
> resolv-retry infinite
> remote-cert-tls server
> tls-client
> persist-key
> persist-tun
> cipher AES-256-CBC
> auth sha256
> comp-lzo
> verb 6
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/490>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by chepaika** [comment]
`OPENSC_DEBUG=9 pkcs11-tool --login --test --module /usr/lib/opensc-pkcs11.so --pin 123456` is too much! I load it to my dropbox.
https://www.dropbox.com/s/a747bubab7xr35j/pkcs11-tool.log?dl=0

**Comment by dengert** [comment]
This could be a problem wit the MacOS pcsc and extended APDs. 
    I don't have a Mac, so someone else should follow up on this.
    
    The failing code is starts at line 4785 in your trace:
    
    0x7fff794fb300 17:15:16.140733193388333 [opensc-pkcs11]
    apdu.c:389:sc_single_transmit: CLA:0, INS:2A, P1:80, P2:86,
    data(256) 0x7fff4ff78c70
    0x7fff794fb300 17:15:16.301 [opensc-pkcs11]
    sm.c:133:sc_sm_single_transmit: called
    0x7fff794fb300 17:15:16.301 [opensc-pkcs11]
    sm.c:134:sc_sm_single_transmit: SM_MODE:200
    0x7fff794fb300 17:15:16.140733193388333 [opensc-pkcs11]
    card-epass2003.c:852:epass2003_sm_get_wrapped_apdu: called
    0x7fff794fb300 17:15:16.301 [opensc-pkcs11]
    card-epass2003.c:692:epass2003_sm_wrap_apdu: called
    0x7fff794fb300 17:15:16.301 [opensc-pkcs11]
    card-epass2003.c:877:epass2003_sm_get_wrapped_apdu: returning with:
    0 (Success)
    0x7fff794fb300 17:15:16.301 [opensc-pkcs11]
    reader-pcsc.c:251:pcsc_transmit: reader 'Feitian ePass2003'
    0x7fff794fb300 17:15:16.140733193388334 [opensc-pkcs11]
    apdu.c:187:sc_apdu_log: 
    Outgoing APDU data [  300 bytes]
    =====================================
    0C 2A 80 86 00 01 23 87 82 01 11 01 01 2B 02 8F .*....#......+..
    DC 93 7A 1B 9D 6F 9A 06 22 69 94 2A 84 99 B8 51 ..z..o.."i.*...Q
    42 F4 4F EC E6 26 9E 01 95 19 99 44 B4 AA 45 04 B.O..&.....D..E.
    15 D5 96 C3 25 3B 00 99 BE 82 2A 98 38 73 AA B0 ....%;....*.8s..
    CB A4 3C 1D A8 1F 7F 73 53 D2 B0 35 3C DE 13 95
    ..<....sS..5<...
    8B ED EF B6 9F AE E1 96 A2 3C A1 68 C1 BC A7 32 .........<.h...2
    EA 21 07 11 C3 80 95 5A 63 66 88 80 01 EF BF 1F .!.....Zcf......
    80 29 B9 37 35 CE 10 71 18 26 1F 6A B0 35 B4 EE .).75..q.&.j.5..
    B2 C2 67 5C 59 3A C8 6A 84 72 9E 54 5D 70 00 3B ..g\Y:.j.r.T]p.;
    87 55 FF 17 1C 6C 50 F7 59 84 51 97 B0 87 67 21 .U...lP.Y.Q...g!
    5F AF EC B8 E5 0B 01 C0 01 A2 06 A2 68 18 36 1F _...........h.6.
    89 FD B1 45 DF FB 3D AE 3F 1A AC B5 A7 65 F3 7F ...E..=.?....e..
    E5 D0 5B EF 79 E5 82 3C 46 2E 55 84 15 FD 6C 60 ..[.y..<F.U...l`
    AE 7C C6 62 BE 87 18 12 4A 2A 30 DB 26 F3 0B DD .|.b....J*0.&...
    5A 6C E0 9B B1 BA 93 0D 46 72 89 3B 69 0D C1 4F Zl......Fr.;i..O
    C0 F6 BF 18 35 86 97 EC A1 2D EF 38 AC 55 21 5F ....5....-.8.U!_
    77 A5 1A 08 B6 CB 88 08 A0 03 F0 B8 F3 89 A7 B2 w...............
    A2 11 E1 D0 90 11 66 54 1C A1 02 F7 97 02 01 00 ......fT........
    8E 08 2F B0 E7 62 3C 6B E4 2C 01 00             ../..b<k.,..
======================================================================
    0x7fff794fb300 17:15:16.140733193388334 [opensc-pkcs11]
    reader-pcsc.c:184:pcsc_internal_transmit: called
    0x7fff794fb300 17:15:16.305 [opensc-pkcs11] apdu.c:187:sc_apdu_log:
    
    Incoming APDU data [    2 bytes]
    =====================================
    6A 80 j.
======================================================================
    0x7fff794fb300 17:15:16.306 [opensc-pkcs11]
    card-epass2003.c:824:epass2003_sm_free_wrapped_apdu: called
    0x7fff794fb300 17:15:16.140733193388338 [opensc-pkcs11]
    card-epass2003.c:794:epass2003_sm_unwrap_apdu: called
    0x7fff794fb300 17:15:16.140733193388338 [opensc-pkcs11]
    iso7816.c:139:iso7816_check_sw: Incorrect parameters in the data
    field
    0x7fff794fb300 17:15:16.306 [opensc-pkcs11]
    card-epass2003.c:812:epass2003_sm_unwrap_apdu: unwrapped APDU:
    resplen 0, SW 6A80
    0x7fff794fb300 17:15:16.306 [opensc-pkcs11]
    card-epass2003.c:813:epass2003_sm_unwrap_apdu: returning with: 0
    (Success)
    0x7fff794fb300 17:15:16.-4294966990 [opensc-pkcs11]
    card-epass2003.c:840:epass2003_sm_free_wrapped_apdu: returning with:
    0 (Success)
    0x7fff794fb300 17:15:16.571230650674 [opensc-pkcs11]
    sm.c:172:sc_sm_single_transmit: returning with: 0 (Success)
    0x7fff794fb300 17:15:16.2986857855505662258 [opensc-pkcs11]
    apdu.c:552:sc_transmit: returning with: 0 (Success)
    0x7fff794fb300 17:15:16.-4294966990 [opensc-pkcs11]
    card.c:392:sc_unlock: called
    0x7fff794fb300 17:15:16.306 [opensc-pkcs11]
    iso7816.c:139:iso7816_check_sw: Incorrect parameters in the data
    field
    
    This APDU was wrapped (the input apdu with data is not shown in
    trace)  and the outgoing wrapped APDU is now using 
    extended length : 00 01 23  (line 4793)
    This is the only extended length APDU  I see. As you said it works
    on Windows and Ubuntu, it would interesting to see what the
    opensc-debug.log on one of these
    systems shows.  (look for sc_pkcs15_compute_signature: called, as
    the start of the sign operation.)
    
    The card returns 6A80  "Incorrect parameters in the command data
    field"
    This could be or the wrapping APDU, or the wrapped APDU, its not
    clear.
    
    I could be the MacOS pcsc may have a problem with the extended
    length. A trace of pcsc might show something.
    
    
    
    On 6/28/2015 9:23 AM, chepaika wrote:
    
    
      OPENSC_DEBUG=9 pkcs11-tool --login --test --module
          /usr/lib/opensc-pkcs11.so --pin 123456 is too much! I
        load it to my dropbox.
        https://www.dropbox.com/s/a747bubab7xr35j/pkcs11-tool.log?dl=0
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
Could you try setting `max_send_size` and `max_recv_size` in the `reader_driver pcsc` of `opensc.conf` to a lower value?

**Comment by frankmorgner** [comment]
@chepaika have you been able to solve this problem?

**Comment by chepaika** [comment]
No. I' just use eToken Pro instead ePass 2003 with oficial drivers. But I
still have some ePass Token and can test it on ElCaptain. Just gimme a few
days.

2015-11-01 23:52 GMT+03:00 Frank Morgner <notifications@github.com>:

> @chepaika <https://github.com/chepaika> have you been able to solve this
> problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/issues/490#issuecomment-152862910>.
>



-- 
Федор

**Comment by frankmorgner** [comment]
Any new input?

**Comment by chepaika** [comment]
Sorry for delay. I chek all again in OS X 10.11 with opensc 0.15 installed
by brew and all working fine! So i think the issue can be closed

2015-11-17 3:09 GMT+03:00 Frank Morgner <notifications@github.com>:

> Any new input?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/issues/490#issuecomment-157215624>.
>



-- 
Федор

**Comment by frankmorgner** [comment]
thanks
