### ISSUE TITLE
Support A.E.T. SafeSign Identity cards

### ISSUE THREAD

**Issue by AlexanderWillner** [OpenSC/OpenSC#491]
Version: 0.14.0

Steps that will reproduce the problem?
1. Run opensc-tool --reader 0 --name

What is the expected result?
Identify the card and print its name

What happens instead?
Unsupported card

Possible workaround:
Install Firefox plugin from https://www.aeteurope.nl/ (SafeSignIC3.0.97 driver) and use smart card in Firefox only.

Any additional information:
```
$ opensc-tool --reader 0 --atr
3b:bb:18:00:c0:10:31:fe:45:80:67:04:12:b0:03:03:00:00:81:05:3c
```
Will test with 0.15.0 as soon as there is a version for OS X available (e.g. via brew)

**Comment by AlexanderWillner** [comment]
Same with version 0.15.0

**Comment by frankmorgner** [comment]
We would be happy to add this ID card. The only problem is, that we don't have one ;-)

If you have some working code we are happy to review a PR. See also https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver.
