### ISSUE TITLE
Can't init KeyStore via Sun PKCS11 Provider

### ISSUE THREAD

**Issue by frapontillo** [OpenSC/OpenSC#495]
I am trying to access the smartcard KeyStore via the OpenSC DLL on Windows 8.1 x64.

I am therefore building the Provider via the following config file:
```
name = SmartCard
library = C:\Windows\SysWOW64\opensc-pkcs11.dll
slotListIndex = 0
```

The provider gets built with the following information:
```
0 = {java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntry@1016} "Provider.id info" -> "SunPKCS11-SmartCard using library C:\Windows\SysWOW64\opensc-pkcs11.dll"
1 = {java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntry@1017} "Provider.id className" -> "sun.security.pkcs11.SunPKCS11"
2 = {java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntry@1018} "Provider.id version" -> "1.8"
3 = {java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntry@1019} "Provider.id name" -> "SunPKCS11-SmartCard"
```

The thing is, if I use the original closed-source driver by Bit4ID (`bit4ipki.dll`), I end up having much more (48) entries in the set, among which there's also a PKCS11 KeyStore.

Therefore, the first line always throws an Exception, since no implementation for KeyStore can be found:
```
Object[] objs = Security.getImpl(type, "KeyStore", provider);
return new KeyStore((KeyStoreSpi)objs[0], (Provider)objs[1], type);
```

Is this a solvable issue? What does it depend on?

My environment is:
```
C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             CASTLES EZ100PU 0

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -a
Using reader with a card: CASTLES EZ100PU 0
3b:ff:18:00:00:81:31:fe:45:00:6b:04:05:07:00:01:21:01:43:4e:53:10:31:80:5f

C:\Program Files (x86)\OpenSC Project\OpenSC\tools>opensc-tool -n
Using reader with a card: CASTLES EZ100PU 0
CNS card
```

**Comment by frankmorgner** [comment]
Does this guide http://www.smartcard-hsm.com/2014/09/05/Accessing_your_SmartCard-HSM_from_EJBCA.html help you?

**Comment by rafikbo76** [comment]
Here is Some java code to register your provider and load the keystore : 

	public static Provider getPKCS11Provider(String pkcs11DLL, long [] slots, final String PIN){
			Provider providerPKCS11 = null;
			String config = "name=OpenSC\n" +
					"library=" + pkcs11DLL + "\n" +
					"slotListIndex = " + slots[0];
			CallbackHandler myCallbackHandler = new CallbackHandler() {
				@Override
				public void handle(Callback[] callbacks) throws IOException,
						UnsupportedCallbackException {
					for (Callback callback : callbacks) {
						System.out.println(callback.getClass().getName());
						if (callback instanceof PasswordCallback) {
							PasswordCallback passwordCallback = (PasswordCallback) callback;
							passwordCallback.setPassword(PIN.toCharArray());
						}
					}
				}
			};
			ByteArrayInputStream bais = new ByteArrayInputStream(config.getBytes());
			providerPKCS11 = new SunPKCS11(bais);
			
			try {
				((SunPKCS11)providerPKCS11).login(null, myCallbackHandler);
				Security.addProvider(providerPKCS11);
			} catch (LoginException e) {
				e.printStackTrace();
				return null;
			}
			return providerPKCS11;
	}

// Load keyStore after registering the provider

	KeyStore ks = null;
	try{
		KeyStore  ks = KeyStore.getInstance("PKCS11");
		ks.load(null,null);
				
	} catch (Exception e) {
		e.printStackTrace();
		return null;
	}

you need to understand some other things : 
- In your java Code, keep c:\windows\system32 as the directory of your PKCS11 DLL (whether it's 32 or 64 version), 
- If the calling application is an x86 app (the JRE in this case), Windows will redirect automatically to SysyWOW64 directory to load the 32 bit version of ur dll
- If the calling application is x64 app, windows will look for 64 version of the DLL in system32 directory

OpenSC guys suggest to install both x86 and x64 version of OpenSC on a 64 windows machine, just because the calling application can be an x86 or x64 app.

**Comment by dengert** [comment]
This sounds like the #523
slotListIndex = 0

**Comment by frapontillo** [comment]
@dengert that bug might be related. I'll try this and get back to you.

**Comment by frapontillo** [comment]
@dengert I have explicited `slotListIndex = 1` and it now works **BUT** it only returns one key, which probably is the one listed by `pkcs11-tool -O`:

```
Public Key Object; RSA 1024 bits
  label:      CNS0
  ID:         01
  Usage:      encrypt, verify, wrap
Certificate Object, type = X.509 cert
  label:      CNS0
  ID:         01
Data object 44644208
  label:          'EF_DatiProcessore'
  application:    'EF_DatiProcessore'
  app_id:         <empty>
  flags:          <empty>

Data object 44643424
  label:          'EF_IDCarta'
  application:    'EF_IDCarta'
  app_id:         <empty>
  flags:          <empty>

Data object 44642472
  label:          'EF_DatiPersonali'
  application:    'EF_DatiPersonali'
  app_id:         <empty>
  flags:          <empty>

Data object 44642528
  label:          'EF_DatiPersonaliAggiuntivi'
  application:    'EF_DatiPersonaliAggiuntivi'
  app_id:         <empty>
  flags:          <empty>

Data object 44644320
  label:          'EF_MemoriaResidua'
  application:    'EF_MemoriaResidua'
  app_id:         <empty>
  flags:          <empty>

Data object 44644376
  label:          'EF_ServiziInstallati'
  application:    'EF_ServiziInstallati'
  app_id:         <empty>
  flags:          <empty>

Data object 44644264
  label:          'EF_INST_FILE'
  application:    'EF_INST_FILE'
  app_id:         <empty>
  flags:          <empty>

Data object 44735192
  label:          'EF_CardStatus'
  application:    'EF_CardStatus'
  app_id:         <empty>
  flags:          <empty>

Data object 44736088
  label:          'EF_GDO'
  application:    'EF_GDO'
  app_id:         <empty>
  flags:          <empty>

Data object 44734800
  label:          'EF_RootInstFile'
  application:    'EF_RootInstFile'
  app_id:         <empty>
  flags:          <empty>

```

There is actually another key, which is supposed to be used for signing, that doesn't show up at all.

**Comment by dengert** [comment]
If there is a key, does it have to have a cert on the card too?
Do you have to be logged in too see the other key and its cert?

Do you have to logon to see the other key and its cert?
pkcs11-tool -O --logon

With Java An opensc-spy trace would help show if its a Java or OpenSC issue.

On 8/26/2015 2:40 AM, Francesco Pontillo wrote:
> @dengert <https://github.com/dengert> I have explicited |slotListIndex = 1| and it now works *BUT* it only returns one key, which probably is the one listed by |pkcs11-tool -O|:
>
> |Public Key Object; RSA 1024 bits label: CNS0 ID: 01 Usage: encrypt, verify, wrap Certificate Object, type = X.509 cert label: CNS0 ID: 01 Data object 44644208 label: 'EF_DatiProcessore' application:
> 'EF_DatiProcessore' app_id: <empty> flags: <empty> Data object 44643424 label: 'EF_IDCarta' application: 'EF_IDCarta' app_id: <empty> flags: <empty> Data object 44642472 label: 'EF_DatiPersonali'
> application: 'EF_DatiPersonali' app_id: <empty> flags: <empty> Data object 44642528 label: 'EF_DatiPersonaliAggiuntivi' application: 'EF_DatiPersonaliAggiuntivi' app_id: <empty> flags: <empty> Data
> object 44644320 label: 'EF_MemoriaResidua' application: 'EF_MemoriaResidua' app_id: <empty> flags: <empty> Data object 44644376 label: 'EF_ServiziInstallati' application: 'EF_ServiziInstallati'
> app_id: <empty> flags: <empty> Data object 44644264 label: 'EF_INST_FILE' application: 'EF_INST_FILE' app_id: <empty> flags: <empty> Data object 44735192 label: 'EF_CardStatus' application:
> 'EF_CardStatus' app_id: <empty> flags: <empty> Data object 44736088 label: 'EF_GDO' application: 'EF_GDO' app_id: <empty> flags: <empty> Data object 44734800 label: 'EF_RootInstFile' application:
> 'EF_RootInstFile' app_id: <empty> flags: <empty> |
>
> There is actually another key, which is supposed to be used for signing, that doesn't show up at all.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/495#issuecomment-134880307>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frapontillo** [comment]
The other key has a different certificate associated to it (different issuer, etc.), if I login (`pkcs11-tool -O --login`) I can simply see the private RSA key associated to the same X509 certificate as before:

```
Private Key Object; RSA
  label:      CNS0
  ID:         01
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 1024 bits
  label:      CNS0
  ID:         01
  Usage:      encrypt, verify, wrap
Certificate Object, type = X.509 cert
  label:      CNS0
  ID:         01
```

For this very reason I think it's not a Java issue but a driver one, as not even `pkcs11-tool` can read the second certificate.

**Comment by martinpaljak** [comment]
Thus I assume the driver does not know how to expose the signature key or there's a bug in it. If pkcs15-tool -D does not show more than one set of keys/certificates, don't debug PKCS#11, but the lower level driver (src/libopensc/pkcs15-itacns.c)

I think the PKCS#11 issue can be closed

**Comment by frapontillo** [comment]
@martinpaljak I assume you mean `pkcs11-tool -D`, right?

How can I debug `src/libopensc/pkcs15-itacns.c` instead?

**Comment by dengert** [comment]
On 8/26/2015 10:45 AM, Francesco Pontillo wrote:
> @martinpaljak <https://github.com/martinpaljak> I assume you mean |pkcs11-tool -D|, right?

No, pkcs15-tool -D. It dumps every thing it can find.

>
> How can I debug |src/libopensc/pkcs15-itacns.c| instead?

use the debug variables in opensc.conf or the -v option  of pkcs15-tool multiple times.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/495#issuecomment-135074170>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frapontillo** [comment]
This is the output of `pkcs15-tool -D -v`, it only shows one certificate and one key pair:

```
Connecting to card in reader CASTLES EZ100PU 0...
Using card driver Italian CNS.
PKCS#15 Card [My Name]:
	Version        : 0
	Serial number  : 2444024000002384
	Manufacturer ID: IC: NXP Semiconductors; mask: Oberthur Card Systems
	Flags          : 

Card has 2 Authentication objects.
PIN [PIN CNS0]
	Object Flags   : [0x3], private, modifiable
	Auth ID        : a0
	ID             : 01
	Flags          : [0x11], case-sensitive, initialized
	Length         : min_len:5, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 16 (0x10)
	Type           : ascii-numeric
	Tries left     : 0

PIN [PUK CNS0]
	Object Flags   : [0x1], private
	ID             : a0
	Flags          : [0x59], case-sensitive, unblock-disabled, initialized, unblockingPin
	Length         : min_len:5, max_len:8, stored_len:8
	Pad char       : 0xFF
	Reference      : 17 (0x11)
	Type           : ascii-numeric
	Tries left     : 0

Card has 1 private key(s).

Private RSA Key [CNS0]
	Object Flags   : [0x1], private
	Usage          : [0x26], decrypt, sign, unwrap
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 1024
	Key ref        : 1 (0x1)
	Native         : yes
	Auth ID        : 01
	ID             : 01
	MD:guid        : {cc111473-641f-503d-15d6-b004e576e9c1}
	  :cmap flags  : 0x0
	  :sign        : 0
	  :key-exchange: 0

Card has 1 public key(s).

Public RSA Key [CNS0]
	Object Flags   : [0x0]
	Usage          : [0x51], encrypt, wrap, verify
	Access Flags   : [0x2], extract
	ModLength      : 1024
	Key ref        : 1 (0x1)
	Native         : no
	Path           : 3f003f01
	ID             : 01

Card has 1 certificate(s).

X.509 Certificate [CNS0]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 3f0011001101
	ID             : 01
	Encoded serial : 02 08 00E7C3C59A13C4CF
Data object 'EF_DatiProcessore'
	applicationName: EF_DatiProcessore
	Path:            3f0010001002
	Data (54 bytes): 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                  000000000000
Data object 'EF_IDCarta'
	applicationName: EF_IDCarta
	Path:            3f0010001003
	Data (16 bytes): 32343434303234303030303032333834
Data object 'EF_DatiPersonali'
	applicationName: EF_DatiPersonali
	Path:            3f0011001102
	Data (400 bytes): 303030303636303332353030383235303932303133303832353039323031393037416E74657A7A613035526F63636F30
                   38313630363139383130314D303031304E545A52434338314831364C34313858303030344C3431383030303030344630
                   353230303030000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   00000000000000000000000000000000
Data object 'EF_DatiPersonaliAggiuntivi'
	applicationName: EF_DatiPersonaliAggiuntivi
	Path:            3f0012001201
	Data (100 bytes): 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   00000000
Data object 'EF_MemoriaResidua'
	applicationName: EF_MemoriaResidua
	Path:            3f0012001202
	Data (2 bytes): 7766
Data object 'EF_ServiziInstallati'
	applicationName: EF_ServiziInstallati
	Path:            3f0012001203
	Data (160 bytes): 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   00000000000000000000000000000000
Data object 'EF_INST_FILE'
	applicationName: EF_INST_FILE
	Path:            3f0012004142
	Data (128 bytes): B49A8939B65506013686E1075F353B125C9658ABE2AF60F7EEAC19F0DA85688B815462DB9316AB43E5BC5C919D9A994D
                   5FF2FC61BDE3E51DA7F1011DC5F75804AE41AD2B812EAD27B812119FDE1E62182BD60DD67618128283D74612D30025F1
                   6865154F896285AAF86138BA66471C343C0E0EE58667DCE5472448B36C68B8DE
Data object 'EF_CardStatus'
	applicationName: EF_CardStatus
	Path:            3f003f02
	Data (20 bytes): 0000000000000000000000000000000000000000
Data object 'EF_GDO'
	applicationName: EF_GDO
	Path:            3f002f02
	Data (105 bytes): 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
                   000000000000000000
Data object 'EF_RootInstFile'
	applicationName: EF_RootInstFile
	Path:            3f000405
	Data (128 bytes): 8E572BE7246F8071D0F82FE5D5BB91F311E59B2D2046E3F4AD934431B5F298CC980D33B09291658D60501F67219464FB
                   B32D1A139E770F59696DE0E6C7E6D55E571575C7452E3473783159A7BE3185C4AD9E00FAD6BBBA06D2008EB7A8A4F38F
                   F85A39555A56EE0C8DC0FD198B328E7DD1199404ABDBAE7E9994DAEEFD853392
```

**Comment by dengert** [comment]
Sounds like OpenSC drivers for this card don't know how to find the certificate. The card drivers may have been for an older version of a standard,  or the vendor that wrote the bit4opki added some non stadard certificate?

Di you try the pkcs15-tool with the --login option? You may only be able to see it it you are loged in.

**Comment by frapontillo** [comment]
@dengert No, I didn't use the `--login` option (there is none), but I did try the `--pin` one, without any success.

**Comment by frankmorgner** [comment]
@frapontillo you may debug `src/libopensc/pkcs15-itacns.c` and `src/libopensc/card-itacns.c` by adding `debug = 20;` to `opensc.conf`. https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/pkcs15-itacns.c#L811-L834 actually looks for the non repudiation certificate:
```
/*** Certificate and keys. ***/
	/* Standard CNS */
	r = itacns_check_and_add_keyset(p15card, "CNS0", cns0_secenv,
		0, "3F0011001101", "3F003F01", NULL,
		0x10, &found_certs);
	SC_TEST_RET(p15card->card->ctx, SC_LOG_DEBUG_NORMAL, r,
		"Could not add CNS0");
	certificate_count += found_certs;

	/* Infocamere 1204 */
	r = itacns_check_and_add_keyset(p15card, "CNS01", 0x21,
		5, "3F002FFF8228", NULL, "3F002FFF0000",
		0x10, &found_certs);
	SC_TEST_RET(p15card->card->ctx, SC_LOG_DEBUG_NORMAL, r,
		"Could not add CNS01");
	certificate_count += found_certs;

	/* Digital signature */
	r = itacns_check_and_add_keyset(p15card, "CNS1", 0x10,
		0, "3F0014009010", "3F00140081108010", "3F0014008110",
		0x1a, &found_certs);
	SC_TEST_RET(p15card->card->ctx, SC_LOG_DEBUG_NORMAL, r,
		"Could not add CNS1");
	certificate_count += found_certs;
```
Maybe your card is using a non-standard location?!

**Comment by frankmorgner** [comment]
@frapontillo is this problem still relevant?

**Comment by frapontillo** [comment]
@frankmorgner I really didn't have any time to test this. I will close the issue and reopen in case your suggestion doesn't work. Thanks for the help!
