### ISSUE TITLE
using pkcs11-tool keypairgen without GUI

### ISSUE THREAD

**Issue by flyingmouse** [OpenSC/OpenSC#509]
Hello, when I am using this command
> pkcs11-tool --module /usr/lib/libidprimepkcs11.so -l --pin 0000 --keypairgen --key-type rsa:1024 --id 12

to generate a key pair, it works fine in Ubuntu in choosing the right PIN type (PIN in my case, PIN4-7 and digital signature as options), but in Intel Edison where there is no  desktop environment, it returns this error message:
>  Unable to initialize GTK+, is DISPLAY set properly?

Is there a way to pass the **PIN-type** parameter in the command in lieu of choosing it graphically? 

Thanks and regards,
Haoming

**Comment by frankmorgner** [comment]
OpenSC does not use GTK at all. I guess this is a misconfiguration in your PKCS#11 provider (which we can't give any support for).

To pkcs11-tool you can supply a PIN by using the CLI or an environment variable. Please check its manpage.
