### ISSUE TITLE
After a fork do not release resources shared with parent when C_Finalize is called

### ISSUE THREAD

**Issue by nmav** [OpenSC/OpenSC#510]
The issue of C_Login returning CKR_GENERAL_ERROR after a fork was resolved by setting a special flag when C_Initialize was called in #494. However, if after a fork, C_Finalize is called the same issue occurs.

For a reproducer download:
https://bugzilla.redhat.com/attachment.cgi?id=1022342

and remove the C_Initialize call after the fork.

**Comment by frankmorgner** [comment]
Wait, didn't http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759987 say that `C_Initialize` *should* be called first? Hence, calling `C_Finalize` in the forked child would not be OK.

**Comment by nmav** [comment]
It does, but that is irrelevant. If due to a bug the child calls C_Finalize(), the parent process shouldn't break. The PKCS #11 instructions are for the child to work properly, they don't imply that if that order  is not kept, the the parent will break.

**Comment by frankmorgner** [comment]
With this logic you should add robustness also to the other library calls, right?

And as you said it, it's a bug in the child - not within OpenSC...

Do you know any application that calls `C_Finalize()` first?

**Comment by nmav** [comment]
Well if the parent breaks I see it as an opensc bug. The child shouldn't affect the parent's resources. We can wait for the issue to be reported if you like, but I do not see the point. The check has no significant cost.

**Comment by frankmorgner** [comment]
Let's wait for comments from the other developers. Maybe someone can name an application that has this behavior...

**Comment by frankmorgner** [comment]
no comments so far. let's re-open this issue when there is an actual problem/need to do this

**Comment by nmav** [comment]
I prefer software to be by default as safe as possible, especially when such an issue has consequences to other processes, consequences which are very hard to debug. In that aspect I think it makes not point optimizing out such an easy check on the deinitialize function.

**Comment by frankmorgner** [comment]
The problem would only occur if an application does not respect PKCS\#11. We can't protect against all variants of invalid use. Name an application that has this problem and we can talk about adding this as workaround for this specific application.

**Comment by nmav** [comment]
That's actually my point, not to make work-arounds for broken applications, but prevent them from being needed. In any case I don't see any point in arguing any more as we clearly disagree in the approach.
