### ISSUE TITLE
Alternative pkcs11 headers

### ISSUE THREAD

**Issue by MikaJustas** [OpenSC/OpenSC#514]
Hi,
I am dealing with gotrust smart card where they provide their own pkcs11 headers and library (,so). I need to compile OpenSC with provided header files, how is that possible? I am struggling with it for a while and cannot find an easy way.

**Comment by frankmorgner** [comment]
PKCS\#11 has a standardized C interface. Hence the header files should be compatible. You should be able to load your custom PKCS#11 provider into OpenSC's pkcs11-tool without any modifications.

**Comment by MikaJustas** [comment]
I have contacted developers of the smart card and they came back to me with the following answer:
"""
The OpenSC project (a sub-project included in OpenVPN) uses a problematic PKCS#11 header file which contains the following two issues:
1)      According to following description from the PKCS#11 spec:
 
8.1 Structure packing
Cryptoki structures are packed to occupy as little space as is possible. In particular, on the Windows platforms, Cryptoki  structures should be packed with 1-byte alignment. In a UNIX environment, it may or may not be necessary (or even possible) to alter the bytealignment of structures.
 
PKCS#11 data structures should be compiled with 1-byte alignment. But OpenSC does not meet this requirement
 
2)      Some data types defined in the PKCS#11 header file of OpenSC are different from the ones defined in our SDK. For example, our SDK defines CK_ULONG as unit32_t which is a 32-bite integer, while OpenSC defines CK_ULONG asunsigned long int which is a 64-bit integer on Linux x64 platform.
"""

The offer by them was to compile OpenSC with their provided headers.

**Comment by CardContact** [comment]
OpenSC works with the majority of PKCS#11 aware applications (SunPKCS11, Firefox, Thunderbird, Adobe, LibreOffice, ssh-agent to name just a few) on all major platforms. So I would challenge the statement you received about OpenSC using wrong header.

Does their PKCS#11 module work with the above applications ?

And OpenSC is no sub-project of OpenVPN either.

**Comment by frankmorgner** [comment]
The data structures *are* 1 byte aligned on Windows, see https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11.h#L84

**Comment by frankmorgner** [comment]
`pkcs11_all.h` included in PKCS\#11 v2.30 *does contain*
```
 typedef unsigned long int CK_ULONG 
```
I guess you should have a deeper look on your SDK...

**Comment by dengert** [comment]
The responses on this list may have been a bit short. It sounds like the Gotrust has misinterperted the PKCS#11 specs.  

As pointed out above,  the PKCS#11 v2.30  uses  typedef unsigned long int CK_ULONG 
The  PKCS#11 v2.20  Section 5, Page 11, Says:

  Cryptoki is based on ANSI C types, and defines the following data types:

   /* an unsigned value, at least 32 bits long */
   typedef unsigned long int CK_ULONG;

   /* a signed value, the same size as a CK_ULONG */
   typedef long int CK_LONG;

   /* at least 32 bits; each bit is a Boolean flag */
   typedef CK_ULONG CK_FLAGS;

   It follows that many of the data and pointer types will vary somewhat from one
   environment to another (e.g., a CK_ULONG will sometimes be 32 bits, and sometimes
   perhaps 64 bits)

Note that the three all say "AT LEAST 32" bits, and even says they may be 64 bits.
So for interoperability the GoTrust code should not be using 
"CK_ULONG as unit32_t". 

The old 2.20 standards can be found at:
http://www.emc.com/emc-plus/rsa-labs/standards-initiatives/pkcs-11-cryptographic-token-interface-standard.htm

The pkcs11t.h uses the definitions in the poblished standards. 

The PKCS#11 v2.40 is at:
http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/cs01/pkcs11-base-v2.40-cs01.pdf

All of the PKCS#11 documents use 
    typedef unsigned long int CK_ULONG;


So for interoperability the GoTrust code should not be using 
"CK_ULONG as unit32_t", but do what everyone else has done and use unsigned long int.
Their code may interoperate on 32 bit systems but they will not on 64 bit.

Please pass on this reference to this OpenSC issue to the GoTrust developers, if they have any other issues.
