### ISSUE TITLE
OSX Yosemite: No smart card readers found.

### ISSUE THREAD

**Issue by rvalle** [OpenSC/OpenSC#518]
Hi!

I have now been running OSX Yosemite with OpenSC + epass2003 & epassPKI tokens for some time, and it all works.

However, once or twice a week, the system will stop recognizing them, and simply reply: No smart card readers found. to any SC commands.

I normally fix this by just rebooting my laptop, and all works again.

I guess some of the daemons required has crashed, or something similar.

Is anybody experiencing this? Is there a workaround to avoid having to restart the laptop?

I am also available to help tracking down this issue, as said, it happens more or less consistently.

R.

**Comment by LudovicRousseau** [comment]
Hello,

Open the Console application in ``/Applications/Utilities/``. If the driver crashed you should see a log line.
The crash log should be stored in ``/Library/Logs/CrashReporter/``

**Comment by rvalle** [comment]
I don't see any crash report,

And looking into system.log, I find a suspicious entry:

com.apple.ifdreader[191]: 00000197 ccid_usb.c:276:OpenUSBByName() USB driver with index 0 already in use

while trying to do pkcs15-tool -D and getting the No smart card readers found.

**Comment by LudovicRousseau** [comment]
I don't think it is an OpenSC issue. Something strange is happening to your reader.

Maybe "Debug a smart card reader driver on Yosemite" http://ludovicrousseau.blogspot.fr/2015/02/debug-smart-card-reader-driver-on.html and "Change syslog logging level on Yosemite" http://ludovicrousseau.blogspot.fr/2015/03/change-syslog-logging-level-on-yosemite.html can help generate more logs.

**Comment by rvalle** [comment]
I dont use any smartcard reader. I use USB tokens only. I understand the token includes a reader + smartcard.

However, when the error happens, re-inserting or re-placing the USB token by another does not help.

Will go through your recommendations anyway.

R.

**Comment by rvalle** [comment]
and, by the way, is there any daemon that can be re-started?

**Comment by rvalle** [comment]
now that I think about it, this is also happening in Linux, with Ubuntu. But then what I do is /etc/init.d/pcscd restart, and fixes things, after reinserting the token.

**Comment by LudovicRousseau** [comment]
It should be far easier to debug on GNU/Linux.
Follow http://pcsclite.alioth.debian.org/ccid.html#support to generate a pcscd trace.

**Comment by frankmorgner** [comment]
either way, it's not a bug in OpenSC...
