### ISSUE TITLE
CKR_SLOT_ID_INVALID Exception with java pkcs11

### ISSUE THREAD

**Issue by wtmann** [OpenSC/OpenSC#523]
I have an application that accesses the data on an Italian ID card which I wrote using version 0.13.0 of OpenSC. Since version 0.14.0 the application no longer works giving the following when trying to access the card:

Exception in thread "main" java.security.ProviderException: Initialization failed
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:376)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	at smartcardtest.SmartCardCIE.setProvider(SmartCardCIE.java:104)
	at smartcardtest.SmartCardTestCIE.main(SmartCardTestCIE.java:32)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SLOT_ID_INVALID
	at sun.security.pkcs11.wrapper.PKCS11.C_GetSlotInfo(Native Method)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:365)
	... 3 more

This is happening in my code where I'm setting the security provider:

        Provider p = new sun.security.pkcs11.SunPKCS11(configName);

where my config file contains:

name = myConfig
library = /usr/lib/opensc-pkcs11.so
slot = 1

Has something changed between version 0.13.0 and 0.14.0 that would be causing this. I also get the same error with version 0.15.0. Anyone have any ideas?

**Comment by frankmorgner** [comment]
Yes it has changed. A lot.

Please provide an opensc debug log of 0.15 and maybe 0.13

Am 13. August 2015 16:31:21 MESZ, schrieb wtmann <notifications@github.com>:

**Comment by wtmann** [comment]
Thanks. Here are the links for the logs:

V.0.13.0 - https://drive.google.com/file/d/0B_lWKDdIYuQTTEVJMGNKNXdYVTA/view?usp=sharing
V.0.15.0 - https://drive.google.com/file/d/0B_lWKDdIYuQTQ1FTYUVBQ1BJYkU/view?usp=sharing

Thanks again.

**Comment by dengert** [comment]
You have two issues #521 and #523 

Did you every get Java or some tool to sign anything with your card?
Do you have a debug trace of a signature that worked?

The opensc-0.13.0 log you sent in the zip file only looks for some objects, then ends. No sign operation. It is also looking for CKO_SECRET_KEY which is strange as these are symmetric key, not RSA. II would expect the caller be looking for CKO_PUBLIC_KEY and /or CKO_PRIVATE_KEY

Java makes calls to PKCS#11, which used to work, but don't with newer versions.
Using  pkcs11-spy with the old version and new version might show some attributes are being returned differently.  See:
 https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

Output of pkcs11-tool with the -O -l --pin xxxxxxx options would also help using. 

Can you try a simpler test where the parameters are under your control, something like:

 openssl sha1 -binary -out /tmp/test.hash < $SOME_FILE
 pkcs11-tool  -module $OPENSC_PATH/opensc-pkcs11.so -v -sign -m $MECH --id $KEYID -i  /tmp/test.hash -o /tmp/test.signature

Where:
 $SOME_FILE some file you want to sign
 $OPENSC_PATH/opensc-pkcs11.so   path to the opensc-pkcs11.so you want to test
 $MECH   =    RSA-PKCS  i.e. takes the hash, and has the lib and card pad and sign with RSA.
 $KEYID is the ID for the private key to use from the output of plcs11-tool -O -l

**Comment by dengert** [comment]
You may need to  export LD_LIBRARY_PATH environment variable before starting Java, or other test programs when doing development because opensc-pkcs11.so will dynamicly load libopensc.so.

**Comment by dengert** [comment]
And the output from OpenSC spy would be helpful to trace pkcs11 calls.

**Comment by wtmann** [comment]
I'm attaching the pkcs11-spy output for versions 0.13.0 and 0.15.0. In the 0.13.0 version there's also the signing of a document. The 0.15 version doesn't do much of a log as it hits this error right away. The links are:

0.13.0 - https://drive.google.com/file/d/0B_lWKDdIYuQTUWhlN0RmMHphYTA/view?usp=sharing
0.15.0 - https://drive.google.com/file/d/0B_lWKDdIYuQTU2J4cDRGWEJWV1E/view?usp=sharing

I was able to successfully sign a file from the command line as you specified. Furthermore the output from the pkcs11-tool -O command is:

Using slot 1 with a present token (0x1)
Logging in to "WILLIAM THOMAS MANN (PIN CNS0)".
Please enter User PIN: 
Private Key Object; RSA 
  label:      CNS0
  ID:         31
  Usage:      sign, non-repudiation, unwrap
Public Key Object; RSA 1024 bits
  label:      CNS0
  ID:         31
  Usage:      verify, wrap
Certificate Object, type = X.509 cert
  label:      CNS0
  ID:         31
Data object 13819152
  label:          'EF_DatiProcessore'
  application:    'EF_DatiProcessore'
  app_id:         <empty>
  flags:          <empty>

Data object 13819248
  label:          'EF_IDCarta'
  application:    'EF_IDCarta'
  app_id:         <empty>
  flags:          <empty>

Data object 13819344
  label:          'EF_DatiPersonali'
  application:    'EF_DatiPersonali'
  app_id:         <empty>
  flags:          <empty>

Data object 13817184
  label:          'EF_DatiPersonaliAggiuntivi'
  application:    'EF_DatiPersonaliAggiuntivi'
  app_id:         <empty>
  flags:          <empty>

Data object 13817280
  label:          'EF_MemoriaResidua'
  application:    'EF_MemoriaResidua'
  app_id:         <empty>
  flags:          <empty>

Data object 13817376
  label:          'EF_ServiziInstallati'
  application:    'EF_ServiziInstallati'
  app_id:         <empty>
  flags:          <empty>

Data object 13817472
  label:          'EF_INST_FILE'
  application:    'EF_INST_FILE'
  app_id:         <empty>
  flags:          <empty>

Data object 13817568
  label:          'EF_CardStatus'
  application:    'EF_CardStatus'
  app_id:         <empty>
  flags:          <empty>

Data object 13817664
  label:          'EF_GDO'
  application:    'EF_GDO'
  app_id:         <empty>
  flags:          <empty>

Data object 13817760
  label:          'EF_RootInstFile'
  application:    'EF_RootInstFile'
  app_id:         <empty>
  flags:          <empty>

Hopefully this'll give you some idea of what's happening.

**Comment by dengert** [comment]
Here is what might be happening with the GetSlotInfo:
Normally a caller will call C_GetSlotList to get the list of slots, requesting a list of all slots or only thoese that have tokens.

The netbeans does not do this, but justs calls C_getSlotInfo with a configured slot. 
It looks like in this situation, the OpenSC implentation returns CKR_SLOT_ID_INVALID

It is not clear if the PKCS#11 specs require C_getSlotList to be called before C_getSlotInfo.

@martinpaljak 
virtual_slots  where added in commit 0244baa494ecf80c0f3b2eb5bffc70f3f6511625
There could be some other change between 0.13.0 and 0.15.0 that caused the virtual_slots to not be set. If not set when C_getSlotInfo is called, maybe the virtual_slots could be initialized. 

An opensc-debug output from Java would show if this is the case. (None of the debug output files you sent appear to be from java. In the future, sending the command line, output of the command, spy and opensc-debug would help.) 

One way to find out, is to use  the Java slotListIndex = 1 
This would cause C_GetSlotList to be called by Java. OpenSC usually defined at least 2 slots,
one for hot-plug, and then one for the first reader.  So also try slotListIndex = 0 if =1 does not work.

http://docs.oracle.com/javase/7/docs/technotes/guides/security/p11guide.html#Config

The above leaves something to be desired in selecting a slot...

**Comment by wtmann** [comment]
Ok, using slotListIndex does indeed work! Thanks for the help! I do agree that maybe the slot list should be initialized if it isn't when a slot is asked for. This is an easy workaround though. Thanks again!

**Comment by dengert** [comment]
This is still an issue and should remain open or at least let other developers comment if OpenSC should be changed.

Early versions of PKCS#11 V.11 said:
  "Furthermore, the set of slots accessible through a Cryptoki library is fixed at the time that C_Initialize is called."
V2.20 says:
  "Furthermore, the set of slots accessible through a Cryptoki library is checked at the time that C_GetSlotList,
for list length prediction (NULL pSlotList argument) is called."
  "Even if C_GetSlotList is successfully called this way, it may or may not be the case that the changed slot list will be
   successfully recognized depending on the library implementation."

All versions says:
  "All slots which C_GetSlotList reports MUST be able to be queried as valid slots by C_GetSlotInfo."

It does not explicity say that the only slots that can be queried (or used)  must be in the slots which C_GetSlotList reports,
but in my option strongly implies it.

In the Java config file, if slot = X is used, no call to C_GetSlotList is ever made.
If slotListIndex = X is used. C_GetSlotList is called.

Note PKCS#11 says: "A priori, any value of CK_SLOT_ID can be a valid slot identifier."
This means that an implementation is not required to start numbering slots with 0 or 1, and need not be in sequence.

Java when used with slot = X is making a bad assumption, but there is a circumvention to use slotListIndex = X
which causes C_GetSlotList to be called so the index can be used to find the slot_id.




On 8/18/2015 4:20 PM, wtmann wrote:
> Closed #523 <https://github.com/OpenSC/OpenSC/issues/523>.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/523#event-385843822>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
Looking for comments from developers. Should OpenSC be changed to handle the case when 
the caller never calls C_GetSlotList, but assumes it knows the value of CK_SLOT_ID in 
other calls?

**Comment by martinpaljak** [comment]
IMHO: Java makes a known bad assumption (about slot index or ID or their sequence) thus I would not try too hard to fix it. But it is always nice to make things work, so it might make sense to have a "sloppy mode" where the slot list is initialized implicitly when getting slot info, even if not populated by an external call beforehand.

**Comment by frapontillo** [comment]
Just for reference @wtmann, what is the Italian ID provider whose card you're having issues with?

**Comment by wtmann** [comment]
It's an earlier version of the CIE (Electronic Identity Card)... Actually
though, this happens with all the cards I've tried using version 0.15.0;
this didn't happen with version 0.13.0 (I also tried 0.14.0 and it has the
same problem). So, as someone said, it could just be a Java thing...

On Tue, Aug 25, 2015 at 2:22 PM, Francesco Pontillo <
notifications@github.com> wrote:

> Just for reference @wtmann <https://github.com/wtmann>, what is the
> Italian ID provider whose card you're having issues with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/issues/523#issuecomment-134568662>.
>



-- 
William Mann

**Comment by FrankieA1960** [comment]
Use PDF Studio,

I love the product.  I had an issue with my CAC reader config.cfg file but after I deleted the "slot = 1" line it worked like a champ.  My file now looks like this:

name = SunPKCS11
library = /usr/lib64/libcackey.so

Great Product!!!

FrankieA

**Comment by Marikawn** [comment]
> Use PDF Studio,
> 
> I love the product. I had an issue with my CAC reader config.cfg file but after I deleted the "slot = 1" line it worked like a champ. My file now looks like this:
> 
> name = SunPKCS11 library = /usr/lib64/libcackey.so
> 
> Great Product!!!
> 
> Can be found at: PDF Studio page: https://www.qoppa.com/pdfstudio/
> 
> FrankieA

Frankie,

I appreciate your comment. I'm too am using PDF Studio and was able to get my CAC working thanks to your comment.

name = SCR33XXSmartCardReader
library = /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so

Jimmy
