### ISSUE TITLE
[Feature Request] Chrome OS port of OpenSC

### ISSUE THREAD

**Issue by dskaram** [OpenSC/OpenSC#527]
Chrome OS will be adding support for PCSC. Having OpenSC ported in a Chrome extension on top of this new support would allow users with Chromebooks access to their smartcards.

The process does not require any new code, but simply taking the existing code and compiling it within Chrome's Native Client.

https://code.google.com/p/chromium/issues/detail?id=220971

**Comment by dengert** [comment]
Dually noted, and I also comments on the Chromium issue, just now.
It addreses both the PIV/CAC issues as well an many other smart cards,
including European ID cards, and cards like the Yubico Neo.


What do we need to test OpenSC on Chromium?

On 8/21/2015 9:35 AM, dskaram wrote:
> Chrome OS will be adding support for PCSC. Having OpenSC ported in a Chrome extension on top of this new support would allow users with Chromebooks access to their smartcards.
>
> The process does not require any new code, but simply taking the existing code and compiling it within Chrome's Native Client.
>
> https://code.google.com/p/chromium/issues/detail?id=220971
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/527>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
Some grunge work seems to have been done here https://github.com/open-eid/chrome-token-signing.

You could try changing the underlying PKCS\#11 library of the chrome-token-signing extension to OpenSC...

**Comment by dskaram** [comment]
Great to have you involved!.

What is required for OpenSC to work in chrome basically is compiling it on
top of the PCSC implementation provided by Google within the Chrome Native
Client.

I can provide details in depth in written form or we can also set up a
video call and we can go over the details of what it would entail. Please
let me know what would work best for you.

**Comment by dengert** [comment]
What I have been doing is looking at
https://www.chromium.org/chromium-os/developer-guide

 From your comment below, is this over kill?
Should I be starting with the Chrome Native Client?


On 8/22/2015 2:55 AM, dskaram wrote:
> Great to have you involved!.
>
> What is required for OpenSC to work in chrome basically is compiling it on
> top of the PCSC implementation provided by Google within the Chrome Native
> Client.
>
> I can provide details in depth in written form or we can also set up a
> video call and we can go over the details of what it would entail. Please
> let me know what would work best for you.
> On Aug 22, 2015 12:19 AM, "Frank Morgner" <notifications@github.com> wrote:
>
>  > Some grunge work seems to have been done here
>  > https://github.com/open-eid/chrome-token-signing.
>  >
>  > You could try changing the underlying PKCS#11 library of the
>  > chrome-token-signing extension to OpenSC...
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/OpenSC/OpenSC/issues/527#issuecomment-133578485>.
>  >
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/527#issuecomment-133649637>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dskaram** [comment]
Yes. OpenSC driver should be packaged as a Chrome extension. Extensions
which need to compile native code need to be compiled with Native Client.

I am travelling this weekend but I can reply with more details on Monday.
Also if you have some time we can talk over Hangout video so I can give you
a better idea of all the details.

Appreciate your interest in this. This has been a much coveted feature in
ChromeOS for some time. Glad we finally got around to putting out there for
the community to develop around and use.

**Comment by frankmorgner** [comment]
pepper_45 does not include PC/SC. @dskaram what's the timeline?

Currently OpenSC loads the PC/SC library at runtime as shared library. https://developer.chrome.com/native-client/nacl-and-pnacl#when-to-use-nacl explains that loading dynamic libraries with pnacl is planned, do you know when this will be available?

I am not sure if NaCl (with support for dynamic loading of libraries) is what we want since it can only be distributed through the Chrome Web Store...

**Comment by dskaram** [comment]
We did not add pcsc into pepper but rather ported pcsc-lite into a chrome
extension using chrome.usb. Communication with this extension would happen
over cross-extension messaging. For native ports we will provide a C
wrapper that would hide these implementation details away.

Re timeline, we have a functional JS implementatoon and next week we should
have the C wrapper. We can sit down a and talk about the best way to load
this into OpenSC.

Regarding the web store, what would be the reservation there? Is the
license restrictive of distribution over a closed source channel? The port
can be open sourced and linked to from the extension. Happy to discuss
further details on this one.

If you guys provide me with email addresses I can start by sending you all
relevant details plus an example implantation of the JS API. C wrapper
still to come next week. I have Douglas' address but I guess should also
include Frank. Let me know if anyone else would like to be on that thread.

Looking forward to your response.

**Comment by martinpaljak** [comment]
Well, from the latest news of the week:
 - Mozilla adopts Chrome Extensions (thus chrome-token-signing might get an overhaul)
 - PCSC (as a PC/SC+CCID hybrid on top of chrome.usb?) developments

The questions still remains that what is the *meaningful* and manageable API for developers. PKCS#11 it is not, everything else (like WebCryptoAPI) are going nowhere because of "lets expose USB and sandboxing, instead" things. But please keep me posted.

**Comment by frankmorgner** [comment]
@dskaram the web store itself is OK (even with a proprietary implementation ;-) ), at least for me (OpenSC is licensed with LGPL, by the way). However, I fear that with the constant lack of time by OpenSC's developers will get even worse when an additional administrative layer is added by building/publishing for the store.

Also, as developer, I like to not being bound to a third party when installing my extensions. But I guess there is some configuration flag that can be set for a local installation of OpenSC that does not require authorization by the web store.

**Comment by martinpaljak** [comment]
@frankmorgner well, the walled garden silos of app stores are apparently not going away (RMS could probably lecture for a while why this is bad for free software) but IMHO it makes sense to make the software available via as many and as "native to the platform" channels as possible.

But if and how the Chrome OS interface stack is supposed to be integrated by developers or used by end users in a meaningful way is a different question.

**Comment by frankmorgner** [comment]
We'd be happy to integrate this, but nobody from the OpenSC team is working on this

**Comment by frankmorgner** [comment]
FYI, there is a Chrome OS extension for the CAC/PIV token. The interesting part is that the implementation internally [maps PKCS#11 to ChromeOS's certificate provider API](https://cackey.rkeene.org/fossil/dir?name=build/chrome). So in theory, this could be used for mapping OpenSC's PKCS#11 interface as well. However, the License of CACKey is unclear to me.

**Comment by dengert** [comment]
Interesting. If they can do the mapping, so  could OpenSC could do it.  
I don't see any license or copyrights either. 

Just to note, Not all CAC cards are PIV, and not all PIV cards are CAC. They are/where set to merge, but have some special features for each. It looks like it is really designed for the CAC. 

This implementation for PIV only supports the 4 PIV certs/keys and not the retired key or history object or  that allows access to the retired keys. 

It only supports RSA, but does refer to some EC key attributes. Maybe in future version.
