### ISSUE TITLE
Add --raw option to pkcs15-tool

### ISSUE THREAD

**Issue by nioncode** [OpenSC/OpenSC#535]
It would be great if there was a '--raw' option in pkcs15-tool to get the 8bit raw data when using "pkcs15-tool -R 'data' --pin PIN" on stdout. pkcs15-crypt has this option already.

Currently, we have to write the data to an output file first and then read it in again.
This is rather inconvenient and also less secure if the file gets written to persistent storage where it can't be easily and securely deleted.

**Comment by frankmorgner** [comment]
I'd be happy to review your pull request... ;-)

**Comment by nioncode** [comment]
I just implemented it and created the pull request.

**Comment by nioncode** [comment]
Closed with #540.
