### ISSUE TITLE
Faster release cycles

### ISSUE THREAD

**Issue by nioncode** [OpenSC/OpenSC#544]
Is there a chance we can get more frequent official releases? From 0.14 to 0.15 it took almost 11 months.
It would be great if we could get this down to one or two months, at most, to integrate new features faster.

**Comment by frankmorgner** [comment]
Well, this *is* on my wishlist, too. However, it requires a lot of work which a single person can't do. If you want to help speed up the release cycles, you may want to help resolving https://github.com/OpenSC/OpenSC/issues and https://github.com/OpenSC/OpenSC/pulls.

**Comment by frankmorgner** [comment]
You may use the nightly build available here http://sourceforge.net/projects/opensc/files/OpenSC/nightly/
