### ISSUE TITLE
Don't convert IOCTL to host byte order?

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#548]
PC/SC pt. 10 v2.02.06, section 2.2 says the following about `GET_FEATURE_REQUEST`:

> The driver shall return SCARD_SUCCESS and a TLV oriented structure as follows: Tag, Length (always 4 bytes), control code value for supported feature The control code is returned in big endian format and must be used for the Control function of the Resource Manager in unmodified form.

But we are converting the IOCTLs to the host byte order, see for example https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L942. @LudovicRousseau Is this an error in OpenSC?

**Comment by dengert** [comment]
Read Ludovic's comments on PC/SC part 10 and endian of machine in this message and thread:

   https://www.mail-archive.com/opensc-devel@lists.opensc-project.org/msg06285.html

I don't thing the line is as error, as long as it is converted when needed.
Do you see a problem?


On 9/10/2015 1:16 AM, Frank Morgner wrote:
> PC/SC pt. 10 v2.02.06, section 2.2 says the following about |GET_FEATURE_REQUEST|:
>
>     The driver shall return SCARD_SUCCESS and a TLV oriented structure as follows: Tag, Length (always 4 bytes), control code value for supported feature The control code is returned in big endian
>     format and must be used for the Control function of the Resource Manager in unmodified form.
>
> But we are converting the IOCTLs to the host byte order, see for example https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L942. @LudovicRousseau
> <https://github.com/LudovicRousseau> Is this an error in OpenSC?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/548>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
The mail is talking about PIN_VERIFY, not about GET_FEATURE_REQUEST. So my question is not answered yet.

The conversion of the IOCTL is *always* done (not only when needed, see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L956). Obviously this is not an error since OpenSC seems to work everywhere the way it is implemented. I am asking to find out if this conversion (and the inclusion of ws2_32) is superfluous or not.

**Comment by dengert** [comment]
The point was the comments on the PCSC working group making many changes without public review,
and that endian issues have come up before.

On 9/11/2015 8:08 AM, Frank Morgner wrote:
> The mail is talking about PIN_VERIFY, not about GET_FEATURE_REQUEST. So my question is not answered yet.
>
> The conversion of the IOCTL is /always/ done (not only when needed, see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L956). Obviously this is not an error since OpenSC
> seems to work everywhere the way it is implemented. I am asking to find out if this conversion (and the inclusion of ws2_32) is superfluous or not.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/548#issuecomment-139541106>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by LudovicRousseau** [comment]
OpenSC use ``ntohl()`` to convert from network order (big endian) to host order so that OpenSC can use the value directly. Why do you think this is a bug?

Note that the CCID driver uses ``htonl()`` to generate this value
https://github.com/LudovicRousseau/CCID/blob/master/src/ifdhandler.c#L1445

**Comment by frankmorgner** [comment]
I thought that using the "unmodified form" meant using the value as given from the driver to OpenSC (with htonl appliet). But reading your code it's clear that it actually means without ntohl appliet.
