### ISSUE TITLE
OpenSC Win32 eidenv

### ISSUE THREAD

**Issue by donalej** [OpenSC/OpenSC#562]
Hello Martin!

I'm new in Github.

I'd like some informations about OpenSC/Win32, and specifically about the Eidenv tool (for Belgium Cards).

It would seem missing for Windows.

First, is this correct? If that tool exists, where can I find it?

Do you know if this is going to be developed and when?

Thanking you in advance

**Comment by frankmorgner** [comment]
The tool was missing in the installer, this was fixed in 8aba7b9598395c97091f70cf82076a99cce43b3f. You can download a nightly build of OpenSC or build it yourself if you need the tool right now.
