### ISSUE TITLE
OpenSC don't recognise my SC reader

### ISSUE THREAD

**Issue by szymex73** [OpenSC/OpenSC#568]
I have HP Compaq nc6400 with built-in SmartCard reader on it, the lspci program recognises it and says:
02:06.4 Communication controller: Texas Instruments PCIxx12 GemCore based SmartCard controller
        Subsystem: Hewlett-Packard Company Device 30ad
        Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Interrupt: pin A routed to IRQ 11
        Region 0: Memory at f4203000 (32-bit, non-prefetchable) [size=4K]
        Region 1: Memory at f4204000 (32-bit, non-prefetchable) [size=4K]
        Capabilities: [44] Power Management version 2
                Flags: PMEClk- DSI- D1+ D2+ AuxCurrent=0mA PME(D0+,D1+,D2+,D3hot+,D3cold-)
                Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-

OpenSC and pcsc_scan don't see it. What should i do?

**Comment by LudovicRousseau** [comment]
I don't know a driver for a PCI smart card reader.
Can you also see the reader on the USB bus, using lsusb?

**Comment by szymex73** [comment]
No, i don't see it

**Comment by frankmorgner** [comment]
Please use google or the vendor's page to download and install the driver for your reader http://bfy.tw/25fR
