### ISSUE TITLE
Add two ATRs for CAC and NEO tokens please

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#578]
Could you please add the following entries to _opensc.conf_:

```
        # US DoD CAC/PIV card (Oberthur)
        card_atr 3b:db:96:00:80:1f:03:00:31:c0:64:b0:f3:10:00:07:90:00:80 {
                name = "Oberthur CAC PIV-II";
                driver = "piv";
        }

        # Yubico Yubikey NEO OTP+U2F+CCID
        card_atr 3b:fc:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:4e:45:4f:72:33:e1 {
                name = "Yubikey NEO PIV Applet";
                driver = "piv";
                pkcs11_enable_InitToken = yes;
                #force_protocol = t1;
        }
```

**Comment by dengert** [comment]
No, The PIV does not need the ATRs listed on opensc.conf

Why do you think they are needed?

On 10/14/2015 1:25 PM, Mouse wrote:
> Could you please add the following entries to /opensc.conf/:
>
> |# US DoD CAC/PIV card (Oberthur) card_atr 3b:db:96:00:80:1f:03:00:31:c0:64:b0:f3:10:00:07:90:00:80 { name = "Oberthur CAC PIV-II"; driver = "piv"; } # Yubico Yubikey NEO OTP+U2F+CCID card_atr
> 3b:fc:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:4e:45:4f:72:33:e1 { name = "Yubikey NEO PIV Applet"; driver = "piv"; pkcs11_enable_InitToken = yes; #force_protocol = t1; } |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/578>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
Possibly my ignorance... I thought that if I need a specific driver with specific parameters for a given card, the simplest way is to add those to opensc.conf.

Also, since CAC is sorta both CAC and PIV...?

But I defer to you here. If you say it is not needed, OK then.

**Comment by dengert** [comment]
It did at one time, and many card drivers only look at the ATR. But over the years
its not the card, but the application on the card that is important.  the AID
can be used to find if an application is on a card and set the card to respond
for the selected AID.

The issue of the PIV driver not working correctly with the CAC + PIV card was
the default application was CAC and the card-piv.c not telling the card to select the
PIV application. So card responded as a CAC, which has some differences.

I only have PIV cards, no CAC cards for testing.



On 10/14/2015 4:46 PM, Mouse wrote:
> Possibly my ignorance... I thought that if I need a specific driver with specific parameters for a given card, the simplest way is to add those to opensc.conf.
>
> Also, since CAC is sorta both CAC and PIV...?
>
> But I defer to you here. If you say it is not needed, OK then.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/578#issuecomment-148211744>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> I only have PIV cards, no CAC cards for testing.

I'd be happy to do any testing you suggest, as I have both.

**Comment by frankmorgner** [comment]
closing this with @dengert's remarks
