### ISSUE TITLE
verify_certificate() failed: certificate is invalid

### ISSUE THREAD

**Issue by r3pek** [OpenSC/OpenSC#589]
the error is because it can't find the local issuer certificate. "unable to get local issuer certificate".
DEBUG:pkcs11_lib.c:1383: login as user CKU_USER
DEBUG:pkcs11_lib.c:1577: Saving Certificate #1:
DEBUG:pkcs11_lib.c:1579: - type: 00
DEBUG:pkcs11_lib.c:1580: - id:   45
DEBUG:pkcs11_lib.c:1577: Saving Certificate #2:
DEBUG:pkcs11_lib.c:1579: - type: 00
DEBUG:pkcs11_lib.c:1580: - id:   52
DEBUG:pkcs11_lib.c:1612: Found 2 certificates in token
DEBUG:mapper_mgr.c:172: Retrieveing mapper module list
DEBUG:mapper_mgr.c:73: Loading static module for mapper 'pwent'
DEBUG:mapper_mgr.c:196: Inserting mapper [pwent] into list
DEBUG:pkcs11_inspect.c:126: Found '2' certificate(s)
DEBUG:pkcs11_inspect.c:130: verifying the certificate #1
DEBUG:cert_vfy.c:338: Adding hashdir lookup to x509_store
DEBUG:cert_vfy.c:350: Adding hash dir '/etc/pam_pkcs11/cacerts' to CACERT checks
DEBUG:pkcs11_lib.c:1443: logout user
DEBUG:pkcs11_lib.c:1450: closing the PKCS #11 session
DEBUG:pkcs11_lib.c:1456: releasing keys and certificates
DEBUG:mapper_mgr.c:213: unloading mapper module list
DEBUG:mapper_mgr.c:137: calling mapper_module_end() pwent
DEBUG:mapper_mgr.c:148: Module pwent is static: don't remove
ERROR:pkcs11_inspect.c:137: verify_certificate() failed: certificate is invalid: unable to get local issuer certificate

Thing is that the CA cert is in place and validating the certificate using openssl works without a problem.
$ pkcs15-tool -r 45 | openssl verify -CApath /etc/pam_pkcs11/cacerts/
Using reader with a card: Alcor Micro AU9540 00 00
stdin: OK

Same with pkcs11-tool:
$ pkcs11-tool -r -d 45 --type cert | openssl x509 -inform DER | openssl verify -CApath /etc/pam_pkcs11/cacerts/
Using slot 1 with a present token (0x1)
stdin: OK

**Comment by dengert** [comment]
Does the path name need a trailing "/" ?


On 10/21/2015 4:39 PM, Carlos Silva wrote:
> the error is because it can't find the local issuer certificate. "unable to get local issuer certificate".
> DEBUG:pkcs11_lib.c:1383: login as user CKU_USER
> DEBUG:pkcs11_lib.c:1577: Saving Certificate #1 <https://github.com/OpenSC/OpenSC/pull/1>:
> DEBUG:pkcs11_lib.c:1579: - type: 00
> DEBUG:pkcs11_lib.c:1580: - id: 45
> DEBUG:pkcs11_lib.c:1577: Saving Certificate #2 <https://github.com/OpenSC/OpenSC/pull/2>:
> DEBUG:pkcs11_lib.c:1579: - type: 00
> DEBUG:pkcs11_lib.c:1580: - id: 52
> DEBUG:pkcs11_lib.c:1612: Found 2 certificates in token
> DEBUG:mapper_mgr.c:172: Retrieveing mapper module list
> DEBUG:mapper_mgr.c:73: Loading static module for mapper 'pwent'
> DEBUG:mapper_mgr.c:196: Inserting mapper [pwent] into list
> DEBUG:pkcs11_inspect.c:126: Found '2' certificate(s)
> DEBUG:pkcs11_inspect.c:130: verifying the certificate #1 <https://github.com/OpenSC/OpenSC/pull/1>
> DEBUG:cert_vfy.c:338: Adding hashdir lookup to x509_store
> DEBUG:cert_vfy.c:350: Adding hash dir '/etc/pam_pkcs11/cacerts' to CACERT checks
> DEBUG:pkcs11_lib.c:1443: logout user
> DEBUG:pkcs11_lib.c:1450: closing the PKCS #11 <https://github.com/OpenSC/OpenSC/pull/11> session
> DEBUG:pkcs11_lib.c:1456: releasing keys and certificates
> DEBUG:mapper_mgr.c:213: unloading mapper module list
> DEBUG:mapper_mgr.c:137: calling mapper_module_end() pwent
> DEBUG:mapper_mgr.c:148: Module pwent is static: don't remove
> ERROR:pkcs11_inspect.c:137: verify_certificate() failed: certificate is invalid: unable to get local issuer certificate
>
> Thing is that the CA cert is in place and validating the certificate using openssl works without a problem.
> $ pkcs15-tool -r 45 | openssl verify -CApath /etc/pam_pkcs11/cacerts/
> Using reader with a card: Alcor Micro AU9540 00 00
> stdin: OK
>
> Same with pkcs11-tool:
> $ pkcs11-tool -r -d 45 --type cert | openssl x509 -inform DER | openssl verify -CApath /etc/pam_pkcs11/cacerts/
> Using slot 1 with a present token (0x1)
> stdin: OK
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/589>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by r3pek** [comment]
nah, don't think so. I did an strace on the program and it even opens the correct certificate.
write(1, "\33[34mDEBUG:cert_vfy.c:350: Addin"..., 91DEBUG:cert_vfy.c:350: Adding hash dir '/etc/pam_pkcs11/cacerts/' to CACERT checks
) = 91
stat("/etc/pam_pkcs11/cacerts/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/etc/pam_pkcs11/crls", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/etc/pam_pkcs11/cacerts/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/etc/pam_pkcs11/cacerts//2f45b672.0", {st_mode=S_IFREG|0644, st_size=1803, ...}) = 0
open("/etc/pam_pkcs11/cacerts//2f45b672.0", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=1803, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8094c04000
read(4, "0\202\7\0070\202\4\357\240\3\2\1\2\2\10\r\247T\353c3\247\3340\r\6\t*\206H\206\367"..., 4096) = 1803
read(4, "", 4096)                       = 0
read(4, "", 4096)                       = 0
close(4)                                = 0
munmap(0x7f8094c04000, 4096)            = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[34mDEBUG:pkcs11_lib.c:1443: lo"..., 46DEBUG:pkcs11_lib.c:1443: logout user

**Comment by r3pek** [comment]
I'm gonna close this issue. My bad for missing the damn root certificate on the directory. Stil, it worked with openssl for whatever reason. anyway, it's working now, thx anyway.
