### ISSUE TITLE
Next Nightly build

### ISSUE THREAD

**Issue by donalej** [OpenSC/OpenSC#595]
Hello,

I would like to know when will the next nightly build for Win64?

Thanks

**Comment by frankmorgner** [comment]
there are build artifacts available here https://ci.appveyor.com/project/LudovicRousseau/opensc

**Comment by frankmorgner** [comment]
we will only provide official binaries for releases

**Comment by CardContact** [comment]
I've updated the wiki frontpage with the link to appveyor.

What about the old nightly builds on sourceforge ? Do we remove them ?

Do we still need references to versions before 0.14 ?

Is it correct, that we don't have nightly tarballs anymore (Can be created with github anyway) ?

**Comment by vletoux** [comment]
The Appveyor link https://ci.appveyor.com/project/LudovicRousseau/opensc/ is inaccurate because it includes also PR.
The correct link is: https://ci.appveyor.com/project/LudovicRousseau/opensc/branch/master

**Comment by frankmorgner** [comment]
@viktorTarasov how do you proceed with your jenkins? If I understood correctly you are not so tightly involved anymore, so I assume it is better to remove the integration with your boxes (i.e. stop upload of nightlies, stop building with github hook, remove the references from the wiki)!?

@CardContact links to the old releases and their binaries should stay where they are. The new home is github, so any new release should be done here. @viktorTarasov or @LudovicRousseau , could you please activate the automatic import of github releases for SourceForge (this way SourceForge essentially only acts as a mirror without our manual interference)?

**Comment by CardContact** [comment]
Fine with me.

Do we know who maintains packages for the various distributions ?

We've received feedback that certain Ubuntu builds are done without OpenSSL, so some of the features are disabled.

**Comment by LudovicRousseau** [comment]
@frankmorgner I added a web-hook in the github project as documented in https://sourceforge.net/p/forge/documentation/GitHub%20Importer/#releases

The next OpenSC github release should be automatically available on https://sourceforge.net/projects/opensc/files/ but I don't know in what subdirectory the release will be present. We will see.

**Comment by viktorTarasov** [comment]
@frankmorgner 
agree to remove from wiki the references to the non-public services

I will stop the upload of the nightly builts and
propose to remove the 'nightly' folder from sourceforge.

**Comment by frankmorgner** [comment]
@LudovicRousseau you can see the result of a different here http://sourceforge.net/projects/vsmartcard/files/. On 2015-12-27 I imported existing releases to sourceforge and created the webhook. On 2016-01-05 I created a new release which got imported via the webhook.

**Comment by frankmorgner** [comment]
I agree with @viktorTarasov

**Comment by viktorTarasov** [comment]
> propose to remove the 'nightly' folder from sourceforge.

as well as folders with the not-majors releases

**Comment by frankmorgner** [comment]
@viktorTarasov what's the current status, do you need any help?

**Comment by viktorTarasov** [comment]
- no more GitHub _webhook_ to opensc.fr/jenkins;
- _Files_ on sourceforge contain only released tarball and windows binaries.

**Comment by frankmorgner** [comment]
@viktorTarasov by the way, for the next release we should use the *draft a release* feature of github. This allows collecting all binaries (windows, mac, autoconf source) before publishing everything. This will allow sourceforge to import everything.
