### ISSUE TITLE
engine_pkcs11 reports outdated libp11

### ISSUE THREAD

**Issue by ce77** [OpenSC/OpenSC#598]
Hi,

I have a strange problem configuring engine_pkcs11. After I downloaded and installed the latest lib11 from your github repository (https://github.com/OpenSC):
-rwxr-xr-x. 1 admin preprod 216783 Oct 30 23:34 libp11.so.2.2.0

$ export LDFLAGS=-L/usr/local/lib
$ export LIBP11_LIBS=/usr/local/lib
$ ./configure
:
checking for utmp.h... yes
checking for P11KIT... no
checking for LIBP11... no
configure: error: libp11 >= 0.2.5 is required

Now, the funny thing is, I did not find a newer version than the one version 2.2 you provided. Did I do something wrong, miss a patch, link or so?

Many thanks in advance & best regards,
Christian

Some information:
Reader and Card work fine with gnuTLS i.e, configuration, linking, compiling etc works with many other packages, I frankly have no clue what you'd really need here, pls let me know.
From libp11 config.h:
/* Version number of package */
#define VERSION "0.3.0_git"
Also: GNU Autoconf 2.69, uname -r 3.10.0-229.14.1.el7.x86_64,
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)

$ opensc-tool -l
# Detected readers (pcsc)
Nr. Card Features Name
0 Yes ACS ACR38U-CCID 00 00
$ p11-kit list-modules
p11-kit-trust: p11-kit-trust.so
library-description: PKCS#11 Kit Trust Module
library-manufacturer: PKCS#11 Kit
library-version: 0.20
token: System Trust
manufacturer: PKCS#11 Kit
model: p11-kit-trust
serial-number: 1
hardware-version: 0.20
flags:
write-protected
token-initialized
token: Default Trust
manufacturer: PKCS#11 Kit
model: p11-kit-trust
serial-number: 1
hardware-version: 0.20
flags:
write-protected
token-initialized
gnome-keyring: gnome-keyring-pkcs11.so
library-description: GNOME Keyring Daemon Core
library-manufacturer: GNOME Keyring
library-version: 1.1
token: SSH Keys
manufacturer: Gnome Keyring
model: 1.0
serial-number: 1:SSH:HOME
flags:
write-protected
user-pin-initialized
protected-authentication-path
token-initialized
token: Secret Store
manufacturer: Gnome Keyring
model: 1.0
serial-number: 1:SECRET:MAIN
flags:
login-required
user-pin-initialized
protected-authentication-path
token-initialized
token: Gnome2 Key Storage
manufacturer: Gnome Keyring
model: 1.0
serial-number: 1:USER:DEFAULT
flags:
login-required
user-pin-initialized
protected-authentication-path
token-initialized
token: User Key Storage
manufacturer: Gnome Keyring
model: 1.0
serial-number: 1:XDG:DEFAULT
flags:
protected-authentication-path
token-initialized
gnutls: /usr/lib64/opensc-pkcs11.so
library-description: Smart card PKCS#11 API
library-manufacturer: OpenSC (www.opensc-project.org)
library-version: 0.0
token: SmartCard-HSM (UserPIN)
manufacturer: www.CardContact.de
model: PKCS#15 emulated
serial-number: DECM010***1
hardware-version: 24.13
firmware-version: 1.2
flags:
rng
login-required
user-pin-initialized
token-initialized
$ pkcs15-tool -D
PKCS#15 Card [SmartCard-HSM]:
Version : 0
Serial number : DECM010***1
Manufacturer ID: www.CardContact.de

**Comment by LudovicRousseau** [comment]
Bugs regarding engine_pkcs11 should be reported to the engine_pkcs11 project at https://github.com/OpenSC/engine_pkcs11/issues

2.2.0 in `libp11.so.2.2.0` is NOT the release version. It is the ABI version.
The latest version is 0.3.0 available at https://github.com/OpenSC/libp11/releases

**Comment by ce77** [comment]
Ludovic, thanks. That however did not change anything:
tar xzvf libp11-0.3.0.tar.gz
cd libp11-0.3.0
./configure; make; make install
--- results in  /usr/local/lib/libp11.so.2.2.0 again ---
tar xzvf engine_pkcs11-0.2.0.tar.gz
cd engine_pkcs11-0.2.0 
export LDFLAGS=-L/usr/local/lib; export LIBP11_LIBS=/usr/local/lib
./configure
  ...
checking for utmp.h... yes
checking for P11KIT... no
checking for LIBP11... no
configure: error: libp11 >= 0.2.5 is required
Regards,
Christian
PS: Shall I answer in https://github.com/OpenSC/engine_pkcs11/issues as well or exclusively?

**Comment by ce77** [comment]
got it solved by correcting PKG_CONFIG_PATH ... sorry & thanks!
Christian
