### ISSUE TITLE
old package versions ?

### ISSUE THREAD

**Issue by jdbirdwell** [OpenSC/OpenSC#603]
This is part request and part question.  The current versions for opensc packages for various OSs are:

Ubuntu: 0.14.0-1ubuntu1
Fedora: 0.15.0
RHEL 7: 0.12.2
CentOS: 0.13.0
Debian: 0.14.0-2

Does 0.15.0 not function correctly on any of these, and if it does, can the packages be updated?

Thanks,
Doug

**Comment by LudovicRousseau** [comment]
Debian has OpenSC version 0.15.0 in its testing and unstable distributions. Only Debian stable provides 0.14.0
https://packages.debian.org/search?keywords=opensc

Ubuntu has version 0.15.0 in wily (15.10) and xenial (16.04) http://packages.ubuntu.com/search?keywords=opensc

Each distribution has its own rules and stable versions.
This is not a situation the OpenSC can change.

**Comment by frankmorgner** [comment]
Todays releases can be found here https://github.com/OpenSC/OpenSC/releases

older releases can still be found here http://sourceforge.net/projects/opensc/files/

**Comment by frankmorgner** [comment]
The OpenSC team did not officially release binaries for the systems you requested
