### ISSUE TITLE
How to write CA certificate to SC-HSM smart card with opensc-tool ?

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#619]
Bonjour Users,

I am trying to import CA certificate in SmartCard-HSM throught pkcs11-tool command. 

pkcs11-tool --module /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so -l --pin xxxxxxxxxxxxxxxx --write-object cacert.der --type cert --id 11

It is imported but not marked as Certificate Authority certificate
When i get the dump through pkcs15-tool -D command, it shows the following output.

X.509 Certificate [Certificate]
        Object Flags   : [0x2], modifiable
        Authority      : no    
        Path           : e82b0601040181c31f0201::ca00
        ID             : 11
        Encoded serial : 02 01 01
        
I want to set the Authority to yes. Please guide me.

**Comment by frankmorgner** [comment]
@CardContact ?

**Comment by CardContact** [comment]
The authority attribute can not be set using PKCS#11. You must use pkcs15-init instead:

pkcs15-init --verify-pin --store-certificate cert.pem --authority

**Comment by scottthomas007** [comment]
Thanks for such quick reply. It worked :)
