### ISSUE TITLE
Issue while Import P12 file in CardContact SmartCard-HSM

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#620]
Bonjour Users,

I created the P12 file to combine my key and cert to store in CardContact SmartCard.
openssl pkcs12 -export -out device.p12 -inkey device.key -in device.crt -certfile cacert.crt

I am trying to import this p12 file in CardContact SmartCard by the following command.

pkcs15-init -S device.p12 -f PKCS12 --auth-id 10 --passphrase xxxxxxxxxxx --pin xxxxxxxx

But its generating the error

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-init -S server.p12 -f PKCS12 --auth-id 10 --passphrase xxxxxxxxxxxxxxxx--pin xxxxxxxxx -v
Using reader with a card: Gemplus USB Smart Card Reader 0
Connecting to card in reader Gemplus USB Smart Card Reader 0...
Using card driver SmartCard-HSM.
Found SmartCard-HSM
About to store private key.
Importing 1 certificates:
  0: /CN=xxxxxxxxxxxxxxxx/OU=xxxxxxxxxxxxxxxxxxxxx
Failed to store private key: Not supported

Please help me to store my externally genrated P12 file.

**Comment by frankmorgner** [comment]
see #621

**Comment by scottthomas007** [comment]
I have to use this SC to import CA key and store user public/private keys. Leaving the import tool, how can i import the P12 file in SC-HSM smart card via some API or command ?

**Comment by CardContact** [comment]
There is no command in OpenSC to import a PKCS#12 container into a SmartCard-HSM directly. You have to use the import_P12.js script from the SDK to do that (https://devnet.cardcontact.de/attachments/download/45/sc-hsm-workspace-20151114.zip).

As said in the other post, the import_P12.js tool first converts the key into the wrapped key format with a random DKEK and then imports that wrapped key into the device. Please make sure you have the unrestricted cryptographic policy installed for your JVM, because the wrapped key is encrypted using AES-256.

**Comment by scottthomas007** [comment]
OpenSC has pkcs15-tool that can import P12 file into smart card and it works succesfully on Cryptoflex and Oberthur cards. I have tested it many times with this command and it works ultimately fine.
pkcs15-init -S file.p12 -f PKCS12 --auth-id 10 --passphrase XXXXXXXXXXXX--pin XXXXXXXXXX

But SC-HSM smart card doesn't work with pkcs15-tool import function.
I want to integrate this import functionality in my development application but i am stuck on it.

**Comment by scottthomas007** [comment]
The above attachment link is giving SSL Error on Chrome, FF & IE. Not accessible

**Comment by CardContact** [comment]
Just because other cards support importing private keys in plain doesn't mean that this is the right way of doing it. For the SmartCard-HSM we are not supporting plain import for security reasons (see #621). Of course we acknowledge that this may be somewhat inconvenient. Security is sometimes not convenient.

As for the link, you need to activate your CDN account first (http://www.cardcontact.de/cdn/activation.html) to get access to additional documentation and software.

**Comment by scottthomas007** [comment]
I have to use this SC to import CA key and store user public/private keys. Leaving the import tool, how can i import the P12 file in SC-HSM smart card via some API or command ?

**Comment by scottthomas007** [comment]
SmartCard-HSM is a good smart card and it must have support an API to import P12 to provide backward compatibility scenarios of key import.

**Comment by CardContact** [comment]
For existing CA keys you might need to use the import_P12.js in a dedicated key management procedure, but for user cards you should have the keys generated on the card and - if it is required for key escrow - extract a key backup for the key. That way you can split management of the card base from key escrow. Private keys are never exposed in plain and can't get copied.

That is the purpose of using a hardware key store: You want to make sure, that the key exists only a single hardware device or in a number of hardware devices that you control. You separate the management of the hardware devices from the actual management of the keys. And the SmartCard-HSM supports you with various DKEK configuration, even with n-of-m control, where the control of hardware on which keys can reside is shared amongst key custodians in an organization.

**Comment by frankmorgner** [comment]
I think it's primarily a decision on the card's side whether key import or export is supported. (Where the current answer is 'no', while @CardContact admits that there is some legitimate demand for this feature.) 

From the OpenSC perspective this issue can be closed.

**Comment by M-Maier** [comment]
> There is no command in OpenSC to import a PKCS#12 container into a SmartCard-HSM directly. You have to use the import_P12.js script from the SDK to do that (https://devnet.cardcontact.de/attachments/download/45/sc-hsm-workspace-20151114.zip).
> 
> As said in the other post, the import_P12.js tool first converts the key into the wrapped key format with a random DKEK and then imports that wrapped key into the device. Please make sure you have the unrestricted cryptographic policy installed for your JVM, because the wrapped key is encrypted using AES-256.

I am working on the issue of importing existing keys into "Nitrokey HSM2" USB "Smartcards". And I would like to try import_p12.js with them. However, I can't download _https://devnet.cardcontact.de/attachments/download/45/sc-hsm-workspace-20151114.zip_ .

Apparently I need to register/become a member to access the file? How can I register?

Has anyone any experience or a recipe with __Nitrokey HSM2__ and importing exisiting RSA keys?

**Comment by CardContact** [comment]
The SmartCard-HSM Workspace for the [Smart Card Shell](https://www.openscdp.org/scsh3/index.html) is part of the [Starterkit](https://www.cardcontact.de/download/sc-hsm-starterkit.zip). The above link in the CDN is outdated.

You can also find the latest P12 import in 220-importp12-plugin.js located in keymanager/plugins of the Smart Card Shell installation.
