### ISSUE TITLE
Austrian e-card

### ISSUE THREAD

**Issue by Schwertspize** [OpenSC/OpenSC#628]
can someone review this? 
https://github.com/OpenSC/OpenSC/wiki/Austrian-"Bürgerkarte"

**Comment by frankmorgner** [comment]
Unfortunately most of the wiki information is outdated. And only few people with the actual cards are posting or reviewing the details...

**Comment by frankmorgner** [comment]
Unfortunately calling "someone" on the internet almost never works... Maybe you can be a bit more specific about your problem?

**Comment by Schwertspize** [comment]
there is no real problem, it's just outdated. (or I think it's outdated.) 

never mind
