### ISSUE TITLE
get_response should be called recursively.

### ISSUE THREAD

**Issue by martinpaljak** [OpenSC/OpenSC#632]
Here's a scenario: READ BINARY is called, card replies with <data>6100, GET RESPONSE is called, card replies with <data>6100 and after this, next call is issued by the OpenSC but the card responds with 6F00.

I read out from 7816-4 that GET RESPONSE should be called recursively until data all data is fetched?

**Comment by dengert** [comment]
I read it :   only when  61XX is returned should it be called again.
    
    6F00 is a "checking error"  "No precise diagnosis"
    
    Sounds like hardware error, or card  has an internal error and does
    not know what else to return.
    
    
    
    On 12/9/2015 8:45 AM, Martin Paljak
      wrote:
    
    
      Here's a scenario: READ BINARY is called, card replies with
        6100, GET RESPONSE is called, card replies with 6100 and after
        this, next call is issued by the OpenSC but the card responds
        with 6F00.
      I read out from 7816-4 that GET RESPONSE should be called
        recursively until data all data is fetched?
      —
        Reply to this email directly or view it on
          GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
Isn't this implemented?
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L548-L549
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L435-L515

**Comment by dengert** [comment]
I think it is implemented, 

iso7816.c  checks for it:
 { 0x6F00, SC_ERROR_CARD_CMD_FAILED,     "No precise diagnosis" },

apdu.c line 476 - 484 should then return  SC_ERROR_CARD_CMD_FAILED

**Comment by germanblanco** [comment]
I am currently having a problem with this.
You can see in 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L435-L515
that get_response is called within a loop and the loop does not check for 6100, it only checks the returned length.
The DNIe is returning 6900, get_response is called again, and then the card returns "Invalid status".
Shoudn't this loop check the response code for 6100 before doing get_response?

**Comment by dengert** [comment]
In Line 476, 477:

rv = card->ops->get_response(card, &resp_len, resp);
if (rv < 0)   {

rv could be the length, or an error code. 
So it depends on the card driver to issue the command, and check the response. 

Best I can tell, card-dnie.c uses iso7816_get_response in iso7816.c 
that calls sc_check_sw in two places to set the return. 

sc_check_sw would then call dnie_check_sw that would then call 
iso7816_check_sw qhich should return SC_ERROR_NOT_ALLOWED.


Could SM be causing a problem? 
 sc_sm_update_apdu_response  is called. 

Is some higher level rouine retrying the get_response?

Does the debug log show anything?

**Comment by frankmorgner** [comment]
Sorry, I can't follow anymore. I think it would be best if one of you who have an actual problem with the current implementation (@martinpaljak or @germanblanco) would fix this error.

Obviously the code currently assumes that `0x6100` means that 256 bytes are available, see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L464, which is in accordance with ISO 7816-4:
> If SW1 is set to '61', then the process is completed and before issuing any other command, a GET RE -
SPONSE command may be issued with the same CLA and using SW2 (number of data bytes still available) as short L e field.

(SW2 == new Le == 0x00 == 256 bytes) If one your cards (@martinpaljak @germanblanco) are interpreting `0x6100` as EOF they should not blindly use `iso7816_check_sw`...

**Comment by germanblanco** [comment]
Thank you for your help.
Please bear with me, I am trying to understand how this works.
Handling of 0x6100 is OK.
When it is received, we enter the loop in https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L469
But after the get_response in 
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L476
new SW1 and SW2 are received, right? Apparently, the next result is SW1=69 and SW2=00. Which might be inconsistent, since the expected length hasn't been received completely. In any case, with the current code, a new get_response is sent, and it fails.
This is my current interpretation of what happens, I need to check it better. I was wondering if it made sense to check that the value of SW1 continues to be 61 for the processing to remain in this loop.
And I want to clarify that I am not working with the current code in master. I am trying to use sm_wrap and unwrap as @frankmorgner suggested instead of the current way to do things in dnie_apdu_transmit.

**Comment by frankmorgner** [comment]
1. `sc_get_response` is called with `0x6100`, which gets translated to a read binary with Ne=256 (Le=0x00)
2. `0x6900` is translated to an error, see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/iso7816.c#L69 (which is correct according to ISO 7816-4).
3. `sc_get_response` should return with an error code https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L484

So `get_response` should not be called an other time (or I still misunderstood you). What you could complain about is that the response data prepended to `0x6900` is ignored. But, honestly, `0x6900` *is an error*, so as middleware there is no way of knowing, for example, if this data is maybe corrupted. So it's OK to ignore that.

**Comment by germanblanco** [comment]
I will check again. I am probably doing something wrong for this error to be handled in a wrong way.

**Comment by dengert** [comment]
Ok, I think I see what you are saying. 
    
    Line 476: 
    rv = card->ops->get_response(card,
    &resp_len, resp);
    sends a get response and receives a new SW1 and SW2.
    
    But line 481:
     sc_sm_update_apdu_response(card, resp,
    resp_len, rv, apdu);
    
    is always looking at the original apdu  with the previous
    apdu->sw1 and apdu->sw2 that was reset in 
    the previous call to sc_sm_update_apdu_response
    and its sw1 and sw2 which may  not be the correct?
    
    It is not clear to me what  sc_sm_update_apdu_response
      is trying to do. 
    
    Could it also be that 6100 is returned, but the actual data returned
    by a get_response is < 256, say because of the SM overhead?
    
    Without SM, it works, because the  in line 476, rv is either an
    error < 0 or the length returned. 
    
    
    On 12/11/2015 7:02 AM, Germán Blanco
      wrote:
    
    
      Thank you for your help.
        Please bear with me, I am trying to understand how this works.
        Handling of 0x6100 is OK.
        When it is received, we enter the loop in https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L469
        But after the get_response in 
        https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L476
        new SW1 and SW2 are received, right? Apparently, the next result
        is SW1=69 and SW2=00. Which might be inconsistent, since the
        expected length hasn't been received completely. In any case,
        with the current code, a new get_response is sent, and it fails.
        This is my current interpretation of what happens, I need to
        check it better. I was wondering if it made sense to check that
        the value of SW1 continues to be 61 for the processing to remain
        in this loop.
        And I want to clarify that I am not working with the current
        code in master. I am trying to use sm_wrap and unwrap as @frankmorgner suggested instead of
        the current way to do things in dnie_apdu_transmit.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
hmm, `sc_sm_update_apdu_response` does not seem to be aware of multiple send/receive cycles. It only returns the response buffer of the last GET RESPONSE.

I'm totally puzzled why `sc_get_response` fiddles around with SM in the first place, because the card's `get_response` calls `sc_transmit`, which should handle SM transparently. Maybe @viktorTarasov can bring some light in this...

**Comment by germanblanco** [comment]
It seems the return code with a problem was actually a 90 00.
I find it very strange that this comment:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L455-456
states that the loop will end when either the result code is SUCCESS or the length is completed, and then in this line:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L507
The condition is that we stay in the loop if result code is different from SUCCESS or the length is zero.
Things work better for me if I change that "or" for an "and".

**Comment by frankmorgner** [comment]
I can't follow anymore. Please make a PR for review when you're satisfied with your changes...

**Comment by germanblanco** [comment]
OK.
I will do it in two parts. The first one is extremely simple, just change the condition in the loop.
The second one will be more tricky and it will handle responses longer than 255 bytes by putting all of them together and then calling a sm_parsing method.
It would be good if @viktorTarasov has worked on this, to have his view.

**Comment by frankmorgner** [comment]
The GET RESPONSE command does not seem to be heavily used by the card drivers. Only the drivers for akis and belpic explicitly use the implementation of `iso7816.c`. For all the other card driver this is explicitly removed or untested. Specifically there is no card that supports SM *and* announces support for GET RESPONSE. DNIe accidentally use the implementation of `iso7816.c` by *not overwriting* the `iso_ops`.

My bet is that SM + GET RESPONSE has *never* been tested and even the pure GET RESPONSE has never been on somebody's page for very long...

**Comment by germanblanco** [comment]
OK, the code seems to be in surprisingly good shape considering that it is not being used that much.
What would be then your suggestion?
Making it work for DNIe doesn't seem that far away. Are there any alternatives?

**Comment by dengert** [comment]
I disagree with @frankmorgner  on the use of get_response. For one, sc_get_response is called from sc_transmit when any command returns 61xx, which is the case for  T=0.  

Many cards  start with the iso_ops when they do something like:
iso_ops = iso_drv->ops;
I see a few overwrite it and 3 drivers set it to NULL. I guess they don't work with T=0? 

Frank, you also said earlier:  "sc_get_response  is called with  0x6100 , which gets translated to a read binary."  Where does that happen?  It would have to be in a card driver, as sc_get_response 
calls card->ops->get_response. 

card-piv.c relies heavily on sc_get_response, and the iso version of it when used with the get data, generate key and general authenticate commands, all of which can return more then 256 bytes.  

Its always on my page... 

A few years ago a change was made in this area which causes the 
card-piv.c to read objects twice. card-piv.c tries to read the first 8 bytes of an object to determine the length of the object, then goes back and read trhe full object. The first read would cause the apdu.c code to read and discard all the data for the first read!  adding SC_APDU_FLAGS_NO_GET_RESP
for the read of 8 bytes fixed that. 


I did some minimal testing yesterday and the change:

-	} while (rv != 0 || minlen != 0);
+	} while (rv != 0 && minlen != 0);

appears to work either way with the card-piv.c in either T=0 or T=1
PIV does not use SM, but is optional in NIST 800-73-4.

**Comment by frankmorgner** [comment]
> Frank, you also said earlier: "sc_get_response is called with 0x6100 , which gets translated to a read binary." Where does that happen? It would have to be in a card driver, as sc_get_response

sorry, it is translated in `sc_get_response` to `card->ops->get_response` with Le=0x00, most likeley as GET RESPONSE *not* READ BINARY.

> Many cards start with the iso_ops when they do something like:
iso_ops = iso_drv->ops;
I see a few overwrite it and 3 drivers set it to NULL. I guess they don't work with T=0?

This is the problem: They don't make it explicit. So you don't really know whether this is needed or tested or if it happened by accident (so my criticism was maybe a bit exaggerated...). Anyway, at least we now know that we have PIV to test with :wink:

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/apdu.c#L504-L505 pretty much explains why we have `||` instead of `&&`:
> if the card has returned 0x9000 but we still expect data ask for more until we have read enough bytes

I don't have any preference since I don't have any card that relys on either behaviour. But aborting when the card has no more data *or* we don't expect any more data seems most reasonable for me. To clearify, I am voting for `&&`!

**Comment by dengert** [comment]
I would vote for && too.  rv == 0  means card has no more data. minlen == 0 means caller does not want any more data. 


ALso, if there is still a problem with SM, I see ./iasecc-sm.c line 328 turn off the 
SC_APDU_FLAGS_NO_GET_RESP flag for some reason. Is that correct?

   rdata.data->apdu.flags &= ~SC_APDU_FLAGS_NO_GET_RESP;

(There is one minor issue, with T=0, and card-piv.c trying to read just 8 bytes to get the length,
and has SC_APDU_FLAGS_NO_GET_RESP set, sc_get_response ends up reading up to 256 bytes from the card (or what the card says is still available) and then returns the  first 8 bytes to the caller. But I would not change this as it still works.)

**Comment by germanblanco** [comment]
Excellent! How do we proceed then?
Maybe the Pull request should also modify the comment above the change so that it is consistent, but otherwise, in terms of code, there seems to be nothing else to do.

**Comment by frankmorgner** [comment]
Reading now stops when the requested data was read. @germanblanco could you check what the result looks like when used with SM?

**Comment by germanblanco** [comment]
It looks better, but I haven't been able to make it work yet.
This change avoid one endless loop in my code, but there is still some way to go.
Thanks a lot, I hope it works ok for all other cards.

**Comment by frankmorgner** [comment]
send a log if you need help analyzing what's going wrong

**Comment by dengert** [comment]
Forgot about #632. Yes it is similar, but was dealing with SM. What appears to be going on in the sc_read_binary is that it breaks up a long read binary into `sc_get_max_recv_size(card)` size chunks that happen to be 256 in T=0 in this case. This loop replace the need to do get_response to read in all the data.

Note '6100' only says more data is available, it does not say it has to be read. My contention is that with the loop of read_binary type 2 ADPUs with T=0 the requested data is already returned and no get_response should be issued. As I pointed out, an extra 256 bytes were read using get_response which may confuse the card and cause it have a problem with the  next read_data that would start with index=256. 

Note the sc_read_binary has a flags option, and is passed to the loop of sc_get_response and to iso7816_read_binary. But iso7816_read_binary does not do anything with it. 

Many card drivers have their own versions of read_binary: 
card-authentic.c:authentic_read_binary
card-belpic.c:static int belpic_read_binary
card-cac.c:static int cac_read_binary
card-coolkey.c:static int coolkey_read_binary
card-dnie.c:static int dnie_read_binary
card-entersafe.c:static int entersafe_read_binary
card-gids.c:static int gids_read_binary
card-gpk.c:gpk_read_binary
card-iasecc.c:static int _iasecc_sm_read_binary
card-jcop.c:static int jcop_read_binary
card-jpki.c:jpki_read_binary
card-muscle.c:static int muscle_read_binary
card-oberthur.c:auth_read_binary
card-openpgp.c:pgp_read_binary
card-piv.c:piv_read_binary
card-sc-hsm.c:static int sc_hsm_read_binary

Some are emulating read_binary like card-coolkey.c, card_cac.c and card-piv.c that pull certificates from objects in a cache where the cert may have been zipped. Some handle card specific issues. Some need to address SM issues. 
 
The point is it is not uncommon to have a card specific read_binary routine. You may need one for this card.

**Comment by dengert** [comment]
See if this [read_binary.patch.txt](https://github.com/OpenSC/OpenSC/files/1455620/read_binary.patch.txt) would work. **It is not tested.** but should eliminate the extra get_response.
