### ISSUE TITLE
Minidriver integration with Microsoft CA

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#640]
Anyone on the list that has tried to use the OpenSC Minidriver with a Microsoft CA ?

Is it possible and is there documentation available ?

We've done some tests with Windows 2008 Server, but even though certutil -scinfo reported that everything is in good shape, the CA could not use the token.

**Comment by frankmorgner** [comment]
I think this is what @vletoux has done, maybe he has some documentation on www.mysmartlogon.com.

**Comment by faezeh-R** [comment]
I used minidriver for login to windows and generating certificate with certmgr.msc 
Maybe I can help you, If I know what is your problem exactly.

**Comment by vletoux** [comment]
@cardcontact use api monitor attached to mmc.exe to debug it.
As I explained to you a few month ago the card sc-hsm is read only for the minidriver. You have to enable the write mode in opensc.conf.
Then I fixed the problem of opensc 0.14 which consisted in not reusing the Windows container name.
Certmgr.msc ; personal; request new certificate 

Vincent

**Comment by vletoux** [comment]
see #652 which has been solved
