### ISSUE TITLE
pkcs#11 test tool

### ISSUE THREAD

**Issue by MaryamSD** [OpenSC/OpenSC#641]
Can anyone help me to find a pkcs#11 tool that be more than an explorer(object viewer). I want to test Encryption/Decryption.

**Comment by dengert** [comment]
pkcs11-tool can do sign and decrypt.

**Comment by MaryamSD** [comment]
pkcs-tool can be used in windows?

**Comment by dengert** [comment]
Yes,
 C:\Program Files (x86)\OpenSC Project\OpenSC\tools\pkcs11-tool.exe

**Comment by vletoux** [comment]
This tool can be used for testing:
https://www.idrix.fr/Root/content/category/5/23/40/
