### ISSUE TITLE
Rutoken ECP 2.0

### ISSUE THREAD

**Issue by hexum** [OpenSC/OpenSC#648]
When I follow [this instruction] (https://www.opensc-project.org/opensc/wiki/AktivRutokenECP) I get an error at point of key creation.

```
pkcs15-init -G rsa/1024 --auth-id 02 --label "My Private Key" --public-key-label "My Public Key"
Using reader with a card: Aktiv Rutoken ECP 00 00
User PIN [User PIN] required.
Please enter User PIN [User PIN]: 
Failed to generate key: Incorrect parameters in APDU
```

```
opensc-tool -i
OpenSC 0.15.0 [gcc  5.3.0]
Enabled features: zlib readline openssl pcsc(libpcsclite.so.1)
```

```
opensc-tool -a
Using reader with a card: Aktiv Rutoken ECP 00 00
3b:8b:01:52:75:74:6f:6b:65:6e:20:44:53:20:c1
```

```
opensc-tool -n
Using reader with a card: Aktiv Rutoken ECP 00 00
Rutoken ECP (DS)
```

The problem is 100% reproducible.

What is going wrong? Can you guide me to do further diagnostics?
Thanks!

**Comment by dengert** [comment]
Try and get an opensc-debug.log. See:
    
    https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC
    
    The original code was from 2007. Your card may be a newer version.
    There may not be an active developer who has the card,
    or even the original. card. 
    
    
    On 1/1/2016 12:33 PM, Eugene wrote:
    
    
      When I follow this
          instruction I get an error at point of key creation
      pkcs15-init -G rsa/1024 --auth-id 02 --label "My Private Key" --public-key-label "My Public Key"
Using reader with a card: Aktiv Rutoken ECP 00 00
User PIN [User PIN] required
Please enter User PIN [User PIN]: 
Failed to generate key: Incorrect parameters in APDU

      opensc-tool -i
OpenSC 0150 [gcc  530]
Enabled features: zlib readline openssl pcsc(libpcscliteso1)

      opensc-tool -a
Using reader with a card: Aktiv Rutoken ECP 00 00
3b:8b:01:52:75:74:6f:6b:65:6e:20:44:53:20:c1

      opensc-tool -n
Using reader with a card: Aktiv Rutoken ECP 00 00
Rutoken ECP (DS)

      The problem is 100% reproducible
      What is going wrong? Can you guide me to do further
        diagnostics?
        Thanks!
      —
        Reply to this email directly or view it on
          GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by hexum** [comment]
I reinitialized token then issued command `OPENSC_DEBUG=9 pkcs15-init -G rsa/1024 --auth-id 02 --label "My Private Key" --public-key-label "My Public Key" --pin 12345678  > /tmp/pkcs15-init.txt 2>&1` and got [the log](https://github.com/OpenSC/OpenSC/files/76340/pkcs15-init.txt).

Subsequent execution of last command lead to another error. [Failed to generate key: File already exist](https://github.com/OpenSC/OpenSC/files/76342/pkcs15-init_subsec.txt).

**Comment by dengert** [comment]
There is not much I can tell you.  The ATR matches the
    libopensc/card-rtecp.c
    
    pkcs15init/pkcs15-rtecp.c  does a SC_CARDCTL_RTECP_GENERATE_KEY 
    and the apdu is formated in libopensc/card-rtecp.c  
    630                 sc_format_apdu(card, &apdu,
    SC_APDU_CASE_2_SHORT, 0x46, 0x80,
    631                                 genkey_data->key_id);
    632                 apdu.resp = buf;
    633                 apdu.resplen = sizeof(buf);
    634                 apdu.le = 256;
    
    The apdu sent is:
    00 46 80 01 00
    The card returned 6A 80  "Incorrect parameters in the data field"
    
    I don't have any cards that use pkcs15-init, someone else might
    help. 
    
    Is "--auth-id 02" the correct parameter?
    should it be "--id 02" ?
    
    
    
    
    
    On 1/2/2016 12:28 PM, Eugene wrote:
    
    
      I reinitialized token then issued command OPENSC_DEBUG=9
          pkcs15-init -G rsa/1024 --auth-id 02 --label "My Private Key"
          --public-key-label "My Public Key" --pin 12345678 >
          /tmp/pkcs15-init.txt 2>&1 and got the
          log.
      Subsequent execution of last command lead to another error. Failed
          to generate key: File already exist.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by hexum** [comment]
There are no mistakes in command line parameters.
```
pkcs15-init
-a, --auth-id <arg>           Specify ID of PIN to use/create
-i, --id <arg>                Specify ID of key/certificate
```
I'll try to get documentation about Rutoken APDU format.
