### ISSUE TITLE
AD smartcard logon with smartcard-hsm, opensc-minidriver and ECC-based certificates

### ISSUE THREAD

**Issue by owinkelmann** [OpenSC/OpenSC#652]
Hello,

I try to set up AD smartcard logon with a smartcard-hsm. 
It works with a private RSA-Key and the corresponding smartcard logon certificate on the smartcard-hsm. But when I use an EC-Key & certificate smartcard logon fails.

I generate an EC-Key on the card:
pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -l --keypairgen --key-type EC:prime256v1 --id 6

Then I create a smartcard certificate request and use a MS CA to sign the request. The certificate seems to be OK. Public key: ECC (265 Bits), Public Key parameters ECDH_P256, principalname, ...

I write it on the smartcard-hsm:
pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -l -w mycert.der  -y cert --id 6

pkcs11-tool -O shows:
sing slot 1 with a present token (0x1)
Logging in to "SmartCard-HSM (UserPIN)".
Please enter User PIN: 
Private Key Object; EC
  label:      Certificate
  ID:         06
  Usage:      sign, derive
Certificate Object, type = X.509 cert
  label:      Certificate
  ID:         06
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   04410401c857a55e25c340553815e52fadb65c01707baaeb109eeef63eca40e74143337980ae8f9b0ee4a4483f09fd6a5c2db24f9f0c19c6863985ea80b2bf5977bc7a
  EC_PARAMS:  06082a8648ce3d030107
  label:      Certificate
  ID:         06
  Usage:      encrypt, verify

certutil -scinfo shows:
...
---   Card:
--- Reader: OMNIKEY CardMan 3x21 0
--- Status: SCARD_STATE_PRESENT
--- Status: The card is available for use.
---   Card: SmartCard-HSM
---    ATR:
        3b fe 18 00 00 81 31 fe  45 80 31 81 54 48 53 4d   ;.....1.E.1.THSM
        31 73 80 21 40 81 07 fa                            1s.!@...
...
Analyzing card in reader: OMNIKEY CardMan 3x21 0
2016-01-04 18:30:14.791 set 'cmapfile'
2016-01-04 18:30:16.072 set 'cmapfile'
2016-01-04 18:30:17.150 set 'cmapfile'
Missing stored keyset
2016-01-04 18:30:18.541 set 'cmapfile'
2016-01-04 18:30:19.791 set 'cmapfile'
Missing stored keyset
...
CertUtil: -SCInfo command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET)
CertUtil: Keyset does not exist

Any ideas?

**Comment by dengert** [comment]
You may need the latest OpenSC minidriver in github.com to use EC
    keys. 
    
    https://technet.microsoft.com/en-us/library/ff404285(v=ws.10).aspx
    might help.
    
https://social.technet.microsoft.com/Forums/fr-FR/76e987a8-57a8-48bf-b143-2db04cb1e3e3/ca-certificate-keyset-does-not-exist-0x80090016-2146893802-ntebadkeyset?forum=winserversecurity
    sounds like the problem is with the CA certs or service, not with
    the user cert. 
    
    You could also consider the Yubco NEO with the PIV applet, and use
    the Microsoft built in PIV driver
    and would not need any OpenSC code for login.  
    (To initialize the Neo you might need the Yubico-piv-tool or the
    OpenSC piv-tool.)
    
    On 1/4/2016 11:37 AM, owinkelmann
      wrote:
    
    
      Hello,
      I try to set up AD smartcard logon with a smartcard-hsm 
        It works with a private RSA-Key and the corresponding smartcard
        logon certificate on the smartcard-hsm But when I use an EC-Key
        & certificate smartcard logon fails
      I generate an EC-Key on the card:
        pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11so
        -l --keypairgen --key-type EC:prime256v1 --id 6
      Then I create a smartcard certificate request and use a MS CA
        to sign the request The certificate seems to be OK Public key:
        ECC (265 Bits), Public Key parameters ECDH_P256, principalname,
      
      I write it on the smartcard-hsm:
        pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11so
        -l -w mycertder -y cert --id 6
      pkcs11-tool -O shows:
        sing slot 1 with a present token (0x1)
        Logging in to "SmartCard-HSM (UserPIN)"
        Please enter User PIN: 
        Private Key Object; EC
        label: Certificate
        ID: 06
        Usage: sign, derive
        Certificate Object, type = X509 cert
        label: Certificate
        ID: 06
        Public Key Object; EC EC_POINT 256 bits
        EC_POINT:
04410401c857a55e25c340553815e52fadb65c01707baaeb109eeef63eca40e74143337980ae8f9b0ee4a4483f09fd6a5c2db24f9f0c19c6863985ea80b2bf5977bc7a
        EC_PARAMS: 06082a8648ce3d030107
        label: Certificate
        ID: 06
        Usage: encrypt, verify
      certutil -scinfo shows:
      --- Card:
        --- Reader: OMNIKEY CardMan 3x21 0
        --- Status: SCARD_STATE_PRESENT
        --- Status: The card is available for use
        --- Card: SmartCard-HSM
        --- ATR:
        3b fe 18 00 00 81 31 fe 45 80 31 81 54 48 53 4d ;1E1THSM
        31 73 80 21 40 81 07 fa 1s!@
      Analyzing card in reader: OMNIKEY CardMan 3x21 0
        2016-01-04 18:30:14791 set 'cmapfile'
        2016-01-04 18:30:16072 set 'cmapfile'
        2016-01-04 18:30:17150 set 'cmapfile'
        Missing stored keyset
        2016-01-04 18:30:18541 set 'cmapfile'
        2016-01-04 18:30:19791 set 'cmapfile'
        Missing stored keyset
      CertUtil: -SCInfo command FAILED: 0x80090016 (-2146893802
        NTE_BAD_KEYSET)
        CertUtil: Keyset does not exist
      Any ideas? 
      —
        Reply to this email directly or view it on
          GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
I already explain the problem: this is related to the hack I used to avoid the request for a minidriver install which conflicts with the Microsoft hack for smart card logon (map a KSP to a CSP).

Open regedit. Search for Calais (not in WOW node !). Search for your card.
Then find the Crypto provider entry. You should find something like "OpenSC CSP". Replace it with "Microsoft Base Smart Card Crypto Provider" like the other cards you may find.

Test the change with "certutil -scinfo" (there is a mention of the crypto provider here).
=> ECC smart card should be working

(it's me who have adapted the minidriver to allow the ECC smart card logon and it does work - this has been done a few month ago so be sure to use the latest version)

see http://www.mysmartlogon.com/knowledge-base/ecc-smart-card-logon/

Vincent

**Comment by owinkelmann** [comment]
Replace "OpenSC CSP" with "Microsoft Base Smart Card Crypto Provider" does not solve the problem:
...
Analyzing card in reader: OMNIKEY CardMan 3x21 0
2016-01-05 11:58:28.993 set 'cmapfile'
2016-01-05 11:58:30.290 set 'cmapfile'
2016-01-05 11:58:31.353 set 'cmapfile'
Missing stored keyset
2016-01-05 11:58:32.774 set 'cmapfile'
2016-01-05 11:58:34.009 set 'cmapfile'
Missing stored keyset
...


When I use your Howto "ECC Smart card logon" I get the Message: The smart card is read-only.

thanks in advance

**Comment by vletoux** [comment]
You have to enable the minidriver write mode in the opensc.conf
This is something that @CardContact should do by default.

**Comment by vletoux** [comment]
Note: you can create the certificate using the tool like you did. The modification I suggested is requested only for the smart card login.

**Comment by vletoux** [comment]
And the fact that there is OpenSC logs when you are doing certutil -scinfo suggests that you are using an old version of OpenSC which does not supports ECC with the minidriver.
You can pick a developer build for Windows here: https://ci.appveyor.com/project/LudovicRousseau/opensc
(select a release and then look for artifacts at the upper right)
=> certutil -scinfo should display your ECC certificate

**Comment by owinkelmann** [comment]
Ok, now I can see the ECC certificate. But smartcard logon is not working. The smartcard credential provider finds the ECC cert, I enter the pin an get the following error message:

This smart card could not be used. Additional details may be available 
in the system event log. Please report this error to your administrator.

certutil -scinfo shows:
...
Analyzing card in reader: Gemplus USB Smart Card Reader 0
Missing stored keyset

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Gemplus USB Smart Card Reader 0
---   Card: SmartCard-HSM
Provider = Microsoft Smart Card Key Storage Provider
Key Container = {a3b9ac48-3aa7-12f9-1852-6f1879fbb435}

Serial Number: 4d0000000e52993d41e4ad78ce00000000000e
...
...
Cert Hash(sha1): 52 84 57 3d 23 c5 fc 5e 80 3f ee 56 0f 05 1e f2 62 c7 d1 c0

Performing  public key matching test...
Public key matching test succeeded
  Key Container = {a3b9ac48-3aa7-12f9-1852-6f1879fbb435}
  Provider = Microsoft Smart Card Key Storage Provider
  ProviderType = 0
  Flags = 1
    0x1 (1)
  KeySpec = 0
Private key verifies

Performing cert chain verification...
Chain validates
Smart Card Logon: Chain validates
dwFlags = CA_VERIFY_FLAGS_NT_AUTH (0x10)
dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
Application[0] = 1.3.6.1.4.1.311.20.2.2 Smart Card Logon
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_NT_AUTH
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwInfoStatus = CERT_TRUST_HAS_PREFERRED_ISSUER (0x100)
ChainContext.dwRevocationFreshnessTime: 22 Hours, 23 Minutes, 55 Seconds

SimpleChain.dwInfoStatus = CERT_TRUST_HAS_PREFERRED_ISSUER (0x100)
SimpleChain.dwRevocationFreshnessTime: 22 Hours, 23 Minutes, 55 Seconds
...
...
CertUtil: -SCInfo command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET)
CertUtil: Keyset does not exist

**Comment by vletoux** [comment]
If you have setup the CA less than 8 hours ago and not testing on the same hosts, I suggest you issue a "gpupdate /force" on the DC & on the workstation to force the deployment of the root CA.

Each DC needs a certificate. This is done automatically by the GPO.
But maybe the DC needs an ECC certificate. If this specific action solve the problem, just tell me that I update my docs.

See http://download.mysmartlogon.com/SmartPolicyv2/Troubleshooting%20smart%20card%20logon%20authentication.pdf for more information

=> please tell me if you are able to make it works

**Comment by owinkelmann** [comment]
After a Reboot of the test-vm ECC-smartcard login is working ;-)

Thanks!

**Comment by scottthomas007** [comment]
> Hello,
> 
> I try to set up AD smartcard logon with a smartcard-hsm. It works with a private RSA-Key and the corresponding smartcard logon certificate on the smartcard-hsm. But when I use an EC-Key & certificate smartcard logon fails.
> 
> I generate an EC-Key on the card: pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -l --keypairgen --key-type EC:prime256v1 --id 6
> 
> Then I create a smartcard certificate request and use a MS CA to sign the request. The certificate seems to be OK. Public key: ECC (265 Bits), Public Key parameters ECDH_P256, principalname, ...
> 
> I write it on the smartcard-hsm: pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -l -w mycert.der -y cert --id 6
> 
> pkcs11-tool -O shows: sing slot 1 with a present token (0x1) Logging in to "SmartCard-HSM (UserPIN)". Please enter User PIN: Private Key Object; EC label: Certificate ID: 06 Usage: sign, derive Certificate Object, type = X.509 cert label: Certificate ID: 06 Public Key Object; EC EC_POINT 256 bits EC_POINT: 04410401c857a55e25c340553815e52fadb65c01707baaeb109eeef63eca40e74143337980ae8f9b0ee4a4483f09fd6a5c2db24f9f0c19c6863985ea80b2bf5977bc7a EC_PARAMS: 06082a8648ce3d030107 label: Certificate ID: 06 Usage: encrypt, verify
> 
> certutil -scinfo shows: ... --- Card: --- Reader: OMNIKEY CardMan 3x21 0 --- Status: SCARD_STATE_PRESENT --- Status: The card is available for use. --- Card: SmartCard-HSM --- ATR: 3b fe 18 00 00 81 31 fe 45 80 31 81 54 48 53 4d ;.....1.E.1.THSM 31 73 80 21 40 81 07 fa 1s.!@... ... Analyzing card in reader: OMNIKEY CardMan 3x21 0 2016-01-04 18:30:14.791 set 'cmapfile' 2016-01-04 18:30:16.072 set 'cmapfile' 2016-01-04 18:30:17.150 set 'cmapfile' Missing stored keyset 2016-01-04 18:30:18.541 set 'cmapfile' 2016-01-04 18:30:19.791 set 'cmapfile' Missing stored keyset ... CertUtil: -SCInfo command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET) CertUtil: Keyset does not exist
> 
> Any ideas?

Hello ,
I am trying to use SmartCard-HSM for smart card logon but there is some issue with middleware. can you please guide me?
