### ISSUE TITLE
Identity Alliance JavaCard is not detected correctly

### ISSUE THREAD

**Issue by odhoette** [OpenSC/OpenSC#653]
We are using Identity Alliance JavaCards with the ATR 3b:f8:13:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:b7.
With opensc > 0.13.x, these cards are not detected correctly due to a few bugs/problems.

1. In src/libopensc/card-muscle.c, the return value of _sc_match_atr is checked for SC_SUCCESS, but the function returns the index of the ATR in the atr_table. This only works, if the matched ATR is the first one in the atr_table.
2. The ATR of our card is listed in the atr_table of the muscle driver as well as in the atr_table of the sc-hsm card driver. This must be wrong as the sc-hsm driver uses completely different ATRs to communicate with the card.
3. The driver for MICARDO checks for an AID if the ATR match fails. This check is also positive on the Identity Alliance JavaCard, so it is not sufficient to detect a MICARDO card.

If issue 1 is fixed, the other two problems can be controlled by a config file change (add a fix driver mapping for this ATR to muscle).
```
        card_atr 3b:f8:13:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:b7 {
		driver = "muscle";
	}
```

Fixes for these issue:

muscle-fix-match-return.patch
```diff
--- opensc-0.15.0.orig/src/libopensc/card-muscle.c
+++ opensc-0.15.0/src/libopensc/card-muscle.c
@@ -476,7 +476,7 @@ static int muscle_init(sc_card_t *card)
 	card->caps |= SC_CARD_CAP_RNG;
 
 	/* Card type detection */
-	if (SC_SUCCESS != _sc_match_atr(card, muscle_atrs, &card->type))
+	if (_sc_match_atr(card, muscle_atrs, &card->type) < 0)
 		SC_FUNC_RETURN(card->ctx, SC_LOG_DEBUG_NORMAL, SC_ERROR_INVALID_CARD);
 
 	if(card->type == SC_CARD_TYPE_MUSCLE_ETOKEN_72K) {
```

--------

sc-hsm-wrong-atr.patch
```diff
--- opensc-0.15.0.orig/src/libopensc/card-sc-hsm.c
+++ opensc-0.15.0/src/libopensc/card-sc-hsm.c
@@ -70,7 +70,6 @@ static struct sc_atr_table sc_hsm_atrs[]
 /* Known ATRs for JavaCards that qualify for SmartCard-HSMs */
 static struct sc_atr_table sc_hsm_jc_atrs[] = {
 	/* standard version */
-	{"3b:f8:13:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:b7", NULL, NULL, SC_CARD_TYPE_SC_HSM, 0, NULL},	// JCOP 2.4.1 Default ATR contact based
 	{"3b:88:80:01:4a:43:4f:50:76:32:34:31:5e", NULL, NULL, SC_CARD_TYPE_SC_HSM, 0, NULL},	// JCOP 2.4.1 Default ATR contactless
 	{NULL, NULL, NULL, 0, 0, NULL}
 };
```

mcrd-remove-aid-check.patch
```diff
--- opensc-0.15.0.orig/src/libopensc/card-mcrd.c
+++ opensc-0.15.0/src/libopensc/card-mcrd.c
@@ -285,7 +285,7 @@ static int mcrd_match_card(sc_card_t * c
 		return 1;
 	}
 
-	sc_format_apdu(card, &apdu, SC_APDU_CASE_3, 0xA4, 0x04, 0x00);
+	/*sc_format_apdu(card, &apdu, SC_APDU_CASE_3, 0xA4, 0x04, 0x00);
 	apdu.lc = sizeof(EstEID_v35_AID);
 	apdu.data = EstEID_v35_AID;
 	apdu.datalen = sizeof(EstEID_v35_AID);
@@ -298,7 +298,7 @@ static int mcrd_match_card(sc_card_t * c
 	        sc_log(card->ctx, "AID found");
 	        card->type = SC_CARD_TYPE_MCRD_ESTEID_V30;
 	        return 1;
-	}
+	}*/
 	return 0;
 }
```
(This is quite 'straight forward', i am sure, there is a better solution for this, but i do not have a MICARDO card here).

**Comment by frankmorgner** [comment]
Using an ATR for card recognition is not bullet proof. If I understand correctly, your card has the same ATR as some other different card that is already recognized in OpenSC. I don't know how common your card is, but for now I assume it is samewhat exotic because you are the first one who reports this problem. In consequence, I advice you to continue using
```
card_atr 3b:f8:13:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:b7 {
        driver = "muscle";
    }
```
```diff
--- opensc-0.15.0.orig/src/libopensc/card-muscle.c
+++ opensc-0.15.0/src/libopensc/card-muscle.c
@@ -476,7 +476,7 @@ static int muscle_init(sc_card_t *card)
    card->caps |= SC_CARD_CAP_RNG;

    /* Card type detection */
-   if (SC_SUCCESS != _sc_match_atr(card, muscle_atrs, &card->type))
+   if (_sc_match_atr(card, muscle_atrs, &card->type) < 0)
        SC_FUNC_RETURN(card->ctx, SC_LOG_DEBUG_NORMAL, SC_ERROR_INVALID_CARD);

    if(card->type == SC_CARD_TYPE_MUSCLE_ETOKEN_72K) {
```
The above patch is already applied in master, which means that this issue should already be fixed.

**Comment by MSBGit** [comment]
Back when Sun Ray (originally from Sun Microsystems, then bought by Oracle in 2010) was a product, I created the smart card identification infrastucture (the SwapDrop language) and wrote most of the card configuration (identification) files. I used a combination of ATR parsing and for cards that that config file thought might have an applet, selecting an applet (or multiple applets in sequence) and also reading a serial number form the card/applet(s). It was a pretty foolproof way to identify cards and also get a unique combination of card type:serial number.

Mike

> On Jan 6, 2016, at 3:44 PM, Frank Morgner <notifications@github.com> wrote:
> 
> Using an ATR for card recognition is not bullet proof. If I understand correctly, your card has the same ATR as some other different card that is already recognized in OpenSC. I don't know how common your card is, but for now I assume it is samewhat exotic because you are the first one who reports this problem. In consequence, I advice you to continue using
> 
> card_atr 3b:f8:13:00:00:81:31:fe:45:4a:43:4f:50:76:32:34:31:b7 {
>         driver = "muscle";
>     }
> --- opensc-0.15.0.orig/src/libopensc/card-muscle.c
> +++ opensc-0.15.0/src/libopensc/card-muscle.c
> @@ -476,7 +476,7 @@ static int muscle_init(sc_card_t *card)
>     card->caps |= SC_CARD_CAP_RNG;
> 
>     /* Card type detection */
> -   if (SC_SUCCESS != _sc_match_atr(card, muscle_atrs, &card->type))
> +   if (_sc_match_atr(card, muscle_atrs, &card->type) < 0)
>         SC_FUNC_RETURN(card->ctx, SC_LOG_DEBUG_NORMAL, SC_ERROR_INVALID_CARD);
> 
>     if(card->type == SC_CARD_TYPE_MUSCLE_ETOKEN_72K) {
> The above patch is already applied in master, which means that this issue should already be fixed.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/653#issuecomment-169499903>.
> 

Michael Bender
michaelbender@me.com

⛵

**Comment by frankmorgner** [comment]
https://github.com/odhoette
