### ISSUE TITLE
Brew install SHA256 mismatch

### ISSUE THREAD

**Issue by alexmatveev** [OpenSC/OpenSC#659]
$ brew install opensc
==> Downloading https://downloads.sourceforge.net/project/opensc/OpenSC/opensc-0.15.0/opensc-0.15.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opensc-0.15.0.tar.gz
Error: SHA256 mismatch
Expected: 399b2107a69e3f67e4e76dc2dbd951dbced8e534b1e0f919e176aea9b85970d7
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821

**Comment by frankmorgner** [comment]
I am not aware that we are handling the brew package

**Comment by LudovicRousseau** [comment]
Remove ``/Library/Caches/Homebrew/opensc-0.15.0.tar.gz`` and try again.
This is not an OpenSC problem.
