### ISSUE TITLE
OpenSC on Mac OSX "El Capitan" 10.11.2

### ISSUE THREAD

**Issue by IgnacioHR** [OpenSC/OpenSC#667]
During the installation phase, the installer raises a warning message...
<img width="478" alt="instalar_opensc_0_15_0_for_os_x_10_9_" src="https://cloud.githubusercontent.com/assets/16385090/12567266/7dd222e2-c3be-11e5-9e22-f101eb243567.png"> the translation of the warning message says more or less that the application can damage my system and make it unusable...

Do you know what's going on and if this message is a serious warning?

**Comment by LudovicRousseau** [comment]
It looks like (according to the image name "instalar_opensc_0_15_0_for_os_x_10_9_") you try to install OpenSC for OS X 10.9 on OS X 10.11.
Is that the case?

**Comment by IgnacioHR** [comment]
I downloaded version 0.15.0.
Link found in the Home page. the description says it is for Mac OSX 10.10 (10.11 is not there) It looks like i might need to compile it cause I can't find a installer for 10.11

**Comment by IgnacioHR** [comment]
Anyone has compiled a new installer for MaxOSX and is it published anywhere? can't find a newer version in the downloads pages!

**Comment by davitb** [comment]
+1 to the question. 
Seems like several bugs have been fixed after 0.15 release and one of them being that OpenSC cannot be properly installed on OSX 10.11. #588 
@LudovicRousseau are you planning releasing a new DMG soon?

**Comment by LudovicRousseau** [comment]
@davitb, I do not release DMG images or anything else.
I don't know if a release for El Capitan 10.11 is ready/available.

**Comment by martinpaljak** [comment]
I'll have a look as time permits.

**Comment by mouse07410** [comment]
I can only say that I've been building DMG for El Capitan 10.11.3 (and before that - for Yosemite) off the Github master for ages. No problem. 

Some small improvements wouldn't hurt - like I edited the build to stop building fat binaries (do you really want i386 code on your x86_64 processor? really?). But it's all very smooth.

If you want `OpenSC.tokend` to work with PIV tokens (full RSA) and support ECDSA correctly, you probably want `mouse07410/OpenSC.tokend` to replace the original one (`OpenSC/OpenSC.tokend`).

**Comment by frankmorgner** [comment]
You can use the binaries included in https://github.com/frankmorgner/vsmartcard/releases/download/npa-0.7/npa-0.7_osx.dmg in the meantime

**Comment by davitb** [comment]
@martinpaljak any updates on dmg file? 
OpenSC 0.15.0 DMG fails to install on 10.11 and I'm not sure what to tell my users.
Would be good at least to know if the team is planning to make a new release or not.

**Comment by frankmorgner** [comment]
See https://github.com/OpenSC/OpenSC/releases/tag/v0.16.0-pre1

Don't expect a real release very soon...
