### ISSUE TITLE
Can't unblock PIN on SmartCard-HSM EA+

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#668]
When initializing a SmartCard-HSM EA+ via the PKCS#11 interface with versions before 72e25db, then the PIN is configured so that unblocking the PIN using the SO-PIN is disabled.

When doing initialization with sc-hsm-tool, the PIN can be unblocked using the SO-PIN.

The issue is caused by a security feature introduced with version 2.0 of the SmartCard-HSM, which allows to disable the PIN unblock. This is controlled by bit 1 of the initialization options, where 1 enables unblocking, while 0 disables the options. In past versions of the tool-chain, bit 1 was always set to 1, so it was expected that existing code would not break the behaviour between 2.0 and previous version.

Unfortunately there was a bug in card-sc-hsm.c, which caused bit 1 to be 0 in all cases.

A fix is to move to versions past 72e25db or use sc-hsm-tool or the KeyManager for initialization.

**Comment by frankmorgner** [comment]
So technically this problem is fixed. It's just  a new release that's needed.

**Comment by CardContact** [comment]
Yes, the issue has been added for documentation and reference.
