### ISSUE TITLE
I cannot create new keys on Rutoken ECP after deleting old one via PKCS#11/pkcs15-init

### ISSUE THREAD

**Issue by ya-isakov** [OpenSC/OpenSC#671]
Hello! So, it seems that I cannot generate new keys after deleting any of existing ones. Problem can be reproduced 100%. I'm using opensc-0.15.0 with patches 
6b2fcf825f6e6203c51791f4a45f351b7c3a312f and e1a3bf8805f712a0c99a8fa8fa1b2d8f3aa9428b applied.
Here is the flow:

```
yar@yar ~ $ pkcs15-init --erase-card -p rutoken_ecp
Using reader with a card: Aktiv Rutoken ECP 00 00
yar@yar ~ $ pkcs15-init --create-pkcs15
Using reader with a card: Aktiv Rutoken ECP 00 00
New Security Officer PIN (Optional - press return for no PIN).
Please enter Security Officer PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
yar@yar ~ $ pkcs15-init --store-pin --label "User PIN" --auth-id 02  --finalize
Using reader with a card: Aktiv Rutoken ECP 00 00
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Security officer PIN [Security Officer PIN] required.
Please enter Security officer PIN [Security Officer PIN]:
yar@yar ~ $ pkcs15-init -G rsa/1024 --auth-id 02 --label "t" --public-key-label "t"
Using reader with a card: Aktiv Rutoken ECP 00 00
User PIN [User PIN] required.
Please enter User PIN [User PIN]:
yar@yar ~ $ pkcs11-tool -l -b -a t -y pubkey
Using slot 1 with a present token (0x1)
Logging in to "Rutoken ECP (User PIN)".
Please enter User PIN: 
yar@yar ~ $ pkcs11-tool -l -b -a t -y privkey
Using slot 1 with a present token (0x1)
Logging in to "Rutoken ECP (User PIN)".
Please enter User PIN: 
yar@yar ~ $ pkcs15-init -G rsa/1024 --auth-id 02 --label "t" --public-key-label "t"
Using reader with a card: Aktiv Rutoken ECP 00 00
User PIN [User PIN] required.
Please enter User PIN [User PIN]: 
Failed to generate key: File already exists
```
Here are the logs with debug:
[1-genkey.txt](https://github.com/OpenSC/OpenSC/files/129076/1-genkey.txt)
[2-list-objects.txt](https://github.com/OpenSC/OpenSC/files/129075/2-list-objects.txt)
[3-remove-pubkey.txt](https://github.com/OpenSC/OpenSC/files/129077/3-remove-pubkey.txt)
[4-remove-privkey.txt](https://github.com/OpenSC/OpenSC/files/129080/4-remove-privkey.txt)
[5-list-objects.txt](https://github.com/OpenSC/OpenSC/files/129078/5-list-objects.txt)
[6-genkey.txt](https://github.com/OpenSC/OpenSC/files/129079/6-genkey.txt)

Deleting via pkcs15-init -D privkey,pubkey --id .... also leads to the same problem.

**Comment by frankmorgner** [comment]
Has this been supported/tested previously?

The code for RuToken-ECP has not been changed since 5 years... @viktorTarasov do have any suggestions?

**Comment by sfff** [comment]
> Has this been supported/tested previously?
> The code for RuToken-ECP has not been changed since 5 years...

I think this has been always. 

[rtecp_store_key](https://github.com/OpenSC/OpenSC/blob/6b2fcf825f6e6203c51791f4a45f351b7c3a312f/src/pkcs15init/pkcs15-rtecp.c#L641) makes two RSF-files ([private key](https://github.com/OpenSC/OpenSC/blob/6b2fcf825f6e6203c51791f4a45f351b7c3a312f/src/pkcs15init/pkcs15-rtecp.c#L379) and [public key](https://github.com/OpenSC/OpenSC/blob/6b2fcf825f6e6203c51791f4a45f351b7c3a312f/src/pkcs15init/pkcs15-rtecp.c#L400)), but [sc_pkcs15init_delete_object](https://github.com/OpenSC/OpenSC/blob/6b2fcf825f6e6203c51791f4a45f351b7c3a312f/src/pkcs15init/pkcs15-lib.c#L2970) remove private key only. Need to symmetrical implementation of [delete](https://github.com/OpenSC/OpenSC/blob/6b2fcf825f6e6203c51791f4a45f351b7c3a312f/src/pkcs15init/pkcs15-rtecp.c#L647).
