### ISSUE TITLE
NFC Contactless card reader SCL-3711 not recognized?

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#672]
Mac OS X 10.11.3, Xcode-7.2.1.

It looks like OpenSC (the current Github version) does not recognize contactless (NFC) card reader `SCL-3711 NFC&RW`. 

`libnfc` package recognizes it and can access the card when placed next to it.

It would be great if this card could be supported by the `opensc-pkcs11.so` library and the CLI like `pkcs11-tool`.

**Comment by LudovicRousseau** [comment]
OpenSC does not use libnfc.
Your reader need to be accessible using PC/SC.

Maybe your SCM reader can be used using my CCID driver. Please follow http://pcsclite.alioth.debian.org/ccid.html#CCID_compliant

**Comment by mouse07410** [comment]
> OpenSC does not use libnfc.

Yes, I know. I brought `libnfc` up to demonstrate that the reader is alive, and at least some apps can see it on Mac OS X.

> Maybe your SCM reader can be used using my CCID driver

I should follow the instruction on your Web page, and install the current CCID driver, overwriting the old/original one on 10.11.3, correct?

**Comment by mouse07410** [comment]
Installing `ccid-1.4.22.tar.bz2` and running `sudo ./src/parse` I got:
```
$ sudo ./src/parse
Parsing USB bus/device: 04E6:5591 (bus 160, device 13)
 idVendor:  0x04E6  iManufacturer: SCM Micro
 idProduct: 0x5591  iProduct: SCL3711-NFC&RW
  NOT a CCID/ICCD device
Parsing USB bus/device: 04E6:5116 (bus 160, device 12)
 idVendor:  0x04E6  iManufacturer: SCM Microsystems Inc.
 idProduct: 0x5116  iProduct: SCR3310 v2.0 USB SC Reader
  Found a CCID/ICCD device at interface 0
 idVendor: 0x04E6
  iManufacturer: SCM Microsystems Inc.
 idProduct: 0x5116
.........
```

So it appears that CCID doesn't recognize this reader. It also looks like `SCL010` contactless reader is explicitly disabled?

This is what I found about it (not much):
[manual](http://www.identive-infrastructure.com/fileadmin/products/datasheets/SCL3711.MANUAL.VER13.pdf)
[data sheet](http://www.identiveusa.com/docs/Dat_SCL3711_e.pdf)

**Comment by frankmorgner** [comment]
There is https://github.com/nfc-tools/ifdnfc which is not (yet) ported to OS X

**Comment by mouse07410** [comment]
@frankmorgner I'm sorry I don't fully understand how it would integrate with OpenCS. Would the user need to do something extra? Or just install OpenSC and this `ifdnfc`? Right now I installed `libnfc` (it works fine with Mac OS X), which only showed that the reader is accessible by it. But the goal is to get OpenSC libraries and CLI working with that reader...

So could you please clarify for me what the plans are, and how it's supposed to merge and evolve?

**Comment by frankmorgner** [comment]
OS X runs (some version of) pcscd. ifdnfc is a driver for pcscd, which lets you access your reader via libnfc. pcscd provides access to the reader for OpenSC via PC/SC. The call stack looks something like this:
```
OpenSC <=(PC/SC)=> pcscd <==> ifdnfc <=(libnfc)=> SCL-3711 <=(NFC)=> card
```

**Comment by mouse07410** [comment]
I see, thanks. So when `ifdnfc` gets ported to Mac, this whole chain would (probably :) ) start working.

**Comment by LudovicRousseau** [comment]
@mouse07410 It looks like your SCL3711-NFC&RW is not CCID compliant. So my CCID driver will not help. The ifdnfc project is the solution.

If you have a SCL010 it _may_ work. See https://pcsclite.alioth.debian.org/ccid/shouldwork.html#0x04E60x5291 and https://pcsclite.alioth.debian.org/ccid/disabled.html#0x04E60x5291

**Comment by mouse07410** [comment]
> It looks like your SCL3711-NFC&RW is not CCID compliant. So my CCID driver will not help. 

I see. Sorry to hear that, but if it's not CCID-compliant, CCID driver can't possibly help...

> The ifdnfc project is the solution.

Great, so there is some hope.

> If you have a SCL010 it *may* work

This SCL3711 device was given to me at work. Somebody on the Net mentioned that he has Gemalto contactless reader that works with OpenSC and `yubico-piv-tool` flawlessly. So if I do change the hardware, I'd go for the proven reader.

Thanks!

**Comment by dengert** [comment]
Note that the yubico-piv-tool is designed to work with Yubico devices. Other devices may have a different vendor interface.

Early Yubico devices treated contact and contactless devices the same the same despite the PIV requirements.
The latest 4 series of Yubico devices follow the PIV standard in regards to contact vs contactless devices.

One would expect that the card would be administered via the contact interface anyway.

As I said before, the ACR122U reader is CCID and works PCSC and PIV cards and Yubico. (I have not tried it with MacOS._

http://www.acs.com.hk/en/press-release/198/acr122-the-worlds-first-nfc-felica-card-reader-with-compliance-to-ccid-standard/


On 2/16/2016 8:49 PM, Mouse wrote:
>     It looks like your SCL3711-NFC&RW is not CCID compliant. So my CCID driver will not help.
>
> I see. Sorry to hear that, but if it's not CCID-compliant, CCID driver can't possibly help...
>
>     The ifdnfc project is the solution.
>
> Great, so there is some hope.
>
>     If you have a SCL010 it /may/ work
>
> This SCL3711 device was given to me at work. Somebody on the Net mentioned that he has Gemalto contactless reader that works with OpenSC and |yubico-piv-tool| flawlessly. So if I do change the
> hardware, I'd go for the proven reader.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/672#issuecomment-184987586>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> Note that the yubico-piv-tool is designed to work with Yubico devices.
> Other devices may have a different vendor interface.

Sure. The idea is - if you put a Yubico device in NFC reach of the reader, `yubico-piv-tool` would be able to talk to it. As another user testified in another thread.

> The latest 4 series of Yubico devices follow the PIV standard in regards to
> contact vs contactless devices.

Yep - Yubikey 4 has no NFC at all. Perfect PIV compliance. :-)

> One would expect that the card would be administered via the contact interface anyway.

I agree. 

> As I said before, the ACR122U reader is CCID and works PCSC and PIV
> cards and Yubico. (I have not tried it with MacOS.)

If the reader we'd get next is ACR122U - I'd be able to verify that it works (or doesn't work) with Mac.

**Comment by mouse07410** [comment]
@frankmorgner just one question. Is there any work being done on https://github.com/nfc-tools/ifdnfc? it seems that it's been stale for several years...?

**Comment by frankmorgner** [comment]
I am not aware that anyone is working on this. It could be that ifdnfc "just works", at least in the configuration it was designed for (Linux/pcscd). I think it's not so difficult to port it to OS X, but your fastest solution should still be a different reader.

**Comment by mouse07410** [comment]
@frankmorgner I tried compiling https://github.com/nfc-tools/ifdnfc on Mac, the configuration fails with:
```
$ ./configure
...
checking for clang option to accept ISO C89... (cached) none needed
checking whether clang understands -c and -o together... (cached) yes
checking dependency style of clang... (cached) gcc3
checking how to run the C preprocessor... clang -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNFC... yes
configure: WARNING: libpcsclite > 1.4.102 not found by pkg-config
checking winscard.h usability... no
checking winscard.h presence... no
checking for winscard.h... no
configure: error: winscard.h not found, install libpcsclite > 1.4.102 or use ./configure PCSC_CFLAGS=...
$
```

Would you have any suggestion how to proceed? This is a standard Mac OS X installation, except that I've added OpenSC (in /Library) and libnfc (in /opt/local).

Thanks!

**Comment by frankmorgner** [comment]
You need to specify the PC/SC headers by hand. For reference, this is how OpenSC detects them:
```
					SDKS_PATH="$(xcode-select --print-path)/Platforms/MacOSX.platform/Developer/SDKs"
					if test -d $SDKS_PATH; then
					    SDK_PATH="${SDK_PATH:-$SDKS_PATH/$(ls -1 ${SDKS_PATH} | sort -n -t. -k2 -r | head -1)}"
					    PCSC_CFLAGS="-I$SDK_PATH/System/Library/Frameworks/PCSC.framework/Versions/Current/Headers"
					else
					    PCSC_CFLAGS="-I/System/Library/Frameworks/PCSC.framework/Headers"
					fi
```
I am not sure, but maybe simply specifying `-framework PCSC` could also be enough...

**Comment by frankmorgner** [comment]
Please let's continue the discussion here https://github.com/nfc-tools/ifdnfc/issues/3
