### ISSUE TITLE
Wrong SO-PIN in SmartCard-HSM after changing with pkcs11-tool --change-PIN

### ISSUE THREAD

**Issue by CardContact** [OpenSC/OpenSC#674]
Steps to reproduce

pkcs11-tool --module /usr/local/lib/opensc-pkcs11.so --login --login-type so --so-pin 3537363231383830 --change-pin --new-pin 0123456789ABCDEF
sc-hsm-tool --initialize --so-pin 0123456789ABCDEF --pin 648219

fails with invalid SO-PIN.

**Comment by scottthomas007** [comment]
It works good on my environment. Here is an example
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --login --login-type so --so-pin 3537363231383830 --change-pin --new-pin 3537363231383838
Using slot 1 with a present token (0x1)
PIN successfully changed

C:\Program Files\OpenSC Project\OpenSC\tools>sc-hsm-tool --initialize --so-pin 3537363231383838 --pin 12345678 --pin-retry 10 --label "Scott Thomas" --reader 0

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-tool.exe -D
Using reader with a card: Gemplus USB Smart Card Reader 0
PKCS#15 Card [Scott Thomas]:
        Version        : 0
        Serial number  : XXXXXXXX
        Manufacturer ID: www.CardContact.de
        Flags          : PRN generation

PIN [UserPIN]
        Object Flags   : [0x3], private, modifiable
        ID             : 01
        Flags          : [0x81A], local, unblock-disabled, initialized, exchangeRefData
        Length         : min_len:6, max_len:15, stored_len:0
        Pad char       : 0x00
        Reference      : 129 (0x81)
        Type           : ascii-numeric
        Tries left     : 3

PIN [SOPIN]
        Object Flags   : [0x1], private
        ID             : 02
        Flags          : [0x9E], local, change-disabled, unblock-disabled, initialized, soPin
        Length         : min_len:16, max_len:16, stored_len:0
        Pad char       : 0x00
        Reference      : 136 (0x88)
        Type           : bcd
        Tries left     : 3

**Comment by CardContact** [comment]
The issue only surfaces if the SO-PIN contains hexadecimal characters A to F, which is valid for the SmartCard-HSM. Characters A-F are mapped to 1-6, so a SO-PIN  0123456789ABCDEF is actually encoded and stored as 0123456789123456 when using pkcs11-tool. As OpenSC does this consistently, the problem is only detected if other tools (like sc-hsm-tool) are used with such a SO-PIN.

Our advise to affected users is to try a the converted SO-PIN, if the hex values does not work (Replace A-1,B-2,C-3,D-4,E-5,F-6). Please remember, that the SO-PIN has a retry counter of 15, so the number of attempts before irreversible blocking the device are limited.

**Comment by gertvdijk** [comment]
@CardContact Does the translation also applies if lowercase characters were used during initialisation of the card? e.g. `0123456789abcdef`

**Comment by CardContact** [comment]
Yes, it applies to both, lower and uppercase characters.

**Comment by gertvdijk** [comment]
@CardContact Thanks. And sorry to use this closed bug report for another related question.

Is there a way to determine the current retry counter of the SO-PIN? I have one card that might be affected by this issue (user pin locked, SO PIN needed). Workaround with remapped hex->decimal appears not to work as well, but it might be a security feature not to tell the user the SO-PIN max retry counter has been reached.

Attempting to change the SO-PIN to something deterministic I upgraded to OpenSC 0.16 and did this (from https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM):

    pkcs11-tool --login --login-type so --so-pin 3537363231383830 --change-pin --new-pin 0123456789012345

returns

    Using slot 0 with a present token (0x0)
    error: PKCS11 function C_SetPIN failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)

although "function not supported" error type, with a different SO-PIN length it returns

    Using slot 0 with a present token (0x0)
    error: PKCS11 function C_SetPIN failed: rv = CKR_PIN_LEN_RANGE (0xa2)

SO-PIN retry counter as shown by `pkcs15-tool -D` is always 15 (on all my cards, even with this one with failed attempts). It might have been irreversibly blocked already, but how can I tell?

**Comment by CardContact** [comment]
Starting with V2.0, the SmartCard-HSM reports the SO-PIN status in sc-hsm-tool. For V1.2 this feature is not available.
