### ISSUE TITLE
SmartCard-HSM: Error Generating Private Key on Smart card through OpenSC PKCS11 Module

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#681]
I am trying to generate private key on SmartCard-HSM but its showing that it is unsupported. I tried to generate the private key through OpenSC PKCS11 module 

It generated the error popup "The procedure entry point sc_error could not ve located in the dynamic link library opensc.dll" 

It also generated the following error 

C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool -l --pin 12345678 --key 
pairgen --key-type rsa:1024 --id 10 -label "KEY" --module C:\WINDOWS\system32\opensc-pkcs11.dll 
sc_dlopen failed: LoadLibrary/GetProcAddress failed 
error: Failed to load pkcs11 module 
Aborting. 

What's this issue, can't we generate a key on SmartCard-HSM ?????

**Comment by CardContact** [comment]
What version of OpenSC did you install ? What version of Windows are you using ? Is this a 32 or 64 bit version ? Did you install the 32 or 64 bit version of OpenSC.

Seems to me like the dll does not match the executable.

**Comment by scottthomas007** [comment]
OpenSC version: 0.15 32bit
OS Version XP SP2 32bit

**Comment by scottthomas007** [comment]
An old library smart card bundle was creating issue. Uninstalled scb and reinstalled the OpenSC and got it working now. Thanks mate
