### ISSUE TITLE
The NSS workaround in pkcs11-global.c causes problems for NSS

### ISSUE THREAD

**Issue by mozkeeler** [OpenSC/OpenSC#683]
In pkcs11-global.c (C_GetSlotList), there is the following code:

```
	if (pSlotList == NULL_PTR && sc_pkcs11_conf.plug_and_play) {
		/* Trick NSS into updating the slot list by changing the hotplug slot ID */
		sc_pkcs11_slot_t *hotplug_slot = list_get_at(&virtual_slots, 0);
		hotplug_slot->id--;
		sc_ctx_detect_readers(context);
	}
```

This changes the id of a preexisting slot, making all existing references to it invalid. Unfortunately, NSS doesn't do a good job of handling this, and it looks like it would be a fair amount of work to address. Furthermore, it's not clear that this is allowed by the PKCS 11 standard. (There are comments in NSS code that say removing slots is not allowed - only adding them is. I haven't found anything in the spec document itself to support this, except it does say that ids returned by C_GetSlotList must be valid as inputs for C_GetSlotInfo, but it's not clear for how long.)
Finally, the reason for this workaround (see https://github.com/OpenSC/OpenSC/commit/0244baa494ecf80c0f3b2eb5bffc70f3f6511625 ) does not appear to be valid any longer - NSS does in fact call C_GetSlotList with a NULL pSlotList parameter and then again with a non-NULL one (see https://dxr.mozilla.org/mozilla-central/rev/d5daf10d3b74b04e8fa63c4e5429de8a0adf79f8/security/nss/lib/pk11wrap/pk11util.c#908 ).

**Comment by frankmorgner** [comment]
Have you tested NSS with the suggested changes? Could you make a pull request?

**Comment by frankmorgner** [comment]
And what is the actual problem you encountered with the current version of OpenSC?

**Comment by mozkeeler** [comment]
The STR is to load onepin-opensc-pkcs11.so in a debug build of Firefox (about:preferences -> Advanced -> Certificates -> Security Devices -> Load) and then insert a device that will be recognized by OpenSC. Upon closing that window (or closing Firefox), an assertion in NSS will fail. This is basically caused by the reference counting on the memory object tracking the PKCS11 slot going wrong. To be sure, I think NSS should handle this situation more gracefully, but since this workaround was added for NSS in the first place, it seems strange to keep it around when it causes problems.

**Comment by mozkeeler** [comment]
As far as I can tell, #687 fixes the issue (and again, NSS does appear to pick up changes in the slot list).

**Comment by frankmorgner** [comment]
closed with https://github.com/OpenSC/OpenSC/commit/1fb741338a010515b35f28cd9c769561f3e574a2
