### ISSUE TITLE
OpenSC pkcs11-tool.exe command fails in C# Applications

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#684]
Hi, i generate key through command prompt. It works fine.
pkcs11-tool -l --pin 12345678 --keypairgen --key-type rsa:1024 --id 10 —label "KEY"

But when i try to integrate this command in my C# application, then it generates the following error.
**Cannot set FMODE to O_BINARY**

The C# code that i am using is 
Process myProcess = new Process();
            myProcess.StartInfo.FileName = "C:\\Program Files\\OpenSC Project\\OpenSC\\tools\\pkcs11-tool.exe";
            myProcess.StartInfo.RedirectStandardOutput = true;
            myProcess.StartInfo.RedirectStandardError = true;
            myProcess.StartInfo.UseShellExecute = false;
			myProcess.StartInfo.Arguments = " -l --pin 12345678 --keypairgen --key-type  rsa:2048 --id 10 ";
            myProcess.StartInfo.CreateNoWindow = true;
            myProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
            myProcess.Start();
            string output2 = myProcess.StandardOutput.ReadToEnd();
            string output_error = myProcess.StandardError.ReadToEnd();
            myProcess.WaitForExit();

**Comment by scottthomas007** [comment]
There is a development thread page that shows the error information, but i can't understand it.

https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c

**Comment by scottthomas007** [comment]
When i tried to store user certificate on the SC-HSM card through pkcs11-tool.exe command
pkcs11-tool -l --pin 12345678 --write-object deviceA.der --type cert --id 10

It generated the same error.
Cannot set FMODE to O_BINARY
other commands such as opensc-tool.exe and pkcs15-tool.exe are working perfectly fine.

**Comment by dengert** [comment]
Do you need a myProcess.StartInfo.RedirectStandardInput = true;
pkcs11-tool has these lines:
if(_setmode(_fileno(stdin), _O_BINARY ) == -1)
	util_fatal("Cannot set FMODE to O_BINARY");

O_Binary is a Windows thing only, as in linux and posix there is no difference in a binary file and a text file.
In Windows uses CR/LF for end of line in text files.

You may need to call _setmode from the C++ code befiore the process starts.

These might be helpful:

   https://msdn.microsoft.com/en-us/library/tw4k6df8.aspx
   https://lists.samba.org/archive/rsync/2003-January/004895.html




On 2/20/2016 3:36 AM, scottthomas007 wrote:
> Hi, i generate key through command prompt. It works fine.
> pkcs11-tool -l --pin 12345678 --keypairgen --key-type rsa:1024 --id 10 —label "KEY"
>
> But when i try to integrate this command in my C# application, then it generates the following error.
> *Cannot set FMODE to O_BINARY*
>
> The C# code that i am using is
> Process myProcess = new Process();
> myProcess.StartInfo.FileName = "C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe";
> myProcess.StartInfo.RedirectStandardOutput = true;
> myProcess.StartInfo.RedirectStandardError = true;
> myProcess.StartInfo.UseShellExecute = false;
> myProcess.StartInfo.Arguments = " -l --pin 12345678 --keypairgen --key-type rsa:2048 --id 10 ";
> myProcess.StartInfo.CreateNoWindow = true;
> myProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
> myProcess.Start();
> string output2 = myProcess.StandardOutput.ReadToEnd();
> string output_error = myProcess.StandardError.ReadToEnd();
> myProcess.WaitForExit();
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/684>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by scottthomas007** [comment]
Adding myProcess.StartInfo.RedirectStandardInput = true; before the command execution worked for me.Thanks bro.
