### ISSUE TITLE
pkcs11-tool.exe Problem with --reader 1 switch

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#685]
I generate key with the following pkcs11-tool.exe command
pkcs11-tool -l --pin 12345678 --keypairgen --key-type rsa:1024 --id 10 —label "KEY"
But this command works for only 1 smart card reader. 
If i attach 2 smart card readers then adding --reader 1 switch generates error that --reader is an unrecognized option. 
What can be the alternate switch to use 2nd smart card reader?

**Comment by dengert** [comment]
pkcs11 has the concept of a slots, not readers.
Multiple slots can be used with the same token.

pkcs11-tool -L
Available slots:
Slot 0 (0xffffffffffffffff): Virtual hotplug slot
   (empty)
Slot 1 (0x1): SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
   token label        : PIV_II (PIV Card Holder pin)
   token manufacturer : piv_II
   token model        : PKCS#15 emulated
   token flags        : rng, login required, PIN initialized, token initialized
   hardware version   : 0.0
   firmware version   : 0.0
   serial num         : b75b00144f1f5ef4
Slot 2 (0x5): ACS ACR122U PICC Interface 01 00
   token label        : PIV_II (PIV Card Holder pin)
   token manufacturer : piv_II
   token model        : PKCS#15 emulated
   token flags        : rng, login required, PIN initialized, token initialized
   hardware version   : 0.0
   firmware version   : 0.0
   serial num         : c9d45c86501843e2



On 2/21/2016 3:49 AM, scottthomas007 wrote:
> I generate key with the following pkcs11-tool.exe command
> pkcs11-tool -l --pin 12345678 --keypairgen --key-type rsa:1024 --id 10 —label "KEY"
> But this command works for only 1 smart card reader.
> If i attach 2 smart card readers then adding --reader 1 switch generates error that --reader is an unrecognized option.
> What can be the alternate switch to use 2nd smart card reader?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/685>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by scottthomas007** [comment]
Thanks, It worked.
