### ISSUE TITLE
Hide Manufacturer details from Smart Card

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#690]
pkcs15-tool.exe  shows the Manufacturer ID and smart card type details, how can we hide it or modify it to custom values?

**Comment by LudovicRousseau** [comment]
Why do you want to hide this information?

**Comment by frankmorgner** [comment]
Again, everything is possible (though maybe questionable), if and only if you modify the card.

**Comment by dengert** [comment]
See my reply to https://github.com/OpenSC/OpenSC/issues/689

On 2/25/2016 10:17 PM, Scott Thomas wrote:
> pkcs15-tool.exe shows the Manufacturer ID and smart card type details, how can we hide it or modify it to custom values?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/690>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by martinpaljak** [comment]
This is not a meaningful request for OpenSC. Any kind of data hiding needs to happen on the card side for a specific card and any security through obscurity on the host (OpenSC) side can be achieved (but of course is not recommended) by custom OpenSC builds.
