### ISSUE TITLE
Compile in version number

### ISSUE THREAD

**Issue by hexum** [OpenSC/OpenSC#691]
Please add info about version in executable files and add flag to easily get it.
It's really can help in bug reporting on systems like Gentoo in case of installing from git.
When you install from ebuild-9999 you can't be quite sure about last commit reference number.

Thanks!

(Now I'm adding opensc-9999 to portage tree to make master version testing easy for gentoo users)

**Comment by hexum** [comment]
Gentoo ebuilds adding request.
https://bugs.gentoo.org/show_bug.cgi?id=575770

**Comment by martinpaljak** [comment]
There is `opensc-tool --info`, do you mean something different?

**Comment by hexum** [comment]
People first try to find out version number with options -v, -V or similar. Option --info is strange but OK.
I've just installed version 0.16.0_pre1 and --info shows 0.15.0. What will it show me when I install version from git? To make correct bug report I need to have git ref number...

**Comment by frankmorgner** [comment]
@hexum please make a pull request with your suggestion

**Comment by hexum** [comment]
OK, I will think about t at weekends.
I have little C experience, so it will take some time.

**Comment by viktorTarasov** [comment]
Possibility to get revision number of installed package was missing for a long time.
I propose to return as result of _-v_ the _git describe_ and date of last commit.

Something like this: viktorTarasov@dd823ad07c7c94b37c7fc62a322925c35bacc7b3

@hexum 
> I've just installed version 0.16.0_pre1 and --info shows 0.15.0.

It will be fixed with the first RC of 0.16.0

**Comment by viktorTarasov** [comment]
@hexum 
Sorry, I intercepted this issue with a PR #697.
It implies not only _C_, but also _autoconf_, _git_ and other more local issues.

@frankmorgner 
I propose to transfer discussion onto PR #697.

**Comment by hexum** [comment]
Great!

**Comment by viktorTarasov** [comment]
closed with 1c0ab2a2d213f38ae8fd016159669cd1fc6a134c
