### ISSUE TITLE
Rutoken ECP 2.0: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)

### ISSUE THREAD

**Issue by hexum** [OpenSC/OpenSC#693]
Can't sign data with Rutoken ECP 2.0

OpenSC version 0.16.0_pre1.
```
How to repoduce:
pkcs15-init --erase-card -p rutoken_ecp
pkcs15-init --create-pkcs15
pkcs15-init --store-pin --label "hexum" --id 02
pkcs15-init -G rsa/2048 --auth-id 02 --label "homeserver" --public-key-label "homeserver.pub"
```

```
pkcs15-tool -D
...
Private RSA Key [homeserver]
        Object Flags   : [0x3], private, modifiable
        Usage          : [0x4], sign
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        ModLength      : 2048
        Key ref        : 1 (0x1)
        Native         : yes
        Path           : 3f001000100060020001
        Auth ID        : 02
        ID             : 3b22ad5f956a4a51e46a5f426afbe280d86ac509
        MD:guid        : {e7600859-c83f-627c-7317-8e2cda8cabba}
...
```
[pkcs11_spy.txt](https://github.com/OpenSC/OpenSC/files/149624/pkcs11_spy.txt)

```
pkcs11-tool -l -s -m SHA256-RSA-PKCS --id 3b22ad5f956a4a51e46a5f426afbe280d86ac509 -i i --module /usr/lib64/pkcs11-spy.so
Using slot 1 with a present token (0x1)
Logging in to "Rutoken ECP (hexum)".
Please enter User PIN: 
Using signature algorithm SHA256-RSA-PKCS
error: PKCS11 function C_SignFinal failed: rv = CKR_GENERAL_ERROR (0x5)

Aborting.
```

file i - random 256 byte file.
Attached pkcs11_spy.txt - file with psy log.

**Comment by hexum** [comment]
Please guide me to do further diagnostics.

**Comment by mouse07410** [comment]
Please try signing a file of 245 bytes (or even smaller), and report the result.

**Comment by mouse07410** [comment]
Actually, based in the algorithm you selected, try a 32-byte file and report the result.

**Comment by hexum** [comment]
Thank you for answer!

I've run singing it with 32 byte long file.
```
ls -lh 32b_random
-rw-r--r-- 1 hexum hexum 32 фев 28 11:42 32b_random

OPENSC_DEBUG=9 pkcs11-tool -l -s -m SHA256-RSA-PKCS --id 3b22ad5f956a4a51e46a5f426afbe280d86ac509 -i 32b_random --module /usr/lib64/pkcs11-spy.so
```

[pkcs11_spy_32b.txt](https://github.com/OpenSC/OpenSC/files/149818/pkcs11_spy_32b.txt)

**Comment by hexum** [comment]
Strange place in console debug output.
[debug9_log.txt](https://github.com/OpenSC/OpenSC/files/150024/debug9_log.txt)
[debug9_log.txt](https://github.com/OpenSC/OpenSC/files/150025/debug9_log.txt)


```
0x7fe0bbf3f700 20:51:28.234 [opensc-pkcs11] iso7816.c:126:iso7816_check_sw: Unknown SWs; SW1=69, SW2=89
0x7fe0bbf3f700 20:51:28.234 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fe0bbf3f700 20:51:28.234 [opensc-pkcs11] card-rtecp.c:382:rtecp_cipher: APDU transmit failed: Card command failed
```

**Comment by mouse07410** [comment]
First, with pkcs11-tool you don't need to use pkcs11-spy. Second, it appears that you fail to unlock the token, somehow. The way I interpret the log, PIN unlocking fails. I'll let somebody more experienced than myself take it from here.

**Comment by hexum** [comment]
When I use wrong pin error CKR_PIN_INCORRECT rises insted of CKR_GENERAL_ERROR.
So the error in other place.

**Comment by viktorTarasov** [comment]
Try _master_.

"It works for me" with actual _master_ and card _"Aktiv Rutoken ECP", ATR:3B 8B 01 52 75 74 6F 6B 65 6E 20 44 53 20 C1_

**Comment by hexum** [comment]
I've installed latest version and repeated all steps.
The error kept the same.
```
Using reader with a card: Aktiv Rutoken ECP 00 00
3b:8b:01:52:75:74:6f:6b:65:6e:20:44:53:20:c1
```

**Comment by viktorTarasov** [comment]
I do not see any outstanding difference in two logs.

There is my command sequence.:
```
./build/bin/pkcs15-init --erase-card
./build/bin/pkcs15-init -C --label "OT-RuToken" -P --auth-id 02 --so-pin "87654321" --so-puk "" --pin "12345678" --finalize
./build/bin/pkcs15-init -G rsa/1024 --pin 12345678 --auth-id 02 --label "RSA 1024"
./build/bin/pkcs15-init -G rsa/2048 --pin 12345678 --auth-id 02 --label "RSA 2048"
./build/bin/pkcs11-tool --module ./build/lib/opensc-pkcs11.so -l -s -m SHA256-RSA-PKCS --id 3228192c204855dbde29c5aca174194c8ce08a01 -i ../test-data/data-24bytes.txt
./build/bin/pkcs11-tool --module ./build/lib/opensc-pkcs11.so -M
./build/bin/pkcs11-tool --module ./build/lib/opensc-pkcs11.so -l -s -m SHA256-RSA-PKCS --id 81e0a95372252e485dd7a2eac201ec7115a3f70a -i ../test-data/data-256bytes.txt 
```

Try to add _--finalize_ to your init token command.

**Comment by sfff** [comment]
> Try to add --finalize to your init token command.

Absolutly right. Use ['--finalize'](https://github.com/OpenSC/OpenSC/wiki/Aktiv-Co.-Rutoken-ECP#initialize-pkcs15-init---erase-card--p-rutoken_ecp-pkcs15-init---create-pkcs15---so-pin-87654321---so-puk--pkcs15-init---store-pin---label-user-pin---auth-id-02---pin-12345678---puk----so-pin-87654321---finalize-pkcs15-tool--dusing-reader-with-a-card-aktiv-rutoken-ecp-00-00pkcs15-card-rutoken-ecpversion---------0serial-number---000000002cdb7256manufacturer-id-aktiv-colast-update-----20121114083252zflags-----------eid-compliant) to set card state with allowed sign.

**Comment by hexum** [comment]
Thats work!
I did not add it at pin creation state. I've just run `pkcs15-init --finalize` with that I had and magic happened.
Now I can sign data and pass ssh authentication.
I still can add new keys. What thing was finalized? What is the purpose of this option?

**Comment by viktorTarasov** [comment]
> What thing was finalized?
 
Not sure about details for RuToken, but _finalized_ activates the ACLs of the files, objects, ... that were created during init/personalization phase. Without it you still can access (create, update, ... not use) objects without authentication (by PIN for ex.).
Normally, in this state the crypto operations are not allowed.

Please, close the issue, if you consider that it was resolved.

**Comment by hexum** [comment]
Strange... PIN was asked every time.

Error CKR_GENERAL_ERROR is not clear for end user. Is there a way to clarify error message in case of not completed finalization?

**Comment by sfff** [comment]
> Not sure about details for RuToken, but finalized activates the ACLs of the files, objects, ...

Of course, It's true for Rutoken ECP


> Error CKR_GENERAL_ERROR is not clear for end user. Is there a way to clarify error message in case of not completed finalization?

Could you please propose [PKCS#11 error code](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.pdf) for this case? (see page 110: C_SignFinal Return values)

**Comment by hexum** [comment]
CKR_CRYPTOKI_NOT_INITIALIZED is best match I think.
But it's so sad to be limited with this spec. Furthermore it doesn't not define this constant meaning...
The best thing we can do is to print something like "You need to finalize token initialization. Please run pkcs11-tool --finalize to do so."

**Comment by viktorTarasov** [comment]
@hexum 
I am afraid you are asking too much. Sign operation returns something like 'internal-error', in better case 'not-allowed'. With there, on the upper framework level to guess that the token is not initialized...

@sfff
> Could you please propose PKCS#11 error code for this case?

Not only. You need to find an appropriate [sc-error](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/errors.h#L31) to associate it with SW 6989, returned by card, and then to associate this sc-error with CKR_XX.

Actually I do not see appropriate sc-error,
but it's true -- we always can add a new one and associate it with some CKR NOT-INITIALIZED.

**Comment by hexum** [comment]
If it will be done, we can start page with error description. I found nothing about error CKR_CRYPTOKI_NOT_INITIALIZED on the Internet.

**Comment by sfff** [comment]
@hexum 
> CKR_CRYPTOKI_NOT_INITIALIZED is best match I think.

Unfortunately, [PKCS#11 Spec Page 63](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.pdf):

> **CKR_CRYPTOKI_NOT_INITIALIZED:** This value can be returned by any function other than
C_Initialize and C_GetFunctionList. It indicates that the function cannot be executed because the
Cryptoki library has not yet been initialized by a call to **C_Initialize.**

**Comment by sfff** [comment]
@viktorTarasov 
> Not only. You need to find...

Yes of course. Thanks for details.

**Comment by hexum** [comment]
I will reopen this when I will be able to support development with patch.
