### ISSUE TITLE
OpenSC support for Oberthur-AuthentIC-applet-v3

### ISSUE THREAD

**Issue by Monloi** [OpenSC/OpenSC#711]
Hi folks,

I'm new to smart cards and I'm not sure if this is the right place to post but how can I make opensc run with Oberthur-AuthentIC-applet-v3 run? Can I simply alter the opensc.conf and add the card's AID and ATR?

For info the card's AID an ATR are as follows.
ATR: 3b:db:96:00:80:b1:fe:45:1f:83:00:31:c0:64:c7:fc:10:00:07:90:00:72
AID: A0 00 00 00 03 00 00 00
Model: Cosmo v7.0
Firmware: 3.22

Regards,
Mon

**Comment by dengert** [comment]
You can try it. The AID look like a GP2.1.1 generic AID, so don't do anything with it.

Modify line 291:
290         # Oberthur's AuthentIC v3.2.2
291         card_atr 3B:DD:18:00:81:31:FE:45:80:F9:A0:00:00:00:77:01:00:70:0A:90:00:8B {
292                 type = 11100;
293                 driver = "authentic";
294                 name = "AuthentIC v3.1";

and change to:
             card_atr 3b:db:96:00:80:b1:fe:45:1f:83:00:31:c0:64:c7:fc:10:00:07:90:00:72

The name says V3.1 but the code says it is for V3.2.



To get a debug trace change:
15         debug = 0;
to:
            debug = 9;

and uncomment:
22         # debug_file = /tmp/opensc-debug.log

If you send a debug file, note that the PIN and other information (but not private keys) may appear in the debug file.


On 3/15/2016 4:39 AM, Monloi wrote:
> Hi folks,
>
> I'm new to smart cards and I'm not sure if this is the right place to post but how can I make opensc run with Oberthur-AuthentIC-applet-v3 run? Can I simply alter the opensc.conf and add the card's
> AID and ATR?
>
> For info the card's AID an ATR are as follows.
> ATR: 3b:db:96:00:80:b1:fe:45:1f:83:00:31:c0:64:c7:fc:10:00:07:90:00:72
> AID: A0 00 00 00 03 00 00 00
> Model: Cosmo v7.0
> Firmware: 3.22
>
> Regards,
> Mon
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenSC/OpenSC/issues/711
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
@Monloi 
>  AID: A0 00 00 00 03 00 00 00

It's not the AID of Oberthur application, but AID of _"Card Manager"_ of java card, defined in _Global Platform_.

In your ATR there is AID: _A0:00:00:00:77:01:00:70:0A_. You can try, but as for me it's too short.

Maybe that you don't need to know the AID of your card -- the application is selected by default after _Power On_.

**Comment by Monloi** [comment]
If it doesnt work what should i do? Should i reset/reinitialize the card to remove the card manager? If thats an option, any way or tool to do that?

Mon

**Comment by Monloi** [comment]
Hi,

I have replaced the ATR for authentic in opensc.conf as per advised. It seems to be able to read the card but still opensc doesn't seem to fully support it. I tried creating a new PKCS structure but if failed and caused a windows error. See the output below and attached is the log.

c:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-init.exe -C
Using reader with a card: OMNIKEY CardMan 5x21 0
New Security Officer PIN (Optional - press return for no PIN).
Please enter Security Officer PIN: Please type again to verify: Unblock Code for
 New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): PIN too short (min 6 characters)
Please enter User unblocking PIN (PUK): Please type again to verify:
--> Windows encountered an error "opensc command line tool has stopped working".


[pkcs15-init-C-opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/175327/pkcs15-init-C-opensc-debug.txt)

**Comment by viktorTarasov** [comment]
Try to use 'oberthur' driver and not 'authentic'.
The type of the first is 'pkcs15 emulation' , the second creates two parallel file systems: one PKCS#15 of OpenSC, second native FS of Oberthur-AuthentIC.

There are few commands to test:
- pkcs15-init -E
- pkcs15-init -C --label "IDX-SCM" -P --auth-id 53434D --so-pin "12345678" --so-puk "123456" --pin "9999" --puk "8888"
- pkcs15-init -a 53434D --label "VTA Cert" -S ~/admin.p12 -f pkcs12 --passphrase opentrust  --so-pin "12345678" --pin "9999"
- pkcs15-init -S ..//tests/generarted_rsa_2048.pem -l "RSA 2048 D" -a 53434d --pin 9999 --split-key -u sign,decrypt,KeyAgreement --so-pin "12345678"
- pkcs15-init -G rsa1024 -l "Generated" -a 53434d --pin 9999 --so-pin "12345678"

**Comment by Monloi** [comment]
sorry, how do i do that? 

Can I simply change the driver 'authentic' to ''oberthur'? I tried this but go an error (see below). attached is the log file.
[pkcs15-init.exe-E-using-oberthur-driver.txt](https://github.com/OpenSC/OpenSC/files/177157/pkcs15-init.exe-E-using-oberthur-driver.txt)

c:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-init.exe -E
Using reader with a card: OMNIKEY CardMan 5x21 0
Failed to connect to card: Card is invalid or cannot be handled


Also, based on the logs I have submitted in the previous post, opensc seems to cycle to all the drivers (i.e. authentic and oberthur).

**Comment by viktorTarasov** [comment]
According to logs 
_Oberthur_ driver select _Card Manager_ to get chip info (serial, ..) and
then failed to select AID _A0 00 00 00 77 01 03 03 00 00 00 F1 00 00 00 02_ .

You should to find out the AID of the application on your card (in Windows, sniff usb when native minidriver is used, or Oberthur's MW ).

You can also try to modify sources and to not select _Card Manager_.
Big chances that AID of AuthentIC Application is selected by default.

**Comment by Monloi** [comment]
Hi,

I think have the AID of the card manager.
CKA_ID               	length = 20, value = 20 bytes	AA FD 04 39 C6 4E A0 77 19 CD DB 83 9B D3 12 14 47 A5 25 38 

What's next? Should I update the AID in authentic.profile fille?

I tried changing the AID in the authentic.profile and got the error below when doing opensc -E
c:\Program Files\OpenSC Project\OpenSC\tools>pkcs15-init.exe -E
Using reader with a card: OMNIKEY CardMan 5x21 0
Couldn't bind to the card: Syntax error
Here is the log for that action.
2016-03-18 10:20:46.114 Incorrect parameters P1-P2
2016-03-18 10:20:46.114 [pkcs15-init] card-authentic.c:807:authentic_select_file: authentic_select_file() check SW failed: -1205 (Incorrect parameters in APDU)
2016-03-18 10:20:46.130 [pkcs15-init] card.c:672:sc_select_file: 'SELECT' error: -1205 (Incorrect parameters in APDU)
2016-03-18 10:20:46.130 [pkcs15-init] profile.c:338:sc_profile_load: called
2016-03-18 10:20:46.130 Using profile directory 'C:\Program Files\OpenSC Project\OpenSC\profiles'.
2016-03-18 10:20:46.130 Trying profile file C:\Program Files\OpenSC Project\OpenSC\profiles\pkcs15.profile
2016-03-18 10:20:46.145 profile C:\Program Files\OpenSC Project\OpenSC\profiles\pkcs15.profile loaded ok
2016-03-18 10:20:46.145 [pkcs15-init] profile.c:395:sc_profile_load: returning with: 0 (Success)
2016-03-18 10:20:46.145 [pkcs15-init] profile.c:338:sc_profile_load: called
2016-03-18 10:20:46.145 Using profile directory 'C:\Program Files\OpenSC Project\OpenSC\profiles'.
2016-03-18 10:20:46.145 Trying profile file C:\Program Files\OpenSC Project\OpenSC\profiles\authentic.profile
2016-03-18 10:20:46.161 profile C:\Program Files\OpenSC Project\OpenSC\profiles\authentic.profile loaded ok
2016-03-18 10:20:46.161 [pkcs15-init] profile.c:390:sc_profile_load: returning with: -1501 (Syntax error)
2016-03-18 10:20:46.161 Failed to load profile 'authentic': Syntax error
2016-03-18 10:20:46.161 [pkcs15-init] pkcs15-lib.c:378:sc_pkcs15init_bind: Load profile error: -1501 (Syntax error)

Below is the entire log from Oberthur's software (AWP Manager)/card manager I believe.
016-03-11 14:14:11 (TID=6344)  [ObjectFunction.cpp:87]	 BEGIN C_GetAttributeValue(0x00000001, 0x00000001, 0x0445F7C4, 0x00000009)

	Object template to complete = 

		CKA_CLASS            	length = 4, value = unknown CKA_CLASS(0x0000003A)
		CKA_ID               	length = 20, value = 20 bytes	06 01 A4 00 C8 03 A4 00 C8 03 A4 00 01 00 00 00 00 00 00 00 
		CKA_KEY_TYPE         	length = 4, value = unknown CKA_KEY_TYPE(0x00000054)
		CKA_LABEL            	length = 28, value = p
		CKA_TOKEN            	length = 1, value = true
		CKA_PRIVATE          	length = 1, value = true
		CKA_MODIFIABLE       	length = 1, value = true
		CKA_MODULUS_BITS     	length = 4, value = 76
		CKA_ECDSA_PARAMS     	length = -1, value = null
	
	Object attribute returned : 
		CKA_CLASS            	length = 4, value = CKO_PRIVATE_KEY
		CKA_ID               	length = 20, value = 20 bytes	AA FD 04 39 C6 4E A0 77 19 CD DB 83 9B D3 12 14 47 A5 25 38 
		CKA_KEY_TYPE         	length = 4, value = CKK_RSA
		CKA_LABEL            	length = 28, value = AuthentiICV3 rsa Private key
		CKA_TOKEN            	length = 1, value = true
		CKA_PRIVATE          	length = 1, value = true
		CKA_MODIFIABLE       	length = 1, value = true
		CKA_MODULUS_BITS     	length = 4, value = 1024

**Comment by Monloi** [comment]
seems like I'm going in circles. Is there really hope in making my card work with opensc? seems like no matter what value I change, the libraries/drivers are too restrictive.

**Comment by Monloi** [comment]
Hi, my bad i used the wrong AID and wrong syntax. Now I have changed the AID in authentic.profile aid     = A0:00:00:00:03:00:00:00;.

I did a "pkcs15-init.exe -C --pin 0000 --puk 111111 --so-pin 2222 --so-puk 333333" and ends up with the Windows error again. Attached is the log.
A few more questions on the log.
1. Should I be worried about this error? if yes how to fix it?
2016-03-18 10:50:38.960 [pkcs15-init] card.c:392:sc_unlock: called
2016-03-18 10:50:38.960 Incorrect parameters P1-P2
2016-03-18 10:50:38.960 [pkcs15-init] card-authentic.c:807:authentic_select_file: authentic_select_file() check SW failed: -1205 (Incorrect parameters in APDU)
2016-03-18 10:50:38.960 [pkcs15-init] card.c:672:sc_select_file: 'SELECT' error: -1205 (Incorrect parameters in APDU)

2. how about this?
2016-03-18 10:50:38.882 [pkcs15-init] card.c:801:sc_card_ctl: called
2016-03-18 10:50:38.882 card_ctl(4) not supported
2016-03-18 10:50:38.882 called; type=2, path=3f0050154946

[opensc-after-aid-change.txt](https://github.com/OpenSC/OpenSC/files/179012/opensc-after-aid-change.txt)

**Comment by viktorTarasov** [comment]
@Monloi 
> ...  changed the AID in authentic.profile aid = A0:00:00:00:03:00:00:00

As I've told earlier; the AID  _A0:00:00:00:03:00:00:00_ is not AID of AuthentIC application,  but AID of _GP Card Manager_ -- application on java cards that manage other applications.

**Comment by viktorTarasov** [comment]
@Monloi 
Wait a little bit, I hope to test the Oberthur's AuthentIC cards during the current release.

**Comment by viktorTarasov** [comment]
@Monloi 
Looking the logs:
- AID of AuthentIC application seems to be _A0 00 00 00 77 01 00 70 0A 10 00 F1 00 00 01 00_;
- it still matches the 'authentic' driver;
- logs seems incomplete,

**Comment by Monloi** [comment]
Hi viktor, any lead time on the new release with he oberthur support?

**Comment by viktorTarasov** [comment]
RC1 is 'almost' published.
The PR from @dengert is the last one that I would like to resolve before propose it to community for testing.

**Comment by dengert** [comment]
@viktorTarasov  Most of the #717 PR could wait till after 0.16.0 It has a lot of changes that still need to be tested, and OpenSSL-1.1 is in beta.  It is in two commits.  

"Handle C and C++ "inline" and "restrict" keywords for various compilers"
https://github.com/OpenSC/OpenSC/pull/717/commits/8f28dcd7b71754675e2ecbe6bc5a5548d2ef2849
could be included as it addresses a specific issue is is localized to 3 files.

**Comment by viktorTarasov** [comment]
Oberthur AuthentIC card has been tested in QA of 0.16.0:

https://github.com/OpenSC/OpenSC/issues/688#issuecomment-202528825
