### ISSUE TITLE
Add support for Deutsche Telekom TeleSec TCOS 3.0 Signature Card V2.0 (ECC)

### ISSUE THREAD

**Issue by wschlich** [OpenSC/OpenSC#712]
### Expected behaviour

Deutsche TelekomTeleSec TCOS 3.0 Signature Card V2.0 should be supported for PKCS#11 operations.

### Actual behaviour

The cards are not supported.

### Logs

```
zephyr ~ # opensc-tool -a
Using reader with a card: REINER SCT cyberJack wave (9411503530) 00 00
3b:9f:96:81:31:fe:9d:00:64:05:a0:03:04:31:c0:73:f7:01:d0:00:90:00:28
zephyr ~ # opensc-tool -n
Using reader with a card: REINER SCT cyberJack wave (9411503530) 00 00
Unsupported card
zephyr ~ # pkcs11-tool -O
No slot with a token was found.
zephyr ~ # 
```

**Comment by wschlich** [comment]
[LB_TCOS_3.0_Signature_Card_V.2.0.pdf](https://github.com/OpenSC/OpenSC/files/174390/LB_TCOS_3.0_Signature_Card_V.2.0.pdf)

**Comment by CardContact** [comment]
Feel free to create a pull request fixing the issue ;-)

No, seriously - I guess we don't have anyone in the project that takes care of TCOS cards.

Peter Koch used to work on the TCOS code, but his last commit is dated 2011.

Maybe you only need to add the ATR to card-tcos.c. It's at least worth a try.

**Comment by wschlich** [comment]
Hmm. It's an ECC smartcard whereas the previous ones were RSA smart cards. I don't think adding the ATR would suffice :-)

**Comment by CardContact** [comment]
Is the card specification (APDU, Filesystem etc.) public or would TeleSec allow an open-source implementation based on a non-public specification ?

Availability of the specifications is the general issue with these kind of cards.

**Comment by frankmorgner** [comment]
Indeed, card-tcos.c does currently not support ECC, though the driver was written for TCOS 3.0.

**Comment by wschlich** [comment]
Here's what they provide online:

Leistungsbeschreibung:
https://www.telesec.de/de/tcos/support/downloadbereich/category/28-leistungsbeschreibung

TeleSec PKCS#11 SDK (with binary PKCS#11 library for Linux):
https://www.telesec.de/de/tcos/support/downloadbereich/category/27-pkcs11-sdk

I'll send them a mail to telesec-smartcard@t-systems.com and ask for specs.

**Comment by wschlich** [comment]
Seems that GnuPG 2.1 has (at least some) support for it:

**Comment by wschlich** [comment]
Today I received the specs by TeleSec (nice guys btw!).

Guidance Documentation of the TCOS 3.0 Signature Card Version 2.0 Release 1 with the application Netkey
[AGD_OPE TCOS 3.0 Signature Card 2.0 Release 1_V1.0_121206.pdf](https://github.com/OpenSC/OpenSC/files/177968/AGD_OPE.TCOS.3.0.Signature.Card.2.0.Release.1_V1.0_121206.pdf)

**Comment by wschlich** [comment]
@CardContact @frankmorgner TeleSec is open to a FOSS implementation regarding their TCOS 3.0 Signature Card 2.0. Is any one of you interested in taking the challenge? :)

**Comment by frankmorgner** [comment]
Maybe if you add some purse you will find a volunteer...

**Comment by wschlich** [comment]
@frankmorgner: What amount do you think would be interesting to someone?

**Comment by erebus2** [comment]
I'm affected by this issue. For me, it means that only one program (secSigner) is able to interface with my signature card (I wonder how they do it, it looks like they don't use OpenSC). Unfortunately, that particular program only supports PKCS#7 detached signatures and I have contacts who want PDF inline.

**Comment by erebus2** [comment]
I tried to extend the card driver in card-tcos.h to support this type of card as well, but no success so far.

$ opensc-tool -a
Using reader with a card: OMNIKEY AG CardMan 3121 00 00
3b:9f:96:81:31:fe:9d:00:64:05:a0:03:04:31:c0:73:f7:01:d0:00:90:00:28
$ opensc-tool -n
Using reader with a card: OMNIKEY AG CardMan 3121 00 00
TCOS
$ pkcs11-tool -O
Using slot 0 with a present token (0x0)
$ pkcs11-tool -M
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GetMechanismList failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.
$

**Comment by erebus2** [comment]
Looks like I have to take a look at the specs first, thx to wschlich for obtaining them :)

**Comment by erebus2** [comment]
Making progress.
Before:
$ pkcs11-tool -M
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GetMechanismList failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.
After:
$ pkcs11-tool -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  ECDSA, keySize={256,256}, hw, sign

**Comment by erebus2** [comment]
OK folks, I need some help. I managed to make some parts of the card driver work but I'm still unable to use it.
It looks like function detect_netkey() in pkcs15-tcos.c is supposed to look for the key on my card but I don't understand how it's supposed to work. At the moment, the code looks like this:

		/*                 p15card  path                    id    kref  klen  auth_id label*/
		if (card->type== SC_CARD_TYPE_TCOS_V3_SC_V20) {
			insert_key(p15card, "4B31",                 0x49, 0x04, 256,  5,      "SigG-Schluessel ECC Global");
									  /* Global key, key ID 04 */
									  /* TODO: Figure out whether id, klen and auth_id are correct. */
		} else if(card->type==SC_CARD_TYPE_TCOS_V3){
			insert_key(p15card, dirpath(dir,"0000"),    0x49, 0x84, 2048, 5,      "SigG-Schluessel");
		} else {
			insert_key(p15card, dirpath(dir,"5331"),    0x49, 0x80, 1024, 5,      "SigG-Schluessel");
		}

I have to admit I know only little about PKCS and smart cards, so I'd be grateful if someone could give me some guidance. What I know so far is that (for obvious reasons) we're not allowed to access file 4B31 because it includes the private key. For me, that raises the question why this is working for earlier TCOS cards. If we can't access the key file, why does insert_key() require a file ID? Maybe we have to use a different file, but which one? I can't find another file on the card that would make sense in this context.

**Comment by erebus2** [comment]
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:740:sc_select_file: called; type=2, path=3f004b31
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:554:sc_transmit_apdu: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:401:sc_lock: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:441:sc_lock: returning with: 0 (Success)
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:521:sc_transmit: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:371:sc_single_transmit: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:378:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:4, data(2) 0x7fffea0a9a22
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:283:pcsc_transmit: reader 'OMNIKEY AG CardMan 3121 00 00'
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:284:pcsc_transmit: 
Outgoing APDU (8 bytes):
00 A4 08 04 02 4B 31 00 .....K1.
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f86c8017700 19:16:24.443 [opensc-explorer] reader-pcsc.c:293:pcsc_transmit: 
Incoming APDU (2 bytes):
69 82 i.
0x7f86c8017700 19:16:24.443 [opensc-explorer] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
0x7f86c8017700 19:16:24.443 [opensc-explorer] apdu.c:543:sc_transmit: returning with: 0 (Success)
0x7f86c8017700 19:16:24.443 [opensc-explorer] card.c:451:sc_unlock: called
0x7f86c8017700 19:16:24.443 [opensc-explorer] iso7816.c:124:iso7816_check_sw: Security status not satisfied
0x7f86c8017700 19:16:24.443 [opensc-explorer] card-tcos.c:435:tcos_select_file: davor
0x7f86c8017700 19:16:24.443 [opensc-explorer] card-tcos.c:436:tcos_select_file: returning with: -1211 (Security status not satisfied)
0x7f86c8017700 19:16:24.443 [opensc-explorer] card.c:762:sc_select_file: 'SELECT' error: -1211 (Security status not satisfied)

**Comment by erebus2** [comment]
huh?
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:740:sc_select_file: called; type=2, path=3f004b31
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:554:sc_transmit_apdu: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:401:sc_lock: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] card.c:441:sc_lock: returning with: 0 (Success)
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:521:sc_transmit: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:371:sc_single_transmit: called
0x7f86c8017700 19:16:24.433 [opensc-explorer] apdu.c:378:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:4, data(2) 0x7fffea0a9a22
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:283:pcsc_transmit: reader 'OMNIKEY AG CardMan 3121 00 00'
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:284:pcsc_transmit: 
Outgoing APDU (8 bytes):
00 A4 08 04 02 4B 31 00 .....K1.
0x7f86c8017700 19:16:24.433 [opensc-explorer] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7f86c8017700 19:16:24.443 [opensc-explorer] reader-pcsc.c:293:pcsc_transmit: 
Incoming APDU (2 bytes):
69 82 i.
0x7f86c8017700 19:16:24.443 [opensc-explorer] apdu.c:390:sc_single_transmit: returning with: 0 (Success)
0x7f86c8017700 19:16:24.443 [opensc-explorer] apdu.c:543:sc_transmit: returning with: 0 (Success)
0x7f86c8017700 19:16:24.443 [opensc-explorer] card.c:451:sc_unlock: called
0x7f86c8017700 19:16:24.443 [opensc-explorer] iso7816.c:124:iso7816_check_sw: Security status not satisfied
0x7f86c8017700 19:16:24.443 [opensc-explorer] card-tcos.c:435:tcos_select_file: davor
0x7f86c8017700 19:16:24.443 [opensc-explorer] card-tcos.c:436:tcos_select_file: returning with: -1211 (Security status not satisfied)
0x7f86c8017700 19:16:24.443 [opensc-explorer] card.c:762:sc_select_file: 'SELECT' error: -1211 (Security status not satisfied)

**Comment by Jakuje** [comment]
Pulling this thread from history, there is #1880 where I am trying to fix some issues with TCOS driver (RSA operations, with the help of provided specs). If somebody in this thread still has any TCOS cards and would be able to test the code, it would be greatly appreciated.

Once I am in it, I can probably check the ECDSA support, if there would be somebody who could test the changes.

**Comment by Mechtecs** [comment]
@Jakuje Do you still need help? I have a "TCOS 3.0 / NetKey 3.0" from DATEV, which is quite new (December). I would like to contribute and could even help with the development where needed. The possibility to use DATEV under Linux could be very sexy :)

**Comment by Jakuje** [comment]
Sorry, It does not look like I will have more time to dig deeper into that in coming weeks.

**Comment by Mechtecs** [comment]
Then I will do it.

Jakub Jelen <notifications@github.com> schrieb am Sa., 21. März 2020, 08:57:

**Comment by smartman** [comment]
I believe Telesec cards are still not working. I have test card also. Let's make it work together!

**Comment by Jackfritt** [comment]
I can confirm that a TeleSec dont work with latest git.
Maybe the Info can help.

src/tools/pkcs11-tool -I
Cryptoki version 3.0
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.23)
Using slot 0 with a present token (0x0)

src/tools/pkcs11-tool -O
Using slot 0 with a present token (0x0)

src/tools/pkcs11-tool --login --test 
error: PKCS11 function C_GetSlotInfo failed: rv = CKR_DEVICE_ERROR (0x30)
Aborting.

src/tools/opensc-tool -n
Using reader with a card: REINER SCT cyberJack RFID komfort (5554708001) 00 00
Unsupported card

src/tools/pkcs11-tool --test
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_RANDOM_NO_RNG (0x121)
error: PKCS11 function C_GetMechanismList failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.

but gpg and gpgsm from latest Debian Bullseye says
gpg --card-status 
Reader ...........: REINER SCT cyberJack RFID komfort (5554708001) 00 00
Application ID ...: 89490171500020964630
Application type .: NetKey

LC_ALL=C gpgsm --learn-card
gpgsm: dirmngr cache-only key lookup failed: Not found
gpgsm: issuer certificate {7016AXXX} not found using authorityKeyIdentifier
gpgsm: dirmngr cache-only key lookup failed: Not found
gpgsm: issuer certificate (#/CN=TeleSec PKS CA 7:PN,OU=Trust Center Deutsche Telekom,O=T-Systems International GmbH,C=DE) not found
gpgsm: dirmngr cache-only key lookup failed: Not found
gpgsm: issuer certificate {7016A6XXX} not found using authorityKeyIdentifier
gpgsm: dirmngr cache-only key lookup failed: Not found
gpgsm: issuer certificate (#/CN=TeleSec PKS CA 7:PN,OU=Trust Center Deutsche Telekom,O=T-Systems International GmbH,C=DE) not found

**Comment by Jackfritt** [comment]
I also tried Datev smartcard Classic.

src/tools/pkcs11-tool -I
Cryptoki version 3.0
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.23)
Using slot 0 with a present token (0x0)

src/tools/pkcs11-tool -O
Using slot 0 with a present token (0x0)

src/tools/pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_RECOGNIZED (0xe1)
Aborting.

src/tools/opensc-tool -n
Using reader with a card: REINER SCT cyberJack RFID komfort (5554708001) 00 00
TCOS

src/tools/pkcs11-tool --test
Using slot 0 with a present token (0x0)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_RANDOM_NO_RNG (0x121)
error: PKCS11 function C_GetMechanismList failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)
Aborting.

LC_ALL=C gpg --card-status
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device

LC_ALL=C gpgsm --learn-card
gpgsm: error learning card: Card removed
