### ISSUE TITLE
No obvious pre-built binary for Mac OSX El Capitan

### ISSUE THREAD

**Issue by yschimke** [OpenSC/OpenSC#713]
### Expected behaviour

Wiki pages should have working link to download binaries for 10.11

### Actual behaviour

The current download warns it could break Mac OSX.  Workaround was to build from source.

### Steps to reproduce

1. https://github.com/OpenSC/OpenSC/wiki
2. Download "Mac OS X 10.9 and 10.10 installer"
3. Try to install

### Logs

N/A

**Comment by nic** [comment]
I think that should be working with this pre-release version of v0.16.0:
https://github.com/OpenSC/OpenSC/releases/download/v0.16.0-pre1/OpenSC-0.15.0.dmg
