### ISSUE TITLE
appveyor: 'deploy' 

### ISSUE THREAD

**Issue by viktorTarasov** [OpenSC/OpenSC#716]
@LudovicRousseau 

I'm trying to install automatic create of GitHub/Release and upload of release artifacts from appveyor.
 
It seems that you are the owner of _OpenSC_ appveyor project.

If so, can you, please:
- generate GitHub access token (https://github.com/settings/tokens) with _repo_ rights;
- encrypt it in your appveyor account (https://ci.appveyor.com/tools/encrypt)
- and update the _deploy->auth_token->secure_value in appveyor.yml file of OpenSC.

**Comment by viktorTarasov** [comment]
@LudovicRousseau 

_appveyor.yml_ has to be updated in _opensc-0.16.0_ branch.

**Comment by LudovicRousseau** [comment]
Done in 6e2a7c93fdb5e96b88331e693baaae9a787cb674
I hope it is correct.

**Comment by viktorTarasov** [comment]
@LudovicRousseau 
can you give the, at least 'build' (better 'admin') right,  to OpenSC/core team in your OpenSC appveyor
project, please.

**Comment by LudovicRousseau** [comment]
@viktorTarasov sure. How do I do that?
I could not find how to add users to a AppVeyor project. All I have in the "Project permissions" is "Administrator" with all allowed and "User" with all "inherit".

**Comment by viktorTarasov** [comment]
The way to add only few rights seems to be:
 - create role, let's say _Collaborator_, going to 'New Role' on [team page](https://ci.appveyor.com/team)
 - edit rights for _Collaborator_: : at least _Projects_ -> _Run project builds_
 - on team page: 
  - _Add/Remove Teams_
  - check OpenSC/Core (normally you have to see it)
  - select appveyor role (_Collaborator_) 
  - update rights with _Update GitHub teams access_

Short way is to assign to OpenSC/Core the _admin_ role (on team page).

**Comment by LudovicRousseau** [comment]
OpenSC/Owners now has the Collaborator role.
