### ISSUE TITLE
github: webhook: sourceforge: path for release files

### ISSUE THREAD

**Issue by viktorTarasov** [OpenSC/OpenSC#719]
WIth the current _github sourceforge webhook_ the directory for new release files is automatically created in _sourceforge: opensc/files/_, at the level of the OpenSC subprojects -- OpenSC (itself), engine, libp11, ...

Does there any way to control destination path and create release directory inside the sub-project (.../projects/opensc/files/OpenSC/) ?

**Comment by frankmorgner** [comment]
I have not seen anything like this. You could try asking the sourceforge support team.
