### ISSUE TITLE
Support for Swedish SIHTS (Health care) eID

### ISSUE THREAD

**Issue by magnusart** [OpenSC/OpenSC#726]
### Expected behaviour

I wish to use the SC to sign data using `pkcs15-crypt` or `pksc11-tool`.

### Actual behaviour

When I run `pkcs15-crypt` to sign a file I get the errors below.

```
pkcs15-crypt -s --pkcs1 --sha-1 -k 46 -i tmp.bin --aid A000000167455349474E -p XXXXXX
Using reader with a card: OMNIKEY AG 3121 USB
PKCS #15 binding failed: Unsupported card
```

```
pkcs11-tool --sign --slot 0x2 --input-file message.txt --login --pin XXXXXX --mechanism SHA1-RSA-PKCS --verbose
error: PKCS11 function C_SignFinal failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
```
### Adding support for card

The card is called `Telia EID IP5a`. Used as eID within the health care sector in Sweden. The card I have is a pre-production card (test card).

Please give further instructions on how I can go about adding support for the card. I tried adding it to the config but I'm not sure I did the correct thing since it did not start working. Below is the information I found using opensc tools. 

```
opensc-tool -n
Using reader with a card: OMNIKEY AG 3121 USB
SetCOS
```

```
opensc-tool -a
Using reader with a card: OMNIKEY AG 3121 USB
3b:7d:96:00:00:80:31:80:65:b0:a3:11:01:f3:83:00:90:00
```

```
opensc-tool --list-algorithms
Using reader with a card: OMNIKEY AG 3121 USB
Algorithm: rsa
Key length: 512
Flags: onboard key generation padding ( pkcs1 ) hashes ( sha1 )

Algorithm: rsa
Key length: 768
Flags: onboard key generation padding ( pkcs1 ) hashes ( sha1 )

Algorithm: rsa
Key length: 1024
Flags: onboard key generation padding ( pkcs1 ) hashes ( sha1 )
```
```
pkcs11-tool -t --login --pin XXXXXX
Using slot 1 with a present token (0x1)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_GENERAL_ERROR (0x5)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only RSA signatures)
  testing key 0 (legitimering)
error: PKCS11 function C_SignFinal failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)

Aborting.
```

```
pkcs15-tool --list-applications
Using reader with a card: OMNIKEY AG 3121 USB
Application 'Telia EID IP5a':
	AID: A000000063504B43532D3135
	DDO: 06062A8570236433

Application 'Telia EID IP5a-Sign':
	AID: A000000167455349474E
```

**Comment by frankmorgner** [comment]
Could you give a log of the errors that are happening (use `debug=20` in `opensc.conf`)? Last editors of `card-setcos.c` include @andbil and @martinpaljak, maybe they can help.

**Comment by magnusart** [comment]
Ran the same commands with `debug=20` attached are the logs. There are two logs in the gist one for pkcs11 and one for pkcs15. The first one very long so it is easy to miss the second log.

https://gist.github.com/magnusart/e5c8a1b834e002076d4af1884638a2ad

**Comment by frankmorgner** [comment]
Did anyone of the creators ever thought of the typo mixing H and I?

**Comment by frankmorgner** [comment]
Your log contains a "Yubico Yubikey 4 OTP+U2F+CCID", which seems not to be the card you mean; please re-generate the log with the Yubikey unplugged.

**Comment by magnusart** [comment]
Hi

The problem existed before I got my yubikey. But I can unplug it and give
it a go again

/Magnus

Den lör 16 apr. 2016 15:16Frank Morgner <notifications@github.com> skrev:

**Comment by frankmorgner** [comment]
The problem is, most people (e.g. me) don't have too much time to waste by scrolling through logs that are irrelevant. If you want someone to look at this, please re-do it without distracting stuff attached.

**Comment by magnusart** [comment]
Hi

I had to hand this card back for a while, but I got it back now and I have ordered new ones so I can continue experimenting. 

Here is a gist where I re-ran the commands previously, this time without my Yubikey attached.
https://gist.github.com/magnusart/006d423853bce49535ec416c247e7c24

**Comment by hean01-cendio** [comment]
@magnusart could you verify that output of `pkcs11-tool -O` shows that you have 2048 bits RSA keys for signing on your SITHS card. If so, then PR #758 should be the fix for using your card.

**Comment by magnusart** [comment]
@hean01-cendio you're right. Any ETA when this will become available through the normal channels?

Below is the output of `pkcs11-tool -O`
```
Using slot 1 with a present token (0x1)
Certificate Object, type = X.509 cert
  label:      legitimering
  ID:         45
Public Key Object; RSA 2048 bits
  label:      legitimering
  ID:         45
  Usage:      encrypt, verify
Certificate Object, type = X.509 cert
  label:      legitimering
  ID:         45
Public Key Object; RSA 2048 bits
  label:      legitimering
  ID:         45
  Usage:      encrypt, verify
Certificate Object, type = X.509 cert
  label:      ROOT CA
  ID:         48
Public Key Object; RSA 4096 bits
  label:      ROOT CA
  ID:         48
  Usage:      encrypt, verify
```
