### ISSUE TITLE
CardOS init broken for readers without extended APDU supported

### ISSUE THREAD

**Issue by viktorTarasov** [OpenSC/OpenSC#735]
After 2e21163273978475b31f664f80ad1ad3c02755c7
CardOS card cannot be initialized
when using card reader without Extended APDU supported.

I guess that a new OpenSC configuration option to control using of extended APDU has to be introduced. Disabled by default.

**Comment by frankmorgner** [comment]
There is already an option to limit the transceive length of any reader. You should use it. Also, if the reader announces short/extended length support this *is* honored.

Though, it could be discussed, whether the reader's limit should assumed to be at short length if it is *completely silent* about its limits.

**Comment by viktorTarasov** [comment]
> .. is already an option to limit the transceive length of any reader

this option exist only in comments of opensc.conf -- not supported by code

>  if the reader announces short/extended length support this is honored

yes, it's true, if the reader clearly declares its capacity or if a reader specific config section will be introduced 

> it could be discussed, whether the reader's limit should assumed to be at short length if it is completely silent about its limits.

it hardly could be discussed -- if reader is silent, then short length has to be assumed.

So, to resume,
- by default extended APDUs are disabled.
- it can be enabled by reader, that clearly declares it's capacities, or by reader specific section -- all that joined by card capacity.

**Comment by frankmorgner** [comment]
set `max_send_size` and `max_recv_size`
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/ctx.c#L303-319

**Comment by frankmorgner** [comment]
There may be a problem here https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L877, though

**Comment by viktorTarasov** [comment]
> set max_send_size and max_recv_size

fine, thanks.

So,
- _max_send_size_ and _max_send_size_ has to be enabled by default;
- parse of _reader_driver_ config section moved from _ctx_ to _detect_readers_ handler of reader's _ops_, and placed before _detect_reader_features_;
- check if common card framework overwrites, if needed,  the card specific _max_XX_sizes_

**Comment by viktorTarasov** [comment]
fixed in _release_ branch
