### ISSUE TITLE
pkcs11-tool fails to load default module (opensc-pkcs11.dylib on Mac)

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#741]
### Platform

Mac OS X 10.11.4, Xcode-7.3. OpenSC - current (as of 2016-04-21) GitHub `master` branch.

### Expected behaviour

Should work as shown below but *without* module explicitly specified:

```
$ pkcs11-tool --module /Library/OpenSC/lib/opensc-pkcs11.dylib -I
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.15)
Using slot 1 with a present token (0x4)
$ 
```

### Actual behaviour

```
$ pkcs11-tool -I
sc_dlopen failed: dlopen(opensc-pkcs11.dylib, 1): image not found
error: Failed to load pkcs11 module
Aborting.
$ 
```

The culprit is line 14 in `config.h`:
```
#define DEFAULT_PKCS11_PROVIDER "opensc-pkcs11.dylib"
```
that does not specify the complete path to `/Library/OpenSC/lib/opensc-pkcs11.dylib`. I could only track it back to commit c3527f4a of 2015-11-12 which did not go far enough (did not add the actual path).

A fix would be to prepend the complete path (`LIBDIR/LIB_PRE`) to `opensc-pkcs11${DYN_LIB_EXT}`. 

A work-around would be to add `/Library/OpenSC/lib` to the default search path, or to sym-link `opensc-pkcs11.dylib` into a directory that already is on that path. But since by the time `config.h` is written to disk,  `LIBDDIR` is known - it makes sense to just include it in the `DEFAULT_PKCS11_PROVIDER`.

### Steps to reproduce

Insert your hardware token and type `pkcs11-tool -I` or `pkcs11-tool -M`.

### Logs

Nothing gets logged because loading of the PKCS11 module fails (prior to any interactions with the token).

**Comment by frankmorgner** [comment]
There is a problem in https://github.com/OpenSC/OpenSC/blob/master/MacOSX/scripts/postinstall#L5. Could you check whether if changing `.so` to `.dylib` the installer works properly?

**Comment by mouse07410** [comment]
It probably would work properly - but wouldn't it be simpler and more correct to just include the full path in the default file name?

**Comment by frankmorgner** [comment]
You'd need a bunch of magic code to make this work on every platform. Think of Windows, for example.

**Comment by mouse07410** [comment]
I see... I personally would be happy if it could include the complete path on Mac and Unix/Linux only, leaving Windows as it is now...

It may be that implementing the above is too hard or inappropriate - though IMHO if something can be made to work well on only some platforms, those "good" platforms shouldn't be penalized and held back just because there are "bad" platforms that cannot benefit from such an improvement. In that case, could the https://github.com/OpenSC/OpenSC/blob/master/MacOSX/scripts/postinstall#L5 do *both* - `.so` *and* `.dylib`?

**Comment by frankmorgner** [comment]
using an absolute path is generally a good idea to avoid depending on a malicious environment. feel free to make a pull request.

**Comment by mouse07410** [comment]
> feel free to make a pull request.

I'd be happy to.

For some reason, my attempts to edit `configure.ac` file (line 652) to prepend `$LIBDIR` failed - it appears that `LIBDIR` has the value `$(libdir)` (literally, not resolvable).

Would you have any advice how/where to do it right?

**Comment by mouse07410** [comment]
Also, semi-related. In `config.h` produced by unmodified `configure`, default SM module path is bad:
```
. . . . . .
/* Default PKCS11 provider */
#define DEFAULT_PKCS11_PROVIDER "opensc-pkcs11.dylib"

/* Default SM module */
#define DEFAULT_SM_MODULE "libsmm-local.dylib"

/* Default SM module path */
#define DEFAULT_SM_MODULE_PATH "module_path = $(libdir);"

/* Enable CT-API support */
/* #undef ENABLE_CTAPI */
. . . . . .
```

I'm having the same problem - trying to somehow get the name of that directory from inside the `configure` script...

**Comment by psorobka** [comment]
Stumbled upon this problem as well - I tried to symlink
`sudo ln -s /Library/OpenSC/lib/opensc-pkcs11.dylib /usr/lib`
but I got Access Denied. I think SIP is the problem.

How I can temporary work around this?

**Comment by mouse07410** [comment]
@psorobka you can work-around by `sudo ln -s /Library/OpenSC/lib/opensc-pkcs11.dylib /usr/local/lib/`

@frankmorgner I'd really love to hear your comments regarding how to grab the `PREFIX` value before the `config.h` file gets written. Because this work-around is ugly.

**Comment by dwmw2** [comment]
On Linux the default provider should generally be the one indicated by running
`pkg-config --variable=proxy_module p11-kit-1`

**Comment by frankmorgner** [comment]
fixed in 630e7ee08efe01c4a8db621df373f19153f8a2fd

**Comment by Radhika205-byte** [comment]
Hi,
I am using opensc 0.12.2 package
When I try to execute commands through pkcs11-tool i am facing issue.

OPENSC_CONF="usr/local/etc/opensc.conf" /usr/local/bin/pkcs11-tool --module /usr/local/lib/opensc-pkcs11.so -l -t
No slot with a token was found.
Segmentation fault (core dumped)

Any suggestion to resolve this problem.

**Comment by noutop** [comment]
I am a newbie, but if you just write pkcs11-tool in your terminal it should show you the Default --module :D
(I installed OpenSC)
Usage: pkcs11-tool [OPTIONS]
Options:
      --module <arg>            Specify the module to load (default:/Library/OpenSC/lib/opensc-pkcs11.so)

Just tested it to sign and decrypt and it worked fine!
