### ISSUE TITLE
unable to use smartcard-hsm for s/mime - opensc 0.16 rc1 - outlook 2016, 32bit

### ISSUE THREAD

**Issue by ldti** [OpenSC/OpenSC#755]
### Expected behaviour

ability to sign or encrypt email messages in outlook.

### Actual behaviour

getting the message ""the smart card cannot perform the requested operation" when trying to set the certificate for s/mime use in outlook

### Steps to reproduce

1. generate a user template certificate signed by a MS CA.
2. try to configure the certificate for use in outlook
3. receive above mentioned message.

**Comment by mouse07410** [comment]
I assume this worked for OpenSC-0.15.0 and/or *master* branch? And your platform is probably Windows? More details wouldn't hurt...

**Comment by ldti** [comment]
No, it didn't work on 15 either. Windows indeed. Tried it with certs from a MS CA and XCA too. Same result..

**Comment by dengert** [comment]
Did you follow the steps in:

https://github.com/OpenSC/OpenSC/wiki/SmartCardHSM

I have used other smart cards with a MS CA, steps included:

- generate  keypair on card.

- have card sign a certificate request with new private key.

- send request to MS CA, used cut-and-paste 

- download signed certificate 

- load certificate on to card. 

All the above might be done at once by some web interface, but from you description, it is not clear what you are doing.

**Comment by ldti** [comment]
yep. did it with web, also tried with cut and paste, also with xca. everything about the cert itself looks normal, as using the same template with a regular certificate (not smart card based) results in a working s/mime.

i am using the microsoft base smart card crypto provider, also tried with the opensc CSP. same result.

**Comment by CardContact** [comment]
What does certutil -scinfo tell you ?

Please also create a minidriver log file by creating c:\tmp. The log is written to md.log.

**Comment by ldti** [comment]
this is the result of certutil -scinfo:

it does not appear to mention my certificate at all, only referencing my work certificate.


The Microsoft Smart Card Resource Manager is running.
Current reader/card status:
Readers: 2
  0: OMNIKEY CardMan 5x21 0
  1: OMNIKEY CardMan 5x21-CL 0
--- Reader: OMNIKEY CardMan 5x21 0
--- Status: SCARD_STATE_PRESENT
--- Status: The card is available for use.
---   Card: SmartCard-HSM
---    ATR:
	3b fe 18 00 00 81 31 fe  45 80 31 81 54 48 53 4d   ;.....1.E.1.THSM
	31 73 80 21 40 81 07 fa                            1s.!@...

--- Reader: OMNIKEY CardMan 5x21-CL 0
--- Status: SCARD_STATE_EMPTY
--- Status: No card.
---   Card:

=======================================================
Analyzing card in reader: OMNIKEY CardMan 5x21 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: OMNIKEY CardMan 5x21 0
---   Card: SmartCard-HSM
Provider = OpenSC CSP
Key Container = Certificate [Default Container]

No AT_SIGNATURE key for reader: OMNIKEY CardMan 5x21 0
Serial Number: 58c1ea2e000200001ee1
Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
 NotBefore: 10/05/2016 16:44
 NotAfter: 10/05/2017 16:44
Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
Non-root Certificate
Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
Cert Hash(sha1): 4e 29 19 cd 6f 86 ef 65 a7 d9 ed db ab 9c 46 5b e0 57 dd fc

Performing AT_KEYEXCHANGE public key matching test...
Public key matching test succeeded
  Key Container = Certificate
  Provider = Microsoft Base Smart Card Crypto Provider
  ProviderType = 1
  Flags = 1
    0x1 (1)
  KeySpec = 1 -- AT_KEYEXCHANGE
Private key verifies

Performing cert chain verification...
CertGetCertificateChain(dwErrorStatus) = 0x1010040
Chain on smart card is invalid
dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_BASE
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
ChainContext.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
ChainContext.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)
SimpleChain.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)

CertContext[0][0]: dwInfoStatus=2 dwErrorStatus=1000040
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
  Element.dwInfoStatus = CERT_TRUST_HAS_KEY_MATCH_ISSUER (0x2)
  Element.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
  Element.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
  Application[0] = 1.3.6.1.4.1.311.20.2.2 Smart Card Logon
  Application[1] = 1.3.6.1.5.5.7.3.2 Client Authentication

Exclude leaf cert:
  0907d8af90186095efbf55320d4b6b5eeea339da
Full chain:
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
Missing Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
A certificate chain could not be built to a trusted root authority. 0x800b010a (-2146762486 CERT_E_CHAINING)
------------------------------------
Incomplete certificate chain
Cannot find certificate:
    CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
Displayed AT_KEYEXCHANGE cert for reader: OMNIKEY CardMan 5x21 0

--------------===========================--------------
================ Certificate 1 ================
--- Reader: OMNIKEY CardMan 5x21 0
---   Card: SmartCard-HSM
Provider = OpenSC CSP
Key Container = Certificate

No AT_SIGNATURE key for reader: OMNIKEY CardMan 5x21 0
Serial Number: 58c1ea2e000200001ee1
Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
 NotBefore: 10/05/2016 16:44
 NotAfter: 10/05/2017 16:44
Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
Non-root Certificate
Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
Cert Hash(sha1): 4e 29 19 cd 6f 86 ef 65 a7 d9 ed db ab 9c 46 5b e0 57 dd fc

Performing AT_KEYEXCHANGE public key matching test...
Public key matching test succeeded
  Key Container = Certificate
  Provider = Microsoft Base Smart Card Crypto Provider
  ProviderType = 1
  Flags = 1
    0x1 (1)
  KeySpec = 1 -- AT_KEYEXCHANGE
Private key verifies

Performing cert chain verification...
CertGetCertificateChain(dwErrorStatus) = 0x1010040
Chain on smart card is invalid
dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_BASE
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
ChainContext.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
ChainContext.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)
SimpleChain.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)

CertContext[0][0]: dwInfoStatus=2 dwErrorStatus=1000040
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
  Element.dwInfoStatus = CERT_TRUST_HAS_KEY_MATCH_ISSUER (0x2)
  Element.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
  Element.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
  Application[0] = 1.3.6.1.4.1.311.20.2.2 Smart Card Logon
  Application[1] = 1.3.6.1.5.5.7.3.2 Client Authentication

Exclude leaf cert:
  0907d8af90186095efbf55320d4b6b5eeea339da
Full chain:
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
Missing Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
A certificate chain could not be built to a trusted root authority. 0x800b010a (-2146762486 CERT_E_CHAINING)
------------------------------------
Incomplete certificate chain
Cannot find certificate:
    CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
Displayed AT_KEYEXCHANGE cert for reader: OMNIKEY CardMan 5x21 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: OMNIKEY CardMan 5x21 0
---   Card: SmartCard-HSM
Provider = Microsoft Smart Card Key Storage Provider
Key Container = Certificate

Serial Number: 58c1ea2e000200001ee1
Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
 NotBefore: 10/05/2016 16:44
 NotAfter: 10/05/2017 16:44
Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
Non-root Certificate
Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
Cert Hash(sha1): 4e 29 19 cd 6f 86 ef 65 a7 d9 ed db ab 9c 46 5b e0 57 dd fc

Performing  public key matching test...
Public key matching test succeeded
  Key Container = Certificate
  Provider = Microsoft Smart Card Key Storage Provider
  ProviderType = 0
  Flags = 1
    0x1 (1)
  KeySpec = 0
Private key verifies

Performing cert chain verification...
CertGetCertificateChain(dwErrorStatus) = 0x1010040
Chain on smart card is invalid
dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_BASE
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
ChainContext.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
ChainContext.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)
SimpleChain.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)

CertContext[0][0]: dwInfoStatus=2 dwErrorStatus=1000040
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
  Element.dwInfoStatus = CERT_TRUST_HAS_KEY_MATCH_ISSUER (0x2)
  Element.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
  Element.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
  Application[0] = 1.3.6.1.4.1.311.20.2.2 Smart Card Logon
  Application[1] = 1.3.6.1.5.5.7.3.2 Client Authentication

Exclude leaf cert:
  0907d8af90186095efbf55320d4b6b5eeea339da
Full chain:
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
Missing Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
A certificate chain could not be built to a trusted root authority. 0x800b010a (-2146762486 CERT_E_CHAINING)
------------------------------------
Incomplete certificate chain
Cannot find certificate:
    CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
Displayed  cert for reader: OMNIKEY CardMan 5x21 0

--------------===========================--------------
================ Certificate 1 ================
--- Reader: OMNIKEY CardMan 5x21 0
---   Card: SmartCard-HSM
Provider = Microsoft Smart Card Key Storage Provider
Key Container = Certificate

Serial Number: 58c1ea2e000200001ee1
Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
 NotBefore: 10/05/2016 16:44
 NotAfter: 10/05/2017 16:44
Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
Non-root Certificate
Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
Cert Hash(sha1): 4e 29 19 cd 6f 86 ef 65 a7 d9 ed db ab 9c 46 5b e0 57 dd fc

Performing  public key matching test...
Public key matching test succeeded
  Key Container = Certificate
  Provider = Microsoft Smart Card Key Storage Provider
  ProviderType = 0
  Flags = 1
    0x1 (1)
  KeySpec = 0
Private key verifies

Performing cert chain verification...
CertGetCertificateChain(dwErrorStatus) = 0x1010040
Chain on smart card is invalid
dwFlags = CA_VERIFY_FLAGS_CONSOLE_TRACE (0x20000000)
dwFlags = CA_VERIFY_FLAGS_DUMP_CHAIN (0x40000000)
ChainFlags = CERT_CHAIN_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT (0x40000000)
HCCE_LOCAL_MACHINE
CERT_CHAIN_POLICY_BASE
-------- CERT_CHAIN_CONTEXT --------
ChainContext.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
ChainContext.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
ChainContext.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)
SimpleChain.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
SimpleChain.dwErrorStatus = CERT_TRUST_IS_PARTIAL_CHAIN (0x10000)

CertContext[0][0]: dwInfoStatus=2 dwErrorStatus=1000040
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
  Element.dwInfoStatus = CERT_TRUST_HAS_KEY_MATCH_ISSUER (0x2)
  Element.dwErrorStatus = CERT_TRUST_REVOCATION_STATUS_UNKNOWN (0x40)
  Element.dwErrorStatus = CERT_TRUST_IS_OFFLINE_REVOCATION (0x1000000)
  Application[0] = 1.3.6.1.4.1.311.20.2.2 Smart Card Logon
  Application[1] = 1.3.6.1.5.5.7.3.2 Client Authentication

Exclude leaf cert:
  0907d8af90186095efbf55320d4b6b5eeea339da
Full chain:
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
Missing Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  Issuer: CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
  NotBefore: 10/05/2016 16:44
  NotAfter: 10/05/2017 16:44
  Subject: CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp
  Serial: 58c1ea2e000200001ee1
  SubjectAltName: Other Name:Principal Name=Leonid.Tsitalovski@playtech.com
  Template: 1.3.6.1.4.1.311.21.8.10226187.16325245.12404408.1954381.3263090.154.7224858.12138929
  fcdd57e05b469cabdbedd9a765ef866fcd19294e
A certificate chain could not be built to a trusted root authority. 0x800b010a (-2146762486 CERT_E_CHAINING)
------------------------------------
Incomplete certificate chain
Cannot find certificate:
    CN=Playtech IL CA, DC=IL, DC=playtech, DC=corp
Displayed  cert for reader: OMNIKEY CardMan 5x21 0

--------------===========================--------------

=======================================================
Analyzing card in reader: OMNIKEY CardMan 5x21-CL 0

--------------===========================--------------

Done.
CertUtil: -SCInfo command completed successfully.

**Comment by ldti** [comment]
here is the md.log
[md.log.txt](https://github.com/OpenSC/OpenSC/files/259454/md.log.txt)

**Comment by dengert** [comment]
Looks like your MS CA certificate needs to be installed into the local machines cert store. 
With card inserted in:
 Control Panel->Internet Options->Content->certificates-Personal
You can view the certificates found on card, and look at the CertificatePath and certificates in the path
and install certificates.

**Comment by ldti** [comment]
if you mean the CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp certificate - this is the work certificate and is irrelevant to the case.

**Comment by ldti** [comment]
![image](https://cloud.githubusercontent.com/assets/11959365/15183728/122dabfc-179b-11e6-9258-9151e030c496.png)

this is the relevant cert. no idea why certutil -scinfo isnt showing it.

**Comment by ldti** [comment]
![image](https://cloud.githubusercontent.com/assets/11959365/15183765/348bb5fe-179b-11e6-9a0b-a9d740f2d74e.png)

**Comment by dengert** [comment]
So you are looking for the Leonid Tsitalovski certificate issued by omega3-DC-CA?
What is the certification path?

Note that sha1 is not considered secure these days. It may be a policy decision to to not allow the certificate even if the path is valid.


On 5/11/2016 9:08 AM, ldti wrote:
> if you mean the CN=Leonid Tsitalovski, OU=IL-Users, OU=Techusers, OU=PlayTech Israel, DC=IL, DC=playtech, DC=corp certificate - this is the work certificate and is irrelevant to the case.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/755#issuecomment-218470445>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by ldti** [comment]
![image](https://cloud.githubusercontent.com/assets/11959365/15184050/65f1a80a-179c-11e6-91fb-d39c5002c197.png)

this is a test cert, so security is not a real consideration right now...

**Comment by ldti** [comment]
also, same happens with sha256.

**Comment by dengert** [comment]
It could be the process created the keypair in the local machine, and not on the card.

If your card was issued by your employer,  are you sure you can write to it?

the @CardContact  people should know more about to do it and if you can do it.

**Comment by ldti** [comment]
A. XCA shows the keypair in the card. also, i can see outlook accessing it when trying to choose the certificate
B. this is my card , but used by me for smartcard logon at work too.

**Comment by dengert** [comment]
If the key and cert are on the card, I am surprised the certutil did not show it.
OpenSC also installs a pkcs11-tool command.
pkcs11-tool -O -l
should show what objects are on the card.

Could it be a certificate usage, or missing key usage problem?


Google for windows 10 sha1 certificate certutil
or similar.
Microsoft is cracting down on sha1 usages in certificates...


On 5/11/2016 9:27 AM, ldti wrote:
> A. XCA shows the keypair in the card. also, i can see outlook accessing it when trying to choose the certificate
> B. this is my card , but used by me for smartcard logon at work too.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/755#issuecomment-218476071>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by ldti** [comment]
Please enter User PIN: Private Key Object; RSA
  label:      Certificate
  ID:         a23f6c3957991918672b029f7089651a601f9d0c
  Usage:      decrypt, sign, unwrap
Certificate Object, type = X.509 cert
  label:      Certificate
  ID:         a23f6c3957991918672b029f7089651a601f9d0c
Public Key Object; RSA 2048 bits
  label:      Certificate
  ID:         a23f6c3957991918672b029f7089651a601f9d0c
  Usage:      encrypt, verify
Private Key Object; RSA
  label:      ldti
  ID:         eeb147e09109ba14
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      ldti@theldti.com
  ID:         787e7ba30a5e921f
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      ldti@theldti.com
  ID:         94264055bebb4553
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      ldti@theldti.com
  ID:         2df16e9fd794b90e
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      ldti@theldti.com
  ID:         3c8e47adc64395f7
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      ldti@theldti.com
  ID:         0faae8a00daa41ed
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      Certificate
  ID:         badfae923d06990fdf0c5ff4de1662bc85f8dc1c
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      Certificate
  ID:         ea0e4a66150e3e2105a981e6b6b68e07af1c61ad
  Usage:      decrypt, sign, unwrap
Private Key Object; RSA
  label:      Certificate
  ID:         54fb79dcce1f1abf41e02e77ab73197d1f33d014
  Usage:      decrypt, sign, unwrap
Certificate Object, type = X.509 cert
  label:      Certificate
  ID:         54fb79dcce1f1abf41e02e77ab73197d1f33d014
Public Key Object; RSA 2048 bits
  label:      Certificate
  ID:         54fb79dcce1f1abf41e02e77ab73197d1f33d014
  Usage:      encrypt, verify


not sure what the ID is supposed to match to.

usage is based on the "user" template in microsoft ca, as it should be.

this is win8.1 , not 10.

**Comment by dengert** [comment]
The objects are listed as type, label, ID, usage. 
The type shows RSA, EC... and may should the keysize. 

The ID is a PKCS#11 thing. on the same token, a matched cert, pubkey and privkey usually have the same ID. Its a way to associate the cert, pubkey and privkey. 

It looks like you have 2 cert/pubkey/privkey sets,  and 7 RSA privkeys, that don't have matching certs or pubkeys. 

The label is for human readability. And on your token, most are as "Certificate" 
You may have attempted to create the keypair a few times and the request was sent to the CA and a cert may have been returned and is sitting in the cert store but has not been written to the the token. 

There may be a final step, were after the CA notifies you of a returned certificate, you have put the card back in and tell it to install the certificate.

**Comment by ldti** [comment]
ok, i have re-initialized the card and created a single s/mime certificate. here is the result of certutil.
[zaza.txt](https://github.com/OpenSC/OpenSC/files/263498/zaza.txt)

**Comment by dengert** [comment]
There could also be an Outlook problem, This might be helpful for outlook 2016:
https://kb.iu.edu/d/bcta

Or it could be a certificate field or extension is missing. you could post a PEM encoded (.CER format on Windows) certificate to the list. 

Many times two different certificates are used, one for Signature certificate, with 
keyUsage=Digial Signature, Non-Repudiation  (c0) 
and an encryption certificate  with 
KeyUsage=Key Encipherment (20)

A third certificate for use with login or to authenticate with client TLS  or windows smart card login which uses PKINIT,  may be present.

**Comment by mouse07410** [comment]
Briefly browsing through `zaza.txt`, I can say that this certificate is not usable for S/MIME (assuming `certutil` showed exactly what's in that cert, nothing more and nothing less):

- Not good for S/MIME Encryption because it doesn't have *Key Encryption* key usage specified
- Not good for S/MIME Signature because it does not have Digital Signature (and probably Non-Repudiation) specified

Therefore no surprise Outlook refused to work with it. It's probably only good for encrypted filesystem, and maybe not even there.

**Comment by ldti** [comment]
i do not think that certutil even displays these. MMC however does.
![image](https://cloud.githubusercontent.com/assets/11959365/15272896/63a5de6c-1a90-11e6-8035-d3bd968c9c94.png)

**Comment by dengert** [comment]
Were you even able to use Outlook with any certificate? For example the certificates/keys from your employer's MS CA that were on your card, or any certificate/keys in software?

Show your problem is not with the certificates/keys before assuming it is a token issue. 
What is the difference between the certificates/keys that do work, and the one you are trying to use on the card?

Try using Thunderbird instead of Outlook see if it an Outlook issue.   Thunderbird's "security Devices" are PKCS#11 shared libs or DLLs. Use the opensc-pkcs11.dll   

Export your certificate  as a CER file and add it to this issue if you want real help with the certificate attributes. Snip-its of partial windows are not very helpful.

Add the non-repudation KeyUsage bit to signing certificate. 

Google for : x509 keyUsage Outlook

**Comment by ldti** [comment]
i as able to use locally generated (computer stored) certificates with outlook.

i will attempt to generate a new cert and will attach the public key here.

**Comment by ldti** [comment]
Public cert attached.
[aa.cer.txt](https://github.com/OpenSC/OpenSC/files/291839/aa.cer.txt)

**Comment by mouse07410** [comment]
First, you really should've uploaded it as `aa.cer.zip`. Bad...

Second, I don't know how important it is, but all my email certificates have *Extended Key Usage* set to include *Email Protection* - which yours does not. You may want to specify that (some software would assume "any" if no Extended Key Usage was provided, some would assume "none").

Third, some software today just refuses to work with certificates signed by SHA1, and insist on at least SHA256.

**Comment by ldti** [comment]
My key has Secure Email (1.3.6.1.5.5.7.3.4) EKU. do you mean something different?

**Comment by frankmorgner** [comment]
have you activated the windows service "Certificate Autoenrollment"?

**Comment by ldti** [comment]
what is the relevance of this? the client is not domain joined.

**Comment by frankmorgner** [comment]
Have you tried?

**Comment by scottthomas007** [comment]
I am having the same issue with SmartCard-HSM on Windows 10 on Microsoft Word & Outlook 2019
