### ISSUE TITLE
[ePass2003] Add second id: Failed to store PIN: Incorrect parameters in APDU

### ISSUE THREAD

**Issue by vDorst** [OpenSC/OpenSC#760]
### Expected behaviour

What should happen?

Create a second id.

### Actual behaviour

Error.
```
Using reader with a card: FS USB Token 0
Failed to store PIN: Incorrect parameters in APDU
```

### Steps to reproduce

1. pkcs15-init -P -l "rra" -a 02 --generate-key rsa/2048 --pin test123 --puk 1234567890123456

### Logs

Windows 8.1 Pro, OpenSC-0.16.0-rc2-win32_vs12-Release.msi: https://gist.github.com/vDorst/2205b3bf8ad9a60199bb42c2f4136bcb

Linux log, Fedora 23 OpenSC-0.15.0-4.fc23: https://gist.github.com/vDorst/9493a2419e898e7cd17c429105c469a2

Maybe related to #720?

### Extra Info

Key was created with PKCS15+ONEPIN profile.

**Comment by vDorst** [comment]
Updated version numbers.

**Comment by FeitianSmartcardReader** [comment]
@vDorst This is Ben, from Feitian tech team. Let us do check on our side and back to you, should be tomorrow, thanks

**Comment by dengert** [comment]
is the pin your are trying to use "test123" as the PIN?   PINs usually only have digits.

**Comment by vDorst** [comment]
yes.
My first id also has a alphanumeric pin which works as expected.
With digits only results in the same error.

```
pkcs15-init --store-pin --id 02 --pin 123456 --puk 1234567890123456
Using reader with a card: Feitian ePass2003 00 00
Failed to store PIN: Incorrect parameters in APDU
```

**Comment by vDorst** [comment]
I think I made a error. I would like to make another authid so i should used `-a` instead of `--id`.
Still results in the same error.

My pkcs15-tool -D output before running command below
https://gist.github.com/vDorst/cf4a38e133fb998ce1dadc7f176bd690

`pkcs15-init --store-pin -a 3 --pin 123456 --puk 1234567890123456 -vv`
```
0x7fe9aa912700 16:37:57.009 [pkcs15-init] reader-pcsc.c:307:refresh_attributes: returning with: 0 (Success)
0x7fe9aa912700 16:37:57.009 [pkcs15-init] reader-pcsc.c:383:pcsc_detect_card_presence: returning with: 1
Using reader with a card: Feitian ePass2003 00 00
0x7fe9aa912700 16:37:57.009 [pkcs15-init] reader-pcsc.c:307:refresh_attributes: returning with: 0 (Success)
0x7fe9aa912700 16:37:57.009 [pkcs15-init] reader-pcsc.c:383:pcsc_detect_card_presence: returning with: 1
Connecting to card in reader Feitian ePass2003 00 00...
0x7fe9aa912700 16:37:57.009 [pkcs15-init] card.c:148:sc_connect_card: called
0x7fe9aa912700 16:37:57.009 [pkcs15-init] reader-pcsc.c:307:refresh_attributes: returning with: 0 (Success)
0x7fe9aa912700 16:37:57.014 [pkcs15-init] card-entersafe.c:106:entersafe_match_card: called
Using card driver epass2003.
Found <<MyCard>>
About to store PIN.
0x7fe9aa912700 16:37:57.789 [pkcs15-init] pkcs15-epass2003.c:193:epass2003_pkcs15_pin_reference: called
0x7fe9aa912700 16:37:57.789 [pkcs15-init] pkcs15-epass2003.c:202:epass2003_pkcs15_pin_reference: returning with: 0 (Success)
0x7fe9aa912700 16:37:57.789 [pkcs15-init] pkcs15-epass2003.c:221:epass2003_pkcs15_create_pin: called
0x7fe9aa912700 16:37:57.855 [pkcs15-init] pkcs15-epass2003.c:289:epass2003_pkcs15_create_pin: returning with: -1205 (Incorrect parameters in APDU)
Failed to store PIN: Incorrect parameters in APDU
0x7fe9aa912700 16:37:57.876 [pkcs15-init] ctx.c:802:sc_release_context: called
```

**Comment by dengert** [comment]
Just to make sure we are not dealing with another problem with sc_hex_to_bin,
can you make sure your test uses a 2 digit id? ( #753 and its many friends.)

Also looking at  card-entersafe.c it would appear that only 3 pins are allowed. User pin 0x01 and PUK 0x02 You are trying to write a pin 3.

Are you sure the card can have more then 2 pins?


Are you sure the card can have more PINS?

**Comment by vDorst** [comment]
`pkcs15-init --store-pin -a 03 --pin 123456 --puk 1234567890123456 -vv`
```
2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success)
2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:402:pcsc_detect_card_presence: returning with: 5
Using reader with a card: FS USB Token 0
2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success)
2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:402:pcsc_detect_card_presence: returning with: 5
Connecting to card in reader FS USB Token 0...
2016-05-17 19:20:49.765 [pkcs15-init] card.c:196:sc_connect_card: called
2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success)
2016-05-17 19:20:49.765 [pkcs15-init] card-entersafe.c:134:entersafe_match_card: called
Using card driver epass2003.
Found <MyCard>>
About to store PIN.
2016-05-17 19:20:50.531 [pkcs15-init] pkcs15-epass2003.c:193:epass2003_pkcs15_pin_reference: called
2016-05-17 19:20:50.531 [pkcs15-init] pkcs15-epass2003.c:202:epass2003_pkcs15_pin_reference: returning with: 0 (Success)
2016-05-17 19:20:50.546 [pkcs15-init] pkcs15-epass2003.c:221:epass2003_pkcs15_create_pin: called
2016-05-17 19:20:50.609 [pkcs15-init] pkcs15-epass2003.c:289:epass2003_pkcs15_create_pin: returning with: -1205 (Incorrect parameters in APDU) 
Failed to store PIN: Incorrect parameters in APDU
2016-05-17 19:20:50.609 [pkcs15-init] ctx.c:840:sc_release_context: called
```

> Are you sure the card can have more then 2 pins?
> Are you sure the card can have more PINS?

I am not sure. That is also the problem I am not sure what this token really can do.
I was hoping that [Wiki ePass2003](Feitian-ePass2003) was more up-to-date and providing information about the token, software usages and limitations.

I found it useful to have multiple pins.
For example to separate personal stuff and work.

**Comment by dengert** [comment]
At one time http://gooze.eu was distributing Epass2003 with software. Looks like they have gone out of business some time after 2011 but see the web site.
Try sales@gooze.eu

They distributed a CD with documentation for their software, ssh, vpn, opensc and feitian. It was never clear to me if they loaded and
additional software onto the tokens they distributed.

Maybe you can find a version of the smartcard-quickstarter-guide.pdf online.

OpenSC has a libopensc/card-entersafe.c and a  libopensc/card-epass2003.c driver. There are also pkcs15init/pkcs15-entersafe.c and pkcs15init/pkcs15-epass2003.c

But for some reason, your trace shows card-entersafe.c and pkcs15-epass2003.c are being used.

For now assume only a PIN and a PUK. are usable.


On 5/17/2016 12:54 PM, René van Dorst wrote:
> |pkcs15-init --store-pin -a 03 --pin 123456 --puk 1234567890123456 -vv|
>
> |2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success) 2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:402:pcsc_detect_card_presence: returning
> with: 5 Using reader with a card: FS USB Token 0 2016-05-17 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success) 2016-05-17 19:20:49.765 [pkcs15-init]
> reader-pcsc.c:402:pcsc_detect_card_presence: returning with: 5 Connecting to card in reader FS USB Token 0... 2016-05-17 19:20:49.765 [pkcs15-init] card.c:196:sc_connect_card: called 2016-05-17
> 19:20:49.765 [pkcs15-init] reader-pcsc.c:323:refresh_attributes: returning with: 0 (Success) 2016-05-17 19:20:49.765 [pkcs15-init] card-entersafe.c:134:entersafe_match_card: called Using card driver
> epass2003. Found <MyCard>> About to store PIN. 2016-05-17 19:20:50.531 [pkcs15-init] pkcs15-epass2003.c:193:epass2003_pkcs15_pin_reference: called 2016-05-17 19:20:50.531 [pkcs15-init]
> pkcs15-epass2003.c:202:epass2003_pkcs15_pin_reference: returning with: 0 (Success) 2016-05-17 19:20:50.546 [pkcs15-init] pkcs15-epass2003.c:221:epass2003_pkcs15_create_pin: called 2016-05-17
> 19:20:50.609 [pkcs15-init] pkcs15-epass2003.c:289:epass2003_pkcs15_create_pin: returning with: -1205 (Incorrect parameters in APDU) Failed to store PIN: Incorrect parameters in APDU 2016-05-17
> 19:20:50.609 [pkcs15-init] ctx.c:840:sc_release_context: called |
>
>     Are you sure the card can have more then 2 pins?
>     Are you sure the card can have more PINS?
>
> I am not sure. That is also the problem I am not sure what this token really can do.
> I was hoping that Wiki ePass2003 <Feitian-ePass2003> was more up-to-date and providing information about the token, software usages and limitations.
>
> I found it useful to have multiple pins.
> For example to separate personal stuff and work.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/760#issuecomment-219799913>
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vDorst** [comment]
I wrote an email to Gooze. Waiting for his response.
In the meantime I hope @FeitianSmartcardReader provides us the information/support we need.

@FeitianSmartcardReader can we have more then one user pin?

**Comment by FeitianSmartcardReader** [comment]
@vDorst Sorry, the current epass2003 only support one PIN now. Gooze has feedback this issue to us before, but from our experience, The pkcs#11 only support one PIN. Is there have any specification has mentioned multi-PINs? If yes, please share us as well. thanks

**Comment by vDorst** [comment]
@FeitianSmartcardReader: Is only a different key. I think it is part of the PKCS15. What I reed is PrKDF points to a private key which points to a PIN. 
Maybe this can not be done at the moment because of the current profile. I try it out with a different profile.

![object](https://cloud.githubusercontent.com/assets/2149253/15353486/9ce4fc2a-1ce9-11e6-97c7-efce99aacd95.png)

Other questions:
- When do I known that the key supports `ECDSA 192/256 bit`?
- How to unblock/reinitialize the ePass2003?
- How to reformat back it too Feitian format?

**Comment by FeitianSmartcardReader** [comment]
@vDorst For init issue, I send you a private mail to you, you can do init on your side. Multi-PIN issue still need talk internal by our team. I will back to you when we got answers, thanks

**Comment by vDorst** [comment]
After init it is only possible to do profile pkcs15+onepin 
```
pkcs15-init.exe -C --profile pkcs15+onepin --pin 12345678 --puk 0102030405060708
Using reader with a card: FS USB Token 0
```

profile: pkcs15 or pkcs15+default 
```
pkcs15-init.exe -C --so-pin 12345678 --so-puk 0102030405060708 --pin 12345678 --puk 0102030405060708 --profile pkcs15+default -a 01
Using reader with a card: FS USB Token 0
Failed to create PKCS #15 meta structure: Security status not satisfied

pkcs15-init.exe -C --so-pin 12345678 --so-puk 0102030405060708 --pin 12345678 --puk 0102030405060708 --profile pkcs15 -a 01
Using reader with a card: FS USB Token 0
Failed to create PKCS #15 meta structure: Security status not satisfied

```

**Comment by FeitianSmartcardReader** [comment]
@vDorst The current COS only support one PIN, the tool just re-back token to normal. To change COS, it will related lots workload, I will need talk internal and to see how is going then back to you. Thanks,

**Comment by vDorst** [comment]
For now it is a noissue.
I close this one.
When I have time I shall update the Wiki.
