### ISSUE TITLE
 Command too long (265 bytes) for max: 261 bytes

### ISSUE THREAD

**Issue by scottthomas007** [OpenSC/OpenSC#769]
Hi,

I am facing issue while using smartcard-hsm on omnikey (3121) Reader.  

Details:

**smart card used =  smart card hsm 
smart card reader = OMNIKEY cardman 3121
OS = Ubuntu 14.04 LTS
opensc/pcsc/ccid installed using apt-get command

opensc version 0.13
smartcard hsm supports Extended APDU and OMNIKEY reader works with proprietary drivers only. However, following error occurs when i use ccid drivers.** 
--------------

/var/log/syslog given below 

PCSC-logs logs shows below. 
------------------------------------
**ay 26 10:26:34 Ubuntu pcscd: commands.c:1661:CmdXfrBlockTPDU_T0() Command too long (265 bytes) for max: 261 bytes**
May 26 10:26:34 Ubuntu pcscd: ifdwrapper.c:527:IFDTransmit() Card not transacted: 612
May 26 10:26:34 Ubuntu pcscd: winscard.c:1612:SCardTransmit() Card not transacted: 0x80100016

-------------------------------------

Due to failure of above command, following error occurred in the stronswan logs.  
------------------------------------------------------------------------------------------------------------------
**May 26 10:26:34 Ubuntu charon: 01[LIB] C_Sign() failed: GENERAL_ERROR
May 26 10:26:34 Ubuntu charon: 01[IKE] authentication of 'CN=device1, OU=strongswan' (myself) with RSA signature failed
May 26 10:26:34 Ubuntu charon: 01[IKE] IKE_SA test[1] state change: CONNECTING => DESTROYING
May 26 10:27:03 Ubuntu charon: 14[JOB] deleting half open IKE_SA after timeout
May 26 10:27:03 Ubuntu charon: 14[IKE] IKE_SA (unnamed)[2] state change: CONNECTING => DESTROYING
May 26 10:27:03 Ubuntu charon: 00[DMN] signal of type SIGINT received. Shutting down
May 26 10:27:03 Ubuntu kernel: [ 3346.345859] netlink: 24 bytes leftover after parsing attributes in process `ip'.
-------------------------------------------------------------------------------------**

Please guide and help

**Comment by LudovicRousseau** [comment]
Problem also reported as https://github.com/LudovicRousseau/PCSC/issues/11

**Comment by frankmorgner** [comment]
reported as not related to OpenSC in LudovicRousseau/PCSC#11
