### ISSUE TITLE
Towards-0.16.0 broke EC key derivation on a PIV token via pkcs11-tool 

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#771]
### Expected behaviour

Symmetric key should be generated and stored in the specified file, without any errors. Here's the output from the *master* branch of a few months ago (sorry, as this used to **always** work, I did not bother to re-test it often):
```
pkcs11-tool --module /Library/OpenSC/lib/opensc-pkcs11.so -l --derive -m ECDH1-COFACTOR-DERIVE -d 03 -i /tmp/derive.31436.pub.der -o /tmp/derive.31436.shared2
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using derive algorithm 0x00001051 ECDH1-COFACTOR-DERIVE

```

### Actual behaviour

```
$ OPENSC_DEBUG=9 pkcs11-tool -v --module /Library/OpenSC/lib/opensc-pkcs11.dylib -l --derive -m ECDH1-DERIVE -d 03 -i ephem256.pub.der -o t.bin
Using slot 0 with a present token (0x0)
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using derive algorithm 0x00001050 ECDH1-DERIVE
error: PKCS11 function C_DeriveKey failed: rv = CKR_GENERAL_ERROR (0x5)

Aborting.
$ OPENSC_DEBUG=9 pkcs11-tool -v --module /Library/OpenSC/lib/opensc-pkcs11.dylib -l --derive -m ECDH1-COFACTOR-DERIVE -d 03 -i ephem256.pub.der -o t.bin
Using slot 0 with a present token (0x0)
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using derive algorithm 0x00001051 ECDH1-COFACTOR-DERIVE
error: PKCS11 function C_DeriveKey failed: rv = CKR_GENERAL_ERROR (0x5)

Aborting.
```

Note that this process worked with the *master* branch. Also note that it still works with OpenSSL and libp11:
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -derive -inkey "pkcs11:object=KEY%20MAN%20key;object-type=private" -peerform DER -peerkey ephem256.pub.der -hexdump
engine "pkcs11" set.
PKCS#11 token PIN:
0000 - 16 2d 11 e2 19 f8 af 5f-97 c4 6f fa 39 65 5c 5b   .-....._..o.9e\[
0010 - 65 5a 5c fc eb bd 89 0a-d6 59 b8 ea e6 5d 95 8f   eZ\......Y...]..
$
```

Also note that specifying `--slot 0` (or whatever) does not change the outcome.

### Steps to reproduce

1. Generate a random EC key pair using OpenSSL 1.0.2h, like 
```
$ openssl ecparam -name prime256v1 -genkey -out ephem256.priv
$ openssl ec -in ephem256.priv -pubout -outform DER -out ephem256.pub.der
read EC key
writing EC key
$
```

2. Insert a PIV token (e.g., Yubikey NEO) with ECC keys

3. Invoke `pkcs11-tool` to derive a shared key:
```
$ pkcs11-tool -v --module /Library/OpenSC/lib/opensc-pkcs11.dylib -l --derive -m ECDH1-DERIVE -d 03 -i ephem256.pub.der -o t.bin
```

### Logs

The following log shows two attempts - one using `ECDH1-DERIVE`, the other one using `ECDH1-COFACTOR-DERIVE`. With the same result, of course.
[opensc-16-tool-broken.txt](https://github.com/OpenSC/OpenSC/files/288299/opensc-16-tool-broken.txt)

The following log shows how key derivation succeeds when `libp11` (under OpenSSL) drives OpenSC library:
[opensc-ssl-good.txt](https://github.com/OpenSC/OpenSC/files/288326/opensc-ssl-good.txt)

Excerpt from the error log:
```
0x7fff70ae2000 07:24:27.748 [opensc-pkcs11] reader-pcsc.c:270:pcsc_transmit:
Outgoing APDU (12 bytes):
00 87 11 9D 06 7C 04 82 00 85 00 00 .....|......
0x7fff70ae2000 07:24:27.748 [opensc-pkcs11] reader-pcsc.c:199:pcsc_internal_transmit: called
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] reader-pcsc.c:279:pcsc_transmit:
Incoming APDU (2 bytes):
6F 00 o.
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] apdu.c:386:sc_single_transmit: returning with: 0 (Success)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] apdu.c:539:sc_transmit: returning with: 0 (Success)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card-piv.c:503:piv_general_io: DEE r=0 apdu.resplen=0 sw1=6f sw2=00
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] iso7816.c:121:iso7816_check_sw: No precise diagnosis
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card-piv.c:515:piv_general_io: Card returned error
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card-piv.c:565:piv_general_io: returning with: -1200 (Card command failed)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card-piv.c:2334:piv_validate_general_authentication: returning with: -1200 (Card command failed)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card-piv.c:2419:piv_decipher: returning with: -1200 (Card command failed)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] sec.c:44:sc_decipher: returning with: -1200 (Card command failed)
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 07:24:27.765 [opensc-pkcs11] pkcs15-sec.c:279:sc_pkcs15_derive: use_key() failed: -1200 (Card command failed)
```

This is the excerpt from the "good" log, showing how key derivation succeeds (it's longer than 10 lines, sorry):
```
: Slot:0 Setting object handle of 0x0 to 0x7f8db343b060
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] pkcs11-object.c:126:sc_create_object_int: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] misc.c:254:session_start_operation: called
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] misc.c:255:session_start_operation: Session 0x7f8db350a3b0, type 5
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] framework-pkcs15.c:3668:pkcs15_prkey_derive: Initiating derivation
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] framework-pkcs15.c:3674:pkcs15_prkey_derive: derivation 0x7f8db350a3b0 0x7f8db3507410 0x7f8db343aa48 0x7f8db343b1e0 40 0x0 0
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] pkcs15-sec.c:252:sc_pkcs15_derive: called
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] pkcs15-sec.c:262:sc_pkcs15_derive: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] framework-pkcs15.c:3719:pkcs15_prkey_derive: Derivation complete. Result 0.
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] framework-pkcs15.c:3668:pkcs15_prkey_derive: Initiating derivation
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] framework-pkcs15.c:3674:pkcs15_prkey_derive: derivation 0x7f8db350a3b0 0x7f8db3507410 0x7f8db343aa48 0x7f8db343b1e0 40 0x7f8db343aa70 32
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] card.c:394:sc_lock: called
0x7fff70ae2000 08:30:23.615 [opensc-pkcs11] reader-pcsc.c:547:pcsc_lock: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] pkcs15-sec.c:252:sc_pkcs15_derive: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] padding.c:283:sc_get_encoding_flags: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] padding.c:287:sc_get_encoding_flags: iFlags 0x0, card capabilities 0x30010
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] padding.c:316:sc_get_encoding_flags: pad flags 0x0, secure algorithm flags 0x10000
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] padding.c:317:sc_get_encoding_flags: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card.c:394:sc_lock: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] sec.c:68:sc_set_security_env: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:2221:piv_set_security_env: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:2225:piv_set_security_env: flags=00000015 op=4 alg=2 algf=00010000 algr=00000100 kr0=9d, krfl=1
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:2252:piv_set_security_env: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] sec.c:72:sc_set_security_env: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] sec.c:40:sc_decipher: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:2417:piv_decipher: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:2281:piv_validate_general_authentication: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:454:piv_general_io: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:457:piv_general_io: 87 11 9d 71 : 255 256
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card.c:394:sc_lock: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card-piv.c:497:piv_general_io: calling sc_transmit_apdu flags=1 le=256, resplen=4096, resp=0x7fff5bf34150
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] apdu.c:550:sc_transmit_apdu: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] card.c:394:sc_lock: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] apdu.c:517:sc_transmit: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] apdu.c:371:sc_single_transmit: called
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] apdu.c:376:sc_single_transmit: CLA:0, INS:87, P1:11, P2:9D, data(71) 0x7fff5bf35240
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] reader-pcsc.c:269:pcsc_transmit: reader 'Yubico Yubikey NEO OTP+U2F+CCID'
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] reader-pcsc.c:270:pcsc_transmit:
Outgoing APDU (77 bytes):
00 87 11 9D 47 7C 45 82 00 85 41 04 EC 47 63 1F ....G|E...A..Gc.
C6 05 85 D2 FE 5F 54 AB 88 FF 77 B7 58 BD 97 7D ....._T...w.X..}
24 E1 BC 80 15 00 F3 09 9E 8C 8A F0 67 62 00 43 $...........gb.C
D1 4F B7 EA BC F6 BB 76 FF D2 D8 D7 CA E7 90 46 .O.....v.......F
88 D2 F1 92 39 50 37 07 D2 AE 28 17 00          ....9P7...(..
0x7fff70ae2000 08:30:23.616 [opensc-pkcs11] reader-pcsc.c:199:pcsc_internal_transmit: called
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] reader-pcsc.c:279:pcsc_transmit:
Incoming APDU (38 bytes):
7C 22 82 20 16 2D 11 E2 19 F8 AF 5F 97 C4 6F FA |". .-....._..o.
39 65 5C 5B 65 5A 5C FC EB BD 89 0A D6 59 B8 EA 9e\[eZ\......Y..
E6 5D 95 8F 90 00                               .]....
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] apdu.c:386:sc_single_transmit: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] apdu.c:539:sc_transmit: returning with: 0 (Success)
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card-piv.c:503:piv_general_io: DEE r=0 apdu.resplen=36 sw1=90 sw2=00
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card-piv.c:548:piv_general_io: DEE got buffer 0x7f8db343b8e0 len 36
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card-piv.c:565:piv_general_io: returning with: 36
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card-piv.c:2334:piv_validate_general_authentication: returning with: 32
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card-piv.c:2419:piv_decipher: returning with: 32
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] sec.c:44:sc_decipher: returning with: 32
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] pkcs15-sec.c:291:sc_pkcs15_derive: returning with: 32
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] card.c:434:sc_unlock: called
0x7fff70ae2000 08:30:23.736 [opensc-pkcs11] reader-pcsc.c:587:pcsc_unlock: called
0x7fff70ae2000 08:30:23.737 [opensc-pkcs11] framework-pkcs15.c:3719:pkcs15_prkey_derive: Derivation complete. Result 32.
```

**Addendum**
There is one difference: the working example of `pkcs11-tool` shown above, had incorrect *Key Usage* - it included both `KeyEncipherment` **and** `KeyAgreement`. As the standard says, for RSA only `KeyEncipherment` must be specified, and for EC (or DH) - only `KeyAgreement` (without `KeyEncipherment`). OpenSSL and libp11 work fine with the correct Key Usage as shown above.

**Comment by dengert** [comment]
On Ubuntu using OpenSC towards-0.16.0  88f85a2e  2016-05-23  with
    openssl 1.0.2 using NIST demo card \#5  with 384 bit key,works for
    me. 
    
    doug@XUbuntu-14:/tmp$ openssl ecparam -name secp384r1 -genkey -out
    ephem384.priv
    doug@XUbuntu-14:/tmp$ openssl ec -in ephem384.priv -pubout -outform
    DER -out ephem384.pub.der
    read EC key
    writing EC key
    doug@XUbuntu-14:/tmp$ openssl asn1parse -inform DER -in
    ephem384.pub.der -dump
        0:d=0  hl=2 l= 118 cons: SEQUENCE          
        2:d=1  hl=2 l=  16 cons: SEQUENCE          
        4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
       13:d=2  hl=2 l=   5 prim: OBJECT            :secp384r1
       20:d=1  hl=2 l=  98 prim: BIT STRING        
          0000 - 00 04 b1 0c 03 a8 c2 40-a9 fe b5 76 66 ad 8a a1  
    .......@...vf...
          0010 - 39 93 c7 19 18 11 44 9b-d7 a5 cb cd 73 7c 40 6f  
    9.....D.....s|@o
          0020 - 58 a1 95 57 b0 14 88 0c-9f c6 8c 8e 08 f3 bc 07  
    X..W............
          0030 - e0 1e ba 8c c4 3c ec c2-ba ca f8 05 6b ec 2e 59  
    .....<......k..Y
          0040 - 5c 3b 1d 17 21 f3 5d fc-de 14 11 66 e7 22 25 60  
    \;..!.]....f."%`
          0050 - d5 a2 3b 5e 70 6e 24 6f-10 9c 14 7b 18 81 1c ad  
    ..;^pn$o...{....
          0060 - e7 fc                                             ..
    pkcs11-tool -v --module /opt/smartcard/lib/opensc-pkcs11.so -l
    --derive -m ECDH1-COFACTOR-DERIVE -d 03 -i ephem384.pub.der -o t.bin
    Using slot 0 with a present token (0x0)
    Logging in to "PIV_II (PIV Card Holder pin)".
    Please enter User PIN: 
    Using derive algorithm 0x00001051 ECDH1-COFACTOR-DERIVE
    doug@XUbuntu-14:/tmp$ od -t x1 < t.bin
    0000000 0d a0 bd 05 d2 d1 6c 1d 67 b7 09 07 b2 fe 64 c7
    0000020 50 3d 6f 28 8b 49 79 37 02 61 9e 49 b1 1f 86 9e
    0000040 ff af 36 5f ed 9d 33 fa e0 4e fe 8a 56 c8 18 59
    0000060
    
    
    
    
    
    
      The following log shows two attempts - one using ECDH1-DERIVE,
        the other one using ECDH1-COFACTOR-DERIVE. With
        the same result, of course.
        opensc-16-tool-broken.txt
    
    
    In your dump I see:
    0x7fff70ae2000 07:23:34.304 [opensc-pkcs11]
    card-piv.c:2281:piv_validate_general_authentication: called
    0x7fff70ae2000 07:23:34.304 [opensc-pkcs11]
    card-piv.c:454:piv_general_io: called
    0x7fff70ae2000 07:23:34.304 [opensc-pkcs11]
    card-piv.c:457:piv_general_io: 87 11 9d 6 : 255 256
    
    Outgoing APDU (12 bytes):
    00 87 11 9D 06 7C 04 82 00 85 00 00 .....|......
    
    Note the length "6" in  in "card-piv.c:457:piv_general_io: 87 11 9d
    6 : 255 256"  line. It should be length of pubkey. What is in your ephem256.pub.der?
      it looks like pkcs11-tool could not parse the pubkey, which should
      be in the TLV "85"
      but it has "85 00" it should be "85 41" followed by "04 XX ..." 
      
      In mine I see:
     f0f0af73740 08:06:29.031 [opensc-pkcs11]
../../../src/src/libopensc/card-piv.c:2281:piv_validate_general_authentication:
    called
     4361 0x7f0f0af73740 08:06:29.031 [opensc-pkcs11]
    ../../../src/src/libopensc/card-piv.c:454:piv_general_io: called
     4362 0x7f0f0af73740 08:06:29.031 [opensc-pkcs11]
    ../../../src/src/libopensc/card-piv.c:457:piv_general_io: 87 14 9d
    103 : 255 256
    
    
    Outgoing APDU (109 bytes):
     4373 00 87 14 9D 67 7C 65 82 00 85 61 04 CA 44 1B 37
    ....g|e...a..D.7
     4374 F9 7E 1D 3D 88 E1 46 42 1F B1 3F B9 C4 C4 F0 23
    .~.=..FB..?....#
     4375 E6 9E BA 6E 94 6D C3 D3 85 B6 CE 33 81 59 0B B9
    ...n.m.....3.Y..
     4376 49 4F 14 C4 75 ED 33 0C 1B 9D C3 D3 38 B5 63 00
    IO..u.3.....8.c.
     4377 00 D1 C0 6D 80 75 EA D4 5B D9 78 BA AE 14 71 49
    ...m.u..[.x...qI
     4378 C4 ED 37 BF DB A6 99 23 FB 9C 33 83 F8 3A 62 6E
    ..7....#..3..:bn
     4379 FE EB 21 CD 88 99 A1 A2 DF 4F C6 52 00          ..!......O.R.
    
    Note length of 103  0x67, and "85 61" "04 XX..."
    
    
    
    
    
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> Note the length "6" in  in "card-piv.c:457:piv_general_io: 87 11 9d 6 : 255 256"  line. It should be length of pubkey. What is in your ephem256.pub.der? It looks like pkcs11-tool could not parse the pubkey, which should be in the TLV "85"  but it has "85 00" it should be "85 41" followed by "04 XX ..."

```
$ dumpasn1 -tilda ephem256.pub.der
  0  89: SEQUENCE {
  2  19: . SEQUENCE {
  4   7: . . OBJECT IDENTIFIER ecPublicKey (1 2 840 10045 2 1)
       : . . . (ANSI X9.62 public key type)
 13   8: . . OBJECT IDENTIFIER prime256v1 (1 2 840 10045 3 1 7)
       : . . . (ANSI X9.62 named elliptic curve)
       : . . }
 23  66: . BIT STRING
       : . . 04 EC 47 63 1F C6 05 85    ..Gc....
       : . . D2 FE 5F 54 AB 88 FF 77    .._T...w
       : . . B7 58 BD 97 7D 24 E1 BC    .X..}$..
       : . . 80 15 00 F3 09 9E 8C 8A    ........
       : . . F0 67 62 00 43 D1 4F B7    .gb.C.O.
       : . . EA BC F6 BB 76 FF D2 D8    ....v...
       : . . D7 CA E7 90 46 88 D2 F1    ....F...
       : . . 92 39 50 37 07 D2 AE 28    .9P7...(
       : . . 17                         .
       : . }

0 warnings, 0 errors.
$ openssl ec -inform DER -in ephem256.pub.der -pubin -text -noout
read EC key
Private-Key: (256 bit)
pub:
    04:ec:47:63:1f:c6:05:85:d2:fe:5f:54:ab:88:ff:
    77:b7:58:bd:97:7d:24:e1:bc:80:15:00:f3:09:9e:
    8c:8a:f0:67:62:00:43:d1:4f:b7:ea:bc:f6:bb:76:
    ff:d2:d8:d7:ca:e7:90:46:88:d2:f1:92:39:50:37:
    07:d2:ae:28:17
ASN1 OID: prime256v1
NIST CURVE: P-256
$
```

And here's the ZIP of the key itself:
[ephem256.pub.der.zip](https://github.com/OpenSC/OpenSC/files/288454/ephem256.pub.der.zip)

What's strange is that OpenSSL and libp11 don't seem to find it difficult to parse this key... ???

**Comment by mouse07410** [comment]
I've added debugging print in `pkcs11-tool`:
```
		len = EC_POINT_point2oct(ecgroup, ecpoint, POINT_CONVERSION_UNCOMPRESSED, buf, sizeof(buf),NULL);

		// Dump converted EC Pubkey
		if (verbose) {
		  fprintf(stderr, "  pkcs11-tool.derive_key(): point (%d bytes):\n", len);
		  for (int ii = 0; ii < len; ii++) {
		    if (ii > 0 && (ii % 16 == 0)) fprintf(stderr, "\n");
		    fprintf(stderr, "%02x ", buf[ii]);
		  }
		  fprintf(stderr, "\n");
		}
		
		memset(&ecdh_parms, 0, sizeof(ecdh_parms));
```

This is the result:
```
$ OPENSC_DEBUG=9 src/tools/.libs/pkcs11-tool -v --module /Library/OpenSC/lib/opensc-pkcs11.so -l --derive -m ECDH1-COFACTOR-DERIVE -d 03 -i ephem256.pub.der -o t.bin
Using slot 0 with a present token (0x0)
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using derive algorithm 0x00001051 ECDH1-COFACTOR-DERIVE
  pkcs11-tool.derive_key(): point (65 bytes):
04 ec 47 63 1f c6 05 85 d2 fe 5f 54 ab 88 ff 77
b7 58 bd 97 7d 24 e1 bc 80 15 00 f3 09 9e 8c 8a
f0 67 62 00 43 d1 4f b7 ea bc f6 bb 76 ff d2 d8
d7 ca e7 90 46 88 d2 f1 92 39 50 37 07 d2 ae 28
17
error: PKCS11 function C_DeriveKey failed: rv = CKR_GENERAL_ERROR (0x5)

Aborting.
$
```

**Comment by mouse07410** [comment]
**Update**

I've added a few debugging prints to several functions presumably along the path of key derivation. It shows that when `pkcs11-tool.c:derive_key()` converts the EC pubkey it got from file, the length of the resulting octet string it passes down is correct, right to the point of invoking `p11->C_DeriveKey(session, &mech, key, newkey_template, 5, &newkey)`.

`framework-pkcs15.c:3674:pkcs15_prkey_derive: derivation 0x7ff5c2d01370 0x7ff5c2c211e0 0x7ff5c2e04648 0x7fff533c0e90 40 0x7ff5c2e04670 32` thinks that the input data is 40 bytes long.

However `pkcs15-sec.c:257:sc_pkcs15_derive: inlen = 0 *poutlen = 32` believes that the input is 0 bytes long, which appears to start the chain of failures.

**Comment by mouse07410** [comment]
OK, I think I found the bug. It is in file `src/tools/pkcs11-tool.c` in `derive_key()` function (not surprising).

The problem is that whoever placed declarations in lines 2677-2683 **within the switch statement** forgot that their scope **ends** when the switch block ends - and according to the C standard, the *compiler behavior is undefined*. So some compilers on some OS may free that memory but not do anything to it (and not re-allocate it), in which case this program would work. Some compilers may zeroize it, or re-allocate - in which case the program would fail. Apparently that's what's happening on Mac OS X with Xcode-7.3.1.

After I moved the declaration outside the switch block, everything stated working again as if by magic.

Please feel free to merge commit https://github.com/OpenSC/OpenSC/pull/773/commits/9d88ae3076dfede0c93b751c469d8149d17491bf from the PR https://github.com/OpenSC/OpenSC/pull/773 (the rest of that PR is not needed - I just don't know how to get rid of it without messing Git even worse).

**Comment by frankmorgner** [comment]
done in towards-opensc-0.16.0
