### ISSUE TITLE
Error with DNIe when doing gpg2 --card-status

### ISSUE THREAD

**Issue by Yajo** [OpenSC/OpenSC#774]
### Expected behaviour

GPG should let me work with my DNIe.

### Actual behaviour

```
gpg2 --card-status
gpg: OpenPGP card not available: Not supported
```

### Steps to reproduce

0. Fedora 23.
1. `pkcon install opensc pcsc-tools pcsc-lite-ccid gnupg2-smime`
2. `systemctl start pcscd.service`
3. `killall gpg-agent scdaemon`
4. `gpg2 --card-status`
5. `pcsc_scan` (this properly displays the DNIe information).

**Comment by frankmorgner** [comment]
You should go the the GPG team, not the OpenSC team!

**Comment by Yajo** [comment]
Oh sorry
