### ISSUE TITLE
towards-opensc-0.16.0 build is broken on Mac = it cannot find newer OpenSSL installations

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#781]
### Expected behaviour

Build should locate `libcrypto.dylib` and use it to link the binaries against.

### Actual behaviour

Build is forced to look only at the Apple-installed old OpenSSL (v0.9.8), and instead of using the existing OpenSSL-1.0.2h, downloads the current version from Github and statically links against it.

### Steps to reproduce

1. Get a current Mac OS X machine, say running 10.11.4+ with SIP enabled.
2. Install Macports (see https://www.macports.org/ for the installer and instructions).
3. Tell Macports to install new OpenSSL (`sudo port install openssl`).
4. For the fun of it, set env variables  `OPENSSL_CFLAGS=-I/opt/local/include` and `OPENSSL_LIBS=-L/opt/local/lib -lcrypto`
4. Get OpenSC and run the build.

You will see that despite the fact that you have a perfectly current perfectly working OpenSSL-1.0.2h (as of the time of this post), the script will re-download and re-build OpenSSL from scratch.

### Cause of the problem

`PKG_CONFIG_PATH` setting in `MacOSX/build-package.in` forces `pkg-config` to look **only** at the Apple-installed packages and ignore everything else. Since it is know that Apple-installed OpenSSL is 0.9.8 (i.e., quite older than the minimum 1.0.1 required), the test will always fail to find a suitable OpenSSL, and will always force downloading from Github and re-building OpenSSL from scratch. 

Setting of `PKG_CONFIG_PATH` is unnecessary if this installation has only the Apple-provided packages (in which case it just repeats the already hard-coded default path in the executable), and dead wrong if 3rd-party packages are installed, e.g. via Macports, Fink, HomeBrew, etc. etc.

### Proposed solution

Stop doing the wrong thing - do not set `PKG_CONFIG_PATH`. See https://github.com/OpenSC/OpenSC/pull/779

### Logs

[opensc-openssl-build.txt](https://github.com/OpenSC/OpenSC/files/291317/opensc-openssl-build.txt)

```
$ port installed openssl
The following ports are currently installed:
  openssl @1.0.2h_1+rfc3779 (active)
$ type openssl
openssl is hashed (/opt/local/bin/openssl)
$ openssl version
OpenSSL 1.0.2h  3 May 2016
$ git clone https://github.com/OpenSC/OpenSC.git OpenSC-test
Cloning into 'OpenSC-test'...
. . . . .
$ cd OpenSC-test
$ git checkout towards-opensc-0.16.0
Branch towards-opensc-0.16.0 set up to track remote branch towards-opensc-0.16.0 from origin.
Switched to a new branch 'towards-opensc-0.16.0'
$ ./bootstrap
autoreconf: Entering directory `.'
. . . . .
src/common/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
$ MacOSX/build
+ test -x ./configure
+ ./configure
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
. . . . .
OpenSC has been configured with the following options:

Version:                 0.16.0rc2
Version fix:             0
Version revision:        14
Git revision:            OpenSC-0.16.0-rc2-14-g2ba8764, rev: 2ba8764, commit-time: 2016-05-31 01:59:40 +0200
. . . . .
OPENSSL_CFLAGS:          -I/opt/local/include -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.1 -msse4.2 -ffunction-sections -fdata-sections
OPENSSL_LIBS:            -L/opt/local/lib -lssl -lcrypto
. . . . .
+ bash ./MacOSX/build-package
+ test -x ./configure
. . . . .
+ export PKG_CONFIG_PATH=/usr/lib/pkgconfig
+ PKG_CONFIG_PATH=/usr/lib/pkgconfig
+ pkg-config libcrypto --atleast-version=1.0.1
+ test -e /Users/ur20980/src/OpenSC-test/openssl_bin/lib/pkgconfig
+ test -e openssl
+ git clone --depth=1 https://github.com/openssl/openssl.git -b OpenSSL_1_0_2-stable
Cloning into 'openssl'...
remote: Counting objects: 2391, done.
remote: Compressing objects: 100% (2121/2121), done.
. . . . .
```

**Comment by frankmorgner** [comment]
fixed in master
