### ISSUE TITLE
Out of bounds write in libsm

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#785]
`sm_incr_ssc` performs an out of bounds write when `ssc` is bigger than 255 in https://github.com/OpenSC/OpenSC/blob/master/src/libsm/sm-common.c#L363. I think the local variable `ii` should be decremented instead of incremented in the `for`-loop.

@viktorTarasov you introduced the code in d30cd83a, could you have a look? (The previous implementation did actually decrement `ii`, see https://github.com/OpenSC/OpenSC/commit/d30cd83ad4b62f2d158cc7b61fa0022afc5d0af2#diff-66662ed51f27f035edd1548b0c664c08L240)

**Comment by frankmorgner** [comment]
@viktorTarasov do you want to check this with your cards before i fix this?

**Comment by viktorTarasov** [comment]
@frankmorgner 
Thanks, and sorry for the non-answering. 

The first question: how could it work with this bug?
Probably the counter had never needed more then one byte.

**Comment by frankmorgner** [comment]
exactly, you need to encrypt more than 255 APDUs (command *and* response) to trigger this. Anyway, it should be fixed now. You should test this with your cards, though.
