### ISSUE TITLE
Recent changes to the CI environment

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/OpenSC#791]
I just noticed some changes that I'm not perfectly comfortable with. However, they are in some regard a matter of taste, so I hope to get some input whether you agree or don't agree...
### Appveyor Configuration

bd1e7aa03297bcd63f2e88b6cc49e481ae418a65 changes the configuration to only use Visual Studio 2013. I think we should test all configurations that are known to work, i.e. we should re-enable all other configurations. @viktorTarasov what was the intent to remove VS2010/VS2015? Also, I'd like to go back to APPVEYOR_BUILD_VERSION in the naming convention as it generates a unique name of the installer per build.
### Coverity Scan

With 88f85a2ef1bc6009809f8edc815aee9bf63a7fa3 analysis was bound to the branch `towards-opensc-0.16.0` which doesn't exist anymore. I suggest to use a dedicated branch `coverity_scan` instead of constantly changing the configuration. When an analysis is needed (e.g. for a new release) I think we should push there even allowing to overwrite the git history. So nobody should rely on a consistent `coverity_scan` branch...
### Github Deployment

94e43b023d57fbf1f7f4d2f2d43a50d8ed329db1 lets AppVeyor export its binaries as Github releases. I am not sure if that's the right step. I think most people are expecting an official binary to come from the OpenSC team, instead of being auto-generated from some third party. I, personally, like to trust people instead of systems. At the very least the current setup has to be made explicit.

**Comment by martinpaljak** [comment]
1) I'd prefer to see the output of compilation from as many compilers as possible. There might be dependant components that only function with a specific version. Yet the latest version of a platform compiler should always be tested, even if not used for the binaries.
2) yes, push -f to a dedicated branch keeps everything simple, and keeps it a "configure once and forget" service (combine with a timed "twice a week" push)
3) Ideally the releases could be signed by someone from the team, if they are not, it doesn't really matter from where the binaries come from, a cloud buildhost is *almost* as good as anything else.

**Comment by viktorTarasov** [comment]
@frankmorgner 
> what was the intent to remove ...

As far as I remember it do not worked properly for the other configurations, also it was very long. So, for the release-preparation branch I reduced it to one configuration. After merge his configuration has been transfered to _master_.

We can restore it.

@frankmorgner 
> coverity scan

According to travis configuration coverity-scan has to be done for _master_.

@frankmorgner 
>  I, personally, like to trust people instead of systems ...

What do you propose? To restore build on dedicated platform controlled by someone from us?

@martinpaljak 
> 1)

Yes, for period between releases we can try to restore many compilers for _master_.

> 2)

I do not understood.
As for me, _push -f_ to dedicated branch has to be a common practice -- to not bring the non essential fix/dev commits to the _master_'s history after merge.

> 3)
Release tag is signed. To sign release binary -- for that, naturally,  I guess that build has to be done on platform owned by someone. 

Question: what about the _nightly-builts_? What are we expecting -- tag.gz, msi, linux packages..?

**Comment by frankmorgner** [comment]
I created https://github.com/OpenSC/OpenSC/pull/798 to resolve 1) and 2).

3), however, needs a deeper look; MSIs and PKGs are offering support for signing which should be used if possible. Of course, we may still use the CI binaries as convenient nightly-builds.

**Comment by frankmorgner** [comment]
closed with https://github.com/OpenSC/OpenSC/pull/874

**Comment by frankmorgner** [comment]
@viktorTarasov, please have a look at https://travis-ci.org/OpenSC/OpenSC/builds/171959051. All builds on master are selected for coverity analysis with the result that no configuration actually performs the standard build. This is essentially the same behaviour as already reported in https://github.com/OpenSC/OpenSC/pull/798#issuecomment-229319505 for a forked repository, but it now also affects @OpenSC.

We will get no feedback if builds on *master* are failing. In consequence, coverity analysis **must done on a dedicated branch**.

**Comment by frankmorgner** [comment]
created a cron job in travis that weekly builds the scan on branch `coverity_scan` and automatically synchronizes with `master`
