### ISSUE TITLE
smartcard-hsm issue with open source ipsec solution 

### ISSUE THREAD

**Issue by develtech1** [OpenSC/OpenSC#792]
Hi all,

I am facing issue while using smartcard-hsm (CardContact) with strongswan ipsec tunnel.   I have already posted my query on strongswan wiki.  Link is given below.
https://wiki.strongswan.org/issues/1493

IPsec tunnel using smartcard-hsm works first time however after that it crashed the strongswan daemon (charon). However, we are getting  **C_Sign return (33/0x21) i.e. CKR_DATA_LEN_RANGE PKCS#11 error.** in the strongswan application.

Another vendor smart cards are perfectly working with the same strongswan setting however smartcard-hsm does not work.

pcscd logs are attached for analysis and guide us in this issue.
[pcscd_log_device-1.txt](https://github.com/OpenSC/OpenSC/files/304022/pcscd_log_device-1.txt)

**Comment by CardContact** [comment]
The PC/SC log looks perfectly fine.

Can you create an OpenSC log with OPENSC_DEBUG=9 ?

It would also be helpful to see what pkcs11-spy reports when monitoring the PKCS#11 interface. To enable this set PKCS11SPY=/usr/local/lib/opensc-pkcs11.so and load pkcs11-spy.so instead.

Generally hashing (if selected by CKM) is done in OpenSC with the raw PKCS#1 block passed to the SmartCard-HSM for signing. So if there is a length issue or buffer overrun, we would need to look for it in the OpenSC code.

Is the other smart card also accessed via OpenSC ?

**Comment by develtech1** [comment]
Thanks for response. 
As per your instruction, log attached using OPENSC_DEBUG=9  with pcscd. Can you check it please
[opensc_log.txt](https://github.com/OpenSC/OpenSC/files/306144/opensc_log.txt)

These logs were taken while using strongswan.

After that we  have tried to enable pkcs11spy in the strongswan but it gives error and do not use pkcs11 so.

**Jun  9 09:31:03 localhost charon: 00[DMN] Starting IKE charon daemon (strongSwan 5.4.0, Linux, mips64)**
**Jun  9 09:31:03 localhost charon: 00[CFG] C_GetFunctionList() error for 'opensc': DEVICE_ERROR**

I think, pkcs11-spy can not be used in this way. Can you guide please.

_yes, other card (cryptoflex) is also accessed by the opensc module in the strongswan._

**Comment by CardContact** [comment]
The opensc_log.txt does not contain the log information of OpenSC,but the output from pcscd.

Are you compiling for your platform (mips64) ? Which version of OpenSC ?

Can you try the PKCS#11 module from sc-hsm-embedded [1] instead ?

Andreas

[1] https://github.com/CardContact/sc-hsm-embedded

**Comment by develtech1** [comment]
Thanks a lot for reply.
Sorry for sharing pcscd logs instead of opensc logs. (earlier debug logs were commented in the opensc.conf)

I have attached opensc logs for your analysis.   Please search **CKR_DATA_LEN_RANGE** in the log file. It will show you the issue that we are facing.   

[opensc-debug_log.txt](https://github.com/OpenSC/OpenSC/files/315800/opensc-debug_log.txt)

**Comment by develtech1** [comment]
Sir, 
pkcs11-spy logs are also attached.  same **CKR_DATA_LEN_RANGE** error occurred.  
[log_pkcs11_dev1.txt](https://github.com/OpenSC/OpenSC/files/315843/log_pkcs11_dev1.txt)

**Comment by CardContact** [comment]
The behaviour can be explained by an intermediate card reset between the signing operations. If the card is reset, it loses the applet selection state and the next SIGN command is not processed by the applet, but the default selected card manager function. This will respond with 6700 to the extended length APDU, which leads to a CKR_DATA_LEN_RANGE (the error is misleading, but a correct mapping to the 6700 wrong length returned by the card.

Seems to me, that at "10:03:38.782" some process is reopening the connection to the device, which was reset after pkcs15-tool finished. Is this the same process that access the device until "10:03:20.749" ?

Who is running pkcs15-tool and why ? This interferes with the running PKCS#11 connection, leading to the observed problem.

**Comment by mouse07410** [comment]
Is this problem related to https://github.com/OpenSC/OpenSC/issues/786? If so, the solution that worked there, might help?

Reason I think there might be similarities is because in both cases another process appears to have affected the card's state between two consecutive operations of the first process.

**Comment by dengert** [comment]
An other example of OpenSC's problems with interference. Maybe @CardContact  wants to get involved with #624 and #797 discussions?

**Comment by mouse07410** [comment]
@develtech1 you're welcome!

Please be aware that #624 plus https://github.com/OpenSC/OpenSC/files/314137/797-card-piv.c.diff.txt, combined with https://github.com/mouse07410/OpenSC.tokend alleviates the need to set `disconnect_action = leave` (at least in most cases I'm aware of).
