### ISSUE TITLE
opensc-0.16.0 tarball missing autotools generated files

### ISSUE THREAD

**Issue by alonbl** [OpenSC/OpenSC#796]
Hello,

opensc-0.16 for some reason changed package name to OpenSC - which may be acceptable.
However, release tarball was not created using "make dist" causing all autotool generated files to be missing.
Can you please fix this and republish proper tarball?

Thanks!

**Comment by LudovicRousseau** [comment]
What archive are you using exactly?

I just checked "opensc-0.16.0.tar.gz" https://github.com/OpenSC/OpenSC/releases/download/0.16.0/opensc-0.16.0.tar.gz and the ``./configure`` script is present.

The archive named "Source code (tar.gz)" https://github.com/OpenSC/OpenSC/archive/0.16.0.tar.gz does NOT contain the ``./configure`` script.
I agree the names are confusing.

**Comment by alonbl** [comment]
Well, this[1] one...

[1] https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/

**Comment by LudovicRousseau** [comment]
Ah OK. You are right.
I don't know who/what uploaded the files to sourceforge.net

**Comment by alonbl** [comment]
It is a good mirror, what we fetch from always. Is it obsoleted now?

**Comment by frankmorgner** [comment]
Yes, it is, please use the Github releases. Obviously the automatic file import from Sourceforge doesn't work very reliably. @LudovicRousseau could you synchronize the packages?

**Comment by frankmorgner** [comment]
It could be that the source code from https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/ contains all of files from the git repository, which doesn't contain any generated autoconf files.

**Comment by LudovicRousseau** [comment]
I uploaded ``opensc-0.16.0.tar.gz`` from github to sf.net. This archive contains the ``./configure`` script.

I also removed ``OpenSC-0.16.0.tar.gz`` from sf.net to avoid confusion. Note the capitalisation differences between ``opensc`` and ``OpenSC`` in the file names.

**Comment by frankmorgner** [comment]
thanks
