### ISSUE TITLE
openssl - interfacing software implementation of PKCS#11 with libp11 engine

### ISSUE THREAD

**Issue by SyedElec** [OpenSC/OpenSC#799]
Hi,
I'm trying to interface a software implementation of PKCS#11 API using libp11 however I have some problems using it with openssl.

### Expected behaviour

What should happen?
I'm expecting to have basic functions from PKCS#11 API for instance C_Digest (I think digest functions are not implemented in libp11), C_Encrypt, C_Decrypt and C_GenerateKey going through my pkcs11 library.

### Actual behaviour

What happens instead?
From what I see in the code, some crypto is done by openssl like RSA key generation .

What I'm trying to have is an engine that doesn't using openssl functions but only pkcs11 functions for crypto operations, for instance, writing this command :
```echo -n "test" | openssl dgst -engine pkcs11 -sha1```
will open a user session, and call C_Digestinit, C_Digest.

other example :
```openssl enc -engine pkcs11 -aes-256-cbc -in test.txt -out file.enc```
will open a user session, call C_EncryptInit and C_Encrypt

Do I have to develop a new engine or can I still use libp11 ? Maybe I'm just don't understand how it really works. 

Thank you very much for your help.

**Comment by frankmorgner** [comment]
Quoting from the libp11 README:

>This code repository produces two libraries:

>  -  libp11 provides a higher-level (compared to the PKCS#11 library) interface to access PKCS#11 objects. It is designed to integrate with applications that use OpenSSL.
>  -  pkcs11 engine plugin for the OpenSSL library allows accessing PKCS#11 modules in a semi-transparent way.

I'm not sure what you want. Do you have a PKCS#11 library that you want to access via libp11? Do you have a PKCS#11 library that you want to access via OpenSSL?

**Comment by mouse07410** [comment]
libp11 is an interface to hardware tokens that speak PKCS#11. I don't think most of the tokens around are capable of doing on-card digest or encrypt. Usually all they can do is Sign and/or Decrypt/Derive.

The current libp11 works with OpenSSL quite well, AFAICT.

**Comment by SyedElec** [comment]
Thank you for your replies, what I want is accessing my PKCS#11 library via OpenSSL. My library includes Digest (MD5, SHA), Encrypt/Decrypt (AES, RSA ...), Sign/Verify, HMac functions. 
I need to be able to access these functions via OpenSSL and I think we can't do it without an engine, so I'm using libp11 as an engine.

As you said, libp11 is an interface to hardware tokens, and it only supports Sign and/or Decrypt/Derive, so I don't think I can use it for my purpose.

Is it possible to interface directly OpenSSL with PKCS#11 library without engine ?

Thank you for your help.

**Comment by frankmorgner** [comment]
You'll need the engine to use it in OpenSSL. And I agree with @mouse07410 that using `C_Digest` is only of limited use, because it doesn't involve a private key and can always be done in software.

But feel free to extend libp11's engine to delegate the other calls, too. We would be happy to review your pull request.
