### ISSUE TITLE
documentation of supported hardware spanish eID

### ISSUE THREAD

**Issue by mercuriete** [OpenSC/OpenSC#800]
I am using the spanish eID opensc mainstream driver and it works really good.

but in the documentation: https://github.com/OpenSC/OpenSC/wiki/Supported-hardware-(smart-cards-and-USB-tokens)

they said that is broken. I thought that this drivers was fully functional. For example i paid my spanish taxes this year using spanish eID and opensc.

Can you check the status of the driver and change the documentation because maybe is out of date.

Thanks for your work :smile:

**Comment by frankmorgner** [comment]
A lot of fixes got merged recently. Feel free to change the wiki page which seems quite outdated.
