### ISSUE TITLE
With OpenSC 0.16 CardOS card work only with readers advertising extended length support

### ISSUE THREAD

**Issue by vbadev** [OpenSC/OpenSC#802]
### Expected behaviour

CardOS cards should work with any reader.

### Actual behaviour

Signing with 2048 bit key works only with readers supported by libccid. With OmniKey tested readers C_SignFinal fails with CKR_GENERAL_ERROR. I have tested with five different readers:

1. ACS ACR 38U-CCID (072f:90cc) - driver libccid
2. ACS ACR38U (072f:9000) -  driver libacr38u 1.7.11-1.1 from Debian testing
3. OMNIKEY CardMan 3021 - latest HID Global driver for Linux (v4.2.8)
4. OMNIKEY CardMan 6121 - latest HID Global driver for Linux (v4.2.8)
5. Gemalto Prox Dual USB PC Link Reader - driver libccid

With readers that works trough libccid I can successfully sign, but with OMNIKEY readers and older ACR38U signing fails. There is no error in pcscd logs, but OpenSC debug log shows following error:

> reader-pcsc.c:199:pcsc_internal_transmit: called
> reader-pcsc.c:279:pcsc_transmit: 
Incoming APDU (2 bytes):
68 84 h.
> apdu.c:382:sc_single_transmit: returning with: 0 (Success)
> apdu.c:535:sc_transmit: returning with: 0 (Success)
> card-cardos.c:304:cardos_check_sw: chaining error
> card.c:434:sc_unlock: called
> iso7816.c:956:iso7816_decipher: APDU transmit failed: -1200 (Card command failed)
> sec.c:44:sc_decipher: returning with: -1200 (Card command failed)
> card.c:434:sc_unlock: called
> pkcs15-sec.c:221:sc_pkcs15_decipher: use_key() failed: -1200 (Card command failed)
> pkcs15-sec.c:369:sc_pkcs15_compute_signature: returning with: -1200 (Card command failed)
> card.c:434:sc_unlock: called
> reader-pcsc.c:583:pcsc_unlock: called
> framework-pkcs15.c:3572:pkcs15_prkey_sign: Sign complete. Result -1200.
> misc.c:61:sc_to_cryptoki_error_common: libopensc return value: -1200 (Card command failed)
> mechanism.c:447:sc_pkcs11_signature_final: returning with: 5
> mechanism.c:312:sc_pkcs11_sign_final: returning with: 5
> pkcs11-object.c:761:C_SignFinal: C_SignFinal() = CKR_GENERAL_ERROR

With git-bisect I have managed to locate commit that introduced this problem - e95b5151631f71fcee60a24d8d9d79f1c9719d8c.

### Steps to reproduce

1. Build and install OpenSC from commit after e95b5151631f71fcee60a24d8d9d79f1c9719d8c.
2. Run "pkcs11-tool -lt" with CardOS card plugged in reader that use different driver from libccid.

### Logs

I have attached opensc debug logs and pcscd apdu logs generated from running "pkcs11-tool -lt" with the same CardOS 4.4 card with OpenSC build from commit e95b5151631f71fcee60a24d8d9d79f1c9719d8c and from previous correctly working commit - 41f34fdbcf85673abc044c98a1685116f60e67d4 - [logs.tar.gz](https://github.com/OpenSC/OpenSC/files/320485/logs.tar.gz).

Card is CardOS 4.4, but with 4.3B result is the same. My system is Debian Testing amd64.

Output from pkcs11-tool -O:

> Using slot 0 with a present token (0x0)
> Public Key Object; RSA 2048 bits
>   label:      DB295C9C-2016-4F47-8E37-90EA8D3BE091
>   ID:         44423239354339432d323031362d344634372d384533372d393045413844334245303931
>   Usage:      encrypt, verify, wrap
> Certificate Object, type = X.509 cert
>   label:      DB295C9C-2016-4F47-8E37-90EA8D3BE091
>   ID:         44423239354339432d323031362d344634372d384533372d393045413844334245303931

**Comment by frankmorgner** [comment]
good:
```
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] sec.c:40:sc_decipher: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] iso7816.c:932:iso7816_decipher: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] card.c:394:sc_lock: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] apdu.c:513:sc_transmit: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] apdu.c:367:sc_single_transmit: called
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] apdu.c:372:sc_single_transmit: CLA:0, INS:2A, P1:80, P2:86, data(257) 0x1d14e50
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] reader-pcsc.c:269:pcsc_transmit: reader 'OMNIKEY CardMan (076B:3021) 3021 00 00'
0x7f796df0d700 15:22:52.313 [opensc-pkcs11] reader-pcsc.c:270:pcsc_transmit: 
Outgoing APDU (266 bytes):
00 2A 80 86 00 01 01 00 00 01 00 00 00 00 00 00 .*..............
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
48 9B DB 6C 79 7F 00 00 20 56 0E 6D 79 7F 00 00 H..ly... V.my...
40 06 70 D8 FF 7F 00 00 A8 09 41 00 00 00 00 00 @.p.......A.....
58 06 70 D8 FF 7F 00 00 01 00 00 00 00 00 00 00 X.p.............
E1 CB D8 6C 79 7F 00 00 00 00 00 00 00 00 00 00 ...ly...........
00 00 00 00 00 00 00 00 01 2A                   .........*
```
bad:
```
0x7ff147424700 15:15:10.418 [opensc-pkcs11] sec.c:40:sc_decipher: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] iso7816.c:932:iso7816_decipher: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] card.c:394:sc_lock: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] apdu.c:513:sc_transmit: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] apdu.c:367:sc_single_transmit: called
0x7ff147424700 15:15:10.418 [opensc-pkcs11] apdu.c:372:sc_single_transmit: CLA:10, INS:2A, P1:80, P2:86, data(255) 0xabbe50
0x7ff147424700 15:15:10.418 [opensc-pkcs11] reader-pcsc.c:269:pcsc_transmit: reader 'OMNIKEY CardMan (076B:3021) 3021 00 00'
0x7ff147424700 15:15:10.418 [opensc-pkcs11] reader-pcsc.c:270:pcsc_transmit: 
Outgoing APDU (260 bytes):
10 2A 80 86 FF 00 00 01 00 00 00 00 00 00 00 00 .*..............
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00 00 00 00 00 00 00 00 00 00 00 00 00 00 48 0B ..............H.
2D 46 F1 7F 00 00 20 C6 5F 46 F1 7F 00 00 A0 E7 -F.... ._F......
39 E5 FD 7F 00 00 A8 09 41 00 00 00 00 00 B8 E7 9.......A.......
39 E5 FD 7F 00 00 01 00 00 00 00 00 00 00 E1 3B 9..............;
2A 46 F1 7F 00 00 00 00 00 00 00 00 00 00 00 00 *F..............
00 00 00 00                                     ....
0x7ff147424700 15:15:10.418 [opensc-pkcs11] reader-pcsc.c:199:pcsc_internal_transmit: called
0x7ff147424700 15:15:10.456 [opensc-pkcs11] reader-pcsc.c:279:pcsc_transmit: 
Incoming APDU (2 bytes):
68 84 h.
```
The data you want to transmit is too big to fit into a short length APDU. I think https://github.com/OpenSC/OpenSC/commit/e95b5151631f71fcee60a24d8d9d79f1c9719d8c is good and should be kept. Is it possible to use chaining in cardos if you can only transmit a short length APDU?

**Comment by vbadev** [comment]
I do not know if the card support chaining. From 68 84 return code it looks that it do not support it.

After future investigation it looks that the problem is more on reader driver side, and not in OpenSC. OmniKey driver sets reader in extended APDU mode but do not report it in TLV properties at least for OmniKey 3021 reader. I now have tried OmniKey 3821 (pin pad reader), and it reports correct dwMaxAPDUDataSize (65536).

As max_send_size and max_recv_size options are honored after e95b5151631f71fcee60a24d8d9d79f1c9719d8c I will use them and will send feature request to HID Global to report dwMaxAPDUDataSize in TLV properties for all readers.

**Comment by vbadev** [comment]
Just want to add some more information:

I have talked to HID Global technical support and they answer was that TLV properties should be returned only for pin pad readers, so their driver works according to specification.
[Part 10 of PC/SC](http://www.pcscworkgroup.com/specifications/html/pcsc10_v2.02.09/#h.4d34og8) states that on GET_FEATURE_REQUEST call "Class 1 drivers should return Device_Success and no TLV structures".

As I do not see easy fix, I will just point every user with this problem to set max_send_size and max_recv_size to 1024 in OpenSC configuration file.

**Comment by frankmorgner** [comment]
@vbadev have you tried https://github.com/OpenSC/OpenSC/commit/b232c9b675fb286a5a9df02fb1fb5f39cbc96cd2 without forcing the transceive length via `opensc.conf`?

**Comment by frankmorgner** [comment]
Sorry, I just realized that it's the reader's limitation that's the problem, not the card's limitation in your case.

**Comment by frankmorgner** [comment]
One could do something like a whitelist with features for specific readers. That could, for example, be derived from @LudovicRousseau 's database about CCID readers, which have the transceive length in the USB descriptor.

**Comment by frankmorgner** [comment]
Or one could probe the transceive-length with an extended length APDU within the card's limit to provoke an error on the card's side. If, instead, the reader throws an error, this could indicate that the reader does not support extended length APDUs.

**Comment by vbadev** [comment]
I don't think that database of ccid readers can not be used for white list. Many OMNIKEY readers support extended APDU only when used with proprietary drivers from HID Global. With free libccid driver and with Microsoft ccid drivers they support only short apdu.

For example OMNIKEY 3821 (pin pad reader) reports short APDU level exchange, and dwMaxCCIDMessageLength of 271 bytes when tested with parse program from libccid, and this is listed on libccid reader matrix [[1]](https://pcsclite.alioth.debian.org/ccid/shouldwork.html#0x076B0x3821) [[2]](https://pcsclite.alioth.debian.org/ccid/readers/CardMan3821.txt). When OpenSC check for dwMaxAPDUDataSize, libccid return 0, but proprietary driver returns 65536.

Maybe valid solution will be to check transceive-length if driver do not report dwMaxAPDUDataSize. At least on Linux/Mac this will mean that most readers will not be checked.
