### ISSUE TITLE
OpenSC does not recognize HID smartcard Crescendo C1100

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#809]
### Expected behaviour

`opensc-tool -an` should fetch and output the appropriate info from the card.

### Actual behaviour

```
$ opensc-tool -an
Using reader with a card: SCM Microsystems Inc. SCR 3310
3b:df:96:ff:81:31:fe:45:5a:01:80:48:49:44:43:31:31:58:58:73:00:01:1b:09
Unsupported card
```

### Steps to reproduce

1. Get an [HID Crescendo C1100 card](https://www.hidglobal.com/products/cards-and-credentials/crescendo/c1100) and initialize/provision it.
2. Install the latest OpenSC *master* from the Github (you may apply #624 on top of it, doesn't make a difference).
3. Insert the card in a reader and try `opensc-tool -an`. Observe the error message.

### Logs

[opensc-ram-old.txt](https://github.com/OpenSC/OpenSC/files/330742/opensc-ram-old.txt)

**Comment by dengert** [comment]
Its an Unsupported card.  If you want to use the card, someone will have to write a driver. 
I see it says it _can_ support PIV, but you may have to order the cards with a PIV applet, then initialize them using the vendor's instructions. 

It does not respond to the piv_select_aid so it is not a PIV card.

**Comment by mouse07410** [comment]
Understood, thank you!
