### ISSUE TITLE
CKA_LOCAL flag using  C_GenerateKey or C_CreateObject

### ISSUE THREAD

**Issue by SyedElec** [OpenSC/OpenSC#811]
Hi,

I have a question regarding PKCS#11 specification. 

The C_CreateObject function specifies that if it is used to create a key object, then this key object will have the CKA_LOCAL set to False. 

![Image](http://s38.imgup.net/2fbfc.jpg)

However using the C_GenerateKey will need to set the flag to True.

![Image](http://m66.imgup.net/pkcs-11v2-d9b5.jpg)

And other-where in the documentation we can read, that CKA_LOCAL must not be set for these 2 functions.

![Image](http://c63.imgup.net/3617a.jpg)

At the end, does the CKA_LOCAL flag need to be set or not using either C_CreateObject or C_GenerateKey ? if yes, which value does it take if I need to implement generation of a key using C_GenerateKey that uses C_CreateObject function ?

Thank you for your help.

**Comment by dengert** [comment]
What version of the PKCS#11 are you reading? (Please don't send
    images of pages, just the text or reference. )
    
    CKA_LOCAL is not set by the caller, but by the token or PKCS#11
    middleware.  It is an indication of where and how the key was
    generated and combined with  CKA_SENSITIVE, CKA_ALWAYS_SENSITIVE and
    some others attributes is an indication of who else may know the
    private key now or in the future. 
     
    When you use C_CreateObject to create a key, the template provides
    the public or private key, to PKCS#11 and/or the token. So obviously
    the calling application knows the key and it CKA_LOCAL must be
    false.
    
    You probably should be looking at C_GenerateKeyPair and not
    C_GenerateKey. C_GenerateKey is for secret keys like AES or 3DES,
    creating domain parameters.  C_GenerateKeyPair would be for RSA or
    EC keys. 
    
    PKCS#11 2.40 Says:
    "The key objects created by a successful call to C_GenerateKeyPair
    will have their CKA_LOCAL
    attributes set to CK_TRUE.
    Note carefully the order of the arguments to C_GenerateKeyPair. The
    last two arguments do not have
    the same order as they did in the original Cryptoki Version 1.0
    document. The order of these two
    arguments has caused some unfortunate confusion."
    
    The problem here is many tokens don't have many of these attributes
    stored on the token, and there is no way to prove that the private
    key was generated on the token or if it is extractable. You have to
    trust the token vendor, the PKCS#11 middleware  the card issuer
    policies and their card management systems. 
    
    
    
    On 6/28/2016 8:08 AM, Sid-Ali wrote:
    
    
      Hi,
      I have a question regarding PKCS#11 specification. 
      The C_CreateObject function specifies that if it is used to
        create a key object, then this key object will have the
        CKA_LOCAL set to False. 
      
      However using the C_GenerateKey will need to set the flag to
        True.
      
      And other-where in the documentation we can read, that
        CKA_LOCAL must not be set for these 2 functions.
      
      At the end, does the CKA_LOCAL flag need to be set or not using
        either C_CreateObject or C_GenerateKey ? if yes, which value
        does it take if I need to implement generation of a key using
        C_GenerateKey that uses C_CreateObject function ?
      Thank you for your help.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by SyedElec** [comment]
Sorry for the images, I'm using latest documentation PKCS#11 V2.30 core specification `pkcs-11v2-30b-d6` from [RSA Laboratories](http://www.emclink.net/emc-plus/rsa-labs/standards-initiatives/pkcs-11-cryptographic-token-interface-standard.htm).

The references are located p.82 for CKA_LOCAL attribute information, and p.68 for corresponding footnotes. (I don't understand this part that says CKA_LOCAL attribute must not be specified)

The CKA_LOCAL attribute is described p.132 for C_CreateObject and p.179 for C_GenerateKey.

A key created by C_CreateObject function has its CKA_LOCAL flag set to false but a key generated by C_GenerateKey (or C_GenerateKeyPair) has its CKA_LOCAL flag set to true but for both functions we provide a template, I suppose the template for C_CreateObject must include every attribute for a key however for C_GenerateKey (or C_GenerateKeyPair) we only provides special key attributes needed to generate a key, no need to provide its class or type. This is the differences I see for generating a key object using these functions.

**Comment by dengert** [comment]
On 6/29/2016 3:15 AM, Sid-Ali wrote:
    
    
      Sorry for the images, I'm using latest documentation PKCS#11
        V2.30 core specification pkcs-11v2-30b-d6 from RSA
          Laboratories.
    
    There is a 2.40 from:
    https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=pkcs11
    
    Note that not all pkcs#11 implementations implement  all  the
    features you may be looking for.  The CK_LOCAL (as best I can tell)
    has not changed since version 2.01 12/22/1997 
    
    
      The references are located p.82 for CKA_LOCAL attribute
        information, and p.68 for corresponding footnotes. (I don't
        understand this part that says CKA_LOCAL attribute must not be
        specified)
      The CKA_LOCAL attribute is described p.132 for C_CreateObject
        and p.179 for C_GenerateKey.
      A key created by C_CreateObject function has its CKA_LOCAL flag
        set to false but a key generated by C_GenerateKey (or
        C_GenerateKeyPair) has its CKA_LOCAL flag set to true but for
        both functions we provide a template, I suppose the template for
        C_CreateObject must include every attribute for a key however
        for C_GenerateKey (or C_GenerateKeyPair) we only provides
        special key attributes needed to generate a key, no need to
        provide its class or type. This is the differences I see for
        generating a key object using these functions.
    
    
    I don't understand what is your problem. Are you having a problem
    with OpenSC pkcs11?
    
    Do you have an example? 
     
    The OpenSC pkcs11-spy can be very helpful with debugging PKCS#11
    opertations. It can be used with other vendors pkcs11 libraries.
     See:
    https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC
    
    
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by SyedElec** [comment]
I don't have any problem regarding OpenSC module, it's working just fine.

I just want to understand PKCS#11 documentation that specifies to set CKA_LOCAL flag in C_CreateObject and C_GenerateKey but also specifies that it must not be set (p.38 and p.48 [from 2.40 doc](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=pkcs11))

**Comment by dengert** [comment]
I would speculate they say "must not be set" is because if they just
    ignored it, the programmer might get the wrong impression of what is
    going on. Better to catch the mistake while programming than find
    out later when  there is a security problem. CKA_LOCAL = true can
    really on be set by the token. 
    
    If you really want an explanation, ask Oasis.
    
    On 6/29/2016 8:48 AM, Sid-Ali wrote:
    
    
      I don't have any problem regarding OpenSC module, it's working
        just fine.
      I just want to understand PKCS#11 documentation that specifies
        to set CKA_LOCAL flag in C_CreateObject and C_GenerateKey but
        also specifies that it must not be set (p.38 and p.48 from
          2.40 doc)
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by SyedElec** [comment]
@dengert thank you very much, it's much clearer for me.
