### ISSUE TITLE
Errors with bash_completion

### ISSUE THREAD

**Issue by lifepillar** [OpenSC/OpenSC#813]
Hello,
I have installed OpenSC with Homebrew (OS X El Capitan). I also have bash_completion. After a recent update (v0.16.0), I have started to get the following errors when I open a terminal:

```
-bash: /usr/local/etc/bash_completion.d/cardos-tool: line 18: syntax error near unexpected token `)'
-bash: /usr/local/etc/bash_completion.d/cardos-tool: line 18: `        		)'
-bash: /usr/local/etc/bash_completion.d/cryptoflex-tool: line 18: syntax error near unexpected token `)'
-bash: /usr/local/etc/bash_completion.d/cryptoflex-tool: line 18: `        		)'
-bash: /usr/local/etc/bash_completion.d/dnie-tool: line 18: syntax error near unexpected token `)'
-bash: /usr/local/etc/bash_completion.d/dnie-tool: line 18: `        		)'
…
```

### Steps to reproduce

1. `brew install bash-completion opensc`
2. `source /usr/local/etc/bash_completion`

**Comment by frankmorgner** [comment]
Fixed with https://github.com/OpenSC/OpenSC/pull/793, this now is a problem purely in brew.

**Comment by anthonysomerset** [comment]
So this issue stems to the fact that Brew can't fix this until some point release is made by OpenSC project - users can manually specify getting direct from HEAD (https://github.com/Homebrew/homebrew-core/issues/5338) and this resolves by pulling latest source but this is not automatic for end users

could OpenSC consider a 0.16.1 release that means we can then do the necessary work on the brew side to fix this for most brew users of this this tool?
