### ISSUE TITLE
Fails to build on kFreeBSD

### ISSUE THREAD

**Issue by zedinosaur** [OpenSC/OpenSC#815]
From Debian user Andreas Beckmann <anbe@debian.org>:

> opensc FTBFS on kfreebsd-*, but previous versions built there:
> https://buildd.debian.org/status/fetch.php?pkg=opensc&arch=kfreebsd-amd64&ver=0.16.0~rc2-1&stamp=1464411154

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -DOPENSC_CONF_PATH=\"/etc/opensc/opensc.conf\" -I../../src -Wdate-time -D_FORTIFY_SOURCE=2 -DPKCS11_THREAD_LOCKING -pthread -I/usr/include/PCSC -fno-strict-aliasing -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -Wno-unused-parameter -Werror=declaration-after-statement -c card-dnie.c  -fPIC -DPIC -o .libs/card-dnie.o
card-dnie.c: In function 'dnie_ask_user_consent':
card-dnie.c:340:2: error: #error "Don't know how to handle user consent in this (rare) Operating System"
 #error "Don't know how to handle user consent in this (rare) Operating System"
  ^
Makefile:723: recipe for target 'card-dnie.lo' failed

```

**Comment by frankmorgner** [comment]
Try configuring with `--enable-dnie-ui`.

**Comment by frankmorgner** [comment]
I meant `--disable-dnie-ui`, of course

**Comment by zedinosaur** [comment]
That's a good point as a workaround, but should this driver actually work under FreeBSD?

**Comment by zedinosaur** [comment]
I believe it did work (or at least build) previously.

**Comment by dengert** [comment]
Why is card-dnie.c doing anything with a UI? Other cards let the OpenSC handle PKCS#15 user_consent as PKCS#11 attribute CKA_ALWAYS_AUTHENTICATE. The calling application then has to get the PIN and call C_Login with  userType = CKU_CONTEXT_SPECIFIC. There is even opensc.conf flags to help with applications that don't understand CKU_CONTEXT_SPECIFIC.

**Comment by frankmorgner** [comment]
I think the idea was to give consent without entering the PIN.
