### ISSUE TITLE
Crash attempting to query AIS card

### ISSUE THREAD

**Issue by programatix** [OpenSC/OpenSC#824]
### Expected behaviour

What should happen?
I'm not expecting a crash
### Actual behaviour

What happens instead?
The application crashed (opensc-explorer.exe, opensc-tool.exe and etc)
### Steps to reproduce

I'm using Windows 10. I tried OpenSC 32-bit and 64-bit with same result.
1. added custom ATR using "Gemalto MultiApp IAS/ECC v1.0.1" config in opensc.conf
2. execute "opensc-tool --atr -v -v -v"
3. crashed with message "OpenSC command line tool has stopped working."

Additional info
If I set "debug_file" in opensc.conf, it doesn't crash.
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

https://gist.github.com/programatix/96396074e23815971af14b7f44e7ec2d

**Comment by frankmorgner** [comment]
You could try running this on Unix in gdb or similar. This would tell the exact place where the program crashes...

@viktorTarasov ?

**Comment by programatix** [comment]
I traced the source code and I think I can safely say that it crashed when calling module_init from dll-tool.dll.

**Comment by programatix** [comment]
I meant smm-local.dll

**Comment by viktorTarasov** [comment]
On Win7-64x with the latest release I do not have such problems.
Will try to find the Win10.

**Comment by viktorTarasov** [comment]
I do not have problems on Win10-64 with the [_latest release_](https://github.com/OpenSC/OpenSC/releases/download/0.16.0/OpenSC-0.16.0-win64_vs12-Release.msi).

Have you used the same release?

**Comment by viktorTarasov** [comment]
> If I set "debug_file" in opensc.conf, it doesn't crash.

Well, taking into consideration this remark, I also have segfault.

**Comment by viktorTarasov** [comment]
Dedicated PR #910 created.
