### ISSUE TITLE
pkcs11-tool writes non-BER-encoded certificates to the card

### ISSUE THREAD

**Issue by Jakuje** [OpenSC/OpenSC#834]
```
pkcs11-tool --write-object file.cert --type=cert
```

where the `file.cert` is certificate in PEM format (`-----BEGIN CERTIFICATE-----`) is trying to write PEM to the card:

```
6: C_CreateObject
2016-07-20 17:43:02.905
[in] hSession = 0x1
[in] pTemplate[10]: 
    CKA_TOKEN             True
    CKA_VALUE             00007ffc794f0140 / 761
    00000000  2D 2D 2D 2D 2D 42 45 47 49 4E 20 43 45 52 54 49  -----BEGIN CERTI
    [...]
```

This should not happen. The 4441efa6 (PR #747) modified the `parse_certificate()` to accept such certificates and parse the appropriate fields from them, but didn't go down the lane of converting them to the format writeable to the card.

Per the `pkcs-11v2-11r1.pdf`, the `CKA_VALUE` for the certificates should contain

> BER-encoding of the certificate

According to [OpenSSL FAQ](https://www.openssl.org/docs/faq.html#PROG4), DER is special case of BER and we should be able to convert the PEM to DER encoding in the above mentioned function and return it to the `write_object()` function, which can write it to the card.

This requires some modification of the interface of the `parse_certificate()` function to allow modification of the buffer, or return some different buffer with data ready to write.

If I understand well, the original idea was to write the data directly to the card without any conversion (know what you write), but since we are half way there, I would consider implementing also this conversion. I can try to put together some pull request tomorrow.

**Comment by dengert** [comment]
Depends on what you think pkcs11-tool is all about. I have always
    looked at it as a development/test tool, not a do everything for
    every one too.
     
    A circumvention is to use
    openssl x509 -inform PEM -outform  DER -in file.cert -out
    file.cert.der
    
    PKCS#11 can also support multiple types of certificates
    CKA_CERTIFICATE_TYPE, of which one type is CKC_X_509. 
    It also says: "Other than providing access to certificate objects,
    Cryptoki does not attach any special meaning to certificates."
    for type CKC_X_509 the CKA_VALUE is DER. 
    For type CKC_WTLS the CKA_VALUE is Byte array
    
    If you feel changes are needed, submit a PR.
    
    
    On 7/20/2016 11:16 AM, Jakuje wrote:
    
    
      pkcs11-tool --write-object file.cert --type=cert

      where the file.cert is certificate in PEM format
        (-----BEGIN CERTIFICATE-----) is trying to write
        PEM to the card:
      6: C_CreateObject
2016-07-20 17:43:02.905
[in] hSession = 0x1
[in] pTemplate[10]: 
    CKA_TOKEN             True
    CKA_VALUE             00007ffc794f0140 / 761
    00000000  2D 2D 2D 2D 2D 42 45 47 49 4E 20 43 45 52 54 49  -----BEGIN CERTI
    [...]

      This should not happen. The 4441efa (PR #747)
        modified the parse_certificate() to accept such
        certificates and parse the appropriate fields from them, but
        didn't go down the lane of converting them to the format
        writeable to the card.
      Per the pkcs-11v2-11r1.pdf, the CKA_VALUE
        for the certificates should contain
      
        BER-encoding of the certificate
      
      According to OpenSSL FAQ,
        DER is special case of BER and we should be able to convert the
        PEM to DER encoding in the above mentioned function and return
        it to the write_object() function, which can write
        it to the card.
      This requires some modification of the interface of the parse_certificate()
        function to allow modification of the buffer, or return some
        different buffer with data ready to write.
      If I understand well, the original idea was to write the data
        directly to the card without any conversion (know what you
        write), but since we are half way there, I would consider
        implementing also this conversion. I can try to put together
        some pull request tomorrow.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by Jakuje** [comment]
I probably didn't read far enough in the specification. Thank you for the mentioning this case. Having different `CKC` certainly makes sense. But current [master have hard-coded](https://github.com/OpenSC/OpenSC/blob/master/src/tools/pkcs11-tool.c#L2234) `CKC_X_509`, which is DER without any discussion.

Manual conversion before writing the certificate is also possibility, but even development/test tool should prevent invalid inputs and guide the user to a proper usage. The manual page now says about accepts only DER input, which is not true.

One possibility is to revert the chunk allowing this behavior or to finish this feature and convert the certificate to DER. Or even add the possibility to change the `CKA_CERTIFICATE_TYPE`, but in that case we would need to specify the subject and friends, if we would be unable to parse the certificate, but this is probably too corner case for the development/test tool

I will check tomorrow what can be done and submit PR.

**Comment by Jakuje** [comment]
AFAIK the intended use case of the change in the PR #747 is to allow writing DER certificate, but reading the `certdata` from the PEM or different format, which might be a valid use case, but it bypasses the certificate "validation" and leads to possibility to write basically anything to the card.

The original feature (`--attr-from` switch) comes from 0d5d3eb1 more than 10 years ago and is strictly DER-only (though I am not sure about legitimate use case -- write some certificate, but store different `CKA_*` attributes? Should not we use also `parse_certificate()` on the thing we write to the card?

Just thinking aloud and clearing the thoughts. Correct me, if some of the assumptions are wrong.

**Comment by frankmorgner** [comment]
Indeed, using `parse_certificate()` to get the type should most appropriate. However, so far nobody requested this feature, so documenting the current limitation would be OK, too.

**Comment by frankmorgner** [comment]
@Jakuje are you planning to change this or should we close this as "wontfix"?

**Comment by Jakuje** [comment]
I would like to give it a try, but half a year ago I was not sure how to fix it so I would not break some other use case (`--attr-from file` would not contain whole certificate or so). Some ideas or hints would be welcome.

I will give it a try during next week.

**Comment by Jakuje** [comment]
Minimal viable fix can look like this:

```
diff --git a/src/tools/pkcs11-tool.c b/src/tools/pkcs11-tool.c
index c832a8b..8683576 100644
--- a/src/tools/pkcs11-tool.c
+++ b/src/tools/pkcs11-tool.c
@@ -1966,18 +1966,18 @@ gen_key(CK_SLOT_ID slot, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE *hSecretKey
 
 #ifdef ENABLE_OPENSSL
 static void	parse_certificate(struct x509cert_info *cert,
-		unsigned char *data, int len)
+		unsigned char *data, int len, int parse_only)
 {
 	X509 *x = NULL;
 	unsigned char *p;
 	int n;
 
-	if (!strstr((char *)data, "-----BEGIN CERTIFICATE-----"))
-		x = d2i_X509(NULL, (const unsigned char **)&data, len);
-	else {
+	if (parse_only && strstr((char *)data, "-----BEGIN CERTIFICATE-----")) {
 		BIO *mem = BIO_new_mem_buf(data, len);
 		x = PEM_read_bio_X509(mem, NULL, NULL, NULL);
 		BIO_free(mem);
+	} else {
+		x = d2i_X509(NULL, (const unsigned char **)&data, len);
 	}
 	if (!x) {
 		util_fatal("OpenSSL error during X509 certificate parsing");
@@ -2275,7 +2275,7 @@ static int write_object(CK_SESSION_HANDLE session)
 
 	if (need_to_parse_certdata) {
 #ifdef ENABLE_OPENSSL
-		parse_certificate(&cert, certdata, certdata_len);
+		parse_certificate(&cert, certdata, certdata_len, (opt_attr_from_file != NULL));
 #else
 		util_fatal("No OpenSSL support, cannot parse certificate");
 #endif
```

This basically limits the usage of PEM certificates to the reading cert data from them and avoids writing PEM certificates to the card. Tested with softhsm:

```
$ p11tool --provider=/usr/lib64/pkcs11/libsofthsm2.so --generate-rsa --login "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project"
$ certtool --generate-self-signed  --outfile=id_rsa.cert --provider /usr/lib64/pkcs11/libsofthsm2.so --load-privkey "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=9b05b3709e1025bc;token=My%20token%201;id=%49%dd%3c%c9%74%1b%f2%cc%02%74%14%44%9b%b5%67%b2%a6%23%af%d6;object=Test%20label;type=private"
$ openssl x509 -inform PEM -outform DER -in "id_rsa.cert" -out "id_rsa.cert.der"
$ ./pkcs11-tool --write-object "id_rsa.cert" --type=cert --id="42" --label="my cert"  --module /usr/lib64/pkcs11/pkcs11-spy.so
error: OpenSSL error during X509 certificate parsing
Aborting.
$ ./pkcs11-tool --write-object "id_rsa.cert.der" --type=cert --id="42" --label="my cert"  --module /usr/lib64/pkcs11/libsofthsm2.so
 (works)
```

What can be done to make it even better would be to convert the PEM certificate to DER under the hood, but again, I am not well knowledgeable about the `--attr-from` use cases so in ideal case I would like not to change its behavior.

Something like below seems to do the desired job:

```
diff --git a/src/tools/pkcs11-tool.c b/src/tools/pkcs11-tool.c
index c832a8b..53787c1 100644
--- a/src/tools/pkcs11-tool.c
+++ b/src/tools/pkcs11-tool.c
@@ -1966,18 +1966,28 @@ gen_key(CK_SLOT_ID slot, CK_SESSION_HANDLE session, CK_OBJECT_HANDLE *hSecretKey
 
 #ifdef ENABLE_OPENSSL
 static void	parse_certificate(struct x509cert_info *cert,
-		unsigned char *data, int len)
+		unsigned char *data, int len, unsigned char *contents,
+		int *contents_len)
 {
 	X509 *x = NULL;
 	unsigned char *p;
 	int n;
 
-	if (!strstr((char *)data, "-----BEGIN CERTIFICATE-----"))
-		x = d2i_X509(NULL, (const unsigned char **)&data, len);
-	else {
+	if (strstr((char *)data, "-----BEGIN CERTIFICATE-----")) {
 		BIO *mem = BIO_new_mem_buf(data, len);
 		x = PEM_read_bio_X509(mem, NULL, NULL, NULL);
+		/* Update what is written to the card to be DER encoded
+		 * If we use  --attr-from  do not check anything and write
+		 * blob to the card */
+		if (contents != NULL) {
+			unsigned char *contents_pointer = contents;
+			*contents_len = i2d_X509(x, &contents_pointer);
+			if (*contents_len < 0)
+				util_fatal("Failed to convert PEM to DER");
+		}
 		BIO_free(mem);
+	} else {
+		x = d2i_X509(NULL, (const unsigned char **)&data, len);
 	}
 	if (!x) {
 		util_fatal("OpenSSL error during X509 certificate parsing");
@@ -2275,7 +2285,8 @@ static int write_object(CK_SESSION_HANDLE session)
 
 	if (need_to_parse_certdata) {
 #ifdef ENABLE_OPENSSL
-		parse_certificate(&cert, certdata, certdata_len);
+		parse_certificate(&cert, certdata, certdata_len,
+			(opt_attr_from_file ? NULL : contents), &contents_len);
 #else
 		util_fatal("No OpenSSL support, cannot parse certificate");
 #endif

```
For basic use case without `--attr-from` checks the actual file and if it is PEM, coverts it to DER. Otherwise it does not do anything and writes whatever user provides (given the certificate data are extracted correctly from the file given as `--attr-from`). Comments welcomed before I will submit PR.

**Comment by frankmorgner** [comment]
Your second fix looks good and applies the least amount of magic to do what most people would expect and still allows a good amount of control.

**Comment by Jakuje** [comment]
Adding @DDvO if he has some objections, if it does not break some of his use cases intended by the change he introduced.
Otherwise I will fill a pull request with the second fix.

**Comment by DDvO** [comment]
Thanks for putting me in the loop here and sorry for the delay answering.

Indeed my respective intention in #747 was to allow PEM as input format (in addition to DER) when reading a cert from files with the `--write-object` option in conjunction with `--type cert`, but I failed to see the need to convert it internally to DER before writing it to the token. This is cured by the second fix by @Jakuje above.

The intention of the `--attr-from` option seems to be to take attribute values from a(nother) cert file. Yet when combined with  `--write-object<file>` and `--type cert`, the contents of `<file>` would still be written verbatim, as @Jakuje mentioned, to the token. This can still lead to PEM encoding being written. So I'd say in this situation one should better warn the user, or do another conversion: for instance replace in pkcs11-tool.c

    if (opt_object_class == CKO_CERTIFICATE && !opt_attr_from_file) {
        memcpy(certdata, contents, MAX_OBJECT_SIZE);
        certdata_len = contents_len;
        need_to_parse_certdata = 1;
    }

by 

    if (opt_object_class == CKO_CERTIFICATE) {
        if (opt_attr_from_file) {
            parse_certificate(contents, contents_len, contents, &contents_len);
        } else {
            memcpy(certdata, contents, MAX_OBJECT_SIZE);
            certdata_len = contents_len;
            need_to_parse_certdata = 1;
        }
    }

and drop from the above fix the comment lines 

                * If we use  --attr-from  do not check anything and write
                * blob to the card */

**Comment by Jakuje** [comment]
Thank you for the answer and clarifying the intentions. I polished the last patch and created the PR #998.
Again, tested with softhsm and pkcs11-sky and it looked ok.
