### ISSUE TITLE
Commit c5a95d4a5ae93e5960ee19988d86246aa688f453 breaks sc-hsm support

### ISSUE THREAD

**Issue by llogar** [OpenSC/OpenSC#845]
### Expected behaviour

`pkcs11-tool --login --pin ... --list-objects`

should display both privata and public key info:

```
Using slot 0 with a present token (0x0)
Private Key Object; RSA 
  label:      rsakey
  ID:         01
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 2048 bits
  label:      rsakey
  ID:         01
  Usage:      encrypt, verify, wrap
```

### Actual behaviour

instead it only shows 

```
Using slot 0 with a present token (0x0)
Private Key Object; RSA 
  label:      rsakey
  ID:         01
  Usage:      decrypt, sign, unwrap
```

The above mentioned commit shrinks the buffer for receiving data, causing 

`pkcs15-sc-hsm.c:278:sc_pkcs15emu_sc_hsm_decode_cvc: Could not decode card verifiable certificate: -1401 (Invalid ASN.1 object)`

error and failing this and possibly many other operations. 

Pull request #844 fixes this error.

**Comment by frankmorgner** [comment]
fixed in 94bedaab9358a1ff66840168f737c4568548c00d
