### ISSUE TITLE
Transmit failed while pkcs15-init

### ISSUE THREAD

**Issue by alex7654** [OpenSC/OpenSC#846]
### Expected behaviour
In former version I used the command >>pkcs15-init -C -T -l "SmartCard xy" --profile pkcs15+onepin<< to initialize my cryptoflex card.

### Actual behaviour
Now, using OpenSC-0.16.0-win64_vs12-Release.msi this command returns "Failed to create PKCS #15 meta structure: Transmit failed" after entering user PIN and user PUK.

### Steps to reproduce
Everytime I use the command pasted above.

### Logs
Using option -vvvvvvv:
Please, see
https://gist.github.com/alex7654/2a58f0860685a215ac91fa6b2e0874e5

Any help is highly appreciated.
Regards
Alexander

**Comment by frankmorgner** [comment]
Your card reader is throwing an error, your best chance is to get an other one, because it is no problem within OpenSC.

**Comment by alex7654** [comment]
Thank you for your reply. I just tried on another Windows-10-PC with another (internal Ricoh) card reader. I still get the same error. Please, see
https://gist.github.com/alex7654/fa8153f8f24e7a46194f1adf630c5f39

I also tried with a different card. "pkcs15-init -E -T" seems to work well on both readers. If I can provide additional details on this issue, please, let me know.

Regards
Alexander

**Comment by frankmorgner** [comment]
Which version of OpenSC has worked for you? Could you use `git bisect` to get the erroneous commit?

**Comment by alex7654** [comment]
Smart card bundle 0.10 worked perfectly on WindowsXP. I still have it running in a virtual machine. Due to the missing cryptoflex profile I could not use later versions on Windows8/10. Now that missing file issue seems resolved but now I got this tramsmit failed issue.
I read some of the git bisect documentation and tried to understand what bisect does and how I could find the erroneous commit but it seems to be beyond my technical understanding. Sorry, but I got no clue how to do that. If I can provide any other helpful information, please, let me know.

Regards
Alexander

**Comment by ValenMX** [comment]
If you use Win10, this can be problem:
"Transmit failed" bunch of errors appears on Windows 10, when u use manual typing of PINs and other input. It's related with some internal MS libs delay resctricted on Win10. Try to add keys with pin (like --new-pin) and so on. When tools running it w/o manual input, it works.

**Comment by alex7654** [comment]
I tried to use options --pin and --puk and it works :-). Thank you for figuring this out. Nevertheless I ran into other (obviously unrelated) issues when importing my certificates, as several things seem to have changed since the ancient version I used before. I will elaborate on these issues in a different threat.

Thanks for your help!
