### ISSUE TITLE
pkcs11-tool write public key without MODULUS_BITS attribute

### ISSUE THREAD

**Issue by SyedElec** [OpenSC/OpenSC#848]
Hi,
I created an OpenSSL key pair (2048bits), extracted the public key and wanted to store it into my token using pkcs11-tool.

### Expected behaviour
The expected behaviour would be to have the CKA_MODULUS_BITS attribute added with original key size (for example 2048bits)

What should happen?
```
Public Key Object; RSA 2048 bits
  label:      label
  ID:         123456
  Usage:      encrypt, verify, wrap
```

### Actual behaviour

I'm using command :
```
pkcs11-tool -l --pin 12345678 --write-object public.pem --usage-sign --usage-decrypt --usage-derive --type pubkey --id 123456 --label "label"
```

What happens instead?

```
warning: PKCS11 function C_GetAttributeValue(MODULUS_BITS) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

Public Key Object; RSA 0 bits
  label:      label
  ID:         123456
  Usage:      encrypt, verify, wrap
```

### Steps to reproduce

1. ```openssl genrsa -out private.pem 2048```
2. ```openssl rsa -in private.pem -pubout -out public.pem```
3. ```pkcs11-tool -l --pin 12345678 --write-object public.pem --usage-sign --usage-decrypt --usage-derive --type pubkey --id 123456 --label "label"```

Am I missing something ?
Thank you for your help.

**Comment by dengert** [comment]
What card are you using? 
    I assume you are using the OpenSC pkcs11 library. 
    
    CKA_MODULUS_BITS is not used when pkcs11-tool calls C_CreateObject
    (and PKCS#11 says it should not be used.)
    So problem does not look like it is in pkcs11-tool.c 
    
    It may be the driver for your card is not saving the size of the
    modulus to be used to respond with the CKA_MODULUS_BITS at a later
    time. 
    
    What is the point it writing the public key to a token if you don't
    write the private key too?
    Do you write the private key in a separate command?
    Do you write a certificate too?
    
    
    On 8/11/2016 7:02 AM, Sid-Ali wrote:
    
    
      Hi,
        I created an OpenSSL key pair (2048bits), extracted the public
        key and wanted to store it into my token using pkcs11-tool.
      Expected behaviour
      The expected behaviour would be to have the CKA_MODULUS_BITS
        attribute added with original key size (for example 2048bits)
      What should happen?
      Public Key Object; RSA 2048 bits
  label:      label
  ID:         123456
  Usage:      encrypt, verify, wrap

      Actual behaviour
      I'm using command :
      pkcs11-tool -l --pin 12345678 --write-object public.pem --usage-sign --usage-decrypt --usage-derive --type pubkey --id 123456 --label "label"

      What happens instead?
      warning: PKCS11 function C_GetAttributeValue(MODULUS_BITS) failed: rv = CKR_ATTRIBUTE_TYPE_INVALID (0x12)

Public Key Object; RSA 0 bits
  label:      label
  ID:         123456
  Usage:      encrypt, verify, wrap

      Steps to reproduce
      
        openssl genrsa -out private.pem 2048
        openssl rsa -in private.pem -pubout -out public.pem
        pkcs11-tool -l --pin 12345678 --write-object
            public.pem --usage-sign --usage-decrypt --usage-derive
            --type pubkey --id 123456 --label "label"
      
      Am I missing something ?
        Thank you for your help.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/OpenSC","title":"OpenSC/OpenSC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/OpenSC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"pkcs11-tool write public key without MODULUS_BITS attribute (#848)"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/OpenSC/issues/848"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by SyedElec** [comment]
Hi,

Thank you for your answer, I was writing the private key also but I think the driver was not taking into account the CKA_MODULUS_BITS... After updating it, it's working.

Thanks. I close the issue.
