### ISSUE TITLE
Flag CKA_ALWAYS_AUTHENTICATE is not displayed

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#851]
### Expected behaviour

I expect to see `CKA_ALWAYS_AUTHENTICATE` flag listed on a private key that has it set.

### Actual behaviour

This flag is not listed:
```
$ pkcs15-tool --list-keys 
. . . . .
Private RSA Key [SIGN key]
	Object Flags   : [0x1], private
	Usage          : [0x20E], decrypt, sign, signRecover, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 2048
	Key ref        : 156 (0x9C)
	Native         : yes
	Auth ID        : 01
	ID             : 02
. . . . .
```

### Steps to reproduce

1. Insert a PIV token.
2. Perform `pkcs15-tool --list-keys`
3. Observe that nowhere in the output this attribute/flag is listed for the keys that you know have it set.

**Comment by dengert** [comment]
CKA_ALWAYS_AUTHENTICATE is a PKCS#11 attribute, not PKCS#15 
      
      pkcs11-tool shows:
       Access:     always authenticate
      
    
    On 8/14/2016 8:40 AM, Mouse wrote:
    
    
      Expected behaviour
      I expect to see CKA_ALWAYS_AUTHENTICATE flag
        listed on a private key that has it set.
      Actual behaviour
      $ pkcs15-tool --list-keys 
. . . . .
Private RSA Key [SIGN key]
    Object Flags   : [0x1], private
    Usage          : [0x20E], decrypt, sign, signRecover, nonRepudiation
    Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
    ModLength      : 2048
    Key ref        : 156 (0x9C)
    Native         : yes
    Auth ID        : 01
    ID             : 02
. . . . .

      Steps to reproduce
      
        Insert a PIV token.
        Perform pkcs15-tool --list-keys
        
        Observe that nowhere in the output this attribute/flag is
          listed for the keys that you know have it set.
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/OpenSC","title":"OpenSC/OpenSC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/OpenSC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Flag CKA_ALWAYS_AUTHENTICATE is not displayed (#851)"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/OpenSC/issues/851"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> `CKA_ALWAYS_AUTHENTICATE` is a PKCS#11 attribute, not PKCS#15

My bad, thank you!

>  pkcs11-tool shows:        
>        Access:     always authenticate

I must be dense today, but I don't understand. How do you get `pkcs11-tool` to show that?

```
$ pkcs11-tool -O
. . . . .
Public Key Object; RSA 2048 bits
  label:      SIGN pubkey
  ID:         02
  Usage:      encrypt, verify
Certificate Object, type = X.509 cert
  label:      Certificate for Digital Signature
  ID:         02
. . . . .
Data object 3540024480
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
. . . . .
```

What's the magic?

**Comment by dengert** [comment]
Without the -l, pkcs11 does not show anything about private keys protected by the pin. 

pkcs11-tool -O -l 
...
Private Key Object; RSA 
 label:      SIGN key
  ID:         02
  Usage:      decrypt, sign, non-repudiation
  Access:     always authenticate
...

    pkcs15-tool could show "user_consent", but not sure why it does
    not.  
    
    On 8/15/2016 9:58 AM, Mouse wrote:
    
    
      
        CKA_ALWAYS_AUTHENTICATE is a PKCS#11 attribute,
          not PKCS#15
      
      My bad, thank you!
      
        pkcs11-tool shows:
          
          Access: always authenticate
      
      I must be dense today, but I don't understand. How do you get pkcs11-tool
        to show that?
      $ pkcs11-tool -O
. . . . .
Public Key Object; RSA 2048 bits
  label:      SIGN pubkey
  ID:         02
  Usage:      encrypt, verify
Certificate Object, type = X.509 cert
  label:      Certificate for Digital Signature
  ID:         02
. . . . .
Data object 3540024480
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
. . . . .

      What's the magic?
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/OpenSC","title":"OpenSC/OpenSC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/OpenSC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mouse07410 in #851: \u003e `CKA_ALWAYS_AUTHENTICATE` is a PKCS#11 attribute, not PKCS#15\r\n\r\nMy bad, thank you!\r\n\r\n\u003e  pkcs11-tool shows:        \r\n\u003e        Access:     always authenticate\r\n\r\nI must be dense today, but I don't understand. How do you get `pkcs11-tool` to show that?\r\n\r\n```\r\n$ pkcs11-tool -O\r\n. . . . .\r\nPublic Key Object; RSA 2048 bits\r\n  label:      SIGN pubkey\r\n  ID:         02\r\n  Usage:      encrypt, verify\r\nCertificate Object, type = X.509 cert\r\n  label:      Certificate for Digital Signature\r\n  ID:         02\r\n. . . . .\r\nData object 3540024480\r\n  label:          'X.509 Certificate for Digital Signature'\r\n  application:    'X.509 Certificate for Digital Signature'\r\n  app_id:         2.16.840.1.101.3.7.2.1.0\r\n  flags:          \u003cempty\u003e\r\n. . . . .\r\n```\r\n\r\nWhat's the magic?"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/OpenSC/issues/851#issuecomment-239824289"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
Thank you, you were right (as usually :).

```
$ pkcs11-tool -O -l
Using slot 2 with a present token (0x8)
Logging in to "PIV Card Holder pin: PIV_II".
Please enter User PIN: 
. . . . .
Private Key Object; RSA 
  label:      SIGN key
  ID:         02
  Usage:      decrypt, sign, non-repudiation
  Access:     always authenticate
. . . . .
```
