### ISSUE TITLE
Segmentation error with pkcs15-init/tool and Feitian PKI card

### ISSUE THREAD

**Issue by iay** [OpenSC/OpenSC#854]
### Expected behaviour

Card initialised, or otherwise changed.

### Actual behaviour

Segmentation fault.

### Steps to reproduce

```
$ pkcs15-init -E
Using reader with a card: SCM Microsystems Inc. SCR 335
Segmentation fault: 11
```

### Additional Information

This is with OpenSC 0.16 on a Mac.

You also get Segmentation fault for most other operations on a fresh card, e.g., `pkcs15-tool --dump`. If you initialise a card on another system (CentOS 7, using OpenSC 0.14) then things like `--dump` work, and `pkcs15-tool -E` works *once*, with subsequent invocations causing the error as above.

I did some basic debugging using lldb. In the case I looked into, the issue seems to be [here](https://github.com/OpenSC/OpenSC/blob/bd84e18f456f9a4ce3898e0f645172d29c231eb9/src/libopensc/card-entersafe.c#L495-L497) in `card-entersafe.c` lines 495--497:

```c
	r = iso_ops->select_file(card,&path,&file);
	if(r) sc_file_free(file);
	SC_TEST_RET(card->ctx, SC_LOG_DEBUG_NORMAL, r, "APDU transmit failed");
```

Here, `select_file` is being implemented by `iso7816_select_file`, which is failing -1209 "Conditions of use not satisfied" according to debug logs. I speculate that in this case it is not writing anything to the `file` parameter, which is then still null. `sc_file_free` does not check its arguments (except in an `assert`) and the segmentation fault is coming from [this line in sc.c](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/sc.c#L546):

```c
	file->magic = 0;
```

It has been around a decade since I spent any time with these sources so it may take me a while to confirm any of the above in any more detail, or provide a PR.

**Comment by dengert** [comment]
Line: 496  if(r) sc_file_free(file);  was added by:
    
    commit e2c21d7c25f07af9d249bfe9018b9ce2a7d4a8e0:
    
    Author: Feitian Technologies <hongbin@ftsafe.com>
    Date:   Mon Nov 30 23:24:05 2015 +0800
    
        Add new Feitian PKI Card ATR into OpenSC
        
        Add new PKI Card ATR into OpenSC support, all of these ATR using
    same
        PKI Applet. and the ATR/JAVA CARD is provided by Feitian.
        
        More information, please check www.javacardos.com
        
        Fixes a memory leak in `entersafe_select_fid`
        
        Closes https://github.com/OpenSC/OpenSC/pull/625
    
    Can you change the line to:
    if(r && file) sc_file_free(file);
    
    
    
    On 8/17/2016 3:58 AM, Ian Young wrote:
    
    
      Expected behaviour
      Card initialised, or otherwise changed.
      Actual behaviour
      Segmentation fault.
      Steps to reproduce
      $ pkcs15-init -E
Using reader with a card: SCM Microsystems Inc. SCR 335
Segmentation fault: 11

      Additional Information
      This is with OpenSC 0.16 on a Mac.
      You also get Segmentation fault for most other operations on a
        fresh card, e.g., pkcs15-tool --dump. If you
        initialise a card on another system (CentOS 7, using OpenSC
        0.14) then things like --dump work, and pkcs15-tool
          -E works once, with subsequent invocations
        causing the error as above.
      I did some basic debugging using lldb. In the case I looked
        into, the issue seems to be here
        in card-entersafe.c lines 495--497:
      
            r = iso_ops->select_file(card,&path,&file);
    if(r) sc_file_free(file);
    SC_TEST_RET(card->ctx, SC_LOG_DEBUG_NORMAL, r, "APDU transmit failed");
      
      Here, select_file is being implemented by iso7816_select_file,
        which is failing -1209 "Conditions of use not satisfied"
        according to debug logs. I speculate that in this case it is not
        writing anything to the file parameter, which is
        then still null. sc_file_free does not check its
        arguments (except in an assert) and the
        segmentation fault is coming from this
          line in sc.c:
      
            file->magic = 0;
      
      It has been around a decade since I spent any time with these
        sources so it may take me a while to confirm any of the above in
        any more detail, or provide a PR.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/OpenSC","title":"OpenSC/OpenSC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/OpenSC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Segmentation error with pkcs15-init/tool and Feitian PKI card (#854)"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/OpenSC/issues/854"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by iay** [comment]
I have to put a dev environment together, which might take a couple of days (this is not critical path for me) but yes that would be the obvious quick fix. I'll let you know.

**Comment by iay** [comment]
Confirming that this is working for me, so I've opened a pull request with that change in it.
