### ISSUE TITLE
Certificates not displayed correctly

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#860]
### Expected behaviour

`pkcs11-tool -O -l` should display all the certificates installed on the token.

### Actual behaviour

Installed certificates are not shown in `X.509 Certificate for Key Management`

### Steps to reproduce

1. Insert a provisioned token.
2. Do `pkcs11-tool -O -l`
3. Observe the output.

### Logs

```
$ pkcs11-tool -O -l
Using slot 1 with a present token (0x4)
Logging in to "PIV Card Holder pin: PIV_II".
Please enter User PIN: 
Private Key Object; RSA 
  label:      PIV AUTH key
  ID:         01
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 2048 bits
  label:      PIV AUTH pubkey
  ID:         01
  Usage:      encrypt, verify, wrap
Certificate Object, type = X.509 cert
  label:      Certificate for PIV Authentication
  ID:         01
Private Key Object; RSA 
  label:      KEY MAN key
  ID:         03
  Usage:      decrypt, unwrap
Public Key Object; RSA 2048 bits
  label:      KEY MAN pubkey
  ID:         03
  Usage:      encrypt, wrap
Certificate Object, type = X.509 cert
  label:      Certificate for Key Management
  ID:         03
Data object 586175312
  label:          'Cardholder Fingerprints'
  application:    'Cardholder Fingerprints'
  app_id:         2.16.840.1.101.3.7.2.96.16
  flags:           private
Data object 586175408
  label:          'Printed Information'
  application:    'Printed Information'
  app_id:         2.16.840.1.101.3.7.2.48.1
  flags:           private
Data object 586176352
  label:          'Cardholder Facial Image'
  application:    'Cardholder Facial Image'
  app_id:         2.16.840.1.101.3.7.2.96.48
  flags:           private
Data object 586174080
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 586173456
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 586173552
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 586175216
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 586176448
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 586176544
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 586176640
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 586176736
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>
Data object 586176832
  label:          'Discovery Object'
  application:    'Discovery Object'
  app_id:         2.16.840.1.101.3.7.2.96.80
  flags:          <empty>
$
```

**Comment by dengert** [comment]
Its there:
    
    Certificate Object, type = X.509 cert
      label:      Certificate for Key Management
      ID:         03
    
    
    On 8/22/2016 6:05 PM, Mouse wrote:
    
    
      Expected behaviour
      pkcs11-tool -O -l should display all the
        certificates installed on the token.
      Actual behaviour
      Installed certificates are not shown in X.509
          Certificate for Key Management
      Steps to reproduce
      
        Insert a provisioned token.
        Do pkcs11-tool -O -l
        
        Observe the output.
      
      Logs
      $ pkcs11-tool -O -l
Using slot 1 with a present token (0x4)
Logging in to "PIV Card Holder pin: PIV_II".
Please enter User PIN: 
Private Key Object; RSA 
  label:      PIV AUTH key
  ID:         01
  Usage:      decrypt, sign, unwrap
Public Key Object; RSA 2048 bits
  label:      PIV AUTH pubkey
  ID:         01
  Usage:      encrypt, verify, wrap
Certificate Object, type = X.509 cert
  label:      Certificate for PIV Authentication
  ID:         01
Private Key Object; RSA 
  label:      KEY MAN key
  ID:         03
  Usage:      decrypt, unwrap
Public Key Object; RSA 2048 bits
  label:      KEY MAN pubkey
  ID:         03
  Usage:      encrypt, wrap
Certificate Object, type = X.509 cert
  label:      Certificate for Key Management
  ID:         03
Data object 586175312
  label:          'Cardholder Fingerprints'
  application:    'Cardholder Fingerprints'
  app_id:         2.16.840.1.101.3.7.2.96.16
  flags:           private
Data object 586175408
  label:          'Printed Information'
  application:    'Printed Information'
  app_id:         2.16.840.1.101.3.7.2.48.1
  flags:           private
Data object 586176352
  label:          'Cardholder Facial Image'
  application:    'Cardholder Facial Image'
  app_id:         2.16.840.1.101.3.7.2.96.48
  flags:           private
Data object 586174080
  label:          'Card Capability Container'
  application:    'Card Capability Container'
  app_id:         2.16.840.1.101.3.7.1.219.0
  flags:          <empty>
Data object 586173456
  label:          'Card Holder Unique Identifier'
  application:    'Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.0
  flags:          <empty>
Data object 586173552
  label:          'Unsigned Card Holder Unique Identifier'
  application:    'Unsigned Card Holder Unique Identifier'
  app_id:         2.16.840.1.101.3.7.2.48.2
  flags:          <empty>
Data object 586175216
  label:          'X.509 Certificate for PIV Authentication'
  application:    'X.509 Certificate for PIV Authentication'
  app_id:         2.16.840.1.101.3.7.2.1.1
  flags:          <empty>
Data object 586176448
  label:          'X.509 Certificate for Digital Signature'
  application:    'X.509 Certificate for Digital Signature'
  app_id:         2.16.840.1.101.3.7.2.1.0
  flags:          <empty>
Data object 586176544
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
Data object 586176640
  label:          'X.509 Certificate for Card Authentication'
  application:    'X.509 Certificate for Card Authentication'
  app_id:         2.16.840.1.101.3.7.2.5.0
  flags:          <empty>
Data object 586176736
  label:          'Security Object'
  application:    'Security Object'
  app_id:         2.16.840.1.101.3.7.2.144.0
  flags:          <empty>
Data object 586176832
  label:          'Discovery Object'
  application:    'Discovery Object'
  app_id:         2.16.840.1.101.3.7.2.96.80
  flags:          <empty>
$

      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/OpenSC","title":"OpenSC/OpenSC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/OpenSC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Certificates not displayed correctly (#860)"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/OpenSC/issues/860"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment]
> Its there:
> ```
    Certificate Object, type = X.509 cert
      label:      Certificate for Key Management
      ID:         03
```

Yes I know - I'm asking about this:
```
. . . . .
Data object 586176544
  label:          'X.509 Certificate for Key Management'
  application:    'X.509 Certificate for Key Management'
  app_id:         2.16.840.1.101.3.7.2.1.2
  flags:          <empty>
. . . . .
```

Are there **two** data objects (references) for the same object? With one appearing set correctly, and the other one showing empty? What's the purpose of that second one, how does one set it, and does it matter if it is not set???

**Comment by dengert** [comment]
The PIV stores"End-Point Data Model Elements" (NIST 7800-73-3 Part 1 Section 3). Within OpenSC they are referred to as objects. These are read by the GET-DATA APDU.  For Elements containing certificates, the card-piv.c will extract the certificate (and unzip it if its gziped) and extract the SPKI i.e. pubkey.  The SPKI is also use to determine the type of privkey and its size. These and the presented to the caller as a PKCS#11  certificate , public key, private key and each of the ""End-Point Data Model Elements" are also presented as a PKCS#11 data object. 

So in effect a single "End-Point Data Model Element" (if its a certificate) is presents 4 times. 

When you say "showing empty" are you referring to the "flags: \<empty>"? If so that means the flags are zero.

If you are referring to pkcs11-tool listing objects that when you go to read them they return not found? If so there was a trade off made in card-piv.c to list potential objects on the card, rather they trying to read all the objects up front. But if you try and read the specific object, it may be empty. 

To see the object containing the  "X.509 Certificate for Key Management", you could use:

pkcs11-tool -r -y data --application-id 2.16.840.1.101.3.7.2.1.2 -o /tmp/cert.03.object

od -t x1 < /tmp/cert.03.object "X.509 Certificate for Key Management"

**Comment by mouse07410** [comment]
> So in effect a single "End-Point Data Model Element" (if its a certificate) is presents 4 times.

I see. I did not realize that. Thanks!

> When you say "showing empty" are you referring to the "flags: <empty>"? If so that means the flags are zero.

Yes I did - and thank you for explaining.

> To see the object containing the "X.509 Certificate for Key Management", you could use:
> ```
pkcs11-tool -r -y data --application-id 2.16.840.1.101.3.7.2.1.2 -o /tmp/cert.03.object
od -t x1 < /tmp/cert.03.object "X.509 Certificate for Key Management"
```

Yes, thank you - it worked.
