### ISSUE TITLE
Error parsing EF.TokenInfo on SC-HSM

### ISSUE THREAD

**Issue by llogar** [OpenSC/OpenSC#862]
Commit c5a95d4a5ae93e5960ee19988d86246aa688f453 broke parsing EF.TokenInfo as the `sc_pkcs15_parse_tokeninfo()` function (called from `sc_pkcs15emu_sc_hsm_read_tokeninfo()`) is called with invalid `blen` parameter (it should be `len` instead of `r`)

**Comment by frankmorgner** [comment]
I thinkt the information in EF.TokenInfo is only informational. My token is fully functional...

Could you please verify https://github.com/OpenSC/OpenSC/pull/865?

**Comment by llogar** [comment]
It may be informational, however since our application is using two cards at the same time, it cannot select the right one based on the card/token label as both cards are labeled (due to this bug) "Smartcard HSM" instead of their true labels (which are stored in EF.TokenInfo) as set at initialization time.

Anyway thanks for the fix.
