### ISSUE TITLE
OpenSC-0.16.0-win64_vs12-Release.msi fails to install "smart card" driver on windows 7

### ISSUE THREAD

**Issue by ruifortes** [OpenSC/OpenSC#870]
OpenSC-0.16.0-win64_vs12-Release.msi fails to install "smart card" driver on windows 7x64.
The "smart card reader" drivers installs fine.
Can someone confirm this? Is it just windows 7? Just my windows 7?

opensc-explorer, pkcs15-tool and pkcs11-tool are working

**Comment by frankmorgner** [comment]
could you try to debug the installation?
```
msiexec /i OpenSC-0.16.0-win64_vs12.msi /l*v MyLogFile.txt
```

**Comment by frankmorgner** [comment]
You may also need to [enable Windows Installer logging via the registry](https://support.microsoft.com/de-de/kb/223300)

**Comment by frankmorgner** [comment]
works for me, closing this without more input
