### ISSUE TITLE
unable to sign using ecdsa-with-SHA256

### ISSUE THREAD

**Issue by c3ph3us** [OpenSC/OpenSC#880]
in short:

    DEBUG:pkcs11_lib.c:1364: opening a new PKCS #11 session for slot 1
    Witaj PIV_II (PIV Card Holder pin)!
    Karta procesorowa - PIN: 
    DEBUG:pkcs11_lib.c:1383: login as user CKU_USER
    DEBUG:pkcs11_lib.c:1577: Saving Certificate #1:
    DEBUG:pkcs11_lib.c:1579: - type: 00
    DEBUG:pkcs11_lib.c:1580: - id:   01
    DEBUG:pkcs11_lib.c:1612: Found 1 certificates in token
    DEBUG:mapper_mgr.c:172: Retrieveing mapper module list
    DEBUG:mapper_mgr.c:73: Loading static module for mapper 'pwent'
    DEBUG:mapper_mgr.c:196: Inserting mapper [pwent] into list
    DEBUG:pam_pkcs11.c:551: verifying the certificate #1
    weryfikacja certyfikatu
    DEBUG:cert_vfy.c:338: Adding hashdir lookup to x509_store
    DEBUG:cert_vfy.c:350: Adding hash dir '/etc/pam_pkcs11/cacerts' to CACERT checks
    DEBUG:cert_vfy.c:450: certificate is valid
    DEBUG:cert_vfy.c:207: crl policy: 0
    DEBUG:cert_vfy.c:210: no revocation-check performed
    DEBUG:cert_vfy.c:464: certificate has not been revoked
    DEBUG:mapper_mgr.c:306: Mapper module pwent match() returns 1
    DEBUG:pam_pkcs11.c:637: certificate is valid and matches the user
    Sprawdzanie podpisu
    DEBUG:pkcs11_lib.c:1765: reading 128 random bytes from /dev/urandom
    DEBUG:pkcs11_lib.c:1784: random-value[128] = [3e:47:aa:...:cf]
    DEBUG:pkcs11_lib.c:1726: hash[35] = [...:51:d3:14:...:af]
    ERROR:pam_pkcs11.c:690: sign_value() failed: C_SignInit() failed: 0x00000063

full problem explained here:

http://security.stackexchange.com/questions/138020/ec-signing-using-pkcs11-failed-c-signinit-failed-0x00000063

https://github.com/OpenSC/pam_pkcs11/issues/23

$ pkcs11-tool -v -O

     Using slot 0 with a present token (0x0)
     Public Key Object; EC  EC_POINT 256 bits
       EC_POINT: 04410432f9bfbad578e5754cef1641b31893a57349c41b686fb13b03398404b1e38ada1f280c5e4d5a204fba3919465c03b32c23a5aedd2304ac26162534015b5fa3b4
       EC_PARAMS:  06082a8648ce3d030107
       label:      PIV AUTH pubkey
       ID:         01
      Usage:      verify
    Certificate Object, type = X.509 cert
      label:      Certificate for PIV Authentication
      ID:         01
    Data object 14705440
      label:          'Card Capability Container'
      application:    'Card Capability Container'
      app_id:         2.16.840.1.101.3.7.1.219.0
      flags:          <empty>

$ ssh-keygen -D  /usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so 

      C_GetAttributeValue failed: 18
      no keys
      cannot read public key from pkcs11

**Comment by mouse07410** [comment]
The following tests `OpenSC`, `libp11` (with `engine_pkcs11`), and OpenSSL `dgst`:
```
$ pkcs11-ecdsa-demo2
Generating random 250 bytes of Base64-encoded data...
openssl rand -base64 -out /tmp/derive.16555.text 250

Examining public key on the token to determine its curve...
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
read EC key
The key pair is on the curve prime256v1, will use hash sha256

Generating digital signature over /tmp/derive.16555.text...
openssl dgst -engine pkcs11 -keyform engine -sha256 -sign "pkcs11:object=SIGN%20key;object-type=private" -out /tmp/derive.16555.text.sig /tmp/derive.16555.text
engine "pkcs11" set.
PKCS#11 token PIN: 
PKCS#11 key PIN: 
Signature is stored in /tmp/derive.16555.text.sig

Verifying signature over /tmp/derive.16555.text...
openssl dgst -engine pkcs11 -keyform engine -sha256 -verify "pkcs11:object=SIGN%20pubkey;object-type=public" -signature /tmp/derive.16555.text.sig /tmp/derive.16555.text
engine "pkcs11" set.
Verified OK
```

**Comment by dengert** [comment]
See https://github.com/OpenSC/pam_pkcs11/issues/23 
The pam_pkcs11 does not support ECDSA or SHA256.

**Comment by dengert** [comment]
This is a pam_pkcs11 issue, not an OpenSC issue.

**Comment by c3ph3us** [comment]
@mouse07410  thanks i will check this lib
