### ISSUE TITLE
Unable to install sc-hsm-driver-x64 in Windows 10

### ISSUE THREAD

**Issue by uae1972** [OpenSC/OpenSC#883]
Hi,
I am not able to install sc-hsm-driver-x64, it gives me an error failed to install the driver.

using the certutil -scinfo I able to test the certification and it recognized by the windows, and XCA is fully function and able to recognize the token as well.

if try to use IE to login to https://devnet.cardcontact.de/ the IE recognize the certification and it gives me choice, to select the reader however it display that **Identiv uTrust 3522 embd SE Token, the smart card required drivers that are not present in this system.** 

I also install the Firefox and I try to add the security device, and I am trying to select the c:\WINDOWS\System32\opensc-pkcs11.dll but is not shown in the folder to add in Firefox wizard, even I check myself in the System32 and both opensc-minidriver.dll and opensc-pkcs11.dll are there in the folder.

The windows regedit indicate 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\SmartCard-HSM-CL and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\SmartCard-HSM  is correctly register.

Regards,
Amr

**Comment by frankmorgner** [comment]
What do you mean with "sc-hsm-driver-x64"? Are you referring to https://github.com/OpenSC/OpenSC/releases/download/0.16.0/OpenSC-0.16.0-win64_vs12-Release.msi?

**Comment by frankmorgner** [comment]
What is the specific error you are getting when installing the driver?

**Comment by frankmorgner** [comment]
please use `pkcs15-tool -n` or `pkcs15-tool -D` for low level debugging..

**Comment by uae1972** [comment]
I am referring to the sc-hsm-driver-x64.exe which comes with the sc-hsm-starterkit , and it doesn't give me details on the error, it just says failed to install the driver in the installation wizard.

I have use pkcs15-tool -D and here is the results:
Using reader with a card: Identiv uTrust 3522 embd SE Token 0
PKCS#15 Card [SmartCard-HSM]:
        Version        : 0
        Serial number  : DECC0300369
        Manufacturer ID: www.CardContact.de
        Flags          :

PIN [UserPIN]
        Object Flags   : [0x3], private, modifiable
        ID             : 01
        Flags          : [0x812], local, initialized, exchangeRefData
        Length         : min_len:6, max_len:15, stored_len:0
        Pad char       : 0x00
        Reference      : 129 (0x81)
        Type           : ascii-numeric
        Path           : e82b0601040181c31f0201::
        Tries left     : 3

PIN [SOPIN]
        Object Flags   : [0x1], private
        ID             : 02
        Flags          : [0x9A], local, unblock-disabled, initialized, soPin
        Length         : min_len:16, max_len:16, stored_len:0
        Pad char       : 0x00
        Reference      : 136 (0x88)
        Type           : bcd
        Path           : e82b0601040181c31f0201::
        Tries left     : 15

Private RSA Key [devnet.cardcontact.de]
        Object Flags   : [0x1], private
        Usage          : [0x2E], decrypt, sign, signRecover, unwrap
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        ModLength      : 2048
        Key ref        : 1 (0x1)
        Native         : yes
        Auth ID        : 01
        ID             : 01
        MD:guid        : 051f8c2e-8366-d535-f79d-12545a7f8396

X.509 Certificate [devnet.cardcontact.de]
        Object Flags   : [0x0]
        Authority      : no
        Path           : ce01
        ID             : 01
        Encoded serial : 02 08 6746534DEAAE8873
Data object 'HPKeyFile'
        applicationName: HPKeyFile
        Path:            e82b0601040181c31f0201::cd00
        Auth ID:         01

**Comment by uae1972** [comment]
if Internet explorer tries to access the Smart Card, Internet explorer gives an error  Identiv uTrust 3522 embd SE Token, the smart card required drivers that are not present in this system.

**Comment by frankmorgner** [comment]
This has not been released here. https://github.com/CardContact/OpenSC/ would be a better place to file this issue. @CardContact could you please look at this?

**Comment by uae1972** [comment]
OK, I will move the this topic to CardContact/sc-hsm-embedded, 
Thank you for the support.
