### ISSUE TITLE
SmartCard-HSM SO-PIN is always reported successful with 16 digits

### ISSUE THREAD

**Issue by gertvdijk** [OpenSC/OpenSC#889]
### Expected behaviour

I would expect the login test for login-type so (SO-PIN) to test if the provided value is correct for the card present.

    $ pkcs11-tool --login --test --login-type so
    Using slot 0 with a present token (0x0)
    Logging in to "SmartCard-HSM (UserPIN)".
    Please enter SO PIN:
    error: PKCS11 function C_Login failed: rv = CKR_PIN_INCORRECT (0xa0)

(return code 130)

### Actual behaviour

Always reported to be successful if length of provided PIN = 16 hexadecimal characters.

    $ pkcs11-tool --login --test --login-type so
    Using slot 0 with a present token (0x0)
    Logging in to "SmartCard-HSM (UserPIN)".
    Please enter SO PIN: 
    C_SeedRandom() and C_GenerateRandom():
      seeding (C_SeedRandom) not supported
      seems to be OK
    Digests:
      all 4 digest functions seem to work
      MD5: OK
      SHA-1: OK
      RIPEMD160: OK
    Signatures: not logged in, skipping signature tests
    Verify: not logged in, skipping verify tests
    Key unwrap: not a R/W session, skipping key unwrap tests
    Decryption: not logged in, skipping decryption tests
    No errors

(return code 0)

If provided with other length than 16 characters, it aborts with `CKR_PIN_LEN_RANGE`.

User-PIN check with `pkcs11-tool --login --test` does work and returns the `CKR_PIN_INCORRECT` error on entering a same-length-but-incorrect PIN.

### Steps to reproduce

1. `pkcs11-tool --login --test --login-type so`
2. Enter a different value than the actual SO-PIN for the card, but use the same length of 16.
3. Observe the absence of an error and the return code of 0 (indicating success).

### Environment

Ubuntu 16.04 with OpenSC 0.16.0 backported from Ubuntu 16.10 (https://launchpad.net/~gertvdijk/+archive/ubuntu/opensc-backports).

SmartCard-HSM version 1.2.

**Comment by frankmorgner** [comment]
The SO PIN is not to be used with PKCS#11. It is only used during initialization with `pkcs15-init`. In PKCS#11 use the USER PIN to log into the token instead.
