### ISSUE TITLE
OpenSC continuous-integration/travis-ci/pr for mingw  are timing out after 10 minutes 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#906]
### Expected behaviour

PR builds for the last few days are timing out with the message below. 

### Actual behaviour

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

**Comment by viktorTarasov** [comment]
Do we really need the cygwin cross compilation?

At least, looking onto the current situation, we can make the results of cross-compilation as the ones without impact onto the general build status.

**Comment by frankmorgner** [comment]
Yes, there are people that use this.

**Comment by dengert** [comment]
How do we fix the build/tracix-ci system so it does not time out?

**Comment by frankmorgner** [comment]
Don't know for sure. Maybe file a bug at Travis, maybe reproduce the Travis build locally?

**Comment by frankmorgner** [comment]
Maybe it's related to https://www.traviscistatus.com/incidents/nq0sf0srvx8s

**Comment by frankmorgner** [comment]
Found the problem.

By the way, cross compilation with mingw does **not** require cygwin.
