### ISSUE TITLE
Strange code in pkcs15-iasecc.c 

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#909]
./pkcs15-syn.c has the list of sc_pkcs15emu_*_init_ex routines. Your routine is listed last and as you suggested, it could be one of the other routines has done something to the sc_pkcs15_card_t. The each routine is passed the same sc_pkcs15_card_t See sc_pkcs15_bind_synthetic.

sc_pkcs15emu_iasecc_init_ex calls sc_pkcs15emu_iasecc_init which does:
rv = sc_pkcs15_bind_internal(p15card, aid);
p15card->ops.parse_df = _iasecc_parse_df;
LOG_FUNC_RETURN(ctx, rv);

This looks strange. This is the only pkcs15-<card>.c that calls sc_pkcs15_bind_internal which on failure calls sc_pkcs15_card_clear(p15card); sc_pkcs15_bind_internal is normally called from pkcs15.c But the above leaves p15card->ops.parse_df = _iasecc_parse_df; set even on a failure.

Also see #907 and #904

**Comment by dengert** [comment]
But this may not be a problem, because I can not find were  SC_PKCS15EMU_FLAGS_NO_CHECK
is ever set.

**Comment by viktorTarasov** [comment]
@dengert 
> This looks strange.

IAS/ECC is PKCS#15 card,  and so, its DFs are parsed with the standard OpenSC/pkcs15 procedures, like _sc_pkcs15_bind_internal()_. Beside the standard PKCS#15 DFs, some of IAS/ECC cards, also contain the non-PKCS#15 DF part, like, for example the minidriver specific data. To parse this specific part the card specific handler __iasecc_parse_df_ is used.

This specific part is the reason why IAS/ECC support is implemented as emulator, but this card-specific emulator uses the standard procedures to parse the on-card data in its standard PKCS#15 part.

> p15card->ops.parse_df  is set even on a failure

You have a reason, it's not nice, but without impact.
Failed once, the _sc_pkcs15_bind_internal()_ will fail for the second  time and card will not be binded.

**Comment by viktorTarasov** [comment]
@dengert 

after re-reading your initial comment:

- the __iasecc_parse_df_ handle is active only for the _SC_CARD_TYPE_IASECC_GEMALTO_ card type, it do nothing for the other types.
- seems that _SC_PKCS15EMU_FLAGS_NO_CHECK_ is not used and can be removed.

**Comment by dengert** [comment]
OK.
