### ISSUE TITLE
outdated wiki links for openct

### ISSUE THREAD

**Issue by mozkeeler** [OpenSC/OpenSC#920]
### Expected behaviour

What should happen?

The wiki page https://github.com/OpenSC/OpenSC/wiki/Overview has some links to the OpenCT project. I imagine https://github.com/OpenSC/openct/wiki should be used.

### Actual behaviour

What happens instead?

The links currently go to http://www.opensc-project.org/openct/ , which appears to be owned by a domain squatter.

### Steps to reproduce

1. Visit https://github.com/OpenSC/OpenSC/wiki/Overview
2. Click on any of the OpenCT links
3. Arrive at domain squatter page

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Paste Log output with less than 10 lines here```

**Comment by frankmorgner** [comment]
It's a Wiki please change the information yourself accordingly
