### ISSUE TITLE
No OpenSC folder after install?

### ISSUE THREAD

**Issue by atiredmachine** [OpenSC/OpenSC#922]
### Expected behaviour

What should happen?

Every documentation I've read states that installation should create a Library/OpenSC folder.

### Actual behaviour

What happens instead?

I can't find any OpenSC folder inside of Library.  I've tried installing versions 14, 15, and 16.
Apparently my mom's work requires her to have this software in order to do her work from her computer.
Also, there is no PKCS#11 module option in Citrix Receiver's advanced preferences.

### Steps to reproduce

1. Install
2. Look in Finder, nothing.
3. 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Paste Log output with less than 10 lines here```

**Comment by martinpaljak** [comment]
Be sure to look at /Library, no ~/Library

**Comment by atiredmachine** [comment]
! Thanks so much.  I'm not a Mac guy, so I didn't realize that was a thing.  I'd been tearing my hair out all night trying to get this to work.
