### ISSUE TITLE
ePass2003 change pin has error

### ISSUE THREAD

**Issue by KungFuArsong** [OpenSC/OpenSC#925]
### Expected behaviour

pkcs15-init --create-pkcs15 --profile pkcs15+onepin --label "My ePass2003" 

it shows Transmit failed.

and generate key shows same error.

it's working on linux but not working on windows

**Comment by frankmorgner** [comment]
transmit failed usually means that there is a problem with your reader or driver. If you want more information, please re-open this issue with a detailed log (use `-vvv`).
