### ISSUE TITLE
Compiling dnie driver with --disable-sm gives errors

### ISSUE THREAD

**Issue by rickyepoderi** [OpenSC/OpenSC#927]
[There is a comment](https://github.com/OpenSC/OpenSC/commit/e1b4bf4d2c2e7e1c4413207c1ce2db33126c5193#commitcomment-20296979) in one of my previous commits that explains that compiling dnie driver with _--disable-sm_ gives errors.

There are two files affected by this issue _cwa14890.c_ and _cwa-dnie.c_. Since the pull request #694 the dnie driver depends on _sm_ completely. You cannot even login with sm disabled.

We can add the the needed _ifdef ENABLE_SM_ or completely remove dnie driver if sm is not defined (like we are doing with openssl).

The latter is my preferred solution. What do you think?

**Comment by dengert** [comment]
I agree. If user is building without SM it is most likely to save space and only support cards the user is interested in. Maybe the configure.ac needs comments that --disable-sm also disables cards dependent on SM.
