### ISSUE TITLE
“OpenSC-0.16.0.pkg” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#933]
The DMG installers seem to be unsigned, and won't install without overriding the security warning:

"OpenSC-0.16.0.pkg” can’t be opened because it is from an unidentified developer.

Your security preferences allow installation of only apps from the Mac App Store and identified developers."

**Comment by martinpaljak** [comment]
For the time being, you can fetch a signed installer from https://github.com/martinpaljak/OpenSC/releases/tag/0.16.0

**Comment by frankmorgner** [comment]
As owner of the project, would you, @martinpaljak, be able to provide the signed installer for macOS to https://github.com/OpenSC/OpenSC/releases for the current and for future releases?

**Comment by frankmorgner** [comment]
Disable the gatekeeper functionality http://www.wikihow.com/Install-Software-from-Unsigned-Developers-on-a-Mac
