### ISSUE TITLE
pkcs15-init --create-pkcs15 --no-so-pin -> segfault (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#934]
### Expected behaviour

What should happen?

Following command runs successfully, or reports a sensible error message:

pkcs15-init --create-pkcs15 --no-so-pin

### Actual behaviour

What happens instead?

Little-Net:OpenSC minfrin$ lldb -- pkcs15-init --create-pkcs15 --no-so-pin
(lldb) target create "pkcs15-init"
Current executable set to 'pkcs15-init' (x86_64).
(lldb) settings set -- target.run-args  "--create-pkcs15" "--no-so-pin"
(lldb) run
Process 62920 launched: '/usr/local/bin/pkcs15-init' (x86_64)
Using reader with a card: ACS ACR 38U-CCID
Process 62920 stopped
* thread #1: tid = 0x2393a, 0x0000000100001e34 pkcs15-init`do_init_app + 980, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100001e34 pkcs15-init`do_init_app + 980
pkcs15-init`do_init_app:
->  0x100001e34 <+980>: movq   (%rax), %rdi
    0x100001e37 <+983>: callq  0x100128a6e               ; symbol stub for: sc_lock
    0x100001e3c <+988>: movl   %eax, -0x30c(%rbp)
    0x100001e42 <+994>: cmpl   $0x0, -0x30c(%rbp)

### Steps to reproduce

1. Build latest git master on MacOSX
2. Run "pkcs15-init --create-pkcs15 --no-so-pin"
3. Crash

### Logs

Little-Net:OpenSC minfrin$ opensc-tool -n
Using reader with a card: ACS ACR 38U-CCID
entersafe

**Comment by minfrin** [comment]
Dropping the --no-so-pin option also causes a crash:

Little-Net:OpenSC minfrin$ lldb -- pkcs15-init --create-pkcs15
(lldb) target create "pkcs15-init"
Current executable set to 'pkcs15-init' (x86_64).
(lldb) settings set -- target.run-args  "--create-pkcs15"
(lldb) run
Process 62947 launched: '/usr/local/bin/pkcs15-init' (x86_64)
Using reader with a card: ACS ACR 38U-CCID
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
Process 62947 stopped
* thread #1: tid = 0x24881, 0x0000000100001e34 pkcs15-init`do_init_app + 980, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100001e34 pkcs15-init`do_init_app + 980
pkcs15-init`do_init_app:
->  0x100001e34 <+980>: movq   (%rax), %rdi
    0x100001e37 <+983>: callq  0x100128a6e               ; symbol stub for: sc_lock
    0x100001e3c <+988>: movl   %eax, -0x30c(%rbp)
    0x100001e42 <+994>: cmpl   $0x0, -0x30c(%rbp)
``

**Comment by minfrin** [comment]
If I'm reading this correctly from the asm p12card is NULL:

        r = sc_lock(p15card->card);
        if (r < 0)
                return r;
        r = sc_pkcs15init_add_app(card, profile, &args);
        sc_unlock(p15card->card);
        return r;

From lldb:

    (lldb) print p15card
    (void *) $0 = 0x0000000000000000

**Comment by frankmorgner** [comment]
please check if https://github.com/OpenSC/OpenSC/pull/937 fixes the problem, thanks
