### ISSUE TITLE
Card driver should return SC_ERROR_INVALID_CARD on failures during initialisation

### ISSUE THREAD

**Issue by dengert** [OpenSC/OpenSC#946]
Issue: https://github.com/OpenSC/OpenSC/issues/943  The underlying issue was card/reader/pcsc was returning 90 00  when selecting AID which does not exist on the card. This appears to be some configuration issue and not a bug in the card driver. But the problem did uncover some other issues with how a failure in init is handled. 

sc_connect_card() in card.c will call ops->match_card(card). If true is returned ops->init(card) will be called.  If SC_ERROR_INVALID_CARD is returned, the loop will be continued. If not the loop will end. 

One problem is card drivers expect if ops->init(card) is called then ops->finish(card) will be called to clean up. This is not done in the loop. This can cause memory leaks.

I would like to propose: 

1. Evaluate the error codes in each driver to see if it should return SC_ERROR_INVALID_CARD indicating that the driver thinks that other drivers (if any) should be tried, or it is some other failure and no other drivers should be tried.  (Maybe this should be in the loop?)

2. In the loop, if ops->init(card) returns SC_ERROR_INVALID_CARD, ops->finish(card) is called. and card->dvr_data = NULL; 

3. Evaluate each driver to see if it depends on any fields in card that may have been changed by a previous card driver's init routine, and make sure these are reset if we continue the loop. We have done this already for many cases. 

We have 37 card drivers (and iso7816.c)
`ls card-*.c | wc`

27 drivers define a *_finish routine:
`grep "_finish(.*sc_card.*)" card-*.c`
(card-openpgp.c is counted twice in the above grep).

28 drivers set the ops.finish:
`grep "ops[.]finish.*=" card-*.c`

10 drivers do not set ops.finish and use what iso7816.c which is a NULL pointer. 
`grep -L "ops[.]finish.*=" card-*.c`

8 of these do not reference drv_data. The other 2 set drv_data = NULL. 
`grep -L "drv_data" card-*.c`

3 cards may return SC_ERROR_INVALID_CARD to try and continue the loop:
`grep SC_ERROR_INVALID_CARD card-*.c`

Only card-openpgp.c in pgp_init does a cleanup by calling its own pgp_finish(card)

Also see #945 that only addressed one driver.

**Comment by frankmorgner** [comment]
I think it would be easiest if you propose a patch. I'm pretty sure that `SC_ERROR_INVALID_CARD` is what should be returned.
