### ISSUE TITLE
Minidriver: Crash on card removal from PIN pad reader

### ISSUE THREAD

**Issue by edgecase14** [OpenSC/OpenSC#973]
OpenSC on windows 7 64bit should allow use of PIN pad - smartcard slot turns red/orange and number pad becomes a PIN pad for the smart card.

When PIN is typed and ENTER is pressed, machine gives BSOD in GKUPRO2D.SYS.  If enable_pinpad = false in opensc.conf, bluescreen is avoided in pkcs11 apps, however when using minidriver, the opensc.conf setting isn't honored, and the BSOD is unavoidable.

This is similar to an old issue:
https://github.com/OpenSC/OpenSC/issues/585

I have not found an update for the driver GKUPRO2D.SYS

I am willing to setup kernel debugger to capture the data that is triggering the crash.

**Comment by dengert** [comment]
Googleing for: gkupro2d sys dell Windows 10
Shows a lot of issues with this Dell driver. 

These Dell pages list the driver from 2015:
http://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=207T0

What version of the driver do you have?
As said in #585, OpenSC should not be able to causes a BSOD. This sounds like a Dell problem.

**Comment by edgecase14** [comment]
The timestamp on the driver .sys file is from 2009.  I don't have much hope for a fix, but the "enable_pinpad = false" workaround has been helpful.  I do plan on pursuing the issue with Dell.   How much work would it be to have a similar workaround for the OpenSC Minidriver?

**Comment by dengert** [comment]
It might be easy. Grep for sc_ctx_win32_get_config_value it is called in a few places. 
In ./libopensc/ctx.c 
172                 rc = RegOpenKeyExA( HKEY_LOCAL_MACHINE, name_key, 0, KEY_QUERY_VALUE, &hKey );
So it looks like it should find  it in HKEY_LOCAL_MACHINE\\Software\\OpenSC Project\\OpenSC
If it did not find  a user version in HKEY_CURRENT_USER\\Software\\OpenSC Project\\OpenSC

See what is in the registry for these two locations. If in both, you may need to change both because
the minidriver may be called  without a current user or environment. And  the HKEY_LOCAL_MACHINE version of opensc.conf must be readable by anyone.

**Comment by dengert** [comment]
If that does not solve the problem @frankmorgner would have more insight.

**Comment by frankmorgner** [comment]
You should be able to disable the PIN pad in the cardmod section (see https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L2257)

**Comment by edgecase14** [comment]
OK now I see why my opensc.conf didn't work, I was in the wrong section.  The minidriver uses opensc.conf, but in a different section.  I tried it however, and even after rebooting and giving opensc.conf Full Control to Everyone permissions, I still get prompted to use the pinpad.  I was just uncommenting enable_pinpad in the sample config file, right at the end: app "cardmod", reader_driver "cardmod"

**Comment by frankmorgner** [comment]
There is a race condition in the minidriver that leads to the crash, see https://github.com/frankmorgner/OpenSC/commit/d3682da56bb1d52ebb60ee707e9205a73b42af01 for a fix.

**Comment by edgecase14** [comment]
Would that make it impossible to use "enable_pinpad = false" in the minidriver?  I tried on another keyboard, Cherry G73-6744 "smartboard".  The pinpad doesn't work, so I tried to disable it.  It uses a different driver than the Dell, but I have the same issue disabling pinpad.  Is that caused by the race condition?  If so I will try compiling with the patch mentioned above.

**Comment by frankmorgner** [comment]
fixed with bfa7aef042600f9a4b76b7e420b8421f4166b82f
