### ISSUE TITLE
Smart card reader is not accessiable 

### ISSUE THREAD

**Issue by develtech1** [OpenSC/OpenSC#976]
### Expected behaviour
Multiple scripts or application can use the same smart card attached to linux device

What should happen?

### Actual behaviour

What happens instead?
strongswan showing error because smart card reader or smart card can not be accessed by the tool.

### Logs

    We are using strongswan to create VPN with digital certificates (stored on smartcard-HSM ). It works perfectly however when i run a cron script which checks connectivity of smart card reader with the machine, i am getting following strongswan error in syslog.

    Feb 13 10:54:05 localhost charon: 00[CFG] no PKCS#11 module found having a keyid 1
    Feb 13 10:54:05 localhost charon: 00[LIB] building CRED_PRIVATE_KEY - (0) failed, tried 4 builders

 

    My further investigation shows that "opensc-tool -a" command output is "No smart card readers found." & pcscd logs show following error;

    05102770 ccid_usb.c:638:WriteUSB() write failed (3/2): -7 Success
    05000129 ccid_usb.c:638:WriteUSB() write failed (3/2): -7 Success
    05000123 ccid_usb.c:638:WriteUSB() write failed (3/2): -7 Success
    00000026 ifdhandler.c:135:IFDHCreateChannelByName() failed
    00000085 readerfactory.c:965:RFInitializeReader() Open Port 0x200000 Failed (usb:08e6/3437:libusb-1.0:3:2:0)
    00000015 readerfactory.c:276:RFAddReader() Gemalto GemPC Twin init failed.

    Detailed pcscd logs are attached.

    xhci-hcd is used when smart card reader is plugged in, the output on console is as below;

    usb 3-1: USB disconnect, device number 2
    usb 3-1: new full-speed USB device number 3 using xhci-hcd
    usb 3-1: ep 0x81 - rounding interval to 128 microframes, ep desc says 192 microframes

    Our packages details are following;
        kernel 3.10.56
        strongswan 5.3
        libusb 1.0.8-1
        pcsc-lite 1.8.1-1
        ccid 1.4.5
        opensc 0.15.0-1
        libtool 2.4.2
        smart cards Cardomatic  

      Gemalto SC reader

**Comment by dengert** [comment]
It could be some process has requested exclusive access to reader and/or smart card at USB level or PCSC level. Restarting pcscd in debug mode  -d and maybe -a -f  might show something.

Reboot and as the first command  Then  opensc-tool -a

What other processes are running that might access the reader without using pcsc?

**Comment by develtech1** [comment]
Hi,
Thanks for reply. 
In the CentOS machine, i am trying to check the presence of smart card by using command "pkcs15-tool -D" in bash/perl script and included in crontab

after 3o sec i got following messages in the logs.
first it gave  "PKCS#15 binding failed:"

Using reader with a card: Gemalto GemPC Twin 00 00
PKCS#15 binding failed: Transmit failed

After another 30 sec the command output was "Failed to connect to card:"
Using reader with a card: Gemalto GemPC Twin 00 00
Failed to connect to card: Generic reader error

And in the end, i got message that Card is not present after running  "pkcs15-tool -D" command. 
IPSec VPN using digital certificate is also not working due this behavior of smart card or reader

**Comment by dengert** [comment]
It sounds like some other application has the reader or card locked. 

It might be on CentOS the usb device may have permissions set to only allow the user at the console to access the reader. You cron job may not have access to it especially if some other application or user is using it. 

"pkcs15-tool -D does a lot of stuff with the card.   If all you are trying to do is detect that A card is present in a reader, you may want to use opensc-tool -l  to list the readers, and if a card is present or not. 
It does very little else. It does not access the card at all. It may or may not respond if the card is locked by some other application. But is worth trying it. 
  


opensc-tool -a will try and determine what type of card is present and may require access to the card which might get blocked if some other application is using

**Comment by frankmorgner** [comment]
I agree, please attach a debug log of both, opensc and pcscd to figure out what happens exactly.

**Comment by develtech1** [comment]
Thanks sir for reply.
I will check opensc command instead of pkcs15 . I will share logs files as well

**Comment by develtech1** [comment]
Hi,
I am sorry for delay. 

I have tested the "opensc-tool -l" command and it worked without any problem, 

However, i have to run pkcs15-tool -D or -c  commands to fetch different parameters of certificates
( e.g X.509 Certificate [CN=device11]).

I have used  "pkcs15-tool -c" & "pkcs15-tool -D" commands in my bash script, first time it works perfectly however after some time it start showing "card is not present" . 
Detail level 9 OPENSC & PCSCD logs are attached, for your ease & quick review a few portions from logs are below;  

**/*A Part from OPENSC log, during this test i did not unplugged smart cards*/**

_0x77b5b210 10:28:40.440 [pkcs15-tool] reader-pcsc.c:376:refresh_attributes: card absent_

**/*A Part from PCSCD log*/**

_05000157 ccid_usb.c:638:WriteUSB() write failed (3/8): -7 Success_

**/*Another part from PCSCD log*/**

_00000012 ifdhandler.c:1292:IFDHTransmitToICC() usb:08e6/3437:libusb-1.0:3:8:0 (lun: 0)
00000008 openct/proto-t1.c:170:t1_transceive() T=1 state machine is DEAD. Reset the card first.
00000005 ifdwrapper.c:520:IFDTransmit() Card not transacted: 612
00000005 winscard.c:1564:SCardTransmit() Card not transacted: 0x80100016_

Both logs are attached.
[logs.tar.gz](https://github.com/OpenSC/OpenSC/files/820834/logs.tar.gz)

**Comment by dengert** [comment]
It is not clear what is going on. PCSC reporting 0x80100016 SCARD_E_NOT_TRANSACTED 
starting at 10:24:19.810 in the logs implies there is a problem with the card, reader or USB. 
We have seen things like this before, where some other process may reset or power down the card, the host powers down the USB port or the reader has problems. 

Things to do:

- Try newer versions of pcsclite and OpenSC (You are running 0.15.0. Try 0.16.0 or better still build from github master version error handling is better.) 
- Try a different reader. 
- Try a different computer.
- Ttry a different card. 
- Look at what other processes or drivers that might acces the reader or card. (may not be using OpenSC and thus not in debug log)
- Google for: OpenSC 80100016,    PCSC 80100016 and GemPC Twin 80100016

**Comment by develtech1** [comment]
Hi,
Sir, after changing reader and smart card, i was getting same error.
However, after that i have changed the libusb and ccid drivers version. and now error is fixed. It is perfectly working for pkcs15-tool -D or -c command.
