### ISSUE TITLE
opensc-pkcs11.dll cannot be loaded into Firefox on Windows

### ISSUE THREAD

**Issue by minfrin** [OpenSC/OpenSC#986]
### Expected behaviour

After installing v0.16.0 of opensc via the Windows MSI on Windows 10, following the instructions below, it should be possible to add opensc-pkcs11 as a new module.

https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

### Actual behaviour

The opensc-pkcs11.dll file is not visible in the "load module" dialog, despite this file being visible in Windows Explorer without a problem.

As a result, it is impossible to add opensc as a PKCS11 driver on Windows.

### Steps to reproduce

See screenshots.

Matching Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1302175

**Comment by frankmorgner** [comment]
Install the 32 bit binaries and load the pkcs11 DLL from syswow64.

Am 6. März 2017 00:49:42 MEZ schrieb minfrin <notifications@github.com>:
>### Expected behaviour
>
>After installing v0.16.0 of opensc via the Windows MSI on Windows 10,
>following the instructions below, it should be possible to add
>opensc-pkcs11 as a new module.
>
>https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step
>
>### Actual behaviour
>
>The opensc-pkcs11.dll file is not visible in the "load module" dialog,
>despite this file being visible in Windows Explorer without a problem.
>
>As a result, it is impossible to add opensc as a PKCS11 driver on
>Windows.
>
>### Steps to reproduce
>
>See screenshots.
>
>Matching Mozilla bug:
>https://bugzilla.mozilla.org/show_bug.cgi?id=1302175
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenSC/OpenSC/issues/986

-- 
Frank Morgner
