### ISSUE TITLE
MacOS: current OpenSC fails to unlock the token

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#987]
### Expected behaviour

Token is unlocked when Keychain Access is requested to do so.

### Actual behaviour

The token does *not* get unlocked, the user is not prompted for his PIN, the OpenSC log indicates that all the code has done was to verify that the token status was indeed "locked".

### Steps to reproduce

1. Token is inserted and unlocked. 
2. Applications work with it. 
3. User locks the token via Keychain Access.
4. User unlocks the token via Keychain Access.
5. *Expected*: token gets unlocked. *Actual*: token stays locked, user is *not* prompted for a PIN.

### Logs

"Good" log -when no application is involved, token gets locked and unlocked OK. 
[opensc-ok-20170305.txt](https://github.com/OpenSC/OpenSC/files/819997/opensc-ok-20170305.txt)
Steps included in this log:
1. Insert the token. 
2. Unlock it via Keychain Access.
3. Lock it via Keychain Access.
4. Unlock it via Keychain Access.

"Bad" log - when OpenSSL performed signing and signature verification, the token cannot be unlocked. 
[opensc-bad-20170305.txt](https://github.com/OpenSC/OpenSC/files/819999/opensc-bad-20170305.txt)
Steps included in this log:
1. Insert the token.
2. Unlock it via Keychain Access ("tokend" entries in the log).
3. Create a digital signature using OpenSSL.
4. Verify that signature using OpenSSL.
5. Lock the token via Keychain Access.
6. Attempt to unlock the token via Keychain Access.
7. Again try to unlock the token via Keychain Access.

Note, that this worked a few months ago.

**Comment by frankmorgner** [comment]
In the bad log you have opensc-pkcs11 interfering with tokend. That, most likely, causes the the problem. Other than that I can't see anything unusual.

**Comment by mouse07410** [comment]
@frankmorgner what input would help you diagnose and fix this problem? What kind of test would you like me to run? I'd be happy to do that.

**Comment by frankmorgner** [comment]
You could re-run your two tests without having a PKCS#11 application accessing the card. If you don't see a problem, then try both tests with your PKCS#11 application running in parallel.
